import type { ConversationActionDecision } from "../action/types";
import type { MaterialQuestion } from "../domain/decisionState";

export interface AuthorizedExplanationFact { readonly id: string; readonly kind: "CATALOG" | "PUBLIC_PRICE" | "APPROXIMATE_BUDGET" | "TECHNICAL_GUIDANCE" | "CONFLICT" | "PERSONA" | "SOCIAL_CONTEXT" | "LIMITATION"; readonly safeText: string; readonly authorizedNumericTokens?: readonly string[]; readonly personaActive?: boolean }
export interface AuthorizedDirectAnswer { readonly safeText: string; readonly factIds: readonly string[] }
export interface MentionableCandidate { readonly candidateId: string; readonly canonicalName: string }
export interface TonePolicy { readonly language: "tr-TR"; readonly warmth: "NEUTRAL" | "WARM"; readonly emoji: "NONE" | "LIGHT"; readonly concise: boolean }
export interface RealizationSafetyPolicy { readonly forbiddenTerms: readonly string[]; readonly unsupportedClaimTerms: readonly string[]; readonly stereotypeTerms: readonly string[]; readonly approximateQualifiers: readonly string[]; readonly nonVerifiedPriceQualifiers: readonly string[] }
export interface RealizationInput { readonly actionDecision: ConversationActionDecision; readonly directAnswer?: AuthorizedDirectAnswer; readonly explanationFacts: readonly AuthorizedExplanationFact[]; readonly materialQuestion: MaterialQuestion | null; readonly mentionableCandidates: readonly MentionableCandidate[]; readonly revealableCandidates: readonly []; readonly tonePolicy: TonePolicy; readonly safetyPolicy: RealizationSafetyPolicy }
export interface NaturalRealizationRequest { readonly contractVersion: "1.0.0"; readonly attempt: 0 | 1; readonly action: ConversationActionDecision["nextAction"]; readonly directAnswer?: AuthorizedDirectAnswer; readonly explanationFacts: readonly AuthorizedExplanationFact[]; readonly materialQuestion: MaterialQuestion | null; readonly mentionableCandidates: readonly MentionableCandidate[]; readonly revealableCandidates: readonly []; readonly tonePolicy: TonePolicy; readonly rules: readonly string[]; readonly previousValidationCodes?: readonly string[] }
export interface NaturalRealizationModel { realize(input: NaturalRealizationRequest): Promise<unknown> }
export interface NaturalRealizationResult { readonly message: string; readonly usedExplanationFactIds: readonly string[]; readonly mentionedCandidateIds: readonly string[]; readonly renderedQuestionId?: string }
export type RealizationValidationCode = "EMPTY_MESSAGE" | "ACTION_MISMATCH" | "GENERIC_COMPLETION_WITHOUT_EFFECT" | "DIRECT_ANSWER_NOT_FIRST" | "QUESTION_NOT_AUTHORIZED" | "QUESTION_OPTIONS_CHANGED" | "QUESTION_OPTIONS_REPEATED" | "FACT_NOT_AUTHORIZED" | "CANDIDATE_NOT_AUTHORIZED" | "REVEAL_NOT_ALLOWED" | "UNAUTHORIZED_NUMBER" | "APPROXIMATE_QUALIFIER_MISSING" | "NON_VERIFIED_PRICE_QUALIFIER_MISSING" | "PERSONA_NOT_AUTHORIZED" | "FORBIDDEN_JARGON" | "FORBIDDEN_STEREOTYPE" | "UNSUPPORTED_CLAIM" | "ABUSE_MIRRORING" | "STATE_ACTION_MISMATCH";
export interface RealizationValidation { readonly ok: boolean; readonly codes: readonly RealizationValidationCode[] }
export interface RealizationExecution { readonly result: NaturalRealizationResult; readonly validation: RealizationValidation; readonly source: "MODEL" | "REPAIRED_MODEL" | "DETERMINISTIC_FALLBACK"; readonly attempts: 1 | 2; readonly firstAttemptCodes: readonly RealizationValidationCode[]; readonly repairAttemptCodes: readonly RealizationValidationCode[] }
