import type { StrollerProduct } from "./contracts";
export const STROLLER_CATALOG_RELEASE="BABY-STROLLER-TR-v0.2-approval-candidate" as const;
export const STROLLER_SOURCES=Object.freeze([
 {id:"CYBEX-TR-BALIOS",url:"https://www.cybex-online.com/en/row/strollers/",authority:"MANUFACTURER_REGIONAL_PRODUCT_INDEX",purpose:"TURKIYE_APPLICABILITY"},
 {id:"CYBEX-BALIOS-PRODUCT",url:"https://www.cybex-online.com/en/gb/p/st-go-balios-s-lux.html",authority:"MANUFACTURER_PRODUCT_PAGE",purpose:"TECHNICAL_FACTS"},
 {id:"CYBEX-BALIOS-MANUAL",url:"https://www.cybex-online.com/on/demandware.static/-/Sites-cybex-master-catalog/default/dwfbcd95b9/pdfs/manuals/ST_GO_Balios_S_Lux_EN/CY_171_8888_B0424_Balios_S_Lux_Illustration_Booklet_DIGITAL_EN.pdf",authority:"MANUFACTURER_MANUAL_WITH_TR",purpose:"SAFETY_AND_SUPPORT"},
 {id:"CHICCO-TR-GOODY-PLUS",url:"https://www.chicco.com.tr/%C3%BCr%C3%BCnler/arabada-%26-d%C4%B1%C5%9Far%C4%B1da/d%C4%B1%C5%9Far%C4%B1da/bebek-arabalar%C4%B1/goody-plus-bebek-arabas%C4%B1-8058664152834-04079877190000.html",authority:"MANUFACTURER_TURKIYE_EXACT_PRODUCT",purpose:"IDENTITY_APPLICABILITY_FACTS"},
 {id:"CHICCO-TR-MYSA",url:"https://www.chicco.com.tr/%C3%BCr%C3%BCnler/arabada-%26-d%C4%B1%C5%9Far%C4%B1da/d%C4%B1%C5%9Far%C4%B1da/bebek-arabalar%C4%B1/mysa-bebek-arabas%C4%B1-8058664181865-05087158450000.html",authority:"MANUFACTURER_TURKIYE_EXACT_PRODUCT",purpose:"IDENTITY_APPLICABILITY_FACTS"},
 {id:"CHICCO-TR-BELLAGIO",url:"https://www.chicco.com.tr/%C3%BCr%C3%BCnler/arabada-%26-d%C4%B1%C5%9Far%C4%B1da/d%C4%B1%C5%9Far%C4%B1da/bebek-arabalar%C4%B1/bellagio-bebek-arabasi-2.0-8058664191055-07087183330000.html",authority:"MANUFACTURER_TURKIYE_EXACT_PRODUCT",purpose:"IDENTITY_APPLICABILITY_FACTS"},
] as const);
const u={childWeightMaxKg:"UNKNOWN",newbornUse:"UNKNOWN",strollerWeightKg:"UNKNOWN",foldedMm:"UNKNOWN",oneHandFold:"UNKNOWN",selfStanding:"UNKNOWN",reversibleSeat:"UNKNOWN",lieFlatRecline:"UNKNOWN",suspension:"UNKNOWN",basketMaxKg:"UNKNOWN",cabinSizeClaim:"UNKNOWN",travelSystemCompatible:"UNKNOWN"} as const;
export const STROLLER_PRODUCTS:readonly StrollerProduct[]=Object.freeze([
 {exactProductId:"CHICCO_GOODY_PLUS_04079877190000_TR",manufacturer:"Chicco",model:"Goody Plus",configurationIdentity:"Chicco Goody Plus / 04079877190000 / Dusty Green / Türkiye",type:["COMPACT_TRAVEL","TRAVEL_SYSTEM_COMPATIBLE"],trApplicability:{status:"VERIFIED",evidenceIds:["CHICCO-TR-GOODY-PLUS"]},facts:{...u,childWeightMaxKg:22,newbornUse:"SEAT_LIE_FLAT",strollerWeightKg:6.9,foldedMm:[250,465,560],oneHandFold:true,selfStanding:true,lieFlatRecline:true,travelSystemCompatible:true},included:["konfor kiti","yağmurluk"],separatelySold:["Soft portbebe","uyumlu oto koltuğu; exact kombinasyon ayrıca doğrulanmalı"],evidenceIds:["CHICCO-TR-GOODY-PLUS"]},
 {exactProductId:"CHICCO_MYSA_05087158450000_TR",manufacturer:"Chicco",model:"Mysa",configurationIdentity:"Chicco Mysa / 05087158450000 / Black Satin / Türkiye",type:["STANDARD","TRAVEL_SYSTEM_COMPATIBLE"],trApplicability:{status:"VERIFIED",evidenceIds:["CHICCO-TR-MYSA"]},facts:{...u,childWeightMaxKg:22,newbornUse:"SEAT_LIE_FLAT",strollerWeightKg:9,foldedMm:[380,560,620],oneHandFold:true,lieFlatRecline:true,travelSystemCompatible:true},included:["adaptör","ön bar","konfor kiti","yağmurluk","iç küçültücü minder","sepet","tente"],separatelySold:["Flexi veya Gran Comfort portbebe","Kory veya First-Seat Recline oto koltuğu"],evidenceIds:["CHICCO-TR-MYSA"]},
 {exactProductId:"CHICCO_BELLAGIO_07087183330000_TR",manufacturer:"Chicco",model:"Bellagio 2.0",configurationIdentity:"Chicco Bellagio 2.0 / 07087183330000 / Fir Tree / Türkiye",type:["STANDARD","TRAVEL_SYSTEM_COMPATIBLE"],trApplicability:{status:"VERIFIED",evidenceIds:["CHICCO-TR-BELLAGIO"]},facts:{...u,childWeightMaxKg:22,newbornUse:"SEAT_LIE_FLAT",strollerWeightKg:9.9,foldedMm:[360,550,680],oneHandFold:true,selfStanding:true,suspension:"ALL_WHEEL",travelSystemCompatible:true},included:["adaptör","yağmurluk"],separatelySold:["Flexi veya Gran Comfort portbebe","Kory veya First-Seat Recline oto koltuğu"],evidenceIds:["CHICCO-TR-BELLAGIO"]},
 {exactProductId:"CYBEX_BALIOS_S_LUX_520001251_TR",manufacturer:"CYBEX",model:"Balios S Lux",configurationIdentity:"CYBEX Balios S Lux / 520001251 / Navy Blue, Silver Frame / Türkiye",type:["STANDARD","TRAVEL_SYSTEM_COMPATIBLE"],trApplicability:{status:"VERIFIED",evidenceIds:["CYBEX-TR-BALIOS","CYBEX-BALIOS-MANUAL"]},facts:{...u,childWeightMaxKg:22,newbornUse:"SEAT_LIE_FLAT",strollerWeightKg:11.7,foldedMm:[430,600,755],oneHandFold:true,selfStanding:true,lieFlatRecline:true,suspension:"ALL_WHEEL",basketMaxKg:5,travelSystemCompatible:true},included:["şasi ve tekerlekler","oturma ünitesi","alışveriş sepeti","ön bar","güneşlik","yağmurluk"],separatelySold:["Cot S","Cocoon S","CYBEX Gold bebek oto koltuğu","Balios S Line adaptörü"],evidenceIds:["CYBEX-BALIOS-PRODUCT","CYBEX-BALIOS-MANUAL"]},
]);
export const STROLLER_DISCOVERY_RECONCILIATION=Object.freeze({discovered:11,admitted:4,rejectedInsufficientTrApplicability:5,rejectedIdentityAmbiguous:2,duplicate:0,retiredUnsupported:0,silentDrops:0,terminalNotes:["Joie Pact: exact Türkiye renk/SKU applicability unproved; terminally rejected after one bounded check.","Joie Tourist: exact Türkiye renk/SKU applicability unproved; terminally rejected after one bounded check."]});
