import{STROLLER_CATALOG_RELEASE,STROLLER_PRODUCTS}from"./catalog";import{authorizeStrollerCard,selectStrollers,type StrollerPreferences}from"./decision";import{STROLLER_AUTHORITY_DIGEST}from"./domainPack";import{babyPayloadHash,type BabyStore}from"./persistence";import type{BabyOutcome,BabyState}from"./runtimeContracts";
const questions=[
 {key:"baby.stroller.carry",text:"Bebek arabasını sık sık elde ya da merdivende taşıyacak mısınız?",need:"CARRY_WEIGHT",yes:"LIGHT"},
 {key:"baby.stroller.folded",text:"Küçük bagaj veya dar saklama alanı için katlı hacmin küçük olması gerekli mi?",need:"FOLDED_SIZE",yes:"SMALL"},
 {key:"baby.stroller.surface",text:"Bozuk zemin için üreticinin açıkça belirttiği dört teker süspansiyon gerekli mi?",need:"SURFACE",yes:"ROUGH"},
 {key:"baby.stroller.travel",text:"Oto koltuğu ya da portbebe bağlanabilen travel sistem uyumu gerekli mi?",need:"TRAVEL_SYSTEM",yes:true},
]as const;
const labels=(ids:readonly string[])=>STROLLER_PRODUCTS.filter(p=>ids.includes(p.exactProductId)).map(p=>({id:p.exactProductId,label:`${p.manufacturer} ${p.model}`}));
function initialState(id:string,now=new Date()):BabyState{return{conversationId:id,schemaVersion:"baby-stroller-conversation/v1",revision:0,departmentId:"BABY_AND_CHILD",categoryId:"STROLLER",pinnedCatalogRelease:STROLLER_CATALOG_RELEASE,pinnedCatalogDigest:STROLLER_AUTHORITY_DIGEST,pinnedPolicyDigest:STROLLER_AUTHORITY_DIGEST,preferences:{},askedQuestionKeys:[],createdAt:now.toISOString(),updatedAt:now.toISOString()}}
function ask(s:BabyState):BabyOutcome{const q=questions.find(x=>!s.askedQuestionKeys.includes(x.key));if(!q)return decide(s);return{kind:"ASK",questionKey:q.key,message:q.text,choices:[{value:"YES",label:"Evet, gerekli"},{value:"NO",label:"Önemli değil"},{value:"UNKNOWN",label:"Henüz bilmiyorum"}],contextRevision:s.revision}}
function decide(s:BabyState):BabyOutcome{const candidates=selectStrollers(s.preferences);if(candidates.length===1){const p=candidates[0]!;return{kind:"DECISION_READY",message:`${p.manufacturer} ${p.model}, belirttiğiniz zorunlu koşulları doğrulanmış bilgilerle karşılayan tek aday.`,card:authorizeStrollerCard(p,s.preferences,s.revision),contextRevision:s.revision}}return{kind:"CLARIFY",questionKey:"NON_DOMINATED_SET",message:"Doğrulanmış bilgiler tek bir ürünü üstün kılmıyor; gizli puanlama veya katalog sırası kullanmadım. Bir modeli açıkça seçebilir ya da önemli bir farkı söyleyebilirsiniz.",candidates:labels(candidates.map(x=>x.exactProductId)),contextRevision:s.revision}}
export async function bootstrapBabyConversation(i:{store:BabyStore;conversationId:string;messageId:string;now?:Date}){const s=initialState(i.conversationId,i.now),q=questions[0],next:BabyState={...s,revision:1,askedQuestionKeys:[q.key],pendingQuestionKey:q.key,updatedAt:(i.now??new Date()).toISOString()},outcome:BabyOutcome={kind:"ASK",questionKey:q.key,message:"Bebek arabalarında temel farklar taşıma ağırlığı, katlı hacim, kullanım aşaması ve uyumlu parçaların ayrıca gerekebilmesidir. Yenidoğan uygunluğunu yalnız üreticinin açık koşuluyla değerlendiririm. "+q.text,choices:[{value:"YES",label:"Evet, sık taşıyacağım"},{value:"NO",label:"Önemli değil"},{value:"UNKNOWN",label:"Henüz bilmiyorum"}],contextRevision:1};next.lastOutcome=outcome;const c=await i.store.commit({expectedRevision:0,messageId:i.messageId,payloadHash:babyPayloadHash({action:"CREATE",categoryId:"STROLLER"}),nextState:next,publicOutcome:outcome});return c.status==="OK"?{status:"OK"as const,state:c.outcome.state,outcome:c.outcome.publicOutcome,replayed:c.outcome.state.revision!==1}:c}
export async function runBabyTurn(i:{store:BabyStore;conversationId:string;messageId:string;expectedRevision:number;message:string;now?:Date}){const found=await i.store.load(i.conversationId);if(!found)return{status:"STATE_UNAVAILABLE"as const};const hash=babyPayloadHash({action:"TURN",message:i.message,expectedRevision:i.expectedRevision}),old=found.messages[i.messageId];if(old)return old.payloadHash===hash?{status:"OK"as const,state:old.outcome.state,outcome:old.outcome.publicOutcome,replayed:true}:{status:"MESSAGE_PAYLOAD_CONFLICT"as const};if(found.state.revision!==i.expectedRevision)return{status:"REVISION_CONFLICT"as const};if(found.state.pinnedCatalogDigest!==STROLLER_AUTHORITY_DIGEST)return{status:"AUTHORITY_MISMATCH"as const};const n=i.message.trim().toLocaleLowerCase("tr-TR"),revision=found.state.revision+1;let preferences={...found.state.preferences},selected:string|undefined,outcome:BabyOutcome|undefined;
 if(/hava nasıl|film öner|telefon öner/iu.test(n))outcome={kind:"UNSUPPORTED",message:"Bebek arabası görüşmesindeyiz; bu ihtiyaca dönelim.",contextRevision:revision};
 else if(/nedir|ne demek|farkı|bilgim yok|neye dikkat/iu.test(n))outcome={kind:"RESPOND",message:"Kompakt modeller taşımaya ve saklamaya, standart modeller farklı şasi ve oturma düzenlerine odaklanabilir. Travel sistem, uyumlu parçanın bağlanabilmesidir; parçanın kutuda olduğu veya her oto koltuğunun uyduğu anlamına gelmez.",contextRevision:revision};
 else{selected=STROLLER_PRODUCTS.find(p=>n.includes(p.model.toLocaleLowerCase("tr-TR"))||n.includes(p.exactProductId.toLocaleLowerCase("tr-TR")))?.exactProductId;const q=questions.find(x=>x.key===found.state.pendingQuestionKey);if(q){if(/evet|gerekli|önemli(?! değil)/u.test(n))preferences={...preferences,[q.need]:q.yes};else if(/önemli değil|fark etmez|hayır|bilmiyorum|emin değilim/u.test(n))preferences={...preferences,[q.need]:"NONE"};}if(/hafif|merdiven|elde taşı/u.test(n))preferences.CARRY_WEIGHT="LIGHT";if(/küçük bagaj|dar.*(?:alan|bagaj)|katlı.*küçük/u.test(n))preferences.FOLDED_SIZE="SMALL";if(/bozuk zemin|dört teker süspansiyon/u.test(n))preferences.SURFACE="ROUGH";if(/travel sistem.*(?:gerekli|istiyorum)|oto koltuğu.*bağ/u.test(n))preferences.TRAVEL_SYSTEM=true;if(/(?:bütçe|en fazla).*(\d[\d.]*)\s*(?:tl|₺)/u.test(n))preferences.BUDGET=Number(n.match(/(\d[\d.]*)\s*(?:tl|₺)/u)?.[1]?.replaceAll(".",""));if(/temizle|sil|unut/u.test(n)&&q){const copy={...preferences};delete copy[q.need as keyof StrollerPreferences];preferences=copy;}}
 let next:BabyState={...found.state,revision,preferences,selectedProductId:selected,updatedAt:(i.now??new Date()).toISOString()};if(!outcome&&selected){const eligible=selectStrollers(preferences).find(p=>p.exactProductId===selected);outcome=eligible?{kind:"DECISION_READY",message:`${eligible.manufacturer} ${eligible.model}, açık seçiminiz ve doğrulanmış koşullar sonrasında yetkilendirildi.`,card:authorizeStrollerCard(eligible,preferences,revision),contextRevision:revision}:{kind:"CLARIFY",message:"Seçtiğiniz model belirttiğiniz zorunlu koşullarla eşleşmiyor.",contextRevision:revision};}if(!outcome){const q=questions.find(x=>!next.askedQuestionKeys.includes(x.key));if(q){next={...next,askedQuestionKeys:[...next.askedQuestionKeys,q.key],pendingQuestionKey:q.key};outcome=ask(next)}else outcome=decide(next)}next={...next,lastOutcome:outcome};const c=await i.store.commit({expectedRevision:i.expectedRevision,messageId:i.messageId,payloadHash:hash,nextState:next,publicOutcome:outcome});return c.status==="OK"?{status:"OK"as const,state:c.outcome.state,outcome:c.outcome.publicOutcome,replayed:false}:c}
export function recoverBabyConversation(found:Awaited<ReturnType<BabyStore["load"]>>){if(!found)return null;if(found.state.pinnedCatalogDigest!==STROLLER_AUTHORITY_DIGEST)return{kind:"FAILED_CLOSED"as const,message:"Bağlı bebek arabası yetkisi değişmiş; görüşme yeniden başlatılmalı."};return{kind:"CONVERSATION"as const,conversationId:found.state.conversationId,revision:found.state.revision,categoryId:"STROLLER"as const,outcome:found.state.lastOutcome}}
