import { describe, expect, it } from "vitest";
import { classifyCandidateDecisionAvailability } from "./availability";
import type { AffordabilityCandidatePool } from "../affordability/types";
import type { TechnicalCandidatePool } from "../filter/types";

function technical(initial = ["v1"]): TechnicalCandidatePool { return { catalogFingerprint: "catalog", decisionFingerprint: "decision", initialCandidateIds: initial, eligibleCandidateIds: initial, notEvaluableCandidateIds: [], eliminatedCandidateIds: [], candidates: [], filterTrace: [], deferredConstraintIds: [], diagnostics: [], counts: { initial: initial.length, eligible: initial.length, notEvaluable: 0, eliminated: 0 } }; }
function affordability(overrides: Partial<AffordabilityCandidatePool> = {}): AffordabilityCandidatePool { return { catalogFingerprint: "catalog", decisionFingerprint: "decision", evaluationTime: "2026-08-20T00:00:00.000Z", initialCandidateIds: ["v1"], verifiedPriceEligibleCandidateIds: [], internalEstimateWithinCandidateIds: [], estimatedOverBudgetConditionalCandidateIds: [], budgetNotAppliedEligibleCandidateIds: [], priceUnresolvedCandidateIds: [], technicallyNotEvaluableCandidateIds: [], verifiedOverBudgetCandidateIds: [], eliminatedCandidateIds: [], selectableCandidateIds: [], candidates: [], budgetIncreaseGuidance: [], trace: [], diagnostics: [], ...overrides }; }
describe("WP8 decision availability", () => {
  it("does not call estimated-over a hard conflict", () => { expect(classifyCandidateDecisionAvailability({ technicalPool: technical(), affordabilityPool: affordability({ estimatedOverBudgetConditionalCandidateIds: ["v1"], selectableCandidateIds: ["v1"] }) })).toBe("READY_WITH_APPROXIMATE_BUDGET"); });
  it("preserves price unresolved and technical unknown", () => { expect(classifyCandidateDecisionAvailability({ technicalPool: technical(), affordabilityPool: affordability({ priceUnresolvedCandidateIds: ["v1"] }) })).toBe("PRICE_UNRESOLVED"); expect(classifyCandidateDecisionAvailability({ technicalPool: technical(), affordabilityPool: affordability({ technicallyNotEvaluableCandidateIds: ["v1"] }) })).toBe("TECHNICALLY_NOT_EVALUABLE"); });
  it("distinguishes empty scope and verified hard conflict", () => { expect(classifyCandidateDecisionAvailability({ technicalPool: technical([]), affordabilityPool: affordability({ initialCandidateIds: [] }) })).toBe("EMPTY_SCOPE"); expect(classifyCandidateDecisionAvailability({ technicalPool: technical(), affordabilityPool: affordability({ verifiedOverBudgetCandidateIds: ["v1"] }) })).toBe("HARD_CONFLICT"); });
});
