import "server-only";

import { randomBytes } from "node:crypto";
import { z } from "zod";
import { EnvironmentProductionKeyProvider, StaticLocalTestKeyProvider, VersionedHmacKeyring, type KeyAuditSink, type SigningKeyProvider } from "@/lib/security/versionedKeyring.server";
import type { AppliancesConversationStore } from "../persistence/types";
import { recoverAppliancesConversation } from "../recovery.server";
import { resolvePersistedComparisonEntitlement } from "@/features/comparison-entitlements/service.server";
import type { ComparisonEntitlementRepository, EntitlementSubject } from "@/features/comparison-entitlements/contracts";

const VERSION = "appliances-stage2-handoff/v2" as const;
const PURPOSE = "ASAMA2_VIEW" as const;
const REPLAY_POLICY = "REVISION_BOUND_REUSABLE_UNTIL_EXPIRY" as const;
const DEFAULT_TTL_SECONDS = 15 * 60;
const claimsSchema = z.strictObject({ version:z.literal(VERSION), kid:z.string().min(1).max(80), purpose:z.literal(PURPOSE), departmentId:z.literal("APPLIANCES"), category:z.string().min(1).max(100), conversationId:z.string().uuid(), revision:z.number().int().positive(), catalogRelease:z.string().min(1).max(160), catalogDigest:z.string().min(1).max(200), semanticAuthorityVersion:z.string().min(1).max(160), semanticAuthorityDigest:z.string().min(1).max(200), exactProductId:z.string().min(1).max(300), configurationIdentity:z.string().min(1).max(500), decisionFingerprint:z.string().min(1).max(300), issuedAt:z.number().int().nonnegative(), expiresAt:z.number().int().positive(), nonce:z.string().min(16).max(100), replayPolicy:z.literal(REPLAY_POLICY) });
export type AppliancesStageTwoHandoffClaims = z.infer<typeof claimsSchema>;
export type AppliancesStageTwoHandoffVerification = { readonly status:"VALID"; readonly claims:AppliancesStageTwoHandoffClaims } | { readonly status:"INVALID"; readonly reason:"MALFORMED"|"UNKNOWN_KEY"|"REVOKED_KEY"|"BAD_SIGNATURE"|"EXPIRED"|"NOT_YET_VALID"|"INVALID_LIFETIME" };
export interface AppliancesStageTwoHandoffService { issue(input:Omit<AppliancesStageTwoHandoffClaims,"version"|"kid"|"purpose"|"departmentId"|"issuedAt"|"expiresAt"|"nonce"|"replayPolicy">):string; verify(token:string):AppliancesStageTwoHandoffVerification }
const encode=(value:string|Buffer)=>Buffer.from(value).toString("base64url");

export function createAppliancesStageTwoHandoffService(input:{readonly secret:string;readonly keyId?:string;readonly ttlSeconds?:number;readonly now?:()=>Date;readonly nonce?:()=>string}):AppliancesStageTwoHandoffService {
  if(Buffer.byteLength(input.secret,"utf8")<32)throw new TypeError("APPLIANCES_STAGE2_HANDOFF_SECRET_TOO_SHORT");
  return createAppliancesStageTwoHandoffServiceFromProvider({provider:new StaticLocalTestKeyProvider([{id:input.keyId?.trim()||"primary",secret:input.secret,state:"ACTIVE"}]),ttlSeconds:input.ttlSeconds,now:input.now,nonce:input.nonce});
}
export function createAppliancesStageTwoHandoffServiceFromProvider(input:{readonly provider:SigningKeyProvider;readonly ttlSeconds?:number;readonly now?:()=>Date;readonly nonce?:()=>string;readonly audit?:KeyAuditSink}):AppliancesStageTwoHandoffService {
  const ttlSeconds=input.ttlSeconds??DEFAULT_TTL_SECONDS,now=input.now??(()=>new Date()),keyring=new VersionedHmacKeyring(input.provider,input.audit);
  if(!Number.isInteger(ttlSeconds)||ttlSeconds<60||ttlSeconds>3600)throw new TypeError("APPLIANCES_STAGE2_HANDOFF_TTL_INVALID");
  const readiness=keyring.readiness();if(!readiness.ready)throw new TypeError(readiness.reason);const activeKeyId=readiness.activeKeyId;
  return { issue(values){const issuedAt=Math.floor(now().getTime()/1000),claims:AppliancesStageTwoHandoffClaims={version:VERSION,kid:activeKeyId,purpose:PURPOSE,departmentId:"APPLIANCES",...values,issuedAt,expiresAt:issuedAt+ttlSeconds,nonce:input.nonce?.()??randomBytes(18).toString("base64url"),replayPolicy:REPLAY_POLICY},body=encode(JSON.stringify(claims)),signed=keyring.sign(body,now());return `${body}.${signed.signature}`;}, verify(token){const pieces=token.split(".");if(pieces.length!==2||!pieces[0]||!pieces[1])return{status:"INVALID",reason:"MALFORMED"};let raw:unknown;try{raw=JSON.parse(Buffer.from(pieces[0],"base64url").toString("utf8"));}catch{return{status:"INVALID",reason:"MALFORMED"};}const parsed=claimsSchema.safeParse(raw);if(!parsed.success)return{status:"INVALID",reason:"MALFORMED"};const signature=keyring.verify(parsed.data.kid,pieces[0],pieces[1],now());if(signature!=="VALID")return{status:"INVALID",reason:signature};const current=Math.floor(now().getTime()/1000);if(parsed.data.expiresAt<=current)return{status:"INVALID",reason:"EXPIRED"};if(parsed.data.issuedAt>current+30)return{status:"INVALID",reason:"NOT_YET_VALID"};if(parsed.data.expiresAt-parsed.data.issuedAt!==ttlSeconds)return{status:"INVALID",reason:"INVALID_LIFETIME"};return{status:"VALID",claims:parsed.data};} };
}

export function loadAppliancesStageTwoHandoffService(environment:NodeJS.ProcessEnv=process.env):AppliancesStageTwoHandoffService|null {try{return createAppliancesStageTwoHandoffServiceFromProvider({provider:new EnvironmentProductionKeyProvider(environment.APPLIANCES_STAGE2_HANDOFF_KEYS),ttlSeconds:environment.APPLIANCES_STAGE2_HANDOFF_TTL_SECONDS?Number(environment.APPLIANCES_STAGE2_HANDOFF_TTL_SECONDS):undefined});}catch{return null;}}
type Recovered=NonNullable<Awaited<ReturnType<typeof recoverAppliancesConversation>>>;
function decision(value:Awaited<ReturnType<typeof recoverAppliancesConversation>>):value is Recovered&{outcome:{kind:"DECISION_READY";decisionFingerprint:string;card:{identity:{productId:string;configurationIdentity:string}}}} {return value?.outcome?.kind==="DECISION_READY"&&Boolean(value.outcome.card);}

export async function issueAppliancesStageTwoHandoff(input:{readonly store:AppliancesConversationStore;readonly service:AppliancesStageTwoHandoffService;readonly conversationId:string;readonly expectedRevision:number}) {const recovered=await recoverAppliancesConversation(input.store,input.conversationId);if(!decision(recovered)||recovered.revision!==input.expectedRevision)return{status:"NOT_AUTHORIZED" as const};return{status:"ISSUED" as const,handoff:input.service.issue({conversationId:recovered.conversationId,revision:recovered.revision,category:recovered.productType,catalogRelease:recovered.catalogBinding.releaseVersion,catalogDigest:recovered.catalogBinding.releaseDigest,semanticAuthorityVersion:recovered.catalogBinding.semanticAuthorityVersion,semanticAuthorityDigest:recovered.catalogBinding.semanticAuthorityDigest,exactProductId:recovered.outcome.card.identity.productId,configurationIdentity:recovered.outcome.card.identity.configurationIdentity,decisionFingerprint:recovered.outcome.decisionFingerprint})};}
export async function readAppliancesStageTwoHandoff(input:{readonly store:AppliancesConversationStore;readonly service:AppliancesStageTwoHandoffService;readonly handoff:string;readonly entitlementRepository?:ComparisonEntitlementRepository;readonly subject?:EntitlementSubject}) {const verified=input.service.verify(input.handoff);if(verified.status!=="VALID")return{status:"INVALID" as const,reason:verified.reason};const recovered=await recoverAppliancesConversation(input.store,verified.claims.conversationId);if(!decision(recovered))return{status:"INVALID" as const,reason:"UNAUTHORIZED" as const};const identity=recovered.outcome.card.identity,binding=recovered.catalogBinding;if(recovered.departmentId!=="APPLIANCES"||recovered.productType!==verified.claims.category||recovered.revision!==verified.claims.revision||recovered.outcome.decisionFingerprint!==verified.claims.decisionFingerprint||binding.releaseVersion!==verified.claims.catalogRelease||binding.releaseDigest!==verified.claims.catalogDigest||binding.semanticAuthorityVersion!==verified.claims.semanticAuthorityVersion||binding.semanticAuthorityDigest!==verified.claims.semanticAuthorityDigest||identity.productId!==verified.claims.exactProductId||identity.configurationIdentity!==verified.claims.configurationIdentity)return{status:"INVALID" as const,reason:"AUTHORITY_MISMATCH" as const};const comparisonEntitlement=await resolvePersistedComparisonEntitlement({repository:input.entitlementRepository??null,subject:input.subject??{type:"SESSION",id:recovered.conversationId},departmentId:"APPLIANCES",category:recovered.productType,conversationId:recovered.conversationId,decisionRevision:recovered.revision,decisionFingerprint:recovered.outcome.decisionFingerprint,exactEvidenceIds:[identity.productId]});return{status:"READY" as const,productType:recovered.productType,revision:recovered.revision,catalogRelease:binding.releaseVersion,selectedCard:recovered.outcome.card,comparisonEntitlement};}
