import { createHmac } from "node:crypto";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { APPLIANCES_CATEGORY_REGISTRY } from "../categoryRegistry";

const fixture = vi.hoisted(() => ({ recovered: null as unknown }));
vi.mock("../recovery.server", () => ({ recoverAppliancesConversation: async () => fixture.recovered }));
import { createAppliancesStageTwoHandoffService, issueAppliancesStageTwoHandoff, readAppliancesStageTwoHandoff } from "./handoff.server";

const secret="test-only-stage-two-secret-material-1234567890";
const now=()=>new Date("2026-09-04T12:00:00Z");
const base={conversationId:"11111111-1111-4111-8111-111111111111",revision:7,category:"WASHING_MACHINE",catalogRelease:"APPLIANCES-WM-TR-v0.1",catalogDigest:"catalog-digest-1",semanticAuthorityVersion:"WASHING_MACHINE_SEMANTIC_REGISTRY/v0.1",semanticAuthorityDigest:"semantic-digest-1",exactProductId:"wm-1",configurationIdentity:"Arçelik WM 1 / TR",decisionFingerprint:"authority-1"};
const service=()=>createAppliancesStageTwoHandoffService({secret,keyId:"test-2026-09",ttlSeconds:300,now,nonce:()=>"fixed-nonce-123456789"});
function signed(claims:unknown){const body=Buffer.from(JSON.stringify(claims)).toString("base64url");return `${body}.${createHmac("sha256",secret).update(body).digest("base64url")}`;}
function recovered(overrides:Record<string,unknown>={}){return{kind:"CONVERSATION",conversationId:base.conversationId,revision:base.revision,departmentId:"APPLIANCES",productType:base.category,catalogBinding:{releaseVersion:base.catalogRelease,releaseDigest:base.catalogDigest,semanticAuthorityVersion:base.semanticAuthorityVersion,semanticAuthorityDigest:base.semanticAuthorityDigest},ended:false,budgetMode:"NEEDS_ONLY",outcome:{kind:"DECISION_READY",decisionFingerprint:base.decisionFingerprint,message:"ready",card:{identity:{productId:base.exactProductId,configurationIdentity:base.configurationIdentity}}},...overrides};}

describe("Appliances AŞAMA 2 signed handoff",()=>{
  beforeEach(()=>{fixture.recovered=recovered();});
  it("binds version, key, purpose, catalog revision, authority identity, time, nonce and replay policy",()=>{const token=service().issue(base);const result=service().verify(token);expect(result).toMatchObject({status:"VALID",claims:{version:"appliances-stage2-handoff/v2",kid:"test-2026-09",purpose:"ASAMA2_VIEW",departmentId:"APPLIANCES",...base,issuedAt:1788523200,expiresAt:1788523500,nonce:"fixed-nonce-123456789",replayPolicy:"REVISION_BOUND_REUSABLE_UNTIL_EXPIRY"}});expect(token).not.toContain(secret);});
  it("rejects tamper, expiry, unknown key, wrong purpose and client-forged material",()=>{const token=service().issue(base);expect(service().verify(`${token.slice(0,-1)}x`)).toMatchObject({status:"INVALID",reason:"BAD_SIGNATURE"});expect(createAppliancesStageTwoHandoffService({secret,ttlSeconds:300,now:()=>new Date("2026-09-04T12:05:00Z")}).verify(token)).toMatchObject({status:"INVALID",reason:"UNKNOWN_KEY"});const claims=JSON.parse(Buffer.from(token.split(".")[0]!,"base64url").toString("utf8"));expect(service().verify(signed({...claims,purpose:"COMPARISON_PURCHASE"}))).toMatchObject({status:"INVALID",reason:"MALFORMED"});expect(service().verify(`${Buffer.from(JSON.stringify(claims)).toString("base64url")}.${Buffer.alloc(32).toString("base64url")}`)).toMatchObject({status:"INVALID",reason:"BAD_SIGNATURE"});});
  it("expires at the boundary and rejects unsafe configuration",()=>{const token=service().issue(base);const expired=createAppliancesStageTwoHandoffService({secret,keyId:"test-2026-09",ttlSeconds:300,now:()=>new Date("2026-09-04T12:05:00Z")});expect(expired.verify(token)).toMatchObject({status:"INVALID",reason:"EXPIRED"});expect(()=>createAppliancesStageTwoHandoffService({secret:"short"})).toThrow(/TOO_SHORT/u);});
  it.each(APPLIANCES_CATEGORY_REGISTRY)("retains the signed contract for $categoryId",category=>{const token=service().issue({...base,category:category.categoryId});expect(service().verify(token)).toMatchObject({status:"VALID",claims:{departmentId:"APPLIANCES",category:category.categoryId,purpose:"ASAMA2_VIEW"}});});
  it("issues only after the persisted revision is DECISION_READY",async()=>{expect(await issueAppliancesStageTwoHandoff({store:{} as never,service:service(),conversationId:base.conversationId,expectedRevision:7})).toMatchObject({status:"ISSUED",handoff:expect.any(String)});fixture.recovered=recovered({revision:8});expect(await issueAppliancesStageTwoHandoff({store:{} as never,service:service(),conversationId:base.conversationId,expectedRevision:7})).toEqual({status:"NOT_AUTHORIZED"});fixture.recovered={...recovered(),outcome:{kind:"ASK"}};expect(await issueAppliancesStageTwoHandoff({store:{} as never,service:service(),conversationId:base.conversationId,expectedRevision:7})).toEqual({status:"NOT_AUTHORIZED"});});
  it.each([["revision",{revision:8}],["category",{productType:"DRYER"}],["department",{departmentId:"CARS"}],["catalog revision",{catalogBinding:{...recovered().catalogBinding,releaseDigest:"changed"}}],["semantic authority",{catalogBinding:{...recovered().catalogBinding,semanticAuthorityDigest:"changed"}}],["decision",{outcome:{...recovered().outcome,decisionFingerprint:"other"}}],["product",{outcome:{...recovered().outcome,card:{identity:{productId:"other",configurationIdentity:base.configurationIdentity}}}}],["configuration",{outcome:{...recovered().outcome,card:{identity:{productId:base.exactProductId,configurationIdentity:"other"}}}}]])("rejects persisted %s mismatch and stale/replay-invalid capabilities",async(_label,change)=>{const token=service().issue(base);fixture.recovered=recovered(change);expect(await readAppliancesStageTwoHandoff({store:{} as never,service:service(),handoff:token})).toMatchObject({status:"INVALID",reason:"AUTHORITY_MISMATCH"});});
  it("reconstructs the selected card from persisted authority and never grants comparison",async()=>{const token=service().issue(base);const result=await readAppliancesStageTwoHandoff({store:{} as never,service:service(),handoff:token});expect(result).toMatchObject({status:"READY",selectedCard:{identity:{productId:"wm-1"}},comparisonEntitlement:{status:"NOT_PURCHASED"}});expect(result).not.toHaveProperty("authorizedComparisonCards");});
});
