import { describe,expect,it } from "vitest";
import { createFileSystemAppliancesArtifactRepository,loadActiveAppliancesAuthority,loadCurrentPriceProjection } from "../authority/loader.server";
import type { AppliancesAuthoritySnapshot } from "../authority/types";
import type { AppliancesConversationState,AppliancesLedgerEvent } from "../contracts";
import { enterAppliancesDepartment } from "../entry.server";
import { evaluateAppliancesCandidates } from "./evaluate";
const repository=createFileSystemAppliancesArtifactRepository(process.cwd());
async function fixture(){const authority=await loadActiveAppliancesAuthority({repository});if(authority.status!=="READY")throw new Error(authority.reason);const entry=await enterAppliancesDepartment({repository,productType:"WASHING_MACHINE",conversationId:"44444444-4444-4444-8444-444444444444",now:new Date("2026-09-03T06:00:00Z")});if(entry.status!=="READY")throw new Error(entry.status);return{authority:authority.snapshot,state:{...entry.state,revision:1} as AppliancesConversationState};}
function event(conceptId:string,normalizedValue:unknown,decisionUse:AppliancesLedgerEvent["decisionUse"]="HARD_FILTER",status:AppliancesLedgerEvent["status"]="ACCEPTED_EXPLICIT"):AppliancesLedgerEvent{return{eventId:`event:${conceptId}:${JSON.stringify(normalizedValue)}`,conceptId,normalizedValue,sourceMessageId:"m",authority:"USER_EXPLICIT",strength:decisionUse==="HARD_FILTER"?"HARD":"SOFT",status,decisionUse,confirmationRequired:false,createdRevision:1,createdAt:"2026-09-03T06:00:00Z"};}
describe("Appliances deterministic candidate evaluation",()=>{
 it("evaluates all 29 exact frozen members in stable order without ranking-shaped output",async()=>{const {authority,state}=await fixture();const first=evaluateAppliancesCandidates({authority,state}),second=evaluateAppliancesCandidates({authority,state});expect(first).toEqual(second);expect(first.status).toBe("READY");if(first.status!=="READY")return;expect(first.projection.counts).toEqual({total:29,eligible:29,ineligible:0,unknown:0,notEvaluated:0});expect(first.projection.candidates.map(c=>c.productId)).toEqual([...authority.productIds].sort());expect(JSON.stringify(first)).not.toMatch(/"(?:rank|score|winner|recommendation|sufficiency)"/i);});
 it("persona and household context have no candidate effect",async()=>{const {authority,state}=await fixture();const household=event("LOAD_CONSOLIDATION",{householdSize:5,capacityConstraint:false},"QUESTION_INPUT");const a=evaluateAppliancesCandidates({authority,state:{...state,ledger:[household]}}),b=evaluateAppliancesCandidates({authority,state:{...state,ledger:[household],personaSignals:[{signalId:"HIGH_VOLUME_OR_BULKY_LOAD",sourceEventIds:[household.eventId],authority:"DERIVED_PLANNING",directCandidateEffect:"NONE",decisionUse:"NONE"}]}});expect(a).toEqual(b);if(a.status==="READY")expect(a.projection.counts.ineligible).toBe(0);});
 it("does not invent a capacity filter where the frozen need mapping has no authorized rule",async()=>{const {authority,state}=await fixture();const result=evaluateAppliancesCandidates({authority,state:{...state,ledger:[event("HIGH_LAUNDRY_VOLUME",{minimumCapacityKg:10})]}});expect(result.status).toBe("READY");if(result.status==="READY"){expect(result.projection.counts.ineligible).toBe(0);expect(result.projection.unsupportedContextEventIds).not.toHaveLength(0);}});
 it("eliminates only conclusive installation oversize and forbids positive fit",async()=>{const {authority,state}=await fixture();const result=evaluateAppliancesCandidates({authority,state:{...state,ledger:[event("INSTALLATION_FIT",{maxWidthMm:590})]}});expect(result.status).toBe("READY");if(result.status!=="READY")return;expect(result.projection.counts.ineligible).toBeGreaterThan(0);expect(result.projection.candidates.find(c=>c.eligibility==="INELIGIBLE")?.reasons).toContainEqual(expect.objectContaining({code:"HARD_TECHNICAL_INCOMPATIBILITY",result:"INCOMPATIBLE"}));const depth=evaluateAppliancesCandidates({authority,state:{...state,ledger:[event("INSTALLATION_FIT",{maxDepthMm:700})]}});if(depth.status==="READY")expect(depth.projection.candidates.every(c=>c.reasons.some(r=>r.code==="INSTALLATION_POSITIVE_FIT_FORBIDDEN"||r.code==="REQUIRED_EVIDENCE_UNKNOWN"))).toBe(true);});
 it("preserves governed capability unknown without inventing absence or hard effect",async()=>{const {authority,state}=await fixture();const result=evaluateAppliancesCandidates({authority,state:{...state,ledger:[event("DETERGENT_CONVENIENCE",true,"SOFT_RANK")]}});expect(result.status).toBe("READY");if(result.status!=="READY")return;expect(result.projection.candidates.some(c=>c.reasons.some(r=>r.code==="REQUIRED_EVIDENCE_UNKNOWN"))).toBe(true);expect(result.projection.counts.ineligible).toBe(0);expect(result.projection.counts.unknown).toBe(0);expect(result.projection.candidates.filter(c=>c.reasons.some(r=>r.result==="SUPPORTED")).every(c=>c.eligibility==="ELIGIBLE")).toBe(true);});
 it("fails a hard budget closed when volatile prices are not rebound to the active catalog",async()=>{const {authority,state}=await fixture();const price=await loadCurrentPriceProjection({repository,authority,now:new Date("2026-09-03T06:00:00Z")});expect(price).toEqual({status:"UNAVAILABLE",reason:"PRICE_BINDING_MISMATCH"});const result=evaluateAppliancesCandidates({authority,state:{...state,ledger:[event("BUDGET_SENSITIVITY",{maximumTry:25000})]},price});expect(result).toEqual({status:"FAILED_CLOSED",reason:"PRICE_INTEGRITY_FAILURE"});expect(JSON.stringify(result)).not.toMatch(/affiliate|payout|seller/i);});
 it("ignores pending, rejected, superseded and cleared context",async()=>{const {authority,state}=await fixture();for(const status of ["PROPOSED","REJECTED","SUPERSEDED","CLEARED"] as const){const result=evaluateAppliancesCandidates({authority,state:{...state,ledger:[event("HYGIENE_PROGRAM_NEED",true,"HARD_FILTER",status)]}});if(result.status==="READY")expect(result.projection.counts.ineligible).toBe(0);}});
 it("fails closed distinctly for context, catalog, semantic and evidence corruption",async()=>{const {authority,state}=await fixture();expect(evaluateAppliancesCandidates({authority,state:{...state,pinnedSemanticDigest:"0".repeat(64)}})).toEqual({status:"FAILED_CLOSED",reason:"CONTEXT_INTEGRITY_FAILURE"});const badCatalog={...authority,catalog:{...authority.catalog,products:[...(authority.catalog.products as unknown[]),(authority.catalog.products as unknown[])[0]]}} as AppliancesAuthoritySnapshot;expect(evaluateAppliancesCandidates({authority:badCatalog,state})).toMatchObject({status:"FAILED_CLOSED",reason:"CATALOG_INTEGRITY_FAILURE"});const badSemantic={...authority,semanticRegistry:{...authority.semanticRegistry,artifacts:{...(authority.semanticRegistry.artifacts as object),"washing-machine-need-evidence-mappings/v1":{records:null}}}} as AppliancesAuthoritySnapshot;expect(evaluateAppliancesCandidates({authority:badSemantic,state})).toMatchObject({status:"FAILED_CLOSED",reason:"SEMANTIC_INTEGRITY_FAILURE"});const badEvidence={...authority,catalog:{...authority.catalog,technicalFacts:[{...(authority.catalog.technicalFacts as Record<string,unknown>[])[0],factStatus:"MAGIC"},...(authority.catalog.technicalFacts as Record<string,unknown>[]).slice(1)]}} as AppliancesAuthoritySnapshot;expect(evaluateAppliancesCandidates({authority:badEvidence,state})).toMatchObject({status:"FAILED_CLOSED",reason:"EVIDENCE_INTEGRITY_FAILURE"});});
});
