import { createHash } from "node:crypto";
import type { AppliancesAuthoritySnapshot, PriceProjectionLoadResult } from "../authority/types";
import type { AppliancesConversationState, AppliancesLedgerEvent } from "../contracts";
import { projectActiveAppliancesContext } from "../context/projection";
import { activeBrandConstraint } from "../brandConstraint";
import { APPLIANCES_CANDIDATE_EVALUATION_POLICY_VERSION, type AppliancesCandidateEvaluation, type AppliancesCandidateEvaluationResult, type CandidateReason } from "./types";

type Json = Record<string, unknown>;
const sha = (value: unknown) => createHash("sha256").update(JSON.stringify(canonical(value))).digest("hex");
function canonical(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonical); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value as Json).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,canonical(item)])); return value; }
const accepted = new Set(["ACCEPTED_EXPLICIT","ACCEPTED_CONFIRMED","ACCEPTED_INTERPRETED"]);
const FACT_ALIASES: Readonly<Record<string,string>> = Object.freeze({ ENERGY_CLASS:"ENERGY_EFFICIENCY_CLASS", BODY_WIDTH:"BODY_WIDTH_MM", BODY_HEIGHT:"BODY_HEIGHT_MM", BODY_DEPTH:"BODY_DEPTH_MM", DEPTH_WITH_DOOR:"DEPTH_WITH_DOOR_MM", DOOR_OPEN_DEPTH:"DOOR_OPEN_DEPTH_MM", REQUIRED_REAR_CLEARANCE:"REQUIRED_REAR_CLEARANCE_MM", HOSE_CONNECTION_CLEARANCE:"HOSE_CONNECTION_CLEARANCE_MM", RATED_CAPACITY:"RATED_CAPACITY_KG", ENERGY_CONSUMPTION_100_CYCLES:"ENERGY_CONSUMPTION_KWH_100_CYCLES", WATER_CONSUMPTION_CYCLE:"WATER_CONSUMPTION_L_CYCLE", ECO_MAX_SPIN:"ECO_MAX_SPIN_RPM", REMAINING_MOISTURE:"WEIGHTED_REMAINING_MOISTURE_PERCENT", NOISE_CLASS:"NOISE_EMISSION_CLASS" });
function fail(reason: Extract<AppliancesCandidateEvaluationResult,{status:"FAILED_CLOSED"}>["reason"]): AppliancesCandidateEvaluationResult { return { status:"FAILED_CLOSED",reason }; }
function contextIsValid(state: AppliancesConversationState, authority: AppliancesAuthoritySnapshot): boolean { return state.departmentId==="APPLIANCES"&&state.productType==="WASHING_MACHINE"&&state.pinnedCatalogRelease===authority.releaseVersion&&state.pinnedCatalogDigest===authority.catalogDigest&&state.pinnedSemanticDigest===authority.semanticDigest&&state.ledger.every(event=>typeof event.eventId==="string"&&authority.conceptIds.has(event.conceptId)&&(accepted.has(event.status)||["PROPOSED","REJECTED","SUPERSEDED","CLEARED"].includes(event.status))); }
export function fingerprintActiveAppliancesContext(state: AppliancesConversationState): string {
 const active=[...projectActiveAppliancesContext(state.ledger).values()].filter(event=>!(event.conceptId==="BUDGET_SENSITIVITY"&&event.decisionUse==="NONE")).sort((a,b)=>a.eventId.localeCompare(b.eventId));
 return sha({ledger:active.map(event=>({eventId:event.eventId,conceptId:event.conceptId,normalizedValue:event.normalizedValue,authority:event.authority,strength:event.strength,decisionUse:event.decisionUse,status:event.status})),brand:activeBrandConstraint(state)});
}
export function evaluateAppliancesCandidates(input:{readonly authority:AppliancesAuthoritySnapshot;readonly state:AppliancesConversationState;readonly price?:PriceProjectionLoadResult}):AppliancesCandidateEvaluationResult {
 const catalog=input.authority.catalog as Json, semantic=input.authority.semanticRegistry as Json;
 if(!contextIsValid(input.state,input.authority))return fail("CONTEXT_INTEGRITY_FAILURE");
 const products=Array.isArray(catalog.products)?catalog.products as Json[]:[],members=Array.isArray(catalog.releaseMembers)?catalog.releaseMembers as string[]:[];
 const ids=products.map(p=>p.productId),identities=products.map(p=>p.configurationIdentity);if(products.length!==members.length||new Set(ids).size!==ids.length||new Set(identities).size!==identities.length||ids.some(id=>typeof id!=="string"||!input.authority.productIds.has(id as string)))return fail("CATALOG_INTEGRITY_FAILURE");
 const facts=Array.isArray(catalog.technicalFacts)?catalog.technicalFacts as Json[]:[],caps=Array.isArray(catalog.capabilityFacts)?catalog.capabilityFacts as Json[]:[],factKeys=new Set(Array.isArray(catalog.factKeyRegistry)?catalog.factKeyRegistry as string[]:[]),capIds=new Set(Array.isArray(catalog.capabilityRegistry)?catalog.capabilityRegistry as string[]:[]);
 if(facts.some(f=>!ids.includes(f.productId)||!factKeys.has(f.factKey as string)||!["VERIFIED","REPORTED","UNKNOWN","CONFLICTED"].includes(f.factStatus as string)))return fail("EVIDENCE_INTEGRITY_FAILURE");
 if(facts.some(f=>Object.keys(f).some(key=>/price|offer|seller|affiliate|retailer/iu.test(key))))return fail("EVIDENCE_INTEGRITY_FAILURE");
 if(caps.some(c=>!ids.includes(c.productId)||!capIds.has(c.capabilityId as string)||!["PRESENT","NOT_AVAILABLE","UNKNOWN"].includes(c.status as string)))return fail("EVIDENCE_INTEGRITY_FAILURE");
 const factRefs=new Set(facts.map(f=>f.factId)),capRefs=new Set(caps.map(c=>c.capabilityFactId)),bindings=Array.isArray(catalog.decisionProjectionBindings)?catalog.decisionProjectionBindings as Json[]:[];if(bindings.length!==products.length||bindings.some(binding=>!ids.includes(binding.productId)||[...((binding.eligibleTechnicalFactRefs as string[]|undefined)??[])].some(ref=>!factRefs.has(ref))||[...((binding.eligibleCapabilityFactRefs as string[]|undefined)??[]),...((binding.hardConstraintEligibleRefs as string[]|undefined)??[])].some(ref=>!capRefs.has(ref))))return fail("EVIDENCE_INTEGRITY_FAILURE");
 const mappings=((((semantic.artifacts as Json|undefined)?.["washing-machine-need-evidence-mappings/v1"] as Json|undefined)?.records)??null) as Json|null;if(!mappings)return fail("SEMANTIC_INTEGRITY_FAILURE");
 const needRecords=(((semantic.artifacts as Json|undefined)?.["washing-machine-user-needs/v1"] as Json|undefined)?.records) as unknown[]|undefined;if(!Array.isArray(needRecords))return fail("SEMANTIC_INTEGRITY_FAILURE");const hardConcepts=new Set(needRecords.flatMap(record=>Array.isArray(record)&&record[1]==="HARD_CONSTRAINT_CAPABLE"&&typeof record[0]==="string"?[record[0]]:[]));
 for(const [need,mapping] of Object.entries(mappings)){if(!input.authority.conceptIds.has(need)||!mapping||typeof mapping!=="object")return fail("SEMANTIC_INTEGRITY_FAILURE");const m=mapping as Json;for(const key of [...((m.primaryFacts as string[]|undefined)??[]),...((m.secondaryFacts as string[]|undefined)??[])])if(!key.includes("WARRANTY")&&!factKeys.has(FACT_ALIASES[key]??key))return fail("SEMANTIC_INTEGRITY_FAILURE");for(const id of (m.requiredCapabilities as string[]|undefined)??[])if(!capIds.has(id))return fail("SEMANTIC_INTEGRITY_FAILURE");}
 const active=[...projectActiveAppliancesContext(input.state.ledger).values()].sort((a,b)=>a.eventId.localeCompare(b.eventId));
 const consumesPrice=active.some(event=>event.conceptId==="BUDGET_SENSITIVITY"&&event.decisionUse==="HARD_FILTER"&&hardConcepts.has(event.conceptId));const price=consumesPrice&&(input.price?.status==="READY"||input.price?.status==="STALE")?input.price:undefined;const priceProjection=price?.projection as Json|undefined;const priceProducts=new Map(((priceProjection?.products as Json[]|undefined)??[]).map(p=>[p.productId as string,p]));
 if(consumesPrice&&input.price?.status==="UNAVAILABLE"&&input.price.reason==="PRICE_BINDING_MISMATCH")return fail("PRICE_INTEGRITY_FAILURE");
 const brand=activeBrandConstraint(input.state);const evaluations=products.slice().sort((a,b)=>String(a.productId).localeCompare(String(b.productId))).map(product=>{const evaluated=evaluateOne(product,active,mappings,hardConcepts,facts,caps,catalog,price,priceProducts);if(!brand||String(product.brandId).toLocaleLowerCase("tr-TR")===brand.brandId)return evaluated;return{...evaluated,eligibility:"INELIGIBLE" as const,reasons:[...evaluated.reasons,{code:"HARD_TECHNICAL_INCOMPATIBILITY" as const,result:"INCOMPATIBLE" as const,contextEventId:brand.eventId,conceptId:"BRAND_CONSTRAINT",evidenceRefs:[brand.policyId,brand.policyDigest]}]};});
 const contextFingerprint=fingerprintActiveAppliancesContext(input.state);
 const fingerprintInput={policyVersion:APPLIANCES_CANDIDATE_EVALUATION_POLICY_VERSION,catalogRelease:input.authority.releaseVersion,catalogDigest:input.authority.catalogDigest,semanticDigest:input.authority.semanticDigest,contextRevision:input.state.revision,contextFingerprint,...(priceProjection?{priceSnapshotId:priceProjection.snapshotId,priceFingerprint:priceProjection.projectionFingerprint,priceFreshness:price!.status}:{})};
 const counts={total:evaluations.length,eligible:evaluations.filter(e=>e.eligibility==="ELIGIBLE").length,ineligible:evaluations.filter(e=>e.eligibility==="INELIGIBLE").length,unknown:evaluations.filter(e=>e.eligibility==="ELIGIBILITY_UNKNOWN").length,notEvaluated:evaluations.filter(e=>e.eligibility==="NOT_EVALUATED").length};
 const unsupported=[...new Set(evaluations.flatMap(e=>e.unevaluatedContextEventIds))].sort();
 return{status:"READY",projection:{policyVersion:APPLIANCES_CANDIDATE_EVALUATION_POLICY_VERSION,catalogRelease:input.authority.releaseVersion,catalogDigest:input.authority.catalogDigest,membershipDigest:String(catalog.membershipDigest),semanticRegistryVersion:String((semantic as Json).registryVersion),semanticDigest:input.authority.semanticDigest,contextRevision:input.state.revision,contextFingerprint,evaluationFingerprint:sha(fingerprintInput),...(priceProjection?{priceSnapshot:{snapshotId:String(priceProjection.snapshotId),projectionFingerprint:String(priceProjection.projectionFingerprint),freshness:price!.status}}:{}),counts,candidates:evaluations,remainingProductRefs:evaluations.filter(e=>e.eligibility!=="INELIGIBLE").map(e=>e.productId),supportedDiscriminators:[...factKeys].sort(),unsupportedContextEventIds:unsupported}};
}
function evaluateOne(product:Json,active:readonly AppliancesLedgerEvent[],mappings:Json,hardConcepts:ReadonlySet<string>,facts:readonly Json[],caps:readonly Json[],catalog:Json,price:({status:"READY"|"STALE";projection:Readonly<Json>})|undefined,priceProducts:ReadonlyMap<string,Json>):AppliancesCandidateEvaluation{
 const id=String(product.productId),reasons:CandidateReason[]=[],unevaluated:string[]=[];const productFacts=facts.filter(f=>f.productId===id),productCaps=caps.filter(c=>c.productId===id);
 for(const event of active){const mapping=mappings[event.conceptId] as Json|undefined;
  if(event.conceptId==="BUDGET_SENSITIVITY"&&event.decisionUse==="HARD_FILTER"){const max=(event.normalizedValue as {maximumTry?:unknown}|null)?.maximumTry,p=priceProducts.get(id);if(typeof max!=="number"){unevaluated.push(event.eventId);continue;}const usable=price?.status==="READY"&&p?.status==="PRICE_AVAILABLE"&&typeof p.representativePriceTRY==="number";const result=usable?(p!.representativePriceTRY as number)<=max?"COMPATIBLE":"INCOMPATIBLE":"UNKNOWN";reasons.push({code:result==="COMPATIBLE"?"PRICE_COMPATIBLE":result==="INCOMPATIBLE"?"BUDGET_INCOMPATIBLE":"BUDGET_ELIGIBILITY_UNKNOWN",result,contextEventId:event.eventId,conceptId:event.conceptId,evidenceRefs:p?.observationRefs as string[]??[]});continue;}
  if(!mapping){unevaluated.push(event.eventId);reasons.push({code:"UNMAPPED_ACCEPTED_CONTEXT",result:"NO_AUTHORIZED_EFFECT",contextEventId:event.eventId,conceptId:event.conceptId,evidenceRefs:[]});continue;}
  if(event.conceptId==="INSTALLATION_FIT"&&event.decisionUse==="HARD_FILTER"){const v=event.normalizedValue as {maxWidthMm?:number;maxHeightMm?:number;maxDepthMm?:number}|null;let compared=false,unknown=false,incompatible=false;for(const [field,key] of [["maxWidthMm","BODY_WIDTH_MM"],["maxHeightMm","BODY_HEIGHT_MM"],["maxDepthMm","BODY_DEPTH_MM"]] as const){if(typeof v?.[field]!=="number")continue;compared=true;const fact=productFacts.find(f=>f.factKey===key&&f.factStatus==="VERIFIED");if(!fact)unknown=true;else if((fact.value as number)>v[field]!)incompatible=true;}const refs=productFacts.filter(f=>["BODY_WIDTH_MM","BODY_HEIGHT_MM","BODY_DEPTH_MM"].includes(f.factKey as string)).map(f=>String(f.factId));if(incompatible)reasons.push({code:"HARD_TECHNICAL_INCOMPATIBILITY",result:"INCOMPATIBLE",contextEventId:event.eventId,conceptId:event.conceptId,semanticMappingRef:"washing-machine-need-evidence-mappings/v1:INSTALLATION_FIT",evidenceRefs:refs});else if(compared)reasons.push({code:unknown?"REQUIRED_EVIDENCE_UNKNOWN":"INSTALLATION_POSITIVE_FIT_FORBIDDEN",result:unknown?"UNKNOWN":"CONDITIONAL",contextEventId:event.eventId,conceptId:event.conceptId,semanticMappingRef:"washing-machine-need-evidence-mappings/v1:INSTALLATION_FIT",evidenceRefs:refs});else unevaluated.push(event.eventId);continue;}
  const required=(mapping.requiredCapabilities as string[]|undefined)??[];if(required.length){for(const capId of required){const cap=productCaps.find(c=>c.capabilityId===capId),hard=event.decisionUse==="HARD_FILTER"&&hardConcepts.has(event.conceptId);const result=cap?.status==="PRESENT"?"SUPPORTED":cap?.status==="NOT_AVAILABLE"?"NOT_SUPPORTED":"UNKNOWN";reasons.push({code:hard&&result==="NOT_SUPPORTED"?"HARD_CAPABILITY_INCOMPATIBILITY":result==="UNKNOWN"?"REQUIRED_EVIDENCE_UNKNOWN":"NON_FILTERING_EVIDENCE",result,contextEventId:event.eventId,conceptId:event.conceptId,semanticMappingRef:`washing-machine-need-evidence-mappings/v1:${event.conceptId}`,evidenceRefs:cap?[String(cap.capabilityFactId),...((cap.assertionRefs as string[]|undefined)??[])]:[]});}continue;}
  const primary=(mapping.primaryFacts as string[]|undefined)??[];const refs=primary.flatMap(key=>productFacts.filter(f=>f.factKey===(FACT_ALIASES[key]??key)&&f.factStatus==="VERIFIED").map(f=>String(f.factId)));reasons.push({code:"NON_FILTERING_EVIDENCE",result:refs.length?"COMPARABLE_VALUE":"UNKNOWN",contextEventId:event.eventId,conceptId:event.conceptId,semanticMappingRef:`washing-machine-need-evidence-mappings/v1:${event.conceptId}`,evidenceRefs:refs});
 }
 const incompatible=reasons.some(r=>r.result==="INCOMPATIBLE"),unknown=reasons.some(r=>{const event=active.find(e=>e.eventId===r.contextEventId);return r.result==="UNKNOWN"&&event?.decisionUse==="HARD_FILTER"&&hardConcepts.has(event.conceptId);});const lifecycle=String(product.lifecycleState);const disclosures=((catalog.decisionProjectionBindings as Json[]|undefined)?.find(p=>p.productId===id)?.requiredDisclosureRefs as string[]|undefined)??[];if(lifecycle==="TEMPORARILY_UNAVAILABLE"&&active.length)reasons.push({code:"LIFECYCLE_RESTRICTION",result:"CONDITIONAL",contextEventId:active[0]!.eventId,conceptId:active[0]!.conceptId,evidenceRefs:[]});return{productId:id,configurationIdentity:String(product.configurationIdentity),lifecycleState:lifecycle,eligibility:incompatible?"INELIGIBLE":unknown?"ELIGIBILITY_UNKNOWN":"ELIGIBLE",reasons,unevaluatedContextEventIds:unevaluated,disclosureRefs:disclosures};
}
