/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial governed fixture mutations exercise fail-closed boundaries */
import { beforeAll, describe, expect, it } from "vitest";
import { createHash } from "node:crypto";
import { createFileSystemAppliancesArtifactRepository, loadActiveAppliancesAuthority, loadCurrentPriceProjection } from "../authority/loader.server";
import type { AppliancesAuthoritySnapshot } from "../authority/types";
import { evaluateAppliancesCandidates } from "../candidate/evaluate";
import type { AppliancesCandidateEvaluationResult } from "../candidate/types";
import type { AppliancesConversationState, AppliancesLedgerEvent } from "../contracts";
import { enterAppliancesDepartment } from "../entry.server";
import { createFileSystemCandidateSelectionPolicyRepository, loadActiveWashingMachineCandidateSelectionPolicy, type CandidateSelectionPolicyLoadResult } from "../governance/candidateSelectionPolicyLoader.server";
import { createFileSystemQuestionPolicyRepository, loadActiveWashingMachineQuestionPolicy } from "../governance/questionPolicyLoader.server";
import { createFileSystemSufficiencyRecommendationPolicyRepository, loadActiveWashingMachineSufficiencyRecommendationPolicy } from "../governance/sufficiencyRecommendationPolicyLoader.server";
import type { AppliancesQuestionPlan } from "../planner/types";
import { evaluateAppliancesSufficiency } from "../sufficiency/evaluate";
import type { AppliancesSufficiencyResult } from "../sufficiency/types";
import { evaluateAppliancesCandidateSelection } from "./evaluate";
import { activeCatalogPriceFixture } from "../testing/activeCatalogPriceFixture";

const root = process.cwd(), repository = createFileSystemAppliancesArtifactRepository(root);
const BEKO_72 = "appliances:wm:tr:beko:cmx-8100", BEKO_72_2 = "appliances:wm:tr:beko:cmx-10120", BOSCH_70 = "appliances:wm:tr:bosch:wgb244a0tr", LG_ABSENT = "appliances:wm:tr:lg:f4t2vym1s";
let authority: AppliancesAuthoritySnapshot, base: AppliancesConversationState, price: Awaited<ReturnType<typeof loadCurrentPriceProjection>>, policy: Extract<CandidateSelectionPolicyLoadResult, { status: "READY" }>, questionPolicy: any, sufficiencyPolicy: any;
beforeAll(async () => {
  const loaded = await loadActiveAppliancesAuthority({ repository }); if (loaded.status !== "READY") throw new Error(loaded.reason); authority = loaded.snapshot;
  const entry = await enterAppliancesDepartment({ repository, productType: "WASHING_MACHINE", conversationId: "88888888-8888-4888-8888-888888888888", now: new Date("2026-09-03T06:00:00Z") }); if (entry.status !== "READY") throw new Error(entry.status); base = entry.state;
  price = activeCatalogPriceFixture(authority);
  questionPolicy = await loadActiveWashingMachineQuestionPolicy({ repository: createFileSystemQuestionPolicyRepository(root), authority }); if (questionPolicy.status !== "READY") throw new Error(questionPolicy.reason);
  sufficiencyPolicy = await loadActiveWashingMachineSufficiencyRecommendationPolicy({ repository: createFileSystemSufficiencyRecommendationPolicyRepository(root), authority, questionPolicy: questionPolicy.snapshot }); if (sufficiencyPolicy.status !== "READY") throw new Error(sufficiencyPolicy.reason);
  const loadedPolicy = await loadActiveWashingMachineCandidateSelectionPolicy({ repository: createFileSystemCandidateSelectionPolicyRepository(root), authority, questionPolicy: questionPolicy.snapshot, sufficiencyPolicy: sufficiencyPolicy.snapshot }); if (loadedPolicy.status !== "READY") throw new Error(loadedPolicy.reason); policy = loadedPolicy;
});
const event = (conceptId: string, normalizedValue: unknown): AppliancesLedgerEvent => ({ eventId: `event:${conceptId}`, conceptId, normalizedValue, sourceMessageId: "message", authority: "USER_EXPLICIT", strength: "SOFT", status: "ACCEPTED_EXPLICIT", decisionUse: "SOFT_RANK", confirmationRequired: false, createdRevision: 0, createdAt: "2026-09-03T06:00:00Z" });
const stateWith = (...events: AppliancesLedgerEvent[]): AppliancesConversationState => ({ ...base, ledger: events });
function projectionFor(state: AppliancesConversationState, keep: readonly string[]): Extract<AppliancesCandidateEvaluationResult, { status: "READY" }> {
  const result = evaluateAppliancesCandidates({ authority, state, price }); if (result.status !== "READY") throw new Error(result.reason);
  const candidates = result.projection.candidates.map((candidate) => keep.includes(candidate.productId) ? candidate : { ...candidate, eligibility: "INELIGIBLE" as const, reasons: [{ code: "HARD_TECHNICAL_INCOMPATIBILITY" as const, result: "INCOMPATIBLE" as const, contextEventId: "fixture-hard-gate", conceptId: "INSTALLATION_FIT", evidenceRefs: [] }] });
  return { ...result, projection: { ...result.projection, candidates, remainingProductRefs: [...keep].sort(), counts: { total: candidates.length, eligible: keep.length, ineligible: candidates.length - keep.length, unknown: 0, notEvaluated: 0 } } };
}
function eligible(state: AppliancesConversationState, evaluation: Extract<AppliancesCandidateEvaluationResult, { status: "READY" }>): Extract<AppliancesSufficiencyResult, { kind: "RECOMMENDATION_POOL_ELIGIBLE" }> {
  const planner: AppliancesQuestionPlan = { kind: "NO_AUTHORIZED_MATERIAL_QUESTION", contextRevision: state.revision, evaluationFingerprint: evaluation.projection.evaluationFingerprint, questionPolicyId: questionPolicy.snapshot.payload.policyId, questionPolicyDigest: questionPolicy.snapshot.policyDigest, meaning: "NEUTRAL_PLANNING_ABSENCE" };
  const result = evaluateAppliancesSufficiency({ authority, state, evaluation, planner, price, policy: sufficiencyPolicy }); if (result.kind !== "RECOMMENDATION_POOL_ELIGIBLE") throw new Error(result.kind); return result;
}
function run(state: AppliancesConversationState, keep: readonly string[], changedAuthority = authority, changedPolicy: CandidateSelectionPolicyLoadResult = policy) { const evaluation = projectionFor(state, keep), sufficiency = eligible(state, evaluation); return evaluateAppliancesCandidateSelection({ authority: changedAuthority, state, evaluation, sufficiency, policy: changedPolicy }); }
function mutateAuthority(fn: (catalog: any) => void): AppliancesAuthoritySnapshot { const catalog = structuredClone(authority.catalog) as any; fn(catalog); return { ...authority, catalog } as AppliancesAuthoritySnapshot; }
const canonical = (value: any): any => Array.isArray(value) ? value.map(canonical) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, canonical(item)])) : value;
const digest = (value: unknown): string => createHash("sha256").update(JSON.stringify(canonical(value))).digest("hex");
function rehashSufficiency(value: any): void { value.evaluationFingerprint = digest({ ...value, evaluationFingerprint: "" }); }

describe("deterministic frozen Pareto Appliances candidate selection", () => {
  it("consumes the frozen policy, selects singleton, and emits no downstream authorization or rank", () => { const result = run(base, [BEKO_72]); expect(result).toMatchObject({ outcome: "SELECTED_SINGLE", selectedCandidateId: BEKO_72, provenance: { selectionPolicyId: "WASHING_MACHINE_CANDIDATE_SELECTION_POLICY/v0.1", selectionPolicyDigest: "d6665b24f8097fee1c99cd84c9855f777d2d8241be05f3417aa2cc2bd6af9ea6" } }); expect(JSON.stringify(result)).not.toMatch(/"(?:score|weight|rank|decisionReady|decisionAuthorization|decisionCard|recommendation|advisor|sellerAction|affiliateAction)"\s*:/iu); });
  it("returns no governed selection with no active preference and is input-order independent", () => { const first = run(base, [BEKO_72, BOSCH_70]), second = run(base, [BOSCH_70, BEKO_72]); expect(first.outcome).toBe("NO_GOVERNED_SELECTION"); expect(second).toEqual(first); });
  it("applies comparable low-noise Pareto dominance and preserves exact known ties", () => { expect(run(stateWith(event("LOW_NOISE_PRIORITY", true)), [BEKO_72, BOSCH_70])).toMatchObject({ outcome: "SELECTED_SINGLE", selectedCandidateId: BOSCH_70 }); expect(run(stateWith(event("LOW_NOISE_PRIORITY", true)), [BEKO_72, BEKO_72_2])).toMatchObject({ outcome: "TIED_TOP_SET", tiedCandidateIds: [BEKO_72_2, BEKO_72] }); });
  it("treats non-comparable noise and unknown capability as non-dominated, never as equal or worse", () => { const noiseAuthority = mutateAuthority((catalog) => { catalog.technicalFacts.find((fact: any) => fact.productId === BOSCH_70 && fact.factKey === "SPIN_NOISE_DB").regime = "OTHER"; }); const noise = run(stateWith(event("LOW_NOISE_PRIORITY", "IMPORTANT")), [BEKO_72, BOSCH_70], noiseAuthority); expect(noise).toMatchObject({ outcome: "NON_DOMINATED_SET" }); expect(JSON.stringify(noise)).toContain("NON_COMPARABLE_REGIME"); const dosing = run(stateWith(event("DETERGENT_CONVENIENCE", "WANTED")), [BEKO_72, BOSCH_70]); expect(dosing).toMatchObject({ outcome: "NON_DOMINATED_SET" }); });
  it("compares exact auto dosing and requires supported remote actions", () => { expect(run(stateWith(event("DETERGENT_CONVENIENCE", "WANTED")), [BOSCH_70, LG_ABSENT])).toMatchObject({ outcome: "SELECTED_SINGLE", selectedCandidateId: BOSCH_70 }); const withoutActions = run(stateWith(event("REMOTE_CONTROL", "WANTED")), [BOSCH_70, LG_ABSENT]); expect(withoutActions.outcome).toBe("NON_DOMINATED_SET"); const withActions = mutateAuthority((catalog) => { catalog.capabilityFacts.find((fact: any) => fact.productId === BOSCH_70 && fact.capabilityId === "SMART_CONNECTIVITY").parameters.supportedActions = ["START", "STATUS"]; }); expect(run(stateWith(event("REMOTE_CONTROL", "WANTED")), [BOSCH_70, LG_ABSENT], withActions)).toMatchObject({ outcome: "SELECTED_SINGLE", selectedCandidateId: BOSCH_70 }); });
  it("keeps inactive values, price, persona, brand, product ID and rationale quantity out of selection", () => { const state = stateWith(event("LOW_NOISE_PRIORITY", "NOT_IMPORTANT")), baseline = run(state, [BEKO_72, BOSCH_70]); const changed = mutateAuthority((catalog) => { catalog.products.find((p: any) => p.productId === BEKO_72).brandId = "zzz"; catalog.rationaleBindings.push(...catalog.rationaleBindings.slice(0, 3)); }); const persona = { ...state, personaSignals: [{ signalId: "NOISE_SENSITIVE", sourceEventIds: [], authority: "DERIVED_PLANNING" as const, directCandidateEffect: "NONE" as const, decisionUse: "NONE" as const }] }; expect(baseline.outcome).toBe("NO_GOVERNED_SELECTION"); expect(run(persona, [BEKO_72, BOSCH_70], changed)).toEqual(baseline); });
  it("preserves budget-unknown IDs and price provenance as disclosure-only", () => { const budgetEvent = { ...event("BUDGET_SENSITIVITY", { maximumTry: 25_000 }), strength: "HARD" as const, decisionUse: "HARD_FILTER" as const }, state = stateWith(budgetEvent), evaluation = evaluateAppliancesCandidates({ authority, state, price }); if (evaluation.status !== "READY") throw new Error(evaluation.reason); const sufficiency = eligible(state, evaluation); const result = evaluateAppliancesCandidateSelection({ authority, state, evaluation, sufficiency, policy }); expect(result.outcome).toBe("NO_GOVERNED_SELECTION"); if (result.outcome !== "FAILED_CLOSED") { expect(result.budgetUnknownCandidateIds).toEqual(sufficiency.candidatePartitions.budgetUnknownCandidateIds); expect(result.provenance.priceSnapshot).toEqual(evaluation.projection.priceSnapshot); } });
  it("preserves cross-dimension tradeoffs as a non-dominated set", () => { const changed = mutateAuthority((catalog) => { const remote = catalog.capabilityFacts.find((fact: any) => fact.productId === BOSCH_70 && fact.capabilityId === "SMART_CONNECTIVITY"); remote.parameters.supportedActions = ["START"]; const dosing = catalog.capabilityFacts.find((fact: any) => fact.productId === BOSCH_70 && fact.capabilityId === "AUTO_DOSING"); dosing.status = "NOT_AVAILABLE"; dosing.decisionEligibility = "ABSENCE_MATCH_ELIGIBLE"; dosing.absenceEvidenceRef = dosing.assertionRefs[0]; const lgDosing = catalog.capabilityFacts.find((fact: any) => fact.productId === LG_ABSENT && fact.capabilityId === "AUTO_DOSING"); lgDosing.status = "PRESENT"; lgDosing.decisionEligibility = "CONDITIONALLY_DECISION_ELIGIBLE"; lgDosing.absenceEvidenceRef = null; catalog.decisionProjectionBindings.find((binding: any) => binding.productId === LG_ABSENT).softPreferenceEligibleRefs.push(lgDosing.capabilityFactId); }); const result = run(stateWith(event("REMOTE_CONTROL", "WANTED"), event("DETERGENT_CONVENIENCE", "WANTED")), [BOSCH_70, LG_ABSENT], changed); expect(result.outcome).toBe("NON_DOMINATED_SET"); });
  it.each([
    ["non-eligible input", (x: any) => { x.sufficiency = { kind: "FAILED_CLOSED", reason: "MALFORMED_CANDIDATE_STATE" }; }, "INPUT_NOT_RECOMMENDATION_POOL_ELIGIBLE"],
    ["pool fingerprint", (x: any) => { x.sufficiency.candidatePool.poolFingerprint = "0".repeat(64); }, "POOL_FINGERPRINT_MISMATCH"],
    ["context fingerprint", (x: any) => { x.evaluation.projection.contextFingerprint = "0".repeat(64); }, "CONTEXT_FINGERPRINT_MISMATCH"],
    ["candidate fingerprint", (x: any) => { x.sufficiency.provenance.evaluationFingerprint = "0".repeat(64); rehashSufficiency(x.sufficiency); }, "CANDIDATE_EVALUATION_FINGERPRINT_MISMATCH"],
    ["duplicate candidate", (x: any) => { x.sufficiency.candidatePool.candidateIds = [BEKO_72, BEKO_72]; }, "DUPLICATE_CANDIDATE_ID"],
    ["unknown candidate", (x: any) => { x.sufficiency.candidatePool.candidateIds = ["appliances:wm:tr:unknown:model"]; }, "UNKNOWN_CANDIDATE_ID"],
  ])("fails closed for %s mismatch", (_label, mutate, reason) => { const state = base, evaluation = projectionFor(state, [BEKO_72]), sufficiency = structuredClone(eligible(state, evaluation)); const input: any = { authority, state, evaluation: structuredClone(evaluation), sufficiency, policy }; mutate(input); expect(evaluateAppliancesCandidateSelection(input)).toMatchObject({ outcome: "FAILED_CLOSED", reason }); });
  it("fails closed for malformed governed evidence and selection-policy loader failure", () => { const malformed = mutateAuthority((catalog) => { catalog.capabilityFacts.find((fact: any) => fact.productId === BOSCH_70 && fact.capabilityId === "AUTO_DOSING").assertionRefs = "bad"; }); expect(run(stateWith(event("DETERGENT_CONVENIENCE", "WANTED")), [BOSCH_70, LG_ABSENT], malformed)).toMatchObject({ outcome: "FAILED_CLOSED", reason: "MALFORMED_CAPABILITY_EVIDENCE" }); expect(run(base, [BEKO_72], authority, { status: "FAILED_CLOSED", reason: "POLICY_MISSING" })).toMatchObject({ outcome: "FAILED_CLOSED", reason: "SELECTION_POLICY_AUTHORITY_FAILURE" }); });
  it("fails closed for malformed technical facts, market divergence, and rationale/evidence mismatch", () => { const malformedFact = mutateAuthority((catalog) => { catalog.technicalFacts.find((fact: any) => fact.productId === BOSCH_70 && fact.factKey === "SPIN_NOISE_DB").value = "quiet"; }); expect(run(stateWith(event("LOW_NOISE_PRIORITY", "IMPORTANT")), [BEKO_72, BOSCH_70], malformedFact)).toMatchObject({ outcome: "FAILED_CLOSED", reason: "MALFORMED_TECHNICAL_FACT" }); const market = mutateAuthority((catalog) => { catalog.marketApplicability.find((item: any) => item.productId === BOSCH_70).status = "UNKNOWN"; }); expect(run(base, [BOSCH_70], market)).toMatchObject({ outcome: "FAILED_CLOSED", reason: "INVALID_LIFECYCLE_OR_MARKET_APPLICABILITY" }); const rationale = mutateAuthority((catalog) => { catalog.rationaleBindings.push({ productId: BOSCH_70, supportedNeedRef: "semantic:WASHING_MACHINE_SEMANTIC_REGISTRY/v0.1:need:LOW_NOISE_PRIORITY", supportingCapabilityFactRefs: [], supportingTechnicalFactRefs: ["fact:not-participating"] }); }); expect(run(stateWith(event("LOW_NOISE_PRIORITY", "IMPORTANT")), [BEKO_72, BOSCH_70], rationale)).toMatchObject({ outcome: "FAILED_CLOSED", reason: "RATIONALE_EVIDENCE_BINDING_MISMATCH" }); });
});
