import type { ConversationActionDecision } from "../action/types";
import type { CatalogSnapshotLoadResult } from "../catalog/types";
import type { ConversationEvent } from "../domain/conversationEvent";
import type { ConversationMemory } from "../domain/conversationMemory";
import type { DecisionState, MaterialQuestionOption } from "../domain/decisionState";
import type { AuthoritativeSemanticPlan } from "../interpretation/types";
import type { PersistedGovernedOffer } from "../offer/types";
export interface RecommendationOfferAuditIntent { readonly kind: "ACCEPT_RECOMMENDATION_TERMS_AND_REVEAL"; readonly conversationId: string; readonly offerId: string; readonly recommendationTermsVersion: "REC-2026.08-v1.1"; readonly acceptedAt: string; readonly revealedAt: string; readonly acceptanceSequence: 1; readonly revealSequence: 2; readonly idempotencyKey: string }
export interface DecisionTurnV2Input { readonly conversationId: string; readonly messageId: string; readonly idempotencyKey: string; readonly expectedConversationRevision: number; readonly userMessage: string; readonly typedOptionId?: string; readonly typedOptionIds?: readonly string[]; readonly offerToken?: string; readonly recommendationOfferAuditIntent?: RecommendationOfferAuditIntent; readonly requestTime: string; readonly signal?: AbortSignal }
export interface PublicOption { readonly id: string; readonly label: string; readonly description?: string }
export interface PublicOptionSelection { readonly mode: "SINGLE" | "MULTIPLE"; readonly minimumSelections: number; readonly maximumSelections: number }
export type PublicAuthorizedCard = import("../presentation/publicCardSchema").DecisionSafePublicCard;
export type PublicRecoverableStatus = "CATALOG_UNAVAILABLE" | "CATALOG_SNAPSHOT_UNAVAILABLE" | "PROVIDER_UNAVAILABLE" | "CONCURRENCY_CONFLICT";
export interface PublicCandidateSummary { readonly count: number; readonly basis: "ACTIVE_DECISION_COHORT" | "BUDGET_NEAREST_SHORTLIST"; readonly label: string }
export interface DecisionTurnV2Output { readonly conversationId: string; readonly revision: number; readonly state: DecisionState; readonly message: string; readonly options: readonly PublicOption[]; readonly optionSelection?: PublicOptionSelection; readonly candidateSummary?: PublicCandidateSummary; readonly cards: readonly PublicAuthorizedCard[]; readonly offer?: { readonly offerId: string; readonly token: string; readonly expiresAt: string }; readonly recoverableStatus?: PublicRecoverableStatus }
export interface StoredV2Conversation { readonly conversationId: string; readonly revision: number; readonly memory?: ConversationMemory; readonly messageResults: Readonly<Record<string, { readonly payloadHash: string; readonly output: DecisionTurnV2Output }>> }
export type PersistedOfferTransitionIntent =
  | ({ readonly offerId: string; readonly conversationId: string; readonly to: "REVEALED"; readonly offerIdentityFingerprint: `sha256:${string}`; readonly postCommitAuthorizationRequired?: boolean } & RecommendationOfferAuditIntent)
  | { readonly offerId: string; readonly conversationId: string; readonly to: "REVOKED"; readonly at: string };
export interface V2ConversationStore { load(conversationId: string): Promise<StoredV2Conversation | null>; commit(input: { readonly expectedRevision: number; readonly next: StoredV2Conversation; readonly events: readonly ConversationEvent[]; readonly offer?: PersistedGovernedOffer; readonly offerTransition?: PersistedOfferTransitionIntent }): Promise<{ readonly status: "OK" } | { readonly status: "REVISION_CONFLICT" }> }
export interface V2TurnStages { loadCatalog(input: { readonly memory?: ConversationMemory; readonly now: Date }): Promise<CatalogSnapshotLoadResult>; interpret(input: DecisionTurnV2Input, prior?: ConversationMemory): Promise<AuthoritativeSemanticPlan>; createEvents(input: { readonly turn: DecisionTurnV2Input; readonly interpretation: AuthoritativeSemanticPlan; readonly previous?: ConversationMemory; readonly catalog: Extract<CatalogSnapshotLoadResult, { status: "READY" }>["snapshot"] }): readonly ConversationEvent[]; reduceMemory(input: { readonly previous?: ConversationMemory; readonly events: readonly ConversationEvent[]; readonly catalog: Extract<CatalogSnapshotLoadResult, { status: "READY" }>["snapshot"] }): ConversationMemory; evaluate(input: { readonly turn: DecisionTurnV2Input; readonly memory: ConversationMemory; readonly catalog: Extract<CatalogSnapshotLoadResult, { status: "READY" }>["snapshot"]; readonly interpretation: AuthoritativeSemanticPlan; readonly now: Date }): Promise<{ readonly action: ConversationActionDecision; readonly offer?: PersistedGovernedOffer; readonly offerToken?: string; readonly offerTransition?: PersistedOfferTransitionIntent; readonly candidateSummary?: PublicCandidateSummary; readonly facts: readonly import("../realization/types").AuthorizedExplanationFact[] }>; authorizeCards?(input: { readonly token: string; readonly conversationId: string; readonly catalog: Extract<CatalogSnapshotLoadResult, { status: "READY" }>["snapshot"]; readonly memory: ConversationMemory; readonly now: Date; readonly pendingOfferTransition?: PersistedOfferTransitionIntent }): Promise<readonly PublicAuthorizedCard[]>; realize(input: { readonly action: ConversationActionDecision; readonly facts: readonly import("../realization/types").AuthorizedExplanationFact[] }): Promise<{ readonly message: string; readonly source: "MODEL" | "REPAIRED_MODEL" | "DETERMINISTIC_FALLBACK" }> }
export const publicOptions = (action: ConversationActionDecision): readonly PublicOption[] => (action.materialQuestion?.options ?? []).map((option: MaterialQuestionOption) => ({ id: option.id, label: option.userFacingLabel, ...(option.userFacingDescription ? { description: option.userFacingDescription } : {}) }));
export const publicOptionSelection = (action: ConversationActionDecision): PublicOptionSelection | undefined => action.materialQuestion ? ({ mode: action.materialQuestion.selectionMode ?? "SINGLE", minimumSelections: action.materialQuestion.minimumSelections ?? 1, maximumSelections: action.materialQuestion.maximumSelections ?? 1 }) : undefined;
export interface V2TurnStages { interpretOfferResponse?(input: DecisionTurnV2Input, prior?: ConversationMemory): Promise<AuthoritativeSemanticPlan | null> }
