"use client";
import{FormEvent,KeyboardEvent,useEffect,useState}from"react";import{BABY_EXPERIENCE}from"@/features/xpy/visualPacks";import{XpyAssistantBubble,XpyComposer,XpyHeader,XpyStageOneFrame,XpyTranscript,XpyUserBubble}from"@/components/xpy/XpyPresentation";
import{XpyDecisionCard}from"@/components/xpy/XpyDecisionCard";import{STROLLER_STAGE_ONE_PRESENTATION,projectStrollerSet}from"@/features/baby/presentation/stageOneAdapter";import type{authorizeStrollerCard}from"@/features/baby/decision";
type Card=ReturnType<typeof authorizeStrollerCard>;type Outcome={kind:string;message:string;questionKey?:string;choices?:readonly{value:string;label:string}[];candidates?:readonly{id:string;label:string}[];card?:Card;revision?:number};type Entry={user?:string;outcome:Outcome};const key="expiya:baby:stroller:conversation";
export default function BabyConversation({embedded=false}:{readonly embedded?:boolean}){const[entries,setEntries]=useState<Entry[]>([]),[draft,setDraft]=useState(""),[id,setId]=useState(""),[revision,setRevision]=useState(0),[busy,setBusy]=useState(true);
 useEffect(()=>{void(async()=>{const conversationId=localStorage.getItem(key)??crypto.randomUUID();let response=await fetch("/api/baby/conversation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"READ",conversationId})});if(response.status===404){response=await fetch("/api/baby/conversation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"CREATE",conversationId,messageId:crypto.randomUUID(),categoryId:"STROLLER"})})}const body=await response.json() as Outcome&{conversationId?:string;outcome?:Outcome};if(response.ok){localStorage.setItem(key,conversationId);setId(conversationId);setRevision(body.revision??0);setEntries([{outcome:body.outcome??body}])}else setEntries([{outcome:{kind:"UNAVAILABLE",message:"Görüşme kaydı şu anda açılamıyor; lütfen daha sonra yeniden deneyin."}}]);setBusy(false)})()},[]);
 async function send(message:string){if(!message.trim()||busy||!id)return;setBusy(true);const response=await fetch("/api/baby/conversation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"TURN",conversationId:id,messageId:crypto.randomUUID(),expectedRevision:revision,message:message.trim()})}),body=await response.json() as Outcome&{revision?:number};if(response.ok){setRevision(body.revision??revision+1);setEntries(x=>[...x,{user:message.trim(),outcome:body}])}else setEntries(x=>[...x,{user:message.trim(),outcome:{kind:"ERROR",message:"Görüşme güncellendi veya geçici olarak kullanılamıyor; sayfayı yenileyin."}}]);setDraft("");setBusy(false)}
 function submit(e:FormEvent){e.preventDefault();void send(draft)}const keyDown=(e:KeyboardEvent<HTMLTextAreaElement>)=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();e.currentTarget.form?.requestSubmit()}};
 return <XpyStageOneFrame adapter={BABY_EXPERIENCE} embedded={embedded}><XpyHeader title="Bebek arabası" description="Tek seferde bir soruyla, yalnız doğrulanmış Türkiye ürün bilgilerine dayanarak ilerler."/><XpyTranscript>{entries.map((entry,index)=><div key={index} className="space-y-3">{entry.user&&<XpyUserBubble>{entry.user}</XpyUserBubble>}<XpyAssistantBubble>{entry.outcome.message}</XpyAssistantBubble>{entry.outcome.choices&&<div className="flex flex-wrap gap-2">{entry.outcome.choices.map(c=><button key={c.value} type="button" disabled={busy} onClick={()=>void send(c.label)} className="rounded-full border border-stone-300 bg-white px-4 py-2 text-sm text-stone-800 hover:bg-stone-50">{c.label}</button>)}</div>}{entry.outcome.candidates&&<XpyDecisionCard card={projectStrollerSet(entry.outcome.candidates)} action={<div className="flex flex-wrap gap-2">{entry.outcome.candidates.map(c=><button key={c.id} type="button" disabled={busy} onClick={()=>void send(c.label)} className="min-h-11 rounded-xl border border-amber-700 px-3 py-2 text-sm font-semibold">{c.label} modelini seç</button>)}</div>}/>} {entry.outcome.card&&<XpyDecisionCard card={STROLLER_STAGE_ONE_PRESENTATION.project(entry.outcome.card)}/>}</div>)}</XpyTranscript><XpyComposer id="baby-message" onSubmit={submit} value={draft} onChange={setDraft} onKeyDown={keyDown} placeholder="İhtiyacınızı veya sorunuzu yazın…" disabled={busy}/></XpyStageOneFrame>}
