import { createHash } from "node:crypto";
import { getOpenAIClient } from "@/lib/openai";
import { createCarsDecisionV2ProductionComposition } from "../composition/production.server";
import { InMemoryV2ConversationStore } from "../orchestrator/store";
import { runCarsDecisionTurnV2 } from "../orchestrator/runCarsDecisionTurnV2";
import { createOpenAIStructuredProviderTransport, readCarsDecisionV2ProviderConfig } from "../provider/openaiTransport.server";
import { createStructuredProviderAdapters } from "../provider/structuredProvider";
import { parseCarsDecisionV2Flags } from "./flags";
import { runCarsDecisionV2Shadow, type CarsDecisionV2ShadowRunner, type ShadowTelemetry } from "./shadow";
let testRunner: CarsDecisionV2ShadowRunner | undefined; let telemetrySink: ((value: ShadowTelemetry) => void) | undefined;
const shadowSessions = new Map<string, { store: InMemoryV2ConversationStore; composition: ReturnType<typeof createCarsDecisionV2ProductionComposition> }>();
export function configureCarsDecisionV2ShadowForTests(value?: CarsDecisionV2ShadowRunner, sink?: (value: ShadowTelemetry) => void) { testRunner = value; telemetrySink = sink; }
function productionRunner(): CarsDecisionV2ShadowRunner { return { async evaluate(raw, signal) { const request = raw as { conversationId?: string; messages?: readonly { id?: string; role?: string; content?: string }[] }; const latest = [...(request.messages ?? [])].reverse().find((message) => message.role === "user"); if (!request.conversationId || !latest?.id || !latest.content) throw new Error("SHADOW_INPUT_INVALID"); const conversationHash = createHash("sha256").update(request.conversationId).digest("hex").slice(0, 20); const shadowConversationId = `shadow_${conversationHash}`; let session = shadowSessions.get(conversationHash); if (!session) { const config = readCarsDecisionV2ProviderConfig(process.env); const adapters = createStructuredProviderAdapters({ transport: createOpenAIStructuredProviderTransport(getOpenAIClient(), config), timeoutMs: config.timeoutMs, signal }); const store = new InMemoryV2ConversationStore(); session = { store, composition: createCarsDecisionV2ProductionComposition({ store, interpreter: adapters.interpreter, realizer: adapters.realizer, shadow: true }) }; if (shadowSessions.size >= 256) shadowSessions.delete(shadowSessions.keys().next().value!); shadowSessions.set(conversationHash, session); } const prior = await session.store.load(shadowConversationId); const output = await runCarsDecisionTurnV2({ conversationId: shadowConversationId, messageId: latest.id, idempotencyKey: `shadow:${latest.id}`, expectedConversationRevision: prior?.revision ?? 0, userMessage: latest.content, requestTime: new Date().toISOString(), signal }, session.composition); return { conversationHash, turnRevision: output.revision, interpretationResult: "SUCCESS", offerCreated: Boolean(output.offer), actionClass: output.state, availability: output.recoverableStatus ?? "READY", candidateBucketSummary: [], questionSemanticKey: output.options[0]?.id, personaActivated: false, personaAffectedRanking: false, dailyLifeMappingClasses: [], realizationResult: output.recoverableStatus ? "NOT_RUN" : "VALIDATED", latencyClass: "NORMAL" }; } }; }
export async function evaluateCarsDecisionV2ShadowAfterResponse(requestData: unknown): Promise<void> { const flags = parseCarsDecisionV2Flags(process.env); if (!flags.shadow) return; await runCarsDecisionV2Shadow({ flags, requestData, runner: testRunner ?? productionRunner(), emit: telemetrySink ?? (() => undefined) }); }
