import {describe,expect,it} from "vitest";
import {createFileSystemAppliancesArtifactRepository,loadActiveAppliancesAuthority} from "../authority/loader.server";
import {loadActiveDryerAuthority} from "../dryer/authority.server";
import {loadActiveRefrigeratorAuthority} from "../refrigerator/authority.server";
import {BOUNDED_TYPES,loadActiveBoundedAuthority} from "../bounded/authority.server";
import {enterAppliancesDepartment} from "../entry.server";
import {activeBrandConstraint,brandRelaxationOutcome,constrainPackAuthority,mutateBrandConstraint} from ".";

describe("all-category brand hard constraint",()=>{
 it("filters exact identities in every Appliances category and never scores",async()=>{const repository=createFileSystemAppliancesArtifactRepository(process.cwd()),types=["WASHING_MACHINE","DRYER","REFRIGERATOR",...BOUNDED_TYPES] as const;for(const productType of types){const entered=await enterAppliancesDepartment({repository,productType,conversationId:crypto.randomUUID()});if(entered.status!=="READY")throw new Error(entered.status);if(productType==="WASHING_MACHINE"){const loaded=await loadActiveAppliancesAuthority({repository});if(loaded.status!=="READY")throw new Error(loaded.reason);const products=(loaded.snapshot.catalog as {products:readonly {brandId:string}[]}).products,brand=products[0]!.brandId;const state=mutateBrandConstraint(entered.state,{kind:"SET",brand:{id:brand.toLocaleLowerCase("tr-TR"),label:brand},active:undefined},{messageId:"m",message:`${brand} marka`,revision:1,createdAt:new Date(0).toISOString()});expect(products.filter(p=>p.brandId.toLocaleLowerCase("tr-TR")===activeBrandConstraint(state)!.brandId).every(p=>p.brandId===brand)).toBe(true);continue;}const loaded=productType==="DRYER"?await loadActiveDryerAuthority(process.cwd()):productType==="REFRIGERATOR"?await loadActiveRefrigeratorAuthority(process.cwd()):await loadActiveBoundedAuthority(process.cwd(),productType);if(loaded.status!=="READY")throw new Error(loaded.reason);const brand=loaded.snapshot.pack.products[0]!.brand,state=mutateBrandConstraint(entered.state,{kind:"SET",brand:{id:brand.toLocaleLowerCase("tr-TR"),label:brand},active:undefined},{messageId:"m",message:`${brand} marka`,revision:1,createdAt:new Date(0).toISOString()}),constrained=constrainPackAuthority(loaded.snapshot,state);expect(constrained.pack.products.length).toBeGreaterThan(0);expect(constrained.pack.products.every(p=>p.brand===brand)).toBe(true);expect(activeBrandConstraint(state)).toMatchObject({decisionUse:"HARD_FILTER"});}});
 it("requires explicit relaxation when an active brand has no eligible candidate",async()=>{const repository=createFileSystemAppliancesArtifactRepository(process.cwd()),entered=await enterAppliancesDepartment({repository,productType:"DRYER"});if(entered.status!=="READY")throw new Error(entered.status);const state=mutateBrandConstraint(entered.state,{kind:"SET",brand:{id:"bosch",label:"Bosch"},active:undefined},{messageId:"m",message:"Bosch marka",revision:1,createdAt:new Date(0).toISOString()}),result=brandRelaxationOutcome(state);expect(result).toMatchObject({outcome:{kind:"CLARIFY",questionKey:"appliances.brand.relaxation"},state:{pendingBrandRelaxation:{brandId:"bosch"}}});});
});
