import { randomUUID } from "node:crypto";
import type { AppliancesConversationState } from "../contracts";
import { BRAND_POLICY_ID } from "./policy.server";

export type CatalogBrand={readonly id:string;readonly label:string};
const escapeRegex=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/gu,"\\$&");
export function activeBrandConstraint(state:AppliancesConversationState){const superseded=new Set((state.brandConstraintEvents??[]).flatMap(e=>e.supersedesEventId?[e.supersedesEventId]:[]));return (state.brandConstraintEvents??[]).findLast(e=>e.status==="ACTIVE"&&!superseded.has(e.eventId));}
export function parseBrandConstraintMessage(message:string,brands:readonly CatalogBrand[],state:AppliancesConversationState){
 const normalized=message.toLocaleLowerCase("tr-TR"),active=activeBrandConstraint(state);
 if(state.pendingBrandRelaxation&&/^(?:evet|olur|tamam|kaldır|gevşet)[.! ]*$/iu.test(message.trim()))return{kind:"RELAX" as const,active};
 if(/marka (?:önemli değil|fark etmez)|marka tercihi(?:mi)? (?:kaldır|unut)|marka kısıt(?:ını|ı) kaldır/iu.test(message))return active?{kind:"CLEAR" as const,active}:{kind:"NONE" as const};
 const match=brands.find(b=>new RegExp(`(?:^|[^\\p{L}\\p{N}])${escapeRegex(b.label.toLocaleLowerCase("tr-TR"))}(?:$|[^\\p{L}\\p{N}])`,"iu").test(normalized));if(match)return{kind:"SET" as const,brand:match,active};
 if(/(?:marka|markalı)/iu.test(message)){const token=message.match(/(?:^|\s)([\p{L}\p{N}-]+)\s+(?:marka|markalı)/iu)?.[1];if(token&&!brands.some(b=>b.label.toLocaleLowerCase("tr-TR")===token.toLocaleLowerCase("tr-TR")))return{kind:"UNKNOWN" as const,label:token};}
 return{kind:"NONE" as const};
}
export function mutateBrandConstraint(state:AppliancesConversationState,parsed:Exclude<ReturnType<typeof parseBrandConstraintMessage>,{kind:"NONE"}|{kind:"UNKNOWN"}>,input:{messageId:string;message:string;revision:number;createdAt:string}){const events=[...(state.brandConstraintEvents??[])],active=parsed.active;if(active)events.push({eventId:randomUUID(),brandId:active.brandId,brandLabel:active.brandLabel,sourceMessageId:input.messageId,sourceText:input.message,createdRevision:input.revision,createdAt:input.createdAt,status:parsed.kind==="RELAX"?"RELAXED" as const:parsed.kind==="CLEAR"?"CLEARED" as const:"SUPERSEDED" as const,supersedesEventId:active.eventId,authority:"USER_EXPLICIT" as const,decisionUse:"NONE" as const,policyId:active.policyId,policyDigest:active.policyDigest});if(parsed.kind==="SET")events.push({eventId:randomUUID(),brandId:parsed.brand.id,brandLabel:parsed.brand.label,sourceMessageId:input.messageId,sourceText:input.message,createdRevision:input.revision,createdAt:input.createdAt,status:"ACTIVE" as const,authority:"USER_EXPLICIT" as const,decisionUse:"HARD_FILTER" as const,policyId:BRAND_POLICY_ID,policyDigest:state.pinnedBrandPolicyDigest!});return{...state,brandConstraintEvents:events,pendingBrandRelaxation:undefined,decisionRecord:undefined,currentDecisionFingerprint:undefined};}
export function filterByActiveBrand<T>(state:AppliancesConversationState,products:readonly T[],brandOf:(product:T)=>string){const active=activeBrandConstraint(state);return active?products.filter(p=>brandOf(p).toLocaleLowerCase("tr-TR")===active.brandId):[...products];}
export function constrainPackAuthority<T extends {readonly pack:{readonly products:readonly P[]}},P extends {readonly brand:string}>(authority:T,state:AppliancesConversationState):T{return{...authority,pack:{...authority.pack,products:filterByActiveBrand(state,authority.pack.products,p=>p.brand)}} as T;}
export function brandRelaxationOutcome(state:AppliancesConversationState){const active=activeBrandConstraint(state);if(!active)return null;return{state:{...state,pendingBrandRelaxation:{brandEventId:active.eventId,brandId:active.brandId,questionKey:"appliances.brand.relaxation" as const}},outcome:{kind:"CLARIFY" as const,questionKey:"appliances.brand.relaxation",message:`${active.brandLabel} marka kısıtıyla diğer zorunlu koşulları birlikte karşılayan bir ürün kalmadı. Marka kısıtını açıkça kaldırmamı ister misin?`}};} 
