import { describe, expect, it } from "vitest";
import { V2_DECISION_FIELD_REGISTRY_V1 } from "../filter/registry";
import { createConversationEventsFromInterpretation } from "../orchestrator/eventFactory";
import { interpretUserMessage } from "./service";
import { assessInterpretationSemanticCompleteness } from "./semanticCompleteness";
import type { AuthoritativeSemanticPlan, InterpretationResult } from "./types";

const raw = (acts: InterpretationResult["acts"], overrides: Partial<InterpretationResult> = {}): InterpretationResult => ({ schemaVersion: 1, messageId: "m", acts, directAnswerRequests: [], constraintMutations: [], budgetMutations: [], modelReferences: [], personaMutations: [], corrections: [], ambiguities: [], ...overrides });
const plan = (result: InterpretationResult, text: string, activeFieldIds: readonly string[] = []) => interpretUserMessage({ model: { interpret: async () => result }, messageId: "m", userText: text, fieldRegistry: V2_DECISION_FIELD_REGISTRY_V1, activeFieldIds });

describe("provider advisory semantic authority boundary", () => {
  it("downgrades provider-hard hybrid preference and excludes BEV", async () => { const value = await plan(raw(["HARD_REQUIREMENT"], { constraintMutations: [{ operation: "ADD", fieldId: "fuelType", normalizedValue: { operator: "ONE_OF", value: ["MHEV", "HEV", "PHEV", "BEV"] }, explicitness: "EXPLICIT_REQUIREMENT", confidence: 1, sourceSpan: "Hibrit istiyorum" }] }), "Hibrit istiyorum"); expect(value.acceptedConstraintMutations[0]).toMatchObject({ deterministicDecisionUse: "STRONG_OR_SOFT_RANK", normalizedValue: { operator: "ONE_OF", value: ["MHEV", "HEV", "PHEV"] } }); expect(value.policyTrace).toContainEqual(expect.objectContaining({ code: "PROVIDER_STRENGTH_DOWNGRADED_BY_POLICY" })); });
  it("enforces explicit hard language even when provider reports soft", async () => { const value = await plan(raw(["PREFERENCE_STATEMENT"]), "Kesinlikle hibrit olmalı"); expect(value.acceptedConstraintMutations[0]?.deterministicDecisionUse).toBe("HARD_CANDIDATE"); expect(value.policyTrace).toContainEqual(expect.objectContaining({ code: "EXPLICIT_HARD_LANGUAGE_ENFORCED" })); });
  it.each(["Hibrit tercih ederim", "Hibrit olabilir"])("keeps %s soft", async (text) => expect((await plan(raw(["HARD_REQUIREMENT"]), text)).acceptedConstraintMutations[0]?.deterministicDecisionUse).toBe("STRONG_OR_SOFT_RANK"));
  it("makes outside-hybrid and BEV negation explicit hard constraints", async () => { expect((await plan(raw(["PREFERENCE_STATEMENT"]), "Hibrit dışında istemiyorum")).acceptedConstraintMutations[0]?.deterministicDecisionUse).toBe("HARD_CANDIDATE"); expect((await plan(raw(["PREFERENCE_STATEMENT"]), "Elektrikli istemiyorum")).acceptedConstraintMutations[0]).toMatchObject({ deterministicDecisionUse: "HARD_CANDIDATE", normalizedValue: { operator: "EXCLUDES", value: ["BEV"] } }); });
  it("clears an active fuel preference when fuel does not matter", async () => expect((await plan(raw(["HARD_REQUIREMENT"]), "Yakıt fark etmez", ["fuelType"])).acceptedConstraintMutations[0]).toMatchObject({ operation: "CLEAR", deterministicDecisionUse: "STRONG_OR_SOFT_RANK" }));
  it("does not let provider hard-ceiling authority turn cash into a ceiling", async () => { const value = await plan(raw(["HARD_REQUIREMENT"], { budgetMutations: [{ operation: "SET", field: "MAXIMUM_HARD_CEILING", value: { amount: 2_000_000, currency: "TRY" }, sourceSpan: "2 milyon nakitim var" }] }), "2 milyon nakitim var"); expect(value.acceptedBudgetMutations.map((item) => item.field)).toEqual(["AVAILABLE_CASH", "BUDGET_UNKNOWN"]); expect(value.acceptedBudgetMutations.map((item) => item.field)).not.toContain("MAXIMUM_HARD_CEILING"); });
  it("creates a hard ceiling from explicit language despite provider softness", async () => expect((await plan(raw(["PREFERENCE_STATEMENT"]), "5 milyonun üzerine çıkamam")).acceptedBudgetMutations).toContainEqual(expect.objectContaining({ field: "MAXIMUM_HARD_CEILING" })));
  it("keeps persona soft and enforces provider-soft cargo/rear-seat hard semantics", async () => { const persona = await plan(raw(["HARD_REQUIREMENT"]), "Premium ve şık istiyorum"); expect(persona.acceptedPersonaMutations).toHaveLength(1); expect(persona.acceptedConstraintMutations).toEqual([]); const cargo = await plan(raw(["PREFERENCE_STATEMENT"]), "Kapalı yük alanı şart, arka koltuk istemiyorum"); expect(cargo.acceptedConstraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "usageArchitecture", deterministicDecisionUse: "HARD_CANDIDATE" }), expect.objectContaining({ fieldId: "rearSeatPreference", deterministicDecisionUse: "HARD_CANDIDATE" })])); });
  it("requires the nominal authoritative plan at the event boundary", async () => { const authoritative = await plan(raw(["HARD_REQUIREMENT"]), "Hibrit istiyorum"); const events = createConversationEventsFromInterpretation({ turn: { conversationId: "c", messageId: "m", idempotencyKey: "k", expectedConversationRevision: 0, userMessage: "Hibrit istiyorum", requestTime: "2026-08-19T00:00:00.000Z" }, interpretation: authoritative, catalog: {} as never }); expect(events.find((event) => event.eventType === "CONSTRAINT")).toMatchObject({ eventType: "CONSTRAINT", kind: "SOFT_PREFERENCE" }); expect(() => createConversationEventsFromInterpretation({ turn: {} as never, interpretation: raw([]) as never, catalog: {} as never })).toThrow("AUTHORITATIVE_SEMANTIC_PLAN_REQUIRED"); });
  it("fails completeness for an authoritative hard or soft plan with its mutation removed", async () => { const hard = await plan(raw(["PREFERENCE_STATEMENT"]), "Kesinlikle hibrit olmalı"); expect(assessInterpretationSemanticCompleteness({ interpretation: { ...hard, acceptedConstraintMutations: [] } as AuthoritativeSemanticPlan, userText: "Kesinlikle hibrit olmalı" }).codes).toContain("HARD_REQUIREMENT_MUTATION_MISSING"); const soft = await plan(raw(["HARD_REQUIREMENT"]), "Hibrit istiyorum"); expect(assessInterpretationSemanticCompleteness({ interpretation: { ...soft, acceptedConstraintMutations: [] } as AuthoritativeSemanticPlan, userText: "Hibrit istiyorum" }).codes).toContain("PREFERENCE_MUTATION_MISSING"); });
  it("reconciles model lookup, consent, social humor and abuse from deterministic context", async () => { expect((await plan(raw(["RECOMMENDATION_REQUEST"]), "Micra var mı?")).result.modelReferences).toHaveLength(1); expect((await plan(raw(["PREFERENCE_STATEMENT"]), "Evet")).result.acts).toContain("OFFER_ACCEPTANCE"); const joke = await plan(raw(["OFF_TOPIC"], { offTopicSignal: { detected: true } }), "Şaka yaptım 😄"); expect(joke.result.acts).toContain("SOCIAL_MESSAGE"); expect(joke.result.acts).not.toContain("OFF_TOPIC"); const abuse = await plan(raw(["SOCIAL_MESSAGE"]), "Salak mısın, hibrit dedim"); expect(abuse.result.acts).toContain("ABUSE"); expect(abuse.acceptedConstraintMutations).toHaveLength(1); });
  it("marks explicit budget information known and does not derive persona from approximate language", async () => { const value = await plan(raw(["HARD_REQUIREMENT"]), "5 milyon üstüne çıkmam; yaklaşık bütçe değerlendirmesi yap"); expect(value.acceptedBudgetMutations).toEqual(expect.arrayContaining([expect.objectContaining({ field: "MAXIMUM_HARD_CEILING" }), expect.objectContaining({ field: "BUDGET_UNKNOWN", value: false })])); expect(value.acceptedPersonaMutations).toEqual([]); });
});
