import type { DeterministicInterpretationEvaluationCase } from "./deterministicEvaluation";

const decisionNeutral = ["constraint:ADD:fuelType:{\"operator\":\"EQUALS\",\"value\":\"BEV\"}", "act:PREFERENCE_STATEMENT"] as const;

export const DETERMINISTIC_INTERPRETATION_EVALUATION_CORPUS: readonly DeterministicInterpretationEvaluationCase[] = Object.freeze([
  ...["pickup", "pick up", "pick-up", "pikap"].map((userText, index) => ({ id: `body-pickup-${index + 1}`, category: "BODY" as const, group: "pickup-alias", userText, openMaterialQuestionField: "bodyStyle", requiredSignals: ["constraint:ADD:bodyStyle:{\"operator\":\"EQUALS\",\"value\":\"Pickup\"}"] })),
  ...["3 milyon", "3 MİLYON", "3 milyon TL", "3.000.000 TL"].map((userText, index) => ({ id: `budget-3m-${index + 1}`, category: "BUDGET" as const, group: "budget-3m", userText, openMaterialQuestionField: "budget", requiredSignals: ["budget:SET:PREFERRED_BUDGET:{\"amount\":3000000,\"currency\":\"TRY\"}"] })),
  ...["2-3 milyon", "2 ile 3 milyon arası"].map((userText, index) => ({ id: `budget-range-${index + 1}`, category: "BUDGET" as const, group: "budget-range", userText, requiredSignals: ["budget:SET:MINIMUM_BUDGET:{\"amount\":2000000,\"currency\":\"TRY\"}", "budget:SET:MAXIMUM_HARD_CEILING:{\"amount\":3000000,\"currency\":\"TRY\"}"] })),
  ...["Fark etmez", "Önemli değil.", "Fikrim yok!"].map((userText, index) => ({ id: `decline-fuel-${index + 1}`, category: "QUESTION_BINDING" as const, group: "decline-open-field", userText, openMaterialQuestionField: "fuelType", requiredSignals: ["constraint:DECLINE:fuelType:null"], forbiddenSignals: ["constraint:DECLINE:bodyStyle:null", "constraint:DECLINE:transmission:null"] })),
  ...["4x4 arazi aracı bakıyorum", "Arazi aracı bakıyorum, 4X4 olsun.", "Ciddi arazi için dört çeker araç istiyorum"].map((userText, index) => ({ id: `off-road-awd-${index + 1}`, category: "USAGE" as const, group: "off-road-awd", userText, requiredSignals: ["constraint:ADD:drivenWheels:{\"operator\":\"EQUALS\",\"value\":\"AWD\"}", "constraint:ADD:usageScenario:\"SERIOUS_OFF_ROAD\""] })),
  { id: "technical-neutral-kw", category: "KNOWLEDGE_NEUTRALITY", group: "technical-neutrality", userText: "Elektrikli araçta kW nedir?", requiredSignals: ["act:TECHNICAL_EXPLANATION_REQUEST", "answer:TECHNICAL_EXPLANATION"], forbiddenSignals: decisionNeutral },
  { id: "technical-neutral-charge", category: "KNOWLEDGE_NEUTRALITY", group: "technical-neutrality", userText: "Elektrikli araçların şarjı nasıl çalışır?", requiredSignals: ["act:TECHNICAL_EXPLANATION_REQUEST", "answer:TECHNICAL_EXPLANATION"], forbiddenSignals: decisionNeutral },
  { id: "seat-exact-9", category: "CAPACITY", group: "seat-9", userText: "9 koltuk kapasitesine sahip olsun", requiredSignals: ["constraint:ADD:seats:{\"operator\":\"EQUALS\",\"unit\":\"COUNT\",\"value\":9}"] },
  { id: "seat-min-14", category: "CAPACITY", group: "seat-minimum", userText: "En az 14 koltuk olsun", requiredSignals: ["constraint:ADD:seats:{\"operator\":\"MINIMUM\",\"unit\":\"COUNT\",\"value\":14}"] },
  { id: "transmission-auto", category: "TRANSMISSION", group: "transmission", userText: "Otomatik olsun", openMaterialQuestionField: "transmission", requiredSignals: ["constraint:ADD:transmission:{\"operator\":\"EQUALS\",\"value\":\"AUTOMATIC\"}"] },
  ...["Clio mu Civic mi?", "Clio mu Civic mi kararsızım"].map((userText, index) => ({ id: `model-compare-${index + 1}`, category: "MODEL_SCOPE" as const, group: "model-comparison", userText, requiredSignals: ["act:MODEL_COMPARISON_REQUEST", "answer:MODEL_COMPARISON", "model:COMPARISON_SCOPE::Civic", "model:COMPARISON_SCOPE::Clio"] })),
  ...["Göster bakalım", "Seçenekleri göster", "Hadi görelim"].map((userText, index) => ({ id: `consent-${index + 1}`, category: "CONSENT" as const, group: "offer-consent", userText, requiredSignals: ["act:OFFER_ACCEPTANCE"], forbiddenSignals: ["act:PREFERENCE_STATEMENT", "act:HARD_REQUIREMENT"] })),
  ...["Araba almak istiyorum ama nereden başlayacağımı bilemiyorum.", "Hangi arabayı seçsem bilmiyorum, yardım eder misin?"].map((userText, index) => ({ id: `discovery-${index + 1}`, category: "DISCOVERY" as const, group: "open-discovery", userText, requiredSignals: ["act:VEHICLE_INTENT", "act:RECOMMENDATION_REQUEST", "answer:RECOMMENDATION_REQUEST"] })),
]);
