import type { DecisionFieldRegistry } from "../filter/types";
import type { InterpretationDiagnostic, InterpretationResult, ProposedBudgetMutation, ProposedPersonaMutation, ValidatedConstraintMutation, ValidatedInterpretation } from "./types";

const HARD_LANGUAGE = /(en az|en fazla|kesin(?:likle)?|şart|olmazsa olmaz|istemiyorum|olmasın|olmalı|zorunda|mutlaka|max(?:imum)?|maksimum|tavan|üzerine çıkmam|üzerine çıkamam|üstüne çıkmam|üstüne çıkamam|dedim|değil|gerekiyor|gerekli|sadece|yalnızca)|(?:\d+|dört|beş|altı|yedi|sekiz|dokuz)\s+(?:kişilik|koltuk)(?:\s+kapasitesine\s+sahip)?\s+olsun|(?:kapalı yük alanı|kapalı kasa|panel ?van|caddy tarzı).*(?:istiyorum|olsun)/iu;
const PERSONA_LANGUAGE = /(premium|şık|tasarım|sportif|performans|çevik|sürüş hissi|aile|konfor|rahat|yormayan|yormasın|ağırbaşlı|prestijli|teknolojik|fütüristik|maceracı|macera\s+ruh(?:u|lu)|arazi|off[ -]?road|yük|eşya|ticari|ekonomik|düşük maliyet|az yak|sade|minimalist|dikkat çekici|gösterişsiz|dinamik|erkeksi|ikinci el|değer kayb|değerini koru|etkile)/iu;
export function normalizeFuelInterpretation(sourceText: string): { readonly operator: "EQUALS" | "ONE_OF"; readonly value: string | readonly string[] } | null {
  const value = sourceText.toLocaleLowerCase("tr-TR"); const fuels = new Set<string>();
  const specificHybrid = /plug[ -]?in|şarjlı h[ıi]bri[td]|mild|hafif h[ıi]bri[td]|tam h[ıi]bri[td]|şarjsız h[ıi]bri[td]/u.test(value);
  if (/plug[ -]?in|şarjlı h[ıi]bri[td]/u.test(value)) fuels.add("PHEV");
  if (/mild|hafif h[ıi]bri[td]/u.test(value)) fuels.add("MHEV");
  if (/tam h[ıi]bri[td]|şarjsız h[ıi]bri[td]/u.test(value)) fuels.add("HEV");
  if (/h[ıi]bri[td]/u.test(value) && !specificHybrid) ["MHEV", "HEV", "PHEV"].forEach((fuel) => fuels.add(fuel));
  if (/elektrik|elketrik/u.test(value)) fuels.add("BEV"); if (/benzin/u.test(value)) fuels.add("GASOLINE"); if (/dizel|mazot/u.test(value)) fuels.add("DIESEL"); if (/\blpg\b/u.test(value)) fuels.add("LPG"); if (/hidrojen/u.test(value)) fuels.add("HYDROGEN");
  const normalized = [...fuels]; return normalized.length === 0 ? null : normalized.length === 1 ? { operator: "EQUALS", value: normalized[0]! } : { operator: "ONE_OF", value: normalized };
}
function moneyValid(value: unknown): boolean { return typeof value === "object" && value !== null && (value as { currency?: unknown }).currency === "TRY" && typeof (value as { amount?: unknown }).amount === "number" && Number.isFinite((value as { amount: number }).amount) && (value as { amount: number }).amount > 0; }
export function validateInterpretationPolicy(input: { readonly result: InterpretationResult; readonly userText: string; readonly fieldRegistry: DecisionFieldRegistry; readonly activeFieldIds: readonly string[]; readonly openMaterialQuestionField?: string; readonly dailyLifeMappingIds: readonly string[]; readonly revealedCandidateReferences: readonly string[] }): ValidatedInterpretation {
  const diagnostics: InterpretationDiagnostic[] = []; const hardFields = new Set(input.fieldRegistry.fields.filter((field) => field.decisionUse === "HARD_FILTER_ALLOWED").map((field) => field.fieldId)); const active = new Set(input.activeFieldIds); const mappings = new Set(input.dailyLifeMappingIds); const accepted: ValidatedConstraintMutation[] = [];
  for (const mutation of input.result.constraintMutations) { if (mutation.operation === "CORRECT" && mutation.supersedesFieldId && !active.has(mutation.supersedesFieldId)) { diagnostics.push({ code: "SUPERSESSION_TARGET_MISSING", reference: mutation.fieldId }); continue; } let use: ValidatedConstraintMutation["deterministicDecisionUse"] = mutation.explicitness === "GUIDED_APPROXIMATION" ? "GUIDED_ONLY" : mutation.explicitness === "ILLUSTRATIVE" ? "ILLUSTRATIVE_ONLY" : "STRONG_OR_SOFT_RANK"; if (mutation.explicitness === "EXPLICIT_REQUIREMENT") { const authoritativeQuestionAnswer = input.openMaterialQuestionField === mutation.fieldId && hardFields.has(mutation.fieldId); const authoritativeAvailabilityScope = /(?:var mı|mevcut mu)[?\s]*$/iu.test(input.userText) && hardFields.has(mutation.fieldId); if (!HARD_LANGUAGE.test(mutation.sourceSpan) && !authoritativeQuestionAnswer && !authoritativeAvailabilityScope) diagnostics.push({ code: "HARD_LANGUAGE_NOT_EXPLICIT", reference: mutation.fieldId }); else if (!hardFields.has(mutation.fieldId) && !["usageArchitecture", "rearSeatPreference"].includes(mutation.fieldId)) diagnostics.push({ code: "FIELD_NOT_HARD_FILTERABLE", reference: mutation.fieldId }); else use = "HARD_CANDIDATE"; } if (mutation.fieldId === "dailyLife") { const mappingId = typeof mutation.normalizedValue === "object" && mutation.normalizedValue !== null && !Array.isArray(mutation.normalizedValue) ? (mutation.normalizedValue as { mappingId?: unknown }).mappingId : undefined; if (typeof mappingId !== "string" || !mappings.has(mappingId)) { diagnostics.push({ code: "DAILY_LIFE_MAPPING_UNAUTHORIZED", reference: String(mappingId) }); continue; } use = mutation.explicitness === "ILLUSTRATIVE" ? "ILLUSTRATIVE_ONLY" : "GUIDED_ONLY"; } accepted.push({ ...mutation, deterministicDecisionUse: use }); }
  const budgets: ProposedBudgetMutation[] = []; for (const mutation of input.result.budgetMutations) { const source = mutation.sourceSpan.toLocaleLowerCase("tr-TR"); let valid = true; const setsValue = mutation.operation === "SET" || mutation.operation === "CORRECT"; if (["AVAILABLE_CASH", "MINIMUM_BUDGET", "PREFERRED_BUDGET", "MAXIMUM_HARD_CEILING"].includes(mutation.field) && setsValue) valid = moneyValid(mutation.value); if (mutation.field === "FINANCE_FLEXIBILITY" && setsValue) valid = ["NONE", "POSSIBLE", "YES", "UNKNOWN"].includes(String(mutation.value)); if (["UNRESOLVED_FINANCED_CEILING", "BUDGET_UNKNOWN"].includes(mutation.field) && setsValue) valid = typeof mutation.value === "boolean"; const explicitRange = /\d+(?:[.,]\d+)?\s*(?:milyon|mn|bin)?\s*(?:[-–]|ile)\s*\d+(?:[.,]\d+)?\s*(?:milyon|mn|bin)(?:\s+arası)?/u.test(source); if (mutation.field === "MAXIMUM_HARD_CEILING" && setsValue && !HARD_LANGUAGE.test(source) && !explicitRange) valid = false; if (mutation.operation === "EXCLUDE_FROM_DECISION" && !/önemli değil|fark etmez|bütçe.*(?:hariç|dahil etme|katma|uygulama)/u.test(source)) valid = false; if (!valid) diagnostics.push({ code: "INVALID_BUDGET_SEMANTICS", reference: mutation.field }); else budgets.push(mutation); }
  const acceptedBudgets = budgets.some((mutation) => mutation.operation === "EXCLUDE_FROM_DECISION")
    ? budgets.filter((mutation) => mutation.operation === "EXCLUDE_FROM_DECISION")
    : budgets;
  const persona: ProposedPersonaMutation[] = []; for (const mutation of input.result.personaMutations) { if (mutation.operation === "ACTIVATE" && (!PERSONA_LANGUAGE.test(mutation.sourceSpan) || mutation.traits.length === 0)) diagnostics.push({ code: "PERSONA_SOURCE_NOT_EXPLICIT" }); else persona.push(mutation); }
  if (input.result.candidateRejection?.scope === "EXACT_REVEALED" && !input.revealedCandidateReferences.includes(input.result.candidateRejection.referenceText)) diagnostics.push({ code: "REJECTION_SCOPE_UNBOUND" });
  return Object.freeze({ result: input.result, acceptedConstraintMutations: Object.freeze(accepted), acceptedBudgetMutations: Object.freeze(acceptedBudgets), acceptedPersonaMutations: Object.freeze(persona), diagnostics: Object.freeze(diagnostics) });
}
