import type { DecisionFieldRegistry } from "../filter/types";
import type { InterpretationDiagnostic, InterpretationResult, ProposedBudgetMutation, ProposedPersonaMutation, ValidatedConstraintMutation, ValidatedInterpretation } from "./types";

const HARD_LANGUAGE = /(en az|en fazla|kesinlikle|şart|olmazsa olmaz|istemiyorum|olmasın|olmalı|zorunda|mutlaka|max(?:imum)?|maksimum|tavan|üzerine çıkmam|üzerine çıkamam|üstüne çıkmam|üstüne çıkamam|dedim|değil|gerekiyor|gerekli)|(?:kapalı yük alanı|kapalı kasa|panel ?van|caddy tarzı).*(?:istiyorum|olsun)/iu;
const PERSONA_LANGUAGE = /(premium|şık|tasarım|sportif|ağırbaşlı|prestijli|teknolojik|fütüristik|maceracı|macera\s+ruh(?:u|lu)|sade|minimalist|dikkat çekici|gösterişsiz|dinamik|erkeksi)/iu;
export function normalizeFuelInterpretation(sourceText: string): { readonly operator: "EQUALS" | "ONE_OF"; readonly value: string | readonly string[] } | null { const value = sourceText.toLocaleLowerCase("tr-TR"); if (/plug[ -]?in|şarjlı hibrit/u.test(value)) return { operator: "EQUALS", value: "PHEV" }; if (/mild|hafif hibrit/u.test(value)) return { operator: "EQUALS", value: "MHEV" }; if (/tam hibrit|şarjsız hibrit/u.test(value)) return { operator: "EQUALS", value: "HEV" }; if (/hibrit/u.test(value)) return { operator: "ONE_OF", value: ["MHEV", "HEV", "PHEV"] }; if (/elektrik/u.test(value)) return { operator: "EQUALS", value: "BEV" }; if (/benzin/u.test(value)) return { operator: "EQUALS", value: "GASOLINE" }; if (/dizel|mazot/u.test(value)) return { operator: "EQUALS", value: "DIESEL" }; if (/\blpg\b/u.test(value)) return { operator: "EQUALS", value: "LPG" }; if (/hidrojen/u.test(value)) return { operator: "EQUALS", value: "HYDROGEN" }; return null; }
function moneyValid(value: unknown): boolean { return typeof value === "object" && value !== null && (value as { currency?: unknown }).currency === "TRY" && typeof (value as { amount?: unknown }).amount === "number" && Number.isFinite((value as { amount: number }).amount) && (value as { amount: number }).amount > 0; }
export function validateInterpretationPolicy(input: { readonly result: InterpretationResult; readonly userText: string; readonly fieldRegistry: DecisionFieldRegistry; readonly activeFieldIds: readonly string[]; readonly dailyLifeMappingIds: readonly string[]; readonly revealedCandidateReferences: readonly string[] }): ValidatedInterpretation {
  const diagnostics: InterpretationDiagnostic[] = []; const hardFields = new Set(input.fieldRegistry.fields.filter((field) => field.decisionUse === "HARD_FILTER_ALLOWED").map((field) => field.fieldId)); const active = new Set(input.activeFieldIds); const mappings = new Set(input.dailyLifeMappingIds); const accepted: ValidatedConstraintMutation[] = [];
  for (const mutation of input.result.constraintMutations) { if (mutation.operation === "CORRECT" && mutation.supersedesFieldId && !active.has(mutation.supersedesFieldId)) { diagnostics.push({ code: "SUPERSESSION_TARGET_MISSING", reference: mutation.fieldId }); continue; } let use: ValidatedConstraintMutation["deterministicDecisionUse"] = mutation.explicitness === "GUIDED_APPROXIMATION" ? "GUIDED_ONLY" : mutation.explicitness === "ILLUSTRATIVE" ? "ILLUSTRATIVE_ONLY" : "STRONG_OR_SOFT_RANK"; if (mutation.explicitness === "EXPLICIT_REQUIREMENT") { if (!HARD_LANGUAGE.test(mutation.sourceSpan)) diagnostics.push({ code: "HARD_LANGUAGE_NOT_EXPLICIT", reference: mutation.fieldId }); else if (!hardFields.has(mutation.fieldId) && !["usageArchitecture", "rearSeatPreference"].includes(mutation.fieldId)) diagnostics.push({ code: "FIELD_NOT_HARD_FILTERABLE", reference: mutation.fieldId }); else use = "HARD_CANDIDATE"; } if (mutation.fieldId === "dailyLife") { const mappingId = typeof mutation.normalizedValue === "object" && mutation.normalizedValue !== null && !Array.isArray(mutation.normalizedValue) ? (mutation.normalizedValue as { mappingId?: unknown }).mappingId : undefined; if (typeof mappingId !== "string" || !mappings.has(mappingId)) { diagnostics.push({ code: "DAILY_LIFE_MAPPING_UNAUTHORIZED", reference: String(mappingId) }); continue; } use = mutation.explicitness === "ILLUSTRATIVE" ? "ILLUSTRATIVE_ONLY" : "GUIDED_ONLY"; } accepted.push({ ...mutation, deterministicDecisionUse: use }); }
  const budgets: ProposedBudgetMutation[] = []; for (const mutation of input.result.budgetMutations) { const source = mutation.sourceSpan.toLocaleLowerCase("tr-TR"); let valid = true; const setsValue = mutation.operation === "SET" || mutation.operation === "CORRECT"; if (["AVAILABLE_CASH", "PREFERRED_BUDGET", "MAXIMUM_HARD_CEILING"].includes(mutation.field) && setsValue) valid = moneyValid(mutation.value); if (mutation.field === "FINANCE_FLEXIBILITY" && setsValue) valid = ["NONE", "POSSIBLE", "YES", "UNKNOWN"].includes(String(mutation.value)); if (["UNRESOLVED_FINANCED_CEILING", "BUDGET_UNKNOWN"].includes(mutation.field) && setsValue) valid = typeof mutation.value === "boolean"; if (mutation.field === "MAXIMUM_HARD_CEILING" && setsValue && !HARD_LANGUAGE.test(source)) valid = false; if (mutation.operation === "EXCLUDE_FROM_DECISION" && !/önemli değil|fark etmez|bütçe.*hariç/u.test(source)) valid = false; if (!valid) diagnostics.push({ code: "INVALID_BUDGET_SEMANTICS", reference: mutation.field }); else budgets.push(mutation); }
  const persona: ProposedPersonaMutation[] = []; for (const mutation of input.result.personaMutations) { if (mutation.operation === "ACTIVATE" && (!PERSONA_LANGUAGE.test(mutation.sourceSpan) || mutation.traits.length === 0)) diagnostics.push({ code: "PERSONA_SOURCE_NOT_EXPLICIT" }); else persona.push(mutation); }
  if (input.result.candidateRejection?.scope === "EXACT_REVEALED" && !input.revealedCandidateReferences.includes(input.result.candidateRejection.referenceText)) diagnostics.push({ code: "REJECTION_SCOPE_UNBOUND" });
  return Object.freeze({ result: input.result, acceptedConstraintMutations: Object.freeze(accepted), acceptedBudgetMutations: Object.freeze(budgets), acceptedPersonaMutations: Object.freeze(persona), diagnostics: Object.freeze(diagnostics) });
}
