import { describe, expect, it } from "vitest";
import type { InterpretationResult } from "./types";
import { enforceInterpretationSemanticCompleteness } from "./semanticCompleteness";

const empty = (messageId = "m"): InterpretationResult => ({ schemaVersion: 1, messageId, acts: [], directAnswerRequests: [], constraintMutations: [], budgetMutations: [], modelReferences: [], personaMutations: [], corrections: [], ambiguities: [] });

describe("semantic completeness enforcement", () => {
  it("does not create constraints for a greeting", () => expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Merhaba", activeFieldIds: [] }).constraintMutations).toEqual([]));
  it("maps hybrid to the closed hybrid family without BEV", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Hibrit tercih ederim", activeFieldIds: [] }); expect(result.constraintMutations[0]?.normalizedValue).toEqual({ operator: "ONE_OF", value: ["MHEV", "HEV", "PHEV"] }); expect(JSON.stringify(result)).not.toContain("BEV"); });
  it("corrects an active body style and never preserves a contradicted pickup", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Pickup demedim, sedan dedim", activeFieldIds: ["bodyStyle"] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ operation: "CORRECT", fieldId: "bodyStyle", supersedesFieldId: "bodyStyle", normalizedValue: { operator: "EQUALS", value: "Sedan" } })); });
  it("keeps a soft sedan preference soft", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Sedan tercih ederim", activeFieldIds: [] }); expect(result.constraintMutations[0]?.explicitness).toBe("EXPLICIT_PREFERENCE"); });
  it("binds an explicit automatic preference to the controlled transmission field", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Otomatik istiyorum", activeFieldIds: [] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "transmission", explicitness: "EXPLICIT_PREFERENCE", normalizedValue: { operator: "EQUALS", value: "AUTOMATIC" } })); });
  it("projects cargo-first meaning and rear-seat not-needed separately", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Şehir içi dağıtım için kapalı yük alanı istiyorum, arka koltuklara gerek yok.", activeFieldIds: [] }); expect(result.constraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "usageArchitecture", explicitness: "EXPLICIT_REQUIREMENT", normalizedValue: { operator: "EQUALS", value: "ENCLOSED_CARGO" } }), expect.objectContaining({ fieldId: "rearSeatPreference", normalizedValue: "NOT_NEEDED" })])); });
  it("separates cash and financing from a hard ceiling", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "5 milyon nakitim var, üstü için kredi kullanabilirim", activeFieldIds: [] }); expect(result.budgetMutations.map((item) => item.field)).toEqual(expect.arrayContaining(["AVAILABLE_CASH", "FINANCE_FLEXIBILITY", "UNRESOLVED_FINANCED_CEILING"])); expect(result.budgetMutations.some((item) => item.field === "MAXIMUM_HARD_CEILING")).toBe(false); });
  it("creates hard ceiling and budget exclusion only from explicit language", () => { expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "5 milyon üstüne çıkmam", activeFieldIds: [] }).budgetMutations).toContainEqual(expect.objectContaining({ field: "MAXIMUM_HARD_CEILING" })); expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Bütçe önemli değil", activeFieldIds: [] }).budgetMutations).toContainEqual(expect.objectContaining({ operation: "EXCLUDE_FROM_DECISION" })); });
  it("binds a bare amount to the open budget question without making it a hard ceiling", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "3 milyon tl", activeFieldIds: [], openMaterialQuestionField: "budget" }); expect(result.budgetMutations).toEqual(expect.arrayContaining([expect.objectContaining({ field: "PREFERRED_BUDGET", value: { amount: 3_000_000, currency: "TRY" } }), expect.objectContaining({ field: "BUDGET_UNKNOWN", value: false })])); expect(result.budgetMutations.some((item) => item.field === "MAXIMUM_HARD_CEILING")).toBe(false); });
  it("does not interpret a bare amount as budget outside a budget-question context", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "3 milyon tl", activeFieldIds: [] }); expect(result.budgetMutations).toEqual([]); });
  it("activates only safe persona vocabulary and supports deactivation", () => { expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Premium ve şık olsun", activeFieldIds: [] }).personaMutations).toContainEqual(expect.objectContaining({ operation: "ACTIVATE", traits: ["PRESTIGE", "DESIGN"] })); expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Fark etmez", activeFieldIds: [] }).personaMutations).toContainEqual(expect.objectContaining({ operation: "DEACTIVATE" })); });
  it("creates a lookup-only model reference without resolving catalog truth", () => expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Micra var mı?", activeFieldIds: [] }).modelReferences).toEqual([expect.objectContaining({ rawText: "Micra", parsedModelText: "Micra", purpose: "LOOKUP_ONLY" })]));
  it("makes simple consent decision-neutral even when the provider hallucinates mutations", () => { const polluted = { ...empty(), constraintMutations: [{ operation: "ADD", fieldId: "bodyStyle", normalizedValue: { operator: "EQUALS", value: "SUV" }, explicitness: "EXPLICIT_REQUIREMENT", confidence: 1, sourceSpan: "Göster" }] } as InterpretationResult; const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "Göster", activeFieldIds: [] }); expect(result.acts).toContain("OFFER_ACCEPTANCE"); expect(result.constraintMutations).toEqual([]); });
  it.each(["Göster bakalım", "Paylaş", "Paylaş bakalım", "Hadi görelim", "Seçenekleri göster", "Devam et öyleyse", "Edelim"])("binds natural consent phrase %s without decision mutations", (userText) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: ["fuelType"] }); expect(result.acts).toEqual(["OFFER_ACCEPTANCE"]); expect(result.constraintMutations).toEqual([]); });
  it("extracts two separately governed comparison references", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Araba almak istiyorum. Clio mu Civic mi kararsızım.", activeFieldIds: [] }); expect(result.acts).toContain("MODEL_COMPARISON_REQUEST"); expect(result.modelReferences).toEqual([expect.objectContaining({ rawText: "Clio", purpose: "COMPARISON_SCOPE" }), expect.objectContaining({ rawText: "Civic", purpose: "COMPARISON_SCOPE" })]); expect(result.directAnswerRequests).toContainEqual({ kind: "MODEL_COMPARISON" }); });
  it("treats a Caddy-style cargo analogy as usage intent rather than a model-suitability detour", () => { const polluted = { ...empty(), acts: ["MODEL_SUITABILITY_REQUEST"], directAnswerRequests: [{ kind: "MODEL_SUITABILITY" }], modelReferences: [{ rawText: "Caddy", parsedModelText: "Caddy", purpose: "PREFERENCE" }] } as InterpretationResult; const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "Caddy tarzı kapalı yük alanı olsun, dizel otomatik istiyorum", activeFieldIds: [] }); expect(result.acts).not.toContain("MODEL_SUITABILITY_REQUEST"); expect(result.directAnswerRequests[0]).toEqual({ kind: "RECOMMENDATION_REQUEST" }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "usageArchitecture" })); });
  it("treats general technical inexperience as tone context rather than a standalone explanation request", () => { const polluted: InterpretationResult = { ...empty(), acts: ["VEHICLE_INTENT", "SOCIAL_MESSAGE", "DONT_KNOW", "TECHNICAL_EXPLANATION_REQUEST"], directAnswerRequests: [{ kind: "TECHNICAL_EXPLANATION" }], socialSignal: { kind: "FIRST_CAR" }, technicalGuidanceRequest: { mode: "GUIDE_WITH_DAILY_LIFE" } }; const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "Merhaba, ilk arabam olacak. Şehir içinde kullanacağım ve teknik terimleri bilmiyorum.", activeFieldIds: [] }); expect(result.acts).not.toContain("TECHNICAL_EXPLANATION_REQUEST"); expect(result.acts).not.toContain("DONT_KNOW"); expect(result.directAnswerRequests).not.toContainEqual({ kind: "TECHNICAL_EXPLANATION" }); expect(result.technicalGuidanceRequest).toBeUndefined(); });
  it("keeps a first-car discovery request active without requiring the literal word recommend", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Merhaba, ilk arabam olacak. Şehir içinde kullanacağım.", activeFieldIds: [] }); expect(result.acts).toEqual(expect.arrayContaining(["VEHICLE_INTENT", "RECOMMENDATION_REQUEST"])); expect(result.directAnswerRequests).toContainEqual({ kind: "RECOMMENDATION_REQUEST" }); });
  it.each(["Araba alacağım", "Bana acil araba almam lazım"])("keeps future-purchase discovery intent active for %s", (userText) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: [] }); expect(result.acts).toEqual(expect.arrayContaining(["VEHICLE_INTENT", "RECOMMENDATION_REQUEST"])); expect(result.directAnswerRequests).toContainEqual({ kind: "RECOMMENDATION_REQUEST" }); });
});
