import { describe, expect, it } from "vitest";
import type { InterpretationResult } from "./types";
import { enforceInterpretationSemanticCompleteness } from "./semanticCompleteness";

const empty = (messageId = "m"): InterpretationResult => ({ schemaVersion: 1, messageId, acts: [], directAnswerRequests: [], constraintMutations: [], budgetMutations: [], modelReferences: [], personaMutations: [], corrections: [], ambiguities: [] });

describe("semantic completeness enforcement", () => {
  it.each(["Selamlar.", "Merhabalar, nasılsın?"])("classifies natural greeting variant %s without inventing vehicle intent", (userText) => {
    const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: [] });
    expect(result.acts).toContain("GREETING");
    expect(result.acts).not.toContain("VEHICLE_INTENT");
    expect(result.socialSignal).toEqual({ kind: "GREETING" });
  });
  it.each([
    ["bağ bahçe işleri", "Bağ bahçe işlerinde kullanmak için araç arıyorum", "ROUGH_ROAD"],
    ["dağıtım", "Hafta içi dağıtım yapacağım", "URBAN_DELIVERY"],
  ])("resolves known daily-life ambiguity %s through the controlled usage contract", (sourceSpan, userText, expected) => { const result = enforceInterpretationSemanticCompleteness({ result: { ...empty(), ambiguities: [{ code: "UNKNOWN_DECISION_PHRASE", sourceSpan }] }, userText, activeFieldIds: [] }); expect(result.ambiguities).toEqual([]); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "usageScenario", normalizedValue: expected })); });
  it("normalizes common hybrid spelling without asking for clarification", () => { const result = enforceInterpretationSemanticCompleteness({ result: { ...empty(), ambiguities: [{ code: "UNKNOWN_DECISION_PHRASE", sourceSpan: "hibrid" }] }, userText: "Elektrikli araç mı almalıyım yoksa hibrid mi?", activeFieldIds: [] }); expect(result.ambiguities).toEqual([]); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "fuelType", normalizedValue: { operator: "ONE_OF", value: ["MHEV", "HEV", "PHEV", "BEV"] } })); });
  it("answers an informational charging question without correcting the active fuel preference", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Elektrikli araçlar tam olarak nasıl şarj oluyor, bilgi verir misin?", activeFieldIds: ["fuelType"], openMaterialQuestionField: "drivenWheels" }); expect(result.constraintMutations.some((item) => item.fieldId === "fuelType")).toBe(false); expect(result.directAnswerRequests).toContainEqual({ kind: "TECHNICAL_EXPLANATION" }); });
  it.each(["Bataryayı doldurmak ne kadar sürüyor?", "Şarj süresi çok uzunmuş; hızlı şarj ne kadar sürer?"])("resolves charging-duration language without a clarification loop: %s", (userText) => {
    const result = enforceInterpretationSemanticCompleteness({ result: { ...empty(), ambiguities: [{ code: "UNKNOWN_DECISION_PHRASE", sourceSpan: userText }] }, userText, activeFieldIds: [] });
    expect(result.acts).toContain("TECHNICAL_EXPLANATION_REQUEST");
    expect(result.directAnswerRequests).toContainEqual({ kind: "TECHNICAL_EXPLANATION" });
    expect(result.ambiguities).toEqual([]);
  });
  it("classifies explicit comprehension failure as negative feedback rather than new social intent", () => {
    const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Hiçbir şey anlamıyorsun!", activeFieldIds: [] });
    expect(result.acts).toContain("NEGATIVE_FEEDBACK");
    expect(result.acts).not.toContain("GREETING");
  });
  it("answers why an open technical choice matters instead of treating uncertainty as social chatter", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Fikrim yok, sence çekiş önemli mi?", activeFieldIds: [], openMaterialQuestionField: "drivenWheels" }); expect(result.directAnswerRequests).toContainEqual({ kind: "TECHNICAL_EXPLANATION" }); expect(result.acts).toContain("TECHNICAL_EXPLANATION_REQUEST"); });
  it("binds an off-road reference to active usage memory while applying the explicit electric preference", () => { const result = enforceInterpretationSemanticCompleteness({ result: { ...empty(), ambiguities: [{ code: "CONTEXTUAL_USAGE_REFERENCE", sourceSpan: "arazi kullanımında" }] }, userText: "Elektrik olsun istiyorum ama arazi kullanımında elektrik sence mantıklı mı?", activeFieldIds: ["usageScenario", "bodyStyle"], openMaterialQuestionField: "fuelType" }); expect(result.ambiguities).toEqual([]); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "fuelType", normalizedValue: { operator: "EQUALS", value: "BEV" } })); expect(result.directAnswerRequests).toContainEqual({ kind: "TECHNICAL_EXPLANATION" }); });
  it("does not reinterpret a non-vehicle recommendation request as technical vehicle guidance", () => { const result = enforceInterpretationSemanticCompleteness({ result: { ...empty(), acts: ["OFF_TOPIC"], offTopicSignal: { detected: true } }, userText: "Telefon önerir misin?", activeFieldIds: [] }); expect(result.acts).toContain("OFF_TOPIC"); expect(result.acts).not.toContain("TECHNICAL_EXPLANATION_REQUEST"); });
  it("retains family capacity and enclosed distribution requirements in one multi-use statement", () => { const result = enforceInterpretationSemanticCompleteness({ result: { ...empty(), ambiguities: [{ code: "UNKNOWN_DECISION_PHRASE", sourceSpan: "dağıtım" }] }, userText: "Gazete ve dergi dağıtımı yapıyorum; kapalı kasa gerekiyor, aynı zamanda 4 kişilik aileyiz.", activeFieldIds: [] }); expect(result.ambiguities).toEqual([]); expect(result.constraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "usageScenario", normalizedValue: "URBAN_DELIVERY" }), expect.objectContaining({ fieldId: "usageArchitecture", normalizedValue: { operator: "EQUALS", value: "ENCLOSED_CARGO" } }), expect.objectContaining({ fieldId: "seats", normalizedValue: { operator: "EQUALS", value: 4, unit: "COUNT" } })])); });
  it("combines rejection of the revealed card with a new model preference", () => { const result = enforceInterpretationSemanticCompleteness({ result: { ...empty(), modelReferences: [{ rawText: "Tesla", parsedBrandText: "Tesla", purpose: "PREFERENCE" }], ambiguities: [{ code: "CONTEXTUAL_REFERENCE", sourceSpan: "bunu" }] }, userText: "Tesla olsun. Bunu beğenmedim.", activeFieldIds: [], revealedCandidateReferences: ["revealed-1"] }); expect(result.ambiguities).toEqual([]); expect(result.candidateRejection).toEqual(expect.objectContaining({ referenceText: "REVEALED_SET" })); expect(result.modelReferences).toContainEqual(expect.objectContaining({ rawText: "Tesla", purpose: "PREFERENCE" })); });
  it("maps value-retention and social style language to bounded persona traits", () => { const resale = enforceInterpretationSemanticCompleteness({ result: { ...empty(), ambiguities: [{ code: "UNKNOWN_DECISION_PHRASE", sourceSpan: "ikinci elde değer kaybetmeyecek" }] }, userText: "İkinci elde değer kaybetmeyecek bir araç öner", activeFieldIds: [] }); expect(resale.ambiguities).toEqual([]); expect(resale.personaMutations).toContainEqual(expect.objectContaining({ traits: ["VALUE"] })); const social = enforceInterpretationSemanticCompleteness({ result: { ...empty(), ambiguities: [{ code: "UNKNOWN_DECISION_PHRASE", sourceSpan: "kız arkadaşımı etkileyecek" }] }, userText: "Kız arkadaşımı etkileyecek bir araç arıyorum", activeFieldIds: [] }); expect(social.ambiguities).toEqual([]); expect(social.personaMutations[0]?.traits).toEqual(expect.arrayContaining(["DESIGN", "PRESTIGE"])); });
  it("honors an explicit closing even when the same turn contains negative language", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Sen hiçbir şey anlamıyorsun, berbatsın. Kapatıyorum.", activeFieldIds: [] }); expect(result.acts).toEqual(expect.arrayContaining(["ABUSE", "CLOSING"])); });
  it("drops a provider ambiguity after the same span is resolved by a controlled usage mapping", () => { const result = enforceInterpretationSemanticCompleteness({ result: { ...empty(), ambiguities: [{ code: "UNKNOWN_DECISION_PHRASE", sourceSpan: "köyde" }] }, userText: "Köyde yaşıyorum, pickup alacağım ve elektrikli kullanmak mümkün mü?", activeFieldIds: [] }); expect(result.ambiguities).toEqual([]); expect(result.constraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "usageScenario", normalizedValue: "ROUGH_ROAD" }), expect.objectContaining({ fieldId: "bodyStyle", normalizedValue: { operator: "EQUALS", value: "Pickup" } }), expect.objectContaining({ fieldId: "fuelType", normalizedValue: { operator: "EQUALS", value: "BEV" } })])); expect(result.directAnswerRequests).toContainEqual({ kind: "TECHNICAL_EXPLANATION" }); });
  it.each(["pickup araç arıyorum", "pick up araç arıyorum", "pick-up araç arıyorum", "pikap araç arıyorum"])("normalizes the body-style alias in %s", (userText) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: [] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "bodyStyle", normalizedValue: { operator: "EQUALS", value: "Pickup" } })); expect(result.acts).toEqual(expect.arrayContaining(["VEHICLE_INTENT", "RECOMMENDATION_REQUEST"])); });
  it("keeps multiple selected fuel and body options as atomic ONE_OF preferences", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Benzin veya dizel; sedan veya hatchback olabilir.", activeFieldIds: [] }); expect(result.constraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "fuelType", normalizedValue: { operator: "ONE_OF", value: ["GASOLINE", "DIESEL"] } }), expect.objectContaining({ fieldId: "bodyStyle", normalizedValue: { operator: "ONE_OF", value: ["Sedan", "Hatchback"] } })])); });
  it("keeps gasoline plus HEV as one atomic set without BEV", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Benzin veya Tam hibrit", activeFieldIds: [], openMaterialQuestionField: "fuelType" }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "fuelType", normalizedValue: { operator: "ONE_OF", value: ["HEV", "GASOLINE"] } })); expect(JSON.stringify(result)).not.toContain("BEV"); });
  it("does not let provider mutations widen an authoritative multi-selection", () => { const polluted = { ...empty(), constraintMutations: [{ operation: "ADD", fieldId: "fuelType", normalizedValue: { operator: "ONE_OF", value: ["GASOLINE", "HEV", "BEV"] }, explicitness: "EXPLICIT_REQUIREMENT", confidence: 1, sourceSpan: "selection" }, { operation: "ADD", fieldId: "bodyStyle", normalizedValue: { operator: "EQUALS", value: "SUV" }, explicitness: "EXPLICIT_REQUIREMENT", confidence: 1, sourceSpan: "selection" }] } as InterpretationResult; const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "Benzin veya Tam hibrit", activeFieldIds: [], openMaterialQuestionField: "fuelType" }); expect(result.constraintMutations).toEqual([expect.objectContaining({ fieldId: "fuelType", normalizedValue: { operator: "ONE_OF", value: ["HEV", "GASOLINE"] } })]); });
  it("canonicalizes a single selection from a multiple question to EQUALS", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Tam hibrit", activeFieldIds: [], openMaterialQuestionField: "fuelType" }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "fuelType", normalizedValue: { operator: "EQUALS", value: "HEV" } })); });
  it("treats explicit technical option answers as authoritative filters", () => {
    const body = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Kapalı kasa ticari veya Şasi kabin", activeFieldIds: [], openMaterialQuestionField: "bodyStyle" });
    expect(body.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "bodyStyle", explicitness: "EXPLICIT_REQUIREMENT", normalizedValue: { operator: "ONE_OF", value: ["Panel Van", "Chassis Cab"] } }));
    const drive = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Önden çekiş", activeFieldIds: [], openMaterialQuestionField: "drivenWheels" });
    expect(drive.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "drivenWheels", explicitness: "EXPLICIT_REQUIREMENT", normalizedValue: { operator: "EQUALS", value: "FWD" } }));
  });
  it("treats a controlled seat answer as a minimum hard requirement", () => {
    const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "9 koltuk", activeFieldIds: [], openMaterialQuestionField: "seats" });
    expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "seats", explicitness: "EXPLICIT_REQUIREMENT", normalizedValue: { operator: "MINIMUM", value: 9, unit: "COUNT" } }));
    expect(result.acts).toContain("HARD_REQUIREMENT");
  });
  it.each([
    ["payloadKg", "1.000 kg yük", 1_000, "KG"],
    ["cargoVolumeLitres", "5.000 litre yük hacmi", 5_000, "LITRE"],
    ["luggageLitres", "500 litre bagaj", 500, "LITRE"],
    ["powerKw", "150 kW", 150, "KW"],
    ["electricRangeKm", "400 km menzil", 400, "KM"],
  ] as const)("treats controlled numeric %s answers as minimum hard requirements", (fieldId, userText, value, unit) => {
    const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: [], openMaterialQuestionField: fieldId });
    expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId, explicitness: "EXPLICIT_REQUIREMENT", normalizedValue: { operator: "MINIMUM", value, unit } }));
  });
  it.each([["Ucuz bir araç istiyorum", "LOWEST_20"], ["En ucuzlardan olsun", "LOWEST_20"], ["Ekonomik fiyatlı araba", "VALUE_20_40"], ["Orta fiyat grubunda olsun", "MID_40_60"], ["Üst fiyat grubunda olsun", "UPPER_60_80"], ["Premium fiyat grubunda olsun", "HIGHEST_80_100"]])("normalizes explicit price language %s", (message, segment) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: message, activeFieldIds: [] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "relativePriceSegment", normalizedValue: segment, explicitness: "EXPLICIT_PREFERENCE" })); });
  it.each(["ekonomik", "az yakan ekonomik araba", "orta seviye", "üst sınıf sedan", "premium ve şık", "üst segment"])('does not infer a price segment from ambiguous language "%s"', (message) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: message, activeFieldIds: [] }); expect(result.constraintMutations.some((mutation) => mutation.fieldId === "relativePriceSegment")).toBe(false); });
  it("preserves explicit persona meaning without turning it into a price segment", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "premium ve şık", activeFieldIds: [] }); expect(result.personaMutations).toContainEqual(expect.objectContaining({ operation: "ACTIVATE", traits: expect.arrayContaining(["PRESTIGE", "DESIGN"]) })); expect(result.constraintMutations.some((mutation) => mutation.fieldId === "relativePriceSegment")).toBe(false); });
  it("binds purchase-price and running-cost clarification answers deterministically", () => {
    const purchase = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Satın alma fiyatı erişilebilir olsun", activeFieldIds: [], openMaterialQuestionField: "relativePriceMeaning" });
    expect(purchase.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "relativePriceSegment", normalizedValue: "LOWEST_20", explicitness: "EXPLICIT_PREFERENCE" }));
    const running = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Kullanım ve yakıt maliyeti düşük olsun", activeFieldIds: [], openMaterialQuestionField: "relativePriceMeaning" });
    expect(running.constraintMutations).toEqual([expect.objectContaining({ fieldId: "runningCostPreference", normalizedValue: "LOW_RUNNING_COST", explicitness: "EXPLICIT_PREFERENCE" })]);
    expect(JSON.stringify(running)).not.toMatch(/combinedLitresPer100Km|combinedKwhPer100Km|litre|kwh/iu);
  });
  it("keeps both economic meanings and can later supersede running cost", () => {
    const both = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "İkisi de önemli", activeFieldIds: [], openMaterialQuestionField: "relativePriceMeaning" });
    expect(both.constraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "relativePriceSegment", normalizedValue: "LOWEST_20" }), expect.objectContaining({ fieldId: "runningCostPreference", normalizedValue: "LOW_RUNNING_COST" })]));
    const corrected = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Satın alma fiyatını kastediyordum", activeFieldIds: ["runningCostPreference"], openMaterialQuestionField: undefined });
    expect(corrected.constraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "relativePriceSegment", normalizedValue: "LOWEST_20" }), expect.objectContaining({ operation: "CLEAR", fieldId: "runningCostPreference" })]));
  });
  it("does not create constraints for a greeting", () => expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Merhaba", activeFieldIds: [] }).constraintMutations).toEqual([]));
  it("maps hybrid to the closed hybrid family without BEV", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Hibrit tercih ederim", activeFieldIds: [] }); expect(result.constraintMutations[0]?.normalizedValue).toEqual({ operator: "ONE_OF", value: ["MHEV", "HEV", "PHEV"] }); expect(JSON.stringify(result)).not.toContain("BEV"); });
  it("corrects an active body style and never preserves a contradicted pickup", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Pickup demedim, sedan dedim", activeFieldIds: ["bodyStyle"] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ operation: "CORRECT", fieldId: "bodyStyle", supersedesFieldId: "bodyStyle", normalizedValue: { operator: "EQUALS", value: "Sedan" } })); });
  it("keeps a soft sedan preference soft", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Sedan tercih ederim", activeFieldIds: [] }); expect(result.constraintMutations[0]?.explicitness).toBe("EXPLICIT_PREFERENCE"); });
  it("binds an explicit automatic preference to the controlled transmission field", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Otomatik istiyorum", activeFieldIds: [] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "transmission", explicitness: "EXPLICIT_PREFERENCE", normalizedValue: { operator: "EQUALS", value: "AUTOMATIC" } })); });
  it("projects cargo-first meaning and rear-seat not-needed separately", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Şehir içi dağıtım için kapalı yük alanı istiyorum, arka koltuklara gerek yok.", activeFieldIds: [] }); expect(result.constraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "usageArchitecture", explicitness: "EXPLICIT_REQUIREMENT", normalizedValue: { operator: "EQUALS", value: "ENCLOSED_CARGO" } }), expect.objectContaining({ fieldId: "rearSeatPreference", normalizedValue: "NOT_NEEDED" })])); });
  it.each([
    ["Günlük şehir içinde kullanacağım", "URBAN_DAILY"], ["Ailemle kullanacağım", "FAMILY"], ["Sık uzun yol yapacağım", "LONG_DISTANCE"], ["Kırsalda kullanım", "ROUGH_ROAD"],
    ["Şehir içinde mal dağıtıyorum", "URBAN_DELIVERY"], ["Genel yük taşıyacağım", "GENERAL_CARGO"], ["Yolcu taşıma işi yapacağım", "PASSENGER_TRANSPORT"],
    ["Köyde bozuk yolda kullanacağım", "ROUGH_ROAD"], ["Köyde kullanacağım", "ROUGH_ROAD"], ["Karlı ve çamurlu yolda kullanacağım", "MUD_SNOW"], ["Ciddi arazi için istiyorum", "SERIOUS_OFF_ROAD"],
  ])("projects controlled usage scenario %s", (userText, scenario) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: [] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "usageScenario", normalizedValue: scenario, explicitness: "EXPLICIT_PREFERENCE" })); expect(result.acts).toContain("USAGE_STATEMENT"); });
  it("keeps use-purpose membership separate from ad-hoc body and drivetrain constraints", () => {
    const cargo = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Yük taşıma", activeFieldIds: [], openMaterialQuestionField: "usageScenario" });
    expect(cargo.constraintMutations).toEqual([expect.objectContaining({ fieldId: "usageScenario", normalizedValue: "GENERAL_CARGO" })]);
    const offRoad = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Ciddi arazi", activeFieldIds: [], openMaterialQuestionField: "usageScenario" });
    expect(offRoad.constraintMutations).toEqual([expect.objectContaining({ fieldId: "usageScenario", normalizedValue: "SERIOUS_OFF_ROAD" })]);
    const family = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Aile ve yolcu kullanımı", activeFieldIds: [], openMaterialQuestionField: "usageScenario" });
    expect(family.constraintMutations.some((item) => item.explicitness === "EXPLICIT_REQUIREMENT")).toBe(false);
  });
  it("removes mixed use from the controlled usage list", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Karma kullanım için arıyorum", activeFieldIds: [], openMaterialQuestionField: "usageScenario" }); expect(result.constraintMutations.some((item) => item.fieldId === "usageScenario")).toBe(false); });
  it.each(["Günlük kullanım için iyi bir arabaya ihtiyacım var.", "Her gün kullanacağım.", "İşe gidip geleceğim.", "Gündelik işler için bir araç arıyorum.", "Şehirde olmasa da günlük kullanım için istiyorum."])("treats broad daily expression as passenger daily context: %s", (userText) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: [] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "usageScenario", normalizedValue: "URBAN_DAILY" })); });
  it("treats an electric off-road availability question as a bounded catalog scope rather than a model lookup", () => { const polluted = { ...empty(), acts: ["MODEL_SUITABILITY_REQUEST"], directAnswerRequests: [{ kind: "MODEL_SUITABILITY" }] } as InterpretationResult; const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "Arazi aracı, elketrikli. Var mı?", activeFieldIds: [] }); expect(result.acts).toEqual(expect.arrayContaining(["VEHICLE_INTENT", "RECOMMENDATION_REQUEST", "USAGE_STATEMENT", "HARD_REQUIREMENT"])); expect(result.acts).not.toContain("MODEL_SUITABILITY_REQUEST"); expect(result.modelReferences).toEqual([]); expect(result.constraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "usageScenario", normalizedValue: "SERIOUS_OFF_ROAD" }), expect.objectContaining({ fieldId: "fuelType", normalizedValue: { operator: "EQUALS", value: "BEV" } })])); });
  it("separates cash and financing from a hard ceiling", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "5 milyon nakitim var, üstü için kredi kullanabilirim", activeFieldIds: [] }); expect(result.budgetMutations.map((item) => item.field)).toEqual(expect.arrayContaining(["AVAILABLE_CASH", "FINANCE_FLEXIBILITY", "UNRESOLVED_FINANCED_CEILING"])); expect(result.budgetMutations.some((item) => item.field === "MAXIMUM_HARD_CEILING")).toBe(false); });
  it("creates hard ceiling and budget exclusion only from explicit language", () => { expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "5 milyon üstüne çıkmam", activeFieldIds: [] }).budgetMutations).toContainEqual(expect.objectContaining({ field: "MAXIMUM_HARD_CEILING" })); expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Bütçe önemli değil", activeFieldIds: [] }).budgetMutations).toContainEqual(expect.objectContaining({ operation: "EXCLUDE_FROM_DECISION" })); });
  it.each(["Bütçe sorun değil", "Bütçe problem değil", "Bütçe sınırım yok", "Bütçe sınırsız"])("excludes budget on explicit unbounded wording: %s", (userText) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: [], openMaterialQuestionField: "budget" }); expect(result.budgetMutations).toContainEqual(expect.objectContaining({ operation: "EXCLUDE_FROM_DECISION" })); });
  it("distinguishes a flexible budget from an explicit only-budget ceiling", () => {
    const flexible = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "2 milyon, belki biraz üstü", activeFieldIds: [], openMaterialQuestionField: "budget" });
    expect(flexible.budgetMutations).toContainEqual(expect.objectContaining({ field: "PREFERRED_BUDGET" }));
    expect(flexible.budgetMutations.some((item) => item.field === "MAXIMUM_HARD_CEILING")).toBe(false);
    const hard = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "2 milyon bütçem var sadece", activeFieldIds: ["PREFERRED_BUDGET"] });
    expect(hard.budgetMutations).toContainEqual(expect.objectContaining({ field: "MAXIMUM_HARD_CEILING", value: { amount: 2_000_000, currency: "TRY" } }));
    const explicit = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Kesin bütçem 1.500.000 TL", activeFieldIds: ["PREFERRED_BUDGET"] });
    expect(explicit.budgetMutations).toContainEqual(expect.objectContaining({ field: "MAXIMUM_HARD_CEILING", value: { amount: 1_500_000, currency: "TRY" } }));
  });
  it("binds a bare amount to the open budget question without making it a hard ceiling", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "3 milyon tl", activeFieldIds: [], openMaterialQuestionField: "budget" }); expect(result.budgetMutations).toEqual(expect.arrayContaining([expect.objectContaining({ field: "PREFERRED_BUDGET", value: { amount: 3_000_000, currency: "TRY" } }), expect.objectContaining({ field: "BUDGET_UNKNOWN", value: false })])); expect(result.budgetMutations.some((item) => item.field === "MAXIMUM_HARD_CEILING")).toBe(false); });
  it("binds available-money wording to the asked budget instead of dropping budget intent", () => {
    const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "1 milyon param var", activeFieldIds: [], openMaterialQuestionField: "budget" });
    expect(result.budgetMutations).toContainEqual(expect.objectContaining({ field: "PREFERRED_BUDGET", value: { amount: 1_000_000, currency: "TRY" } }));
    expect(result.budgetMutations.some((item) => item.field === "AVAILABLE_CASH")).toBe(false);
    const financed = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "1 milyon param var, üstü için kredi kullanabilirim", activeFieldIds: [], openMaterialQuestionField: "budget" });
    expect(financed.budgetMutations.map((item) => item.field)).toEqual(expect.arrayContaining(["AVAILABLE_CASH", "FINANCE_FLEXIBILITY", "UNRESOLVED_FINANCED_CEILING"]));
  });
  it("binds a bare daily answer only to the open usage question", () => {
    for (const userText of ["günlük", "günlük takılırız", "gündelik hayatımızda kullanacağız", "günlük işler için"]) {
      const bound = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: [], openMaterialQuestionField: "usageScenario" });
      expect(bound.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "usageScenario", normalizedValue: "URBAN_DAILY" }));
    }
    const unbound = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "günlük", activeFieldIds: [] });
    expect(unbound.constraintMutations.some((item) => item.fieldId === "usageScenario")).toBe(false);
  });
  it("keeps a more specific long-distance meaning ahead of an informal daily prefix", () => {
    const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "günlük uzun yol yaparım", activeFieldIds: [], openMaterialQuestionField: "usageScenario" });
    expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "usageScenario", normalizedValue: "LONG_DISTANCE" }));
  });
  it("recognizes first-car context independently of provider wording", () => {
    const completed = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "İyiyim, ilk arabamı almak için heyecanlıyım.", activeFieldIds: [] });
    expect(completed.socialSignal).toEqual({ kind: "FIRST_CAR" });
    expect(completed.acts).toContain("SOCIAL_MESSAGE");
  });
  it("binds a plural dislike to the revealed candidate set without guessing a brand or family", () => {
    const completed = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Bunları beğenmedim, bütçem 15 milyon.", activeFieldIds: [], revealedCandidateReferences: ["v1", "v2", "v3"] });
    expect(completed.candidateRejection).toEqual({ scope: "AMBIGUOUS", referenceText: "REVEALED_SET", sourceSpan: "Bunları beğenmedim, bütçem 15 milyon." });
    expect(completed.acts).toContain("CANDIDATE_REJECTION");
  });
  it("turns a cheaper-alternative request into a value preference and rejection of the revealed set", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Bunlardan daha ucuz ve daha hesaplı araçlar göster", activeFieldIds: [], revealedCandidateReferences: ["v1", "v2", "v3"] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "relativePriceSegment", normalizedValue: "LOWEST_20" })); expect(result.candidateRejection).toEqual(expect.objectContaining({ referenceText: "REVEALED_SET" })); expect(result.acts).toEqual(expect.arrayContaining(["ALTERNATIVE_REQUEST", "CANDIDATE_REJECTION"])); expect(result.directAnswerRequests).toContainEqual({ kind: "ALTERNATIVE_REQUEST" }); });
  it("binds a too-expensive complaint to the revealed candidate set", () => {
    const userText = "Bunlar çok pahalı. 2 milyon bütçem var sadece.";
    const completed = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: [], revealedCandidateReferences: ["v1", "v2", "v3"] });
    expect(completed.candidateRejection).toEqual({ scope: "AMBIGUOUS", referenceText: "REVEALED_SET", sourceSpan: userText });
    expect(completed.acts).toContain("CANDIDATE_REJECTION");
  });
  it("does not interpret a bare amount as budget outside a budget-question context", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "3 milyon tl", activeFieldIds: [] }); expect(result.budgetMutations).toEqual([]); });
  it("activates only safe persona vocabulary and supports deactivation", () => { expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Premium ve şık olsun", activeFieldIds: [] }).personaMutations).toContainEqual(expect.objectContaining({ operation: "ACTIVATE", traits: ["PRESTIGE", "DESIGN"] })); expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Fark etmez", activeFieldIds: [] }).personaMutations).toContainEqual(expect.objectContaining({ operation: "DEACTIVATE" })); });
  it("creates a lookup-only model reference without resolving catalog truth", () => expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Micra var mı?", activeFieldIds: [] }).modelReferences).toEqual([expect.objectContaining({ rawText: "Micra", parsedModelText: "Micra", purpose: "LOOKUP_ONLY" })]));
  it("repairs a polluted model lookup into an explicit recommendation request", () => {
    const polluted = { ...empty(), acts: ["MODEL_LOOKUP_REQUEST"], directAnswerRequests: [{ kind: "MODEL_AVAILABILITY" }], modelReferences: [{ rawText: "BYD Dolphin Comfort 2025", parsedBrandText: "BYD", parsedModelText: "Dolphin Comfort 2025", purpose: "LOOKUP_ONLY" }] } as InterpretationResult;
    const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "BYD Dolphin Comfort 2025 almak istiyorum; başlangıç noktası alarak seçeneği hazırla.", activeFieldIds: [] });
    expect(result.acts).toContain("RECOMMENDATION_REQUEST");
    expect(result.acts).not.toContain("MODEL_LOOKUP_REQUEST");
    expect(result.directAnswerRequests).toEqual([{ kind: "RECOMMENDATION_REQUEST" }]);
  });
  it("makes simple consent decision-neutral even when the provider hallucinates mutations", () => { const polluted = { ...empty(), constraintMutations: [{ operation: "ADD", fieldId: "bodyStyle", normalizedValue: { operator: "EQUALS", value: "SUV" }, explicitness: "EXPLICIT_REQUIREMENT", confidence: 1, sourceSpan: "Göster" }] } as InterpretationResult; const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "Göster", activeFieldIds: [] }); expect(result.acts).toContain("OFFER_ACCEPTANCE"); expect(result.constraintMutations).toEqual([]); });
  it.each(["Göster bakalım", "Paylaş", "Paylaş bakalım", "Hadi görelim", "Seçenekleri göster", "Devam et öyleyse", "Edelim"])("binds natural consent phrase %s without decision mutations", (userText) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: ["fuelType"] }); expect(result.acts).toEqual(["OFFER_ACCEPTANCE"]); expect(result.constraintMutations).toEqual([]); });
  it("binds a conversational yes-plus-show consent without provider help", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Evet, göster bakalım", activeFieldIds: [] }); expect(result.acts).toEqual(["OFFER_ACCEPTANCE"]); });
  it("extracts two separately governed comparison references", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Araba almak istiyorum. Clio mu Civic mi kararsızım.", activeFieldIds: [] }); expect(result.acts).toContain("MODEL_COMPARISON_REQUEST"); expect(result.modelReferences).toEqual([expect.objectContaining({ rawText: "Clio", purpose: "COMPARISON_SCOPE" }), expect.objectContaining({ rawText: "Civic", purpose: "COMPARISON_SCOPE" })]); expect(result.directAnswerRequests).toContainEqual({ kind: "MODEL_COMPARISON" }); });
  it("treats a Caddy-style cargo analogy as usage intent rather than a model-suitability detour", () => { const polluted = { ...empty(), acts: ["MODEL_SUITABILITY_REQUEST"], directAnswerRequests: [{ kind: "MODEL_SUITABILITY" }], modelReferences: [{ rawText: "Caddy", parsedModelText: "Caddy", purpose: "PREFERENCE" }] } as InterpretationResult; const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "Caddy tarzı kapalı yük alanı olsun, dizel otomatik istiyorum", activeFieldIds: [] }); expect(result.acts).not.toContain("MODEL_SUITABILITY_REQUEST"); expect(result.directAnswerRequests[0]).toEqual({ kind: "RECOMMENDATION_REQUEST" }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "usageArchitecture" })); });
  it("treats general technical inexperience as tone context rather than a standalone explanation request", () => { const polluted: InterpretationResult = { ...empty(), acts: ["VEHICLE_INTENT", "SOCIAL_MESSAGE", "DONT_KNOW", "TECHNICAL_EXPLANATION_REQUEST"], directAnswerRequests: [{ kind: "TECHNICAL_EXPLANATION" }], socialSignal: { kind: "FIRST_CAR" }, technicalGuidanceRequest: { mode: "GUIDE_WITH_DAILY_LIFE" } }; const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "Merhaba, ilk arabam olacak. Şehir içinde kullanacağım ve teknik terimleri bilmiyorum.", activeFieldIds: [] }); expect(result.acts).not.toContain("TECHNICAL_EXPLANATION_REQUEST"); expect(result.acts).not.toContain("DONT_KNOW"); expect(result.directAnswerRequests).not.toContainEqual({ kind: "TECHNICAL_EXPLANATION" }); expect(result.technicalGuidanceRequest).toBeUndefined(); });
  it("keeps a first-car discovery request active without requiring the literal word recommend", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Merhaba, ilk arabam olacak. Şehir içinde kullanacağım.", activeFieldIds: [] }); expect(result.acts).toEqual(expect.arrayContaining(["VEHICLE_INTENT", "RECOMMENDATION_REQUEST"])); expect(result.directAnswerRequests).toContainEqual({ kind: "RECOMMENDATION_REQUEST" }); });
  it.each(["Araba alacağım", "Bana acil araba almam lazım", "İlk arabamı alacağım", "Oğluma ilk arabasını hediye edeceğim", "Şehir içinde kullanmak için araç lazım", "İş için araç almam gerekiyor", "Nasıl bir araba almalıyım bilmiyorum"])("keeps future-purchase discovery intent active for %s", (userText) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: ["NEW_CAR_SCOPE"] }); expect(result.acts).toEqual(expect.arrayContaining(["VEHICLE_INTENT", "RECOMMENDATION_REQUEST"])); expect(result.directAnswerRequests).toContainEqual({ kind: "RECOMMENDATION_REQUEST" }); });
});
