import { describe, expect, it } from "vitest";
import type { InterpretationResult } from "./types";
import { enforceInterpretationSemanticCompleteness } from "./semanticCompleteness";

const empty = (messageId = "m"): InterpretationResult => ({ schemaVersion: 1, messageId, acts: [], directAnswerRequests: [], constraintMutations: [], budgetMutations: [], modelReferences: [], personaMutations: [], corrections: [], ambiguities: [] });

describe("semantic completeness enforcement", () => {
  it("keeps multiple selected fuel and body options as atomic ONE_OF preferences", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Benzin veya dizel; sedan veya hatchback olabilir.", activeFieldIds: [] }); expect(result.constraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "fuelType", normalizedValue: { operator: "ONE_OF", value: ["GASOLINE", "DIESEL"] } }), expect.objectContaining({ fieldId: "bodyStyle", normalizedValue: { operator: "ONE_OF", value: ["Sedan", "Hatchback"] } })])); });
  it("keeps gasoline plus HEV as one atomic set without BEV", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Benzin veya Tam hibrit", activeFieldIds: [], openMaterialQuestionField: "fuelType" }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "fuelType", normalizedValue: { operator: "ONE_OF", value: ["HEV", "GASOLINE"] } })); expect(JSON.stringify(result)).not.toContain("BEV"); });
  it("does not let provider mutations widen an authoritative multi-selection", () => { const polluted = { ...empty(), constraintMutations: [{ operation: "ADD", fieldId: "fuelType", normalizedValue: { operator: "ONE_OF", value: ["GASOLINE", "HEV", "BEV"] }, explicitness: "EXPLICIT_REQUIREMENT", confidence: 1, sourceSpan: "selection" }, { operation: "ADD", fieldId: "bodyStyle", normalizedValue: { operator: "EQUALS", value: "SUV" }, explicitness: "EXPLICIT_REQUIREMENT", confidence: 1, sourceSpan: "selection" }] } as InterpretationResult; const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "Benzin veya Tam hibrit", activeFieldIds: [], openMaterialQuestionField: "fuelType" }); expect(result.constraintMutations).toEqual([expect.objectContaining({ fieldId: "fuelType", normalizedValue: { operator: "ONE_OF", value: ["HEV", "GASOLINE"] } })]); });
  it("canonicalizes a single selection from a multiple question to EQUALS", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Tam hibrit", activeFieldIds: [], openMaterialQuestionField: "fuelType" }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "fuelType", normalizedValue: { operator: "EQUALS", value: "HEV" } })); });
  it.each([["Ucuz bir araç istiyorum", "LOWEST_20"], ["En ucuzlardan olsun", "LOWEST_20"], ["Ekonomik fiyatlı araba", "VALUE_20_40"], ["Orta fiyat grubunda olsun", "MID_40_60"], ["Üst fiyat grubunda olsun", "UPPER_60_80"], ["Premium fiyat grubunda olsun", "HIGHEST_80_100"]])("normalizes explicit price language %s", (message, segment) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: message, activeFieldIds: [] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "relativePriceSegment", normalizedValue: segment, explicitness: "EXPLICIT_PREFERENCE" })); });
  it.each(["ekonomik", "az yakan ekonomik araba", "orta seviye", "üst sınıf sedan", "premium ve şık", "üst segment"])('does not infer a price segment from ambiguous language "%s"', (message) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: message, activeFieldIds: [] }); expect(result.constraintMutations.some((mutation) => mutation.fieldId === "relativePriceSegment")).toBe(false); });
  it("preserves explicit persona meaning without turning it into a price segment", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "premium ve şık", activeFieldIds: [] }); expect(result.personaMutations).toContainEqual(expect.objectContaining({ operation: "ACTIVATE", traits: expect.arrayContaining(["PRESTIGE", "DESIGN"]) })); expect(result.constraintMutations.some((mutation) => mutation.fieldId === "relativePriceSegment")).toBe(false); });
  it("binds purchase-price and running-cost clarification answers deterministically", () => {
    const purchase = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Satın alma fiyatı erişilebilir olsun", activeFieldIds: [], openMaterialQuestionField: "relativePriceMeaning" });
    expect(purchase.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "relativePriceSegment", normalizedValue: "LOWEST_20", explicitness: "EXPLICIT_PREFERENCE" }));
    const running = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Kullanım ve yakıt maliyeti düşük olsun", activeFieldIds: [], openMaterialQuestionField: "relativePriceMeaning" });
    expect(running.constraintMutations).toEqual([expect.objectContaining({ fieldId: "runningCostPreference", normalizedValue: "LOW_RUNNING_COST", explicitness: "EXPLICIT_PREFERENCE" })]);
    expect(JSON.stringify(running)).not.toMatch(/combinedLitresPer100Km|combinedKwhPer100Km|litre|kwh/iu);
  });
  it("keeps both economic meanings and can later supersede running cost", () => {
    const both = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "İkisi de önemli", activeFieldIds: [], openMaterialQuestionField: "relativePriceMeaning" });
    expect(both.constraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "relativePriceSegment", normalizedValue: "LOWEST_20" }), expect.objectContaining({ fieldId: "runningCostPreference", normalizedValue: "LOW_RUNNING_COST" })]));
    const corrected = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Satın alma fiyatını kastediyordum", activeFieldIds: ["runningCostPreference"], openMaterialQuestionField: undefined });
    expect(corrected.constraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "relativePriceSegment", normalizedValue: "LOWEST_20" }), expect.objectContaining({ operation: "CLEAR", fieldId: "runningCostPreference" })]));
  });
  it("does not create constraints for a greeting", () => expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Merhaba", activeFieldIds: [] }).constraintMutations).toEqual([]));
  it("maps hybrid to the closed hybrid family without BEV", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Hibrit tercih ederim", activeFieldIds: [] }); expect(result.constraintMutations[0]?.normalizedValue).toEqual({ operator: "ONE_OF", value: ["MHEV", "HEV", "PHEV"] }); expect(JSON.stringify(result)).not.toContain("BEV"); });
  it("corrects an active body style and never preserves a contradicted pickup", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Pickup demedim, sedan dedim", activeFieldIds: ["bodyStyle"] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ operation: "CORRECT", fieldId: "bodyStyle", supersedesFieldId: "bodyStyle", normalizedValue: { operator: "EQUALS", value: "Sedan" } })); });
  it("keeps a soft sedan preference soft", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Sedan tercih ederim", activeFieldIds: [] }); expect(result.constraintMutations[0]?.explicitness).toBe("EXPLICIT_PREFERENCE"); });
  it("binds an explicit automatic preference to the controlled transmission field", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Otomatik istiyorum", activeFieldIds: [] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "transmission", explicitness: "EXPLICIT_PREFERENCE", normalizedValue: { operator: "EQUALS", value: "AUTOMATIC" } })); });
  it("projects cargo-first meaning and rear-seat not-needed separately", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Şehir içi dağıtım için kapalı yük alanı istiyorum, arka koltuklara gerek yok.", activeFieldIds: [] }); expect(result.constraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "usageArchitecture", explicitness: "EXPLICIT_REQUIREMENT", normalizedValue: { operator: "EQUALS", value: "ENCLOSED_CARGO" } }), expect.objectContaining({ fieldId: "rearSeatPreference", normalizedValue: "NOT_NEEDED" })])); });
  it.each([
    ["Günlük şehir içinde kullanacağım", "URBAN_DAILY"], ["Ailemle kullanacağım", "FAMILY"], ["Sık uzun yol yapacağım", "LONG_DISTANCE"],
    ["Şehir içinde mal dağıtıyorum", "URBAN_DELIVERY"], ["Genel yük taşıyacağım", "GENERAL_CARGO"], ["Yolcu taşıma işi yapacağım", "PASSENGER_TRANSPORT"],
    ["Köyde bozuk yolda kullanacağım", "ROUGH_ROAD"], ["Karlı ve çamurlu yolda kullanacağım", "MUD_SNOW"], ["Ciddi arazi için istiyorum", "SERIOUS_OFF_ROAD"],
    ["Karma kullanım için arıyorum", "MIXED_PASSENGER"],
  ])("projects controlled usage scenario %s", (userText, scenario) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: [] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "usageScenario", normalizedValue: scenario, explicitness: "EXPLICIT_PREFERENCE" })); expect(result.acts).toContain("USAGE_STATEMENT"); });
  it.each(["Günlük kullanım için iyi bir arabaya ihtiyacım var.", "Her gün kullanacağım.", "İşe gidip geleceğim.", "Gündelik işler için bir araç arıyorum.", "Şehirde olmasa da günlük kullanım için istiyorum."])("treats broad daily expression as passenger daily context: %s", (userText) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: [] }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "usageScenario", normalizedValue: "URBAN_DAILY" })); });
  it("treats an electric off-road availability question as needs discovery rather than a model lookup", () => { const polluted = { ...empty(), acts: ["MODEL_SUITABILITY_REQUEST"], directAnswerRequests: [{ kind: "MODEL_SUITABILITY" }] } as InterpretationResult; const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "Arazi aracı, elketrikli. Var mı?", activeFieldIds: [] }); expect(result.acts).toEqual(expect.arrayContaining(["VEHICLE_INTENT", "RECOMMENDATION_REQUEST", "USAGE_STATEMENT", "PREFERENCE_STATEMENT"])); expect(result.acts).not.toContain("MODEL_SUITABILITY_REQUEST"); expect(result.modelReferences).toEqual([]); expect(result.constraintMutations).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: "usageScenario", normalizedValue: "SERIOUS_OFF_ROAD" }), expect.objectContaining({ fieldId: "fuelType", normalizedValue: { operator: "EQUALS", value: "BEV" } })])); });
  it("separates cash and financing from a hard ceiling", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "5 milyon nakitim var, üstü için kredi kullanabilirim", activeFieldIds: [] }); expect(result.budgetMutations.map((item) => item.field)).toEqual(expect.arrayContaining(["AVAILABLE_CASH", "FINANCE_FLEXIBILITY", "UNRESOLVED_FINANCED_CEILING"])); expect(result.budgetMutations.some((item) => item.field === "MAXIMUM_HARD_CEILING")).toBe(false); });
  it("creates hard ceiling and budget exclusion only from explicit language", () => { expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "5 milyon üstüne çıkmam", activeFieldIds: [] }).budgetMutations).toContainEqual(expect.objectContaining({ field: "MAXIMUM_HARD_CEILING" })); expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Bütçe önemli değil", activeFieldIds: [] }).budgetMutations).toContainEqual(expect.objectContaining({ operation: "EXCLUDE_FROM_DECISION" })); });
  it("distinguishes a flexible budget from an explicit only-budget ceiling", () => {
    const flexible = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "2 milyon, belki biraz üstü", activeFieldIds: [], openMaterialQuestionField: "budget" });
    expect(flexible.budgetMutations).toContainEqual(expect.objectContaining({ field: "PREFERRED_BUDGET" }));
    expect(flexible.budgetMutations.some((item) => item.field === "MAXIMUM_HARD_CEILING")).toBe(false);
    const hard = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "2 milyon bütçem var sadece", activeFieldIds: ["PREFERRED_BUDGET"] });
    expect(hard.budgetMutations).toContainEqual(expect.objectContaining({ field: "MAXIMUM_HARD_CEILING", value: { amount: 2_000_000, currency: "TRY" } }));
  });
  it("binds a bare amount to the open budget question without making it a hard ceiling", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "3 milyon tl", activeFieldIds: [], openMaterialQuestionField: "budget" }); expect(result.budgetMutations).toEqual(expect.arrayContaining([expect.objectContaining({ field: "PREFERRED_BUDGET", value: { amount: 3_000_000, currency: "TRY" } }), expect.objectContaining({ field: "BUDGET_UNKNOWN", value: false })])); expect(result.budgetMutations.some((item) => item.field === "MAXIMUM_HARD_CEILING")).toBe(false); });
  it("binds a bare daily answer only to the open usage question", () => {
    for (const userText of ["günlük", "günlük takılırız", "gündelik hayatımızda kullanacağız", "günlük işler için"]) {
      const bound = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: [], openMaterialQuestionField: "usageScenario" });
      expect(bound.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "usageScenario", normalizedValue: "URBAN_DAILY" }));
    }
    const unbound = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "günlük", activeFieldIds: [] });
    expect(unbound.constraintMutations.some((item) => item.fieldId === "usageScenario")).toBe(false);
  });
  it("keeps a more specific long-distance meaning ahead of an informal daily prefix", () => {
    const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "günlük uzun yol yaparım", activeFieldIds: [], openMaterialQuestionField: "usageScenario" });
    expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "usageScenario", normalizedValue: "LONG_DISTANCE" }));
  });
  it("recognizes first-car context independently of provider wording", () => {
    const completed = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "İyiyim, ilk arabamı almak için heyecanlıyım.", activeFieldIds: [] });
    expect(completed.socialSignal).toEqual({ kind: "FIRST_CAR" });
    expect(completed.acts).toContain("SOCIAL_MESSAGE");
  });
  it("binds a plural dislike to the revealed candidate set without guessing a brand or family", () => {
    const completed = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Bunları beğenmedim, bütçem 15 milyon.", activeFieldIds: [], revealedCandidateReferences: ["v1", "v2", "v3"] });
    expect(completed.candidateRejection).toEqual({ scope: "AMBIGUOUS", referenceText: "REVEALED_SET", sourceSpan: "Bunları beğenmedim, bütçem 15 milyon." });
    expect(completed.acts).toContain("CANDIDATE_REJECTION");
  });
  it("binds a too-expensive complaint to the revealed candidate set", () => {
    const userText = "Bunlar çok pahalı. 2 milyon bütçem var sadece.";
    const completed = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: [], revealedCandidateReferences: ["v1", "v2", "v3"] });
    expect(completed.candidateRejection).toEqual({ scope: "AMBIGUOUS", referenceText: "REVEALED_SET", sourceSpan: userText });
    expect(completed.acts).toContain("CANDIDATE_REJECTION");
  });
  it("does not interpret a bare amount as budget outside a budget-question context", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "3 milyon tl", activeFieldIds: [] }); expect(result.budgetMutations).toEqual([]); });
  it("activates only safe persona vocabulary and supports deactivation", () => { expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Premium ve şık olsun", activeFieldIds: [] }).personaMutations).toContainEqual(expect.objectContaining({ operation: "ACTIVATE", traits: ["PRESTIGE", "DESIGN"] })); expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Fark etmez", activeFieldIds: [] }).personaMutations).toContainEqual(expect.objectContaining({ operation: "DEACTIVATE" })); });
  it("creates a lookup-only model reference without resolving catalog truth", () => expect(enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Micra var mı?", activeFieldIds: [] }).modelReferences).toEqual([expect.objectContaining({ rawText: "Micra", parsedModelText: "Micra", purpose: "LOOKUP_ONLY" })]));
  it("makes simple consent decision-neutral even when the provider hallucinates mutations", () => { const polluted = { ...empty(), constraintMutations: [{ operation: "ADD", fieldId: "bodyStyle", normalizedValue: { operator: "EQUALS", value: "SUV" }, explicitness: "EXPLICIT_REQUIREMENT", confidence: 1, sourceSpan: "Göster" }] } as InterpretationResult; const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "Göster", activeFieldIds: [] }); expect(result.acts).toContain("OFFER_ACCEPTANCE"); expect(result.constraintMutations).toEqual([]); });
  it.each(["Göster bakalım", "Paylaş", "Paylaş bakalım", "Hadi görelim", "Seçenekleri göster", "Devam et öyleyse", "Edelim"])("binds natural consent phrase %s without decision mutations", (userText) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: ["fuelType"] }); expect(result.acts).toEqual(["OFFER_ACCEPTANCE"]); expect(result.constraintMutations).toEqual([]); });
  it("extracts two separately governed comparison references", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Araba almak istiyorum. Clio mu Civic mi kararsızım.", activeFieldIds: [] }); expect(result.acts).toContain("MODEL_COMPARISON_REQUEST"); expect(result.modelReferences).toEqual([expect.objectContaining({ rawText: "Clio", purpose: "COMPARISON_SCOPE" }), expect.objectContaining({ rawText: "Civic", purpose: "COMPARISON_SCOPE" })]); expect(result.directAnswerRequests).toContainEqual({ kind: "MODEL_COMPARISON" }); });
  it("treats a Caddy-style cargo analogy as usage intent rather than a model-suitability detour", () => { const polluted = { ...empty(), acts: ["MODEL_SUITABILITY_REQUEST"], directAnswerRequests: [{ kind: "MODEL_SUITABILITY" }], modelReferences: [{ rawText: "Caddy", parsedModelText: "Caddy", purpose: "PREFERENCE" }] } as InterpretationResult; const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "Caddy tarzı kapalı yük alanı olsun, dizel otomatik istiyorum", activeFieldIds: [] }); expect(result.acts).not.toContain("MODEL_SUITABILITY_REQUEST"); expect(result.directAnswerRequests[0]).toEqual({ kind: "RECOMMENDATION_REQUEST" }); expect(result.constraintMutations).toContainEqual(expect.objectContaining({ fieldId: "usageArchitecture" })); });
  it("treats general technical inexperience as tone context rather than a standalone explanation request", () => { const polluted: InterpretationResult = { ...empty(), acts: ["VEHICLE_INTENT", "SOCIAL_MESSAGE", "DONT_KNOW", "TECHNICAL_EXPLANATION_REQUEST"], directAnswerRequests: [{ kind: "TECHNICAL_EXPLANATION" }], socialSignal: { kind: "FIRST_CAR" }, technicalGuidanceRequest: { mode: "GUIDE_WITH_DAILY_LIFE" } }; const result = enforceInterpretationSemanticCompleteness({ result: polluted, userText: "Merhaba, ilk arabam olacak. Şehir içinde kullanacağım ve teknik terimleri bilmiyorum.", activeFieldIds: [] }); expect(result.acts).not.toContain("TECHNICAL_EXPLANATION_REQUEST"); expect(result.acts).not.toContain("DONT_KNOW"); expect(result.directAnswerRequests).not.toContainEqual({ kind: "TECHNICAL_EXPLANATION" }); expect(result.technicalGuidanceRequest).toBeUndefined(); });
  it("keeps a first-car discovery request active without requiring the literal word recommend", () => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText: "Merhaba, ilk arabam olacak. Şehir içinde kullanacağım.", activeFieldIds: [] }); expect(result.acts).toEqual(expect.arrayContaining(["VEHICLE_INTENT", "RECOMMENDATION_REQUEST"])); expect(result.directAnswerRequests).toContainEqual({ kind: "RECOMMENDATION_REQUEST" }); });
  it.each(["Araba alacağım", "Bana acil araba almam lazım", "İlk arabamı alacağım", "Oğluma ilk arabasını hediye edeceğim", "Şehir içinde kullanmak için araç lazım", "İş için araç almam gerekiyor", "Nasıl bir araba almalıyım bilmiyorum"])("keeps future-purchase discovery intent active for %s", (userText) => { const result = enforceInterpretationSemanticCompleteness({ result: empty(), userText, activeFieldIds: ["NEW_CAR_SCOPE"] }); expect(result.acts).toEqual(expect.arrayContaining(["VEHICLE_INTENT", "RECOMMENDATION_REQUEST"])); expect(result.directAnswerRequests).toContainEqual({ kind: "RECOMMENDATION_REQUEST" }); });
});
