import type { VehiclePersonaTrait } from "../domain/conversationEvent";
import type { HumanContextKind } from "../domain/humanContext";

export type JsonSafeValue = null | boolean | number | string | readonly JsonSafeValue[] | { readonly [key: string]: JsonSafeValue };

export const USER_ACTS = ["GREETING", "SOCIAL_MESSAGE", "VEHICLE_INTENT", "USAGE_STATEMENT", "PREFERENCE_STATEMENT", "HARD_REQUIREMENT", "BUDGET_STATEMENT", "MODEL_LOOKUP_REQUEST", "MODEL_COMPARISON_REQUEST", "MODEL_SUITABILITY_REQUEST", "ALTERNATIVE_REQUEST", "RECOMMENDATION_REQUEST", "TECHNICAL_EXPLANATION_REQUEST", "CORRECTION", "CANDIDATE_REJECTION", "OFFER_ACCEPTANCE", "OFFER_DECLINE", "POSITIVE_FEEDBACK", "NEGATIVE_FEEDBACK", "QUESTION_ANSWER", "DONT_KNOW", "DECLINE_TO_ANSWER", "OFF_TOPIC", "ABUSE", "CLOSING"] as const;
export type UserAct = typeof USER_ACTS[number];
export type ProviderActAuthority = "ADVISORY" | "STRUCTURAL" | "SAFETY_SIGNAL";
export type SemanticPolicyTraceCode = "PROVIDER_STRENGTH_DOWNGRADED_BY_POLICY" | "EXPLICIT_HARD_LANGUAGE_ENFORCED" | "CRITICAL_SEMANTIC_MUTATION_COMPLETED" | "UNSUPPORTED_PROVIDER_ACT_REMOVED";
export interface SemanticPolicyTraceEntry { readonly code: SemanticPolicyTraceCode; readonly act?: UserAct; readonly fieldId?: AllowedInterpretationFieldId }
export const ALLOWED_INTERPRETATION_FIELDS = ["usageScenario", "fuelType", "transmission", "bodyStyle", "drivenWheels", "seats", "luggageLitres", "cargoVolumeLitres", "payloadKg", "powerKw", "electricRangeKm", "combinedLitresPer100Km", "combinedKwhPer100Km", "usageArchitecture", "rearSeatPreference", "dailyLife", "comfort", "design"] as const;
export type AllowedInterpretationFieldId = typeof ALLOWED_INTERPRETATION_FIELDS[number];
export interface ProposedConstraintMutation { readonly operation: "ADD" | "CORRECT" | "CLEAR" | "DECLINE"; readonly fieldId: AllowedInterpretationFieldId; readonly normalizedValue: JsonSafeValue; readonly explicitness: "EXPLICIT_REQUIREMENT" | "EXPLICIT_PREFERENCE" | "GUIDED_APPROXIMATION" | "ILLUSTRATIVE"; readonly confidence: number; readonly sourceSpan: string; readonly supersedesFieldId?: AllowedInterpretationFieldId }
export interface ProposedBudgetMutation { readonly operation: "SET" | "CORRECT" | "CLEAR" | "EXCLUDE_FROM_DECISION"; readonly field: "AVAILABLE_CASH" | "PREFERRED_BUDGET" | "MAXIMUM_HARD_CEILING" | "FINANCE_FLEXIBILITY" | "UNRESOLVED_FINANCED_CEILING" | "BUDGET_UNKNOWN"; readonly value?: JsonSafeValue; readonly sourceSpan: string }
export interface ProposedModelReference { readonly rawText: string; readonly parsedBrandText?: string; readonly parsedModelText?: string; readonly purpose: "LOOKUP_ONLY" | "COMPARISON_SCOPE" | "PREFERENCE" | "HARD_SCOPE" }
export interface ProposedPersonaMutation { readonly operation: "ACTIVATE" | "DEACTIVATE"; readonly traits: readonly VehiclePersonaTrait[]; readonly sourceSpan: string }
export interface ProposedCandidateRejection { readonly scope: "EXACT_REVEALED" | "MODEL_FAMILY_EXPLICIT" | "BRAND_EXPLICIT" | "AMBIGUOUS"; readonly referenceText: string; readonly sourceSpan: string }
export interface DirectAnswerRequest { readonly kind: "MODEL_AVAILABILITY" | "MODEL_SUITABILITY" | "MODEL_COMPARISON" | "ALTERNATIVE_REQUEST" | "RECOMMENDATION_REQUEST" | "TECHNICAL_EXPLANATION" | "BUDGET_IMPACT" | "OTHER_SUPPORTED" }
export interface InterpretationResult { readonly schemaVersion: 1; readonly messageId: string; readonly acts: readonly UserAct[]; readonly directAnswerRequests: readonly DirectAnswerRequest[]; readonly constraintMutations: readonly ProposedConstraintMutation[]; readonly budgetMutations: readonly ProposedBudgetMutation[]; readonly modelReferences: readonly ProposedModelReference[]; readonly personaMutations: readonly ProposedPersonaMutation[]; readonly candidateRejection?: ProposedCandidateRejection; readonly technicalGuidanceRequest?: { readonly fieldId?: AllowedInterpretationFieldId; readonly mode: "EXPLAIN" | "GUIDE_WITH_DAILY_LIFE" }; readonly socialSignal?: { readonly kind: "GREETING" | "GENERAL" | HumanContextKind }; readonly offTopicSignal?: { readonly detected: true }; readonly abuseSignal?: { readonly detected: true }; readonly corrections: readonly { readonly fieldId: AllowedInterpretationFieldId; readonly sourceSpan: string }[]; readonly ambiguities: readonly { readonly code: string; readonly sourceSpan: string }[] }
export interface StructuredInterpretationRequest { readonly contractVersion: "1.0.0"; readonly messageId: string; readonly userMessageData: { readonly text: string }; readonly allowedFieldIds: readonly AllowedInterpretationFieldId[]; readonly instructions: readonly string[] }
export interface StructuredInterpretationModel { interpret(input: StructuredInterpretationRequest): Promise<unknown> }
export interface InterpretationDiagnostic { readonly code: "SCHEMA_INVALID" | "FIELD_NOT_HARD_FILTERABLE" | "HARD_LANGUAGE_NOT_EXPLICIT" | "DAILY_LIFE_MAPPING_UNAUTHORIZED" | "INVALID_BUDGET_SEMANTICS" | "PERSONA_SOURCE_NOT_EXPLICIT" | "REJECTION_SCOPE_UNBOUND" | "SUPERSESSION_TARGET_MISSING"; readonly reference?: string }
export interface ValidatedConstraintMutation extends ProposedConstraintMutation { readonly deterministicDecisionUse: "HARD_CANDIDATE" | "STRONG_OR_SOFT_RANK" | "GUIDED_ONLY" | "ILLUSTRATIVE_ONLY" }
export interface ValidatedInterpretation { readonly result: InterpretationResult; readonly acceptedConstraintMutations: readonly ValidatedConstraintMutation[]; readonly acceptedBudgetMutations: readonly ProposedBudgetMutation[]; readonly acceptedPersonaMutations: readonly ProposedPersonaMutation[]; readonly diagnostics: readonly InterpretationDiagnostic[] }
export interface AuthoritativeSemanticPlan extends ValidatedInterpretation { readonly authorityBoundary: "AUTHORITATIVE_SEMANTIC_PLAN"; readonly providerActs: readonly UserAct[]; readonly policyTrace: readonly SemanticPolicyTraceEntry[] }
