import { runCatalogIngestionFactory, sha256 } from "../catalog-ingestion";
import type { DiscoveryCandidateInput, DiscoverySnapshot } from "../catalog-ingestion/contracts";
import type { FactoryInput, IdentityResolution } from "./contracts";

export const CORDLESS_DRILL_WAVE_ID = "WU-CATALOG-FACTORY-CORDLESS-DRILL-REAL-WAVE-01" as const;
type Drill = { id: string; brand: string; model: string; sku: string; kit: string; platform: string; voltage: string; torque: string; impact: string; chuck: string; rpm: string; weight: string; compatibility: string; manufacturerUrl: string; retailerUrl?: string };

export const ACCEPTED_DRILLS: readonly Drill[] = Object.freeze([
  { id:"bosch-easyimpact-18v-40-06039d8100",brand:"Bosch DIY",model:"EasyImpact 18V-40",sku:"06039D8100",kit:"BARE: no battery/charger",platform:"POWER FOR ALL 18V",voltage:"18 V",torque:"38/20 Nm hard/soft; 40 Nm declared max",impact:"0-24,450 bpm",chuck:"13 mm keyless",rpm:"0-430 / 0-1,630",weight:"1.40 kg with battery; battery-dependent",compatibility:"PBA 18V >=1.5Ah / POWER FOR ALL Alliance",manufacturerUrl:"https://www.bosch-diy.com/tr/tr/p/easyimpact-18v-40-06039d8100" },
  { id:"bosch-gsb-18v-50-06019h5100",brand:"Bosch Professional",model:"GSB 18V-50",sku:"06019H5100",kit:"KIT: 2x2Ah, GAL18V-20, L-CASE",platform:"Professional 18V",voltage:"18 V",torque:"28/50 Nm soft/hard",impact:"0-27,000 bpm",chuck:"1.5-13 mm metal",rpm:"0-460 / 0-1,800",weight:"1.5 kg with battery",compatibility:"Bosch Professional 18V",manufacturerUrl:"https://www.bosch-professional.com/tr/tr/products/gsb-18v-50-06019H5100" },
  { id:"bosch-gsb-18v-110c-06019g030b",brand:"Bosch Professional",model:"GSB 18V-110 C",sku:"06019G030B",kit:"KIT: 2x4Ah ProCORE, charger, L-BOXX",platform:"Professional 18V / AMPShare",voltage:"18 V",torque:"47/85/110 Nm",impact:"0-31,500 bpm",chuck:"1.5-13 mm",rpm:"0-480 / 0-2,100",weight:"1.9 kg bare",compatibility:"Bosch Professional 18V and AMPShare",manufacturerUrl:"https://www.bosch-professional.com/tr/tr/products/gsb-18v-110-c-06019G030B" },
  { id:"makita-dhp484rtj",brand:"Makita",model:"DHP484RTJ",sku:"DHP484RTJ",kit:"KIT: 2x5Ah, DC18RC, Makpac",platform:"LXT 18V",voltage:"18 V",torque:"54/30 Nm hard/soft; 60 Nm lock",impact:"0-7,500 / 0-30,000 ipm",chuck:"1.5-13 mm",rpm:"0-500 / 0-2,000",weight:"1.5 kg net; 1.6-1.9 kg with battery",compatibility:"Makita LXT 18V",manufacturerUrl:"https://www.makita.com.tr/darbeli-matkap-vidalama-18v-p-da4e9d83-a459-4748-76d0-08daa04b0b98" },
  { id:"makita-dhp482rfe",brand:"Makita",model:"DHP482RFE",sku:"DHP482RFE",kit:"KIT: 2x3Ah BL1830B, DC18RC, case",platform:"LXT 18V",voltage:"18 V",torque:"62/36 Nm hard/soft",impact:"0-9,000 / 0-28,500 ipm",chuck:"1.5-13 mm",rpm:"0-600 / 0-1,900",weight:"1.5 kg net; battery-dependent",compatibility:"Makita LXT 18V; motor type UNKNOWN due source conflict",manufacturerUrl:"https://www.makita.com.tr/darbeli-matkap-vidalama-18v-p-8590ca23-711b-46cd-767c-08daa04b0b98" },
  { id:"dewalt-dcd796p2-qw",brand:"DeWalt",model:"DCD796P2-QW",sku:"DCD796P2-QW",kit:"KIT: 2x5Ah, DCB115, TSTAK",platform:"XR 18V",voltage:"18 V",torque:"70/27 Nm hard/soft",impact:"0-9,350 / 0-34,000 bpm",chuck:"1.5-13 mm metal",rpm:"0-550 / 0-2,000",weight:"UNKNOWN on exact TR page",compatibility:"DeWalt XR 18V",manufacturerUrl:"https://www.tr.dewalt.global/tr-tr/rnler/dcd796p2-qw/18v-50ah-li-ion-cift-akulu-komursuz-profesyonel-darbeli-matkap" },
  { id:"dewalt-dcd805nt-xj",brand:"DeWalt",model:"DCD805NT-XJ",sku:"DCD805NT-XJ",kit:"BARE with TSTAK; no battery/charger",platform:"XR 18V",voltage:"18 V",torque:"90 Nm",impact:"0-11,050 / 0-34,000 bpm",chuck:"1.5-13 mm",rpm:"0-650 / 0-2,000",weight:"1.34 kg bare",compatibility:"DeWalt XR 18V",manufacturerUrl:"https://www.tr.dewalt.global/tr-tr/rnler/dcd805nt-xj/18v-komursuz-darbeli-matkapakusuz-t-st" },
  { id:"milwaukee-m18-fpd3-502x",brand:"Milwaukee",model:"M18 FPD3-502X",sku:"4933479860",kit:"KIT: 2x5Ah M18 B5, M12-18 FC, HD box",platform:"M18",voltage:"18 V",torque:"158 Nm",impact:"0-33,000 bpm",chuck:"13 mm metal",rpm:"0-500 / 0-2,100",weight:"2.2 kg with M18 B5",compatibility:"All Milwaukee M18 batteries",manufacturerUrl:"https://www.milwaukeetool.eu/en-eu/m18-fuel-percussion-drill/m18-fpd3/",retailerUrl:"https://www.cdtmilwaukee.com/m18-fpd3-502x-akulu-darbmatkapvidalama-158-nm" },
  { id:"milwaukee-m18-blpdrc-502c",brand:"Milwaukee",model:"M18 BLPDRC-502C",sku:"4933492826",kit:"KIT: 2x5Ah, M12-18C, kitbox",platform:"M18",voltage:"18 V",torque:"60.5 Nm",impact:"0-25,500 bpm; TR source says 25,000",chuck:"13 mm metal",rpm:"0-550 / 0-1,700",weight:"1.5 kg with M18 B5",compatibility:"All Milwaukee M18 batteries",manufacturerUrl:"https://www.milwaukeetool.eu/en-eu/m18-compact-brushless-percussion-drill/m18-blpdrc/",retailerUrl:"https://www.724hirdavat.com/urun/milwaukee-m18-blpdrc-502c-akulu-darbeli-matkap-vidalama" },
  { id:"einhell-te-cd-18-50-solo-4514345",brand:"Einhell",model:"TE-CD 18/50 Li Solo",sku:"4514345",kit:"BARE",platform:"Power X-Change",voltage:"18 V",torque:"50 Nm",impact:"NO",chuck:"2-13 mm metal",rpm:"UNKNOWN",weight:"1.14 kg product",compatibility:"All Power X-Change batteries",manufacturerUrl:"https://www.einhell.com.tr/p/4514345-te-cd-18-50-li-solo/" },
  { id:"einhell-tp-cd-18-50-li-i-bl-solo-4513942",brand:"Einhell",model:"TP-CD 18/50 Li-i BL Solo",sku:"4513942",kit:"BARE",platform:"Power X-Change",voltage:"18 V",torque:"50 Nm",impact:"8,000 / 28,800 bpm",chuck:"2-13 mm metal",rpm:"UNKNOWN",weight:"1.19 kg product",compatibility:"All Power X-Change batteries",manufacturerUrl:"https://www.einhell.com.tr/p/4513942-tp-cd-18-50-li-i-bl-solo/" },
  { id:"einhell-tp-cd-18-60-li-bl-solo-4514210",brand:"Einhell",model:"TP-CD 18/60 Li BL Solo",sku:"4514210",kit:"BARE",platform:"Power X-Change",voltage:"18 V",torque:"60 Nm",impact:"NO",chuck:"2-13 mm metal",rpm:"0-500 / 0-2,000",weight:"1.3 kg product",compatibility:"All Power X-Change batteries",manufacturerUrl:"https://www.einhell.com.tr/p/4514210-tp-cd-18-60-li-bl-solo/" },
  { id:"einhell-tp-cd-18-60-li-i-bl-solo-4514205",brand:"Einhell",model:"TP-CD 18/60 Li-i BL Solo",sku:"4514205",kit:"BARE",platform:"Power X-Change",voltage:"18 V",torque:"60 Nm",impact:"8,000 / 32,000 bpm",chuck:"2-13 mm metal",rpm:"UNKNOWN",weight:"1.37 kg product",compatibility:"All Power X-Change batteries",manufacturerUrl:"https://www.einhell.com.tr/p/4514205-tp-cd-18-60-li-i-bl-solo/" },
  { id:"ryobi-rpd18bl1-0-5133006237",brand:"Ryobi",model:"RPD18BL1-0",sku:"5133006237",kit:"BARE",platform:"ONE+ 18V",voltage:"18 V",torque:"54 Nm",impact:"27,200 ipm",chuck:"13 mm metal",rpm:"0-450 / 0-1,700",weight:"UNKNOWN bare",compatibility:"Ryobi ONE+ 18V",manufacturerUrl:"https://static.ryobitools.eu/RyobiTools/media/MediaLibrary/RYOBI_18V_ONE-_MAXPOWER_Katalog_2024-1_SCREEN.pdf",retailerUrl:"https://www.koctas.com.tr/ryobi-rpd18bl1-0-akulu-komursuz-darbeli-matkap-aku-ve-sarj-cihazi-dahil-degildir-5133006237/p/5003053628" },
  { id:"ryobi-rpd18x1-0-5133006610",brand:"Ryobi",model:"RPD18X1-0",sku:"5133006610",kit:"BARE",platform:"ONE+ HP 18V",voltage:"18 V",torque:"105 Nm",impact:"11,200 / 34,400 ipm",chuck:"13 mm metal",rpm:"0-700 / 0-2,150",weight:"1.9 kg with RB1820C; bare UNKNOWN",compatibility:"Ryobi ONE+ 18V",manufacturerUrl:"https://static.ryobitools.eu/RyobiTools/media/MediaLibrary/Ryobi_OnePlus_Leaflet_HUNGARY.pdf?v=1772786656",retailerUrl:"https://www.hirdavatagaci.com/urun/ryobi-rpd18x1-0-18v-akulu-komursuz-darbeli-matkap-aku-dahil-degildir-5133006610-11973" },
  { id:"metabo-sb-18-l-bl-602331500",brand:"Metabo",model:"SB 18 L BL",sku:"602331500",kit:"KIT: 2x2Ah, SC30, case",platform:"CAS / Metabo 18V",voltage:"18 V",torque:"25/60 Nm soft/hard",impact:"26,000 bpm",chuck:"1.5-13 mm",rpm:"0-550 / 0-1,850",weight:"1.4 kg with battery",compatibility:"Metabo 18V / CAS subject to pack compatibility",manufacturerUrl:"https://www.metabo.com/t3/fileadmin/metabo/at/070_aktuell/02_kataloge_logos/2023_Sortimentsuebersicht_AT-screen.pdf",retailerUrl:"https://www.724magazam.com/urun/metabo-sb-18-l-bl-2-0-akulu-darbeli-matkap-ve-tornavida-2x2-0ah" },
]);

const unknowns = [
  { observationId:"unknown-dewalt-dcd805e2t-qw",rawLabel:"DeWalt DCD805E2T-QW: official page conflicts on battery capacity, included DCD800/DCD805 tool and speed",sourceUrl:"https://www.tr.dewalt.global/tr-tr/rnler/dcd805e2t-qw/18v-20ah-li-ion-cift-akulu-komursuz-pro",reasonCode:"OFFICIAL_KIT_CONTENT_CONFLICT" },
  { observationId:"unknown-einhell-4514217",rawLabel:"Einhell 4514217: official page conflicts on 2Ah/4Ah batteries and charger count",sourceUrl:"https://www.einhell.com.tr/p/4514217-te-cd-18-50-li-i-bl-2-4ah/",reasonCode:"OFFICIAL_KIT_CONTENT_CONFLICT" },
  { observationId:"unknown-ryobi-rpd18-252ta127",rawLabel:"Ryobi RPD18-252TA127: retailer-defined suffix lacks manufacturer SKU/EAN authority",sourceUrl:"https://www.arpakcistore.com/urun/ryobi-rpd18-252ta127-1x5ah-1x2ah-cift-akulu-darbeli-matkap",reasonCode:"RETAILER_BUNDLE_IDENTITY_UNVERIFIED" },
  { observationId:"unknown-amazon-tr-access",rawLabel:"Amazon Türkiye discovery/API access unavailable in this acquisition pass; no absence inferred",sourceUrl:"https://www.amazon.com.tr/",reasonCode:"AMAZON_ACCESS_BLOCKED" },
] as const;

const profile = (row: Drill) => `kit=${row.kit}; platform=${row.platform}; voltage=${row.voltage}; torque=${row.torque}; impact=${row.impact}; chuck=${row.chuck}; rpm=${row.rpm}; weight=${row.weight}; compatibility=${row.compatibility}`;
export function buildCordlessDrillWaveInput(): FactoryInput {
  const snapshots: DiscoverySnapshot[] = ACCEPTED_DRILLS.map(row => { const content = `${row.brand} ${row.model} ${row.sku} ${profile(row)}`; return { snapshotId:`mfr-${row.id}`,schemaVersion:"discovery-snapshot/v1",sourceClass:row.manufacturerUrl.endsWith(".pdf")||row.manufacturerUrl.includes(".pdf?")?"MANUFACTURER_DOCUMENT":"MANUFACTURER_PRODUCT_PAGE",sourceUrl:row.manufacturerUrl,retrievedAt:"2026-09-06T18:00:00.000Z",market:"TR",locator:`exact model/SKU ${row.sku}`,contentDigest:sha256(content),content }; });
  const candidates: DiscoveryCandidateInput[] = ACCEPTED_DRILLS.map(row => ({ candidateId:row.id,identity:{department:"DURABLE_GOODS_CANDIDATE",category:"CORDLESS_DRILL",manufacturer:row.brand,model:row.model,variant:row.sku,manufacturerPartNumber:row.sku},discoverySnapshotIds:[`mfr-${row.id}`],identityEvidenceSnapshotIds:[`mfr-${row.id}`],claims:[{claimId:`profile-${row.id}`,field:"technicalProfile",value:profile(row),evidenceSnapshotIds:[`mfr-${row.id}`],decisionMaterial:true}] }));
  const ingestion = runCatalogIngestionFactory({ runId:CORDLESS_DRILL_WAVE_ID,createdAt:"2026-09-06T18:00:00.000Z",snapshots,candidates }); if(ingestion.status!=="READY") throw new Error(ingestion.errors.join(","));
  const retailerRows=ACCEPTED_DRILLS.filter((row):row is Drill & {retailerUrl:string}=>Boolean(row.retailerUrl));
  const observations = [...ACCEPTED_DRILLS.map(row => ({ observationId:`mfr-${row.id}`,departmentId:"DURABLE_GOODS_CANDIDATE",categoryId:"CORDLESS_DRILL",sourceUrl:row.manufacturerUrl,sourceClass:(row.manufacturerUrl.includes(".pdf")?"OFFICIAL_MANUAL":"MANUFACTURER_PRODUCT") as "OFFICIAL_MANUAL"|"MANUFACTURER_PRODUCT",observedAt:"2026-09-06T18:00:00.000Z",freshnessUntil:"2027-03-06T18:00:00.000Z",rawLabel:`${row.brand} ${row.model} ${row.sku}`,identifiers:{brand:row.brand,model:row.model,exactVariant:row.sku,sku:row.sku} })),...retailerRows.map(row=>({observationId:`retail-${row.id}`,departmentId:"DURABLE_GOODS_CANDIDATE",categoryId:"CORDLESS_DRILL",sourceUrl:row.retailerUrl,sourceClass:"RELIABLE_TR_RETAILER" as const,observedAt:"2026-09-06T18:00:00.000Z",freshnessUntil:"2026-09-13T18:00:00.000Z",rawLabel:`Türkiye sale presence: ${row.brand} ${row.model} ${row.sku}`,identifiers:{brand:row.brand,model:row.model,exactVariant:row.sku,sku:row.sku}})),...unknowns.map(row=>({observationId:row.observationId,departmentId:"DURABLE_GOODS_CANDIDATE",categoryId:"CORDLESS_DRILL",sourceUrl:row.sourceUrl,sourceClass:(row.observationId.includes("amazon")?"AMAZON_TR_COMMERCE":"RELIABLE_TR_RETAILER") as "AMAZON_TR_COMMERCE"|"RELIABLE_TR_RETAILER",observedAt:"2026-09-06T18:00:00.000Z",freshnessUntil:"2026-09-13T18:00:00.000Z",rawLabel:row.rawLabel,identifiers:{}}))];
  const identities: IdentityResolution[] = [...ACCEPTED_DRILLS.map(row=>({observationId:`mfr-${row.id}`,outcome:"EXACT" as const,exactProductId:`durable:cordless-drill:${row.id}`,reasonCode:"EXACT_MANUFACTURER_MODEL_SKU"})),...retailerRows.map(row=>({observationId:`retail-${row.id}`,outcome:"EXACT" as const,exactProductId:`durable:cordless-drill:${row.id}`,reasonCode:"RETAIL_SALE_PRESENCE_MATCHED_TO_MANUFACTURER_SKU"})),...unknowns.map(row=>({observationId:row.observationId,outcome:"UNKNOWN" as const,reasonCode:row.reasonCode}))];
  return { schemaVersion:"catalog-factory-input/v0.1",ingestion,taxonomy:[{departmentId:"DURABLE_GOODS_CANDIDATE",categoryId:"CORDLESS_DRILL",publicLabelTr:"Akülü matkap ve akülü darbeli matkap",riskFlags:[]}],observations,identities,evidence:ACCEPTED_DRILLS.map(row=>({exactProductId:`durable:cordless-drill:${row.id}`,factKey:"technicalProfile",value:profile(row),sourceObservationIds:[`mfr-${row.id}`],evidenceClasses:[row.manufacturerUrl.includes(".pdf")?"OFFICIAL_MANUAL":"MANUFACTURER_PRODUCT"],authority:"PRIMARY"})),semantics:ACCEPTED_DRILLS.map(row=>({exactProductId:`durable:cordless-drill:${row.id}`,factKeys:["technicalProfile"],dailyLife:`${row.kit}; ${row.torque}; ${row.weight}. Darbe bilgisi: ${row.impact}.`,needs:["batarya platformu uyumu","duvar delme gerekiyorsa darbeli mod","taşıma ve uzun çalışma dengesi"],possibleHardFilters:["bare veya kit","batarya platformu","darbeli mod","minimum tork","mandren kapasitesi"],materialDiscriminators:["kitContents","batteryPlatform","torque","impactRate","chuck","rpm","weight"],status:"SUPPORTED"})),personas:ACCEPTED_DRILLS.map(row=>({exactProductId:`durable:cordless-drill:${row.id}`,hierarchy:["DIY_AND_TRADE","CORDLESS_TOOL",row.impact==="NO"?"DRILL_DRIVER":"IMPACT_DRILL_DRIVER",row.kit.startsWith("BARE")?"EXISTING_PLATFORM_OWNER":"FIRST_KIT_BUYER"],evidenceClasses:["MANUFACTURER_PRODUCT"],aggregateSoftScore:0.6,authority:"SOFT_RANKING_ONLY"})),commerceMedia:retailerRows.map(row=>({exactProductId:`durable:cordless-drill:${row.id}`,offers:[{retailer:new URL(row.retailerUrl).hostname,stock:"UNKNOWN",observedAt:"2026-09-06T18:00:00.000Z",sourceObservationId:`retail-${row.id}`}],media:[],technicalEvidenceDigest:null})) };
}
