import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import catalog from "@/data/production/catalog/releases/v0.55.1/catalog.json";
import batch from "@/data/production/equipment-evidence/pilots/pilot-v1.0.1-catalog-v0.55.1-2026-08-18/batch-001-manifest.json";
import lifecycle from "@/data/production/equipment-evidence/pilots/pilot-v1.0.0-catalog-v0.55.1-2026-08-18/lifecycle.json";
import matrix from "@/data/production/equipment-evidence/pilots/pilot-v1.0.1-catalog-v0.55.1-2026-08-18/pilot-matrix.json";
import manifest from "@/data/production/equipment-evidence/pilots/pilot-v1.0.1-catalog-v0.55.1-2026-08-18/pilot-manifest.json";
import oldManifest from "@/data/production/equipment-evidence/pilots/pilot-v1.0.0-catalog-v0.55.1-2026-08-18/pilot-manifest.json";
import priceProjection from "@/data/production/equipment-evidence/pilots/pilot-v1.0.1-catalog-v0.55.1-2026-08-18/price-segmentation-reference.json";
import type { EquipmentEvidenceAssertion, EquipmentReviewEvent } from "@/types/equipmentEvidence";
import { EQUIPMENT_FEATURE_CODES } from "@/types/equipmentEvidence";
import { createCanonicalPackageId, createCanonicalTrimId } from "./equipmentCanonicalIdentity";
import { createEquipmentOperationalRecordId, EQUIPMENT_OPERATION_IDS, EQUIPMENT_SOURCE_PRIORITY_POLICY_V1, validateEquipmentEvidenceLocator, validateResearchLedger, validateReviewEvents } from "./equipmentCollectionProtocol";
import { selectEquipmentPilot, type PilotPriceSegment } from "./equipmentPilotSelection";

const source = { sourceId: "SRC-000001", registryRelease: "v0.4.0", sourceType: "OFFICIAL_EQUIPMENT_LIST" as const, sourceAuthority: "OFFICIAL_PRICE_EQUIPMENT_LIST" as const, originalUrl: "https://example.com/equipment.pdf", artifactReference: "snapshots/SRC-000001/equipment.pdf", artifactSha256: `sha256:${"a".repeat(64)}` as const, observedAt: "2026-08-18T00:00:00.000Z" };
const negative: EquipmentEvidenceAssertion = { assertionId: "A-NEG", featureCode: "REAR_VIEW_CAMERA", exactVariantId: catalog.records[0].variant.id, sourceApplicability: "EXACT_VARIANT", source, locator: { kind: "PDF_PAGE", pageNumber: 3, table: "Equipment", row: "Camera" }, market: "TR", modelYearFrom: 2026, modelYearTo: 2026, evidencePolarity: "NEGATIVE", negativeEvidenceReason: "OFFICIAL_EQUIPMENT_MATRIX_EXPLICIT_ABSENCE", availabilityStatus: "NOT_AVAILABLE", provisionMode: "NOT_OFFERED", verificationState: "VERIFIED", confidence: "HIGH", conflictState: "CLEAR" };
const event = (overrides: Partial<EquipmentReviewEvent>): EquipmentReviewEvent => ({ reviewEventId: "R1", subjectType: "ASSERTION", subjectId: "A-NEG", toState: "COLLECTED", actorRole: "EQUIPMENT_COLLECTOR_PRIMARY", actorInstanceId: "ACTOR-COLLECTOR-1", reviewedAt: "2026-08-18T00:00:00.000Z", reasonCode: "COLLECTED", ...overrides });
const validReview = (subjectType: EquipmentReviewEvent["subjectType"] = "ASSERTION", subjectId = "A-NEG"): EquipmentReviewEvent[] => [
  event({ subjectType, subjectId }),
  event({ reviewEventId: "R2", subjectType, subjectId, fromState: "COLLECTED", toState: "SECOND_REVIEW_REQUIRED", actorRole: "EQUIPMENT_REVIEWER_SECONDARY", actorInstanceId: "ACTOR-COORDINATOR", reviewedAt: "2026-08-18T00:01:00.000Z" }),
  event({ reviewEventId: "R3", subjectType, subjectId, fromState: "SECOND_REVIEW_REQUIRED", toState: "SECOND_REVIEW_PASSED", actorRole: "EQUIPMENT_REVIEWER_SECONDARY", actorInstanceId: "ACTOR-REVIEWER-2", reviewedAt: "2026-08-18T00:02:00.000Z" }),
];
const priceSegments = Object.fromEntries(priceProjection.projections.map((item) => [item.exactVariantId, item.globalCatalogPriceSegment === "LOWEST_20" || item.globalCatalogPriceSegment === "VALUE_20_40" ? "MAINSTREAM" : item.globalCatalogPriceSegment === "MID_40_60" ? "MID" : "HIGH"])) as Record<string, PilotPriceSegment>;

describe("Equipment Evidence V1.2.1 pilot operations", () => {
  it("validates structured locators", () => { expect(validateEquipmentEvidenceLocator({ kind: "PDF_PAGE", pageNumber: 1 })).toEqual([]); expect(validateEquipmentEvidenceLocator({ kind: "HTML_SECTION" })).toContain("HTML_LOCATOR_EMPTY"); });
  it("keeps NOT_RESEARCHED assertion-free", () => { expect(validateResearchLedger([{ ledgerEntryId: "EE-RES-X", exactVariantId: "V1", featureCode: "LANE_KEEP_ASSIST", disposition: "NOT_RESEARCHED", researchCycleId: EQUIPMENT_OPERATION_IDS.researchCycleId, updatedAt: "2026-08-18T00:00:00.000Z", sourceIds: [], assertionIds: [], collectorRole: "EQUIPMENT_COLLECTOR_PRIMARY", collectorInstanceId: "ACTOR-COLLECTOR-1" }])).toEqual([]); });
  it("requires second review for negative assertions", () => { expect(validateReviewEvents([], [negative])).toContain("NEGATIVE_ASSERTION_SECOND_REVIEW_MISSING"); });
  it("rejects direct collector self-review", () => { const events = validReview(); events[2] = event({ ...events[2], actorInstanceId: "ACTOR-COLLECTOR-1" }); expect(validateReviewEvents(events, [negative])).toContain("SELF_REVIEW_NOT_ALLOWED"); });
  it("rejects collector self-review even after an intermediate actor event", () => { const events = validReview(); events[1] = event({ ...events[1], actorInstanceId: "ACTOR-COORDINATOR-OTHER" }); events[2] = event({ ...events[2], actorInstanceId: "ACTOR-COLLECTOR-1" }); expect(validateReviewEvents(events, [negative])).toContain("SELF_REVIEW_NOT_ALLOWED"); });
  it("accepts an independent secondary reviewer", () => { expect(validateReviewEvents(validReview(), [negative])).toEqual([]); });
  it("applies self-review protection to trim and package links", () => { for (const subjectType of ["TRIM_LINK", "PACKAGE_LINK"] as const) { const events = validReview(subjectType, "LINK-1"); events[2] = event({ ...events[2], subjectType, subjectId: "LINK-1", actorInstanceId: "ACTOR-COLLECTOR-1" }); expect(validateReviewEvents(events, [])).toContain("SELF_REVIEW_NOT_ALLOWED"); } });
  it("requires the owner role and independent actor for owner approval", () => { const events = [...validReview(), event({ reviewEventId: "R4", fromState: "SECOND_REVIEW_PASSED", toState: "OWNER_APPROVAL_REQUIRED", actorRole: "EQUIPMENT_REVIEWER_SECONDARY", actorInstanceId: "ACTOR-REVIEWER-2", reviewedAt: "2026-08-18T00:03:00.000Z" }), event({ reviewEventId: "R5", fromState: "OWNER_APPROVAL_REQUIRED", toState: "APPROVED", actorRole: "EQUIPMENT_REVIEWER_SECONDARY", actorInstanceId: "ACTOR-REVIEWER-2", reviewedAt: "2026-08-18T00:04:00.000Z" })]; expect(validateReviewEvents(events, [negative])).toEqual(expect.arrayContaining(["OWNER_APPROVAL_ROLE_INVALID", "OWNER_APPROVER_NOT_INDEPENDENT"])); });
  it("creates deterministic collision-scoped IDs", () => { expect(createEquipmentOperationalRecordId("EE-AST", "stable-key")).toBe(createEquipmentOperationalRecordId("EE-AST", "stable-key")); expect(createEquipmentOperationalRecordId("EE-AST", "stable-key")).not.toBe(createEquipmentOperationalRecordId("EE-RES", "stable-key")); });
  it("keeps canonical trim/package identities context-scoped", () => { const trim = { market: "TR", brand: "Örnek", modelFamily: "X", modelYear: 2026, trimName: "Premium" }; expect(createCanonicalTrimId(trim)).not.toBe(createCanonicalTrimId({ ...trim, modelYear: 2027 })); const pkg = { market: "TR", brand: "Örnek", modelFamily: "X", modelYearFrom: 2026, modelYearTo: 2026, packageName: "Tech" }; expect(createCanonicalPackageId(pkg)).not.toBe(createCanonicalPackageId({ ...pkg, revision: "R2" })); });
  it("preserves old manifest bytes and marks it superseded before collection", () => { expect(readFileSync("data/production/equipment-evidence/pilots/pilot-v1.0.0-catalog-v0.55.1-2026-08-18/pilot-manifest.json", "utf8")).toBe(`${JSON.stringify(oldManifest, null, 2)}\n`); expect(lifecycle).toMatchObject({ lifecycleState: "SUPERSEDED_BEFORE_COLLECTION", reason: "PILOT_DISTRIBUTION_AND_PAIRED_TRIM_COVERAGE_INSUFFICIENT", researchStartedAt: null }); });
  it("regenerates the exact immutable v1.0.1 manifest against its pinned catalog fixture", () => { expect(selectEquipmentPilot({ records: catalog.records, priceSegments, catalogFingerprint: manifest.catalogFingerprint as `sha256:${string}`, generatedAt: manifest.generatedAt, count: 28 })).toEqual(manifest); });
  it("meets body architecture minima", () => { const count = (pattern: RegExp) => manifest.variants.filter((item) => pattern.test(item.bodyStyle)).length; expect(count(/sedan/iu)).toBeGreaterThanOrEqual(3); expect(count(/hatchback/iu)).toBeGreaterThanOrEqual(3); expect(count(/suv|crossover/iu)).toBeGreaterThanOrEqual(5); expect(count(/coupe|liftback/iu)).toBeGreaterThanOrEqual(1); expect(count(/^mpv$/iu)).toBeGreaterThanOrEqual(1); expect(count(/passenger van/iu)).toBeGreaterThanOrEqual(1); expect(count(/panel van/iu)).toBeGreaterThanOrEqual(1); expect(count(/pickup|off.?road/iu)).toBeGreaterThanOrEqual(1); });
  it("meets fuel minima including PHEV and BEV cap", () => { const count = (fuel: string) => manifest.variants.filter((item) => item.fuelType === fuel).length; for (const [fuel, minimum] of [["GASOLINE", 3], ["DIESEL", 3], ["HEV", 3], ["PHEV", 2], ["MHEV", 2], ["LPG", 1], ["BEV", 5]] as const) expect(count(fuel)).toBeGreaterThanOrEqual(minimum); expect(count("BEV")).toBeLessThanOrEqual(10); });
  it("contains three exact paired families", () => { const pairs = new Map<string, typeof manifest.variants>(); for (const item of manifest.variants.filter((entry) => entry.pairedFamilyId)) pairs.set(item.pairedFamilyId!, [...(pairs.get(item.pairedFamilyId!) ?? []), item]); expect(pairs.size).toBeGreaterThanOrEqual(3); expect([...pairs.values()].every((items) => items.length === 2 && items[0]!.pairedExactVariantId === items[1]!.exactVariantId && items[1]!.pairedExactVariantId === items[0]!.exactVariantId)).toBe(true); });
  it("pins 28 variants, 1428 untouched matrix rows and the historical v0.55.1 fingerprint", () => { expect(manifest).toMatchObject({ pilotId: "EE-PILOT-001", lifecycleState: "PREPARED", researchStartedAt: null, completedAt: null, catalogFingerprint: "sha256:96f318680dd788c9df0827cbe3ce5635a36a5f1b354ab8fc7e6654bfa3ddc07e" }); expect(manifest.variants).toHaveLength(28); expect(matrix).toHaveLength(28 * 51); expect(matrix.every((item) => item.disposition === "NOT_RESEARCHED")).toBe(true); });
  it("defines batch 001 as one paired family and all 51 features", () => { const selected = manifest.variants.filter((item) => batch.exactVariantIds.includes(item.exactVariantId)); expect(batch).toMatchObject({ batchId: "EE-PILOT-001-BATCH-001", researchCycleId: "EE-PILOT-001-CYCLE-001", lifecycleState: "PREPARED", researchStartedAt: null, completedAt: null }); expect(selected).toHaveLength(2); expect(selected[0]!.pairedFamilyId).toBe(selected[1]!.pairedFamilyId); expect(batch.featureCodes).toEqual(EQUIPMENT_FEATURE_CODES); });
  it("pins source priority to official evidence only", () => { expect(EQUIPMENT_SOURCE_PRIORITY_POLICY_V1).toEqual(["OFFICIAL_TR_EQUIPMENT_LIST", "OFFICIAL_TR_CONFIGURATOR", "OFFICIAL_TR_TECH_SPEC", "OFFICIAL_TR_BROCHURE", "OFFICIAL_TR_DISTRIBUTOR_PRODUCT_PAGE", "GLOBAL_MANUFACTURER_WITH_EXPLICIT_TR_APPLICABILITY"]); });
});
