import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import catalog from "@/data/production/catalog/releases/v0.55.1/catalog.json";
import activePointer from "@/data/production/equipment-evidence/active.json";
import payloadJson from "@/data/production/equipment-evidence/releases/v1.2.1-catalog-v0.55.1-2026-08-18/equipment-evidence.json";
import manifestJson from "@/data/production/equipment-evidence/releases/v1.2.1-catalog-v0.55.1-2026-08-18/manifest.json";
import type { EquipmentAvailabilityStatus, EquipmentEvidenceAssertion, EquipmentEvidenceLayer, EquipmentEvidenceManifest, EquipmentFeatureCode, EquipmentProvisionMode } from "@/types/equipmentEvidence";
import { parseEquipmentEvidenceLayer } from "./equipmentEvidenceSchema";
import { assertActiveEquipmentEvidenceCompatibility, getEquipmentFeatureDefinition, getVariantEquipmentFeatures, loadActiveEquipmentEvidenceLayer, resolveEquipmentRequirement } from "./equipmentEvidenceResolver";
import { projectEquipmentEvidence } from "./projectEquipmentEvidence";
import { calculateEquipmentFeatureCoverage } from "./equipmentEvidenceCoverage";
import { evaluateEquipmentCandidateEffect } from "./equipmentCandidateEffect";
import { equipmentEvidenceSha256, validateEquipmentEvidenceCompatibility, validateEquipmentEvidenceLayer } from "./validateEquipmentEvidenceLayer";

const layer = payloadJson as EquipmentEvidenceLayer, manifest = manifestJson as EquipmentEvidenceManifest;
const variant = { exactVariantId: catalog.records[0].variant.id, modelYear: catalog.records[0].variant.modelYear.value, market: "TR" as const };
const provision: Record<EquipmentAvailabilityStatus, EquipmentProvisionMode> = { STANDARD: "INCLUDED", OPTIONAL: "FACTORY_OPTION", PACKAGE_DEPENDENT: "PACKAGE_OPTION", NOT_AVAILABLE: "NOT_OFFERED", UNKNOWN: "UNRESOLVED" };
const source = { sourceId: "SRC-000001", registryRelease: "v0.4.0", sourceType: "OFFICIAL_EQUIPMENT_LIST" as const, sourceAuthority: "OFFICIAL_PRICE_EQUIPMENT_LIST" as const, originalUrl: "https://example.com/equipment.pdf", artifactReference: "data/cars/vehicle_evidence/source_snapshots/SRC-000001/2026-08-18/equipment.pdf", artifactSha256: `sha256:${"a".repeat(64)}` as const, observedAt: "2026-08-18T00:00:00.000Z" };
const assertion = (overrides: Partial<EquipmentEvidenceAssertion> = {}): EquipmentEvidenceAssertion => ({ assertionId: "AST-1", featureCode: "REAR_VIEW_CAMERA", exactVariantId: variant.exactVariantId, sourceApplicability: "EXACT_VARIANT", source, locator: { kind: "PDF_PAGE", pageNumber: 7, table: "Equipment" }, market: "TR", modelYearFrom: variant.modelYear, modelYearTo: variant.modelYear, evidencePolarity: "POSITIVE", availabilityStatus: "STANDARD", provisionMode: "INCLUDED", verificationState: "VERIFIED", confidence: "HIGH", conflictState: "CLEAR", ...overrides });
const project = (assertions: readonly EquipmentEvidenceAssertion[], featureCode: EquipmentFeatureCode = "REAR_VIEW_CAMERA", packageLinks: Parameters<typeof projectEquipmentEvidence>[0]["packageLinks"] = [], trimLinks: Parameters<typeof projectEquipmentEvidence>[0]["trimLinks"] = []) => projectEquipmentEvidence({ variant, featureCode, assertions, packageLinks, trimLinks });

describe("Equipment Evidence production layer V1", () => {
  it("1. keeps UNKNOWN distinct from NOT_AVAILABLE", () => { expect(provision.UNKNOWN).toBe("UNRESOLVED"); expect(provision.UNKNOWN).not.toBe(provision.NOT_AVAILABLE); });
  it("2. keeps OPTIONAL distinct from STANDARD", () => { const result = project([assertion({ availabilityStatus: "OPTIONAL", provisionMode: "FACTORY_OPTION" })]); expect(result?.availabilityStatus).toBe("OPTIONAL"); expect(result?.availabilityStatus).not.toBe("STANDARD"); });
  it("3. does not project a package assertion without an exact verified package link", () => { expect(project([assertion({ exactVariantId: undefined, sourceApplicability: "EXACT_TRIM", packageName: "Tech", availabilityStatus: "PACKAGE_DEPENDENT", provisionMode: "PACKAGE_OPTION" })])).toBeUndefined(); });
  it("4. does not apply evidence from another model year", () => { expect(project([assertion({ modelYearFrom: variant.modelYear + 1, modelYearTo: variant.modelYear + 1 })])).toBeUndefined(); });
  it("5. does not apply evidence from another market", () => { expect(project([assertion({ market: "DE" })])).toBeUndefined(); });
  it("6. does not project model-family evidence", () => { expect(project([assertion({ exactVariantId: undefined, sourceApplicability: "MODEL_FAMILY" })])).toBeUndefined(); });
  it("7. converts conflicting exact evidence to UNKNOWN and INSUFFICIENT", () => { const result = project([assertion(), assertion({ assertionId: "AST-2", availabilityStatus: "NOT_AVAILABLE", provisionMode: "NOT_OFFERED" })]); expect(result).toMatchObject({ availabilityStatus: "UNKNOWN", projectionAuthority: "INSUFFICIENT", conflictState: "CONFLICTING" }); });
  it("8. excludes superseded assertions", () => { expect(project([assertion({ conflictState: "SUPERSEDED" })])).toBeUndefined(); });
  it("9. resolves exact verified STANDARD evidence", () => { expect(project([assertion()])).toMatchObject({ availabilityStatus: "STANDARD", projectionAuthority: "EXACT_VERIFIED", conflictState: "CLEAR" }); });
  it("10. resolves exact verified NOT_AVAILABLE evidence", () => { expect(project([assertion({ availabilityStatus: "NOT_AVAILABLE", provisionMode: "NOT_OFFERED", evidencePolarity: "NEGATIVE", negativeEvidenceReason: "OFFICIAL_EQUIPMENT_MATRIX_EXPLICIT_ABSENCE" })])).toMatchObject({ availabilityStatus: "NOT_AVAILABLE", projectionAuthority: "EXACT_VERIFIED" }); });
  it("11. rejects feature codes outside the closed vocabulary", () => { const changed = JSON.parse(JSON.stringify(layer)); changed.featureDefinitions[0].featureCode = "MAGIC_SEAT"; expect(() => parseEquipmentEvidenceLayer(changed)).toThrow(); });
  it("12. rejects source authority outside its closed vocabulary", () => { const changed = JSON.parse(JSON.stringify(layer)); changed.assertions = [{ ...assertion(), source: { ...source, sourceAuthority: "BLOG" } }]; expect(() => parseEquipmentEvidenceLayer(changed)).toThrow(); });
  it("13. fails checksum validation for changed payload bytes", () => { expect(validateEquipmentEvidenceCompatibility({ layer, manifest, rawPayload: `${JSON.stringify(layer)}\nchanged`, catalogRelease: "v0.55.1", catalogFingerprint: manifest.compatibleCatalogFingerprint, catalogVariantIds: catalog.records.map((item) => item.variant.id) }).some((item) => item.code === "PAYLOAD_CHECKSUM_MISMATCH")).toBe(true); });
  it("14. fails closed on catalog fingerprint mismatch", () => { expect(validateEquipmentEvidenceCompatibility({ layer, manifest, rawPayload: readFileSync("data/production/equipment-evidence/releases/v1.2.1-catalog-v0.55.1-2026-08-18/equipment-evidence.json", "utf8"), catalogRelease: "v0.55.1", catalogFingerprint: "sha256:wrong", catalogVariantIds: catalog.records.map((item) => item.variant.id) }).some((item) => item.code === "CATALOG_FINGERPRINT_MISMATCH")).toBe(true); });
  it("15. leaves the technical catalog untouched when equipment coverage is empty", () => { expect(layer.projections).toEqual([]); expect(catalog.records).toHaveLength(577); });
  it("16. resolver only returns data and never selects or ranks candidates", () => { expect(getVariantEquipmentFeatures(variant.exactVariantId)).toEqual([]); expect(Object.keys(loadActiveEquipmentEvidenceLayer())).toEqual(["layer", "manifest", "release"]); });
  it("17. does not turn OPTIONAL into a concrete stock-presence claim", () => { expect(project([assertion({ availabilityStatus: "OPTIONAL", provisionMode: "FACTORY_OPTION" })])).toMatchObject({ availabilityStatus: "OPTIONAL", provisionMode: "FACTORY_OPTION" }); });
  it("18. rejects a projection without assertion provenance", () => { const changed = { ...layer, projections: [{ exactVariantId: variant.exactVariantId, featureCode: "REAR_VIEW_CAMERA", availabilityStatus: "STANDARD", provisionMode: "INCLUDED", decisionUse: "HARD_FILTER_ELIGIBLE", assertionIds: [], projectionAuthority: "EXACT_VERIFIED", conflictState: "CLEAR" }] } as EquipmentEvidenceLayer; expect(validateEquipmentEvidenceLayer(changed).some((item) => item.code === "PROJECTION_PROVENANCE_INVALID")).toBe(true); });
  it("19. never silently merges opposing exact assertions", () => { const result = project([assertion(), assertion({ assertionId: "AST-2", availabilityStatus: "NOT_AVAILABLE", provisionMode: "NOT_OFFERED" })]); expect(result?.assertionIds).toEqual(["AST-1", "AST-2"]); expect(result?.conflictState).toBe("CONFLICTING"); });
  it("20. keeps the empty production release decision-neutral and compatible", () => { expect(() => assertActiveEquipmentEvidenceCompatibility()).not.toThrow(); expect(activePointer.payloadSha256).toBe(equipmentEvidenceSha256(readFileSync(`data/production/equipment-evidence/releases/${activePointer.activeEquipmentEvidenceRelease}/equipment-evidence.json`, "utf8"))); expect(getEquipmentFeatureDefinition("LANE_KEEP_ASSIST")?.defaultDecisionUse).toBe("HARD_FILTER_AFTER_CONFIRMATION"); expect(resolveEquipmentRequirement("kendi kendine park etsin")[0]?.featureCode).toBe("AUTOMATIC_PARK_ASSIST"); });
  it("21. projects a verified package only through canonical package identity", () => { const item = assertion({ assertionId: "AST-P", exactVariantId: undefined, sourceApplicability: "EXACT_TRIM", canonicalTrimId: "TRIM-1", packageName: "Tech", canonicalPackageId: "PKG-1", availabilityStatus: "PACKAGE_DEPENDENT", provisionMode: "PACKAGE_OPTION" }); const result = project([item], "REAR_VIEW_CAMERA", [{ linkId: "L-1", exactVariantId: variant.exactVariantId, packageName: "Different display name", canonicalPackageId: "PKG-1", market: "TR", modelYearFrom: variant.modelYear, modelYearTo: variant.modelYear, mandatoryInCanonicalVariant: false, assertionIds: ["AST-P"], verificationState: "VERIFIED" }]); expect(result).toMatchObject({ availabilityStatus: "PACKAGE_DEPENDENT", projectionAuthority: "PACKAGE_VERIFIED" }); });
  it("22. promotes a package feature only when the canonical package is mandatory", () => { const item = assertion({ assertionId: "AST-P", exactVariantId: undefined, sourceApplicability: "EXACT_TRIM", canonicalTrimId: "TRIM-1", packageName: "Tech", canonicalPackageId: "PKG-1", availabilityStatus: "PACKAGE_DEPENDENT", provisionMode: "PACKAGE_OPTION" }); const result = project([item], "REAR_VIEW_CAMERA", [{ linkId: "L-1", exactVariantId: variant.exactVariantId, packageName: "Tech", canonicalPackageId: "PKG-1", market: "TR", modelYearFrom: variant.modelYear, modelYearTo: variant.modelYear, mandatoryInCanonicalVariant: true, assertionIds: ["AST-P"], verificationState: "VERIFIED" }]); expect(result).toMatchObject({ availabilityStatus: "STANDARD", provisionMode: "INCLUDED", projectionAuthority: "PACKAGE_VERIFIED" }); });
  it("23. rejects unjustified NOT_AVAILABLE", () => { const changed = { ...layer, assertions: [assertion({ availabilityStatus: "NOT_AVAILABLE", provisionMode: "NOT_OFFERED" })] }; expect(validateEquipmentEvidenceLayer(changed).some((item) => item.code === "NEGATIVE_EVIDENCE_JUSTIFICATION_REQUIRED")).toBe(true); });
  it("24. is order-independent", () => { const a = assertion(), b = assertion({ assertionId: "AST-2" }); expect(project([a, b])).toEqual(project([b, a])); });
  it("25. treats negated intent as negated, not desired", () => { expect(resolveEquipmentRequirement("Kör nokta olmasın")[0]).toMatchObject({ polarity: "NEGATED", requiresConfirmation: true }); });
  it("26. uses word boundaries and does not substring-match", () => { expect(resolveEquipmentRequirement("kör noktalama işareti")).toEqual([]); });
  it("27. keeps generic language unbound", () => { expect(resolveEquipmentRequirement("güvenli olsun")[0]).toMatchObject({ featureCode: undefined, ambiguityClass: "GENERIC_NOT_BINDABLE" }); });
  it("28. reports feature/cohort coverage without treating cohort exclusion as absence", () => { const coverage = calculateEquipmentFeatureCoverage({ featureCode: "POWER_TAILGATE", cohortPolicyId: "TAILGATE_BODY_V1", variants: [{ exactVariantId: "SUV", bodyStyle: "SUV" }, { exactVariantId: "SEDAN", bodyStyle: "SEDAN" }], projections: [] }); expect(coverage).toMatchObject({ eligibleVariantCount: 1, notAvailableCount: 0, unknownCount: 1, featureCoverageRate: 0 }); });
  it("29. scopes hard failure to an explicit equipment requirement", () => { const feature = layer.featureDefinitions.find((item) => item.featureCode === "REAR_VIEW_CAMERA")!; expect(evaluateEquipmentCandidateEffect({ activation: "NOT_REQUESTED", feature, technicallyEligible: true })).toBe("NO_EFFECT"); expect(evaluateEquipmentCandidateEffect({ activation: "HARD_REQUIREMENT", feature, technicallyEligible: true })).toBe("HARD_FAIL"); });
  it("30. never lets equipment restore a technically rejected candidate", () => { const feature = layer.featureDefinitions[0]; expect(evaluateEquipmentCandidateEffect({ activation: "HARD_REQUIREMENT", feature, technicallyEligible: false, projection: project([assertion()]) })).toBe("NO_EFFECT"); });
  it("31. has natural Turkish labels for every controlled feature", () => { expect(layer.featureDefinitions).toHaveLength(51); expect(layer.featureDefinitions.every((item) => item.labelTr.length > 2 && item.labelTr !== item.featureCode)).toBe(true); });
});
