import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { evaluateEquipmentAssociationObservation, validateEquipmentAssociationObservation } from "./equipmentAssociationObservation";

const ROOT = process.cwd(), BASE = "data/production/equipment-evidence/working/EE-PILOT-002/EE-PILOT-002-BATCH-002", R1 = `${BASE}/corrections/EE-PILOT-002-BATCH-002-R1`, REVIEW = `${R1}/second-review`;
const read = <T>(file: string): T => JSON.parse(readFileSync(path.join(ROOT, file), "utf8")) as T;
const sha = (file: string) => `sha256:${createHash("sha256").update(readFileSync(path.join(ROOT, file))).digest("hex")}`;

describe("Batch 002 R1 independent association review", () => {
  const result = read<Record<string, unknown>>(`${REVIEW}/independent-review-results.json`), observations = read<Array<Record<string, unknown>>>(`${R1}/association-observations.json`), events = read<Array<Record<string, unknown>>>(`${REVIEW}/independent-review-events.json`);
  it("passes 98 unique subjects under an independent reviewer", () => { expect(result).toMatchObject({ finalDisposition: "ACCEPTED_PROVISION_UNRESOLVED_ASSOCIATIONS", passedAssociationObservations: 49, conflictAssociationObservations: 0, passedCorrectionTransitions: 49, conflictCorrectionTransitions: 0 }); expect(result.reviewerActorId).not.toBe("ACTOR-COLLECTOR-CODEX-CATALOG-001"); expect(result.reviewerActorId).not.toBe("EQUIPMENT_OWNER_001"); expect(events).toHaveLength(98); expect(new Set(events.map((item) => `${item.subjectType}|${item.subjectId}`)).size).toBe(98); });
  it("keeps observations outside assertion and projection authority", () => { expect(observations).toHaveLength(49); expect(observations.every((item) => !("availabilityStatus" in item) && !("provisionMode" in item) && item.observationType === "LISTED_FOR_EXACT_TRIM" && item.provisionKnowledge === "PROVISION_UNRESOLVED" && item.decisionUse === "CONFIRMATION_REQUIRED")).toBe(true); expect(validateEquipmentAssociationObservation({ ...observations[0], availabilityStatus: "STANDARD", provisionMode: "INCLUDED" })).toEqual(expect.arrayContaining(["ASSOCIATION_AVAILABILITY_STATUS_FORBIDDEN", "ASSOCIATION_PROVISION_MODE_FORBIDDEN"])); });
  it("returns zero candidate effect even for adversarial extra authority fields", () => { const effect = evaluateEquipmentAssociationObservation({ ...observations[0], hardFilter: true, rankingContribution: 100, confirmedUserFacingFact: true } as never); expect(effect).toEqual({ hardFilter: false, rankingContribution: 0, confirmedUserFacingFact: false, productionProjectionEligible: false, confirmationRequired: true }); });
  it("validates 196 collector events as two lifecycle events for each subject", () => { expect(read<Record<string, unknown>>(`${REVIEW}/collector-lifecycle-review.json`)).toMatchObject({ disposition: "PASSED", eventCount: 196, subjectCount: 98, eventsPerSubject: 2, collectedEvents: 98, secondReviewRequiredEvents: 98, secondReviewPassedEvents: 0 }); });
  it("preserves historical records and the pre-activation pointer audit value", () => { const preservation = read<Record<string, { sha256: string }>>(`${R1}/historical-artifact-preservation.json`); expect(sha(`${BASE}/assertions.json`)).toBe(preservation.originalAssertions.sha256); expect(sha(`${BASE}/trim-links.json`)).toBe(preservation.originalTrimLinks.sha256); expect(result.activePointerBeforeSha256).toBe("sha256:aec85d8f92c51ef3e5126a9f0dcf7db19bad3b9cb31a8851b58c2ef833950765"); expect(sha("data/production/equipment-evidence/active.json")).toBe("sha256:39eae2723b0ca4bc38589bc25157326f084ed36f8fa4b6a946c7542d8ea4c98a"); });
  it("reports the terminal view without counting observations as verified assertions", () => { expect(read<Record<string, unknown>>(`${REVIEW}/terminal-view.json`)).toEqual({ verifiedEquipmentAssertions: 0, passedAssociationObservations: 49, conflictAssociationObservations: 0, passedCorrectionTransitions: 49, conflictCorrectionTransitions: 0, passedTrimLinks: 2, historicalConflictAssertions: 49, inconclusiveLedgerRows: 53 }); });
});
