import { createHash } from "node:crypto";
import { z } from "zod";
import type { AppliancesCommerceSnapshot, CurrentProductCommerce, ExactOfferObservation } from "./types";

const https = z.string().url().refine(value => value.startsWith("https://"));
const allowedHosts = new Set(["destek.arzum.com.tr","download.arcelik.com.tr","gsim2hwnpbvwtwmb1dg11z6.blob.core.windows.net","images.samsung.com","m.miele.com.tr","media.miele.com","media3.bosch-home.com","media3.bsh-group.com","statik.vestel.com.tr","www.arcelik.com.tr","www.arnica.com.tr","www.arzum.com.tr","www.baymak.com.tr","www.beko.com.tr","www.bosch-home.com.tr","www.bosch-homecomfort.com","www.delonghi.com","www.dyson.com.tr","www.electrolux.com.tr","www.karaca.com","www.kenwoodworld.com","www.lg.com","www.mi.com","www.miele.com.tr","www.ninjaturkiye.com","www.philips.com.tr","www.samsung.com","www.siemens-home.bsh-group.com","www.smeg.com.tr","www.tefal.com.tr","www.toshiba-klima.com.tr","www.vestel.com.tr","www.amazon.com.tr","www.trendyol.com","www.hepsiburada.com","www.akakce.com","gumuscudtm.com"]);
export function isAllowedCommerceUrl(value: string): boolean { try { const url = new URL(value); return url.protocol === "https:" && allowedHosts.has(url.hostname) && !url.username && !url.password; } catch { return false; } }
function stable(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; if (value && typeof value === "object") return `{${Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(",")}}`; return JSON.stringify(value); }
export function commerceDigest(value: Omit<AppliancesCommerceSnapshot,"snapshotDigest">): string { return createHash("sha256").update(stable(value)).digest("hex"); }
export function offerFingerprint(value: Readonly<Record<string,unknown>>): string { return createHash("sha256").update(stable(value)).digest("hex"); }
export function normalizeSellerIdentity(value: string): string { return value.normalize("NFKD").replace(/\p{M}/gu,"").toLocaleLowerCase("tr-TR").replace(/[^a-z0-9]+/gu,"").trim(); }
export function normalizeExactModel(value: string): string { return value.normalize("NFKD").replace(/\p{M}/gu,"").toLocaleUpperCase("en-US").replace(/[^A-Z0-9]+/gu,""); }
export function hasExactModelMatch(expected: string, observed: string): boolean { const model=normalizeExactModel(expected), text=normalizeExactModel(observed); return model.length>=4 && text.includes(model); }

const mediaSchema=z.strictObject({assetId:z.string().min(1),exactProductId:z.string().min(1),sourceUrl:https,canonicalProductPage:https,mediaUrl:https.optional(),localAssetPath:z.string().startsWith("/appliances/").optional(),sourceType:z.enum(["MANUFACTURER_TR","MANUFACTURER_CDN","REPOSITORY"]),retrievedAt:z.iso.datetime({offset:true}),verifiedAt:z.iso.datetime({offset:true}),rightsStatus:z.enum(["MANUFACTURER_PUBLISHED_REMOTE_DISPLAY","LICENSE_VERIFIED","RIGHTS_UNCLEAR"]),identityMatchEvidence:z.array(z.string().min(1)).min(1),file:z.strictObject({sha256:z.string().regex(/^[a-f0-9]{64}$/u),width:z.number().int().positive(),height:z.number().int().positive(),contentType:z.string().min(1)}).optional(),status:z.enum(["EXACT_APPROVED","REPRESENTATIVE_DISCLOSED","UNAVAILABLE"])});
const offerSchema=z.strictObject({exactProductId:z.string().min(1),categoryId:z.string().min(1),merchant:z.string().min(1),marketplace:z.boolean(),seller:z.string().min(1),sellerIdentity:z.string().regex(/^[a-z0-9]+$/u),canonicalListingUrl:https,amount:z.number().positive(),currency:z.literal("TRY"),shippingInclusion:z.enum(["INCLUDED","EXCLUDED","UNKNOWN"]),availability:z.enum(["IN_STOCK","LIMITED","OUT_OF_STOCK","UNKNOWN"]),observedAt:z.iso.datetime({offset:true}),expiresAt:z.iso.datetime({offset:true}),sourceKind:z.enum(["MANUFACTURER_DIRECT","MARKETPLACE","INDEPENDENT_MERCHANT"]),discoveredVia:z.strictObject({aggregator:z.literal("AKAKCE"),url:https}).optional(),identityMatchEvidence:z.array(z.string().min(1)).min(1),exactModelMatched:z.literal(true),affiliate:z.strictObject({program:z.string().min(1),attributionOnly:z.literal(true),url:https.optional()}).optional(),observationFingerprint:z.string().regex(/^[a-f0-9]{64}$/u)});
const attemptSchema=z.strictObject({exactProductId:z.string().min(1),channel:z.enum(["MANUFACTURER_TR","AMAZON_TR","HEPSIBURADA","TRENDYOL","AKAKCE","INDEPENDENT_TR"]),discoveryUrl:https,attemptedAt:z.iso.datetime({offset:true}),outcome:z.enum(["EXACT_OFFER_ACCEPTED","NO_CANONICAL_EXACT_LISTING_VERIFIED","IDENTITY_MISMATCH","UNAVAILABLE","BLOCKED","FETCH_FAILED","MEDIA_EXACT_APPROVED","MEDIA_UNAVAILABLE_FAIL_CLOSED"]),evidence:z.string().min(1),attemptNumber:z.number().int().positive(),retryable:z.boolean(),httpStatus:z.number().int().min(100).max(599).optional()});
const scopeSchema=z.strictObject({exactProductId:z.string().min(1),categoryId:z.string().min(1),brand:z.string().min(1),model:z.string().min(1)});
const snapshotSchema=z.strictObject({schemaVersion:z.literal("appliances-commerce-snapshot/v2"),snapshotId:z.string().min(1),publishedAt:z.iso.datetime({offset:true}),freshnessPolicy:z.strictObject({maxAgeHours:z.number().positive().max(168),unavailableRetention:z.literal(true)}),productScope:z.array(scopeSchema),media:z.array(mediaSchema),offers:z.array(offerSchema),sourceAttempts:z.array(attemptSchema),snapshotDigest:z.string().regex(/^[a-f0-9]{64}$/u)});

function fingerprintPayload(item: ExactOfferObservation): Record<string,unknown> { const value={...item} as Record<string,unknown>; delete value.observationFingerprint; delete value.affiliate; return value; }
export function deduplicateIndependentOffers(offers: readonly ExactOfferObservation[]): readonly ExactOfferObservation[] { const bySeller=new Map<string,ExactOfferObservation>(); for(const offer of offers){const prior=bySeller.get(offer.sellerIdentity);if(!prior||offer.amount<prior.amount||(offer.amount===prior.amount&&offer.canonicalListingUrl.localeCompare(prior.canonicalListingUrl)<0))bySeller.set(offer.sellerIdentity,offer);} return [...bySeller.values()].sort((a,b)=>a.amount-b.amount||a.sellerIdentity.localeCompare(b.sellerIdentity)); }
export function classifyBudgetFromOffers(offers: readonly ExactOfferObservation[],upperLimitTry:number): "PRICE_COMPATIBLE"|"BUDGET_INCOMPATIBLE"|"BUDGET_ELIGIBILITY_UNKNOWN" { if(!Number.isFinite(upperLimitTry)||upperLimitTry<=0||offers.length===0)return "BUDGET_ELIGIBILITY_UNKNOWN";return offers.some(item=>item.amount<=upperLimitTry)?"PRICE_COMPATIBLE":"BUDGET_INCOMPATIBLE"; }

export function validateCommerceSnapshot(input:unknown,now:Date):{status:"READY";snapshot:AppliancesCommerceSnapshot}|{status:"FAILED_CLOSED";reason:string}{
  const parsed=snapshotSchema.safeParse(input);if(!parsed.success)return{status:"FAILED_CLOSED",reason:"SCHEMA_INVALID"};const snapshot=parsed.data as AppliancesCommerceSnapshot;const{snapshotDigest,...payload}=snapshot;
  if(commerceDigest(payload)!==snapshotDigest)return{status:"FAILED_CLOSED",reason:"DIGEST_MISMATCH"};
  const scopeIds=snapshot.productScope.map(x=>x.exactProductId);if(new Set(scopeIds).size!==scopeIds.length)return{status:"FAILED_CLOSED",reason:"DUPLICATE_SCOPE"};const scoped=new Set(scopeIds);
  for(const item of snapshot.media)if(!scoped.has(item.exactProductId)||!isAllowedCommerceUrl(item.sourceUrl)||!isAllowedCommerceUrl(item.canonicalProductPage)||(item.mediaUrl&&!isAllowedCommerceUrl(item.mediaUrl)))return{status:"FAILED_CLOSED",reason:"MEDIA_AUTHORITY_INVALID"};else if(item.status==="EXACT_APPROVED"){
    const licensedLocal=item.rightsStatus==="LICENSE_VERIFIED"&&Boolean(item.localAssetPath)&&Boolean(item.file)&&!item.mediaUrl;
    const licensedRemote=item.rightsStatus==="MANUFACTURER_PUBLISHED_REMOTE_DISPLAY"&&Boolean(item.mediaUrl)&&!item.localAssetPath&&!item.file;
    if(!licensedLocal&&!licensedRemote)return{status:"FAILED_CLOSED",reason:"MEDIA_PROVENANCE_INVALID"};
  }
  for(const item of snapshot.offers){const scope=snapshot.productScope.find(x=>x.exactProductId===item.exactProductId);if(!scope||scope.categoryId!==item.categoryId||!isAllowedCommerceUrl(item.canonicalListingUrl)||(item.discoveredVia&&!isAllowedCommerceUrl(item.discoveredVia.url))||(item.affiliate?.url&&!isAllowedCommerceUrl(item.affiliate.url))||normalizeSellerIdentity(item.seller)!==item.sellerIdentity||offerFingerprint(fingerprintPayload(item))!==item.observationFingerprint||Date.parse(item.expiresAt)<=Date.parse(item.observedAt))return{status:"FAILED_CLOSED",reason:"OFFER_AUTHORITY_INVALID"};}
  for(const id of scopeIds){if(snapshot.media.filter(x=>x.exactProductId===id).length!==1)return{status:"FAILED_CLOSED",reason:"MEDIA_COVERAGE_INCOMPLETE"};const attempts=snapshot.sourceAttempts.filter(x=>x.exactProductId===id);if(!(["MANUFACTURER_TR","AMAZON_TR","HEPSIBURADA","TRENDYOL","AKAKCE"] as const).every(channel=>attempts.some(x=>x.channel===channel)))return{status:"FAILED_CLOSED",reason:"SOURCE_COVERAGE_INCOMPLETE"};}
  for(const item of snapshot.sourceAttempts)if(!scoped.has(item.exactProductId)||!isAllowedCommerceUrl(item.discoveryUrl))return{status:"FAILED_CLOSED",reason:"SOURCE_ATTEMPT_INVALID"};
  if(!Number.isFinite(now.getTime()))return{status:"FAILED_CLOSED",reason:"CLOCK_INVALID"};return{status:"READY",snapshot:Object.freeze(snapshot)};
}

export function resolveCurrentProductCommerce(snapshot:AppliancesCommerceSnapshot,productId:string,now:Date):CurrentProductCommerce{
  const media=snapshot.media.find(x=>x.exactProductId===productId&&x.status==="EXACT_APPROVED")??null;
  const fresh=snapshot.offers.filter(x=>x.exactProductId===productId&&x.availability!=="OUT_OF_STOCK"&&Date.parse(x.expiresAt)>now.getTime()&&now.getTime()-Date.parse(x.observedAt)<=snapshot.freshnessPolicy.maxAgeHours*3_600_000);
  const offers=deduplicateIndependentOffers(fresh), latest=offers.map(x=>x.observedAt).sort().at(-1);
  const priceRange=offers.length?{minimumTry:offers[0].amount,maximumTry:offers[offers.length-1].amount,observedAtLatest:latest!}:null;
  const range=priceRange?priceRange.minimumTry===priceRange.maximumTry?`${priceRange.minimumTry.toLocaleString("tr-TR")} TL güncel fiyat`:`${priceRange.minimumTry.toLocaleString("tr-TR")}–${priceRange.maximumTry.toLocaleString("tr-TR")} TL güncel fiyat aralığı`:"";
  return{snapshotId:snapshot.snapshotId,snapshotDigest:snapshot.snapshotDigest,media,offers,independentFreshOfferCount:offers.length,priceRange,coverageNotice:offers.length>=3?`${range}; ${offers.length} bağımsız satıcıda doğrulandı.`:offers.length?`${range}; ${offers.length} bağımsız satıcıda doğrulandı, daha geniş fiyat kapsamı henüz yok.`:"Bu ürün için güncel ve doğrulanmış satıcı teklifi bulunmuyor. Teknik uygunluğu ve katalog üyeliği korunur; satışta bulunurluk veya bütçe uyumu iddia edilmez."}; 
}
