import { describe,expect,it } from "vitest";
import { acceptParsedExactOffer } from "./acquisition";
import { classifyBudgetFromOffers,commerceDigest,deduplicateIndependentOffers,offerFingerprint,resolveCurrentProductCommerce,validateCommerceSnapshot } from "./authority";
import type { AppliancesCommerceSnapshot,ExactOfferObservation } from "./types";
const now=new Date("2026-09-04T09:00:00+03:00"),product={exactProductId:"P1",categoryId:"VACUUM",brand:"Bosch",model:"BGC41PET"};
function offer(overrides:Partial<ExactOfferObservation>={}):ExactOfferObservation{const core={exactProductId:product.exactProductId,categoryId:product.categoryId,merchant:"Trendyol",marketplace:true,seller:"Seller A",sellerIdentity:"sellera",canonicalListingUrl:"https://www.trendyol.com/bosch/bgc41pet-p-1",amount:100,currency:"TRY" as const,shippingInclusion:"UNKNOWN" as const,availability:"IN_STOCK" as const,observedAt:"2026-09-04T08:00:00+03:00",expiresAt:"2026-09-05T08:00:00+03:00",sourceKind:"MARKETPLACE" as const,identityMatchEvidence:["Exact BGC41PET"],exactModelMatched:true as const,...overrides};const fingerprint={...core} as Record<string,unknown>;delete fingerprint.observationFingerprint;delete fingerprint.affiliate;return{...core,observationFingerprint:offerFingerprint(fingerprint)};}
function snapshot(overrides:Partial<AppliancesCommerceSnapshot>={}):AppliancesCommerceSnapshot{const media={assetId:"none",exactProductId:"P1",sourceUrl:"https://www.bosch-home.com.tr/tr/product/BGC41PET",canonicalProductPage:"https://www.bosch-home.com.tr/tr/product/BGC41PET",sourceType:"MANUFACTURER_TR" as const,retrievedAt:now.toISOString(),verifiedAt:now.toISOString(),rightsStatus:"RIGHTS_UNCLEAR" as const,identityMatchEvidence:["BGC41PET"],status:"UNAVAILABLE" as const};const sourceAttempts=(["MANUFACTURER_TR","AMAZON_TR","HEPSIBURADA","TRENDYOL","AKAKCE"] as const).map(channel=>({exactProductId:"P1",channel,discoveryUrl:channel==="MANUFACTURER_TR"?media.sourceUrl:channel==="AMAZON_TR"?"https://www.amazon.com.tr/s?k=BGC41PET":channel==="HEPSIBURADA"?"https://www.hepsiburada.com/ara?q=BGC41PET":channel==="TRENDYOL"?"https://www.trendyol.com/sr?q=BGC41PET":"https://www.akakce.com/arama/?q=BGC41PET",attemptedAt:now.toISOString(),outcome:"NO_CANONICAL_EXACT_LISTING_VERIFIED" as const,evidence:"recorded",attemptNumber:1,retryable:false}));const core={schemaVersion:"appliances-commerce-snapshot/v2" as const,snapshotId:"test",publishedAt:now.toISOString(),freshnessPolicy:{maxAgeHours:24,unavailableRetention:true as const},productScope:[product],media:[media],offers:[offer()],sourceAttempts,...overrides};return{...core,snapshotDigest:commerceDigest(core)};}

describe("appliances volatile exact-offer authority",()=>{
  it("admits explicitly authorized remote display without implying cache permission",()=>{const remote={...snapshot().media[0],mediaUrl:"https://media3.bosch-home.com/p1.webp",rightsStatus:"MANUFACTURER_PUBLISHED_REMOTE_DISPLAY" as const,status:"EXACT_APPROVED" as const};const checked=validateCommerceSnapshot(snapshot({media:[remote]}),now);expect(checked.status).toBe("READY");expect(remote).not.toHaveProperty("localAssetPath");});
  it("rejects model mismatch, non-TRY and unavailable observations",()=>{const base={product,merchant:"Bosch",seller:"Bosch",marketplace:false,canonicalListingUrl:"https://www.bosch-home.com.tr/p",pageIdentity:"Bosch BGC41PET",amount:100,currency:"TRY",availability:"InStock",observedAt:now.toISOString(),expiresAt:"2026-09-05T09:00:00+03:00"};expect(acceptParsedExactOffer(base)?.exactModelMatched).toBe(true);expect(acceptParsedExactOffer({...base,pageIdentity:"Bosch BGC21X300"})).toBeNull();expect(acceptParsedExactOffer({...base,currency:"EUR"})).toBeNull();expect(acceptParsedExactOffer({...base,availability:"OutOfStock"})).toBeNull();});
  it("expires stale data and retains budget eligibility as unknown",()=>{const valid=validateCommerceSnapshot(snapshot(),now);expect(valid.status).toBe("READY");if(valid.status!=="READY")return;const stale=resolveCurrentProductCommerce(valid.snapshot,"P1",new Date("2026-09-06T09:00:00+03:00"));expect(stale.offers).toEqual([]);expect(classifyBudgetFromOffers(stale.offers,1000)).toBe("BUDGET_ELIGIBILITY_UNKNOWN");});
  it("deduplicates one marketplace seller across surfaces and keeps Akakce as discovery only",()=>{const same=offer({merchant:"Hepsiburada",canonicalListingUrl:"https://www.hepsiburada.com/bosch-p-2",amount:110}),underlying=offer({merchant:"Trendyol",discoveredVia:{aggregator:"AKAKCE",url:"https://www.akakce.com/arama/?q=BGC41PET"},amount:90});expect(deduplicateIndependentOffers([same,underlying])).toEqual([underlying]);});
  it("resolves price conflict conservatively by current independent offers",()=>{const a=offer({amount:99}),b=offer({seller:"Seller B",sellerIdentity:"sellerb",amount:150});expect(classifyBudgetFromOffers([a,b],120)).toBe("PRICE_COMPATIBLE");expect(classifyBudgetFromOffers([a,b],90)).toBe("BUDGET_INCOMPATIBLE");const current=resolveCurrentProductCommerce(snapshot({offers:[a,b]}),"P1",now);expect(current.priceRange).toMatchObject({minimumTry:99,maximumTry:150});});
  it("keeps affiliate attribution outside fingerprints and neutral ordering",()=>{const plain=offer({amount:200}),affiliate=offer({amount:200,affiliate:{program:"x",attributionOnly:true,url:"https://www.trendyol.com/bosch/bgc41pet-p-1"}});expect(plain.observationFingerprint).toBe(affiliate.observationFingerprint);expect(deduplicateIndependentOffers([affiliate,offer({seller:"Seller B",sellerIdentity:"sellerb",amount:100})]).map(x=>x.amount)).toEqual([100,200]);});
  it("is reproducible and fails closed on mutation",()=>{const first=snapshot(),second=snapshot();expect(first.snapshotDigest).toBe(second.snapshotDigest);expect(validateCommerceSnapshot({...first,snapshotId:"changed"},now)).toMatchObject({status:"FAILED_CLOSED",reason:"DIGEST_MISMATCH"});});
});
