/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial immutable authority fixtures require controlled structural mutation */
import { describe,expect,it,beforeAll } from "vitest";
import { createFileSystemAppliancesArtifactRepository,loadActiveAppliancesAuthority } from "../authority/loader.server";
import type { AppliancesAuthoritySnapshot,PriceProjectionLoadResult } from "../authority/types";
import { evaluateAppliancesCandidates } from "../candidate/evaluate";
import type { AppliancesCandidateEvaluationResult } from "../candidate/types";
import type { AppliancesConversationState,AppliancesLedgerEvent } from "../contracts";
import { enterAppliancesDepartment } from "../entry.server";
import { createFileSystemQuestionPolicyRepository,loadActiveWashingMachineQuestionPolicy,type QuestionPolicyLoadResult } from "../governance/questionPolicyLoader.server";
import { planAppliancesQuestion } from "./plan";
import { activeCatalogPriceFixture } from "../testing/activeCatalogPriceFixture";

const repository=createFileSystemAppliancesArtifactRepository(process.cwd());let authority:AppliancesAuthoritySnapshot,policy:Extract<QuestionPolicyLoadResult,{status:"READY"}>,price:PriceProjectionLoadResult,base:AppliancesConversationState;
beforeAll(async()=>{const a=await loadActiveAppliancesAuthority({repository});if(a.status!=="READY")throw new Error(a.reason);authority=a.snapshot;const p=await loadActiveWashingMachineQuestionPolicy({repository:createFileSystemQuestionPolicyRepository(process.cwd()),authority});if(p.status!=="READY")throw new Error(p.reason);policy=p;price=activeCatalogPriceFixture(authority);const e=await enterAppliancesDepartment({repository,productType:"WASHING_MACHINE",conversationId:"11111111-1111-4111-8111-111111111111",now:new Date("2026-09-03T09:00:00Z")});if(e.status!=="READY")throw new Error(e.status);base=e.state;});
const event=(conceptId:string,normalizedValue:unknown,status:AppliancesLedgerEvent["status"]="ACCEPTED_EXPLICIT",eventId=`e-${conceptId}`):AppliancesLedgerEvent=>({eventId,conceptId,normalizedValue,sourceMessageId:`m-${eventId}`,authority:"USER_EXPLICIT",strength:"STRONG",status,decisionUse:conceptId==="BUDGET_SENSITIVITY"||conceptId==="INSTALLATION_FIT"?"HARD_FILTER":"SOFT_RANK",confirmationRequired:status==="PROPOSED",createdRevision:0,createdAt:"2026-09-03T09:00:00Z"});
const evaluate=(state:AppliancesConversationState):Extract<AppliancesCandidateEvaluationResult,{status:"READY"}>=>{const result=evaluateAppliancesCandidates({authority,state,price});if(result.status!=="READY")throw new Error(result.reason);return result;};
const plan=(state=base,evaluation=evaluate(state),activePolicy:QuestionPolicyLoadResult=policy,activePrice=price)=>planAppliancesQuestion({authority,policy:activePolicy,state,evaluation,price:activePrice});

describe("governed Appliances Question Planner",()=>{
 it("consumes only the verified active policy and emits one deterministic ASK with digest provenance",()=>{const first=plan(),second=plan();expect(first).toEqual(second);expect(first).toMatchObject({kind:"ASK",questionKey:"appliances.wm.budget.maximumTry",questionPolicyId:"WASHING_MACHINE_QUESTION_POLICY/v0.1",questionPolicyDigest:"f5bcc250d3484c2a114c403b05970dc4c9c82412919ba7b6bcee0c0927d9100d"});expect(Array.isArray(first)).toBe(false);});
 it("fails closed for missing policy and candidate failure",()=>{expect(plan(base,evaluate(base),{status:"FAILED_CLOSED",reason:"POLICY_MISSING"})).toEqual({kind:"FAILED_CLOSED",reason:"QUESTION_POLICY_AUTHORITY_FAILURE"});expect(planAppliancesQuestion({authority,policy,state:base,evaluation:{status:"FAILED_CLOSED",reason:"CATALOG_INTEGRITY_FAILURE"},price})).toEqual({kind:"FAILED_CLOSED",reason:"CANDIDATE_EVALUATION_FAILURE"});});
 it("is invariant to candidate order and persona-only changes",()=>{const evaluation=evaluate(base),reordered={...evaluation,projection:{...evaluation.projection,candidates:[...evaluation.projection.candidates].reverse(),remainingProductRefs:[...evaluation.projection.remainingProductRefs].reverse()}};expect(plan(base,reordered)).toEqual(plan(base,evaluation));expect(plan({...base,personaSignals:[{signalId:"X",sourceEventIds:[],authority:"DERIVED_PLANNING",directCandidateEffect:"NONE",decisionUse:"NONE"}]})).toEqual(plan(base));});
 it("gives authoritative pending confirmation precedence without mutating state",()=>{const proposed=event("LOW_NOISE_PRIORITY",true,"PROPOSED","pending-1"),state={...base,ledger:[proposed],pendingConfirmation:{eventId:proposed.eventId,conceptId:proposed.conceptId,normalizedValue:true,sourceMessageId:proposed.sourceMessageId,createdRevision:0,expiresAfterRevision:2,question:"Bunu doğrular mısın?"}};const before=JSON.stringify(state);expect(plan(state)).toMatchObject({kind:"CLARIFY",authoritativeEventId:"pending-1",targetConcept:"LOW_NOISE_PRIORITY"});expect(JSON.stringify(state)).toBe(before);});
 it("fails closed for an impossible pending clarification",()=>{const state={...base,pendingConfirmation:{eventId:"missing",conceptId:"LOW_NOISE_PRIORITY",normalizedValue:true,sourceMessageId:"m",createdRevision:0,expiresAfterRevision:2,question:"?"}};expect(plan(state)).toEqual({kind:"FAILED_CLOSED",reason:"INVALID_PENDING_CLARIFICATION"});});
 it("asks installation dimensions only after accepted applicability and in frozen order",()=>{const location=event("INSTALLATION_FIT",{location:"KITCHEN",fitConfirmed:false}),width=event("INSTALLATION_FIT",{location:"KITCHEN",maxWidthMm:620},"ACCEPTED_EXPLICIT","width");const first={...base,ledger:[location]};expect(plan(first)).toMatchObject({kind:"ASK",questionKey:"appliances.wm.installation.maxWidthMm"});const second={...base,ledger:[location,{...width,supersedesEventId:location.eventId}]};expect(plan(second)).toMatchObject({kind:"ASK",questionKey:"appliances.wm.installation.maxHeightMm"});const height={...event("INSTALLATION_FIT",{location:"KITCHEN",maxWidthMm:620,maxHeightMm:900},"ACCEPTED_EXPLICIT","height"),supersedesEventId:width.eventId};expect(plan({...base,ledger:[location,{...width,supersedesEventId:location.eventId},height]})).toMatchObject({kind:"ASK",questionKey:"appliances.wm.installation.maxBodyDepthMm"});expect(plan(base)).not.toMatchObject({questionKey:expect.stringContaining("installation")});});
 it("suppresses accepted hard budget and never claims positive fit",()=>{const state={...base,ledger:[event("BUDGET_SENSITIVITY",{maximumTry:50000})]};expect(plan(state)).not.toMatchObject({questionKey:"appliances.wm.budget.maximumTry"});const installation={...base,ledger:[event("INSTALLATION_FIT",{location:"KITCHEN"})]};const result=plan(installation);expect(JSON.stringify(result)).not.toMatch(/safe fit|fits safely|uygunluk doğrulandı/iu);});
 it("preserves approved soft domains without hard-filter semantics",()=>{const questions=policy.snapshot.payload.questions;expect(questions.find(q=>q.targetConcept==="REMOTE_CONTROL")?.answerDomain).toMatchObject({values:["WANTED","NOT_IMPORTANT"]});expect(questions.find(q=>q.targetConcept==="DETERGENT_CONVENIENCE")?.answerDomain).toMatchObject({values:["WANTED","NOT_IMPORTANT"]});expect(questions.find(q=>q.targetConcept==="LOW_NOISE_PRIORITY")?.answerDomain).toMatchObject({values:["IMPORTANT","NOT_IMPORTANT"]});expect(JSON.stringify(questions)).not.toMatch(/PROHIBITED|"REQUIRED"/u);expect(questions.filter(q=>["REMOTE_CONTROL","DETERGENT_CONVENIENCE","LOW_NOISE_PRIORITY"].includes(q.targetConcept)).every(q=>q.materiality.softPreferenceEffect==="NON_FILTERING")).toBe(true);});
 it("never selects capacity and explicit capacity context invents no ASK",()=>{const state={...base,ledger:[event("HIGH_LAUNDRY_VOLUME",{minimumCapacityKg:9})]};expect(JSON.stringify(plan(state))).not.toMatch(/capacity|minimumKg|household.*kg/iu);expect(policy.snapshot.payload.questions).toHaveLength(7);});
 it("suppresses an asked question under unchanged authority and reopens only when authority changes",()=>{const evaluation=evaluate(base),asked={...base,askedQuestionKeys:["appliances.wm.budget.maximumTry"],lastQuestionKey:"appliances.wm.budget.maximumTry",candidateSnapshotRef:evaluation.projection.evaluationFingerprint};expect(plan(asked,evaluation)).not.toMatchObject({questionKey:"appliances.wm.budget.maximumTry"});expect(plan({...asked,candidateSnapshotRef:"older-authority"},evaluation)).toMatchObject({kind:"ASK",questionKey:"appliances.wm.budget.maximumTry"});});
 it("never lets fingerprint change override accepted context",()=>{const state={...base,ledger:[event("BUDGET_SENSITIVITY",{maximumTry:50000})],askedQuestionKeys:["appliances.wm.budget.maximumTry"],lastQuestionKey:"appliances.wm.budget.maximumTry",candidateSnapshotRef:"older"};expect(plan(state)).not.toMatchObject({questionKey:"appliances.wm.budget.maximumTry"});});
 it("ignores transcript text and treats stale prices as non-material",()=>{expect(plan(base,evaluate(base),policy,{...price,status:"STALE"} as PriceProjectionLoadResult)).not.toMatchObject({questionKey:"appliances.wm.budget.maximumTry"});expect(JSON.stringify(plan(base))).not.toMatch(/seller|affiliate/iu);});
 it("returns neutral no-question without recommendation or sufficiency",()=>{const ledger=[event("BUDGET_SENSITIVITY",{maximumTry:50000}),event("REMOTE_CONTROL",{wanted:true}),event("DETERGENT_CONVENIENCE",{wanted:true}),event("LOW_NOISE_PRIORITY",true)];const result=plan({...base,ledger});expect(result).toMatchObject({kind:"NO_AUTHORIZED_MATERIAL_QUESTION",meaning:"NEUTRAL_PLANNING_ABSENCE"});expect(JSON.stringify(result)).not.toMatch(/DECISION_READY|sufficient|recommend|winner/iu);});
 it("fails closed for revision, asked-key and discriminator divergence",()=>{const evaluation=evaluate(base);expect(plan({...base,revision:1},evaluation)).toEqual({kind:"FAILED_CLOSED",reason:"CONTEXT_REVISION_MISMATCH"});expect(plan({...base,askedQuestionKeys:["unknown"]},evaluation)).toEqual({kind:"FAILED_CLOSED",reason:"INVALID_ASKED_QUESTION_STATE"});const changed=structuredClone(policy) as any;changed.snapshot.payload.questions[3].materiality.requiresCandidateDifference="UNKNOWN";expect(plan(base,evaluation,changed)).toEqual({kind:"FAILED_CLOSED",reason:"UNKNOWN_POLICY_DISCRIMINATOR"});});
});
