import { createHash } from "node:crypto";
import { projectActiveAppliancesContext } from "../context/projection";
import type { WashingMachineQuestionPolicyPayload } from "../governance/questionPolicyAuthority";
import { APPLIANCES_QUESTION_SELECTION_POLICY_VERSION,type AppliancesQuestionPlan,type AppliancesQuestionPlannerInput } from "./types";

type Json=Record<string,unknown>;
const frozenKeys=new Set(["appliances.wm.installation.maxWidthMm","appliances.wm.installation.maxHeightMm","appliances.wm.installation.maxBodyDepthMm","appliances.wm.budget.maximumTry","appliances.wm.remoteControl.requirement","appliances.wm.autoDosing.preference","appliances.wm.noise.priority"]);
const contextField:Readonly<Record<string,string>>={"appliances.wm.installation.maxWidthMm":"maxWidthMm","appliances.wm.installation.maxHeightMm":"maxHeightMm","appliances.wm.installation.maxBodyDepthMm":"maxDepthMm","appliances.wm.budget.maximumTry":"maximumTry"};
const fail=(reason:Extract<AppliancesQuestionPlan,{kind:"FAILED_CLOSED"}>["reason"]):AppliancesQuestionPlan=>({kind:"FAILED_CLOSED",reason});
function distinctValues(input:AppliancesQuestionPlannerInput,policy:WashingMachineQuestionPolicyPayload,question:WashingMachineQuestionPolicyPayload["questions"][number],remaining:ReadonlySet<string>):number|null{
 const catalog=input.authority.catalog as Json,discriminator=question.materiality.requiresCandidateDifference;
 if(discriminator==="FRESH_REPRESENTATIVE_PRICE_TRY"){if(input.price?.status!=="READY")return 0;const products=(input.price.projection.products as readonly Json[]|undefined)??[];return new Set(products.filter(p=>remaining.has(String(p.productId))&&p.status==="PRICE_AVAILABLE"&&typeof p.representativePriceTRY==="number").map(p=>p.representativePriceTRY)).size;}
 const facts=(catalog.technicalFacts as readonly Json[]|undefined)??[];if(((catalog.factKeyRegistry as readonly string[]|undefined)??[]).includes(discriminator))return new Set(facts.filter(f=>remaining.has(String(f.productId))&&f.factKey===discriminator&&f.factStatus==="VERIFIED").map(f=>JSON.stringify(f.value))).size;
 const capabilities=(catalog.capabilityFacts as readonly Json[]|undefined)??[];if(((catalog.capabilityRegistry as readonly string[]|undefined)??[]).includes(discriminator))return new Set(capabilities.filter(c=>remaining.has(String(c.productId))&&c.capabilityId===discriminator&&["PRESENT","NOT_AVAILABLE"].includes(String(c.status))).map(c=>c.status)).size;
 void policy;return null;
}
export function planAppliancesQuestion(input:AppliancesQuestionPlannerInput):AppliancesQuestionPlan{
 if(input.policy.status!=="READY")return fail("QUESTION_POLICY_AUTHORITY_FAILURE");if(input.evaluation.status!=="READY")return fail("CANDIDATE_EVALUATION_FAILURE");
 const p=input.policy.snapshot.payload,e=input.evaluation.projection;if(input.state.departmentId!=="APPLIANCES"||input.state.productType!=="WASHING_MACHINE"||input.state.pinnedCatalogRelease!==input.authority.releaseVersion||input.state.pinnedCatalogDigest!==input.authority.catalogDigest||input.state.pinnedSemanticDigest!==input.authority.semanticDigest||p.bindings.catalogDigest!==input.authority.catalogDigest||p.bindings.semanticRegistryDigest!==input.authority.semanticDigest)return fail("CONTEXT_AUTHORITY_MISMATCH");if(e.contextRevision!==input.state.revision)return fail("CONTEXT_REVISION_MISMATCH");if(!/^[a-f0-9]{64}$/u.test(e.evaluationFingerprint))return fail("EVALUATION_FINGERPRINT_INVALID");
 if(p.questions.length!==7||p.questions.some(q=>!frozenKeys.has(q.questionKey))||p.selectionPolicy.personaInfluence!=="NONE"||p.selectionPolicy.candidateArrayOrderInfluence!=="NONE")return fail("RUNTIME_POLICY_DIVERGENCE");if(input.state.askedQuestionKeys.some(k=>!frozenKeys.has(k))||input.state.lastQuestionKey&&!frozenKeys.has(input.state.lastQuestionKey))return fail("INVALID_ASKED_QUESTION_STATE");
 if(input.state.pendingConfirmation){const pending=input.state.pendingConfirmation,event=input.state.ledger.find(x=>x.eventId===pending.eventId);if(!event||event.status!=="PROPOSED"||event.conceptId!==pending.conceptId||!event.confirmationRequired)return fail("INVALID_PENDING_CLARIFICATION");return{kind:"CLARIFY",questionKey:`CONFIRM:${pending.conceptId}`,message:pending.question,authoritativeEventId:event.eventId,targetConcept:event.conceptId,contextRevision:input.state.revision};}
 const active=projectActiveAppliancesContext(input.state.ledger),remaining=new Set(e.remainingProductRefs),materialityAuthorityFingerprint=createHash("sha256").update(JSON.stringify({catalog:e.catalogDigest,semantic:e.semanticDigest,context:e.contextFingerprint,remaining:[...remaining].sort(),price:e.priceSnapshot?.projectionFingerprint??null,priceFreshness:e.priceSnapshot?.freshness??null})).digest("hex");const ordered=[...p.questions].sort((a,b)=>a.priority-b.priority||a.questionKey.localeCompare(b.questionKey));
 for(const q of ordered){const accepted=active.get(q.targetConcept),field=contextField[q.questionKey];if(input.state.questionDeferrals?.some(item=>item.questionKey===q.questionKey&&item.status==="ACTIVE"))continue;if(accepted&&(!field||typeof (accepted.normalizedValue as Json|null)?.[field]!=="undefined"))continue;if(q.targetConcept==="INSTALLATION_FIT"&&!accepted)continue;if(input.state.askedQuestionKeys.includes(q.questionKey)&&(input.state.candidateSnapshotRef===materialityAuthorityFingerprint||input.state.candidateSnapshotRef===e.evaluationFingerprint))continue;const count=distinctValues(input,p,q,remaining);if(count===null)return fail("UNKNOWN_POLICY_DISCRIMINATOR");if(count<2)continue;return{kind:"ASK",questionKey:q.questionKey,message:q.realization.textTr,targetConcept:q.targetConcept,priority:q.priority,answerDomain:q.answerDomain,templateRef:q.realization.templateRef,materiality:{discriminator:q.materiality.requiresCandidateDifference,distinctCandidateValues:count,missingContextCondition:q.materiality.requiresContextCondition},contextRevision:input.state.revision,evaluationFingerprint:e.evaluationFingerprint,materialityAuthorityFingerprint,questionPolicyId:p.policyId,questionPolicyDigest:input.policy.snapshot.policyDigest,selectionPolicyVersion:APPLIANCES_QUESTION_SELECTION_POLICY_VERSION};}
 return{kind:"NO_AUTHORIZED_MATERIAL_QUESTION",contextRevision:input.state.revision,evaluationFingerprint:e.evaluationFingerprint,questionPolicyId:p.policyId,questionPolicyDigest:input.policy.snapshot.policyDigest,meaning:"NEUTRAL_PLANNING_ABSENCE"};
}
