import { describe,expect,it } from "vitest";
import { createFileSystemAppliancesArtifactRepository,loadActiveAppliancesAuthority } from "../authority/loader.server";
import { enterAppliancesDepartment } from "../entry.server";
import { createFileSystemQuestionPolicyRepository } from "../governance/questionPolicyLoader.server";
import { MemoryAppliancesConversationStore } from "../persistence/memoryStore.testSupport";
import { commitAppliancesBootstrap } from "../persistence/service";
import { runAppliancesQuestionPlanning } from "./runtime.server";

const id="33333333-3333-4333-8333-333333333333";
async function setup(){const artifactRepository=createFileSystemAppliancesArtifactRepository(process.cwd()),policyRepository=createFileSystemQuestionPolicyRepository(process.cwd()),loaded=await loadActiveAppliancesAuthority({repository:artifactRepository});if(loaded.status!=="READY")throw new Error(loaded.reason);const entry=await enterAppliancesDepartment({repository:artifactRepository,productType:"WASHING_MACHINE",conversationId:id,now:new Date("2026-09-03T09:00:00Z")});if(entry.status!=="READY")throw new Error(entry.status);const store=new MemoryAppliancesConversationStore();await commitAppliancesBootstrap({store,state:entry.state,messageId:"bootstrap",payload:{action:"CREATE"}});return{store,artifactRepository,policyRepository};}
describe("Appliances Question Planner recording boundary",()=>{
 it("records one ASK with one revision increment and exact idempotent replay",async()=>{const setupValue=await setup(),input={...setupValue,conversationId:id,messageId:"plan-1",expectedRevision:1,now:new Date("2026-09-03T12:00:00+03:00")};const first=await runAppliancesQuestionPlanning(input),replay=await runAppliancesQuestionPlanning(input);expect(first).toMatchObject({status:"OK",replayed:false,plan:{kind:"ASK",questionKey:"appliances.wm.remoteControl.requirement"}});expect(replay).toEqual({...first,replayed:true});const stored=await setupValue.store.load(id);expect(stored?.state).toMatchObject({revision:2,lastQuestionKey:"appliances.wm.remoteControl.requirement"});expect(stored?.state.askedQuestionKeys).toEqual(["appliances.wm.remoteControl.requirement"]);expect(Object.keys(stored?.messages??{})).toHaveLength(2);});
 it("does not repeat a recorded ASK merely because recording incremented revision",async()=>{const s=await setup();await runAppliancesQuestionPlanning({...s,conversationId:id,messageId:"plan-1",expectedRevision:1,now:new Date("2026-09-03T12:00:00+03:00")});const next=await runAppliancesQuestionPlanning({...s,conversationId:id,messageId:"plan-2",expectedRevision:2,now:new Date("2026-09-03T12:00:00+03:00")});expect(next).not.toMatchObject({plan:{questionKey:"appliances.wm.remoteControl.requirement"}});});
 it("rejects stale revision and same message id with a different payload hash",async()=>{const s=await setup();expect(await runAppliancesQuestionPlanning({...s,conversationId:id,messageId:"plan",expectedRevision:0,now:new Date("2026-09-03T12:00:00+03:00")})).toEqual({status:"REVISION_CONFLICT"});await runAppliancesQuestionPlanning({...s,conversationId:id,messageId:"plan",expectedRevision:1,now:new Date("2026-09-03T12:00:00+03:00")});expect(await runAppliancesQuestionPlanning({...s,conversationId:id,messageId:"plan",expectedRevision:2,now:new Date("2026-09-03T12:00:00+03:00")})).toEqual({status:"MESSAGE_PAYLOAD_CONFLICT"});});
});
