import { getLaunchDomainStatuses, type LaunchDomain } from "./launchControl";
export type DeliveryWave = "W1_DECISIONS" | "W2_STAGING_FOUNDATION" | "W3_INTEGRATION_VALIDATION" | "W4_CONTROLLED_PILOT" | "W5_PRODUCTION_SCALE";
export type DeliveryOwner = "PRODUCT" | "ENGINEERING" | "SECURITY" | "LEGAL_PRIVACY" | "OPERATIONS" | "DATA_AI" | "COMMERCIAL";
export interface DeliveryWorkstream { readonly domain: LaunchDomain; readonly wave: DeliveryWave; readonly primaryOwner: DeliveryOwner; readonly supportingOwners: readonly DeliveryOwner[]; readonly requiresExternalDecision: boolean; readonly requiresRealEnvironment: boolean; readonly exitEvidence: readonly string[] }
export const usedCarsDeliveryWorkstreams: readonly DeliveryWorkstream[] = Object.freeze([
  { domain: "PRODUCT_GOVERNANCE", wave: "W1_DECISIONS", primaryOwner: "PRODUCT", supportingOwners: ["LEGAL_PRIVACY", "SECURITY", "OPERATIONS"], requiresExternalDecision: true, requiresRealEnvironment: false, exitEvidence: ["10 signed decision approvals"] },
  { domain: "LEGAL_GOVERNANCE", wave: "W1_DECISIONS", primaryOwner: "LEGAL_PRIVACY", supportingOwners: ["PRODUCT", "COMMERCIAL"], requiresExternalDecision: true, requiresRealEnvironment: false, exitEvidence: ["active legal artifact manifest"] },
  { domain: "DATA_GOVERNANCE", wave: "W1_DECISIONS", primaryOwner: "LEGAL_PRIVACY", supportingOwners: ["SECURITY", "DATA_AI"], requiresExternalDecision: true, requiresRealEnvironment: false, exitEvidence: ["approved processing inventory", "DPIA decisions"] },
  { domain: "VENDOR_GOVERNANCE", wave: "W1_DECISIONS", primaryOwner: "SECURITY", supportingOwners: ["LEGAL_PRIVACY", "ENGINEERING", "COMMERCIAL"], requiresExternalDecision: true, requiresRealEnvironment: false, exitEvidence: ["approved provider portfolio"] },
  { domain: "IDENTITY", wave: "W2_STAGING_FOUNDATION", primaryOwner: "SECURITY", supportingOwners: ["ENGINEERING"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["MFA/recovery/rotation test report"] },
  { domain: "DATABASE_RLS", wave: "W2_STAGING_FOUNDATION", primaryOwner: "ENGINEERING", supportingOwners: ["SECURITY", "LEGAL_PRIVACY"], requiresExternalDecision: false, requiresRealEnvironment: true, exitEvidence: ["PostgreSQL RLS adversarial report", "rollback result"] },
  { domain: "DEPLOYMENT", wave: "W2_STAGING_FOUNDATION", primaryOwner: "ENGINEERING", supportingOwners: ["SECURITY"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["host isolation report", "rollback drill"] },
  { domain: "SUPPLY_CHAIN", wave: "W2_STAGING_FOUNDATION", primaryOwner: "SECURITY", supportingOwners: ["ENGINEERING"], requiresExternalDecision: false, requiresRealEnvironment: true, exitEvidence: ["signed SBOM/provenance", "promotion verification"] },
  { domain: "API_GOVERNANCE", wave: "W2_STAGING_FOUNDATION", primaryOwner: "ENGINEERING", supportingOwners: ["SECURITY"], requiresExternalDecision: false, requiresRealEnvironment: true, exitEvidence: ["contract compatibility suite", "load test"] },
  { domain: "OBSERVABILITY", wave: "W2_STAGING_FOUNDATION", primaryOwner: "ENGINEERING", supportingOwners: ["SECURITY", "LEGAL_PRIVACY"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["redaction canary", "dashboard/alert evidence"] },
  { domain: "RESILIENCE", wave: "W2_STAGING_FOUNDATION", primaryOwner: "ENGINEERING", supportingOwners: ["SECURITY", "OPERATIONS"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["restore/failover drill"] },
  { domain: "PRIVACY_OPERATIONS", wave: "W3_INTEGRATION_VALIDATION", primaryOwner: "LEGAL_PRIVACY", supportingOwners: ["ENGINEERING", "OPERATIONS", "SECURITY"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["DSAR/export/deletion drill"] },
  { domain: "SECURITY_VALIDATION", wave: "W3_INTEGRATION_VALIDATION", primaryOwner: "SECURITY", supportingOwners: ["ENGINEERING"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["independent pentest", "retest closure"] },
  { domain: "ACCESSIBILITY", wave: "W3_INTEGRATION_VALIDATION", primaryOwner: "PRODUCT", supportingOwners: ["ENGINEERING", "OPERATIONS"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["device/AT audit matrix"] },
  { domain: "CONTENT_GOVERNANCE", wave: "W3_INTEGRATION_VALIDATION", primaryOwner: "PRODUCT", supportingOwners: ["LEGAL_PRIVACY", "DATA_AI"], requiresExternalDecision: true, requiresRealEnvironment: false, exitEvidence: ["approved production copy manifest"] },
  { domain: "MODEL_GOVERNANCE", wave: "W3_INTEGRATION_VALIDATION", primaryOwner: "DATA_AI", supportingOwners: ["PRODUCT", "SECURITY", "LEGAL_PRIVACY"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["fairness/red-team/shadow eval"] },
  { domain: "EXPERIMENT_GOVERNANCE", wave: "W3_INTEGRATION_VALIDATION", primaryOwner: "PRODUCT", supportingOwners: ["DATA_AI", "LEGAL_PRIVACY", "SECURITY"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["kill-switch and audit test"] },
  { domain: "FEED_INTEGRATION", wave: "W3_INTEGRATION_VALIDATION", primaryOwner: "ENGINEERING", supportingOwners: ["OPERATIONS", "SECURITY"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["sandbox certification", "reconciliation drill"] },
  { domain: "TAXONOMY", wave: "W4_CONTROLLED_PILOT", primaryOwner: "DATA_AI", supportingOwners: ["LEGAL_PRIVACY", "OPERATIONS"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["licensed pilot release manifest"] },
  { domain: "HUMAN_OPERATIONS", wave: "W4_CONTROLLED_PILOT", primaryOwner: "OPERATIONS", supportingOwners: ["SECURITY", "LEGAL_PRIVACY"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["staffing roster", "runbook rehearsals"] },
  { domain: "MODERATION_INCIDENT", wave: "W4_CONTROLLED_PILOT", primaryOwner: "OPERATIONS", supportingOwners: ["SECURITY", "LEGAL_PRIVACY"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["moderation and incident drills"] },
  { domain: "DATA_QUALITY", wave: "W4_CONTROLLED_PILOT", primaryOwner: "DATA_AI", supportingOwners: ["ENGINEERING", "OPERATIONS"], requiresExternalDecision: false, requiresRealEnvironment: true, exitEvidence: ["freshness/duplicate dashboards", "correction rehearsal"] },
  { domain: "PILOT_OPERATIONS", wave: "W4_CONTROLLED_PILOT", primaryOwner: "OPERATIONS", supportingOwners: ["PRODUCT", "LEGAL_PRIVACY", "SECURITY"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["approved city/dealer/stock cohort"] },
  { domain: "COMMERCIAL", wave: "W5_PRODUCTION_SCALE", primaryOwner: "COMMERCIAL", supportingOwners: ["LEGAL_PRIVACY", "PRODUCT", "ENGINEERING"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["billing/tax/refund certification", "ranking audit"] },
  { domain: "CONVERSATIONAL_COMMERCE", wave: "W5_PRODUCTION_SCALE", primaryOwner: "PRODUCT", supportingOwners: ["DATA_AI", "LEGAL_PRIVACY", "OPERATIONS", "SECURITY"], requiresExternalDecision: true, requiresRealEnvironment: true, exitEvidence: ["provider approvals", "AI/video/channel safety drills"] },
]);

export function createDeliveryWorkstreamReport() {
  const statuses = new Map(getLaunchDomainStatuses().map((status) => [status.domain, status]));
  const waves = (["W1_DECISIONS", "W2_STAGING_FOUNDATION", "W3_INTEGRATION_VALIDATION", "W4_CONTROLLED_PILOT", "W5_PRODUCTION_SCALE"] as const).map((wave) => {
    const workstreams = usedCarsDeliveryWorkstreams.filter((item) => item.wave === wave);
    return Object.freeze({ wave, domains: Object.freeze(workstreams.map((item) => item.domain)), openChecks: workstreams.reduce((count, item) => count + (statuses.get(item.domain)?.missing.length ?? 0), 0), externalDecisionDomains: workstreams.filter((item) => item.requiresExternalDecision).length, realEnvironmentDomains: workstreams.filter((item) => item.requiresRealEnvironment).length });
  });
  return Object.freeze({ domainCoverageComplete: usedCarsDeliveryWorkstreams.length === statuses.size && usedCarsDeliveryWorkstreams.every((item) => statuses.has(item.domain)), totalOpenChecks: [...statuses.values()].reduce((count, status) => count + status.missing.length, 0), waves: Object.freeze(waves), productionAuthorizationChanged: false as const });
}
