import type {LaunchStage} from "./launchControl";
export interface StageGate {readonly stage:LaunchStage;readonly predecessor:LaunchStage|null;readonly allowsRealData:boolean;readonly allowsExternalCommunication:boolean;readonly allowsCharges:boolean;readonly requiresNamedApprover:boolean;readonly requiresRollbackPlan:boolean}
export const usedCarsStageGates:readonly StageGate[]=Object.freeze([
 {stage:"SYNTHETIC_MVP",predecessor:null,allowsRealData:false,allowsExternalCommunication:false,allowsCharges:false,requiresNamedApprover:false,requiresRollbackPlan:false},
 {stage:"STAGING_INTEGRATION",predecessor:"SYNTHETIC_MVP",allowsRealData:false,allowsExternalCommunication:false,allowsCharges:false,requiresNamedApprover:true,requiresRollbackPlan:true},
 {stage:"CONTROLLED_PILOT",predecessor:"STAGING_INTEGRATION",allowsRealData:true,allowsExternalCommunication:true,allowsCharges:false,requiresNamedApprover:true,requiresRollbackPlan:true},
 {stage:"PRODUCTION",predecessor:"CONTROLLED_PILOT",allowsRealData:true,allowsExternalCommunication:true,allowsCharges:true,requiresNamedApprover:true,requiresRollbackPlan:true},
]);
export function validateStagePromotion(input:{readonly target:LaunchStage;readonly completedStages:readonly LaunchStage[];readonly namedApproverId:string|null;readonly rollbackPlanChecksum:string|null;readonly explicitScopeAuthorization:boolean}){const gate=usedCarsStageGates.find(item=>item.stage===input.target);if(!gate)return {allowed:false,reason:"UNKNOWN_STAGE"};if(gate.predecessor&&!input.completedStages.includes(gate.predecessor))return {allowed:false,reason:"PREDECESSOR_INCOMPLETE"};if(gate.requiresNamedApprover&&!input.namedApproverId)return {allowed:false,reason:"NAMED_APPROVER_REQUIRED"};if(gate.requiresRollbackPlan&&!input.rollbackPlanChecksum?.match(/^sha256:[a-f0-9]{64}$/u))return {allowed:false,reason:"ROLLBACK_PLAN_REQUIRED"};if(!input.explicitScopeAuthorization)return {allowed:false,reason:"EXPLICIT_SCOPE_AUTHORIZATION_REQUIRED"};return {allowed:true,automaticPromotion:false as const};}
