import { validateDecisionLayerCompatibility } from "../layers/compatibility";
import type { AffordabilityTier } from "../affordability/types";
import type { VehiclePersonaTrait } from "../domain/conversationEvent";
import type { CandidateRanking, CandidateRankingResult, RankCandidatesInput, RankingSignal, RankingTierResult } from "./types";

const AFFORDABILITY: Readonly<Record<AffordabilityTier, number>> = Object.freeze({ VERIFIED_WITHIN_BUDGET: 4, ESTIMATED_WITHIN_BUDGET: 3, BUDGET_NOT_APPLIED: 2, ESTIMATED_OVER_BUDGET_CONDITIONAL: 1, PRICE_UNRESOLVED: 0, VERIFIED_OVER_BUDGET: -1, TECHNICALLY_NOT_EVALUABLE: -2, ELIMINATED: -3 });
function score(signals: readonly RankingSignal[] | undefined, id: string): number { return (signals ?? []).filter((signal) => signal.exactVariantId === id).reduce((total, signal) => total + signal.score, 0); }
function compareVectors(left: CandidateRankingResult, right: CandidateRankingResult): number { for (let index = 0; index < left.rankVector.length; index += 1) { const difference = right.rankVector[index]!.score - left.rankVector[index]!.score; if (difference) return difference; } return left.modelFamilyId.localeCompare(right.modelFamilyId) || left.exactVariantId.localeCompare(right.exactVariantId); }
export function rankSelectableCandidates(input: RankCandidatesInput): CandidateRanking {
  const diagnostics = validateDecisionLayerCompatibility({ snapshot: input.snapshot, dailyLife: input.dailyLifeLayer, persona: input.personaLayer }); const dailyCompatible = !diagnostics.some((item) => item.code === "DAILY_LIFE_LAYER_INCOMPATIBLE"); const personaCompatible = !diagnostics.some((item) => item.code === "PERSONA_LAYER_INCOMPATIBLE");
  const affordabilityById = new Map(input.affordabilityPool.candidates.map((candidate) => [candidate.exactVariantId, candidate])); const technicalById = new Map(input.technicalPool.candidates.map((candidate) => [candidate.exactVariantId, candidate])); const usageById = new Map((input.usageEvaluations ?? []).map((evaluation) => [evaluation.exactVariantId, evaluation]));
  const results: CandidateRankingResult[] = input.affordabilityPool.selectableCandidateIds.map((id) => {
    const affordability = affordabilityById.get(id)!; const technical = technicalById.get(id)!; const usage = usageById.get(id); const dailySignals = dailyCompatible ? (input.dailyLifeLayer?.signals ?? []).filter((signal) => signal.exactVariantId === id) : []; const rankableDaily = dailySignals.filter((signal) => signal.decisionUse === "SOFT_UNTIL_CONFIRMED");
    const requested: readonly VehiclePersonaTrait[] = input.persona.activated ? input.persona.requestedTraits : []; const personaSignals = input.persona.activated && personaCompatible ? (input.personaLayer?.signals ?? []).filter((signal) => signal.exactVariantId === id && requested.includes(signal.trait)) : []; const matchedTraits = [...new Set(personaSignals.map((signal) => signal.trait))].sort();
    const functionalScore = score(input.confirmedFunctionalSignals, id); const usageScore = (usage?.rankingSignals ?? []).reduce((total, signal) => total + (signal.direction === "POSITIVE" ? signal.strength === "STRONG" ? 2 : 1 : 0), 0); const preferredBudgetSignals = affordability.softSignals.filter((signal) => ["WITHIN_PREFERRED_BUDGET", "OVER_PREFERRED_BUDGET", "BELOW_BUDGET_RANGE", "WITHIN_BUDGET_RANGE", "OVER_BUDGET_RANGE"].includes(signal.kind)); const preferredBudgetFit = preferredBudgetSignals.reduce((total, signal) => total + (signal.rankingScore ?? 0), 0); const dailyScore = rankableDaily.reduce((total, signal) => total + signal.rankingEffect, 0); const softScore = score(input.softPreferenceSignals, id); const personaScore = personaSignals.reduce((total, signal) => total + signal.matchStrength, 0); const publicPrice = affordability.priceAuthority.publicExactAmountTry; const valueScore = publicPrice === undefined ? 0 : 1 / publicPrice;
    const tier = (name: RankingTierResult["tier"], value: number, authority: string, reasons: readonly string[] = []): RankingTierResult => ({ tier: name, score: value, authority, reasonCodes: reasons });
    const rankVector = [tier("CONFIRMED_FUNCTIONAL_FIT", functionalScore, "NORMALIZED_FUNCTIONAL_SIGNAL"), tier("USAGE_SCENARIO_FIT", usageScore, "WP4_USAGE_RANKING_SIGNAL"), tier("AFFORDABILITY_TIER", AFFORDABILITY[affordability.affordabilityTier], "WP6.1_AFFORDABILITY_TIER", [affordability.affordabilityTier]), tier("PREFERRED_BUDGET_FIT", preferredBudgetFit, "WP6_PREFERRED_BUDGET_SOFT_SIGNAL", preferredBudgetSignals.map((signal) => signal.kind)), tier("GUIDED_DAILY_LIFE_FIT", dailyScore, "COMPATIBLE_DAILY_LIFE_LAYER", rankableDaily.map((signal) => signal.mappingId)), tier("EXPLICIT_SOFT_PREFERENCE", softScore, "NORMALIZED_EXPLICIT_PREFERENCE"), tier("PERSONA_FIT", personaScore, "EXPLICIT_PERSONA_LAYER", matchedTraits), tier("VERIFIED_VALUE_SIGNAL", valueScore, publicPrice === undefined ? "NONE" : "PUBLIC_VERIFIED_CURRENT_PRICE")];
    const personaTrace = { personaActivated: input.persona.activated, ...(input.persona.activated ? { activationSource: input.persona.activationSource } : {}), requestedPersonaTraits: [...requested], matchedPersonaTraits: matchedTraits, personaScore, affectedRanking: personaScore !== 0, sourceAuthority: personaSignals[0]?.authority ?? "NONE", decisionUse: input.persona.activated ? "LEXICOGRAPHIC_TIER_6" as const : "NONE" as const };
    const dailyLifeTrace = { mappings: dailySignals.map(({ mappingId, authority, mappingClass, decisionUse, rankingEffect }) => ({ mappingId, authority, mappingClass, decisionUse, rankingEffect })), score: dailyScore, affectedRanking: dailyScore !== 0 };
    return { exactVariantId: id, modelFamilyId: technical.modelFamilyId, affordabilityTier: affordability.affordabilityTier, rankVector, rankingReasonCodes: rankVector.flatMap((item) => item.reasonCodes), explanationFactInputs: [...(input.confirmedFunctionalSignals ?? []), ...(input.softPreferenceSignals ?? [])].filter((signal) => signal.exactVariantId === id && signal.explanationFactId).map((signal) => signal.explanationFactId!), personaTrace, dailyLifeTrace, finalOrdinal: 0 };
  });
  results.sort(compareVectors); const ranked = results.map((candidate, index) => ({ ...candidate, finalOrdinal: index + 1 }));
  return Object.freeze({ catalogFingerprint: input.snapshot.authority.catalogFingerprint, decisionFingerprint: input.affordabilityPool.decisionFingerprint, rankedCandidateIds: Object.freeze(ranked.map((candidate) => candidate.exactVariantId)), priceUnresolvedCandidateIds: input.affordabilityPool.priceUnresolvedCandidateIds, candidates: Object.freeze(ranked), diagnostics });
}
