import { describe, expect, it } from "vitest";
import { buildCatalogSnapshot } from "../catalog/snapshot";
import { release, sourced, variant } from "../catalog/testFixtures.testSupport";
import { evaluateTechnicalCandidatePool } from "../filter/pipeline";
import { V2_DECISION_FIELD_REGISTRY_V1 } from "../filter/registry";
import { USAGE_CARGO_POLICIES_V1 } from "../usage/policy";
import { evaluateAffordabilityCandidatePool } from "../affordability/evaluate";
import { AFFORDABILITY_POLICY_V1, PRICE_AUTHORITY_POLICY_V1 } from "../affordability/policy";
import { rankSelectableCandidates } from "./evaluate";
import { selectRankedCandidateShortlist } from "./shortlist";

const NOW = "2026-08-20T00:00:00.000Z";
function price(id: string, amount: number, estimate = false) { return { id: `p-${id}`, vehicleVariantId: id, market: "TR", condition: "NEW", amountTry: amount, priceType: estimate ? "ESTIMATE" : "LIST", consumerVisibility: estimate ? "INTERNAL_ONLY" : "PUBLIC", estimationMethod: estimate ? "bounded" : undefined, validFrom: "2026-08-19T00:00:00.000Z", provenance: sourced("p").provenance, confidence: "HIGH" }; }
async function base() {
  const records = [
    { ...variant("v1", "Generic A", "Family One", "Base", { bodyStyle: sourced("SUV") }), activeNewPrice: price("v1", 1_800_000) },
    { ...variant("v2", "Generic A", "Family One", "Plus", { bodyStyle: sourced("SUV") }), activeNewPrice: price("v2", 1_700_000) },
    { ...variant("v3", "Generic B", "Family Two", "Base", { bodyStyle: sourced("SUV") }), activeNewPrice: price("v3", 1_900_000, true) },
    { ...variant("v4", "Generic C", "Family Three", "Base", { bodyStyle: sourced("SUV") }), activeNewPrice: price("v4", 2_300_000, true) },
  ]; const fixture = release("1.0.0", records as unknown as ReturnType<typeof variant>[]); const loaded = await buildCatalogSnapshot({ pointer: fixture.pointer, manifest: fixture.manifest, catalog: fixture.catalog, decisionFacets: fixture.facets, now: new Date(NOW) }); if (loaded.status !== "READY") throw new Error(loaded.reason);
  const technicalPool = evaluateTechnicalCandidatePool({ snapshot: loaded.snapshot, decisionFingerprint: "decision", activeConstraints: { activeHardConstraints: [], activeNonHardConstraints: [], supersessionTrace: [], diagnostics: [] }, activeRejections: { rejections: [] }, usageNeed: { commercialScenario: "UNSPECIFIED", orientation: "UNKNOWN" }, fieldRegistry: V2_DECISION_FIELD_REGISTRY_V1, usagePolicies: USAGE_CARGO_POLICIES_V1 });
  const affordabilityPool = evaluateAffordabilityCandidatePool({ snapshot: loaded.snapshot, technicalPool, budget: { maximumHardCeiling: { amount: 2_000_000, currency: "TRY" }, financeFlexibility: "NONE", unresolvedFinancedCeiling: false, budgetImportance: "HARD", budgetUnknown: false, budgetExcluded: false }, evaluationTime: NOW, priceAuthorityPolicy: PRICE_AUTHORITY_POLICY_V1, affordabilityPolicy: AFFORDABILITY_POLICY_V1 }); return { snapshot: loaded.snapshot, technicalPool, affordabilityPool };
}

describe("WP7 lexicographic ranking", () => {
  it("lets confirmed functional fit outrank affordability without a weighted sum", async () => { const input = await base(); const ranking = rankSelectableCandidates({ ...input, persona: { activated: false, requestedTraits: [] }, confirmedFunctionalSignals: [{ exactVariantId: "v4", score: 1, reasonCode: "FUNCTIONAL_MATCH" }] }); expect(ranking.rankedCandidateIds[0]).toBe("v4"); });
  it("orders affordability only after functional and usage tiers", async () => { const input = await base(); const ranking = rankSelectableCandidates({ ...input, persona: { activated: false, requestedTraits: [] } }); expect(ranking.rankedCandidateIds.slice(0, 2)).toEqual(["v2", "v1"]); expect(ranking.rankedCandidateIds.at(-1)).toBe("v4"); });
  it("uses persona only when explicitly activated and never adds candidates", async () => { const input = await base(); const layer = { catalogReleaseVersion: input.snapshot.authority.releaseVersion, catalogFingerprint: input.snapshot.authority.catalogFingerprint, layerVersion: "1", signals: [{ exactVariantId: "v1", trait: "DESIGN" as const, authority: "OWNER_EDITORIAL", matchStrength: 3 as const }] }; const off = rankSelectableCandidates({ ...input, persona: { activated: false, requestedTraits: [] }, personaLayer: layer }); const on = rankSelectableCandidates({ ...input, persona: { activated: true, activationSource: "USER_EXPLICIT", requestedTraits: ["DESIGN"], sourceTurn: 1 }, personaLayer: layer }); expect(off.candidates.find((item) => item.exactVariantId === "v1")?.personaTrace.personaScore).toBe(0); expect(on.candidates.find((item) => item.exactVariantId === "v1")?.personaTrace.personaScore).toBe(3); expect(on.rankedCandidateIds).toHaveLength(input.affordabilityPool.selectableCandidateIds.length); });
  it("ranks only SOFT_UNTIL_CONFIRMED daily-life signals and traces illustrative mappings", async () => { const input = await base(); const dailyLifeLayer = { catalogReleaseVersion: input.snapshot.authority.releaseVersion, catalogFingerprint: input.snapshot.authority.catalogFingerprint, layerVersion: "1", signals: [{ exactVariantId: "v1", mappingId: "soft", authority: "POLICY", mappingClass: "GUIDED", decisionUse: "SOFT_UNTIL_CONFIRMED" as const, rankingEffect: 1 as const }, { exactVariantId: "v2", mappingId: "example", authority: "POLICY", mappingClass: "EXAMPLE", decisionUse: "ILLUSTRATIVE_ONLY" as const, rankingEffect: 1 as const }] }; const ranking = rankSelectableCandidates({ ...input, persona: { activated: false, requestedTraits: [] }, dailyLifeLayer }); expect(ranking.rankedCandidateIds[0]).toBe("v1"); expect(ranking.candidates.find((item) => item.exactVariantId === "v2")?.dailyLifeTrace.score).toBe(0); });
  it("fails closed on incompatible layers", async () => { const input = await base(); const ranking = rankSelectableCandidates({ ...input, persona: { activated: false, requestedTraits: [] }, dailyLifeLayer: { catalogReleaseVersion: "wrong", catalogFingerprint: "wrong", layerVersion: "1", signals: [] } }); expect(ranking.diagnostics.map((item) => item.code)).toContain("DAILY_LIFE_LAYER_INCOMPATIBLE"); });
  it("selects at most one exact variant per family by default", async () => { const input = await base(); const ranking = rankSelectableCandidates({ ...input, persona: { activated: false, requestedTraits: [] } }); const diverse = selectRankedCandidateShortlist({ ranking, maximumCandidates: 3 }); expect(diverse.candidateIds).toHaveLength(3); expect(new Set(diverse.candidateIds.map((id) => ranking.candidates.find((item) => item.exactVariantId === id)!.modelFamilyId)).size).toBe(3); expect(selectRankedCandidateShortlist({ ranking, singleRequested: true }).candidateIds).toHaveLength(1); expect(selectRankedCandidateShortlist({ ranking, explicitTrimComparisonRequested: true }).mode).toBe("TRIM_COMPARISON"); });
  it("is deterministic", async () => { const input = await base(); expect(rankSelectableCandidates({ ...input, persona: { activated: false, requestedTraits: [] } })).toEqual(rankSelectableCandidates({ ...input, persona: { activated: false, requestedTraits: [] } })); });
});
