// Generated by scripts/sync-active-technical-daily-life.ts. Do not edit manually.
export { default as activeTechnicalDailyLifePayload } from "./releases/v2.1-0.55.1-2026-08-16-compatibility-rebind/technical-daily-life.json";
export { default as activeTechnicalDailyLifeManifest } from "./releases/v2.1-0.55.1-2026-08-16-compatibility-rebind/manifest.json";
export const activeTechnicalDailyLifeRelease = "v2.1-0.55.1-2026-08-16-compatibility-rebind";
export const compatibleTechnicalDailyLifeCatalogRelease = "v0.55.1";
