import type { Pool,PoolClient } from "pg";
import type { AppliancesConversationState,AppliancesStoredMessage,AppliancesStoredOutcome } from "../contracts";
import type { AppliancesCommitResult,AppliancesConversationStore } from "./types";
export class PostgresAppliancesConversationStore implements AppliancesConversationStore {
 constructor(private readonly pool:Pick<Pool,"connect">){}
 async load(conversationId:string){const client=await this.pool.connect();try{const conversation=await client.query("select state from appliances_conversations where conversation_id=$1",[conversationId]);if(!(conversation.rowCount??0))return null;const messages=await client.query("select message_id,payload_hash,committed_revision,stored_outcome from appliances_conversation_messages where conversation_id=$1",[conversationId]);return{state:conversation.rows[0].state as AppliancesConversationState,messages:Object.fromEntries(messages.rows.map(row=>[row.message_id,{messageId:row.message_id,payloadHash:row.payload_hash,committedRevision:row.committed_revision,outcome:row.stored_outcome} satisfies AppliancesStoredMessage]))};}finally{client.release();}}
 async commit(input:Parameters<AppliancesConversationStore["commit"]>[0]):Promise<AppliancesCommitResult>{const client=await this.pool.connect();try{await client.query("begin");const prior=await client.query("select payload_hash,stored_outcome from appliances_conversation_messages where conversation_id=$1 and message_id=$2 for update",[input.nextState.conversationId,input.messageId]);if(prior.rowCount){if(prior.rows[0].payload_hash!==input.payloadHash){await client.query("rollback");return{status:"MESSAGE_PAYLOAD_CONFLICT"};}await client.query("commit");return{status:"OK",outcome:prior.rows[0].stored_outcome as AppliancesStoredOutcome};}const locked=await client.query("select revision from appliances_conversations where conversation_id=$1 for update",[input.nextState.conversationId]);const exists=Boolean(locked.rowCount);const revision=exists?Number(locked.rows[0].revision):0;if(revision!==input.expectedRevision||input.nextState.revision!==revision+1){await client.query("rollback");return{status:"REVISION_CONFLICT"};}if(exists)await this.update(client,input.nextState);else await this.insert(client,input.nextState);for(const event of input.events)await client.query("insert into appliances_conversation_events (conversation_id,event_id,concept_id,canonical_event,created_revision,created_at) values ($1,$2,$3,$4,$5,$6)",[input.nextState.conversationId,event.eventId,event.conceptId,event,event.createdRevision,event.createdAt]);const outcome:AppliancesStoredOutcome={kind:input.outcomeKind,conversationId:input.nextState.conversationId,revision:input.nextState.revision,state:input.nextState,...(input.publicOutcome?{publicOutcome:input.publicOutcome}:{})};await client.query("insert into appliances_conversation_messages (conversation_id,message_id,payload_hash,committed_revision,stored_outcome) values ($1,$2,$3,$4,$5)",[input.nextState.conversationId,input.messageId,input.payloadHash,input.nextState.revision,outcome]);await client.query("commit");return{status:"OK",outcome};}catch(error){await client.query("rollback");throw error;}finally{client.release();}}
 private insert(client:PoolClient,state:AppliancesConversationState){return client.query("insert into appliances_conversations (conversation_id,schema_version,revision,department_id,product_type,pinned_catalog_release,pinned_catalog_digest,pinned_semantic_version,pinned_semantic_digest,state,created_at,updated_at) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)",[state.conversationId,state.schemaVersion,state.revision,state.departmentId,state.productType,state.pinnedCatalogRelease,state.pinnedCatalogDigest,state.pinnedSemanticVersion,state.pinnedSemanticDigest,state,state.createdAt,state.updatedAt]);}
 private update(client:PoolClient,state:AppliancesConversationState){return client.query("update appliances_conversations set revision=$2,state=$3,updated_at=$4 where conversation_id=$1",[state.conversationId,state.revision,state,state.updatedAt]);}
}
