/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial projection mutations verify fail-closed runtime behavior */
import { beforeAll, describe, expect, it } from "vitest";
import { createFileSystemAppliancesArtifactRepository, loadActiveAppliancesAuthority } from "../authority/loader.server";
import type { AppliancesAuthoritySnapshot, PriceProjectionLoadResult } from "../authority/types";
import { evaluateAppliancesCandidates } from "../candidate/evaluate";
import type { AppliancesCandidateEvaluationProjection, AppliancesCandidateEvaluationResult } from "../candidate/types";
import type { AppliancesConversationState, AppliancesLedgerEvent } from "../contracts";
import { enterAppliancesDepartment } from "../entry.server";
import { createFileSystemQuestionPolicyRepository, loadActiveWashingMachineQuestionPolicy, type QuestionPolicyLoadResult } from "../governance/questionPolicyLoader.server";
import { createFileSystemSufficiencyRecommendationPolicyRepository, loadActiveWashingMachineSufficiencyRecommendationPolicy, type SufficiencyRecommendationPolicyLoadResult } from "../governance/sufficiencyRecommendationPolicyLoader.server";
import type { AppliancesQuestionPlan } from "../planner/types";
import { evaluateAppliancesSufficiency } from "./evaluate";
import { activeCatalogPriceFixture } from "../testing/activeCatalogPriceFixture";

const root = process.cwd(), repository = createFileSystemAppliancesArtifactRepository(root);
let authority: AppliancesAuthoritySnapshot, base: AppliancesConversationState, price: PriceProjectionLoadResult, questionPolicy: Extract<QuestionPolicyLoadResult, { status: "READY" }>, policy: Extract<SufficiencyRecommendationPolicyLoadResult, { status: "READY" }>;
beforeAll(async () => { const loadedAuthority = await loadActiveAppliancesAuthority({ repository }); if (loadedAuthority.status !== "READY") throw new Error(loadedAuthority.reason); authority = loadedAuthority.snapshot; const entry = await enterAppliancesDepartment({ repository, productType: "WASHING_MACHINE", conversationId: "77777777-7777-4777-8777-777777777777", now: new Date("2026-09-03T06:00:00Z") }); if (entry.status !== "READY") throw new Error(entry.status); base = entry.state; price = activeCatalogPriceFixture(authority); const q = await loadActiveWashingMachineQuestionPolicy({ repository: createFileSystemQuestionPolicyRepository(root), authority }); if (q.status !== "READY") throw new Error(q.reason); questionPolicy = q; const s = await loadActiveWashingMachineSufficiencyRecommendationPolicy({ repository: createFileSystemSufficiencyRecommendationPolicyRepository(root), authority, questionPolicy: q.snapshot }); if (s.status !== "READY") throw new Error(s.reason); policy = s; });
const event = (conceptId: string, normalizedValue: unknown, decisionUse: AppliancesLedgerEvent["decisionUse"] = "HARD_FILTER", status: AppliancesLedgerEvent["status"] = "ACCEPTED_EXPLICIT"): AppliancesLedgerEvent => ({ eventId: `event:${conceptId}:${JSON.stringify(normalizedValue)}`, conceptId, normalizedValue, sourceMessageId: "message", authority: "USER_EXPLICIT", strength: decisionUse === "HARD_FILTER" ? "HARD" : "SOFT", status, decisionUse, confirmationRequired: status === "PROPOSED", createdRevision: 0, createdAt: "2026-09-03T06:00:00Z" });
const neutral = (projection: AppliancesCandidateEvaluationProjection): AppliancesQuestionPlan => ({ kind: "NO_AUTHORIZED_MATERIAL_QUESTION", contextRevision: projection.contextRevision, evaluationFingerprint: projection.evaluationFingerprint, questionPolicyId: questionPolicy.snapshot.payload.policyId, questionPolicyDigest: questionPolicy.snapshot.policyDigest, meaning: "NEUTRAL_PLANNING_ABSENCE" });
const readyEvaluation = (state: AppliancesConversationState, activePrice = price): Extract<AppliancesCandidateEvaluationResult, { status: "READY" }> => { const result = evaluateAppliancesCandidates({ authority, state, price: activePrice }); if (result.status !== "READY") throw new Error(result.reason); return result; };
const run = (state = base, evaluation = readyEvaluation(state), planner = neutral(evaluation.projection), activePrice = price, activePolicy: SufficiencyRecommendationPolicyLoadResult = policy) => evaluateAppliancesSufficiency({ authority, state, evaluation, planner, price: activePrice, policy: activePolicy });
const withCounts = (projection: AppliancesCandidateEvaluationProjection): AppliancesCandidateEvaluationProjection => ({ ...projection, counts: { total: projection.candidates.length, eligible: projection.candidates.filter((x) => x.eligibility === "ELIGIBLE").length, ineligible: projection.candidates.filter((x) => x.eligibility === "INELIGIBLE").length, unknown: projection.candidates.filter((x) => x.eligibility === "ELIGIBILITY_UNKNOWN").length, notEvaluated: projection.candidates.filter((x) => x.eligibility === "NOT_EVALUATED").length }, remainingProductRefs: projection.candidates.filter((x) => x.eligibility !== "INELIGIBLE").map((x) => x.productId) });

describe("deterministic Appliances sufficiency/recommendation-pool boundary", () => {
  it("consumes the active policy and emits a deterministic provenance-bearing non-ranked pool", () => { const first = run(), second = run(); expect(first).toEqual(second); expect(first).toMatchObject({ kind: "RECOMMENDATION_POOL_ELIGIBLE", provenance: { policyId: "WASHING_MACHINE_SUFFICIENCY_RECOMMENDATION_ENTRY_POLICY/v0.1", policyDigest: "1ea9819b5e686a6d631bff2d4e27303dd4a1769469e4259a4e215689e0408828" }, candidatePool: { canonicalOrderMeaning: "SERIALIZATION_ONLY", selectionPolicyRequired: true } }); if (first.kind === "RECOMMENDATION_POOL_ELIGIBLE") expect(first.candidatePool.candidateIds).toEqual([...authority.productIds].sort()); });
  it("maps planner ASK and CLARIFY ahead of all later gates without choosing another question", () => { const evaluation = readyEvaluation(base); const ask: AppliancesQuestionPlan = { kind: "ASK", questionKey: "appliances.wm.budget.maximumTry", message: "governed", targetConcept: "BUDGET_SENSITIVITY", priority: 40, answerDomain: {}, templateRef: "template", materiality: { discriminator: "FRESH_REPRESENTATIVE_PRICE_TRY", distinctCandidateValues: 2, missingContextCondition: "NO_ACCEPTED_HARD_BUDGET" }, contextRevision: 0, evaluationFingerprint: evaluation.projection.evaluationFingerprint, materialityAuthorityFingerprint: "0".repeat(64), questionPolicyId: questionPolicy.snapshot.payload.policyId, questionPolicyDigest: questionPolicy.snapshot.policyDigest, selectionPolicyVersion: "appliances-question-selection/v1" }; expect(run(base, evaluation, ask)).toMatchObject({ kind: "MORE_INFORMATION_REQUIRED", question: { questionKey: ask.questionKey } }); const proposed = event("LOW_NOISE_PRIORITY", true, "SOFT_RANK", "PROPOSED"), state = { ...base, ledger: [proposed], pendingConfirmation: { eventId: proposed.eventId, conceptId: proposed.conceptId, normalizedValue: true, sourceMessageId: "message", createdRevision: 0, expiresAfterRevision: 1, question: "confirm" } }; const clarification: AppliancesQuestionPlan = { kind: "CLARIFY", questionKey: "CONFIRM:LOW_NOISE_PRIORITY", message: "confirm", authoritativeEventId: proposed.eventId, targetConcept: proposed.conceptId, contextRevision: 0 }; expect(run(state, readyEvaluation(state), clarification)).toMatchObject({ kind: "CLARIFICATION_REQUIRED", clarification: { authoritativeEventId: proposed.eventId } }); });
  it("does not treat neutral no-question as sufficient when hard unknown or not-evaluated remains", () => { const evaluation = readyEvaluation(base), first = evaluation.projection.candidates[0]!; for (const eligibility of ["ELIGIBILITY_UNKNOWN", "NOT_EVALUATED"] as const) { const changed = { ...evaluation, projection: withCounts({ ...evaluation.projection, candidates: evaluation.projection.candidates.map((candidate) => candidate.productId === first.productId ? { ...candidate, eligibility, unevaluatedContextEventIds: ["hard-event"] } : candidate) }) }; expect(run(base, changed, neutral(changed.projection))).toMatchObject({ kind: "UNRESOLVED_HARD_UNCERTAINTY" }); } });
  it("keeps soft unknown non-blocking and disclosed without turning it false", () => { const state = { ...base, ledger: [event("DETERGENT_CONVENIENCE", { wanted: true }, "SOFT_RANK")] }, evaluation = readyEvaluation(state), result = run(state, evaluation); expect(result.kind).toBe("RECOMMENDATION_POOL_ELIGIBLE"); if (result.kind !== "FAILED_CLOSED") expect(result.disclosureCodes).toContain("SOFT_UNCERTAINTY_PRESENT"); expect(evaluation.projection.candidates.some((candidate) => candidate.reasons.some((reason) => reason.result === "UNKNOWN"))).toBe(true); });
  it("ignores non-accepted context and persona for the verdict", () => { const baseline = run(); for (const status of ["PROPOSED", "REJECTED", "SUPERSEDED", "CLEARED"] as const) { const state = { ...base, ledger: [event("HIGH_LAUNDRY_VOLUME", { minimumCapacityKg: 99 }, "HARD_FILTER", status)] }; expect(run(state)).toEqual(baseline); } const persona = { ...base, personaSignals: [{ signalId: "X", sourceEventIds: [], authority: "DERIVED_PLANNING" as const, directCandidateEffect: "NONE" as const, decisionUse: "NONE" as const }] }; expect(run(persona)).toEqual(baseline); });
  it("implements mixed compatible plus unknown without a global block and preserves unknown IDs", () => { const state = { ...base, ledger: [event("BUDGET_SENSITIVITY", { maximumTry: 25000 })] }, evaluation = readyEvaluation(state), result = run(state, evaluation); expect(result).toMatchObject({ kind: "RECOMMENDATION_POOL_ELIGIBLE", candidatePartitions: { budgetUnknownCandidateIds: expect.any(Array) }, disclosureCodes: expect.arrayContaining(["HARD_BUDGET_PRICE_COVERAGE_LIMITED", "BUDGET_UNKNOWN_CANDIDATES_PRESERVED"]) }); if (result.kind === "RECOMMENDATION_POOL_ELIGIBLE") { expect(result.candidatePool.candidateIds).toEqual(result.candidatePartitions.budgetCompatibleCandidateIds); expect(result.candidatePartitions.budgetUnknownCandidateIds.length).toBeGreaterThan(0); } });
  it("blocks zero-compatible plus unknown and an entirely stale price projection", async () => { const lowBudget = { ...base, ledger: [event("BUDGET_SENSITIVITY", { maximumTry: 1000 })] }, lowEvaluation = readyEvaluation(lowBudget); expect(run(lowBudget, lowEvaluation)).toMatchObject({ kind: "UNRESOLVED_HARD_UNCERTAINTY", candidatePartitions: { budgetCompatibleCandidateIds: [], budgetUnknownCandidateIds: expect.any(Array) } }); const stale = activeCatalogPriceFixture(authority, "STALE"), staleEvaluation = readyEvaluation(lowBudget, stale); expect(run(lowBudget, staleEvaluation, neutral(staleEvaluation.projection), stale)).toMatchObject({ kind: "UNRESOLVED_HARD_UNCERTAINTY", disclosureCodes: expect.arrayContaining(["PRICE_PROJECTION_STALE"]) }); });
  it("returns conclusive zero when every candidate is conclusively ineligible", () => { const evaluation = readyEvaluation(base), changed = { ...evaluation, projection: withCounts({ ...evaluation.projection, candidates: evaluation.projection.candidates.map((candidate) => ({ ...candidate, eligibility: "INELIGIBLE" as const, reasons: [{ code: "HARD_TECHNICAL_INCOMPATIBILITY" as const, result: "INCOMPATIBLE" as const, contextEventId: "hard", conceptId: "INSTALLATION_FIT", evidenceRefs: [] }], unevaluatedContextEventIds: [] })) }) }; expect(run(base, changed, neutral(changed.projection))).toMatchObject({ kind: "NO_RECOMMENDATION_ELIGIBLE_CANDIDATE" }); });
  it("returns no eligible candidate when every otherwise eligible candidate is freshly over budget", () => { const state = { ...base, ledger: [event("BUDGET_SENSITIVITY", { maximumTry: 1000 })] }, evaluation = readyEvaluation(state), changed = { ...evaluation, projection: withCounts({ ...evaluation.projection, candidates: evaluation.projection.candidates.map((candidate) => ({ ...candidate, eligibility: "INELIGIBLE" as const, reasons: [{ code: "BUDGET_INCOMPATIBLE" as const, result: "INCOMPATIBLE" as const, contextEventId: state.ledger[0]!.eventId, conceptId: "BUDGET_SENSITIVITY", evidenceRefs: ["fresh-price"] }], unevaluatedContextEventIds: [] })) }) }; expect(run(state, changed, neutral(changed.projection))).toMatchObject({ kind: "NO_RECOMMENDATION_ELIGIBLE_CANDIDATE", reasonCodes: ["ALL_CANDIDATES_CONCLUSIVELY_INELIGIBLE_INCLUDING_BUDGET"] }); });
  it("produces a non-ranked singleton and stable multiple pool regardless of input order", () => { const evaluation = readyEvaluation(base), keep = evaluation.projection.candidates[0]!, singleton = { ...evaluation, projection: withCounts({ ...evaluation.projection, candidates: evaluation.projection.candidates.map((candidate) => candidate.productId === keep.productId ? candidate : { ...candidate, eligibility: "INELIGIBLE" as const, reasons: [{ code: "HARD_TECHNICAL_INCOMPATIBILITY" as const, result: "INCOMPATIBLE" as const, contextEventId: "hard", conceptId: "INSTALLATION_FIT", evidenceRefs: [] }] }) }) }; expect(run(base, singleton, neutral(singleton.projection))).toMatchObject({ kind: "RECOMMENDATION_POOL_ELIGIBLE", candidatePool: { candidateIds: [keep.productId], selectionPolicyRequired: false } }); const reversed = { ...evaluation, projection: { ...evaluation.projection, candidates: [...evaluation.projection.candidates].reverse(), remainingProductRefs: [...evaluation.projection.remainingProductRefs].reverse() } }; expect(run(base, reversed, neutral(reversed.projection))).toEqual(run(base, evaluation)); const result = run(base, reversed, neutral(reversed.projection)); expect(JSON.stringify(result)).not.toMatch(/"(?:rank|score|winner|recommendation)"\s*:/iu); });
  it("fails closed with absolute precedence for policy candidate planner and price failures", () => { expect(run(base, readyEvaluation(base), neutral(readyEvaluation(base).projection), price, { status: "FAILED_CLOSED", reason: "POLICY_MISSING" })).toEqual({ kind: "FAILED_CLOSED", reason: "SUFFICIENCY_POLICY_AUTHORITY_FAILURE" }); expect(evaluateAppliancesSufficiency({ authority, state: base, evaluation: { status: "FAILED_CLOSED", reason: "CATALOG_INTEGRITY_FAILURE" }, planner: { kind: "FAILED_CLOSED", reason: "CANDIDATE_EVALUATION_FAILURE" }, price, policy })).toEqual({ kind: "FAILED_CLOSED", reason: "CANDIDATE_EVALUATION_FAILED_CLOSED" }); expect(run(base, readyEvaluation(base), { kind: "FAILED_CLOSED", reason: "RUNTIME_POLICY_DIVERGENCE" })).toEqual({ kind: "FAILED_CLOSED", reason: "PLANNER_FAILED_CLOSED" }); const budget = { ...base, ledger: [event("BUDGET_SENSITIVITY", { maximumTry: 25000 })] }; expect(evaluateAppliancesSufficiency({ authority, state: budget, evaluation: { status: "FAILED_CLOSED", reason: "PRICE_INTEGRITY_FAILURE" }, planner: { kind: "FAILED_CLOSED", reason: "CANDIDATE_EVALUATION_FAILURE" }, price: { status: "UNAVAILABLE", reason: "PRICE_BINDING_MISMATCH" }, policy })).toEqual({ kind: "FAILED_CLOSED", reason: "INVALID_PRICE_BINDING" }); });
  it.each([
    ["revision", (e: any) => e.projection.contextRevision++, "CONTEXT_REVISION_MISMATCH"], ["evaluation fingerprint", (e: any) => e.projection.evaluationFingerprint = "bad", "CANDIDATE_FINGERPRINT_MISMATCH"], ["context fingerprint", (e: any) => e.projection.contextFingerprint = "0".repeat(64), "CANDIDATE_FINGERPRINT_MISMATCH"], ["duplicate", (e: any) => e.projection.candidates[1].productId = e.projection.candidates[0].productId, "DUPLICATE_CANDIDATE_ID"], ["unknown id", (e: any) => e.projection.candidates[0].productId = "unknown", "UNKNOWN_CANDIDATE_ID"], ["counts", (e: any) => e.projection.counts.total = 99, "IMPOSSIBLE_AGGREGATE_COUNTS"]
  ])("fails closed for malformed %s projection", (_kind, mutate, reason) => { const evaluation = structuredClone(readyEvaluation(base)) as any; mutate(evaluation); expect(run(base, evaluation, neutral(evaluation.projection))).toEqual({ kind: "FAILED_CLOSED", reason }); });
  it("keeps an invalid price binding neutral when no hard budget is active", () => { expect(run(base, readyEvaluation(base), undefined, { status: "UNAVAILABLE", reason: "PRICE_BINDING_MISMATCH" })).toMatchObject({ kind: "RECOMMENDATION_POOL_ELIGIBLE" }); });
  it("keeps capacity excluded and scope-bounded", () => { const state = { ...base, ledger: [event("HIGH_LAUNDRY_VOLUME", { minimumCapacityKg: 99 })] }, result = run(state); expect(result.kind).toBe("RECOMMENDATION_POOL_ELIGIBLE"); expect(JSON.stringify(result)).not.toMatch(/"(?:decisionReady|decisionAuthorization|decisionCard|advisor|sellerAction|affiliateAction)"\s*:/iu); });
});
