import { createHash } from "node:crypto";
import { projectActiveAppliancesContext } from "../context/projection";
import { SUFFICIENCY_OUTCOME_PRECEDENCE } from "../governance/sufficiencyRecommendationPolicyAuthority";
import { APPLIANCES_CANDIDATE_EVALUATION_POLICY_VERSION, type AppliancesCandidateEvaluation, type CandidateReason } from "../candidate/types";
import { fingerprintActiveAppliancesContext } from "../candidate/evaluate";
import { APPLIANCES_QUESTION_SELECTION_POLICY_VERSION } from "../planner/types";
import { APPLIANCES_SUFFICIENCY_RUNTIME_VERSION, type AppliancesCandidatePartitions, type AppliancesSufficiencyFailureReason, type AppliancesSufficiencyInput, type AppliancesSufficiencyProvenance, type AppliancesSufficiencyResult } from "./types";

type Json = Record<string, unknown>;
const KNOWN_REASON_CODES = new Set(["HARD_TECHNICAL_INCOMPATIBILITY", "HARD_CAPABILITY_INCOMPATIBILITY", "REQUIRED_EVIDENCE_UNKNOWN", "PRICE_COMPATIBLE", "BUDGET_INCOMPATIBLE", "BUDGET_ELIGIBILITY_UNKNOWN", "NON_FILTERING_EVIDENCE", "UNMAPPED_ACCEPTED_CONTEXT", "INSTALLATION_POSITIVE_FIT_FORBIDDEN", "LIFECYCLE_RESTRICTION"]);
const CAPACITY_EXCLUDED_CONCEPTS = new Set(["HIGH_LAUNDRY_VOLUME", "LOW_LAUNDRY_VOLUME", "LOAD_CONSOLIDATION"]);
const canonical = (value: unknown): unknown => Array.isArray(value) ? value.map(canonical) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value as Json).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, canonical(item)])) : value;
const fingerprint = (value: unknown): string => createHash("sha256").update(JSON.stringify(canonical(value))).digest("hex");
const sortedUnique = (values: readonly string[]): readonly string[] => [...new Set(values)].sort((a, b) => a.localeCompare(b));
const fail = (reason: AppliancesSufficiencyFailureReason): AppliancesSufficiencyResult => ({ kind: "FAILED_CLOSED", reason });
const reasonFor = (candidate: AppliancesCandidateEvaluation, code: CandidateReason["code"]): CandidateReason | undefined => candidate.reasons.find((reason) => reason.code === code);

export function evaluateAppliancesSufficiency(input: AppliancesSufficiencyInput): AppliancesSufficiencyResult {
  if (input.policy.status !== "READY") return fail("SUFFICIENCY_POLICY_AUTHORITY_FAILURE");
  const policy = input.policy.snapshot, p = policy.payload;
  if (p.precedence.some((value, index) => value !== SUFFICIENCY_OUTCOME_PRECEDENCE[index]) || new Set(p.outcomes.map((outcome) => outcome.kind)).size !== 6) return fail("INCOMPLETE_POLICY_OUTCOME");
  if (p.scope.boundaryOutput !== "NON_RANKED_CANDIDATE_POOL_ONLY" || p.exclusions.capacity.kilogramThreshold !== "ABSENT" || p.exclusions.persona.sufficiencyEffect !== "NONE" || p.exclusions.persona.recommendationEntryEffect !== "NONE") return fail("RUNTIME_POLICY_CONTRACT_DIVERGENCE");
  const bindings = p.bindings, manifest = input.authority.manifest as Json, catalog = input.authority.catalog as Json;
  if (bindings.catalog.release !== input.authority.releaseVersion || bindings.catalog.releaseDigest !== input.authority.catalogDigest || bindings.catalog.membershipDigest !== catalog.membershipDigest || bindings.catalog.artifactSha256 !== manifest.catalogArtifactSha256 || bindings.semanticRegistry.id !== manifest.semanticRegistryVersion || bindings.semanticRegistry.digest !== input.authority.semanticDigest) return fail("AUTHORITY_BINDING_MISMATCH");
  if (input.evaluation.status !== "READY") return fail(input.evaluation.reason === "PRICE_INTEGRITY_FAILURE" ? "INVALID_PRICE_BINDING" : "CANDIDATE_EVALUATION_FAILED_CLOSED");
  if (input.planner.kind === "FAILED_CLOSED") return fail("PLANNER_FAILED_CLOSED");
  const evaluation = input.evaluation.projection;
  if (bindings.questionPolicy.id !== ("questionPolicyId" in input.planner ? input.planner.questionPolicyId : "WASHING_MACHINE_QUESTION_POLICY/v0.1") || ("questionPolicyDigest" in input.planner && bindings.questionPolicy.digest !== input.planner.questionPolicyDigest)) return fail("QUESTION_POLICY_BINDING_MISMATCH");
  if (bindings.candidateEvaluationPolicy !== evaluation.policyVersion || evaluation.policyVersion !== APPLIANCES_CANDIDATE_EVALUATION_POLICY_VERSION) return fail("CANDIDATE_POLICY_BINDING_MISMATCH");
  if (("selectionPolicyVersion" in input.planner && input.planner.selectionPolicyVersion !== bindings.questionPlannerContract) || bindings.questionPlannerContract !== APPLIANCES_QUESTION_SELECTION_POLICY_VERSION) return fail("PLANNER_POLICY_BINDING_MISMATCH");
  if (evaluation.catalogRelease !== input.authority.releaseVersion || evaluation.catalogDigest !== input.authority.catalogDigest || evaluation.membershipDigest !== bindings.catalog.membershipDigest || evaluation.semanticRegistryVersion !== bindings.semanticRegistry.id || evaluation.semanticDigest !== input.authority.semanticDigest) return fail("AUTHORITY_BINDING_MISMATCH");
  if (evaluation.contextRevision !== input.state.revision || input.planner.contextRevision !== input.state.revision) return fail("CONTEXT_REVISION_MISMATCH");
  if (evaluation.contextFingerprint !== fingerprintActiveAppliancesContext(input.state)) return fail("CANDIDATE_FINGERPRINT_MISMATCH");
  if (!/^[a-f0-9]{64}$/u.test(evaluation.evaluationFingerprint)) return fail("CANDIDATE_FINGERPRINT_MISMATCH");
  if ("evaluationFingerprint" in input.planner && input.planner.evaluationFingerprint !== evaluation.evaluationFingerprint) return fail("PLANNER_FINGERPRINT_MISMATCH");
  if (input.planner.kind === "CLARIFY" && (!input.state.pendingConfirmation || input.state.pendingConfirmation.eventId !== input.planner.authoritativeEventId)) return fail("CONTRADICTORY_PLANNER_CONTEXT_STATE");
  const candidates = evaluation.candidates, ids = candidates.map((candidate) => candidate.productId);
  if (ids.length !== new Set(ids).size) return fail("DUPLICATE_CANDIDATE_ID");
  if (ids.some((id) => !input.authority.productIds.has(id))) return fail("UNKNOWN_CANDIDATE_ID");
  if (candidates.some((candidate) => !["ELIGIBLE", "INELIGIBLE", "ELIGIBILITY_UNKNOWN", "NOT_EVALUATED"].includes(candidate.eligibility))) return fail("MALFORMED_CANDIDATE_STATE");
  if (candidates.some((candidate) => candidate.reasons.some((reason) => !KNOWN_REASON_CODES.has(reason.code)))) return fail("UNKNOWN_REQUIRED_REASON_CODE");
  const actualCounts = { total: candidates.length, eligible: candidates.filter((candidate) => candidate.eligibility === "ELIGIBLE").length, ineligible: candidates.filter((candidate) => candidate.eligibility === "INELIGIBLE").length, unknown: candidates.filter((candidate) => candidate.eligibility === "ELIGIBILITY_UNKNOWN").length, notEvaluated: candidates.filter((candidate) => candidate.eligibility === "NOT_EVALUATED").length };
  if (Object.entries(actualCounts).some(([key, value]) => evaluation.counts[key as keyof typeof actualCounts] !== value) || actualCounts.total !== input.authority.productIds.size) return fail("IMPOSSIBLE_AGGREGATE_COUNTS");
  const active = projectActiveAppliancesContext(input.state.ledger), hardBudget = active.get("BUDGET_SENSITIVITY")?.decisionUse === "HARD_FILTER";
  if (hardBudget && input.price.status === "UNAVAILABLE" && input.price.reason === "PRICE_BINDING_MISMATCH") return fail("INVALID_PRICE_BINDING");
  const budgetCompatible = sortedUnique(candidates.filter((candidate) => reasonFor(candidate, "PRICE_COMPATIBLE")).map((candidate) => candidate.productId));
  const budgetIncompatible = sortedUnique(candidates.filter((candidate) => reasonFor(candidate, "BUDGET_INCOMPATIBLE")).map((candidate) => candidate.productId));
  const budgetUnknown = sortedUnique(candidates.filter((candidate) => reasonFor(candidate, "BUDGET_ELIGIBILITY_UNKNOWN")).map((candidate) => candidate.productId));
  const materiallyUnevaluated = (candidate: AppliancesCandidateEvaluation) => candidate.unevaluatedContextEventIds.filter((eventId) => { const event = input.state.ledger.find((item) => item.eventId === eventId); return !event || !CAPACITY_EXCLUDED_CONCEPTS.has(event.conceptId); });
  const budgetOnlyUnknown = new Set(candidates.filter((candidate) => candidate.eligibility === "ELIGIBILITY_UNKNOWN" && reasonFor(candidate, "BUDGET_ELIGIBILITY_UNKNOWN") && materiallyUnevaluated(candidate).length === 0 && !candidate.reasons.some((reason) => reason.result === "UNKNOWN" && reason.code !== "BUDGET_ELIGIBILITY_UNKNOWN" && active.get(reason.conceptId)?.decisionUse === "HARD_FILTER")).map((candidate) => candidate.productId));
  const hardUnknown = sortedUnique(candidates.filter((candidate) => candidate.eligibility === "NOT_EVALUATED" || (candidate.eligibility === "ELIGIBILITY_UNKNOWN" && !budgetOnlyUnknown.has(candidate.productId)) || materiallyUnevaluated(candidate).length > 0).map((candidate) => candidate.productId));
  const knownEligible = sortedUnique(candidates.filter((candidate) => candidate.eligibility === "ELIGIBLE").map((candidate) => candidate.productId));
  const hardIncompatible = sortedUnique(candidates.filter((candidate) => candidate.eligibility === "INELIGIBLE").map((candidate) => candidate.productId));
  const partitions: AppliancesCandidatePartitions = { knownEligibleCandidateIds: knownEligible, knownHardIncompatibleCandidateIds: hardIncompatible, hardUnknownCandidateIds: hardUnknown, budgetCompatibleCandidateIds: budgetCompatible, budgetIncompatibleCandidateIds: budgetIncompatible, budgetUnknownCandidateIds: budgetUnknown };
  const disclosures = sortedUnique([...candidates.flatMap((candidate) => candidate.disclosureRefs), ...candidates.flatMap((candidate) => candidate.reasons.filter((reason) => reason.result === "UNKNOWN" && active.get(reason.conceptId)?.decisionUse !== "HARD_FILTER").map(() => "SOFT_UNCERTAINTY_PRESENT")), ...(hardBudget && budgetUnknown.length ? ["HARD_BUDGET_PRICE_COVERAGE_LIMITED", "BUDGET_UNKNOWN_CANDIDATES_PRESERVED"] : []), ...(input.price.status === "STALE" && hardBudget ? ["PRICE_PROJECTION_STALE"] : [])]);
  const provenance: AppliancesSufficiencyProvenance = { runtimeVersion: APPLIANCES_SUFFICIENCY_RUNTIME_VERSION, policyId: p.policyId, policyDigest: policy.policyDigest, catalogRelease: evaluation.catalogRelease, catalogDigest: evaluation.catalogDigest, semanticRegistryId: bindings.semanticRegistry.id, semanticDigest: evaluation.semanticDigest, questionPolicyId: bindings.questionPolicy.id, questionPolicyDigest: bindings.questionPolicy.digest, candidatePolicy: evaluation.policyVersion, plannerPolicy: bindings.questionPlannerContract, contextRevision: evaluation.contextRevision, contextFingerprint: evaluation.contextFingerprint, evaluationFingerprint: evaluation.evaluationFingerprint, plannerKind: input.planner.kind, ...(evaluation.priceSnapshot ? { priceSnapshot: evaluation.priceSnapshot } : {}) };
  const base = { provenance, candidatePartitions: partitions, disclosureCodes: disclosures, evaluationFingerprint: "" };
  if (input.planner.kind === "CLARIFY") { const result = { ...base, kind: "CLARIFICATION_REQUIRED" as const, reasonCodes: ["PLANNER_CLARIFICATION_REQUIRED"] as const, clarification: { questionKey: input.planner.questionKey, targetConcept: input.planner.targetConcept, authoritativeEventId: input.planner.authoritativeEventId, contextRevision: input.planner.contextRevision } }; return { ...result, evaluationFingerprint: fingerprint(result) }; }
  if (input.planner.kind === "ASK") { const result = { ...base, kind: "MORE_INFORMATION_REQUIRED" as const, reasonCodes: ["AUTHORIZED_MATERIAL_QUESTION_AVAILABLE"] as const, question: { questionKey: input.planner.questionKey, targetConcept: input.planner.targetConcept, priority: input.planner.priority, contextRevision: input.planner.contextRevision, evaluationFingerprint: input.planner.evaluationFingerprint, questionPolicyId: input.planner.questionPolicyId, questionPolicyDigest: input.planner.questionPolicyDigest, selectionPolicyVersion: input.planner.selectionPolicyVersion } }; return { ...result, evaluationFingerprint: fingerprint(result) }; }
  const mixedBudgetException = hardBudget && budgetCompatible.length > 0 && budgetUnknown.length > 0 && hardUnknown.length === 0;
  if (hardUnknown.length > 0 || (hardBudget && budgetCompatible.length === 0 && budgetUnknown.length > 0)) { const codes = sortedUnique([...(hardUnknown.length ? ["HARD_CANDIDATE_ELIGIBILITY_UNRESOLVED"] : []), ...(budgetUnknown.length ? [input.price.status === "STALE" ? "HARD_BUDGET_PRICE_STALE" : "HARD_BUDGET_PRICE_UNRESOLVED"] : [])]); const result = { ...base, kind: "UNRESOLVED_HARD_UNCERTAINTY" as const, reasonCodes: codes }; return { ...result, evaluationFingerprint: fingerprint(result) }; }
  const poolIds = mixedBudgetException ? budgetCompatible.filter(id => knownEligible.includes(id)) : knownEligible;
  if (poolIds.length === 0) { const result = { ...base, kind: "NO_RECOMMENDATION_ELIGIBLE_CANDIDATE" as const, reasonCodes: [hardBudget && budgetIncompatible.length > 0 ? "ALL_CANDIDATES_CONCLUSIVELY_INELIGIBLE_INCLUDING_BUDGET" : "ALL_CANDIDATES_CONCLUSIVELY_HARD_INCOMPATIBLE"] }; return { ...result, evaluationFingerprint: fingerprint(result) }; }
  const result = { ...base, kind: "RECOMMENDATION_POOL_ELIGIBLE" as const, reasonCodes: ["NON_RANKED_CANDIDATE_POOL_AVAILABLE"] as const, candidatePool: { candidateIds: poolIds, poolFingerprint: fingerprint({ candidateIds: poolIds, canonicalOrderMeaning: "SERIALIZATION_ONLY" }), canonicalOrderMeaning: "SERIALIZATION_ONLY" as const, selectionPolicyRequired: poolIds.length > 1 } }; return { ...result, evaluationFingerprint: fingerprint(result) };
}
