import type { AppliancesAuthoritySnapshot, PriceProjectionLoadResult } from "../authority/types";
import type { AppliancesCandidateEvaluationResult } from "../candidate/types";
import type { AppliancesConversationState } from "../contracts";
import type { SufficiencyRecommendationPolicyLoadResult } from "../governance/sufficiencyRecommendationPolicyLoader.server";
import type { AppliancesQuestionPlan } from "../planner/types";

export const APPLIANCES_SUFFICIENCY_RUNTIME_VERSION = "appliances-sufficiency-recommendation-entry-runtime/v1" as const;
export type AppliancesSufficiencyOutcomeKind = "FAILED_CLOSED" | "CLARIFICATION_REQUIRED" | "MORE_INFORMATION_REQUIRED" | "UNRESOLVED_HARD_UNCERTAINTY" | "NO_RECOMMENDATION_ELIGIBLE_CANDIDATE" | "RECOMMENDATION_POOL_ELIGIBLE";
export type AppliancesSufficiencyFailureReason = "SUFFICIENCY_POLICY_AUTHORITY_FAILURE" | "AUTHORITY_BINDING_MISMATCH" | "QUESTION_POLICY_BINDING_MISMATCH" | "CANDIDATE_POLICY_BINDING_MISMATCH" | "PLANNER_POLICY_BINDING_MISMATCH" | "CONTEXT_REVISION_MISMATCH" | "CANDIDATE_FINGERPRINT_MISMATCH" | "PLANNER_FINGERPRINT_MISMATCH" | "CANDIDATE_EVALUATION_FAILED_CLOSED" | "PLANNER_FAILED_CLOSED" | "MALFORMED_CANDIDATE_STATE" | "DUPLICATE_CANDIDATE_ID" | "UNKNOWN_CANDIDATE_ID" | "IMPOSSIBLE_AGGREGATE_COUNTS" | "UNKNOWN_REQUIRED_REASON_CODE" | "INVALID_PRICE_BINDING" | "CONTRADICTORY_PLANNER_CONTEXT_STATE" | "INCOMPLETE_POLICY_OUTCOME" | "RUNTIME_POLICY_CONTRACT_DIVERGENCE";

export interface AppliancesSufficiencyInput { readonly authority: AppliancesAuthoritySnapshot; readonly state: AppliancesConversationState; readonly evaluation: AppliancesCandidateEvaluationResult; readonly planner: AppliancesQuestionPlan; readonly price: PriceProjectionLoadResult; readonly policy: SufficiencyRecommendationPolicyLoadResult }
export interface AppliancesSufficiencyProvenance { readonly runtimeVersion: typeof APPLIANCES_SUFFICIENCY_RUNTIME_VERSION; readonly policyId: string; readonly policyDigest: string; readonly catalogRelease: string; readonly catalogDigest: string; readonly semanticRegistryId: string; readonly semanticDigest: string; readonly questionPolicyId: string; readonly questionPolicyDigest: string; readonly candidatePolicy: string; readonly plannerPolicy: string; readonly contextRevision: number; readonly contextFingerprint: string; readonly evaluationFingerprint: string; readonly plannerKind: AppliancesQuestionPlan["kind"]; readonly priceSnapshot?: { readonly snapshotId: string; readonly projectionFingerprint: string; readonly freshness: "READY" | "STALE" } }
export interface AppliancesCandidatePartitions { readonly knownEligibleCandidateIds: readonly string[]; readonly knownHardIncompatibleCandidateIds: readonly string[]; readonly hardUnknownCandidateIds: readonly string[]; readonly budgetCompatibleCandidateIds: readonly string[]; readonly budgetIncompatibleCandidateIds: readonly string[]; readonly budgetUnknownCandidateIds: readonly string[] }
interface NormalBase { readonly provenance: AppliancesSufficiencyProvenance; readonly candidatePartitions: AppliancesCandidatePartitions; readonly disclosureCodes: readonly string[]; readonly evaluationFingerprint: string }
export type AppliancesSufficiencyResult =
  | { readonly kind: "FAILED_CLOSED"; readonly reason: AppliancesSufficiencyFailureReason }
  | (NormalBase & { readonly kind: "CLARIFICATION_REQUIRED"; readonly reasonCodes: readonly ["PLANNER_CLARIFICATION_REQUIRED"]; readonly clarification: { readonly questionKey: string; readonly targetConcept: string; readonly authoritativeEventId: string; readonly contextRevision: number } })
  | (NormalBase & { readonly kind: "MORE_INFORMATION_REQUIRED"; readonly reasonCodes: readonly ["AUTHORIZED_MATERIAL_QUESTION_AVAILABLE"]; readonly question: { readonly questionKey: string; readonly targetConcept: string; readonly priority: number; readonly contextRevision: number; readonly evaluationFingerprint: string; readonly questionPolicyId: string; readonly questionPolicyDigest: string; readonly selectionPolicyVersion: string } })
  | (NormalBase & { readonly kind: "UNRESOLVED_HARD_UNCERTAINTY"; readonly reasonCodes: readonly string[] })
  | (NormalBase & { readonly kind: "NO_RECOMMENDATION_ELIGIBLE_CANDIDATE"; readonly reasonCodes: readonly string[] })
  | (NormalBase & { readonly kind: "RECOMMENDATION_POOL_ELIGIBLE"; readonly reasonCodes: readonly ["NON_RANKED_CANDIDATE_POOL_AVAILABLE"]; readonly candidatePool: { readonly candidateIds: readonly string[]; readonly poolFingerprint: string; readonly canonicalOrderMeaning: "SERIALIZATION_ONLY"; readonly selectionPolicyRequired: boolean } });
