// Generated by scripts/sync-active-production-catalog.ts. Do not edit manually.
export { default as activeCatalogPayload } from "./releases/v0.55.0/catalog.json";
export { default as activeCatalogManifest } from "./releases/v0.55.0/manifest.json";
export { default as activeDecisionFacetPayload } from "./releases/v0.55.0/decision-facets.json";
export const activeCatalogReleaseVersion = "0.55.0";
