/* eslint-disable @typescript-eslint/no-explicit-any -- authority mutation tests intentionally cross governed JSON shapes */
import { readFile } from "node:fs/promises";
import path from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import { createFileSystemAppliancesArtifactRepository, loadActiveAppliancesAuthority } from "../authority/loader.server";
import type { AppliancesAuthoritySnapshot } from "../authority/types";
import { digestCandidateSelectionPolicy } from "./candidateSelectionPolicyAuthority";
import { createFileSystemCandidateSelectionPolicyRepository, loadActiveWashingMachineCandidateSelectionPolicy, type CandidateSelectionPolicyRepository } from "./candidateSelectionPolicyLoader.server";
import { createFileSystemQuestionPolicyRepository, loadActiveWashingMachineQuestionPolicy } from "./questionPolicyLoader.server";
import type { WashingMachineQuestionPolicyArtifact } from "./questionPolicyAuthority";
import { createFileSystemSufficiencyRecommendationPolicyRepository, loadActiveWashingMachineSufficiencyRecommendationPolicy } from "./sufficiencyRecommendationPolicyLoader.server";
import type { SufficiencyRecommendationPolicyArtifact } from "./sufficiencyRecommendationPolicyAuthority";

const root = process.cwd(), policyPath = path.join(root, "data/production/appliances/candidate-selection-policy/releases/WASHING_MACHINE_CANDIDATE_SELECTION_POLICY-v0.2/policy.json"), pointerPath = path.join(root, "data/production/appliances/candidate-selection-policy/active.json");
let authority: AppliancesAuthoritySnapshot, questionPolicy: WashingMachineQuestionPolicyArtifact, sufficiencyPolicy: SufficiencyRecommendationPolicyArtifact, policyRaw: string, pointerRaw: string;
beforeAll(async () => {
  const loadedAuthority = await loadActiveAppliancesAuthority({ repository: createFileSystemAppliancesArtifactRepository(root) }); if (loadedAuthority.status !== "READY") throw new Error(loadedAuthority.reason); authority = loadedAuthority.snapshot;
  const loadedQuestion = await loadActiveWashingMachineQuestionPolicy({ repository: createFileSystemQuestionPolicyRepository(root), authority }); if (loadedQuestion.status !== "READY") throw new Error(loadedQuestion.reason); questionPolicy = loadedQuestion.snapshot;
  const loadedSufficiency = await loadActiveWashingMachineSufficiencyRecommendationPolicy({ repository: createFileSystemSufficiencyRecommendationPolicyRepository(root), authority, questionPolicy }); if (loadedSufficiency.status !== "READY") throw new Error(loadedSufficiency.reason); sufficiencyPolicy = loadedSufficiency.snapshot;
  [policyRaw, pointerRaw] = await Promise.all([readFile(policyPath, "utf8"), readFile(pointerPath, "utf8")]);
});
const repository = (policy = policyRaw, pointer = pointerRaw): CandidateSelectionPolicyRepository => ({ readActive: async () => pointer, readPolicy: async () => policy });
const mutate = (fn: (artifact: any) => void, rehash = false) => { const artifact = JSON.parse(policyRaw), pointer = JSON.parse(pointerRaw); fn(artifact); if (rehash) { artifact.policyDigest = digestCandidateSelectionPolicy(artifact.payload); pointer.policyDigest = artifact.policyDigest; } return { policy: JSON.stringify(artifact), pointer: JSON.stringify(pointer) }; };
const load = (changed?: { policy: string; pointer: string }, overrides?: Partial<Parameters<typeof loadActiveWashingMachineCandidateSelectionPolicy>[0]>) => loadActiveWashingMachineCandidateSelectionPolicy({ repository: changed ? repository(changed.policy, changed.pointer) : repository(), authority, questionPolicy, sufficiencyPolicy, ...overrides });

describe("approved Washing Machine Candidate Selection Policy authority", () => {
  it("loads the exact approved frozen active v0.1 pointer as a deeply immutable snapshot", async () => { const result = await loadActiveWashingMachineCandidateSelectionPolicy({ repository: createFileSystemCandidateSelectionPolicyRepository(root), authority, questionPolicy, sufficiencyPolicy }); expect(result.status).toBe("READY"); if (result.status === "READY") { expect(result.snapshot.payload).toMatchObject({ policyId: "WASHING_MACHINE_CANDIDATE_SELECTION_POLICY/v0.1", governanceStatus: "APPROVED", lifecycle: "FROZEN", runtimeActive: true }); expect(digestCandidateSelectionPolicy(result.snapshot.payload)).toBe(result.snapshot.policyDigest); expect(Object.isFrozen(result.snapshot.payload.rules)).toBe(true); } });
  it("does not treat the historical non-active draft as runtime authority", async () => { const draft = await readFile(path.join(root, "data/governance/appliances/candidate-selection-policy/drafts/WASHING_MACHINE_CANDIDATE_SELECTION_POLICY-v0.1.json"), "utf8"); await expect(load({ policy: draft, pointer: pointerRaw })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "POLICY_SCHEMA_INVALID" }); });
  it("freezes the Pareto model with equal priorities, no weights and no total order", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); expect(result.snapshot.payload.model).toMatchObject({ kind: "RULE_BASED_PARETO_DOMINANCE", preferencePriority: "EQUAL", globalWeights: "NONE", contextualWeights: "NONE", totalOrderGuaranteed: false }); });
  it("freezes exactly three affirmative active preferences and no reverse preferences", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); const rules = result.snapshot.payload.rules; expect(rules.filter((rule) => rule.selectionRole === "ACTIVE").map((rule) => `${rule.conceptId}=${rule.activeValue}`)).toEqual(["REMOTE_CONTROL=WANTED", "DETERGENT_CONVENIENCE=WANTED", "LOW_NOISE_PRIORITY=IMPORTANT"]); expect(rules.filter((rule) => rule.activeValue === "NOT_IMPORTANT").every((rule) => rule.comparison.includes("no reverse preference"))).toBe(true); });
  it("freezes capability directions and the exact comparable noise regime", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); const rules = result.snapshot.payload.rules; expect(rules.find((rule) => rule.ruleId === "CSP-001")?.comparison).toMatch(/PRESENT.*NOT_AVAILABLE/u); expect(rules.find((rule) => rule.ruleId === "CSP-003")?.comparison).toMatch(/PRESENT.*NOT_AVAILABLE/u); expect(rules.find((rule) => rule.ruleId === "CSP-005")?.comparison).toMatch(/Lower.*dB.*SPIN_PHASE.*EU_2019_2014/u); });
  it("freezes unknown, missing, conflict, price, persona and rationale boundaries", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); const p = result.snapshot.payload; expect(p.evidenceStates).toMatchObject({ llmConflictResolution: "FORBIDDEN" }); expect(p.evidenceStates.UNKNOWN).toContain("neither false nor worse"); expect(p.evidenceStates.MISSING).toContain("not NOT_AVAILABLE"); expect(p.pricePolicy).toMatchObject({ postEligibilityRole: "DISCLOSURE_ONLY", tieBreakEffect: "NONE", sellerAvailabilityEffect: "NONE", affiliateEffect: "NONE" }); expect(p.persona).toMatchObject({ selectionEffect: "NONE", rankingEffect: "NONE", tieBreakEffect: "NONE" }); expect(p.rationaleBoundary).toMatchObject({ effect: "EXPLANATION_ONLY", countEffect: "NONE", lengthEffect: "NONE", bindingMismatchEffect: "FAILED_CLOSED" }); });
  it("freezes all five distinct outcomes and all forbidden tie-breaks", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); expect(result.snapshot.payload.outcomes.map((outcome) => outcome.kind)).toEqual(["SELECTED_SINGLE", "TIED_TOP_SET", "NON_DOMINATED_SET", "NO_GOVERNED_SELECTION", "FAILED_CLOSED"]); expect(result.snapshot.payload.ties.forbiddenTieBreaks).toHaveLength(13); expect(result.snapshot.payload.ties.canonicalSortMeaning).toBe("SERIALIZATION_ONLY"); });
  it.each(["selection model", "active value", "comparison direction", "unknown treatment", "price role", "tie outcome", "input gate", "persona", "rationale authority", "dependency binding"])("rejects an un-rehashed %s mutation by digest", async (kind) => { const changed = mutate((a) => { if (kind === "selection model") a.payload.model.kind = "WEIGHTED"; else if (kind === "active value") a.payload.rules[0].activeValue = "REQUIRED"; else if (kind === "comparison direction") a.payload.rules[4].comparison = "Higher is better"; else if (kind === "unknown treatment") a.payload.evidenceStates.UNKNOWN = "zero"; else if (kind === "price role") a.payload.pricePolicy.postEligibilityRole = "RANK"; else if (kind === "tie outcome") a.payload.ties.exactEqualityOutcome = "SELECTED_SINGLE"; else if (kind === "input gate") a.payload.inputPolicy.allowedOutcome = "FAILED_CLOSED"; else if (kind === "persona") a.payload.persona.selectionEffect = "RANK"; else if (kind === "rationale authority") a.payload.rationaleBoundary.effect = "SELECTION"; else a.payload.bindings.catalog.releaseDigest = "0".repeat(64); }); await expect(load(changed)).resolves.toEqual({ status: "FAILED_CLOSED", reason: "POLICY_DIGEST_MISMATCH" }); });
  it.each([
    ["active concept", (a: any) => a.payload.rules[0].activeValue = "REQUIRED", "UNAUTHORIZED_ACTIVE_CONCEPT"],
    ["comparison direction", (a: any) => a.payload.rules[4].comparison = "Higher", "INVALID_COMPARISON_DIRECTION"],
    ["noise regime", (a: any) => a.payload.rules[4].comparison = a.payload.rules[4].comparison.replace("EU_2019_2014", "OTHER"), "INCOMPATIBLE_EVIDENCE_REGIME"],
    ["unknown", (a: any) => a.payload.evidenceStates.UNKNOWN = "UNKNOWN is zero", "INCOMPLETE_UNKNOWN_POLICY"],
    ["tie", (a: any) => a.payload.ties.exactEqualityOutcome = "SELECTED_SINGLE", "INCOMPLETE_TIE_POLICY"],
    ["tie-break", (a: any) => a.payload.ties.forbiddenTieBreaks.pop(), "UNAUTHORIZED_TIE_BREAK"],
    ["persona", (a: any) => a.payload.persona.tieBreakEffect = "ACTIVE", "PERSONA_AUTHORITY_VIOLATION"],
    ["price", (a: any) => a.payload.pricePolicy.tieBreakEffect = "LOWER", "PRICE_AUTHORITY_VIOLATION"],
    ["rationale", (a: any) => a.payload.rationaleBoundary.countEffect = "RANK", "RATIONALE_AUTHORITY_VIOLATION"],
  ])("fails semantically after rehashed %s mutation", async (_label, fn, reason) => { await expect(load(mutate(fn, true))).resolves.toEqual({ status: "FAILED_CLOSED", reason }); });
  it.each([
    ["catalog release", (a: any) => a.payload.bindings.catalog.release = "OTHER", "POLICY_SCHEMA_INVALID"], ["catalog digest", (a: any) => a.payload.bindings.catalog.releaseDigest = "0".repeat(64), "CATALOG_BINDING_MISMATCH"], ["membership", (a: any) => a.payload.bindings.catalog.membershipDigest = "0".repeat(64), "CATALOG_BINDING_MISMATCH"], ["artifact", (a: any) => a.payload.bindings.catalog.artifactSha256 = "0".repeat(64), "CATALOG_BINDING_MISMATCH"],
    ["semantic", (a: any) => a.payload.bindings.semanticRegistry.digest = "0".repeat(64), "SEMANTIC_BINDING_MISMATCH"], ["question", (a: any) => a.payload.bindings.questionPolicy.digest = "0".repeat(64), "QUESTION_POLICY_BINDING_MISMATCH"], ["sufficiency", (a: any) => a.payload.bindings.sufficiencyPolicy.digest = "0".repeat(64), "SUFFICIENCY_POLICY_BINDING_MISMATCH"], ["candidate", (a: any) => a.payload.bindings.candidateEvaluationPolicy = "other/v1", "POLICY_SCHEMA_INVALID"], ["input", (a: any) => a.payload.bindings.selectionInputContract = "other/v1", "POLICY_SCHEMA_INVALID"],
  ])("fails closed for rehashed %s dependency mismatch", async (_label, fn, reason) => { await expect(load(mutate(fn, true))).resolves.toEqual({ status: "FAILED_CLOSED", reason }); });
  it("fails for missing pointers, unsafe paths, missing policies and invalid pointer identity", async () => { await expect(load(undefined, { repository: { readActive: async () => { throw new Error("missing"); }, readPolicy: async () => policyRaw } })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "ACTIVE_POINTER_MISSING" }); const unsafe = JSON.parse(pointerRaw); unsafe.policyFile = "../draft.json"; await expect(load({ policy: policyRaw, pointer: JSON.stringify(unsafe) })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "UNSAFE_POLICY_PATH" }); const wrong = JSON.parse(pointerRaw); wrong.policyId = "OTHER"; await expect(load({ policy: policyRaw, pointer: JSON.stringify(wrong) })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "ACTIVE_POINTER_INVALID" }); });
  it("contains policy authority only and no runtime selector or downstream authorization", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); expect(result.snapshot.payload.scope).toEqual({ selectionOutcomeAuthority: "POLICY_ONLY", runtimeSelector: "OUT_OF_SCOPE", recommendationConstruction: "OUT_OF_SCOPE", decisionAuthorization: "OUT_OF_SCOPE", decisionCard: "OUT_OF_SCOPE", advisor: "OUT_OF_SCOPE", commerceEffect: "NONE" }); expect(result.snapshot.payload.outputContract).toMatchObject({ authorizesDecisionReady: false, authorizesDecisionAuthorization: false, authorizesDecisionCard: false, authorizesRecommendationProse: false, authorizesCommerce: false }); });
});
