import { z } from "zod";

const answerDomain = z.discriminatedUnion("type", [
  z.strictObject({ type: z.literal("INTEGER"), unit: z.enum(["mm", "TRY"]), minimum: z.number(), maximum: z.number(), normalizedShape: z.string().min(1) }),
  z.strictObject({ type: z.literal("ENUM"), values: z.array(z.string().min(1)).min(2), normalizedShape: z.string().min(1) }),
]);
const question = z.strictObject({
  questionKey: z.string().regex(/^appliances\.wm\.[a-zA-Z0-9.]+$/u), targetConcept: z.string().min(1), kind: z.literal("DISCOVERY_ASK"), priority: z.number().int().positive(), dependencies: z.array(z.string()), answerDomain,
  materiality: z.strictObject({ requiresCandidateDifference: z.string().min(1), requiresContextCondition: z.string().min(1), candidateEffect: z.string().min(1) }),
  suppression: z.array(z.string().min(1)).min(1), reopening: z.array(z.string().min(1)).min(1),
  realization: z.strictObject({ model: z.literal("APPROVED_TEMPLATE"), templateRef: z.string().min(1), textTr: z.string().min(1) }),
  semanticAuthorityRef: z.string().min(1), candidateEffectRef: z.string().min(1), governanceClassification: z.literal("DERIVED_GOVERNANCE_PROPOSAL"),
});
const decision = z.strictObject({ decisionId:z.string().min(1),topic:z.string().min(1),currentAuthorityEvidence:z.string().min(1),proposedDecision:z.string().min(1),alternativesConsidered:z.array(z.string()).min(1),runtimeConsequence:z.string().min(1),riskIfUnresolved:z.string().min(1),governanceClassification:z.enum(["EXISTING_PRODUCT_AUTHORITY","EXISTING_SEMANTIC_AUTHORITY","EXISTING_ARCHITECTURE_CONSTRAINT","DERIVED_GOVERNANCE_PROPOSAL","UNRESOLVED_PRODUCT_DECISION"]),approvalRequired:z.boolean() });
export const washingMachineQuestionPolicyDraftSchema = z.strictObject({
  schemaVersion:z.literal("washing-machine-question-policy-draft/v1"),policyId:z.literal("WASHING_MACHINE_QUESTION_POLICY/v0.1"),governanceStatus:z.literal("READY_FOR_APPROVAL"),departmentId:z.literal("APPLIANCES"),productType:z.literal("WASHING_MACHINE"),market:z.literal("TR"),stage:z.literal("AŞAMA_1"),runtimeActive:z.literal(false),createdAt:z.string().datetime({offset:true}),
  provenance:z.strictObject({workUnit:z.literal("WU-APPL-QUESTION-POLICY-01"),semanticRegistryVersion:z.string(),semanticRegistryDigest:z.string().regex(/^[a-f0-9]{64}$/u),catalogRelease:z.string(),catalogDigest:z.string().regex(/^[a-f0-9]{64}$/u),candidateEvaluationPolicy:z.string()}),
  selectionPolicy:z.strictObject({clarificationPrecedence:z.literal(true),maximumQuestionsPerSelection:z.literal(1),priorityModel:z.literal("TOTAL_ORDER_THEN_STABLE_KEY"),personaInfluence:z.literal("NONE"),candidateArrayOrderInfluence:z.literal("NONE"),noQuestionMeaning:z.string()}),questions:z.array(question).min(1),excludedTopics:z.array(z.strictObject({topic:z.string(),classification:z.enum(["NON_MATERIAL","CONTEXT_ONLY","ADVISOR_ONLY","UNSUPPORTED_PENDING_PRODUCT_DECISION"]),reason:z.string()})),decisionRegister:z.array(decision).min(1),
});
export type WashingMachineQuestionPolicyDraft = z.infer<typeof washingMachineQuestionPolicyDraftSchema>;
export type QuestionPolicyValidation = {readonly status:"VALID_DRAFT"}|{readonly status:"INVALID_DRAFT";readonly reasons:readonly string[]};
export function validateWashingMachineQuestionPolicyDraft(input:unknown,knownConceptIds:ReadonlySet<string>,knownDiscriminators:ReadonlySet<string>):QuestionPolicyValidation{
 const parsed=washingMachineQuestionPolicyDraftSchema.safeParse(input);if(!parsed.success)return{status:"INVALID_DRAFT",reasons:parsed.error.issues.map(issue=>`SCHEMA:${issue.path.join(".")}`)};const reasons:string[]=[];const keys=parsed.data.questions.map(q=>q.questionKey),priorities=parsed.data.questions.map(q=>q.priority);if(new Set(keys).size!==keys.length)reasons.push("DUPLICATE_QUESTION_KEY");if(new Set(priorities).size!==priorities.length)reasons.push("AMBIGUOUS_PRIORITY");for(const q of parsed.data.questions){if(!knownConceptIds.has(q.targetConcept))reasons.push(`UNKNOWN_TARGET_CONCEPT:${q.questionKey}`);if(q.answerDomain.type==="INTEGER"&&q.answerDomain.minimum>=q.answerDomain.maximum)reasons.push(`INVALID_NUMERIC_DOMAIN:${q.questionKey}`);if(q.answerDomain.type==="ENUM"&&new Set(q.answerDomain.values).size!==q.answerDomain.values.length)reasons.push(`DUPLICATE_ANSWER_VALUE:${q.questionKey}`);if(!knownDiscriminators.has(q.materiality.requiresCandidateDifference)&&q.materiality.requiresCandidateDifference!=="FRESH_REPRESENTATIVE_PRICE_TRY")reasons.push(`UNKNOWN_DISCRIMINATOR:${q.questionKey}`);for(const dependency of q.dependencies)if(!keys.includes(dependency))reasons.push(`UNKNOWN_DEPENDENCY:${q.questionKey}`);}
 const graph=new Map(parsed.data.questions.map(q=>[q.questionKey,q.dependencies]));const visiting=new Set<string>(),visited=new Set<string>();const cycle=(key:string):boolean=>{if(visiting.has(key))return true;if(visited.has(key))return false;visiting.add(key);for(const next of graph.get(key)??[])if(cycle(next))return true;visiting.delete(key);visited.add(key);return false;};if(keys.some(cycle))reasons.push("DEPENDENCY_CYCLE");if(parsed.data.decisionRegister.some(d=>d.governanceClassification==="UNRESOLVED_PRODUCT_DECISION"&&!d.approvalRequired))reasons.push("UNRESOLVED_DECISION_NOT_MARKED_FOR_APPROVAL");return reasons.length?{status:"INVALID_DRAFT",reasons}:{status:"VALID_DRAFT"};
}
