import { readFile } from "node:fs/promises";
import path from "node:path";
import type { AppliancesAuthoritySnapshot } from "../authority/types";
import { washingMachineQuestionPolicyActivePointerSchema, validateQuestionPolicyIntegrity, type QuestionPolicyIntegrityFailure, type WashingMachineQuestionPolicyArtifact } from "./questionPolicyAuthority";

const SAFE_POLICY_FILE=/^releases\/WASHING_MACHINE_QUESTION_POLICY-v\d+\.\d+\/policy\.json$/u;
export type QuestionPolicyLoadFailure="ACTIVE_POINTER_MISSING"|"ACTIVE_POINTER_INVALID"|"UNSAFE_POLICY_PATH"|"POLICY_MISSING"|"WRONG_ACTIVE_POLICY_IDENTITY"|QuestionPolicyIntegrityFailure;
export type QuestionPolicyLoadResult={readonly status:"READY";readonly snapshot:Readonly<WashingMachineQuestionPolicyArtifact>}|{readonly status:"FAILED_CLOSED";readonly reason:QuestionPolicyLoadFailure};
export interface QuestionPolicyArtifactRepository{readActive():Promise<string>;readPolicy(relativeFile:string):Promise<string>}
export function createFileSystemQuestionPolicyRepository(repositoryRoot:string):QuestionPolicyArtifactRepository{const root=path.join(repositoryRoot,"data/production/appliances/question-policy");return{readActive:()=>readFile(path.join(root,"active.json"),"utf8"),readPolicy:(relativeFile)=>{if(!SAFE_POLICY_FILE.test(relativeFile))return Promise.reject(new TypeError("UNSAFE_POLICY_PATH"));const resolved=path.resolve(root,relativeFile);if(!resolved.startsWith(`${path.resolve(root,"releases")}${path.sep}`))return Promise.reject(new TypeError("UNSAFE_POLICY_PATH"));return readFile(resolved,"utf8");}};}
const freeze=<T>(value:T,seen=new WeakSet<object>()):T=>{if(!value||typeof value!=="object"||seen.has(value as object))return value;seen.add(value as object);for(const child of Object.values(value as object))freeze(child,seen);return Object.freeze(value);};
export async function loadActiveWashingMachineQuestionPolicy(input:{repository:QuestionPolicyArtifactRepository;authority:AppliancesAuthoritySnapshot}):Promise<QuestionPolicyLoadResult>{let activeRaw:string;try{activeRaw=await input.repository.readActive();}catch{return{status:"FAILED_CLOSED",reason:"ACTIVE_POINTER_MISSING"};}let active;try{active=washingMachineQuestionPolicyActivePointerSchema.parse(JSON.parse(activeRaw));}catch{return{status:"FAILED_CLOSED",reason:"ACTIVE_POINTER_INVALID"};}if(!SAFE_POLICY_FILE.test(active.policyFile))return{status:"FAILED_CLOSED",reason:"UNSAFE_POLICY_PATH"};let raw:string;try{raw=await input.repository.readPolicy(active.policyFile);}catch(error){return{status:"FAILED_CLOSED",reason:error instanceof Error&&error.message==="UNSAFE_POLICY_PATH"?"UNSAFE_POLICY_PATH":"POLICY_MISSING"};}let artifact:unknown;try{artifact=JSON.parse(raw);}catch{return{status:"FAILED_CLOSED",reason:"POLICY_SCHEMA_INVALID"};}const catalog=input.authority.catalog as Record<string,unknown>;const discriminators=new Set([...(catalog.factKeyRegistry as string[]??[]),...(catalog.capabilityRegistry as string[]??[]),"FRESH_REPRESENTATIVE_PRICE_TRY"]);const checked=validateQuestionPolicyIntegrity({artifact,expectedDigest:active.policyDigest,conceptIds:input.authority.conceptIds,discriminators,catalogRelease:input.authority.releaseVersion,catalogDigest:input.authority.catalogDigest,semanticDigest:input.authority.semanticDigest});if(checked.status==="INVALID")return{status:"FAILED_CLOSED",reason:checked.reason};if(checked.artifact.payload.policyId!==active.policyId)return{status:"FAILED_CLOSED",reason:"WRONG_ACTIVE_POLICY_IDENTITY"};return{status:"READY",snapshot:freeze(checked.artifact)};}
