/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial governed JSON mutations intentionally cross heterogeneous fields */
import { readFile } from "node:fs/promises";
import path from "node:path";
import { beforeAll,describe,expect,it } from "vitest";
import { createFileSystemAppliancesArtifactRepository,loadActiveAppliancesAuthority } from "../authority/loader.server";
import type { AppliancesAuthoritySnapshot } from "../authority/types";
import { digestQuestionPolicy } from "./questionPolicyAuthority";
import { createFileSystemQuestionPolicyRepository,loadActiveWashingMachineQuestionPolicy,type QuestionPolicyArtifactRepository } from "./questionPolicyLoader.server";

const root=process.cwd(),policyPath=path.join(root,"data/production/appliances/question-policy/releases/WASHING_MACHINE_QUESTION_POLICY-v0.2/policy.json"),pointerPath=path.join(root,"data/production/appliances/question-policy/active.json");
let authority:AppliancesAuthoritySnapshot,pointerRaw:string,policyRaw:string;
beforeAll(async()=>{const loaded=await loadActiveAppliancesAuthority({repository:createFileSystemAppliancesArtifactRepository(root)});if(loaded.status!=="READY")throw new Error(loaded.reason);authority=loaded.snapshot;[pointerRaw,policyRaw]=await Promise.all([readFile(pointerPath,"utf8"),readFile(policyPath,"utf8")]);});
const repo=(pointer=pointerRaw,policy=policyRaw):QuestionPolicyArtifactRepository=>({readActive:async()=>pointer,readPolicy:async()=>policy});
// Governed fixture mutation intentionally crosses heterogeneous JSON fields.
const mutate=(fn:(artifact:any)=>void,rehash=false):string=>{const value=JSON.parse(policyRaw);fn(value);if(rehash)value.policyDigest=digestQuestionPolicy(value.payload);return JSON.stringify(value);};
const load=(policy=policyRaw,pointer?:string)=>{const artifact=JSON.parse(policy),active=JSON.parse(pointer??pointerRaw);if(pointer===undefined&&artifact.policyDigest!==JSON.parse(policyRaw).policyDigest)active.policyDigest=artifact.policyDigest;return loadActiveWashingMachineQuestionPolicy({repository:repo(JSON.stringify(active),policy),authority});};

describe("approved Washing Machine Question Policy authority",()=>{
 it("loads the explicit active approved/frozen v0.1 authority",async()=>{const result=await loadActiveWashingMachineQuestionPolicy({repository:createFileSystemQuestionPolicyRepository(root),authority});expect(result.status).toBe("READY");if(result.status==="READY"){expect(result.snapshot.payload).toMatchObject({policyId:"WASHING_MACHINE_QUESTION_POLICY/v0.1",governanceStatus:"APPROVED",lifecycle:"FROZEN",runtimeActive:true});expect(result.snapshot.payload.questions).toHaveLength(7);expect(Object.isFrozen(result.snapshot)).toBe(true);}});
 it("applies the remote-control amendment without inverse semantics",async()=>{const result=await load();if(result.status!=="READY")throw new Error(result.reason);const remote=result.snapshot.payload.questions.find(q=>q.targetConcept==="REMOTE_CONTROL");expect(remote?.answerDomain).toMatchObject({type:"ENUM",values:["WANTED","NOT_IMPORTANT"],normalizedShape:"{wanted:boolean}"});expect(JSON.stringify(remote)).not.toMatch(/PROHIBITED|REQUIRED|kesinlikle olmasın/iu);});
 it("freezes capacity exclusion without a kg question or threshold",async()=>{const result=await load();if(result.status!=="READY")throw new Error(result.reason);expect(result.snapshot.payload.questions.every(q=>!/capacity|kg/iu.test(q.questionKey))).toBe(true);expect(result.snapshot.payload.excludedTopics).toContainEqual(expect.objectContaining({topic:"CAPACITY_MINIMUM_KG",classification:"FROZEN_EXCLUSION"}));expect(result.snapshot.payload.questions.some(q=>JSON.stringify(q.answerDomain).match(/kg/iu))).toBe(false);});
 it("preserves total priority, clarification, neutral absence and influence boundaries",async()=>{const result=await load();if(result.status!=="READY")throw new Error(result.reason);const p=result.snapshot.payload;expect(p.questions.map(q=>[q.questionKey,q.priority])).toEqual([["appliances.wm.installation.maxWidthMm",10],["appliances.wm.installation.maxHeightMm",20],["appliances.wm.installation.maxBodyDepthMm",30],["appliances.wm.budget.maximumTry",40],["appliances.wm.remoteControl.requirement",50],["appliances.wm.autoDosing.preference",60],["appliances.wm.noise.priority",70]]);expect(p.selectionPolicy).toMatchObject({clarificationPrecedence:true,maximumQuestionsPerSelection:1,stableQuestionKeyTieBreak:true,personaInfluence:"NONE",candidateArrayOrderInfluence:"NONE"});expect(p.selectionPolicy.noQuestionMeaning).toContain("NOT_SUFFICIENCY");expect(p.selectionPolicy.noQuestionMeaning).toContain("NOT_DECISION_READY");});
 it("freezes materiality, suppression and governed reopening",async()=>{const result=await load();if(result.status!=="READY")throw new Error(result.reason);const p=result.snapshot.payload;expect(p.questions.every(q=>q.materiality.requiresCandidateDifference&&q.materiality.requiresContextCondition&&q.materiality.softPreferenceEffect==="NON_FILTERING")).toBe(true);expect(p.suppressionPolicy).toEqual({acceptedTargetSuppresses:true,pendingTargetSuppresses:true,unchangedAskedStateSuppresses:true,fingerprintCannotOverrideActiveAcceptedAnswer:true,transcriptInference:"FORBIDDEN",retryOrTimeReopening:"FORBIDDEN"});expect(p.reopeningPolicy.authorizedReasons).toEqual(["TARGET_CLEARED","TARGET_CORRECTED","TARGET_SUPERSEDED","MATERIALLY_CHANGED_EVALUATION_AUTHORITY"]);});
 it.each(["questionKey","priority","answer enum","template","materiality","suppression/reopening"])("fails closed when %s changes without a new digest",async(kind)=>{const changed=mutate(a=>{if(kind==="questionKey")a.payload.questions[0].questionKey+="x";else if(kind==="priority")a.payload.questions[0].priority=999;else if(kind==="answer enum")a.payload.questions[4].answerDomain.values=["WANTED","PROHIBITED"];else if(kind==="template")a.payload.questions[0].realization.textTr+=" değişti";else if(kind==="materiality")a.payload.questions[0].materiality.requiresContextCondition="OTHER";else a.payload.suppressionPolicy.acceptedTargetSuppresses=false;});await expect(load(changed)).resolves.toEqual({status:"FAILED_CLOSED",reason:"POLICY_DIGEST_MISMATCH"});});
 it.each([
  ["duplicate keys",(a:any)=>{a.payload.questions[1].questionKey=a.payload.questions[0].questionKey;},"DUPLICATE_QUESTION_KEY"],
  ["unknown target",(a:any)=>{a.payload.questions[0].targetConcept="UNKNOWN";},"UNKNOWN_TARGET_CONCEPT"],
  ["unknown discriminator",(a:any)=>{a.payload.questions[0].materiality.requiresCandidateDifference="UNKNOWN";},"UNKNOWN_DISCRIMINATOR"],
  ["invalid numeric range",(a:any)=>{a.payload.questions[0].answerDomain.minimum=a.payload.questions[0].answerDomain.maximum;},"INVALID_ANSWER_DOMAIN"],
  ["duplicate enum",(a:any)=>{a.payload.questions[4].answerDomain.values=["WANTED","WANTED"];},"INVALID_ANSWER_DOMAIN"],
  ["ambiguous priority",(a:any)=>{a.payload.questions[1].priority=a.payload.questions[0].priority;},"AMBIGUOUS_PRIORITY"],
  ["dependency cycle",(a:any)=>{a.payload.questions[0].dependencies=[a.payload.questions[0].questionKey];},"DEPENDENCY_CYCLE"],
  ["wrong semantic",(a:any)=>{a.payload.bindings.semanticRegistryDigest="0".repeat(64);},"SEMANTIC_BINDING_MISMATCH"],
  ["wrong catalog",(a:any)=>{a.payload.bindings.catalogDigest="0".repeat(64);},"CATALOG_BINDING_MISMATCH"],
 ] as const)("fails closed for %s",async(_label,mutation,reason)=>expect(load(mutate(mutation,true))).resolves.toEqual({status:"FAILED_CLOSED",reason}));
 it("rejects missing templates, status/lifecycle/activity failures, unsafe paths and wrong identity",async()=>{expect(await load(mutate(a=>{a.payload.questions[0].realization.textTr="";},true))).toEqual({status:"FAILED_CLOSED",reason:"POLICY_SCHEMA_INVALID"});expect(await load(mutate(a=>{a.payload.governanceStatus="DRAFT";},true))).toEqual({status:"FAILED_CLOSED",reason:"POLICY_NOT_APPROVED"});expect(await load(mutate(a=>{a.payload.lifecycle="MUTABLE";},true))).toEqual({status:"FAILED_CLOSED",reason:"POLICY_NOT_FROZEN"});expect(await load(mutate(a=>{a.payload.runtimeActive=false;},true))).toEqual({status:"FAILED_CLOSED",reason:"POLICY_NOT_ACTIVE"});const unsafe=JSON.stringify({...JSON.parse(pointerRaw),policyFile:"../../secret.json"});expect(await load(policyRaw,unsafe)).toEqual({status:"FAILED_CLOSED",reason:"UNSAFE_POLICY_PATH"});const wrong=JSON.stringify({...JSON.parse(pointerRaw),policyId:"OTHER"});expect(await load(policyRaw,wrong)).toEqual({status:"FAILED_CLOSED",reason:"ACTIVE_POINTER_INVALID"});});
 it("contains no planner, ranking, recommendation, sufficiency authorization or commerce fields",async()=>{const result=await load();if(result.status!=="READY")throw new Error(result.reason);expect(JSON.stringify(result.snapshot.payload)).not.toMatch(/"(?:rank|score|winner|recommendation|sufficiencyRule|decisionCard|advisor|seller|affiliate)"\s*:/iu);});
});
