import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
import { createFileSystemAppliancesArtifactRepository,loadActiveAppliancesAuthority } from "../authority/loader.server";
import { evaluateAppliancesCandidates } from "../candidate/evaluate";
import { enterAppliancesDepartment } from "../entry.server";
import { validateWashingMachineQuestionPolicyDraft,washingMachineQuestionPolicyDraftSchema } from "./questionPolicyDraft";
const file=new URL("../../../data/governance/appliances/question-policy/drafts/WASHING_MACHINE_QUESTION_POLICY-v0.1.json",import.meta.url);
const draft=JSON.parse(readFileSync(file,"utf8")) as unknown;
async function authority(){const repository=createFileSystemAppliancesArtifactRepository(process.cwd());const loaded=await loadActiveAppliancesAuthority({repository});if(loaded.status!=="READY")throw new Error(loaded.reason);const entry=await enterAppliancesDepartment({repository,productType:"WASHING_MACHINE"});if(entry.status!=="READY")throw new Error(entry.status);const evaluated=evaluateAppliancesCandidates({authority:loaded.snapshot,state:entry.state});if(evaluated.status!=="READY")throw new Error(evaluated.reason);return{snapshot:loaded.snapshot,discriminators:new Set([...evaluated.projection.supportedDiscriminators,...(loaded.snapshot.catalog.capabilityRegistry as string[])])};}
describe("Washing Machine Question Policy governance draft",()=>{
 it("is schema-valid, non-active and honestly review-only",()=>{const parsed=washingMachineQuestionPolicyDraftSchema.parse(draft);expect(parsed.governanceStatus).toBe("READY_FOR_APPROVAL");expect(parsed.runtimeActive).toBe(false);expect(JSON.stringify(parsed)).not.toMatch(/"(?:rank|score|winner|recommendation)"\s*:/iu);});
 it("validates unique keys, total priority, semantic refs, materiality and acyclic dependencies",async()=>{const a=await authority();expect(validateWashingMachineQuestionPolicyDraft(draft,a.snapshot.conceptIds,a.discriminators)).toEqual({status:"VALID_DRAFT"});});
 it("keeps capacity outside discovery and records the unresolved Product decision",()=>{const parsed=washingMachineQuestionPolicyDraftSchema.parse(draft);expect(parsed.questions.every(q=>!q.questionKey.toLowerCase().includes("capacity"))).toBe(true);expect(parsed.excludedTopics).toContainEqual(expect.objectContaining({topic:"CAPACITY_MINIMUM_KG",classification:"UNSUPPORTED_PENDING_PRODUCT_DECISION"}));expect(parsed.decisionRegister).toContainEqual(expect.objectContaining({topic:"capacity-threshold-treatment",governanceClassification:"UNRESOLVED_PRODUCT_DECISION",approvalRequired:true}));});
 it("keeps clarification, persona and one-question boundaries explicit",()=>{const parsed=washingMachineQuestionPolicyDraftSchema.parse(draft);expect(parsed.selectionPolicy).toMatchObject({clarificationPrecedence:true,maximumQuestionsPerSelection:1,personaInfluence:"NONE",candidateArrayOrderInfluence:"NONE"});expect(parsed.selectionPolicy.noQuestionMeaning).toContain("NOT_SUFFICIENCY_OR_AUTHORIZATION");});
 it("fails duplicate keys, unknown concepts, ambiguous priority and dependency cycles",async()=>{const a=await authority();const parsed=washingMachineQuestionPolicyDraftSchema.parse(draft);const questions=[...parsed.questions];questions[1]={...questions[1],questionKey:questions[0].questionKey,targetConcept:"UNKNOWN",priority:questions[0].priority,dependencies:[questions[0].questionKey]};questions[0]={...questions[0],dependencies:[questions[0].questionKey]};const result=validateWashingMachineQuestionPolicyDraft({...parsed,questions},a.snapshot.conceptIds,a.discriminators);expect(result.status).toBe("INVALID_DRAFT");if(result.status==="INVALID_DRAFT")expect(result.reasons).toEqual(expect.arrayContaining(["DUPLICATE_QUESTION_KEY","AMBIGUOUS_PRIORITY",expect.stringContaining("UNKNOWN_TARGET_CONCEPT"),"DEPENDENCY_CYCLE"]));});
});
