/* eslint-disable @typescript-eslint/no-explicit-any -- mutation tests intentionally cross governed JSON shapes */
import { readFile } from "node:fs/promises";
import path from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import { createFileSystemAppliancesArtifactRepository, loadActiveAppliancesAuthority } from "../authority/loader.server";
import type { AppliancesAuthoritySnapshot } from "../authority/types";
import { createFileSystemQuestionPolicyRepository, loadActiveWashingMachineQuestionPolicy } from "./questionPolicyLoader.server";
import { createFileSystemSufficiencyRecommendationPolicyRepository, loadActiveWashingMachineSufficiencyRecommendationPolicy } from "./sufficiencyRecommendationPolicyLoader.server";
import { createFileSystemCandidateSelectionPolicyRepository, loadActiveWashingMachineCandidateSelectionPolicy } from "./candidateSelectionPolicyLoader.server";
import type { WashingMachineQuestionPolicyArtifact } from "./questionPolicyAuthority";
import type { SufficiencyRecommendationPolicyArtifact } from "./sufficiencyRecommendationPolicyAuthority";
import type { WashingMachineCandidateSelectionPolicyArtifact } from "./candidateSelectionPolicyAuthority";
import { digestRecommendationConstructionPolicy } from "./recommendationConstructionPolicyAuthority";
import { createFileSystemRecommendationConstructionPolicyRepository, loadActiveWashingMachineRecommendationConstructionPolicy, type RecommendationConstructionPolicyRepository } from "./recommendationConstructionPolicyLoader.server";

const root = process.cwd();
const releasePath = path.join(root, "data/production/appliances/recommendation-construction-policy/releases/WASHING_MACHINE_RECOMMENDATION_CONSTRUCTION_POLICY-v0.2/policy.json");
const pointerPath = path.join(root, "data/production/appliances/recommendation-construction-policy/active.json");
let authority: AppliancesAuthoritySnapshot, questionPolicy: WashingMachineQuestionPolicyArtifact, sufficiencyPolicy: SufficiencyRecommendationPolicyArtifact, selectionPolicy: WashingMachineCandidateSelectionPolicyArtifact, policyRaw: string, pointerRaw: string;
beforeAll(async () => {
  const a = await loadActiveAppliancesAuthority({ repository: createFileSystemAppliancesArtifactRepository(root) }); if (a.status !== "READY") throw new Error(a.reason); authority = a.snapshot;
  const q = await loadActiveWashingMachineQuestionPolicy({ repository: createFileSystemQuestionPolicyRepository(root), authority }); if (q.status !== "READY") throw new Error(q.reason); questionPolicy = q.snapshot;
  const s = await loadActiveWashingMachineSufficiencyRecommendationPolicy({ repository: createFileSystemSufficiencyRecommendationPolicyRepository(root), authority, questionPolicy }); if (s.status !== "READY") throw new Error(s.reason); sufficiencyPolicy = s.snapshot;
  const c = await loadActiveWashingMachineCandidateSelectionPolicy({ repository: createFileSystemCandidateSelectionPolicyRepository(root), authority, questionPolicy, sufficiencyPolicy }); if (c.status !== "READY") throw new Error(c.reason); selectionPolicy = c.snapshot;
  [policyRaw, pointerRaw] = await Promise.all([readFile(releasePath, "utf8"), readFile(pointerPath, "utf8")]);
});
const repository = (policy = policyRaw, pointer = pointerRaw): RecommendationConstructionPolicyRepository => ({ readActive: async () => pointer, readPolicy: async () => policy });
const mutate = (fn: (artifact: any) => void, rehash = false) => { const artifact = JSON.parse(policyRaw), pointer = JSON.parse(pointerRaw); fn(artifact); if (rehash) { artifact.policyDigest = digestRecommendationConstructionPolicy(artifact.payload); pointer.policyDigest = artifact.policyDigest; } return { policy: JSON.stringify(artifact), pointer: JSON.stringify(pointer) }; };
const load = (changed?: { policy: string; pointer: string }, overrides?: Partial<Parameters<typeof loadActiveWashingMachineRecommendationConstructionPolicy>[0]>) => loadActiveWashingMachineRecommendationConstructionPolicy({ repository: changed ? repository(changed.policy, changed.pointer) : repository(), authority, questionPolicy, sufficiencyPolicy, selectionPolicy, ...overrides });

describe("approved Washing Machine Recommendation Construction Policy authority", () => {
  it("loads approved frozen active v0.2 with deterministic digest and deep immutability", async () => { const result = await loadActiveWashingMachineRecommendationConstructionPolicy({ repository: createFileSystemRecommendationConstructionPolicyRepository(root), authority, questionPolicy, sufficiencyPolicy, selectionPolicy }); expect(result.status).toBe("READY"); if (result.status === "READY") { expect(result.snapshot.payload).toMatchObject({ policyId: "WASHING_MACHINE_RECOMMENDATION_CONSTRUCTION_POLICY/v0.1", governanceStatus: "APPROVED", lifecycle: "FROZEN", runtimeActive: true }); expect(digestRecommendationConstructionPolicy(result.snapshot.payload)).toBe("758ff2fe35578aa447f4316dfb869450d02edd54708a07e0ee2931e2cfac7c95"); expect(result.snapshot.policyDigest).toBe("758ff2fe35578aa447f4316dfb869450d02edd54708a07e0ee2931e2cfac7c95"); expect(Object.isFrozen(result.snapshot.payload.traceabilityMatrix)).toBe(true); } });
  it("does not treat the preserved draft as active authority", async () => { const draft = await readFile(path.join(root, "data/governance/appliances/recommendation-construction-policy/drafts/WASHING_MACHINE_RECOMMENDATION_CONSTRUCTION_POLICY-v0.1.json"), "utf8"); await expect(load({ policy: draft, pointer: pointerRaw })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "POLICY_SCHEMA_INVALID" }); });
  it("freezes all outcomes and permits a single recommendation only for SELECTED_SINGLE", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); expect(result.snapshot.payload.outcomePolicy.map((item) => [item.selectionOutcome, item.artifactKind, item.singleProductAllowed])).toEqual([["SELECTED_SINGLE", "SINGLE_PRODUCT_RECOMMENDATION", true], ["TIED_TOP_SET", "TIED_SET_EXPLANATION", false], ["NON_DOMINATED_SET", "TRADE_OFF_SET_EXPLANATION", false], ["NO_GOVERNED_SELECTION", "NO_RECOMMENDATION_CONSTRUCTIBLE", false], ["FAILED_CLOSED", "FAILED_CLOSED", false]]); });
  it("freezes structured authority, evidence separation, disclosure order, price volatility and bounded realization", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); const p = result.snapshot.payload; expect(p.artifactContract.authoritativeForm).toBe("STRUCTURED_ARTIFACT"); expect(p.rationaleContract.technicalInterpretationSeparation.fields).toHaveLength(5); expect(p.disclosurePolicy.categories).toHaveLength(15); expect(p.disclosurePolicy.ordering).toHaveLength(12); expect(p.pricePolicy).toMatchObject({ permanentTruth: false, technicalFact: false, sellerEffect: "NONE", affiliateEffect: "NONE" }); expect(p.realizationPolicy).toMatchObject({ model: "STRUCTURED_FACTS_PLUS_BOUNDED_MODEL_REALIZATION", fallback: "DETERMINISTIC_TEMPLATES_OR_NO_PROSE" }); });
  it("freezes authorization, persona and commerce non-authority", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); const p = result.snapshot.payload; expect(p.decisionAuthorizationBoundary).toMatchObject({ authorizesDecisionReady: false, authorizesDecisionAuthorization: false, authorizesDecisionCard: false }); expect(p.persona).toEqual({ rationaleAuthority: "NONE", contentEffect: "NONE", orderingEffect: "NONE" }); expect(p.commerce).toEqual({ sellerEffect: "NONE", retailerEffect: "NONE", affiliateEffect: "NONE" }); });
  it.each(["outcome", "artifact", "rationale", "disclosure", "realization", "forbidden claim", "dependency"])('rejects un-rehashed %s mutation by digest', async (kind) => { const changed = mutate((a) => { if (kind === "outcome") a.payload.outcomePolicy[0].behavior += " changed"; else if (kind === "artifact") a.payload.artifactContract.requiredFields.pop(); else if (kind === "rationale") a.payload.rationaleContract.allowedSources[0] = "marketing"; else if (kind === "disclosure") a.payload.disclosurePolicy.ordering.reverse(); else if (kind === "realization") a.payload.realizationPolicy.modelMay[0] += " and invent"; else if (kind === "forbidden claim") a.payload.languagePolicy.forbiddenClaimClasses[0] += " changed"; else a.payload.bindings.catalog.releaseDigest = "0".repeat(64); }); await expect(load(changed)).resolves.toEqual({ status: "FAILED_CLOSED", reason: "POLICY_DIGEST_MISMATCH" }); });
  it.each([["interpretation", (a: any) => a.payload.rationaleContract.technicalInterpretationSeparation.semanticAuthorityRequired = false], ["price", (a: any) => a.payload.pricePolicy.permanentTruth = true], ["fallback", (a: any) => a.payload.realizationPolicy.fallback = "FREE_FORM"], ["authorization", (a: any) => a.payload.decisionAuthorizationBoundary.chain += " changed"]])("structurally rejects %s mutations before digest acceptance", async (_name, fn) => { await expect(load(mutate(fn))).resolves.toEqual({ status: "FAILED_CLOSED", reason: "POLICY_SCHEMA_INVALID" }); });
  it.each([
    ["catalog", (a: any) => a.payload.bindings.catalog.releaseDigest = "0".repeat(64), "CATALOG_BINDING_MISMATCH"], ["semantic", (a: any) => a.payload.bindings.semanticRegistry.digest = "0".repeat(64), "SEMANTIC_BINDING_MISMATCH"], ["question", (a: any) => a.payload.bindings.questionPolicy.digest = "0".repeat(64), "QUESTION_POLICY_BINDING_MISMATCH"], ["sufficiency", (a: any) => a.payload.bindings.sufficiencyPolicy.digest = "0".repeat(64), "SUFFICIENCY_POLICY_BINDING_MISMATCH"], ["selection", (a: any) => a.payload.bindings.candidateSelectionPolicy.digest = "0".repeat(64), "SELECTION_POLICY_BINDING_MISMATCH"], ["selection runtime", (a: any) => a.payload.bindings.selectionRuntimeInputContract = "other/v1", "SELECTION_RUNTIME_BINDING_MISMATCH"],
  ])("fails closed for rehashed %s dependency mutation", async (_name, fn, reason) => { await expect(load(mutate(fn, true))).resolves.toEqual({ status: "FAILED_CLOSED", reason }); });
  it.each([
    ["outcome", (a: any) => { a.payload.outcomePolicy[1].selectionOutcome = "SELECTED_SINGLE"; }, "INCOMPLETE_OUTCOME_HANDLING"], ["artifact", (a: any) => a.payload.artifactContract.requiredFields.splice(0, 4), "INCOMPLETE_ARTIFACT_CONTRACT"], ["rationale source", (a: any) => a.payload.rationaleContract.allowedSources[0] = "marketing", "INVALID_RATIONALE_SOURCE"], ["disclosure", (a: any) => a.payload.disclosurePolicy.ordering.pop(), "INCOMPLETE_DISCLOSURE_POLICY"],
  ])("fails semantically for rehashed %s mutation", async (_name, fn, reason) => { await expect(load(mutate(fn, true))).resolves.toEqual({ status: "FAILED_CLOSED", reason }); });
  it("fails for lifecycle and activation mutations", async () => { await expect(load(mutate((a) => a.payload.governanceStatus = "READY_FOR_APPROVAL", true))).resolves.toEqual({ status: "FAILED_CLOSED", reason: "POLICY_NOT_APPROVED" }); await expect(load(mutate((a) => a.payload.lifecycle = "DRAFT", true))).resolves.toEqual({ status: "FAILED_CLOSED", reason: "POLICY_NOT_FROZEN" }); await expect(load(mutate((a) => a.payload.runtimeActive = false, true))).resolves.toEqual({ status: "FAILED_CLOSED", reason: "POLICY_NOT_ACTIVE" }); });
  it("fails for missing, unsafe, invalid, and absent active artifacts", async () => { await expect(load(undefined, { repository: { readActive: async () => { throw new Error("missing"); }, readPolicy: async () => policyRaw } })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "ACTIVE_POINTER_MISSING" }); const unsafe = JSON.parse(pointerRaw); unsafe.policyFile = "../draft.json"; await expect(load({ policy: policyRaw, pointer: JSON.stringify(unsafe) })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "ACTIVE_POINTER_INVALID" }); await expect(load(undefined, { repository: { readActive: async () => pointerRaw, readPolicy: async () => { throw new Error("missing"); } } })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "POLICY_MISSING" }); });
});
