/* eslint-disable @typescript-eslint/no-explicit-any -- mutation tests intentionally cross governed JSON shapes */
import { readFile } from "node:fs/promises";
import path from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import { createFileSystemAppliancesArtifactRepository, loadActiveAppliancesAuthority } from "../authority/loader.server";
import type { AppliancesAuthoritySnapshot } from "../authority/types";
import { createFileSystemQuestionPolicyRepository, loadActiveWashingMachineQuestionPolicy } from "./questionPolicyLoader.server";
import type { WashingMachineQuestionPolicyArtifact } from "./questionPolicyAuthority";
import { digestSufficiencyRecommendationPolicy, SUFFICIENCY_OUTCOME_PRECEDENCE } from "./sufficiencyRecommendationPolicyAuthority";
import { createFileSystemSufficiencyRecommendationPolicyRepository, loadActiveWashingMachineSufficiencyRecommendationPolicy, type SufficiencyRecommendationPolicyRepository } from "./sufficiencyRecommendationPolicyLoader.server";

const root = process.cwd();
const artifactPath = path.join(root, "data/production/appliances/sufficiency-recommendation-entry/releases/WASHING_MACHINE_SUFFICIENCY_RECOMMENDATION_ENTRY_POLICY-v0.2/policy.json");
const pointerPath = path.join(root, "data/production/appliances/sufficiency-recommendation-entry/active.json");
let authority: AppliancesAuthoritySnapshot, questionPolicy: WashingMachineQuestionPolicyArtifact, artifactRaw: string, pointerRaw: string;
beforeAll(async () => { const loadedAuthority = await loadActiveAppliancesAuthority({ repository: createFileSystemAppliancesArtifactRepository(root) }); if (loadedAuthority.status !== "READY") throw new Error(loadedAuthority.reason); authority = loadedAuthority.snapshot; const loadedQuestion = await loadActiveWashingMachineQuestionPolicy({ repository: createFileSystemQuestionPolicyRepository(root), authority }); if (loadedQuestion.status !== "READY") throw new Error(loadedQuestion.reason); questionPolicy = loadedQuestion.snapshot; [artifactRaw, pointerRaw] = await Promise.all([readFile(artifactPath, "utf8"), readFile(pointerPath, "utf8")]); });
const repository = (artifact = artifactRaw, pointer = pointerRaw): SufficiencyRecommendationPolicyRepository => ({ readActive: async () => pointer, readPolicy: async () => artifact });
const mutate = (fn: (artifact: any) => void, rehash = false): { artifact: string; pointer: string } => { const artifact = JSON.parse(artifactRaw), pointer = JSON.parse(pointerRaw); fn(artifact); if (rehash) { artifact.policyDigest = digestSufficiencyRecommendationPolicy(artifact.payload); pointer.policyDigest = artifact.policyDigest; } return { artifact: JSON.stringify(artifact), pointer: JSON.stringify(pointer) }; };
const load = (changed?: { artifact: string; pointer: string }, overrides?: Partial<Parameters<typeof loadActiveWashingMachineSufficiencyRecommendationPolicy>[0]>) => loadActiveWashingMachineSufficiencyRecommendationPolicy({ repository: changed ? repository(changed.artifact, changed.pointer) : repository(), authority, questionPolicy, ...overrides });

describe("approved sufficiency/recommendation-entry policy authority", () => {
  it("loads an immutable approved frozen active v0.1 snapshot with deterministic digest and exact bindings", async () => { const result = await loadActiveWashingMachineSufficiencyRecommendationPolicy({ repository: createFileSystemSufficiencyRecommendationPolicyRepository(root), authority, questionPolicy }); expect(result.status).toBe("READY"); if (result.status === "READY") { const p = result.snapshot.payload; expect(p).toMatchObject({ policyId: "WASHING_MACHINE_SUFFICIENCY_RECOMMENDATION_ENTRY_POLICY/v0.1", governanceStatus: "APPROVED", lifecycle: "FROZEN", runtimeActive: true }); expect(digestSufficiencyRecommendationPolicy(p)).toBe(result.snapshot.policyDigest); expect(p.bindings).toMatchObject({ catalog: { release: authority.releaseVersion, releaseDigest: authority.catalogDigest }, semanticRegistry: { digest: authority.semanticDigest } }); expect(p.bindings.questionPolicy.digest).toBe(questionPolicy.policyDigest); expect(Object.isFrozen(result.snapshot.payload.pricePolicy.states)).toBe(true); } });
  it("freezes total precedence and complete outcomes without ambiguity", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); expect(result.snapshot.payload.precedence).toEqual(SUFFICIENCY_OUTCOME_PRECEDENCE); expect(result.snapshot.payload.outcomes.map((x) => x.kind)).toEqual(expect.arrayContaining([...SUFFICIENCY_OUTCOME_PRECEDENCE])); });
  it("maps planner states while preserving neutral no-question semantics", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); expect(result.snapshot.payload.plannerMapping).toEqual({ FAILED_CLOSED: "FAILED_CLOSED", CLARIFY: "CLARIFICATION_REQUIRED", ASK: "MORE_INFORMATION_REQUIRED", NO_AUTHORIZED_MATERIAL_QUESTION: "CONTINUE_REMAINING_GATES_NEUTRAL_ONLY" }); expect(result.snapshot.payload.outcomes.find((x) => x.kind === "RECOMMENDATION_POOL_ELIGIBLE")?.meaning).toContain("passed entry gates"); });
  it("keeps hard and soft uncertainty distinct", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); expect(result.snapshot.payload.uncertaintyPolicy).toMatchObject({ hard: { effect: "BLOCKING_EXCEPT_APPROVED_MIXED_PRICE_CASE" }, soft: { effect: "NON_BLOCKING" }, unknownClassification: "MUST_NOT_CONVERT_TO_COMPATIBLE_OR_INCOMPATIBLE" }); });
  it.each([
    ["NO_HARD_BUDGET", "PRICE_HAS_NO_ENTRY_EFFECT", "CONTINUE"], ["FRESH_COMPATIBLE", "PRICE_COMPATIBLE", "KNOWN_COMPATIBLE_POOL"], ["FRESH_INCOMPATIBLE", "BUDGET_INCOMPATIBLE", "KNOWN_INCOMPATIBLE_SET"], ["UNKNOWN_OR_UNUSABLE", "BUDGET_ELIGIBILITY_UNKNOWN", "PRESERVE_SEPARATELY"], ["MIXED_COMPATIBLE_AND_UNKNOWN", "PARTIAL_PRICE_COVERAGE", "CONTINUE_WITH_KNOWN_COMPATIBLE_POOL"], ["ZERO_COMPATIBLE_WITH_UNKNOWNS", "UNRESOLVED_PRICE_COVERAGE", "UNRESOLVED_HARD_UNCERTAINTY"], ["ALL_CONCLUSIVELY_OVER_BUDGET", "CONCLUSIVE_BUDGET_ZERO", "NO_RECOMMENDATION_ELIGIBLE_CANDIDATE"], ["ENTIRE_PROJECTION_STALE", "NO_FRESH_CANDIDATE_SPECIFIC_PRICE", "UNRESOLVED_HARD_UNCERTAINTY"], ["BINDING_MISMATCH", "AUTHORITY_FAILURE", "FAILED_CLOSED"]
  ])("freezes price state %s", async (state, classification, outcome) => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); expect(result.snapshot.payload.pricePolicy.states.find((x) => x.state === state)).toMatchObject({ classification, outcome }); });
  it("preserves unknown IDs in the mixed case and makes disclosure mandatory without a global block", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); const mixed = result.snapshot.payload.pricePolicy.states.find((x) => x.state === "MIXED_COMPATIBLE_AND_UNKNOWN"); expect(mixed).toMatchObject({ outcome: "CONTINUE_WITH_KNOWN_COMPATIBLE_POOL", unknownPreservation: "EXPLICIT_SEPARATE_SET", disclosureRequired: true }); expect(result.snapshot.payload.pricePolicy.requiredProvenance).toContain("budgetUnknownCandidateIds"); expect(result.snapshot.payload.pricePolicy.affiliateAvailabilityEffect).toBe("NONE"); });
  it("freezes zero singleton and multiple-candidate semantics without providing selection fields", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); const p = result.snapshot.payload; expect(p.candidateCountPolicy).toEqual(expect.arrayContaining([expect.objectContaining({ state: "CONCLUSIVE_ZERO", outcome: "NO_RECOMMENDATION_ELIGIBLE_CANDIDATE" }), expect.objectContaining({ state: "ZERO_KNOWN_PLUS_UNKNOWN", outcome: "UNRESOLVED_HARD_UNCERTAINTY" }), expect.objectContaining({ state: "SINGLETON", outcome: "RECOMMENDATION_POOL_ELIGIBLE" }), expect.objectContaining({ state: "MULTIPLE", outcome: "RECOMMENDATION_POOL_ELIGIBLE" }), expect.objectContaining({ state: "AUTHORITY_FAILURE", outcome: "FAILED_CLOSED" })])); expect(p.poolContract.provides).toEqual([]); expect(p.poolContract.form).toContain("NON_RANKED"); expect(p.poolContract.selectionPolicyDependency).toContain("REQUIRED_BEFORE"); });
  it("preserves capacity exclusion and persona NONE", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); expect(result.snapshot.payload.exclusions).toEqual({ capacity: { missingContextEffect: "NONE", questionRequired: false, kilogramThreshold: "ABSENT", householdMapping: "FORBIDDEN" }, persona: { sufficiencyEffect: "NONE", recommendationEntryEffect: "NONE" } }); expect(JSON.stringify(result.snapshot.payload.exclusions.capacity)).not.toMatch(/\d+\s*kg/iu); });
  it.each(["outcome", "precedence", "price rule", "candidate-count rule", "selection dependency", "capacity exclusion", "persona rule", "source digest", "required disclosure"])("detects unrehashable %s mutation by digest", async (kind) => { const changed = mutate((a) => { if (kind === "outcome") a.payload.outcomes[0].meaning += " changed"; else if (kind === "precedence") a.payload.precedence.reverse(); else if (kind === "price rule") a.payload.pricePolicy.states[4].outcome = "UNRESOLVED_HARD_UNCERTAINTY"; else if (kind === "candidate-count rule") a.payload.candidateCountPolicy[3].outcome = "UNRESOLVED_HARD_UNCERTAINTY"; else if (kind === "selection dependency") a.payload.poolContract.selectionPolicyDependency = "NONE"; else if (kind === "capacity exclusion") a.payload.exclusions.capacity.kilogramThreshold = "8kg"; else if (kind === "persona rule") a.payload.exclusions.persona.sufficiencyEffect = "MATERIAL"; else if (kind === "source digest") a.payload.bindings.semanticRegistry.digest = "0".repeat(64); else a.payload.requiredDisclosures[0] += " changed"; }); await expect(load(changed)).resolves.toEqual({ status: "FAILED_CLOSED", reason: "POLICY_DIGEST_MISMATCH" }); });
  it.each([
    ["precedence", (a: any) => a.payload.precedence.reverse(), "AMBIGUOUS_PRECEDENCE"], ["mixed price", (a: any) => a.payload.pricePolicy.states[4].outcome = "UNRESOLVED_HARD_UNCERTAINTY", "INCOMPLETE_PRICE_STATE"], ["selection", (a: any) => a.payload.poolContract.selectionPolicyDependency = "NONE", "INVALID_SELECTION_DEPENDENCY"], ["capacity", (a: any) => a.payload.exclusions.capacity.kilogramThreshold = "8kg", "CAPACITY_EXCLUSION_MISSING"], ["persona", (a: any) => a.payload.exclusions.persona.sufficiencyEffect = "MATERIAL", "PERSONA_AUTHORITY_VIOLATION"]
  ])("fails semantically after rehashed %s mutation", async (_kind, fn, reason) => { await expect(load(mutate(fn, true))).resolves.toEqual({ status: "FAILED_CLOSED", reason }); });
  it.each([
    ["catalog", (a: any) => a.payload.bindings.catalog.releaseDigest = "0".repeat(64), "CATALOG_BINDING_MISMATCH"],
    ["semantic", (a: any) => a.payload.bindings.semanticRegistry.digest = "0".repeat(64), "SEMANTIC_BINDING_MISMATCH"],
    ["question", (a: any) => a.payload.bindings.questionPolicy.digest = "0".repeat(64), "QUESTION_POLICY_BINDING_MISMATCH"],
    ["candidate", (a: any) => a.payload.bindings.candidateEvaluationPolicy = "wrong/v1", "CANDIDATE_POLICY_BINDING_MISMATCH"],
    ["planner", (a: any) => a.payload.bindings.questionPlannerContract = "wrong/v1", "PLANNER_POLICY_BINDING_MISMATCH"]
  ])("fails closed for rehashed %s dependency mismatch", async (_kind, fn, reason) => { await expect(load(mutate(fn, true))).resolves.toEqual({ status: "FAILED_CLOSED", reason }); });
  it("fails closed for missing active pointer unsafe paths and dependency mismatch", async () => { await expect(load(undefined, { repository: { readActive: async () => { throw new Error("missing"); }, readPolicy: async () => artifactRaw } })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "ACTIVE_POINTER_MISSING" }); const pointer = JSON.parse(pointerRaw); pointer.policyFile = "../draft.json"; await expect(load({ artifact: artifactRaw, pointer: JSON.stringify(pointer) })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "UNSAFE_POLICY_PATH" }); const wrongQuestion = structuredClone(questionPolicy); wrongQuestion.policyDigest = "0".repeat(64); await expect(load(undefined, { questionPolicy: wrongQuestion })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "QUESTION_POLICY_BINDING_MISMATCH" }); });
  it("keeps implementation scope at the authority boundary", async () => { const result = await load(); if (result.status !== "READY") throw new Error(result.reason); expect(result.snapshot.payload.scope).toEqual({ boundaryOutput: "NON_RANKED_CANDIDATE_POOL_ONLY", selectionImplementation: "OUT_OF_SCOPE", recommendationConstruction: "OUT_OF_SCOPE", decisionAuthorization: "OUT_OF_SCOPE", runtimeEvaluator: "OUT_OF_SCOPE", commerceEffect: "NONE" }); });
});
