import { createHash } from "node:crypto";
import { z } from "zod";

export const SUFFICIENCY_RECOMMENDATION_POLICY_ID = "WASHING_MACHINE_SUFFICIENCY_RECOMMENDATION_ENTRY_POLICY/v0.1" as const;
export const SUFFICIENCY_RECOMMENDATION_CANONICALIZATION = "CANONICAL_JSON_SORTED_KEYS_V1" as const;
export const SUFFICIENCY_OUTCOME_PRECEDENCE = ["FAILED_CLOSED", "CLARIFICATION_REQUIRED", "MORE_INFORMATION_REQUIRED", "UNRESOLVED_HARD_UNCERTAINTY", "NO_RECOMMENDATION_ELIGIBLE_CANDIDATE", "RECOMMENDATION_POOL_ELIGIBLE"] as const;

const sha = z.string().regex(/^[a-f0-9]{64}$/u);
const text = z.string().min(1);
const outcome = z.strictObject({ kind: z.enum(SUFFICIENCY_OUTCOME_PRECEDENCE), meaning: text, permission: text, prohibition: text });
const priceState = z.strictObject({ state: z.enum(["NO_HARD_BUDGET", "FRESH_COMPATIBLE", "FRESH_INCOMPATIBLE", "UNKNOWN_OR_UNUSABLE", "MIXED_COMPATIBLE_AND_UNKNOWN", "ZERO_COMPATIBLE_WITH_UNKNOWNS", "ALL_CONCLUSIVELY_OVER_BUDGET", "ENTIRE_PROJECTION_STALE", "BINDING_MISMATCH"]), classification: text, outcome: text, unknownPreservation: text, disclosureRequired: z.boolean() });
const candidateState = z.strictObject({ state: z.enum(["CONCLUSIVE_ZERO", "ZERO_KNOWN_PLUS_UNKNOWN", "SINGLETON", "MULTIPLE", "AUTHORITY_FAILURE"]), outcome: z.enum(SUFFICIENCY_OUTCOME_PRECEDENCE), contract: text });
const decision = z.strictObject({ decisionId: z.string().regex(/^PDR-\d{3}$/u), topic: text, approvedDecision: text, runtimeConsequence: text, approvalStatus: z.literal("APPROVED") });
const rule = z.strictObject({ ruleId: z.string().regex(/^SRP-\d{3}$/u), input: text, authority: text, output: text, blocking: z.enum(["BLOCKING", "NON_BLOCKING", "CONDITIONAL"]), disclosure: text });

export const sufficiencyRecommendationPolicyPayloadSchema = z.strictObject({
  schemaVersion: z.literal("washing-machine-sufficiency-recommendation-entry-policy/v1"), policyId: z.literal(SUFFICIENCY_RECOMMENDATION_POLICY_ID), governanceStatus: z.literal("APPROVED"), lifecycle: z.literal("FROZEN"), runtimeActive: z.literal(true), department: z.literal("APPLIANCES"), capability: z.literal("WASHING_MACHINE"), market: z.literal("TR"), stage: z.literal("AŞAMA_1"), approvedAt: z.string().datetime({ offset: true }),
  provenance: z.strictObject({ draftWorkUnit: z.literal("WU-APPL-SUFFICIENCY-RECOMMENDATION-POLICY-01"), approvalWorkUnit: z.literal("WU-APPL-SUFFICIENCY-RECOMMENDATION-POLICY-APPROVAL-FREEZE-01"), approvedBy: z.literal("ORGANIZATOR"), reviewVerdict: z.literal("ACCEPTED_WITH_REQUIRED_AMENDMENTS"), draftSource: text, amendments: z.tuple([z.literal("HARD_BUDGET_PRICE_UNCERTAINTY"), z.literal("MULTIPLE_CANDIDATE_HANDOFF")]) }),
  bindings: z.strictObject({ catalog: z.strictObject({ release: z.string().regex(/^APPLIANCES-WM-TR-v\d+\.\d+$/u), releaseDigest: sha, membershipDigest: sha, artifactSha256: sha }), semanticRegistry: z.strictObject({ id: z.literal("WASHING_MACHINE_SEMANTIC_REGISTRY/v0.1"), digest: sha }), questionPolicy: z.strictObject({ id: z.literal("WASHING_MACHINE_QUESTION_POLICY/v0.1"), digest: sha }), candidateEvaluationPolicy: z.literal("appliances-candidate-evaluation/v1"), questionPlannerContract: z.literal("appliances-question-selection/v1") }),
  precedence: z.tuple(SUFFICIENCY_OUTCOME_PRECEDENCE.map((value) => z.literal(value)) as [z.ZodLiteral<"FAILED_CLOSED">, z.ZodLiteral<"CLARIFICATION_REQUIRED">, z.ZodLiteral<"MORE_INFORMATION_REQUIRED">, z.ZodLiteral<"UNRESOLVED_HARD_UNCERTAINTY">, z.ZodLiteral<"NO_RECOMMENDATION_ELIGIBLE_CANDIDATE">, z.ZodLiteral<"RECOMMENDATION_POOL_ELIGIBLE">]),
  outcomes: z.array(outcome).length(6), plannerMapping: z.strictObject({ FAILED_CLOSED: z.literal("FAILED_CLOSED"), CLARIFY: z.literal("CLARIFICATION_REQUIRED"), ASK: z.literal("MORE_INFORMATION_REQUIRED"), NO_AUTHORIZED_MATERIAL_QUESTION: z.literal("CONTINUE_REMAINING_GATES_NEUTRAL_ONLY") }),
  contextPolicy: z.strictObject({ accepted: z.tuple([z.literal("ACCEPTED_EXPLICIT"), z.literal("ACCEPTED_CONFIRMED"), z.literal("ACCEPTED_INTERPRETED")]), nonSatisfying: z.array(z.enum(["PENDING", "REJECTED", "SUPERSEDED", "CLEARED", "CONTRADICTED", "RAW_UTTERANCE", "MODEL_PROPOSAL"])).length(7), questionApplicability: z.literal("ONLY_CURRENTLY_APPLICABLE_AND_MATERIAL_QUESTIONS_BLOCK; NO_GLOBALLY_MANDATORY_QUESTION") }),
  uncertaintyPolicy: z.strictObject({ hard: z.strictObject({ effect: z.literal("BLOCKING_EXCEPT_APPROVED_MIXED_PRICE_CASE"), states: z.array(text).min(5) }), soft: z.strictObject({ effect: z.literal("NON_BLOCKING"), disclosure: z.literal("REQUIRED_WHEN_LATER_RATIONALE_OR_COMPARISON_DEPENDS_ON_IT") }), unknownClassification: z.literal("MUST_NOT_CONVERT_TO_COMPATIBLE_OR_INCOMPATIBLE") }),
  pricePolicy: z.strictObject({ states: z.array(priceState).length(9), affiliateAvailabilityEffect: z.literal("NONE"), requiredProvenance: z.tuple([z.literal("knownCompatibleCandidateIds"), z.literal("knownIncompatibleCandidateIds"), z.literal("budgetUnknownCandidateIds"), z.literal("priceSnapshotIdentity"), z.literal("freshnessState"), z.literal("coverageLimitation"), z.literal("acceptedHardBudgetContextReference")]) }),
  candidateCountPolicy: z.array(candidateState).length(5), poolContract: z.strictObject({ form: z.literal("EXACT_UNIQUE_CANONICALLY_SERIALIZED_NON_RANKED_CANDIDATE_IDS"), canonicalOrderMeaning: z.literal("SERIALIZATION_ONLY"), singletonAllowed: z.literal(true), multipleAllowed: z.literal(true), unknownCandidateSet: z.literal("SEPARATE_EXPLICIT_PRESERVED_SET"), provides: z.tuple([]), selectionPolicyDependency: z.literal("REQUIRED_BEFORE_ANY_WINNER_ORDER_OR_RECOMMENDATION_FOR_MULTIPLE_CANDIDATES") }),
  exclusions: z.strictObject({ capacity: z.strictObject({ missingContextEffect: z.literal("NONE"), questionRequired: z.literal(false), kilogramThreshold: z.literal("ABSENT"), householdMapping: z.literal("FORBIDDEN") }), persona: z.strictObject({ sufficiencyEffect: z.literal("NONE"), recommendationEntryEffect: z.literal("NONE") }) }),
  requiredDisclosures: z.array(text).min(4), failClosedRules: z.array(text).min(8), productDecisionRegister: z.array(decision).min(12), traceabilityMatrix: z.array(rule).min(18), scope: z.strictObject({ boundaryOutput: z.literal("NON_RANKED_CANDIDATE_POOL_ONLY"), selectionImplementation: z.literal("OUT_OF_SCOPE"), recommendationConstruction: z.literal("OUT_OF_SCOPE"), decisionAuthorization: z.literal("OUT_OF_SCOPE"), runtimeEvaluator: z.literal("OUT_OF_SCOPE"), commerceEffect: z.literal("NONE") })
});
export const sufficiencyRecommendationPolicyArtifactSchema = z.strictObject({ envelopeSchemaVersion: z.literal("washing-machine-sufficiency-recommendation-entry-policy-artifact/v1"), canonicalSerialization: z.literal(SUFFICIENCY_RECOMMENDATION_CANONICALIZATION), policyDigest: sha, payload: sufficiencyRecommendationPolicyPayloadSchema });
export const sufficiencyRecommendationPolicyActivePointerSchema = z.strictObject({ schemaVersion: z.literal("appliances-sufficiency-recommendation-entry-active-pointer/v1"), policyId: z.literal(SUFFICIENCY_RECOMMENDATION_POLICY_ID), policyDigest: sha, policyFile: text, lifecycle: z.literal("ACTIVE") });
export type SufficiencyRecommendationPolicyArtifact = z.infer<typeof sufficiencyRecommendationPolicyArtifactSchema>;
export type SufficiencyRecommendationPolicyFailure = "POLICY_SCHEMA_INVALID"|"POLICY_DIGEST_MISMATCH"|"POLICY_NOT_APPROVED"|"POLICY_NOT_FROZEN"|"POLICY_NOT_ACTIVE"|"CATALOG_BINDING_MISMATCH"|"SEMANTIC_BINDING_MISMATCH"|"QUESTION_POLICY_BINDING_MISMATCH"|"CANDIDATE_POLICY_BINDING_MISMATCH"|"PLANNER_POLICY_BINDING_MISMATCH"|"AMBIGUOUS_PRECEDENCE"|"INCOMPLETE_OUTCOME"|"INCOMPLETE_PRICE_STATE"|"INCOMPLETE_CANDIDATE_COUNT_STATE"|"INVALID_SELECTION_DEPENDENCY"|"CAPACITY_EXCLUSION_MISSING"|"PERSONA_AUTHORITY_VIOLATION"|"INCOMPATIBLE_AUTHORITY";

export function canonicalizeSufficiencyRecommendationPolicy(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonicalizeSufficiencyRecommendationPolicy); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, canonicalizeSufficiencyRecommendationPolicy(item)])); return value; }
export function digestSufficiencyRecommendationPolicy(payload: unknown): string { return createHash("sha256").update(JSON.stringify(canonicalizeSufficiencyRecommendationPolicy(payload))).digest("hex"); }

export function validateSufficiencyRecommendationPolicy(input: { artifact: unknown; expectedDigest: string; catalogRelease: string; catalogDigest: string; membershipDigest: string; catalogArtifactSha256: string; semanticVersion: string; semanticDigest: string; questionPolicyId: string; questionPolicyDigest: string; candidatePolicy: string; plannerPolicy: string }): { status: "VALID"; artifact: SufficiencyRecommendationPolicyArtifact } | { status: "INVALID"; reason: SufficiencyRecommendationPolicyFailure } {
  type RawPayload = { governanceStatus?: unknown; lifecycle?: unknown; runtimeActive?: unknown; precedence?: unknown[]; bindings?: { catalog?: { release?: unknown; releaseDigest?: unknown; membershipDigest?: unknown; artifactSha256?: unknown }; semanticRegistry?: { id?: unknown; digest?: unknown }; questionPolicy?: { id?: unknown; digest?: unknown }; candidateEvaluationPolicy?: unknown; questionPlannerContract?: unknown }; poolContract?: { selectionPolicyDependency?: unknown }; exclusions?: { capacity?: { kilogramThreshold?: unknown; questionRequired?: unknown; householdMapping?: unknown }; persona?: { sufficiencyEffect?: unknown; recommendationEntryEffect?: unknown } } };
  const rawArtifact = input.artifact as { policyDigest?: unknown; payload?: RawPayload } | null, rawPayload = rawArtifact?.payload;
  if (rawPayload && typeof rawArtifact?.policyDigest === "string" && (rawArtifact.policyDigest !== input.expectedDigest || digestSufficiencyRecommendationPolicy(rawPayload) !== rawArtifact.policyDigest)) return { status: "INVALID", reason: "POLICY_DIGEST_MISMATCH" };
  const rawBindings = rawPayload?.bindings;
  if (rawBindings?.catalog && (rawBindings.catalog.release !== input.catalogRelease || rawBindings.catalog.releaseDigest !== input.catalogDigest || rawBindings.catalog.membershipDigest !== input.membershipDigest || rawBindings.catalog.artifactSha256 !== input.catalogArtifactSha256)) return { status: "INVALID", reason: "CATALOG_BINDING_MISMATCH" };
  if (rawBindings?.semanticRegistry && (rawBindings.semanticRegistry.id !== input.semanticVersion || rawBindings.semanticRegistry.digest !== input.semanticDigest)) return { status: "INVALID", reason: "SEMANTIC_BINDING_MISMATCH" };
  if (rawBindings?.questionPolicy && (rawBindings.questionPolicy.id !== input.questionPolicyId || rawBindings.questionPolicy.digest !== input.questionPolicyDigest)) return { status: "INVALID", reason: "QUESTION_POLICY_BINDING_MISMATCH" };
  if (rawBindings?.candidateEvaluationPolicy !== undefined && rawBindings.candidateEvaluationPolicy !== input.candidatePolicy) return { status: "INVALID", reason: "CANDIDATE_POLICY_BINDING_MISMATCH" };
  if (rawBindings?.questionPlannerContract !== undefined && rawBindings.questionPlannerContract !== input.plannerPolicy) return { status: "INVALID", reason: "PLANNER_POLICY_BINDING_MISMATCH" };
  if (rawPayload && Array.isArray(rawPayload.precedence) && rawPayload.precedence.some((value: unknown, index: number) => value !== SUFFICIENCY_OUTCOME_PRECEDENCE[index])) return { status: "INVALID", reason: "AMBIGUOUS_PRECEDENCE" };
  if (rawPayload?.poolContract?.selectionPolicyDependency !== undefined && rawPayload.poolContract.selectionPolicyDependency !== "REQUIRED_BEFORE_ANY_WINNER_ORDER_OR_RECOMMENDATION_FOR_MULTIPLE_CANDIDATES") return { status: "INVALID", reason: "INVALID_SELECTION_DEPENDENCY" };
  if (rawPayload?.exclusions?.capacity && (rawPayload.exclusions.capacity.kilogramThreshold !== "ABSENT" || rawPayload.exclusions.capacity.questionRequired !== false || rawPayload.exclusions.capacity.householdMapping !== "FORBIDDEN")) return { status: "INVALID", reason: "CAPACITY_EXCLUSION_MISSING" };
  if (rawPayload?.exclusions?.persona && (rawPayload.exclusions.persona.sufficiencyEffect !== "NONE" || rawPayload.exclusions.persona.recommendationEntryEffect !== "NONE")) return { status: "INVALID", reason: "PERSONA_AUTHORITY_VIOLATION" };
  const parsed = sufficiencyRecommendationPolicyArtifactSchema.safeParse(input.artifact);
  if (!parsed.success) { const payload = (input.artifact as { payload?: Record<string, unknown> } | null)?.payload; if (payload?.governanceStatus !== undefined && payload.governanceStatus !== "APPROVED") return { status: "INVALID", reason: "POLICY_NOT_APPROVED" }; if (payload?.lifecycle !== undefined && payload.lifecycle !== "FROZEN") return { status: "INVALID", reason: "POLICY_NOT_FROZEN" }; if (payload?.runtimeActive !== undefined && payload.runtimeActive !== true) return { status: "INVALID", reason: "POLICY_NOT_ACTIVE" }; return { status: "INVALID", reason: "POLICY_SCHEMA_INVALID" }; }
  const artifact = parsed.data, p = artifact.payload, b = p.bindings;
  if (artifact.policyDigest !== input.expectedDigest || digestSufficiencyRecommendationPolicy(p) !== artifact.policyDigest) return { status: "INVALID", reason: "POLICY_DIGEST_MISMATCH" };
  if (b.catalog.release !== input.catalogRelease || b.catalog.releaseDigest !== input.catalogDigest || b.catalog.membershipDigest !== input.membershipDigest || b.catalog.artifactSha256 !== input.catalogArtifactSha256) return { status: "INVALID", reason: "CATALOG_BINDING_MISMATCH" };
  if (b.semanticRegistry.id !== input.semanticVersion || b.semanticRegistry.digest !== input.semanticDigest) return { status: "INVALID", reason: "SEMANTIC_BINDING_MISMATCH" };
  if (b.questionPolicy.id !== input.questionPolicyId || b.questionPolicy.digest !== input.questionPolicyDigest) return { status: "INVALID", reason: "QUESTION_POLICY_BINDING_MISMATCH" };
  if (b.candidateEvaluationPolicy !== input.candidatePolicy) return { status: "INVALID", reason: "CANDIDATE_POLICY_BINDING_MISMATCH" }; if (b.questionPlannerContract !== input.plannerPolicy) return { status: "INVALID", reason: "PLANNER_POLICY_BINDING_MISMATCH" };
  if (new Set(p.precedence).size !== 6 || p.precedence.some((value, index) => value !== SUFFICIENCY_OUTCOME_PRECEDENCE[index])) return { status: "INVALID", reason: "AMBIGUOUS_PRECEDENCE" };
  if (new Set(p.outcomes.map((x) => x.kind)).size !== 6) return { status: "INVALID", reason: "INCOMPLETE_OUTCOME" }; if (new Set(p.pricePolicy.states.map((x) => x.state)).size !== 9) return { status: "INVALID", reason: "INCOMPLETE_PRICE_STATE" }; if (new Set(p.candidateCountPolicy.map((x) => x.state)).size !== 5) return { status: "INVALID", reason: "INCOMPLETE_CANDIDATE_COUNT_STATE" };
  const mixed = p.pricePolicy.states.find((x) => x.state === "MIXED_COMPATIBLE_AND_UNKNOWN"), zeroUnknown = p.pricePolicy.states.find((x) => x.state === "ZERO_COMPATIBLE_WITH_UNKNOWNS"); if (mixed?.outcome !== "CONTINUE_WITH_KNOWN_COMPATIBLE_POOL" || !mixed.disclosureRequired || mixed.unknownPreservation !== "EXPLICIT_SEPARATE_SET" || zeroUnknown?.outcome !== "UNRESOLVED_HARD_UNCERTAINTY") return { status: "INVALID", reason: "INCOMPLETE_PRICE_STATE" };
  if (p.poolContract.form !== "EXACT_UNIQUE_CANONICALLY_SERIALIZED_NON_RANKED_CANDIDATE_IDS" || p.poolContract.provides.length !== 0 || p.poolContract.selectionPolicyDependency !== "REQUIRED_BEFORE_ANY_WINNER_ORDER_OR_RECOMMENDATION_FOR_MULTIPLE_CANDIDATES") return { status: "INVALID", reason: "INVALID_SELECTION_DEPENDENCY" };
  if (p.exclusions.capacity.kilogramThreshold !== "ABSENT" || p.exclusions.capacity.questionRequired || p.exclusions.capacity.householdMapping !== "FORBIDDEN") return { status: "INVALID", reason: "CAPACITY_EXCLUSION_MISSING" }; if (p.exclusions.persona.sufficiencyEffect !== "NONE" || p.exclusions.persona.recommendationEntryEffect !== "NONE") return { status: "INVALID", reason: "PERSONA_AUTHORITY_VIOLATION" };
  if (p.scope.runtimeEvaluator !== "OUT_OF_SCOPE" || p.scope.selectionImplementation !== "OUT_OF_SCOPE" || p.scope.recommendationConstruction !== "OUT_OF_SCOPE" || p.scope.decisionAuthorization !== "OUT_OF_SCOPE" || p.scope.commerceEffect !== "NONE") return { status: "INVALID", reason: "INCOMPATIBLE_AUTHORITY" };
  return { status: "VALID", artifact };
}
