import { readFile } from "node:fs/promises";
import path from "node:path";
import { beforeEach, describe, expect, it } from "vitest";
import { createFileSystemAppliancesArtifactRepository, loadActiveAppliancesAuthority, loadCurrentPriceProjection, resetAppliancesAuthorityCacheForTests, type AppliancesArtifactRepository } from "./loader.server";
const root = process.cwd(); const release = "APPLIANCES-WM-TR-v0.1"; const releaseRoot = path.join(root, "data/production/appliances/washing-machines/releases", release);
const raws = async () => ({ active: JSON.stringify({ schemaVersion: "appliances-authority-active-pointer/v1", releaseVersion: release, lifecycle: "ACTIVE" }), manifest: await readFile(path.join(releaseRoot, "manifest.json"), "utf8"), catalog: await readFile(path.join(releaseRoot, "catalog.json"), "utf8"), semantic: await readFile(path.join(releaseRoot, "semantic-registry.json"), "utf8"), pricePointer: await readFile(path.join(root, "data/production/appliances/prices/current.json"), "utf8"), price: await readFile(path.join(root, "data/production/appliances/prices/snapshots/APPLIANCES-WM-TR-PRICE-2026-09-03T021000+0300.json"), "utf8") });
const repository = async (mutate: Partial<Record<"active" | "manifest" | "catalog" | "semantic" | "pricePointer" | "price", (value: string) => string>> = {}): Promise<AppliancesArtifactRepository> => { const data = await raws(); for (const [key, fn] of Object.entries(mutate)) data[key as keyof typeof data] = fn!(data[key as keyof typeof data]); return { readActive: async () => data.active, readRelease: async (_release, file) => file === "manifest.json" ? data.manifest : file === "catalog.json" ? data.catalog : data.semantic, readPricePointer: async () => data.pricePointer, readPriceSnapshot: async () => data.price }; };
// Test mutations intentionally address heterogeneous governed JSON fixtures.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const mutateJson = (raw: string, fn: (value: any) => void) => { const value = JSON.parse(raw); fn(value); return JSON.stringify(value); };
describe("Appliances governed authority loader", () => { beforeEach(resetAppliancesAuthorityCacheForTests); it("loads the approved decision-adoption successor", async () => { const result = await loadActiveAppliancesAuthority({ repository: createFileSystemAppliancesArtifactRepository(root) }); expect(result.status).toBe("READY"); if (result.status === "READY") { expect(result.snapshot.productIds.size).toBe(29); expect(result.snapshot.catalogDigest).toBe("1b89b1bcfb3bc7c8e19a1916417c67db6246c44ec9d55fa835ec6bfa9fbad587"); } }); it("fails for a missing release", async () => { const repo = await repository(); repo.readRelease = async () => { throw new Error("missing"); }; await expect(loadActiveAppliancesAuthority({ repository: repo })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "RELEASE_MISSING" }); }); it.each([
  ["catalog schema", { catalog: (raw: string) => mutateJson(raw, (x) => { x.schemaVersion = "future"; }) }, "CATALOG_SCHEMA_MISMATCH"],
  ["member count", { manifest: (raw: string) => mutateJson(raw, (x) => { x.memberCount = 23; }) }, "MEMBER_COUNT_MISMATCH"],
  ["catalog digest", { catalog: (raw: string) => mutateJson(raw, (x) => { x.releaseDigest = "0".repeat(64); }) }, "CATALOG_ARTIFACT_DIGEST_MISMATCH"],
  ["membership", { catalog: (raw: string) => mutateJson(raw, (x) => { x.membershipDigest = "0".repeat(64); }) }, "MEMBERSHIP_DIGEST_MISMATCH"],
  ["semantic digest", { semantic: (raw: string) => `${raw} ` }, "SEMANTIC_DIGEST_MISMATCH"],
  ["wrong market", { catalog: (raw: string) => mutateJson(raw, (x) => { x.products[0].market = "US"; }) }, "WRONG_MARKET"],
  ["wrong product type", { catalog: (raw: string) => mutateJson(raw, (x) => { x.products[0].productType = "DRYER"; }) }, "WRONG_PRODUCT_TYPE"],
  ["duplicate active product", { catalog: (raw: string) => mutateJson(raw, (x) => { x.products[1].productId = x.products[0].productId; }) }, "DUPLICATE_PRODUCT_IDENTITY"],
  ["historical contamination", { catalog: (raw: string) => mutateJson(raw, (x) => { x.historicalProducts[0].productId = x.releaseMembers[0]; }) }, "HISTORICAL_MEMBER_CONTAMINATION"],
  ["unknown capability", { catalog: (raw: string) => mutateJson(raw, (x) => { x.capabilityFacts[0].capabilityId = "UNKNOWN_NEW_CAPABILITY"; }) }, "UNKNOWN_CAPABILITY_ID"],
] as const)("fails closed on %s", async (_name, mutation, reason) => expect(loadActiveAppliancesAuthority({ repository: await repository(mutation) })).resolves.toEqual({ status: "FAILED_CLOSED", reason })); it("fails when the active manifest pointer is missing", async () => { const repo = await repository(); repo.readActive = async () => { throw new Error("missing"); }; await expect(loadActiveAppliancesAuthority({ repository: repo })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "ACTIVE_POINTER_MISSING" }); }); it("rejects unsafe active release paths", async () => expect(loadActiveAppliancesAuthority({ repository: await repository({ active: (raw) => mutateJson(raw, (x) => { x.releaseVersion = "../../secret"; }) }) })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "UNSAFE_RELEASE_PATH" })); });
describe("price projection isolation", () => { beforeEach(resetAppliancesAuthorityCacheForTests); it("keeps the unrebound price projection neutral after decision adoption", async () => { const repo = createFileSystemAppliancesArtifactRepository(root); const authority = await loadActiveAppliancesAuthority({ repository: repo }); expect(authority.status).toBe("READY"); if (authority.status !== "READY") return; await expect(loadCurrentPriceProjection({ repository: repo, authority: authority.snapshot, now: new Date("2026-09-03T12:00:00+03:00") })).resolves.toEqual({ status: "UNAVAILABLE", reason: "PRICE_BINDING_MISMATCH" }); }); it("keeps an expired unrebound projection neutral", async () => { const repo = createFileSystemAppliancesArtifactRepository(root); const authority = await loadActiveAppliancesAuthority({ repository: repo }); expect(authority.status).toBe("READY"); if (authority.status === "READY") await expect(loadCurrentPriceProjection({ repository: repo, authority: authority.snapshot, now: new Date("2026-09-05T00:00:00Z") })).resolves.toEqual({ status: "UNAVAILABLE", reason: "PRICE_BINDING_MISMATCH" }); }); it("keeps technical authority ready when prices are missing", async () => { const repo = await repository(); repo.readPricePointer = async () => { throw new Error("missing"); }; const authority = await loadActiveAppliancesAuthority({ repository: repo }); expect(authority.status).toBe("READY"); if (authority.status === "READY") await expect(loadCurrentPriceProjection({ repository: repo, authority: authority.snapshot, now: new Date() })).resolves.toEqual({ status: "UNAVAILABLE", reason: "PRICE_POINTER_MISSING" }); }); it("rejects price fields in TechnicalFact", async () => expect(loadActiveAppliancesAuthority({ repository: await repository({ catalog: (raw) => mutateJson(raw, (x) => { x.technicalFacts[0].priceTRY = 1; }) }) })).resolves.toEqual({ status: "FAILED_CLOSED", reason: "INCOMPATIBLE_AUTHORITY" })); });
