import Link from "next/link";
import Image from "next/image";
import type { ReactNode } from "react";
import type { DepartmentLandingPack } from "@/features/xpy/departmentLanding";
import { LegacyConversationForwarder } from "./LegacyConversationForwarder";

export function DepartmentLanding({ pack, legacyConversationDestination, stageOne }: { readonly pack: DepartmentLandingPack; readonly legacyConversationDestination?: string; readonly compactPlatformInfo?: boolean; readonly stageOne?: ReactNode }) {
  const appliance = pack.visualPack.sceneConcept === "STUDIO_CYCLORAMA";
  return <main data-xpy-landing={pack.version} data-xpy-department={pack.departmentId} data-xpy-visual-pack={pack.visualPack.visualPackId} data-xpy-scene={pack.visualPack.sceneConcept} className="overflow-x-clip bg-[#f5f3ee] text-stone-950">
    {legacyConversationDestination ? <LegacyConversationForwarder destination={legacyConversationDestination}/> : null}
    <section className={`relative isolate overflow-hidden bg-white ${stageOne ? "min-h-dvh" : "min-h-[min(800px,100dvh)]"}`}>
      {pack.heroImage ? <div aria-hidden="true" className="absolute inset-0"><Image src={pack.heroImage.src} alt={pack.heroImage.alt} fill preload sizes={pack.heroImage.sizes} className="object-cover object-[72%_center] sm:object-[68%_center] lg:object-center"/><div className="absolute inset-0 bg-gradient-to-r from-white via-white/90 to-white/5 sm:via-white/75 lg:via-white/35"/><div className="absolute inset-0 bg-gradient-to-t from-white/35 via-transparent to-white/20"/></div> : <><div aria-hidden="true" className={`absolute inset-0 ${appliance ? "bg-[radial-gradient(ellipse_at_75%_50%,#d9f3e8_0,transparent_32%),linear-gradient(115deg,#fff_42%,#e8e5df_42%,#faf9f6_75%)]" : "bg-[radial-gradient(ellipse_at_80%_40%,#d6ebe7_0,transparent_31%),linear-gradient(135deg,#fff_35%,#e8eeeb_68%,#bccbc6)]"}`} /><div aria-hidden="true" className={`absolute bottom-[-12%] right-[-8%] h-[48%] w-[62%] rounded-[50%] border-[26px] ${appliance ? "border-white/80 bg-stone-100/70 shadow-[inset_0_30px_70px_rgba(16,185,129,.10)]" : "rotate-[-8deg] border-white/65 bg-stone-700/10 shadow-[0_0_0_34px_rgba(255,255,255,.36)]"}`} /></>}
      <div className={`relative mx-auto flex max-w-7xl flex-col px-5 pb-14 pt-6 sm:px-8 lg:px-12 ${stageOne ? "min-h-dvh" : "min-h-[min(800px,100dvh)]"}`}>
        <header className="flex items-center justify-between gap-4"><Link href="/" aria-label="Expiya ana sayfasına dön" className="inline-flex min-h-11 items-center rounded-full border border-stone-200 bg-white/80 px-4 text-sm font-semibold shadow-sm backdrop-blur focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-700">← Ana sayfa</Link><Link href={pack.canonicalPath} aria-label={`${pack.visualPack.publicName} ana sayfa`} className="text-lg font-black tracking-[-.07em] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-700">EXPIYA <span className="font-medium tracking-tight text-emerald-800">{pack.visualPack.publicName.replace("Expiya ", "")}</span></Link></header>
        <div className={`${stageOne ? "grid flex-1 items-center gap-10 py-10 lg:grid-cols-[minmax(17rem,.72fr)_minmax(35rem,1.28fr)] lg:py-12" : "my-auto max-w-3xl py-16 sm:py-24"}`}>
          <div className={stageOne ? "order-2 min-w-0 lg:order-1" : undefined}><p className="flex items-center gap-3 text-xs font-bold uppercase tracking-[.3em] text-emerald-800 before:h-px before:w-10 before:bg-emerald-700">{pack.eyebrow}</p><h1 className={`mt-8 font-medium leading-[.86] tracking-[-.075em] ${stageOne ? "text-[clamp(3rem,5.5vw,5.8rem)]" : "text-[clamp(3.3rem,8vw,7rem)]"}`}><span className="block">{pack.headline[0]}</span><span className="block text-stone-500">{pack.headline[1]}.</span></h1><p className="mt-8 max-w-2xl text-base leading-7 text-stone-600 sm:text-xl sm:leading-9">{pack.supportingCopy}</p><div className="mt-9 flex flex-wrap gap-3">{stageOne ? null : <Link href={pack.primaryCta.href} className="inline-flex min-h-12 items-center rounded-full bg-emerald-700 px-6 font-semibold text-white shadow-lg shadow-emerald-900/10 transition hover:bg-emerald-800 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-700">{pack.primaryCta.label}<span aria-hidden="true" className="ml-4">→</span></Link>}{pack.secondaryCta ? <Link href={pack.secondaryCta.href} className="inline-flex min-h-12 items-center rounded-full border border-stone-300 bg-white/80 px-6 font-semibold backdrop-blur focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-700">{pack.secondaryCta.label}</Link> : null}</div><p className="mt-5 text-sm text-stone-500">Ücretsiz · Türkçe · Kendi hızında</p></div>
          {stageOne ? <div id="asama-1" className="order-1 min-w-0 scroll-mt-6 lg:order-2" aria-label={`${pack.visualPack.publicName} Aşama 1 karar görüşmesi`}>{stageOne}</div> : null}
        </div>
      </div>
    </section>

    {!stageOne ? <section className="bg-white px-5 py-20 text-center sm:px-8"><p className="text-xs font-bold uppercase tracking-[.3em] text-emerald-800">{pack.visualPack.publicName}</p><h2 className="mx-auto mt-4 max-w-3xl text-4xl font-medium tracking-[-.045em] sm:text-6xl">Karar yolculuğunu başlat.</h2><Link href={pack.primaryCta.href} className="mt-8 inline-flex min-h-12 items-center rounded-full bg-emerald-700 px-7 font-semibold text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-700">{pack.primaryCta.label}<span aria-hidden="true" className="ml-4">→</span></Link></section> : null}
    <footer className="border-t border-stone-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-8 text-sm text-stone-600 sm:px-8 md:flex-row md:items-center md:justify-between lg:px-12"><p className="max-w-2xl"><strong className="text-stone-950">EXPIYA · {pack.visualPack.publicName.replace("Expiya ", "")}</strong><span className="ml-2">{pack.footerCopy}</span></p><nav aria-label="Site bağlantıları" className="flex flex-wrap gap-x-5 gap-y-2"><Link href="/">Expiya Platform</Link><Link href="/expiya-nedir">Expiya nedir?</Link><Link href="/gizlilik">Gizlilik ve KVKK</Link></nav></div></footer>
  </main>;
}
