import Link from "next/link";
import type { ReactNode } from "react";
import type { XpyExperienceAdapter, XpyExperienceSlot, XpyExperienceState, XpyStageId } from "@/features/xpy/experience";

export function XpyStageNavigation({ adapter, current }: { readonly adapter: XpyExperienceAdapter; readonly current: XpyStageId }) {
  return <nav aria-label="XPY aşamaları" className="border-b border-stone-200 bg-white/95 text-stone-950 dark:border-stone-800 dark:bg-stone-950 dark:text-stone-50"><ol className="mx-auto grid max-w-7xl grid-cols-3 gap-1 px-3 py-2 sm:gap-2 sm:px-8">{adapter.stages.map((stage, index) => { const selected = stage.id === current; const gated = stage.availability === "UNAVAILABLE" || (stage.availability === "REQUIRES_HANDOFF" && !selected); const content = <><span className="block text-[10px] font-semibold uppercase tracking-wider opacity-60">{index + 1}. aşama</span><span className="block truncate text-xs font-semibold sm:text-sm">{stage.label.replace(/^Aşama \d · /u, "")}</span></>; return <li key={stage.id} className="min-w-0">{gated || selected ? <span aria-current={selected ? "step" : undefined} aria-disabled={gated ? "true" : undefined} title={stage.unavailableReason} className={`block min-h-12 rounded-xl border px-2 py-2 ${selected ? "border-emerald-600 bg-emerald-50 text-emerald-950 dark:bg-emerald-950 dark:text-emerald-50" : "cursor-not-allowed border-dashed border-stone-300 opacity-55 dark:border-stone-700"}`}>{content}{gated && <span className="sr-only"> Kullanılamıyor: {stage.unavailableReason}</span>}</span> : <Link href={stage.href} className="block min-h-12 rounded-xl border border-stone-200 px-2 py-2 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600 dark:border-stone-700">{content}</Link>}</li>; })}</ol></nav>;
}
export function XpyStagePage({ adapter, current, children, className = "bg-[#f4f1eb] text-stone-950" }: { readonly adapter: XpyExperienceAdapter; readonly current: XpyStageId; readonly children: ReactNode; readonly className?: string }) { return <main data-xpy-experience={adapter.experienceVersion} data-xpy-department={adapter.departmentId} data-xpy-visual-pack={adapter.visualPack.visualPackId} data-xpy-scene={adapter.visualPack.sceneConcept} data-xpy-stage={current} className={`expiya-adaptive-surface min-h-screen ${className}`}><XpyStageNavigation adapter={adapter} current={current}/>{children}</main>; }
export function XpyStageSlot({ name, children, className }: { readonly name: XpyExperienceSlot; readonly children: ReactNode; readonly className?: string }) { return <div data-xpy-slot={name} className={className}>{children}</div>; }
export function XpyStageState({ adapter, current, state, title, description, returnHref, returnLabel }: { readonly adapter: XpyExperienceAdapter; readonly current: XpyStageId; readonly state: XpyExperienceState; readonly title: string; readonly description: string; readonly returnHref: string; readonly returnLabel: string }) { return <XpyStagePage adapter={adapter} current={current}><section className="mx-auto flex min-h-[70dvh] max-w-4xl items-center px-4 py-10 sm:px-8"><div className="w-full overflow-hidden rounded-[2rem] border border-stone-200 bg-white shadow-xl"><div className="min-h-40 bg-[radial-gradient(circle_at_70%_20%,rgba(16,185,129,.25),transparent_38%),linear-gradient(135deg,#1c1917,#0c0a09)] p-6 text-white sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-300">{adapter.visualPack.labels[current === "STAGE_2_EVALUATION" ? "stageTwo" : "stageThree"]}</p><h1 className="mt-3 text-3xl font-semibold sm:text-5xl">{title}</h1></div><div data-xpy-state={state} role={state === "ERROR" ? "alert" : "status"} className="p-6 sm:p-10"><p className="max-w-2xl text-base leading-7 text-stone-600">{description}</p><p className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950">Bu ekran ürün karşılaştırması, ölçüm, tavsiye, sıralama, satıcı, teklif veya işlem verisi üretmez.</p><Link href={returnHref} className="mt-6 inline-flex min-h-12 items-center rounded-full bg-stone-950 px-5 font-semibold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600">← {returnLabel}</Link></div></div></section></XpyStagePage>; }
