import Link from "next/link";
import type { ReactNode } from "react";
import { XPY_STAGE_THREE_CONTRACT_VERSION, type XpyStageThreePresentationAdapter } from "@/features/xpy/stageThree/contracts";

export type XpyStageThreeShellState = "VERIFYING" | "READY" | "UNAVAILABLE" | "INVALID" | "COMPLETE";

const stateLabels: Record<XpyStageThreeShellState, string> = { VERIFYING: "Bağlantı kontrol ediliyor", READY: "Güvenli adım", UNAVAILABLE: "Henüz kullanılamıyor", INVALID: "Bağlantı geçersiz", COMPLETE: "Kontrol tamamlandı" };
const capabilityLabel = (state: "INTERNAL_REVIEW_ONLY" | "VERIFIED" | "UNAVAILABLE") => state === "VERIFIED" ? "Kullanılabilir" : state === "INTERNAL_REVIEW_ONLY" ? "Yalnız deneme" : "Kullanılamıyor";

export function XpyStageThreeShell({ adapter, state, title, description, publicProductIdentity, intentLabel, returnHref, returnLabel, notice, children }: { readonly adapter: XpyStageThreePresentationAdapter; readonly state: XpyStageThreeShellState; readonly title: string; readonly description: string; readonly publicProductIdentity?: string; readonly intentLabel?: string; readonly returnHref: string; readonly returnLabel: string; readonly notice?: string; readonly children?: ReactNode }) {
  return <div data-xpy-stage-three={XPY_STAGE_THREE_CONTRACT_VERSION} data-xpy-stage-three-adapter={adapter.adapterId} data-xpy-stage-three-state={state} className="min-h-[80dvh] bg-[#f4f1eb] text-stone-950">
    <header className="border-b border-white/10 bg-stone-950 text-white"><div className="mx-auto flex min-h-16 max-w-6xl flex-wrap items-center justify-between gap-3 px-5 py-3 sm:px-8"><span className="font-bold">{adapter.departmentLabel}</span><Link href={returnHref} className="inline-flex min-h-11 items-center rounded-full border border-white/25 px-4 text-sm font-semibold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-400">← {returnLabel}</Link></div></header>
    <section className="bg-[radial-gradient(circle_at_75%_15%,rgba(52,211,153,.22),transparent_35%),linear-gradient(135deg,#1c1917,#0c0a09)] text-white"><div className="mx-auto max-w-6xl px-5 py-10 sm:px-8 sm:py-14"><div className="flex flex-wrap gap-2"><span className="rounded-full border border-white/20 bg-black/25 px-3 py-1.5 text-xs">AŞAMA 3</span><span className="rounded-full border border-white/20 bg-black/25 px-3 py-1.5 text-xs">{stateLabels[state]}</span>{intentLabel ? <span className="rounded-full border border-emerald-300/40 bg-emerald-300/10 px-3 py-1.5 text-xs text-emerald-200">{intentLabel}</span> : null}</div><p className="mt-7 text-xs font-semibold uppercase tracking-[.24em] text-emerald-300">Karardan ayrı eylem alanı</p><h1 className="mt-3 max-w-4xl text-3xl font-semibold tracking-tight sm:text-5xl">{title}</h1>{publicProductIdentity ? <p className="mt-4 text-lg text-stone-200">Seçili {adapter.productNoun}: <strong className="font-semibold text-white">{publicProductIdentity}</strong></p> : null}<p className="mt-5 max-w-3xl leading-7 text-stone-300">{description}</p></div></section>
    <section aria-labelledby="stage-three-boundary-title" className="mx-auto max-w-6xl px-5 py-7 sm:px-8"><div className="rounded-3xl border border-stone-200 bg-white p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-700">Bu aşamada</p><h2 id="stage-three-boundary-title" className="mt-2 text-2xl font-semibold">Seçtiğin {adapter.productNoun} değişmez; yalnız sonraki adım hazırlanır.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-stone-600">Bu sayfa {adapter.productNoun} kararını yeniden vermez. Teklif, stok veya satış bilgisi doğrulanmadıysa işlem başlatmaz ve senden iletişim bilgisi istemez.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{adapter.capabilities.map(item => <article key={item.capability} className="rounded-2xl border border-stone-200 bg-stone-50 p-4"><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-semibold">{item.publicLabel}</h3><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-semibold ${item.state === "VERIFIED" ? "bg-emerald-100 text-emerald-900" : item.state === "INTERNAL_REVIEW_ONLY" ? "bg-amber-100 text-amber-950" : "bg-stone-200 text-stone-600"}`}>{capabilityLabel(item.state)}</span></div><p className="mt-2 text-xs leading-5 text-stone-600">{item.explanation}</p></article>)}</div>{notice ? <p role={state === "INVALID" ? "alert" : "status"} className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950">{notice}</p> : null}</div></section>
    {children ? <div className="mx-auto max-w-6xl px-5 pb-12 sm:px-8">{children}</div> : null}
  </div>;
}
