import { DEMO_BRANCHES, DEMO_ROLES } from "@/features/used-cars/demo/access";
import { PartnerDemoNav } from "./PartnerDemoNav";

export function AccessManagementDemo() {
  const role = DEMO_ROLES[0];
  return <main className="min-h-[calc(100vh-73px)] bg-stone-50"><PartnerDemoNav active="/ikinciel/partner-demo/erisim"/><div className="mx-auto max-w-5xl px-5 py-10 lg:px-8">
    <p className="text-sm font-black uppercase tracking-widest text-emerald-700">Erişim yönetimi</p><h1 className="mt-2 text-3xl font-black tracking-tight">Tek rol, açık yetki</h1><p className="mt-3 max-w-2xl text-stone-600">İlk sürümde tüm satıcı kullanıcıları yalnız “Tam yetkili” rolüyle çalışır. Yeni roller ihtiyaç oluştuğunda ayrıca tasarlanacaktır.</p>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1fr_1.2fr]"><section className="rounded-2xl border border-stone-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-black">Kullanıcı rolü</h2><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-900">TEK ROL</span></div><div className="mt-5 rounded-2xl bg-stone-50 p-5"><p className="text-xl font-black">{role.role}</p><p className="mt-2 text-sm leading-6 text-stone-600">Firma, şube, kullanıcı, stok, talepler, analitik, üyelik ve audit alanlarının tamamına erişir.</p><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-stone-500">Kapsam</dt><dd className="font-bold">Tüm firma</dd></div><div><dt className="text-stone-500">MFA</dt><dd className="font-bold">Zorunlu</dd></div></dl></div><button type="button" disabled className="mt-5 w-full cursor-not-allowed rounded-xl bg-stone-100 px-4 py-3 font-bold text-stone-500">Kullanıcı daveti · Yakında</button></section>
      <section className="rounded-2xl border border-stone-200 bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Şubeler</h2><p className="mt-1 text-sm text-stone-500">Tam yetkili rol tüm şubeleri görür.</p></div><button type="button" className="rounded-xl border border-stone-300 px-3 py-2 text-sm font-bold">+ Şube</button></div><div className="mt-5 space-y-3">{DEMO_BRANCHES.map(branch => <article key={branch.id} className="flex items-center justify-between rounded-xl border border-stone-200 p-4"><div><strong>{branch.name}</strong><p className="mt-1 text-xs text-stone-500">{branch.stock} aktif stok · {branch.users} kullanıcı</p></div><span className="h-2.5 w-2.5 rounded-full bg-emerald-500" aria-label="Aktif"/></article>)}</div></section></div>
    <div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>Güvenlik notu:</strong> Tek rol daha basit bir yönetim sağlar ancak güçlü MFA, session rotation, tenant izolasyonu ve immutable audit zorunluluğunu değiştirmez.</div>
  </div></main>;
}
