import { buildDemoAuditChain } from "@/features/used-cars/demo/audit";
import { verifyAuditChain } from "@/features/used-cars/audit/envelope";
import { PartnerDemoNav } from "./PartnerDemoNav";

const actionLabel: Record<string,string> = { INVENTORY_CREATED: "Stok kaydı oluşturuldu", PRICE_CHANGED: "Fiyat güncellendi", CHANGES_REQUESTED: "Moderasyon düzeltme istedi" };
export function AuditHistoryDemo() {
  const events = buildDemoAuditChain(); const valid = verifyAuditChain(events);
  return <main className="min-h-[calc(100vh-73px)] bg-[#f3f3ef]"><PartnerDemoNav active="/ikinciel/partner-demo/audit"/><div className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-widest text-emerald-700">Append-only demo geçmişi</p><h1 className="mt-2 text-4xl font-black tracking-tight">İşlem ve değişiklik zinciri</h1><p className="mt-2 text-stone-600">Kim, hangi tenant bağlamında, neyi ve hangi gerekçeyle değiştirdi?</p></div><span className={`rounded-full px-4 py-2 text-xs font-black ${valid ? "bg-emerald-100 text-emerald-900" : "bg-red-100 text-red-900"}`}>{valid ? "HASH ZİNCİRİ TUTARLI" : "ZİNCİR HATASI"}</span></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_330px]"><section className="overflow-hidden rounded-3xl border border-stone-200 bg-white">{[...events].reverse().map(event => <article key={event.eventId} className="grid gap-4 border-b border-stone-100 p-6 last:border-0 sm:grid-cols-[55px_1fr_auto]"><div className="grid h-11 w-11 place-items-center rounded-full bg-stone-950 font-black text-white">{event.sequence}</div><div><h2 className="font-black">{actionLabel[event.action] ?? event.action}</h2><p className="mt-1 text-sm text-stone-600">{event.subjectType} · {event.subjectId}</p><p className="mt-2 text-xs text-stone-500">Aktör: {event.actorId} ({event.actorType}) · {event.reasonCode}</p><p className="mt-2 truncate font-mono text-[10px] text-stone-400">{event.eventHash}</p></div><time className="text-xs font-bold text-stone-500">{new Date(event.occurredAt).toLocaleString("tr-TR", { timeZone: "Europe/Istanbul" })}</time></article>)}</section>
      <aside className="space-y-5"><div className="rounded-3xl bg-stone-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-widest text-emerald-300">Zincir modeli</p><p className="mt-3 text-sm leading-6 text-stone-300">Her olay önceki olayın hash’ini taşır. Geçmişteki bir olay sessizce değiştirilirse doğrulama başarısız olur.</p></div><div className="rounded-3xl border border-stone-200 bg-white p-6"><h2 className="font-black">Kapsanan değişiklikler</h2><ul className="mt-4 space-y-2 text-sm text-stone-600"><li>• Fiyat ve stok durumu</li><li>• Yayın/moderasyon kararları</li><li>• Rol ve yetki değişiklikleri</li><li>• PII erişimi ve dışa aktarım</li><li>• Tenant kapatma olayları</li></ul></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-xs leading-5 text-amber-950">Audit kaydı uygulama loguna VIN, plaka, telefon veya belge içeriği yazmaz; kimlikler opaque ID olarak tutulur.</div></aside></div></div></main>;
}
