"use client";

import { useState } from "react";
import { DEMO_CLASSIC_CLAIMS } from "@/features/used-cars/demo/classic";
import { PartnerDemoNav } from "./PartnerDemoNav";

const claimLabel = { ORIGINAL: "Orijinal", MATCHING_NUMBERS: "Matching numbers", COLLECTIBLE: "Koleksiyonluk", PERIOD_CORRECT: "Dönem doğruluğu" } as const;
export function ClassicVehicleDemo() {
  const [section,setSection] = useState<"identity"|"history"|"claims">("identity");
  return <main className="min-h-[calc(100vh-73px)] bg-[#f3f3ef]"><PartnerDemoNav active="/ikinciel/partner-demo/klasik-arac"/><div className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><div><p className="text-sm font-black uppercase tracking-widest text-amber-700">Ayrı klasik araç profili</p><h1 className="mt-2 text-4xl font-black tracking-tight">Yaşlı araç değil, tarihsel nesne.</h1><p className="mt-3 max-w-3xl text-stone-600">Üretim dönemi, şasi serisi, restorasyon, dönem doğruluğu ve arşiv kanıtları normal ikinci el kaydından ayrı değerlendirilir.</p></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[240px_1fr]"><aside className="h-fit rounded-3xl bg-stone-950 p-4 text-white">{[["identity","Kimlik ve dönem"],["history","Restorasyon ve geçmiş"],["claims","Yüksek riskli iddialar"]].map(([key,label]) => <button key={key} type="button" onClick={() => setSection(key as typeof section)} className={`mb-2 w-full rounded-xl px-4 py-3 text-left text-sm font-black ${section===key ? "bg-amber-300 text-amber-950" : "text-stone-300"}`}>{label}</button>)}<p className="mt-6 px-4 text-xs leading-5 text-stone-400">Her bölüm uzman incelemesi gereksinimini ayrıca taşır.</p></aside><section className="rounded-3xl border border-stone-200 bg-white p-6 sm:p-8">{section === "identity" && <div><h2 className="text-2xl font-black">Kimlik ve üretim dönemi</h2><div className="mt-6 grid gap-5 sm:grid-cols-2">{[["Tahmini üretim dönemi","1972–1974"],["Şasi/kasa serisi","Seri C · satıcı beyanı"],["Pazar/ithalat","TR · özel ithalat beyanı"],["Tescil durumu","Belge yüklendi, doğrulanmadı"]].map(([label,value]) => <label key={label} className="text-sm font-bold">{label}<input value={value} readOnly className="mt-2 w-full rounded-xl border border-stone-300 bg-stone-50 px-4 py-3 font-normal"/></label>)}</div></div>}
      {section === "history" && <div><h2 className="text-2xl font-black">Restorasyon ve kullanım geçmişi</h2><div className="mt-6 space-y-3">{[["Restorasyon durumu","Tam restorasyon · satıcı beyanı"],["Motor/şanzıman değişikliği","Motor kodu inceleme bekliyor"],["Koleksiyon geçmişi","2 önceki koleksiyon beyanı"],["Arşiv kayıtları","3 doküman yüklendi"],["Parça bulunabilirliği","Uzman değerlendirmesi yok"],["Saklama koşulları","Kapalı garaj · satıcı beyanı"]].map(([name,value]) => <div key={name} className="flex flex-wrap justify-between gap-3 rounded-2xl border border-stone-200 p-4"><strong>{name}</strong><span className="text-sm text-stone-600">{value}</span></div>)}</div></div>}
      {section === "claims" && <div><h2 className="text-2xl font-black">Public iddia sınırları</h2><p className="mt-2 text-sm text-stone-600">Uzman ve arşiv kanıtı yoksa iddia doğrulanmış gösterilemez.</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{DEMO_CLASSIC_CLAIMS.map(item => <article key={item.claim} className={`rounded-2xl border p-5 ${item.display === "HIDDEN" ? "border-red-200 bg-red-50" : "border-amber-200 bg-amber-50"}`}><h3 className="font-black">{claimLabel[item.claim]}</h3><span className={`mt-3 inline-block rounded-full px-3 py-1 text-xs font-black ${item.display === "HIDDEN" ? "bg-red-200 text-red-950" : "bg-amber-200 text-amber-950"}`}>{item.display === "HIDDEN" ? "Public alanda gizli" : "Yalnız satıcı beyanı"}</span><p className="mt-3 text-xs text-stone-600">Uzman incelemesi zorunlu · satın alma talimatı verilemez</p></article>)}</div></div>}
    </section></div><div className="mt-6 rounded-2xl bg-amber-100 p-5 text-sm leading-6 text-amber-950"><strong>Güvenlik notu:</strong> “Orijinal”, “matching numbers”, “koleksiyonluk” ve “dönem doğru” ifadeleri canonical araç kimliğinin parçası değildir; kanıt kapsamı ve uzman incelemesiyle ayrı iddia olarak yönetilir.</div></div></main>;
}
