"use client";

import { useState } from "react";
import { DEMO_IMPORT_ROWS, summarizeDemoImport } from "@/features/used-cars/demo/import";
import { PartnerDemoNav } from "./PartnerDemoNav";

export function ImportDryRunDemo() {
  const [ran, setRan] = useState(false);
  const summary = summarizeDemoImport(DEMO_IMPORT_ROWS);
  return <main className="min-h-[calc(100vh-73px)] bg-[#f3f3ef]"><PartnerDemoNav active="/ikinciel/partner-demo/import"/><div className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><div><p className="text-sm font-black uppercase tracking-widest text-emerald-700">Toplu stok aktarımı</p><h1 className="mt-2 text-4xl font-black tracking-tight">Önce doğrula, sonra yetkilendir.</h1><p className="mt-3 max-w-3xl text-stone-600">Dosya yüklemek hiçbir stok kaydı oluşturmaz. Dry-run tenant, taxonomy, şema, VIN tekrarı ve satır bütünlüğünü raporlar.</p></div>
    {!ran ? <section className="mt-8 rounded-3xl border-2 border-dashed border-stone-300 bg-white p-10 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-emerald-100 text-2xl">⇧</div><h2 className="mt-5 text-2xl font-black">Demo stok şablonu</h2><p className="mt-2 text-sm text-stone-600">CSV/XLSX temsili · 4 sentetik satır · dosya gerçekten yüklenmez</p><button type="button" onClick={() => setRan(true)} className="mt-6 rounded-xl bg-emerald-900 px-6 py-4 font-black text-white">Sentetik dry-run çalıştır</button><div className="mx-auto mt-6 max-w-xl rounded-xl bg-stone-100 p-4 text-left font-mono text-xs text-stone-600">Idempotency-Key: demo-import-20260901-001<br/>Tenant: demo-tenant-marmara<br/>Mode: VALIDATE_ONLY · WRITE=false</div></section> : <section className="mt-8"><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-emerald-950 p-5 text-white"><span className="text-xs text-emerald-200">Kabul edilen</span><strong className="mt-2 block text-3xl">{summary.accepted}</strong></div><div className="rounded-2xl bg-red-950 p-5 text-white"><span className="text-xs text-red-200">Reddedilen/tekrar</span><strong className="mt-2 block text-3xl">{summary.rejected}</strong></div><div className="rounded-2xl bg-amber-200 p-5 text-amber-950"><span className="text-xs">Veri yazma yetkisi</span><strong className="mt-2 block text-3xl">KAPALI</strong></div></div>
      <div className="mt-5 overflow-hidden rounded-3xl border border-stone-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-stone-100 text-xs uppercase tracking-wider text-stone-500"><tr><th className="px-5 py-3">Satır</th><th className="px-5 py-3">Stok</th><th className="px-5 py-3">Taxonomy ID</th><th className="px-5 py-3">VIN</th><th className="px-5 py-3">Sonuç</th><th className="px-5 py-3">Mesaj</th></tr></thead><tbody>{DEMO_IMPORT_ROWS.map(row => <tr key={row.row} className="border-t border-stone-100"><td className="px-5 py-4">{row.row}</td><td className="px-5 py-4 font-bold">{row.stockNumber}</td><td className="px-5 py-4 font-mono text-xs">{row.taxonomyId}</td><td className="px-5 py-4 font-mono text-xs">{row.vinMasked}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-black ${row.status === "ACCEPTED" ? "bg-emerald-100 text-emerald-900" : "bg-red-100 text-red-900"}`}>{row.status}</span></td><td className="px-5 py-4 text-xs text-red-700">{row.messages.join(" · ") || "—"}</td></tr>)}</tbody></table></div></div>
      <div className="mt-5 flex flex-wrap justify-between gap-3"><button type="button" onClick={() => setRan(false)} className="rounded-xl border border-stone-300 px-5 py-3 font-bold">Başa dön</button><button disabled type="button" className="cursor-not-allowed rounded-xl bg-stone-300 px-5 py-3 font-black text-stone-600">Yazmayı yetkilendir — demo kapalı</button></div></section>}
    <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>İzolasyon:</strong> Her satır aktif tenant ile doğrulanır. Başka tenant kimliği taşıyan satır reddedilir; kısmi veya sessiz cross-tenant write yapılmaz.</div></div></main>;
}

