import { DEMO_MEMBERSHIP_PLANS } from "@/features/used-cars/demo/plans";
import { PartnerDemoNav } from "./PartnerDemoNav";

export function MembershipDemo() {
  return <main className="min-h-[calc(100vh-73px)] bg-[#f3f3ef]"><PartnerDemoNav active="/ikinciel/partner-demo/uyelik"/><div className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><div><p className="text-sm font-black uppercase tracking-widest text-emerald-700">Ticari model demosu</p><h1 className="mt-2 text-4xl font-black tracking-tight">Kapasite satın alınır, karar değil.</h1><p className="mt-3 max-w-3xl text-stone-600">Paketler operasyon kapasitesini ve araçları yönetme araçlarını belirler. Organik eşleştirme puanına hiçbir ticari alan girmez.</p></div>
    <div className="mt-8 grid gap-5 lg:grid-cols-3">{DEMO_MEMBERSHIP_PLANS.map((plan,index) => <article key={plan.code} className={`rounded-3xl border bg-white p-6 ${index === 1 ? "border-emerald-700 ring-4 ring-emerald-100" : "border-stone-200"}`}><div className="flex items-center justify-between"><span className="text-xs font-black uppercase tracking-widest text-stone-500">{plan.code}</span>{index === 1 && <span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-900">Demo aktif paket</span>}</div><h2 className="mt-4 text-2xl font-black">{plan.name}</h2><p className="mt-2 min-h-12 text-sm text-stone-600">{plan.audience}</p><ul className="mt-6 space-y-3 text-sm"><li><strong>{plan.stockLimit === "CUSTOM" ? "Özel" : plan.stockLimit}</strong> aktif stok</li><li><strong>{plan.branchLimit === "CUSTOM" ? "Özel" : plan.branchLimit}</strong> şube</li><li>{plan.analytics === "ADVANCED" ? "Gelişmiş" : "Temel"} analitik</li><li>{plan.feedIntegration ? "✓ API/feed entegrasyonu" : "— Manuel stok yönetimi"}</li></ul><button type="button" className="mt-7 w-full rounded-xl border border-stone-300 px-4 py-3 font-black">Teklifi incele (demo)</button></article>)}</div>
    <div className="mt-7 grid gap-4 md:grid-cols-2"><div className="rounded-3xl bg-emerald-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-widest text-emerald-300">Organik sonuç sözleşmesi</p><h2 className="mt-2 text-xl font-black">Yasak ticari alanlar</h2><p className="mt-3 text-sm leading-6 text-emerald-100">Plan kodu, aylık ücret, tenant kimliği ve sponsorlu kampanya kimliği organik ranking girdisine kabul edilmez.</p></div><div className="rounded-3xl bg-stone-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-widest text-amber-300">Sponsorlu alan</p><h2 className="mt-2 text-xl font-black">Ayrı akış, zorunlu etiket</h2><p className="mt-3 text-sm leading-6 text-stone-300">Sponsorlu vitrin ileride açılırsa organik listeye karışmaz ve her yerleşim “Sponsorlu” etiketi taşır.</p></div></div>
    <p className="mt-6 text-xs text-stone-500">Fiyatlar ve ödeme bu tasarım prototipinde bilinçli olarak etkin değildir; gerçek tahsilat yapılmaz.</p></div></main>;
}
