import { PartnerDemoNav } from "./PartnerDemoNav";

export function ModerationDemo() {
  return <main className="min-h-[calc(100vh-73px)] bg-[#f3f3ef]"><PartnerDemoNav active="/ikinciel/partner-demo/moderasyon"/><div className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-widest text-purple-700">Expiya moderatörü · sentetik görev</p><h1 className="mt-2 text-4xl font-black tracking-tight">İlan revizyonu MOD-2084</h1><p className="mt-2 text-stone-600">Atanmış moderatör görünümü; tenant operasyon ekranından ayrı yetki alanı.</p></div><span className="rounded-full bg-sky-100 px-4 py-2 text-sm font-black text-sky-900">İncelemede</span></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="space-y-5"><article className="rounded-3xl border border-stone-200 bg-white p-6"><p className="text-xs font-black uppercase tracking-widest text-stone-500">Araç kimliği</p><h2 className="mt-2 text-2xl font-black">Toyota C-HR · AX10</h2><p className="mt-1 text-stone-600">1.8 Hybrid · Passion · MY2021 · taxonomy tr-2026.09</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Kilometre","48.200 km"],["Fiyat","1.575.000 ₺"],["Şube","İstanbul"],["Revizyon","rev-0007"]].map(([k,v]) => <div key={k} className="rounded-xl bg-stone-100 p-3"><span className="block text-xs text-stone-500">{k}</span><strong className="mt-1 block text-sm">{v}</strong></div>)}</div></article>
      <article className="rounded-3xl border border-stone-200 bg-white p-6"><h2 className="text-xl font-black">Kanıt ve beyan matrisi</h2><div className="mt-5 space-y-3">{[["Kilometre","Satıcı beyanı","Belge yüklendi · içerik doğrulanmadı","amber"],["Bakım geçmişi","Satıcı beyanı","3 servis belgesi · doğrulama bekliyor","amber"],["Ağır hasar","Satıcı beyanı: yok","Bağımsız kaynak yok","red"],["Araç kimliği","Taxonomy kaydı","Expiya tarafından doğrulandı","green"]].map(([field,claim,evidence,color]) => <div key={field} className="grid gap-2 rounded-2xl border border-stone-200 p-4 sm:grid-cols-[140px_1fr_1.3fr]"><strong>{field}</strong><span className="text-sm text-stone-600">{claim}</span><span className={`text-sm font-bold ${color === "green" ? "text-emerald-700" : color === "red" ? "text-red-700" : "text-amber-700"}`}>{evidence}</span></div>)}</div></article>
    </section><aside className="space-y-5"><div className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><p className="text-xs font-black uppercase tracking-widest text-amber-800">Otomatik kontroller</p><ul className="mt-4 space-y-3 text-sm"><li>✓ Duplicate VIN sinyali yok</li><li>✓ Görsel malware taraması geçti</li><li>✓ VIN/plaka public projection’da maskeli</li><li className="font-bold text-amber-900">● Bakım belgesi içeriği bekliyor</li></ul></div><div className="rounded-3xl border border-stone-200 bg-white p-6"><h2 className="font-black">Karar</h2><label className="mt-4 block text-sm font-bold">Reason code<select className="mt-2 w-full rounded-xl border border-stone-300 bg-white px-3 py-3"><option>DOCUMENT_VERIFICATION_REQUIRED</option><option>CHANGES_REQUESTED</option><option>APPROVED</option></select></label><textarea aria-label="Moderatör notu" placeholder="Audit kaydına girecek gerekçeyi yazın" className="mt-4 min-h-28 w-full rounded-xl border border-stone-300 p-3 text-sm"/><button type="button" className="mt-3 w-full rounded-xl bg-emerald-900 px-4 py-3 font-black text-white">Kararı kaydet (demo)</button><p className="mt-3 text-xs leading-5 text-stone-500">İtiraz halinde ikinci incelemeyi ilk kararı veren moderatör yapamaz.</p></div></aside></div></div></main>;
}

