import { DEMO_ANALYTICS_CONTRACT, DEMO_DEMAND_BUCKETS, DEMO_FUNNEL } from "@/features/used-cars/demo/analytics";
import { PartnerDemoNav } from "./PartnerDemoNav";

export function PartnerAnalyticsDemo() {
  const funnel = [["Organik gösterim",DEMO_FUNNEL.organicImpressions],["Detay açılışı",DEMO_FUNNEL.detailOpens],["Rızalı talep",DEMO_FUNNEL.consentedLeads],["İletişim kuruldu",DEMO_FUNNEL.contacted]] as const;
  return <main className="min-h-[calc(100vh-73px)] bg-[#f3f3ef]"><PartnerDemoNav active="/ikinciel/partner-demo/analitik"/><div className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-widest text-emerald-700">Toplulaştırılmış demo metrikleri</p><h1 className="mt-2 text-4xl font-black tracking-tight">Stok ve talep uyumu</h1><p className="mt-2 max-w-3xl text-stone-600">Kullanıcı kimliği değil, ihtiyaç kümeleri görünür. Küçük kohortlar ve hassas tercihler satıcıya açılmaz.</p></div><span className="rounded-full bg-emerald-100 px-4 py-2 text-xs font-black text-emerald-900">PII YOK · ORGANİK AKIŞ</span></div>
    <div className="mt-8 grid gap-4 md:grid-cols-4">{funnel.map(([label,value],index) => <div key={label} className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-xs font-bold text-stone-500">{label}</p><p className="mt-2 text-3xl font-black">{value.toLocaleString("tr-TR")}</p>{index>0 && <p className="mt-2 text-xs text-emerald-700">Önceki adıma göre %{Math.round(value/funnel[index-1][1]*100)}</p>}</div>)}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-3xl border border-stone-200 bg-white p-6"><h2 className="text-xl font-black">İhtiyaç kümeleri</h2><p className="mt-1 text-sm text-stone-500">Endeks: 0–100 · gerçek piyasa veya fiyat tahmini değildir</p><div className="mt-6 space-y-6">{DEMO_DEMAND_BUCKETS.map(bucket => <div key={bucket.label}><div className="flex justify-between text-sm"><strong>{bucket.label}</strong><span className="text-stone-500">Talep {bucket.demand} · Stok {bucket.stock}</span></div><div className="mt-2 space-y-1"><div className="h-3 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-emerald-700" style={{width:`${bucket.demand}%`}}/></div><div className="h-3 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-stone-400" style={{width:`${bucket.stock}%`}}/></div></div></div>)}</div><div className="mt-5 flex gap-5 text-xs"><span><i className="mr-2 inline-block h-2 w-4 bg-emerald-700"/>Talep</span><span><i className="mr-2 inline-block h-2 w-4 bg-stone-400"/>Aktif stok</span></div></section>
      <aside className="space-y-5"><div className="rounded-3xl bg-emerald-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-widest text-emerald-300">Okunabilir içgörü</p><h2 className="mt-3 text-2xl font-black">Hibrit SUV açığı</h2><p className="mt-3 text-sm leading-6 text-emerald-100">Demo ihtiyaç kümesinde talep endeksi stok endeksinden 59 puan yüksek. Bu bilgi araç sıralamasını veya fiyatı değiştirmez.</p></div><div className="rounded-3xl border border-stone-200 bg-white p-6"><p className="text-xs font-black uppercase tracking-widest text-stone-500">Event sözleşmesi</p><dl className="mt-4 space-y-3 text-sm">{Object.entries(DEMO_ANALYTICS_CONTRACT).map(([key,value]) => <div key={key} className="flex justify-between gap-4"><dt className="text-stone-500">{key}</dt><dd className="font-mono font-bold">{String(value)}</dd></div>)}</dl></div></aside></div></div></main>;
}
