import Link from "next/link";
import { PartnerDemoNav } from "./PartnerDemoNav";

const stock = [
  ["Demo C-HR", "STK-1042", "Moderasyonda", "1.575.000 ₺"],
  ["Demo Clio", "STK-1038", "Yayında", "1.080.000 ₺"],
  ["Demo Egea", "STK-1029", "Bilgi bekliyor", "995.000 ₺"],
] as const;

export function PartnerDashboardDemo() {
  return <main className="min-h-screen bg-stone-50"><PartnerDemoNav active="/ikinciel/partner-demo"/><div className="mx-auto max-w-7xl px-5 py-8 lg:px-8">
    <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-950"><strong>Sentetik taslak:</strong> Gerçek firma, stok, e-posta veya ödeme işlemi içermez.</div>
    <header className="mt-8 flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-bold text-stone-500">Demo Marmara Mobilite · İstanbul Merkez</p><h1 className="mt-1 text-3xl font-black tracking-tight">Günaydın, stok durumunuz burada.</h1></div><div className="flex gap-2"><Link href="/ikinciel/partner-demo/talepler" className="rounded-xl border border-stone-300 bg-white px-4 py-3 text-sm font-bold">Talepleri gör</Link><Link href="/ikinciel/partner-demo/stok/yeni" className="rounded-xl bg-emerald-950 px-4 py-3 text-sm font-black text-white">+ Araç ekle</Link></div></header>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4" aria-label="Operasyon özeti">{[["Aktif ilan","28","50 kapasite"],["Yeni talep","5","14 açık talep"],["Moderasyonda","3","1 belge bekliyor"],["Ortalama yanıt","42 dk","Hedef 60 dk"]].map(([label,value,note]) => <article key={label} className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-sm font-bold text-stone-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p><p className="mt-2 text-xs text-emerald-700">{note}</p></article>)}</section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.55fr_.85fr]"><section className="overflow-hidden rounded-2xl border border-stone-200 bg-white"><div className="flex items-center justify-between border-b border-stone-200 px-5 py-4"><div><h2 className="font-black">Güncel stok</h2><p className="mt-1 text-xs text-stone-500">Öncelikli üç kayıt</p></div><Link href="/ikinciel/partner-demo/hazirlik" className="text-sm font-bold text-emerald-800">Tümünü gör →</Link></div><div className="divide-y divide-stone-100">{stock.map(([car,id,status,price]) => <article key={id} className="grid gap-3 px-5 py-4 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="font-bold">{car}</p><p className="text-xs text-stone-500">{id}</p></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-bold ${status === "Yayında" ? "bg-emerald-100 text-emerald-900" : status === "Moderasyonda" ? "bg-sky-100 text-sky-900" : "bg-amber-100 text-amber-900"}`}>{status}</span><p className="font-black">{price}</p></article>)}</div></section>
      <aside className="space-y-5"><section className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-widest text-emerald-700">Haftalık stok e-postası</p><h2 className="mt-2 text-xl font-black">Her pazartesi 09.00</h2><p className="mt-2 text-sm leading-6 text-stone-600">Aktif, taslak, moderasyondaki ve eskiyen stokların özeti tam yetkili kullanıcılara gönderilir.</p><div className="mt-4 flex items-center justify-between rounded-xl bg-stone-50 px-4 py-3 text-sm"><span>Sonraki rapor</span><strong>7 Eylül Pazartesi</strong></div><p className="mt-3 text-xs text-amber-700">Demo modunda e-posta gönderimi kapalıdır.</p></section><section className="rounded-2xl bg-emerald-950 p-5 text-white"><p className="text-xs font-black uppercase tracking-widest text-emerald-300">Yapılacaklar</p><ul className="mt-4 space-y-3 text-sm"><li className="flex justify-between gap-3"><span>Belge bekleyen araç</span><strong>1</strong></li><li className="flex justify-between gap-3"><span>Yanıt bekleyen talep</span><strong>5</strong></li><li className="flex justify-between gap-3"><span>7+ gündür güncellenmeyen</span><strong>2</strong></li></ul></section></aside>
    </div>
    <section className="mt-6 rounded-2xl border border-stone-200 bg-white p-5"><h2 className="font-black">Hızlı işlemler</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Yeni araç ekle","/ikinciel/partner-demo/stok/yeni"],["Toplu stok aktar","/ikinciel/partner-demo/import"],["Üyeliği görüntüle","/ikinciel/partner-demo/uyelik"],["Firma ve erişim","/ikinciel/partner-demo/erisim"]].map(([label,href]) => <Link key={href} href={href} className="rounded-xl border border-stone-200 px-4 py-4 text-sm font-bold hover:border-emerald-700 hover:bg-emerald-50">{label} →</Link>)}</div></section>
  </div></main>;
}
