import { DEMO_LEADS } from "@/features/used-cars/demo/leads";
import { PartnerDemoNav } from "./PartnerDemoNav";

const purpose = { CONTACT: "İletişim", TEST_DRIVE: "Test sürüşü", PRICE_QUOTE: "Fiyat teklifi" } as const;
export function PartnerLeadsDemo() {
  return <main className="min-h-[calc(100vh-73px)] bg-[#f3f3ef]"><PartnerDemoNav active="/ikinciel/partner-demo/talepler"/><div className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-widest text-emerald-700">Sentetik lead kasası</p><h1 className="mt-2 text-4xl font-black tracking-tight">Kullanıcı talepleri</h1><p className="mt-2 text-stone-600">PII varsayılan olarak maskeli; yalnız yetkili satış danışmanı amaç ve süre sınırıyla açabilir.</p></div><span className="rounded-full bg-red-100 px-4 py-2 text-xs font-black text-red-900">DIŞA AKTARIM KAPALI</span></div>
    <div className="mt-8 grid gap-5">{DEMO_LEADS.map(lead => <article key={lead.id} className="grid gap-5 rounded-3xl border border-stone-200 bg-white p-6 md:grid-cols-[1fr_1fr_auto] md:items-center"><div><div className="flex gap-2"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-900">{purpose[lead.purpose]}</span><span className={`rounded-full px-3 py-1 text-xs font-black ${lead.status === "NEW" ? "bg-sky-100 text-sky-900" : "bg-stone-100 text-stone-700"}`}>{lead.status === "NEW" ? "Yeni" : "İletişim kuruldu"}</span></div><h2 className="mt-3 text-lg font-black">{lead.vehicle}</h2><p className="mt-1 text-xs text-stone-500">{lead.id} · {lead.createdAt}</p></div><div><p className="font-black">{lead.customerMasked}</p><p className="mt-1 font-mono text-sm text-stone-600">{lead.phoneMasked}</p><p className="mt-2 text-xs text-stone-500">Rıza kapsamı: {lead.consentScope}</p></div><button type="button" className="rounded-xl border border-stone-300 px-4 py-3 text-sm font-black">Yetkiyle görüntüle</button></article>)}</div>
    <div className="mt-6 grid gap-4 md:grid-cols-3">{[["Amaç sınırlaması","Talep verisi başka stok veya pazarlama amacıyla kullanılamaz."],["Süre sınırlaması","Erişim grant’i kısa ömürlüdür; her görüntüleme audit edilir."],["Silme ve kapatma","Talep kapanınca retention politikasıyla maskelenir veya silinir."]].map(([title,body]) => <div key={title} className="rounded-2xl bg-stone-950 p-5 text-white"><strong>{title}</strong><p className="mt-2 text-sm leading-6 text-stone-300">{body}</p></div>)}</div></div></main>;
}

