"use client";

import { useState } from "react";
import { DEMO_TAXONOMY_PATHS } from "@/features/used-cars/demo/taxonomy";
import { PartnerDemoNav } from "./PartnerDemoNav";

const steps = ["Araç kimliği", "Somut araç", "Durum ve geçmiş", "Medya ve belgeler", "Ön kontrol"];

export function StockCreateDemo() {
  const [step, setStep] = useState(0);
  const [pathId, setPathId] = useState(DEMO_TAXONOMY_PATHS[0].model.id);
  const selected = DEMO_TAXONOMY_PATHS.find(item => item.model.id === pathId) ?? DEMO_TAXONOMY_PATHS[0];
  return <main className="min-h-[calc(100vh-73px)] bg-[#f3f3ef]"><PartnerDemoNav active="/ikinciel/partner-demo/stok/yeni"/><div className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><div><p className="text-sm font-black uppercase tracking-widest text-emerald-700">Sentetik stok kaydı</p><h1 className="mt-2 text-4xl font-black tracking-tight">Yeni araç oluştur</h1><p className="mt-2 text-stone-600">Canonical araç adı serbest metinle oluşturulamaz.</p></div>
    <ol className="mt-8 grid gap-2 md:grid-cols-5">{steps.map((item,index) => <li key={item} className={`rounded-xl px-3 py-3 text-xs font-black ${index === step ? "bg-emerald-950 text-white" : index < step ? "bg-emerald-100 text-emerald-900" : "bg-white text-stone-500"}`}>{index+1}. {item}</li>)}</ol>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_300px]"><section className="rounded-3xl border border-stone-200 bg-white p-6 sm:p-8">
      {step === 0 && <div><h2 className="text-2xl font-black">Yönetilen araç kimliğini seçin</h2><p className="mt-2 text-sm text-stone-600">Marka, model, nesil, motor ve donanım tek sürümlü taxonomy yolundan gelir.</p><div className="mt-6 grid gap-3">{DEMO_TAXONOMY_PATHS.map(path => <button key={path.model.id} type="button" onClick={() => setPathId(path.model.id)} className={`rounded-2xl border p-5 text-left ${pathId === path.model.id ? "border-emerald-800 bg-emerald-50" : "border-stone-200"}`}><strong className="text-lg">{path.make.label} {path.model.label}</strong><span className="mt-1 block text-sm text-stone-600">{path.generation.label} · {path.powertrain.label} · {path.trim.label}</span><span className="mt-3 inline-block rounded-full bg-white px-3 py-1 text-xs font-bold">{path.version} · güven: {path.confidence}</span></button>)}</div><button type="button" className="mt-5 text-sm font-black text-emerald-800">Aracımı bulamadım → yeni kimlik talebi oluştur</button></div>}
      {step === 1 && <div><h2 className="text-2xl font-black">Somut araca ait bilgiler</h2><div className="mt-6 grid gap-5 sm:grid-cols-2">{[["Model yılı","2021"],["İlk tescil","12.04.2021"],["Kilometre","48.200"],["Renk","Füme"],["Stok numarası","STK-1042"],["Fiyat","1.575.000 ₺"]].map(([label,value]) => <label key={label} className="text-sm font-bold">{label}<input value={value} readOnly className="mt-2 w-full rounded-xl border border-stone-300 bg-stone-50 px-4 py-3 font-normal"/></label>)}</div><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">VIN — public gösterilmez<input value="NMTKZ3BX••••1042" readOnly className="mt-2 w-full rounded-xl border border-stone-300 bg-stone-50 px-4 py-3 font-mono font-normal"/></label><label className="text-sm font-bold">Plaka — public gösterilmez<input value="34 DEM ••" readOnly className="mt-2 w-full rounded-xl border border-stone-300 bg-stone-50 px-4 py-3 font-normal"/></label></div></div>}
      {step === 2 && <div><h2 className="text-2xl font-black">Durum ve geçmiş beyanları</h2><div className="mt-6 space-y-3">{[["Ağır hasar kaydı","Satıcı beyanı: yok"],["Boya / değişen","Satıcı beyanı: 1 boyalı"],["Bakım geçmişi","Belge yüklenecek"],["Garanti","6 ay satıcı garantisi"]].map(([name,value]) => <div key={name} className="flex flex-wrap justify-between gap-3 rounded-2xl border border-stone-200 p-4"><strong>{name}</strong><span className="text-sm text-stone-600">{value}</span></div>)}</div><div className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-950">Bu beyanlar otomatik olarak “doğrulanmış” statüsüne geçmez.</div></div>}
      {step === 3 && <div><h2 className="text-2xl font-black">Medya ve belgeler</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border-2 border-dashed border-stone-300 p-8 text-center"><strong>Fotoğraflar</strong><p className="mt-2 text-xs text-stone-500">MIME, boyut, malware ve EXIF/PII kontrolü</p></div><div className="rounded-2xl border-2 border-dashed border-stone-300 p-8 text-center"><strong>Belgeler</strong><p className="mt-2 text-xs text-stone-500">Yüklenmesi içeriğin doğrulandığı anlamına gelmez</p></div></div></div>}
      {step === 4 && <div><h2 className="text-2xl font-black">Yayına gönderme ön kontrolü</h2><div className="mt-6 space-y-3">{[["Taxonomy kimliği","Hazır",true],["Kritik araç alanları","Hazır",true],["Medya malware taraması","Demo bekliyor",false],["Firma yayın kapıları","Kimlik incelemesinde",false]].map(([name,value,ok]) => <div key={String(name)} className="flex justify-between rounded-2xl border border-stone-200 p-4"><strong>{name}</strong><span className={`text-sm font-black ${ok ? "text-emerald-700" : "text-amber-800"}`}>{value}</span></div>)}</div><button disabled className="mt-6 w-full cursor-not-allowed rounded-xl bg-stone-300 px-5 py-4 font-black text-stone-600">Moderasyona gönder — kapılar tamamlanmadı</button></div>}
      <div className="mt-8 flex justify-between border-t border-stone-200 pt-5"><button type="button" disabled={step === 0} onClick={() => setStep(value => value-1)} className="rounded-xl border border-stone-300 px-5 py-3 font-bold disabled:opacity-30">Geri</button>{step < steps.length-1 && <button type="button" onClick={() => setStep(value => value+1)} className="rounded-xl bg-emerald-900 px-5 py-3 font-bold text-white">Devam</button>}</div>
    </section><aside className="h-fit rounded-3xl bg-stone-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-widest text-stone-400">Canonical seçim</p><h2 className="mt-3 text-xl font-black">{selected.make.label} {selected.model.label}</h2><p className="mt-2 text-sm text-stone-300">{selected.generation.label}<br/>{selected.powertrain.label}<br/>{selected.trim.label}</p><div className="mt-6 border-t border-white/10 pt-5 text-xs leading-6 text-stone-400">Stable ID: {selected.model.id}<br/>Taxonomy: {selected.version}<br/>Public VIN/plaka: maskeli</div></aside></div></div></main>;
}
