import { DEMO_IDENTITY_REQUEST } from "@/features/used-cars/demo/taxonomyRequest";
import { PartnerDemoNav } from "./PartnerDemoNav";

export function TaxonomyRequestDemo() {
  return <main className="min-h-[calc(100vh-73px)] bg-[#f3f3ef]"><PartnerDemoNav active="/ikinciel/partner-demo/taxonomy-talebi"/><div className="mx-auto max-w-5xl px-5 py-10 lg:px-8"><div><p className="text-sm font-black uppercase tracking-widest text-emerald-700">Yönetilen index yönetişimi</p><h1 className="mt-2 text-4xl font-black tracking-tight">Yeni araç kimliği talebi</h1><p className="mt-3 max-w-3xl text-stone-600">Satıcı aracı tarif edebilir ve kanıt sunabilir; marka/model/nesil için canonical kayıt oluşturamaz.</p></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="rounded-3xl border border-stone-200 bg-white p-6 sm:p-8"><h2 className="text-xl font-black">Talep {DEMO_IDENTITY_REQUEST.id}</h2><div className="mt-6 grid gap-5 sm:grid-cols-2">{[["Satıcının kullandığı ad",DEMO_IDENTITY_REQUEST.sellerSuppliedLabel],["Tahmini dönem",DEMO_IDENTITY_REQUEST.approximatePeriod],["Pazar",DEMO_IDENTITY_REQUEST.market],["İnceleme durumu","Kanıt incelemesinde"]].map(([label,value]) => <div key={label} className="rounded-2xl bg-stone-100 p-4"><span className="text-xs font-bold text-stone-500">{label}</span><strong className="mt-1 block">{value}</strong></div>)}</div><h3 className="mt-7 font-black">Eklenen kanıt türleri</h3><div className="mt-3 flex flex-wrap gap-2">{DEMO_IDENTITY_REQUEST.evidenceTypes.map(item => <span key={item} className="rounded-full bg-sky-100 px-3 py-2 text-xs font-bold text-sky-900">{item}</span>)}</div><div className="mt-7 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950">Yüklenen materyaller canonical kimliğin doğruluğunu otomatik kanıtlamaz. Kaynak lisansı, pazar uygunluğu ve çelişkiler moderasyon tarafından incelenir.</div></section>
      <aside className="space-y-5"><div className="rounded-3xl bg-emerald-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-widest text-emerald-300">Çözüm yolu</p><ol className="mt-5 space-y-4 text-sm">{["Mevcut kayıtlarla eşleşme ara","Birinci kanıt incelemesi","Yeni entity veya mevcut eşleşme öner","Bağımsız ikinci inceleme","Sürümlü taxonomy release ile çöz"].map((item,index) => <li key={item} className="flex gap-3"><strong className="text-emerald-300">0{index+1}</strong><span>{item}</span></li>)}</ol></div><div className="rounded-3xl border border-red-200 bg-red-50 p-5"><p className="text-xs font-black uppercase tracking-widest text-red-800">Satıcı yetkisi</p><strong className="mt-2 block text-xl text-red-950">Canonical ad oluşturamaz</strong><p className="mt-2 text-sm leading-6 text-red-900">Talep çözülene kadar araç yayınlanamaz; serbest metin geçici kimlik olarak kullanılmaz.</p></div></aside></div></div></main>;
}

