import "server-only";
import type {Pool,PoolClient} from "pg";
import type {ComparisonEntitlementRecord,ComparisonEntitlementRepository,VerifiedComparisonIssuerEvent} from "./contracts";
export class PostgresComparisonEntitlementRepository implements ComparisonEntitlementRepository{
 constructor(private readonly pool:Pick<Pool,"connect">){}
 async findActive(binding:Parameters<ComparisonEntitlementRepository["findActive"]>[0],now:Date){const client=await this.pool.connect();try{const result=await client.query("select record from comparison_entitlements where subject_type=$1 and subject_id=$2 and department_id=$3 and category=$4 and conversation_id=$5 and decision_revision=$6 and decision_fingerprint=$7 and state='ACTIVE' and issued_at<=$8 and expires_at>$8 order by issued_at desc limit 1",[binding.subject.type,binding.subject.id,binding.departmentId,binding.category,binding.conversationId,binding.decisionRevision,binding.decisionFingerprint,now.toISOString()]);return result.rowCount?result.rows[0].record as ComparisonEntitlementRecord:null;}finally{client.release();}}
 async applyIssuerEvent(event:VerifiedComparisonIssuerEvent){const client=await this.pool.connect();try{await client.query("begin");const replay=await client.query("select entitlement_id from comparison_entitlement_events where issuer=$1 and issuer_event_id=$2 union select entitlement_id from comparison_entitlements where issuer=$1 and idempotency_key=$3",[event.record.issuer,event.eventId,event.idempotencyKey]);if(replay.rowCount){await client.query("commit");return{status:"REPLAYED" as const};}const current=await client.query("select issuer_event_sequence,record from comparison_entitlements where entitlement_id=$1 for update",[event.record.id]);if(current.rowCount&&Number(current.rows[0].issuer_event_sequence)>=event.sequence){await this.audit(client,event,"REPLAY_IGNORED");await client.query("commit");return{status:"STALE" as const};}const state=event.type==="ENTITLEMENT_ISSUED"?"ACTIVE":event.type==="PURCHASE_REFUNDED"?"REFUNDED":"REVOKED";const record:ComparisonEntitlementRecord={...event.record,state,issuerEventSequence:event.sequence,idempotencyKey:event.idempotencyKey,...(state!=="ACTIVE"?{revokedAt:event.occurredAt}:{})};await client.query("insert into comparison_entitlements (entitlement_id,subject_type,subject_id,purchase_reference_id,department_id,category,conversation_id,decision_revision,decision_fingerprint,evidence_set_fingerprint,state,issued_at,expires_at,issuer,provider,issuer_event_sequence,idempotency_key,record) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) on conflict(entitlement_id) do update set state=excluded.state,revoked_at=case when excluded.state='ACTIVE' then null else excluded.record->>'revokedAt' end,issuer_event_sequence=excluded.issuer_event_sequence,record=excluded.record",[record.id,record.subject.type,record.subject.id,record.purchaseReferenceId,record.departmentId,record.category,record.conversationId,record.decisionRevision,record.decisionFingerprint,record.evidenceSetFingerprint,record.state,record.issuedAt,record.expiresAt,record.issuer,record.provider,record.issuerEventSequence,record.idempotencyKey,record]);await this.audit(client,event,event.type==="ENTITLEMENT_ISSUED"?"ISSUED":event.type==="PURCHASE_REFUNDED"?"REFUNDED":"REVOKED");await client.query("commit");return{status:"APPLIED" as const,entitlement:record};}catch(error){await client.query("rollback");throw error;}finally{client.release();}}
 private audit(client:PoolClient,event:VerifiedComparisonIssuerEvent,type:string){return client.query("insert into comparison_entitlement_events (issuer,issuer_event_id,entitlement_id,event_type,event_sequence,occurred_at,metadata) values ($1,$2,$3,$4,$5,$6,$7)",[event.record.issuer,event.eventId,event.record.id,type,event.sequence,event.occurredAt,{provider:event.record.provider}]);}
}
