import {describe,expect,it} from "vitest";
import type {ComparisonIssuerAdapter,VerifiedComparisonIssuerEvent} from "./contracts";
import {MemoryComparisonEntitlementRepository} from "./memoryRepository.testSupport";
import {evidenceSetFingerprint,ingestComparisonIssuerEvent,resolvePersistedComparisonEntitlement} from "./service.server";
import {createHmacComparisonIssuerAdapter} from "./hmacIssuerAdapter.server";
import {createHmac} from "node:crypto";
const now="2026-09-04T12:00:00.000Z";
const event=(overrides:Partial<VerifiedComparisonIssuerEvent>={}):VerifiedComparisonIssuerEvent=>({verified:true,eventId:"evt-1",sequence:1,type:"ENTITLEMENT_ISSUED",occurredAt:now,idempotencyKey:"idem-1",record:{id:"ent-1",schemaVersion:"comparison-entitlement/v1",subject:{type:"SESSION",id:"session-1"},purchaseReferenceId:"purchase-1",departmentId:"APPLIANCES",category:"WASHING_MACHINE",conversationId:"session-1",decisionRevision:7,decisionFingerprint:"decision-1",authorizedExactIds:["A","B"],evidenceSetFingerprint:evidenceSetFingerprint(["A","B"]),issuedAt:now,expiresAt:"2026-09-05T12:00:00.000Z",issuer:"future-payments",provider:"sandbox-contract"},...overrides});
const adapter=(value:VerifiedComparisonIssuerEvent|null):ComparisonIssuerAdapter=>({issuer:"future-payments",verify:()=>value});
const resolve=(repository:MemoryComparisonEntitlementRepository,overrides:Record<string,unknown>={})=>resolvePersistedComparisonEntitlement({repository,subject:{type:"SESSION",id:"session-1"},departmentId:"APPLIANCES",category:"WASHING_MACHINE",conversationId:"session-1",decisionRevision:7,decisionFingerprint:"decision-1",exactEvidenceIds:["A","B"],now:new Date("2026-09-04T13:00:00Z"),...overrides});
describe("persisted paid comparison entitlement",()=>{
 it("fails closed without configured or valid issuer verification",async()=>{const repository=new MemoryComparisonEntitlementRepository();expect(await ingestComparisonIssuerEvent({adapter:null,repository,rawBody:"{}",headers:{}})).toMatchObject({status:"REJECTED",reason:"ISSUER_CONFIGURATION_MISSING"});expect(await ingestComparisonIssuerEvent({adapter:adapter(null),repository,rawBody:"{}",headers:{}})).toMatchObject({status:"REJECTED",reason:"ISSUER_SIGNATURE_INVALID"});});
 it("issues idempotently, ignores replay and applies ordered refund/revocation",async()=>{const repository=new MemoryComparisonEntitlementRepository();expect(await ingestComparisonIssuerEvent({adapter:adapter(event()),repository,rawBody:"signed",headers:{}})).toMatchObject({status:"APPLIED"});expect(await ingestComparisonIssuerEvent({adapter:adapter(event()),repository,rawBody:"signed",headers:{}})).toMatchObject({status:"REPLAYED"});expect(await resolve(repository)).toMatchObject({status:"PURCHASED",authorizedExactProductIds:["A","B"]});const refund=event({eventId:"evt-2",idempotencyKey:"idem-2",sequence:2,type:"PURCHASE_REFUNDED"});expect(await ingestComparisonIssuerEvent({adapter:adapter(refund),repository,rawBody:"signed",headers:{}})).toMatchObject({status:"APPLIED",entitlement:{state:"REFUNDED"}});expect(await resolve(repository)).toEqual({status:"NOT_PURCHASED"});const oldReissue=event({eventId:"evt-3",idempotencyKey:"idem-3",sequence:1});expect(await ingestComparisonIssuerEvent({adapter:adapter(oldReissue),repository,rawBody:"signed",headers:{}})).toMatchObject({status:"STALE"});});
 it("rejects expiry, cross-category/decision/subject and exact-set escalation",async()=>{const repository=new MemoryComparisonEntitlementRepository();await repository.applyIssuerEvent(event());expect(await resolve(repository,{category:"DRYER"})).toEqual({status:"NOT_PURCHASED"});expect(await resolve(repository,{decisionFingerprint:"forged"})).toEqual({status:"NOT_PURCHASED"});expect(await resolve(repository,{subject:{type:"SESSION",id:"other"}})).toEqual({status:"NOT_PURCHASED"});expect(await resolve(repository,{exactEvidenceIds:["A"]})).toEqual({status:"NOT_PURCHASED"});expect(await resolve(repository,{now:new Date("2026-09-06T00:00:00Z")})).toEqual({status:"NOT_PURCHASED"});});
 it("does not accept client entitlement-shaped values",async()=>{const repository=new MemoryComparisonEntitlementRepository();expect(await resolve(repository,{clientEntitlement:{status:"PURCHASED",authorizedExactProductIds:["A"]}})).toEqual({status:"NOT_PURCHASED"});});
 it("verifies the raw webhook before provider parsing and fails closed without config",()=>{const body=JSON.stringify(event()),secret="test-webhook-secret-012345678901234567890123";expect(createHmacComparisonIssuerAdapter({issuer:"future-payments",secret:undefined,parse:JSON.parse})).toBeNull();const verified=createHmacComparisonIssuerAdapter({issuer:"future-payments",secret,parse:raw=>JSON.parse(raw)})!;expect(verified.verify(body,{"x-expiya-signature":"forged"})).toBeNull();expect(verified.verify(body,{"x-expiya-signature":createHmac("sha256",secret).update(body).digest("base64url")})).toMatchObject({verified:true,eventId:"evt-1"});});
});
