import Link from "next/link";
import { StatusPill } from "@/components/used-cars/ops/OpsShell";

const metrics=[["Açık firma başvurusu","18","4 SLA riski"],["Moderasyon kuyruğu","43","7 yüksek risk"],["Taxonomy ikinci göz","6","2 klasik araç"],["Güvenlik vakası","3","1 acil"]];
export default function OpsDashboardPage(){return <div className="mx-auto max-w-7xl">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-cyan-300">02 Eylül 2026 · İstanbul</p><h2 className="mt-1 text-3xl font-semibold">Operasyon komuta merkezi</h2><p className="mt-2 max-w-2xl text-sm text-slate-400">Atanmış işler, SLA riski ve iki göz bekleyen sentetik vakalar. Tüm değerler demonstrasyon verisidir.</p></div><StatusPill tone="emerald">Servisler: sentetik hazır</StatusPill></div>
  <section className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,note])=><article key={label} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p><p className="mt-2 text-xs text-amber-200">{note}</p></article>)}</section>
  <section className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">Öncelikli işlerim</h3><span className="text-xs text-slate-500">yalnız atanmış kapsam</span></div><div className="mt-4 divide-y divide-white/10">{[["APP-24091","Firma doğrulama","SLA 42 dk",'/ops-demo/firma-basvurulari'],["LST-88214","EİDS invalidation","Acil",'/ops-demo/ilan-moderasyonu'],["TAX-0194","Klasik araç kimliği","İkinci göz",'/ops-demo/taxonomy']].map(([id,title,sla,href])=><Link href={href} key={id} className="grid grid-cols-[90px_1fr_auto] gap-3 py-4 text-sm hover:text-cyan-200"><span className="font-mono text-cyan-300">{id}</span><span>{title}</span><span className="text-amber-200">{sla}</span></Link>)}</div></div><div className="rounded-2xl border border-rose-300/20 bg-rose-300/5 p-5"><h3 className="font-semibold text-rose-100">Kontrol durumu</h3><ul className="mt-4 space-y-3 text-sm text-slate-300"><li>Production authentication: <b className="text-rose-200">kapalı</b></li><li>Gerçek provider çağrıları: <b className="text-rose-200">yasak</b></li><li>Toplu export: <b className="text-rose-200">kapalı</b></li><li>Yüksek etkili karar: <b className="text-amber-200">iki göz + step-up</b></li></ul></div></section>
</div>}

