import type { MobilityProduct } from "./contracts";
export const MOBILITY_CATALOG_RELEASE = "MOBILITY-TR-v0.1-owner-review-candidate" as const;
export const MOBILITY_SOURCES = Object.freeze([
  { id:"AMAZON-TR-DISCOVERY", url:"https://www.amazon.com.tr/s?k=elektrikli+scooter", authority:"COMMERCE_DISCOVERY", observedAt:"2026-09-06T00:00:00+03:00", note:"Amazon listing access is discovery-only; unavailable or ambiguous observations cannot establish facts." },
  { id:"XIAOMI-TR-4-LITE-2", url:"https://www.mi.com/tr/product/xiaomi-electric-scooter-4-lite-2nd-gen/", authority:"MANUFACTURER_TR_PRODUCT" },
  { id:"XIAOMI-TR-4-PRO-2", url:"https://www.mi.com/tr/product/xiaomi-electric-scooter-4-pro-2nd-gen/", authority:"MANUFACTURER_TR_PRODUCT" },
  { id:"SEGWAY-TR-F2-PRO-E", url:"https://tr-tr.segway.com/products/f2-pro-e", authority:"MANUFACTURER_TR_PRODUCT" },
  { id:"DECATHLON-TR-ELECTRIC", url:"https://www.decathlon.com.tr/tum-sporlar/bisiklet/elektrikli-bisikletler", authority:"RETAILER_TR_EXACT_DISCOVERY" },
  { id:"DECATHLON-TR-BICYCLES", url:"https://www.decathlon.com.tr/tum-sporlar/bisiklet/bisikletler", authority:"RETAILER_TR_EXACT_DISCOVERY" },
  { id:"DECATHLON-SUPPORT-EBIKE", url:"https://support.decathlon.com.tr/elektrikli-bisiklet-vae-decathlon-ssh", authority:"MANUFACTURER_SUPPORT" },
] as const);
const u="UNKNOWN" as const;
export const MOBILITY_PRODUCTS: readonly MobilityProduct[] = Object.freeze([
 {exactProductId:"XIAOMI_4_LITE_2ND_GEN_TR",categoryId:"ELECTRIC_SCOOTER",brand:"Xiaomi",family:"Electric Scooter",model:"4 Lite (2nd Gen)",variant:"Türkiye",configurationIdentity:"Xiaomi Electric Scooter 4 Lite (2nd Gen) / Türkiye",trApplicability:{status:"VERIFIED",evidenceIds:["XIAOMI-TR-4-LITE-2"]},facts:{ratedMotorW:300,maxMotorW:390,batteryWh:u,manufacturerRangeKm:25,speedLimitKmh:25,payloadKg:100,weightKg:16.2,wheelIn:10,brakes:"Ön kampana + arka E-ABS",suspension:u,ingressRating:"IPX4",chargeHours:8,foldable:true},capabilities:["Katlanabilir şehir içi elektrikli scooter"],limitations:["Menzil bir garanti değildir; yük, sıcaklık, hız ve yol koşulları sonucu değiştirir."],evidenceIds:["XIAOMI-TR-4-LITE-2"],persona:{hierarchy:["Xiaomi","ELECTRIC_SCOOTER","Electric Scooter","4 Lite (2nd Gen)","Türkiye"],status:"GOVERNED",evidenceClass:"INTENDED_POSITIONING"}},
 {exactProductId:"XIAOMI_4_PRO_2ND_GEN_TR",categoryId:"ELECTRIC_SCOOTER",brand:"Xiaomi",family:"Electric Scooter",model:"4 Pro (2nd Gen)",variant:"Türkiye",configurationIdentity:"Xiaomi Electric Scooter 4 Pro (2nd Gen) / Türkiye",trApplicability:{status:"VERIFIED",evidenceIds:["XIAOMI-TR-4-PRO-2"]},facts:{ratedMotorW:400,maxMotorW:1000,batteryWh:468,manufacturerRangeKm:60,speedLimitKmh:25,payloadKg:120,weightKg:19,wheelIn:10,brakes:"Ön kampana + arka E-ABS",suspension:u,ingressRating:"IPX4",chargeHours:9,foldable:true},capabilities:["Katlanabilir şehir içi elektrikli scooter"],limitations:["Üretici menzil koşulları gerçek kullanımı garanti etmez."],evidenceIds:["XIAOMI-TR-4-PRO-2"],persona:{hierarchy:["Xiaomi","ELECTRIC_SCOOTER","Electric Scooter","4 Pro (2nd Gen)","Türkiye"],status:"GOVERNED",evidenceClass:"INTENDED_POSITIONING"}},
 {exactProductId:"SEGWAY_NINEBOT_F2_PRO_E_TR",categoryId:"ELECTRIC_SCOOTER",brand:"Segway",family:"Ninebot F",model:"F2 Pro E",variant:"EU/TR",configurationIdentity:"Segway Ninebot F2 Pro E / EU-Türkiye",trApplicability:{status:"VERIFIED",evidenceIds:["SEGWAY-TR-F2-PRO-E"]},facts:{ratedMotorW:u,maxMotorW:u,batteryWh:u,manufacturerRangeKm:u,speedLimitKmh:u,payloadKg:u,weightKg:u,wheelIn:u,brakes:u,suspension:u,ingressRating:u,chargeHours:u,foldable:u},capabilities:[],limitations:["Teknik değerler, üretici Türkiye kaynağı yeniden erişilip doğrulanana kadar UNKNOWN."],evidenceIds:["SEGWAY-TR-F2-PRO-E"],persona:{hierarchy:["Segway","ELECTRIC_SCOOTER","Ninebot F","F2 Pro E","EU/TR"],status:"GOVERNED",evidenceClass:"INTENDED_POSITIONING"}},
 {exactProductId:"ROCKRIDER_E_ACTV_100_GREY_TR",categoryId:"ELECTRIC_BICYCLE",brand:"Rockrider",family:"E-ACTV",model:"E-ACTV 100",variant:"Gri / beden seçilir",configurationIdentity:"Rockrider E-ACTV 100 elektrikli hibrit / gri / Türkiye / beden seçilir",trApplicability:{status:"VERIFIED",evidenceIds:["DECATHLON-TR-ELECTRIC"]},facts:{nominalMotorW:250,motorPosition:"Arka",torqueNm:45,batteryWh:356,batteryRemovable:true,manufacturerRangeKm:70,wheelIn:28,gears:8,brakes:"Mekanik disk",payloadKg:120,weightKg:u},capabilities:["Trekking ve şehir kullanımı","Çıkarılabilir batarya"],limitations:["Beden exact seçimde ayrıca doğrulanmalıdır.","Menzil kullanım koşullarına bağlıdır."],evidenceIds:["DECATHLON-TR-ELECTRIC","DECATHLON-SUPPORT-EBIKE"],persona:{hierarchy:["Rockrider","ELECTRIC_BICYCLE","E-ACTV","E-ACTV 100","Gri / beden seçilir"],status:"GOVERNED",evidenceClass:"INTENDED_POSITIONING"}},
 {exactProductId:"BTWIN_E_FOLD_500_GREEN_TR",categoryId:"ELECTRIC_BICYCLE",brand:"Btwin",family:"E Fold",model:"E Fold 500",variant:"Yeşil / tek beden",configurationIdentity:"Btwin E Fold 500 katlanır elektrikli bisiklet / yeşil / Türkiye",trApplicability:{status:"VERIFIED",evidenceIds:["DECATHLON-TR-ELECTRIC"]},facts:{nominalMotorW:250,motorPosition:"Arka",torqueNm:35,batteryWh:252,batteryRemovable:true,manufacturerRangeKm:50,wheelIn:20,gears:6,brakes:"V-fren",payloadKg:120,weightKg:u,foldable:true},capabilities:["Katlanabilir","Şehir içi kullanım"],limitations:["Katlı ölçü ve ürün ağırlığı bu aday sürümünde UNKNOWN."],evidenceIds:["DECATHLON-TR-ELECTRIC"],persona:{hierarchy:["Btwin","ELECTRIC_BICYCLE","E Fold","E Fold 500","Yeşil / tek beden"],status:"GOVERNED",evidenceClass:"INTENDED_POSITIONING"}},
 {exactProductId:"ROCKRIDER_E_EXPL_700_GREEN_TR",categoryId:"ELECTRIC_BICYCLE",brand:"Rockrider",family:"E-EXPL",model:"E-EXPL 700",variant:"Yeşil / 29 inç / beden seçilir",configurationIdentity:"Rockrider E-EXPL 700 elektrikli dağ bisikleti / yeşil / 29 inç / Türkiye",trApplicability:{status:"VERIFIED",evidenceIds:["DECATHLON-TR-ELECTRIC"]},facts:{nominalMotorW:250,motorPosition:"Orta",torqueNm:70,batteryWh:630,batteryRemovable:true,manufacturerRangeKm:100,wheelIn:29,gears:10,brakes:"Hidrolik disk",payloadKg:120,weightKg:u},capabilities:["Dağ bisikleti kullanımı","Ön süspansiyon"],limitations:["Arazi kabiliyeti sürücü becerisi veya güvenlik garantisi değildir."],evidenceIds:["DECATHLON-TR-ELECTRIC"],persona:{hierarchy:["Rockrider","ELECTRIC_BICYCLE","E-EXPL","E-EXPL 700","Yeşil / 29 inç / beden seçilir"],status:"GOVERNED",evidenceClass:"INTENDED_POSITIONING"}},
 {exactProductId:"ELOPS_520_PURPLE_28_TR",categoryId:"BICYCLE",brand:"Elops",family:"Elops 500",model:"520",variant:"Mor / 28 inç / beden seçilir",configurationIdentity:"Elops 520 şehir bisikleti / mor / 28 inç / Türkiye",trApplicability:{status:"VERIFIED",evidenceIds:["DECATHLON-TR-BICYCLES"]},facts:{intendedClass:"Şehir",frameMaterial:u,wheelIn:28,gears:6,brakes:"V-fren",suspension:false,payloadKg:100,weightKg:u,rack:true,fenders:true,lights:true},capabilities:["Şehir içi kullanım","Portbagaj, çamurluk ve aydınlatma"],limitations:["Kadro bedeni kullanıcı boyu ve üretici fit tablosuyla eşleştirilmelidir."],evidenceIds:["DECATHLON-TR-BICYCLES"],persona:{hierarchy:["Elops","BICYCLE","Elops 500","520","Mor / 28 inç / beden seçilir"],status:"GOVERNED",evidenceClass:"INTENDED_POSITIONING"}},
 {exactProductId:"ELOPS_LD500_GREY_28_TR",categoryId:"BICYCLE",brand:"Elops",family:"Long Distance",model:"LD 500",variant:"Gri / 28 inç / beden seçilir",configurationIdentity:"Elops LD 500 tur-şehir bisikleti / gri / 28 inç / Türkiye",trApplicability:{status:"VERIFIED",evidenceIds:["DECATHLON-TR-BICYCLES"]},facts:{intendedClass:"Tur/şehir",frameMaterial:"Alüminyum",wheelIn:28,gears:9,brakes:"Hidrolik disk",suspension:false,payloadKg:140,weightKg:u,rack:true,fenders:true,lights:true},capabilities:["Şehir ve tur kullanımı","Portbagaj, çamurluk ve aydınlatma"],limitations:["Beden ve toplam yük sınırı exact ürün sayfasında yeniden doğrulanmalıdır."],evidenceIds:["DECATHLON-TR-BICYCLES"],persona:{hierarchy:["Elops","BICYCLE","Long Distance","LD 500","Gri / 28 inç / beden seçilir"],status:"GOVERNED",evidenceClass:"INTENDED_POSITIONING"}},
 {exactProductId:"BTWIN_TILT_500_NAVY_TR",categoryId:"BICYCLE",brand:"Btwin",family:"Tilt",model:"Tilt 500",variant:"Koyu mavi / 20 inç / tek beden",configurationIdentity:"Btwin Tilt 500 katlanır bisiklet / koyu mavi / 20 inç / Türkiye",trApplicability:{status:"VERIFIED",evidenceIds:["DECATHLON-TR-BICYCLES"]},facts:{intendedClass:"Katlanır şehir",frameMaterial:"Alüminyum",wheelIn:20,gears:7,brakes:"V-fren",suspension:false,payloadKg:100,weightKg:u,foldable:true},capabilities:["Katlanabilir","Şehir içi kullanım"],limitations:["Katlı ölçü ve kullanıcı boy aralığı bu aday sürümünde UNKNOWN."],evidenceIds:["DECATHLON-TR-BICYCLES"],persona:{hierarchy:["Btwin","BICYCLE","Tilt","Tilt 500","Koyu mavi / 20 inç / tek beden"],status:"GOVERNED",evidenceClass:"INTENDED_POSITIONING"}},
 {exactProductId:"ROCKRIDER_RACE_500_BLUE_29_TR",categoryId:"BICYCLE",brand:"Rockrider",family:"Race",model:"Race 500",variant:"Mavi / 29 inç / beden seçilir",configurationIdentity:"Rockrider Race 500 dağ bisikleti / mavi / 29 inç / Türkiye",trApplicability:{status:"VERIFIED",evidenceIds:["DECATHLON-TR-BICYCLES"]},facts:{intendedClass:"Dağ",frameMaterial:"Alüminyum",wheelIn:29,gears:12,brakes:"Hidrolik disk",suspension:"Ön",payloadKg:u,weightKg:u},capabilities:["Dağ bisikleti kullanımı","Ön süspansiyon"],limitations:["Arazi kullanımı güvenlik veya performans garantisi değildir."],evidenceIds:["DECATHLON-TR-BICYCLES"],persona:{hierarchy:["Rockrider","BICYCLE","Race","Race 500","Mavi / 29 inç / beden seçilir"],status:"GOVERNED",evidenceClass:"INTENDED_POSITIONING"}},
]);
export const MOBILITY_DISCOVERY_RECONCILIATION = Object.freeze({ amazonObserved: 8, amazonAdmitted: 0, nonAmazonObserved: 16, admitted: 10, duplicate: 3, ambiguous: 5, insufficientTrApplicability: 4, retiredUnsupported: 2, silentDrops: 0, note:"Amazon pages were retained as commerce observations only because exact identity and primary technical evidence could not be closed lawfully in this pass." });
