import { describe, expect, it } from "vitest";
import { createFileSystemAppliancesArtifactRepository, loadActiveAppliancesAuthority } from "../authority/loader.server";
import { enterAppliancesDepartment } from "../entry.server";
import { MemoryAppliancesConversationStore } from "../persistence/memoryStore.testSupport";
import { commitAppliancesBootstrap } from "../persistence/service";
import { interpretAppliancesTurn, type AppliancesSemanticProposal } from "./interpretation";
import { projectActiveAppliancesContext } from "./projection";
import { runAppliancesContextTurn } from "./runtime.server";
import { validateAppliancesProposalSet } from "./validation";
const conversationId = "22222222-2222-4222-8222-222222222222";
async function setup(){const repository=createFileSystemAppliancesArtifactRepository(process.cwd());const authority=await loadActiveAppliancesAuthority({repository});if(authority.status!=="READY")throw new Error(authority.reason);const entry=await enterAppliancesDepartment({repository,productType:"WASHING_MACHINE",conversationId});if(entry.status!=="READY")throw new Error(entry.status);const store=new MemoryAppliancesConversationStore();await commitAppliancesBootstrap({store,state:entry.state,messageId:"bootstrap",payload:{action:"CREATE"}});return{store,authority:authority.snapshot};}
describe("Appliances confirmation lifecycle",()=>{
 it("creates one bound pending proposal and generic yes confirms it exactly once",async()=>{const {store,authority}=await setup();const proposed=await runAppliancesContextTurn({store,authority,conversationId,messageId:"m1",expectedRevision:1,message:"Gece çalıştıracağım, rahatsız etmesin"});expect(proposed.status).toBe("OK");if(proposed.status!=="OK")return;expect(proposed.state.pendingConfirmation).toMatchObject({conceptId:"LOW_NOISE_PRIORITY",sourceMessageId:"m1",createdRevision:2});expect(proposed.state.ledger.find(e=>e.conceptId==="LOW_NOISE_PRIORITY")?.status).toBe("PROPOSED");const confirmed=await runAppliancesContextTurn({store,authority,conversationId,messageId:"m2",expectedRevision:2,message:"evet"});expect(confirmed.status).toBe("OK");if(confirmed.status!=="OK")return;expect(confirmed.state.revision).toBe(3);expect(confirmed.state.pendingConfirmation).toBeUndefined();expect(projectActiveAppliancesContext(confirmed.state.ledger).get("LOW_NOISE_PRIORITY")).toMatchObject({status:"ACCEPTED_CONFIRMED",authority:"USER_CONFIRMED",sourceMessageId:"m2"});const replay=await runAppliancesContextTurn({store,authority,conversationId,messageId:"m2",expectedRevision:2,message:"evet"});expect(replay.status==="OK"&&replay.replayed).toBe(true);expect((await store.load(conversationId))?.state.ledger).toHaveLength(confirmed.state.ledger.length);});
 it("generic rejection appends REJECTED and invalidates pending",async()=>{const {store,authority}=await setup();await runAppliancesContextTurn({store,authority,conversationId,messageId:"m1",expectedRevision:1,message:"Gece çalıştıracağım, rahatsız etmesin"});const rejected=await runAppliancesContextTurn({store,authority,conversationId,messageId:"m2",expectedRevision:2,message:"hayır"});expect(rejected.status).toBe("OK");if(rejected.status!=="OK")return;expect(rejected.state.pendingConfirmation).toBeUndefined();expect(rejected.state.ledger.at(-1)).toMatchObject({status:"REJECTED",sourceMessageId:"m2"});expect(projectActiveAppliancesContext(rejected.state.ledger).has("LOW_NOISE_PRIORITY")).toBe(false);});
 it("does not fabricate context without a pending target",async()=>{const {store,authority}=await setup();const result=await runAppliancesContextTurn({store,authority,conversationId,messageId:"m",expectedRevision:1,message:"evet"});expect(result.status==="OK"&&result.outcome).toMatchObject({kind:"CLARIFY",questionKey:"UNBOUND_CONFIRMATION"});expect((await store.load(conversationId))?.state.revision).toBe(1);});
 it("superseding explicit input invalidates pending while preserving its history",async()=>{const {store,authority}=await setup();await runAppliancesContextTurn({store,authority,conversationId,messageId:"m1",expectedRevision:1,message:"Gece çalıştıracağım, rahatsız etmesin"});const explicit=await runAppliancesContextTurn({store,authority,conversationId,messageId:"m2",expectedRevision:2,message:"Sessiz olması önemli"});expect(explicit.status).toBe("OK");if(explicit.status!=="OK")return;expect(explicit.state.pendingConfirmation).toBeUndefined();expect(explicit.state.ledger.some(e=>e.status==="SUPERSEDED"&&e.conceptId==="LOW_NOISE_PRIORITY")).toBe(true);expect(projectActiveAppliancesContext(explicit.state.ledger).get("LOW_NOISE_PRIORITY")?.status).toBe("ACCEPTED_EXPLICIT");});
 it("rejects multiple confirmation targets and inconsistent sets atomically",async()=>{const message="Gece çalıştıracağım, rahatsız etmesin";const parsed=interpretAppliancesTurn(message,"m");const interpreted=parsed.proposals.find(p=>p.confirmationRequired)!;const second={...interpreted,proposalId:"m:other",conceptId:"SPECIAL_CARE"} satisfies AppliancesSemanticProposal;expect(validateAppliancesProposalSet([interpreted,second]).status).toBe("VALID");const conflicting={...interpreted,proposalId:"m:conflict",normalizedValue:false};expect(validateAppliancesProposalSet([interpreted,conflicting])).toMatchObject({status:"INCONSISTENT_SET",conceptId:"LOW_NOISE_PRIORITY"});});
 it("keeps valid proposals when an unrelated value is invalid",()=>{const valid=interpretAppliancesTurn("Sessiz olması önemli","m").proposals[0]!;const invalid={...valid,proposalId:"invalid",conceptId:"BUDGET_SENSITIVITY",normalizedValue:{maximumTry:-1}};expect(validateAppliancesProposalSet([valid,invalid])).toMatchObject({status:"VALID",accepted:[valid],rejectedProposalIds:["invalid"]});});
});
