import { describe,expect,it } from "vitest";
import { createFileSystemAppliancesArtifactRepository,loadActiveAppliancesAuthority } from "../authority/loader.server";
import { enterAppliancesDepartment } from "../entry.server";
import { MemoryAppliancesConversationStore } from "../persistence/memoryStore.testSupport";
import { commitAppliancesBootstrap } from "../persistence/service";
import { runAppliancesContextTurn } from "./runtime.server";
const conversationId="33333333-3333-4333-8333-333333333333";
async function setup(){const repository=createFileSystemAppliancesArtifactRepository(process.cwd());const authority=await loadActiveAppliancesAuthority({repository});if(authority.status!=="READY")throw new Error(authority.reason);const entry=await enterAppliancesDepartment({repository,productType:"WASHING_MACHINE",conversationId});if(entry.status!=="READY")throw new Error(entry.status);const store=new MemoryAppliancesConversationStore();await commitAppliancesBootstrap({store,state:entry.state,messageId:"bootstrap",payload:{action:"CREATE"}});return{store,authority:authority.snapshot};}
describe("pending confirmation invalidation",()=>{
 it("related clear invalidates the pending proposal",async()=>{const {store,authority}=await setup();await runAppliancesContextTurn({store,authority,conversationId,messageId:"m1",expectedRevision:1,message:"Gece çalıştıracağım, rahatsız etmesin"});const result=await runAppliancesContextTurn({store,authority,conversationId,messageId:"m2",expectedRevision:2,message:"Gürültü konusu önemli değil"});expect(result.status).toBe("OK");if(result.status!=="OK")return;expect(result.state.pendingConfirmation).toBeUndefined();expect(result.state.ledger.at(-1)).toMatchObject({conceptId:"LOW_NOISE_PRIORITY",status:"CLEARED"});});
 it("stale generic confirmation clarifies without mutation",async()=>{const {store,authority}=await setup();await runAppliancesContextTurn({store,authority,conversationId,messageId:"m1",expectedRevision:1,message:"Gece çalıştıracağım, rahatsız etmesin"});for(const [messageId,expectedRevision] of [["m2",2],["m3",3],["m4",4]] as const)await runAppliancesContextTurn({store,authority,conversationId,messageId,expectedRevision,message:"Bugün hava nasıl?"});const result=await runAppliancesContextTurn({store,authority,conversationId,messageId:"m5",expectedRevision:5,message:"evet"});expect(result.status==="OK"&&result.outcome).toMatchObject({kind:"CLARIFY",questionKey:"STALE_CONFIRMATION"});expect((await store.load(conversationId))?.state.revision).toBe(5);});
 it("multiple interpreted targets clarify atomically",async()=>{const {store,authority}=await setup();const result=await runAppliancesContextTurn({store,authority,conversationId,messageId:"m",expectedRevision:1,message:"Gece çalıştıracağım, rahatsız etmesin; hassas çamaşır yıkıyorum"});expect(result.status==="OK"&&result.outcome).toMatchObject({kind:"CLARIFY",questionKey:"MULTIPLE_CONFIRMATIONS"});expect((await store.load(conversationId))?.state.revision).toBe(1);});
});
