import { describe,expect,it } from "vitest";
import { createFileSystemAppliancesArtifactRepository,loadActiveAppliancesAuthority } from "../authority/loader.server";
import { enterAppliancesDepartment } from "../entry.server";
import { MemoryAppliancesConversationStore } from "../persistence/memoryStore.testSupport";
import { commitAppliancesBootstrap } from "../persistence/service";
import { interpretAppliancesTurn,proposalSchema } from "./interpretation";
import { projectActiveAppliancesContext } from "./projection";
import { runAppliancesContextTurn } from "./runtime.server";
const id="11111111-1111-4111-8111-111111111111";
async function setup(){const repository=createFileSystemAppliancesArtifactRepository(process.cwd());const authority=await loadActiveAppliancesAuthority({repository});if(authority.status!=="READY")throw new Error(authority.reason);const entry=await enterAppliancesDepartment({repository,productType:"WASHING_MACHINE",conversationId:id,now:new Date("2026-09-03T10:00:00Z")});if(entry.status!=="READY")throw new Error(entry.status);const store=new MemoryAppliancesConversationStore();await commitAppliancesBootstrap({store,state:entry.state,messageId:"bootstrap",payload:{action:"CREATE"}});return{store,authority:authority.snapshot};}
describe("Appliances context authority",()=>{
 it("extracts multiple exact spans without turning household size into capacity",()=>{const message="5 kişiyiz, haftada neredeyse her gün çamaşır yıkıyoruz.";const result=interpretAppliancesTurn(message,"m");expect(result.proposals.map(p=>p.conceptId)).toEqual(["LOAD_CONSOLIDATION","FREQUENT_WASHING"]);for(const p of result.proposals)expect(message.slice(p.sourceSpan!.start,p.sourceSpan!.end)).toBe(p.sourceSpan!.text);expect(JSON.stringify(result)).not.toContain("minimumCapacityKg");});
it("keeps interpreted night noise distinct from explicit authority",()=>{const result=interpretAppliancesTurn("Gece çalıştıracağım, rahatsız etmesin.","m");expect(result.proposals.find(p=>p.conceptId==="LOW_NOISE_PRIORITY")?.interpretationAuthority).toBe("INTERPRETED_USER_MEANING");});
it("treats night-only language as a confirmable noise inference",()=>{const result=interpretAppliancesTurn("Geceleri çalıştıracağım","m");expect(result.proposals.find(p=>p.conceptId==="LOW_NOISE_PRIORITY")).toMatchObject({interpretationAuthority:"INTERPRETED_USER_MEANING",confirmationRequired:true});});
 it("normalizes remote-control context only to the approved wanted domain",()=>{const unwanted=interpretAppliancesTurn("Wi-Fi benim için önemli değil","m1").proposals.find(p=>p.conceptId==="REMOTE_CONTROL");const wanted=interpretAppliancesTurn("Uygulamadan uzaktan kontrol istiyorum","m2").proposals.find(p=>p.conceptId==="REMOTE_CONTROL");expect(unwanted?.normalizedValue).toEqual({wanted:false});expect(wanted?.normalizedValue).toEqual({wanted:true});expect(JSON.stringify([unwanted?.normalizedValue,wanted?.normalizedValue])).not.toMatch(/prohibited|required/iu);});
 it("strictly rejects malformed proposals",()=>expect(proposalSchema.safeParse({proposalId:"p",kind:"SET",conceptId:"UNKNOWN",sourceMessageId:"m",interpretationAuthority:"MODEL",confirmationRequired:false}).success).toBe(false));
 it("accepts explicit context, derives planning-only personas and replays exactly",async()=>{const {store,authority}=await setup();const input={store,authority,conversationId:id,messageId:"m1",expectedRevision:1,message:"9 kilo bakıyorum, mutfağa koyacağım ve gece çalıştırıyorum.",now:new Date("2026-09-03T10:01:00Z")};const first=await runAppliancesContextTurn(input);const replay=await runAppliancesContextTurn(input);expect(first.status).toBe("OK");expect(replay).toEqual({...first,replayed:true});if(first.status!=="OK")return;expect(first.state.revision).toBe(2);expect(first.state.ledger).toHaveLength(4);expect(first.state.pendingConfirmation?.conceptId).toBe("LOW_NOISE_PRIORITY");expect(first.state.personaSignals).toEqual(expect.arrayContaining([expect.objectContaining({signalId:"SPACE_CONSTRAINED",authority:"DERIVED_PLANNING",directCandidateEffect:"NONE",decisionUse:"NONE"})]));expect(first.outcome).toMatchObject({kind:"RESPOND",contextMutation:"VALIDATED",contextRevision:2});});
 it("fails a reused message id with a different payload and leaves state unchanged",async()=>{const {store,authority}=await setup();await runAppliancesContextTurn({store,authority,conversationId:id,messageId:"m",expectedRevision:1,message:"Wi-Fi istemiyorum"});const conflict=await runAppliancesContextTurn({store,authority,conversationId:id,messageId:"m",expectedRevision:1,message:"Sessiz olması önemli"});expect(conflict).toEqual({status:"MESSAGE_PAYLOAD_CONFLICT"});expect((await store.load(id))?.state.revision).toBe(2);});
 it("supersedes corrections, clears by tombstone and projects deterministically",async()=>{const {store,authority}=await setup();await runAppliancesContextTurn({store,authority,conversationId:id,messageId:"m1",expectedRevision:1,message:"En az 10 kg istiyorum"});await runAppliancesContextTurn({store,authority,conversationId:id,messageId:"m2",expectedRevision:2,message:"Aslında 9 kg da olabilir"});const cleared=await runAppliancesContextTurn({store,authority,conversationId:id,messageId:"m3",expectedRevision:3,message:"Bütçem 30 bin TL"});expect(cleared.status).toBe("OK");const loaded=await store.load(id);expect(loaded?.state.ledger.some(e=>e.status==="SUPERSEDED")).toBe(true);expect((projectActiveAppliancesContext(loaded!.state.ledger).get("HIGH_LAUNDRY_VOLUME")?.normalizedValue as {minimumCapacityKg:number}).minimumCapacityKg).toBe(9);});
 it("clarifies ambiguity and contradiction without mutation",async()=>{const {store,authority}=await setup();const ambiguous=await runAppliancesContextTurn({store,authority,conversationId:id,messageId:"m1",expectedRevision:1,message:"Bu şartı unut"});expect(ambiguous.status==="OK"&&ambiguous.outcome.kind).toBe("CLARIFY");expect((await store.load(id))?.state.revision).toBe(1);});
	 it.each([["1400 devir ne demek?","DOMAIN_INFORMATION"],["teşekkürler","SOCIAL_ACKNOWLEDGEMENT"],["Bugün hava nasıl?","OFF_TOPIC_REDIRECT"],["Elektrik kablosunu söküp tamir edeyim mi?","SAFETY_BOUNDARY"],["teşekkürler, kapatalım","USER_CLOSING"]] as const)("routes bounded RESPOND: %s",async(message,responseKind)=>{const {store,authority}=await setup();const result=await runAppliancesContextTurn({store,authority,conversationId:id,messageId:"m",expectedRevision:1,message});expect(result.status==="OK"&&result.outcome).toMatchObject({kind:"RESPOND",responseKind});if(result.status==="OK"&&"message" in result.outcome)expect(result.outcome.message).not.toMatch(/öneriyorum|satın al|model/i);});
 it("keeps known inactive products unsupported",async()=>{const {store,authority}=await setup();const result=await runAppliancesContextTurn({store,authority,conversationId:id,messageId:"m",expectedRevision:1,message:"Bulaşık makinesi arıyorum"});expect(result.status==="OK"&&result.outcome).toMatchObject({kind:"UNSUPPORTED",productType:"DISHWASHER"});expect((await store.load(id))?.state.revision).toBe(1);});
});
