import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { ELECTRONICS_CATEGORY_IDS } from "./architectureBaseline";
import { digestElectronicsPolicy, validateElectronicsCategoryPolicy, type ElectronicsCategoryPolicyArtifact } from "./categoryPolicy";
import { loadActiveElectronicsCategoryPolicy } from "./categoryPolicyLoader.server";
import { ELECTRONICS_CATEGORY_REGISTRY } from "./architectureBaseline";
import { electronicsQuestionText, electronicsWelcomeText } from "./publicLanguage";

const root = process.cwd(); const releaseDir = path.join(root, "data/production/electronics/category-policy/releases/ELECTRONICS-CATEGORY-POLICY-TR-v1.0"); const artifact = JSON.parse(readFileSync(path.join(releaseDir, "policy.json"), "utf8")) as ElectronicsCategoryPolicyArtifact;
describe("Electronics 24-category frozen policy authority", () => {
  it("binds all 24 categories uniquely to ready evidence", () => { expect(validateElectronicsCategoryPolicy(artifact)).toEqual([]); expect(artifact.payload.categories.map(row => row.categoryId)).toEqual(ELECTRONICS_CATEGORY_IDS); expect(new Set(artifact.payload.categories.map(row => row.evidenceReleaseDigest)).size).toBe(4); for (const row of artifact.payload.categories) expect(row.governedEvidenceFieldRefs.length).toBeGreaterThanOrEqual(4); });
  it("allows exactly one material friendly question and suppresses repeats", () => { const p = artifact.payload.sharedSemantics.p; expect(p.maximumQuestionsPerTurn).toBe(1); expect(p.forbiddenPrompt).toBe("LIST_ALL_MEASUREMENTS_OR_FUNCTIONS"); expect(p.suppressAcceptedOrPendingOrUnchangedAsked).toBe(true); for (const row of artifact.payload.categories) for (const question of row.questionPlan) { expect(question.textTr).toMatch(/\?$/u); expect(question.choicesTr).toEqual(["Önemli", "Önemli değil", "Henüz bilmiyorum"]); expect(question.noRepeatUnless).toEqual(["CORRECTED", "CLEARED", "AUTHORITY_MATERIALLY_CHANGED"]); } });
  it("projects every active question into human Turkish without internal vocabulary", () => { for (const row of artifact.payload.categories) { const label = ELECTRONICS_CATEGORY_REGISTRY.find((item) => item.categoryId === row.categoryId)!.publicLabelTr; for (const question of row.questionPlan) { const text = electronicsQuestionText(row.categoryId, label, question.targetConcept); expect(text).toMatch(/\?$/u); expect(text).not.toMatch(/(?:[a-zçğıöşü]+_[a-z0-9_]+|\b(?:runtime|exact|concept|field|policy|support|compatibility|topology|throughput|backhaul|autofocus)\b)/iu); } } });
  it("explains Tablet software support through its daily-life consequence", () => { expect(electronicsQuestionText("TABLET", "Tablet", "OS_SUPPORT")).toBe("Tabletin yeni uygulamalarla çalışmaya ve güvenlik güncellemeleri almaya devam etmesi ne kadar önemli?"); });
  it("gives every active category a governed X welcome with one easy question", () => { for (const row of artifact.payload.categories) { const label = ELECTRONICS_CATEGORY_REGISTRY.find((item) => item.categoryId === row.categoryId)!.publicLabelTr; const welcome = electronicsWelcomeText(row.categoryId, label, row); expect(welcome.length).toBeGreaterThan(120); expect(welcome.match(/\?/gu)).toHaveLength(1); expect(welcome).not.toMatch(/(?:[a-zçğıöşü]+_[a-z0-9_]+|\b(?:runtime|exact|concept|field|policy)\b)/iu); } });
  it("separates informational RESPOND from purchase progress", () => { expect(artifact.payload.sharedSemantics.x.informationalTurn).toContain("WITHOUT_PURCHASE_PROGRESS"); expect(artifact.payload.sharedSemantics.sufficiency).toMatchObject({ informationOnly: "RESPOND", purchaseIntent: "PROGRESS_ONLY_WHEN_MINIMUM_CONTEXT_AND_ELIGIBLE_POOL_EXIST" }); });
  it("freezes correction, clear, unknown and not-important semantics", () => { expect(artifact.payload.sharedSemantics.context).toEqual({ normalization: "CANONICAL_CONCEPT_VALUE_WITH_SOURCE_EVENT", correction: "SUPERSEDE_PRIOR_ACCEPTED_VALUE_AND_REEVALUATE", clear: "REMOVE_ACTIVE_VALUE_AND_ALLOW_MATERIAL_REASK", unknown: "EXPLICIT_UNKNOWN_NEVER_INFERRED", notImportant: "ACCEPTED_NON_FILTERING_VALUE" }); });
  it("keeps hard constraints exact, evidence unknown neutral and budget unknown non-eliminating", () => { expect(artifact.payload.sharedSemantics.candidateEvaluation).toMatchObject({ hardCompatibility: "EVIDENCED_EXACT_CONSTRAINT_MISMATCH_ONLY", identity: "EXACT_PRODUCT_CONFIGURATION_REGION_REVISION_REQUIRED", unknown: "UNKNOWN_NEVER_SILENT_ELIMINATION_OR_ADVANTAGE", missingOrStalePrice: "UNKNOWN_NOT_TECHNICAL_ELIMINATION" }); });
  it("does not invent a winner for ties or non-dominated sets", () => { expect(artifact.payload.sharedSemantics.selection).toMatchObject({ tie: "RETURN_TIED_TOP_SET_NO_WINNER", nonDominated: "RETURN_NON_DOMINATED_SET_NO_WINNER", arrayOrderEffect: "NONE" }); });
  it("requires evidence-bound rationale and authorization before card projection", () => { expect(artifact.payload.sharedSemantics.recommendation).toMatchObject({ rationale: "BIND_ACCEPTED_NEEDS_TO_GOVERNED_FACTS_AND_DAILY_LIFE_INTERPRETATION", unsupportedSuperlatives: "FORBIDDEN" }); expect(artifact.payload.sharedSemantics.authorization.order.at(-2)).toBe("AUTHORIZATION"); expect(artifact.payload.sharedSemantics.authorization.order.at(-1)).toBe("CARD_PROJECTION"); expect(artifact.payload.sharedSemantics.authorization.cardWithoutAuthorization).toBe("FORBIDDEN"); });
  it("binds category risk and manual limits", () => { for (const row of artifact.payload.categories) expect(row.riskBoundaries).toContain("COMPATIBILITY_ECOSYSTEM_REGION"); for (const id of ["SMARTWATCH", "FITNESS_TRACKER"]) expect(artifact.payload.categories.find(row => row.categoryId === id)?.riskBoundaries).toContain("HEALTH_NON_MEDICAL"); for (const id of ["HOME_SECURITY_CAMERA", "VIDEO_DOORBELL", "SMART_HOME_HUB"]) expect(artifact.payload.categories.find(row => row.categoryId === id)?.riskBoundaries).toContain("PRIVACY_ACCOUNT_CLOUD_SUBSCRIPTION"); expect(artifact.payload.sharedSemantics.manuals.technicalAuthority).toBe("NONE_UNLESS_SEPARATELY_PROMOTED"); });
  it("gives persona and commerce zero direct decision authority", () => { expect(artifact.payload.sharedSemantics.persona).toEqual({ mode: "DERIVED_PLANNING", decisionUse: "NONE", directCandidateEffect: "NONE" }); expect(artifact.payload.sharedSemantics.commerce).toMatchObject({ l10RankingEffect: "NONE", amazonEffect: "NONE", affiliateReviewSellerProminenceEffect: "NONE" }); });
  it("isolates Electronics semantics from Cars and Appliances", () => { expect(artifact.payload.isolation).toEqual({ appliancesPolicyImported: false, carsPolicyImported: false, mechanicsReusedOnly: true, electronicsEvidenceOnly: true }); expect(artifact.payload.sharedSemantics.x.offTopic).toBe("REDIRECT_TO_CURRENT_ELECTRONICS_CATEGORY_NEVER_CARS"); });
  it("is canonical, deterministic, authority-only and loads fail closed", () => { expect(artifact.policyDigest).toBe(digestElectronicsPolicy(artifact.payload)); expect(loadActiveElectronicsCategoryPolicy().policyDigest).toBe(artifact.policyDigest); expect(artifact.payload.runtimeActive).toBe(false); expect(Object.values(artifact.payload.boundaries).every(value => value === false)).toBe(true); const temp = mkdtempSync(path.join(os.tmpdir(), "electronics-policy-")); const pointerDir = path.join(temp, "data/production/electronics/category-policy"); mkdirSync(pointerDir, { recursive: true }); const pointer = JSON.parse(readFileSync(path.join(root, "data/production/electronics/category-policy/active.json"), "utf8")) as Record<string, unknown>; writeFileSync(path.join(pointerDir, "active.json"), JSON.stringify({ ...pointer, policyDigest: "sha256:deadbeef" })); expect(() => loadActiveElectronicsCategoryPolicy(temp)).toThrow(); });
  it("fails closed for a missing category or unknown concept binding", () => { const missing = structuredClone(artifact); (missing.payload.categories as unknown as unknown[]).pop(); expect(validateElectronicsCategoryPolicy(missing)).toContain("CATEGORY_COVERAGE_INVALID"); const bad = structuredClone(artifact); (bad.payload.categories[0]!.minimumAcceptedContext as unknown as string[])[0] = "NOT_A_CONCEPT"; expect(validateElectronicsCategoryPolicy(bad)).toContain(`CONCEPT_BINDING_INVALID:${bad.payload.categories[0]!.categoryId}`); });
});
