import { randomUUID } from "node:crypto";
import { executeValidatedTurn } from "../conversation-kernel/executeValidatedTurn";
import { bindXpyRuntime } from "../xpy/runtimeContract";
import { requireXpyDomainPack } from "../xpy/domainPacks";
import { ELECTRONICS_CATEGORY_IDS, ELECTRONICS_CATEGORY_REGISTRY, type ElectronicsCategoryId } from "./architectureBaseline";
import type { ElectronicsCategoryPolicyArtifact } from "./categoryPolicy";
import { electronicsKnowledgeAnswer, electronicsQuestionText, electronicsWelcomeText } from "./publicLanguage";
import type { ElectronicsRuntimeCatalog } from "./runtimeAuthority.server";
import { electronicsDecisionFingerprint } from "./decision";
import { electronicsPayloadHash, type ElectronicsConversationStore } from "./persistence";
import type { ElectronicsConversationState, ElectronicsDecisionCard, ElectronicsLedgerEvent, ElectronicsRuntimeOutcome } from "./runtimeContracts";
import { assessCandidateFactMateriality } from "../xpy/questionGuidance";
type Authority = { readonly policy: ElectronicsCategoryPolicyArtifact; readonly catalog: ElectronicsRuntimeCatalog };
type Proposal = { readonly kind: "SET" | "CORRECT" | "CLEAR"; readonly conceptId: string; readonly value?: unknown } | { readonly kind: "BUDGET"; readonly maximumTry: number } | { readonly kind: "BUDGET_OFF" } | { readonly kind: "EXACT_PRODUCT"; readonly exactProductId: string };
export type ElectronicsTurnResult = { readonly status: "OK"; readonly outcome: ElectronicsRuntimeOutcome; readonly state: ElectronicsConversationState; readonly replayed: boolean } | { readonly status: "STATE_UNAVAILABLE" | "MESSAGE_PAYLOAD_CONFLICT" | "REVISION_CONFLICT" | "AUTHORITY_MISMATCH" | "INTEGRITY_FAILURE" };
const activeEvents = (state: ElectronicsConversationState) => { const retired = new Set(state.ledger.filter(row => row.supersedesEventId).map(row => row.supersedesEventId)); return state.ledger.filter(row => row.status === "ACCEPTED_EXPLICIT" && !retired.has(row.eventId)); };
const SMARTPHONE_EVIDENCE_BY_CONCEPT: Readonly<Record<string, readonly string[]>> = Object.freeze({
  OS_SUPPORT: ["manufacturer_support_years", "security_support_years"],
  CELLULAR_BANDS: ["cellular_generation"],
  CAMERA: ["optical_image_stabilization", "camera_configuration"],
  BATTERY: ["battery_mah", "charging_watts"],
});
const catalogCandidates = (categoryId: ElectronicsCategoryId, authority: Authority) => authority.catalog.products.filter(row => row.categoryId === categoryId).map(row => ({ candidateId: row.exactProductId, facts: Object.fromEntries(row.facts.map(fact => [fact.key, fact.value])) }));
const materialQuestions = (categoryId: ElectronicsCategoryId, policy: ElectronicsCategoryPolicyArtifact["payload"]["categories"][number], authority: Authority) => {
  const questions = categoryId === "HEADPHONES" ? policy.questionPlan.filter(question => question.targetConcept !== "MICROPHONE") : policy.questionPlan;
  if (categoryId !== "SMARTPHONE") return questions;
  const candidates = catalogCandidates(categoryId, authority);
  return questions.map(question => ({ question, assessment: assessCandidateFactMateriality(candidates, SMARTPHONE_EVIDENCE_BY_CONCEPT[question.targetConcept] ?? []) }))
    .filter(row => row.assessment.material)
    .sort((left, right) => right.assessment.impact - left.assessment.impact || left.question.priority - right.question.priority || left.question.questionKey.localeCompare(right.question.questionKey))
    .map(row => row.question);
};
export function createElectronicsConversationState(authority: Authority, conversationId: string, categoryId: ElectronicsCategoryId, now = new Date()): ElectronicsConversationState { return { conversationId, schemaVersion: "electronics-conversation/v1", revision: 0, departmentId: "ELECTRONICS", categoryId, pinnedCatalogRelease: authority.catalog.releaseVersion, pinnedCatalogDigest: authority.catalog.releaseDigest, pinnedPolicyVersion: authority.policy.payload.policyVersion, pinnedPolicyDigest: authority.policy.policyDigest, ledger: [], askedQuestionKeys: [], personaSignals: [], budget: { mode: "NEEDS_ONLY" }, ended: false, createdAt: now.toISOString(), updatedAt: now.toISOString() }; }
export async function bootstrapElectronicsConversation(input: { readonly store: ElectronicsConversationStore; readonly authority: Authority; readonly conversationId: string; readonly categoryId: ElectronicsCategoryId; readonly messageId: string; readonly now?: Date }): Promise<ElectronicsTurnResult> { if (!ELECTRONICS_CATEGORY_IDS.includes(input.categoryId)) return { status: "INTEGRITY_FAILURE" }; const state = createElectronicsConversationState(input.authority, input.conversationId, input.categoryId, input.now), policy = input.authority.policy.payload.categories.find(row => row.categoryId === input.categoryId)!; const question = materialQuestions(input.categoryId, policy, input.authority)[0]; const next: ElectronicsConversationState = question ? { ...state, revision: 1, askedQuestionKeys: [question.questionKey], lastQuestionKey: question.questionKey, pendingQuestionKey: question.questionKey } : { ...state, revision: 1 }; const label = ELECTRONICS_CATEGORY_REGISTRY.find((row) => row.categoryId === input.categoryId)!.publicLabelTr; const outcome = question ? { ...questionOutcome(next, question), message: electronicsWelcomeText(input.categoryId, label, policy) } : nonDominatedOutcome(next, input.authority); const committed = await input.store.commit({ expectedRevision: 0, messageId: input.messageId, payloadHash: electronicsPayloadHash({ action: "CREATE", categoryId: input.categoryId }), nextState: next, events: [], outcomeKind: "CONVERSATION_BOOTSTRAPPED", publicOutcome: outcome }); return committed.status === "OK" ? { status: "OK", outcome: committed.outcome.publicOutcome!, state: committed.outcome.state, replayed: committed.outcome.state.revision !== 1 } : { status: committed.status }; }
export async function runElectronicsTurn(input: { readonly store: ElectronicsConversationStore; readonly authority: Authority; readonly conversationId: string; readonly messageId: string; readonly expectedRevision: number; readonly message: string; readonly now?: Date }): Promise<ElectronicsTurnResult> { const runtime = bindXpyRuntime(requireXpyDomainPack("ELECTRONICS"), input.authority.catalog.categories[0]!.categoryId); const payloadFingerprint = electronicsPayloadHash({ action: "TURN", message: input.message }); return executeValidatedTurn<ElectronicsConversationState, Proposal, ElectronicsLedgerEvent, ElectronicsRuntimeOutcome, ElectronicsTurnResult>({ runtime, expectedRevision: input.expectedRevision, messageId: input.messageId, payloadFingerprint, load: async () => { const found = await input.store.load(input.conversationId); if (!found) return null; const stored = found.messages[input.messageId]; return { state: found.state, ...(stored ? { replay: { payloadFingerprint: stored.payloadHash, outcome: stored.outcome.publicOutcome!, state: stored.outcome.state } } : {}) }; }, authorityMatches: state => state.pinnedCatalogDigest === input.authority.catalog.releaseDigest && state.pinnedPolicyDigest === input.authority.policy.policyDigest, propose: state => propose(input.message, state, input.authority), validate: proposals => validateProposals(proposals, input.authority), reduce: (state, proposals) => reduceTurn(state, proposals, input.message, input.messageId, input.now ?? new Date(), input.authority), isResult: value => typeof value === "object" && value !== null && "status" in value, commit: async update => { const result = await input.store.commit({ expectedRevision: update.expectedRevision, messageId: update.messageId, payloadHash: update.payloadFingerprint, nextState: update.state, events: update.events, outcomeKind: "CONTEXT_MUTATED", publicOutcome: update.outcome }); return result.status === "OK" ? { status: "OK" as const, outcome: result.outcome.publicOutcome!, state: result.outcome.state, replayed: false } : { status: result.status }; }, unavailable: () => ({ status: "STATE_UNAVAILABLE" }), payloadConflict: () => ({ status: "MESSAGE_PAYLOAD_CONFLICT" }), revisionConflict: () => ({ status: "REVISION_CONFLICT" }), authorityMismatch: () => ({ status: "AUTHORITY_MISMATCH" }), invalid: () => ({ status: "INTEGRITY_FAILURE" }), replay: stored => ({ status: "OK", outcome: stored.outcome, state: stored.state, replayed: true }) }); }
function propose(message: string, state: ElectronicsConversationState, authority: Authority): Proposal[] { const normalized = message.trim().toLocaleLowerCase("tr-TR"), product = authority.catalog.products.find(row => row.categoryId === state.categoryId && (normalized.includes(row.exactProductId.toLocaleLowerCase("tr-TR")) || normalized.includes(row.modelCode.toLocaleLowerCase("tr-TR")))); if (product) return [{ kind: "EXACT_PRODUCT", exactProductId: product.exactProductId }]; if (/bütçe\s+filtresini\s+(?:kapat|kullanma)/u.test(normalized)) return [{ kind: "BUDGET_OFF" }]; const amount = normalized.match(/([\d.]+)\s*(?:tl|₺)/u); if (/bütçe.*(?:filtre|ele|sınır)/u.test(normalized) && amount) return [{ kind: "BUDGET", maximumTry: Number(amount[1]!.replaceAll(".", "")) }]; const categoryPolicy = authority.policy.payload.categories.find(row => row.categoryId === state.categoryId)!, pending = categoryPolicy.questionPlan.find(row => row.questionKey === state.pendingQuestionKey); let concept = pending?.targetConcept; if (/ilk\s+tercih/iu.test(normalized)) concept = activeEvents(state)[0]?.conceptId; if (!concept) return []; if (/(?:temizle|sil|unut)/u.test(normalized)) return [{ kind: "CLEAR", conceptId: concept }]; const value = /(?:önemli değil|fark etmez)/u.test(normalized) ? "NOT_IMPORTANT" : /(?:bilmiyorum|emin değilim)/u.test(normalized) ? "UNKNOWN" : /(?:önemli|istiyorum|evet)/u.test(normalized) ? "IMPORTANT" : undefined; return value ? [{ kind: /düzelt/u.test(normalized) ? "CORRECT" : "SET", conceptId: concept, value }] : []; }
function validateProposals(proposals: readonly Proposal[], authority: Authority) { const concepts = new Set(authority.policy.payload.categories.flatMap(row => row.acceptedContextConcepts)); return proposals.some(row => "conceptId" in row && !concepts.has(row.conceptId) || row.kind === "EXACT_PRODUCT" && !authority.catalog.products.some(product => product.exactProductId === row.exactProductId) || row.kind === "BUDGET" && (!Number.isFinite(row.maximumTry) || row.maximumTry <= 0)) ? { kind: "INVALID" as const } : { kind: "VALID" as const, proposals }; }
function reduceTurn(state: ElectronicsConversationState, proposals: readonly Proposal[], message: string, messageId: string, now: Date, authority: Authority) { const revision = state.revision + 1, createdAt = now.toISOString(), policy = authority.policy.payload.categories.find(row => row.categoryId === state.categoryId)!; if (mentionsOtherCategory(message, state.categoryId)) return { state: { ...state, revision, updatedAt: createdAt }, events: [], outcome: { kind: "UNSUPPORTED", message: `${policy.publicLabelTr} görüşmesindeyiz; başka kategori için ayrı bir Elektronik görüşmesi başlatmalısın.`, contextRevision: revision } as ElectronicsRuntimeOutcome }; const informational = isInformational(message); if (informational && !proposals.length) return { state: { ...state, revision, updatedAt: createdAt }, events: [], outcome: { kind: "RESPOND", message: electronicsKnowledgeAnswer(state.categoryId, policy.publicLabelTr, policy), contextRevision: revision } as ElectronicsRuntimeOutcome };
  const ledger = [...state.ledger]; let budget = state.budget, selectedId: string | undefined; const events: ElectronicsLedgerEvent[] = []; for (const proposal of proposals) { if (proposal.kind === "BUDGET") { budget = { mode: "BUDGET_AS_DECISION_FILTER", maximumTry: proposal.maximumTry, sourceMessageId: messageId }; continue; } if (proposal.kind === "BUDGET_OFF") { budget = { mode: "NEEDS_ONLY" }; continue; } if (proposal.kind === "EXACT_PRODUCT") { selectedId = proposal.exactProductId; continue; } const active = activeEvents({ ...state, ledger }).find(row => row.conceptId === proposal.conceptId); if (active && proposal.kind === "SET" && active.normalizedValue !== proposal.value) return { state: { ...state, revision, updatedAt: createdAt }, events: [], outcome: { kind: "CLARIFY", questionKey: `CONTRADICTION:${proposal.conceptId}`, message: "Bu tercih daha önce farklı kaydedilmişti. Değiştirmek istiyorsan bunun bir düzeltme olduğunu belirtir misin?", contextRevision: revision } as ElectronicsRuntimeOutcome }; if (active) { const terminal: ElectronicsLedgerEvent = { eventId: randomUUID(), conceptId: proposal.conceptId, normalizedValue: null, sourceMessageId: messageId, status: proposal.kind === "CLEAR" ? "CLEARED" : "SUPERSEDED", authority: "USER_EXPLICIT", decisionUse: "NONE", supersedesEventId: active.eventId, createdRevision: revision, createdAt }; ledger.push(terminal); events.push(terminal); } if (proposal.kind !== "CLEAR") { const event: ElectronicsLedgerEvent = { eventId: randomUUID(), conceptId: proposal.conceptId, normalizedValue: proposal.value, sourceMessageId: messageId, status: "ACCEPTED_EXPLICIT", authority: "USER_EXPLICIT", decisionUse: proposal.value === "IMPORTANT" ? "QUESTION_INPUT" : "NONE", createdRevision: revision, createdAt }; ledger.push(event); events.push(event); } }
  let next: ElectronicsConversationState = { ...state, revision, ledger, budget, pendingQuestionKey: undefined, decisionRecord: undefined, updatedAt: createdAt }; const acceptedConceptIds = new Set(activeEvents(next).map(row => row.conceptId)), sufficient = policy.minimumAcceptedContext.every(concept => acceptedConceptIds.has(concept)); if (selectedId && sufficient && budget?.mode !== "BUDGET_AS_DECISION_FILTER") { const card = authorizeCard(next, selectedId, authority); next = { ...next, decisionRecord: card }; return { state: next, events, outcome: { kind: "DECISION_READY", message: `${card.manufacturer} ${card.modelCode}, açıkça seçtiğin exact yapılandırma olarak doğrulandı.`, card, decisionFingerprint: card.authorizationFingerprint, contextRevision: revision, budgetEligibility: "NOT_ENABLED" } as ElectronicsRuntimeOutcome }; } if (selectedId && sufficient && budget?.mode === "BUDGET_AS_DECISION_FILTER") { const product = authority.catalog.products.find(row => row.exactProductId === selectedId)!; return { state: next, events, outcome: { kind: "CLARIFY", questionKey: "BUDGET_ELIGIBILITY_UNKNOWN", message: "Bu ürün için taze doğrulanmış fiyat yok; bütçeye uygunluğunu bilinmiyor olarak koruyorum ve karar kartı yetkilendirmiyorum.", candidateSummaries: [{ manufacturer: product.manufacturer, modelCode: product.modelCode }], budgetEligibility: "BUDGET_ELIGIBILITY_UNKNOWN", contextRevision: revision } as ElectronicsRuntimeOutcome }; }
  const active = activeEvents(next), answered = new Set(active.map(row => row.conceptId)), cleared = new Set(next.ledger.filter(row => row.status === "CLEARED").map(row => row.conceptId)); const question = materialQuestions(state.categoryId, policy, authority).find(row => !answered.has(row.targetConcept) && (!next.askedQuestionKeys.includes(row.questionKey) || cleared.has(row.targetConcept))); if (question) { next = { ...next, askedQuestionKeys: [...new Set([...next.askedQuestionKeys, question.questionKey])], lastQuestionKey: question.questionKey, pendingQuestionKey: question.questionKey }; return { state: next, events, outcome: questionOutcome(next, question) }; }
  return { state: next, events, outcome: nonDominatedOutcome(next, authority) }; }
function nonDominatedOutcome(state: ElectronicsConversationState, authority: Authority): ElectronicsRuntimeOutcome { const candidates = authority.catalog.products.filter(row => row.categoryId === state.categoryId).sort((a, b) => a.exactProductId.localeCompare(b.exactProductId)); return { kind: "CLARIFY", questionKey: "NON_DOMINATED_SET", message: "Doğrulanmış bilgiler bu modeller arasında maddi bir fark göstermiyor. Tek bir kazanan varsaymadan adayları birlikte koruyorum.", candidateSummaries: candidates.map(row => ({ manufacturer: row.manufacturer, modelCode: row.modelCode })), uncertainty: ["Bazı karşılaştırma bilgileri bilinmiyor.", "Yeni bir soru ancak doğrulanmış bilgiler adayları gerçekten ayırırsa sorulur."], contextRevision: state.revision, budgetEligibility: state.budget?.mode === "BUDGET_AS_DECISION_FILTER" ? "BUDGET_ELIGIBILITY_UNKNOWN" : "NOT_ENABLED" }; }
function questionOutcome(state: ElectronicsConversationState, question: ElectronicsCategoryPolicyArtifact["payload"]["categories"][number]["questionPlan"][number]): ElectronicsRuntimeOutcome { const label = ELECTRONICS_CATEGORY_REGISTRY.find((row) => row.categoryId === state.categoryId)!.publicLabelTr; return { kind: "ASK", questionKey: question.questionKey, message: electronicsQuestionText(state.categoryId, label, question.targetConcept), choices: question.choicesTr.map((choiceLabel, index) => ({ value: ["IMPORTANT", "NOT_IMPORTANT", "UNKNOWN"][index]!, label: choiceLabel })), contextRevision: state.revision }; }
function authorizeCard(state: ElectronicsConversationState, exactProductId: string, authority: Authority): ElectronicsDecisionCard { const product = authority.catalog.products.find(row => row.categoryId === state.categoryId && row.exactProductId === exactProductId); if (!product) throw new Error("EXACT_PRODUCT_NOT_IN_ACTIVE_CATEGORY"); const accepted = activeEvents(state); const core = { exactProductId, categoryId: state.categoryId, manufacturer: product.manufacturer, modelCode: product.modelCode, configurationIdentity: product.configurationIdentity, rationale: accepted.map(event => ({ acceptedConcept: event.conceptId, evidenceFactIds: product.facts.slice(0, 2).map(fact => fact.factId), explanationTr: `${humanize(event.conceptId)} tercihi, doğrulanmış ürün bilgileriyle birlikte değerlendirildi.` })), technicalEvidence: product.facts.slice(0, 6).map(fact => ({ label: humanize(fact.key), value: String(fact.value) })), dailyLifeInterpretation: accepted.filter(event => event.normalizedValue === "IMPORTANT").map(event => `${humanize(event.conceptId)} önceliğin karar gerekçesinde korundu.`), authority: { policyDigest: authority.policy.policyDigest, catalogReleaseDigest: authority.catalog.releaseDigest, contextRevision: state.revision } }; return { ...core, authorizationFingerprint: electronicsDecisionFingerprint(core) }; }
export function recoverElectronicsConversation(authority: Authority, found: Awaited<ReturnType<ElectronicsConversationStore["load"]>>) { if (!found) return null; if (found.state.pinnedCatalogDigest !== authority.catalog.releaseDigest || found.state.pinnedPolicyDigest !== authority.policy.policyDigest) return { kind: "FAILED_CLOSED" as const, message: "Bağlı Electronics yetkisi değişmiş; karar yeniden hesaplanmalıdır." }; const latest = Object.values(found.messages).find(row => row.committedRevision === found.state.revision)?.outcome.publicOutcome; if (latest?.kind === "DECISION_READY" && (!found.state.decisionRecord || latest.decisionFingerprint !== found.state.decisionRecord.authorizationFingerprint || !authority.catalog.products.some(row => row.exactProductId === found.state.decisionRecord?.exactProductId))) return { kind: "FAILED_CLOSED" as const, message: "Karar yetkisi doğrulanamadı." }; return { kind: "CONVERSATION" as const, conversationId: found.state.conversationId, revision: found.state.revision, categoryId: found.state.categoryId, outcome: latest }; }
const isInformational = (message: string) => /(?:bilgim yok|neye dikkat|nedir|nasıl çalışır|hakkında bilgi)/iu.test(message); const humanize = (value: string) => value.replaceAll("_", " ").toLocaleLowerCase("tr-TR"); function mentionsOtherCategory(message: string, current: ElectronicsCategoryId) { const normalized = message.toLocaleLowerCase("tr-TR"); return ELECTRONICS_CATEGORY_REGISTRY.some(row => row.categoryId !== current && normalized.includes(row.publicLabelTr.toLocaleLowerCase("tr-TR")) && /(?:arıyorum|almak|istiyorum)/u.test(normalized)); }
