import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { loadActiveElectronicsCategoryPolicy } from "./categoryPolicyLoader.server";
import { ELECTRONICS_CATEGORY_IDS, type ElectronicsCategoryId } from "./architectureBaseline";
import { XPY_RUNTIME_DIGEST, XPY_RUNTIME_VERSION } from "../xpy/runtimeContract";

export interface ElectronicsRuntimeCatalog {
  readonly schemaVersion: "electronics-runtime-catalog/v1"; readonly releaseVersion: string; readonly departmentId: "ELECTRONICS"; readonly market: "TR"; readonly lifecycle: "FROZEN";
  readonly policyVersion: string; readonly policyDigest: `sha256:${string}`; readonly runtimeVersion: typeof XPY_RUNTIME_VERSION; readonly runtimeDigest: typeof XPY_RUNTIME_DIGEST; readonly domainPackId: "electronics-stage1/v1";
  readonly evidenceChain: readonly { readonly wave: number; readonly releaseDigest: `sha256:${string}` }[];
  readonly categories: readonly { readonly categoryId: ElectronicsCategoryId; readonly exactProductIds: readonly string[] }[];
  readonly products: readonly { readonly exactProductId: string; readonly categoryId: ElectronicsCategoryId; readonly manufacturer: string; readonly modelCode: string; readonly configurationIdentity: string; readonly evidenceReleaseDigest: `sha256:${string}`; readonly facts: readonly { readonly factId: string; readonly key: string; readonly value: unknown; readonly sourceId: string; readonly locator: string }[]; readonly unknownCodes: readonly string[]; readonly personaEffect: "NONE"; readonly commerceEffect: "NONE" }[];
  readonly releaseDigest: `sha256:${string}`;
}
const sha = (raw: string | Buffer) => `sha256:${createHash("sha256").update(raw).digest("hex")}`;
export function validateElectronicsRuntimeCatalog(catalog: ElectronicsRuntimeCatalog, policyDigest: string): readonly string[] { const issues: string[] = [], { releaseDigest, ...unsigned } = catalog; if (releaseDigest !== `sha256:${createHash("sha256").update(JSON.stringify(canonical(unsigned))).digest("hex")}`) issues.push("CATALOG_DIGEST_MISMATCH"); if (catalog.policyDigest !== policyDigest || catalog.runtimeVersion !== XPY_RUNTIME_VERSION || catalog.runtimeDigest !== XPY_RUNTIME_DIGEST) issues.push("AUTHORITY_BINDING_MISMATCH"); const ids = catalog.categories.map(row => row.categoryId); if (ids.length !== 24 || new Set(ids).size !== 24 || ELECTRONICS_CATEGORY_IDS.some(id => !ids.includes(id)) || catalog.products.some(row => !ids.includes(row.categoryId) || !row.facts.length || row.personaEffect !== "NONE" || row.commerceEffect !== "NONE")) issues.push("CATALOG_MEMBERSHIP_OR_EVIDENCE_INVALID"); return Object.freeze(issues); }
export function loadActiveElectronicsRuntimeAuthority(root = process.cwd()): { readonly policy: ReturnType<typeof loadActiveElectronicsCategoryPolicy>; readonly catalog: ElectronicsRuntimeCatalog; readonly catalogArtifactSha256: string } {
  const policy = loadActiveElectronicsCategoryPolicy(root); const pointer = JSON.parse(readFileSync(path.join(root, "data/production/electronics/runtime/active.json"), "utf8")) as { lifecycle?: string; runtimeActive?: boolean; productionDeployed?: boolean; catalogFile?: string; catalogArtifactSha256?: string; catalogReleaseDigest?: string; policyDigest?: string; manifestFile?: string; manifestSha256?: string; activationEventFile?: string; activationEventSha256?: string; deploymentEventFile?: string; deploymentEventSha256?: string };
  if (pointer.lifecycle !== "ACTIVE" || pointer.runtimeActive !== true || pointer.productionDeployed !== true || typeof pointer.catalogFile !== "string" || typeof pointer.catalogArtifactSha256 !== "string" || typeof pointer.manifestFile !== "string" || typeof pointer.manifestSha256 !== "string" || typeof pointer.activationEventFile !== "string" || typeof pointer.activationEventSha256 !== "string" || typeof pointer.deploymentEventFile !== "string" || typeof pointer.deploymentEventSha256 !== "string") throw new Error("ELECTRONICS_RUNTIME_POINTER_INVALID");
  const raw = readFileSync(path.join(root, pointer.catalogFile)); if (sha(raw) !== pointer.catalogArtifactSha256) throw new Error("ELECTRONICS_RUNTIME_CATALOG_CHECKSUM_MISMATCH"); const catalog = JSON.parse(raw.toString("utf8")) as ElectronicsRuntimeCatalog;
  if (validateElectronicsRuntimeCatalog(catalog, policy.policyDigest).length || pointer.catalogReleaseDigest !== catalog.releaseDigest || pointer.policyDigest !== policy.policyDigest) throw new Error("ELECTRONICS_RUNTIME_AUTHORITY_MISMATCH");
  const manifestRaw = readFileSync(path.join(root, pointer.manifestFile)); if (sha(manifestRaw) !== pointer.manifestSha256) throw new Error("ELECTRONICS_RUNTIME_MANIFEST_CHECKSUM_MISMATCH"); const manifest = JSON.parse(manifestRaw.toString("utf8")) as { releaseDigest?: string; policyDigest?: string; productionDeployed?: boolean }; if (manifest.releaseDigest !== catalog.releaseDigest || manifest.policyDigest !== policy.policyDigest || manifest.productionDeployed !== false) throw new Error("ELECTRONICS_RUNTIME_MANIFEST_INVALID");
  const eventRaw = readFileSync(path.join(root, pointer.activationEventFile)); if (sha(eventRaw) !== pointer.activationEventSha256) throw new Error("ELECTRONICS_RUNTIME_ACTIVATION_CHECKSUM_MISMATCH"); const event = JSON.parse(eventRaw.toString("utf8")) as { catalogReleaseDigest?: string; policyDigest?: string; productionMigrationApplied?: boolean; deployed?: boolean }; if (event.catalogReleaseDigest !== catalog.releaseDigest || event.policyDigest !== policy.policyDigest || event.productionMigrationApplied !== false || event.deployed !== false) throw new Error("ELECTRONICS_RUNTIME_ACTIVATION_INVALID");
  const deploymentRaw = readFileSync(path.join(root, pointer.deploymentEventFile)); if (sha(deploymentRaw) !== pointer.deploymentEventSha256) throw new Error("ELECTRONICS_RUNTIME_DEPLOYMENT_CHECKSUM_MISMATCH"); const deployment = JSON.parse(deploymentRaw.toString("utf8")) as { catalogReleaseDigest?: string; policyDigest?: string; migrationSha256?: string; migrationApplied?: boolean; deploymentReady?: boolean }; if (deployment.catalogReleaseDigest !== catalog.releaseDigest || deployment.policyDigest !== policy.policyDigest || deployment.migrationSha256 !== "sha256:c508311e0d268432f16285802079d2f458ded9a32ab75a185733ac80f34d436f" || deployment.migrationApplied !== true || deployment.deploymentReady !== true) throw new Error("ELECTRONICS_RUNTIME_DEPLOYMENT_INVALID");
  return { policy, catalog, catalogArtifactSha256: pointer.catalogArtifactSha256 };
}
function canonical(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonical); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, canonical(item)])); return value; }
