// Generated by scripts/sync-active-vehicle-persona-safe-traits.ts. Do not edit manually.
export { default as activeVehiclePersonaSafeTraitRelease } from "./releases/v1.0.2-catalog-v0.55.1-2026-08-16/vehicle-persona-safe-traits.json";
export { default as activeVehiclePersonaSafeTraitManifest } from "./releases/v1.0.2-catalog-v0.55.1-2026-08-16/manifest.json";
export const activeVehiclePersonaSafeTraitReleaseVersion = "v1.0.2-catalog-v0.55.1-2026-08-16";
