import { describe, expect, it } from "vitest";
import safePersonaRelease from "@/data/production/personas/safe-traits/releases/v1.0.0-catalog-v0.55.0-2026-08-16/vehicle-persona-safe-traits.json";
import type { VehiclePersonaSafeTraitRelease } from "@/types/vehiclePersonaSafeTraits";
import { loadActiveProductionSnapshotForTest } from "../catalog/productionSnapshotFixture.testSupport";
import { loadProductionDecisionLayers, projectProductionPersonaLayer, validateDailyLifeActivationAuthority, type DailyLifeActivationAuthorityInput } from "./productionAdapter.server";

describe("production decision layer adapter", () => {
  it("loads active compatible layers with coverage derived from the pinned catalog snapshot", async () => { const catalog = await loadActiveProductionSnapshotForTest(); expect(catalog.status).toBe("READY"); if (catalog.status !== "READY") return; const expectedCoverage = catalog.snapshot.variants.length; const result = await loadProductionDecisionLayers(catalog.snapshot); expect(result.dailyLife.status, JSON.stringify(result.diagnostics)).toBe("READY"); if (result.dailyLife.status === "READY") { expect(result.dailyLife.mappings).toHaveLength(117); expect(result.dailyLife.candidateCoverage).toBe(expectedCoverage); } expect(result.persona.status, JSON.stringify(result.diagnostics)).toBe("READY"); if (result.persona.status !== "UNAVAILABLE") { expect(result.persona.technicalCompatibility).toBe("READY"); expect(result.persona.editorialApproval).toBe("OWNER_APPROVED"); expect(result.persona.rankingEnabled).toBe(true); expect(result.persona.candidateCoverage).toBe(expectedCoverage); expect(result.persona.approvedFamilyCount).toBe(catalog.snapshot.familyIndex.size); expect(result.persona.signals.length).toBeGreaterThan(0); expect(result.persona.signals.every((signal) => signal.authority === "OWNER_EDITORIAL" && signal.decisionUse === "SOFT_PREFERENCE_ONLY" && signal.matchStrength === 1)).toBe(true); expect(JSON.stringify(result.persona)).not.toMatch(/brandPersona|seriesEditorial|HARD_FILTER/u); } expect(result.diagnostics).toEqual([]); });
  it("projects signals only after explicit family owner approval", () => { const release = safePersonaRelease as VehiclePersonaSafeTraitRelease; const family = release.families.find((item) => item.traits.length > 0)!; const approved = { ...release, families: release.families.map((item) => item.familyId === family.familyId ? { ...item, reviewStatus: "OWNER_APPROVED" as const } : item) }; const result = projectProductionPersonaLayer(approved, "sha256:test"); expect(result.status).toBe("READY"); expect(result.rankingEnabled).toBe(true); expect(result.approvedFamilyCount).toBe(1); expect(result.signals.length).toBeGreaterThan(0); expect(result.signals.every((signal) => signal.authority === "OWNER_EDITORIAL" && signal.decisionUse === "SOFT_PREFERENCE_ONLY")).toBe(true); });
});

describe("Daily-Life activation lifecycle authority", () => {
  const valid: DailyLifeActivationAuthorityInput = { manifestValidationStatus:"VALIDATED_PRE_ACTIVATION",manifestActivationPerformed:false,manifestReleaseId:"daily-v1",manifestCatalogRelease:"v0.55.4",manifestCatalogFingerprint:"sha256:catalog",manifestPayloadChecksum:"sha256:payload",actualPayloadChecksum:"sha256:payload",pointerState:"ACTIVE",pointerReleaseId:"daily-v1",pointerCatalogRelease:"v0.55.4",pointerChecksum:"sha256:pointer",activeCatalogRelease:"0.55.4",activeCatalogFingerprint:"sha256:catalog",activationEvent:{activationEventId:"event-1",releases:{dailyLife:"daily-v1"},catalogFingerprint:"sha256:catalog"},activationResult:{status:"ACTIVATED_AND_POST_VALIDATED",activationEventId:"event-1",releases:{dailyLife:"daily-v1"},pointerChecksums:{dailyPointer:"sha256:pointer"},rollbackPerformed:false},postValidation:{status:"PASSED"},rollbackResultPresent:false };
  it("accepts a complete active append-only lifecycle chain",()=>expect(validateDailyLifeActivationAuthority(valid)).toEqual([]));
  it.each([
    ["event missing",{activationEvent:undefined},"DAILY_LIFE_ACTIVATION_CHAIN_MISSING"],
    ["event release mismatch",{activationEvent:{...valid.activationEvent!,releases:{dailyLife:"other"}}},"DAILY_LIFE_ACTIVATION_RELEASE_MISMATCH"],
    ["pointer checksum mismatch",{activationResult:{...valid.activationResult!,pointerChecksums:{dailyPointer:"sha256:other"}}},"DAILY_LIFE_ACTIVATION_POINTER_CHECKSUM_MISMATCH"],
    ["post-validation failed",{postValidation:{status:"FAILED"}},"DAILY_LIFE_POST_VALIDATION_NOT_PASSED"],
    ["payload checksum mismatch",{actualPayloadChecksum:"sha256:other"},"DAILY_LIFE_PAYLOAD_CHECKSUM_MISMATCH"],
    ["catalog fingerprint mismatch",{activeCatalogFingerprint:"sha256:other"},"DAILY_LIFE_CATALOG_COMPATIBILITY_MISMATCH"],
    ["attempt rolled back",{rollbackResultPresent:true},"DAILY_LIFE_ACTIVATION_ROLLED_BACK"],
    ["manifest only",{pointerState:"INACTIVE",activationEvent:undefined,activationResult:undefined,postValidation:undefined},"DAILY_LIFE_ACTIVE_POINTER_MISMATCH"],
  ])("rejects %s",(_name,override,expected)=>expect(validateDailyLifeActivationAuthority({...valid,...override} as DailyLifeActivationAuthorityInput)).toContain(expected));
});
