import { describe, expect, it } from "vitest";
import safePersonaRelease from "@/data/production/personas/safe-traits/releases/v1.0.0-catalog-v0.55.0-2026-08-16/vehicle-persona-safe-traits.json";
import type { VehiclePersonaSafeTraitRelease } from "@/types/vehiclePersonaSafeTraits";
import { loadProductionCatalogSnapshotForTest } from "../catalog/productionSnapshotFixture.testSupport";
import { loadProductionDecisionLayers, projectProductionPersonaLayer } from "./productionAdapter.server";

describe("production decision layer adapter", () => {
  it("loads the active owner-approved release while preserving technical compatibility and soft-only authority", async () => { const catalog = await loadProductionCatalogSnapshotForTest(new Date("2026-08-16T19:33:14.000Z")); expect(catalog.status).toBe("READY"); if (catalog.status !== "READY") return; const result = await loadProductionDecisionLayers(catalog.snapshot); expect(result.dailyLife.status, JSON.stringify(result.diagnostics)).toBe("READY"); if (result.dailyLife.status === "READY") { expect(result.dailyLife.mappings).toHaveLength(117); expect(result.dailyLife.candidateCoverage).toBe(577); } expect(result.persona.status, JSON.stringify(result.diagnostics)).toBe("READY"); if (result.persona.status !== "UNAVAILABLE") { expect(result.persona.technicalCompatibility).toBe("READY"); expect(result.persona.editorialApproval).toBe("OWNER_APPROVED"); expect(result.persona.rankingEnabled).toBe(true); expect(result.persona.candidateCoverage).toBe(577); expect(result.persona.approvedFamilyCount).toBe(397); expect(result.persona.signals.length).toBeGreaterThan(0); expect(result.persona.signals.every((signal) => signal.authority === "OWNER_EDITORIAL" && signal.decisionUse === "SOFT_PREFERENCE_ONLY" && signal.matchStrength === 1)).toBe(true); expect(JSON.stringify(result.persona)).not.toMatch(/brandPersona|seriesEditorial|HARD_FILTER/u); } expect(result.diagnostics).toEqual([]); });
  it("projects signals only after explicit family owner approval", () => { const release = safePersonaRelease as VehiclePersonaSafeTraitRelease; const family = release.families.find((item) => item.traits.length > 0)!; const approved = { ...release, families: release.families.map((item) => item.familyId === family.familyId ? { ...item, reviewStatus: "OWNER_APPROVED" as const } : item) }; const result = projectProductionPersonaLayer(approved, "sha256:test"); expect(result.status).toBe("READY"); expect(result.rankingEnabled).toBe(true); expect(result.approvedFamilyCount).toBe(1); expect(result.signals.length).toBeGreaterThan(0); expect(result.signals.every((signal) => signal.authority === "OWNER_EDITORIAL" && signal.decisionUse === "SOFT_PREFERENCE_ONLY")).toBe(true); });
});
