import type { AppliancesConversationState } from "../contracts";
import { authorizeRecommendation, authorizationMatches, type AppliancesDecisionAuthorization } from "./authorize";
import type { RecommendationArtifact } from "./construct";
import type { RecommendationAuthority } from "./current.server";
import type { AppliancesDecisionCard } from "./publicCard";

export function projectAuthorizedAppliancesCard(bundle: RecommendationAuthority, state: AppliancesConversationState, artifact: RecommendationArtifact, authorization: AppliancesDecisionAuthorization): AppliancesDecisionCard {
  if (!authorizationMatches(authorization, authorizeRecommendation(bundle, state, artifact))) throw new Error("CARD_NOT_AUTHORIZED");
  return { schemaVersion: "appliances-public-card/v1", identity: artifact.exactProductIdentities[0], reasons: artifact.governedReasons, acceptedNeeds: artifact.userNeedsAddressed, nonSelectionNeeds: artifact.nonSelectionActiveAcceptedNeeds, technicalEvidence: artifact.technicalEvidenceUnits, capabilities: artifact.capabilityEvidenceUnits, dailyLife: artifact.dailyLifeInterpretationUnits, limitations: artifact.limitationsAndTradeoffs, disclosures: artifact.requiredDisclosures, price: artifact.priceCoverageAndFreshness, lifecycleAndMarket: artifact.lifecycleAndMarketApplicability, warranty: artifact.warrantyDisclosure, provenance: { authorizationFingerprint: authorization.authorityFingerprint, artifactFingerprint: artifact.deterministicArtifactFingerprint, catalog: artifact.catalogIdentityAndDigests, semantic: artifact.semanticRegistryIdentityAndDigest, selectionFingerprint: artifact.selectionResultFingerprint, constructionPolicyDigest: artifact.constructionPolicyDigest, questionPolicy: artifact.questionPolicyIdentityAndDigest, sufficiencyPolicy: artifact.sufficiencyPolicyIdentityAndDigest, selectionPolicy: artifact.candidateSelectionPolicyIdentityAndDigest, contextRevision: artifact.contextRevision, contextFingerprint: artifact.contextFingerprint, candidateEvaluationFingerprint: artifact.candidateEvaluationFingerprint, sufficiencyFingerprint: artifact.sufficiencyFingerprint, candidatePoolFingerprint: artifact.candidatePoolFingerprint } };
}
