import { describe, expect, it } from "vitest";
import type { UsedCarFieldAssertion } from "./evidence/contracts";
import { projectTenantPublicListings, type TenantPublicationSnapshot } from "./listing/publicationProjector";

const assertion = <T>(value:T): UsedCarFieldAssertion<T> => ({ value, status:"DEALER_DECLARED", sourceReferenceIds:["private"], assertedBy:"DEALER", observedAt:"2026-09-01T10:00:00Z", limitations:[] });
const gates = { dealerStatus:"PUBLISHING_ELIGIBLE" as const, identityVerified:true, contractActive:true, paymentCurrent:true, operationalReviewPassed:true, moderationEnabled:true };
const privateView = { inventoryUnitId:"unit-1", listingId:"listing-1", tenantId:"tenant-a", branchId:"branch-a", taxonomyVariantId:"variant-1", vinCiphertext:"cipher", vinFingerprint:"fingerprint", maskedVin:"***", stockNumber:"STK-1", modelYear:assertion(2022), mileageKm:assertion(40_000), color:assertion("Beyaz"), askingPriceTry:assertion(1_400_000), damageDisclosure:assertion<readonly string[]>([]), maintenanceHistory:assertion<readonly string[]>([]), warranty:assertion("Yok"), inspection:assertion("Eksik"), publicMediaUrls:[], sellerDisplayName:"Demo Satıcı", branchDisplayName:"Demo Şube" };
const media = { asset:{ id:"media-1", tenantId:"tenant-a", inventoryUnitId:"unit-1", kind:"VEHICLE_IMAGE" as const, state:"PUBLIC_RENDITION_READY" as const, storageClass:"PUBLIC_RENDITION" as const, declaredMimeType:"image/webp", detectedMimeType:"image/webp", byteSize:100_000, sha256:"sha256:test", malwareScan:"PASSED" as const, exifRemoved:true, piiReview:"PASSED" as const, identityReview:"PASSED" as const, rightsConfirmed:true, derivedFromAssetId:"original-1" }, publicUrl:"https://media.expiya.example/public/media-1.webp" };
const base: TenantPublicationSnapshot = { version:"used-cars-publication-snapshot/v1", tenantId:"tenant-a", snapshotAt:"2026-09-01T12:00:00Z", dealerGates:gates, listings:[{ lifecycle:{ status:"PUBLISHED", stockConfirmedAt:"2026-09-01T10:00:00Z", freshnessValidUntil:"2026-09-02T10:00:00Z", criticalConflictCount:0 }, privateView, media:[media] }] };

describe("atomic fail-closed public listing projector",()=>{
  it("publishes only a gate-eligible listing with fully safe media",()=>{const result=projectTenantPublicListings(base); expect(result.published).toHaveLength(1); expect(result.published[0].mediaUrls).toEqual([media.publicUrl]); expect(JSON.stringify(result.published)).not.toMatch(/cipher|fingerprint|tenant-a|private/);});
  it("removes every listing when any dealer gate closes",()=>{for(const mutation of [{dealerStatus:"SUSPENDED" as const},{identityVerified:false},{contractActive:false},{paymentCurrent:false},{operationalReviewPassed:false},{moderationEnabled:false}]){const result=projectTenantPublicListings({...base,dealerGates:{...gates,...mutation},listings:[...base.listings,{...base.listings[0],privateView:{...privateView,listingId:"listing-2"}}]}); expect(result.published).toEqual([]); expect(result.blockedListingIds).toEqual(["listing-1","listing-2"]); expect(result.failClosed).toBe(true);}});
  it("blocks stale, conflicted, cross-tenant and unsafe-media listings",()=>{const cases=[{...base.listings[0],lifecycle:{...base.listings[0].lifecycle,freshnessValidUntil:"2026-08-31T10:00:00Z"}},{...base.listings[0],lifecycle:{...base.listings[0].lifecycle,criticalConflictCount:1}},{...base.listings[0],privateView:{...privateView,tenantId:"tenant-b"}},{...base.listings[0],media:[{...media,asset:{...media.asset,malwareScan:"FAILED" as const}}]}]; for(const listing of cases){const result=projectTenantPublicListings({...base,listings:[listing]}); expect(result.published).toEqual([]); expect(result.failClosed).toBe(true);}});
});

