import { describe, expect, it } from "vitest";
import { fingerprintVehicleIdentifier, fingerprintVehicleIdentifierForFraud, normalizeVehicleIdentifier, projectIdentifierFreePublicReference, protectVehicleIdentifier, type IdentifierEncryptionProvider } from "./security/sensitiveVehicleIdentifiers";

const secret = new TextEncoder().encode("test-only-key-material-32-bytes-minimum");
const provider: IdentifierEncryptionProvider = { provider: "KMS_ENVELOPE", async encrypt({ plaintext, context }) { return { ciphertext: `test-ciphertext:${plaintext.byteLength}:${context.tenantId}`, keyVersion: "test-kms-v3" }; } };

describe("VIN and plate cryptographic boundary", () => {
  it("normalizes supported identifiers and rejects invalid VIN/plate", () => { expect(normalizeVehicleIdentifier("VIN", "wvw zzz 1jz 3w 386752")).toBe("WVWZZZ1JZ3W386752"); expect(normalizeVehicleIdentifier("PLATE", "34 abc 1234")).toBe("34ABC1234"); expect(() => normalizeVehicleIdentifier("VIN", "SHORT")).toThrow("INVALID_VIN"); expect(() => normalizeVehicleIdentifier("PLATE", "not-a-plate")).toThrow("INVALID_TR_PLATE"); });
  it("uses keyed tenant and field scoped fingerprints", () => { const base = { normalizedValue: "WVWZZZ1JZ3W386752", tenantId: "tenant-a", identifierType: "VIN" as const, fingerprintSecret: secret, fingerprintKeyVersion: "hmac-v2" }; const fingerprint = fingerprintVehicleIdentifier(base); expect(fingerprint).not.toContain(base.normalizedValue); expect(fingerprintVehicleIdentifier({ ...base, tenantId: "tenant-b" })).not.toBe(fingerprint); expect(fingerprintVehicleIdentifier({ ...base, identifierType: "CHASSIS_SERIAL" })).not.toBe(fingerprint); expect(() => fingerprintVehicleIdentifier({ ...base, fingerprintSecret: new Uint8Array(8) })).toThrow("FINGERPRINT_KEY_TOO_SHORT"); });
  it("returns versioned encryption and fingerprint envelopes without public identifiers", async () => { const protectedValue = await protectVehicleIdentifier({ tenantId: "tenant-a", inventoryUnitId: "unit-1", identifierType: "VIN", rawValue: "WVWZZZ1JZ3W386752", fingerprintSecret: secret, fingerprintKeyVersion: "hmac-v2", encryptionProvider: provider }); expect(protectedValue).toMatchObject({ encryptionKeyVersion: "test-kms-v3", fingerprintKeyVersion: "hmac-v2", publicDisplayAllowed: false }); const publicValue = projectIdentifierFreePublicReference(protectedValue); expect(publicValue).toEqual({ inventoryUnitId: "unit-1", identifierTypePresent: true }); expect(JSON.stringify(publicValue)).not.toMatch(/cipher|fingerprint|WVW|plate|vin/i); });
  it("supports a separate fraud-only cross-tenant blind index",()=>{const input={normalizedValue:"WVWZZZ1JZ3W386752",identifierType:"VIN" as const,fraudSecret:secret,fraudKeyVersion:"fraud-v1"};expect(fingerprintVehicleIdentifierForFraud(input)).toBe(fingerprintVehicleIdentifierForFraud(input));expect(fingerprintVehicleIdentifierForFraud(input)).not.toContain(input.normalizedValue);});
});
