import { describe, expect, it } from "vitest";
import { withVerifiedPartnerTransaction, type UsedCarsDbClient, type UsedCarsDbPool } from "./tenancy/transactionRunner";
import type { VerifiedPartnerSessionClaims } from "./tenancy/sessionContext";

const baseClaims: VerifiedPartnerSessionClaims = { source: "VERIFIED_IDENTITY_PROVIDER", tenantId: "11111111-1111-4111-8111-111111111111", actorId: "22222222-2222-4222-8222-222222222222", role: "DEALER_ADMIN", branchIds: ["33333333-3333-4333-8333-333333333333"], mfaVerified: true, sessionExpiresAt: "2026-09-01T20:00:00Z" };
function harness(rollbackFails=false) { const calls: Array<{ statement: string; parameters?: readonly unknown[] }> = []; let released = false; let releaseError:Error|undefined; const client: UsedCarsDbClient = { async query<T>(statement: string, parameters?: readonly unknown[]) { calls.push({ statement, parameters }); if(rollbackFails&&statement==="rollback")throw new Error("ROLLBACK_CONNECTION_FAILED"); return { ok: true } as T; }, release(error) { released = true; releaseError=error; } }; const pool: UsedCarsDbPool = { async connect() { return client; } }; return { calls, pool, released: () => released, releaseError:()=>releaseError }; }

describe("verified partner transaction runner", () => {
  it("sets tenant context locally before work and commits", async () => { const test = harness(); await withVerifiedPartnerTransaction({ pool: test.pool, claims: baseClaims, nowIso: "2026-09-01T18:00:00Z", work: tx => tx.query("select inventory_id from used_cars.inventory_units") }); expect(test.calls.map(call => call.statement)).toEqual(["begin", "select set_config($1, $2, true)", "select set_config($1, $2, true)", "select set_config($1, $2, true)", "select set_config($1, $2, true)", "select inventory_id from used_cars.inventory_units", "commit"]); expect(test.released()).toBe(true); });
  it("rolls back and releases when work fails", async () => { const test = harness(); await expect(withVerifiedPartnerTransaction({ pool: test.pool, claims: baseClaims, nowIso: "2026-09-01T18:00:00Z", work: async () => { throw new Error("WORK_FAILED"); } })).rejects.toThrow("WORK_FAILED"); expect(test.calls.at(-1)?.statement).toBe("rollback"); expect(test.released()).toBe(true); });
  it("prevents work from changing transaction or session context", async () => { for (const statement of ["SET app.tenant_id = 'other'", "reset all", "commit", "rollback"]) { const test = harness(); await expect(withVerifiedPartnerTransaction({ pool: test.pool, claims: baseClaims, nowIso: "2026-09-01T18:00:00Z", work: tx => tx.query(statement) })).rejects.toThrow("TRANSACTION_CONTROL_FORBIDDEN_IN_WORK"); expect(test.calls.slice(0, -1).some(call => call.statement === statement)).toBe(false); expect(test.calls.at(-1)?.statement).toBe("rollback"); } });
  it("does not reuse a previous request tenant context", async () => { const first = harness(); const second = harness(); await withVerifiedPartnerTransaction({ pool: first.pool, claims: baseClaims, nowIso: "2026-09-01T18:00:00Z", work: tx => tx.query("select 1") }); await withVerifiedPartnerTransaction({ pool: second.pool, claims: { ...baseClaims, tenantId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa" }, nowIso: "2026-09-01T18:00:00Z", work: tx => tx.query("select 1") }); expect(first.calls[1].parameters?.[1]).toBe(baseClaims.tenantId); expect(second.calls[1].parameters?.[1]).toBe("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"); expect(first.released()).toBe(true); expect(second.released()).toBe(true); });
  it("destroys a connection whose rollback failed",async()=>{const test=harness(true);await expect(withVerifiedPartnerTransaction({pool:test.pool,claims:baseClaims,nowIso:"2026-09-01T18:00:00Z",work:async()=>{throw new Error("WORK_FAILED");}})).rejects.toThrow("WORK_FAILED");expect(test.releaseError()?.message).toBe("ROLLBACK_CONNECTION_FAILED");});
});
