import { describe,expect,it } from "vitest";
import { evaluatePartnerSession,type AuthoritativePartnerAuthState,type PartnerSessionState } from "./security/sessionPolicy";
const session:PartnerSessionState={sessionId:"session-1",actorId:"actor-1",tenantId:"tenant-a",role:"DEALER_ADMIN",tenantAuthVersion:3,actorAuthVersion:7,issuedAt:1000,lastSeenAt:2000,lastRotatedAt:1900,mfaVerifiedAt:1950,expiresAt:20_000,revokedAt:null};
const auth:AuthoritativePartnerAuthState={tenantId:"tenant-a",role:"DEALER_ADMIN",tenantAuthVersion:3,actorAuthVersion:7,actorActive:true,tenantActive:true};
describe("partner session security policy",()=>{
  it("allows a current, MFA-verified session",()=>expect(evaluatePartnerSession({session,authoritative:auth,actionRisk:"MUTATION",now:2100})).toEqual({decision:"ALLOW"}));
  it("revokes explicit, expired, idle, disabled and closed-tenant sessions",()=>{expect(evaluatePartnerSession({session:{...session,revokedAt:2050},authoritative:auth,actionRisk:"READ",now:2100})).toEqual({decision:"REVOKE",reason:"SESSION_REVOKED"});expect(evaluatePartnerSession({session,authoritative:auth,actionRisk:"READ",now:20_000})).toEqual({decision:"REVOKE",reason:"SESSION_EXPIRED"});expect(evaluatePartnerSession({session:{...session,lastSeenAt:1000},authoritative:auth,actionRisk:"READ",now:3000})).toEqual({decision:"REVOKE",reason:"IDLE_TIMEOUT"});expect(evaluatePartnerSession({session,authoritative:{...auth,actorActive:false},actionRisk:"READ",now:2100})).toEqual({decision:"REVOKE",reason:"ACTOR_DISABLED"});expect(evaluatePartnerSession({session,authoritative:{...auth,tenantActive:false},actionRisk:"READ",now:2100})).toEqual({decision:"REVOKE",reason:"TENANT_DISABLED"});});
  it("revokes tenant, role and authorization-version changes",()=>{expect(evaluatePartnerSession({session,authoritative:{...auth,tenantId:"tenant-b"},actionRisk:"READ",now:2100})).toEqual({decision:"REVOKE",reason:"TENANT_CHANGED"});expect(evaluatePartnerSession({session,authoritative:{...auth,role:"REPORT_VIEWER"},actionRisk:"READ",now:2100})).toEqual({decision:"REVOKE",reason:"ROLE_CHANGED"});expect(evaluatePartnerSession({session,authoritative:{...auth,actorAuthVersion:8},actionRisk:"READ",now:2100})).toEqual({decision:"REVOKE",reason:"AUTH_VERSION_CHANGED"});});
  it("requires MFA and applies stricter freshness to PII",()=>{expect(evaluatePartnerSession({session:{...session,mfaVerifiedAt:null},authoritative:auth,actionRisk:"READ",now:2100})).toEqual({decision:"REAUTH_MFA",reason:"MFA_REQUIRED"});expect(evaluatePartnerSession({session:{...session,mfaVerifiedAt:1000},authoritative:auth,actionRisk:"PII_ACCESS",now:1700})).toEqual({decision:"REAUTH_MFA",reason:"MFA_STALE"});});
  it("rotates an otherwise valid session without extending absolute lifetime",()=>expect(evaluatePartnerSession({session:{...session,lastRotatedAt:1000,mfaVerifiedAt:2050},authoritative:auth,actionRisk:"MUTATION",now:2100})).toEqual({decision:"ROTATE",reason:"ROTATION_DUE"}));
});

