import { describe, expect, it } from "vitest";
import { assessMigrationReadiness } from "./readiness/assessMigrationReadiness";
import { assertSameTenant, assertSameTenantAndBranch, compositeOwnershipKey } from "./tenancy/ownership";
import { buildTransactionLocalContext, contextIsTransactionLocal, type VerifiedPartnerSessionClaims } from "./tenancy/sessionContext";
const claims: VerifiedPartnerSessionClaims = { source: "VERIFIED_IDENTITY_PROVIDER", tenantId: "11111111-1111-4111-8111-111111111111", actorId: "22222222-2222-4222-8222-222222222222", role: "DEALER_ADMIN", branchIds: ["33333333-3333-4333-8333-333333333333"], mfaVerified: true, sessionExpiresAt: "2026-09-01T20:00:00Z" };
describe("used-cars migration safety prerequisites", () => {
  it("builds only parameterized transaction-local settings from verified MFA claims", () => { const settings = buildTransactionLocalContext(claims, "2026-09-01T18:00:00Z"); expect(contextIsTransactionLocal(settings)).toBe(true); expect(settings.every(setting => setting.statement === "select set_config($1, $2, true)")).toBe(true); });
  it("fails closed for missing MFA, expiry and malformed identifiers", () => { expect(() => buildTransactionLocalContext({ ...claims, mfaVerified: false }, "2026-09-01T18:00:00Z")).toThrow("MFA_REQUIRED"); expect(() => buildTransactionLocalContext(claims, "2026-09-01T21:00:00Z")).toThrow("SESSION_EXPIRED"); expect(() => buildTransactionLocalContext({ ...claims, tenantId: "request-body-tenant" }, "2026-09-01T18:00:00Z")).toThrow("INVALID_SESSION_IDENTIFIER"); });
  it("rejects malformed session timestamps instead of comparing strings",()=>{expect(()=>buildTransactionLocalContext({...claims,sessionExpiresAt:"not-a-time"},"2026-09-01T18:00:00Z")).toThrow("INVALID_SESSION_TIME");expect(()=>buildTransactionLocalContext(claims,"not-a-time")).toThrow("INVALID_SESSION_TIME");});
  it("blocks cross-tenant and cross-branch relationships", () => { expect(() => assertSameTenant({ tenantId: "tenant-a" }, { tenantId: "tenant-b" })).toThrow("CROSS_TENANT_REFERENCE_FORBIDDEN"); expect(() => assertSameTenantAndBranch({ tenantId: "tenant-a", branchId: "one" }, { tenantId: "tenant-a", branchId: "two" })).toThrow("CROSS_BRANCH_REFERENCE_FORBIDDEN"); expect(compositeOwnershipKey("tenant-a", "unit-1")).toEqual({ tenantId: "tenant-a", entityId: "unit-1" }); });
  it("keeps migration blocked until every external gate is satisfied", () => { const result = assessMigrationReadiness({ verifiedSessionContract: true, poolTransactionIsolationTested: false, compositeTenantKeysReviewed: true, retentionMatrixLegallyApproved: false, kmsAndHmacRotationApproved: false, publicProjectionFailClosedTested: false, moderatorGrantModelReviewed: false, independentSecurityReviewComplete: false, stagingRollbackTested: false }); expect(result.ready).toBe(false); expect(result.productionWriteAuthorized).toBe(false); expect(result.missing).toContain("poolTransactionIsolationTested"); });
});
