import { describe,expect,it } from "vitest";
import { buildUsedCarsRateLimitKey,enforceUsedCarsRateLimit,evaluateUsedCarsRateLimit,usedCarsRateLimitPolicies } from "./security/rateLimit";
const secret=new TextEncoder().encode("test-only-rate-limit-secret-32-bytes");
describe("used-cars privacy-preserving rate limits",()=>{
  it("builds tenant and actor scoped keys without raw IP",()=>{const first=buildUsedCarsRateLimitKey({action:"INVENTORY_MUTATE",identity:{tenantId:"tenant-a",actorId:"actor-1",anonymousSessionId:null,ipAddress:"203.0.113.4"},networkSecret:secret,keyVersion:"net-v1"});const otherTenant=buildUsedCarsRateLimitKey({action:"INVENTORY_MUTATE",identity:{tenantId:"tenant-b",actorId:"actor-1",anonymousSessionId:null,ipAddress:"203.0.113.4"},networkSecret:secret,keyVersion:"net-v1"});expect(first.key).not.toBe(otherTenant.key);expect(JSON.stringify(first)).not.toContain("203.0.113.4");expect(first.rawIpStored).toBe(false);});
  it("requires tenant for authenticated partner actors and a principal for public requests",()=>{expect(()=>buildUsedCarsRateLimitKey({action:"PARTNER_LOGIN",identity:{tenantId:null,actorId:"actor-1",anonymousSessionId:null,ipAddress:"203.0.113.4"},networkSecret:secret,keyVersion:"v1"})).toThrow("PARTNER_TENANT_REQUIRED");expect(()=>buildUsedCarsRateLimitKey({action:"PUBLIC_MATCH",identity:{tenantId:null,actorId:null,anonymousSessionId:null,ipAddress:"203.0.113.4"},networkSecret:secret,keyVersion:"v1"})).toThrow("RATE_LIMIT_PRINCIPAL_REQUIRED");});
  it("blocks at the limit and resets only after the window",()=>{const policy=usedCarsRateLimitPolicies.LEAD_SUBMIT;expect(evaluateUsedCarsRateLimit(policy,{count:4,windowStartedAtEpochSeconds:1000},1100)).toEqual({allowed:true,remaining:0,resetAtEpochSeconds:1600});expect(evaluateUsedCarsRateLimit(policy,{count:5,windowStartedAtEpochSeconds:1000},1100)).toEqual({allowed:false,remaining:0,retryAfterSeconds:500,resetAtEpochSeconds:1600});expect(evaluateUsedCarsRateLimit(policy,{count:5,windowStartedAtEpochSeconds:1000},1600)).toEqual({allowed:true,remaining:4,resetAtEpochSeconds:2200});});
  it("forbids paid plan overrides for every action",()=>expect(Object.values(usedCarsRateLimitPolicies).every(policy=>policy.paidPlanOverrideAllowed===false)).toBe(true));
  it("requires an atomic distributed store in production and fails closed on store errors",async()=>{const key=buildUsedCarsRateLimitKey({action:"LEAD_SUBMIT",identity:{tenantId:null,actorId:null,anonymousSessionId:"anon",ipAddress:"203.0.113.4"},networkSecret:secret,keyVersion:"v1"});const local={mode:"LOCAL_TEST" as const,async increment(){return {count:1,windowStartedAtEpochSeconds:1000};}};await expect(enforceUsedCarsRateLimit({policy:usedCarsRateLimitPolicies.LEAD_SUBMIT,key,store:local,nowEpochSeconds:1001,production:true})).rejects.toThrow("DISTRIBUTED_RATE_LIMIT_STORE_REQUIRED");const failed={mode:"DISTRIBUTED_ATOMIC" as const,async increment():Promise<never>{throw new Error("offline");}};await expect(enforceUsedCarsRateLimit({policy:usedCarsRateLimitPolicies.LEAD_SUBMIT,key,store:failed,nowEpochSeconds:1001,production:true})).rejects.toThrow("RATE_LIMIT_STORE_UNAVAILABLE");});
});
