import Image from "next/image";
import Link from "next/link";
import { CatalogVariantOpenButton } from "@/components/cars/CatalogVariantOpenButton";
import { getCatalogBrowserPage, parseCatalogBrowserQuery } from "@/features/catalog-browser/catalog.server";

export const dynamic = "force-dynamic";
const controlClass = "min-h-12 w-full rounded-2xl border border-stone-200 bg-white px-4 text-sm text-stone-900 shadow-[0_1px_0_rgba(28,25,23,.03)] outline-none transition hover:border-stone-300 focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100";
const pageHref = (raw: Record<string, string | string[] | undefined>, page: number) => { const params = new URLSearchParams(); for (const [key, value] of Object.entries(raw)) { const item = Array.isArray(value) ? value[0] : value; if (item && key !== "page") params.set(key, item); } params.set("page", String(page)); return `/cars/catalog?${params.toString()}`; };
const Arrow = () => <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" className="size-5" stroke="currentColor" strokeWidth="1.8"><path d="m8 5 7 7-7 7" strokeLinecap="round" strokeLinejoin="round" /></svg>;

export default async function CatalogPage({ searchParams }: { readonly searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams; const query = parseCatalogBrowserQuery(raw); const result = await getCatalogBrowserPage(query);
  return <main className="min-h-screen bg-[#f7f8f5] text-stone-950">
    <header className="sticky top-0 z-30 border-b border-stone-200/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[92rem] items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="inline-flex items-baseline gap-2 text-lg font-bold tracking-tight">EXPIYA <span className="font-light text-emerald-700">CARS</span></Link><Link href="/?resume=conversation#sohbet" className="group inline-flex min-h-11 items-center gap-2 rounded-full border border-stone-200 bg-white px-4 text-sm font-semibold shadow-sm transition hover:border-emerald-600 hover:text-emerald-800">Karar motoruyla sohbet et <span className="transition-transform group-hover:translate-x-0.5">→</span></Link></div></header>
    <section className="relative isolate overflow-hidden border-b border-stone-200 bg-white"><div aria-hidden="true" className="absolute -right-28 -top-40 size-[32rem] rounded-full bg-emerald-100/70 blur-3xl" /><div aria-hidden="true" className="absolute bottom-0 left-[38%] h-28 w-96 rounded-full bg-amber-50 blur-3xl" /><div className="relative mx-auto grid max-w-[92rem] gap-8 px-5 py-12 sm:px-8 sm:py-16 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="flex items-center gap-3 text-xs font-semibold uppercase tracking-[.26em] text-emerald-700"><span className="h-px w-9 bg-emerald-600" />Türkiye sıfır araç kataloğu</div><h1 className="mt-5 max-w-4xl text-4xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-6xl">Tüm seçenekler.<br /><span className="text-stone-400">Kontrol tamamen sende.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-stone-600 sm:text-lg">Satıştaki araçları kendi ölçütlerinle keşfet. Filtrele, sırala ve seçtiğin exact varyantı ayrıntılı incele.</p></div><div className="grid grid-cols-2 gap-2"><div className="rounded-3xl border border-stone-200 bg-white/80 px-5 py-4 shadow-sm backdrop-blur"><p className="text-3xl font-semibold">{result.initialCount}</p><p className="mt-1 text-xs text-stone-500">Satıştaki varyant</p></div><div className="rounded-3xl border border-stone-200 bg-white/80 px-5 py-4 shadow-sm backdrop-blur"><p className="text-3xl font-semibold">{result.release}</p><p className="mt-1 text-xs text-stone-500">Aktif katalog</p></div></div></div></section>
    <div className="mx-auto max-w-[92rem] px-5 py-7 sm:px-8 sm:py-10">
      <form method="get" className="rounded-[2rem] border border-stone-200 bg-white p-4 shadow-[0_24px_70px_-48px_rgba(28,25,23,.35)] sm:p-5" aria-label="Araç kataloğu filtreleri"><div className="mb-4 flex items-center justify-between"><p className="font-semibold">Aramanı daralt</p><Link href="/cars/catalog" className="text-sm font-semibold text-stone-500 hover:text-emerald-700">Tümünü temizle</Link></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">
        <label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-semibold text-stone-600">Marka, model veya varyant ara</span><input name="q" defaultValue={query.q} placeholder="Örn. Sportage" className={controlClass} /></label>
        <label><span className="mb-1.5 block text-xs font-semibold text-stone-600">Marka</span><select name="brand" defaultValue={query.brand} className={controlClass}><option value="">Tümü</option>{result.facets.brands.map((value) => <option key={value}>{value}</option>)}</select></label>
        <label><span className="mb-1.5 block text-xs font-semibold text-stone-600">Sınıf</span><select name="class" defaultValue={query.useClass} className={controlClass}><option value="">Tümü</option>{result.facets.useClasses.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
        <label><span className="mb-1.5 block text-xs font-semibold text-stone-600">Gövde</span><select name="body" defaultValue={query.bodyStyle} className={controlClass}><option value="">Tümü</option>{result.facets.bodyStyles.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
        <label><span className="mb-1.5 block text-xs font-semibold text-stone-600">Yakıt</span><select name="fuel" defaultValue={query.fuelType} className={controlClass}><option value="">Tümü</option>{result.facets.fuelTypes.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
        <label><span className="mb-1.5 block text-xs font-semibold text-stone-600">Sırala</span><select name="sort" defaultValue={query.sort} className={controlClass}><option value="BRAND_ASC">Marka / model</option><option value="PRICE_ASC">Fiyat: düşükten yükseğe</option><option value="PRICE_DESC">Fiyat: yüksekten düşüğe</option><option value="YEAR_DESC">Model yılı</option><option value="SEATS_DESC">Koltuk sayısı</option></select></label>
        <button className="mt-auto inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-emerald-700 px-5 text-sm font-semibold text-white shadow-[0_12px_28px_rgba(4,120,87,.2)] transition hover:bg-emerald-800">Sonuçları göster <Arrow /></button>
        <label><span className="mb-1.5 block text-xs font-semibold text-stone-600">En düşük fiyat</span><input inputMode="numeric" name="minPrice" defaultValue={query.minPriceTry} placeholder="TL" className={controlClass} /></label><label><span className="mb-1.5 block text-xs font-semibold text-stone-600">En yüksek fiyat</span><input inputMode="numeric" name="maxPrice" defaultValue={query.maxPriceTry} placeholder="TL" className={controlClass} /></label>
      </div></form>
      <div className="mt-7 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-700">Seçenekler</p><h2 className="mt-1 text-2xl font-semibold tracking-tight"><span className="text-emerald-700">{result.total}</span> varyant bulundu</h2></div><p className="max-w-lg text-xs leading-5 text-stone-500">Tahmini fiyatlar gösterilmez; yalnız filtreleme ve sıralamadaki göreli konum için kullanılır.</p></div>
      <div className="mt-5 space-y-3">{result.rows.map((row) => <article key={row.id} className="group overflow-hidden rounded-[1.75rem] border border-stone-200 bg-white shadow-[0_14px_45px_-38px_rgba(28,25,23,.5)] transition duration-300 hover:-translate-y-0.5 hover:border-emerald-200 hover:shadow-[0_24px_60px_-36px_rgba(4,120,87,.28)]"><div className="grid md:grid-cols-[13rem_minmax(0,1fr)] xl:grid-cols-[13rem_minmax(16rem,1.15fr)_minmax(24rem,1fr)_13rem] xl:items-center">
        <div className="relative min-h-52 overflow-hidden bg-stone-100 md:min-h-full"><Image src={row.image} alt={`${row.brand} ${row.model}`} fill sizes="(max-width: 768px) 100vw, 208px" className="object-cover transition duration-500 group-hover:scale-[1.025]" /><span className="absolute left-3 top-3 rounded-full border border-white/60 bg-white/90 px-3 py-1 text-[11px] font-semibold shadow-sm backdrop-blur">{row.modelYear} model</span></div>
        <div className="p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-700">{row.brand}</p><h3 className="mt-2 text-xl font-semibold leading-tight tracking-tight sm:text-2xl">{row.model}</h3><p className="mt-2 text-sm leading-6 text-stone-500">{row.trim}</p></div>
        <dl className="grid grid-cols-2 gap-x-5 gap-y-4 border-y border-stone-100 px-5 py-5 text-sm sm:grid-cols-3 md:px-6 xl:border-x xl:border-y-0"><div><dt className="text-[11px] font-semibold uppercase tracking-wide text-stone-400">Sınıf</dt><dd className="mt-1 font-medium">{row.useClass}</dd></div><div><dt className="text-[11px] font-semibold uppercase tracking-wide text-stone-400">Gövde</dt><dd className="mt-1 font-medium">{row.bodyStyle}</dd></div><div><dt className="text-[11px] font-semibold uppercase tracking-wide text-stone-400">Yakıt</dt><dd className="mt-1 font-medium">{row.fuelType}</dd></div><div><dt className="text-[11px] font-semibold uppercase tracking-wide text-stone-400">Koltuk</dt><dd className="mt-1 font-medium">{row.seats ?? "—"} kişilik</dd></div><div className="col-span-2"><dt className="text-[11px] font-semibold uppercase tracking-wide text-stone-400">Şanzıman</dt><dd className="mt-1 font-medium leading-5">{row.transmission}</dd></div></dl>
        <div className="flex flex-col justify-between gap-4 p-5 sm:p-6 xl:min-h-48"><div><p className="text-[11px] font-semibold uppercase tracking-wide text-stone-400">Fiyat durumu</p><p className="mt-2 text-lg font-semibold tracking-tight">{row.priceDisplay}</p>{row.priceStatus === "EXPIRED" ? <p className="mt-1.5 text-xs font-medium text-amber-700">Güncel olmayabilir</p> : row.priceStatus === "INTERNAL_ONLY" ? <p className="mt-1.5 text-xs leading-5 text-stone-500">Doğrulanmış tutar bekleniyor</p> : null}</div><CatalogVariantOpenButton exactVariantId={row.id} /></div>
      </div></article>)}</div>
      {!result.rows.length ? <div className="mt-5 rounded-[2rem] border border-dashed border-stone-300 bg-white p-10 text-center"><p className="text-lg font-semibold">Bu filtrelerle eşleşen varyant bulunamadı.</p><p className="mt-2 text-sm text-stone-500">Filtreleri kaldırarak seçenekleri genişletebilirsin.</p><Link href="/cars/catalog" className="mt-5 inline-flex rounded-full bg-stone-900 px-5 py-3 text-sm font-semibold text-white">Tüm araçları göster</Link></div> : null}
      <nav aria-label="Katalog sayfaları" className="mt-8 flex items-center justify-center gap-3"><Link aria-disabled={result.page === 1} href={pageHref(raw, Math.max(1, result.page - 1))} className={`rounded-full border border-stone-200 bg-white px-5 py-3 text-sm font-semibold shadow-sm ${result.page === 1 ? "pointer-events-none opacity-40" : "hover:border-emerald-500"}`}>← Önceki</Link><span className="rounded-full bg-stone-200/70 px-4 py-2 text-sm font-medium text-stone-600">{result.page} / {result.pageCount}</span><Link aria-disabled={result.page === result.pageCount} href={pageHref(raw, Math.min(result.pageCount, result.page + 1))} className={`rounded-full border border-stone-200 bg-white px-5 py-3 text-sm font-semibold shadow-sm ${result.page === result.pageCount ? "pointer-events-none opacity-40" : "hover:border-emerald-500"}`}>Sonraki →</Link></nav>
    </div>
  </main>;
}
