import Image from "next/image";
import Link from "next/link";
import { CatalogVariantOpenButton } from "@/components/cars/CatalogVariantOpenButton";
import { CatalogPriceInput } from "@/components/cars/CatalogPriceInput";
import { getCatalogBrowserPage, parseCatalogBrowserQuery } from "@/features/catalog-browser/catalog.server";

export const dynamic = "force-dynamic";
const controlClass = "min-h-12 w-full rounded-2xl border border-stone-200 bg-white px-4 text-sm text-stone-900 shadow-[0_1px_0_rgba(28,25,23,.03)] outline-none transition hover:border-stone-300 focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100";
const pageHref = (raw: Record<string, string | string[] | undefined>, page: number) => { const params = new URLSearchParams(); for (const [key, value] of Object.entries(raw)) { const item = Array.isArray(value) ? value[0] : value; if (item && key !== "page") params.set(key, item); } params.set("page", String(page)); return `/cars/catalog?${params.toString()}`; };
const Arrow = () => <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" className="size-5" stroke="currentColor" strokeWidth="1.8"><path d="m8 5 7 7-7 7" strokeLinecap="round" strokeLinejoin="round" /></svg>;

export default async function CatalogPage({ searchParams }: { readonly searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams; const query = parseCatalogBrowserQuery(raw); const result = await getCatalogBrowserPage(query);
  return <main className="min-h-screen bg-[#f7f8f5] text-stone-950">
    <header className="sticky top-0 z-30 border-b border-stone-200/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[92rem] items-center justify-between px-5 py-4 sm:px-8"><Link href="/cars" className="inline-flex items-baseline gap-2 text-lg font-bold tracking-tight">EXPIYA <span className="font-light text-emerald-700">CARS</span></Link><Link href="/cars?resume=conversation#sohbet" className="group inline-flex min-h-11 items-center gap-2 rounded-full border border-stone-200 bg-white px-4 text-sm font-semibold shadow-sm transition hover:border-emerald-600 hover:text-emerald-800">Karar motoruyla sohbet et <span className="transition-transform group-hover:translate-x-0.5">→</span></Link></div></header>
    <section className="relative isolate overflow-hidden border-b border-stone-200 bg-white"><div aria-hidden="true" className="absolute -right-28 -top-40 size-[32rem] rounded-full bg-emerald-100/70 blur-3xl" /><div className="relative mx-auto grid max-w-[92rem] gap-8 px-5 py-10 sm:px-8 sm:py-14 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="flex items-center gap-3 text-xs font-semibold uppercase tracking-[.26em] text-emerald-700"><span className="h-px w-9 bg-emerald-600" />Türkiye sıfır araç kataloğu</div><h1 className="mt-4 max-w-4xl text-4xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-6xl">Tüm seçenekler.<br /><span className="text-stone-400">Kontrol tamamen sende.</span></h1><p className="mt-4 max-w-2xl leading-7 text-stone-600">Satıştaki araçları kendi ölçütlerinle keşfet. Filtrele, sırala ve seçtiğin exact varyantı ayrıntılı incele.</p></div><div className="grid grid-cols-3 gap-2"><div className="rounded-2xl border border-stone-200 bg-white/85 px-4 py-3 shadow-sm"><p className="text-2xl font-semibold">{result.initialCount}</p><p className="mt-1 text-[11px] text-stone-500">Satıştaki varyant</p></div><div className="rounded-2xl border border-stone-200 bg-white/85 px-4 py-3 shadow-sm"><p className="text-2xl font-semibold">{result.modelCount}</p><p className="mt-1 text-[11px] text-stone-500">Aktif model</p></div><div className="rounded-2xl border border-stone-200 bg-white/85 px-4 py-3 shadow-sm"><p className="text-2xl font-semibold">{result.brandCount}</p><p className="mt-1 text-[11px] text-stone-500">Aktif marka</p></div></div></div></section>
    <div className="mx-auto max-w-[92rem] px-5 py-7 sm:px-8 sm:py-10">
      <form method="get" action="/cars/catalog#secenekler" className="rounded-[2rem] border border-stone-200 bg-white p-4 shadow-[0_24px_70px_-48px_rgba(28,25,23,.35)] sm:p-5" aria-label="Araç kataloğu filtreleri"><div className="mb-4 flex items-center justify-between"><p className="font-semibold">Aramanı daralt</p><Link href="/cars/catalog" className="text-sm font-semibold text-stone-500 hover:text-emerald-700">Tümünü temizle</Link></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">
        <label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-semibold text-stone-600">Marka, model veya varyant ara</span><input name="q" defaultValue={query.q} placeholder="Örn. Sportage" className={controlClass} /></label>
        <label><span className="mb-1.5 block text-xs font-semibold text-stone-600">Marka</span><select name="brand" defaultValue={query.brand} className={controlClass}><option value="">Tümü</option>{result.facets.brands.map((value) => <option key={value}>{value}</option>)}</select></label>
        <label><span className="mb-1.5 block text-xs font-semibold text-stone-600">Sınıf</span><select name="class" defaultValue={query.useClass} className={controlClass}><option value="">Tümü</option>{result.facets.useClasses.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
        <label><span className="mb-1.5 block text-xs font-semibold text-stone-600">Gövde</span><select name="body" defaultValue={query.bodyStyle} className={controlClass}><option value="">Tümü</option>{result.facets.bodyStyles.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
        <label><span className="mb-1.5 block text-xs font-semibold text-stone-600">Yakıt</span><select name="fuel" defaultValue={query.fuelType} className={controlClass}><option value="">Tümü</option>{result.facets.fuelTypes.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
        <label><span className="mb-1.5 block text-xs font-semibold text-stone-600">Sırala</span><select name="sort" defaultValue={query.sort} className={controlClass}><option value="BRAND_ASC">Marka / model</option><option value="PRICE_ASC">Fiyat: düşükten yükseğe</option><option value="PRICE_DESC">Fiyat: yüksekten düşüğe</option><option value="YEAR_DESC">Model yılı</option><option value="SEATS_DESC">Koltuk sayısı</option></select></label>
        <button className="mt-auto inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-emerald-700 px-5 text-sm font-semibold text-white shadow-[0_12px_28px_rgba(4,120,87,.2)] transition hover:bg-emerald-800">Sonuçları göster <Arrow /></button>
        <label><span className="mb-1.5 block text-xs font-semibold text-stone-600">En yüksek fiyat</span><CatalogPriceInput defaultValue={query.maxPriceTry} /></label>
      </div></form>
      <aside role="note" className="mt-4 rounded-2xl border border-stone-200 bg-white px-4 py-3 text-xs leading-5 text-stone-600"><strong className="text-stone-800">Bilgilendirme:</strong> Expiya araç satışı yapmaz. Bu katalog, kamuya açık ve kaynaklandırılmış araç bilgilerini araştırmayı kolaylaştırmak için derler; fiyat, stok, donanım ve satış koşulları satın alma öncesinde yetkili satıcıdan doğrulanmalıdır.</aside>
      <div id="secenekler" className="mt-7 scroll-mt-24"><p className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-700">Seçenekler</p><h2 className="mt-1 text-2xl font-semibold tracking-tight"><span className="text-emerald-700">{result.total}</span> varyant bulundu</h2></div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{result.rows.map((row) => <article key={row.id} className="group flex min-w-0 flex-col overflow-hidden rounded-[1.5rem] border border-stone-200 bg-white shadow-[0_14px_42px_-34px_rgba(28,25,23,.48)] transition duration-300 hover:-translate-y-1 hover:border-emerald-200 hover:shadow-[0_22px_50px_-30px_rgba(4,120,87,.25)]">
        <div className="relative aspect-[4/3] overflow-hidden bg-gradient-to-br from-white to-stone-100"><Image src={row.image} alt={`${row.brand} ${row.model}`} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 25vw" className="object-contain p-3 transition duration-500 group-hover:scale-[1.025]" /><CatalogVariantOpenButton exactVariantId={row.id} mode="IMAGE" /><span className="pointer-events-none absolute left-3 top-3 z-20 rounded-full border border-white/60 bg-white/90 px-2.5 py-1 text-[10px] font-semibold shadow-sm backdrop-blur">{row.modelYear}</span></div>
        <div className="flex flex-1 flex-col p-4"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-emerald-700">{row.brand}</p><h3 className="mt-1.5 text-lg font-semibold leading-tight tracking-tight">{row.model}</h3><p className="mt-1.5 line-clamp-2 min-h-10 text-xs leading-5 text-stone-500">{row.trim}</p>
        <dl className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-stone-50 p-2.5"><dt className="text-[9px] uppercase tracking-wide text-stone-400">Gövde</dt><dd className="mt-1 truncate font-medium">{row.bodyStyle}</dd></div><div className="rounded-xl bg-stone-50 p-2.5"><dt className="text-[9px] uppercase tracking-wide text-stone-400">Yakıt</dt><dd className="mt-1 truncate font-medium">{row.fuelType}</dd></div><div className="rounded-xl bg-stone-50 p-2.5"><dt className="text-[9px] uppercase tracking-wide text-stone-400">Sınıf</dt><dd className="mt-1 truncate font-medium">{row.useClass}</dd></div><div className="rounded-xl bg-stone-50 p-2.5"><dt className="text-[9px] uppercase tracking-wide text-stone-400">Koltuk</dt><dd className="mt-1 font-medium">{row.seats ?? "—"} kişilik</dd></div></dl>
        <div className="mt-4 border-t border-stone-100 pt-4"><p className="text-[9px] font-semibold uppercase tracking-wide text-stone-400">Fiyat durumu</p><p className="mt-1 text-base font-semibold tracking-tight">{row.priceDisplay}</p>{row.priceDateDisplay ? <p className="mt-1 text-[10px] text-stone-500">Fiyat tarihi: {row.priceDateDisplay}</p> : null}{row.priceStatus === "EXPIRED" ? <p className="mt-1 text-[10px] font-medium text-amber-700">Güncel olmayabilir</p> : row.priceStatus === "INTERNAL_ONLY" ? <p className="mt-1 text-[10px] text-stone-500">Doğrulanmış tutar bekleniyor</p> : null}</div><div className="mt-auto pt-4"><CatalogVariantOpenButton exactVariantId={row.id} /></div></div>
      </article>)}</div>
      {!result.rows.length ? <div className="mt-5 rounded-[2rem] border border-dashed border-stone-300 bg-white p-10 text-center"><p className="text-lg font-semibold">Bu filtrelerle eşleşen varyant bulunamadı.</p><p className="mt-2 text-sm text-stone-500">Filtreleri kaldırarak seçenekleri genişletebilirsin.</p><Link href="/cars/catalog" className="mt-5 inline-flex rounded-full bg-stone-900 px-5 py-3 text-sm font-semibold text-white">Tüm araçları göster</Link></div> : null}
      <nav aria-label="Katalog sayfaları" className="mt-8 flex items-center justify-center gap-3"><Link aria-disabled={result.page === 1} href={pageHref(raw, Math.max(1, result.page - 1))} className={`rounded-full border border-stone-200 bg-white px-5 py-3 text-sm font-semibold shadow-sm ${result.page === 1 ? "pointer-events-none opacity-40" : "hover:border-emerald-500"}`}>← Önceki</Link><span className="rounded-full bg-stone-200/70 px-4 py-2 text-sm font-medium text-stone-600">{result.page} / {result.pageCount}</span><Link aria-disabled={result.page === result.pageCount} href={pageHref(raw, Math.min(result.pageCount, result.page + 1))} className={`rounded-full border border-stone-200 bg-white px-5 py-3 text-sm font-semibold shadow-sm ${result.page === result.pageCount ? "pointer-events-none opacity-40" : "hover:border-emerald-500"}`}>Sonraki →</Link></nav>
    </div>
  </main>;
}
