import { readFile } from "node:fs/promises";
import path from "node:path";
import fontkit from "@pdf-lib/fontkit";
import { PDFDocument, rgb, type PDFFont, type PDFPage } from "pdf-lib";

type Fact = { value: string | number | null; missing: boolean; sources?: readonly string[] };
type PdfVehicle = { exactVariantId: string; role: string; identity: { brand: string; model: string; trim: string; sources?: readonly string[] }; price: { value: number | null; validFrom: string | null; sources?: readonly string[] }; facts: Record<string, Fact>; safetyFeatures?: readonly Fact[]; imageUrl?: string; imageStatus?: string };
export type PaidComparisonPdfInput = { generatedAt: string; catalogReleaseVersion: string; needsSummary: readonly { summary: string }[]; assessment: { conclusion: string; scores: readonly { exactVariantId: string; score: number | null }[]; conditions: readonly { exactVariantId: string; text: string }[] }; vehicles: readonly PdfVehicle[] };

const A4: [number, number] = [595.28, 841.89];
const navy = rgb(0.063, 0.165, 0.263); const blue = rgb(0.11, 0.39, 0.95); const green = rgb(0.09, 0.61, 0.38); const ink = rgb(0.08, 0.14, 0.21); const muted = rgb(0.32, 0.4, 0.48); const pale = rgb(0.965, 0.98, 0.99); const line = rgb(0.84, 0.89, 0.93); const amber = rgb(0.9, 0.54, 0);

function wrap(text: string, font: PDFFont, size: number, width: number): string[] {
  const words = text.replace(/\s+/gu, " ").trim().split(" "); const lines: string[] = []; let current = "";
  for (const word of words) { const candidate = current ? `${current} ${word}` : word; if (font.widthOfTextAtSize(candidate, size) <= width) current = candidate; else { if (current) lines.push(current); current = word; } }
  if (current) lines.push(current); return lines.length ? lines : [""];
}
function text(page: PDFPage, value: string, x: number, y: number, options: { font: PDFFont; size?: number; color?: ReturnType<typeof rgb>; width?: number; lineHeight?: number } ): number {
  const printable = value.replace(/[✓↗◆]/gu, "").trim();
  const size = options.size ?? 9; const lines = options.width ? wrap(printable, options.font, size, options.width) : [printable]; const height = options.lineHeight ?? size * 1.3;
  lines.forEach((item, index) => page.drawText(item, { x, y: y - index * height, size, font: options.font, color: options.color ?? ink })); return y - lines.length * height;
}
function sectionTitle(page: PDFPage, title: string, y: number, bold: PDFFont, number: string): number {
  page.drawCircle({ x: 42, y: y - 2, size: 13, color: blue }); text(page, number, 35, y - 6, { font: bold, size: 8, color: rgb(1,1,1) }); text(page, title, 62, y + 2, { font: bold, size: 16, color: navy }); page.drawLine({ start: { x: 32, y: y - 22 }, end: { x: 563, y: y - 22 }, color: line, thickness: 1 }); return y - 42;
}
function footer(page: PDFPage, regular: PDFFont, pageNumber: number) { page.drawLine({ start: { x: 32, y: 30 }, end: { x: 563, y: 30 }, color: line, thickness: .7 }); text(page, "Expiya Cars - Karar desteği; ekspertiz veya kesin satın alma talimatı değildir.", 32, 18, { font: regular, size: 6.5, color: muted }); text(page, String(pageNumber), 548, 18, { font: regular, size: 7, color: muted }); }
const UNKNOWN = "o";
const formatValue = (fact: Fact | undefined) => !fact || fact.missing || fact.value === null ? UNKNOWN : String(fact.value);
const money = (value: number | null) => value === null ? UNKNOWN : `${new Intl.NumberFormat("tr-TR", { maximumFractionDigits: 0 }).format(value)} TL`;
const dateOnly = (value: string | null) => { if (!value) return UNKNOWN; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value.split("T")[0] ?? value : new Intl.DateTimeFormat("tr-TR", { day: "2-digit", month: "2-digit", year: "numeric" }).format(parsed); };

export async function createPaidComparisonPdf(report: PaidComparisonPdfInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create(); pdf.registerFontkit(fontkit);
  // WOFF2 fonts render as blank text in some browser PDF viewers. TrueType is
  // embedded deliberately so the report is portable across browser, mobile and print.
  const fontRoot = path.join(process.cwd(), "node_modules", "pdfjs-dist", "standard_fonts");
  const [regularBytes, boldBytes] = await Promise.all([readFile(path.join(fontRoot, "LiberationSans-Regular.ttf")), readFile(path.join(fontRoot, "LiberationSans-Bold.ttf"))]);
  const regular = await pdf.embedFont(regularBytes, { subset: false }); const bold = await pdf.embedFont(boldBytes, { subset: false });
  const pages: PDFPage[] = []; const addPage = () => { const page = pdf.addPage(A4); pages.push(page); return page; };
  const vehicles = report.vehicles.slice(0, 3);
  const isAnonymousSample = report.catalogReleaseVersion.includes("ANONİM ÖRNEK");

  let page = addPage(); page.drawRectangle({ x: 0, y: 0, width: A4[0], height: A4[1], color: navy });
  try { const heroBytes=await readFile(path.join(process.cwd(),"public/cars/expiya-hero-highway-mixed-fleet.png")); const hero=await pdf.embedPng(heroBytes); const scale=Math.max(A4[0]/hero.width,300/hero.height); page.drawImage(hero,{x:(A4[0]-hero.width*scale)/2,y:542,width:hero.width*scale,height:hero.height*scale}); page.drawRectangle({x:0,y:542,width:A4[0],height:300,color:navy,opacity:.37}); } catch { /* branded solid cover remains */ }
  page.drawRectangle({x:0,y:522,width:A4[0],height:320,color:navy,opacity:.18});
  text(page, "EXPIYA CARS", 42, 796, { font: bold, size: 13, color: rgb(.58,.96,.78) }); text(page, "XPY", 503, 796, { font: bold, size: 15, color: rgb(1,1,1) });
  text(page, "Senin için doğru araca", 42, 742, { font: bold, size: 29, color: rgb(1,1,1) }); text(page, "karar verir", 42, 704, { font: bold, size: 29, color: rgb(1,1,1) });
  text(page, "3 ARAÇ · KİŞİSEL KARŞILAŞTIRMA RAPORU", 42, 660, { font: bold, size: 10, color: rgb(.58,.96,.78) });
  for (let index=0; index<vehicles.length; index++) { const vehicle=vehicles[index]!; const x=42+index*174; page.drawRectangle({ x, y: 322, width: 158, height: 188, color: index===0 ? rgb(.9,.98,.94) : rgb(.975,.985,.99), borderColor: index===0 ? green : line, borderWidth: 1.4 });
    if (vehicle.imageUrl) { try { const bytes=vehicle.imageUrl.startsWith("/") ? await readFile(path.join(process.cwd(),"public",vehicle.imageUrl.replace(/^\/+/, ""))) : new Uint8Array(await (await fetch(vehicle.imageUrl, { signal: AbortSignal.timeout(8_000) })).arrayBuffer()); const image=vehicle.imageUrl.toLowerCase().split("?")[0]?.endsWith(".png") ? await pdf.embedPng(bytes) : await pdf.embedJpg(bytes); const scaled=image.scaleToFit(146,78); page.drawImage(image,{x:x+6+(146-scaled.width)/2,y:424+(78-scaled.height)/2,width:scaled.width,height:scaled.height}); } catch { page.drawRectangle({x:x+6,y:424,width:146,height:78,color:line}); } }
    text(page,index===0?"KARAR ARACI":"ALTERNATİF",x+10,405,{font:bold,size:7.5,color:index===0?green:blue}); text(page,`${vehicle.identity.brand} ${vehicle.identity.model}`,x+10,383,{font:bold,size:12,color:navy,width:138}); text(page,vehicle.identity.trim,x+10,351,{font:regular,size:8.5,color:muted,width:138}); text(page,money(vehicle.price.value),x+10,333,{font:bold,size:10,color:ink}); }
  page.drawRectangle({x:42,y:190,width:506,height:92,color:rgb(.985,.955,.88),borderColor:amber,borderWidth:1}); text(page,isAnonymousSample?"! ANONİM VE TEMSİLİ ÖRNEK":"! VERİ ŞEFFAFLIĞI",56,255,{font:bold,size:10,color:amber}); text(page,isAnonymousSample?"Temel teknik veriler gerçek katalogdan anonimleştirilmiştir. Donanım ve maliyet katmanlarındaki tamamlayıcı değerler yalnız rapor deneyimini göstermek için sentetiktir; güncel tavsiye veya teklif değildir.":"Doğrulanmayan hiçbir değer tahmin edilmez. Rapor boyunca 'o' işareti, ilgili alan için doğrulanmış veri bulunmadığını gösterir.",56,230,{font:regular,size:10,color:ink,width:475,lineHeight:14}); text(page,`Oluşturma: ${new Date(report.generatedAt).toLocaleString("tr-TR")}  ·  Katalog: ${report.catalogReleaseVersion}`,42,70,{font:regular,size:8,color:rgb(.75,.82,.88)}); text(page,"Experience. Powered by You.",42,48,{font:bold,size:9,color:rgb(.58,.96,.78)});

  page=addPage(); let y=sectionTitle(page,"İhtiyaç özeti ve karar",790,bold,"1");
  text(page,"XPY KARAR PUSULASI",42,y,{font:bold,size:9,color:green}); y-=22;
  if (report.needsSummary.length) for (const need of report.needsSummary) { page.drawCircle({x:48,y:y+2,size:9,color:rgb(.9,.98,.94)}); text(page,"✓",44,y-2,{font:bold,size:8,color:green}); y=text(page,need.summary,66,y+7,{font:regular,size:11,width:470,lineHeight:15})-10; } else y=text(page,"Bu test kararında ayrıntılı ihtiyaç bağlamı bulunmuyor.",42,y,{font:regular,size:11,color:muted})-12;
  page.drawRectangle({x:42,y:y-120,width:506,height:110,color:rgb(.91,.97,.94),borderColor:green,borderWidth:1}); text(page,"KARAR DOĞRULAMA SONUCU",58,y-36,{font:bold,size:9,color:green}); text(page,report.assessment.conclusion,58,y-62,{font:bold,size:15,color:navy,width:470,lineHeight:19}); y-=155;
  for (const vehicle of vehicles) { const score=report.assessment.scores.find(item=>item.exactVariantId===vehicle.exactVariantId)?.score; text(page,`${vehicle.identity.brand} ${vehicle.identity.model}`,42,y,{font:bold,size:10,width:150}); page.drawRectangle({x:205,y:y-3,width:260,height:14,color:line}); if(score!==null&&score!==undefined)page.drawRectangle({x:205,y:y-3,width:260*score/100,height:14,color:score>=75?green:blue}); text(page,score===null||score===undefined?UNKNOWN:`${score}/100`,485,y,{font:bold,size:10,color:score!==null&&score!==undefined?green:muted}); y-=34; }
  y-=10; text(page,"Hangi koşulda hangisi?",42,y,{font:bold,size:14,color:navy}); y-=25; for(const condition of report.assessment.conditions){const vehicle=vehicles.find(v=>v.exactVariantId===condition.exactVariantId);y=text(page,`${vehicle?.identity.brand ?? "Araç"} ${vehicle?.identity.model ?? ""}: ${condition.text}`,42,y,{font:regular,size:9,width:500,lineHeight:13})-8;}

  const groups: readonly [string,string,readonly [string,string][]][] = [
    ["Araç kimliği ve fiyat","2",[["Liste fiyatı","price"],["Fiyat tarihi","priceDate"],["Model yılı","modelYear"],["Gövde","bodyStyle"],["Yakıt / enerji","fuelType"],["Şanzıman","transmission"]]],
    ["Motor, aktarma ve verimlilik","3",[["Güç (kW)","powerKw"],["Tork (Nm)","torqueNm"],["Motor hacmi (cc)","engineDisplacementCc"],["Çekiş","drivenWheels"],["Tüketim (L/100 km)","combinedLitresPer100Km"],["Tüketim (kWh/100 km)","combinedKwhPer100Km"],["Elektrikli menzil (km)","electricRangeKm"],["DC şarj (kW)","maxDcChargeKw"]]],
    ["Boyutlar ve günlük kullanım","4",[["Koltuk","seats"],["Bagaj (L)","luggageLitres"],["Kargo hacmi (L)","cargoVolumeLitres"],["Uzunluk (mm)","lengthMm"],["Genişlik (mm)","widthMm"],["Yükseklik (mm)","heightMm"],["Aks mesafesi (mm)","wheelbaseMm"],["Frenli çekme (kg)","brakedTowingKg"]]],
    ["Konfor ve kabin","5",[["Klima türü","climateControl"],["Park sensörleri","parkingSensors"],["Anahtarsız giriş","keylessEntry"],["Hız sabitleyici","cruiseControl"],["Elektrikli aynalar","electricMirrors"],["Yağmur / far sensörü","rainLightSensor"],["Koltuk ayarı","seatAdjustment"],["Isıtmalı koltuk","heatedSeats"]]],
    ["Multimedya ve bağlantı","6",[["Multimedya ekranı","displaySize"],["Dijital gösterge","digitalCluster"],["Apple CarPlay","appleCarPlay"],["Android Auto","androidAuto"],["Bluetooth","bluetooth"],["Kablosuz şarj","wirelessCharging"],["USB bağlantıları","usbPorts"],["Navigasyon","navigation"]]],
    ["Dış donanım, aydınlatma ve renkler","7",[["Far teknolojisi","headlightTechnology"],["Gündüz farı","daytimeRunningLights"],["Otomatik uzun far","automaticHighBeam"],["Jant ölçüsü","wheelSize"],["Lastik ölçüsü","tyreSize"],["Stepne / tamir kiti","spareWheelKit"],["Tavan penceresi","sunroof"],["Standart dış renkler","standardColours"]]],
    ["Garanti, servis ve sahip olma maliyeti","8",[["Araç garantisi","warranty"],["Yol yardım","roadsideAssistance"],["Bakım aralığı","serviceInterval"],["Servis erişimi","serviceNetwork"],["Bakım maliyeti","maintenanceCost"],["MTV göstergesi","mtvIndicator"],["Sigorta göstergesi","insuranceIndicator"],["3 yıllık maliyet göstergesi","threeYearCost"]]],
    ["Kılavuz, belge ve kanıt derinliği","9",[["Türkiye kullanım kılavuzu","turkeyOwnersManual"],["Teknik veri föyü","technicalDataSheet"],["Fiyat listesi","officialPriceList"],["Donanım listesi","equipmentList"],["Garanti belgesi","warrantyDocument"],["Renk kataloğu","colourCatalogue"],["Exact varyant fotoğrafı","exactVariantMedia"],["Veri güven seviyesi","evidenceDepth"]]],
  ];
  for(const [titleValue,number,rows] of groups){page=addPage();y=sectionTitle(page,titleValue,790,bold,number);const col=[42,192,313,434];const widths=[148,120,120,120];for(let c=0;c<4;c++){page.drawRectangle({x:col[c]!,y:y-61,width:widths[c]!,height:61,color:c===0?navy:(c===1?rgb(.9,.98,.94):pale),borderColor:line,borderWidth:.5});if(c===0){text(page,"KARŞILAŞTIRMA",col[c]!+9,y-27,{font:bold,size:9,color:rgb(1,1,1)});text(page,"XPY · doğrulanmış veri",col[c]!+9,y-44,{font:regular,size:7.5,color:rgb(.72,.84,.9)});}else{const vehicle=vehicles[c-1];text(page,c===1?"✓ KARAR":"↗ ALTERNATİF",col[c]!+7,y-17,{font:bold,size:6.8,color:c===1?green:blue});text(page,`${vehicle?.identity.brand ?? ""} ${vehicle?.identity.model ?? ""}`,col[c]!+7,y-35,{font:bold,size:9,width:widths[c]!-14});text(page,vehicle?.identity.trim??"",col[c]!+7,y-49,{font:regular,size:6.8,color:muted,width:widths[c]!-14});}}y-=61;for(const [label,key] of rows){let maxLines=1;const vals=vehicles.map(v=>key==="price"?money(v.price.value):key==="priceDate"?dateOnly(v.price.validFrom):formatValue(v.facts[key]));for(const value of vals)maxLines=Math.max(maxLines,wrap(value,regular,8.5,108).length);const h=Math.max(34,maxLines*11+12);page.drawRectangle({x:42,y:y-h,width:148,height:h,color:pale,borderColor:line,borderWidth:.5});text(page,`◆  ${label}`,49,y-19,{font:bold,size:8.5,width:134});const numeric=vals.map(v=>Number(String(v).replace(/[^0-9.,-]/gu,"").replace(".","").replace(",","."))).filter(Number.isFinite);const maximum=Math.max(...numeric,0);vals.forEach((value,i)=>{page.drawRectangle({x:col[i+1]!,y:y-h,width:120,height:h,color:rgb(1,1,1),borderColor:line,borderWidth:.5});const n=Number(String(value).replace(/[^0-9.,-]/gu,"").replace(".","").replace(",","."));if(value!==UNKNOWN&&Number.isFinite(n)&&maximum>0)page.drawRectangle({x:col[i+1]!+1,y:y-h+1,width:118*Math.min(1,n/maximum),height:5,color:i===0?green:blue,opacity:.7});text(page,value,col[i+1]!+7,y-19,{font:value===UNKNOWN?bold:regular,size:value===UNKNOWN?11:8.5,color:value===UNKNOWN?amber:ink,width:106,lineHeight:11});});y-=h;}text(page,"o = Bu alan için doğrulanmış veri bulunmuyor; değer üretilmemiştir.",42,52,{font:regular,size:8,color:muted});}

  page=addPage();y=sectionTitle(page,"Güvenlik ve sürüş destekleri",790,bold,"10");text(page,"Doğrulanmış güvenlik kayıtları",42,y,{font:bold,size:14,color:navy});y-=28;for(const vehicle of vehicles){page.drawRectangle({x:42,y:y-94,width:506,height:86,color:pale,borderColor:line,borderWidth:.7});text(page,`${vehicle.identity.brand} ${vehicle.identity.model}`,54,y-27,{font:bold,size:10,color:navy});const safety=vehicle.safetyFeatures??[];y=text(page,safety.length?safety.map(formatValue).join("  •  "):UNKNOWN,54,y-49,{font:regular,size:9,width:480,lineHeight:13})-62;}text(page,"o = Bu alan için doğrulanmış veri bulunmuyor; özelliğin bulunmadığı anlamına gelmez.",42,52,{font:regular,size:8,color:muted});

  page=addPage();y=sectionTitle(page,"Kaynaklar, hukuk ve satış adımları",790,bold,"11");const legal=["Bu rapor ekspertiz, teknik inceleme, bağlayıcı teklif veya kesin al/alma talimatı değildir.","Bilgiler hatalı, eksik, gecikmeli veya güncelliğini yitirmiş olabilir.","Expiya Cars ve Skybit; üretici, distribütör veya yetkili satıcının temsilcisi ya da garantörü değildir.","Fiyat, stok, donanım, garanti ve teslim koşulları satın alma öncesinde ilgili yetkili taraftan doğrulanmalıdır.","Satış bağlantısına tıklamak tek başına teklif, rezervasyon veya satış oluşturmaz."];for(const item of legal){page.drawCircle({x:45,y:y+3,size:5,color:amber});y=text(page,item,60,y+7,{font:regular,size:9,width:480,lineHeight:13})-10;}
  y-=10;text(page,"Veri kaynakları",42,y,{font:bold,size:13,color:navy});y-=23;const sources=[...new Set(vehicles.flatMap(v=>[...(v.identity.sources??[]),...(v.price.sources??[]),...Object.values(v.facts).flatMap(f=>f.sources??[])]))];for(const source of sources.slice(0,16)){y=text(page,source,42,y,{font:regular,size:7,color:blue,width:500,lineHeight:10})-4;if(y<70)break;}
  pages.forEach((item,index)=>footer(item,regular,index+1)); pdf.setTitle("Expiya Cars 3 Araç Karşılaştırma Raporu");pdf.setAuthor("Expiya Cars / Skybit");pdf.setSubject("Kişiselleştirilmiş araç karar doğrulama raporu");return pdf.save();
}
