import type { SqlConnection, SqlQueryable } from "@/features/vehicle-data/repository";
import { createPaidComparisonPdf, type PaidComparisonPdfInput } from "./pdfDocument.server";
import { decryptPaidReportDeliveryEmail, maskPaidReportDeliveryEmail } from "./deliveryEmailCipher.server";
export type PaidReportEmailJob = { orderId: string; deliveryEmailEncrypted: string; document: PaidComparisonPdfInput };
export interface PaidReportEmailOutboxRepository { claim(now: Date): Promise<PaidReportEmailJob | undefined>; complete(orderId: string, providerMessageId: string, now: Date): Promise<void>; fail(orderId: string, failureCode: string): Promise<void> }
export interface PaidReportEmailClient { send(input: { to: string; pdf: Uint8Array; idempotencyKey: string }): Promise<{ messageId: string }> }
export class PostgresPaidReportEmailOutboxRepository implements PaidReportEmailOutboxRepository {
  constructor(private readonly database: SqlQueryable) {}
  private async transaction<T>(operation: (connection: SqlQueryable | SqlConnection) => Promise<T>): Promise<T> { const pooled = this.database.connect ? await this.database.connect() : undefined; const connection = pooled ?? this.database; await connection.query("begin"); try { const result = await operation(connection); await connection.query("commit"); return result; } catch (error) { await connection.query("rollback"); throw error; } finally { pooled?.release(); } }
  async claim(now: Date): Promise<PaidReportEmailJob | undefined> { return this.transaction(async connection => { const selected = await connection.query(`select e.order_id, o.delivery_email_encrypted, d.document from paid_report_email_outbox e join paid_report_orders o on o.id=e.order_id join comparison_report_documents d on d.id=e.report_id where e.status in ('PENDING','FAILED') and e.attempt_count < 3 order by e.created_at for update skip locked limit 1`) as { rows?: { order_id: string; delivery_email_encrypted: string | null; document: PaidComparisonPdfInput }[] }; const row = selected.rows?.[0]; if (!row?.delivery_email_encrypted) return undefined; const updated = await connection.query(`update paid_report_email_outbox set status='SENDING',attempt_count=attempt_count+1,started_at=$2,failure_code=null where order_id=$1 and status in ('PENDING','FAILED') returning order_id`, [row.order_id, now.toISOString()]) as { rows?: { order_id: string }[] }; if (!updated.rows?.length) throw new TypeError("PAID_REPORT_EMAIL_CLAIM_INVALID"); return { orderId: row.order_id, deliveryEmailEncrypted: row.delivery_email_encrypted, document: row.document }; }); }
  async complete(orderId: string, providerMessageId: string, now: Date) { const result = await this.database.query(`update paid_report_email_outbox set status='SENT',provider_message_id=$2,sent_at=$3 where order_id=$1 and status='SENDING' returning order_id`, [orderId, providerMessageId, now.toISOString()]) as { rows?: { order_id: string }[] }; if (!result.rows?.length) throw new TypeError("PAID_REPORT_EMAIL_COMPLETE_INVALID"); }
  async fail(orderId: string, failureCode: string) { await this.database.query(`update paid_report_email_outbox set status='FAILED',failure_code=$2 where order_id=$1 and status='SENDING'`, [orderId, failureCode.slice(0, 80)]); }
}
export class ResendPaidReportEmailClient implements PaidReportEmailClient {
  constructor(private readonly config: { apiKey: string; from: string; internalNotificationEmail?: string }, private readonly fetcher: typeof fetch = fetch) {}
  async send(input: { to: string; pdf: Uint8Array; idempotencyKey: string }) {
    const headers = { Authorization: `Bearer ${this.config.apiKey}`, "Content-Type": "application/json" };
    const response = await this.fetcher("https://api.resend.com/emails", { method: "POST", headers: { ...headers, "Idempotency-Key": input.idempotencyKey }, body: JSON.stringify({ from: this.config.from, to: [input.to], subject: "Expiya Cars karşılaştırma raporun hazır", html: "<p>Expiya Cars 3 araç karşılaştırma raporun ektedir.</p><p>Fiyat, donanım ve teslim koşullarını satın alma öncesinde yetkili satıcıdan doğrula.</p>", attachments: [{ filename: "expiya-cars-3-arac-karsilastirma-raporu.pdf", content: Buffer.from(input.pdf).toString("base64") }] }) });
    if (!response.ok) throw new TypeError(`RESEND_EMAIL_FAILED_${response.status}`);
    const body = await response.json() as { id?: unknown };
    if (typeof body.id !== "string") throw new TypeError("RESEND_EMAIL_RESPONSE_INVALID");
    if (this.config.internalNotificationEmail) {
      await this.fetcher("https://api.resend.com/emails", { method: "POST", headers: { ...headers, "Idempotency-Key": `${input.idempotencyKey}/internal` }, body: JSON.stringify({ from: this.config.from, to: [this.config.internalNotificationEmail], subject: "Expiya Cars rapor teslim edildi", html: `<p>Yeni bir ücretli karşılaştırma raporu müşteriye teslim edildi.</p><p>Sipariş referansı: ${input.idempotencyKey.replace("paid-report/", "")}</p><p>Alıcı: ${maskPaidReportDeliveryEmail(input.to)}</p><p>Bu operasyon bildiriminde kişiselleştirilmiş rapor ve müşteri verisi eki bulunmaz.</p>` }) }).catch(() => undefined);
    }
    return { messageId: body.id };
  }
}
export async function processOnePaidReportEmail(input: { repository: PaidReportEmailOutboxRepository; client: PaidReportEmailClient; now?: Date; environment?: NodeJS.ProcessEnv }) { const now = input.now ?? new Date(); const job = await input.repository.claim(now); if (!job) return { status: "IDLE" as const }; try { const to = decryptPaidReportDeliveryEmail(job.deliveryEmailEncrypted, input.environment); const pdf = await createPaidComparisonPdf(job.document); const sent = await input.client.send({ to, pdf, idempotencyKey: `paid-report/${job.orderId}` }); await input.repository.complete(job.orderId, sent.messageId, now); return { status: "SENT" as const, orderId: job.orderId }; } catch (error) { await input.repository.fail(job.orderId, error instanceof Error ? error.message : "PAID_REPORT_EMAIL_FAILED"); return { status: "FAILED" as const, orderId: job.orderId }; } }
export function resolvePaidReportEmailConfig(environment: NodeJS.ProcessEnv = process.env) { const apiKey = environment.RESEND_API_KEY; const from = environment.PAID_REPORT_FROM_EMAIL; if (!apiKey || !from) throw new TypeError("PAID_REPORT_EMAIL_CONFIG_REQUIRED"); return { apiKey, from, internalNotificationEmail: environment.PAID_REPORT_INTERNAL_NOTIFICATION_EMAIL }; }
