import type { BudgetState, MoneyTry } from "../domain/budget";
import type { CatalogSnapshot } from "../catalog/types";
import type { TechnicalCandidatePool } from "../filter/types";
import { evaluatePriceAuthority } from "./priceAuthority";
import type { AffordabilityPolicy, PriceAuthorityPolicy } from "./policy";
import type { AffordabilityCandidatePool, AffordabilityCandidateResult, AffordabilityDiagnostic, AffordabilityReasonCode, AffordabilitySoftSignal, BudgetIncreaseGuidance, PriceAuthorityEvaluation } from "./types";

function deepFreeze<T>(value: T, seen = new WeakSet<object>()): T { if (!value || typeof value !== "object" || seen.has(value as object)) return value; seen.add(value as object); for (const child of Object.values(value as object)) deepFreeze(child, seen); return Object.freeze(value); }
function validMoney(value: MoneyTry | undefined): boolean { return value === undefined || (value.currency === "TRY" && Number.isFinite(value.amount) && value.amount > 0); }

export function evaluateAffordabilityCandidatePool(input: { readonly snapshot: CatalogSnapshot; readonly technicalPool: TechnicalCandidatePool; readonly budget: BudgetState; readonly evaluationTime: string; readonly priceAuthorityPolicy: PriceAuthorityPolicy; readonly affordabilityPolicy: AffordabilityPolicy }): AffordabilityCandidatePool {
  const diagnostics: AffordabilityDiagnostic[] = [];
  const parsedTime = Date.parse(input.evaluationTime); if (!Number.isFinite(parsedTime) || new Date(parsedTime).toISOString() !== input.evaluationTime) diagnostics.push({ code: "INVALID_EVALUATION_TIME" });
  const fingerprintMatches = input.snapshot.authority.catalogFingerprint === input.technicalPool.catalogFingerprint; if (!fingerprintMatches) diagnostics.push({ code: "CATALOG_FINGERPRINT_MISMATCH" });
  const snapshotIds = new Set(input.snapshot.variants.map((variant) => variant.id)); const technicalIds = new Set(input.technicalPool.initialCandidateIds); const candidateScopeMatches = snapshotIds.size === technicalIds.size && [...snapshotIds].every((id) => technicalIds.has(id)); if (!candidateScopeMatches) diagnostics.push({ code: "CANDIDATE_SCOPE_MISMATCH" });
  if (![input.budget.availableCash, input.budget.preferredBudget, input.budget.maximumHardCeiling].every(validMoney)) diagnostics.push({ code: "INVALID_BUDGET_AMOUNT" });
  if (input.budget.budgetExcluded && input.budget.maximumHardCeiling) diagnostics.push({ code: "BUDGET_EXCLUDED_WITH_HARD_CEILING" });
  if (input.budget.budgetImportance === "HARD" && !input.budget.maximumHardCeiling) diagnostics.push({ code: "HARD_BUDGET_WITHOUT_CEILING" });
  if (input.budget.budgetUnknown && input.budget.maximumHardCeiling) diagnostics.push({ code: "BUDGET_UNKNOWN_WITH_HARD_CEILING" });
  if (input.budget.unresolvedFinancedCeiling) diagnostics.push({ code: "UNRESOLVED_FINANCED_CEILING_NOT_APPLIED" });
  const hardCeilingValid = validMoney(input.budget.maximumHardCeiling) && !!input.budget.maximumHardCeiling && !input.budget.budgetExcluded && !input.budget.budgetUnknown && fingerprintMatches && candidateScopeMatches && Number.isFinite(parsedTime);
  const variantById = new Map(input.snapshot.variants.map((variant) => [variant.id, variant]));
  const candidates: AffordabilityCandidateResult[] = [...input.technicalPool.candidates].sort((a, b) => a.exactVariantId.localeCompare(b.exactVariantId)).map((technical) => {
    const variant = variantById.get(technical.exactVariantId); const preserveOnly = technical.disposition !== "ELIGIBLE";
    const priceAuthority: PriceAuthorityEvaluation = preserveOnly ? Object.freeze({ state: "UNKNOWN" as const, decisionUse: "NO_AFFORDABILITY_USE" as const, reasonCodes: ["PRICE_UNKNOWN" as const], factReferences: [], realizationPermission: "NO_PRICE_LANGUAGE" as const, hardBudgetEvaluationAllowed: false }) : evaluatePriceAuthority({ price: variant?.activeNewPrice, exactVariantId: technical.exactVariantId, catalogFingerprint: input.snapshot.authority.catalogFingerprint, evaluationTime: input.evaluationTime, policy: input.priceAuthorityPolicy });
    const internalEstimateAmount = priceAuthority.decisionUse === "INTERNAL_APPROXIMATE_AFFORDABILITY" ? variant?.activeNewPrice?.amountTry : undefined;
    const reasons: AffordabilityReasonCode[] = [...priceAuthority.reasonCodes]; let budgetDisposition: AffordabilityCandidateResult["budgetDisposition"] = "NOT_APPLIED"; let finalDisposition: AffordabilityCandidateResult["finalDisposition"]; let tier: AffordabilityCandidateResult["affordabilityTier"];
    if (technical.disposition === "ELIMINATED") { finalDisposition = "ELIMINATED"; tier = "ELIMINATED"; reasons.push("TECHNICAL_ELIMINATION_PRESERVED"); }
    else if (technical.disposition === "NOT_EVALUABLE") { finalDisposition = "TECHNICALLY_NOT_EVALUABLE"; tier = "TECHNICALLY_NOT_EVALUABLE"; budgetDisposition = hardCeilingValid ? "NOT_EVALUABLE" : "NOT_APPLIED"; reasons.push("TECHNICAL_NOT_EVALUABLE_PRESERVED"); }
    else if (input.budget.maximumHardCeiling && !input.budget.budgetExcluded && !hardCeilingValid) { budgetDisposition = "NOT_EVALUABLE"; finalDisposition = "TECHNICALLY_ELIGIBLE_PRICE_UNRESOLVED"; tier = "PRICE_UNRESOLVED"; reasons.push("PRICE_INVALID"); }
    else if (!hardCeilingValid) { finalDisposition = "ELIGIBLE_BUDGET_NOT_APPLIED"; tier = "BUDGET_NOT_APPLIED"; reasons.push(input.budget.budgetExcluded ? "BUDGET_EXCLUDED" : "BUDGET_NOT_APPLIED"); if (input.budget.availableCash) reasons.push("AVAILABLE_CASH_NOT_HARD_CEILING"); if (input.budget.preferredBudget) reasons.push("PREFERRED_BUDGET_NOT_HARD_CEILING"); if (input.budget.financeFlexibility !== "NONE") reasons.push("FINANCE_FLEXIBILITY_NOT_A_CEILING"); }
    else if (priceAuthority.decisionUse === "PUBLIC_EXACT_AFFORDABILITY" && priceAuthority.publicExactAmountTry !== undefined) { const within = priceAuthority.publicExactAmountTry <= input.budget.maximumHardCeiling!.amount; budgetDisposition = within ? "CONFIRMED_WITHIN_BUDGET" : "CONFIRMED_OVER_BUDGET"; finalDisposition = within ? "FULLY_ELIGIBLE_VERIFIED_PRICE" : "CONFIRMED_OVER_BUDGET"; tier = within ? "VERIFIED_WITHIN_BUDGET" : "VERIFIED_OVER_BUDGET"; reasons.push(within ? "PRICE_CONFIRMED_WITHIN_BUDGET" : "PRICE_CONFIRMED_OVER_BUDGET"); }
    else if (priceAuthority.decisionUse === "INTERNAL_APPROXIMATE_AFFORDABILITY" && internalEstimateAmount !== undefined) { const within = internalEstimateAmount <= input.budget.maximumHardCeiling!.amount; budgetDisposition = "NOT_EVALUABLE"; finalDisposition = within ? "ELIGIBLE_INTERNAL_ESTIMATE_WITHIN_BUDGET" : "CONDITIONALLY_ELIGIBLE_ESTIMATED_OVER_BUDGET"; tier = within ? "ESTIMATED_WITHIN_BUDGET" : "ESTIMATED_OVER_BUDGET_CONDITIONAL"; reasons.push(within ? "ESTIMATE_APPROXIMATELY_WITHIN_BUDGET" : "ESTIMATE_APPROXIMATELY_OVER_BUDGET"); }
    else { budgetDisposition = "NOT_EVALUABLE"; finalDisposition = "TECHNICALLY_ELIGIBLE_PRICE_UNRESOLVED"; tier = "PRICE_UNRESOLVED"; }
    const softSignals: AffordabilitySoftSignal[] = [];
    if (technical.disposition === "ELIGIBLE" && priceAuthority.publicExactAmountTry !== undefined) { if (input.budget.preferredBudget) softSignals.push({ kind: priceAuthority.publicExactAmountTry <= input.budget.preferredBudget.amount ? "WITHIN_PREFERRED_BUDGET" : "OVER_PREFERRED_BUDGET", exactVariantId: technical.exactVariantId }); if (input.budget.availableCash && priceAuthority.publicExactAmountTry <= input.budget.availableCash.amount) softSignals.push({ kind: "WITHIN_AVAILABLE_CASH", exactVariantId: technical.exactVariantId }); else if (input.budget.availableCash && input.budget.financeFlexibility === "YES") softSignals.push({ kind: "FINANCING_MAY_BE_REQUIRED", exactVariantId: technical.exactVariantId }); }
    else if (technical.disposition === "ELIGIBLE" && priceAuthority.decisionUse === "NO_AFFORDABILITY_USE") softSignals.push({ kind: "PRICE_UNKNOWN", exactVariantId: technical.exactVariantId });
    const selectable = ["FULLY_ELIGIBLE_VERIFIED_PRICE", "ELIGIBLE_INTERNAL_ESTIMATE_WITHIN_BUDGET", "CONDITIONALLY_ELIGIBLE_ESTIMATED_OVER_BUDGET", "ELIGIBLE_BUDGET_NOT_APPLIED"].includes(finalDisposition);
    return { exactVariantId: technical.exactVariantId, technicalDisposition: technical.disposition, priceAuthority, budgetDisposition, finalDisposition, affordabilityTier: tier, selectable, affordabilityClaimAllowed: finalDisposition === "FULLY_ELIGIBLE_VERIFIED_PRICE", priceMentionAllowed: priceAuthority.realizationPermission === "EXACT_PUBLIC_PRICE_ALLOWED", includedInMinimumBudgetIncrease: finalDisposition === "CONFIRMED_OVER_BUDGET", reasonCodes: [...new Set(reasons)], factReferences: priceAuthority.factReferences, policyReferences: [{ policyId: input.priceAuthorityPolicy.policyId, policyVersion: input.priceAuthorityPolicy.policyVersion, decisionEffect: hardCeilingValid ? "HARD_FILTER" : "EXPLANATION_ONLY" }, { policyId: input.affordabilityPolicy.policyId, policyVersion: input.affordabilityPolicy.policyVersion, decisionEffect: hardCeilingValid ? "HARD_FILTER" : "EXPLANATION_ONLY" }], softSignals };
  });
  const eligibleTechnical = candidates.filter((candidate) => candidate.technicalDisposition === "ELIGIBLE"); const guidance: BudgetIncreaseGuidance[] = [];
  if (!input.budget.maximumHardCeiling || input.budget.budgetExcluded) guidance.push({ status: "NO_HARD_CEILING", authority: "UNAVAILABLE" });
  else if (!eligibleTechnical.length) guidance.push({ status: "TECHNICAL_POOL_EMPTY", authority: "UNAVAILABLE" });
  else {
    const ceiling = input.budget.maximumHardCeiling.amount;
    const verifiedOver = candidates.filter((candidate) => candidate.finalDisposition === "CONFIRMED_OVER_BUDGET" && candidate.priceAuthority.publicExactAmountTry !== undefined);
    if (verifiedOver.length) { const nearest = Math.min(...verifiedOver.map((candidate) => candidate.priceAuthority.publicExactAmountTry!)); const increase = nearest - ceiling; const exactPercent = increase / ceiling * 100; const suggestedPercent = Math.ceil(exactPercent / input.affordabilityPolicy.suggestedIncreaseStepPercent) * input.affordabilityPolicy.suggestedIncreaseStepPercent; guidance.push({ status: "VERIFIED_AVAILABLE", authority: "VERIFIED", currentCeilingTry: ceiling, nearestEligiblePriceTry: nearest, exactIncreaseTry: increase, exactIncreasePercent: exactPercent, suggestedIncreasePercent: suggestedPercent, suggestedCeilingTry: Math.max(nearest, Math.ceil(ceiling * (1 + suggestedPercent / 100))), candidateIds: verifiedOver.filter((candidate) => candidate.priceAuthority.publicExactAmountTry === nearest).map((candidate) => candidate.exactVariantId).sort(), priceFactReferences: verifiedOver.filter((candidate) => candidate.priceAuthority.publicExactAmountTry === nearest).flatMap((candidate) => candidate.factReferences) }); }
    const estimatedOver = candidates.filter((candidate) => candidate.finalDisposition === "CONDITIONALLY_ELIGIBLE_ESTIMATED_OVER_BUDGET").map((candidate) => ({ candidate, amount: variantById.get(candidate.exactVariantId)?.activeNewPrice?.amountTry })).filter((entry): entry is { candidate: AffordabilityCandidateResult; amount: number } => typeof entry.amount === "number");
    if (estimatedOver.length) { const nearest = Math.min(...estimatedOver.map((entry) => entry.amount)); const exactPercent = (nearest - ceiling) / ceiling * 100; const step = input.affordabilityPolicy.estimatedGuidanceBandPercent; const minimum = Math.floor(exactPercent / step) * step; const maximum = Math.max(minimum + step, Math.ceil(exactPercent / step) * step); const rounding = input.affordabilityPolicy.estimatedBudgetBandRoundingTry; guidance.push({ status: "ESTIMATED_AVAILABLE", authority: "APPROXIMATE_INTERNAL_ESTIMATE", currentCeilingTry: ceiling, approximateIncreasePercentBand: { minimum, maximum }, approximateSuggestedBudgetBandTry: { minimum: Math.floor(ceiling * (1 + minimum / 100) / rounding) * rounding, maximum: Math.ceil(ceiling * (1 + maximum / 100) / rounding) * rounding }, candidateIds: estimatedOver.filter((entry) => entry.amount === nearest).map((entry) => entry.candidate.exactVariantId).sort(), requiredLanguage: ["TAHMINEN_OR_APPROXIMATELY", "NOT_A_VERIFIED_PRICE"], exactEstimateDisclosureAllowed: false }); }
    if (!guidance.length) guidance.push({ status: eligibleTechnical.some((candidate) => candidate.affordabilityTier === "PRICE_UNRESOLVED") ? "INSUFFICIENT_PRICE_AUTHORITY" : "NO_OVER_BUDGET_SIGNAL", authority: "UNAVAILABLE" });
  }
  const ids = (disposition: AffordabilityCandidateResult["finalDisposition"]) => candidates.filter((candidate) => candidate.finalDisposition === disposition).map((candidate) => candidate.exactVariantId);
  return deepFreeze({ catalogFingerprint: input.snapshot.authority.catalogFingerprint, decisionFingerprint: input.technicalPool.decisionFingerprint, evaluationTime: input.evaluationTime, initialCandidateIds: candidates.map((candidate) => candidate.exactVariantId), verifiedPriceEligibleCandidateIds: ids("FULLY_ELIGIBLE_VERIFIED_PRICE"), internalEstimateWithinCandidateIds: ids("ELIGIBLE_INTERNAL_ESTIMATE_WITHIN_BUDGET"), estimatedOverBudgetConditionalCandidateIds: ids("CONDITIONALLY_ELIGIBLE_ESTIMATED_OVER_BUDGET"), budgetNotAppliedEligibleCandidateIds: ids("ELIGIBLE_BUDGET_NOT_APPLIED"), priceUnresolvedCandidateIds: ids("TECHNICALLY_ELIGIBLE_PRICE_UNRESOLVED"), technicallyNotEvaluableCandidateIds: ids("TECHNICALLY_NOT_EVALUABLE"), verifiedOverBudgetCandidateIds: ids("CONFIRMED_OVER_BUDGET"), eliminatedCandidateIds: ids("ELIMINATED"), selectableCandidateIds: candidates.filter((candidate) => candidate.selectable).map((candidate) => candidate.exactVariantId), candidates, budgetIncreaseGuidance: guidance, trace: candidates.map((candidate) => ({ exactVariantId: candidate.exactVariantId, technicalDisposition: candidate.technicalDisposition, priceAuthorityState: candidate.priceAuthority.state, budgetDisposition: candidate.budgetDisposition, finalDisposition: candidate.finalDisposition, reasonCodes: candidate.reasonCodes })), diagnostics });
}
