import type { CatalogPriceObservationFact } from "../catalog/types";
import type { CatalogFactReference } from "../usage/types";
import type { PriceAuthorityPolicy } from "./policy";
import type { PriceAuthorityEvaluation } from "./types";

function reference(price: CatalogPriceObservationFact): CatalogFactReference { return Object.freeze({ field: "activeNewPrice", catalogFingerprint: price.catalogFingerprint, confidence: price.confidence, provenanceCount: price.provenance.length, factKind: "CANONICAL" }); }
export function evaluatePriceAuthority(input: { readonly price?: CatalogPriceObservationFact; readonly exactVariantId: string; readonly catalogFingerprint: string; readonly evaluationTime: string; readonly vehicleUseClass?: "PASSENGER" | "LIGHT_COMMERCIAL" | "HEAVY_COMMERCIAL"; readonly policy: PriceAuthorityPolicy }): PriceAuthorityEvaluation {
  const price = input.price; if (!price) return Object.freeze({ state: "UNKNOWN", decisionUse: "NO_AFFORDABILITY_USE", reasonCodes: ["PRICE_UNKNOWN"] as const, factReferences: [], realizationPermission: "NO_PRICE_LANGUAGE", hardBudgetEvaluationAllowed: false });
  const refs = [reference(price)];
  const now = Date.parse(input.evaluationTime), from = Date.parse(price.validFrom), until = price.validUntil === undefined ? undefined : Date.parse(price.validUntil);
  if (price.priceType === "ESTIMATE" && price.consumerVisibility === "INTERNAL_ONLY") {
    const valid = Number.isFinite(now) && Number.isFinite(from) && now >= from && (until === undefined || (Number.isFinite(until) && now <= until)) && price.vehicleVariantId === input.exactVariantId && price.market === "TR" && price.condition === "NEW" && price.catalogFingerprint === input.catalogFingerprint && price.provenance.length > 0 && Number.isFinite(price.amountTry) && price.amountTry > 0;
    if (!valid) return Object.freeze({ state: "INVALID", decisionUse: "NO_AFFORDABILITY_USE", priceObservationId: price.id, reasonCodes: ["PRICE_INVALID"] as const, factReferences: refs, realizationPermission: "NO_PRICE_LANGUAGE", hardBudgetEvaluationAllowed: false });
    return Object.freeze({ state: "INTERNAL_ESTIMATE", decisionUse: "INTERNAL_APPROXIMATE_AFFORDABILITY", priceObservationId: price.id, estimationMethodPresent: typeof price.estimationMethod === "string" && price.estimationMethod.length > 0, taxTreatment: price.taxTreatment, validFrom: price.validFrom, validUntil: price.validUntil, reasonCodes: ["PRICE_INTERNAL_ESTIMATE"] as const, factReferences: refs, realizationPermission: "APPROXIMATE_BUDGET_LANGUAGE_ONLY", hardBudgetEvaluationAllowed: false });
  }
  const structurallyValid = Number.isFinite(now) && Number.isFinite(from) && (until === undefined || Number.isFinite(until)) && price.market === "TR" && price.condition === "NEW" && price.consumerVisibility === "PUBLIC" && price.realizationSafe && price.catalogFingerprint === input.catalogFingerprint && price.provenance.length > 0 && price.confidence !== "LOW" && Number.isFinite(price.amountTry) && price.amountTry > 0 && (price.priceType === "LIST" || price.priceType === "CAMPAIGN");
  if (!structurallyValid) return Object.freeze({ state: "INVALID", decisionUse: "NO_AFFORDABILITY_USE", priceObservationId: price.id, reasonCodes: ["PRICE_INVALID"] as const, factReferences: refs, realizationPermission: "NO_PRICE_LANGUAGE", hardBudgetEvaluationAllowed: false });
  if (price.priceType === "CAMPAIGN") return Object.freeze({ state: "VERIFIED_CURRENT", decisionUse: "NO_AFFORDABILITY_USE", priceObservationId: price.id, reasonCodes: ["CONDITIONAL_CAMPAIGN"] as const, factReferences: refs, realizationPermission: "NO_PRICE_LANGUAGE", hardBudgetEvaluationAllowed: false });
  if (now < from) return Object.freeze({ state: "VERIFIED_NOT_YET_VALID", decisionUse: "NO_AFFORDABILITY_USE", priceObservationId: price.id, reasonCodes: ["PRICE_NOT_YET_VALID"] as const, factReferences: refs, realizationPermission: "NO_PRICE_LANGUAGE", hardBudgetEvaluationAllowed: false });
  if (until !== undefined && now > until) return Object.freeze({ state: "VERIFIED_STALE", decisionUse: "NO_AFFORDABILITY_USE", priceObservationId: price.id, reasonCodes: ["PRICE_STALE"] as const, factReferences: refs, realizationPermission: "NO_PRICE_LANGUAGE", hardBudgetEvaluationAllowed: false });
  if (input.vehicleUseClass === "LIGHT_COMMERCIAL" || input.vehicleUseClass === "HEAVY_COMMERCIAL") {
    if (price.taxTreatment === "UNKNOWN") return Object.freeze({ state: "INVALID", decisionUse: "NO_AFFORDABILITY_USE", priceObservationId: price.id, taxTreatment: price.taxTreatment, validFrom: price.validFrom, validUntil: price.validUntil, reasonCodes: ["COMMERCIAL_PRICE_TAX_TREATMENT_UNKNOWN"] as const, factReferences: refs, realizationPermission: "NO_PRICE_LANGUAGE", hardBudgetEvaluationAllowed: false });
    if (price.taxTreatment === "EXCLUDED") return Object.freeze({ state: "VERIFIED_CURRENT", decisionUse: "NO_AFFORDABILITY_USE", priceObservationId: price.id, taxTreatment: price.taxTreatment, validFrom: price.validFrom, validUntil: price.validUntil, reasonCodes: ["COMMERCIAL_PRICE_EXCLUDES_TAX"] as const, factReferences: refs, realizationPermission: "NO_PRICE_LANGUAGE", hardBudgetEvaluationAllowed: false });
  }
  return Object.freeze({ state: "VERIFIED_CURRENT", decisionUse: "PUBLIC_EXACT_AFFORDABILITY", publicExactAmountTry: price.amountTry, priceObservationId: price.id, taxTreatment: price.taxTreatment, validFrom: price.validFrom, validUntil: price.validUntil, reasonCodes: ["VERIFIED_LIST_PRICE_CURRENT"] as const, factReferences: refs, realizationPermission: "EXACT_PUBLIC_PRICE_ALLOWED", hardBudgetEvaluationAllowed: true });
}
