import type { CatalogFactReference, UsagePolicyReference as PolicyReference } from "../usage/types";
import type { PriceAuthorityState, BudgetDisposition } from "../domain/affordability";
import type { TechnicalCandidateDisposition } from "../filter/types";

export type PriceDecisionUse = "PUBLIC_EXACT_AFFORDABILITY" | "INTERNAL_APPROXIMATE_AFFORDABILITY" | "NO_AFFORDABILITY_USE";
export type PriceRealizationPermission = "EXACT_PUBLIC_PRICE_ALLOWED" | "APPROXIMATE_BUDGET_LANGUAGE_ONLY" | "NO_PRICE_LANGUAGE";
export type AffordabilityTier = "VERIFIED_WITHIN_BUDGET" | "ESTIMATED_WITHIN_BUDGET" | "BUDGET_NOT_APPLIED" | "ESTIMATED_OVER_BUDGET_CONDITIONAL" | "PRICE_UNRESOLVED" | "VERIFIED_OVER_BUDGET" | "TECHNICALLY_NOT_EVALUABLE" | "ELIMINATED";
export type FinalCandidateDisposition = "FULLY_ELIGIBLE_VERIFIED_PRICE" | "ELIGIBLE_INTERNAL_ESTIMATE_WITHIN_BUDGET" | "ELIGIBLE_BUDGET_NOT_APPLIED" | "CONDITIONALLY_ELIGIBLE_ESTIMATED_OVER_BUDGET" | "TECHNICALLY_ELIGIBLE_PRICE_UNRESOLVED" | "TECHNICALLY_NOT_EVALUABLE" | "CONFIRMED_OVER_BUDGET" | "ELIMINATED";
export type AffordabilityReasonCode = "BUDGET_NOT_APPLIED" | "BUDGET_EXCLUDED" | "AVAILABLE_CASH_NOT_HARD_CEILING" | "PREFERRED_BUDGET_NOT_HARD_CEILING" | "FINANCE_FLEXIBILITY_NOT_A_CEILING" | "VERIFIED_LIST_PRICE_CURRENT" | "PRICE_CONFIRMED_WITHIN_BUDGET" | "PRICE_CONFIRMED_OVER_BUDGET" | "ESTIMATE_APPROXIMATELY_WITHIN_BUDGET" | "ESTIMATE_APPROXIMATELY_OVER_BUDGET" | "PRICE_UNKNOWN" | "PRICE_INTERNAL_ESTIMATE" | "PRICE_STALE" | "PRICE_NOT_YET_VALID" | "PRICE_INVALID" | "CONDITIONAL_CAMPAIGN" | "TECHNICAL_NOT_EVALUABLE_PRESERVED" | "TECHNICAL_ELIMINATION_PRESERVED" | "MINIMUM_INCREASE_AVAILABLE" | "MINIMUM_INCREASE_NOT_COMPUTABLE";
export interface PriceAuthorityEvaluation { readonly state: PriceAuthorityState; readonly decisionUse: PriceDecisionUse; readonly publicExactAmountTry?: number; readonly priceObservationId?: string; readonly estimationMethodPresent?: boolean; readonly reasonCodes: readonly AffordabilityReasonCode[]; readonly factReferences: readonly CatalogFactReference[]; readonly realizationPermission: PriceRealizationPermission; readonly hardBudgetEvaluationAllowed: boolean }
export interface AffordabilitySoftSignal { readonly kind: "WITHIN_PREFERRED_BUDGET" | "OVER_PREFERRED_BUDGET" | "WITHIN_AVAILABLE_CASH" | "FINANCING_MAY_BE_REQUIRED" | "PRICE_UNKNOWN"; readonly exactVariantId: string }
export interface AffordabilityCandidateResult { readonly exactVariantId: string; readonly technicalDisposition: TechnicalCandidateDisposition; readonly priceAuthority: PriceAuthorityEvaluation; readonly budgetDisposition: BudgetDisposition; readonly finalDisposition: FinalCandidateDisposition; readonly affordabilityTier: AffordabilityTier; readonly selectable: boolean; readonly affordabilityClaimAllowed: boolean; readonly priceMentionAllowed: boolean; readonly includedInMinimumBudgetIncrease: boolean; readonly reasonCodes: readonly AffordabilityReasonCode[]; readonly factReferences: readonly CatalogFactReference[]; readonly policyReferences: readonly PolicyReference[]; readonly softSignals: readonly AffordabilitySoftSignal[] }
export type VerifiedBudgetIncreaseGuidance = { readonly status: "VERIFIED_AVAILABLE"; readonly authority: "VERIFIED"; readonly currentCeilingTry: number; readonly nearestEligiblePriceTry: number; readonly exactIncreaseTry: number; readonly exactIncreasePercent: number; readonly suggestedIncreasePercent: number; readonly suggestedCeilingTry: number; readonly candidateIds: readonly string[]; readonly priceFactReferences: readonly CatalogFactReference[] };
export type EstimatedBudgetIncreaseGuidance = { readonly status: "ESTIMATED_AVAILABLE"; readonly authority: "APPROXIMATE_INTERNAL_ESTIMATE"; readonly currentCeilingTry: number; readonly approximateIncreasePercentBand: { readonly minimum: number; readonly maximum: number }; readonly approximateSuggestedBudgetBandTry: { readonly minimum: number; readonly maximum: number }; readonly candidateIds: readonly string[]; readonly requiredLanguage: readonly ["TAHMINEN_OR_APPROXIMATELY", "NOT_A_VERIFIED_PRICE"]; readonly exactEstimateDisclosureAllowed: false };
export type BudgetIncreaseUnavailable = { readonly status: "NO_HARD_CEILING" | "NO_OVER_BUDGET_SIGNAL" | "TECHNICAL_POOL_EMPTY" | "INSUFFICIENT_PRICE_AUTHORITY"; readonly authority: "UNAVAILABLE" };
export type BudgetIncreaseGuidance = VerifiedBudgetIncreaseGuidance | EstimatedBudgetIncreaseGuidance | BudgetIncreaseUnavailable;
export type AffordabilityDiagnosticCode = "CATALOG_FINGERPRINT_MISMATCH" | "CANDIDATE_SCOPE_MISMATCH" | "INVALID_EVALUATION_TIME" | "BUDGET_EXCLUDED_WITH_HARD_CEILING" | "HARD_BUDGET_WITHOUT_CEILING" | "INVALID_BUDGET_AMOUNT" | "BUDGET_UNKNOWN_WITH_HARD_CEILING" | "UNRESOLVED_FINANCED_CEILING_NOT_APPLIED";
export interface AffordabilityDiagnostic { readonly code: AffordabilityDiagnosticCode; readonly referenceId?: string }
export interface AffordabilityTraceStep { readonly exactVariantId: string; readonly technicalDisposition: TechnicalCandidateDisposition; readonly priceAuthorityState: PriceAuthorityState; readonly budgetDisposition: BudgetDisposition; readonly finalDisposition: FinalCandidateDisposition; readonly reasonCodes: readonly AffordabilityReasonCode[] }
export interface AffordabilityCandidatePool { readonly catalogFingerprint: string; readonly decisionFingerprint: string; readonly evaluationTime: string; readonly initialCandidateIds: readonly string[]; readonly verifiedPriceEligibleCandidateIds: readonly string[]; readonly internalEstimateWithinCandidateIds: readonly string[]; readonly estimatedOverBudgetConditionalCandidateIds: readonly string[]; readonly budgetNotAppliedEligibleCandidateIds: readonly string[]; readonly priceUnresolvedCandidateIds: readonly string[]; readonly technicallyNotEvaluableCandidateIds: readonly string[]; readonly verifiedOverBudgetCandidateIds: readonly string[]; readonly eliminatedCandidateIds: readonly string[]; readonly selectableCandidateIds: readonly string[]; readonly candidates: readonly AffordabilityCandidateResult[]; readonly budgetIncreaseGuidance: readonly BudgetIncreaseGuidance[]; readonly trace: readonly AffordabilityTraceStep[]; readonly diagnostics: readonly AffordabilityDiagnostic[] }
