import type { Pool, PoolClient } from "pg";
import type { ConversationEvent } from "../domain/conversationEvent";
import type { GovernedOfferStore, OfferStoreResult, PersistedGovernedOffer, PersistedOfferState } from "../offer/types";
import type { PersistedOfferTransitionIntent, StoredV2Conversation, V2ConversationStore } from "../orchestrator/types";
import { resolvePersistedRecommendationOfferAuditProof, type RecommendationOfferAuditProof } from "../offer/recOfferAuditFoundation.server";
export class PostgresV2ConversationStore implements V2ConversationStore, GovernedOfferStore {
  readonly persistsCreationWithConversationCommit = true;
  constructor(private readonly pool: Pick<Pool, "connect">) {}
  async load(conversationId: string): Promise<StoredV2Conversation | null> { const client = await this.pool.connect(); try { const conversation = await client.query("select revision, memory from cars_decision_v2_conversations where conversation_id=$1", [conversationId]); if (!(conversation.rowCount ?? 0)) return null; const messages = await client.query("select message_id,payload_hash,public_output from cars_decision_v2_messages where conversation_id=$1", [conversationId]); return { conversationId, revision: conversation.rows[0].revision, memory: conversation.rows[0].memory, messageResults: Object.fromEntries(messages.rows.map((row) => [row.message_id, { payloadHash: row.payload_hash, output: row.public_output }])) }; } finally { client.release(); } }
  async get(offerId: string): Promise<PersistedGovernedOffer | null> { const client = await this.pool.connect(); try { const result = await client.query("select * from cars_decision_v2_offers where offer_id=$1", [offerId]); return (result.rowCount ?? 0) ? this.offerFromRow(result.rows[0]) : null; } finally { client.release(); } }
  async resolveRecommendationOfferAuditProof(conversationId: string, offerId: string, expectedCatalogFingerprint?: string): Promise<RecommendationOfferAuditProof> { const client = await this.pool.connect(); try { const offerResult = await client.query("select * from cars_decision_v2_offers where offer_id=$1", [offerId]); const offer = (offerResult.rowCount ?? 0) ? this.offerFromRow(offerResult.rows[0]) : null; const eventResult = await client.query("select canonical_payload from cars_decision_v2_events where conversation_id=$1 and event_type in ('RECOMMENDATION_TERMS_ACCEPTED','OFFER_REVEALED') and canonical_payload->>'offerId'=$2 order by source_turn,sequence", [conversationId, offerId]); return resolvePersistedRecommendationOfferAuditProof({ conversationId, offerId, offer, events: eventResult.rows.map((row) => row.canonical_payload), expectedCatalogFingerprint }); } finally { client.release(); } }
  async create(record: PersistedGovernedOffer, expectedConversationRevision: number, idempotencyKey: string): Promise<OfferStoreResult> { void record; void expectedConversationRevision; void idempotencyKey; return { status: "INVALID_TRANSITION" }; }
  async transition(input: { readonly offerId: string; readonly conversationId: string; readonly to: PersistedOfferState; readonly at: string; readonly expectedConversationRevision: number; readonly idempotencyKey: string }): Promise<OfferStoreResult> { const client = await this.pool.connect(); try { await client.query("begin"); const conversation = await client.query("select revision from cars_decision_v2_conversations where conversation_id=$1 for update", [input.conversationId]); if (!(conversation.rowCount ?? 0) || conversation.rows[0].revision !== input.expectedConversationRevision) { await client.query("rollback"); return { status: "REVISION_CONFLICT" }; } const found = await client.query("select * from cars_decision_v2_offers where offer_id=$1 for update", [input.offerId]); if (!(found.rowCount ?? 0)) { await client.query("rollback"); return { status: "NOT_FOUND" }; } const record = this.offerFromRow(found.rows[0]); if (record.conversationId !== input.conversationId) { await client.query("rollback"); return { status: "WRONG_CONVERSATION" }; } const allowed: Readonly<Record<PersistedOfferState, readonly PersistedOfferState[]>> = { CREATED: ["CONSENTED", "EXPIRED", "REVOKED"], CONSENTED: ["REVEALED", "EXPIRED", "REVOKED"], REVEALED: [], EXPIRED: [], REVOKED: [] }; if (record.lifecycleState === input.to && input.to === "REVEALED") { await client.query("commit"); return { status: "OK", record, revision: input.expectedConversationRevision }; } if (!allowed[record.lifecycleState].includes(input.to)) { await client.query("rollback"); return { status: "INVALID_TRANSITION" }; } if (Date.parse(record.expiresAt) < Date.parse(input.at)) { await client.query("rollback"); return { status: "EXPIRED" }; } await client.query("update cars_decision_v2_offers set lifecycle=$2, consented_at=case when $2='CONSENTED' then $3 else consented_at end, revealed_at=case when $2='REVEALED' then $3 else revealed_at end where offer_id=$1", [input.offerId, input.to, input.at]); await client.query("commit"); return { status: "OK", record: { ...record, lifecycleState: input.to, ...(input.to === "CONSENTED" ? { consentedAt: input.at } : {}), ...(input.to === "REVEALED" ? { revealedAt: input.at } : {}) }, revision: input.expectedConversationRevision }; } catch (error) { await client.query("rollback"); throw error; } finally { client.release(); } }
  async revokeByConversationDecisionFingerprint(conversationId: string, currentDecisionFingerprint: string): Promise<void> { const client = await this.pool.connect(); try { await client.query("update cars_decision_v2_offers set lifecycle='REVOKED' where conversation_id=$1 and decision_fingerprint<>$2 and lifecycle in ('CREATED','CONSENTED')", [conversationId, currentDecisionFingerprint]); } finally { client.release(); } }
  async commit(input: { readonly expectedRevision: number; readonly next: StoredV2Conversation; readonly events: readonly ConversationEvent[]; readonly offer?: PersistedGovernedOffer; readonly offerTransition?: PersistedOfferTransitionIntent }): Promise<{ readonly status: "OK" } | { readonly status: "REVISION_CONFLICT" }> { const client = await this.pool.connect(); try { await client.query("begin"); const locked = await client.query("select revision from cars_decision_v2_conversations where conversation_id=$1 for update", [input.next.conversationId]); const exists = (locked.rowCount ?? 0) > 0; const revision = exists ? locked.rows[0].revision as number : 0; if (revision !== input.expectedRevision) { await client.query("rollback"); return { status: "REVISION_CONFLICT" }; }
    if (input.offerTransition?.to === "REVEALED") { const transition = input.offerTransition; if (!(Date.parse(transition.acceptedAt) < Date.parse(transition.revealedAt)) || transition.acceptanceSequence !== 1 || transition.revealSequence !== 2) throw new Error("REC_AUDIT_TEMPORAL_INVARIANT_FAILED"); const found = await client.query("select lifecycle,expires_at from cars_decision_v2_offers where offer_id=$1 and conversation_id=$2 for update", [transition.offerId, transition.conversationId]); if ((found.rowCount ?? 0) !== 1 || found.rows[0].lifecycle !== "CREATED") throw new Error("ATOMIC_OFFER_TRANSITION_FAILED"); if (Date.parse(String(found.rows[0].expires_at)) < Date.parse(transition.revealedAt)) throw new Error("OFFER_EXPIRED"); }
    for (const event of input.events) await client.query("insert into cars_decision_v2_events (conversation_id,event_id,source_turn,sequence,event_type,schema_version,canonical_payload,created_at) values ($1,$2,$3,$4,$5,$6,$7,$8)", [input.next.conversationId, event.id, event.sourceTurn, event.sequence, event.eventType, event.schemaVersion, event, event.createdAt]);
    if (input.offerTransition?.to === "REVEALED") { const transition = input.offerTransition; const transitioned = await client.query("update cars_decision_v2_offers set lifecycle='REVEALED',consented_at=$3,revealed_at=$4 where offer_id=$1 and conversation_id=$2 and lifecycle='CREATED'", [transition.offerId, transition.conversationId, transition.acceptedAt, transition.revealedAt]); if (transitioned.rowCount !== 1) throw new Error("ATOMIC_OFFER_TRANSITION_FAILED"); }
    if (input.offerTransition?.to === "REVOKED") { const transitioned = await client.query("update cars_decision_v2_offers set lifecycle='REVOKED' where offer_id=$1 and conversation_id=$2 and lifecycle in ('CREATED','CONSENTED')", [input.offerTransition.offerId, input.offerTransition.conversationId]); if (transitioned.rowCount !== 1) throw new Error("ATOMIC_OFFER_TRANSITION_FAILED"); }
    await this.writeConversation(client, input.next, exists); const message = Object.entries(input.next.messageResults).find(([, value]) => value.output.revision === input.next.revision); if (message) await client.query("insert into cars_decision_v2_messages (conversation_id,message_id,idempotency_key,payload_hash,committed_revision,public_output) values ($1,$2,$3,$4,$5,$6)", [input.next.conversationId, message[0], `${input.next.conversationId}:${message[0]}`, message[1].payloadHash, input.next.revision, message[1].output]); if (input.offer) await this.writeOffer(client, input.offer); await client.query("commit"); return { status: "OK" }; } catch (error) { await client.query("rollback"); console.info("cars_decision_v2_commit_failure", { errorClass: error instanceof Error ? error.name : "UNKNOWN", errorCode: safePersistenceErrorCode(error) }); throw error; } finally { client.release(); } }
  private async writeConversation(client: PoolClient, value: StoredV2Conversation, exists: boolean) { const memory = value.memory!; if (exists) await client.query("update cars_decision_v2_conversations set revision=$2,memory=$3,memory_fingerprint=$4,decision_fingerprint=$5,updated_at=now() where conversation_id=$1", [value.conversationId, value.revision, memory, memory.memoryFingerprint, memory.decisionFingerprint]); else await client.query("insert into cars_decision_v2_conversations (conversation_id,revision,catalog_release_version,catalog_fingerprint,memory,memory_fingerprint,decision_fingerprint) values ($1,$2,$3,$4,$5,$6,$7)", [value.conversationId, value.revision, memory.catalogAuthority.releaseVersion, memory.catalogAuthority.catalogFingerprint, memory, memory.memoryFingerprint, memory.decisionFingerprint]); }
  private async writeOffer(client: PoolClient, offer: PersistedGovernedOffer) { await client.query("insert into cars_decision_v2_offers (offer_id,conversation_id,lifecycle,mode,candidate_refs,catalog_release_version,catalog_fingerprint,decision_fingerprint,nonce,expires_at,authorization_version,created_at,consented_at,revealed_at) values ($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9,$10,$11,$12,$13,$14)", [offer.offerId, offer.conversationId, offer.lifecycleState, offer.mode, JSON.stringify(offer.candidateRefs), offer.catalogReleaseVersion, offer.catalogFingerprint, offer.decisionFingerprint, offer.nonce, offer.expiresAt, offer.authorizationVersion, offer.createdAt, offer.consentedAt, offer.revealedAt]); }
  private offerFromRow(row: Record<string, unknown>): PersistedGovernedOffer { return { offerId: String(row.offer_id), conversationId: String(row.conversation_id), candidateRefs: row.candidate_refs as PersistedGovernedOffer["candidateRefs"], mode: row.mode as PersistedGovernedOffer["mode"], catalogReleaseVersion: String(row.catalog_release_version), catalogFingerprint: String(row.catalog_fingerprint), decisionFingerprint: String(row.decision_fingerprint), lifecycleState: row.lifecycle as PersistedOfferState, createdAt: new Date(String(row.created_at)).toISOString(), expiresAt: new Date(String(row.expires_at)).toISOString(), ...(row.consented_at ? { consentedAt: new Date(String(row.consented_at)).toISOString() } : {}), ...(row.revealed_at ? { revealedAt: new Date(String(row.revealed_at)).toISOString() } : {}), authorizationVersion: row.authorization_version as "1.0.0", nonce: String(row.nonce) }; }
}

function safePersistenceErrorCode(error: unknown): string {
  if (!(error instanceof Error)) return "UNKNOWN";
  const normalized = error.message.toUpperCase().replace(/[^A-Z0-9]+/gu, "_").replace(/^_+|_+$/gu, "").slice(0, 120);
  return normalized || "ERROR";
}
