import type { AppliancesBudgetDecisionMode, AppliancesConversationState } from "./contracts";
export type AppliancesBudgetCoverage = "NOT_APPLIED" | "EXACT_PRICE_COVERAGE_AVAILABLE" | "EXACT_PRICE_COVERAGE_LIMITED" | "EXACT_PRICE_COVERAGE_UNAVAILABLE";
export interface AppliancesPublicBudgetStatus { readonly mode: AppliancesBudgetDecisionMode; readonly hardMaximumTry?: number; readonly currency: "TRY"; readonly includedInDecision: boolean; readonly coverage: AppliancesBudgetCoverage; readonly compatibleCandidateCount: number; readonly incompatibleCandidateCount: number; readonly eligibilityUnknownCandidateCount: number; readonly disclosure: string }
export function projectAppliancesBudgetStatus(state: AppliancesConversationState, counts?: { readonly compatible: number; readonly incompatible: number; readonly unknown: number; readonly hasUsableCoverage: boolean }): AppliancesPublicBudgetStatus {
  const mode=state.budgetMode??"NEEDS_ONLY",included=mode==="BUDGET_AS_DECISION_FILTER"&&Boolean(state.budgetMetadata);
  if(!included)return{mode,...(state.budgetMetadata?{hardMaximumTry:state.budgetMetadata.amountTry}:{}),currency:"TRY",includedInDecision:false,coverage:"NOT_APPLIED",compatibleCandidateCount:0,incompatibleCandidateCount:0,eligibilityUnknownCandidateCount:0,disclosure:state.budgetMetadata?"Kayıtlı bütçe karar filtresine dahil edilmedi.":"Bütçe karar filtresine dahil değil."};
  const c=counts??{compatible:0,incompatible:0,unknown:0,hasUsableCoverage:false};const coverage:AppliancesBudgetCoverage=!c.hasUsableCoverage?"EXACT_PRICE_COVERAGE_UNAVAILABLE":c.unknown?"EXACT_PRICE_COVERAGE_LIMITED":"EXACT_PRICE_COVERAGE_AVAILABLE";
  const disclosure=coverage==="EXACT_PRICE_COVERAGE_UNAVAILABLE"?"Güncel ve doğrulanmış ürün fiyatı yok; teknik olarak geçerli adaylar bütçe nedeniyle elenmedi ve bütçe uygunlukları bilinmiyor.":coverage==="EXACT_PRICE_COVERAGE_LIMITED"?"Bütçe yalnız güncel ve doğrulanmış fiyatı bulunan ürünlere uygulandı; fiyatı bilinmeyen adaylar korunmuştur.":"Bütçe güncel ve doğrulanmış fiyatı bulunan ürünlere uygulandı."; 
  return{mode,hardMaximumTry:state.budgetMetadata!.amountTry,currency:"TRY",includedInDecision:true,coverage,compatibleCandidateCount:c.compatible,incompatibleCandidateCount:c.incompatible,eligibilityUnknownCandidateCount:c.unknown,disclosure};
}
