export const APPLIANCES_DEPARTMENT_ID = "APPLIANCES" as const;
export const APPLIANCES_PRODUCT_TYPES = ["WASHING_MACHINE", "REFRIGERATOR", "DISHWASHER", "DRYER", "VACUUM", "ROBOT_VACUUM", "FREEZER", "BUILT_IN_OVEN", "FREESTANDING_COOKER", "HOB", "RANGE_HOOD", "COUNTERTOP_MICROWAVE_OVEN", "BUILT_IN_MICROWAVE_OVEN", "AIR_PURIFIER", "FULLY_AUTOMATIC_ESPRESSO_MACHINE", "MANUAL_ESPRESSO_MACHINE", "FILTER_COFFEE_MACHINE", "TURKISH_COFFEE_MACHINE", "AIR_FRYER", "BLENDER", "FOOD_PROCESSOR", "ELECTRIC_STORAGE_WATER_HEATER", "INSTANTANEOUS_ELECTRIC_WATER_HEATER", "SPLIT_AIR_CONDITIONER"] as const;
export type AppliancesProductType = typeof APPLIANCES_PRODUCT_TYPES[number];
export type { AppliancesCategoryId } from "./categoryRegistry";
export type AppliancesRuntimeOutcomeKind = "ASK" | "CLARIFY" | "RESPOND" | "DECISION_READY" | "UNSUPPORTED" | "FAILED_CLOSED";
export type AppliancesRespondKind = "DOMAIN_INFORMATION" | "SOCIAL_ACKNOWLEDGEMENT" | "OFF_TOPIC_REDIRECT" | "SAFETY_BOUNDARY" | "USER_CLOSING";
export type AppliancesRuntimeOutcome =
  | { readonly kind: "ASK" | "CLARIFY"; readonly message: string; readonly questionKey: string; readonly advisory?: import("@/features/xpy/contracts").XpyAdvisoryPresentation; readonly choices?: import("@/features/xpy/contracts").XpyChoiceSet; readonly budget?: import("./budgetPublic").AppliancesPublicBudgetStatus; readonly selectionState?: { readonly kind: "TIED_SET_EXPLANATION" | "TRADE_OFF_SET_EXPLANATION" | "NO_RECOMMENDATION_CONSTRUCTIBLE"; readonly identities: readonly import("./recommendation/construct").ProductIdentity[]; readonly disclosures: readonly import("./recommendation/construct").Disclosure[]; readonly comparisons: readonly import("./selection/types").PairwiseComparisonRecord[] } }
  | { readonly kind: "RESPOND"; readonly responseKind: AppliancesRespondKind; readonly message: string; readonly conversationDisposition: "CONTINUE" | "END"; readonly contextMutation: "NONE" | "VALIDATED"; readonly contextRevision: number; readonly resumeQuestionKey?: string; readonly budget?: import("./budgetPublic").AppliancesPublicBudgetStatus }
  | { readonly kind: "DECISION_READY"; readonly message: string; readonly decisionFingerprint: string; readonly card: import("./recommendation/publicCard").AppliancesDecisionCard; readonly budget?: import("./budgetPublic").AppliancesPublicBudgetStatus }
  | { readonly kind: "UNSUPPORTED"; readonly departmentId: typeof APPLIANCES_DEPARTMENT_ID; readonly productType: Exclude<AppliancesProductType, "WASHING_MACHINE" | "DRYER" | "REFRIGERATOR">; readonly budget?: import("./budgetPublic").AppliancesPublicBudgetStatus }
  | { readonly kind: "FAILED_CLOSED"; readonly message: string; readonly budget?: import("./budgetPublic").AppliancesPublicBudgetStatus };

export type AppliancesIntentState = "OPEN" | "PRODUCT_TYPE_RESOLVED" | "ENDED_WITHOUT_DECISION";
export type AppliancesBudgetDecisionMode = "NEEDS_ONLY" | "BUDGET_AS_DECISION_FILTER";
export interface AppliancesBudgetMetadata { readonly amountTry: number; readonly currency: "TRY"; readonly provenance: { readonly sourceMessageId: string; readonly sourceSpan?: { readonly start: number; readonly end: number; readonly text: string }; readonly authority: "USER_EXPLICIT" }; readonly includedInDecision: boolean; readonly priceSemantics: "FRESH_EXACT_PRICE_ONLY" }
export interface AppliancesBudgetModeEvent { readonly revision: number; readonly from: AppliancesBudgetDecisionMode; readonly to: AppliancesBudgetDecisionMode; readonly authority: "USER_EXPLICIT"; readonly sourceMessageId: string; readonly createdAt: string }
export type LedgerEventStatus = "PROPOSED" | "ACCEPTED_EXPLICIT" | "ACCEPTED_CONFIRMED" | "ACCEPTED_INTERPRETED" | "REJECTED" | "SUPERSEDED" | "CLEARED";
export type LedgerAuthority = "USER_EXPLICIT" | "USER_CONFIRMED" | "DOMAIN_INTERPRETATION" | "PRODUCT_POLICY" | "DERIVED_PLANNING";
export type LedgerStrength = "HARD" | "STRONG" | "SOFT" | "HYPOTHESIS";
export type LedgerDecisionUse = "HARD_FILTER" | "SOFT_RANK" | "QUESTION_INPUT" | "NONE";
export interface AppliancesLedgerEvent { readonly eventId: string; readonly conceptId: string; readonly normalizedValue: unknown; readonly sourceMessageId: string; readonly sourceSpan?: { readonly start: number; readonly end: number; readonly text: string }; readonly authority: LedgerAuthority; readonly strength: LedgerStrength; readonly status: LedgerEventStatus; readonly decisionUse: LedgerDecisionUse; readonly supersedesEventId?: string; readonly confirmationRequired: boolean; readonly createdRevision: number; readonly createdAt: string }
export interface AppliancesConversationState { readonly conversationId: string; readonly schemaVersion: "appliances-conversation/v1"; readonly revision: number; readonly departmentId: typeof APPLIANCES_DEPARTMENT_ID; readonly productType: AppliancesProductType; readonly pinnedCatalogRelease: string; readonly pinnedCatalogDigest: string; readonly pinnedSemanticVersion: string; readonly pinnedSemanticDigest: string; readonly intentState: AppliancesIntentState; readonly ledger: readonly AppliancesLedgerEvent[]; readonly pendingConfirmation?: { readonly eventId: string; readonly conceptId: string; readonly normalizedValue: unknown; readonly sourceMessageId: string; readonly createdRevision: number; readonly expiresAfterRevision: number; readonly question: string }; readonly askedQuestionKeys: readonly string[]; readonly lastQuestionKey?: string; readonly personaSignals: readonly { readonly signalId: string; readonly sourceEventIds: readonly string[]; readonly authority: "DERIVED_PLANNING"; readonly directCandidateEffect: "NONE"; readonly decisionUse: "NONE" }[]; readonly candidateSnapshotRef?: string; readonly currentDecisionFingerprint?: string; readonly ended: boolean; readonly createdAt: string; readonly updatedAt: string }
export interface AppliancesStoredOutcome { readonly kind: "CONVERSATION_BOOTSTRAPPED" | "CONTEXT_MUTATED"; readonly conversationId: string; readonly revision: number; readonly state: AppliancesConversationState; readonly publicOutcome?: AppliancesRuntimeOutcome }
export interface AppliancesStoredMessage { readonly messageId: string; readonly payloadHash: string; readonly committedRevision: number; readonly outcome: AppliancesStoredOutcome }
export interface AppliancesConversationState {
  readonly planningSignals?: readonly { readonly kind: "SOFT_AFFORDABILITY"; readonly sourceMessageId: string; readonly sourceText: string; readonly decisionUse: "NONE" }[];
  readonly brandConstraintEvents?: readonly { readonly eventId: string; readonly brandId: string; readonly brandLabel: string; readonly sourceMessageId: string; readonly sourceText: string; readonly createdRevision: number; readonly createdAt: string; readonly status: "ACTIVE" | "SUPERSEDED" | "CLEARED" | "RELAXED"; readonly supersedesEventId?: string; readonly authority: "USER_EXPLICIT"; readonly decisionUse: "HARD_FILTER" | "NONE"; readonly policyId: string; readonly policyDigest: string }[];
  readonly pendingBrandRelaxation?: { readonly brandEventId: string; readonly brandId: string; readonly questionKey: "appliances.brand.relaxation" };
  readonly pinnedBrandPolicyId?: string;
  readonly pinnedBrandPolicyDigest?: string;
  readonly questionDeferrals?: readonly { readonly questionKey: string; readonly sourceMessageId: string; readonly sourceText: string; readonly createdRevision: number; readonly status: "ACTIVE" | "REOPENED" }[];
  readonly budgetMode?: AppliancesBudgetDecisionMode;
  readonly budgetModeEvents?: readonly AppliancesBudgetModeEvent[];
  readonly budgetMetadata?: AppliancesBudgetMetadata;
  readonly decisionRecord?: { readonly artifact: import("./recommendation/construct").RecommendationArtifact; readonly authorization: import("./recommendation/authorize").AppliancesDecisionAuthorization };
}
