import { z } from "zod";
import { ELECTRONICS_CATEGORY_IDS } from "@/features/electronics/architectureBaseline";
import { loadActiveElectronicsRuntimeAuthority } from "@/features/electronics/runtimeAuthority.server";
import { bootstrapElectronicsConversation, recoverElectronicsConversation, runElectronicsTurn } from "@/features/electronics/conversation.server";
import { initializeElectronicsStore } from "@/features/electronics/initializeStore.server";
import { PostgresElectronicsConversationStore } from "@/features/electronics/persistence";
import { projectElectronicsPublicOutcome } from "@/features/electronics/publicLanguage";
import { enforceRateLimit, readJsonWithLimit, verifySameOrigin } from "@/lib/security/requestSecurity";
export const runtime = "nodejs";
const schema = z.discriminatedUnion("action", [z.strictObject({ action: z.literal("CREATE"), conversationId: z.string().uuid(), messageId: z.string().min(1).max(200), categoryId: z.enum(ELECTRONICS_CATEGORY_IDS) }), z.strictObject({ action: z.literal("READ"), conversationId: z.string().uuid() }), z.strictObject({ action: z.literal("TURN"), conversationId: z.string().uuid(), messageId: z.string().min(1).max(200), expectedRevision: z.number().int().nonnegative(), message: z.string().trim().min(1).max(4000), choice: z.strictObject({ questionKey: z.string().min(1).max(200), values: z.array(z.enum(["IMPORTANT", "NOT_IMPORTANT", "UNKNOWN"])).length(1) }).optional() })]);
const json = (body: unknown, status = 200) => Response.json(body, { status, headers: { "Cache-Control": "no-store" } }); const closed = (message: string, status = 409) => json({ kind: "FAILED_CLOSED", message }, status); const choiceText = (value: string) => value === "IMPORTANT" ? "Önemli" : value === "NOT_IMPORTANT" ? "Önemli değil" : "Henüz bilmiyorum";
export async function POST(request: Request) { const origin = verifySameOrigin(request); if (origin) return origin; const limited = await enforceRateLimit(request, { scope: "electronics-conversation", limit: 30, windowMs: 60_000 }); if (limited) return limited; let raw: unknown; try { raw = await readJsonWithLimit(request, 16_384); } catch { return closed("Geçersiz istek.", 400); } const parsed = schema.safeParse(raw); if (!parsed.success) return closed("Geçersiz istek.", 400); try { const authority = loadActiveElectronicsRuntimeAuthority(); const database = await initializeElectronicsStore({ DATABASE_URL: process.env.DATABASE_URL, DATABASE_POOL_MAX: process.env.DATABASE_POOL_MAX }); if (database.status !== "READY") { console.error("electronics_store_unavailable", { reason: database.reason }); return closed("Elektronik konuşması şu anda kullanılamıyor.", 503); } const store = new PostgresElectronicsConversationStore(database.pool), data = parsed.data; if (data.action === "READ") { const recovered = recoverElectronicsConversation(authority, await store.load(data.conversationId)); return recovered ? json(recovered.kind === "CONVERSATION" && recovered.outcome ? { ...recovered, outcome: projectElectronicsPublicOutcome(recovered.outcome) } : recovered) : json({ kind: "NOT_FOUND" }, 404); } const result = data.action === "CREATE" ? await bootstrapElectronicsConversation({ store, authority, conversationId: data.conversationId, categoryId: data.categoryId, messageId: data.messageId }) : await runElectronicsTurn({ store, authority, conversationId: data.conversationId, messageId: data.messageId, expectedRevision: data.expectedRevision, message: data.choice ? choiceText(data.choice.values[0]!) : data.message }); if (result.status !== "OK") return closed(result.status === "STATE_UNAVAILABLE" ? "Konuşma bulunamadı." : result.status === "REVISION_CONFLICT" ? "Konuşma güncellendi; yeniden okuyun." : result.status === "MESSAGE_PAYLOAD_CONFLICT" ? "Mesaj kimliği uyuşmazlığı." : "Yetki doğrulanamadı.", result.status === "STATE_UNAVAILABLE" ? 404 : 409); return json({ ...projectElectronicsPublicOutcome(result.outcome), conversationId: result.state.conversationId, revision: result.state.revision, categoryId: result.state.categoryId, replayed: result.replayed }); } catch (error) { console.error("electronics_conversation_failed", { code: error instanceof Error ? error.message : "UNKNOWN" }); return closed("Elektronik yetkisi güvenli biçimde yüklenemedi.", 503); } }
