"use client";

import { FormEvent, KeyboardEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import type { AppliancesBudgetMetadata, AppliancesBudgetDecisionMode, AppliancesProductType, AppliancesRuntimeOutcome } from "@/features/appliances/contracts";
import { APPLIANCES_CATEGORY_REGISTRY, type AppliancesCategoryId } from "@/features/appliances/categoryRegistry";
import type { AppliancesDecisionCard } from "@/features/appliances/recommendation/publicCard";
import type { AppliancesPublicBudgetStatus } from "@/features/appliances/budgetPublic";
import { XpyBudgetBand, XpyChoiceGroup, XpyHeader, XpyLoading, XpyStageOneFrame } from "@/components/xpy/XpyPresentation";
import { XpyDecisionCard } from "@/components/xpy/XpyDecisionCard";
import { APPLIANCES_EXPERIENCE } from "@/features/xpy/visualPacks";
import { APPLIANCES_STAGE_ONE_PRESENTATION, projectAppliancesSet } from "@/features/appliances/presentation/stageOneAdapter";
import type { XpyChoiceSubmission } from "@/features/xpy/contracts";
import { appliancesAdvisoryPlan, appliancesOpeningGreeting } from "@/features/appliances/advisory";
import { clearSecretaryPendingMessage, readSecretaryPendingMessage } from "@/features/platform/secretaryClientHandoff";

type Reply = AppliancesRuntimeOutcome & { revision?: number; ended?: boolean; budgetMode?: AppliancesBudgetDecisionMode; budgetMetadata?: AppliancesBudgetMetadata };
type Session = { conversationId: string; revision: number };
type Pending = { action: "TURN"; conversationId: string; messageId: string; expectedRevision: number; message: string; choice?: XpyChoiceSubmission };
const categories = APPLIANCES_CATEGORY_REGISTRY.map(category => ({ value: category.categoryId, label: category.publicLabelTr, short: category.publicLabelTr, status: category.status }));
async function request(body: unknown) { const response = await fetch("/api/appliances/conversation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); return { response, body: await response.json() }; }
const formatBudget = (value: string) => { const digits = value.replace(/[^\d]/gu, "").replace(/^0+(?=\d)/u, ""); return digits ? Number(digits).toLocaleString("tr-TR") : ""; };

function BudgetDisclosure({ budget }: { readonly budget: AppliancesPublicBudgetStatus }) {
  const uncertain = budget.eligibilityUnknownCandidateCount > 0 || budget.coverage === "EXACT_PRICE_COVERAGE_UNAVAILABLE";
  return <aside className={`rounded-xl border p-3 text-sm leading-6 ${uncertain ? "border-amber-300 bg-amber-50 text-amber-950 dark:border-amber-800 dark:bg-amber-950/40 dark:text-amber-100" : "border-emerald-200 bg-emerald-50 text-emerald-950 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-100"}`} aria-label="Bütçe kapsamı">
    <p className="font-semibold">{budget.includedInDecision ? "Bütçe filtresi uygulandı" : "Bütçe karar filtresinde değil"}{budget.hardMaximumTry ? ` · ${budget.hardMaximumTry.toLocaleString("tr-TR")} TL` : ""}</p><p className="mt-1 text-xs leading-5">{budget.disclosure}</p>
    {budget.includedInDecision && <p className="mt-1 text-xs">Uygun: {budget.compatibleCandidateCount} · Uygun değil: {budget.incompatibleCandidateCount} · Fiyatı bilinmeyen: {budget.eligibilityUnknownCandidateCount}</p>}
  </aside>;
}

export function AppliancesCard({ card, budget, conversationId, revision }: { card: AppliancesDecisionCard; budget?: AppliancesPublicBudgetStatus; conversationId?: string; revision?: number }) {
  const persistedConversationId = conversationId ?? /^#conversation=([a-f0-9-]{36})$/iu.exec(typeof window === "undefined" ? "" : window.location.hash)?.[1];
  const expectedRevision = revision ?? card.provenance.contextRevision;
  const [state, setState] = useState<{ href?: string; error?: string }>({});
  useEffect(() => { let cancelled = false; if (!persistedConversationId || !expectedRevision) return; void requestStageTwoHandoff(persistedConversationId, expectedRevision).then(handoff => { if (!cancelled) setState({ href: `/appliances/stage/2?handoff=${encodeURIComponent(handoff)}` }); }).catch(reason => { if (!cancelled) setState({ error: reason instanceof Error ? reason.message : "Güvenli bağlantı oluşturulamadı." }); }); return () => { cancelled = true; }; }, [expectedRevision, persistedConversationId]);
  const action = !persistedConversationId || !expectedRevision ? null : state.error ? <p className="rounded-xl border border-amber-500 px-4 py-3 text-xs text-amber-200">{state.error}</p> : state.href ? <a href={state.href} referrerPolicy="no-referrer" className="flex min-h-12 items-center justify-center rounded-xl border border-emerald-500 px-4 py-3 text-sm font-semibold text-emerald-300">AŞAMA 2 · Ayrıntılı değerlendirmeyi aç</a> : <p className="px-4 py-3 text-xs text-stone-400">Güvenli AŞAMA 2 bağlantısı hazırlanıyor…</p>;
  return <div className="space-y-3">{budget && <BudgetDisclosure budget={budget}/>}<XpyDecisionCard card={APPLIANCES_STAGE_ONE_PRESENTATION.project(card)} onActivate={state.href ? () => window.location.assign(state.href!) : undefined} activationLabel={`${card.identity.brand} ${card.identity.model} için Aşama 2'yi aç`} action={action}/></div>;
}

async function requestStageTwoHandoff(conversationId: string, expectedRevision: number) { const response = await fetch("/api/appliances/stage-two-handoff", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "ISSUE", conversationId, expectedRevision }) }); const body = await response.json() as { kind?: string; handoff?: string; message?: string }; if (!response.ok || body.kind !== "HANDOFF_ISSUED" || !body.handoff) throw new Error(body.message ?? "Güvenli AŞAMA 2 bağlantısı oluşturulamadı."); return body.handoff; }
function SelectionState({ reply }: { readonly reply: Extract<AppliancesRuntimeOutcome, { kind: "ASK" | "CLARIFY" }> }) { return reply.selectionState ? <XpyDecisionCard card={projectAppliancesSet(reply.selectionState)}/> : null; }

export default function AppliancesConversation({ initialCategory, embedded = false, secretaryEntry = false }: { readonly initialCategory?: string; readonly embedded?: boolean; readonly secretaryEntry?: boolean }) {
  const initialProductType = categories.some((item) => item.value === initialCategory) ? initialCategory as AppliancesCategoryId : "WASHING_MACHINE";
  const [productType, setProductType] = useState<AppliancesCategoryId>(initialProductType); const [session, setSession] = useState<Session>(); const [message, setMessage] = useState(""); const [history, setHistory] = useState<{ user: string; reply: Reply }[]>([]);
  const [busy, setBusy] = useState(true); const [error, setError] = useState(""); const [ended, setEnded] = useState(false); const [retry, setRetry] = useState(false); const [budgetMode, setBudgetMode] = useState<AppliancesBudgetDecisionMode>("NEEDS_ONLY"); const [budgetMetadata, setBudgetMetadata] = useState<AppliancesBudgetMetadata>(); const [budgetDraft, setBudgetDraft] = useState(""); const [budgetEditorOpen, setBudgetEditorOpen] = useState(false); const [selectedChoices, setSelectedChoices] = useState<Readonly<Record<string, string>>>({}); const [arrivedFromSecretary, setArrivedFromSecretary] = useState(secretaryEntry);
  const pending = useRef<Pending | undefined>(undefined); const creation = useRef({ conversationId: "", messageId: "" }); const lock = useRef(false); const logRef = useRef<HTMLDivElement>(null);
  useEffect(() => { let cancelled = false; lock.current = true; if (secretaryEntry) { readSecretaryPendingMessage(sessionStorage); clearSecretaryPendingMessage(sessionStorage); } const id = /^#conversation=([a-f0-9-]{36})$/iu.exec(window.location.hash)?.[1]; Promise.resolve().then(async () => { if (!id) return; const recovered = await request({ action: "READ", conversationId: id }); if (cancelled) return; if (!recovered.response.ok || recovered.body.kind !== "CONVERSATION" || typeof recovered.body.revision !== "number") throw new Error("Konuşma geri yüklenemedi. Sayfayı yeniden yükleyebilir veya yeni konuşma başlatabilirsin."); if (categories.some((item) => item.value === recovered.body.productType)) setProductType(recovered.body.productType as AppliancesCategoryId); setSession({ conversationId: id, revision: recovered.body.revision }); setEnded(Boolean(recovered.body.ended)); setBudgetMode(recovered.body.budgetMode ?? "NEEDS_ONLY"); setBudgetMetadata(recovered.body.budgetMetadata); if (recovered.body.outcome) setHistory([{ user: "", reply: recovered.body.outcome }]); }).catch((cause) => { if (!cancelled) setError(cause instanceof Error ? cause.message : "Konuşma geri yüklenemedi."); }).finally(() => { if (!cancelled) { setBusy(false); lock.current = false; } }); return () => { cancelled = true; }; }, [secretaryEntry]);
  useEffect(() => { const log = logRef.current; if (log) log.scrollTop = log.scrollHeight; }, [busy, history]);
  async function send(content?: string, choice?: XpyChoiceSubmission) { const outgoing = content?.trim() ?? message.trim(); if (lock.current || (!outgoing && !pending.current) || ended) return; const typedMessage = content === undefined ? message : ""; lock.current = true; if (typedMessage) setMessage(""); setBusy(true); setError(""); try { let current = session; if (!current) { if (!creation.current.conversationId) creation.current = { conversationId: crypto.randomUUID(), messageId: crypto.randomUUID() }; const created = await request({ action: "CREATE", ...creation.current, productType }); if (!created.response.ok) throw new Error(created.body.message ?? "Konuşma başlatılamadı."); current = { conversationId: created.body.conversationId, revision: created.body.revision }; setSession(current); window.history.replaceState(null, "", `#conversation=${current.conversationId}`); } pending.current ??= { action: "TURN", conversationId: current.conversationId, messageId: crypto.randomUUID(), expectedRevision: current.revision, message: outgoing, ...(choice ? { choice } : {}) }; const sent = pending.current; const result = await request(sent); if (!result.response.ok) { if (result.response.status === 409) { const read = await request({ action: "READ", conversationId: current.conversationId }); if (read.response.ok) { setSession({ ...current, revision: read.body.revision }); setEnded(Boolean(read.body.ended)); pending.current = undefined; } } throw new Error(result.body.message ?? "İstek tamamlanamadı. Yeniden deneyin."); } const reply = result.body as Reply; if (typeof reply.revision !== "number") throw new Error("Görüşmenin güncel durumu doğrulanamadı."); setSession({ ...current, revision: reply.revision }); setEnded(Boolean(reply.ended)); if (reply.budgetMode) setBudgetMode(reply.budgetMode); if ("budgetMetadata" in reply) setBudgetMetadata(reply.budgetMetadata); setHistory((items) => [...items, { user: sent.message, reply }]); setMessage(""); pending.current = undefined; } catch (cause) { if (typedMessage) setMessage(typedMessage); setError(cause instanceof Error ? cause.message : "Bağlantı kesildi. Aynı mesajı yeniden deneyin."); } finally { setBusy(false); setRetry(Boolean(pending.current)); lock.current = false; } }
  const selected = categories.find((item) => item.value === productType)!; const categoryReady = selected.status === "ACTIVE"; const openingPlan = categoryReady ? appliancesAdvisoryPlan(productType as AppliancesProductType) : undefined; const budgetEnabled = budgetMode === "BUDGET_AS_DECISION_FILTER" || budgetEditorOpen; const latestReply = history.at(-1)?.reply;
  function toggleBudget() { if (busy || ended) return; if (budgetEnabled) { setBudgetEditorOpen(false); setBudgetDraft(""); if (budgetMode === "BUDGET_AS_DECISION_FILTER") void send("Bütçeyi karardan çıkar, ihtiyaç odaklı devam."); } else setBudgetEditorOpen(true); }
  function submitBudget(event: FormEvent) { event.preventDefault(); const amount = Number(budgetDraft.replace(/[^\d]/gu, "")); if (amount <= 0 || busy) return; setBudgetDraft(""); setBudgetEditorOpen(false); void send(`Bütçemi karar filtresi olarak kullan. Kesin bütçe üst sınırım ${amount.toLocaleString("tr-TR")} TL.`); }
  function submitOnEnter(event: KeyboardEvent<HTMLTextAreaElement>) { if ((event.key === "Enter" || event.key === "NumpadEnter") && !event.shiftKey && !event.nativeEvent.isComposing) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }
  function reset() { window.history.replaceState(null, "", `/appliances?category=${encodeURIComponent(productType)}#asama-1`); setSession(undefined); setHistory([]); setMessage(""); setError(""); setEnded(false); setRetry(false); setBudgetMode("NEEDS_ONLY"); setBudgetMetadata(undefined); setBudgetDraft(""); setBudgetEditorOpen(false); setSelectedChoices({}); setArrivedFromSecretary(false); pending.current = undefined; creation.current = { conversationId: "", messageId: "" }; }
  const labels: Record<Reply["kind"], string> = { ASK: "Bir bilgi gerekli", CLARIFY: "Netleştirelim", RESPOND: "Bilgi", DECISION_READY: "Karar hazır", UNSUPPORTED: "Kapsam dışında", FAILED_CLOSED: "Güvenli duruş" };
  return <XpyStageOneFrame adapter={APPLIANCES_EXPERIENCE} embedded={embedded}>
    <XpyHeader title="Ev ürünleri danışmanın" description="İhtiyacını konuşalım; doğrulanmış seçenekleri birlikte sadeleştirip doğru ürüne ilerleyelim." status={<p className="mt-2 inline-flex rounded-full bg-emerald-50 px-2.5 py-1 text-xs text-emerald-800 ring-1 ring-emerald-200 dark:bg-emerald-950 dark:text-emerald-200 dark:ring-emerald-800">{selected.label} görüşmesi</p>} action={<div className="flex flex-wrap items-center justify-end gap-2"><Link href="/appliances#asama-1" className="inline-flex min-h-11 items-center rounded-full border border-stone-300 px-3 text-xs font-semibold text-stone-600 focus-visible:outline-2 focus-visible:outline-emerald-600 dark:border-stone-700 dark:text-stone-300">Kategoriler</Link><button type="button" onClick={reset} disabled={busy || (!session && history.length === 0)} className="min-h-11 shrink-0 rounded-full border border-stone-300 px-3 text-xs font-semibold text-stone-600 focus-visible:outline-2 focus-visible:outline-emerald-600 disabled:opacity-40 dark:border-stone-700 dark:text-stone-300">Yeni görüşme</button></div>}/>
    {!session && <fieldset className="border-b border-stone-200 bg-white/60 px-4 py-4 dark:border-stone-800 dark:bg-stone-950/35 sm:px-6"><legend className="text-sm font-semibold">Hangi ürünü birlikte seçelim?</legend><details open={!initialCategory} className="mt-3 group"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between rounded-xl border border-stone-300 bg-white px-3 py-2 text-sm font-semibold focus-visible:outline-2 focus-visible:outline-emerald-600 dark:border-stone-700 dark:bg-stone-900"><span>{selected.label}</span><span className="text-xs text-emerald-700 group-open:hidden dark:text-emerald-300">Değiştir</span><span className="hidden text-xs text-stone-500 group-open:inline">Listeyi kapat</span></summary><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3">{categories.map((item) => <button key={item.value} type="button" aria-pressed={productType === item.value} onClick={() => { setProductType(item.value); setSelectedChoices({}); setArrivedFromSecretary(false); window.history.replaceState(null, "", `/appliances?category=${encodeURIComponent(item.value)}#asama-1`); }} className={`min-h-11 rounded-xl border px-3 py-2 text-left text-sm font-semibold transition focus-visible:outline-2 focus-visible:outline-emerald-600 ${productType === item.value ? "border-emerald-600 bg-emerald-50 text-emerald-950 ring-1 ring-emerald-500 dark:bg-emerald-950 dark:text-emerald-100" : "border-stone-200 bg-white text-stone-700 dark:border-stone-700 dark:bg-stone-900 dark:text-stone-200"}`}><span>{item.label}</span>{item.status === "NOT_READY" && <span className="mt-1 block text-xs font-normal opacity-70">Yakında</span>}</button>)}</div></details></fieldset>}
    {!categoryReady && <section className="border-b border-amber-200 bg-amber-50 px-4 py-4 text-amber-950 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-100 sm:px-6" aria-live="polite"><h2 className="font-semibold">{selected.label} henüz hazır değil</h2><p className="mt-1 text-sm leading-6">Bu kategori için doğrulanmış ürün bilgileri tamamlanmadığı için görüşme, ürün kartları, danışman ve karşılaştırma özellikleri henüz kullanılamıyor.</p></section>}
    {categoryReady && <XpyBudgetBand id="appliances-budget-title" description="İstersen kesin üst sınır belirle; kapalıyken bütçe hiçbir ürünü elemez." enabled={budgetEnabled} disabled={busy || ended} onToggle={toggleBudget} status={<p role="status" className={`mt-2 text-xs ${budgetMode === "BUDGET_AS_DECISION_FILTER" && budgetMetadata ? "text-emerald-700 dark:text-emerald-300" : budgetEnabled ? "text-amber-800 dark:text-amber-300" : "text-stone-500 dark:text-stone-400"}`}>{budgetMetadata ? `${budgetMetadata.amountTry.toLocaleString("tr-TR")} TL bütçe ${budgetMetadata.includedInDecision ? "karar filtresine dahil" : "kaydedildi; karar filtresine dahil edilmedi"}.` : budgetEnabled ? "Kesin üst sınır bekleniyor; tutarı girdiğinde değerlendirmeye dahil edilir." : "Bütçe karar filtresine dahil değil."}</p>}>
      {budgetEnabled && <form onSubmit={submitBudget} className="mt-3"><div className="flex flex-wrap items-end gap-2"><label className="min-w-56 flex-1"><span className="mb-1 block text-xs font-semibold text-stone-700 dark:text-stone-300">Kesin bütçe üst sınırı</span><div className="flex items-center rounded-xl border border-stone-300 bg-white px-3 focus-within:border-emerald-600 focus-within:ring-2 focus-within:ring-emerald-100 dark:border-stone-700 dark:bg-stone-900"><input inputMode="numeric" autoComplete="off" value={budgetDraft} disabled={busy || ended} onChange={(event) => setBudgetDraft(formatBudget(event.target.value))} placeholder={budgetMetadata?.amountTry.toLocaleString("tr-TR") ?? "Örn. 5.000"} aria-describedby="appliances-budget-help" className="min-w-0 flex-1 bg-transparent py-2.5 outline-none"/><span className="text-sm text-stone-500">TL</span></div></label><button disabled={busy || ended || Number(budgetDraft.replace(/[^\d]/gu, "")) <= 0} className="min-h-11 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Üst sınırı uygula</button></div><p id="appliances-budget-help" className="mt-1.5 text-xs text-stone-500 dark:text-stone-400">Pozitif herhangi bir tutar girebilir ve etkin sınırı buradan değiştirebilirsin.</p></form>}
    </XpyBudgetBand>}
    {error && <div role="alert" className="border-b border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800 dark:border-rose-900 dark:bg-rose-950/40 dark:text-rose-300 sm:px-6"><p className="font-semibold">Görüşme şu anda ilerleyemedi</p><p className="mt-1">{error}</p>{retry && <p className="mt-1 text-xs">Mesajın korundu; yeniden deneyebilirsin.</p>}</div>}
    <div ref={logRef} className="min-h-0 flex-1 space-y-3 overflow-y-auto bg-[radial-gradient(circle_at_top,#f5f1e8_0,transparent_42%)] px-3 py-4 dark:bg-[radial-gradient(circle_at_top,#292524_0,transparent_45%)] sm:px-6" role="log" aria-live="polite" aria-relevant="additions text">{categoryReady && history.length === 0 && !busy && openingPlan && <div className="max-w-[92%] rounded-2xl rounded-bl-md bg-white px-3.5 py-2.5 text-[15px] leading-6 text-stone-700 shadow-sm ring-1 ring-stone-200 dark:bg-stone-800 dark:text-stone-200 dark:ring-stone-700 sm:max-w-[82%]"><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700 dark:text-emerald-300">X · Kategori danışmanı</p><p className="mt-1">{appliancesOpeningGreeting(productType as AppliancesProductType, arrivedFromSecretary)}</p></div>}
      {history.map((item, index) => { const choiceKey = String(item.reply.revision ?? index); const choices = item.reply.kind === "ASK" || item.reply.kind === "CLARIFY" ? item.reply.choices : undefined; const activeChoices = index === history.length - 1 && !busy ? choices : undefined; const choice = selectedChoices[choiceKey]; return <div className="space-y-2" key={`${index}:${item.reply.kind}`}>{item.user ? <div className="ml-auto max-w-[88%] rounded-2xl rounded-br-md bg-emerald-100 px-3.5 py-2.5 text-[15px] text-emerald-950 shadow-sm ring-1 ring-emerald-200 dark:bg-emerald-800 dark:text-white dark:ring-emerald-700 sm:max-w-[78%]"><p className="whitespace-pre-wrap leading-6">{item.user}</p></div> : <p className="max-w-[92%] rounded-xl border border-sky-200 bg-sky-50 p-3 text-xs text-sky-900 dark:border-sky-900 dark:bg-sky-950/40 dark:text-sky-200">Görüşme geri yüklendi; son yanıtın ve onayladığın ihtiyaçlarla devam edebilirsin.</p>}<div className="max-w-[92%] space-y-2 sm:max-w-[82%]">{(item.reply.kind === "ASK" || item.reply.kind === "CLARIFY") && item.reply.advisory && <div className="rounded-2xl rounded-bl-md border border-emerald-200 bg-emerald-50 px-3.5 py-3 text-[15px] text-emerald-950 shadow-sm dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-100"><p className="whitespace-pre-wrap leading-6">{item.reply.advisory.message}</p></div>}<div className="rounded-2xl rounded-bl-md bg-white px-3.5 py-2.5 text-[15px] text-stone-800 shadow-sm ring-1 ring-stone-200 dark:bg-stone-800 dark:text-stone-100 dark:ring-stone-700"><span className="sr-only">{labels[item.reply.kind]}: </span><p className="whitespace-pre-wrap leading-6">{"message" in item.reply ? item.reply.message : "Bu ürün türü henüz desteklenmiyor."}</p></div>{activeChoices && <XpyChoiceGroup options={activeChoices.options} selected={choice ? [choice] : []} multiple={activeChoices.selectionMode === "MULTIPLE"} disabled={busy} onToggle={(option) => setSelectedChoices((current) => ({ ...current, [choiceKey]: option.value }))} onSubmit={() => choice && void send(choice, { questionKey: activeChoices.questionKey, values: [choice] })}/>} {item.reply.kind === "CLARIFY" && <SelectionState reply={item.reply}/>} {item.reply.kind === "DECISION_READY" && <AppliancesCard card={item.reply.card} budget={item.reply.budget} conversationId={session?.conversationId} revision={item.reply.revision}/>}</div></div>; })}
      {latestReply?.budget && latestReply.kind !== "DECISION_READY" && latestReply.budget.includedInDecision && latestReply.budget.coverage !== "EXACT_PRICE_COVERAGE_AVAILABLE" && <BudgetDisclosure budget={latestReply.budget}/>} 
      {busy && <XpyLoading/>}{ended && <p className="mx-auto max-w-md rounded-full border border-stone-300 bg-white/80 px-4 py-2 text-center text-xs text-stone-600 dark:border-stone-700 dark:bg-stone-900 dark:text-stone-300">Bu görüşme senin isteğinle kapandı. Yeni bir görüşme başlatabilirsin.</p>}</div>
    {categoryReady && <form onSubmit={(event) => { event.preventDefault(); void send(); }} className="border-t border-stone-200 bg-white/95 p-3 backdrop-blur dark:border-stone-800 dark:bg-stone-950/90 sm:p-4"><label htmlFor="appliances-message" className="sr-only">Mesajın</label><div className="flex items-end gap-2"><textarea id="appliances-message" rows={1} className="max-h-32 min-h-12 flex-1 resize-none rounded-2xl border border-stone-300 bg-stone-50 px-4 py-3 text-[15px] outline-none transition focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100 disabled:opacity-50 dark:border-stone-700 dark:bg-stone-900" value={message} maxLength={4000} disabled={busy || ended || retry} onChange={(event) => setMessage(event.target.value)} onKeyDown={submitOnEnter} placeholder="İhtiyacını anlat…"/><button aria-label={retry ? "Aynı mesajı yeniden dene" : "Mesajı gönder"} className="flex min-h-12 items-center rounded-full bg-emerald-600 px-5 text-sm font-semibold text-white shadow-sm focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600 disabled:opacity-40" disabled={busy || ended || (!message.trim() && !retry)}>{retry ? "Yeniden dene" : "Gönder"}<span className="ml-2" aria-hidden="true">↑</span></button></div><p className="mt-2 px-1 text-xs text-stone-500 dark:text-stone-400">Enter ile gönder · Yeni satır için Shift + Enter</p></form>}
  </XpyStageOneFrame>;
}
