import { loadActiveVehiclePersonaSafeTraits, } from "@/features/vehicle-data/vehiclePersonaSafeTraits.server";
import { createHash } from "node:crypto";
import { selectOwnerApprovedSafePersonaSignals } from "@/features/vehicle-data/vehiclePersonaSafeTraits";
import { decideConversationAction } from "../action/decide";
import { ACTION_POLICY_V1 } from "../action/policy";
import { generateMaterialQuestionCandidates } from "../action/questionGeneration";
import { createConversationLocalSemanticRecoveryQuestion } from "../action/semanticRecovery";
import { assessRecommendationReadiness } from "../action/readiness";
import { evaluateAffordabilityCandidatePool } from "../affordability/evaluate";
import { AFFORDABILITY_POLICY_V1, PRICE_AUTHORITY_POLICY_V1 } from "../affordability/policy";
import { projectRelativePriceSegmentsCached } from "../affordability/priceSegmentation";
import { createProductionCatalogReleaseRepository } from "../catalog/fileSystemRepository.server";
import { loadActiveCatalogSnapshot, loadPinnedCatalogSnapshot } from "../catalog/snapshot";
import { classifyCandidateDecisionAvailability } from "../conflict/availability";
import type { DirectAnswerObligation } from "../domain/decisionTurnResult";
import { projectActiveConstraints } from "../filter/constraintProjection";
import { evaluateTechnicalCandidatePool } from "../filter/pipeline";
import { projectActiveRejections } from "../filter/rejectionProjection";
import { V2_DECISION_FIELD_REGISTRY_V1 } from "../filter/registry";
import { CARS_MEMORY_FINGERPRINT_POLICY_V1 } from "../fingerprint/policy";
import { interpretUserMessage } from "../interpretation/service";
import type { NaturalRealizationModel } from "../realization/types";
import type { StructuredInterpretationModel } from "../interpretation/types";
import { createDailyLifeLayerSnapshot, createPersonaLayerSnapshot } from "../layers/adapter";
import { loadProductionDecisionLayers } from "../layers/productionAdapter.server";
import { reduceConversationMemoryV2, replayConversationMemoryV2 } from "../memory/reducer";
import { authorizePersistedCards, createPersistedGovernedOffer } from "../offer/authorize";
import { offerIdentityFingerprint } from "../offer/recOfferAuditFoundation.server";
import type { GovernedOfferStore, OfferSigner } from "../offer/types";
import type { PersistedOfferTransitionIntent } from "../orchestrator/types";
import { rankSelectableCandidates } from "../ranking/evaluate";
import { createExplicitFunctionalPreferenceSignals } from "../ranking/constraintSignals";
import { selectRankedCandidateShortlist } from "../ranking/shortlist";
import { realizeDecisionResponse } from "../realization/service";
import { REALIZATION_SAFETY_POLICY_V1, TURKISH_TONE_POLICY } from "../realization/policy";
import { USAGE_CARGO_POLICIES_V1 } from "../usage/policy";
import { projectUsageCargoNeedFromConstraints } from "../usage/memoryProjection";
import { createConversationEventsFromInterpretation } from "../orchestrator/eventFactory";
import type { V2TurnStages } from "../orchestrator/types";
import { projectAuthorizedPublicCards } from "../presentation/projectAuthorizedCard.server";
import { classifyDeterministicOfferResponse, createDeterministicOfferResponsePlan } from "../offer/offerResponse";
import type { HumanContextKind } from "../domain/humanContext";
import { detectHumanContext } from "../interpretation/humanContextPolicy";
import { createPreferenceAcknowledgement } from "../realization/preferenceAcknowledgement";

const normalizedAct = (acts: readonly string[]) => acts.includes("ABUSE") ? "ABUSE" as const : acts.includes("OFFER_ACCEPTANCE") ? "CONSENT" as const : acts.includes("OFFER_DECLINE") ? "DECLINE" as const : acts.includes("CORRECTION") ? "CORRECTION" as const : acts.includes("CANDIDATE_REJECTION") ? "REJECTION" as const : acts.includes("TECHNICAL_EXPLANATION_REQUEST") ? "TECHNICAL_EXPLANATION_REQUEST" as const : acts.includes("DONT_KNOW") ? "UNKNOWN_TECHNICAL_CONCEPT" as const : acts.includes("RECOMMENDATION_REQUEST") ? "RECOMMENDATION_REQUEST" as const : acts.includes("OFF_TOPIC") ? "OFF_TOPIC" as const : acts.includes("CLOSING") ? "CLOSING" as const : acts.some((act) => act === "GREETING" || act === "SOCIAL_MESSAGE") ? "SOCIAL" as const : "INFORMATION" as const;
const directAnswer = (messageId: string, requests: readonly { kind: DirectAnswerObligation["kind"] }[]): DirectAnswerObligation | null => requests[0] ? { kind: requests[0].kind, sourceMessageId: messageId, authorizedExplanationFactIds: ["direct-answer"], authorizedCandidateIds: [], placement: "BEFORE_MATERIAL_QUESTION" } : null;
const TECHNICAL_GUIDANCE: Readonly<Record<string, string>> = Object.freeze({
  transmission: "Şanzıman, aracın gücü tekerleklere nasıl aktardığını anlatır. Şehir içinde rahatlık istiyorsan otomatik; vites değiştirmeyi kendin yönetmek istiyorsan manuel seçebilirsin. Çift kavrama, e-DCT veya tek oran gibi alt türleri bilmen gerekmiyor; önce otomatik–manuel tercihinden ilerleyebiliriz.",
  fuelType: "Yakıt tercihini teknik adlarla bilmen gerekmiyor. Benzin kısa ve karma kullanımda tanıdık bir seçenek; dizel düzenli uzun yol yapanlara daha yakın olabilir; hibrit şehir içindeki dur-kalkta elektrik desteği kullanır; elektrikli ise şarj erişimi ister.",
  bodyStyle: "Gövde tipi aracın biçimini ve günlük kullanımını anlatır: hatchback daha kompakt, sedan ayrı bagajlı, SUV/crossover daha yüksek yapılı, panel van ise yük taşımaya odaklıdır.",
  drivenWheels: "FWD gücü ön tekerleklere, RWD arka tekerleklere, AWD ise ön ve arka tekerleklere aktarır. Günlük asfalt kullanımında önden çekiş çoğu kişi için yeterlidir; çamur, kar ve bozuk zeminde dört çeker daha fazla tutunma sağlayabilir.",
  budget: "Kesin bir bütçe bilmiyorsan sorun değil. İstersen rahat ödeyebileceğin aralığı söyle; bütçe önemli değilse onu da karar filtresinin dışında bırakabiliriz.",
  powerKw: "kW, elektrikli aracın motor gücünü anlatır; benzinli araçlardaki beygir gücünün başka bir ölçüsüdür. Kabaca 100–150 kW günlük şehir ve otoyol kullanımı için canlı, 150–250 kW belirgin biçimde güçlü, 250 kW üzeri ise yüksek performanslı sayılabilir. Araç ağırlığı ve çekiş düzeni de hissi değiştirdiği için yalnız kW değerine bakarak seçim yapmayız.",
  combinedLitresPer100Km: "L/100 km, aracın 100 kilometrede yaklaşık kaç litre yakıt tükettiğini anlatır. Kabaca 5 litrenin altı düşük, 5–7 litre orta, 7 litrenin üzeri daha yüksek tüketim gibi düşünülebilir; şehir trafiği, hava ve sürüş tarzı gerçek sonucu değiştirir.",
  luggageLitres: "Bagaj litresi tek başına gözünde canlanmayabilir. Yaklaşık 300 litre günlük alışveriş ve birkaç kabin boy çanta, 400–500 litre iki büyük bavul ve ek çantalar, daha geniş hacimler ise aile tatili yükü için daha rahattır; bagajın şekli de en az litre kadar önemlidir.",
  electricRangeKm: "Elektrikli menzil, tek şarjla ölçülen yaklaşık mesafedir. Günlük şehir kullanımında 250–350 km çoğu rutin için yeterli olabilir; sık uzun yolda daha yüksek menzil ve hızlı şarj erişimi daha önemlidir. Hava, hız ve klima gerçek menzili değiştirir.",
  maxDcChargePower: "DC şarj gücü, uygun hızlı şarj istasyonunda aracın enerjiyi ne kadar hızlı alabildiğini gösterir. Yüksek kW genellikle daha kısa mola demektir; fakat gerçek süre batarya sıcaklığına, doluluk aralığına ve istasyona göre değişir. Uzun yol beklentini 'kahve molası kadar' diye anlatman sayı vermenden daha yararlıdır.",
});
function inferredGuidanceField(userMessage: string): string | undefined {
  if (/\b(?:fwd|awd|rwd)\b|önden çekiş|arkadan itiş|dört çeker|çekiş düzen/iu.test(userMessage)) return "drivenWheels";
  if (/\bkw\b|motor gücü|beygir/iu.test(userMessage)) return "powerKw";
  if (/l\/100|litre.*100|yakıt tüketim|ne kadar yak/iu.test(userMessage)) return "combinedLitresPer100Km";
  if (/bagaj|bavul|valiz/iu.test(userMessage)) return "luggageLitres";
  if (/dc|hızlı şarj|şarj.*(?:süre|bekle|mola)/iu.test(userMessage)) return "maxDcChargePower";
  if (/menzil|tek şarj/iu.test(userMessage)) return "electricRangeKm";
  return undefined;
}
function socialResponse(userMessage: string, kind: "GREETING" | "GENERAL" | HumanContextKind | undefined): string {
  if (/nasılsın diye sormadım/iu.test(userMessage)) return "Haklısın; nasılsın diye sormadın. Önceki cevabım hatalıydı.";
  if (/sana güvenmiyorum/iu.test(userMessage)) return "Bunu söylemende haklısın; net olmayan cevaplar güven vermedi. Söylediğin ihtiyetten devam edeceğim.";
  if (/hangi tercih\??/iu.test(userMessage)) return "Henüz netleşmiş bir araç tercihin yok; önceki cevabım bu yüzden anlamsızdı.";
  const humanContext = detectHumanContext(userMessage);
  if (humanContext && humanContext.kind === kind) return humanContext.safeAcknowledgement;
  if (/nasılsın|nasıl gidiyor/iu.test(userMessage)) return "İyiyim, teşekkürler. Sen nasılsın?";
  if (/^(?:merhaba|selam|selamlar|iyi günler)[.! ]*$/iu.test(userMessage)) return "Merhaba! Hoş geldin.";
  return "Seni dinliyorum; araç ihtiyacından devam edebiliriz.";
}
function guidanceField(memory: import("../domain/conversationMemory").ConversationMemory, interpretation: import("../interpretation/types").AuthoritativeSemanticPlan, userMessage: string): string | undefined { return interpretation.result.technicalGuidanceRequest?.fieldId ?? inferredGuidanceField(userMessage) ?? [...memory.materialQuestionHistory].reverse().find((item) => item.answerStatus === "OPEN")?.field; }
function technicalGuidance(field: string | undefined, userMessage: string): string | undefined {
  if (field === "fuelType" && /hafif hibrit|mild hibrit|tam hibrit/iu.test(userMessage)) return "Hafif hibritte elektrik motoru benzinli motora destek olur ama aracı genellikle tek başına yürütmez. Tam hibrit ise özellikle düşük hızda ve kısa mesafede yalnız elektrikle ilerleyebilir; şehir içindeki dur-kalkta farkı daha belirgin hissedilir. İkisi de prize takılmadan kullanılır.";
  return TECHNICAL_GUIDANCE[field ?? ""];
}
const offerIdentity = (conversationId: string, messageId: string) => createHash("sha256").update(`${conversationId}:${messageId}`).digest("hex").slice(0, 32);
export function createProductionV2TurnStages(input: { readonly repositoryRoot?: string; readonly interpreter: StructuredInterpretationModel; readonly realizer: NaturalRealizationModel; readonly signer?: OfferSigner; readonly offerStore?: GovernedOfferStore; readonly shadow?: boolean; readonly smokeObserver?: (value: Readonly<Record<string, unknown>>) => void }): V2TurnStages {
  const repositoryRoot = input.repositoryRoot ?? process.cwd(); const catalogRepository = createProductionCatalogReleaseRepository(repositoryRoot);
  const decisionLayersByCatalog = new Map<string, ReturnType<typeof loadProductionDecisionLayers>>();
  const safePersonaByCatalog = new Map<string, ReturnType<typeof loadActiveVehiclePersonaSafeTraits>>();
  return {
    loadCatalog: ({ memory, now }) => memory ? loadPinnedCatalogSnapshot({ repository: catalogRepository, releaseVersion: memory.catalogAuthority.releaseVersion, catalogFingerprint: memory.catalogAuthority.catalogFingerprint, activatedAt: memory.catalogAuthority.activatedAt, now }) : loadActiveCatalogSnapshot({ repository: catalogRepository, now }),
    interpretOfferResponse: async (turn, previous) => { const response = classifyDeterministicOfferResponse(turn.userMessage); if (!response || !turn.offerToken || !previous || !input.signer || !input.offerStore) return null; const verified = input.signer.verify(turn.offerToken); if (verified.status !== "VALID" || verified.conversationId !== turn.conversationId || verified.catalogFingerprint !== previous.catalogAuthority.catalogFingerprint || verified.decisionFingerprint !== previous.decisionFingerprint) return null; const persisted = await input.offerStore.get(verified.offerId); if (!persisted || persisted.conversationId !== turn.conversationId || !["CREATED", "CONSENTED"].includes(persisted.lifecycleState) || persisted.catalogFingerprint !== previous.catalogAuthority.catalogFingerprint || persisted.decisionFingerprint !== previous.decisionFingerprint || Date.parse(persisted.expiresAt) < Date.parse(turn.requestTime)) return null; input.smokeObserver?.({ phase: "OFFER_RESPONSE", interpretationSource: "DETERMINISTIC_OFFER_RESPONSE", providerCalled: false, offerResponse: response, offerVerification: "VALID" }); return createDeterministicOfferResponsePlan(turn.messageId, response); },
    interpret: (turn, previous) => interpretUserMessage({ model: input.interpreter, messageId: turn.messageId, userText: turn.userMessage, fieldRegistry: V2_DECISION_FIELD_REGISTRY_V1, activeFieldIds: previous?.events.filter((event): event is Extract<typeof event, { eventType: "CONSTRAINT" }> => event.eventType === "CONSTRAINT" && event.status === "ACTIVE").map((event) => event.field), openMaterialQuestionField: [...(previous?.materialQuestionHistory ?? [])].reverse().find((item) => item.answerStatus === "OPEN")?.field, revealedCandidateReferences: previous?.revealedCandidateIds }),
    createEvents: createConversationEventsFromInterpretation,
    reduceMemory: ({ previous, events, catalog }) => previous ? reduceConversationMemoryV2({ conversationId: previous.conversationId, previousMemory: previous, appendedEvents: events, catalogAuthority: catalog.authority, fingerprintPolicy: CARS_MEMORY_FINGERPRINT_POLICY_V1 }) : replayConversationMemoryV2({ conversationId: events[0]?.conversationId ?? "unknown", events, catalogAuthority: catalog.authority, fingerprintPolicy: CARS_MEMORY_FINGERPRINT_POLICY_V1 }),
    evaluate: async ({ turn, memory, catalog, interpretation, now }) => {
      if (memory.catalogAuthority.catalogFingerprint !== catalog.authority.catalogFingerprint) throw new Error("COMPOSITION_CATALOG_FINGERPRINT_MISMATCH");
      const constraints = projectActiveConstraints(memory.events.filter((event) => event.eventType === "CONSTRAINT")); const rejections = projectActiveRejections(memory.events.filter((event) => event.eventType === "CANDIDATE_REJECTION"));
      const currentModelReferences = memory.modelReferences.filter((reference) => reference.sourceMessageId === turn.messageId);
      const comparisonReferences = currentModelReferences.filter((reference) => reference.decisionEffect === "COMPARISON_SCOPE");
      const comparisonFamilyIds = [...new Set(comparisonReferences.flatMap((reference) => reference.resolvedFamilyIds))];
      const comparisonScope = comparisonReferences.length > 0;
      const latestModelPreference = [...memory.modelReferences].reverse().find((event) => event.decisionEffect === "PREFERENCE");
      const preferenceFamilyIds = latestModelPreference?.resolution === "EXACT_MODEL_FAMILY" ? latestModelPreference.resolvedFamilyIds : [];
      const preferenceScope = !comparisonScope && preferenceFamilyIds.length > 0;
      const scopedFamilyIds = comparisonScope ? comparisonFamilyIds : preferenceScope ? preferenceFamilyIds : [];
      const scopedVariantIds = new Set(scopedFamilyIds.flatMap((familyId) => catalog.familyIndex.get(familyId)?.variantIds ?? []));
      const decisionCatalog = scopedFamilyIds.length ? { ...catalog, variants: Object.freeze(catalog.variants.filter((variant) => scopedVariantIds.has(variant.id))) } : catalog;
      const usageNeed = projectUsageCargoNeedFromConstraints(memory.events.filter((event): event is Extract<typeof event, { eventType: "CONSTRAINT" }> => event.eventType === "CONSTRAINT"));
      const technical = evaluateTechnicalCandidatePool({ snapshot: decisionCatalog, decisionFingerprint: memory.decisionFingerprint, activeConstraints: constraints, activeRejections: rejections, usageNeed, fieldRegistry: V2_DECISION_FIELD_REGISTRY_V1, usagePolicies: USAGE_CARGO_POLICIES_V1 });
      const affordability = evaluateAffordabilityCandidatePool({ snapshot: catalog, technicalPool: technical, budget: memory.budget, evaluationTime: now.toISOString(), priceAuthorityPolicy: PRICE_AUTHORITY_POLICY_V1, affordabilityPolicy: AFFORDABILITY_POLICY_V1 });
      const layerCacheKey = `${catalog.authority.releaseVersion}:${catalog.authority.catalogFingerprint}`;
      const productionDailyPromise = decisionLayersByCatalog.get(layerCacheKey) ?? loadProductionDecisionLayers(catalog, repositoryRoot);
      decisionLayersByCatalog.set(layerCacheKey, productionDailyPromise);
      const productionDaily = await productionDailyPromise; const dailyLife = productionDaily.dailyLife.status === "READY" ? createDailyLifeLayerSnapshot({ catalogReleaseVersion: catalog.authority.releaseVersion, catalogFingerprint: catalog.authority.catalogFingerprint, layerVersion: productionDaily.dailyLife.releaseVersion, signals: [] }) : undefined;
      const safePersonaPromise = safePersonaByCatalog.get(layerCacheKey) ?? loadActiveVehiclePersonaSafeTraits({ repositoryRoot, catalogRelease: catalog.authority.releaseVersion.startsWith("v") ? catalog.authority.releaseVersion : `v${catalog.authority.releaseVersion}`, catalogFingerprint: catalog.authority.catalogFingerprint, catalogVariantIds: catalog.variants.map((variant) => variant.id), catalogFamilies: catalog.familyIndex.values().map((family) => ({ familyId: family.familyId, variantIds: family.variantIds })) });
      safePersonaByCatalog.set(layerCacheKey, safePersonaPromise);
      const safePersona = await safePersonaPromise;
      const persona = safePersona.status === "READY" ? createPersonaLayerSnapshot({ catalogReleaseVersion: catalog.authority.releaseVersion, catalogFingerprint: catalog.authority.catalogFingerprint, layerVersion: safePersona.release.releaseVersion, signals: selectOwnerApprovedSafePersonaSignals(safePersona.release).signals }) : undefined;
      const functionalPreferenceSignals = createExplicitFunctionalPreferenceSignals({ snapshot: catalog, constraints: constraints.activeNonHardConstraints });
      const requestedPriceSegment = constraints.activeNonHardConstraints.find((constraint) => constraint.fieldId === "relativePriceSegment")?.normalizedValue;
      const priceSegmentSignals = typeof requestedPriceSegment === "string" ? projectRelativePriceSegmentsCached({ snapshot: catalog, evaluationTime: now.toISOString(), priceAuthorityPolicy: PRICE_AUTHORITY_POLICY_V1 }).projections.filter((projection) => projection.comparableCohortPriceSegment === requestedPriceSegment).map((projection) => ({ exactVariantId: projection.exactVariantId, score: 1, reasonCode: `RELATIVE_PRICE_SEGMENT_${requestedPriceSegment}`, explanationFactId: `relative-price-segment:${projection.exactVariantId}` })) : [];
      const technicallyEligibleIds = new Set(technical.eligibleCandidateIds);
      const preferredBudgetOfferIds = new Set(affordability.candidates.filter((candidate) => candidate.softSignals.some((signal) => (signal.kind === "WITHIN_PREFERRED_BUDGET" || signal.kind === "OVER_PREFERRED_BUDGET") && (signal.rankingScore ?? Number.NEGATIVE_INFINITY) >= 3)).map((candidate) => candidate.exactVariantId));
      const hasPreferredBudgetGate = Boolean(memory.budget.preferredBudget && !memory.budget.maximumHardCeiling && !memory.budget.budgetExcluded);
      const selectableTechnicalIds = affordability.selectableCandidateIds.filter((candidateId) => {
        if (!technicallyEligibleIds.has(candidateId)) return false;
        const candidate = affordability.candidates.find((item) => item.exactVariantId === candidateId);
        if (candidate?.finalDisposition === "CONDITIONALLY_ELIGIBLE_ESTIMATED_OVER_BUDGET") return false;
        return !hasPreferredBudgetGate || preferredBudgetOfferIds.has(candidateId);
      });
      const preferredBudgetGap = hasPreferredBudgetGate && selectableTechnicalIds.length === 0 && technical.eligibleCandidateIds.length > 0;
      const rankableAffordability = { ...affordability, selectableCandidateIds: selectableTechnicalIds };
      const ranking = rankSelectableCandidates({ snapshot: catalog, technicalPool: technical, affordabilityPool: rankableAffordability, persona: memory.persona, confirmedFunctionalSignals: functionalPreferenceSignals, softPreferenceSignals: priceSegmentSignals, dailyLifeLayer: dailyLife, personaLayer: persona });
      const shortlist = selectRankedCandidateShortlist({ ranking, maximumCandidates: 3, familyDiversity: !comparisonScope, singleRequested: preferenceScope });
      const availability = classifyCandidateDecisionAvailability({ technicalPool: technical, affordabilityPool: { ...affordability, selectableCandidateIds: selectableTechnicalIds }, ranking });
      const generatedQuestions = generateMaterialQuestionCandidates({ snapshot: catalog, candidateIds: ranking.rankedCandidateIds, memory, constraints, comparisonScope });
      const semanticRecoveryQuestion = createConversationLocalSemanticRecoveryQuestion({
        userText: turn.userMessage,
        memory,
        snapshot: catalog,
        candidateIds: ranking.rankedCandidateIds,
        bodyStyleAlreadyInterpreted: interpretation.acceptedConstraintMutations.some((mutation) => mutation.fieldId === "bodyStyle"),
        priceMeaningClarificationEligible: generatedQuestions.stageCompletion.filter((stage) => ["USAGE_CONTEXT", "VEHICLE_ARCHITECTURE", "FUNCTIONAL_NEEDS", "ENERGY_FIT", "TECHNICAL_PREFERENCES"].includes(stage.stage)).every((stage) => stage.status !== "INCOMPLETE"),
      });
      const questions = semanticRecoveryQuestion
        ? Object.freeze({
            ...generatedQuestions,
            unansweredDecisionFields: Object.freeze([...new Set([...generatedQuestions.unansweredDecisionFields, semanticRecoveryQuestion.question.field])]),
            questionCandidates: Object.freeze([semanticRecoveryQuestion, ...generatedQuestions.questionCandidates]),
          })
        : generatedQuestions;
      const recommendationReadiness = assessRecommendationReadiness({ memory, candidateAvailability: availability, candidateCount: ranking.rankedCandidateIds.length, comparisonScope, unansweredDecisionFields: questions.unansweredDecisionFields, questionCandidates: questions.questionCandidates });
      const obligation = directAnswer(interpretation.result.messageId, interpretation.result.directAnswerRequests);
      const abusiveCorrection = interpretation.result.acts.includes("ABUSE") && interpretation.acceptedConstraintMutations.some((mutation) => mutation.operation === "CORRECT" || mutation.operation === "CLEAR");
      const act = normalizedAct(interpretation.result.acts);
      let action = decideConversationAction({ memory, directAnswerObligation: obligation, candidateAvailability: availability, recommendationReadiness, ranking, rankedShortlist: shortlist, conflictAnalysis: null, unansweredDecisionFields: questions.unansweredDecisionFields, questionCandidates: questions.questionCandidates, normalizedUserAct: act, policy: ACTION_POLICY_V1, catalogSnapshotAvailable: true, explicitTrimComparisonRequested: comparisonScope, systemCorrectionRequired: abusiveCorrection, approximateBudgetCaveatFactIds: affordability.budgetIncreaseGuidance.some((item) => item.authority === "APPROXIMATE_INTERNAL_ESTIMATE") ? ["approximate-budget"] : [] });
      const functionalScoreByCandidate = new Map<string, number>();
      for (const signal of functionalPreferenceSignals) functionalScoreByCandidate.set(signal.exactVariantId, (functionalScoreByCandidate.get(signal.exactVariantId) ?? 0) + signal.score);
      const strongestCatalogFunctionalScore = Math.max(0, ...functionalScoreByCandidate.values());
      const strongestRemainingFunctionalScore = Math.max(0, ...ranking.candidates.map((candidate) => candidate.rankVector.find((tier) => tier.tier === "CONFIRMED_FUNCTIONAL_FIT")?.score ?? 0));
      const rejectedAllFullPreferenceMatches = act === "REJECTION" && strongestCatalogFunctionalScore > 0 && strongestRemainingFunctionalScore < strongestCatalogFunctionalScore;
      if (rejectedAllFullPreferenceMatches) action = { ...action, nextState: "FILTERING", nextAction: { type: "ANSWER_DIRECTLY" }, shortlistIntent: null, materialQuestion: null };
      const latestLookup = [...currentModelReferences].reverse().find((event) => event.decisionEffect === "LOOKUP_ONLY");
      const lookupFamily = latestLookup?.resolvedFamilyIds[0] ? catalog.familyIndex.get(latestLookup.resolvedFamilyIds[0]) : undefined;
      const lookupText = latestLookup?.resolution === "NOT_FOUND" ? `${latestLookup.rawText} aktif sıfır araç kataloğunda bulunmuyor.` : latestLookup?.resolution === "AMBIGUOUS" ? `${latestLookup.rawText} birden fazla katalog modeliyle eşleşiyor; marka bilgisini netleştirmek gerekiyor.` : lookupFamily ? `${lookupFamily.canonicalBrand} ${lookupFamily.canonicalModel} aktif sıfır araç kataloğunda bulunuyor.` : undefined;
      const preferredFamily = latestModelPreference?.resolvedFamilyIds[0] ? catalog.familyIndex.get(latestModelPreference.resolvedFamilyIds[0]) : undefined;
      const modelPreferenceText = latestModelPreference?.resolution === "EXACT_MODEL_FAMILY" && preferredFamily
        ? `${preferredFamily.canonicalBrand} ${preferredFamily.canonicalModel} isteğini başlangıç noktası olarak tutuyorum; kullanımına uyup uymadığını birlikte kontrol edelim.`
        : undefined;
      const comparisonText = comparisonScope ? comparisonReferences.map((reference) => { const family = reference.resolvedFamilyIds[0] ? catalog.familyIndex.get(reference.resolvedFamilyIds[0]) : undefined; return reference.resolution === "NOT_FOUND" ? `${reference.rawText} aktif katalogda bulunmuyor.` : reference.resolution === "AMBIGUOUS" ? `${reference.rawText} için marka bilgisi netleşmeli.` : family ? `${family.canonicalBrand} ${family.canonicalModel} aktif katalogda bulunuyor.` : `${reference.rawText} katalog kapsamında çözülemedi.`; }).join(" ") : undefined;
      const technicalField = guidanceField(memory, interpretation, turn.userMessage); const technicalText = technicalGuidance(technicalField, turn.userMessage);
      const corrected = interpretation.acceptedConstraintMutations.at(-1); const correctionText = corrected ? `Tamam; ${corrected.fieldId === "bodyStyle" ? "gövde" : corrected.fieldId === "transmission" ? "şanzıman" : corrected.fieldId === "fuelType" ? "yakıt" : "araç"} tercihini düzelttim.` : "Tamam, düzeltmeni dikkate aldım.";
      const socialText = socialResponse(turn.userMessage, interpretation.result.socialSignal?.kind);
      const currentSocialContextEvent = memory.events.find((event): event is Extract<typeof event, { eventType: "SOCIAL_INTERACTION" }> => event.eventType === "SOCIAL_INTERACTION" && event.sourceMessageId === turn.messageId);
      const currentHumanContext = currentSocialContextEvent?.humanContext;
      const humanContextAlreadyAcknowledged = currentHumanContext ? memory.events.some((event) => event.eventType === "SOCIAL_INTERACTION" && event.humanContext === currentHumanContext && event.sourceMessageId !== turn.messageId) : false;
      const contextualSocialAcknowledgement = Boolean(currentHumanContext && !humanContextAlreadyAcknowledged);
      const neutralChoiceAcknowledgement = /\b(?:fark etmez|önemli değil|bilmiyorum|emin değilim|atla)\b/iu.test(turn.userMessage.trim()) ? "Bu başlığı açık bırakalım; seni gereksiz yere tek seçeneğe sıkıştırmayacağım." : undefined;
      const preferenceAcknowledgement = createPreferenceAcknowledgement({ constraints: interpretation.acceptedConstraintMutations, budgets: interpretation.acceptedBudgetMutations }) ?? neutralChoiceAcknowledgement;
      const technicalAnswerRequested = obligation?.kind === "TECHNICAL_EXPLANATION" || act === "TECHNICAL_EXPLANATION_REQUEST" || act === "UNKNOWN_TECHNICAL_CONCEPT";
      const descriptiveAvailability = /(?:arazi arac[ıi]|elektrikli araç|dizel araç|benzinli araç|hibrit araç).*(?:var mı|mevcut mu)/iu.test(turn.userMessage);
      const pluralRevealedRejection = act === "REJECTION" && /(?:bunları|bu araçları|bu modelleri|hepsini|üçünü|ikisini)/iu.test(turn.userMessage);
      const safeFactText = comparisonText ?? modelPreferenceText ?? (act === "REJECTION" ? rejectedAllFullPreferenceMatches ? "Bu seçenekleri yeniden önermeyeceğim. Aynı gövde ve yakıt tercihlerini birlikte karşılayan, daha önce göstermediğim başka bir seçenek kalmadı; gövde veya yakıt tercihinden hangisinin esneyebileceğini söyleyebilirsin." : pluralRevealedRejection ? "Bu seçenekleri yeniden önermeyeceğim; kalan araçlarla devam ediyorum." : "Bu modeli yeniden önermeyeceğim; kalan seçeneklerle devam ediyorum." : act === "CORRECTION" ? correctionText : undefined) ?? (contextualSocialAcknowledgement ? socialText : undefined) ?? (technicalAnswerRequested ? technicalText ?? "Teknik terimi bilmen gerekmiyor; günlük kullanım beklentine göre ilerleyebiliriz." : lookupText) ?? preferenceAcknowledgement ?? (act === "SOCIAL" ? socialText : act === "ABUSE" ? abusiveCorrection ? `Hakaret etmeden devam edelim; düzeltmeni uyguladım. ${correctionText}` : action.nextAction.type === "END_POLITELY" ? "Hakaret içeren üslup sürdüğü için bu görüşmeyi burada bitiriyorum." : "Hakaret etmeden devam edelim; araç seçimi konusunda yardımcı olmaya hazırım." : act === "OFF_TOPIC" ? action.nextAction.type === "END_POLITELY" ? "Araç seçimi dışındaki talepler sürdüğü için bu görüşmeyi burada bitiriyorum." : "Bu görüşme araç seçimine odaklanıyor; kısa bir sapmadan sonra araç ihtiyacına dönebiliriz." : preferredBudgetGap ? "Bu kullanım ve araç tercihlerini belirttiğin bütçe seviyesinde karşılayan bir seçenek bulamadım. İstersen bütçeyi ne kadar artırabileceğini konuşabilir veya araç tercihlerinden birini esnetebiliriz." : availability === "HARD_CONFLICT" ? "Bu şartların tümünü aynı anda karşılayan bir araç bulamadım. Hangi tercihin esneyebileceğini birlikte seçebiliriz." : availability === "PRICE_UNRESOLVED" ? "Teknik olarak eşleşen seçenekler var; ancak fiyatları doğrulanmadığı için bütçe uyumlarını kesinleştiremiyorum. Bütçe tavanını kaldırabilir veya koşullardan birini esnetebilirsin." : availability === "TECHNICALLY_NOT_EVALUABLE" ? "Bazı teknik şartlar mevcut verilerle kesin değerlendirilemiyor; doğrulayabildiğim koşulları koruyarak devam edebilirim." : descriptiveAvailability ? "Elektrikli ve arazi kullanımına uygun seçenekleri doğru gövde tipini belirleyerek kontrol edebiliriz." : obligation?.kind === "RECOMMENDATION_REQUEST" && recommendationReadiness === "READY_FOR_OFFER" ? "İhtiyaçlarına uyan seçenekler hazır. Görmek ister misin?" : obligation?.kind === "RECOMMENDATION_REQUEST" ? "İhtiyacını birlikte daraltalım." : action.materialQuestion ? "Kararı etkileyen bir noktayı netleştirelim." : "Söylediğin bilgi karar üzerinde bir değişiklik oluşturmadı; neyi kastettiğini netleştirebiliriz.");
      const factKind = contextualSocialAcknowledgement || act === "SOCIAL" ? "SOCIAL_CONTEXT" as const : technicalText || obligation?.kind === "TECHNICAL_EXPLANATION" ? "TECHNICAL_GUIDANCE" as const : comparisonText || lookupText || modelPreferenceText ? "CATALOG" as const : "LIMITATION" as const;
      if (modelPreferenceText && !action.directAnswerObligation) action = { ...action, directAnswerObligation: { kind: "OTHER_SUPPORTED", sourceMessageId: turn.messageId, authorizedExplanationFactIds: ["direct-answer"], authorizedCandidateIds: [], placement: "BEFORE_MATERIAL_QUESTION" } };
      if (preferenceAcknowledgement && !action.directAnswerObligation) action = { ...action, directAnswerObligation: { kind: "OTHER_SUPPORTED", sourceMessageId: turn.messageId, authorizedExplanationFactIds: ["direct-answer"], authorizedCandidateIds: [], placement: "BEFORE_MATERIAL_QUESTION" }, explanationFactIds: [...new Set([...action.explanationFactIds, "direct-answer"])] };
      if ((["CORRECTION", "REJECTION"].includes(act) || abusiveCorrection) && !action.explanationFactIds.includes("direct-answer")) action = { ...action, explanationFactIds: [...action.explanationFactIds, "direct-answer"] };
      if (act === "REJECTION" && !action.directAnswerObligation) action = { ...action, directAnswerObligation: { kind: "OTHER_SUPPORTED", sourceMessageId: turn.messageId, authorizedExplanationFactIds: ["direct-answer"], authorizedCandidateIds: [], placement: "BEFORE_MATERIAL_QUESTION" } };
      const facts = [{ id: "direct-answer", kind: factKind, safeText: safeFactText }];
      const offerStoreRevision = memory.events.filter((event) => event.eventType === "OFFER_LIFECYCLE").length;
      let offerTransition: PersistedOfferTransitionIntent | undefined; if (!input.shadow && input.signer && input.offerStore && turn.offerToken && interpretation.result.acts.includes("OFFER_ACCEPTANCE")) { const verified = input.signer.verify(turn.offerToken); if (verified.status === "VALID" && verified.conversationId === memory.conversationId) { if (input.offerStore.persistsCreationWithConversationCommit) { const persisted = await input.offerStore.get(verified.offerId); const audit = turn.recommendationOfferAuditIntent; if (persisted && audit && audit.offerId === verified.offerId && audit.conversationId === memory.conversationId && persisted.lifecycleState === "CREATED" && persisted.catalogFingerprint === memory.catalogAuthority.catalogFingerprint && persisted.decisionFingerprint === memory.decisionFingerprint) { offerTransition = { ...audit, offerId: verified.offerId, conversationId: memory.conversationId, to: "REVEALED" as const, offerIdentityFingerprint: offerIdentityFingerprint(persisted) }; action = { ...action, nextState: "REVEALED", nextAction: { type: "REVEAL_AUTHORIZED_CARDS" }, shortlistIntent: null, materialQuestion: null }; } } else { const persisted = await input.offerStore.get(verified.offerId); const acceptedAt = turn.recommendationOfferAuditIntent?.acceptedAt ?? now.toISOString(); const revealedAt = turn.recommendationOfferAuditIntent?.revealedAt ?? new Date(Date.parse(acceptedAt) + 1).toISOString(); const consented = await input.offerStore.transition({ offerId: verified.offerId, conversationId: memory.conversationId, to: "CONSENTED", at: acceptedAt, expectedConversationRevision: offerStoreRevision, idempotencyKey: `${turn.idempotencyKey}:consent` }); if (consented.status === "OK" && persisted) { await input.offerStore.transition({ offerId: verified.offerId, conversationId: memory.conversationId, to: "REVEALED", at: revealedAt, expectedConversationRevision: consented.revision, idempotencyKey: `${turn.idempotencyKey}:reveal` }); offerTransition = { kind: "ACCEPT_RECOMMENDATION_TERMS_AND_REVEAL", offerId: verified.offerId, conversationId: memory.conversationId, to: "REVEALED" as const, recommendationTermsVersion: "REC-2026.08-v1.1", acceptedAt, revealedAt, acceptanceSequence: 1, revealSequence: 2, idempotencyKey: `${turn.idempotencyKey}:rec-audit`, offerIdentityFingerprint: offerIdentityFingerprint(persisted) }; action = { ...action, nextState: "REVEALED", nextAction: { type: "REVEAL_AUTHORIZED_CARDS" }, shortlistIntent: null, materialQuestion: null }; } } } }
      if (!offerTransition && input.signer && input.offerStore && !input.offerStore.persistsCreationWithConversationCommit && turn.offerToken && action.nextAction.type === "REVEAL_AUTHORIZED_CARDS") { const verified = input.signer.verify(turn.offerToken); if (verified.status === "VALID" && verified.conversationId === memory.conversationId) { const current = await input.offerStore.get(verified.offerId); if (current?.lifecycleState === "CREATED") { const acceptedAt = now.toISOString(); const revealedAt = new Date(now.getTime() + 1).toISOString(); const consented = await input.offerStore.transition({ offerId: verified.offerId, conversationId: memory.conversationId, to: "CONSENTED", at: acceptedAt, expectedConversationRevision: offerStoreRevision, idempotencyKey: `${turn.idempotencyKey}:consent` }); if (consented.status === "OK") { await input.offerStore.transition({ offerId: verified.offerId, conversationId: memory.conversationId, to: "REVEALED", at: revealedAt, expectedConversationRevision: consented.revision, idempotencyKey: `${turn.idempotencyKey}:reveal` }); offerTransition = { kind: "ACCEPT_RECOMMENDATION_TERMS_AND_REVEAL", offerId: verified.offerId, conversationId: memory.conversationId, to: "REVEALED" as const, recommendationTermsVersion: "REC-2026.08-v1.1", acceptedAt, revealedAt, acceptanceSequence: 1, revealSequence: 2, idempotencyKey: `${turn.idempotencyKey}:rec-audit`, offerIdentityFingerprint: offerIdentityFingerprint(current) }; } } } }
      if (!input.shadow && input.signer && input.offerStore && turn.offerToken && interpretation.result.acts.includes("OFFER_DECLINE")) { const verified = input.signer.verify(turn.offerToken); if (verified.status === "VALID" && verified.conversationId === memory.conversationId) { if (input.offerStore.persistsCreationWithConversationCommit) offerTransition = { offerId: verified.offerId, conversationId: memory.conversationId, to: "REVOKED" as const, at: now.toISOString() }; else await input.offerStore.transition({ offerId: verified.offerId, conversationId: memory.conversationId, to: "REVOKED", at: now.toISOString(), expectedConversationRevision: offerStoreRevision, idempotencyKey: `${turn.idempotencyKey}:decline` }); action = { ...action, nextState: "UNDERSTANDING_NEEDS", nextAction: { type: "ANSWER_DIRECTLY" }, shortlistIntent: null, materialQuestion: null }; } }
      if (offerTransition?.to === "REVEALED" && input.offerStore?.persistsCreationWithConversationCommit) offerTransition = { ...offerTransition, postCommitAuthorizationRequired: true };
      let offer; let offerToken; if (!input.shadow && input.signer && action.shortlistIntent) { const lastMessage = memory.events.at(-1)?.sourceMessageId ?? "turn"; const identity = offerIdentity(memory.conversationId, lastMessage); offer = createPersistedGovernedOffer({ shortlist: action.shortlistIntent, ranking, affordability, snapshot: catalog, conversationId: memory.conversationId, offerId: `offer_${identity}`, nonce: `nonce_${identity}`, createdAt: now.toISOString(), expiresAt: new Date(now.getTime() + 10 * 60_000).toISOString(), rejectedCandidateIds: rejections.rejections.flatMap((item) => item.candidateId ? [item.candidateId] : []), explicitTrimComparisonRequested: false, explicitPriceUnresolvedConsent: false }); if (input.offerStore && !input.offerStore.persistsCreationWithConversationCommit) { const created = await input.offerStore.create(offer, offerStoreRevision, `${memory.conversationId}:${turn.idempotencyKey}:offer`); if (created.status !== "OK") throw new Error(`OFFER_STORE_${created.status}`); } offerToken = input.signer.sign(offer); }
      input.smokeObserver?.({ phase: "DECISION", messageId: turn.messageId, interpretedActs: interpretation.result.acts, semanticCompleteness: "COMPLETE", acceptedMutationCounts: { constraints: interpretation.acceptedConstraintMutations.length, budgets: interpretation.acceptedBudgetMutations.length, personas: interpretation.acceptedPersonaMutations.length, modelReferences: interpretation.result.modelReferences.length }, action: action.nextAction.type, recommendationReadiness, unansweredDecisionFields: questions.unansweredDecisionFields, generatedQuestionKeys: questions.questionCandidates.map((candidate) => candidate.question.stableSemanticKey), generatedQuestionStages: questions.questionCandidates.map((candidate) => ({ stableSemanticKey: candidate.question.stableSemanticKey, stage: candidate.stage, eligible: candidate.eligible, blockedUntilStagesComplete: candidate.blockedUntilStagesComplete })), questionStageCompletion: questions.stageCompletion, selectedQuestionKey: action.materialQuestion?.stableSemanticKey ?? null, selectedQuestionStage: questions.questionCandidates.find((candidate) => candidate.question.stableSemanticKey === action.materialQuestion?.stableSemanticKey)?.stage ?? null, materialQuestionCount: action.materialQuestion ? 1 : 0, directAnswerRequired: Boolean(obligation), directAnswerPlacement: obligation?.placement ?? null, lookupResolution: latestLookup?.resolution ?? null, modelScope: scopedFamilyIds, modelPreferenceScope: preferenceScope, directAnswerFact: comparisonText ?? lookupText ?? null, availability, technicalBuckets: { eligible: technical.eligibleCandidateIds.length, notEvaluable: technical.notEvaluableCandidateIds.length, eliminated: technical.eliminatedCandidateIds.length }, affordabilityBuckets: { selectable: affordability.selectableCandidateIds.length, verifiedWithin: affordability.verifiedPriceEligibleCandidateIds.length, estimateWithin: affordability.internalEstimateWithinCandidateIds.length, estimateOverConditional: affordability.estimatedOverBudgetConditionalCandidateIds.length, budgetNotApplied: affordability.budgetNotAppliedEligibleCandidateIds.length, verifiedOver: affordability.verifiedOverBudgetCandidateIds.length, unresolved: affordability.priceUnresolvedCandidateIds.length, technicalUnknown: affordability.technicallyNotEvaluableCandidateIds.length, eliminated: affordability.eliminatedCandidateIds.length }, persona: { activated: memory.persona.activated, requestedTraits: memory.persona.requestedTraits, affectedRanking: ranking.candidates.some((candidate) => candidate.personaTrace.affectedRanking) }, activeOffer: memory.currentOffer?.offerId ?? null, offerCreated: Boolean(offer), identityFreeOffer: Boolean(offer), shortlistCandidateIds: shortlist.candidateIds });
      input.smokeObserver?.({ phase: "SEMANTIC_AUTHORITY", messageId: turn.messageId, providerActs: interpretation.providerActs, authoritativeActs: interpretation.result.acts, policyTrace: interpretation.policyTrace });
      return { action, offer, offerToken, offerTransition, facts };
    },
    authorizeCards: async ({ token, conversationId, catalog, memory }) => { if (!input.signer || !input.offerStore) return []; const authorization = await authorizePersistedCards({ token, signer: input.signer, store: input.offerStore, conversationId, catalogFingerprint: catalog.authority.catalogFingerprint, decisionFingerprint: memory.decisionFingerprint }); if (authorization.status !== "AUTHORIZED") return []; const verified = input.signer.verify(token); if (verified.status !== "VALID") return []; const offer = await input.offerStore.get(verified.offerId); if (!offer) return []; return projectAuthorizedPublicCards({ offer, conversationId, decisionFingerprint: memory.decisionFingerprint, snapshot: catalog }); },
    realize: async ({ action, facts }) => { const directFact = action.directAnswerObligation ? facts.find((fact) => action.directAnswerObligation?.authorizedExplanationFactIds.includes(fact.id)) : undefined; const result = await realizeDecisionResponse({ actionDecision: action, ...(directFact ? { directAnswer: { safeText: directFact.safeText, factIds: [directFact.id] } } : {}), explanationFacts: facts, materialQuestion: action.materialQuestion, mentionableCandidates: [], revealableCandidates: [], tonePolicy: TURKISH_TONE_POLICY, safetyPolicy: REALIZATION_SAFETY_POLICY_V1 }, input.realizer); input.smokeObserver?.({ phase: "REALIZATION", action: action.nextAction.type, validation: result.validation.ok ? "VALID" : result.validation.codes, source: result.source, attempts: result.attempts, firstAttemptCodes: result.firstAttemptCodes, repairAttemptCodes: result.repairAttemptCodes }); return { message: result.result.message, source: result.source }; },
  };
}
export function createCarsDecisionV2ProductionComposition(input: Parameters<typeof createProductionV2TurnStages>[0] & { readonly store: import("../orchestrator/types").V2ConversationStore }) { return Object.freeze({ store: input.store, stages: createProductionV2TurnStages(input) }); }
