import { describe, expect, it } from "vitest";
import { createFileSystemAppliancesArtifactRepository } from "../authority/loader.server";
import { enterAppliancesDepartment } from "../entry.server";
import { MemoryAppliancesConversationStore } from "../persistence/memoryStore.testSupport";
import { commitAppliancesBootstrap } from "../persistence/service";
import { recoverAppliancesConversation } from "../recovery.server";
import { loadActiveRefrigeratorAuthority } from "./authority.server";
import { runRefrigeratorConversationTurn } from "./conversation.server";

const id="77777777-7777-4777-8777-777777777777";
async function fixture(){const repository=createFileSystemAppliancesArtifactRepository(process.cwd()),store=new MemoryAppliancesConversationStore();const entry=await enterAppliancesDepartment({repository,productType:"REFRIGERATOR",conversationId:id,now:new Date("2026-09-03T09:00:00Z")});if(entry.status!=="READY")throw new Error(entry.status);await commitAppliancesBootstrap({store,state:entry.state,messageId:"create",payload:{productType:"REFRIGERATOR"}});const loaded=await loadActiveRefrigeratorAuthority(process.cwd());if(loaded.status!=="READY")throw new Error(loaded.reason);return{store,authority:loaded.snapshot};}

describe("REFRIGERATOR end-to-end category adapter",()=>{
  it("loads eight approved exact identities but fails LG closed from runtime selection",async()=>{const loaded=await loadActiveRefrigeratorAuthority(process.cwd());expect(loaded.status).toBe("READY");if(loaded.status!=="READY")return;expect(loaded.snapshot.pack.products).toHaveLength(8);expect(loaded.snapshot.pack.products.map(p=>p.model)).toEqual(expect.arrayContaining(["RB34C6B0E12/TR","KGN55CIE0N","KG56NVWD0N","GC-B569NLLM"]));expect(loaded.snapshot.pack.products.find(p=>p.brand==="LG")).toMatchObject({runtimeSelectable:false,technicalFacts:{dimensionConflict:true}});expect(loaded.snapshot.pack.comparability).toMatchObject({grossNetSubstitution:false,energyRegime:"TR_2019_2016_AB"});});
  it("keeps ties cardless after correction when the expanded catalog remains unresolved",async()=>{const{store,authority}=await fixture();const tied=await runRefrigeratorConversationTurn({store,authority,conversationId:id,messageId:"m1",expectedRevision:1,message:"Genişlik en fazla 80 cm, derinlik en fazla 85 cm, taze gıda net hacmi en az 200 litre",now:new Date("2026-09-03T09:01:00Z")});expect(tied.status).toBe("OK");if(tied.status!=="OK")return;expect(tied.outcome).toMatchObject({kind:"CLARIFY",questionKey:"TIED_SET_EXPLANATION"});expect(tied.state.decisionRecord).toBeUndefined();expect(tied.state.ledger.some(e=>e.conceptId==="BUDGET_SENSITIVITY")).toBe(false);const corrected=await runRefrigeratorConversationTurn({store,authority,conversationId:id,messageId:"m2",expectedRevision:2,message:"Aslında taze gıda net hacmi en az 300 litre",now:new Date("2026-09-03T09:02:00Z")});expect(corrected.status).toBe("OK");if(corrected.status!=="OK")return;expect(corrected.outcome).toMatchObject({kind:"CLARIFY"});expect(corrected.state.decisionRecord).toBeUndefined();expect((await recoverAppliancesConversation(store,id))?.outcome).toMatchObject({kind:"CLARIFY"});});
  it("blocks dependent hard unknowns, supports confirmation/rejection and Pareto without price authority",async()=>{const{store,authority}=await fixture();const unknown=await runRefrigeratorConversationTurn({store,authority,conversationId:id,messageId:"m1",expectedRevision:1,message:"Genişlik en fazla 80 cm, kapı açık derinlik en fazla 120 cm, dondurucu net hacmi en az 100 litre",now:new Date("2026-09-03T09:01:00Z")});expect(unknown.status).toBe("OK");if(unknown.status!=="OK")return;expect(unknown.outcome).toMatchObject({kind:"CLARIFY",questionKey:"UNRESOLVED_HARD_UNCERTAINTY"});const{store:store2,authority:authority2}=await fixture();const proposed=await runRefrigeratorConversationTurn({store:store2,authority:authority2,conversationId:id,messageId:"p1",expectedRevision:1,message:"Mutfak salonla birleşik",now:new Date("2026-09-03T09:01:00Z")});expect(proposed.status).toBe("OK");if(proposed.status!=="OK")return;expect(proposed.state.pendingConfirmation?.conceptId).toBe("LOW_NOISE_PRIORITY");const rejected=await runRefrigeratorConversationTurn({store:store2,authority:authority2,conversationId:id,messageId:"p2",expectedRevision:2,message:"Hayır",now:new Date("2026-09-03T09:02:00Z")});expect(rejected.status).toBe("OK");if(rejected.status!=="OK")return;expect(rejected.state.pendingConfirmation).toBeUndefined();expect(rejected.state.ledger.some(e=>e.status==="REJECTED")).toBe(true);});
});

describe("REFRIGERATOR conversational parity",()=>{it("resolves the reported broad-capacity follow-up without repeating a generic question",async()=>{const{store,authority}=await fixture();const broad=await runRefrigeratorConversationTurn({store,authority,conversationId:id,messageId:"wide-1",expectedRevision:1,message:"Geniş iç hacimli bir buzdolabına ihtiyacım var."});expect(broad.status).toBe("OK");if(broad.status!=="OK")return;expect(broad.outcome).toMatchObject({kind:"CLARIFY",questionKey:"appliances.refrigerator.capacityScope"});expect("message" in broad.outcome&&broad.outcome.message).toContain("toplam net hacim");const contextual=await runRefrigeratorConversationTurn({store,authority,conversationId:id,messageId:"wide-2",expectedRevision:2,message:"En geniş hacim."});expect(contextual.status).toBe("OK");if(contextual.status!=="OK")return;expect(contextual.state.ledger.some(e=>e.conceptId==="TOTAL_NET_CAPACITY_PRIORITY"&&e.status==="ACCEPTED_EXPLICIT")).toBe(true);expect(contextual.outcome).toMatchObject({kind:"ASK",questionKey:"appliances.refrigerator.installationEnvelope"});});});
describe("REFRIGERATOR pending question binding",()=>{it("records a declined installation constraint and advances without repeating it",async()=>{const{store,authority}=await fixture();const asked=await runRefrigeratorConversationTurn({store,authority,conversationId:id,messageId:"q1",expectedRevision:1,message:"Sessiz olsun"});expect(asked.status==="OK"&&asked.outcome).toMatchObject({kind:"ASK",questionKey:"appliances.refrigerator.installationEnvelope"});const answered=await runRefrigeratorConversationTurn({store,authority,conversationId:id,messageId:"q2",expectedRevision:2,message:"gerek yok"});expect(answered.status).toBe("OK");if(answered.status!=="OK")return;expect(answered.outcome).not.toMatchObject({questionKey:"appliances.refrigerator.installationEnvelope"});expect(answered.state.ledger).toEqual(expect.arrayContaining([expect.objectContaining({conceptId:"INSTALLATION_ENVELOPE",normalizedValue:{declined:true},decisionUse:"NONE"})]));});});
describe("REFRIGERATOR lifecycle characterization",()=>{it("preserves exact replay, payload conflict and revision conflict",async()=>{const{store,authority}=await fixture();const input={store,authority,conversationId:id,messageId:"life",expectedRevision:1,message:"Mutfak salonla birleşik"};const first=await runRefrigeratorConversationTurn(input);expect(first.status).toBe("OK");expect(await runRefrigeratorConversationTurn(input)).toEqual(first.status==="OK"?{...first,replayed:true}:first);expect(await runRefrigeratorConversationTurn({...input,message:"Sessiz olsun"})).toEqual({status:"MESSAGE_PAYLOAD_CONFLICT"});expect(await runRefrigeratorConversationTurn({...input,messageId:"stale",expectedRevision:1})).toEqual({status:"REVISION_CONFLICT"});});});
describe("REFRIGERATOR çift-kapı ambiguity",()=>{it("acknowledges without redefining the term, then validates one precise arrangement answer",async()=>{const{store,authority}=await fixture();const first=await runRefrigeratorConversationTurn({store,authority,conversationId:id,messageId:"door-1",expectedRevision:1,message:"çift kapılı buzdolabına ihtiyacım var"});expect(first.status).toBe("OK");if(first.status!=="OK")return;expect(first.outcome).toMatchObject({kind:"CLARIFY",questionKey:"appliances.refrigerator.freezerArrangement"});expect("message" in first.outcome&&first.outcome.message).toContain("varsayımına çevirmiyorum");expect("message" in first.outcome&&first.outcome.message.match(/\?/gu)).toHaveLength(1);const answered=await runRefrigeratorConversationTurn({store,authority,conversationId:id,messageId:"door-2",expectedRevision:2,message:"Dondurucu altta olsun"});expect(answered.status).toBe("OK");if(answered.status!=="OK")return;expect(answered.state.ledger).toEqual(expect.arrayContaining([expect.objectContaining({conceptId:"FREEZER_ARRANGEMENT",normalizedValue:"BOTTOM_FREEZER_COMBI",decisionUse:"HARD_FILTER"})]));expect(answered.outcome).toMatchObject({kind:"ASK",questionKey:"appliances.refrigerator.installationEnvelope"});expect((await recoverAppliancesConversation(store,id))?.outcome).toMatchObject({choices:{questionKey:"appliances.refrigerator.installationEnvelope",source:"DOMAIN_PACK"}});});});
