import { cookies } from "next/headers";

import { PILOT_SESSION_COOKIE, verifyPilotSessionToken } from "@/features/pilot/pilotSession.server";

export default async function PilotPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const session = verifyPilotSessionToken((await cookies()).get(PILOT_SESSION_COOKIE)?.value);
  if (!session) return <main className="min-h-screen bg-white px-5 py-16 text-neutral-950"><section className="mx-auto max-w-md rounded-3xl border border-neutral-200 bg-white p-8 shadow-sm"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-neutral-500">Expiya Cars Pilot</p><h1 className="mt-4 text-3xl font-bold">Pilot girişi</h1><p className="mt-3 text-sm text-neutral-600">Size verilen kullanıcı adı ve şifreyle giriş yapın.</p>{(await searchParams).error ? <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">Kullanıcı adı veya şifre doğrulanamadı.</p> : null}<form action="/api/pilot/session" method="post" className="mt-6 space-y-4"><label className="block text-sm font-medium">Kullanıcı adı<input name="username" autoComplete="username" required className="mt-1 w-full rounded-xl border border-neutral-300 px-4 py-3" /></label><label className="block text-sm font-medium">Şifre<input name="password" type="password" autoComplete="current-password" required minLength={8} className="mt-1 w-full rounded-xl border border-neutral-300 px-4 py-3" /></label><button className="w-full rounded-xl bg-neutral-950 px-5 py-3 font-semibold text-white">Giriş yap</button></form></section></main>;
  return <main className="min-h-screen bg-white px-5 py-16 text-neutral-950"><section className="mx-auto max-w-2xl rounded-3xl border border-neutral-200 bg-white p-8 shadow-sm"><div className="flex items-center justify-between gap-4"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-neutral-500">Expiya Cars Pilot</p><form action="/api/pilot/logout" method="post"><button className="text-sm font-semibold underline underline-offset-4">Çıkış yap</button></form></div><h1 className="mt-4 text-3xl font-bold">Hoş geldin, {session.displayName}</h1><p className="mt-3 leading-7 text-neutral-600">Karar motorunu farklı ihtiyaçlar ve doğal konuşmalarla test edebilirsin. Görüşmen, “Görüşmeyi sil” dediğinde kullanıcı adına bağlı tamamlanmış pilot kaydı olarak arşivlenir. Her pilot kullanıcı en fazla 200 görüşme tamamlayabilir.</p><form action="/cars/analysis" className="mt-8"><input type="hidden" name="pilot" value="1" /><label className="block text-sm font-medium">İlk mesaj<textarea name="query" required className="mt-2 h-36 w-full rounded-2xl border border-neutral-300 p-4" placeholder="Araç ihtiyacını anlat…" /></label><button className="mt-4 rounded-xl bg-neutral-950 px-6 py-3 font-semibold text-white">Görüşmeyi başlat</button></form></section></main>;
}
