/* eslint-disable @typescript-eslint/no-explicit-any -- heterogeneous immutable v1 catalog schemas are normalized at this repository boundary */
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import { finalizeRelease, proveExactIdentity, sha256, splitExtractedPages, stableJson, validateOfficialManualUrl, validateRelease, type GovernedManual, type L9Knowledge, type ManualBlocker, type ManualInventoryMember } from "../features/appliances/manuals/governedManuals";

const exec = promisify(execFile), root = process.cwd();
const releaseId = "APPLIANCES-GOVERNED-EXACT-MANUAL-L9-TR-v0.1";
const output = path.join(root,"data/production/appliances/manuals/releases",releaseId);
const python = process.env.CODEX_PYTHON_PATH ?? "/Users/serdarakgul/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3";
const now = process.env.MANUAL_RETRIEVED_AT ?? "2026-09-04T12:00:00.000Z";
type RawProduct={productId:string;brand?:string;model?:string;configurationIdentity?:string;identity?:{brandId?:string;manufacturerModelIdentifier?:string;configurationIdentity?:string}};
type Candidate={member:ManualInventoryMember;sourceId:string;url:string;code:string};

const hashHex=(v:string)=>createHash("sha256").update(v).digest("hex");
const directPdf=(url:string)=>/\.pdf(?:$|\?)/iu.test(url);
const categoryPriority=(id:string)=>id==="SPLIT_AIR_CONDITIONER"?0:id.includes("WATER_HEATER")?1:["BUILT_IN_OVEN","FREESTANDING_COOKER","HOB","RANGE_HOOD","BUILT_IN_MICROWAVE_OVEN"].includes(id)?2:3;
const identityAliases=(model:string)=>{const compact=model.toUpperCase().replace(/[^A-Z0-9]/gu,"");const tokens=model.toUpperCase().match(/[A-Z]+\s*[-/]?\s*\d+[A-Z0-9.-]*/gu)?.map(x=>x.replace(/[^A-Z0-9]/gu,""))??[];const exactCodes=model.toUpperCase().match(/[A-Z]{1,8}\s*[-/]?\s*\d{2,}/gu)?.map(x=>x.replace(/[^A-Z0-9]/gu,""))??[];return [...new Set([compact,...tokens,...exactCodes].filter(x=>x.length>=4))].sort((a,b)=>a.length-b.length);};
const recipes:Readonly<Record<string,readonly {needle:string;statement:string;kind:L9Knowledge["knowledgeKind"];professional:boolean}[]>>={
 ARZUM_AR012_LAGUNA_TR:[{needle:"topraklı",statement:"Elektrik bağlantısı koruyucu topraklama gerektirir; kurulum ve bağlantı uygun yetkinlikte profesyonel tarafından doğrulanmalıdır.",kind:"INSTALLATION",professional:true},{needle:"susuz",statement:"Cihaz susuz çalıştırılmamalıdır; devreye alma sırası exact kılavuza göre uygulanmalıdır.",kind:"SAFETY",professional:true}],
 BEKO_KMX_82_TR:[{needle:"filtre",statement:"Tiftik filtresi kılavuzda tarif edilen bakım düzeninde temizlenmelidir; bakım öncesinde cihaz güvenli duruma alınmalıdır.",kind:"MAINTENANCE",professional:false}],
 BOSCH_WQG24100TR:[{needle:"Tiftik filtresi",statement:"Tiftik filtresi kılavuzdaki prosedüre göre düzenli temizlenmelidir; bu bilgi kurutma sonucu veya bakım sıklığı garantisi değildir.",kind:"MAINTENANCE",professional:false}],
 ARZUM_OK004_0400_TR:[{needle:"sıcak",statement:"Pişirme sırasında sıcak yüzey ve buhar riski vardır; cihaz exact kılavuzdaki güvenli kullanım ve temizlik adımlarına göre kullanılmalıdır.",kind:"SAFETY",professional:false}],
 ARCELIK_K3300_TFF_TR:[{needle:"temiz",statement:"Temizlikten önce cihazın enerjisi kesilmeli ve exact kılavuzdaki temizlik sınırları izlenmelidir.",kind:"MAINTENANCE",professional:false}],
};

async function inventory():Promise<{members:ManualInventoryMember[];candidates:Candidate[]}>{
 const base=path.join(root,"data/production/appliances"),members:ManualInventoryMember[]=[],candidates:Candidate[]=[];
 for(const slug of (await readdir(base)).sort()){
  const activePath=path.join(base,slug,"active.json"); let active:any; try{active=JSON.parse(await readFile(activePath,"utf8"));}catch{continue;} if(!active.releaseVersion)continue;
  const releaseDir=path.join(base,slug,"releases",active.releaseVersion); let raw="",doc:any,file="";
  for(const name of ["domain-pack.json","catalog.json"]){try{file=path.join(releaseDir,name);raw=await readFile(file,"utf8");doc=JSON.parse(raw);break;}catch{}}
  if(!doc)continue; const products:RawProduct[]=doc.products??[]; const categoryId=doc.productType??doc.manifest?.productType??doc.department?.productType??(doc.schemaVersion?.includes("WASHING_MACHINE")?"WASHING_MACHINE":undefined)??(products[0] as any)?.identity?.productType;
  const parentSha=hashHex(raw), sources:any[]=doc.sources??[], assertions:any[]=doc.assertions??doc.evidenceAssertions??[];
  const manualSources=sources.filter(s=>/MANUAL/iu.test(String(s.authority??s.sourceType??s.kind??""))||/MANUAL/iu.test(String(s.sourceId??""))).map(s=>({sourceId:String(s.sourceId),url:String(s.url??s.canonicalReference??s.uri),kind:directPdf(String(s.url??s.canonicalReference??s.uri))?"DIRECT_PDF" as const:"SUPPORT_INDEX" as const}));
  for(const p of products){const productId=p.productId, model=p.model??p.identity?.manufacturerModelIdentifier??productId, refs=new Set<string>((p as any).evidenceRefs??assertions.filter(a=>a.productId===productId).map(a=>a.sourceId));const discovered=manualSources.filter(s=>refs.has(s.sourceId));const member={categoryId,productId,brand:p.brand??p.identity?.brandId??"UNKNOWN",model,configurationIdentity:p.configurationIdentity??p.identity?.configurationIdentity??model,parentRelease:active.releaseVersion,parentArtifactSha256:parentSha,discoveredManuals:discovered};members.push(member);for(const source of discovered)if(source.kind==="DIRECT_PDF")candidates.push({member,sourceId:source.sourceId,url:source.url,code:model});}
 }
 members.sort((a,b)=>a.categoryId.localeCompare(b.categoryId)||a.productId.localeCompare(b.productId));candidates.sort((a,b)=>categoryPriority(a.member.categoryId)-categoryPriority(b.member.categoryId)||a.member.productId.localeCompare(b.member.productId));return{members,candidates};
}

async function extractPdf(bytesPath:string):Promise<string>{
 const code="import pdfplumber,sys\nwith pdfplumber.open(sys.argv[1]) as p:\n print('\\f'.join((x.extract_text(x_tolerance=2,y_tolerance=3) or '') for x in p.pages),end='')";
 const {stdout}=await exec(python,["-c",code,bytesPath],{maxBuffer:50*1024*1024});return stdout;
}

async function main(){
 const {members,candidates}=await inventory(), manuals:GovernedManual[]=[],blockers:ManualBlocker[]=[],knowledge:L9Knowledge[]=[];await mkdir(path.join(output,"bytes"),{recursive:true});await mkdir(path.join(output,"text"),{recursive:true});
 for(const member of members)if(!member.discoveredManuals.length)blockers.push({categoryId:member.categoryId,productId:member.productId,code:"NO_MANUAL_IDENTIFIER",retryable:true,detail:"No official manual URL or support identifier is bound to this exact catalog member."});else for(const source of member.discoveredManuals)if(source.kind==="SUPPORT_INDEX")blockers.push({categoryId:member.categoryId,productId:member.productId,sourceUrl:source.url,code:"SUPPORT_INDEX_DYNAMIC",retryable:true,detail:"Official support index requires a separately resolved immutable PDF URL."});
 await Promise.all(candidates.map(async candidate=>{
  try{validateOfficialManualUrl(candidate.url);const response=await fetch(candidate.url,{redirect:"follow",signal:AbortSignal.timeout(30000),headers:{"user-agent":"Expiya-Governed-Manual-Acquisition/1.0"}});if(!response.ok)throw new Error(`HTTP_${response.status}`);const contentType=response.headers.get("content-type")?.split(";")[0].trim()??"unknown",bytes=new Uint8Array(await response.arrayBuffer());if(bytes.length<5||new TextDecoder().decode(bytes.slice(0,5))!=="%PDF-"){blockers.push({categoryId:candidate.member.categoryId,productId:candidate.member.productId,sourceUrl:candidate.url,code:"NON_PDF_RESPONSE",retryable:true,detail:`Response was ${contentType}, ${bytes.length} bytes.`});return;}
   const artifact=sha256(bytes), key=artifact.slice(7,23), bytesRel=`bytes/${key}.pdf`,textRel=`text/${key}.txt`,bytesPath=path.join(output,bytesRel);await writeFile(bytesPath,bytes);let text="";try{text=await extractPdf(bytesPath);}catch(error){blockers.push({categoryId:candidate.member.categoryId,productId:candidate.member.productId,sourceUrl:candidate.url,code:"NON_EXTRACTABLE",retryable:false,detail:String(error)});return;}const pages=splitExtractedPages(text);if(!text.trim()||!pages.length){blockers.push({categoryId:candidate.member.categoryId,productId:candidate.member.productId,sourceUrl:candidate.url,code:"NON_EXTRACTABLE",retryable:false,detail:"PDF yielded no searchable text."});return;}const provenCode=identityAliases(candidate.code).find(alias=>proveExactIdentity(pages,alias));if(!provenCode){blockers.push({categoryId:candidate.member.categoryId,productId:candidate.member.productId,sourceUrl:candidate.url,code:"IDENTITY_MISMATCH",retryable:true,detail:`No exact product-code alias from ${candidate.code} was found in extracted document text.`});return;}const identityLocator=proveExactIdentity(pages,provenCode)!;await writeFile(path.join(output,textRel),text,"utf8");const admitted={manualId:`APPL-MANUAL-${key.toUpperCase()}`,sourceId:candidate.sourceId,sourceUrl:candidate.url,retrievedAt:now,contentType,byteLength:bytes.length,artifactSha256:artifact,textArtifactSha256:sha256(text),categoryId:candidate.member.categoryId,productId:candidate.member.productId,exactProductCode:provenCode,identityLocator,pageCount:pages.length,language:"tr-TR",immutableBytesPath:bytesRel,immutableTextPath:textRel} satisfies GovernedManual;manuals.push(admitted);for(const [index,recipe] of (recipes[admitted.productId]??[]).entries()){const pageIndex=pages.findIndex(page=>page.toLocaleLowerCase("tr-TR").includes(recipe.needle.toLocaleLowerCase("tr-TR")));if(pageIndex>=0)knowledge.push({knowledgeId:`L9-${key.toUpperCase()}-${index+1}`,manualId:admitted.manualId,categoryId:admitted.categoryId,productId:admitted.productId,statement:recipe.statement,locator:{page:pageIndex+1,section:recipe.needle},knowledgeKind:recipe.kind,decisionAuthority:"NONE",candidateEffect:"NONE",professionalInstallationRequired:recipe.professional,publicSourceDisclosure:`${candidate.member.brand} ${candidate.member.model} üretici kullanım kılavuzu`});}
  }catch(error){blockers.push({categoryId:candidate.member.categoryId,productId:candidate.member.productId,sourceUrl:candidate.url,code:"DOWNLOAD_FAILED",retryable:true,detail:error instanceof Error?error.message:String(error)});}
 }));
 const duplicate=new Map<string,GovernedManual>();for(const m of manuals){const prior=duplicate.get(m.artifactSha256);if(prior&&prior.productId!==m.productId)blockers.push({categoryId:m.categoryId,productId:m.productId,sourceUrl:m.sourceUrl,code:"DUPLICATE_BYTES_DIFFERENT_IDENTITY",retryable:false,detail:`Same bytes already admitted for ${prior.productId}; both records excluded from L9 pending exact multi-model review.`});else duplicate.set(m.artifactSha256,m);}
 manuals.sort((a,b)=>a.categoryId.localeCompare(b.categoryId)||a.productId.localeCompare(b.productId));knowledge.sort((a,b)=>a.productId.localeCompare(b.productId)||a.knowledgeId.localeCompare(b.knowledgeId));blockers.sort((a,b)=>a.categoryId.localeCompare(b.categoryId)||a.productId.localeCompare(b.productId)||a.code.localeCompare(b.code));
 const release=finalizeRelease({schemaVersion:"appliances-governed-manual-release/v1",releaseId,generatedAt:now,lifecycle:"FROZEN_READ_ONLY",authority:"L9_ADVISOR_ONLY",parentPolicy:"IMMUTABLE_NO_OVERWRITE",inventoryDigest:sha256(stableJson(members)),members,manuals,l9AdvisorKnowledge:knowledge,blockers,boundaries:{candidateEligibility:"NONE",scoring:"NONE",sufficiency:"NONE",recommendation:"NONE",y:"NONE",absenceTreatment:"NEUTRAL",crossProductPromotion:"FORBIDDEN"}});const issues=validateRelease(release);if(issues.length)throw new Error(`RELEASE_INVALID:${issues.join(",")}`);const releaseRaw=stableJson(release),coverageRaw=stableJson({schemaVersion:"appliances-manual-coverage/v1",releaseId,totalMembers:members.length,categories:[...new Set(members.map(x=>x.categoryId))].sort().map(categoryId=>({categoryId,members:members.filter(x=>x.categoryId===categoryId).length,manuals:manuals.filter(x=>x.categoryId===categoryId).length,l9Entries:knowledge.filter(x=>x.categoryId===categoryId).length,blockers:blockers.filter(x=>x.categoryId===categoryId).length})),manualCount:manuals.length,l9EntryCount:knowledge.length,blockerCount:blockers.length,next:"WU-XPY-APPL-GOVERNED-MEDIA-PHOTO-ACQUISITION-01"});await writeFile(path.join(output,"release.json"),releaseRaw);await writeFile(path.join(output,"coverage.json"),coverageRaw);await writeFile(path.join(output,"manifest.json"),stableJson({schemaVersion:"appliances-governed-manual-manifest/v1",releaseId,lifecycle:"FROZEN_READ_ONLY",releaseArtifactSha256:sha256(releaseRaw),coverageArtifactSha256:sha256(coverageRaw),manualArtifacts:manuals.map(x=>({manualId:x.manualId,artifactSha256:x.artifactSha256,textArtifactSha256:x.textArtifactSha256})),parentPolicy:"IMMUTABLE_NO_OVERWRITE",next:"WU-XPY-APPL-GOVERNED-MEDIA-PHOTO-ACQUISITION-01"}));console.log(JSON.stringify({releaseId,members:members.length,categories:new Set(members.map(x=>x.categoryId)).size,candidates:candidates.length,manuals:manuals.length,blockers:blockers.length}));
}
void main();
