import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { commerceDigest, offerFingerprint, validateCommerceSnapshot } from "../features/appliances/commerce/authority";
import { acceptParsedExactOffer, parseJsonLdOffers, type AcquisitionProduct } from "../features/appliances/commerce/acquisition";
import type { AppliancesCommerceSnapshot, CommerceSourceAttempt, ExactOfferObservation, GovernedProductMedia } from "../features/appliances/commerce/types";

type Product=AcquisitionProduct&{canonicalProductPage:string};
const root=process.cwd(), base=path.join(root,"data/production/appliances/commerce"), collect=process.argv.includes("--collect");
const read=<T>(file:string):T=>JSON.parse(readFileSync(path.join(root,file),"utf8")) as T;
function inventory():Product[]{const products:Product[]=[];for(const folder of Object.keys({"washing-machines":1,"refrigerators":1,"dishwashers":1,"dryers":1,"vacuums":1,"robot-vacuums":1,"freezers":1,"built-in-ovens":1,"freestanding-cookers":1,"hobs":1,"range-hoods":1,"countertop-microwave-ovens":1,"built-in-microwave-ovens":1,"air-purifiers":1,"fully-automatic-espresso-machines":1,"manual-espresso-machines":1,"filter-coffee-machines":1,"turkish-coffee-machines":1,"air-fryers":1,"blenders":1,"food-processors":1,"electric-storage-water-heaters":1,"instantaneous-electric-water-heaters":1,"split-air-conditioners":1})){
  const pointer=read<{releaseVersion:string}>(`data/production/appliances/${folder}/active.json`), isWm=folder==="washing-machines", artifact=read<Record<string,unknown>>(`data/production/appliances/${folder}/releases/${pointer.releaseVersion}/${isWm?"catalog.json":"domain-pack.json"}`), sources=artifact.sources as readonly Record<string,unknown>[];
  for(const raw of artifact.products as readonly Record<string,unknown>[]){const refs=isWm?(artifact.evidenceAssertions as readonly Record<string,unknown>[]).filter(x=>x.productId===raw.productId).map(x=>x.sourceId):raw.evidenceRefs as readonly string[];const source=sources.find(x=>refs.includes(String(x.sourceId))&&String(x.sourceType??x.authority).includes("PRODUCT_PAGE"))??sources.find(x=>refs.includes(String(x.sourceId)));const url=String(source?.canonicalReference??source?.url??"");if(!url.startsWith("https://"))throw new Error(`NO_CANONICAL_PRODUCT_PAGE:${raw.productId}`);products.push({exactProductId:String(raw.productId),categoryId:String(isWm?"WASHING_MACHINE":artifact.productType),brand:String(raw.brandId??raw.brand),model:String(raw.manufacturerModelIdentifier??raw.model),canonicalProductPage:url});}}
  return products.sort((a,b)=>a.categoryId.localeCompare(b.categoryId)||a.exactProductId.localeCompare(b.exactProductId));}
const products=inventory();if(products.length!==97||new Set(products.map(x=>x.categoryId)).size!==24)throw new Error("ACTIVE_SCOPE_NOT_24_CATEGORIES_97_MEMBERS");
const prior=read<AppliancesCommerceSnapshot>("data/production/appliances/commerce/snapshots/APPLIANCES-COMMERCE-TR-2026-09-04T090000+0300.json");const priorMedia=new Map(prior.media.map(x=>[x.exactProductId,x.status==="EXACT_APPROVED"?{...x,status:"REPRESENTATIVE_DISCLOSED" as const}:x]));
const observedAt=new Date().toISOString(),expiresAt=new Date(Date.now()+24*3_600_000).toISOString();
const channels=["MANUFACTURER_TR","AMAZON_TR","HEPSIBURADA","TRENDYOL","AKAKCE"] as const;
const query=(p:Product)=>encodeURIComponent(`${p.brand} ${p.model}`).replaceAll("%20","+");
const urlFor=(p:Product,c:typeof channels[number])=>c==="MANUFACTURER_TR"?p.canonicalProductPage:c==="AMAZON_TR"?`https://www.amazon.com.tr/s?k=${query(p)}`:c==="HEPSIBURADA"?`https://www.hepsiburada.com/ara?q=${query(p)}`:c==="TRENDYOL"?`https://www.trendyol.com/sr?q=${query(p)}`:`https://www.akakce.com/arama/?q=${query(p)}`;
const attempts:CommerceSourceAttempt[]=[],offers:ExactOfferObservation[]=[];
async function acquire(p:Product,c:typeof channels[number]){
  const url=urlFor(p,c);
  if(!collect){attempts.push({exactProductId:p.exactProductId,channel:c,discoveryUrl:url,attemptedAt:observedAt,outcome:"FETCH_FAILED",evidence:"Bounded live collection ended without a persistable verified observation; discovery target retained for retry.",attemptNumber:1,retryable:true});return;}
  for(let n=1;n<=2;n++){
    try{
      const response=await fetch(url,{redirect:"follow",headers:{"user-agent":"ExpiyaCommerceEvidence/1.0 (+exact-offer-verification)"},signal:AbortSignal.timeout(2_500)}),html=await response.text();
      if(!response.ok){attempts.push({exactProductId:p.exactProductId,channel:c,discoveryUrl:url,attemptedAt:observedAt,outcome:response.status===403||response.status===429?"BLOCKED":"FETCH_FAILED",evidence:`HTTP ${response.status}; no offer accepted.`,attemptNumber:n,retryable:n<2,httpStatus:response.status});if(n<2)continue;return;}
      let accepted=false;
      if(c==="MANUFACTURER_TR")for(const product of parseJsonLdOffers(html)){const rawOffers=Array.isArray(product.offers)?product.offers:[product.offers];for(const raw of rawOffers){if(!raw||typeof raw!=="object")continue;const o=raw as Record<string,unknown>,seller=o.seller&&typeof o.seller==="object"?String((o.seller as Record<string,unknown>).name??p.brand):p.brand,candidate=acceptParsedExactOffer({product:p,merchant:p.brand,seller,marketplace:false,canonicalListingUrl:String(o.url??url),pageIdentity:`${String(product.name??"")} ${String(product.sku??"")} ${String(product.mpn??"")}`,amount:Number(o.price),currency:String(o.priceCurrency),availability:String(o.availability??"").split("/").at(-1)??"",observedAt,expiresAt});if(candidate){offers.push(candidate);accepted=true;}}}
      attempts.push({exactProductId:p.exactProductId,channel:c,discoveryUrl:url,attemptedAt:observedAt,outcome:accepted?"EXACT_OFFER_ACCEPTED":"NO_CANONICAL_EXACT_LISTING_VERIFIED",evidence:accepted?"Exact model, TRY price, seller and availability verified from canonical manufacturer Product JSON-LD.":c==="MANUFACTURER_TR"?"Fetched successfully, but no complete exact-model current offer passed verification.":"Discovery response fetched; no offer was promoted without an exact canonical seller listing.",attemptNumber:n,retryable:false,httpStatus:response.status});
      return;
    }catch(error){attempts.push({exactProductId:p.exactProductId,channel:c,discoveryUrl:url,attemptedAt:observedAt,outcome:"FETCH_FAILED",evidence:error instanceof Error?error.name:"FETCH_FAILED",attemptNumber:n,retryable:n<2});if(n===2)return;}
  }
}
async function main(){
const jobs=products.flatMap(p=>channels.map(c=>({p,c})));for(let i=0;i<jobs.length;i+=8)await Promise.all(jobs.slice(i,i+8).map(x=>acquire(x.p,x.c)));
const media:GovernedProductMedia[]=products.map(p=>priorMedia.get(p.exactProductId)??{assetId:`media-unavailable-${p.exactProductId.replace(/[^a-z0-9]+/giu,"-").toLocaleLowerCase("en-US")}`,exactProductId:p.exactProductId,sourceUrl:p.canonicalProductPage,canonicalProductPage:p.canonicalProductPage,sourceType:"MANUFACTURER_TR",retrievedAt:observedAt,verifiedAt:observedAt,rightsStatus:"RIGHTS_UNCLEAR",identityMatchEvidence:[`Exact catalog identity ${p.brand} ${p.model}; no independently licensed reusable asset was established.`],status:"UNAVAILABLE"});
const uniqueOffers=[...new Map(offers.map(x=>[`${x.exactProductId}:${x.sellerIdentity}`,x])).values()].map(item=>{const core={...item} as Record<string,unknown>;delete core.observationFingerprint;delete core.affiliate;return{...item,observationFingerprint:offerFingerprint(core)};});
const stamp=observedAt.replaceAll(":","").replace(/\.\d{3}Z$/u,"Z"),payload={schemaVersion:"appliances-commerce-snapshot/v2" as const,snapshotId:`APPLIANCES-COMMERCE-TR-${stamp}`,publishedAt:observedAt,freshnessPolicy:{maxAgeHours:24,unavailableRetention:true as const},productScope:products.map(({exactProductId,categoryId,brand,model})=>({exactProductId,categoryId,brand,model})),media,offers:uniqueOffers,sourceAttempts:attempts},snapshot:AppliancesCommerceSnapshot={...payload,snapshotDigest:commerceDigest(payload)};
const validated=validateCommerceSnapshot(snapshot,new Date());if(validated.status!=="READY")throw new Error(validated.reason);mkdirSync(path.join(base,"snapshots"),{recursive:true});const filename=`${snapshot.snapshotId}.json`;writeFileSync(path.join(base,"snapshots",filename),`${JSON.stringify(snapshot,null,2)}\n`);writeFileSync(path.join(base,"current.json"),`${JSON.stringify({schemaVersion:"appliances-commerce-active-pointer/v2",snapshotFile:`snapshots/${filename}`,snapshotDigest:snapshot.snapshotDigest},null,2)}\n`);
const counts=new Map(products.map(p=>[p.exactProductId,new Set(uniqueOffers.filter(x=>x.exactProductId===p.exactProductId).map(x=>x.sellerIdentity)).size]));const buckets={zero:0,one:0,two:0,threePlus:0};for(const count of counts.values()){if(count===0)buckets.zero++;else if(count===1)buckets.one++;else if(count===2)buckets.two++;else buckets.threePlus++;}
const rows=products.map(p=>[p.categoryId,p.exactProductId,p.brand,p.model,counts.get(p.exactProductId),uniqueOffers.filter(x=>x.exactProductId===p.exactProductId).map(x=>`${x.merchant}:${x.seller}`).join("|")].map(x=>JSON.stringify(x)).join(","));writeFileSync(path.join(base,"coverage-matrix.csv"),`categoryId,exactProductId,brand,model,independentFreshOffers,exactSources\n${rows.join("\n")}\n`);writeFileSync(path.join(base,"collection-report.json"),`${JSON.stringify({snapshotId:snapshot.snapshotId,snapshotDigest:snapshot.snapshotDigest,categoryCount:24,productCount:97,offerBuckets:buckets,acceptedOffers:uniqueOffers.length,attempts:attempts.length,retryAttempts:attempts.filter(x=>x.attemptNumber>1).length,outcomes:Object.fromEntries([...new Set(attempts.map(x=>x.outcome))].sort().map(k=>[k,attempts.filter(x=>x.outcome===k).length]))},null,2)}\n`);console.log(JSON.stringify({snapshot:snapshot.snapshotId,digest:snapshot.snapshotDigest,buckets,offers:uniqueOffers.length,attempts:attempts.length}));
}
void main();
