import { readFile, rename, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { buildModelFamilyIndexes } from "@/features/decision/v2/catalog/familyIndex";
import { buildCatalogSnapshot } from "@/features/decision/v2/catalog/snapshot";
import type { CatalogVariantSnapshot } from "@/features/decision/v2/catalog/types";
import { parseTechnicalDailyLifeLayer } from "@/features/vehicle-data/technicalDailyLifeSchema";
import { assertTechnicalDailyLifeCompatibility, sha256Text } from "@/features/vehicle-data/validateTechnicalDailyLifeLayer";
import { validateVehiclePersonaSafeTraitRelease, vehiclePersonaSafeTraitManifestSchema, vehiclePersonaSafeTraitPointerSchema, vehiclePersonaSafeTraitReleaseSchema } from "@/features/vehicle-data/vehiclePersonaSafeTraits";
import { validateProductionCatalogActivation, validateProductionCatalogRelease } from "@/features/vehicle-data/productionCatalogRelease";
import type { ProductionCatalogActivation, ProductionCatalogReleaseManifest, ProductionCatalogReleasePayload } from "@/features/vehicle-data/productionCatalogRelease";

const ROOT=process.cwd(),CATALOG="0.55.1",TDL="v2.1-0.55.1-2026-08-16-compatibility-rebind",PERSONA="v1.0.2-catalog-v0.55.1-2026-08-16",ACTIVATED_AT="2026-08-16T19:33:14.000Z";
const json=(value:unknown)=>`${JSON.stringify(value,null,2)}\n`;
async function main(){
  const catalogRoot=path.join(ROOT,"data/production/catalog/releases/v0.55.1");const [rawCatalog,rawManifest,facetsRaw]=await Promise.all([readFile(path.join(catalogRoot,"catalog.json"),"utf8"),readFile(path.join(catalogRoot,"manifest.json"),"utf8"),readFile(path.join(catalogRoot,"decision-facets.json"),"utf8")]);const catalog=JSON.parse(rawCatalog) as ProductionCatalogReleasePayload,manifest=JSON.parse(rawManifest) as ProductionCatalogReleaseManifest;
  const catalogPointer:ProductionCatalogActivation={market:"TR",state:"ACTIVE",active_catalog_release_version:CATALOG,catalog_payload_hash:manifest.catalog_payload_hash,activated_at:ACTIVATED_AT,activation_reference:"user-directed-temporal-catalog-correction-v0.55.1",previous_active_release:"0.55.0",rollback_release:"0.3.0"};
  const catalogErrors=[...validateProductionCatalogRelease(catalog,manifest,rawCatalog),...validateProductionCatalogActivation(catalogPointer,manifest)];if(catalogErrors.length)throw new Error(`CATALOG_STACK_ACTIVATION_BLOCKED:${catalogErrors.join(",")}`);
  const snapshot=buildCatalogSnapshot({pointer:catalogPointer,manifest,catalog,decisionFacets:JSON.parse(facetsRaw),now:new Date("2026-08-16T19:33:14.000Z")});if(snapshot.status!=="READY")throw new Error(`CATALOG_NOT_READY_AT_INJECTED_CLOCK:${JSON.stringify(snapshot)}`);

  const tdlRoot=path.join(ROOT,"data/production/technical-daily-life/releases",TDL),[rawTdl,rawTdlManifest]=await Promise.all([readFile(path.join(tdlRoot,"technical-daily-life.json"),"utf8"),readFile(path.join(tdlRoot,"manifest.json"),"utf8")]);const tdl=parseTechnicalDailyLifeLayer(JSON.parse(rawTdl)),tdlManifest=JSON.parse(rawTdlManifest) as {releaseId:string;schemaVersion:number;compatibleCatalogRelease:string;contentChecksum:string};if(tdlManifest.releaseId!==TDL||tdlManifest.compatibleCatalogRelease!=="v0.55.1"||tdlManifest.contentChecksum!==sha256Text(rawTdl))throw new Error("TDL_STACK_ACTIVATION_BLOCKED");assertTechnicalDailyLifeCompatibility({layer:tdl,records:catalog.records,catalogRelease:"v0.55.1",expectedCatalogRelease:"v0.55.1"});const tdlPointer={state:"ACTIVE",activeTechnicalDailyLifeRelease:TDL,compatibleCatalogRelease:"v0.55.1",schemaVersion:1};

  const personaRoot=path.join(ROOT,"data/production/personas/safe-traits/releases",PERSONA),[rawPersona,rawPersonaManifest]=await Promise.all([readFile(path.join(personaRoot,"vehicle-persona-safe-traits.json"),"utf8"),readFile(path.join(personaRoot,"manifest.json"),"utf8")]);const persona=vehiclePersonaSafeTraitReleaseSchema.parse(JSON.parse(rawPersona)),personaManifest=vehiclePersonaSafeTraitManifestSchema.parse(JSON.parse(rawPersonaManifest));const personaPointer=vehiclePersonaSafeTraitPointerSchema.parse({state:"ACTIVE",activeReleaseVersion:PERSONA,compatibleCatalogRelease:"v0.55.1",compatibleCatalogFingerprint:manifest.catalog_payload_hash,payloadSha256:personaManifest.payloadSha256,schemaVersion:"1.1.0"});const catalogVariants=catalog.records.map(({variant})=>({id:variant.id,brand:variant.brand.value,model:variant.model.value})) as CatalogVariantSnapshot[];const catalogFamilies=buildModelFamilyIndexes(catalogVariants).familyIndex.values().map((family)=>({familyId:family.familyId,variantIds:family.variantIds}));const personaErrors=validateVehiclePersonaSafeTraitRelease({release:persona,manifest:personaManifest,pointer:personaPointer,rawPayload:rawPersona,catalogRelease:"v0.55.1",catalogFingerprint:manifest.catalog_payload_hash,catalogVariantIds:catalogVariants.map((variant)=>variant.id),catalogFamilies});if(personaErrors.length)throw new Error(`PERSONA_STACK_ACTIVATION_BLOCKED:${personaErrors.join(",")}`);

  const writes=[
    ["data/production/catalog/active.json",json(catalogPointer)],
    ["data/production/catalog/activeCatalog.generated.ts",`// Generated by scripts/sync-active-production-catalog.ts. Do not edit manually.\nexport { default as activeCatalogPayload } from "./releases/v0.55.1/catalog.json";\nexport { default as activeCatalogManifest } from "./releases/v0.55.1/manifest.json";\nexport { default as activeDecisionFacetPayload } from "./releases/v0.55.1/decision-facets.json";\nexport const activeCatalogReleaseVersion = "0.55.1";\n`],
    ["data/production/technical-daily-life/active.json",json(tdlPointer)],
    ["data/production/technical-daily-life/activeTechnicalDailyLife.generated.ts",`// Generated by scripts/sync-active-technical-daily-life.ts. Do not edit manually.\nexport { default as activeTechnicalDailyLifePayload } from "./releases/${TDL}/technical-daily-life.json";\nexport { default as activeTechnicalDailyLifeManifest } from "./releases/${TDL}/manifest.json";\nexport const activeTechnicalDailyLifeRelease = "${TDL}";\nexport const compatibleTechnicalDailyLifeCatalogRelease = "v0.55.1";\n`],
    ["data/production/personas/safe-traits/active.json",json(personaPointer)],
    ["data/production/personas/safe-traits/activeVehiclePersonaSafeTraits.generated.ts",`// Generated by scripts/sync-active-vehicle-persona-safe-traits.ts. Do not edit manually.\nexport { default as activeVehiclePersonaSafeTraitRelease } from "./releases/${PERSONA}/vehicle-persona-safe-traits.json";\nexport { default as activeVehiclePersonaSafeTraitManifest } from "./releases/${PERSONA}/manifest.json";\nexport const activeVehiclePersonaSafeTraitReleaseVersion = "${PERSONA}";\n`],
  ] as const;
  const originals=new Map<string,string>();for(const[file]of writes)originals.set(file,await readFile(path.join(ROOT,file),"utf8"));const temps=writes.map(([file,content])=>[file,`${path.join(ROOT,file)}.temporal-stack-tmp`,content]as const);
  try{await Promise.all(temps.map(([,tmp,content])=>writeFile(tmp,content,"utf8")));for(const[file,tmp]of temps)await rename(tmp,path.join(ROOT,file))}catch(error){await Promise.all([...originals].map(([file,content])=>writeFile(path.join(ROOT,file),content,"utf8")));await Promise.all(temps.map(([,tmp])=>unlink(tmp).catch(()=>undefined)));throw error}
  console.log(JSON.stringify({status:"ACTIVATED",catalog:{version:"v0.55.1",hash:manifest.catalog_payload_hash},dailyLife:TDL,persona:PERSONA,readyAt:"2026-08-16T19:33:14.000Z"}));
}
void main();
