/* eslint-disable @typescript-eslint/no-explicit-any -- bounded activation validates immutable JSON artifacts */
import { createHash } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { canonicalJson, fingerprint } from "../features/vehicle-data/equipmentVerificationMaterialization";
import { scaleWaveOwnerManifestChecksum } from "../features/vehicle-data/equipmentScaleWaveOwnerManifest";

const ROOT=process.cwd(), RELEASE="v1.5.0-scale-wave-verified-catalog-v0.55.2-2026-08-19", ROLLBACK="v1.4.0-reviewed-associations-catalog-v0.55.2-2026-08-18";
const CANDIDATE=path.join(ROOT,"data/production/equipment-evidence/release-candidates",RELEASE), PRODUCTION=path.join(ROOT,"data/production/equipment-evidence/releases",RELEASE);
const ACTIVE=path.join(ROOT,"data/production/equipment-evidence/active.json"), MODULE=path.join(ROOT,"data/production/equipment-evidence/activeEquipmentEvidence.generated.ts");
const MANIFEST_PATH=path.join(ROOT,"data/production/equipment-evidence/working/EE-PILOT-002/EE-PILOT-002-SCALE-WAVE-001/corrections/EE-PILOT-002-SCALE-WAVE-001-R1/owner-governance/EE-OAM-SCALE-WAVE-001-R1-BYD-NISSAN/approval-manifest.json");
const PAYLOAD_SHA="sha256:5c9ad2d7fa3085b883d04d116bed6ca2bbfb8944e97a81ec590037bc2afd01d2", POINTER_SHA="sha256:39eae2723b0ca4bc38589bc25157326f084ed36f8fa4b6a946c7542d8ea4c98a", MODULE_SHA="sha256:897a1d8d251240b931ebba5d84fa91b0c937687418a6d7aaa2669c2446ee9e09";
const OLD_POINTER="sha256:4ba2ec5ee76a09906092c19446a2b4846015ac5fd8d08708056b413a721ec8ed",OLD_MODULE="sha256:9c5971b14716bc503a649f99790655bdddc02f8513a6e13b6f198749f0166fea",MANIFEST_SHA="sha256:bc7f5af057e55cac8dacbb094286cdc030b70f53433b66b35ba2daa5346ee1f3",ATTESTATION_ID="EE-OAA-1B8DCAC1A60E8F54FDBE",ATTESTATION_SHA="sha256:93534f047314c64c46fc09079c5a212b875535a95a9cd2b6debaf8bd7988428c",AT="2026-08-19T10:00:00.000+03:00";
const STATEMENT=`EQUIPMENT_OWNER_001 olarak
v1.5.0-scale-wave-verified-catalog-v0.55.2-2026-08-19 release candidate’ının
Equipment Evidence active pointer’ına alınmasını onaylıyorum. Release checksum’ı
sha256:5c9ad2d7fa3085b883d04d116bed6ca2bbfb8944e97a81ec590037bc2afd01d2,
beklenen pointer checksum’ı
sha256:39eae2723b0ca4bc38589bc25157326f084ed36f8fa4b6a946c7542d8ea4c98a
ve beklenen generated module checksum’ı
sha256:897a1d8d251240b931ebba5d84fa91b0c937687418a6d7aaa2669c2446ee9e09
olarak doğrulanmıştır. Aktivasyonun SHADOW_AND_EXPLANATION_DISABLED yetkisiyle
yapılmasını kabul ediyorum. Yeni 65 assertion’ın 62 STANDARD + INCLUDED ve
yalnız BYD Dolphin Comfort TR MY2025 exact matrix kapsamındaki 3 NOT_AVAILABLE
+ NOT_OFFERED kayıttan oluştuğunu; Nissan için negatif assertion bulunmadığını
kabul ediyorum. Mevcut 47 Junior assertion için provision mode geriye dönük
varsayılmamasını ve LEGACY_STANDARD_NO_PROVISION_MODE olarak ayrı tutulmasını
kabul ediyorum. Bu aktivasyonun Equipment verisine filtreleme, sıralama, soru
üretme veya kullanıcıya confirmed equipment fact sunma yetkisi vermediğini
kabul ediyorum. Rollback hedefinin
v1.4.0-reviewed-associations-catalog-v0.55.2-2026-08-18 olmasını onaylıyorum.`;
const sha=(x:string|Buffer)=>`sha256:${createHash("sha256").update(x).digest("hex")}`,read=async<T>(f:string)=>JSON.parse(await readFile(f,"utf8")) as T,write=async(f:string,v:unknown)=>writeFile(f,canonicalJson(v));
async function main(){
 const oldPointer=await readFile(ACTIVE,"utf8"),oldModule=await readFile(MODULE,"utf8");if(sha(oldPointer)!==OLD_POINTER||sha(oldModule)!==OLD_MODULE)throw new Error("PRE_ACTIVATION_ACTIVE_STATE_MISMATCH");
 const actor=(await read<any>(path.join(ROOT,"data/production/equipment-evidence/governance/actor-registry.json"))).actors.find((x:any)=>x.actorId==="EQUIPMENT_OWNER_001");if(!actor||actor.status!=="ACTIVE"||actor.scope!=="EQUIPMENT_EVIDENCE_ONLY"||actor.role!=="EQUIPMENT_OWNER_APPROVER")throw new Error("OWNER_ACTOR_INVALID");
 const approvalManifest=await read<any>(MANIFEST_PATH),{manifestChecksum,...manifestPayload}=approvalManifest;if(manifestChecksum!==MANIFEST_SHA||scaleWaveOwnerManifestChecksum(manifestPayload)!==MANIFEST_SHA)throw new Error("APPROVAL_MANIFEST_MISMATCH");
 const candidateRaw=await readFile(path.join(CANDIDATE,"equipment-evidence.json"),"utf8"),candidate=JSON.parse(candidateRaw),result=await read<any>(path.join(CANDIDATE,"materialization-result.json")),attestation=await read<any>(path.join(CANDIDATE,"approval-attestation.json")),events=await read<any[]>(path.join(CANDIDATE,"owner-approval-events.json")),newAssertions=await read<any[]>(path.join(CANDIDATE,"verified-assertion-materializations.json")),newTrims=await read<any[]>(path.join(CANDIDATE,"verified-trim-link-materializations.json"));
 if(sha(candidateRaw)!==PAYLOAD_SHA||result.approvalAttestationId!==ATTESTATION_ID||result.approvalAttestationChecksum!==ATTESTATION_SHA||fingerprint(attestation)!==ATTESTATION_SHA)throw new Error("CANDIDATE_OR_ATTESTATION_MISMATCH");
 const negatives=newAssertions.filter(x=>x.availabilityStatus==="NOT_AVAILABLE");if(events.length!==67||newAssertions.length!==65||newTrims.length!==2||newAssertions.filter(x=>x.availabilityStatus==="STANDARD"&&x.provisionMode==="INCLUDED").length!==62||negatives.length!==3||negatives.some(x=>x.exactVariantId!=="6cb56615-37ef-51a8-9202-a73e59d4e14b"||x.marketApplicability!=="TR"||x.modelYearApplicability.from!==2025)||newAssertions.some(x=>x.exactVariantId==="90e65f94-6fdb-5eea-ad7e-0b4e18435427"&&x.availabilityStatus==="NOT_AVAILABLE"))throw new Error("CANDIDATE_SCOPE_OR_NEGATIVE_EVIDENCE_MISMATCH");
 if(candidate.verifiedAssertions.length!==112||candidate.reviewedAssociations.length!==49||candidate.verifiedTrimLinks.length!==6||candidate.projections.length!==112||candidate.coverage.verifiedAssertionCoverage.exactVariantCount!==4||candidate.coverage.reviewedAssociationOnlyCoverage.exactVariantCount!==2||candidate.coverage.uncoveredCoverage.exactVariantCount!==560||candidate.decisionAuthority!=="SHADOW_AND_EXPLANATION_DISABLED"||candidate.compatibleCatalogRelease!=="v0.55.2"||candidate.compatibleCatalogFingerprint!=="sha256:fd5609adcc0ca3fec0f8c9dc4dd1c903ed5514326bd322eacd4decff5a044f0f")throw new Error("CANDIDATE_COUNTS_AUTHORITY_OR_CATALOG_MISMATCH");
 const pointerRaw=await readFile(path.join(CANDIDATE,"proposed-active-pointer.json"),"utf8"),moduleRaw=await readFile(path.join(CANDIDATE,"proposed-activeEquipmentEvidence.generated.ts.txt"),"utf8");if(sha(pointerRaw)!==POINTER_SHA||sha(moduleRaw)!==MODULE_SHA)throw new Error("PROPOSED_ACTIVE_ARTIFACT_MISMATCH");
 const activationApprovalId=`EE-ACT-${fingerprint({release:RELEASE,statement:STATEMENT}).slice(7,27).toUpperCase()}`,activationAttestation={activationApprovalId,ownerActorId:"EQUIPMENT_OWNER_001",normalizedApprovalStatement:STATEMENT,approvalStatementChecksum:sha(STATEMENT),releaseId:RELEASE,releaseChecksum:PAYLOAD_SHA,expectedPointerChecksum:POINTER_SHA,expectedGeneratedModuleChecksum:MODULE_SHA,rollbackReleaseId:ROLLBACK,decisionAuthority:"SHADOW_AND_EXPLANATION_DISABLED",recordedAt:AT,governancePolicyVersion:"ATOMIC_EQUIPMENT_ACTIVATION_V1"};
 await mkdir(PRODUCTION,{recursive:true});const files=["equipment-evidence.json","manifest.json","approval-attestation.json","approval-statement.txt","owner-approval-events.json","verified-assertion-materializations.json","verified-trim-link-materializations.json","coverage-report.json","availability-provision-distribution.json","projection-report.json","provenance-appendix.json","decision-neutrality-dry-run.json","rollback-plan.json","checksums.json","materialization-result.json"];for(const f of files)await writeFile(path.join(PRODUCTION,f),await readFile(path.join(CANDIDATE,f)));await writeFile(path.join(PRODUCTION,"activation-approval-statement.txt"),STATEMENT+"\n");await write(path.join(PRODUCTION,"activation-attestation.json"),activationAttestation);if(sha(await readFile(path.join(PRODUCTION,"equipment-evidence.json")))!==PAYLOAD_SHA)throw new Error("PRODUCTION_PAYLOAD_MISMATCH");
 const ptmp=`${ACTIVE}.activation-tmp`,mtmp=`${MODULE}.activation-tmp`;try{await writeFile(ptmp,pointerRaw);await writeFile(mtmp,moduleRaw);if(sha(await readFile(ptmp))!==POINTER_SHA||sha(await readFile(mtmp))!==MODULE_SHA)throw new Error("ATOMIC_STAGING_HASH_MISMATCH");await rename(ptmp,ACTIVE);await rename(mtmp,MODULE);if(sha(await readFile(ACTIVE))!==POINTER_SHA||sha(await readFile(MODULE))!==MODULE_SHA)throw new Error("POST_ACTIVATION_HASH_MISMATCH")}catch(error){await writeFile(ACTIVE,oldPointer);await writeFile(MODULE,oldModule);await write(path.join(PRODUCTION,"activation-failure.json"),{status:"FAILED_ROLLED_BACK",errorCode:error instanceof Error?error.message:"UNKNOWN",sanitized:true,rollbackReleaseId:ROLLBACK,occurredAt:AT});throw error}
 const activationResult={status:"ACTIVATED",activationApprovalId,activationApprovalChecksum:fingerprint(activationAttestation),releaseId:RELEASE,releaseChecksum:PAYLOAD_SHA,activePointerChecksum:POINTER_SHA,generatedModuleChecksum:MODULE_SHA,rollbackReleaseId:ROLLBACK,rollbackPointerChecksum:OLD_POINTER,rollbackGeneratedModuleChecksum:OLD_MODULE,evidence:{verifiedAssertions:112,reviewedAssociations:49,verifiedTrimLinks:6,projections:112},coverage:{verifiedAssertion:4,associationOnly:2,uncovered:560,total:566},negativeIsolation:{BYD:3,Nissan:0,Junior:0,Tonale:0,Volvo:0,silentAbsence:0,inconclusiveConversion:0},legacyProvisionMode:"LEGACY_STANDARD_NO_PROVISION_MODE",decisionAuthority:"SHADOW_AND_EXPLANATION_DISABLED",decisionImpact:"ZERO",activatedAt:AT};await write(path.join(PRODUCTION,"activation-result.json"),activationResult);await write(path.join(PRODUCTION,"post-activation-verification.json"),{status:"PASSED",candidateProductionPayloadEqual:true,pointerModuleAtomic:true,adapterBoundaries:{verifiedAssertions:"SEPARATE",reviewedAssociations:"SEPARATE",trimLinks:"SEPARATE",projections:"SEPARATE"},decisionEngineEquipmentImportAuthority:false,publicFactAllowlistExpanded:false,decisionNeutrality:"ZERO",rollbackDryRun:{target:ROLLBACK,pointerChecksum:OLD_POINTER,moduleChecksum:OLD_MODULE,immutableV15Preserved:true,selectionOnly:true}});console.log(JSON.stringify(activationResult,null,2));
}
main().catch(e=>{console.error(e);process.exitCode=1});
