import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { canonicalizeSourceUrl, parseCsv, type Row } from "./vehicle-evidence";

const excelDate="46248";
const quote=(v:string)=>/[",\r\n]/.test(v)?`"${v.replaceAll('"','""')}"`:v;
const serialize=(rows:Row[])=>{const h=Object.keys(rows[0]??{});return [h,...rows.map(r=>h.map(k=>r[k]??""))].map(r=>r.map(quote).join(",")).join("\n")+"\n";};
const pad=(n:number)=>String(n).padStart(6,"0");

async function main(){
 const [dir]=process.argv.slice(2); if(!dir) throw new Error("Usage: apply-scale-batch03 <tables-dir>");
 const names=["models","generations","powertrains","configurations","evidence_facts","equipment","sources","assertions","collection_queue"];
 const t=Object.fromEntries(await Promise.all(names.map(async n=>[n,parseCsv(await readFile(path.join(dir,`${n}.csv`),"utf8"))]))) as Record<string,Row[]>;
 const next=(table:string,field:string,prefix:string)=>`${prefix}-${pad(Math.max(0,...t[table].map(r=>Number(r[field]?.slice(4))||0))+1)}`;
 const add=(table:string,row:Row)=>t[table].push(row);
 const source=(publisher:string,title:string,type:string,url:string,notes:string,authority="A1_OFFICIAL_MARKET")=>{const canonical=canonicalizeSourceUrl(url);const old=t.sources.find(r=>canonicalizeSourceUrl(r.source_url_canonical||r.source_url)===canonical);if(old)return old.source_id;const id=next("sources","source_id","SRC");add("sources",{source_id:id,publisher,source_title:title,source_type:type,source_url:url,market:"TR",publication_date:"",retrieved_at:excelDate,authority_class:authority,source_status:"ACTIVE",notes:`SCALE_BATCH_03; ${notes}`,source_url_canonical:canonical,source_version_label:"observed 2026-08-14",source_observed_at:excelDate,source_content_hash:"",source_snapshot_ref:""});return id;};
 const S={
  vwPolo:source("Volkswagen Türkiye","Polo model ve teknik bilgiler","OFFICIAL_WEB","https://binekarac.vw.com.tr/tr/modeller-fiyatlar/arac-modelleri/yeni-polo.html","Current Turkey model and technical/equipment entry."),
  vwGolf:source("Volkswagen Türkiye","Golf model ve teknik bilgiler","OFFICIAL_WEB","https://binekarac.vw.com.tr/tr/modeller-fiyatlar/arac-modelleri/yeni-golf.html","Current Turkey C-hatch entry."),
  vwTroc:source("Volkswagen Türkiye","Yeni T-Roc 2026","OFFICIAL_WEB","https://binekarac.vw.com.tr/tr/modeller-fiyatlar/arac-modelleri/vw-yeni-t-roc.html","Current 2026 Turkey compact SUV entry."),
  opel:source("Opel Türkiye","MY26 modeller ve teknik özellikler","OFFICIAL_TECH_SPEC","https://www.opel.com.tr/uygulamalar/modeller-ve-teknik-ozellikler.html","Official MY26 technical-document registry."),
  captur:source("Renault Türkiye","Captur techno mild hybrid configurator","OFFICIAL_WEB","https://www.renault.com.tr/hybrid-araclar/captur-e-tech/konfigurator-yeni.html","Exact techno mild hybrid EDC 140 HP Turkey configuration."),
  duster:source("Dacia Türkiye","Dacia ECO-G model range","OFFICIAL_WEB","https://www.dacia.com.tr/dacia-eco-g-serisi.html","Official factory LPG family and Duster presence; exact trim provisional."),
  logan:source("Dacia Türkiye","Yeni Logan","OFFICIAL_WEB","https://www.dacia.com.tr/modeller/yeni-logan.html","Current Turkey Logan Eco-G 120 EDC model and versions."),
  yarisCross:source("Toyota Türkiye","Yaris Cross Hybrid Teknik ve Donanım Mart 2026","OFFICIAL_TECH_SPEC","https://www.toyota.com.tr/content/dam/toyota/nmsc/turkey/cars/e-brosur/yaris-cross/Toyota_YarisCross_TeknikDonanim_2026_03.pdf","Dated Turkey technical/equipment matrix."),
  xtrail:source("Nissan Türkiye","X-Trail e-POWER/e-4ORCE","OFFICIAL_WEB","https://www.nissan.com.tr/modeller/binek-araclar/yeni-x-trail/performans.html","Official Turkey e-POWER/e-4ORCE model evidence; exact trim provisional."),
  sportage:source("Kia Türkiye","Sportage","OFFICIAL_WEB","https://www.kia.com/tr/modeller/sportage/teknik-ozellikler.html","Official Turkey family SUV technical entry; exact HEV trim provisional."),
  peugeot:source("Peugeot Türkiye","Model broşürleri ve teknik belgeler","OFFICIAL_TECH_SPEC","https://www.peugeot.com.tr/hizli-erisim/model-brosurleri.html","Official current Turkey brochure registry; 408 exact powertrain provisional."),
  ec3:source("Citroën Türkiye","Elektrikli ë-C3 MY26 teknik föy","OFFICIAL_TECH_SPEC","https://talep.citroen.com.tr/api/model-pdf?model=c3","Official Turkey technical/equipment PDF."),
  bmw:source("BMW Türkiye","BMW 320i Sedan M Sport 2026","OFFICIAL_WEB","https://bmwnibul.bmw.com.tr/tasarla-ve-rezerve-et/otomobil/%402352084?available=1","Current exact Turkey inventory configuration."),
  t03:source("Leapmotor Türkiye","Leapmotor T03 teknik özellikler","OFFICIAL_WEB","https://leapmotor.com.tr/","Official Turkey distributor technical table.","A1_OFFICIAL_MARKET"),
  torres:source("KGM/SsangYong Türkiye","Torres 2026 kullanıcı el kitabı ve teknik özellikler","OFFICIAL_MANUAL","https://www.ssangyong.com.tr/storage/kataloglar/2026/01/08/695fbb161e122_f8e0eb1b-61fc-40ea-8636-f79fdc00e7fb.pdf","Official Turkey manual verifies powertrain/dimensions; exact trim provisional."),
  volvo:source("Volvo Cars Türkiye","XC60 mild hybrid specifications","OFFICIAL_TECH_SPEC","https://www.volvocars.com/tr/cars/xc60/specifications//","Live Turkey B5 AWD technical and market data."),
  chery:source("Chery Türkiye","Tiggo 7 Pro teknik veri ve donanım broşürü","OFFICIAL_BROCHURE","https://cherytr.com/application/files/4616/9720/1668/TIGGO-7-PRO-YATAY-A4-BROSUR_compressed.pdf","Official Turkey brochure; current exact trim retained provisional.")
 };
 type Spec={brand:string,name:string,body:string,role:string,mix:string,source:string,gen:string,status:string,powers:Array<{name:string,fuel:string,elec:string,cc?:number,kw?:number,ps?:number,torque?:number,trans:string,gears?:number,drive:string,status:string,year?:string,trim:string,official:string,cfgStatus:string}>};
 const specs:Spec[]=[
  {brand:"Volkswagen",name:"Polo",body:"HATCHBACK",role:"B city hatch; urban automatic; first car",mix:"MAINSTREAM",source:S.vwPolo,gen:"Polo current",status:"PROVISIONAL",powers:[{name:"1.0 TSI 95 PS DSG",fuel:"PETROL",elec:"NONE",ps:95,trans:"DCT",gears:7,drive:"FWD",status:"VERIFIED",year:"2026",trim:"Life",official:"Polo Life 1.0 TSI 95 PS DSG",cfgStatus:"PROVISIONAL"}]},
  {brand:"Volkswagen",name:"Golf",body:"HATCHBACK",role:"C-hatch; family; long-distance",mix:"MAINSTREAM",source:S.vwGolf,gen:"Golf current",status:"PROVISIONAL",powers:[{name:"1.5 eTSI 150 PS DSG",fuel:"PETROL",elec:"MHEV",ps:150,trans:"DCT",gears:7,drive:"FWD",status:"PROVISIONAL",year:"2026",trim:"Style",official:"Golf Style 1.5 eTSI 150 PS DSG",cfgStatus:"PROVISIONAL"}]},
  {brand:"Volkswagen",name:"T-Roc",body:"SUV",role:"B/C-SUV; urban family; mainstream alternative",mix:"MAINSTREAM",source:S.vwTroc,gen:"New T-Roc 2026",status:"VERIFIED",powers:[{name:"1.5 eTSI 150 PS DSG",fuel:"PETROL",elec:"MHEV",ps:150,trans:"DCT",gears:7,drive:"FWD",status:"PROVISIONAL",year:"2026",trim:"Life",official:"Yeni T-Roc Life 1.5 eTSI DSG",cfgStatus:"PROVISIONAL"}]},
  {brand:"Opel",name:"Corsa",body:"HATCHBACK",role:"B city hatch; fuel-efficient urban; automatic",mix:"MAINSTREAM",source:S.opel,gen:"Corsa MY26",status:"VERIFIED",powers:[{name:"Hybrid 1.2 145 (136 HP)",fuel:"PETROL",elec:"MHEV",ps:136,trans:"DCT",gears:6,drive:"FWD",status:"VERIFIED",year:"2026",trim:"GS",official:"Corsa Hybrid 1.2 145 (136 HP) GS",cfgStatus:"VERIFIED"}]},
  {brand:"Renault",name:"Captur",body:"SUV",role:"B-SUV; urban automatic; small family",mix:"MAINSTREAM",source:S.captur,gen:"Captur current",status:"VERIFIED",powers:[{name:"1.3 mild hybrid EDC 140 hp",fuel:"PETROL",elec:"MHEV",cc:1332,kw:104,ps:140,torque:245,trans:"DCT",gears:7,drive:"FWD",status:"VERIFIED",year:"2026",trim:"techno",official:"CAPTUR techno mild hybrid EDC 140 hp",cfgStatus:"VERIFIED"}]},
  {brand:"Dacia",name:"Duster",body:"SUV",role:"LPG affordability; rough-road family; camping",mix:"MAINSTREAM",source:S.duster,gen:"New Duster current",status:"PROVISIONAL",powers:[{name:"Eco-G 100",fuel:"LPG",elec:"NONE",ps:100,trans:"MANUAL",gears:6,drive:"FWD",status:"PROVISIONAL",trim:"Expression",official:"Duster Expression Eco-G 100",cfgStatus:"PROVISIONAL"}]},
  {brand:"Dacia",name:"Logan",body:"SEDAN",role:"entry sedan; LPG affordability; practical family",mix:"MAINSTREAM",source:S.logan,gen:"New Logan 2026",status:"VERIFIED",powers:[{name:"Eco-G 120 EDC",fuel:"LPG",elec:"NONE",ps:120,torque:197,trans:"DCT",gears:6,drive:"FWD",status:"VERIFIED",year:"2026",trim:"Journey",official:"Logan Journey Eco-G 120 EDC",cfgStatus:"VERIFIED"}]},
  {brand:"Toyota",name:"Yaris Cross",body:"SUV",role:"B-SUV; HEV city; small family",mix:"MAINSTREAM",source:S.yarisCross,gen:"Yaris Cross Mar 2026",status:"VERIFIED",powers:[{name:"1.5 Hybrid 130 HP e-CVT",fuel:"PETROL",elec:"HEV",cc:1490,kw:96,ps:130,torque:120,trans:"E_CVT",drive:"FWD",status:"VERIFIED",year:"2026",trim:"Hybrid Dream",official:"Yaris Cross Hybrid Dream 1.5 130 HP e-CVT",cfgStatus:"VERIFIED"}]},
  {brand:"Nissan",name:"X-Trail",body:"SUV",role:"7-seat family; HEV AWD; long-distance",mix:"MAINSTREAM",source:S.xtrail,gen:"X-Trail current",status:"PROVISIONAL",powers:[{name:"e-POWER e-4ORCE",fuel:"PETROL",elec:"HEV",trans:"SINGLE_SPEED",drive:"AWD",status:"PROVISIONAL",year:"2026",trim:"Platinum Premium",official:"X-Trail e-POWER e-4ORCE Platinum Premium 7 Koltuk",cfgStatus:"PROVISIONAL"}]},
  {brand:"Kia",name:"Sportage",body:"SUV",role:"mainstream family SUV; HEV AWD",mix:"MAINSTREAM",source:S.sportage,gen:"Sportage current",status:"PROVISIONAL",powers:[{name:"1.6 T-GDI HEV AWD",fuel:"PETROL",elec:"HEV",trans:"AUTOMATIC",gears:6,drive:"AWD",status:"PROVISIONAL",year:"2026",trim:"Prestige",official:"Sportage 1.6 T-GDI HEV Prestige 4x4",cfgStatus:"PROVISIONAL"}]},
  {brand:"Peugeot",name:"408",body:"HATCHBACK",role:"fastback; family practical non-SUV; upper-mainstream",mix:"MAINSTREAM",source:S.peugeot,gen:"408 current",status:"PROVISIONAL",powers:[{name:"Hybrid 145 e-DCS6",fuel:"PETROL",elec:"MHEV",ps:145,trans:"DCT",gears:6,drive:"FWD",status:"PROVISIONAL",year:"2026",trim:"GT",official:"Peugeot 408 GT Hybrid 145 e-DCS6",cfgStatus:"PROVISIONAL"}]},
  {brand:"Citroën",name:"ë-C3",body:"HATCHBACK",role:"affordable urban EV; first EV; city hatch",mix:"MAINSTREAM",source:S.ec3,gen:"ë-C3 MY26",status:"VERIFIED",powers:[{name:"83 kW 44 kWh",fuel:"ELECTRIC",elec:"BEV",kw:83,ps:113,torque:125,trans:"SINGLE_SPEED",drive:"FWD",status:"VERIFIED",year:"2026",trim:"Max",official:"Citroën ë-C3 Max 83 kW 44 kWh MY26",cfgStatus:"VERIFIED"}]},
  {brand:"BMW",name:"320i Sedan",body:"SEDAN",role:"premium non-EV; performance; long-distance",mix:"DISCOVERY",source:S.bmw,gen:"G20 LCI current",status:"VERIFIED",powers:[{name:"320i 170 HP Automatic",fuel:"PETROL",elec:"NONE",cc:1597,ps:170,torque:250,trans:"AUTOMATIC",drive:"RWD",status:"VERIFIED",year:"2026",trim:"M Sport",official:"BMW 320i Sedan M Sport",cfgStatus:"VERIFIED"}]},
  {brand:"Leapmotor",name:"T03",body:"HATCHBACK",role:"affordable urban EV; compact discovery",mix:"DISCOVERY",source:S.t03,gen:"T03 current",status:"VERIFIED",powers:[{name:"55 kW 41 kWh",fuel:"ELECTRIC",elec:"BEV",kw:55,torque:158,trans:"SINGLE_SPEED",drive:"FWD",status:"VERIFIED",trim:"T03",official:"Leapmotor T03 55 kW 41 kWh",cfgStatus:"VERIFIED"}]},
  {brand:"KGM",name:"Torres",body:"SUV",role:"rough-road discovery; large family; utility",mix:"DISCOVERY",source:S.torres,gen:"Torres 2026",status:"VERIFIED",powers:[{name:"1.5 GDI Turbo 4x4 Automatic",fuel:"PETROL",elec:"NONE",cc:1497,kw:120,ps:163,torque:280,trans:"AUTOMATIC",drive:"4WD",status:"VERIFIED",year:"2026",trim:"4x4",official:"Torres 1.5 GDI Turbo 4x4 Automatic",cfgStatus:"PROVISIONAL"}]},
  {brand:"Volvo",name:"XC60",body:"SUV",role:"premium family; MHEV AWD; towing",mix:"DISCOVERY",source:S.volvo,gen:"XC60 current",status:"VERIFIED",powers:[{name:"B5 AWD Mild Hybrid",fuel:"PETROL",elec:"MHEV",kw:184,ps:250,torque:360,trans:"AUTOMATIC",drive:"AWD",status:"VERIFIED",year:"2026",trim:"Plus",official:"XC60 B5 AWD Mild Hybrid Plus",cfgStatus:"VERIFIED"}]},
  {brand:"Chery",name:"Tiggo 7 Pro",body:"SUV",role:"discovery family SUV; alternative mainstream",mix:"DISCOVERY",source:S.chery,gen:"Tiggo 7 Pro current",status:"PROVISIONAL",powers:[{name:"1.6 TGDI 183 HP 7DCT",fuel:"PETROL",elec:"NONE",cc:1598,kw:136.5,ps:183,torque:275,trans:"DCT",gears:7,drive:"FWD",status:"VERIFIED",trim:"Excellent",official:"Tiggo 7 Pro Excellent 1.6 TGDI 183 HP 7DCT",cfgStatus:"PROVISIONAL"}]}
 ];
 const refs:Record<string,{g:string;p:string;c:string;s:string}>={};
 for(const s of specs){const m=next("models","model_id","MOD");add("models",{model_id:m,brand:s.brand,model_name:s.name,body_family:s.body,market_relevance_tr:"CURRENT",source_catalog_status:"RESMI_KAYNAKTAN_DERLENDI",legacy_source_id:"SCALE_BATCH_03",notes:`SCALE_BATCH_03 ${s.mix}: ${s.role}.`});const g=next("generations","generation_id","GEN");add("generations",{generation_id:g,model_id:m,generation_name:s.gen,generation_code:"",facelift_status:"UNKNOWN",production_start_year:"",production_end_year:"",market_start_year_tr:"",market_end_year_tr:"",identity_status:s.status,legacy_source_id:"SCALE_BATCH_03",notes:`Identity source ${s.source}.`});for(const p of s.powers){const pid=next("powertrains","powertrain_id","PWR");add("powertrains",{powertrain_id:pid,generation_id:g,marketing_name:p.name,fuel_type:p.fuel,electrification_type:p.elec,engine_displacement_cc:p.cc?.toString()??"",power_kw:p.kw?.toString()??"",power_ps:p.ps?.toString()??"",torque_nm:p.torque?.toString()??"",transmission_type:p.trans,transmission_gears:p.gears?.toString()??"",drivetrain:p.drive,battery_usable_kwh:"",identity_status:p.status,legacy_motor_text:"",notes:`SCALE_BATCH_03 source ${s.source}.`});const c=next("configurations","configuration_id","CFG");add("configurations",{configuration_id:c,generation_id:g,powertrain_id:pid,market:"TR",model_year:p.year??"",trim_name:p.trim,official_configuration_name:p.official,availability_status:"CURRENT",availability_from:"",availability_to:"",configuration_status:p.cfgStatus,legacy_trim_text:"",legacy_source_id:"SCALE_BATCH_03",notes:`Exact applicability follows invariant; source ${s.source}.`});refs[`${s.brand}|${s.name}`]={g,p:pid,c,s:s.source};}}
 const fact=(key:string,subjectType:string,subjectId:string,value:string,unit:string,src:string,context:string,extra:Partial<Row>={})=>{const id=next("evidence_facts","fact_id","FAC");add("evidence_facts",{fact_id:id,subject_type:subjectType,subject_id:subjectId,fact_key:key,value_type:"NUMBER",value,unit,evidence_state:"VERIFIED",measurement_context:context,valid_from_model_year:"2026",valid_to_model_year:"",market:"TR",notes:"SCALE_BATCH_03 P0 evidence.",value_min:"",value_max:"",range_semantics:"NONE",source_value_semantics:"EXACT_SCALAR",source_value_raw:"",soc_start_pct:"",soc_end_pct:"",charge_power_context_kw:"",...extra});add("assertions",{assertion_id:next("assertions","assertion_id","AST"),evidence_type:"TECHNICAL_FACT",evidence_id:id,source_id:src,source_location:context,extraction_method:"MANUAL",verification_status:"VERIFIED",applicability_status:"EXACT",verified_at:excelDate,verified_by:"Codex/web research",notes:"SCALE_BATCH_03 controlled ingest."});};
 const F=(brand:string,name:string)=>refs[`${brand}|${name}`];
 {const x=F("Renault","Captur");for(const [k,v,u] of [["length_mm","4239","mm"],["width_mm","1797","mm"],["height_mm","1575","mm"]])fact(k,"GENERATION",x.g,v,u,x.s,"official configurator dimensions");fact("seats","CONFIGURATION",x.c,"5","count",x.s,"official configurator");fact("official_fuel_consumption_combined","CONFIGURATION",x.c,"5.9","L/100km",x.s,"WLTP combined");}
 {const x=F("Toyota","Yaris Cross");for(const [k,v,u] of [["length_mm","4172","mm"],["width_mm","1765","mm"],["height_mm","1595","mm"],["wheelbase_mm","2560","mm"]])fact(k,"GENERATION",x.g,v,u,x.s,"March 2026 technical PDF");fact("seats","CONFIGURATION",x.c,"5","count",x.s,"official specs");fact("cargo_volume_l","CONFIGURATION",x.c,"397","L",x.s,"rear seats upright");fact("official_fuel_consumption_combined","CONFIGURATION",x.c,"4.6","L/100km",x.s,"WLTP combined");}
 {const x=F("Citroën","ë-C3");fact("battery_capacity_reported_kwh","POWERTRAIN",x.p,"44","kWh",x.s,"capacity unqualified",{source_value_semantics:"BATTERY_CAPACITY_UNQUALIFIED"});fact("official_electric_range","CONFIGURATION",x.c,"320","km",x.s,"WLTP combined");fact("dc_charge_time_min","CONFIGURATION",x.c,"26","min",x.s,"DC 100 kW 20-80%",{soc_start_pct:"20",soc_end_pct:"80",charge_power_context_kw:"100",source_value_semantics:"CHARGE_TIME_WITH_SOC_CONTEXT"});}
 {const x=F("BMW","320i Sedan");for(const [k,v,u] of [["length_mm","4713","mm"],["width_mm","1827","mm"],["height_mm","1440","mm"]])fact(k,"GENERATION",x.g,v,u,x.s,"current inventory technical data");fact("official_fuel_consumption_combined","CONFIGURATION",x.c,"7.3","L/100km",x.s,"current inventory average");}
 {const x=F("Leapmotor","T03");for(const [k,v,u] of [["length_mm","3620","mm"],["width_mm","1652","mm"],["height_mm","1577","mm"],["wheelbase_mm","2400","mm"],["ground_clearance_mm","140","mm"]])fact(k,"GENERATION",x.g,v,u,x.s,"official distributor technical table");fact("seats","CONFIGURATION",x.c,"4","count",x.s,"official technical table");fact("cargo_volume_l","CONFIGURATION",x.c,"210","L",x.s,"official technical table");fact("battery_capacity_reported_kwh","POWERTRAIN",x.p,"41","kWh",x.s,"reported capacity",{source_value_semantics:"BATTERY_CAPACITY_UNQUALIFIED"});fact("official_electric_range","CONFIGURATION",x.c,"258","km",x.s,"WLTP combined");fact("dc_charge_time_min","CONFIGURATION",x.c,"36","min",x.s,"DC 30-80%",{soc_start_pct:"30",soc_end_pct:"80",source_value_semantics:"CHARGE_TIME_WITH_SOC_CONTEXT"});}
 {const x=F("KGM","Torres");for(const [k,v,u] of [["length_mm","4700","mm"],["width_mm","1890","mm"],["height_mm","1710","mm"]])fact(k,"GENERATION",x.g,v,u,x.s,"2026 official manual");}
 {const x=F("Volvo","XC60");for(const [k,v,u] of [["length_mm","4708","mm"],["width_mm","1902","mm"],["height_mm","1655","mm"],["wheelbase_mm","2865","mm"]])fact(k,"GENERATION",x.g,v,u,x.s,"live Turkey specifications");for(const [k,v,u] of [["seats","5","count"],["cargo_volume_l","483","L"],["official_fuel_consumption_combined","7.6","L/100km"],["towing_braked_kg","2400","kg"]])fact(k,"CONFIGURATION",x.c,v,u,x.s,"live Turkey B5 AWD specifications");}
 {const x=F("Chery","Tiggo 7 Pro");for(const [k,v,u] of [["length_mm","4500","mm"],["width_mm","1842","mm"],["height_mm","1705","mm"],["wheelbase_mm","2670","mm"]])fact(k,"GENERATION",x.g,v,u,x.s,"official Turkey brochure");}
 for(const r of Object.values(refs)){for(const key of ["identity_exact_configuration","dimensions_core","cargo_volume_l","ground_clearance_mm","efficiency_or_range_core","equipment_mvp_core"]){const cfg=t.configurations.find(x=>x.configuration_id===r.c)!;const complete=key==="identity_exact_configuration"?cfg.configuration_status==="VERIFIED":key==="dimensions_core"?t.evidence_facts.some(x=>x.subject_id===r.g&&x.fact_key==="length_mm"):key==="cargo_volume_l"?t.evidence_facts.some(x=>x.subject_id===r.c&&x.fact_key==="cargo_volume_l"):key==="ground_clearance_mm"?t.evidence_facts.some(x=>x.subject_id===r.g&&x.fact_key==="ground_clearance_mm"):key==="efficiency_or_range_core"?t.evidence_facts.some(x=>x.subject_id===r.c&&["official_fuel_consumption_combined","official_electric_range"].includes(x.fact_key)):false;add("collection_queue",{queue_id:next("collection_queue","queue_id","QUE"),subject_id:r.c,fact_key:key,priority:"P0",collection_status:complete?"COMPLETE":"NOT_STARTED",preferred_source_type:"A1_OFFICIAL_MARKET",assigned_method:"WEB",attempt_count:complete?"1":"0",last_attempt_at:complete?excelDate:"",result:complete?"FOUND":"PENDING",notes:complete?"SCALE_BATCH_03 collected.":"Bounded P0 gap retained; no inference."});}}
 for(const n of names) await writeFile(path.join(dir,`${n}.csv`),serialize(t[n]));
}
main().catch(e=>{console.error(e);process.exitCode=1;});
