import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { canonicalizeSourceUrl, parseCsv, type Row } from "./vehicle-evidence";

const excelDate = "46248";
const quote = (value: string) => /[",\r\n]/.test(value) ? `"${value.replaceAll('"','""')}"` : value;
const serialize = (rows: Row[]) => {
  const headers = Object.keys(rows[0] ?? {});
  return [headers, ...rows.map((row) => headers.map((header) => row[header] ?? ""))].map((row) => row.map(quote).join(",")).join("\n") + "\n";
};
const pad = (n: number) => String(n).padStart(6, "0");

async function main() {
  const [directory] = process.argv.slice(2);
  if (!directory) throw new Error("Usage: apply-scale-batch02 <tables-dir>");
  const names = ["models","generations","powertrains","configurations","evidence_facts","equipment","sources","assertions","collection_queue"];
  const tables = Object.fromEntries(await Promise.all(names.map(async (name) => [name, parseCsv(await readFile(path.join(directory, `${name}.csv`), "utf8"))]))) as Record<string, Row[]>;
  const next = (table: string, field: string, prefix: string) => `${prefix}-${pad(Math.max(0, ...tables[table].map((r) => Number(r[field]?.slice(4)) || 0)) + 1)}`;
  const add = (table: string, row: Row) => tables[table].push(row);

  const sourceByKey = new Map<string,string>();
  for (const row of tables.sources) sourceByKey.set(row.notes?.match(/SCALE_BATCH_02_KEY=([^;]+)/)?.[1] ?? "", row.source_id);
  const source = (key:string,publisher:string,title:string,type:string,url:string,notes:string,authority="A1_OFFICIAL_MARKET") => {
    const existing = sourceByKey.get(key); if (existing) return existing;
    const canonical = canonicalizeSourceUrl(url);
    const duplicate = tables.sources.find((r) => canonicalizeSourceUrl(r.source_url_canonical || r.source_url) === canonical);
    if (duplicate) { sourceByKey.set(key, duplicate.source_id); return duplicate.source_id; }
    const id=next("sources","source_id","SRC");
    add("sources",{source_id:id,publisher,source_title:title,source_type:type,source_url:url,market:"TR",publication_date:"",retrieved_at:excelDate,authority_class:authority,source_status:"ACTIVE",notes:`SCALE_BATCH_02_KEY=${key}; ${notes}`,source_url_canonical:canonical,source_version_label:"observed 2026-08-14",source_observed_at:excelDate,source_content_hash:"",source_snapshot_ref:""});
    sourceByKey.set(key,id); return id;
  };

  const S = {
    hyundaiMarket: source("hyundai-market","Hyundai Motor Türkiye","Hyundai Türkiye güncel model ve konfigürasyon listesi","OFFICIAL_PRICE_LIST","https://kredi.hyundai.com.tr/product/","Current Turkey model/configuration names and model years."),
    bayon: source("bayon","Hyundai Motor Türkiye","BAYON","OFFICIAL_WEB","https://www.hyundai.com/tr/tr/modeller/bayon.html","Current Turkey B-SUV product page."),
    inster: source("inster","Hyundai Motor Türkiye","INSTER Broşürü","OFFICIAL_BROCHURE","https://www.hyundai.com/content/dam/hyundai/downloads/tr/tr/brosurler/inster-brosur.pdf","Turkey brochure with 42/49 kWh configurations, WLTP range, charging and dimensions."),
    ioniq6: source("ioniq6","Hyundai Motor Türkiye","IONIQ 6 performans","OFFICIAL_TECH_SPEC","https://www.hyundai.com/tr/tr/modeller/ioniq6/performans.html","Turkey technical page for 53 kWh RWD and 77.4 kWh AWD."),
    ioniq5n: source("ioniq5n","Hyundai Motor Türkiye","IONIQ 5 N","OFFICIAL_WEB","https://www.hyundai.com/tr/tr/modeller/ioniq5-n.html","Turkey performance EV product page; exact market configuration also in Hyundai market list."),
    ioniq9: source("ioniq9","Hyundai Motor Türkiye","IONIQ 9 performans","OFFICIAL_TECH_SPEC","https://www.hyundai.com/tr/tr/modeller/ioniq9/performans.html","Turkey technical page with RWD/AWD, battery, range and charging."),
    staria: source("staria","Hyundai Motor Türkiye","STARIA Hibrit","OFFICIAL_WEB","https://www.hyundai.com/tr/tr/modeller/staria-hibrit.html","Turkey nine-seat HEV passenger-van product page."),
    santafe: source("santafe","Hyundai Motor Türkiye","SANTA FE Hybrid","OFFICIAL_WEB","https://www.hyundai.com/tr/tr/modeller/santa-fe.html","Turkey large-family AWD HEV product page; exact Progressive configuration in market list."),
    landcruiser: source("landcruiser","Toyota Türkiye","Land Cruiser teknik ve donanım özellikleri 2026","OFFICIAL_TECH_SPEC","https://www.toyota.com.tr/content/dam/toyota/nmsc/turkey/cars/e-brosur/land-cruiser-prado/Land-Cruiser-Prado-Teknik-ve-Donanim-Ozellikleri-2026.pdf","2026 Turkey technical sheet; diesel MHEV, off-road geometry, dimensions and capacity."),
    ranger: source("ranger","Ford Türkiye","Yeni Ford Ranger","OFFICIAL_WEB","https://www.ford.com.tr/ticari-araclar/yeni-ford-ranger","Current Turkey pickup page; exact current configuration remains provisional pending deterministic brochure extraction."),
    berlingo: source("berlingo","Citroën Türkiye","Citroën Berlingo Ocak 2026 teknik föy","OFFICIAL_TECH_SPEC","https://talep.citroen.com.tr/api/model-pdf?model=yeni-berlingo","MY26 passenger van technical and equipment matrix."),
    berlingovan: source("berlingovan","Citroën Türkiye","Citroën Berlingo Van MY26 teknik föy","OFFICIAL_TECH_SPEC","https://talep.citroen.com.tr/api/model-pdf?model=yeni-berlingo-van","MY26 commercial van manual/automatic technical and equipment matrix."),
    sealion7: source("sealion7","BYD Türkiye","BYD SEALION 7 teknik özellikler ve donanım tablosu","OFFICIAL_TECH_SPEC","https://www.bydauto.com.tr/storage/pdf/teknik/byd-sealion-7-teknik-ozellikler-ve-donanim-tablosu-23-01-26.pdf","2026 Turkey two-configuration BEV technical matrix."),
    mini: source("mini-countryman","MINI Türkiye","Tamamen Elektrikli MINI Countryman","OFFICIAL_BROCHURE","https://www.mini.com.tr/content/dam/MINI/marketTR/mini_com_tr/e-brosur/Tamamen_Elektrikli_MINI_Countryman.pdf.asset.1762270931299.pdf","Turkey E and SE ALL4 technical data."),
    peugeot: source("peugeot-3008","Peugeot Türkiye","Peugeot 3008 teknik broşürü","OFFICIAL_TECH_SPEC","https://www.peugeot.com.tr/content/dam/peugeot/turkey/b2c/brosurler/2025/Ekim_3008_Teknik_Brosur.pdf","Turkey multi-powertrain technical brochure; only E-3008 representative ingested."),
    jimny: source("jimny","Suzuki Türkiye","Suzuki Jimny teknik broşürü","OFFICIAL_BROCHURE","https://www.suzuki.com.tr/upi/brosur/jimny.pdf","Turkey technical brochure for 1.5 GLX 4x4 automatic; current exact configuration kept provisional."),
  };

  type Spec={brand:string;name:string;body:string;role:string;discovery:string;source:string;gen:string;genStatus:string;powers:Array<{name:string;fuel:string;elec:string;cc?:number;kw?:number;ps?:number;torque?:number;trans:string;gears?:number;drive:string;status:string;configs:Array<{year:string;trim:string;official:string;status:string}>}>};
  const specs:Spec[]=[
    {brand:"Ford",name:"Ranger",body:"PICKUP",role:"pickup; towing; diesel long-distance; rough-road",discovery:"MAINSTREAM",source:S.ranger,gen:"Current Ranger",genStatus:"PROVISIONAL",powers:[{name:"2.0L EcoBlue 4x4 Automatic",fuel:"DIESEL",elec:"NONE",trans:"AUTOMATIC",gears:10,drive:"4WD",status:"PROVISIONAL",configs:[{year:"2026",trim:"Wildtrak",official:"Ranger Wildtrak 2.0L EcoBlue 4x4 Automatic",status:"PROVISIONAL"}]}]},
    {brand:"Toyota",name:"Land Cruiser Prado",body:"SUV",role:"real 4x4; towing; large family; diesel long-distance",discovery:"MAINSTREAM",source:S.landcruiser,gen:"J250 2026 Mild Hybrid",genStatus:"VERIFIED",powers:[{name:"2.8L D-4D 48V Mild Hybrid 8 A/T",fuel:"DIESEL",elec:"MHEV",cc:2755,kw:151,ps:205,torque:500,trans:"AUTOMATIC",gears:8,drive:"4WD",status:"VERIFIED",configs:[{year:"2026",trim:"Power",official:"Land Cruiser Prado 2.8L D-4D Mild Hybrid Power 8 A/T",status:"VERIFIED"}]}]},
    {brand:"Hyundai",name:"Bayon",body:"SUV",role:"small B-SUV; urban; mainstream price/size bridge",discovery:"MAINSTREAM",source:S.bayon,gen:"Current Bayon",genStatus:"VERIFIED",powers:[{name:"1.0 T-GDI 90 PS 7DCT",fuel:"PETROL",elec:"NONE",ps:90,trans:"DCT",gears:7,drive:"FWD",status:"VERIFIED",configs:[{year:"2026",trim:"Style",official:"BAYON Style 1.0 T-GDI 90 PS 7DCT",status:"VERIFIED"}]}]},
    {brand:"Hyundai",name:"INSTER",body:"HATCHBACK",role:"city hatch; affordable EV; urban EV",discovery:"MAINSTREAM",source:S.inster,gen:"INSTER 2025",genStatus:"VERIFIED",powers:[{name:"42 kWh 71.1 kW",fuel:"ELECTRIC",elec:"BEV",kw:71.1,ps:97,torque:147,trans:"SINGLE_SPEED",drive:"FWD",status:"VERIFIED",configs:[{year:"2025",trim:"Dynamic",official:"INSTER Dynamic 71.1 kW 42 kWh",status:"VERIFIED"}]},{name:"49 kWh 84.5 kW",fuel:"ELECTRIC",elec:"BEV",kw:84.5,ps:115,trans:"SINGLE_SPEED",drive:"FWD",status:"VERIFIED",configs:[{year:"2025",trim:"Advance",official:"INSTER Advance 84.5 kW 49 kWh",status:"VERIFIED"}]}]},
    {brand:"Hyundai",name:"IONIQ 6",body:"SEDAN",role:"long-range EV; efficient fastback; premium alternative",discovery:"DISCOVERY",source:S.ioniq6,gen:"IONIQ 6 current",genStatus:"VERIFIED",powers:[{name:"53 kWh 111 kW RWD",fuel:"ELECTRIC",elec:"BEV",kw:111,ps:151,trans:"SINGLE_SPEED",drive:"RWD",status:"VERIFIED",configs:[{year:"2025",trim:"Advance",official:"IONIQ 6 Advance 111 kW 4x2",status:"VERIFIED"}]}]},
    {brand:"Hyundai",name:"IONIQ 5 N",body:"HATCHBACK",role:"performance EV; AWD; premium alternative",discovery:"DISCOVERY",source:S.ioniq5n,gen:"IONIQ 5 N current",genStatus:"VERIFIED",powers:[{name:"448 kW AWD",fuel:"ELECTRIC",elec:"BEV",kw:448,trans:"SINGLE_SPEED",drive:"AWD",status:"VERIFIED",configs:[{year:"2025",trim:"N",official:"IONIQ 5 N 448 kW 4x4",status:"VERIFIED"}]}]},
    {brand:"Hyundai",name:"IONIQ 9",body:"SUV",role:"large 7-seat SUV; family EV; long-range EV; towing",discovery:"DISCOVERY",source:S.ioniq9,gen:"IONIQ 9 2026",genStatus:"VERIFIED",powers:[{name:"110.3 kWh 160 kW RWD",fuel:"ELECTRIC",elec:"BEV",kw:160,trans:"SINGLE_SPEED",drive:"RWD",status:"VERIFIED",configs:[{year:"2026",trim:"Progressive",official:"IONIQ 9 Progressive 160 kW 4x2",status:"VERIFIED"}]},{name:"110.3 kWh 226.1 kW AWD",fuel:"ELECTRIC",elec:"BEV",kw:226.1,trans:"SINGLE_SPEED",drive:"AWD",status:"VERIFIED",configs:[{year:"2026",trim:"Calligraphy",official:"IONIQ 9 Calligraphy 226.1 kW 4x4",status:"VERIFIED"}]}]},
    {brand:"Hyundai",name:"STARIA HEV",body:"MPV",role:"MPV; passenger van; 9-seat; large family",discovery:"DISCOVERY",source:S.staria,gen:"STARIA Hybrid current",genStatus:"VERIFIED",powers:[{name:"1.6 T-GDI 225 PS HEV 6AT",fuel:"PETROL",elec:"HEV",ps:225,trans:"AUTOMATIC",gears:6,drive:"FWD",status:"VERIFIED",configs:[{year:"2025",trim:"Elite",official:"STARIA HEV Elite 1.6 T-GDI 225 PS AT 4x2",status:"VERIFIED"}]}]},
    {brand:"Hyundai",name:"SANTA FE",body:"SUV",role:"large 7-seat SUV; HEV + AWD; family; towing",discovery:"MAINSTREAM",source:S.santafe,gen:"SANTA FE 2026",genStatus:"VERIFIED",powers:[{name:"1.6 T-GDI HEV AWD AT",fuel:"PETROL",elec:"HEV",trans:"AUTOMATIC",drive:"AWD",status:"VERIFIED",configs:[{year:"2026",trim:"Progressive",official:"SANTA FE 1.6 T-GDI HEV Progressive 4x4 AT",status:"VERIFIED"}]}]},
    {brand:"Citroën",name:"Berlingo",body:"MPV",role:"passenger van; cargo-oriented family; diesel long-distance",discovery:"MAINSTREAM",source:S.berlingo,gen:"Berlingo MY26",genStatus:"VERIFIED",powers:[{name:"1.5 BlueHDi 130 6MT",fuel:"DIESEL",elec:"NONE",cc:1499,ps:130,torque:300,trans:"MANUAL",gears:6,drive:"FWD",status:"VERIFIED",configs:[{year:"2026",trim:"Plus",official:"Berlingo Plus 1.5 BlueHDi 130 6MT",status:"VERIFIED"}]},{name:"1.5 BlueHDi 130 EAT8",fuel:"DIESEL",elec:"NONE",cc:1499,ps:130,torque:300,trans:"AUTOMATIC",gears:8,drive:"FWD",status:"VERIFIED",configs:[{year:"2026",trim:"Max",official:"Berlingo Max 1.5 BlueHDi 130 EAT8",status:"VERIFIED"}]}]},
    {brand:"Citroën",name:"Berlingo Van",body:"VAN",role:"commercial/practical van; cargo",discovery:"MAINSTREAM",source:S.berlingovan,gen:"Berlingo Van MY26",genStatus:"VERIFIED",powers:[{name:"1.5 BlueHDi 130 6MT",fuel:"DIESEL",elec:"NONE",cc:1499,ps:130,torque:300,trans:"MANUAL",gears:6,drive:"FWD",status:"VERIFIED",configs:[{year:"2026",trim:"Van",official:"Berlingo Van 1.5 BlueHDi 130 6MT MY26",status:"VERIFIED"}]},{name:"1.5 BlueHDi 130 EAT8",fuel:"DIESEL",elec:"NONE",cc:1499,ps:130,torque:300,trans:"AUTOMATIC",gears:8,drive:"FWD",status:"VERIFIED",configs:[{year:"2026",trim:"Van",official:"Berlingo Van 1.5 BlueHDi 130 EAT8 MY26",status:"VERIFIED"}]}]},
    {brand:"BYD",name:"SEALION 7",body:"SUV",role:"family EV; long-range EV; performance EV; BEV AWD",discovery:"DISCOVERY",source:S.sealion7,gen:"SEALION 7 2026",genStatus:"VERIFIED",powers:[{name:"71.8 kWh 160 kW RWD",fuel:"ELECTRIC",elec:"BEV",kw:160,ps:218,torque:380,trans:"SINGLE_SPEED",drive:"RWD",status:"VERIFIED",configs:[{year:"2026",trim:"Design",official:"BYD SEALION 7 160 kW Design",status:"VERIFIED"}]},{name:"91.3 kWh 390 kW AWD",fuel:"ELECTRIC",elec:"BEV",kw:390,ps:530,torque:690,trans:"SINGLE_SPEED",drive:"AWD",status:"VERIFIED",configs:[{year:"2026",trim:"Excellence",official:"BYD SEALION 7 390 kW AWD Excellence",status:"VERIFIED"}]}]},
    {brand:"MINI",name:"Countryman Electric",body:"SUV",role:"premium alternative; family EV; BEV AWD",discovery:"DISCOVERY",source:S.mini,gen:"U25 Electric",genStatus:"VERIFIED",powers:[{name:"Countryman E 150 kW",fuel:"ELECTRIC",elec:"BEV",kw:150,ps:204,torque:250,trans:"SINGLE_SPEED",drive:"FWD",status:"VERIFIED",configs:[{year:"2026",trim:"E",official:"Tamamen Elektrikli MINI Countryman E",status:"VERIFIED"}]},{name:"Countryman SE ALL4 230 kW",fuel:"ELECTRIC",elec:"BEV",kw:230,ps:313,torque:494,trans:"SINGLE_SPEED",drive:"AWD",status:"VERIFIED",configs:[{year:"2026",trim:"SE ALL4",official:"Tamamen Elektrikli MINI Countryman SE ALL4",status:"VERIFIED"}]}]},
    {brand:"Peugeot",name:"3008",body:"SUV",role:"family EV; fastback; mainstream premium bridge",discovery:"MAINSTREAM",source:S.peugeot,gen:"New 3008",genStatus:"VERIFIED",powers:[{name:"E-3008 73 kWh 157 kW",fuel:"ELECTRIC",elec:"BEV",kw:157,trans:"SINGLE_SPEED",drive:"FWD",status:"VERIFIED",configs:[{year:"2026",trim:"GT",official:"Peugeot E-3008 GT 157 kW",status:"VERIFIED"}]}]},
    {brand:"Suzuki",name:"Jimny",body:"SUV",role:"real 4x4; compact off-road; rough-road; camping",discovery:"DISCOVERY",source:S.jimny,gen:"Current Jimny",genStatus:"PROVISIONAL",powers:[{name:"1.5 GLX 4x4 Automatic",fuel:"PETROL",elec:"NONE",cc:1462,ps:102,torque:130,trans:"AUTOMATIC",gears:4,drive:"4WD",status:"VERIFIED",configs:[{year:"",trim:"GLX",official:"Jimny 1.5 GLX Benzinli 4x4 Otomatik",status:"PROVISIONAL"}]}]},
  ];

  const refs:Array<{model:string;gen:string;pwr:string;cfg:string;source:string;role:string}> = [];
  for (const spec of specs) {
    const model=next("models","model_id","MOD"); add("models",{model_id:model,brand:spec.brand,model_name:spec.name,body_family:spec.body,market_relevance_tr:"CURRENT",source_catalog_status:"RESMI_KAYNAKTAN_DERLENDI",legacy_source_id:"SCALE_BATCH_02",notes:`SCALE_BATCH_02 ${spec.discovery}: ${spec.role}.`});
    const gen=next("generations","generation_id","GEN"); add("generations",{generation_id:gen,model_id:model,generation_name:spec.gen,generation_code:"",facelift_status:"UNKNOWN",production_start_year:"",production_end_year:"",market_start_year_tr:"",market_end_year_tr:"",identity_status:spec.genStatus,legacy_source_id:"SCALE_BATCH_02",notes:`Official Turkey source ${spec.source}; status follows exact generation applicability.`});
    for (const power of spec.powers) {
      const pwr=next("powertrains","powertrain_id","PWR"); add("powertrains",{powertrain_id:pwr,generation_id:gen,marketing_name:power.name,fuel_type:power.fuel,electrification_type:power.elec,engine_displacement_cc:power.cc?.toString()??"",power_kw:power.kw?.toString()??"",power_ps:power.ps?.toString()??"",torque_nm:power.torque?.toString()??"",transmission_type:power.trans,transmission_gears:power.gears?.toString()??"",drivetrain:power.drive,battery_usable_kwh:"",identity_status:power.status,legacy_motor_text:"",notes:`SCALE_BATCH_02 identity-first evidence: ${spec.source}.`});
      for (const config of power.configs) { const cfg=next("configurations","configuration_id","CFG"); add("configurations",{configuration_id:cfg,generation_id:gen,powertrain_id:pwr,market:"TR",model_year:config.year,trim_name:config.trim,official_configuration_name:config.official,availability_status:"CURRENT",availability_from:"",availability_to:"",configuration_status:config.status,legacy_trim_text:"",legacy_source_id:"SCALE_BATCH_02",notes:`Official Turkey applicability source ${spec.source}; no global trim import.`}); refs.push({model,gen,pwr,cfg,source:spec.source,role:spec.role}); }
    }
  }

  const find=(brand:string,name:string,officialIncludes:string)=>{const m=tables.models.find((r)=>r.brand===brand&&r.model_name===name)!;const g=tables.generations.find((r)=>r.model_id===m.model_id)!;const c=tables.configurations.find((r)=>r.generation_id===g.generation_id&&r.official_configuration_name.includes(officialIncludes))!;return {m,g,c,p:tables.powertrains.find((r)=>r.powertrain_id===c.powertrain_id)!,s:refs.find((r)=>r.cfg===c.configuration_id)!.source};};
  const fact=(subject_type:string,subject_id:string,key:string,value:string,unit:string,src:string,context="",extra:Partial<Row>={})=>{const id=next("evidence_facts","fact_id","FAC");add("evidence_facts",{fact_id:id,subject_type,subject_id,fact_key:key,value_type:"NUMBER",value,unit,evidence_state:"VERIFIED",measurement_context:context,valid_from_model_year:"",valid_to_model_year:"",market:"TR",notes:"SCALE_BATCH_02 P0 evidence.",value_min:"",value_max:"",range_semantics:"NONE",source_value_semantics:"EXACT_SCALAR",source_value_raw:"",soc_start_pct:"",soc_end_pct:"",charge_power_context_kw:"",...extra});const ast=next("assertions","assertion_id","AST");add("assertions",{assertion_id:ast,evidence_type:"TECHNICAL_FACT",evidence_id:id,source_id:src,source_location:context||"technical data",extraction_method:"MANUAL",verification_status:"VERIFIED",applicability_status:"EXACT",verified_at:excelDate,verified_by:"ChatGPT/web research",notes:"SCALE_BATCH_02 controlled ingest."});return id;};
  const rangeFact=(subject_type:string,subject_id:string,key:string,min:string,max:string,unit:string,src:string,context="")=>fact(subject_type,subject_id,key,"",unit,src,context,{value_min:min,value_max:max,range_semantics:"MIN_MAX",source_value_semantics:"EXACT_RANGE",source_value_raw:`${min}-${max}`});
  const eq=(cfg:string,key:string,src:string,availability="STANDARD")=>{const id=next("equipment","equipment_id","EQP");add("equipment",{equipment_id:id,configuration_id:cfg,equipment_key:key,availability,evidence_state:"VERIFIED",notes:"SCALE_BATCH_02 decision-relevant equipment only."});add("assertions",{assertion_id:next("assertions","assertion_id","AST"),evidence_type:"EQUIPMENT_FACT",evidence_id:id,source_id:src,source_location:"equipment matrix",extraction_method:"MANUAL",verification_status:"VERIFIED",applicability_status:"EXACT",verified_at:excelDate,verified_by:"ChatGPT/web research",notes:""});};

  {const x=find("Toyota","Land Cruiser Prado","Power"); for(const [k,v,u] of [["length_mm","4925","mm"],["width_mm","1980","mm"],["height_mm","1935","mm"],["wheelbase_mm","2850","mm"],["ground_clearance_mm","215.3","mm"],["seats","5","count"],["cargo_volume_l","573","L"],["official_fuel_consumption_combined","10.8","L/100km"]]) fact(k.includes("length")||k.includes("width")||k.includes("height")||k.includes("wheelbase")||k.includes("clearance")?"GENERATION":"CONFIGURATION",k.includes("length")||k.includes("width")||k.includes("height")||k.includes("wheelbase")||k.includes("clearance")?x.g.generation_id:x.c.configuration_id,k,v,u,x.s,"2026 official technical sheet");}
  for (const suffix of ["42 kWh","49 kWh"]) {const x=find("Hyundai","INSTER",suffix); const is42=suffix.startsWith("42"); fact("POWERTRAIN",x.p.powertrain_id,"battery_capacity_reported_kwh",is42?"42":"49","kWh",x.s,"capacity semantics not gross/usable",{source_value_semantics:"BATTERY_CAPACITY_UNQUALIFIED"}); fact("CONFIGURATION",x.c.configuration_id,"official_electric_range",is42?"327":"360","km",x.s,"WLTP combined"); fact("CONFIGURATION",x.c.configuration_id,"official_energy_consumption_combined",is42?"14.3":"15.1","kWh/100km",x.s,"WLTP combined"); fact("CONFIGURATION",x.c.configuration_id,"dc_charge_time_min",is42?"30":"30","min",x.s,"DC fast charge 10-80%",{soc_start_pct:"10",soc_end_pct:"80",charge_power_context_kw:"350",source_value_semantics:"CHARGE_TIME_WITH_SOC_CONTEXT"});}
  {const x=find("Hyundai","IONIQ 6","111 kW");fact("POWERTRAIN",x.p.powertrain_id,"battery_capacity_reported_kwh","53","kWh",x.s,"reported battery capacity",{source_value_semantics:"BATTERY_CAPACITY_UNQUALIFIED"});fact("CONFIGURATION",x.c.configuration_id,"official_electric_range","429","km",x.s,"WLTP combined");fact("CONFIGURATION",x.c.configuration_id,"official_energy_consumption_combined","13.9","kWh/100km",x.s,"WLTP combined");}
  for (const suffix of ["Progressive","Calligraphy"]) {const x=find("Hyundai","IONIQ 9",suffix);fact("POWERTRAIN",x.p.powertrain_id,"battery_capacity_reported_kwh","110.3","kWh",x.s,"reported battery capacity",{source_value_semantics:"BATTERY_CAPACITY_UNQUALIFIED"});fact("CONFIGURATION",x.c.configuration_id,"dc_charge_time_min","24","min",x.s,"350 kW DC 10-80%",{soc_start_pct:"10",soc_end_pct:"80",charge_power_context_kw:"350",source_value_semantics:"CHARGE_TIME_WITH_SOC_CONTEXT"});fact("CONFIGURATION",x.c.configuration_id,"seats",suffix==="Progressive"?"7":"6","count",x.s,"Turkey trim-specific seating");fact("GENERATION",x.g.generation_id,"length_mm","5060","mm",x.s);fact("GENERATION",x.g.generation_id,"width_mm","1980","mm",x.s);fact("GENERATION",x.g.generation_id,"height_mm","1790","mm",x.s);fact("CONFIGURATION",x.c.configuration_id,"cargo_volume_l","338","L",x.s,"all rows upright");fact("CONFIGURATION",x.c.configuration_id,"towing_braked_kg","2500","kg",x.s,"up to; model technical FAQ");}
  {const x=find("Hyundai","STARIA HEV","Elite");fact("CONFIGURATION",x.c.configuration_id,"seats","9","count",x.s,"official Turkey product page");for(const k of ["aeb","adaptive_cruise_control","lane_keep_assist","reversing_camera"])eq(x.c.configuration_id,k,x.s);}
  for (const name of ["Berlingo","Berlingo Van"]) for (const suffix of ["6MT","EAT8"]) {const x=find("Citroën",name,suffix);fact("GENERATION",x.g.generation_id,"length_mm","4403","mm",x.s);fact("GENERATION",x.g.generation_id,"width_mm","1848","mm",x.s);fact("GENERATION",x.g.generation_id,"height_mm","1880","mm",x.s);fact("GENERATION",x.g.generation_id,"wheelbase_mm","2785","mm",x.s);fact("CONFIGURATION",x.c.configuration_id,"official_fuel_consumption_combined",suffix==="6MT"?"5.8":"5.9","L/100km",x.s,"WLTP combined");fact("CONFIGURATION",x.c.configuration_id,"seats",name==="Berlingo"?"5":"3","count",x.s); if(name==="Berlingo") fact("CONFIGURATION",x.c.configuration_id,"cargo_volume_l","775","L",x.s,"parcel shelf level");for(const k of ["aeb","lane_keep_assist","isofix_rear","parking_sensors_rear","apple_carplay","android_auto"]) if(!(name==="Berlingo Van"&&k==="isofix_rear")) eq(x.c.configuration_id,k,x.s);}
  for (const suffix of ["160 kW","390 kW"]) {const x=find("BYD","SEALION 7",suffix);const awd=suffix.startsWith("390");fact("POWERTRAIN",x.p.powertrain_id,"battery_capacity_reported_kwh",awd?"91.3":"71.8","kWh",x.s,"capacity semantics not gross/usable",{source_value_semantics:"BATTERY_CAPACITY_UNQUALIFIED"});fact("CONFIGURATION",x.c.configuration_id,"official_electric_range",awd?"502":"440","km",x.s,"WLTP combined");fact("CONFIGURATION",x.c.configuration_id,"official_energy_consumption_combined",awd?"21.9":"18.7","kWh/100km",x.s,"WLTP combined");fact("CONFIGURATION",x.c.configuration_id,"dc_charge_time_min",awd?"18":"20","min",x.s,"DC 30-80%",{soc_start_pct:"30",soc_end_pct:"80",charge_power_context_kw:awd?"230":"180",source_value_semantics:"CHARGE_TIME_WITH_SOC_CONTEXT"});fact("CONFIGURATION",x.c.configuration_id,"cargo_volume_l","520","L",x.s);fact("CONFIGURATION",x.c.configuration_id,"towing_braked_kg",awd?"1500":"750","kg",x.s);for(const k of ["aeb","adaptive_cruise_control","lane_keep_assist","blind_spot_monitor","rear_cross_traffic_alert","camera_360","apple_carplay","android_auto"])eq(x.c.configuration_id,k,x.s);}
  for (const suffix of ["Countryman E","SE ALL4"]) {const x=find("MINI","Countryman Electric",suffix);const awd=suffix==="SE ALL4";fact("POWERTRAIN",x.p.powertrain_id,"battery_capacity_reported_kwh","66.5","kWh",x.s,"brochure states net 64.6 / gross 66.5; reported field used conservatively");rangeFact("CONFIGURATION",x.c.configuration_id,"official_electric_range",awd?"399":"423",awd?"432":"462","km",x.s,"WLTP combined");rangeFact("CONFIGURATION",x.c.configuration_id,"official_energy_consumption_combined",awd?"16.8":"15.7",awd?"18.5":"17.4","kWh/100km",x.s,"WLTP combined");}
  {const x=find("Peugeot","3008","E-3008");rangeFact("CONFIGURATION",x.c.configuration_id,"official_electric_range","483","500","km",x.s,"WLTP combined");rangeFact("CONFIGURATION",x.c.configuration_id,"official_energy_consumption_combined","17.9","18.5","kWh/100km",x.s,"WLTP combined");fact("CONFIGURATION",x.c.configuration_id,"dc_charge_time_min","30","min",x.s,"DC fast charge; brochure interval",{soc_start_pct:"20",soc_end_pct:"80",charge_power_context_kw:"160",source_value_semantics:"CHARGE_TIME_WITH_SOC_CONTEXT"});}
  {const x=find("Suzuki","Jimny","GLX");for(const [k,v,u] of [["length_mm","3645","mm"],["width_mm","1645","mm"],["height_mm","1720","mm"],["wheelbase_mm","2250","mm"],["ground_clearance_mm","210","mm"]])fact("GENERATION",x.g.generation_id,k,v,u,x.s);fact("CONFIGURATION",x.c.configuration_id,"seats","4","count",x.s);fact("CONFIGURATION",x.c.configuration_id,"cargo_volume_l","85","L",x.s,"rear seats upright");fact("CONFIGURATION",x.c.configuration_id,"official_fuel_consumption_combined","8.1","L/100km",x.s,"WLTP combined");}

  const queueKeys=["identity_exact_configuration","dimensions_core","cargo_volume_l","ground_clearance_mm","efficiency_or_range_core","equipment_mvp_core"];
  for (const ref of refs) for (const key of queueKeys) {const has = key==="identity_exact_configuration" ? tables.configurations.find((r)=>r.configuration_id===ref.cfg)?.configuration_status==="VERIFIED" : key==="equipment_mvp_core" ? tables.equipment.some((r)=>r.configuration_id===ref.cfg) : key==="dimensions_core" ? tables.evidence_facts.some((r)=>r.subject_id===ref.gen&&r.fact_key==="length_mm") : tables.evidence_facts.some((r)=>[ref.cfg,ref.gen,ref.pwr].includes(r.subject_id)&&({cargo_volume_l:["cargo_volume_l"],ground_clearance_mm:["ground_clearance_mm"],efficiency_or_range_core:["official_fuel_consumption_combined","official_electric_range"]} as Record<string,string[]>)[key]?.includes(r.fact_key));add("collection_queue",{queue_id:next("collection_queue","queue_id","QUE"),subject_id:ref.cfg,fact_key:key,priority:"P0",collection_status:has?"COMPLETE":"NOT_STARTED",preferred_source_type:"A1_OFFICIAL_MARKET",assigned_method:"WEB",attempt_count:has?"1":"0",last_attempt_at:has?excelDate:"",result:has?"FOUND":"PENDING",notes:has?"SCALE_BATCH_02 collected.":"Bounded P0 evidence gap retained; no inference."});}

  for (const name of names) await writeFile(path.join(directory,`${name}.csv`),serialize(tables[name]));

  const coverage=[
    ["Role","Current models","Coverage","Assessment"],["city/B hatch","Clio; i20; Jazz e:HEV","3","represented"],["C hatch","Scala","1","weak"],["sedan","Egea Sedan; Corolla Sedan; Civic","3","represented"],["wagon","Octavia Combi; Superb Combi","2","represented"],["B-SUV","Vitara; Sandero Stepway","2","weak/specialized"],["C-SUV/crossover","Qashqai; C-HR; Austral; Formentor; HS Hybrid+; Elroq; EV3","7","strong"],["large family SUV","Forester e-BOXER","1","weak"],["7-seat family","Jogger","1 provisional","weak"],["MPV/passenger van","Jogger","1 provisional","weak"],["commercial/practical van","","0","absent"],["pickup","","0","absent"],["real 4x4","","0","absent"],["rough-road crossover","Crosstrek; Forester; Vitara","3","represented"],["BEV RWD","T10X; Elroq","2","represented"],["BEV AWD","","0","absent"],["performance EV","","0","absent"],["long-range EV","T10X (conflicting official values)","1","weak"]];
  await writeFile(path.join(path.dirname(directory),"SCALE_BATCH_02_CURRENT_COVERAGE.csv"),coverage.map((r)=>r.map(quote).join(",")).join("\n")+"\n");
  const gaps=[["GAP","CURRENT COVERAGE","WHY IT MATTERS TO EXPIYA","PRIORITY"],["pickup","0","Work/fleet/towing and mixed-use decision path","HIGH"],["real 4x4","0","Separates genuine off-road capability from crossover styling","HIGH"],["large 7-seat SUV","Jogger only; provisional","Large-family and towing decisions","HIGH"],["passenger/commercial van","0","Cargo, trades and high-seat-count use cases","HIGH"],["affordable urban BEV","EV3 only; SUV","Entry EV and city-footprint decisions","HIGH"],["long-range/family BEV","T10X/Elroq/EV3; narrow","Range, 3-row and family practicality comparison","HIGH"],["performance EV / BEV AWD","0","Performance and traction-specific discovery","MEDIUM"],["diesel long-distance","Egea only","High-mileage and load-carrying use","MEDIUM"],["premium alternative","Formentor only","Discovery beyond obvious mainstream set","MEDIUM"],["PHEV AWD","0","Electrified towing/traction bridge","MEDIUM"]];
  await writeFile(path.join(path.dirname(directory),"SCALE_BATCH_02_GAP_ANALYSIS.csv"),gaps.map((r)=>r.map(quote).join(",")).join("\n")+"\n");
  const candidates=[["Model","Brand","Segment","Propulsion","Mainstream / Discovery","Coverage Gap Filled","Turkey Availability Evidence","Selection Decision"],...specs.map((s)=>[s.name,s.brand,s.role.split(";")[0],s.powers.map((p)=>`${p.elec}/${p.drive}`).join(" + "),s.discovery,s.role,s.source,"SELECTED"]),["RAV4 Hybrid","Toyota","D-SUV","HEV/AWD","MAINSTREAM","HEV + AWD",S.landcruiser,"REJECTED: REDUNDANT_ROLE"],["Kona EV","Hyundai","B-SUV","BEV/FWD","MAINSTREAM","urban EV",S.hyundaiMarket,"REJECTED: LOW_MARGINAL_COVERAGE"],["i30","Hyundai","C-hatch","MHEV/FWD","MAINSTREAM","C-hatch",S.hyundaiMarket,"REJECTED: BATCH_BALANCE"],["Rafale E-Tech 4x4","Renault","D-SUV fastback","PHEV/AWD","MAINSTREAM","PHEV AWD",S.ranger,"REJECTED: EXACT_CONFIGURATION_UNRESOLVED"],["Mazda CX-80","Mazda","large 7-seat SUV","PHEV/AWD","DISCOVERY","PHEV AWD; 7-seat",S.ranger,"REJECTED: WEAK_TR_AVAILABILITY"]];
  await writeFile(path.join(path.dirname(directory),"SCALE_BATCH_02_CANDIDATE_SELECTION.csv"),candidates.map((r)=>r.map(quote).join(",")).join("\n")+"\n");
}
main().catch((error)=>{console.error(error);process.exitCode=1;});
