import { describe, expect, it, vi } from "vitest";
import { spawnSync } from "node:child_process";
import { createHmacOfferSigner } from "../features/decision/v2/offer/signer.server";
import type { PersistedGovernedOffer } from "../features/decision/v2/offer/types";
import { createMutableSmokeClock, runBoundedSmoke } from "./cars-decision-v2-smoke-lifecycle";

describe("bounded smoke lifecycle", () => {
  it("retains incremental summaries and completes with a zero-worthy result", async () => { const records: Record<string, unknown>[] = []; const result = await runBoundedSmoke({ runId: "run", timeoutMs: 1000, write: async (record) => { records.push({ ...record }); }, journeys: [{ name: "one", run: async () => ({ safe: 1 }) }, { name: "two", run: async () => ({ safe: 2 }) }] }); expect(result).toMatchObject({ ok: true, completedJourneys: 2 }); expect(records.map((record) => record.type)).toEqual(["JOURNEY_STARTED", "JOURNEY_COMPLETED", "JOURNEY_STARTED", "JOURNEY_COMPLETED", "RUN_COMPLETED"]); });
  it("sets a sanitized assertion failure and preserves earlier output", async () => { const records: Record<string, unknown>[] = []; const result = await runBoundedSmoke({ runId: "run", timeoutMs: 1000, write: async (record) => { records.push({ ...record }); }, journeys: [{ name: "one", run: async () => "kept" }, { name: "two", run: async ({ setPhase }) => { setPhase("ASSERTION", 2); const error = new Error("secret raw message"); error.name = "AssertionError"; throw error; } }] }); expect(result).toMatchObject({ ok: false, completedJourneys: 1, summaries: ["kept"] }); const failure = records.at(-1)!; expect(failure).toMatchObject({ type: "RUN_FAILED", journey: "two", turn: 2, phase: "ASSERTION", errorClass: "ASSERTION", errorCode: "ASSERTION_FAILED" }); expect(JSON.stringify(records)).not.toContain("secret raw message"); });
  it("sanitizes provider rejection", async () => { const records: Record<string, unknown>[] = []; await runBoundedSmoke({ runId: "run", timeoutMs: 1000, write: async (record) => { records.push({ ...record }); }, journeys: [{ name: "provider", run: async () => { throw new Error("429 api-key-secret"); } }] }); expect(records.at(-1)).toMatchObject({ errorClass: "PROVIDER", errorCode: "PROVIDER_RATE_LIMITED" }); expect(JSON.stringify(records)).not.toContain("api-key-secret"); });
  it("reports and clears a bounded global timeout", async () => { vi.useFakeTimers(); const records: Record<string, unknown>[] = []; const promise = runBoundedSmoke({ runId: "run", timeoutMs: 50, write: async (record) => { records.push({ ...record }); }, journeys: [{ name: "slow", run: () => new Promise(() => undefined) }] }); await vi.advanceTimersByTimeAsync(50); expect(await promise).toMatchObject({ ok: false, completedJourneys: 0 }); expect(records.at(-1)).toMatchObject({ errorCode: "GLOBAL_TIMEOUT" }); vi.useRealTimers(); });
  it("transforms the real CJS entrypoint and emits one sanitized setup failure", () => { const env = { ...process.env }; delete env.OPENAI_API_KEY; const child = spawnSync(process.execPath, ["--import", "tsx", "scripts/smoke-cars-decision-v2-manual-failures.ts"], { cwd: process.cwd(), env, encoding: "utf8", timeout: 10_000 }); expect(child.status).toBe(1); const lines = child.stdout.trim().split("\n").filter(Boolean).map((line) => JSON.parse(line) as Record<string, unknown>); expect(lines).toHaveLength(1); expect(lines[0]).toMatchObject({ type: "RUN_FAILED", errorCode: "SETUP_FAILED" }); expect(`${child.stdout}${child.stderr}`).not.toMatch(/OPENAI_API_KEY_REQUIRED|at main|Error:/u); });
  it("supports successful and rejected CJS promise lifecycles without hanging or leaking raw errors", () => { const successCode = `import('./scripts/cars-decision-v2-smoke-lifecycle.ts').then(async(m)=>{const r=await m.runBoundedSmoke({runId:'cli',timeoutMs:1000,write:(x)=>m.writeJsonLine(process.stdout,x),journeys:[{name:'ok',run:async()=>({ok:true})}]});process.exitCode=r.ok?0:1})`; const success = spawnSync(process.execPath, ["--import", "tsx", "-e", successCode], { cwd: process.cwd(), encoding: "utf8", timeout: 5_000 }); expect(success.status).toBe(0); expect(success.stdout).toContain('"type":"RUN_COMPLETED"'); const rejectCode = `import('./scripts/cars-decision-v2-smoke-lifecycle.ts').then(async(m)=>{const r=await m.runBoundedSmoke({runId:'cli',timeoutMs:1000,write:(x)=>m.writeJsonLine(process.stdout,x),journeys:[{name:'bad',run:async()=>{throw new Error('raw-secret-message')}}]});process.exitCode=r.ok?0:1})`; const rejected = spawnSync(process.execPath, ["--import", "tsx", "-e", rejectCode], { cwd: process.cwd(), encoding: "utf8", timeout: 5_000 }); expect(rejected.status).toBe(1); expect(rejected.stdout.match(/RUN_FAILED/gu)).toHaveLength(1); expect(`${rejected.stdout}${rejected.stderr}`).not.toContain("raw-secret-message"); });
  it("keeps offer verification on each turn request time without changing expiry policy", () => { const clock = createMutableSmokeClock("2026-08-19T00:00:00.000Z"); const signer = createHmacOfferSigner({ secret: "01234567890123456789012345678901", now: clock.now }); const offer = { offerId: "o", conversationId: "c", candidateRefs: [{ exactVariantId: "v", modelFamilyId: "f", finalDisposition: "ELIGIBLE_BUDGET_NOT_APPLIED", rankingOrdinal: 1, caveatFactIds: [], priceRealizationPermission: "NO_PRICE_LANGUAGE" }], mode: "SINGLE_REQUESTED", catalogReleaseVersion: "0.55.1", catalogFingerprint: "catalog", decisionFingerprint: "decision", lifecycleState: "CREATED", createdAt: "2026-08-19T00:00:00.000Z", expiresAt: "2026-08-19T00:10:00.000Z", authorizationVersion: "1.0.0", nonce: "nonce" } as PersistedGovernedOffer; const token = signer.sign(offer); clock.set("2026-08-19T00:01:00.000Z"); expect(signer.verify(token).status).toBe("VALID"); expect(clock.now().toISOString()).toBe("2026-08-19T00:01:00.000Z"); clock.set("2026-08-19T00:10:00.001Z"); expect(signer.verify(token).status).toBe("EXPIRED"); });
});
