import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { digest, materiality, validateSmartphoneObservations, type SmartphoneObservation } from "../features/electronics/smartphoneCatalogExpansion";

const root = process.cwd(), out = path.join(root, "data/research/electronics/smartphone-amazon-tr-catalog-expansion-01"), generatedAt = "2026-09-06T03:00:00.000Z";
const current = [
  { exactProductId:"electronics:smartphone:honor:dny-nx9-8-256-black",manufacturer:"HONOR",modelCode:"DNY-NX9",configuration:"HONOR 400|8GB|256GB|Gece Siyahı|5G|TR",facts:{storage_gb:256,memory_gb:8,chipset:null,display_inches:6.55,display_panel:null,refresh_hz:null,battery_mah:6000,charging_watts:null,wireless_charging:null,camera_configuration:null,optical_image_stabilization:null,ip_rating:null,cellular_generation:"5G",esim:null,os_version:null,support_years:null},sourceIds:["honor-tr:HONOR400","honor-global:DNY-NX9"] },
  { exactProductId:"electronics:smartphone:samsung:sm-a266bzkctur",manufacturer:"Samsung",modelCode:"SM-A266BZKCTUR",configuration:"Galaxy A26 5G|8GB|256GB|Black|TR",facts:{storage_gb:256,memory_gb:8,chipset:null,display_inches:null,display_panel:null,refresh_hz:null,battery_mah:null,charging_watts:null,wireless_charging:null,camera_configuration:null,optical_image_stabilization:null,ip_rating:null,cellular_generation:"5G",esim:null,os_version:null,support_years:null},sourceIds:["samsung-tr:SM-A266BZKCTUR"] },
  { exactProductId:"electronics:smartphone:samsung:sm-a366bzkgtur",manufacturer:"Samsung",modelCode:"SM-A366BZKGTUR",configuration:"Galaxy A36 5G|8GB|256GB|Black|TR",facts:{storage_gb:256,memory_gb:8,chipset:null,display_inches:null,display_panel:null,refresh_hz:null,battery_mah:null,charging_watts:null,wireless_charging:null,camera_configuration:null,optical_image_stabilization:null,ip_rating:null,cellular_generation:"5G",esim:null,os_version:null,support_years:null},sourceIds:["samsung-tr:SM-A366BZKGTUR"] },
];
const observed = [
  ["akıllı telefon 256 GB",1,"B0DSWCG72N","Redmi Note 14 Pro 8GB RAM, 256GB ROM, Siyah","ADMITTED","electronics:smartphone:xiaomi:redmi-note-14-pro-8-256-black","Exact 8+256 GB configuration appears on Xiaomi Türkiye specifications."],
  ["akıllı telefon 128 GB",1,"B0DXRBRLSY","Apple iPhone 16e (128 GB), Beyaz","ADMITTED","electronics:smartphone:apple:iphone-16e-128-white","Apple Türkiye support specifications enumerate 128 GB and white."],
  ["akıllı telefon 256 GB",1,"B0DGLV15YR","Xiaomi 14T 12GB RAM 256GB ROM, Titan Siyah","ADMITTED","electronics:smartphone:xiaomi:14t-12-256-black","Exact configuration reconciled to Xiaomi Türkiye product specifications."],
  ["Samsung telefon 256 GB",1,"B0CR6RKN78","Samsung Galaxy S24+ 12 GB RAM, 256 GB, Siyah","REJECTED_IDENTITY_AMBIGUOUS",null,"Amazon did not expose a Türkiye exact SKU; a generic Samsung Türkiye family page cannot close configuration identity."],
  ["POCO telefon",1,"B0DQLL7HWR","POCO X7 Pro 12GB RAM 512GB ROM, Sarı","REJECTED_INSUFFICIENT_TR_APPLICABILITY",null,"Amazon observation did not bind an exact manufacturer Türkiye SKU/configuration."],
  ["POCO telefon",1,"B0D383RCLP","Poco F6 Pro 12GB RAM 512GB ROM, Siyah","RETIRED_UNSUPPORTED",null,"No current Türkiye lifecycle/support admission was established in this pass."],
  ["POCO telefon",1,"B0BV6JK81H","Xiaomi POCO X5 Pro 5G 8GB RAM 256GB, Siyah","RETIRED_UNSUPPORTED",null,"Older listing has no current Türkiye lifecycle/support admission in this pass."],
] as const;
const observations: SmartphoneObservation[] = observed.map(([query,page,asin,observedTitle,terminalState,exactProductId,reason]) => ({ query,page,asin,observedTitle,observedAt: generatedAt,canonicalUrl:`https://www.amazon.com.tr/dp/${asin}`,terminalState,exactProductId,reason })) as SmartphoneObservation[];
const issues = validateSmartphoneObservations(observations); if (issues.length) throw new Error(issues.join(","));
const sources = [
  { sourceId:"honor-tr:HONOR400",authority:"MANUFACTURER_TR",url:"https://www.honor.com/tr/phones/honor-400/",supports:["current exact family","8+256 configuration","display","battery"] },
  { sourceId:"honor-global:DNY-NX9",authority:"MANUFACTURER_GLOBAL_ENRICHMENT_ONLY",url:"https://www.honor.com/global/phones/honor-400/spec/",supports:["model code enrichment; not Türkiye applicability alone"] },
  { sourceId:"samsung-tr:SM-A266BZKCTUR",authority:"MANUFACTURER_TR",url:"https://www.samsung.com/tr/smartphones/galaxy-a/galaxy-a26-5g-black-256gb-sm-a266bzkctur/",supports:["current exact Türkiye SKU","8+256 configuration","5G"] },
  { sourceId:"samsung-tr:SM-A366BZKGTUR",authority:"MANUFACTURER_TR",url:"https://www.samsung.com/tr/smartphones/galaxy-a/galaxy-a36-5g-black-256gb-sm-a366bzkgtur/",supports:["current exact Türkiye SKU","8+256 configuration","5G"] },
  { sourceId:"apple-tr:iphone-16e-spec",authority:"MANUFACTURER_TR",url:"https://support.apple.com/tr-tr/122208",supports:["identity","storage","display","dimensions","weight","chipset","camera","IP68","SIM/eSIM","OS"] },
  { sourceId:"xiaomi-tr:redmi-note-14-pro-spec",authority:"MANUFACTURER_TR",url:"https://www.mi.com/tr/product/redmi-note-14-pro/specs/",supports:["identity","8+256 configuration","chipset","display","battery","charging","camera/OIS","IP64","SIM","connectivity"] },
  { sourceId:"xiaomi-tr:14t-spec",authority:"MANUFACTURER_TR",url:"https://www.mi.com/tr/product/xiaomi-14t/specs/",supports:["identity","12+256 configuration","chipset","display","battery","charging","camera/OIS","IP68","SIM/eSIM","connectivity"] },
  { sourceId:"samsung-tr:s24-plus-spec",authority:"MANUFACTURER_TR",url:"https://www.samsung.com/tr/smartphones/galaxy-s24/specs/",supports:["family","256 GB configuration","chipset","display","battery","charging","camera/OIS","IP68","SIM/eSIM","connectivity"] },
  { sourceId:"samsung-tr:s25-example",authority:"MANUFACTURER_TR",url:"https://www.samsung.com/tr/business/smartphones/galaxy-s/galaxy-s25-silver-shadow-256gb-sm-s931bzsgtur/",supports:["future candidate exact Türkiye SKU pattern"] },
  { sourceId:"honor-tr:magic7-pro",authority:"MANUFACTURER_TR",url:"https://www.honor.com/tr/phones/honor-magic7-pro/",supports:["future candidate family","display","chipset","camera/OIS","charging","IP68/IP69"] },
];
const additions = [
 { exactProductId:"electronics:smartphone:apple:iphone-16e-128-white",manufacturer:"Apple",modelCode:"iPhone 16e",configuration:"128GB|White|TR",facts:{storage_gb:128,memory_gb:null,chipset:"A18",display_inches:6.1,display_panel:"OLED",refresh_hz:null,battery_mah:null,charging_watts:null,wireless_charging:true,camera_configuration:"48MP Fusion + 12MP front",optical_image_stabilization:null,ip_rating:"IP68",cellular_generation:"5G",esim:true,os_version:null,support_years:null},sourceIds:["apple-tr:iphone-16e-spec"] },
 { exactProductId:"electronics:smartphone:xiaomi:redmi-note-14-pro-8-256-black",manufacturer:"Xiaomi",modelCode:"Redmi Note 14 Pro",configuration:"8GB|256GB|Midnight Black|TR",facts:{storage_gb:256,memory_gb:8,chipset:"Helio G100-Ultra",display_inches:6.67,display_panel:"AMOLED",refresh_hz:120,battery_mah:5500,charging_watts:45,wireless_charging:null,camera_configuration:"200MP OIS + 8MP ultrawide + 2MP macro; 32MP front",optical_image_stabilization:true,ip_rating:"IP64",cellular_generation:"4G",esim:false,os_version:"Xiaomi HyperOS",support_years:null},sourceIds:["xiaomi-tr:redmi-note-14-pro-spec"] },
 { exactProductId:"electronics:smartphone:xiaomi:14t-12-256-black",manufacturer:"Xiaomi",modelCode:"14T",configuration:"12GB|256GB|Titan Black|TR",facts:{storage_gb:256,memory_gb:12,chipset:"Dimensity 8300-Ultra",display_inches:6.67,display_panel:"AMOLED",refresh_hz:144,battery_mah:5000,charging_watts:67,wireless_charging:false,camera_configuration:"50MP main OIS + 50MP telephoto + 12MP ultrawide; 32MP front",optical_image_stabilization:true,ip_rating:"IP68",cellular_generation:"5G",esim:true,os_version:"Xiaomi HyperOS",support_years:null},sourceIds:["xiaomi-tr:14t-spec"] },
];
type CandidateProduct = { readonly exactProductId: string; readonly facts: Readonly<Record<string, unknown>>; readonly proposedStatus: string } & Readonly<Record<string, unknown>>;
const products = [...current.map(row => ({...row,proposedStatus:"PRESERVED_CURRENT_EXACT"})),...additions.map(row=>({...row,proposedStatus:"NEW_CANDIDATE_NOT_ACTIVE"}))] as CandidateProduct[];
const factKeys = ["storage_gb","memory_gb","chipset","display_inches","display_panel","refresh_hz","battery_mah","charging_watts","wireless_charging","camera_configuration","optical_image_stabilization","ip_rating","cellular_generation","esim","os_version","support_years"];
const matrix = factKeys.map(key=>({factKey:key,values:Object.fromEntries(products.map(row=>[row.exactProductId,row.facts[key]??null])),assessment:materiality(products.map(row=>row.facts[key]))}));
const unknownLedger = products.flatMap(row=>factKeys.filter(key=>row.facts[key]==null).map(key=>({exactProductId:row.exactProductId,factKey:key,value:"UNKNOWN",reason:"No exact source-bound manufacturer Türkiye fact admitted."})));
const semantic = {status:"PROPOSAL_ONLY",rawKeysExposed:false,mappings:[{concept:"STORAGE_NEEDS",facts:["storage_gb"],gate:"MATERIAL",promptTr:"Fotoğraf, video ve uygulamalar için daha geniş depolama alanı senin için önemli mi?"},{concept:"SCREEN_EXPERIENCE",facts:["display_inches"],gate:"MATERIAL",promptTr:"Daha büyük ekran alanı senin için önemli mi?"},{concept:"NETWORK_GENERATION",facts:["cellular_generation"],gate:"MATERIAL",promptTr:"5G bağlantısı senin için önemli mi?"},{concept:"CHARGING_ACCESS",facts:["charging_watts","wireless_charging"],gate:"SUPPRESSED_PREDOMINANTLY_UNKNOWN",promptTr:"Kısa şarj fırsatlarında daha hızlı dolum veya kablosuz şarj senin için önemli mi?"},{concept:"CAMERA_USE",facts:["camera_configuration","optical_image_stabilization"],gate:"SUPPRESSED_PREDOMINANTLY_UNKNOWN",promptTr:"Hareketli ya da düşük ışıklı çekimlerde optik sabitleme senin için önemli mi?"},{concept:"WATER_EXPOSURE",facts:["ip_rating"],gate:"SUPPRESSED_PREDOMINANTLY_UNKNOWN",promptTr:"Yağmur ve su sıçramalarına karşı belgeli koruma senin için önemli mi?"},{concept:"SIM_ESIM",facts:["esim"],gate:"SUPPRESSED_PREDOMINANTLY_UNKNOWN",promptTr:"Fiziksel SIM yanında eSIM kullanabilmek senin için önemli mi?"},{concept:"SUPPORT_LONGEVITY",facts:["support_years"],gate:"SUPPRESSED_PREDOMINANTLY_UNKNOWN",promptTr:"Üreticinin açıkça taahhüt ettiği uzun güncelleme süresi senin için önemli mi?"}],suppressed:[{concept:"WORKLOAD_PERFORMANCE",reason:"No approved chipset-to-workload performance-class mapping."},{concept:"BRAND",reason:"Brand is explicit user context only; never prompted or scored."}]};
const terminal = {schemaVersion:"electronics-smartphone-terminal-ledger/v1",workUnit:"WU-ELECTRONICS-SMARTPHONE-AMAZON-TR-CATALOG-EXPANSION-01",generatedAt,observations};
const packageData = {schemaVersion:"electronics-smartphone-owner-approval-package/v1",workUnit:terminal.workUnit,verdict:"COVERAGE_INCOMPLETE",baseGitRef:"6858382",counts:{amazonQueryRuns:4,observedAsins:7,retained:7,reconciled:7,admittedExactProducts:6,newExactProducts:3,rejected:4},products,sources,unknownLedger,materialityMatrix:matrix,semanticProposal:semantic,invariants:{amazonTechnicalAuthority:"NONE",priceRankingEffect:"NONE",affiliateRankingEffect:"NONE",sellerClaimTechnicalEffect:"NONE",brandPrompting:"PROHIBITED",brandExplicitContextOnly:true,catalogOrderRankingEffect:"NONE",personaEffect:"NONE",commerceEffect:"NONE",activePointerMutation:false,runtimeMutation:false,activationPerformed:false},preview:{before:{outcome:"NON_DOMINATED_SET",candidateCount:3,questions:[]},after:{outcomeSequence:["ASK:STORAGE_NEEDS","ASK:SCREEN_EXPERIENCE","ASK:NETWORK_GENERATION","NON_DOMINATED_SET"],oneQuestionAtATime:true,noWinnerFabricated:true,suppressedPredominantlyUnknown:["CHARGING_ACCESS","CAMERA_USE","WATER_EXPOSURE","SIM_ESIM","SUPPORT_LONGEVITY"]}},coverage:{represented:["mainstream/value","compact-screen","large-screen","camera-oriented","battery-oriented","premium"],missing:["exact foldable Türkiye SKU","exact rugged/durable Türkiye SKU"],unresolvedCandidates:["Samsung Galaxy Z Flip6 12GB/256GB Türkiye exact SKU","HONOR Magic7 Pro Türkiye exact RAM/storage SKU"]},approval:{status:"NOT_ELIGIBLE",reason:"Named foldable and durable/rugged market segments remain unreconciled.",activationAllowed:false}};
rmSync(out,{recursive:true,force:true}); mkdirSync(out,{recursive:true});
const files:Record<string,unknown>={"amazon-observations.json":{queryRuns:["akıllı telefon 256 GB","akıllı telefon 128 GB","Samsung telefon 256 GB","POCO telefon"],observations},"terminal-ledger.json":terminal,"source-register.json":sources,"manuals-support-register.json":sources.map(source=>({sourceId:source.sourceId,url:source.url,manualChecksum:"UNKNOWN_NOT_DOWNLOADED",warrantyScope:"UNKNOWN_UNLESS_EXPLICIT_IN_SOURCE"})),"candidate-catalog.json":{status:"CANDIDATE_NOT_ACTIVE",products},"technical-facts.json":additions,"unknown-ledger.json":unknownLedger,"coverage-report.json":packageData.coverage,"semantic-proposal.json":semantic,"materiality-matrix.json":matrix,"owner-approval-package.json":packageData};
for(const [name,value] of Object.entries(files)) writeFileSync(path.join(out,name),`${JSON.stringify(value,null,2)}\n`);
const manifest={schemaVersion:"electronics-smartphone-expansion-manifest/v1",generatedAt,files:Object.entries(files).map(([name,value])=>({name,digest:digest(value)})),packageDigest:digest(packageData),activePointerMutation:false,activationPerformed:false}; writeFileSync(path.join(out,"manifest.json"),`${JSON.stringify(manifest,null,2)}\n`);
console.log(JSON.stringify({out,verdict:packageData.verdict,counts:packageData.counts,packageDigest:manifest.packageDigest}));
