import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ELECTRONICS_CATEGORY_REGISTRY, type ElectronicsCategoryId } from "../features/electronics/architectureBaseline";
import { ELECTRONICS_TURKEY_SECOND_PASS_VERSION, validateTurkeySecondPass, type AmazonRelation, type TurkeySecondPassCandidate, type TurkeySecondPassInvestigation } from "../features/electronics/turkeySecondPass";

const root = process.cwd();
const observedAt = "2026-09-05T10:30:00.000Z";
const amazonDir = path.join(root, "data/research/electronics/amazon-tr-primary-catalog-01");
const amazonManifest = JSON.parse(readFileSync(path.join(amazonDir, "manifest.json"), "utf8"));
const amazon = JSON.parse(readFileSync(path.join(amazonDir, "amazon-primary-research.json"), "utf8"));
const requiredAmazonDigest = "sha256:09ef0e34db66fa00f9fb3b98f83db0370f1e0a2905da805c50282073576e3a20";
if (amazonManifest.payloadDigest !== requiredAmazonDigest) throw new Error("AMAZON_PRIMARY_DIGEST_MISMATCH");

type Seed = readonly [ElectronicsCategoryId, string, string | null, string | null, string, "OFFICIAL_TR_MANUFACTURER" | "OFFICIAL_TR_SUPPORT" | "AUTHORIZED_TR_CHANNEL" | "INTERNATIONAL_OFFICIAL", AmazonRelation, "ADMIT" | "IDENTITY_GAP" | "TR_GAP" | "CONFIG_GAP"];
const seeds: readonly Seed[] = [
  ["SMARTPHONE", "Samsung Galaxy A36 5G 256GB Black", "SM-A366BZKGTUR", "Samsung|Galaxy A36 5G|SM-A366BZKGTUR|8GB|256GB|Black|TR", "https://www.samsung.com/tr/smartphones/galaxy-a/galaxy-a36-5g-awesome-black-256gb-sm-a366bzkgtur/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "ADMIT"],
  ["SMARTPHONE", "Samsung Galaxy A36 5G 256GB Lime", "SM-A366BLGGTUR", null, "https://www.samsung.com/tr/smartphones/galaxy-a/galaxy-a36-5g/buy/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["LAPTOP", "Lenovo IdeaPad Slim 3 16IRH10", "83K20077TR", null, "https://psref.lenovo.com/", "INTERNATIONAL_OFFICIAL", "OBSERVED_AMBIGUOUS_OR_FAMILY_ONLY", "TR_GAP"],
  ["LAPTOP", "ASUS TUF Gaming F16", "FX607VJB-RL279", null, "https://www.asus.com/tr/laptops/for-gaming/tuf-gaming/", "OFFICIAL_TR_MANUFACTURER", "OBSERVED_AMBIGUOUS_OR_FAMILY_ONLY", "CONFIG_GAP"],
  ["TABLET", "Samsung Galaxy Tab S11 Wi-Fi Silver 256GB", "SM-X730NZSPTUR", "Samsung|Galaxy Tab S11 Wi-Fi|SM-X730NZSPTUR|12GB|256GB|Silver|TR", "https://www.samsung.com/tr/tablets/galaxy-tab-s/galaxy-tab-s11-silver-256gb-sm-x730nzsptur/buy/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "ADMIT"],
  ["TABLET", "Samsung Galaxy Tab S10 FE Wi-Fi Silver 256GB", "SM-X520NZSPTUR", "Samsung|Galaxy Tab S10 FE Wi-Fi|SM-X520NZSPTUR|256GB|Silver|TR", "https://www.samsung.com/tr/tablets/galaxy-tab-s/galaxy-tab-s10-fe-silver-256gb-sm-x520nzsptur/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "ADMIT"],
  ["MONITOR", "Samsung ViewFinity S6 S61F 27 QHD", "LS27F612EAUXUF", "Samsung|ViewFinity S6 S61F|LS27F612EAUXUF|27in|QHD|100Hz|TR", "https://www.samsung.com/tr/monitors/high-resolution/viewfinity-s6-s61f-27-inch-qhd-100hz-ergonomic-ls27f612eauxuf/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "ADMIT"],
  ["MONITOR", "Samsung ViewFinity S9 27 5K", "LS27C902PAUXUF", "Samsung|ViewFinity S9|LS27C902PAUXUF|27in|5K|TR", "https://www.samsung.com/tr/monitors/high-resolution/viewfinity-s9-27-inch-5k-resolution-ls27c902pauxuf/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "ADMIT"],
  ["TELEVISION", "Samsung Neo QLED 55", null, null, "https://www.samsung.com/tr/tvs/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "IDENTITY_GAP"],
  ["TELEVISION", "TCL QLED 55", null, null, "https://www.tcl.com/tr/tr/tvs", "OFFICIAL_TR_MANUFACTURER", "OBSERVED_AMBIGUOUS_OR_FAMILY_ONLY", "IDENTITY_GAP"],
  ["E_READER", "Kobo Libra Colour Black 32GB", "N428-KU-BK-K-EP", null, "https://www.kobo.com/tr/tr/ereaders/kobo-libra-colour", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["E_READER", "Kobo Elipsa 2E 32GB", null, null, "https://www.kobo.com/tr/tr/ereaders", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "IDENTITY_GAP"],
  ["HEADPHONES", "HUAWEI FreeBuds 6i Black", null, null, "https://consumer.huawei.com/tr/headphones/freebuds6i/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "IDENTITY_GAP"],
  ["HEADPHONES", "HUAWEI FreeBuds 6 Black", null, null, "https://consumer.huawei.com/tr/headphones/freebuds6/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "IDENTITY_GAP"],
  ["PORTABLE_SPEAKER", "JBL Flip 7 Black", "JBLFLIP7BLK", null, "https://tr.jbl.com/bluetooth-hoparlorler/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["PORTABLE_SPEAKER", "JBL Charge 6 Black", "JBLCHARGE6BLK", null, "https://tr.jbl.com/bluetooth-hoparlorler/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["SOUNDBAR", "Samsung HW-Q800F", "HW-Q800F/TK", null, "https://www.samsung.com/tr/audio-devices/soundbar/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["SOUNDBAR", "Samsung HW-Q600F", "HW-Q600F/TK", null, "https://www.samsung.com/tr/audio-devices/soundbar/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["DIGITAL_CAMERA", "Sony ZV-E10 II Body Black", "ZVE10M2B.CEC", "Sony|ZV-E10 II Body|ZVE10M2B.CEC|Body Only|Black|TR", "https://www.sony.com.tr/electronics/degistirilebilir-lensli-fotograf-makineleri/zv-e10m2/buy/zve10m2b.cec", "OFFICIAL_TR_MANUFACTURER", "OBSERVED_ACCESSORY_OR_BUNDLE_ONLY", "ADMIT"],
  ["DIGITAL_CAMERA", "Canon EOS R50 RF-S 18-45 Kit", null, null, "https://www.canon.com.tr/cameras/eos-r50/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "IDENTITY_GAP"],
  ["PROJECTOR", "Epson CO-FH02", "V11HA85040", null, "https://www.epson.com.tr/tr_TR/ürünler/projektörler/c/home-cinema", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["PROJECTOR", "Epson EH-TW6250", "V11HA73040", null, "https://www.epson.com.tr/tr_TR/ürünler/projektörler/c/home-cinema", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["GAME_CONSOLE", "PlayStation 5 Pro", "CFI-7021", null, "https://bilkom.com.tr/", "AUTHORIZED_TR_CHANNEL", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["GAME_CONSOLE", "Xbox Series S 1TB", null, null, "https://www.xbox.com/tr-TR/consoles", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "IDENTITY_GAP"],
  ["WIFI_ROUTER_MESH", "TP-Link Deco BE25 EU V1 2-pack", "Deco BE25(EU) V1 (2-pack)", "TP-Link|Deco BE25|EU V1|2-pack|BE3600|TR", "https://www.tp-link.com/tr/home-networking/deco/deco-be25/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "ADMIT"],
  ["WIFI_ROUTER_MESH", "TP-Link Deco BE25 EU V1 3-pack", "Deco BE25(EU) V1 (3-pack)", null, "https://www.tp-link.com/tr/home-networking/deco/deco-be25/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["NETWORK_ATTACHED_STORAGE", "Synology DS224+", "DS224+", null, "https://www.synology.com/tr-tr/products/DS224+", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["NETWORK_ATTACHED_STORAGE", "QNAP TS-264-8G", "TS-264-8G", null, "https://www.qnap.com/tr-tr/product/ts-264", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["EXTERNAL_STORAGE", "Samsung Portable SSD T9 1TB Black", "MU-PG1T0B/WW", "Samsung|T9|MU-PG1T0B/WW|1TB|USB 3.2 Gen2x2|Black|TR", "https://www.samsung.com/tr/memory-storage/portable-ssd/portable-ssd-t9-1tb-black-mu-pg1t0b-ww/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "ADMIT"],
  ["EXTERNAL_STORAGE", "Samsung Portable SSD T9 2TB Black", "MU-PG2T0B/WW", null, "https://www.samsung.com/tr/memory-storage/portable-ssd/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["PRINTER", "Epson EcoTank L3276", "C11CJ67435", null, "https://www.epson.com.tr/tr_TR/ürünler/yazıcılar/inkjet/tüketici/ecotank-l3276/p/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["PRINTER", "HP LaserJet M140w", "7MD72A", null, "https://support.hp.com/tr-tr/", "OFFICIAL_TR_SUPPORT", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["WEBCAM", "Logitech Brio 500 Graphite", "960-001422", null, "https://www.logitech.com/tr-tr/products/webcams/brio-500-webcam.html", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["WEBCAM", "Logitech MX Brio Graphite", "960-001559", null, "https://www.logitech.com/tr-tr/products/webcams/mx-brio.html", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["COMPUTER_AUDIO", "Logitech Z407", "980-001348", null, "https://www.logitech.com/tr-tr/products/speakers/z407-bluetooth-computer-speakers.html", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["COMPUTER_AUDIO", "Logitech Z207", "980-001295", null, "https://www.logitech.com/tr-tr/products/speakers/z207-stereo-speakers-bluetooth.html", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["SMARTWATCH", "HUAWEI WATCH GT 5 46mm Black", null, null, "https://consumer.huawei.com/tr/wearables/watch-gt5/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "IDENTITY_GAP"],
  ["SMARTWATCH", "Samsung Galaxy Watch8 44mm Bluetooth", null, null, "https://www.samsung.com/tr/watches/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "IDENTITY_GAP"],
  ["FITNESS_TRACKER", "Xiaomi Smart Band 9 Pro Black", null, null, "https://www.mi.com/tr/product/xiaomi-smart-band-9-pro/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "IDENTITY_GAP"],
  ["FITNESS_TRACKER", "HUAWEI Band 10 Black", null, null, "https://consumer.huawei.com/tr/wearables/band10/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "IDENTITY_GAP"],
  ["HOME_SECURITY_CAMERA", "TP-Link Tapo C225 EU V1", "Tapo C225(EU) V1", "TP-Link|Tapo C225|EU V1|Indoor|12V|TR", "https://www.tp-link.com/tr/home-networking/cloud-camera/tapo-c225/v1/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "ADMIT"],
  ["HOME_SECURITY_CAMERA", "TP-Link Tapo C225 EU V2", "Tapo C225(EU) V2", null, "https://www.tp-link.com/tr/home-networking/cloud-camera/tapo-c225/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["VIDEO_DOORBELL", "TP-Link Tapo D235", "Tapo D235", "TP-Link|Tapo D235|Battery or 8-24V Wired|Chime Included|TR", "https://www.tp-link.com/tr/home-networking/cloud-camera/tapo-d235/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "ADMIT"],
  ["VIDEO_DOORBELL", "TP-Link Tapo D225", "Tapo D225", null, "https://www.tp-link.com/tr/support/faq/4194/", "OFFICIAL_TR_SUPPORT", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["SMART_HOME_HUB", "Aqara Hub M3", "HM-G01D", null, "https://www.aqara.com/eu/product/hub-m3/", "INTERNATIONAL_OFFICIAL", "NOT_OBSERVED_ON_AMAZON_TR", "TR_GAP"],
  ["SMART_HOME_HUB", "Aqara Hub M2", "HM2-G01", null, "https://www.aqara.com/eu/product/hub-m2/", "INTERNATIONAL_OFFICIAL", "NOT_OBSERVED_ON_AMAZON_TR", "TR_GAP"],
  ["UNINTERRUPTIBLE_POWER_SUPPLY", "APC Back-UPS BX2200MI-GR", "BX2200MI-GR", null, "https://www.se.com/tr/tr/product/BX2200MI-GR/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
  ["UNINTERRUPTIBLE_POWER_SUPPLY", "APC Back-UPS BX1200MI-GR", "BX1200MI-GR", null, "https://www.se.com/tr/tr/product/BX1200MI-GR/", "OFFICIAL_TR_MANUFACTURER", "NOT_OBSERVED_ON_AMAZON_TR", "CONFIG_GAP"],
];

const categoryById = new Map(ELECTRONICS_CATEGORY_REGISTRY.map(category => [category.categoryId, category]));
const disposition = (status: Seed[7]) => status === "ADMIT" ? "ADMITTED" as const : status === "IDENTITY_GAP" ? "REJECTED_IDENTITY_INCOMPLETE" as const : status === "TR_GAP" ? "REJECTED_TR_APPLICABILITY_INCOMPLETE" as const : "REJECTED_CONFIGURATION_MISMATCH" as const;
const investigations: TurkeySecondPassInvestigation[] = seeds.map((seed, index) => { const [categoryId, model, manufacturerModelCode, configurationIdentity, sourceUri, sourceKind, amazonRelation, status] = seed; const category = categoryById.get(categoryId)!; return { investigationId: `TR2-${String(index + 1).padStart(3, "0")}`, categoryId: category.categoryId, wave: category.wave, brand: model.split(" ")[0], model, manufacturerModelCode, configurationIdentity, sourceId: `source:${categoryId.toLowerCase()}:${index + 1}`, sourceUri, sourceKind, observedAt, amazonRelation, disposition: disposition(status), reason: status === "ADMIT" ? "Exact configuration and Türkiye applicability established by the cited official Türkiye source." : status === "IDENTITY_GAP" ? "Official Türkiye family/model presence found, but exact manufacturer configuration code is missing." : status === "TR_GAP" ? "Technical identity source is international; independent Türkiye applicability remains unproven." : "Product/model code is visible, but exact saleable configuration discriminators are incomplete or mismatched.", retailerTechnicalAuthority: "NONE", internationalTrApplicabilityAuthority: "NONE" }; });
const candidates: TurkeySecondPassCandidate[] = investigations.filter(row => row.disposition === "ADMITTED").map(row => ({ exactProductId: `electronics:${row.categoryId.toLowerCase().replaceAll("_", "-")}:${row.brand.toLowerCase()}:${row.manufacturerModelCode!.toLowerCase().replaceAll(/[/.() ]/gu, "-")}`, categoryId: row.categoryId, wave: row.wave, brand: row.brand, model: row.model, manufacturerModelCode: row.manufacturerModelCode!, configurationIdentity: row.configurationIdentity!, trApplicabilitySourceId: row.sourceId, amazonRelation: row.amazonRelation as TurkeySecondPassCandidate["amazonRelation"], lifecycle: "GOVERNED_CATALOG_CANDIDATE", amazonPriorityEffect: "NONE", decisionAuthority: "NONE" }));
const amazonExactIds = amazon.candidates.map((candidate: { exactProductId: string }) => candidate.exactProductId);
const amazonConfigurations = amazon.candidates.map((candidate: { configurationIdentity: string }) => candidate.configurationIdentity);
const issues = validateTurkeySecondPass({ categoryIds: ELECTRONICS_CATEGORY_REGISTRY.map(category => category.categoryId), investigations, candidates, amazonExactIds, amazonConfigurations });
if (issues.length) throw new Error(`TURKEY_SECOND_PASS_INVALID:${issues.join(",")}`);
const canonical = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b, "en")).map(([key, child]) => `${JSON.stringify(key)}:${canonical(child)}`).join(",")}}`;
const digest = (value: unknown) => `sha256:${createHash("sha256").update(canonical(value)).digest("hex")}`;
const queryRuns = ELECTRONICS_CATEGORY_REGISTRY.flatMap(category => ["official Türkiye product support exact model", "authorized Türkiye channel exact configuration"].map((family, index) => ({ categoryId: category.categoryId, wave: category.wave, queryFamily: family, runId: `${category.categoryId}:TR:${index + 1}`, resultCap: 8, observedAt })));
const coverage = ELECTRONICS_CATEGORY_REGISTRY.map(category => ({ categoryId: category.categoryId, wave: category.wave, queryRuns: 2, investigated: investigations.filter(row => row.categoryId === category.categoryId).length, admitted: candidates.filter(candidate => candidate.categoryId === category.categoryId).length, rejected: investigations.filter(row => row.categoryId === category.categoryId && row.disposition !== "ADMITTED").length }));
const combined = { amazonFirst: { digest: requiredAmazonDigest, candidateCount: amazon.candidates.length }, turkeySecondPass: { candidateCount: candidates.length }, union: { candidateCount: amazon.candidates.length + candidates.length, duplicateCount: 0 }, invariants: { amazonAbsencePriorityEffect: "NONE", amazonUnavailabilityPriorityEffect: "NONE", candidateMembershipAuthority: "EXACT_IDENTITY_AND_TR_APPLICABILITY_ONLY" } };
const payload = { schemaVersion: ELECTRONICS_TURKEY_SECOND_PASS_VERSION, workUnit: "WU-ELECTRONICS-TURKEY-NON-AMAZON-CATALOG-01", authorityStatus: "GOVERNED_CANDIDATES_NOT_ACTIVE", scope: { departmentId: "ELECTRONICS", market: "TR", categoryCount: 24 }, method: { queryFamiliesPerCategory: 2, investigationCapPerCategory: 2, exhaustiveCoverageClaim: false }, queryRuns, investigations, candidates, rejectionLedger: investigations.filter(row => row.disposition !== "ADMITTED"), coverage, combined, boundaries: { pricesStockOffers: "L10_VOLATILE_NONE_CAPTURED", retailerTechnicalAuthority: "NONE", internationalTrApplicabilityAuthority: "NONE", mediaImported: false, decisionAuthority: "NONE", activePointersMutated: false } };
const reconciliation = { schemaVersion: "electronics-cross-pass-reconciliation/v1", amazonFirstDigest: requiredAmazonDigest, amazonFirstExactIds: amazonExactIds, secondPassExactIds: candidates.map(candidate => candidate.exactProductId), combinedExactIds: [...amazonExactIds, ...candidates.map(candidate => candidate.exactProductId)].sort(), duplicateExactIds: [], duplicateConfigurations: [], amazonRelationHasPriorityEffect: false, digest: digest(combined) };
const manifest = { schemaVersion: "electronics-turkey-second-pass-manifest/v1", generatedAt: observedAt, payloadFile: "turkey-second-pass.json", payloadDigest: digest(payload), reconciliationFile: "cross-pass-reconciliation.json", reconciliationDigest: digest(reconciliation), counts: { categories: 24, queryRuns: queryRuns.length, investigations: investigations.length, candidates: candidates.length, rejections: investigations.length - candidates.length, combinedCandidates: combined.union.candidateCount }, activation: { permitted: false, productionAuthority: false } };
const output = path.join(root, "data/research/electronics/turkey-non-amazon-catalog-01"); mkdirSync(output, { recursive: true });
writeFileSync(path.join(output, "turkey-second-pass.json"), `${JSON.stringify(payload, null, 2)}\n`); writeFileSync(path.join(output, "cross-pass-reconciliation.json"), `${JSON.stringify(reconciliation, null, 2)}\n`); writeFileSync(path.join(output, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
console.log(JSON.stringify({ output, ...manifest.counts, payloadDigest: manifest.payloadDigest, reconciliationDigest: manifest.reconciliationDigest }));
