import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ELECTRONICS_WAVE_3_CATEGORY_IDS, ELECTRONICS_WAVE_3_PARENT_DIGEST, ELECTRONICS_WAVE_3_VERSION, validateWave3EvidenceClosure, type Wave3EvidenceRelease } from "../features/electronics/wave3EvidenceClosure";

const root = process.cwd(); const pretty = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`; const sha = (raw: string | Buffer) => `sha256:${createHash("sha256").update(raw).digest("hex")}` as `sha256:${string}`;
const parentPath = path.join(root, "data/production/electronics/wave-2-repair/releases/ELECTRONICS-WAVE-2-GAME-CONSOLE-IDENTITY-REPAIR-TR-v0.1/repair-release.json"); if (sha(readFileSync(parentPath)) !== ELECTRONICS_WAVE_3_PARENT_DIGEST) throw new Error("WAVE_2_PARENT_DIGEST_MISMATCH");
const amazonManifest = JSON.parse(readFileSync(path.join(root, "data/research/electronics/amazon-tr-primary-catalog-01/manifest.json"), "utf8")) as { payloadDigest: `sha256:${string}` };
type Product = Wave3EvidenceRelease["products"][number]; const products: Product[] = [
  { exactProductId: "electronics:wifi-router-mesh:tp-link:deco-be25-eu-v1-2pack", categoryId: "WIFI_ROUTER_MESH", manufacturer: "TP-Link", modelCode: "Deco BE25(EU) V1 (2-pack)", configurationIdentity: "TP-Link|Deco BE25|EU V1|Wi-Fi 7 BE3600|2-pack|TR", trApplicabilitySourceIds: ["tplink-tr:Deco-BE25-EU-V1"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:wifi-router-mesh:asus:xd5-w-2-pk", categoryId: "WIFI_ROUTER_MESH", manufacturer: "ASUS", modelCode: "XD5 (W-2-PK)", configurationIdentity: "ASUS|ZenWiFi XD5|XD5 W-2-PK|Wi-Fi 6 AX3000|2-pack|White|TR|Hardware revision not separately published", trApplicabilitySourceIds: ["asus-tr:XD5-W-2-PK"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:nas:synology:ds224plus-diskless-2gb", categoryId: "NETWORK_ATTACHED_STORAGE", manufacturer: "Synology", modelCode: "DS224+", configurationIdentity: "Synology|DS224+|2-bay|Diskless|2GB DDR4|TR", trApplicabilitySourceIds: ["synology-tr:DS224plus"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:nas:qnap:ts-264-8g-diskless", categoryId: "NETWORK_ATTACHED_STORAGE", manufacturer: "QNAP", modelCode: "TS-264-8G", configurationIdentity: "QNAP|TS-264-8G|2-bay|Diskless|8GB|TR", trApplicabilitySourceIds: ["qnap-tr:TS-264-8G"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:external-storage:samsung:mu-pg1t0b-ww", categoryId: "EXTERNAL_STORAGE", manufacturer: "Samsung", modelCode: "MU-PG1T0B/WW", configurationIdentity: "Samsung|Portable SSD T9|MU-PG1T0B/WW|SSD|1TB|USB 3.2 Gen 2x2|Black|TR", trApplicabilitySourceIds: ["samsung-tr:MU-PG1T0B-WW"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:external-storage:sandisk:sdssde61-1t00-g25", categoryId: "EXTERNAL_STORAGE", manufacturer: "SanDisk", modelCode: "SDSSDE61-1T00-G25", configurationIdentity: "SanDisk|Extreme Portable SSD|SDSSDE61-1T00-G25|SSD|1TB|USB 3.2 Gen 2|Black/Orange|TR", trApplicabilitySourceIds: ["wd-tr:SDSSDE61-1T00-G25"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:printer:epson:c11cj67435", categoryId: "PRINTER", manufacturer: "Epson", modelCode: "C11CJ67435", configurationIdentity: "Epson|EcoTank L3276|C11CJ67435|Ink tank|Color|Print scan copy|Wi-Fi|TR", trApplicabilitySourceIds: ["epson-tr:C11CJ67435"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:printer:hp:7md72a", categoryId: "PRINTER", manufacturer: "HP", modelCode: "7MD72A", configurationIdentity: "HP|LaserJet MFP M140w|7MD72A|Laser|Mono|Print scan copy|Wi-Fi|TR", trApplicabilitySourceIds: ["hp-tr:7MD72A"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:webcam:logitech:960-001422", categoryId: "WEBCAM", manufacturer: "Logitech", modelCode: "960-001422", configurationIdentity: "Logitech|Brio 500|960-001422|1080p30|USB-C|Graphite|Webcam only|TR", trApplicabilitySourceIds: ["logitech-tr:Brio500-960-001422"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:webcam:asus:webcam-c3", categoryId: "WEBCAM", manufacturer: "ASUS", modelCode: "ASUS Webcam C3", configurationIdentity: "ASUS|Webcam C3|1080p30|USB 2.0 wired|Fixed focus|Standard bundle|TR", trApplicabilitySourceIds: ["asus-tr:Webcam-C3"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:computer-audio:logitech:980-001295", categoryId: "COMPUTER_AUDIO", manufacturer: "Logitech", modelCode: "980-001295", configurationIdentity: "Logitech|Z207|980-001295|2.0|Bluetooth and 3.5mm|No subwoofer|Black|TR", trApplicabilitySourceIds: ["logitech-tr:Z207-980-001295"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:computer-audio:edifier:r1280dbs-black", categoryId: "COMPUTER_AUDIO", manufacturer: "Edifier", modelCode: "R1280DBs", configurationIdentity: "Edifier|R1280DBs|2.0|Bluetooth 5.0/optical/coaxial/dual RCA|Subwoofer output but none included|Black|TR", trApplicabilitySourceIds: ["edifier-tr:R1280DBs"], unresolvedIdentityDiscriminators: [] },
];
type Source = Wave3EvidenceRelease["sources"][number]; const src = (sourceId: string, uri: string, ids: string[], authority: Source["authority"] = "TECHNICAL", tr: Source["trApplicabilityAuthority"] = "EXACT", market: Source["market"] = "TR"): Source => ({ sourceId, uri, market, authority, exactProductIds: ids, trApplicabilityAuthority: tr, decisionAuthority: "NONE" }); const p = (i: number) => products[i].exactProductId;
const sources: Source[] = [
  src("tplink-tr:Deco-BE25-EU-V1", "https://www.tp-link.com/tr/home-networking/deco/deco-be25/", [p(0)]), src("tplink-global:Deco-BE25-datasheet", "https://static.tp-link.com/upload/product-overview/2024/202406/20240614/Deco%20BE25%28EU%291.0_Datasheet.pdf", [p(0)], "INTERNATIONAL_BOUNDED", "NONE", "GLOBAL"), src("asus-tr:XD5-W-2-PK", "https://www.asus.com/tr/networking-iot-servers/whole-home-mesh-systems/asus-zenwifi/asus-zenwifi-xd5/techspec/", [p(1)]),
  src("synology-tr:DS224plus", "https://www.synology.com/tr-tr/products/DS224%2B", [p(2)]), src("synology-tr:DS224plus-manual", "https://global.download.synology.com/download/Document/Hardware/HIG/DiskStation/24-year/DS224%2B/trk/DS224p_HIG_trk.pdf", [p(2)], "MANUAL"), src("qnap-tr:TS-264-8G", "https://www.qnap.com/tr-tr/product/ts-264", [p(3)]),
  src("samsung-tr:MU-PG1T0B-WW", "https://www.samsung.com/tr/memory-storage/portable-ssd/portable-ssd-t9-1tb-black-mu-pg1t0b-ww/", [p(4)]), src("wd-tr:SDSSDE61-1T00-G25", "https://www.westerndigital.com/tr-tr/products/portable-drives/sandisk-extreme-usb-3-2-ssd", [p(5)]), src("sandisk-global:SDSSDE61-datasheet", "https://documents.westerndigital.com/content/dam/doc-library/en_us/assets/public/sandisk/product/portable-drives/extreme-portable-ssd/data-sheet-extreme-portable-ssd.pdf", [p(5)], "INTERNATIONAL_BOUNDED", "NONE", "GLOBAL"),
  src("epson-tr:C11CJ67435", "https://www.epson.com.tr/tr_TR/%C3%BCr%C3%BCnler/yaz%C4%B1c%C4%B1lar/inkjet/t%C3%BCketici/ecotank-l3276/p/C11CJ67435", [p(6)]), src("hp-tr:7MD72A", "https://support.hp.com/tr-tr/product/details/null/model/30190589", [p(7)]),
  src("logitech-tr:Brio500-960-001422", "https://www.logitech.com/tr-tr/shop/p/brio-500-webcam.960-001422", [p(8)]), src("asus-tr:Webcam-C3", "https://www.asus.com/tr/accessories/streaming-kits/all-series/asus-webcam-c3/techspec/", [p(9)]), src("asus-tr:Webcam-C3-manual", "https://dlcdnets.asus.com/pub/ASUS/Accessory/Manual/Turkish_Manual_Webcam.pdf?model=ASUS+Webcam+C3", [p(9)], "MANUAL"),
  src("logitech-tr:Z207-980-001295", "https://www.logitech.com/tr-tr/shop/p/z207-stereo-speakers-bluetooth.980-001295", [p(10)]), src("logitech-global:Z207-manual", "https://www.logitech.com/assets/65728/2/z207-qsg.pdf", [p(10)], "MANUAL", "NONE", "GLOBAL"), src("edifier-tr:R1280DBs", "https://www.edifierturkiye.com/edifier-r1280dbs-subwoofer-cikisli-optik-girisli-4-bass-unitesi-multi-media-2.0-aktif-v.5.0-bluetooth-hoparlor-42w-rms-", [p(11)]), src("edifier-global:R1280DBs", "https://www.edifier.com/us/p/bookshelf-speakers/r1280dbs", [p(11)], "INTERNATIONAL_BOUNDED", "NONE", "GLOBAL"),
];
type FactInput = readonly [string, string | number | boolean, string?]; const input: readonly (readonly FactInput[])[] = [
  [["wifi_generation", "Wi-Fi 7"], ["unit_count", 2], ["regional_revision", "EU V1"], ["aggregate_class", "BE3600"], ["ethernet_ports_per_unit", "2 x 2.5GbE"]],
  [["wifi_generation", "Wi-Fi 6"], ["unit_count", 2], ["regional_variant", "XD5 W-2-PK"], ["aggregate_class", "AX3000"], ["ethernet_ports_per_unit", "2 x 1GbE"]],
  [["bay_count", 2], ["disk_population", "diskless"], ["memory_gb", 2, "GB"], ["cpu", "Intel Celeron J4125"], ["network_ports", "2 x 1GbE"]],
  [["bay_count", 2], ["disk_population", "diskless"], ["memory_gb", 8, "GB"], ["cpu", "Intel Celeron N5095"], ["network_ports", "2 x 2.5GbE"]],
  [["media_type", "NVMe portable SSD"], ["capacity_tb", 1, "TB"], ["interface", "USB 3.2 Gen 2x2 20Gbps"], ["max_read_mbps", 2000, "MB/s"], ["warranty_years", 5, "years"]],
  [["media_type", "portable SSD"], ["capacity_tb", 1, "TB"], ["interface", "USB 3.2 Gen 2 10Gbps"], ["max_read_mbps", 1050, "MB/s"], ["ingress_rating", "IP65"]],
  [["print_technology", "refillable ink tank"], ["color_capability", true], ["functions", "print/scan/copy"], ["duplex", "manual"], ["connectivity", "Wi-Fi/Wi-Fi Direct/USB"]],
  [["print_technology", "laser"], ["color_capability", false], ["functions", "print/scan/copy"], ["duplex", "manual"], ["connectivity", "Wi-Fi/USB"]],
  [["resolution_fps", "1080p30/720p60"], ["field_of_view", "90/78/65 degrees"], ["connectivity", "attached USB-C"], ["focus", "autofocus"], ["microphones", "dual noise-reducing"]],
  [["resolution_fps", "1080p30"], ["field_of_view", "wide"], ["connectivity", "USB 2.0 wired"], ["focus", "fixed"], ["microphones", "dual beamforming"]],
  [["channel_configuration", "2.0"], ["connectivity", "Bluetooth and 3.5mm"], ["included_subwoofer", false], ["power_rms_w", 5, "W"], ["device_switching", "two Bluetooth devices"]],
  [["channel_configuration", "2.0"], ["connectivity", "Bluetooth 5.0/optical/coaxial/dual RCA"], ["included_subwoofer", false], ["power_rms_w", 42, "W"], ["subwoofer_output", true]],
];
const slug = (v: string) => v.replaceAll(/[^a-zA-Z0-9]+/gu, "-").replaceAll(/^-|-$/gu, "").toLowerCase(); const tech = (product: Product) => sources.find(row => row.exactProductIds.includes(product.exactProductId) && row.authority === "TECHNICAL")!;
const comparativeFacts: Wave3EvidenceRelease["comparativeFacts"] = products.flatMap((product, pi) => input[pi].map(([key, value, unit], fi) => ({ factId: `wave3-fact:${slug(product.exactProductId)}:${key}:${fi + 1}`, exactProductId: product.exactProductId, categoryId: product.categoryId, key, value, ...(unit ? { unit } : {}), sourceId: tech(product).sourceId, locator: "Exact official product/specification field within the cited source scope", decisionEligibility: "DRAFT_POLICY_INPUT", conflictState: "CLEAR" }))) as Wave3EvidenceRelease["comparativeFacts"];
const manualInput = [
  { manualId: "wave3-manual:synology-ds224plus-tr", exactProductId: p(2), sourceUri: sources[4].uri, localPath: "data/production/electronics/wave-3-evidence/manuals/synology-ds224plus-tr.pdf", locators: ["1.1 Package contents", "1.5 Hardware specifications", "2 Hardware setup"] },
  { manualId: "wave3-manual:asus-webcam-c3-tr", exactProductId: p(9), sourceUri: sources[13].uri, localPath: "data/production/electronics/wave-3-evidence/manuals/asus-webcam-c3-tr.pdf", locators: ["Package contents", "Hardware installation", "Safety notices"] },
  { manualId: "wave3-manual:logitech-z207-qsg", exactProductId: p(10), sourceUri: sources[15].uri, localPath: "data/production/electronics/wave-3-evidence/manuals/logitech-z207-qsg.pdf", locators: ["Power and 3.5mm setup", "Bluetooth pairing", "Control layout"] },
] as const;
const manuals: Wave3EvidenceRelease["manuals"] = manualInput.map(row => ({ ...row, sha256: sha(readFileSync(path.join(root, row.localPath))), layer: "L9_ADVISOR_KNOWLEDGE" }));
const categoryReadiness: Wave3EvidenceRelease["categoryReadiness"] = ELECTRONICS_WAVE_3_CATEGORY_IDS.map(categoryId => ({ categoryId, candidateCount: products.filter(row => row.categoryId === categoryId).length, manufacturerCount: new Set(products.filter(row => row.categoryId === categoryId).map(row => row.manufacturer)).size, comparableFieldCount: new Set(comparativeFacts.filter(row => row.categoryId === categoryId).map(row => row.key)).size, readiness: "DECISION_EVIDENCE_READY", reasons: ["EXACT_TR_IDENTITIES_WITH_MULTI_MANUFACTURER_COMPARATIVE_EVIDENCE"], policyStatus: "REVIEW_REQUIRED_NON_ACTIVE" }));
const decisionProjections: Wave3EvidenceRelease["decisionProjections"] = products.map(row => ({ projectionId: `wave3-projection:${slug(row.exactProductId)}`, exactProductId: row.exactProductId, eligibleFactIds: comparativeFacts.filter(fact => fact.exactProductId === row.exactProductId).map(fact => fact.factId), status: "DRAFT_NON_ACTIVE", unknownTreatment: "NEUTRAL_FAIL_CLOSED", rankingWeights: "NONE" }));
const unknownsAndConflicts: Wave3EvidenceRelease["unknownsAndConflicts"] = products.flatMap(row => ["L7_GOVERNED_EXPERIENCE_ABSENT", "GOVERNED_MEDIA_REUSE_PROVENANCE_ABSENT", ...(manuals.some(manual => manual.exactProductId === row.exactProductId) ? [] : ["EXACT_MANUAL_NOT_CHECKSUM_BOUND"]), ...(row.exactProductId.includes("xd5") ? ["HARDWARE_REVISION_NOT_SEPARATELY_PUBLISHED_REVISION_SENSITIVE_CLAIMS_BLOCKED"] : [])].map(code => ({ exactProductId: row.exactProductId, code, effect: "NEUTRAL_FAIL_CLOSED" })));
const boundaries = { l7Experience: "ABSENT", mediaImported: false, l10YEffect: "NONE", amazonStatusEffect: "NONE", activationPerformed: false, registryChanged: false, runtimeChanged: false, databaseChanged: false, pointerChanged: false, deploymentPerformed: false } as const;
const release: Wave3EvidenceRelease = { schemaVersion: "electronics-wave-3-evidence/v1", releaseVersion: ELECTRONICS_WAVE_3_VERSION, parent: { releaseDigest: ELECTRONICS_WAVE_3_PARENT_DIGEST, relationship: "IMMUTABLE_CHILD_NO_OVERWRITE" }, research: { amazonFirstDigest: amazonManifest.payloadDigest, amazonRole: "DISCOVERY_ONLY_ZERO_DECISION_EFFECT", internationalRole: "TECHNICAL_GAP_FILL_ONLY_NOT_TR_APPLICABILITY" }, products, sources, comparativeFacts, manuals, categoryReadiness, decisionProjections, unknownsAndConflicts, carryForward: { scope: "WAVES_1_AND_2_PARENT_CHAIN", parentReleaseDigest: ELECTRONICS_WAVE_3_PARENT_DIGEST, parentBytesUnmodified: true }, boundaries };
const issues = validateWave3EvidenceClosure(release); if (issues.length) throw new Error(`WAVE_3_INVALID:${issues.join(",")}`);
const comparison = { schemaVersion: "electronics-wave-3-comparison/v1", categories: categoryReadiness.map(row => ({ ...row, exactProductIds: products.filter(product => product.categoryId === row.categoryId).map(product => product.exactProductId), fields: [...new Set(comparativeFacts.filter(fact => fact.categoryId === row.categoryId).map(fact => fact.key))].sort() })) };
const policyProposal = { schemaVersion: "electronics-wave-3-policy-input/v1", status: "NON_ACTIVE_CATEGORY_REVIEW_INPUT", categories: comparison.categories.map(row => ({ categoryId: row.categoryId, eligibleFields: row.fields, rankingWeights: "NONE", sufficiencyThresholds: "UNDEFINED_PENDING_PRODUCT_REVIEW", unknownTreatment: "NEUTRAL_FAIL_CLOSED", commerceEffect: "NONE" })) };
const reconciliation = { schemaVersion: "electronics-wave-3-reconciliation/v1", parentReleaseDigest: ELECTRONICS_WAVE_3_PARENT_DIGEST, parentBytesUnmodified: true, parentArtifactPath: path.relative(root, parentPath), amazonFirstDigest: amazonManifest.payloadDigest, wave3ExactProductIds: products.map(row => row.exactProductId).sort(), duplicateExactProductIds: [], activationEffect: "NONE" };
const output = path.join(root, "data/production/electronics/wave-3-evidence/releases", ELECTRONICS_WAVE_3_VERSION); mkdirSync(output, { recursive: true }); const artifactRaw = { "evidence-release.json": pretty(release), "comparative-matrix.json": pretty(comparison), "policy-input-proposal.json": pretty(policyProposal), "reconciliation.json": pretty(reconciliation) }; for (const [name, raw] of Object.entries(artifactRaw)) writeFileSync(path.join(output, name), raw);
const manifest = { schemaVersion: "electronics-wave-3-manifest/v1", workUnitId: "WU-ELECTRONICS-WAVE-3-MULTI-CANDIDATE-EVIDENCE-CLOSURE-01", releaseVersion: ELECTRONICS_WAVE_3_VERSION, verdict: "IMPLEMENTED", parentReleaseDigest: ELECTRONICS_WAVE_3_PARENT_DIGEST, counts: { categories: 6, products: products.length, manufacturers: new Set(products.map(row => row.manufacturer)).size, sources: sources.length, comparativeFacts: comparativeFacts.length, manuals: manuals.length, unknowns: unknownsAndConflicts.length }, readiness: { DECISION_EVIDENCE_READY: 6, POLICY_REVIEW_REQUIRED: 0, INFORMATION_ONLY: 0, BLOCKED_EVIDENCE: 0 }, artifacts: Object.fromEntries(Object.entries(artifactRaw).map(([name, raw]) => [name, sha(raw)])), activation: boundaries }; writeFileSync(path.join(output, "manifest.json"), pretty(manifest)); console.log(JSON.stringify({ output, ...manifest.counts, releaseDigest: manifest.artifacts["evidence-release.json"] }));
