import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ELECTRONICS_WAVE_1_CATEGORY_IDS, ELECTRONICS_WAVE_1_EVIDENCE_VERSION, validateWave1EvidenceRelease, type Wave1EvidenceRelease, type Wave1Readiness } from "../features/electronics/wave1EvidenceClosure";

const root = process.cwd();
const parentDir = path.join(root, "data/production/electronics/richness/releases/ELECTRONICS-CATALOG-RICHNESS-TR-v0.1");
const parent = JSON.parse(readFileSync(path.join(parentDir, "catalog-release.json"), "utf8"));
const parentManifest = JSON.parse(readFileSync(path.join(parentDir, "manifest.json"), "utf8"));
const parentDigest = "sha256:091968ca447271d29ccd15d50cf398c4b896ea1de410731ec1a91ec88241dd91";
if (parent.releaseDigest !== parentDigest || parentManifest.activation.performed) throw new Error("PARENT_RICHNESS_AUTHORITY_MISMATCH");

type Product = Wave1EvidenceRelease["products"][number];
const priorCategory = new Map(parent.offerings.map((row: { offeringId: string }) => [row.offeringId, row.offeringId.split(":")[1].toUpperCase().replaceAll("-", "_")]));
const priorProducts: Product[] = parent.offerings.filter((row: { offeringId: string }) => ELECTRONICS_WAVE_1_CATEGORY_IDS.includes(priorCategory.get(row.offeringId) as typeof ELECTRONICS_WAVE_1_CATEGORY_IDS[number])).map((row: { offeringId: string; identity: { manufacturer: string; identifiers: { manufacturerModelCode: string }; configuration: string } }) => ({ exactProductId: row.offeringId, categoryId: priorCategory.get(row.offeringId)!, manufacturer: row.identity.manufacturer, manufacturerModelCode: row.identity.identifiers.manufacturerModelCode, configurationIdentity: row.identity.configuration, trApplicabilitySourceIds: parent.sources.filter((source: { sourceId: string }) => parent.evidence.some((ev: { sourceId: string; offeringIds: string[] }) => ev.sourceId === source.sourceId && ev.offeringIds.includes(row.offeringId))).map((source: { sourceId: string }) => source.sourceId), lifecycle: "FROZEN_CANDIDATE" }));
const additions: Product[] = [
  { exactProductId: "electronics:laptop:lenovo:83k20077tr", categoryId: "LAPTOP", manufacturer: "Lenovo", manufacturerModelCode: "83K20077TR", configurationIdentity: "Lenovo|IdeaPad Slim 3 16IRH10|83K20077TR|Core i5-13420H|16GB|1TB SSD|16in WUXGA IPS|FreeDOS|TR", trApplicabilitySourceIds: ["lenovo-tr-support:83K20077TR", "amazon-tr:B0-83K20077TR"], lifecycle: "FROZEN_CANDIDATE" },
  { exactProductId: "electronics:laptop:lenovo:83k2001vtr", categoryId: "LAPTOP", manufacturer: "Lenovo", manufacturerModelCode: "83K2001VTR", configurationIdentity: "Lenovo|IdeaPad Slim 3 16IRH10|83K2001VTR|Core i7-13620H|16GB|1TB SSD|16in WUXGA IPS|FreeDOS|TR", trApplicabilitySourceIds: ["lenovo-tr-support:83K2001VTR", "mediamarkt-tr:83K2001VTR"], lifecycle: "FROZEN_CANDIDATE" },
  { exactProductId: "electronics:television:lg:oled55b65la", categoryId: "TELEVISION", manufacturer: "LG", manufacturerModelCode: "OLED55B65LA", configurationIdentity: "LG|OLED B6 2026|OLED55B65LA|55in|4K|120Hz VRR|webOS26|TR", trApplicabilitySourceIds: ["lg-tr:OLED55B65LA"], lifecycle: "FROZEN_CANDIDATE" },
  { exactProductId: "electronics:e-reader:kobo:n428", categoryId: "E_READER", manufacturer: "Rakuten Kobo", manufacturerModelCode: "N428", configurationIdentity: "Rakuten Kobo|Libra Colour|N428|7in Colour|Page Buttons|Stylus Compatible|TR", trApplicabilitySourceIds: ["kobo-tr:N428"], lifecycle: "FROZEN_CANDIDATE" },
  { exactProductId: "electronics:e-reader:kobo:n367", categoryId: "E_READER", manufacturer: "Rakuten Kobo", manufacturerModelCode: "N367", configurationIdentity: "Rakuten Kobo|Clara Colour|N367|6in Colour|TR", trApplicabilitySourceIds: ["kobo-tr:N367"], lifecycle: "FROZEN_CANDIDATE" },
];
const products = [...priorProducts, ...additions].sort((a, b) => a.exactProductId.localeCompare(b.exactProductId, "en"));

const reusedSources = parent.sources.filter((source: { sourceId: string }) => priorProducts.some(product => product.trApplicabilitySourceIds.includes(source.sourceId))).map((source: { sourceId: string; uri: string }) => ({ sourceId: source.sourceId, uri: source.uri, market: "TR", authority: "TECHNICAL" as const, exactProductIds: priorProducts.filter(product => product.trApplicabilitySourceIds.includes(source.sourceId)).map(product => product.exactProductId), trApplicabilityAuthority: "EXACT" as const, decisionAuthority: "NONE" as const }));
const sources: Wave1EvidenceRelease["sources"] = [...reusedSources,
  { sourceId: "lenovo-tr-support:83K20077TR", uri: "https://pcsupport.lenovo.com/tr/tr/products/LAPTOPS-AND-NETBOOKS/IDEAPAD-S-SERIES-NETBOOKS/IDEAPAD-SLIM-3-16IRH10/83K2/83K20077TR", market: "TR", authority: "TR_APPLICABILITY", exactProductIds: ["electronics:laptop:lenovo:83k20077tr"], trApplicabilityAuthority: "EXACT", decisionAuthority: "NONE" },
  { sourceId: "lenovo-tr-support:83K2001VTR", uri: "https://pcsupport.lenovo.com/tr/tr/products/laptops-and-netbooks/ideapad-s-series-netbooks/ideapad-slim-3-16irh10/83k2/83k2001vtr", market: "TR", authority: "TR_APPLICABILITY", exactProductIds: ["electronics:laptop:lenovo:83k2001vtr"], trApplicabilityAuthority: "EXACT", decisionAuthority: "NONE" },
  { sourceId: "lenovo-psref:83K20077TR", uri: "https://psref.lenovo.com/Detail/IdeaPad_Slim_3_16IRH10?M=83K20077TR", market: "GLOBAL", authority: "INTERNATIONAL_BOUNDED", exactProductIds: ["electronics:laptop:lenovo:83k20077tr"], trApplicabilityAuthority: "NONE", decisionAuthority: "NONE" },
  { sourceId: "lenovo-psref:83K2001VTR", uri: "https://psref.lenovo.com/Detail/IdeaPad_Slim_3_16IRH10?M=83K2001VTR", market: "GLOBAL", authority: "INTERNATIONAL_BOUNDED", exactProductIds: ["electronics:laptop:lenovo:83k2001vtr"], trApplicabilityAuthority: "NONE", decisionAuthority: "NONE" },
  { sourceId: "amazon-tr:B0-83K20077TR", uri: "https://www.amazon.com.tr/s?k=83K20077TR", market: "TR", authority: "COMMERCE_DISCOVERY", exactProductIds: ["electronics:laptop:lenovo:83k20077tr"], trApplicabilityAuthority: "NONE", decisionAuthority: "NONE" },
  { sourceId: "mediamarkt-tr:83K2001VTR", uri: "https://www.mediamarkt.com.tr/tr/product/_lenovo-ideapad-slim-3-16irh10-83k2001vtr-intel-core-i7-13620h-16-gb-ram-1-tb-ssd-uhd-graphics-16-inc-freedos-laptop-gri-161583986.html", market: "TR", authority: "COMMERCE_DISCOVERY", exactProductIds: ["electronics:laptop:lenovo:83k2001vtr"], trApplicabilityAuthority: "NONE", decisionAuthority: "NONE" },
  { sourceId: "lg-tr:OLED55B65LA", uri: "https://www.lg.com/tr/tv-soundbar/oled/oled55b65la/", market: "TR", authority: "TECHNICAL", exactProductIds: ["electronics:television:lg:oled55b65la"], trApplicabilityAuthority: "EXACT", decisionAuthority: "NONE" },
  { sourceId: "kobo-tr:N428", uri: "https://help.kobo.com/hc/tr/articles/360019676973-Kobo-eOkuyucunuzu-veya-Kobo-tabletinizi-tan%C4%B1mlay%C4%B1n", market: "TR", authority: "TECHNICAL", exactProductIds: ["electronics:e-reader:kobo:n428"], trApplicabilityAuthority: "EXACT", decisionAuthority: "NONE" },
  { sourceId: "kobo-tr:N367", uri: "https://help.kobo.com/hc/tr/articles/18001606982679-Kobo-Clara-Colour", market: "TR", authority: "TECHNICAL", exactProductIds: ["electronics:e-reader:kobo:n367"], trApplicabilityAuthority: "EXACT", decisionAuthority: "NONE" },
  { sourceId: "kobo-manual:N428", uri: "https://cdn.kobo.com/downloads/magento/userguides/N428-Legal-and-Safety/n428regandsafetyinfo-english20240430.pdf", market: "GLOBAL", authority: "MANUAL_L9", exactProductIds: ["electronics:e-reader:kobo:n428"], trApplicabilityAuthority: "NONE", decisionAuthority: "NONE" },
  { sourceId: "kobo-manual:N367", uri: "https://cdn.kobo.com/downloads/magento/userguides/legalAndSafety/N367-Legal-and-Safety/n367regandsafetyinfo-turkish2024430.pdf", market: "TR", authority: "MANUAL_L9", exactProductIds: ["electronics:e-reader:kobo:n367"], trApplicabilityAuthority: "EXACT", decisionAuthority: "NONE" },
];

type FactSeed = readonly [string, string, string | number, string?, "DRAFT_POLICY_INPUT"?];
const specs: Record<string, readonly FactSeed[]> = {
  "electronics:smartphone:samsung:sm-a266bzkctur": [["memory_gb", "samsung-tr:SM-A266BZKCTUR", 8, "GB", "DRAFT_POLICY_INPUT"], ["storage_gb", "samsung-tr:SM-A266BZKCTUR", 256, "GB", "DRAFT_POLICY_INPUT"], ["cellular_generation", "samsung-tr:SM-A266BZKCTUR", "5G"]],
  "electronics:smartphone:samsung:sm-a366bzkgtur": [["memory_gb", "source:smartphone:1", 8, "GB", "DRAFT_POLICY_INPUT"], ["storage_gb", "source:smartphone:1", 256, "GB", "DRAFT_POLICY_INPUT"], ["cellular_generation", "source:smartphone:1", "5G"]],
  "electronics:tablet:samsung:sm-x730nzsptur": [["storage_gb", "source:tablet:5", 256, "GB", "DRAFT_POLICY_INPUT"], ["display_inches", "source:tablet:5", 11, "in", "DRAFT_POLICY_INPUT"], ["connectivity", "source:tablet:5", "Wi-Fi"]],
  "electronics:tablet:samsung:sm-x520nzsptur": [["storage_gb", "source:tablet:6", 256, "GB", "DRAFT_POLICY_INPUT"], ["display_inches", "source:tablet:6", 10.9, "in", "DRAFT_POLICY_INPUT"], ["connectivity", "source:tablet:6", "Wi-Fi"]],
  "electronics:monitor:samsung:ls27f612eauxuf": [["display_inches", "source:monitor:7", 27, "in", "DRAFT_POLICY_INPUT"], ["resolution", "source:monitor:7", "QHD", undefined, "DRAFT_POLICY_INPUT"], ["refresh_hz", "source:monitor:7", 100, "Hz", "DRAFT_POLICY_INPUT"]],
  "electronics:monitor:samsung:ls27c902pauxuf": [["display_inches", "source:monitor:8", 27, "in", "DRAFT_POLICY_INPUT"], ["resolution", "source:monitor:8", "5K", undefined, "DRAFT_POLICY_INPUT"]],
  "electronics:television:next:ye-55gfsg8-qled": [["display_inches", "next-tr:YE-55GFSG8-QLED", 55, "in", "DRAFT_POLICY_INPUT"], ["resolution", "next-tr:YE-55GFSG8-QLED", "4K", undefined, "DRAFT_POLICY_INPUT"], ["platform", "next-tr:YE-55GFSG8-QLED", "Google TV"]],
  "electronics:laptop:lenovo:83k20077tr": [["processor", "lenovo-psref:83K20077TR", "Intel Core i5-13420H", undefined, "DRAFT_POLICY_INPUT"], ["memory_gb", "lenovo-psref:83K20077TR", 16, "GB", "DRAFT_POLICY_INPUT"], ["storage_gb", "lenovo-psref:83K20077TR", 1024, "GB", "DRAFT_POLICY_INPUT"], ["display", "lenovo-psref:83K20077TR", "16in 1920x1200 IPS"]],
  "electronics:laptop:lenovo:83k2001vtr": [["processor", "lenovo-psref:83K2001VTR", "Intel Core i7-13620H", undefined, "DRAFT_POLICY_INPUT"], ["memory_gb", "lenovo-psref:83K2001VTR", 16, "GB", "DRAFT_POLICY_INPUT"], ["storage_gb", "lenovo-psref:83K2001VTR", 1024, "GB", "DRAFT_POLICY_INPUT"], ["display", "lenovo-psref:83K2001VTR", "16in 1920x1200 IPS"]],
  "electronics:television:lg:oled55b65la": [["display_inches", "lg-tr:OLED55B65LA", 55, "in", "DRAFT_POLICY_INPUT"], ["resolution", "lg-tr:OLED55B65LA", "4K", undefined, "DRAFT_POLICY_INPUT"], ["refresh_hz", "lg-tr:OLED55B65LA", 120, "Hz", "DRAFT_POLICY_INPUT"], ["panel", "lg-tr:OLED55B65LA", "OLED"]],
  "electronics:e-reader:kobo:n428": [["display_inches", "kobo-tr:N428", 7, "in", "DRAFT_POLICY_INPUT"], ["display_color", "kobo-tr:N428", "COLOR", undefined, "DRAFT_POLICY_INPUT"], ["page_turn_buttons", "kobo-tr:N428", "PRESENT"], ["stylus_compatible", "kobo-tr:N428", "PRESENT"]],
  "electronics:e-reader:kobo:n367": [["display_inches", "kobo-tr:N367", 6, "in", "DRAFT_POLICY_INPUT"], ["display_color", "kobo-tr:N367", "COLOR", undefined, "DRAFT_POLICY_INPUT"]],
};
const id = (value: string) => value.replaceAll(/[^a-zA-Z0-9]+/gu, "-").replaceAll(/^-|-$/gu, "").toLowerCase();
const comparativeFacts = products.flatMap(product => (specs[product.exactProductId] ?? []).map(([key, sourceId, value, unit, eligibility], index) => ({ factId: `w1-fact:${id(product.exactProductId)}:${key}:${index + 1}`, exactProductId: product.exactProductId, categoryId: product.categoryId, key, value, ...(unit ? { unit } : {}), sourceId, locator: "Exact product page/support/PSREF field matching the recorded model code", decisionEligibility: eligibility ?? "EXPLANATION_ONLY" as const, conflictState: "CLEAR" as const })));
const capabilities = products.map(product => { const facts = comparativeFacts.filter(fact => fact.exactProductId === product.exactProductId); return { capabilityId: `w1-cap:${id(product.exactProductId)}`, exactProductId: product.exactProductId, factIds: facts.map(fact => fact.factId), state: facts.length ? "PRESENT" as const : "UNKNOWN" as const, directCandidateEffect: "NONE" as const }; });
const factKeys: Record<string, string[]> = { SMARTPHONE: ["memory_gb", "storage_gb", "cellular_generation"], LAPTOP: ["processor", "memory_gb", "storage_gb", "display"], TABLET: ["storage_gb", "display_inches", "connectivity"], MONITOR: ["display_inches", "resolution", "refresh_hz"], TELEVISION: ["display_inches", "resolution", "refresh_hz", "panel", "platform"], E_READER: ["display_inches", "display_color", "page_turn_buttons", "stylus_compatible"] };
const readiness: Record<string, { status: Wave1Readiness; blockers: string[] }> = { SMARTPHONE: { status: "POLICY_REVIEW_REQUIRED", blockers: ["Single-manufacturer set", "Display, camera, battery, support-lifecycle and privacy facts incomplete"] }, LAPTOP: { status: "POLICY_REVIEW_REQUIRED", blockers: ["Single-family/single-manufacturer set", "Build-to-order and OS mutation risk requires strict exact-MTM policy"] }, TABLET: { status: "POLICY_REVIEW_REQUIRED", blockers: ["Single-manufacturer set", "Memory, display, battery and accessory-bundle evidence incomplete"] }, MONITOR: { status: "POLICY_REVIEW_REQUIRED", blockers: ["Single-manufacturer set", "S9 refresh, ports, panel behavior and ergonomics incomplete"] }, TELEVISION: { status: "DECISION_EVIDENCE_READY", blockers: ["Draft category policy review still required before runtime use"] }, E_READER: { status: "DECISION_EVIDENCE_READY", blockers: ["Draft category policy review still required before runtime use"] } };
const manuals: Wave1EvidenceRelease["manuals"] = [
  { manualId: "manual:kobo:n428:safety", exactProductId: "electronics:e-reader:kobo:n428", path: "manuals/n428-safety-en.pdf", sourceUri: sources.find(row => row.sourceId === "kobo-manual:N428")!.uri, sha256: "sha256:12b4c1937e9e41eafd38c0cb45b2c1a685cebc2475335c06d6921c6a34d47e40", pages: 10, locator: "Pages 1-10; model N428 legal and safety scope", language: "en", decisionAuthority: "NONE" },
  { manualId: "manual:kobo:n367:safety", exactProductId: "electronics:e-reader:kobo:n367", path: "manuals/n367-safety-tr.pdf", sourceUri: sources.find(row => row.sourceId === "kobo-manual:N367")!.uri, sha256: "sha256:b39fef7b06e9f5e42a84d1d24eb835cbfb66ec5258e031ef316a95681a70b8a4", pages: 9, locator: "Pages 1-9; model N367 Turkish legal and safety scope", language: "tr", decisionAuthority: "NONE" },
];
const release: Wave1EvidenceRelease = { schemaVersion: "electronics-wave-1-evidence-closure/v1", releaseVersion: ELECTRONICS_WAVE_1_EVIDENCE_VERSION, parentRichnessDigest: parentDigest, products, sources, comparativeFacts, capabilities, usageSemantics: ELECTRONICS_WAVE_1_CATEGORY_IDS.map(categoryId => ({ semanticId: `w1-semantic:${categoryId.toLowerCase()}`, categoryId, factKeys: factKeys[categoryId], status: "DRAFT_NON_ACTIVE" })), needs: ELECTRONICS_WAVE_1_CATEGORY_IDS.map(categoryId => ({ needId: `w1-need:${categoryId.toLowerCase()}:comparison`, categoryId, evidenceKeys: factKeys[categoryId], decisionUse: "NONE_DRAFT_INPUT" })), personaSignals: ELECTRONICS_WAVE_1_CATEGORY_IDS.map(categoryId => ({ signalId: `w1-persona:${categoryId.toLowerCase()}`, categoryId, decisionUse: "NONE", directCandidateEffect: "NONE" })), dailyLifeInterpretations: products.map(product => ({ interpretationId: `w1-interpretation:${id(product.exactProductId)}`, exactProductId: product.exactProductId, factIds: comparativeFacts.filter(fact => fact.exactProductId === product.exactProductId).slice(0, 2).map(fact => fact.factId), text: "Recorded dimensions can support transparent follow-up questions; they do not establish suitability or superiority without an approved category policy.", technicalTruthAuthority: "NONE", directCandidateEffect: "NONE" })), decisionProjections: products.map(product => ({ projectionId: `w1-projection:${id(product.exactProductId)}`, exactProductId: product.exactProductId, eligibleFactIds: comparativeFacts.filter(fact => fact.exactProductId === product.exactProductId && fact.decisionEligibility === "DRAFT_POLICY_INPUT").map(fact => fact.factId), unknownTreatment: "NEUTRAL_FAIL_CLOSED", status: "DRAFT_NON_ACTIVE" })), manuals, categoryReadiness: ELECTRONICS_WAVE_1_CATEGORY_IDS.map(categoryId => ({ categoryId, candidateCount: products.filter(product => product.categoryId === categoryId).length, manufacturerCount: new Set(products.filter(product => product.categoryId === categoryId).map(product => product.manufacturer)).size, readiness: readiness[categoryId].status, blockers: readiness[categoryId].blockers })), unknownsAndConflicts: products.flatMap(product => ["EXACT_WARRANTY_SCOPE_INCOMPLETE", "GOVERNED_MEDIA_REUSE_PROVENANCE_ABSENT", "L7_GOVERNED_EXPERIENCE_ABSENT", ...(readiness[product.categoryId].status === "DECISION_EVIDENCE_READY" ? [] : ["CATEGORY_COMPARATIVE_EVIDENCE_OR_DIVERSITY_INCOMPLETE"])].map(code => ({ exactProductId: product.exactProductId, code, effect: "NEUTRAL_FAIL_CLOSED" as const }))), boundaries: { l7Experience: "ABSENT", l10YEffect: "NONE", amazonStatusEffect: "NONE", mediaDecisionAuthority: "NONE", activationPerformed: false } };
const issues = validateWave1EvidenceRelease(release); if (issues.length) throw new Error(`WAVE1_INVALID:${issues.join(",")}`);
for (const manual of manuals) { const raw = readFileSync(path.join(root, "data/production/electronics/wave-1-evidence/releases", ELECTRONICS_WAVE_1_EVIDENCE_VERSION, manual.path)); const actual = `sha256:${createHash("sha256").update(raw).digest("hex")}`; if (actual !== manual.sha256) throw new Error(`MANUAL_DIGEST_MISMATCH:${manual.manualId}`); }
const matrix = { schemaVersion: "electronics-wave-1-comparative-matrix/v1", releaseVersion: ELECTRONICS_WAVE_1_EVIDENCE_VERSION, categories: ELECTRONICS_WAVE_1_CATEGORY_IDS.map(categoryId => ({ categoryId, fields: factKeys[categoryId], rows: products.filter(product => product.categoryId === categoryId).map(product => ({ exactProductId: product.exactProductId, manufacturer: product.manufacturer, values: Object.fromEntries(comparativeFacts.filter(fact => fact.exactProductId === product.exactProductId).map(fact => [fact.key, { value: fact.value, unit: fact.unit ?? null, eligibility: fact.decisionEligibility }])) })) })) };
const policyInputs = { schemaVersion: "electronics-wave-1-policy-input-proposal/v1", status: "DRAFT_NON_ACTIVE", categories: ELECTRONICS_WAVE_1_CATEGORY_IDS.map(categoryId => ({ categoryId, questionInputs: factKeys[categoryId], sufficiencyThresholds: "UNDEFINED_REQUIRES_CATEGORY_REVIEW", rankingWeights: "NONE", unknownTreatment: "NEUTRAL_FAIL_CLOSED", amazonAvailabilityEffect: "NONE" })) };
const output = path.join(root, "data/production/electronics/wave-1-evidence/releases", ELECTRONICS_WAVE_1_EVIDENCE_VERSION); mkdirSync(output, { recursive: true });
const stable = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`; const sha = (raw: string | Buffer) => `sha256:${createHash("sha256").update(raw).digest("hex")}`;
const artifacts = { "evidence-release.json": stable(release), "comparative-matrix.json": stable(matrix), "policy-input-proposal.json": stable(policyInputs) };
for (const [name, raw] of Object.entries(artifacts)) writeFileSync(path.join(output, name), raw);
const manifest = { schemaVersion: "electronics-wave-1-evidence-manifest/v1", workUnitId: "WU-ELECTRONICS-WAVE-1-MULTI-CANDIDATE-EVIDENCE-CLOSURE-01", releaseVersion: ELECTRONICS_WAVE_1_EVIDENCE_VERSION, verdict: "PARTIAL", parent: { releaseDigest: parentDigest, relationship: "IMMUTABLE_CHILD_NO_OVERWRITE" }, counts: { categories: 6, products: products.length, manufacturers: new Set(products.map(product => product.manufacturer)).size, sources: sources.length, comparativeFacts: comparativeFacts.length, manuals: manuals.length, unknowns: release.unknownsAndConflicts.length }, readiness: Object.fromEntries(["DECISION_EVIDENCE_READY", "POLICY_REVIEW_REQUIRED", "INFORMATION_ONLY", "BLOCKED_EVIDENCE"].map(status => [status, release.categoryReadiness.filter(row => row.readiness === status).length])), artifacts: { ...Object.fromEntries(Object.entries(artifacts).map(([name, raw]) => [name, sha(raw)])), ...Object.fromEntries(manuals.map(manual => [manual.path, manual.sha256])) }, activation: { performed: false, registryChanged: false, domainPackChanged: false, databaseChanged: false, runtimeChanged: false, pointerChanged: false, deploymentPerformed: false } };
writeFileSync(path.join(output, "manifest.json"), stable(manifest)); console.log(JSON.stringify({ output, ...manifest.counts, readiness: manifest.readiness, releaseDigest: sha(artifacts["evidence-release.json"]) }));
