import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ELECTRONICS_WAVE_2_CATEGORY_IDS, ELECTRONICS_WAVE_2_PARENT_DIGEST, ELECTRONICS_WAVE_2_VERSION, validateWave2EvidenceClosure, type Wave2EvidenceRelease } from "../features/electronics/wave2EvidenceClosure";

const root = process.cwd(); const pretty = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`; const sha = (raw: string | Buffer) => `sha256:${createHash("sha256").update(raw).digest("hex")}` as `sha256:${string}`;
const parentPath = path.join(root, "data/production/electronics/wave-1-repair/releases/ELECTRONICS-WAVE-1-DIVERSITY-REPAIR-TR-v0.1/repair-release.json");
if (sha(readFileSync(parentPath)) !== ELECTRONICS_WAVE_2_PARENT_DIGEST) throw new Error("WAVE_1_PARENT_DIGEST_MISMATCH");
const amazonManifest = JSON.parse(readFileSync(path.join(root, "data/research/electronics/amazon-tr-primary-catalog-01/manifest.json"), "utf8")) as { payloadDigest: `sha256:${string}` };
type Product = Wave2EvidenceRelease["products"][number];
const products: Product[] = [
  { exactProductId: "electronics:headphones:sony:wh1000xm5b-ce7", categoryId: "HEADPHONES", manufacturer: "Sony", modelCode: "WH1000XM5B.CE7", configurationIdentity: "Sony|WH-1000XM5|WH1000XM5B.CE7|Over-ear|Bluetooth|Black|No bundle|TR", trApplicabilitySourceIds: ["sony-tr:WH1000XM5B-CE7"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:headphones:huawei:freebuds-6-black", categoryId: "HEADPHONES", manufacturer: "HUAWEI", modelCode: "FreeBuds 6", configurationIdentity: "HUAWEI|FreeBuds 6|Open-fit true wireless|Bluetooth 5.2|Black|Standard box|TR", trApplicabilitySourceIds: ["huawei-tr:FreeBuds6"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:portable-speaker:jbl:jblflip7blk", categoryId: "PORTABLE_SPEAKER", manufacturer: "JBL", modelCode: "JBLFLIP7BLK", configurationIdentity: "JBL|Flip 7|JBLFLIP7BLK|Portable|Bluetooth|Black|TR", trApplicabilitySourceIds: ["jbl-tr:Flip7", "vatan-tr:JBLFLIP7BLK"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:portable-speaker:sony:srsult10b-ce7", categoryId: "PORTABLE_SPEAKER", manufacturer: "Sony", modelCode: "SRSULT10B.CE7", configurationIdentity: "Sony|ULT FIELD 1|SRSULT10B.CE7|Portable|Bluetooth|Black|TR", trApplicabilitySourceIds: ["sony-tr:SRSULT10"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:soundbar:samsung:hw-q800f-tk", categoryId: "SOUNDBAR", manufacturer: "Samsung", modelCode: "HW-Q800F/TK", configurationIdentity: "Samsung|HW-Q800F/TK|5.1.2|Wireless subwoofer included|Rear speakers excluded|Black|TR", trApplicabilitySourceIds: ["samsung-tr:HW-Q800F-TK"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:soundbar:lg:s70ty", categoryId: "SOUNDBAR", manufacturer: "LG", modelCode: "S70TY", configurationIdentity: "LG|S70TY|3.1.1|Wireless subwoofer included|Rear speakers excluded|Black|TR", trApplicabilitySourceIds: ["lg-tr:S70TY"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:digital-camera:sony:zve10m2b-cec", categoryId: "DIGITAL_CAMERA", manufacturer: "Sony", modelCode: "ZVE10M2B.CEC", configurationIdentity: "Sony|ZV-E10 II|ZVE10M2B.CEC|E mount|Body only|No kit lens|Black|TR", trApplicabilitySourceIds: ["sony-tr:ZVE10M2B-CEC"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:digital-camera:canon:5811c013", categoryId: "DIGITAL_CAMERA", manufacturer: "Canon", modelCode: "5811C013", configurationIdentity: "Canon|EOS R50|5811C013|RF mount|Kit|RF-S 18-45mm F4.5-6.3 IS STM|Black|TR", trApplicabilitySourceIds: ["canon-tr:EOS-R50", "fotografium-tr:5811C013"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:projector:epson:v11ha85040", categoryId: "PROJECTOR", manufacturer: "Epson", modelCode: "V11HA85040", configurationIdentity: "Epson|CO-FH02|V11HA85040|1920x1080|Lamp|TR", trApplicabilitySourceIds: ["epson-tr:V11HA85040"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:projector:samsung:sp-lff3claxxtk", categoryId: "PROJECTOR", manufacturer: "Samsung", modelCode: "SP-LFF3CLAXXTK", configurationIdentity: "Samsung|The Freestyle 2nd Gen|SP-LFF3CLAXXTK|1920x1080|LED|TR", trApplicabilitySourceIds: ["samsung-tr:SP-LFF3CLAXXTK"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:game-console:sony:cfi-7021", categoryId: "GAME_CONSOLE", manufacturer: "Sony Interactive Entertainment", modelCode: "CFI-7021", configurationIdentity: "Sony Interactive Entertainment|PlayStation 5 Pro|CFI-7021|2TB|Disc drive optional excluded|Standard console|TR", trApplicabilitySourceIds: ["playstation-tr:PS5-Pro", "playstation-tr:CFI-7021-manual"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:game-console:microsoft:xbox-series-s-1tb-carbon-black", categoryId: "GAME_CONSOLE", manufacturer: "Microsoft", modelCode: "Xbox Series S 1TB Carbon Black", configurationIdentity: "Microsoft|Xbox Series S|Hardware revision not published|1TB|All-digital|Carbon Black|Standard console|TR", trApplicabilitySourceIds: ["xbox-tr:Series-S"], unresolvedIdentityDiscriminators: ["hardwareRevision"] },
];
type Source = Wave2EvidenceRelease["sources"][number]; const src = (sourceId: string, uri: string, exactProductIds: string[], authority: Source["authority"] = "TECHNICAL", tr: Source["trApplicabilityAuthority"] = "EXACT", market: Source["market"] = "TR"): Source => ({ sourceId, uri, market, authority, exactProductIds, trApplicabilityAuthority: tr, decisionAuthority: "NONE" });
const p = (index: number) => products[index].exactProductId;
const sources: Source[] = [
  src("sony-tr:WH1000XM5B-CE7", "https://www.sony.com.tr/electronics/kafa-bantli-kulakliklar/wh-1000xm5", [p(0)]), src("sony-tr:WH1000XM5-manual", "https://helpguide.sony.net/mdr/wh1000xm5/v1/tr/print.pdf", [p(0)], "MANUAL"),
  src("huawei-tr:FreeBuds6", "https://consumer.huawei.com/tr/headphones/freebuds6/specs/", [p(1)]), src("jbl-tr:Flip7", "https://tr.jbl.com/bluetooth-hoparlorler/", [p(2)], "TECHNICAL", "NONE"), src("vatan-tr:JBLFLIP7BLK", "https://www.vatanbilgisayar.com/jbl-flip7-bluetooth-hoparlor.html", [p(2)], "COMMERCE_DISCOVERY"),
  src("sony-tr:SRSULT10", "https://www.sony.com.tr/wireless-speakers/products/ult-field-1", [p(3)]), src("samsung-tr:HW-Q800F-TK", "https://www.samsung.com/tr/audio-devices/soundbar/q800f-black-hw-q800f-tk/", [p(4)]), src("samsung-tr:HW-Q800F-manual", "https://www.samsung.com/tr/support/model/HW-Q800F/TK/", [p(4)], "MANUAL"), src("lg-tr:S70TY", "https://www.lg.com/tr/sound-bar/s70ty/", [p(5)]),
  src("sony-tr:ZVE10M2B-CEC", "https://www.sony.com.tr/electronics/degistirilebilir-lensli-fotograf-makineleri/zv-e10m2/buy/zve10m2b.cec", [p(6)]), src("canon-tr:EOS-R50", "https://www.canon.com.tr/cameras/eos-r50/", [p(7)], "TECHNICAL", "NONE"), src("fotografium-tr:5811C013", "https://fotografium.com/canon-eos-r50-rf-s-18-45mm-lens-kit", [p(7)], "COMMERCE_DISCOVERY"),
  src("epson-tr:V11HA85040", "https://www.epson.com.tr/projektor/is-egitimi/co-fh02-v11ha85040", [p(8)]), src("samsung-tr:SP-LFF3CLAXXTK", "https://www.samsung.com/tr/projectors/the-freestyle/lff3c-the-freestyle-2nd-gen-sp-lff3claxxtk/", [p(9)]),
  src("playstation-tr:PS5-Pro", "https://www.playstation.com/tr-tr/ps5/ps5-pro/", [p(10)]), src("playstation-tr:CFI-7021-manual", "https://www.playstation.com/content/dam/global_pdc/tr/corporate/support/manuals/ps5-docs/7000/CFI-70XX_PS5_Quick_Start_Guide_Web%24tr.pdf", [p(10)], "MANUAL"), src("xbox-tr:Series-S", "https://www.xbox.com/tr-TR/consoles/xbox-series-s", [p(11)]),
];
type FactInput = readonly [string, string | number | boolean, string?]; const factsByProduct: readonly (readonly FactInput[])[] = [
  [["form_factor", "over-ear"], ["connectivity", "Bluetooth 5.2 and 3.5mm"], ["noise_control", "active noise cancellation"], ["battery_hours_anc", 30, "h"], ["weight_g", 250, "g"]],
  [["form_factor", "open-fit true wireless"], ["connectivity", "Bluetooth 5.2"], ["noise_control", "open-fit active noise cancellation"], ["battery_hours_anc_off", 6, "h"], ["codec_support", "SBC/AAC/L2HC 4.0/LDAC"]],
  [["connectivity", "Bluetooth"], ["ingress_rating", "IP68"], ["battery_hours", 14, "h"], ["playtime_boost_hours", 2, "h"], ["replaceable_carry_accessory", true]],
  [["connectivity", "Bluetooth"], ["ingress_rating", "IP67"], ["battery_hours", 12, "h"], ["shockproof", true], ["stereo_pair", true]],
  [["channel_configuration", "5.1.2"], ["included_subwoofer", true], ["rear_speakers_included", false], ["hdmi_earc", true], ["bluetooth_version", "5.3"]],
  [["channel_configuration", "3.1.1"], ["power_w", 400, "W"], ["included_subwoofer", true], ["rear_speakers_included", false], ["hdmi_earc", true]],
  [["sensor", "APS-C Exmor R CMOS"], ["megapixels", 26, "MP"], ["mount", "Sony E"], ["body_or_kit", "body only"], ["video_max", "4K 60p"]],
  [["sensor", "APS-C CMOS"], ["megapixels", 24.2, "MP"], ["mount", "Canon RF"], ["body_or_kit", "RF-S 18-45mm kit"], ["video_max", "4K 30p"]],
  [["native_resolution", "1920x1080"], ["light_source", "lamp"], ["brightness_lumens", 3000, "lm"], ["throw_ratio", "1.19-1.61"], ["platform", "Android TV"]],
  [["native_resolution", "1920x1080"], ["light_source", "LED"], ["brightness_ansi_lumens", 230, "ANSI lm"], ["throw_ratio", "1.2"], ["platform", "Tizen"]],
  [["platform", "PlayStation 5 Pro"], ["storage_tb", 2, "TB"], ["disc_capability", "optional external drive; excluded"], ["display_output", "4K up to 120Hz; 8K compatible"], ["wireless", "Wi-Fi 7"]],
  [["platform", "Xbox Series S"], ["storage_tb", 1, "TB"], ["disc_capability", "all-digital"], ["display_output", "1440p up to 120fps"], ["memory_gb", 10, "GB"]],
];
const slug = (value: string) => value.replaceAll(/[^a-zA-Z0-9]+/gu, "-").replaceAll(/^-|-$/gu, "").toLowerCase();
const technicalSource = (product: Product) => sources.find(source => source.exactProductIds.includes(product.exactProductId) && source.authority === "TECHNICAL")!;
const comparativeFacts: Wave2EvidenceRelease["comparativeFacts"] = products.flatMap((product, productIndex) => factsByProduct[productIndex].map(([key, value, unit], index) => ({ factId: `wave2-fact:${slug(product.exactProductId)}:${key}:${index + 1}`, exactProductId: product.exactProductId, categoryId: product.categoryId, key, value, ...(unit ? { unit } : {}), sourceId: technicalSource(product).sourceId, locator: "Exact official Türkiye product/specification field; exact configuration identity is separately recorded", decisionEligibility: "DRAFT_POLICY_INPUT", conflictState: "CLEAR" }))) as Wave2EvidenceRelease["comparativeFacts"];
const manualInputs = [
  { manualId: "wave2-manual:sony-wh1000xm5-tr", exactProductId: p(0), sourceUri: sources[1].uri, localPath: "data/production/electronics/wave-2-evidence/manuals/sony-wh-1000xm5-help-tr.pdf", locators: ["Pairing and connection", "Noise canceling function", "Precautions"] },
  { manualId: "wave2-manual:ps5-pro-cfi-7021-tr", exactProductId: p(10), sourceUri: sources[15].uri, localPath: "data/production/electronics/wave-2-evidence/manuals/ps5-pro-cfi-7021-quick-start-tr.pdf", locators: ["CFI-7021 model cover", "Getting started / HDMI and power", "Parental controls", "Disc drive sold separately"] },
] as const;
const manuals: Wave2EvidenceRelease["manuals"] = manualInputs.map(manual => ({ ...manual, sha256: sha(readFileSync(path.join(root, manual.localPath))), layer: "L9_ADVISOR_KNOWLEDGE" }));
const categoryReadiness: Wave2EvidenceRelease["categoryReadiness"] = ELECTRONICS_WAVE_2_CATEGORY_IDS.map(categoryId => { const categoryProducts = products.filter(row => row.categoryId === categoryId); const comparableFieldCount = new Set(comparativeFacts.filter(row => row.categoryId === categoryId).map(row => row.key)).size; const identityGaps = categoryProducts.flatMap(row => row.unresolvedIdentityDiscriminators); return { categoryId, candidateCount: categoryProducts.length, manufacturerCount: new Set(categoryProducts.map(row => row.manufacturer)).size, comparableFieldCount, readiness: identityGaps.length ? "POLICY_REVIEW_REQUIRED" : "DECISION_EVIDENCE_READY", reasons: identityGaps.length ? [`UNRESOLVED_EXACT_IDENTITY:${[...new Set(identityGaps)].join(",")}`] : ["EXACT_TR_IDENTITIES_WITH_MULTI_MANUFACTURER_COMPARATIVE_EVIDENCE"], policyStatus: "REVIEW_REQUIRED_NON_ACTIVE" }; });
const decisionProjections: Wave2EvidenceRelease["decisionProjections"] = products.map(product => ({ projectionId: `wave2-projection:${slug(product.exactProductId)}`, exactProductId: product.exactProductId, eligibleFactIds: comparativeFacts.filter(fact => fact.exactProductId === product.exactProductId).map(fact => fact.factId), status: "DRAFT_NON_ACTIVE", unknownTreatment: "NEUTRAL_FAIL_CLOSED", rankingWeights: "NONE" }));
const unknownsAndConflicts: Wave2EvidenceRelease["unknownsAndConflicts"] = products.flatMap(product => ["L7_GOVERNED_EXPERIENCE_ABSENT", "GOVERNED_MEDIA_REUSE_PROVENANCE_ABSENT", ...(manuals.some(manual => manual.exactProductId === product.exactProductId) ? [] : ["EXACT_MANUAL_NOT_CHECKSUM_BOUND"]), ...(product.categoryId === "GAME_CONSOLE" ? ["SUBSCRIPTION_AND_SERVICE_LIFECYCLE_VOLATILE"] : []), ...product.unresolvedIdentityDiscriminators.map(field => `IDENTITY_DISCRIMINATOR_UNKNOWN:${field}`)].map(code => ({ exactProductId: product.exactProductId, code, effect: "NEUTRAL_FAIL_CLOSED" })));
const boundaries = { l7Experience: "ABSENT", mediaImported: false, l10YEffect: "NONE", amazonStatusEffect: "NONE", activationPerformed: false, registryChanged: false, runtimeChanged: false, databaseChanged: false, pointerChanged: false, deploymentPerformed: false } as const;
const release: Wave2EvidenceRelease = { schemaVersion: "electronics-wave-2-evidence/v1", releaseVersion: ELECTRONICS_WAVE_2_VERSION, parent: { releaseDigest: ELECTRONICS_WAVE_2_PARENT_DIGEST, relationship: "IMMUTABLE_CHILD_NO_OVERWRITE" }, research: { amazonFirstDigest: amazonManifest.payloadDigest, amazonRole: "DISCOVERY_ONLY_ZERO_DECISION_EFFECT", internationalRole: "TECHNICAL_GAP_FILL_ONLY_NOT_TR_APPLICABILITY" }, products, sources, comparativeFacts, manuals, categoryReadiness, decisionProjections, unknownsAndConflicts, boundaries };
const issues = validateWave2EvidenceClosure(release); if (issues.length) throw new Error(`WAVE_2_EVIDENCE_INVALID:${issues.join(",")}`);
const comparison = { schemaVersion: "electronics-wave-2-comparison/v1", categories: categoryReadiness.map(row => ({ ...row, exactProductIds: products.filter(product => product.categoryId === row.categoryId).map(product => product.exactProductId), fields: [...new Set(comparativeFacts.filter(fact => fact.categoryId === row.categoryId).map(fact => fact.key))].sort() })) };
const policyProposal = { schemaVersion: "electronics-wave-2-policy-input/v1", status: "NON_ACTIVE_CATEGORY_REVIEW_INPUT", categories: comparison.categories.map(row => ({ categoryId: row.categoryId, eligibleFields: row.fields, rankingWeights: "NONE", sufficiencyThresholds: "UNDEFINED_PENDING_PRODUCT_REVIEW", unknownTreatment: "NEUTRAL_FAIL_CLOSED", commerceEffect: "NONE" })) };
const reconciliation = { schemaVersion: "electronics-wave-2-reconciliation/v1", parentReleaseDigest: ELECTRONICS_WAVE_2_PARENT_DIGEST, parentBytesUnmodified: true, parentArtifactPath: path.relative(root, parentPath), amazonFirstDigest: amazonManifest.payloadDigest, wave2ExactProductIds: products.map(row => row.exactProductId).sort(), duplicateExactProductIds: [], activationEffect: "NONE" };
const output = path.join(root, "data/production/electronics/wave-2-evidence/releases", ELECTRONICS_WAVE_2_VERSION); mkdirSync(output, { recursive: true });
const artifactRaw = { "evidence-release.json": pretty(release), "comparative-matrix.json": pretty(comparison), "policy-input-proposal.json": pretty(policyProposal), "reconciliation.json": pretty(reconciliation) }; for (const [name, raw] of Object.entries(artifactRaw)) writeFileSync(path.join(output, name), raw);
const manifest = { schemaVersion: "electronics-wave-2-manifest/v1", workUnitId: "WU-ELECTRONICS-WAVE-2-MULTI-CANDIDATE-EVIDENCE-CLOSURE-01", releaseVersion: ELECTRONICS_WAVE_2_VERSION, verdict: "PARTIAL", parentReleaseDigest: ELECTRONICS_WAVE_2_PARENT_DIGEST, counts: { categories: ELECTRONICS_WAVE_2_CATEGORY_IDS.length, products: products.length, manufacturers: new Set(products.map(row => row.manufacturer)).size, sources: sources.length, comparativeFacts: comparativeFacts.length, manuals: manuals.length, unknowns: unknownsAndConflicts.length }, readiness: Object.fromEntries(["DECISION_EVIDENCE_READY", "POLICY_REVIEW_REQUIRED", "INFORMATION_ONLY", "BLOCKED_EVIDENCE"].map(status => [status, categoryReadiness.filter(row => row.readiness === status).length])), artifacts: Object.fromEntries(Object.entries(artifactRaw).map(([name, raw]) => [name, sha(raw)])), activation: boundaries };
writeFileSync(path.join(output, "manifest.json"), pretty(manifest)); console.log(JSON.stringify({ output, ...manifest.counts, readiness: manifest.readiness, releaseDigest: manifest.artifacts["evidence-release.json"] }));
