import { createHash } from "node:crypto";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

type FacetClass = "HARD_CONSTRAINT" | "MATERIAL_TECHNICAL_DISCRIMINATOR" | "SOFT_PREFERENCE" | "VOLATILE_COMMERCE" | "NON_MATERIAL_BASELINE" | "UNRELIABLE_FACET";
type Facts = Record<string, string | number | boolean | null>;
type Family = { brand:string; family:string; model:string; modelCode:string|null; sourceId:string; url:string; sourceAuthority:"MANUFACTURER_TR"|"RELIABLE_TR_RETAILER_IDENTITY_ONLY"; segments:string[]; facts:Facts; configs:Array<{ram:number|null;storage:number;color:string;sku?:string}> };

const generatedAt = "2026-09-07T00:00:00.000Z";
const workUnit = "WU-CATALOG-FACTORY-SMARTPHONE-AMAZON-TR-COVERAGE-EXPANSION-02";
const out = path.join(process.cwd(), "data/research/electronics/smartphone-amazon-tr-catalog-expansion-02");
const slug = (value:string) => value.toLocaleLowerCase("tr-TR").normalize("NFKD").replace(/ı/g,"i").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const sha = (value:unknown) => `sha256:${createHash("sha256").update(JSON.stringify(value)).digest("hex")}`;

const requiredFactKeys = ["ram_gb","storage_gb","soc","performance_class","display_inches","display_type","refresh_hz","os","support_policy","battery_mah","wired_charging_w","wireless_charging_w","rear_camera_system","ois","telephoto","ultrawide","front_camera","ip_rating","sim","esim","cellular","connector","weight_g","biometrics","video_capability","stylus"];
const families:Family[] = [
 {brand:"Apple",family:"iPhone 17",model:"iPhone 17",modelCode:null,sourceId:"apple-tr:iphone-17-spec",url:"https://www.apple.com/tr/iphone-17/specs/",sourceAuthority:"MANUFACTURER_TR",segments:["compact","camera-led","premium"],facts:{soc:"A19",performance_class:"FLAGSHIP",display_inches:6.3,display_type:"OLED",refresh_hz:120,os:"iOS",support_policy:null,battery_mah:null,wired_charging_w:null,wireless_charging_w:null,rear_camera_system:"48 MP Fusion main OIS + 48 MP ultrawide; 2x optical-quality crop",ois:true,telephoto:false,ultrawide:true,front_camera:"18 MP Center Stage",ip_rating:"IP68",sim:"eSIM only",esim:true,cellular:"5G",connector:"USB-C",weight_g:177,biometrics:"Face ID",video_capability:"4K Dolby Vision",stylus:false},configs:[{ram:null,storage:256,color:"Siyah"},{ram:null,storage:512,color:"Lavanta"}]},
 {brand:"Apple",family:"iPhone 17 Pro",model:"iPhone 17 Pro",modelCode:null,sourceId:"apple-tr:iphone-17-pro-spec",url:"https://www.apple.com/tr/iphone-17-pro/specs/",sourceAuthority:"MANUFACTURER_TR",segments:["camera-led","performance","premium"],facts:{soc:"A19 Pro",performance_class:"FLAGSHIP",display_inches:6.3,display_type:"OLED",refresh_hz:120,os:"iOS",support_policy:null,battery_mah:null,wired_charging_w:null,wireless_charging_w:null,rear_camera_system:"48 MP Pro Fusion triple camera with telephoto and ultrawide",ois:true,telephoto:true,ultrawide:true,front_camera:"18 MP Center Stage",ip_rating:"IP68",sim:"eSIM only",esim:true,cellular:"5G",connector:"USB-C (USB 3)",weight_g:null,biometrics:"Face ID",video_capability:"4K Dolby Vision / ProRes",stylus:false},configs:[{ram:null,storage:256,color:"Kozmik Turuncu"},{ram:null,storage:512,color:"Derin Mavi"},{ram:null,storage:1024,color:"Gümüş"}]},
 {brand:"Samsung",family:"Galaxy A26 5G",model:"Galaxy A26 5G",modelCode:"SM-A266B",sourceId:"samsung-tr:galaxy-a26",url:"https://www.samsung.com/tr/smartphones/galaxy-a/galaxy-a26-5g-black-256gb-sm-a266bzkctur/",sourceAuthority:"MANUFACTURER_TR",segments:["budget","durable"],facts:{soc:"Exynos 1380",performance_class:"MAINSTREAM",display_inches:6.7,display_type:"Super AMOLED",refresh_hz:120,os:"Android / One UI",support_policy:"6 OS generations and 6 years security",battery_mah:5000,wired_charging_w:25,wireless_charging_w:0,rear_camera_system:"50 MP main OIS + 8 MP ultrawide + 2 MP macro",ois:true,telephoto:false,ultrawide:true,front_camera:"13 MP",ip_rating:"IP67",sim:"dual nano-SIM",esim:false,cellular:"5G",connector:"USB-C",weight_g:200,biometrics:"side fingerprint",video_capability:"4K30",stylus:false},configs:[{ram:8,storage:256,color:"Black",sku:"SM-A266BZKCTUR"}]},
 {brand:"Samsung",family:"Galaxy A36 5G",model:"Galaxy A36 5G",modelCode:"SM-A366B",sourceId:"samsung-tr:galaxy-a36",url:"https://www.samsung.com/tr/smartphones/galaxy-a/galaxy-a36-5g-black-256gb-sm-a366bzkgtur/",sourceAuthority:"MANUFACTURER_TR",segments:["mainstream","durable"],facts:{soc:"Snapdragon 6 Gen 3",performance_class:"MAINSTREAM",display_inches:6.7,display_type:"Super AMOLED",refresh_hz:120,os:"Android / One UI",support_policy:"6 OS generations and 6 years security",battery_mah:5000,wired_charging_w:45,wireless_charging_w:0,rear_camera_system:"50 MP main OIS + 8 MP ultrawide + 5 MP macro",ois:true,telephoto:false,ultrawide:true,front_camera:"12 MP",ip_rating:"IP67",sim:"dual nano-SIM",esim:true,cellular:"5G",connector:"USB-C",weight_g:195,biometrics:"in-display fingerprint",video_capability:"4K30",stylus:false},configs:[{ram:8,storage:256,color:"Black",sku:"SM-A366BZKGTUR"}]},
 {brand:"Samsung",family:"Galaxy S25",model:"Galaxy S25",modelCode:"SM-S931B",sourceId:"samsung-tr:galaxy-s25",url:"https://www.samsung.com/tr/smartphones/galaxy-s25/",sourceAuthority:"MANUFACTURER_TR",segments:["compact","performance","camera-led"],facts:{soc:"Snapdragon 8 Elite for Galaxy",performance_class:"FLAGSHIP",display_inches:6.2,display_type:"Dynamic AMOLED 2X",refresh_hz:120,os:"Android / One UI",support_policy:"7 OS generations and 7 years security",battery_mah:4000,wired_charging_w:25,wireless_charging_w:15,rear_camera_system:"50 MP main OIS + 10 MP 3x telephoto OIS + 12 MP ultrawide",ois:true,telephoto:true,ultrawide:true,front_camera:"12 MP",ip_rating:"IP68",sim:"dual SIM",esim:true,cellular:"5G",connector:"USB-C",weight_g:162,biometrics:"ultrasonic in-display fingerprint",video_capability:"8K30 / 4K120",stylus:false},configs:[{ram:12,storage:128,color:"Lacivert"},{ram:12,storage:256,color:"Gümüş"},{ram:12,storage:512,color:"Mavi"}]},
 {brand:"Samsung",family:"Galaxy S25 Ultra",model:"Galaxy S25 Ultra",modelCode:"SM-S938B",sourceId:"samsung-tr:galaxy-s25-ultra",url:"https://www.samsung.com/tr/smartphones/galaxy-s25-ultra/",sourceAuthority:"MANUFACTURER_TR",segments:["camera-led","performance","stylus","premium"],facts:{soc:"Snapdragon 8 Elite for Galaxy",performance_class:"FLAGSHIP",display_inches:6.9,display_type:"Dynamic AMOLED 2X",refresh_hz:120,os:"Android / One UI",support_policy:"7 OS generations and 7 years security",battery_mah:5000,wired_charging_w:45,wireless_charging_w:15,rear_camera_system:"200 MP main OIS + 50 MP 5x telephoto OIS + 10 MP 3x telephoto OIS + 50 MP ultrawide",ois:true,telephoto:true,ultrawide:true,front_camera:"12 MP",ip_rating:"IP68",sim:"dual SIM",esim:true,cellular:"5G",connector:"USB-C",weight_g:218,biometrics:"ultrasonic in-display fingerprint",video_capability:"8K30 / 4K120",stylus:true},configs:[{ram:12,storage:256,color:"Titanyum Siyah"},{ram:12,storage:512,color:"Titanyum Gri"},{ram:12,storage:1024,color:"Titanyum Gümüş"}]},
 {brand:"Samsung",family:"Galaxy Z Flip7 FE",model:"Galaxy Z Flip7 FE",modelCode:"SM-F761B",sourceId:"samsung-tr:z-flip7-fe",url:"https://www.samsung.com/tr/smartphones/galaxy-z/galaxy-z-flip7-fe-black-256gb-sm-f761bzkhtur/buy/",sourceAuthority:"MANUFACTURER_TR",segments:["foldable","compact"],facts:{soc:"Exynos 2400",performance_class:"FLAGSHIP",display_inches:6.7,display_type:"Dynamic AMOLED 2X foldable",refresh_hz:120,os:"Android / One UI",support_policy:null,battery_mah:4000,wired_charging_w:25,wireless_charging_w:15,rear_camera_system:"50 MP main OIS + 12 MP ultrawide",ois:true,telephoto:false,ultrawide:true,front_camera:"10 MP",ip_rating:"IP48",sim:"nano-SIM",esim:true,cellular:"5G",connector:"USB-C",weight_g:null,biometrics:"side fingerprint",video_capability:"4K",stylus:false},configs:[{ram:8,storage:256,color:"Siyah",sku:"SM-F761BZKHTUR"}]},
 {brand:"Xiaomi",family:"Xiaomi 14T",model:"Xiaomi 14T",modelCode:null,sourceId:"xiaomi-tr:14t-spec",url:"https://www.mi.com/tr/product/xiaomi-14t/specs/",sourceAuthority:"MANUFACTURER_TR",segments:["camera-led","performance"],facts:{soc:"Dimensity 8300-Ultra",performance_class:"UPPER_MAINSTREAM",display_inches:6.67,display_type:"AMOLED",refresh_hz:144,os:"Xiaomi HyperOS",support_policy:null,battery_mah:5000,wired_charging_w:67,wireless_charging_w:0,rear_camera_system:"50 MP main OIS + 50 MP telephoto + 12 MP ultrawide",ois:true,telephoto:true,ultrawide:true,front_camera:"32 MP",ip_rating:"IP68",sim:"dual nano-SIM",esim:true,cellular:"5G",connector:"USB-C",weight_g:195,biometrics:"in-display fingerprint",video_capability:"4K60",stylus:false},configs:[{ram:12,storage:256,color:"Titan Siyah"},{ram:12,storage:512,color:"Titan Mavi"}]},
 {brand:"Redmi",family:"Redmi Note 14 Pro",model:"Redmi Note 14 Pro",modelCode:null,sourceId:"xiaomi-tr:redmi-note-14-pro",url:"https://www.mi.com/tr/product/redmi-note-14-pro/specs/",sourceAuthority:"MANUFACTURER_TR",segments:["budget","camera-led","long-battery"],facts:{soc:"Helio G100-Ultra",performance_class:"MAINSTREAM",display_inches:6.67,display_type:"AMOLED",refresh_hz:120,os:"Xiaomi HyperOS",support_policy:null,battery_mah:5500,wired_charging_w:45,wireless_charging_w:0,rear_camera_system:"200 MP main OIS + 8 MP ultrawide + 2 MP macro",ois:true,telephoto:false,ultrawide:true,front_camera:"32 MP",ip_rating:"IP64",sim:"dual nano-SIM",esim:false,cellular:"4G",connector:"USB-C",weight_g:180,biometrics:"in-display fingerprint",video_capability:"1080p60",stylus:false},configs:[{ram:8,storage:256,color:"Gece Siyahı"},{ram:12,storage:512,color:"Okyanus Mavisi"}]},
 {brand:"POCO",family:"POCO X7 Pro",model:"POCO X7 Pro",modelCode:null,sourceId:"xiaomi-tr:poco-x7-pro",url:"https://www.mi.com/tr/product/poco-x7-pro/specs/",sourceAuthority:"MANUFACTURER_TR",segments:["performance","long-battery","value"],facts:{soc:"Dimensity 8400-Ultra",performance_class:"FLAGSHIP_VALUE",display_inches:6.67,display_type:"AMOLED",refresh_hz:120,os:"Xiaomi HyperOS",support_policy:null,battery_mah:6000,wired_charging_w:90,wireless_charging_w:0,rear_camera_system:"50 MP main OIS + 8 MP ultrawide",ois:true,telephoto:false,ultrawide:true,front_camera:"20 MP",ip_rating:"IP68",sim:"dual nano-SIM",esim:false,cellular:"5G",connector:"USB-C",weight_g:195,biometrics:"in-display fingerprint",video_capability:"4K60",stylus:false},configs:[{ram:8,storage:256,color:"Siyah"},{ram:12,storage:512,color:"Sarı"}]},
 {brand:"HONOR",family:"HONOR 400",model:"HONOR 400",modelCode:"DNY-NX9",sourceId:"honor-tr:honor-400",url:"https://www.honor.com/tr/phones/honor-400/",sourceAuthority:"MANUFACTURER_TR",segments:["mainstream","long-battery","camera-led"],facts:{soc:"Snapdragon 7 Gen 3",performance_class:"UPPER_MAINSTREAM",display_inches:6.55,display_type:"AMOLED",refresh_hz:120,os:"MagicOS",support_policy:null,battery_mah:6000,wired_charging_w:80,wireless_charging_w:0,rear_camera_system:"200 MP main OIS + 12 MP ultrawide",ois:true,telephoto:false,ultrawide:true,front_camera:"50 MP",ip_rating:"IP65",sim:"dual nano-SIM",esim:true,cellular:"5G",connector:"USB-C",weight_g:184,biometrics:"in-display fingerprint",video_capability:"4K",stylus:false},configs:[{ram:8,storage:256,color:"Gece Siyahı",sku:"DNY-NX9"},{ram:12,storage:512,color:"Çöl Altını",sku:"DNY-NX9"}]},
 {brand:"HUAWEI",family:"Mate X6",model:"Mate X6",modelCode:null,sourceId:"huawei-tr:mate-x6",url:"https://consumer.huawei.com/tr/phones/mate-x6/specs/",sourceAuthority:"MANUFACTURER_TR",segments:["foldable","camera-led","premium"],facts:{soc:null,performance_class:"FLAGSHIP",display_inches:7.93,display_type:"foldable OLED",refresh_hz:120,os:"EMUI",support_policy:null,battery_mah:5110,wired_charging_w:66,wireless_charging_w:50,rear_camera_system:"50 MP variable-aperture main OIS + 48 MP telephoto macro OIS + 40 MP ultrawide",ois:true,telephoto:true,ultrawide:true,front_camera:"8 MP inner + 8 MP outer",ip_rating:"IPX8",sim:"dual nano-SIM",esim:false,cellular:"4G",connector:"USB-C",weight_g:239,biometrics:"side fingerprint",video_capability:"4K",stylus:false},configs:[{ram:12,storage:512,color:"Siyah"},{ram:12,storage:512,color:"Nebula Kırmızı"}]},
 {brand:"HUAWEI",family:"Pura 80 Pro",model:"Pura 80 Pro",modelCode:null,sourceId:"huawei-tr:pura-80-pro",url:"https://consumer.huawei.com/tr/phones/pura80-pro/specs/",sourceAuthority:"MANUFACTURER_TR",segments:["camera-led","premium","durable"],facts:{soc:null,performance_class:"FLAGSHIP",display_inches:6.8,display_type:"LTPO OLED",refresh_hz:120,os:"EMUI",support_policy:null,battery_mah:5170,wired_charging_w:100,wireless_charging_w:80,rear_camera_system:"50 MP 1-inch variable-aperture main OIS + macro telephoto OIS + ultrawide",ois:true,telephoto:true,ultrawide:true,front_camera:"13 MP",ip_rating:"IP68/IP69",sim:"dual nano-SIM",esim:false,cellular:"4G",connector:"USB-C",weight_g:null,biometrics:"side fingerprint",video_capability:"4K",stylus:false},configs:[{ram:12,storage:512,color:"Siyah"}]},
 {brand:"Nothing",family:"Phone (3a)",model:"Phone (3a)",modelCode:"A059",sourceId:"nothing-tr:phone-3a",url:"https://tr.nothing.tech/pages/phone-3a",sourceAuthority:"MANUFACTURER_TR",segments:["value","design","long-battery"],facts:{soc:"Snapdragon 7s Gen 3",performance_class:"UPPER_MAINSTREAM",display_inches:6.77,display_type:"AMOLED",refresh_hz:120,os:"Nothing OS",support_policy:"3 Android upgrades and 6 years security/functionality updates",battery_mah:5000,wired_charging_w:50,wireless_charging_w:0,rear_camera_system:"50 MP main OIS + 50 MP 2x telephoto + 8 MP ultrawide",ois:true,telephoto:true,ultrawide:true,front_camera:"32 MP",ip_rating:"IP64",sim:"dual nano-SIM",esim:false,cellular:"5G",connector:"USB-C",weight_g:201,biometrics:"in-display fingerprint",video_capability:"4K30",stylus:false},configs:[{ram:8,storage:128,color:"Siyah"},{ram:12,storage:256,color:"Beyaz"}]},
 {brand:"OPPO",family:"Reno13 F 5G",model:"Reno13 F 5G",modelCode:"CPH2699",sourceId:"oppo-tr:reno13-f-5g",url:"https://www.oppo.com/tr/smartphones/series-reno/reno13-f-5g/specs/",sourceAuthority:"MANUFACTURER_TR",segments:["mainstream","durable","long-battery"],facts:{soc:"Snapdragon 6 Gen 1",performance_class:"MAINSTREAM",display_inches:6.67,display_type:"AMOLED",refresh_hz:120,os:"ColorOS",support_policy:null,battery_mah:5800,wired_charging_w:45,wireless_charging_w:0,rear_camera_system:"50 MP main OIS + 8 MP ultrawide + 2 MP macro",ois:true,telephoto:false,ultrawide:true,front_camera:"32 MP",ip_rating:"IP66/IP68/IP69",sim:"dual nano-SIM",esim:false,cellular:"5G",connector:"USB-C",weight_g:192,biometrics:"in-display fingerprint",video_capability:"4K30",stylus:false},configs:[{ram:12,storage:256,color:"Grafit Gri"},{ram:12,storage:512,color:"Tüy Beyazı"}]},
 {brand:"TECNO",family:"CAMON 30 5G",model:"CAMON 30 5G",modelCode:null,sourceId:"tecno-tr:camon-30-5g",url:"https://turkiye.tecno-mobile.com/phones/tech-specs/tecspecs/camon-30-5g/",sourceAuthority:"MANUFACTURER_TR",segments:["camera-led","value","long-battery"],facts:{soc:"Dimensity 7020",performance_class:"MAINSTREAM",display_inches:6.78,display_type:"AMOLED",refresh_hz:120,os:"Android 14 / HiOS",support_policy:null,battery_mah:5000,wired_charging_w:70,wireless_charging_w:0,rear_camera_system:"50 MP main OIS + 2 MP depth + light sensor",ois:true,telephoto:false,ultrawide:false,front_camera:"50 MP AF",ip_rating:null,sim:"dual SIM",esim:false,cellular:"5G",connector:"USB-C",weight_g:null,biometrics:"fingerprint",video_capability:null,stylus:false},configs:[{ram:8,storage:256,color:"İzlanda Bazalt Siyah"},{ram:8,storage:512,color:"Uyuni Tuz Beyaz"},{ram:12,storage:512,color:"Zümrüt Göl Yeşil"}]},
 {brand:"General Mobile",family:"GM Phoenix 5G",model:"GM Phoenix 5G",modelCode:null,sourceId:"gm-tr:phoenix-5g",url:"https://www.generalmobile.com/tr/urunler/gmphoenix5g",sourceAuthority:"MANUFACTURER_TR",segments:["budget","local-brand","5g"],facts:{soc:"Dimensity 7050",performance_class:"MAINSTREAM",display_inches:6.78,display_type:"AMOLED",refresh_hz:120,os:"Android",support_policy:null,battery_mah:4700,wired_charging_w:66,wireless_charging_w:0,rear_camera_system:"200 MP main; auxiliary cameras not sufficiently specified",ois:null,telephoto:false,ultrawide:null,front_camera:null,ip_rating:null,sim:"dual nano-SIM",esim:false,cellular:"5G",connector:"USB-C",weight_g:210,biometrics:"fingerprint",video_capability:null,stylus:false},configs:[{ram:8,storage:256,color:"Karbon Siyahı"}]},
];

const products = families.flatMap(family => family.configs.map(config => {
 const identity = `${family.brand}|${family.family}|${family.modelCode ?? "NO_PUBLIC_SKU"}|${config.ram ?? "UNKNOWN"}GB|${config.storage}GB|${config.color}|TR`;
 const exactProductId = `electronics:smartphone:${slug(family.brand)}:${slug(family.family)}:${slug(`${config.sku ?? family.modelCode ?? "no-public-sku"}-${config.ram ?? "unknown"}-${config.storage}-${config.color}`)}`;
 const facts = {...family.facts,ram_gb:config.ram,storage_gb:config.storage};
 return {exactProductId,brand:family.brand,family:family.family,model:family.model,sku:config.sku ?? null,modelCode:family.modelCode,configurationIdentity:identity,market:"TR",segments:family.segments,facts,sourceIds:[family.sourceId],trApplicability:"EXACT_TR_CONFIGURATION",terminalState:"CANDIDATE_NOT_ACTIVE",commerce:{price:null,stock:null,rating:null,deals:null,seller:null,greyImportState:null,state:"UNKNOWN_FAIL_CLOSED"}};
}));
if (new Set(products.map(p=>p.exactProductId)).size !== products.length) throw new Error("DUPLICATE_EXACT_PRODUCT_ID");
for (const product of products) for (const key of requiredFactKeys) if (!(key in product.facts)) throw new Error(`MISSING_FACT_KEY:${product.exactProductId}:${key}`);

const facetClassification:Array<{field:string;classification:FacetClass;rule:string}> = [
 {field:"market/exact configuration/SKU",classification:"HARD_CONSTRAINT",rule:"Türkiye applicability and exact configuration must be source-bound; otherwise quarantine."},
 {field:"SIM/eSIM, cellular generation, connector, OS compatibility",classification:"HARD_CONSTRAINT",rule:"Hard only when the user explicitly requires the value."},
 ...["RAM/storage","SoC/performance class","display size/type/refresh","verified support policy","battery/charging","rear camera system with OIS/telephoto/ultrawide","front camera","IP rating","weight","biometrics","video capability","stylus"].map(field=>({field,classification:"MATERIAL_TECHNICAL_DISCRIMINATOR" as const,rule:"Ask/rank only when known candidate values materially differ; MP alone never represents camera quality."})),
 {field:"brand/color/design",classification:"SOFT_PREFERENCE",rule:"Brand only after explicit user preference; no hidden prestige ranking."},
 {field:"price/stock/rating/deals/seller/international or grey import",classification:"VOLATILE_COMMERCE",rule:"Unknown and fail-closed without a fresh approved offer binding; never technical authority."},
 {field:"touchscreen/camera/phone calling/app installation",classification:"NON_MATERIAL_BASELINE",rule:"Suppress when common across the candidate set."},
 {field:"Amazon bestseller badge/facet labels/title adjectives",classification:"UNRELIABLE_FACET",rule:"Discovery hint only; never copied into facts or ranking."},
];
const questions = [
 {id:"form",concept:"FORM_FACTOR",prompt:"Katlanınca cebe daha rahat sığan bir model mi, yoksa klasik düz gövde mi istersin?",values:["katlanabilir","klasik düz"],facts:["segments"]},
 {id:"size",concept:"DISPLAY_SIZE",prompt:"Ekran boyutunda 6,2–6,3 inç daha kompakt mı, 6,5–6,8 inç dengeli mi, yoksa 6,9 inç ve üzeri geniş alan mı istersin?",values:["6,2–6,3 inç","6,5–6,8 inç","6,9+ inç"],facts:["display_inches"]},
 {id:"storage",concept:"STORAGE",prompt:"Depolama için 128 GB yeterli mi, 256 GB mı, yoksa 512 GB ve üzeri mi istersin?",values:["128 GB","256 GB","512 GB+"],facts:["storage_gb"]},
 {id:"camera",concept:"CAMERA_SYSTEM",prompt:"Kamerada hangisi daha önemli: optik sabitleme, gerçek telefoto yakınlaştırma, yoksa ultra geniş açı?",values:["OIS","telefoto","ultra geniş"],facts:["ois","telephoto","ultrawide"]},
 {id:"durability",concept:"INGRESS",prompt:"Su ve toz dayanımında IP64, IP67 veya IP68/IP69 seviyelerinden biri senin için şart mı?",values:["IP64","IP67","IP68/IP69","şart değil"],facts:["ip_rating"]},
 {id:"charging",concept:"CHARGING",prompt:"Şarjda 25–45 W, 50–80 W, 90 W ve üzeri kablolu hız mı; yoksa kablosuz şarj mı daha önemli?",values:["25–45 W","50–80 W","90 W+","kablosuz"],facts:["wired_charging_w","wireless_charging_w"]},
 {id:"support",concept:"SUPPORT",prompt:"Üreticinin açıkça doğruladığı 6–7 yıllık güncelleme taahhüdü senin için seçim kriteri mi?",values:["evet","hayır","emin değilim"],facts:["support_policy"]},
];
const traces = questions.slice(0,4).map((question,index)=>({turn:index+1,P:{questionId:question.id,text:question.prompt,oneQuestionOnly:true,offeredValues:question.values},Y:{answer:question.values[0],effect:"MATERIAL_FILTER_OR_RANK_ONLY",unknownBehavior:"NEUTRAL_NO_SILENT_DROP",provenanceRequired:true}}));
const coverage = {exactVariantCount:products.length,brandCount:new Set(products.map(p=>p.brand)).size,brands:[...new Set(products.map(p=>p.brand))],segments:Object.fromEntries([...new Set(products.flatMap(p=>p.segments))].sort().map(segment=>[segment,products.filter(p=>p.segments.includes(segment)).length])),factCoverage:Object.fromEntries(requiredFactKeys.map(key=>[key,{known:products.filter(p=>p.facts[key]!==null).length,unknown:products.filter(p=>p.facts[key]===null).length}])),activeAuthorityAudit:{activeExactVariantCount:3,activeBrands:["HONOR","Samsung"],domainPackStatus:"CANDIDATE_REVALIDATION_REQUIRED",domainPackRetainedObservationCount:3},target:{minimum:30,preferredMaximum:50,met:products.length>=30&&products.length<=50}};
const sources = families.map(({sourceId,url,sourceAuthority,brand,family})=>({sourceId,url,sourceAuthority,brand,family,market:"TR",observedAt:generatedAt,technicalAuthority:sourceAuthority==="MANUFACTURER_TR",exactConfigurationScope:true}));
const unknownLedger = products.flatMap(product=>requiredFactKeys.filter(key=>product.facts[key]===null).map(factKey=>({exactProductId:product.exactProductId,factKey,value:"UNKNOWN",decisionEffect:"NEUTRAL",reason:"No exact Türkiye source-bound value admitted; candidate retained."})));
const packageData = {schemaVersion:"electronics-smartphone-domain-pack/v2",workUnit,generatedAt,status:"OWNER_REVIEW_CANDIDATE_NOT_ACTIVE",authorityAudit:coverage.activeAuthorityAudit,products,sources,facetClassification,dailyLifeSemantics:[{concept:"POCKETABILITY",inputs:["display_inches","weight_g","segments"],meaning:"Tek elle kullanım ve cepte taşıma kolaylığı; ölçüler yoksa iddia kurulmaz."},{concept:"PHOTO_FLEXIBILITY",inputs:["ois","telephoto","ultrawide"],meaning:"Farklı çekim koşullarındaki donanım esnekliği; megapiksel kalite puanı değildir."},{concept:"SHORT_CHARGE_RECOVERY",inputs:["wired_charging_w","wireless_charging_w","battery_mah"],meaning:"Kısa şarj fırsatlarında pratik toparlanma; gerçek süre iddiası kurulmaz."},{concept:"LONG_TERM_USE",inputs:["support_policy","ip_rating"],meaning:"Doğrulanmış destek taahhüdü ve belgeli dayanım; UNKNOWN nötr kalır."}],personaHierarchy:{order:["HARD_CONSTRAINT","EXPLICIT_USER_PREFERENCE","MATERIAL_TECHNICAL_DISCRIMINATOR","SOFT_PREFERENCE","NON_MATERIAL_BASELINE"],brandPolicy:"EXPLICIT_ONLY_NO_PRESTIGE_PRIOR",unknownPolicy:"NEUTRAL_NO_SILENT_DROP",commercePolicy:"SEPARATE_FAIL_CLOSED"},questions,traces,coverage,unknownLedger,amazonDiscovery:{status:"BLOCKED_NO_DISCOVERY_OR_API_ACCESS",technicalAuthority:"NONE",continuation:"Official Türkiye and support sources used; Amazon facets not copied."},invariants:{activePointerMutation:false,activationPerformed:false,deploymentPerformed:false,packageApprovalRequired:true}};
const files:Record<string,unknown>={"candidate-catalog.json":{status:packageData.status,products},"source-register.json":sources,"facet-classification.json":facetClassification,"daily-life-semantics.json":packageData.dailyLifeSemantics,"persona-hierarchy.json":packageData.personaHierarchy,"domain-pack.json":packageData,"p-y-trace-previews.json":traces,"coverage-matrix.json":coverage,"unknown-ledger.json":unknownLedger,"amazon-access-ledger.json":packageData.amazonDiscovery,"owner-approval-package.json":{...packageData,approval:{status:"PENDING_SEPARATE_PACKAGE_APPROVAL",activationAllowed:false}}};
rmSync(out,{recursive:true,force:true}); mkdirSync(out,{recursive:true});
for (const [name,value] of Object.entries(files)) writeFileSync(path.join(out,name),`${JSON.stringify(value,null,2)}\n`);
const manifest={schemaVersion:"electronics-smartphone-expansion-manifest/v2",workUnit,generatedAt,status:"CANDIDATE_NOT_ACTIVE",files:Object.entries(files).map(([name,value])=>({name,sha256:sha(value)})),packageSha256:sha(packageData),activePointerMutation:false,activationPerformed:false,deploymentPerformed:false};
writeFileSync(path.join(out,"manifest.json"),`${JSON.stringify(manifest,null,2)}\n`);
console.log(JSON.stringify({out,exactVariantCount:products.length,brandCount:coverage.brandCount,targetMet:coverage.target.met,packageSha256:manifest.packageSha256}));
