import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ELECTRONICS_CATEGORY_REGISTRY } from "../features/electronics/architectureBaseline";
import { ELECTRONICS_RICHNESS_RELEASE_VERSION, validateElectronicsRichness, type ElectronicsRichnessGovernance } from "../features/electronics/catalogRichness";
import { XPY_CATALOG_VERSION, type CatalogSource, type XpyCatalogRelease } from "../features/xpy/catalog/contract";
import { validateXpyCatalogRelease, xpyCatalogReleaseDigest } from "../features/xpy/catalog/validation";
import { XPY_RUNTIME_DIGEST, XPY_RUNTIME_VERSION } from "../features/xpy/runtimeContract";

const root = process.cwd();
const reviewedAt = "2026-09-05T14:00:00.000Z";
const amazonDir = path.join(root, "data/research/electronics/amazon-tr-primary-catalog-01");
const turkeyDir = path.join(root, "data/research/electronics/turkey-non-amazon-catalog-01");
const amazon = JSON.parse(readFileSync(path.join(amazonDir, "amazon-primary-research.json"), "utf8"));
const amazonManifest = JSON.parse(readFileSync(path.join(amazonDir, "manifest.json"), "utf8"));
const turkey = JSON.parse(readFileSync(path.join(turkeyDir, "turkey-second-pass.json"), "utf8"));
const turkeyManifest = JSON.parse(readFileSync(path.join(turkeyDir, "manifest.json"), "utf8"));
const reconciliation = JSON.parse(readFileSync(path.join(turkeyDir, "cross-pass-reconciliation.json"), "utf8"));
const expected = { amazon: "sha256:09ef0e34db66fa00f9fb3b98f83db0370f1e0a2905da805c50282073576e3a20", turkey: "sha256:159fd871ec94071cfb87fb1def85302baeba5710d4de708da9aa87fafc4c500f", reconciliation: "sha256:a487ad809306da0bbd6947a34ce01f549fc8bcc424ca11af8dfa32c4bd4a46ab" };
if (amazonManifest.payloadDigest !== expected.amazon || turkeyManifest.payloadDigest !== expected.turkey || turkeyManifest.reconciliationDigest !== expected.reconciliation) throw new Error("ACCEPTED_INPUT_DIGEST_MISMATCH");

type Product = { exactProductId: string; categoryId: string; wave: number; brand: string; model: string; manufacturerModelCode: string; configurationIdentity: string; sourceId: string; sourceUri: string; sourceKind: string; amazonRelation: string; asin?: string };
const amazonSources = new Map(amazon.sources.map((row: { sourceId: string }) => [row.sourceId, row]));
const turkeyInvestigations = new Map(turkey.investigations.map((row: { sourceId: string }) => [row.sourceId, row]));
const products: Product[] = [
  ...amazon.candidates.map((row: { exactProductId: string; categoryId: string; wave: number; brand: string; commercialModel: string; manufacturerModelCode: string; configurationIdentity: string; trApplicabilitySourceId: string; asin: string }) => { const source = amazonSources.get(row.trApplicabilitySourceId) as { uri: string; kind: string }; return { exactProductId: row.exactProductId, categoryId: row.categoryId, wave: row.wave, brand: row.brand, model: row.commercialModel, manufacturerModelCode: row.manufacturerModelCode, configurationIdentity: row.configurationIdentity, sourceId: row.trApplicabilitySourceId, sourceUri: source.uri, sourceKind: source.kind, amazonRelation: "EXACT_ACTIVE", asin: row.asin }; }),
  ...turkey.candidates.map((row: { exactProductId: string; categoryId: string; wave: number; brand: string; model: string; manufacturerModelCode: string; configurationIdentity: string; trApplicabilitySourceId: string; amazonRelation: string }) => { const source = turkeyInvestigations.get(row.trApplicabilitySourceId) as { sourceUri: string; sourceKind: string }; return { exactProductId: row.exactProductId, categoryId: row.categoryId, wave: row.wave, brand: row.brand, model: row.model, manufacturerModelCode: row.manufacturerModelCode, configurationIdentity: row.configurationIdentity, sourceId: row.trApplicabilitySourceId, sourceUri: source.sourceUri, sourceKind: source.sourceKind, amazonRelation: row.amazonRelation }; }),
];
if (products.length !== 16 || new Set(products.map(row => row.exactProductId)).size !== 16 || reconciliation.combinedExactIds.some((id: string) => !products.some(row => row.exactProductId === id))) throw new Error("COMBINED_IDENTITY_MISMATCH");

const slug = (value: string) => value.toLowerCase().replaceAll(/[^a-z0-9]+/gu, "-").replaceAll(/^-|-$/gu, "");
const sources: CatalogSource[] = products.map(row => ({ sourceId: row.sourceId, kind: "OFFICIAL", uri: row.sourceUri, version: "observed-2026-09-05", observedAt: reviewedAt, reviewedAt, market: "TR", applicabilityStatus: "EXACT", status: "VERIFIED", language: "tr" }));
const offerings = products.map(row => ({ offeringId: row.exactProductId, market: "TR", lifecycle: "FROZEN" as const, validFrom: reviewedAt, identity: { kind: "PRODUCT" as const, manufacturer: row.brand, model: row.model, configuration: row.configurationIdentity, identifiers: { manufacturerModelCode: row.manufacturerModelCode, ...(row.asin ? { asin: row.asin } : {}) } } }));
const evidence = products.flatMap(row => [
  { evidenceId: `ev:model-code:${slug(row.exactProductId)}`, kind: "TECHNICAL" as const, sourceId: row.sourceId, assertionId: `assert:model-code:${slug(row.exactProductId)}`, offeringIds: [row.exactProductId], market: "TR", observedAt: reviewedAt, reviewedAt, confidence: "HIGH" as const, status: "VERIFIED" as const, limitations: ["Establishes exact identity and Türkiye applicability; it does not establish every technical specification."], assertion: { locator: "Official Türkiye product/support page: exact model or part code", value: row.manufacturerModelCode, applicability: { offeringId: row.exactProductId, market: "TR", model: row.model, configuration: row.configurationIdentity, status: "EXACT" as const } } },
  { evidenceId: `ev:configuration:${slug(row.exactProductId)}`, kind: "CAPABILITY" as const, sourceId: row.sourceId, assertionId: `assert:configuration:${slug(row.exactProductId)}`, offeringIds: [row.exactProductId], market: "TR", observedAt: reviewedAt, reviewedAt, confidence: "HIGH" as const, status: "VERIFIED" as const, limitations: ["Configuration-token capability only; performance and outcome claims remain unknown."], assertion: { locator: "Official Türkiye page: saleable configuration identity", value: row.configurationIdentity, applicability: { offeringId: row.exactProductId, market: "TR", model: row.model, configuration: row.configurationIdentity, status: "EXACT" as const } } },
]);
const facts = products.map(row => ({ factId: `fact:model-code:${slug(row.exactProductId)}`, offeringId: row.exactProductId, key: "manufacturer_model_code", value: row.manufacturerModelCode, evidenceId: `ev:model-code:${slug(row.exactProductId)}` }));
const capabilities = products.map(row => ({ capabilityId: `cap:exact-tr-configuration:${slug(row.exactProductId)}`, offeringId: row.exactProductId, key: "exact_tr_configuration_identified", state: "PRESENT" as const, evidenceId: `ev:configuration:${slug(row.exactProductId)}`, limitations: ["Does not imply decision sufficiency or comparative superiority."] }));
const categories = [...new Set(products.map(row => row.categoryId))].sort();
const needs = categories.map(categoryId => ({ needId: `need:${categoryId.toLowerCase()}:exact-compatibility`, meaning: `Confirm exact ${categoryId.toLowerCase().replaceAll("_", " ")} configuration compatibility before comparison.` }));
const mappings = products.map(row => ({ mappingId: `mapping:exact:${slug(row.exactProductId)}`, needId: `need:${row.categoryId.toLowerCase()}:exact-compatibility`, eligibleFactIds: [`fact:model-code:${slug(row.exactProductId)}`], eligibleCapabilityIds: [`cap:exact-tr-configuration:${slug(row.exactProductId)}`], policy: "QUESTION_INPUT" as const }));
const semanticCore = { l3UsageSemantics: products.map(row => ({ semanticId: `semantic:identity:${slug(row.exactProductId)}`, meaning: "Use only for exact-configuration confirmation; broader performance semantics are not yet governed.", factIds: [`fact:model-code:${slug(row.exactProductId)}`], capabilityIds: [`cap:exact-tr-configuration:${slug(row.exactProductId)}`] })), l4Needs: needs, l4NeedEvidenceMappings: mappings, l5PersonaSignals: categories.map(categoryId => ({ signalId: `persona:${categoryId.toLowerCase()}:planning`, needIds: [`need:${categoryId.toLowerCase()}:exact-compatibility`], authority: "DOMAIN_PLANNING" as const, classification: "DERIVED_PLANNING" as const, decisionUse: "NONE" as const, directCandidateEffect: "NONE" as const })), l6DailyLifeInterpretations: products.map(row => ({ interpretationId: `interpretation:identity:${slug(row.exactProductId)}`, offeringId: row.exactProductId, text: "The exact Türkiye configuration is distinguishable for follow-up compatibility questions; no performance or suitability outcome is asserted.", factIds: [`fact:model-code:${slug(row.exactProductId)}`], capabilityIds: [`cap:exact-tr-configuration:${slug(row.exactProductId)}`], method: "DETERMINISTIC_REVIEWED_MAPPING" as const, reviewedAt, polarity: "NEUTRAL" as const, limitations: ["Identity-level interpretation only."], nonGuarantees: ["No guarantee of performance, compatibility, availability, price, warranty coverage or user outcome."] })) };
const semanticDigest = `sha256:${createHash("sha256").update(JSON.stringify(semanticCore)).digest("hex")}` as const;
const withoutDigest: Omit<XpyCatalogRelease, "releaseDigest"> = { schemaVersion: XPY_CATALOG_VERSION, releaseId: "electronics-catalog-richness-tr-v0.1", releaseVersion: ELECTRONICS_RICHNESS_RELEASE_VERSION, departmentId: "ELECTRONICS", categoryId: "MULTI_CATEGORY_24_READINESS", market: "TR", lifecycle: "FROZEN", effectiveAt: reviewedAt, compatibility: { runtime: { version: XPY_RUNTIME_VERSION, digest: XPY_RUNTIME_DIGEST, domainPackId: "ELECTRONICS-INACTIVE-CANDIDATE/v0.1" }, domainPackVersion: "ELECTRONICS-INACTIVE-CANDIDATE/v0.1", semanticAuthorityVersion: "electronics-semantic-candidate/v0.1", semanticAuthorityDigest: semanticDigest, revisionClass: "SEMANTIC_POLICY_CHANGE", semanticAuthorityChange: "VERSIONED_CHANGE" }, sources, evidence, offerings, layers: { l1Facts: facts, l2Capabilities: capabilities, ...semanticCore, l7ExperienceRules: [], l8DecisionProjections: products.map(row => ({ projectionId: `projection:${slug(row.exactProductId)}`, offeringId: row.exactProductId, eligibleEvidenceIds: [`ev:model-code:${slug(row.exactProductId)}`, `ev:configuration:${slug(row.exactProductId)}`], needMappingIds: [`mapping:exact:${slug(row.exactProductId)}`], limitations: ["Identity-only evidence is insufficient for recommendation or comparison."], disclosures: ["Unknown technical, lifecycle, warranty, safety and commerce attributes are neutral and fail closed."], traceability: "EXACT" })), l9AdvisorKnowledge: [] }, externalBoundaries: { commerce: "EXTERNAL_VOLATILE_EXACT_IDENTITY_JOIN_ONLY", media: "EXTERNAL_VOLATILE_EXACT_IDENTITY_JOIN_ONLY", offerIdentityAuthority: "NONE", offerRankingAuthority: "NONE", affiliateRankingAuthority: "NONE" } };
const release: XpyCatalogRelease = { ...withoutDigest, releaseDigest: xpyCatalogReleaseDigest(withoutDigest) };
const layerStatus = { L0: "COMPLETE", L1: "PARTIAL", L2: "PARTIAL", L3: "PARTIAL", L4: "PARTIAL", L5: "PARTIAL", L6: "PARTIAL", L7: "ABSENT", L8: "PARTIAL", L9: "ABSENT", L10: "PARTIAL" } as const;
const categoryReadiness = ELECTRONICS_CATEGORY_REGISTRY.map(category => { const count = products.filter(row => row.categoryId === category.categoryId).length; return { categoryId: category.categoryId, candidateCount: count, readiness: count === 0 ? "NO_CANDIDATES" as const : count === 1 ? "SINGLE_CANDIDATE_INFORMATION_ONLY" as const : "MULTI_CANDIDATE_POLICY_REQUIRED" as const, gap: count === 0 ? "Acquire at least two exact Türkiye configurations with governed technical evidence." : count === 1 ? "Acquire a second exact candidate and category decision evidence/policy." : "Identity is sufficient for bounded catalog inclusion; technical comparison evidence and reviewed category policy are still required." }; });
const governance: ElectronicsRichnessGovernance = { schemaVersion: "electronics-richness-governance/v1", releaseVersion: ELECTRONICS_RICHNESS_RELEASE_VERSION, products: products.map(row => ({ exactProductId: row.exactProductId, categoryId: row.categoryId, layers: layerStatus, manual: { status: "ABSENT_NO_IMMUTABLE_EXACT_ARTIFACT", decisionAuthority: "NONE" }, media: { status: "ABSENT_NO_REUSE_PROVENANCE", decisionAuthority: "NONE" }, experience: { status: "ABSENT_NO_GOVERNED_AGGREGATE", technicalTruthAuthority: "NONE" }, warrantyLifecycleSafety: { status: "UNKNOWN_REQUIRES_EXACT_EVIDENCE", decisionUse: "NONE" } })), categoryReadiness, conflictsAndUnknowns: products.flatMap(row => ["EXACT_MANUAL_NOT_CHECKSUM_BOUND", "GOVERNED_MEDIA_REUSE_PROVENANCE_ABSENT", "WARRANTY_LIFECYCLE_SAFETY_NOT_ASSERTION_GOVERNED", "COMPARATIVE_TECHNICAL_FACTS_INSUFFICIENT"].map(code => ({ exactProductId: row.exactProductId, code, effect: "NEUTRAL_FAIL_CLOSED" as const }))), authority: { technicalFactEqualsDailyLifeInterpretation: false, personaDecisionUse: "NONE", commerceYEffect: "NONE", mediaYEffect: "NONE", manualYEffect: "NONE", activationPerformed: false } };
const amazonAudit = new Map(amazon.auditRows.filter((row: { asin: string | null }) => row.asin).map((row: { asin: string }) => [row.asin, row]));
const commerceMedia = { schemaVersion: "electronics-external-commerce-media/v1", releaseVersion: ELECTRONICS_RICHNESS_RELEASE_VERSION, freshness: { observedAt: reviewedAt, expiresAt: "2026-09-06T14:00:00.000Z", staleEffect: "DISPLAY_UNAVAILABLE_NO_Y_EFFECT" }, products: products.map(row => { const observation = row.asin ? amazonAudit.get(row.asin) as { canonicalAmazonUrl: string; priceObserved: unknown; seller: unknown; fulfilment: unknown; stockState: string; sponsored: boolean } : undefined; return { exactProductId: row.exactProductId, amazonRelation: row.amazonRelation, offers: observation ? [{ merchant: "Amazon.com.tr", url: observation.canonicalAmazonUrl, priceObserved: observation.priceObserved, seller: observation.seller, fulfilment: observation.fulfilment, stockState: observation.stockState, sponsored: observation.sponsored, decisionAuthority: "NONE" }] : [], nonAmazonTurkeyOffers: [], media: [], affiliateRankingAuthority: "NONE", yEffect: "NONE" }; }), boundaries: { technicalAuthority: "NONE", applicabilityAuthority: "NONE", rankingAuthority: "NONE", membershipEffect: "NONE", yEffect: "NONE" } };
const sourceRegistry = { schemaVersion: "electronics-source-registry/v1", sources, internationalSources: [
  { researchId: "INTL-SWEEP-SAMSUNG-A26", exactFamilyCode: "SM-A266B", uri: "https://www.samsung.com/ae/smartphones/galaxy-a/galaxy-a26-5g-black-256gb-sm-a266bzkjmea/", market: "AE", disposition: "NOT_ADMITTED_REGION_CONFIGURATION_DIFFERS", trApplicabilityAuthority: "NONE", decisionAuthority: "NONE" },
  { researchId: "INTL-SWEEP-SAMSUNG-A36", exactFamilyCode: "SM-A366B", uri: "https://www.samsung.com/global/sustainability/policy-file/AYVhR1k6BicAIx95/LCA%20Results%20for%20Smart%20phones_0222.pdf", market: "GLOBAL", disposition: "NOT_ADMITTED_FAMILY_SCOPED_ONLY", trApplicabilityAuthority: "NONE", decisionAuthority: "NONE" },
  { researchId: "INTL-SWEEP-SAMSUNG-TAB-S11", exactFamilyCode: "SM-X730", uri: "https://www.samsung.com/uk/tablets/galaxy-tab-s/galaxy-tab-s11-silver-256gb-wi-fi-sm-x730nzspeub/", market: "UK", disposition: "NOT_ADMITTED_REGION_SUFFIX_DIFFERS", trApplicabilityAuthority: "NONE", decisionAuthority: "NONE" },
  { researchId: "INTL-SWEEP-SAMSUNG-TAB-S10-FE", exactFamilyCode: "SM-X520", uri: "https://www.samsung.com/ca/tablets/galaxy-tab-s/galaxy-tab-s10-fe-gray-256gb-sm-x520nzaexac/", market: "CA", disposition: "NOT_ADMITTED_REGION_AND_COLOR_SUFFIX_DIFFER", trApplicabilityAuthority: "NONE", decisionAuthority: "NONE" },
], boundary: "International primary sources are a recorded gap-sweep only. None was admitted because the exact Türkiye configuration suffix was not equivalent; they cannot establish Türkiye applicability or drive Y." };
const output = path.join(root, "data/production/electronics/richness/releases", ELECTRONICS_RICHNESS_RELEASE_VERSION);
mkdirSync(output, { recursive: true });
const stable = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;
const sha = (raw: string) => `sha256:${createHash("sha256").update(raw).digest("hex")}`;
const artifacts = { "catalog-release.json": stable(release), "source-registry.json": stable(sourceRegistry), "governance-report.json": stable(governance), "commerce-media.json": stable(commerceMedia) };
const releaseIssues = validateXpyCatalogRelease(release); const governanceIssues = validateElectronicsRichness(release, governance, ELECTRONICS_CATEGORY_REGISTRY.map(row => row.categoryId));
if (releaseIssues.length || governanceIssues.length) throw new Error(`RICHNESS_INVALID:${[...releaseIssues, ...governanceIssues].join(",")}`);
for (const [name, raw] of Object.entries(artifacts)) writeFileSync(path.join(output, name), raw);
const manifest = { schemaVersion: "electronics-richness-manifest/v1", workUnitId: "WU-ELECTRONICS-CATALOG-RICHNESS-01", releaseVersion: ELECTRONICS_RICHNESS_RELEASE_VERSION, verdict: "PARTIAL", inputs: expected, counts: { products: products.length, representedCategories: categories.length, allCategories: 24, sources: sources.length, evidence: evidence.length, facts: facts.length, capabilities: capabilities.length, unknowns: governance.conflictsAndUnknowns.length }, readiness: Object.fromEntries(["NO_CANDIDATES", "SINGLE_CANDIDATE_INFORMATION_ONLY", "MULTI_CANDIDATE_POLICY_REQUIRED", "DECISION_DATA_READY"].map(status => [status, categoryReadiness.filter(row => row.readiness === status).length])), artifacts: Object.fromEntries(Object.entries(artifacts).map(([name, raw]) => [name, sha(raw)])), activation: { performed: false, registryChanged: false, domainPackChanged: false, runtimeChanged: false, databaseChanged: false, pointerChanged: false, deploymentPerformed: false } };
writeFileSync(path.join(output, "manifest.json"), stable(manifest));
console.log(JSON.stringify({ output, ...manifest.counts, readiness: manifest.readiness, releaseDigest: release.releaseDigest }));
