import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { STROLLER_PRODUCTS, STROLLER_SOURCES } from "@/features/baby/catalog";
import { ACTIVE_APPLIANCES_CATEGORY_IDS } from "@/features/appliances/categoryRegistry";
import { ELECTRONICS_CATEGORY_IDS } from "@/features/electronics/architectureBaseline";
import { personaDigest, UNIVERSAL_PERSONA_SCHEMA_VERSION, UNIVERSAL_PERSONA_TRAITS, validateUniversalPersonaPackage, type UniversalPersonaPackage } from "@/features/persona/universalAuthority";
import { rankWithBoundedSoftSignals } from "@/features/xpy/boundedSoftRanking";

const ROOT = process.cwd(), GENERATED_AT = "2026-09-06T00:00:00.000Z", RETRIEVED_AT = "2026-09-06";
const RELEASE_ID = "XPY-UNIVERSAL-PERSONA-AUTHORITY-TR-v0.1-owner-review-candidate";
const OUTPUT = path.join(ROOT, "data/production/personas/universal/release-candidates", RELEASE_ID);
type InventoryRow = { exactProductId: string; departmentId: "APPLIANCES"|"ELECTRONICS"|"BABY_AND_CHILD"; categoryId: string; brand: string; model: string; configurationIdentity: string; sourceArtifact: string };
type RawSource = UniversalPersonaPackage["sources"][number];
type ApplianceProduct = { productId:string; brand?:string; brandId?:string; model?:string; manufacturerModelIdentifier?:string; configurationIdentity:string; evidenceRefs?:string[] };
type ApplianceFact = { productId:string; sourceId?:string };
type ElectronicsProduct = { exactProductId:string; categoryId:string; manufacturer:string; modelCode:string; configurationIdentity:string };

const dirByCategory: Record<string,string> = { WASHING_MACHINE:"washing-machines",REFRIGERATOR:"refrigerators",DISHWASHER:"dishwashers",DRYER:"dryers",VACUUM:"vacuums",ROBOT_VACUUM:"robot-vacuums",FREEZER:"freezers",BUILT_IN_OVEN:"built-in-ovens",FREESTANDING_COOKER:"freestanding-cookers",HOB:"hobs",RANGE_HOOD:"range-hoods",COUNTERTOP_MICROWAVE_OVEN:"countertop-microwave-ovens",BUILT_IN_MICROWAVE_OVEN:"built-in-microwave-ovens",AIR_PURIFIER:"air-purifiers",FULLY_AUTOMATIC_ESPRESSO_MACHINE:"fully-automatic-espresso-machines",MANUAL_ESPRESSO_MACHINE:"manual-espresso-machines",FILTER_COFFEE_MACHINE:"filter-coffee-machines",TURKISH_COFFEE_MACHINE:"turkish-coffee-machines",AIR_FRYER:"air-fryers",BLENDER:"blenders",FOOD_PROCESSOR:"food-processors",ELECTRIC_STORAGE_WATER_HEATER:"electric-storage-water-heaters",INSTANTANEOUS_ELECTRIC_WATER_HEATER:"instantaneous-electric-water-heaters",SPLIT_AIR_CONDITIONER:"split-air-conditioners" };
const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;
const readJson = async (file: string) => JSON.parse(await readFile(path.join(ROOT,file),"utf8"));
const fileSha = async (file: string) => `sha256:${createHash("sha256").update(await readFile(path.join(ROOT,file))).digest("hex")}`;

async function applianceInventory(): Promise<{ rows: InventoryRow[]; sources: RawSource[] }> {
  const rows: InventoryRow[] = [], sources: RawSource[] = [];
  for (const categoryId of ACTIVE_APPLIANCES_CATEGORY_IDS) {
    const dir=dirByCategory[categoryId], pointerFile=`data/production/appliances/${dir}/active.json`, pointer=await readJson(pointerFile), release=pointer.releaseVersion;
    const base=`data/production/appliances/${dir}/releases/${release}`, candidates=[`${base}/domain-pack.json`,`${base}/catalog.json`]; let artifact="";
    for(const candidate of candidates) try { await readFile(path.join(ROOT,candidate)); artifact=candidate; break; } catch {}
    if(!artifact) throw new Error(`ACTIVE_APPLIANCE_ARTIFACT_MISSING:${categoryId}`); const payload=await readJson(artifact);
    const products=payload.products as ApplianceProduct[], facts=(payload.technicalFacts??[]) as ApplianceFact[];
    for(const product of products) rows.push({exactProductId:product.productId,departmentId:"APPLIANCES",categoryId,brand:product.brand??product.brandId??"UNKNOWN_BRAND",model:product.model??product.manufacturerModelIdentifier??"UNKNOWN_MODEL",configurationIdentity:product.configurationIdentity,sourceArtifact:artifact});
    for(const item of (payload.sources??[]) as Array<{sourceId:string;url?:string}>) { const exactProductIds=products.filter(product=>(product.evidenceRefs??[]).includes(item.sourceId)||facts.some(fact=>fact.productId===product.productId&&fact.sourceId===item.sourceId)).map(product=>product.productId); if(!exactProductIds.length||!item.url)continue; sources.push({sourceId:`persona-source:${item.sourceId}`,url:item.url,publisher:new URL(item.url).hostname,sourceType:"MANUFACTURER_POSITIONING",retrievedAt:RETRIEVED_AT,productIdentityMatch:"IDENTITY_ONLY",assertionLocator:"Existing exact-product authority page; no persona assertion admitted without independent corroboration.",market:"TR",independenceClass:"FIRST_PARTY_POSITIONING",commercialRelationship:"Manufacturer or authorized distributor source.",limitations:["Identity/technical source only; proves intended positioning at most and contributes zero persona score."],exactProductIds}); }
  }
  return {rows,sources};
}
async function electronicsInventory(): Promise<InventoryRow[]> { const artifact="data/production/electronics/runtime/releases/ELECTRONICS-RUNTIME-CATALOG-TR-v1.0/catalog.json", payload=await readJson(artifact); return (payload.products as ElectronicsProduct[]).map(product=>({exactProductId:product.exactProductId,departmentId:"ELECTRONICS",categoryId:product.categoryId,brand:product.manufacturer,model:product.modelCode,configurationIdentity:product.configurationIdentity,sourceArtifact:artifact})); }

const vocabulary: UniversalPersonaPackage["vocabulary"] = [
 ["ADVENTURE","Outdoor, exploratory or rugged-use character",["maceracı","outdoor ruhlu"]],["CHARISMATIC","Strong and memorable non-technical character",["karizmatik","karakterli"]],["COMFORT","Comfort-oriented character, never a comfort fact",["konfor odaklı","rahat hissettiren"]],["COMPACT_FEELING","Perceived spatial lightness or unobtrusiveness, not dimensions",["kompakt hissettiren","az yer kaplıyor hissi veren"]],["DESIGN_LED","Design is a central positioning theme",["tasarım odaklı","tasarımı ön planda"]],["DRIVING_ENGAGEMENT","Cars-only engagement character retained from V3.9",["sürüşü keyifli","sürücü odaklı"]],["FAMILY_ORIENTED","Family-life positioning, not capacity or safety proof",["aile odaklı","aileye hitap eden"]],["PLAYFUL","Playful, colourful or expressive character",["eğlenceli","oyuncu","renkli karakterli"]],["PRACTICALITY","Pragmatic/everyday-use character, not capability proof",["pragmatik","işlev odaklı","gösterişsiz iş gören"]],["PREMIUM_POSITIONING","Premium positioning only; never price or quality inference",["premium hisli","üst segment algılı"]],["PROFESSIONAL","Professional/work-oriented character",["profesyonel","iş odaklı","kurumsal görünümlü"]],["TECHNOLOGY","Technology-led character, not technical superiority",["teknoloji odaklı","teknolojik hisli"]],["UNDERSTATED","Restrained, quiet visual character",["sade","abartısız","minimal"]],["VISUALLY_DISTINCTIVE","Visually differentiated character",["görsel olarak ayırt edici","özgün görünümlü","dikkat çekici"]],
].map(([trait,meaning,turkishExpressions])=>({trait:trait as typeof UNIVERSAL_PERSONA_TRAITS[number],meaning:meaning as string,turkishExpressions:turkishExpressions as string[],aliases:trait==="PRACTICALITY"?["PRAGMATIC"]:trait==="FAMILY_ORIENTED"?["FAMILY"]:trait==="DESIGN_LED"?["DESIGN"]:trait==="PREMIUM_POSITIONING"?["PRESTIGE"]:[]}));

async function main(){
 const appliances=await applianceInventory(), electronics=await electronicsInventory(), baby:InventoryRow[]=STROLLER_PRODUCTS.map(product=>({exactProductId:product.exactProductId,departmentId:"BABY_AND_CHILD",categoryId:"STROLLER",brand:product.manufacturer,model:product.model,configurationIdentity:product.configurationIdentity,sourceArtifact:"features/baby/catalog.ts"}));
 const inventory=[...appliances.rows,...electronics,...baby].sort((a,b)=>a.departmentId.localeCompare(b.departmentId)||a.categoryId.localeCompare(b.categoryId)||a.exactProductId.localeCompare(b.exactProductId));
 const strollerSources:RawSource[]=STROLLER_SOURCES.map(item=>({sourceId:`persona-source:${item.id}`,url:item.url,publisher:new URL(item.url).hostname,sourceType:"MANUFACTURER_POSITIONING" as const,retrievedAt:RETRIEVED_AT,productIdentityMatch:item.id.includes("TR-")?"EXACT" as const:"COMPATIBLE_FAMILY_LIMITED" as const,assertionLocator:"Existing manufacturer product page; no persona assertion admitted without independent corroboration.",market:item.id.includes("TR-")?"TR":"GLOBAL",independenceClass:"FIRST_PARTY_POSITIONING" as const,commercialRelationship:"Manufacturer source.",limitations:["Manufacturer positioning/identity only; contributes zero persona score.",...(item.id.includes("TR-")?[]:["Foreign/regional family applicability remains limited."])],exactProductIds:STROLLER_PRODUCTS.filter(product=>product.evidenceIds.includes(item.id as never)).map(product=>product.exactProductId)})).filter(row=>row.exactProductIds.length);
 const sources=[...appliances.sources,...strollerSources].sort((a,b)=>a.sourceId.localeCompare(b.sourceId));
 const records=inventory.map(row=>({...row,status:"PERSONA_EVIDENCE_UNKNOWN" as const,traits:[],claimIds:[],unknownReason:"INSUFFICIENT_INDEPENDENT_CORROBORATION",conflictIds:[]}));
 const authorityRecords=records.map(row=>({exactProductId:row.exactProductId,departmentId:row.departmentId,categoryId:row.categoryId,brand:row.brand,model:row.model,configurationIdentity:row.configurationIdentity,status:row.status,traits:row.traits,claimIds:row.claimIds,unknownReason:row.unknownReason,conflictIds:row.conflictIds}));
 const inventoryDigest=personaDigest(inventory), core={schemaVersion:UNIVERSAL_PERSONA_SCHEMA_VERSION,releaseId:RELEASE_ID,generatedAt:GENERATED_AT,inventoryDigest,vocabulary,methodology:{singleSourceAuthority:false as const,manufacturerRole:"POSITIONING_ONLY" as const,technicalFactsCanInferPersona:false as const,userThemeMinimum:{minimumReviews:20,minimumPlatforms:2,minimumIndependentAuthors:20,personalData:"EXCLUDED" as const},foreignMarketRule:"EXACT_FAMILY_COMPATIBILITY_AND_EXPLICIT_LIMITATION_REQUIRED" as const,sourceCountGaming:"FORBIDDEN" as const},scoringPolicy:{status:"PROPOSED_OWNER_APPROVAL_REQUIRED" as const,formula:"BASE_SCORE_PLUS_CAPPED_PERSONA" as const,decisionUse:"BOUNDED_SOFT_RANKING_ONLY" as const,eligibleContributions:[0.25,0.5,0.75],candidateCap:0.75 as const,membershipEffect:"NONE" as const,unknownEffect:0 as const,conflictedEffect:0 as const,inactiveEffect:0 as const,tiePolicy:"TIES_REMAIN_TIES" as const,serializationOrderAuthority:false as const},sources,claims:[],records:authorityRecords,conflicts:[],ownerApproval:{state:"PENDING" as const,requiredBindings:["VOCABULARY","EVIDENCE_RULES","EXPRESSION_MAPPINGS","SCORING_POLICY","EXACT_PRODUCT_RECORDS"],approvalId:null,approvedPayloadDigest:null}};
 const payload={...core,payloadDigest:personaDigest({...core,payloadDigest:undefined})}; const issues=validateUniversalPersonaPackage(payload,inventory); if(issues.length)throw new Error(issues.join("\n"));
 const byCategory=Object.values(Object.groupBy(inventory,row=>`${row.departmentId}:${row.categoryId}`)).map(group=>({departmentId:group![0]!.departmentId,categoryId:group![0]!.categoryId,activeExactProducts:group!.length,personaRecords:group!.length,governed:0,unknown:group!.length,conflicted:0})).sort((a,b)=>a.departmentId.localeCompare(b.departmentId)||a.categoryId.localeCompare(b.categoryId));
 if(byCategory.filter(x=>x.departmentId==="APPLIANCES").length!==ACTIVE_APPLIANCES_CATEGORY_IDS.length||byCategory.filter(x=>x.departmentId==="ELECTRONICS").length!==ELECTRONICS_CATEGORY_IDS.length)throw new Error("CATEGORY_COVERAGE_MISMATCH");
 const traceCategories=["LAPTOP","SMARTPHONE","WASHING_MACHINE","REFRIGERATOR","FULLY_AUTOMATIC_ESPRESSO_MACHINE","HEADPHONES","STROLLER"], traces=traceCategories.map(categoryId=>{const ids=inventory.filter(row=>row.categoryId===categoryId).slice(0,3).map(row=>row.exactProductId);const result=rankWithBoundedSoftSignals({eligibleCandidateIds:ids,preferences:[{eventId:`preview:${categoryId}`,preferenceKey:"DESIGN_LED",status:"ACTIVE"}],signals:ids.map(exactCandidateId=>({exactCandidateId,preferenceKey:"DESIGN_LED",mappingRef:"preview:unknown",evidenceRef:`persona-record:${exactCandidateId}`,evidenceState:"UNKNOWN" as const,contribution:0.25,reasonCode:"PERSONA_UNKNOWN_NEUTRAL",authority:{authorityId:"preview-unapproved-persona",version:RELEASE_ID,digest:payload.payloadDigest,decisionUse:"BOUNDED_SOFT_RANKING_ONLY" as const}})),scoreCap:0.75,singleSelectionAuthorized:false});return{categoryId,beforeCandidateIds:[...ids].sort(),afterCandidateIds:result.orderedCandidateIds,membershipUnchanged:JSON.stringify([...ids].sort())===JSON.stringify(result.retainedCandidateIds),selectionOutcome:result.selectionOutcome,traces:result.traces};});
 const coverage={schemaVersion:"xpy-persona-coverage-report/v1",releaseId:RELEASE_ID,inventoryDigest,totals:{activeExactProducts:inventory.length,personaRecords:records.length,governed:0,unknown:records.length,conflicted:0,sourceRecords:sources.length,independentSources:0,userThemeSources:0},byCategory,readiness:"CATALOG_NOT_READY — EXTERNAL_PERSONA_EVIDENCE_INCOMPLETE",noSilentDrops:inventory.length===records.length};
 const sourceQuality={schemaVersion:"xpy-persona-source-quality/v1",method:"Existing catalog sources were audited as a deterministic first checkpoint. Manufacturer pages establish positioning/identity only. No independent or repeated-user evidence was fabricated.",totals:{registered:sources.length,independent:0,manufacturerPositioning:sources.length,userThemeAggregates:0,commerciallyRelated:0},blocker:"Every exact product still requires independent specialist/editorial corroboration and, where used, the declared multi-platform user-theme threshold."};
 const inventoryArtifacts=await Promise.all([...new Set(inventory.map(row=>row.sourceArtifact))].sort().map(async file=>({file,sha256:await fileSha(file)})));
 const completionReport="data/production/personas/universal/release-candidates/XPY-UNIVERSAL-PERSONA-AUTHORITY-TR-v0.1-owner-review-candidate/completion-report.md";
 const manifest={schemaVersion:"xpy-universal-persona-manifest/v1",releaseId:RELEASE_ID,generatedAt:GENERATED_AT,lifecycle:"OWNER_REVIEW_CANDIDATE_NOT_ACTIVE",decisionAuthority:"NONE_UNTIL_OWNER_APPROVAL",artifacts:{"persona-authority.json":payload.payloadDigest,"inventory.json":personaDigest(inventory),"coverage-report.json":personaDigest(coverage),"source-quality-report.json":personaDigest(sourceQuality),"trace-previews.json":personaDigest(traces),"completion-report.md":await fileSha(completionReport)},inventoryArtifacts};
 await mkdir(OUTPUT,{recursive:true}); await Promise.all([["persona-authority.json",payload],["inventory.json",inventory],["coverage-report.json",coverage],["source-quality-report.json",sourceQuality],["trace-previews.json",traces],["manifest.json",manifest]].map(([name,value])=>writeFile(path.join(OUTPUT,name as string),json(value))));
 console.log(json({status:"GENERATED",releaseId:RELEASE_ID,inventory:inventory.length,categories:byCategory.length,payloadDigest:payload.payloadDigest,output:path.relative(ROOT,OUTPUT)}));
}
void main().catch(error=>{console.error(error);process.exitCode=1;});
