/* eslint-disable @typescript-eslint/no-explicit-any */
import { createHash } from "node:crypto";
import { mkdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { serializeCanonical } from "@/features/vehicle-data/productionCatalogRelease";

const ROOT = process.cwd();
const AT = "2026-08-18T18:00:00.000Z";
const EXCLUDED = new Map<string, "IDENTITY_FIELD_MISMATCH" | "PROVENANCE_INSUFFICIENT">([
  ["6fd52c36-be09-5918-a70f-c5b8b3aba511", "IDENTITY_FIELD_MISMATCH"], ["ec80fc69-2bfd-566e-bbb8-ebd5ab1c9a36", "IDENTITY_FIELD_MISMATCH"],
  ["da4dfc76-f52c-5870-b3d7-7bf33ff0001b", "IDENTITY_FIELD_MISMATCH"], ["deae889d-3153-5a48-8c7f-51eafc8ecf17", "IDENTITY_FIELD_MISMATCH"],
  ["d7459c01-11de-591c-b3ba-54cd0aed7f6a", "PROVENANCE_INSUFFICIENT"], ["3c43850f-5b8f-52dc-80c8-ad46e458c028", "PROVENANCE_INSUFFICIENT"],
  ["93034371-be93-5394-9ada-425ce9f87027", "PROVENANCE_INSUFFICIENT"], ["aec50fe7-d04d-549b-b078-7e4182d88655", "PROVENANCE_INSUFFICIENT"],
  ["817d265f-26f5-52a3-998b-ed33a37fe424", "PROVENANCE_INSUFFICIENT"], ["ca93e62a-9800-500a-867b-6f2e168c9eea", "PROVENANCE_INSUFFICIENT"],
  ["6a126fde-6808-561e-85ad-d488cdf92b05", "PROVENANCE_INSUFFICIENT"],
]);
const VALID_DACIA = new Set(["08030664-0509-51a0-ac5e-283bde7843f3", "d671819b-a90b-54d6-b20a-d230d6c69677", "84b2d12e-6ed2-5b7f-9a18-6fe6c41914c7", "7892b355-44bd-5008-be87-7f25ad1c90d6", "3bb22c59-4d34-58f6-80d0-9365943607de", "09975ae7-2fc1-599f-ab09-18d33f3d43bf", "512fbf76-d6f0-527c-a281-bfbace026310"]);
const CONFIGURATION_PROVENANCE: Record<string, { sourceId: string; sourceUrl: string; artifact: string; checksum: string; locator: string }> = {
  "08030664-0509-51a0-ac5e-283bde7843f3": { sourceId:"SRC-000041", sourceUrl:"https://www.dacia.com.tr/modeller/yeni-jogger/konfigurator-yeni.html", artifact:"data/cars/vehicle_evidence/source_snapshots/SRC-000041/2026-08-14/source.html", checksum:"f0f21ffecd8db4fed17613d40c3895b3d8183d1f01f7849e23acf26fd7607ce3", locator:"STRUCTURED_RECORD:VEC063_TURQ" },
  "d671819b-a90b-54d6-b20a-d230d6c69677": { sourceId:"SRC-000067", sourceUrl:"https://www.dacia.com.tr/modeller/yeni-logan.html", artifact:"data/cars/vehicle_evidence/source_snapshots/SRC-000067/2026-08-14/source.html", checksum:"a6138ea1f4b78720dd41cb613012d21ec7cae63fec69faf925e0d5bb8bc10a27", locator:"HTML_SECTION:Essential/TCe 100" },
  "84b2d12e-6ed2-5b7f-9a18-6fe6c41914c7": { sourceId:"SRC-000067", sourceUrl:"https://www.dacia.com.tr/modeller/yeni-logan.html", artifact:"data/cars/vehicle_evidence/source_snapshots/SRC-000067/2026-08-14/source.html", checksum:"a6138ea1f4b78720dd41cb613012d21ec7cae63fec69faf925e0d5bb8bc10a27", locator:"HTML_SECTION:Expression/Eco-G 120 auto" },
  "7892b355-44bd-5008-be87-7f25ad1c90d6": { sourceId:"SRC-000067", sourceUrl:"https://www.dacia.com.tr/modeller/yeni-logan.html", artifact:"data/cars/vehicle_evidence/source_snapshots/SRC-000067/2026-08-14/source.html", checksum:"a6138ea1f4b78720dd41cb613012d21ec7cae63fec69faf925e0d5bb8bc10a27", locator:"HTML_SECTION:Journey/Eco-G 120 auto" },
  "3bb22c59-4d34-58f6-80d0-9365943607de": { sourceId:"SRC-000082", sourceUrl:"https://www.dacia.com.tr/modeller/yeni-sandero-bi1-ph2/konfigurator-yeni.html", artifact:"data/cars/vehicle_evidence/source_snapshots/SRC-000082/2026-08-18/source.html", checksum:"dbb07d88248e0bf679f79a7855cb908d4ec431092ecb3e984f7f879dc8ea3af2", locator:"CONFIGURATOR_PATH:Essential/TCe 100" },
  "09975ae7-2fc1-599f-ab09-18d33f3d43bf": { sourceId:"SRC-000021", sourceUrl:"https://www.dacia.com.tr/modeller/yeni-sandero-stepway-bi1-ph2/konfigurator-yeni.html", artifact:"data/cars/vehicle_evidence/source_snapshots/SRC-000021/2026-08-14/source.html", checksum:"20b46da91269b77aef0f77d7d9edce740644ee431f2883760eb30d2c484b2d7e", locator:"CONFIGURATOR_PATH:Expression/Eco-G 120 auto" },
  "512fbf76-d6f0-527c-a281-bfbace026310": { sourceId:"SRC-000020", sourceUrl:"https://www.dacia.com.tr/modeller/yeni-sandero-stepway-bi1-ph2/karsilastirma.html", artifact:"data/cars/vehicle_evidence/source_snapshots/SRC-000020/2026-08-14/source.html", checksum:"cd57696d718a09136406a776fe4a2b6de89eb4de3a85b0c4d1267633f9b3e911", locator:"HTML_SECTION:Extreme/Eco-G 120 auto" },
};
const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;
const sha = (value: string) => `sha256:${createHash("sha256").update(value).digest("hex")}`;
async function immutable(file: string, content: string) { await mkdir(path.dirname(file), { recursive: true }); try { await writeFile(file, content, { encoding: "utf8", flag: "wx" }); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; if (await readFile(file, "utf8") !== content) throw new Error(`IMMUTABLE_ARTIFACT_DIFFERS:${file}`); } }

async function main() {
  const oldRoot = path.join(ROOT, "data/production/catalog/releases/v0.55.1");
  const oldCatalog = JSON.parse(await readFile(path.join(oldRoot, "catalog.json"), "utf8")) as { catalog_schema_version: string; market: string; effective_as_of: string; records: Array<{ variant: { id: string } }> };
  const oldManifest = JSON.parse(await readFile(path.join(oldRoot, "manifest.json"), "utf8")) as Record<string, unknown>;
  const records = oldCatalog.records.filter(({ variant }) => !EXCLUDED.has(variant.id)).map((record) => {
    const evidence = CONFIGURATION_PROVENANCE[record.variant.id]; if (!evidence) return record;
    const cloned = structuredClone(record) as any;
    const visit = (value: unknown): void => { if (!value || typeof value !== "object") return; const object = value as Record<string, unknown>; if (Array.isArray(object.provenance)) object.provenance = object.provenance.map((entry) => ({ ...(entry as object), sourceId:evidence.sourceId, sourceUrl:evidence.sourceUrl, accessedAt:AT, documentVersion:`Dacia exact configuration evidence; ${evidence.locator}`, extractionMethod:"DOCUMENT_IMPORT", confidence:"HIGH", limitations:[`immutableArtifact=${evidence.artifact}`,`artifactSha256=sha256:${evidence.checksum}`,`locator=${evidence.locator}`,"market=TR"] })); for (const nested of Object.values(object)) if (nested !== object.provenance) { if (Array.isArray(nested)) nested.forEach(visit); else visit(nested); } };
    visit(cloned.variant); return cloned;
  });
  if (records.length !== 566 || [...VALID_DACIA].some((id) => !records.some(({ variant }) => variant.id === id))) throw new Error("DACIA_PATCH_RECORD_SET_INVALID");
  const catalog = { ...oldCatalog, effective_as_of: AT, records };
  const rawCatalog = serializeCanonical(catalog), catalogHash = sha(rawCatalog);
  const quarantine = { schemaVersion: 1, release: "v0.55.2", parentRelease: "v0.55.1", createdAt: AT, records: [...EXCLUDED].sort(([a], [b]) => a.localeCompare(b)).map(([exactVariantId, reason]) => ({ exactVariantId, sourceCatalogRelease: "v0.55.1", excludedFromCatalogRelease: "v0.55.2", reason, auditIssueId: reason === "IDENTITY_FIELD_MISMATCH" ? "CATALOG-DQ-D41AFAEE91B604E17B74" : undefined, auditArtifactReference: "outputs/catalog-evidence-audit-dacia-batch01-v0551/configuration-audit-results.json", recommendationEligible: false, authorizationAliasAllowed: false, createdAt: AT })) };
  const correction = { schemaVersion: 1, release: "v0.55.2", relations: [...EXCLUDED].map(([id, reason]) => ({ oldExactVariantId: id, relation: "QUARANTINED_WITHOUT_AUTHORIZATION_ALIAS", reason, replacementExactVariantId: null, authorizationAliasAllowed: false })) };
  const manifest = { ...oldManifest, catalog_release_version: "0.55.2", previous_release: "0.55.1", effective_as_of: AT, catalog_payload_hash: catalogHash, record_count: records.length, publishable_record_count: records.length, included_variant_ids: records.map(({ variant }) => variant.id).sort(), source_revision: "dacia-integrity-patch-v0.55.2", source_path: "scripts/generate-dacia-integrity-stack-552.ts", generator_version: "dacia-integrity-patch-1", approval: { state: "APPROVED", reference: "user-directed-dacia-batch01-configuration-integrity-correction", at: AT }, staging: { state: "STAGED", target: "INTERNAL_INTEGRATION_NON_PRODUCTION", actor_reference: "controlled-dacia-integrity-patch", at: AT }, declared_limitations: ["11-audited-dacia-records-quarantined", "new-jogger-expression-manual-not-created-model-year-exact-source-missing", "authorization-aliases-for-quarantined-identities-forbidden"] };
  const releaseRoot = path.join(ROOT, "data/production/catalog/releases/v0.55.2");
  await immutable(path.join(releaseRoot, "catalog.json"), rawCatalog); await immutable(path.join(releaseRoot, "manifest.json"), json(manifest));
  await immutable(path.join(releaseRoot, "decision-facets.json"), await readFile(path.join(oldRoot, "decision-facets.json"), "utf8"));
  await immutable(path.join(releaseRoot, "quarantine-registry.json"), json(quarantine)); await immutable(path.join(releaseRoot, "correction-registry.json"), json(correction));
  await immutable(path.join(releaseRoot, "semantic-diff.json"), json({ parent: "v0.55.1", release: "v0.55.2", patchReason: "DACIA_BATCH01_CONFIGURATION_INTEGRITY_CORRECTION", parentRecords: 577, excludedIds: [...EXCLUDED.keys()].sort(), addedIds: [], preservedIds: records.map(({ variant }) => variant.id).sort(), recordCount: 566, newJoggerVariant: { created: false, reason: "MODEL_YEAR_EXACT_APPLICABILITY_NOT_PROVEN_FAIL_CLOSED" } }));

  const oldTdlRelease = "v2.1-0.55.1-2026-08-16-compatibility-rebind", newTdlRelease = "v2.1-0.55.2-2026-08-18-compatibility-rebind";
  const oldTdlRoot = path.join(ROOT, "data/production/technical-daily-life/releases", oldTdlRelease), oldTdl = JSON.parse(await readFile(path.join(oldTdlRoot, "technical-daily-life.json"), "utf8")), oldTdlManifest = JSON.parse(await readFile(path.join(oldTdlRoot, "manifest.json"), "utf8"));
  const tdl = { ...oldTdl, metadata: { ...oldTdl.metadata, activeCatalogVersion: "0.55.2", dailyLifeLayerVersion: newTdlRelease, compatibilityRebind: { type: "COMPATIBILITY_ONLY", sourceRelease: oldTdlRelease, catalogRelease: "v0.55.2", catalogFingerprint: catalogHash, reboundAt: AT } } }, rawTdl = json(tdl);
  const tdlManifest = { ...oldTdlManifest, releaseId: newTdlRelease, compatibleCatalogRelease: "v0.55.2", contentChecksum: sha(rawTdl), compatibilityRebind: { type: "COMPATIBILITY_ONLY", sourceRelease: oldTdlRelease, catalogFingerprint: catalogHash, reboundAt: AT }, declaredLimitations: ["mapping-editorial-content-unchanged", "compatibility-only-rebind-to-v0.55.2"] };
  const tdlRoot = path.join(ROOT, "data/production/technical-daily-life/releases", newTdlRelease); await immutable(path.join(tdlRoot, "technical-daily-life.json"), rawTdl); await immutable(path.join(tdlRoot, "manifest.json"), json(tdlManifest));

  const oldPersonaRelease = "v1.0.2-catalog-v0.55.1-2026-08-16", newPersonaRelease = "v1.0.3-catalog-v0.55.2-2026-08-18";
  const oldPersonaRoot = path.join(ROOT, "data/production/personas/safe-traits/releases", oldPersonaRelease), oldPersona = JSON.parse(await readFile(path.join(oldPersonaRoot, "vehicle-persona-safe-traits.json"), "utf8")), oldPersonaManifest = JSON.parse(await readFile(path.join(oldPersonaRoot, "manifest.json"), "utf8"));
  const activeIds = new Set(records.map(({ variant }) => variant.id)), variants = oldPersona.variants.filter((item: { exactVariantId: string }) => activeIds.has(item.exactVariantId));
  const usedFamilies = new Set(variants.map((item: { familyId: string }) => item.familyId)), families = oldPersona.families.filter((item: { familyId: string }) => usedFamilies.has(item.familyId));
  const persona = { ...oldPersona, releaseVersion: newPersonaRelease, compatibleCatalogRelease: "v0.55.2", compatibleCatalogFingerprint: catalogHash, variants, families, generatedAt: AT }, rawPersona = json(persona);
  const approvedNonEmptyFamilyCount = families.filter((item: { reviewStatus: string; traits: unknown[] }) => item.reviewStatus === "OWNER_APPROVED" && item.traits.length > 0).length;
  const keepEmptyFamilyCount = families.filter((item: { reviewStatus: string; traits: unknown[] }) => item.reviewStatus === "OWNER_APPROVED" && item.traits.length === 0).length;
  const traitDistribution = Object.fromEntries(oldPersona.traitVocabulary.map((trait: string) => [trait, families.filter((item: { traits: string[] }) => item.traits.includes(trait)).length]));
  const personaManifest = { ...oldPersonaManifest, releaseVersion: newPersonaRelease, compatibleCatalogRelease: "v0.55.2", compatibleCatalogFingerprint: catalogHash, sourceSafeDraftRelease: oldPersonaRelease, payloadSha256: sha(rawPersona), familyCount: families.length, variantCount: variants.length, approvedNonEmptyFamilyCount, keepEmptyFamilyCount, emptyTraitFamilyCount: keepEmptyFamilyCount, traitDistribution, declaredLimitations: [...new Set([...(oldPersonaManifest.declaredLimitations ?? []), "compatibility-and-stale-variant-removal-rebind-v0.55.2", "owner-approved-family-traits-unchanged"])] };
  const personaRoot = path.join(ROOT, "data/production/personas/safe-traits/releases", newPersonaRelease); await immutable(path.join(personaRoot, "vehicle-persona-safe-traits.json"), rawPersona); await immutable(path.join(personaRoot, "manifest.json"), json(personaManifest));

  const oldEquipmentRelease = "v1.2.1-catalog-v0.55.1-2026-08-18", newEquipmentRelease = "v1.2.2-catalog-v0.55.2-2026-08-18";
  const oldEquipmentRoot = path.join(ROOT, "data/production/equipment-evidence/releases", oldEquipmentRelease), equipment = JSON.parse(await readFile(path.join(oldEquipmentRoot, "equipment-evidence.json"), "utf8")), oldEquipmentManifest = JSON.parse(await readFile(path.join(oldEquipmentRoot, "manifest.json"), "utf8"));
  const reboundEquipment = { ...equipment, releaseVersion: newEquipmentRelease, compatibleCatalogRelease: "v0.55.2", compatibleCatalogFingerprint: catalogHash, state: "COLLECTING", generatedAt: AT }, rawEquipment = json(reboundEquipment);
  const equipmentManifest = { ...oldEquipmentManifest, releaseVersion: newEquipmentRelease, compatibleCatalogRelease: "v0.55.2", compatibleCatalogFingerprint: catalogHash, payloadSha256: sha(rawEquipment), generatedAt: AT, declaredLimitations: [...new Set([...(oldEquipmentManifest.declaredLimitations ?? []), "compatibility-only-empty-evidence-rebind-v0.55.2", "batch-001-evidence-not-transferred-to-corrected-identities"])] };
  const equipmentRoot = path.join(ROOT, "data/production/equipment-evidence/releases", newEquipmentRelease); await immutable(path.join(equipmentRoot, "equipment-evidence.json"), rawEquipment); await immutable(path.join(equipmentRoot, "manifest.json"), json(equipmentManifest));

  const pilotOldRoot = path.join(ROOT, "data/production/equipment-evidence/pilots/pilot-v1.0.1-catalog-v0.55.1-2026-08-18");
  await immutable(path.join(pilotOldRoot, "catalog-patch-lifecycle.json"), json({ pilotId: "EE-PILOT-001", state: "SUPERSEDED_BY_CATALOG_PATCH", supersededByCatalog: "v0.55.2", supersededAt: AT, immutableManifestPreserved: true, batch001HistoryPreserved: true }));
  const oldPilot = JSON.parse(await readFile(path.join(pilotOldRoot, "pilot-manifest.json"), "utf8")) as { variants: Array<{ exactVariantId: string; pairedExactVariantId?: string; [key: string]: unknown }> };
  const retained = oldPilot.variants.filter((item) => activeIds.has(item.exactVariantId) && !item.pairedExactVariantId);
  const catalogCandidates = records.filter(({ variant }) => !retained.some((item: { exactVariantId: string }) => item.exactVariantId === variant.id));
  while (retained.length < 22) { const next = catalogCandidates.shift(); if (!next) throw new Error("PILOT_FILL_FAILED"); retained.push({ exactVariantId: next.variant.id, canonicalBrand: (next as any).variant.brand.value, canonicalModel: (next as any).variant.model.value, trim: (next as any).variant.trim.value, modelYear: (next as any).variant.modelYear.value, bodyStyle: (next as any).variant.bodyStyle.value, vehicleUseClass: (next as any).variant.vehicleUseClass?.value ?? "UNSPECIFIED", fuelType: (next as any).variant.powertrain.fuelType.value, priceSegment: "UNSEGMENTED", selectionReason: "CATALOG_PATCH_DETERMINISTIC_FILL", testAxes: ["STRATIFIED_DETERMINISTIC_FILL"] }); }
  const groups = new Map<string, any[]>(); for (const record of records as any[]) { const key = `${record.variant.brand.value}|${record.variant.model.value}|${record.variant.modelYear.value}`; groups.set(key, [...(groups.get(key) ?? []), record]); }
  const pairs = [...groups.entries()].filter(([, items]) => items.length >= 2 && new Set(items.map((x) => x.variant.trim.value)).size >= 2).sort(([a], [b]) => a.localeCompare(b)).slice(0, 3);
  const paired: any[] = []; for (const [key, items] of pairs) { const [a, b] = items.sort((x, y) => x.variant.id.localeCompare(y.variant.id)).slice(0, 2); for (const [x, other] of [[a, b], [b, a]]) paired.push({ exactVariantId: x.variant.id, canonicalBrand: x.variant.brand.value, canonicalModel: x.variant.model.value, trim: x.variant.trim.value, modelYear: x.variant.modelYear.value, bodyStyle: x.variant.bodyStyle.value, vehicleUseClass: x.variant.vehicleUseClass?.value ?? "UNSPECIFIED", fuelType: x.variant.powertrain.fuelType.value, priceSegment: "UNSEGMENTED", selectionReason: "PAIRED_TRIM_PACKAGE_PROJECTION", testAxes: ["PAIRED_TRIM_PACKAGE_PROJECTION"], pairedFamilyId: `family-${sha(key).slice(7, 23)}`, pairedExactVariantId: other.variant.id, pairedDifferenceReason: `CATALOG_TRIM_DIFF:${x.variant.trim.value}`, expectedProjectionBoundary: "FAMILY_EVIDENCE_MUST_NOT_PROJECT_WITHOUT_EXACT_TRIM_OR_PACKAGE_LINK" }); }
  const pilotVariants = [...retained.slice(0, 22), ...paired].filter((item, index, all) => all.findIndex((x) => x.exactVariantId === item.exactVariantId) === index).slice(0, 28);
  while (pilotVariants.length < 28) { const next = catalogCandidates.find((x) => !pilotVariants.some((p) => p.exactVariantId === x.variant.id)); if (!next) throw new Error("PILOT_28_FAILED"); pilotVariants.push({ exactVariantId: next.variant.id, canonicalBrand: (next as any).variant.brand.value, canonicalModel: (next as any).variant.model.value, trim: (next as any).variant.trim.value, modelYear: (next as any).variant.modelYear.value, bodyStyle: (next as any).variant.bodyStyle.value, vehicleUseClass: (next as any).variant.vehicleUseClass?.value ?? "UNSPECIFIED", fuelType: (next as any).variant.powertrain.fuelType.value, priceSegment: "UNSEGMENTED", selectionReason: "CATALOG_PATCH_DETERMINISTIC_FILL", testAxes: ["STRATIFIED_DETERMINISTIC_FILL"] }); }
  if (!pilotVariants.some((item) => item.fuelType === "LPG")) { const lpg = (records as any[]).find((record) => record.variant.powertrain.fuelType.value === "LPG" && !pilotVariants.some((item) => item.exactVariantId === record.variant.id)); const replaceAt = pilotVariants.findLastIndex((item) => !item.pairedFamilyId && ["BEV", "DIESEL", "MHEV"].includes(item.fuelType)); if (!lpg || replaceAt < 0) throw new Error("PILOT_AXIS_UNSATISFIED:FUEL_LPG"); pilotVariants[replaceAt] = { exactVariantId:lpg.variant.id, canonicalBrand:lpg.variant.brand.value, canonicalModel:lpg.variant.model.value, trim:lpg.variant.trim.value, modelYear:lpg.variant.modelYear.value, bodyStyle:lpg.variant.bodyStyle.value, vehicleUseClass:lpg.variant.vehicleUseClass?.value ?? "UNSPECIFIED", fuelType:"LPG", priceSegment:"UNSEGMENTED", selectionReason:"FUEL_LPG", testAxes:["FUEL_LPG"] }; }
  pilotVariants.sort((a, b) => a.exactVariantId.localeCompare(b.exactVariantId));
  const pilot = { pilotId: "EE-PILOT-002", manifestVersion: "1.0.2", selectionPolicyVersion: "1.0.1", lifecycleState: "PREPARED", supersedesPilotId: "EE-PILOT-001", catalogRelease: "v0.55.2", catalogFingerprint: catalogHash, generatedAt: AT, researchStartedAt: null, completedAt: null, immutableSelection: true, variants: pilotVariants };
  const featureCodes = reboundEquipment.featureDefinitions.map((x: { featureCode: string }) => x.featureCode), matrix = pilotVariants.flatMap((variant) => featureCodes.map((featureCode: string) => ({ exactVariantId: variant.exactVariantId, featureCode, disposition: "NOT_RESEARCHED" })));
  const pilotRoot = path.join(ROOT, "data/production/equipment-evidence/pilots/pilot-v1.0.2-catalog-v0.55.2-2026-08-18"); await immutable(path.join(pilotRoot, "pilot-manifest.json"), json(pilot)); await immutable(path.join(pilotRoot, "pilot-matrix.json"), json(matrix));
  await immutable(path.join(pilotRoot, "batch-001-manifest.json"), json({ batchId: "EE-PILOT-002-BATCH-001", pilotId: "EE-PILOT-002", lifecycleState: "PREPARED", exactVariantIds: paired.slice(0, 2).map((x) => x.exactVariantId), researchStartedAt: null, immutableSelection: true }));

  const pointers = [
    ["data/production/catalog/active.json", { market: "TR", state: "ACTIVE", active_catalog_release_version: "0.55.2", catalog_payload_hash: catalogHash, activated_at: AT, activation_reference: "user-directed-dacia-integrity-patch-v0.55.2", previous_active_release: "0.55.1", rollback_release: "0.55.1" }],
    ["data/production/technical-daily-life/active.json", { state: "ACTIVE", activeTechnicalDailyLifeRelease: newTdlRelease, compatibleCatalogRelease: "v0.55.2", schemaVersion: 1 }],
    ["data/production/personas/safe-traits/active.json", { state: "ACTIVE", activeReleaseVersion: newPersonaRelease, compatibleCatalogRelease: "v0.55.2", compatibleCatalogFingerprint: catalogHash, payloadSha256: sha(rawPersona), schemaVersion: "1.1.0" }],
    ["data/production/equipment-evidence/active.json", { state: "ACTIVE", activeEquipmentEvidenceRelease: newEquipmentRelease, compatibleCatalogRelease: "v0.55.2", compatibleCatalogFingerprint: catalogHash, payloadSha256: sha(rawEquipment), schemaVersion: "1.2.1" }],
  ] as const;
  const generated = [
    ["data/production/catalog/activeCatalog.generated.ts", `// Generated. Do not edit.\nexport { default as activeCatalogPayload } from "./releases/v0.55.2/catalog.json";\nexport { default as activeCatalogManifest } from "./releases/v0.55.2/manifest.json";\nexport { default as activeDecisionFacetPayload } from "./releases/v0.55.2/decision-facets.json";\nexport const activeCatalogReleaseVersion = "0.55.2";\n`],
    ["data/production/technical-daily-life/activeTechnicalDailyLife.generated.ts", `// Generated. Do not edit.\nexport { default as activeTechnicalDailyLifePayload } from "./releases/${newTdlRelease}/technical-daily-life.json";\nexport { default as activeTechnicalDailyLifeManifest } from "./releases/${newTdlRelease}/manifest.json";\nexport const activeTechnicalDailyLifeRelease = "${newTdlRelease}";\nexport const compatibleTechnicalDailyLifeCatalogRelease = "v0.55.2";\n`],
    ["data/production/personas/safe-traits/activeVehiclePersonaSafeTraits.generated.ts", `// Generated. Do not edit.\nexport { default as activeVehiclePersonaSafeTraitRelease } from "./releases/${newPersonaRelease}/vehicle-persona-safe-traits.json";\nexport { default as activeVehiclePersonaSafeTraitManifest } from "./releases/${newPersonaRelease}/manifest.json";\nexport const activeVehiclePersonaSafeTraitReleaseVersion = "${newPersonaRelease}";\n`],
    ["data/production/equipment-evidence/activeEquipmentEvidence.generated.ts", `// Generated. Do not edit.\nexport { default as activeEquipmentEvidencePayload } from "./releases/${newEquipmentRelease}/equipment-evidence.json";\nexport { default as activeEquipmentEvidenceManifest } from "./releases/${newEquipmentRelease}/manifest.json";\nexport const activeEquipmentEvidenceRelease = "${newEquipmentRelease}";\n`],
  ] as const;
  const dryRun = { status: "READY_TO_APPLY", catalog: "v0.55.2", fingerprint: catalogHash, records: 566, layers: { dailyLife: newTdlRelease, persona: newPersonaRelease, equipment: newEquipmentRelease }, rollback: { catalog: "v0.55.1", dailyLife: oldTdlRelease, persona: oldPersonaRelease, equipment: oldEquipmentRelease } };
  await immutable(path.join(ROOT, "outputs/catalog-dacia-integrity-patch-v0.55.2/activation-dry-run.json"), json(dryRun));
  if (process.argv.includes("--dry-run")) { console.log(json(dryRun)); return; }
  const writes = [...pointers.map(([file, value]) => [file, json(value)] as const), ...generated]; const originals = new Map<string, string>(); for (const [file] of writes) originals.set(file, await readFile(path.join(ROOT, file), "utf8"));
  const temps = writes.map(([file, content]) => [file, `${path.join(ROOT, file)}.v0552-tmp`, content] as const);
  try { await Promise.all(temps.map(([, tmp, content]) => writeFile(tmp, content, "utf8"))); for (const [file, tmp] of temps) await rename(tmp, path.join(ROOT, file)); }
  catch (error) { await Promise.all([...originals].map(([file, content]) => writeFile(path.join(ROOT, file), content, "utf8"))); await Promise.all(temps.map(([, tmp]) => unlink(tmp).catch(() => undefined))); throw error; }
  await immutable(path.join(ROOT, "outputs/catalog-dacia-integrity-patch-v0.55.2/activation-result.json"), json({ ...dryRun, status: "ACTIVATED_LOCAL_POINTERS" }));
  console.log(json({ ...dryRun, status: "ACTIVATED_LOCAL_POINTERS", pilot: "EE-PILOT-002", firstBatch: paired.slice(0, 2).map((x) => x.exactVariantId) }));
}
void main();
