import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { buildModelFamilyIndexes } from "@/features/decision/v2/catalog/familyIndex";
import type { CatalogVariantSnapshot } from "@/features/decision/v2/catalog/types";
import { parseTechnicalDailyLifeLayer } from "@/features/vehicle-data/technicalDailyLifeSchema";
import { assertTechnicalDailyLifeCompatibility, sha256Text } from "@/features/vehicle-data/validateTechnicalDailyLifeLayer";
import { validateVehiclePersonaSafeTraitRelease, vehiclePersonaSafeTraitManifestSchema, vehiclePersonaSafeTraitReleaseSchema } from "@/features/vehicle-data/vehiclePersonaSafeTraits";
import type { TechnicalDailyLifeManifest } from "@/types/technicalDailyLife";
import type { VehiclePersonaSafeTraitManifest, VehiclePersonaSafeTraitRelease } from "@/types/vehiclePersonaSafeTraits";

const ROOT=process.cwd(),CATALOG_VERSION="v0.55.1",TDL_OLD="v2.1-0.55.0-2026-08-16",TDL_NEW="v2.1-0.55.1-2026-08-16-compatibility-rebind",PERSONA_OLD="v1.0.1-catalog-v0.55.0-2026-08-16",PERSONA_NEW="v1.0.2-catalog-v0.55.1-2026-08-16",REBIND_AT="2026-08-16T19:33:14.000Z";
async function immutable(file:string,content:string){try{await writeFile(file,content,{encoding:"utf8",flag:"wx"})}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;if(await readFile(file,"utf8")!==content)throw new Error(`IMMUTABLE_RELEASE_ARTIFACT_DIFFERS:${file}`)}}
const json=(value:unknown)=>`${JSON.stringify(value,null,2)}\n`,hash=(value:string)=>`sha256:${createHash("sha256").update(value).digest("hex")}`;
async function main(){
  const catalogRaw=await readFile(path.join(ROOT,"data/production/catalog/releases/v0.55.1/catalog.json"),"utf8"),catalogManifest=JSON.parse(await readFile(path.join(ROOT,"data/production/catalog/releases/v0.55.1/manifest.json"),"utf8")) as {catalog_payload_hash:string};const catalog=JSON.parse(catalogRaw) as {records:{variant:{id:string;brand:{value:string};model:{value:string}}}[]};
  const tdlOldRoot=path.join(ROOT,"data/production/technical-daily-life/releases",TDL_OLD),tdlNewRoot=path.join(ROOT,"data/production/technical-daily-life/releases",TDL_NEW);const oldTdl=JSON.parse(await readFile(path.join(tdlOldRoot,"technical-daily-life.json"),"utf8")) as {metadata:Record<string,unknown>;fields:unknown[]};const oldTdlManifest=JSON.parse(await readFile(path.join(tdlOldRoot,"manifest.json"),"utf8")) as TechnicalDailyLifeManifest;
  const tdl={...oldTdl,metadata:{...oldTdl.metadata,activeCatalogVersion:"0.55.1",dailyLifeLayerVersion:TDL_NEW,generatedAt:"2026-08-16",compatibilityRebind:{type:"COMPATIBILITY_ONLY",sourceRelease:TDL_OLD,catalogRelease:CATALOG_VERSION,catalogFingerprint:catalogManifest.catalog_payload_hash,reboundAt:REBIND_AT}}};const rawTdl=json(tdl),tdlChecksum=sha256Text(rawTdl);
  const tdlManifest={...oldTdlManifest,releaseId:TDL_NEW,compatibleCatalogRelease:CATALOG_VERSION,producedAt:"2026-08-16",source:{...oldTdlManifest.source,identity:`${oldTdlManifest.source.identity}:compatibility-rebind-v0.55.1`},contentChecksum:tdlChecksum,compatibilityRebind:{type:"COMPATIBILITY_ONLY",sourceRelease:TDL_OLD,catalogFingerprint:catalogManifest.catalog_payload_hash,reboundAt:REBIND_AT},declaredLimitations:["mapping-editorial-content-unchanged","compatibility-only-rebind-to-v0.55.1"]};
  const parsedTdl=parseTechnicalDailyLifeLayer(tdl);assertTechnicalDailyLifeCompatibility({layer:parsedTdl,records:catalog.records,catalogRelease:CATALOG_VERSION,expectedCatalogRelease:CATALOG_VERSION});
  const mappings=parsedTdl.fields.flatMap((field)=>field.usageMappings);if(parsedTdl.fields.length!==31||mappings.length!==117||mappings.reduce((n,m)=>n+m.dailyLifeExamples.length,0)!==220||mappings.reduce((n,m)=>n+m.advisorQuestions.length,0)!==321)throw new Error("TDL_REBIND_COUNTS_CHANGED");
  await mkdir(tdlNewRoot,{recursive:true});await immutable(path.join(tdlNewRoot,"technical-daily-life.json"),rawTdl);await immutable(path.join(tdlNewRoot,"manifest.json"),json(tdlManifest));

  const personaOldRoot=path.join(ROOT,"data/production/personas/safe-traits/releases",PERSONA_OLD),personaNewRoot=path.join(ROOT,"data/production/personas/safe-traits/releases",PERSONA_NEW);const oldPersona=vehiclePersonaSafeTraitReleaseSchema.parse(JSON.parse(await readFile(path.join(personaOldRoot,"vehicle-persona-safe-traits.json"),"utf8"))) as VehiclePersonaSafeTraitRelease;const oldPersonaManifest=vehiclePersonaSafeTraitManifestSchema.parse(JSON.parse(await readFile(path.join(personaOldRoot,"manifest.json"),"utf8"))) as VehiclePersonaSafeTraitManifest;
  const persona:VehiclePersonaSafeTraitRelease={...oldPersona,releaseVersion:PERSONA_NEW,compatibleCatalogRelease:CATALOG_VERSION,compatibleCatalogFingerprint:catalogManifest.catalog_payload_hash,generatedAt:REBIND_AT};const rawPersona=json(persona),personaChecksum=hash(rawPersona);const personaManifest:VehiclePersonaSafeTraitManifest={...oldPersonaManifest,releaseVersion:PERSONA_NEW,compatibleCatalogRelease:CATALOG_VERSION,compatibleCatalogFingerprint:catalogManifest.catalog_payload_hash,sourceSafeDraftRelease:PERSONA_OLD,payloadSha256:personaChecksum,declaredLimitations:[...new Set([...oldPersonaManifest.declaredLimitations.filter((item)=>item!=="compatible-catalog-currently-future-effective-at-2026-08-16-runtime-clock"),"compatibility-only-rebind-from-v1.0.1-catalog-v0.55.0","owner-approval-remains-scoped-to-identical-sanitized-trait-content","catalog-version-or-fingerprint-change-requires-a-new-compatible-safe-persona-release"])]};
  const snapshotVariants=catalog.records.map(({variant})=>({id:variant.id,brand:variant.brand.value,model:variant.model.value})) as CatalogVariantSnapshot[];const families=buildModelFamilyIndexes(snapshotVariants).familyIndex.values().map((family)=>({familyId:family.familyId,variantIds:family.variantIds}));const personaErrors=validateVehiclePersonaSafeTraitRelease({release:persona,manifest:personaManifest,rawPayload:rawPersona,catalogRelease:CATALOG_VERSION,catalogFingerprint:catalogManifest.catalog_payload_hash,catalogVariantIds:snapshotVariants.map((variant)=>variant.id),catalogFamilies:families});if(personaErrors.length)throw new Error(`PERSONA_REBIND_INVALID:${personaErrors.join(",")}`);
  if(JSON.stringify(oldPersona.families)!==JSON.stringify(persona.families)||JSON.stringify(oldPersona.variants)!==JSON.stringify(persona.variants))throw new Error("PERSONA_REBIND_CONTENT_CHANGED");
  await mkdir(personaNewRoot,{recursive:true});await immutable(path.join(personaNewRoot,"vehicle-persona-safe-traits.json"),rawPersona);await immutable(path.join(personaNewRoot,"manifest.json"),json(personaManifest));
  console.log(JSON.stringify({catalogRelease:CATALOG_VERSION,dailyLife:{release:TDL_NEW,checksum:tdlChecksum,mappings:117,examples:220,questions:321},persona:{release:PERSONA_NEW,checksum:personaChecksum,families:397,variants:577,signals:534}}));
}
void main();
