import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ELECTRONICS_CATEGORY_REGISTRY, type ElectronicsCategoryId } from "../features/electronics/architectureBaseline";
import { ELECTRONICS_CATEGORY_POLICY_CANONICALIZATION, ELECTRONICS_CATEGORY_POLICY_SCHEMA, ELECTRONICS_CATEGORY_POLICY_VERSION, digestElectronicsPolicy, validateElectronicsCategoryPolicy, type ElectronicsCategoryPolicyArtifact, type ElectronicsCategoryPolicyPayload, type ElectronicsRiskBoundary } from "../features/electronics/categoryPolicy";

const root = process.cwd(); const pretty = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`; const fileSha = (raw: string | Buffer) => `sha256:${createHash("sha256").update(raw).digest("hex")}` as `sha256:${string}`;
const evidenceInputs = [
  { wave: 1 as const, releaseVersion: "ELECTRONICS-WAVE-1-DIVERSITY-REPAIR-TR-v0.1", artifactPath: "data/production/electronics/wave-1-repair/releases/ELECTRONICS-WAVE-1-DIVERSITY-REPAIR-TR-v0.1/repair-release.json", manifestPath: "data/production/electronics/wave-1-repair/releases/ELECTRONICS-WAVE-1-DIVERSITY-REPAIR-TR-v0.1/manifest.json", releaseDigest: "sha256:4f66ab249373ae03580733249472a3ddebc3fe0369707afd7abec14d2e6b5ab2" as const },
  { wave: 2 as const, releaseVersion: "ELECTRONICS-WAVE-2-GAME-CONSOLE-IDENTITY-REPAIR-TR-v0.1", artifactPath: "data/production/electronics/wave-2-repair/releases/ELECTRONICS-WAVE-2-GAME-CONSOLE-IDENTITY-REPAIR-TR-v0.1/repair-release.json", manifestPath: "data/production/electronics/wave-2-repair/releases/ELECTRONICS-WAVE-2-GAME-CONSOLE-IDENTITY-REPAIR-TR-v0.1/manifest.json", releaseDigest: "sha256:824b159a07e7e6c586b687627bb29591a417454c6d475cbbcdba7dec915598f1" as const },
  { wave: 3 as const, releaseVersion: "ELECTRONICS-WAVE-3-EVIDENCE-TR-v0.1", artifactPath: "data/production/electronics/wave-3-evidence/releases/ELECTRONICS-WAVE-3-EVIDENCE-TR-v0.1/evidence-release.json", manifestPath: "data/production/electronics/wave-3-evidence/releases/ELECTRONICS-WAVE-3-EVIDENCE-TR-v0.1/manifest.json", releaseDigest: "sha256:13fe5452cff50e1115f39b68c3a8382f249caa7a5d71c9651a44991a068ca773" as const },
  { wave: 4 as const, releaseVersion: "ELECTRONICS-WAVE-4-SMART-HOME-HUB-REPAIR-TR-v0.1", artifactPath: "data/production/electronics/wave-4-repair/releases/ELECTRONICS-WAVE-4-SMART-HOME-HUB-REPAIR-TR-v0.1/repair-release.json", manifestPath: "data/production/electronics/wave-4-repair/releases/ELECTRONICS-WAVE-4-SMART-HOME-HUB-REPAIR-TR-v0.1/manifest.json", releaseDigest: "sha256:548f7337fc9de4cbf70b04c8f4b8ff39d6059ee2b7b71a4da91733a3d44e1975" as const },
];
type Evidence = { comparativeFacts: readonly { categoryId: ElectronicsCategoryId; key: string }[]; categoryReadiness: readonly { categoryId: ElectronicsCategoryId; readiness: string }[] };
const evidenceByWave = new Map<number, Evidence>(); const evidenceChain = evidenceInputs.map(input => { const raw = readFileSync(path.join(root, input.artifactPath)); if (fileSha(raw) !== input.releaseDigest) throw new Error(`EVIDENCE_DIGEST_MISMATCH:${input.wave}`); const parsed = JSON.parse(raw.toString("utf8")) as Evidence; if (parsed.categoryReadiness.some(row => row.readiness !== "DECISION_EVIDENCE_READY")) throw new Error(`EVIDENCE_NOT_READY:${input.wave}`); evidenceByWave.set(input.wave, parsed); return { wave: input.wave, releaseVersion: input.releaseVersion, releaseDigest: input.releaseDigest, artifactPath: input.artifactPath, manifestDigest: fileSha(readFileSync(path.join(root, input.manifestPath))) }; });
const privacy = new Set<ElectronicsCategoryId>(["SMARTPHONE", "LAPTOP", "TABLET", "TELEVISION", "E_READER", "GAME_CONSOLE", "WIFI_ROUTER_MESH", "NETWORK_ATTACHED_STORAGE", "PRINTER", "SMARTWATCH", "FITNESS_TRACKER", "HOME_SECURITY_CAMERA", "VIDEO_DOORBELL", "SMART_HOME_HUB"]);
const health = new Set<ElectronicsCategoryId>(["HEADPHONES", "PORTABLE_SPEAKER", "COMPUTER_AUDIO", "SMARTWATCH", "FITNESS_TRACKER"]);
const lifecycle = new Set<ElectronicsCategoryId>(["SMARTPHONE", "LAPTOP", "TABLET", "TELEVISION", "E_READER", "DIGITAL_CAMERA", "PROJECTOR", "GAME_CONSOLE", "WIFI_ROUTER_MESH", "NETWORK_ATTACHED_STORAGE", "PRINTER", "WEBCAM", "SMARTWATCH", "FITNESS_TRACKER", "HOME_SECURITY_CAMERA", "VIDEO_DOORBELL", "SMART_HOME_HUB"]);
const power = new Set<ElectronicsCategoryId>(["SMARTPHONE", "LAPTOP", "TABLET", "MONITOR", "TELEVISION", "E_READER", "HEADPHONES", "PORTABLE_SPEAKER", "SOUNDBAR", "DIGITAL_CAMERA", "PROJECTOR", "GAME_CONSOLE", "WIFI_ROUTER_MESH", "NETWORK_ATTACHED_STORAGE", "EXTERNAL_STORAGE", "PRINTER", "WEBCAM", "COMPUTER_AUDIO", "SMARTWATCH", "FITNESS_TRACKER", "HOME_SECURITY_CAMERA", "VIDEO_DOORBELL", "SMART_HOME_HUB", "UNINTERRUPTIBLE_POWER_SUPPLY"]);
const risks = (id: ElectronicsCategoryId): ElectronicsRiskBoundary[] => ["COMPATIBILITY_ECOSYSTEM_REGION", ...(privacy.has(id) ? ["PRIVACY_ACCOUNT_CLOUD_SUBSCRIPTION" as const] : []), ...(health.has(id) ? ["HEALTH_NON_MEDICAL" as const] : []), ...(power.has(id) ? ["INSTALLATION_ELECTRICAL_BATTERY_FIRE" as const] : []), ...(lifecycle.has(id) ? ["SOFTWARE_FIRMWARE_LIFECYCLE" as const] : [])];
const labels: Record<string, string> = { WORKLOAD: "Ne için kullanacaksınız?", ROOM: "Kullanacağınız ortam nasıl?", PHONE_COMPATIBILITY: "Hangi telefonla kullanacaksınız?", PRIVACY: "Yerel kayıt ve gizlilik sizin için ne kadar önemli?", LOAD: "Bağlayacağınız cihazların toplam yükü nedir?", ECOSYSTEM: "Hangi akıllı ev ekosistemiyle kullanacaksınız?", GAME_ECOSYSTEM: "Hangi oyun ekosistemi sizin için önemli?", USE_CASE: "En çok hangi çekim türünde kullanacaksınız?" };
const categories = ELECTRONICS_CATEGORY_REGISTRY.map(row => { const evidence = evidenceByWave.get(row.wave)!; const fields = [...new Set(evidence.comparativeFacts.filter(fact => fact.categoryId === row.categoryId).map(fact => fact.key))].sort(); if (!fields.length) throw new Error(`MISSING_EVIDENCE_FIELDS:${row.categoryId}`); const accepted = [...row.categoryPolicyRequired]; return { categoryId: row.categoryId, publicLabelTr: row.publicLabelTr, evidenceReleaseDigest: evidenceInputs[row.wave - 1]!.releaseDigest, acceptedContextConcepts: accepted, identityDiscriminators: [...row.identityDiscriminators], minimumAcceptedContext: accepted.slice(0, Math.min(2, accepted.length)), governedEvidenceFieldRefs: fields.map(field => `${row.categoryId}:${field}`), questionPlan: accepted.map((concept, index) => ({ questionKey: `electronics.${row.categoryId.toLowerCase()}.${concept.toLowerCase()}`, targetConcept: concept, priority: index + 1, textTr: labels[concept] ?? `${row.publicLabelTr} seçiminizde ${concept.toLocaleLowerCase("tr-TR")} ne kadar önemli?`, choicesTr: ["Önemli", "Önemli değil", "Henüz bilmiyorum"] as const, askOnlyWhenMaterial: true as const, alreadyAnsweredSuppresses: true as const, noRepeatUnless: ["CORRECTED", "CLEARED", "AUTHORITY_MATERIALLY_CHANGED"] as const })), riskBoundaries: risks(row.categoryId) }; });
const payload: ElectronicsCategoryPolicyPayload = { schemaVersion: ELECTRONICS_CATEGORY_POLICY_SCHEMA, policyVersion: ELECTRONICS_CATEGORY_POLICY_VERSION, departmentId: "ELECTRONICS", market: "TR", lifecycle: "FROZEN", governanceStatus: "APPROVED", policyAuthorityActive: true, runtimeActive: false, evidenceChain, sharedSemantics: {
  context: { normalization: "CANONICAL_CONCEPT_VALUE_WITH_SOURCE_EVENT", correction: "SUPERSEDE_PRIOR_ACCEPTED_VALUE_AND_REEVALUATE", clear: "REMOVE_ACTIVE_VALUE_AND_ALLOW_MATERIAL_REASK", unknown: "EXPLICIT_UNKNOWN_NEVER_INFERRED", notImportant: "ACCEPTED_NON_FILTERING_VALUE" },
  x: { informationalTurn: "RESPOND_WITH_GOVERNED_INFORMATION_WITHOUT_PURCHASE_PROGRESS", advisoryBoundary: "NO_SELECTION_RECOMMENDATION_OR_CARD", offTopic: "REDIRECT_TO_CURRENT_ELECTRONICS_CATEGORY_NEVER_CARS" },
  p: { maximumQuestionsPerTurn: 1, style: "ONE_MATERIAL_HUMAN_LANGUAGE_QUESTION_WITH_CHOICES_WHERE_APPROPRIATE", forbiddenPrompt: "LIST_ALL_MEASUREMENTS_OR_FUNCTIONS", ordering: "MATERIAL_EVIDENCE_SAFETY_PRIVACY_COMPATIBILITY_THEN_STABLE_KEY", suppressAcceptedOrPendingOrUnchangedAsked: true, unknownAndNotImportantAccepted: true },
  candidateEvaluation: { hardCompatibility: "EVIDENCED_EXACT_CONSTRAINT_MISMATCH_ONLY", incompatibility: "NEEDS_AND_EXACT_CONFIGURATION_OR_REGION_CONFLICT", unknown: "UNKNOWN_NEVER_SILENT_ELIMINATION_OR_ADVANTAGE", identity: "EXACT_PRODUCT_CONFIGURATION_REGION_REVISION_REQUIRED", budget: "ONLY_USER_ENABLED_FRESH_EXACT_PRICE_MAY_HARD_FILTER", missingOrStalePrice: "UNKNOWN_NOT_TECHNICAL_ELIMINATION" },
  sufficiency: { model: "CATEGORY_REQUIRED_ACCEPTED_CONTEXT_SET_NO_NUMERIC_SCORE", informationOnly: "RESPOND", purchaseIntent: "PROGRESS_ONLY_WHEN_MINIMUM_CONTEXT_AND_ELIGIBLE_POOL_EXIST" }, selection: { algorithm: "DETERMINISTIC_PAIRWISE_EVIDENCE_DOMINANCE_STABLE_SERIALIZATION", tie: "RETURN_TIED_TOP_SET_NO_WINNER", nonDominated: "RETURN_NON_DOMINATED_SET_NO_WINNER", arrayOrderEffect: "NONE" }, recommendation: { rationale: "BIND_ACCEPTED_NEEDS_TO_GOVERNED_FACTS_AND_DAILY_LIFE_INTERPRETATION", unsupportedSuperlatives: "FORBIDDEN", singleWinner: "ONLY_UNIQUE_EVIDENCED_DOMINATOR_OR_SINGLE_ELIGIBLE" }, authorization: { order: ["SUFFICIENT_CONTEXT", "EVALUATED_POOL", "DETERMINISTIC_SELECTION", "EVIDENCE_BOUND_RATIONALE", "AUTHORIZATION", "CARD_PROJECTION"], cardWithoutAuthorization: "FORBIDDEN" }, persona: { mode: "DERIVED_PLANNING", decisionUse: "NONE", directCandidateEffect: "NONE" }, commerce: { l10RankingEffect: "NONE", amazonEffect: "NONE", affiliateReviewSellerProminenceEffect: "NONE", soleException: "EXPLICIT_USER_ENABLED_FRESH_EXACT_HARD_BUDGET_FILTER" }, manuals: { layer: "L9_ADVISOR_KNOWLEDGE", technicalAuthority: "NONE_UNLESS_SEPARATELY_PROMOTED" },
}, categories, isolation: { appliancesPolicyImported: false, carsPolicyImported: false, mechanicsReusedOnly: true, electronicsEvidenceOnly: true }, boundaries: { departmentRegistryActivated: false, domainPackActivated: false, persistenceChanged: false, publicUiChanged: false, productionRuntimeActivated: false, deployed: false } };
const artifact: ElectronicsCategoryPolicyArtifact = { envelopeSchemaVersion: "electronics-category-policy-artifact/v1", canonicalSerialization: ELECTRONICS_CATEGORY_POLICY_CANONICALIZATION, policyDigest: digestElectronicsPolicy(payload), payload }; const issues = validateElectronicsCategoryPolicy(artifact); if (issues.length) throw new Error(`POLICY_INVALID:${issues.join(",")}`);
const output = path.join(root, "data/production/electronics/category-policy/releases", ELECTRONICS_CATEGORY_POLICY_VERSION); mkdirSync(output, { recursive: true }); const policyRaw = pretty(artifact); writeFileSync(path.join(output, "policy.json"), policyRaw);
const approvalCore = { schemaVersion: "electronics-category-policy-approval-event/v1", eventId: `ELECTRONICS-CATEGORY-POLICY-POA-${artifact.policyDigest.slice(7, 23).toUpperCase()}`, workUnitId: "WU-ELECTRONICS-CATEGORY-POLICY-FREEZE-01", approvedAt: "2026-09-05T14:49:00+03:00", approvedBy: "PRODUCT_OWNER", authorityBasis: "USER_STANDING_SCOPE_BOUND_AUTHORIZATION", scope: "ELECTRONICS_24_CATEGORY_POLICY_AUTHORITY_ONLY", policyVersion: ELECTRONICS_CATEGORY_POLICY_VERSION, policyDigest: artifact.policyDigest, validationIssues: [], runtimeOrPublicActivationAuthorized: false } as const; const approval = { ...approvalCore, approvalEventDigest: digestElectronicsPolicy(approvalCore) }; const approvalRaw = pretty(approval); writeFileSync(path.join(output, "approval-event.json"), approvalRaw);
const manifestCore = { schemaVersion: "electronics-category-policy-manifest/v1", workUnitId: "WU-ELECTRONICS-CATEGORY-POLICY-FREEZE-01", policyVersion: ELECTRONICS_CATEGORY_POLICY_VERSION, verdict: "IMPLEMENTED", categoryCount: 24, evidenceChain, policyDigest: artifact.policyDigest, policyArtifactSha256: fileSha(policyRaw), approvalEventDigest: approval.approvalEventDigest, approvalArtifactSha256: fileSha(approvalRaw), policyAuthorityActive: true, runtimeActive: false, boundaries: payload.boundaries }; const manifest = { ...manifestCore, manifestPayloadDigest: digestElectronicsPolicy(manifestCore) }; const manifestRaw = pretty(manifest); writeFileSync(path.join(output, "manifest.json"), manifestRaw);
const active = { schemaVersion: "electronics-category-policy-active-pointer/v1", lifecycle: "ACTIVE", authorityOnly: true, policyVersion: ELECTRONICS_CATEGORY_POLICY_VERSION, policyDigest: artifact.policyDigest, policyFile: path.relative(root, path.join(output, "policy.json")), artifactSha256: fileSha(policyRaw), approvalEventFile: path.relative(root, path.join(output, "approval-event.json")), approvalEventDigest: approval.approvalEventDigest, approvalArtifactSha256: fileSha(approvalRaw), manifestFile: path.relative(root, path.join(output, "manifest.json")), manifestSha256: fileSha(manifestRaw), runtimeActive: false }; const activeDir = path.join(root, "data/production/electronics/category-policy"); mkdirSync(activeDir, { recursive: true }); writeFileSync(path.join(activeDir, "active.json"), pretty(active));
console.log(JSON.stringify({ output, policyDigest: artifact.policyDigest, policyArtifactSha256: fileSha(policyRaw), approvalEventDigest: approval.approvalEventDigest, manifestSha256: fileSha(manifestRaw), activePointerSha256: fileSha(pretty(active)), categories: categories.length }));
