import{mkdir,mkdtemp,readFile,rename,rm,writeFile}from"node:fs/promises";import{tmpdir}from"node:os";import path from"node:path";import{buildPublishedCatalog}from"@/features/vehicle-data/buildPublishedCatalog";import*as R from"@/features/vehicle-data/productionCatalogRelease";import type{ProductionCatalogReleaseManifest,ProductionCatalogReleasePayload}from"@/features/vehicle-data/productionCatalogRelease";import type{PilotVehicleRecord}from"@/data/production/pilotVehicles";import{twentiethReleaseSourceRecords}from"@/scripts/generate-alphabetic-production-catalog-releases";
import{hongqiBatch01Records}from"@/data/production/hongqiBatch01";import{jaecooBatch01Records}from"@/data/production/jaecooBatch01";import{jaguarBatch01Records}from"@/data/production/jaguarBatch01";import{jeepBatch01Records}from"@/data/production/jeepBatch01";import{kgmBatch01Records}from"@/data/production/kgmBatch01";import{kiaBatch01Records}from"@/data/production/kiaBatch01";import{lamborghiniBatch01Records}from"@/data/production/lamborghiniBatch01";import{landRoverBatch01Records}from"@/data/production/landRoverBatch01";import{leapmotorBatch01Records}from"@/data/production/leapmotorBatch01";import{lexusBatch01Records}from"@/data/production/lexusBatch01";
import{maseratiBatch01Records}from"@/data/production/maseratiBatch01";import{mercedesBatch01Records}from"@/data/production/mercedesBatch01";import{mgBatch01Records}from"@/data/production/mgBatch01";import{miniBatch01Records}from"@/data/production/miniBatch01";import{mitsubishiBatch01Records}from"@/data/production/mitsubishiBatch01";import{nissanBatch01Records}from"@/data/production/nissanBatch01";import{omodaBatch01Records}from"@/data/production/omodaBatch01";import{opelBatch02Records}from"@/data/production/opelBatch02";import{peugeotBatch01Records}from"@/data/production/peugeotBatch01";import{porscheBatch01Records}from"@/data/production/porscheBatch01";
type S={version:string;at:string;batch:readonly PilotVehicleRecord[];payload:(x:ReturnType<typeof buildPublishedCatalog>["records"])=>ProductionCatalogReleasePayload;manifest:(x:ProductionCatalogReleasePayload)=>ProductionCatalogReleaseManifest};
const previous=[...twentiethReleaseSourceRecords,...hongqiBatch01Records,...jaecooBatch01Records,...jaguarBatch01Records,...jeepBatch01Records,...kgmBatch01Records,...kiaBatch01Records,...lamborghiniBatch01Records,...landRoverBatch01Records,...leapmotorBatch01Records,...lexusBatch01Records];
const specs:readonly S[]=[
 [R.THIRTY_FIRST_CATALOG_RELEASE_VERSION,R.THIRTY_FIRST_CATALOG_RELEASE_AS_OF,maseratiBatch01Records,R.createThirtyFirstReleasePayload,R.createThirtyFirstReleaseManifest],
 [R.THIRTY_SECOND_CATALOG_RELEASE_VERSION,R.THIRTY_SECOND_CATALOG_RELEASE_AS_OF,mercedesBatch01Records,R.createThirtySecondReleasePayload,R.createThirtySecondReleaseManifest],
 [R.THIRTY_THIRD_CATALOG_RELEASE_VERSION,R.THIRTY_THIRD_CATALOG_RELEASE_AS_OF,mgBatch01Records,R.createThirtyThirdReleasePayload,R.createThirtyThirdReleaseManifest],
 [R.THIRTY_FOURTH_CATALOG_RELEASE_VERSION,R.THIRTY_FOURTH_CATALOG_RELEASE_AS_OF,miniBatch01Records,R.createThirtyFourthReleasePayload,R.createThirtyFourthReleaseManifest],
 [R.THIRTY_FIFTH_CATALOG_RELEASE_VERSION,R.THIRTY_FIFTH_CATALOG_RELEASE_AS_OF,mitsubishiBatch01Records,R.createThirtyFifthReleasePayload,R.createThirtyFifthReleaseManifest],
 [R.THIRTY_SIXTH_CATALOG_RELEASE_VERSION,R.THIRTY_SIXTH_CATALOG_RELEASE_AS_OF,nissanBatch01Records,R.createThirtySixthReleasePayload,R.createThirtySixthReleaseManifest],
 [R.THIRTY_SEVENTH_CATALOG_RELEASE_VERSION,R.THIRTY_SEVENTH_CATALOG_RELEASE_AS_OF,omodaBatch01Records,R.createThirtySeventhReleasePayload,R.createThirtySeventhReleaseManifest],
 [R.THIRTY_EIGHTH_CATALOG_RELEASE_VERSION,R.THIRTY_EIGHTH_CATALOG_RELEASE_AS_OF,opelBatch02Records,R.createThirtyEighthReleasePayload,R.createThirtyEighthReleaseManifest],
 [R.THIRTY_NINTH_CATALOG_RELEASE_VERSION,R.THIRTY_NINTH_CATALOG_RELEASE_AS_OF,peugeotBatch01Records,R.createThirtyNinthReleasePayload,R.createThirtyNinthReleaseManifest],
 [R.FORTIETH_CATALOG_RELEASE_VERSION,R.FORTIETH_CATALOG_RELEASE_AS_OF,porscheBatch01Records,R.createFortiethReleasePayload,R.createFortiethReleaseManifest],
].map(([version,at,batch,payload,manifest])=>({version,at,batch,payload,manifest}))as S[];
async function write(s:S,payload:ProductionCatalogReleasePayload,manifest:ProductionCatalogReleaseManifest){const d=path.resolve("data/production/catalog/releases",`v${s.version}`),catalog=R.serializeCanonical(payload),meta=R.serializeCanonical(manifest),errors=R.validateProductionCatalogRelease(payload,manifest,catalog);if(errors.length)throw new Error(`${s.version}:${errors.join(",")}`);try{const[a,b]=await Promise.all([readFile(path.join(d,"catalog.json"),"utf8"),readFile(path.join(d,"manifest.json"),"utf8")]);if(a===catalog&&b===meta)return"already-exists";throw new Error(`Immutable release v${s.version} differs`)}catch(e){if((e as NodeJS.ErrnoException).code!=="ENOENT")throw e}await mkdir(path.dirname(d),{recursive:true});const t=await mkdtemp(path.join(tmpdir(),`expiya-v${s.version}-`));try{await Promise.all([writeFile(path.join(t,"catalog.json"),catalog,{encoding:"utf8",flag:"wx"}),writeFile(path.join(t,"manifest.json"),meta,{encoding:"utf8",flag:"wx"})]);await rename(t,d)}catch(e){await rm(t,{recursive:true,force:true});throw e}return"created"}
export async function generateAlphabeticReleases31to40(){let records=[...previous];const out:string[]=[];for(const s of specs){records=[...records,...s.batch];const built=buildPublishedCatalog(records,new Date(s.at));if(built.rejected.length)throw new Error(`${s.version}:${JSON.stringify(built.rejected)}`);const payload=s.payload(built.records),manifest=s.manifest(payload);out.push(`v${s.version}:${await write(s,payload,manifest)}:${payload.records.length}`)}return out}if(import.meta.url===`file://${process.argv[1]}`)generateAlphabeticReleases31to40().then(x=>console.log(x.join("\n")));
