import { readFile, readdir, stat, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { reconcileCandidateManualEvidence, sha256, stableJson, validateGlobalEvidenceCandidate, verifySha256, type CandidateManual, type GlobalEvidenceAssertion, type GlobalEvidenceSource } from "../features/appliances/globalEvidence";

const root = process.cwd();
const workUnitId = "WU-XPY-GLOBAL-EVIDENCE-CANDIDATE-REPAIR-01";
const generatedAt = "2026-09-05T01:10:00.000+03:00";
const candidateId = "APPLIANCES-GLOBAL-EVIDENCE-TR-v0.1-rc1";
const output = path.join(root, "data/production/appliances/global-evidence/release-candidates", candidateId);
const researchOutput = path.join(root, "data/research/appliances-global-evidence-01");
const manualReleasePath = path.join(root, "data/production/appliances/manuals/releases/APPLIANCES-GOVERNED-EXACT-MANUAL-L9-TR-v0.2/release.json");

const officialDomainByBrand: Record<string, string> = {
  arcelik: "arcelik.com.tr", arnica: "arnica.com.tr", arzum: "arzum.com.tr", baymak: "baymak.com.tr",
  beko: "beko.com", bosch: "bosch-home.com", delonghi: "delonghi.com", dyson: "dyson.com",
  electrolux: "electrolux.com", karaca: "karaca.com", kenwood: "kenwoodworld.com", lg: "lg.com",
  miele: "miele.com", ninja: "ninjakitchen.eu", philips: "philips.com", samsung: "samsung.com",
  siemens: "siemens-home.bsh-group.com", smeg: "smeg.com", tefal: "tefal.com", toshiba: "toshiba-aircon.co.uk",
  vestel: "vestel.com.tr", xiaomi: "mi.com",
};

function officialDomain(brand: string): string {
  const key = brand.toLocaleLowerCase("en-US").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "");
  return officialDomainByBrand[key] ?? `${key}.com`;
}

type ProductRow = { category: string; categoryId: string; productId: string; brand: string; model: string; configurationIdentity: string; parentRelease: string; parentArtifactSha256: string; sources: unknown[]; exactVerifiedAssertions: number; nullFields: string[] };

const discovered: readonly (GlobalEvidenceSource & { productId: string; assertions: readonly [string, unknown][] })[] = [
  { productId:"PHILIPS_NA350_00_TR",sourceId:"GLOBAL-PHILIPS-NA350-00-LEAFLET",url:"https://www.documents.philips.com/assets/20231219/8c19f96a9fad46849f4fb0dd01156904.pdf",publisher:"Philips",sourceType:"MANUFACTURER_DOCUMENT",market:"GB",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"NA350/00",disposition:"EXPLANATION_ONLY",assertions:[["basketCapacityL",9],["temperatureRangeC","40-200"],["presetCount",8]] },
  { productId:"XIAOMI_AC_M16_SC_TR",sourceId:"GLOBAL-XIAOMI-AC-M16-SC-IN",url:"https://www.mi.com/in/product/xiaomi-smart-air-purifier-4/specs/",publisher:"Xiaomi",sourceType:"MANUFACTURER_PRODUCT_PAGE",market:"IN",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"AC-M16-SC",disposition:"EXPLANATION_ONLY",assertions:[["particleCadrM3h",400],["effectiveAreaM2","28-48"],["maximumNoiseDbA",64]] },
  { productId:"PHILIPS_AC1711_10_TR",sourceId:"GLOBAL-PHILIPS-AC1711-10",url:"https://www.philips.com/c-p/AC1711_10/air-purifier-1000-series",publisher:"Philips",sourceType:"MANUFACTURER_PRODUCT_PAGE",market:"GLOBAL",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"AC1711/10",disposition:"EXPLANATION_ONLY",assertions:[["particleCadrM3h",300],["minimumNoiseDbA",15],["maximumNoiseDbA",50]] },
  { productId:"BOSCH_MMB6172S_TR",sourceId:"GLOBAL-BOSCH-MMB6172S-DE",url:"https://www.bosch-home.com/de/de/product/kuechengeraete/standmixer/blenders/MMB6172S",publisher:"Bosch",sourceType:"MANUFACTURER_PRODUCT_PAGE",market:"DE",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"MMB6172S",disposition:"EXPLANATION_ONLY",assertions:[["usableCapacityL",1.5],["speedSettings",2],["connectionRatingW",1200]] },
  { productId:"TEFAL_BL811D_TR",sourceId:"GLOBAL-TEFAL-BL811D-FAMILY",url:"https://www.tefal.com/instructions-for-use/csp/7211002786",publisher:"Tefal",sourceType:"MANUFACTURER_SUPPORT_PAGE",market:"GLOBAL",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"BL811DKR",disposition:"EXPLANATION_ONLY",assertions:[["familyMotorPowerW",1200],["familyPresetCount",3]] },
  { productId:"BOSCH_HBF534ES3T_TR",sourceId:"GLOBAL-BOSCH-HBF534ES3T-SUPPORT",url:"https://www.bosch-home.com/us/en/productservice/HBF534ES3T-04",publisher:"Bosch",sourceType:"MANUFACTURER_SUPPORT_PAGE",market:"US",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"HBF534ES3T/04",disposition:"EXPLANATION_ONLY",assertions:[["supportManualAvailable",true]] },
  { productId:"BOSCH_SMS4IKI62T_TR",sourceId:"GLOBAL-BOSCH-SMS4IKI62T-SUPPORT",url:"https://www.bosch-home.com/us/en/productservice/SMS4IKI62T-34",publisher:"Bosch",sourceType:"MANUFACTURER_SUPPORT_PAGE",market:"US",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"SMS4IKI62T/34",disposition:"EXPLANATION_ONLY",assertions:[["installationInstructionsAvailable",true]] },
  { productId:"BOSCH_WQG24100TR",sourceId:"GLOBAL-BOSCH-WQG24100TR-SUPPORT",url:"https://www.bosch-home.com/us/en/productservice/WQG24100TR-03",publisher:"Bosch",sourceType:"MANUFACTURER_SUPPORT_PAGE",market:"US",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"WQG24100TR/03",disposition:"EXPLANATION_ONLY",assertions:[["supportDocumentAvailable",true]] },
  { productId:"PHILIPS_HD7462_20_TR",sourceId:"GLOBAL-PHILIPS-HD7462-20",url:"https://www.documents.philips.com/assets/20230811/16e3d31e38a04cbd9c27b05b005415eb.pdf",publisher:"Philips",sourceType:"MANUFACTURER_DOCUMENT",market:"GLOBAL",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"HD7462/20",disposition:"EXPLANATION_ONLY",assertions:[["waterTankCapacityL",1.2],["brewTimeMinutes",10],["autoShutoff",true]] },
  { productId:"BOSCH_TKA6A041_TR",sourceId:"GLOBAL-BOSCH-TKA6A041-DE",url:"https://media3.bosch-home.com/Documents/specsheet/de-CH/TKA6A041.pdf",publisher:"Bosch",sourceType:"MANUFACTURER_DOCUMENT",market:"CH",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"TKA6A041",disposition:"EXPLANATION_ONLY",assertions:[["waterTankCapacityL",1.2],["connectionRatingW",1200]] },
  { productId:"KENWOOD_FDP65_450WH_TR",sourceId:"GLOBAL-KENWOOD-FDP65-450WH",url:"https://www.kenwoodworld.com/en/p/multipro-express-multipro-express-white-fdp65.450wh/FDP65.450WH.html",publisher:"Kenwood",sourceType:"MANUFACTURER_PRODUCT_PAGE",market:"GLOBAL",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"FDP65.450WH",disposition:"EXPLANATION_ONLY",assertions:[["bowlSizeL",3],["blenderCapacityL",1.5],["safetyInterlock",true]] },
  { productId:"DELONGHI_ECAM220_22_GB_TR",sourceId:"GLOBAL-DELONGHI-ECAM220-22-GB",url:"https://www.delonghi.com/en-gb/magnifica-start-automatic-coffee-maker-ecam220-22-gb/p/ECAM220.22.GB",publisher:"De'Longhi",sourceType:"MANUFACTURER_PRODUCT_PAGE",market:"GB",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"ECAM220.22.GB",disposition:"EXPLANATION_ONLY",assertions:[["waterTankCapacityL",1.8],["pumpPressureBar",15],["beanCapacityG",250]] },
  { productId:"PHILIPS_EP2220_10_TR",sourceId:"GLOBAL-PHILIPS-EP2220-10",url:"https://www.documents.philips.com/assets/20210528/7d035da1f91845c491e8ad36012800cd.pdf",publisher:"Philips",sourceType:"MANUFACTURER_DOCUMENT",market:"GLOBAL",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"EP2220/10",disposition:"EXPLANATION_ONLY",assertions:[["waterTankCapacityL",1.8],["grinderSettings",12],["pumpPressureBar",15]] },
  { productId:"BOSCH_PUE611BB5E_TR",sourceId:"GLOBAL-BOSCH-PUE611BB5E-EU",url:"https://media3.bosch-home.com/Documents/eudatasheet/en-GB/PUE611BB5E.pdf",publisher:"Bosch",sourceType:"REGULATORY_PRODUCT_FICHE",market:"EU",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"PUE611BB5E",disposition:"EXPLANATION_ONLY",assertions:[["zoneCount",4],["heatingTechnology","INDUCTION"],["energyConsumptionWhKg",175]] },
  { productId:"DELONGHI_EC685_M_TR",sourceId:"GLOBAL-DELONGHI-EC685-M",url:"https://www.delonghi.com/it-it/p/macchine-da-caffe-espresso-manuali-dedica-macchina-da-caffe-manuale-dedica-style-ec685.m/EC685.M%2BEX%253A4.html",publisher:"De'Longhi",sourceType:"MANUFACTURER_PRODUCT_PAGE",market:"IT",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"EC685.M EX:4",disposition:"EXPLANATION_ONLY",assertions:[["waterTankCapacityL",1.1],["pumpPressureBar",15],["maximumCupHeightMm",120]] },
  { productId:"SMEG_ECF02CREU_TR",sourceId:"GLOBAL-SMEG-ECF02CREU",url:"https://www.smeg.com/ch-de/produkt/ECF02CREU",publisher:"Smeg",sourceType:"MANUFACTURER_PRODUCT_PAGE",market:"CH",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"ECF02CREU",disposition:"EXPLANATION_ONLY",assertions:[["exactModelInternationalPageAvailable",true]] },
  { productId:"PHILIPS_PSA3228_01_TR",sourceId:"GLOBAL-PHILIPS-PSA3228-01",url:"https://www.documents.philips.com/assets/20240215/e380bbc417264abc84d7b117011830c7.pdf",publisher:"Philips",sourceType:"MANUFACTURER_DOCUMENT",market:"IT",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"PSA3228/01",disposition:"EXPLANATION_ONLY",assertions:[["waterTankCapacityL",2.3],["grinderSettings",15],["pumpPressureBar",15]] },
  { productId:"LG_GC_B569NLLM_TR",sourceId:"GLOBAL-LG-GC-B569NLLM-BR",url:"https://www.lg.com/br/geladeiras/geladeiras-inverse/gc-b569nllm/",publisher:"LG",sourceType:"MANUFACTURER_PRODUCT_PAGE",market:"BR",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"GC-B569NLLM",disposition:"EXCLUDED_CONFLICT",assertions:[] },
  { productId:"BOSCH_BCRC2W_TR",sourceId:"GLOBAL-BOSCH-BCRC2W-MANUAL",url:"https://media3.bosch-home.com/Documents/8001349116_C.pdf",publisher:"Bosch",sourceType:"MANUFACTURER_DOCUMENT",market:"MULTI",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"BCRC2W",disposition:"EXPLANATION_ONLY",assertions:[["multiModelManualAvailable",true]] },
  { productId:"XIAOMI_H40_OV51_TR",sourceId:"GLOBAL-XIAOMI-H40-OV51-GB",url:"https://www.mi.com/uk/product/xiaomi-robot-vacuum-h40/specs/",publisher:"Xiaomi",sourceType:"MANUFACTURER_PRODUCT_PAGE",market:"GB",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"OV51",disposition:"EXPLANATION_ONLY",assertions:[["batteryCapacityMah",5200],["vacuumDimensionsMm","340x340x97"],["dockModel","OV51JCZ"]] },
  { productId:"BOSCH_CL3000IU_W_35_E__CL3000I_35_E_TR",sourceId:"GLOBAL-BOSCH-CL3000I-35-E-INSTALL",url:"https://www.bosch-homecomfort.com/web-etk/documents/doc?id=451570",publisher:"Bosch Home Comfort",sourceType:"MANUFACTURER_DOCUMENT",market:"EU",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"CL3000iU W 35 E + CL3000i 35 E",disposition:"EXPLANATION_ONLY",assertions:[["indoorDimensionsMm","802x295x200"],["outdoorDimensionsMm","790x720x270"]] },
  { productId:"PHILIPS_FC9330_07_TR",sourceId:"GLOBAL-PHILIPS-FC9330-07",url:"https://www.philips.com/c-p/FC9330_07/powerpro-compact-bagless-vacuum-cleaner",publisher:"Philips",sourceType:"MANUFACTURER_PRODUCT_PAGE",market:"GLOBAL",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"FC9330/07",disposition:"EXPLANATION_ONLY",assertions:[["soundPowerDb",76],["dustCapacityL",1.5],["actionRadiusM",9]] },
  { productId:"BOSCH_BGC21X300_TR",sourceId:"GLOBAL-BOSCH-BGC21X300-DE",url:"https://www.bosch-home.com/de/de/product/staubsauger/beutellose-staubsauger/BGC21X300",publisher:"Bosch",sourceType:"MANUFACTURER_PRODUCT_PAGE",market:"DE",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"BGC21X300",disposition:"EXPLANATION_ONLY",assertions:[["internationalProductPageAvailable",true]] },
  { productId:"BOSCH_BGC41PET_TR",sourceId:"GLOBAL-BOSCH-BGC41PET-DE",url:"https://media3.bosch-home.com/Documents/specsheet/de-CH/BGC41PET.pdf",publisher:"Bosch",sourceType:"MANUFACTURER_DOCUMENT",market:"CH",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"BGC41PET",disposition:"EXPLANATION_ONLY",assertions:[["soundPowerDb",72],["dustCapacityL",2.4],["actionRadiusM",10]] },
  { productId:"appliances:wm:tr:miele:wwa120-wcs-8kg-active",sourceId:"GLOBAL-MIELE-WWA120-EU-FICHE",url:"https://media.miele.com/downloads/4a/05/01_C7F128284A4D1FD0A9E54A2CD6B74A05.pdf",publisher:"Miele",sourceType:"REGULATORY_PRODUCT_FICHE",market:"GB",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"WWA120 WCS 8kg Active",disposition:"EXPLANATION_ONLY",assertions:[["ratedCapacityKg",8],["energyClass","A"],["waterConsumptionLCycle",48]] },
  { productId:"appliances:wm:tr:lg:f4r3tyw3we",sourceId:"GLOBAL-LG-F4R3TYW3WE-EU-FICHE",url:"https://www.lg.com/dk/lgecs.downloadFile.ldwf?DOC_ID=20210227125408&FILE_NAME=WO_Eco4060_Product_Fiche_R+type_8kg_R04_201209.pdf&GSRI_DOC=GSRI&ORIGINAL_NAME_b1_a1=WO_Eco4060_Product_Fiche_R+type_8kg_R04_201209%5B20210227014204355%5D.pdf&SPEC_DOWNLOAD=N&TC=DwnCmd",publisher:"LG",sourceType:"REGULATORY_PRODUCT_FICHE",market:"EU",retrievedAt:generatedAt,applicability:"FAMILY_SCOPED",exactModelCodeObserved:"F4R3TYW3WE",disposition:"EXPLANATION_ONLY",assertions:[["ratedCapacityKg",8],["energyClass","D"],["spinNoiseDbA",74]] }
];

async function inventory(): Promise<ProductRow[]> {
  const manualRelease = JSON.parse(await readFile(manualReleasePath, "utf8"));
  const memberByProduct = new Map(manualRelease.members.map((x: any) => [x.productId, x]));
  const rows: ProductRow[] = [];
  for (const category of (await readdir(path.join(root, "data/production/appliances"))).sort()) {
    const pointerPath = path.join(root, "data/production/appliances", category, "active.json");
    let pointer: any; try { pointer = JSON.parse(await readFile(pointerPath, "utf8")); } catch { continue; }
    if (!pointer.releaseVersion?.startsWith("APPLIANCES-")) continue;
    const releaseDir = path.join(root, "data/production/appliances", category, "releases", pointer.releaseVersion);
    let file: string; try { await stat(path.join(releaseDir, "domain-pack.json")); file = path.join(releaseDir, "domain-pack.json"); } catch { file = path.join(releaseDir, "catalog.json"); }
    const catalog = JSON.parse(await readFile(file, "utf8"));
    for (const product of catalog.products) {
      const member: any = memberByProduct.get(product.productId);
      const isWm = category === "washing-machines";
      const facts = isWm ? catalog.technicalFacts.filter((x: any) => x.productId === product.productId && x.factStatus === "VERIFIED") : Object.entries(product.technicalFacts ?? {}).filter(([, value]) => value !== null);
      const capabilities = isWm ? catalog.capabilityFacts.filter((x: any) => x.productId === product.productId && ["PRESENT", "ABSENT"].includes(x.status)) : Object.entries(product.capabilities ?? {}).filter(([, value]) => value !== null);
      const nullFields = isWm ? [] : [...Object.entries(product.technicalFacts ?? {}), ...Object.entries(product.capabilities ?? {})].filter(([, value]) => value === null).map(([key]) => key);
      const sourceIds = isWm ? new Set(catalog.evidenceAssertions.filter((x: any) => x.productId === product.productId).map((x: any) => x.sourceId)) : new Set(product.evidenceRefs ?? []);
      rows.push({ category, categoryId: member.categoryId, productId: product.productId, brand: product.brand ?? product.brandId, model: product.model ?? product.manufacturerModelIdentifier, configurationIdentity: product.configurationIdentity, parentRelease: pointer.releaseVersion, parentArtifactSha256: member.parentArtifactSha256, sources: catalog.sources.filter((x: any) => sourceIds.has(x.sourceId)), exactVerifiedAssertions: facts.length + capabilities.length, nullFields });
    }
  }
  return rows;
}

function dailyLifeText(targetKey: string): string {
  if (/noise|sound/i.test(targetKey)) return "This published sound figure can help frame where operation may be noticeable, while perceived loudness still depends on room acoustics and use.";
  if (/dimension|height|width|depth|clearance|installation|dock/i.test(targetKey)) return "This published size or installation detail can help prepare a space check, but the exact Türkiye configuration and site conditions still require verification.";
  if (/capacity|litre|liter|tank|bowl|basket|serving|dust/i.test(targetKey)) return "This published capacity can help estimate refill, emptying, or batch frequency; actual convenience depends on the household's routine.";
  if (/energy|power|watt|consumption/i.test(targetKey)) return "This declared energy or electrical figure can help contextualize connection and use, but it is not a performance score and must stay within its stated regime.";
  if (/program|preset|setting|remote|support|manual/i.test(targetKey)) return "This documented function can help explain the available workflow, while program conditions and model-specific instructions remain controlling.";
  return "This manufacturer-published characteristic can add day-to-day context, but it does not establish an outcome or the frozen Türkiye configuration.";
}

async function activePointerHashes(): Promise<Record<string, string>> {
  const base = path.join(root, "data/production/appliances");
  const paths: string[] = [];
  for (const entry of await readdir(base, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const relative = path.join("data/production/appliances", entry.name, "active.json");
    try { await stat(path.join(root, relative)); paths.push(relative); } catch {}
  }
  return Object.fromEntries(await Promise.all(paths.sort().map(async (relative) => [relative, `sha256:${sha256(await readFile(path.join(root, relative)))}`])));
}

async function main() {
  const pointerHashesBefore = await activePointerHashes();
  const rows = await inventory();
  if (rows.length !== 97 || new Set(rows.map((x) => x.categoryId)).size !== 24) throw new Error(`INVENTORY_MISMATCH:${rows.length}`);
  const manualRelease = JSON.parse(await readFile(manualReleasePath, "utf8"));
  const manualByProduct = new Map(manualRelease.manuals.map((x: any) => [x.productId, x]));
  const l9ByProduct = new Map<string, number>(); for (const x of manualRelease.l9AdvisorKnowledge) l9ByProduct.set(x.productId, (l9ByProduct.get(x.productId) ?? 0) + 1);
  let admittedManuals: CandidateManual[] = []; try { admittedManuals = JSON.parse(await readFile(path.join(researchOutput, "admitted-manuals.json"), "utf8")); } catch {}
  const reconciliation = reconcileCandidateManualEvidence({ activeManuals: manualRelease.manuals, activeL9: manualRelease.l9AdvisorKnowledge, candidateManuals: admittedManuals });
  const candidateManuals = [...reconciliation.newManuals];
  const candidateManualProductIds = new Set(admittedManuals.map((manual) => manual.productId));
  const effectiveManualProductIds = new Set([...manualByProduct.keys(), ...reconciliation.newlyCoveredManualProductIds]);
  const effectiveL9ProductIds = new Set([...l9ByProduct.keys(), ...reconciliation.newlyCoveredL9ProductIds]);
  const manualByteBindings = await Promise.all(admittedManuals.map(async (manual) => {
    const bytes = await readFile(path.join(root, manual.immutableBytesPath));
    if (!verifySha256(manual.artifactSha256, bytes) || bytes.length !== manual.byteLength) throw new Error(`MANUAL_BYTES_MISMATCH:${manual.productId}`);
    return { productId: manual.productId, path: manual.immutableBytesPath, sha256: manual.artifactSha256, byteLength: bytes.length, pageCount: manual.pageCount };
  }));
  const researchLedger = rows.map((row) => { const findings = discovered.filter((x) => x.productId === row.productId); return { categoryId: row.categoryId, category: row.category, productId: row.productId, brand: row.brand, model: row.model, configurationIdentity: row.configurationIdentity, knownGaps: [...row.nullFields, ...(effectiveManualProductIds.has(row.productId) ? [] : ["EXACT_CHECKSUM_BOUND_MANUAL"]), ...(effectiveL9ProductIds.has(row.productId) ? [] : ["L9_ADVISOR_KNOWLEDGE"])], targetSourceTypes:["INTERNATIONAL_MANUFACTURER_PRODUCT_OR_SUPPORT","OFFICIAL_MANUAL_OR_INSTALLATION_GUIDE","PRIMARY_REGULATORY_PRODUCT_FICHE"], attemptedQueries:[`site:${officialDomain(String(row.brand))} ${row.model} official manual specifications`], researchedAt:generatedAt, status:findings.length ? "RESEARCHED_SOURCE_DISCOVERED" : candidateManualProductIds.has(row.productId) ? "RESEARCHED_EXACT_MANUAL_ADMITTED" : "RESEARCHED_NO_ADMISSIBLE_NEW_SOURCE", sourceDispositions:findings.map((x) => ({ sourceId:x.sourceId, scope:x.applicability, disposition:x.disposition })) }; });
  const sources: GlobalEvidenceSource[] = discovered.map(({ productId: _productId, assertions: _assertions, ...source }) => ({ ...source, documentVersion: source.documentVersion ?? null }));
  const assertions: GlobalEvidenceAssertion[] = discovered.flatMap((source) => source.assertions.map(([targetKey, value], index) => ({ assertionId:`global-appl:${source.productId}:${targetKey}:${index + 1}`,productId:source.productId,sourceId:source.sourceId,scope:source.applicability,decisionUse:"EXPLANATION_ONLY" as const,market:source.market,targetKey,value,applicabilityReason:"Exact manufacturer model token observed outside the frozen TR market/configuration; retained as family-scoped explanation-only evidence until TR applicability is independently proven." })));
  const dailyLifeInterpretations = assertions.map((assertion) => ({ interpretationId:`l6:${assertion.assertionId}`,productId:assertion.productId,underlyingAssertionId:assertion.assertionId,authority:"EVIDENCE_BACKED_EDITORIAL",decisionUse:"EXPLANATION_ONLY",scope:assertion.scope,text:dailyLifeText(assertion.targetKey),limitations:["Does not prove the frozen Türkiye configuration.","Cannot drive filtering, ranking, questions, sufficiency, recommendation, or Y authorization."] }));
  const manualByCandidateProduct = new Map(admittedManuals.map((manual) => [manual.productId, manual]));
  const l9AdvisorKnowledge = reconciliation.newL9.map((entry,index) => { const manual=manualByCandidateProduct.get(entry.productId)!; return { knowledgeId:`l9-global:${entry.productId}:${index+1}`,productId:entry.productId,exactProductCode:manual.exactProductCode,manualArtifactSha256:entry.manualArtifactSha256,locator:entry.locator,statement:`Consult the exact ${manual.exactProductCode} manual section '${entry.locator.section}' for ${entry.locator.kind.toLowerCase()} guidance.`,decisionAuthority:"NONE",candidateEffect:"NONE",advisorReadOnly:true }; });
  const conflicts = [{ productId:"LG_GC_B569NLLM_TR", targetKey:"dimensionsAndEnergyRegime", values:["TR catalog active evidence","BR 127V product page dimensions/regime"], disposition:"UNKNOWN_EXCLUDED", reason:"SAME_MODEL_TOKEN_DIFFERENT_MARKET_CONFIGURATION_AND_ENERGY_REGIME" }];
  const boundaries = { candidateSelection:"NONE",hardFilters:"NONE",questions:"NONE",sufficiency:"NONE",ranking:"NONE",recommendation:"NONE",yAuthorization:"NONE",commerceOrdering:"NONE",l9Authority:"ADVISOR_READ_ONLY" };
  const candidate = { schemaVersion:"appliances-global-evidence-candidate/v1",workUnitId,candidateId,generatedAt,lifecycle:"RELEASE_CANDIDATE_NOT_ACTIVE",market:"TR",members:rows.map(({sources: _sources,exactVerifiedAssertions: _count,nullFields: _nulls,...row})=>row),sources,assertions,dailyLifeInterpretations,l9AdvisorKnowledge,conflicts,manualCandidates:candidateManuals,manualEvidenceReferences:manualByteBindings,boundaries,researchLedgerRef:"data/research/appliances-global-evidence-01/research-ledger.json" };
  const issues = validateGlobalEvidenceCandidate({ assertions, sources, manuals:candidateManuals, conflicts, boundaries });
  const beforeExact = rows.reduce((n,x)=>n+x.exactVerifiedAssertions,0), beforeAbsent = rows.reduce((n,x)=>n+x.nullFields.length,0) + rows.filter(x=>!manualByProduct.has(x.productId)).length + rows.filter(x=>!l9ByProduct.has(x.productId)).length;
  const improved = new Set([...discovered.filter(x=>x.disposition!=="EXCLUDED_CONFLICT").map(x=>x.productId),...admittedManuals.map(x=>x.productId)]);
  const categoryCoverage = [...new Set(rows.map(x=>x.categoryId))].sort().map(categoryId=>{const members=rows.filter(x=>x.categoryId===categoryId),ids=new Set(members.map(x=>x.productId)),family=assertions.filter(x=>ids.has(x.productId)).length,newManuals=candidateManuals.filter(x=>ids.has(x.productId)).length,newL9=l9AdvisorKnowledge.filter(x=>ids.has(x.productId)).length;return{categoryId,members:members.length,researchAttempted:members.length,exactVerifiedBefore:members.reduce((n,x)=>n+x.exactVerifiedAssertions,0),exactVerifiedAfter:members.reduce((n,x)=>n+x.exactVerifiedAssertions,0),familyScopedBefore:0,familyScopedAfter:family,conflicts:conflicts.filter(x=>ids.has(x.productId)).length,unknownNullFields:members.reduce((n,x)=>n+x.nullFields.length,0),manualsBefore:members.filter(x=>manualByProduct.has(x.productId)).length,manualsAfter:members.filter(x=>manualByProduct.has(x.productId)).length+newManuals,l9Before:members.reduce((n,x)=>n+(l9ByProduct.get(x.productId)??0),0),l9After:members.reduce((n,x)=>n+(l9ByProduct.get(x.productId)??0),0)+newL9,l6Before:0,l6After:family,productsImproved:members.filter(x=>improved.has(x.productId)).length,productsUnchanged:members.filter(x=>!improved.has(x.productId)).length};});
  const afterAbsent = rows.reduce((n,x)=>n+x.nullFields.length,0) + rows.filter(x=>!effectiveManualProductIds.has(x.productId)).length + rows.filter(x=>!effectiveL9ProductIds.has(x.productId)).length;
  const coverage = { schemaVersion:"appliances-global-evidence-coverage/v1",workUnitId,candidateId,verdict:issues.length?"FAILED":"PARTIAL",metricDefinitions:{exactVerified:"Existing accepted exact-product technical and capability assertions; candidate intentionally adds no cross-market exact assertion without TR applicability proof.",familyScoped:"New primary-source assertions with the exact model token but unproven TR configuration applicability; explanation-only.",unresolved:"Products with one or more explicit null catalog fields, plus separately recorded cross-market conflicts.",absent:"Explicit null catalog fields plus products lacking an admitted exact manual plus products lacking any L9 record; recomputed from canonical unique product sets."},before:{exactVerified:beforeExact,familyScoped:0,unresolved:rows.filter(x=>x.nullFields.length>0).length,absent:beforeAbsent,manuals:manualRelease.manuals.length,l9Entries:manualRelease.l9AdvisorKnowledge.length,l6Interpretations:0},after:{exactVerified:beforeExact,familyScoped:assertions.length,unresolved:rows.filter(x=>x.nullFields.length>0).length+conflicts.length,absent:afterAbsent,manuals:manualRelease.manuals.length+candidateManuals.length,l9Entries:manualRelease.l9AdvisorKnowledge.length+l9AdvisorKnowledge.length,l6Interpretations:dailyLifeInterpretations.length},portfolio:{members:rows.length,categories:categoryCoverage.length,researchAttempted:researchLedger.length,officialSourcesDiscovered:sources.length,productsImproved:improved.size,productsUnchanged:rows.length-improved.size,unchangedReason:"No safe new primary-source assertion survived exact/family applicability review in this bounded pass."},canonicalGains:{newManuals:candidateManuals.length,newL9Entries:l9AdvisorKnowledge.length,newManualProducts:reconciliation.newlyCoveredManualProductIds.length,newL9Products:reconciliation.newlyCoveredL9ProductIds.length},categories:categoryCoverage,conflictsAndExclusions:conflicts,validationIssues:issues };
  if (beforeExact !== 1253 || assertions.length !== 60 || dailyLifeInterpretations.length !== 60) throw new Error("EXACT_OR_FAMILY_COUNT_REGRESSION");
  if (coverage.before.manuals !== 14 || coverage.after.manuals !== 17 || coverage.before.l9Entries !== 9 || coverage.after.l9Entries !== 16 || beforeAbsent !== 213 || afterAbsent !== 207) throw new Error(`CANONICAL_COVERAGE_MISMATCH:${JSON.stringify({before:coverage.before,after:coverage.after})}`);
  const unresolved = {schemaVersion:"appliances-global-unresolved-ledger/v1",workUnitId,generatedAt,rows:researchLedger.filter(x=>x.status==="RESEARCHED_NO_ADMISSIBLE_NEW_SOURCE").map(x=>({categoryId:x.categoryId,productId:x.productId,model:x.model,attemptedQueries:x.attemptedQueries,blocker:"NO_NEW_PRIMARY_SOURCE_SURVIVED_APPLICABILITY_REVIEW"})),conflicts,manualExclusionsRef:"data/research/appliances-global-evidence-01/manual-exclusions.json"};
  if (unresolved.rows.some((row)=>candidateManualProductIds.has(row.productId))) throw new Error("ADMITTED_MANUAL_EMITTED_AS_UNRESOLVED");
  const categoryRows=categoryCoverage.map(x=>`| ${x.categoryId} | ${x.members} | ${x.exactVerifiedBefore}→${x.exactVerifiedAfter} | ${x.familyScopedBefore}→${x.familyScopedAfter} | ${x.manualsBefore}→${x.manualsAfter} | ${x.l9Before}→${x.l9After} | ${x.l6After} | ${x.productsImproved} / ${x.productsUnchanged} |`).join("\n");
  const completionReport=`# ${workUnitId} - Appliances candidate\n\n## Verdict\n\n**REPAIRED_INACTIVE_CANDIDATE.** The candidate is decision-neutral and ready for an approval decision; no activation was performed.\n\n## Canonical activation-effective totals\n\n| Metric | Before | Candidate |\n| --- | ---: | ---: |\n| Exact assertions | ${coverage.before.exactVerified} | ${coverage.after.exactVerified} |\n| Family-scoped explanation-only assertions / L6 | 0 | ${coverage.after.familyScoped} |\n| Unique exact manuals | ${coverage.before.manuals} | ${coverage.after.manuals} |\n| Non-duplicate L9 records | ${coverage.before.l9Entries} | ${coverage.after.l9Entries} |\n| Absent coverage units | ${coverage.before.absent} | ${coverage.after.absent} |\n\nArzum AR 012 is not counted as a new manual. Its active page-4 grounding is removed as a duplicate; its genuinely new page-10 installation locator remains. The four manual-researched products are not present in the unresolved ledger. LG GC-B569NLLM remains UNKNOWN_EXCLUDED.\n\n## Per-category coverage\n\n| Category | Members | Exact | Family | Manuals | L9 | L6 | Improved / unchanged |\n| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n${categoryRows}\n\n## Authority and activation boundary\n\nAll 1,253 exact assertions remain unchanged. All 60 new assertions and L6 interpretations are FAMILY_SCOPED and EXPLANATION_ONLY. All seven new L9 records are Advisor-read-only with no P/Y, filtering, ranking, sufficiency, recommendation, authorization, or commerce effect. Every candidate manual byte is checksum-bound in the manifest. Active pointer hashes are recorded before and after generation and remain identical.\n`;
  const candidateRaw=stableJson(candidate),coverageRaw=stableJson(coverage),ledgerRaw=stableJson({schemaVersion:"appliances-global-evidence-research-ledger/v1",workUnitId,generatedAt,rows:researchLedger});
  const sourceRegistryRaw=stableJson({schemaVersion:"appliances-global-source-registry/v1",workUnitId,generatedAt,sources});
  const unresolvedRaw=stableJson(unresolved);
  const manualExclusionsRaw=(await readFile(path.join(researchOutput,"manual-exclusions.json"),"utf8")).trim();
  const admittedManualsRaw=(await readFile(path.join(researchOutput,"admitted-manuals.json"),"utf8")).trim();
  await mkdir(output,{recursive:true}); await mkdir(researchOutput,{recursive:true});
  await Promise.all([[path.join(researchOutput,"research-ledger.json"),ledgerRaw],[path.join(researchOutput,"source-registry.json"),sourceRegistryRaw],[path.join(researchOutput,"unresolved-ledger.json"),unresolvedRaw],[path.join(output,"candidate.json"),candidateRaw],[path.join(output,"coverage-report.json"),coverageRaw],[path.join(output,"completion-report.md"),completionReport.trimEnd()]].map(([file,raw])=>writeFile(file,`${raw}\n`,"utf8")));
  const pointerHashesAfter=await activePointerHashes();
  if(stableJson(pointerHashesAfter)!==stableJson(pointerHashesBefore))throw new Error("ACTIVE_POINTER_MUTATION_DETECTED");
  const dryRun={schemaVersion:"appliances-global-evidence-dry-run/v1",workUnitId,candidateId,status:issues.length?"FAILED":"PASS",activePointersChanged:false,activePointerHashesBefore:pointerHashesBefore,activePointerHashesAfter:pointerHashesAfter,parentArtifactsChanged:false,decisionNeutrality:issues.filter(x=>x.startsWith("DECISION_NEUTRALITY")).length===0,membershipPreserved:rows.length===97,exactVsFamilyValidated:issues.filter(x=>x.includes("FAMILY")).length===0,manualLocatorsValidated:issues.filter(x=>x.includes("MANUAL")).length===0,manualsDeduplicatedAgainstActive:candidateManuals.length===3,l9DeduplicatedAgainstActive:l9AdvisorKnowledge.length===7,canonicalCountsValidated:coverage.after.manuals===17&&coverage.after.l9Entries===16&&coverage.after.absent===207,admittedManualsExcludedFromUnresolved:unresolved.rows.every((row)=>!candidateManualProductIds.has(row.productId)),activationAuthorized:false};
  const dryRunRaw=stableJson(dryRun);
  const composite={candidate:candidateRaw,coverage:coverageRaw,ledger:ledgerRaw,sourceRegistry:sourceRegistryRaw,unresolved:unresolvedRaw,dryRun:dryRunRaw,completionReport:completionReport.trimEnd(),manualExclusions:manualExclusionsRaw,admittedManuals:admittedManualsRaw,manualByteBindings,pointerHashesBefore,pointerHashesAfter};
  const manifest={schemaVersion:"appliances-global-evidence-manifest/v1",workUnitId,candidateId,repairedCandidateFromWorkUnitId:"WU-XPY-APPLIANCES-GLOBAL-EVIDENCE-ENRICHMENT-01",generatedAt,lifecycle:"RELEASE_CANDIDATE_NOT_ACTIVE",memberCount:rows.length,categoryCount:categoryCoverage.length,candidateSha256:`sha256:${sha256(candidateRaw)}`,coverageSha256:`sha256:${sha256(coverageRaw)}`,researchLedgerSha256:`sha256:${sha256(ledgerRaw)}`,sourceRegistrySha256:`sha256:${sha256(sourceRegistryRaw)}`,unresolvedLedgerSha256:`sha256:${sha256(unresolvedRaw)}`,dryRunSha256:`sha256:${sha256(dryRunRaw)}`,completionReportSha256:`sha256:${sha256(completionReport.trimEnd())}`,manualExclusionsSha256:`sha256:${sha256(manualExclusionsRaw)}`,admittedManualsSha256:`sha256:${sha256(admittedManualsRaw)}`,manualByteBindings,canonicalSets:{newManualProductIds:reconciliation.newlyCoveredManualProductIds,newL9ProductIds:reconciliation.newlyCoveredL9ProductIds,newManualProductIdsSha256:`sha256:${sha256(stableJson(reconciliation.newlyCoveredManualProductIds))}`,newL9ProductIdsSha256:`sha256:${sha256(stableJson(reconciliation.newlyCoveredL9ProductIds))}`},activePointerHashesBefore:pointerHashesBefore,activePointerHashesAfter:pointerHashesAfter,releaseDigest:`sha256:${sha256(stableJson(composite))}`,activation:{performed:false,activePointersChanged:false,separateApprovalRequired:true}};
  await Promise.all([[path.join(output,"decision-neutrality-dry-run.json"),dryRunRaw],[path.join(output,"manifest.json"),stableJson(manifest)]].map(([file,raw])=>writeFile(file,`${raw}\n`,"utf8")));
  console.log(JSON.stringify({candidateId,memberCount:rows.length,categoryCount:categoryCoverage.length,sourceCount:sources.length,familyAssertions:assertions.length,candidateManuals:candidateManuals.length,newL9Entries:l9AdvisorKnowledge.length,absentAfter:afterAbsent,issues,releaseDigest:manifest.releaseDigest},null,2));
}

void main();
