import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { projectAdvisorRead, projectComparisonEvidence } from "../features/xpy/catalog/readProjections";
import { buildRefrigeratorRichnessRelease, REFRIGERATOR_COMPARISON_DIMENSIONS, REFRIGERATOR_PARENT_ARTIFACT_SHA256, REFRIGERATOR_PARENT_RELEASE_VERSION, REFRIGERATOR_REVIEWED_AT, REFRIGERATOR_RICHNESS_COUNTS, REFRIGERATOR_RICHNESS_RELEASE_VERSION, REFRIGERATOR_SEMANTIC_AUTHORITY_VERSION } from "../features/xpy/catalog/refrigeratorRichness";

const root = process.cwd(), output = path.join(root, "data/production/appliances/refrigerators/richness/releases", REFRIGERATOR_RICHNESS_RELEASE_VERSION);
const sha = (raw: string) => createHash("sha256").update(raw).digest("hex"), stable = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;
async function main() {
  const release = buildRefrigeratorRichnessRelease();
  const semantic = { schemaVersion: REFRIGERATOR_SEMANTIC_AUTHORITY_VERSION, releaseVersion: release.releaseVersion, market: "TR", parentRelease: REFRIGERATOR_PARENT_RELEASE_VERSION, usageSemantics: release.layers.l3UsageSemantics, needs: release.layers.l4Needs, needEvidenceMappings: release.layers.l4NeedEvidenceMappings, personaPlanningSignals: release.layers.l5PersonaSignals, dailyLifeInterpretations: release.layers.l6DailyLifeInterpretations, comparisonDimensions: REFRIGERATOR_COMPARISON_DIMENSIONS, boundaries: { experience: "ABSENT_NO_GOVERNED_AUTHORITY", manualAdvisorKnowledge: "ABSENT_NO_CHECKSUM_BOUND_EXACT_MANUAL", personaDecisionUse: "NONE", unknownTreatment: "NEUTRAL_NO_PENALTY", crossCategorySemantics: "FORBIDDEN" } };
  const authorization = { purchaseStatus: "PURCHASED" as const, entitlementId: "GOVERNANCE-VERIFICATION-NON-PRODUCTION", comparisonSetId: "REFRIGERATOR-EXACT-SET-GOVERNANCE-VERIFICATION", exactOfferingIds: release.offerings.map((item) => item.offeringId) };
  const comparison = projectComparisonEvidence({ release, authorization, dimensions: REFRIGERATOR_COMPARISON_DIMENSIONS });
  const advisors = release.offerings.map((item) => projectAdvisorRead({ release, authorizedDecision: { decisionId: `GOVERNANCE-VERIFICATION:${item.offeringId}`, exactOfferingId: item.offeringId } }));
  const projections = { schemaVersion: "refrigerator-read-projection-verification/v1", status: "NON_PRODUCTION_GOVERNANCE_VERIFICATION", entitlementAuthority: "SYNTHETIC_TEST_ONLY_NOT_USER_ACCESS", comparison, advisors };
  const before = { L0: "COMPLETE", L1: "PARTIAL", L2: "PARTIAL", L3: "PARTIAL", L4: "PARTIAL", L5: "ABSENT", L6: "ABSENT", L7: "ABSENT", L8: "PARTIAL", L9: "ABSENT", L10: "PARTIAL" }, after = { L0: "COMPLETE", L1: "PARTIAL", L2: "COMPLETE", L3: "COMPLETE", L4: "COMPLETE", L5: "COMPLETE", L6: "COMPLETE", L7: "ABSENT", L8: "COMPLETE", L9: "ABSENT", L10: "PARTIAL" };
  const perProduct = release.offerings.map((item) => ({ offeringId: item.offeringId, label: item.identity.kind === "PRODUCT" ? `${item.identity.manufacturer} ${item.identity.model}` : item.offeringId, before, after, dispositions: { objectiveFacts: release.layers.l1Facts.filter((row) => row.offeringId === item.offeringId).length, capabilities: release.layers.l2Capabilities.filter((row) => row.offeringId === item.offeringId).length, dailyLifeInterpretations: release.layers.l6DailyLifeInterpretations.filter((row) => row.offeringId === item.offeringId).length, advisorKnowledge: 0, unresolved: item.offeringId === "LG_GC_B569NLLM_TR" ? ["WIDTH_AND_DEPTH_CONFLICT", "DOOR_OPEN_DEPTH_UNKNOWN", "CLEARANCES_UNKNOWN", "EXACT_MANUAL_NOT_CHECKSUM_BOUND"] : ["DOOR_OPEN_DEPTH_UNKNOWN", "CLEARANCES_UNKNOWN", "EXACT_MANUAL_NOT_CHECKSUM_BOUND"] } }));
  const coverage = { schemaVersion: "refrigerator-catalog-richness-coverage/v1", workUnitId: "WU-XPY-APPL-REFRIGERATOR-CATALOG-RICHNESS-01", generatedAt: REFRIGERATOR_REVIEWED_AT, verdict: "IMPLEMENTED", before, after, counts: { ...REFRIGERATOR_RICHNESS_COUNTS, evidence: release.evidence.length, assertionLevelEvidence: release.evidence.filter((item) => item.assertion).length, advisorReadProjectionsGenerated: advisors.length, comparisonEvidenceProjectionsGenerated: 1 }, perProduct, unresolvedGlobal: ["L7 remains absent because no governed experience authority exists.", "L9 remains absent because no checksum-bound exact-applicability manual exists in the repository.", "Door-open depth and installation clearances remain unknown for all products.", "LG width and depth conflict remains unknown and the parent keeps LG non-selectable.", "L10 price, media and offers remain external volatile joins."], nonRegression: { parentAuthorityBytesChanged: false, membershipChanged: false, candidateSelectionChanged: false, yAuthorizationChanged: false, commerceOrderingChanged: false }, nextBoundedWorkUnit: { workUnitId: "WU-XPY-APPL-DISHWASHER-CATALOG-RICHNESS-01" } };
  const releaseRaw = stable(release), semanticRaw = stable(semantic), coverageRaw = stable(coverage), projectionsRaw = stable(projections);
  const parentRaw = await readFile(path.join(root, `data/production/appliances/refrigerators/releases/${REFRIGERATOR_PARENT_RELEASE_VERSION}/domain-pack.json`), "utf8"); if (sha(parentRaw) !== REFRIGERATOR_PARENT_ARTIFACT_SHA256) throw new Error("PARENT_DIGEST_MISMATCH");
  const manifest = { schemaVersion: "refrigerator-richness-manifest/v1", workUnitId: "WU-XPY-APPL-REFRIGERATOR-CATALOG-RICHNESS-01", releaseVersion: release.releaseVersion, parent: { releaseVersion: REFRIGERATOR_PARENT_RELEASE_VERSION, artifactSha256: REFRIGERATOR_PARENT_ARTIFACT_SHA256, relationship: "IMMUTABLE_CHILD_NO_OVERWRITE" }, compatibility: release.compatibility, releaseDigest: release.releaseDigest, catalogArtifactSha256: sha(releaseRaw), semanticArtifactSha256: sha(semanticRaw), coverageArtifactSha256: sha(coverageRaw), projectionsArtifactSha256: sha(projectionsRaw), membershipDigest: sha(release.offerings.map((item) => item.offeringId).sort().join("\n")), memberCount: release.offerings.length, counts: coverage.counts, reviewerStatus: "AWAITING_PRODUCT_OWNER_ACTIVATION_APPROVAL", activation: { performed: false, activePointerRelease: REFRIGERATOR_PARENT_RELEASE_VERSION } };
  await mkdir(output, { recursive: true }); await Promise.all([["catalog-release.json", releaseRaw], ["semantic-registry.json", semanticRaw], ["coverage-report.json", coverageRaw], ["read-projections.json", projectionsRaw], ["manifest.json", stable(manifest)]].map(([name, raw]) => writeFile(path.join(output, name), raw, "utf8")));
  console.log(`${release.releaseVersion} generated with ${release.evidence.length} exact assertions.`);
}
void main();
