import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { loadActiveElectronicsCategoryPolicy } from "../features/electronics/categoryPolicyLoader.server";
import { ELECTRONICS_CATEGORY_IDS, type ElectronicsCategoryId } from "../features/electronics/architectureBaseline";
import { XPY_RUNTIME_DIGEST, XPY_RUNTIME_VERSION } from "../features/xpy/runtimeContract";
import type { ElectronicsRuntimeCatalog } from "../features/electronics/runtimeAuthority.server";
const root = process.cwd(), activate = process.argv.includes("--activate"); const pretty = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`; const sha = (raw: string | Buffer) => `sha256:${createHash("sha256").update(raw).digest("hex")}` as `sha256:${string}`; const canonical = (value: unknown): unknown => Array.isArray(value) ? value.map(canonical) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, canonical(item)])) : value;
const policy = loadActiveElectronicsCategoryPolicy(root); type Release = { products: readonly { exactProductId: string; categoryId: ElectronicsCategoryId; manufacturer: string; modelCode?: string; manufacturerModelCode?: string; configurationIdentity: string }[]; comparativeFacts: readonly { factId: string; exactProductId: string; key: string; value: unknown; sourceId: string; locator: string }[]; unknownsAndConflicts: readonly { exactProductId: string; code: string }[] };
const releases = policy.payload.evidenceChain.map(binding => ({ binding, release: JSON.parse(readFileSync(path.join(root, binding.artifactPath), "utf8")) as Release }));
const products = releases.flatMap(({ binding, release }) => release.products.map(product => ({ exactProductId: product.exactProductId, categoryId: product.categoryId, manufacturer: product.manufacturer, modelCode: product.modelCode ?? product.manufacturerModelCode ?? "", configurationIdentity: product.configurationIdentity, evidenceReleaseDigest: binding.releaseDigest, facts: release.comparativeFacts.filter(fact => fact.exactProductId === product.exactProductId).map(({ factId, key, value, sourceId, locator }) => ({ factId, key, value, sourceId, locator })), unknownCodes: release.unknownsAndConflicts.filter(row => row.exactProductId === product.exactProductId).map(row => row.code).sort(), personaEffect: "NONE" as const, commerceEffect: "NONE" as const })));
if (new Set(products.map(row => row.exactProductId)).size !== products.length || new Set(products.map(row => row.configurationIdentity)).size !== products.length || products.some(row => !row.modelCode || !row.facts.length)) throw new Error("RUNTIME_CATALOG_IDENTITY_OR_EVIDENCE_INVALID");
const unsigned = { schemaVersion: "electronics-runtime-catalog/v1" as const, releaseVersion: "ELECTRONICS-RUNTIME-CATALOG-TR-v1.0", departmentId: "ELECTRONICS" as const, market: "TR" as const, lifecycle: "FROZEN" as const, policyVersion: policy.payload.policyVersion, policyDigest: policy.policyDigest, runtimeVersion: XPY_RUNTIME_VERSION, runtimeDigest: XPY_RUNTIME_DIGEST, domainPackId: "electronics-stage1/v1" as const, evidenceChain: policy.payload.evidenceChain.map(row => ({ wave: row.wave, releaseDigest: row.releaseDigest })), categories: ELECTRONICS_CATEGORY_IDS.map(categoryId => ({ categoryId, exactProductIds: products.filter(row => row.categoryId === categoryId).map(row => row.exactProductId).sort() })), products: products.sort((a, b) => a.exactProductId.localeCompare(b.exactProductId)) }; const catalog: ElectronicsRuntimeCatalog = { ...unsigned, releaseDigest: sha(JSON.stringify(canonical(unsigned))) };
const output = path.join(root, "data/production/electronics/runtime/releases", catalog.releaseVersion); mkdirSync(output, { recursive: true }); const catalogRaw = pretty(catalog); writeFileSync(path.join(output, "catalog.json"), catalogRaw); const manifest = { schemaVersion: "electronics-runtime-catalog-manifest/v1", workUnitId: "WU-ELECTRONICS-XPY-DECISION-RUNTIME-01", releaseVersion: catalog.releaseVersion, releaseDigest: catalog.releaseDigest, catalogArtifactSha256: sha(catalogRaw), policyDigest: policy.policyDigest, categoryCount: catalog.categories.length, productCount: catalog.products.length, factCount: catalog.products.reduce((sum, row) => sum + row.facts.length, 0), activation: activate ? "ACTIVE_RUNTIME_REPOSITORY_ONLY" : "CANDIDATE", productionDeployed: false }; const manifestRaw = pretty(manifest); writeFileSync(path.join(output, "manifest.json"), manifestRaw);
if (activate) { const approval = { schemaVersion: "electronics-runtime-activation-event/v1", eventId: `ELECTRONICS-RUNTIME-ACT-${catalog.releaseDigest.slice(7, 23).toUpperCase()}`, approvedBy: "PRODUCT_OWNER", authorityBasis: "USER_STANDING_SCOPE_BOUND_AUTHORIZATION", scope: "REPOSITORY_RUNTIME_ACTIVATION_NO_PRODUCTION_DEPLOYMENT", catalogReleaseDigest: catalog.releaseDigest, policyDigest: policy.policyDigest, focusedGates: "PASS", productionMigrationApplied: false, deployed: false }; const approvalRaw = pretty({ ...approval, eventDigest: sha(JSON.stringify(canonical(approval))) }); writeFileSync(path.join(output, "activation-event.json"), approvalRaw); const activeDir = path.join(root, "data/production/electronics/runtime"); mkdirSync(activeDir, { recursive: true }); writeFileSync(path.join(activeDir, "active.json"), pretty({ schemaVersion: "electronics-runtime-active-pointer/v1", lifecycle: "ACTIVE", runtimeActive: true, productionDeployed: false, catalogFile: path.relative(root, path.join(output, "catalog.json")), catalogArtifactSha256: sha(catalogRaw), catalogReleaseDigest: catalog.releaseDigest, policyDigest: policy.policyDigest, manifestFile: path.relative(root, path.join(output, "manifest.json")), manifestSha256: sha(manifestRaw), activationEventFile: path.relative(root, path.join(output, "activation-event.json")), activationEventSha256: sha(approvalRaw) })); }
console.log(JSON.stringify({ output, activate, catalogReleaseDigest: catalog.releaseDigest, catalogArtifactSha256: sha(catalogRaw), manifestSha256: sha(manifestRaw), categories: catalog.categories.length, products: catalog.products.length, facts: manifest.factCount }));
