#!/usr/bin/env python3
import json, os, hashlib
from datetime import datetime
from zoneinfo import ZoneInfo
from urllib.parse import urlencode
from pathlib import Path
from PIL import Image as PIL
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,PageBreak,Image,HRFlowable
from reportlab.graphics.shapes import Drawing,Circle,String,Rect

R=Path(__file__).resolve().parents[1]; OUT=R/'output/pdf/expiya-cars-ornek-karsilastirma-raporu-hyundai-i20.pdf'; TMP=R/'tmp/pdfs/portrait-assets'
HERO=R/'assets/paid-comparison/three-hatchbacks-representative.png'; CAT=R/'data/production/catalog/releases/v0.55.4/catalog.json'
IDS=['786724ef-1a07-5888-9e78-3ffe22635e60','ab1eeac7-0954-5c11-8c8c-d2cbd9e3c229','f4f85dca-db7b-58c7-8049-08158325bec9']
NAVY=colors.HexColor('#102A43'); BLUE=colors.HexColor('#1C64F2'); CYAN=colors.HexColor('#00A6A6'); GREEN=colors.HexColor('#169B62'); AMBER=colors.HexColor('#E58A00'); RED=colors.HexColor('#D64545'); INK=colors.HexColor('#152536'); MUTED=colors.HexColor('#526579'); LINE=colors.HexColor('#D7E2EC'); PALE=colors.HexColor('#F6F9FC'); SKY=colors.HexColor('#EAF2FF'); EMPTY='Doğrulanmış veri yok'
pdfmetrics.registerFont(TTFont('Arial','/System/Library/Fonts/Supplemental/Arial.ttf')); pdfmetrics.registerFont(TTFont('Arial-Bold','/System/Library/Fonts/Supplemental/Arial Bold.ttf'))
S={n:ParagraphStyle(name=n,fontName=f,fontSize=z,leading=l,textColor=c) for n,f,z,l,c in [('body','Arial',9.5,13,INK),('small','Arial',7,9,MUTED),('cell','Arial',7.8,9.8,INK),('bold','Arial-Bold',7.8,9.8,INK),('h1','Arial-Bold',17,21,NAVY),('cover','Arial-Bold',27,31,colors.white),('white','Arial',10,14,colors.white)]}
def p(x,s='cell'): return Paragraph(str(x if x not in (None,'') else EMPTY).replace('&','&amp;'),S[s])
def val(x): return x.get('value') if isinstance(x,dict) else x
raw=json.loads(CAT.read_text()); by={x['variant']['id']:x for x in raw['records']}; cars=[]
for i in IDS:
 r=by[i];v=r['variant'];q=r['activeNewPrice'];cars.append({'id':i,'trim':val(v['trim']),'price':q['amountTry'],'year':val(v['modelYear']),'body':val(v['bodyStyle']),'trans':val(v['powertrain']['transmission']),'cc':val(v['powertrain']['engineDisplacementCc']),'kw':val(v['powertrain']['powerKw']),'torque':val(v['powertrain']['torqueNm']),'cons':val(v['efficiency']['combinedLitresPer100Km']),'safety':[val(x) for x in v['safetyFeatureCodes']]})
GENERATED=datetime.now(ZoneInfo('Europe/Istanbul')); REPORT_ID=os.getenv('EXPIYA_REPORT_ID','sample-report-hyundai-i20-20260829'); CONVERSATION_ID=os.getenv('EXPIYA_CONVERSATION_ID','sample-conversation-phase1')
RECORD_NO='XPY-CAR-'+GENERATED.strftime('%Y%m%d')+'-'+hashlib.sha256(REPORT_ID.encode()).hexdigest()[:8].upper(); CONVERSATION_REF='CV-'+hashlib.sha256(CONVERSATION_ID.encode()).hexdigest()[:10].upper()
def action_url(car_id,intent): return 'https://www.expiya.com/cars/paid-comparison/report/action?'+urlencode({'variant':car_id,'intent':intent,'record':RECORD_NO})
def link(label,url): return Paragraph(f'<link href="{url}" color="#1C64F2"><u>{label}</u></link>',S['bold'])
TMP.mkdir(parents=True,exist_ok=True); im=PIL.open(HERO); w,h=im.size; boxes=[(0,h*.2,w*.38,h*.82),(w*.29,h*.2,w*.71,h*.82),(w*.62,h*.2,w,h*.82)]; imgs=[]
for i,b in enumerate(boxes):
 q=TMP/f'car-{i}.jpg'; im.crop(tuple(map(int,b))).save(q,quality=92);imgs.append(q)
def icon(t,c=BLUE):
 d=Drawing(8*mm,8*mm);d.add(Circle(4*mm,4*mm,3.5*mm,fillColor=c,strokeColor=None));d.add(String(4*mm,2.7*mm,t,fontName='Arial-Bold',fontSize=7,fillColor=colors.white,textAnchor='middle'));return d
def head(n,title,t='i',c=BLUE):
 x=Table([[icon(t,c),p(f'{n}. {title}','h1')]],colWidths=[11*mm,169*mm]);x.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),0)]));return [x,HRFlowable(width='100%',color=LINE),Spacer(1,3*mm)]
def card(i):
 x=Table([[Image(str(imgs[i]),38*mm,17*mm,kind='proportional')],[p(['KARAR ARACI','ALTERNATİF 1','ALTERNATİF 2'][i],'small')],[p(['DCT Jump','MT Jump','DCT Elite'][i],'bold')],[p('Temsili görsel','small')]],colWidths=[42*mm]);x.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),SKY if i==0 else PALE),('BOX',(0,0),(-1,-1),.7,BLUE if i==0 else LINE),('ALIGN',(0,0),(-1,-1),'CENTER'),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),2),('BOTTOMPADDING',(0,0),(-1,-1),2)]));return x
def status(x): return Table([[icon('V',GREEN) if x=='Var' else icon('?',AMBER),p(x)]],colWidths=[9*mm,30*mm])
def matrix(title,rows):
 data=[[p(title,'bold'),card(0),card(1),card(2)]]+[[p(a,'bold')]+[status(v) if v in ('Var',EMPTY) else p(v) for v in b] for a,b in rows];t=Table(data,colWidths=[45*mm]*4,repeatRows=0);t.setStyle(TableStyle([('GRID',(0,0),(-1,-1),.5,LINE),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,PALE]),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),4),('RIGHTPADDING',(0,0),(-1,-1),4),('TOPPADDING',(0,1),(-1,-1),5),('BOTTOMPADDING',(0,1),(-1,-1),5)]));return t
def note(t,title,text,c=BLUE,b=SKY):
 x=Table([[icon(t,c),p(f'<b>{title}</b><br/>{text}','body')]],colWidths=[12*mm,168*mm]);x.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),b),('BOX',(0,0),(-1,-1),.6,c),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),6),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));return x
def footer(c,d): c.saveState();c.setStrokeColor(LINE);c.line(15*mm,12*mm,195*mm,12*mm);c.setFont('Arial',6.5);c.setFillColor(MUTED);c.drawString(15*mm,8*mm,'Expiya Cars - Örnek rapor - Ekspertiz veya kesin satın alma talimatı değildir');c.drawRightString(195*mm,8*mm,str(d.page));c.restoreState()
story=[]
banner=Table([[p('EXPIYA CARS','white')],[p('3 araç karşılaştırma<br/>analizi','cover')],[p('Kişiselleştirilmiş örnek rapor','white')]],colWidths=[180*mm],rowHeights=[13*mm,38*mm,16*mm]);banner.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),NAVY),('LEFTPADDING',(0,0),(-1,-1),10*mm),('VALIGN',(0,0),(-1,-1),'MIDDLE')]));story += [banner,Spacer(1,5*mm),Image(str(HERO),180*mm,86*mm,kind='proportional'),p('Temsili görseller - exact varyant fotoğrafı değildir','small'),Spacer(1,5*mm),Table([[card(1),card(0),card(2)]],colWidths=[60*mm]*3),Spacer(1,5*mm),note('!','Veri güveni','Doğrulanamayan donanım, renk, garanti ve kılavuz alanları açıkça boş bırakılmıştır.',AMBER,colors.HexColor('#FFF4DE')),Spacer(1,3*mm),p(f'Kayıt no: {RECORD_NO} | Sohbet referansı: {CONVERSATION_REF} | Oluşturma: {GENERATED.strftime("%d.%m.%Y %H:%M:%S %Z")}','small'),PageBreak()]
story+=head('1','İhtiyaç özeti ve karar','K',GREEN);story += [Table([[icon('₺'),p('1,90 M TL<br/><font size="7">Üst bütçe</font>','h1'),icon('A',CYAN),p('OTOMATİK<br/><font size="7">Öncelik</font>','h1')],[icon('G',GREEN),p('ŞEHİR İÇİ<br/><font size="7">Ana kullanım</font>','h1'),icon('3',AMBER),p('3 ARAÇ<br/><font size="7">Aynı sınıf</font>','h1')]],colWidths=[12*mm,78*mm,12*mm,78*mm],style=TableStyle([('BACKGROUND',(0,0),(-1,-1),PALE),('GRID',(0,0),(-1,-1),.5,LINE),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7)])),Spacer(1,6*mm),note('✓','Örnek karar: DCT Jump','Otomatik şanzımanı korurken Elite’e göre 155.610 TL daha düşük kampanya fiyatıyla en dengeli seçenek.',GREEN,colors.HexColor('#E8F7F0')),Spacer(1,5*mm)]
g=Drawing(180*mm,35*mm)
for j,(lab,v,c) in enumerate([('Bütçe uyumu',83,GREEN),('Kullanım uyumu',78,BLUE),('Veri tamlığı',58,AMBER)]): y=80-j*30;g.add(String(0,y,lab,fontName='Arial-Bold',fontSize=8,fillColor=INK));g.add(Rect(50*mm,y-2,105*mm,7,fillColor=LINE,strokeColor=None));g.add(Rect(50*mm,y-2,105*mm*v/100,7,fillColor=c,strokeColor=None));g.add(String(160*mm,y,str(v)+'/100',fontName='Arial-Bold',fontSize=8,fillColor=c))
story += [g,note('?','Karar güveni: ORTA','Temel veriler yüksek güvenli; donanım, renk, garanti ve kılavuz katmanları tamamlanmadı.',AMBER,colors.HexColor('#FFF4DE')),PageBreak()]
story+=head('2','Araç kimliği ve fiyat','₺');story += [matrix('Kimlik ve fiyat',[('Tam varyant',[c['trim'] for c in cars]),('Model yılı',[str(c['year']) for c in cars]),('Gövde',[c['body'] for c in cars]),('Kampanya fiyatı',[f"{c['price']:,.0f} TL".replace(',','.') for c in cars]),('Fiyat tarihi',['16.08.2026']*3),('Karar aracına fark',['-','-174.000 TL','+155.610 TL'])]),Spacer(1,5*mm),note('!','Fiyat uyarısı','Kampanya fiyatı stok ve bayi katılımına bağlı olabilir; yazılı teklif alınmalıdır.',AMBER,colors.HexColor('#FFF4DE')),PageBreak()]
story+=head('3','Motor, aktarma ve verimlilik','M',CYAN);story += [matrix('Teknik',[('Yakıt',['Benzin']*3),('Motor hacmi',[f"{c['cc']} cc" for c in cars]),('Güç',[f"{c['kw']} kW / yaklaşık 90 PS" for c in cars]),('Tork',[f"{c['torque']} Nm" for c in cars]),('Şanzıman',[c['trans'] for c in cars]),('Çekiş',['Önden çekiş']*3),('Birleşik tüketim',[f"{c['cons']} l/100 km" for c in cars]),('0-100 km/s',[EMPTY]*3),('CO2',[EMPTY]*3)]),PageBreak()]
story+=head('4','Boyutlar ve günlük kullanım','B',GREEN);story += [matrix('Boyutlar',[('Uzunluk',['4065 mm']*3),('Genişlik',['1775 mm']*3),('Yükseklik',['1450 mm']*3),('Aks mesafesi',['2580 mm']*3),('Bagaj',['352 litre']*3),('Koltuk sayısı',[EMPTY]*3),('Yerden yükseklik',[EMPTY]*3)]),Spacer(1,5*mm),note('✓','Günlük kullanım','Ortak ölçüler nedeniyle park, kabin ve bagaj kullanımında doğrulanmış varyant farkı yok.',GREEN,colors.HexColor('#E8F7F0')),PageBreak()]
abbr={x:x for x in cars[0]['safety']}; s=[(abbr[x],["Var"]*3) for x in cars[0]['safety']]
for k,chunk in enumerate([s[:11],s[11:]+[('Adaptif hız sabitleyici',[EMPTY]*3),('Kör nokta izleme',[EMPTY]*3),('360° kamera',[EMPTY]*3)]]): story+=head('5','Güvenlik ve sürüş destekleri'+(' - devam' if k else ''),'G',RED);story += [matrix('Güvenlik',chunk),PageBreak()]
groups=[('6','Konfor ve kabin','K',['Klima türü','Park sensörleri','Anahtarsız giriş','Hız sabitleyici','Elektrikli aynalar','Yağmur/far sensörü','Elektrikli camlar','Koltuk ayarı','Isıtmalı koltuk']),('6','Multimedya ve bağlantı - devam','E',['Döşeme','Kablosuz şarj','USB girişleri','Ekran boyutu','Dijital gösterge','CarPlay / Android Auto','Bluetooth','Navigasyon']),('7','Dış donanım, aydınlatma ve renkler','D',['Far teknolojisi','Gündüz farı','Otomatik uzun far','Jant ölçüsü','Lastik ölçüsü','Stepne / tamir kiti','Tavan penceresi','Arka cam karartma','Tavan rengi','Standart dış renkler','Opsiyonel dış renkler','İç döşeme kombinasyonları']),('8','Garanti, servis ve sahip olma maliyeti','₺',['Araç garantisi','Yol yardım','Bakım aralığı','Servis erişimi','Bakım fiyatı','MTV','Trafik sigortası','Kasko','Yıllık yakıt maliyeti','Değer kaybı','3 yıllık toplam maliyet'])]
for n,t,ic,items in groups:
 story+=head(n,t,ic)
 common=[[p('Alan','bold'),p('Üç varyant için durum','bold')]]+[[p(x,'bold'),status(EMPTY)] for x in items]
 ct=Table(common,colWidths=[75*mm,105*mm],repeatRows=1,style=TableStyle([('BACKGROUND',(0,0),(-1,0),SKY),('GRID',(0,0),(-1,-1),.5,LINE),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,PALE]),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),5),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]))
 story += [Table([[card(0),card(1),card(2)]],colWidths=[60*mm]*3),Spacer(1,4*mm),ct,Spacer(1,4*mm),p('Bu durum üç exact varyant için ortaktır; boş alan özelliğin araçta olmadığı anlamına gelmez.','small'),PageBreak()]
story+=head('9','Kullanım kılavuzu ve kanıt derinliği','K',AMBER);story += [note('?','Exact Türkiye kılavuzu','Doğrulanmış exact varyant kılavuzu yok. İngiltere MY25 aile kılavuzu Türkiye 2026 trim standardı sayılmadı.',AMBER,colors.HexColor('#FFF4DE')),Spacer(1,6*mm),note('→','Fail-closed kuralı','Aile kılavuzundaki özellik exact varyanta sessizce taşınmaz.',CYAN,SKY),PageBreak()]
story+=head('10','Fotoğraf, renk ve belge galerisi','F'); gal=[]
for i,t in enumerate(['Ön görünüm','Arka görünüm','Yan profil','Kokpit','Ön koltuklar','Arka koltuklar']): gal.append(Table([[Image(str(imgs[i%3]),76*mm,37*mm,kind='proportional')],[p(t,'bold')],[status('Temsili görsel - exact medya bekleniyor')]],colWidths=[86*mm],style=TableStyle([('BOX',(0,0),(-1,-1),.6,LINE),('ALIGN',(0,0),(-1,-1),'CENTER'),('TOPPADDING',(0,0),(-1,-1),4),('BOTTOMPADDING',(0,0),(-1,-1),4)])))
for i in range(0,6,2):story += [Table([[gal[i],gal[i+1]]],colWidths=[90*mm]*2),Spacer(1,4*mm)]
story += [PageBreak()];story+=head('11','Kullanım koşulları ve veri sorumluluğu','!',AMBER)
legal=[('Karar desteği','Rapor; ekspertiz, teknik inceleme, bağlayıcı teklif veya kesin al/alma talimatı değildir.'),('Veri doğruluğu','Bilgiler hatalı, eksik, gecikmeli veya güncelliğini yitirmiş olabilir. Kullanıcı satın alma öncesinde fiyatı, donanımı, garanti ve teslim koşullarını yetkili satıcı veya distribütörün güncel belgesiyle doğrulamalıdır.'),('Bağımsız taraflar','Expiya Cars ve raporu düzenleyen/faturalayan Skybit; üretici, distribütör veya bayinin temsilcisi, acentesi ya da garantörü değildir. Rapor bu üçüncü kişiler adına taahhüt oluşturmaz ve onlar bakımından bağlayıcı değildir.'),('Sorumluluk sınırı','Emredici tüketici hükümleri ile kast ve ağır kusur halleri saklı kalmak üzere, yalnız rapora dayanılarak verilen kararların ticari veya kullanım sonuçlarından Expiya Cars ve Skybit sorumlu tutulamaz.'),('Satış bağlantıları','Bağlantıya tıklamak tek başına teklif, rezervasyon, satış veya bayi aktarımı oluşturmaz. Satış talep formunda ayrıca bilgilendirme, doğrulama ve gerekli rızalar tamamlanır.'),('Kişisel veri','PDF bağlantısı ham sohbet kimliği taşımaz. Önceki karar sohbetinin bağlamı, güvenli rapor oturumu ve sunucu tarafı kayıt ilişkisi üzerinden korunur.')]
lt=Table([[icon(str(i+1),AMBER),p(a,'bold'),p(b,'body')] for i,(a,b) in enumerate(legal)],colWidths=[11*mm,38*mm,131*mm],style=TableStyle([('GRID',(0,0),(-1,-1),.5,LINE),('ROWBACKGROUNDS',(0,0),(-1,-1),[colors.white,PALE]),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),5),('RIGHTPADDING',(0,0),(-1,-1),5),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7)]));story += [lt,Spacer(1,5*mm),note('!','Hukuki durum','Bu metin ürün gereksinimi taslağıdır; canlı kullanım öncesinde Skybit hukuk danışmanı tarafından onaylanmalıdır.',RED,colors.HexColor('#FDECEC')),PageBreak()]
story+=head('12','Koşullu seçim ve satış aksiyonları','→',GREEN)
rows=[[p('Aksiyon','bold'),card(0),card(1),card(2)]]
for label,intent,cta in [('Fiyat teklifi iste','REQUEST_QUOTE','Teklif talebini başlat →'),('Test sürüşü talep et','REQUEST_TEST_DRIVE','Test sürüşü talebini başlat →'),('Satıcıyla görüş','REQUEST_DEALER_CONTACT','Satıcı iletişim talebini başlat →')]: rows.append([p(label,'bold')]+[link(cta,action_url(c['id'],intent)) for c in cars])
at=Table(rows,colWidths=[45*mm]*4,style=TableStyle([('GRID',(0,0),(-1,-1),.5,LINE),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,PALE]),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),5),('RIGHTPADDING',(0,0),(-1,-1),5),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]))
story += [Table([[card(0),card(1),card(2)]],colWidths=[60*mm]*3),Spacer(1,5*mm),note('✓','Sonuç','DCT Jump, otomatik rahatlığı ve bütçe dengesiyle öne çıkıyor; sonuç koşulludur.',GREEN,colors.HexColor('#E8F7F0')),Spacer(1,5*mm),at,Spacer(1,5*mm),note('→','Güvenli talep bağlantısı','PDF bağlantısı rapor erişimi sürdüğü müddetçe daha sonra da kullanılabilir. Tıklandığında sunucu erişim yetkisini, exact varyantı ve önceki karar sohbetini doğrular; yalnız açık talep işlemi için 30 dakika geçerli geçici güvenlik bileti üretir. Süre dolarsa PDF bağlantısına yeniden tıklamak yeterlidir.',CYAN,SKY),Spacer(1,4*mm),p(f'Kayıt no: {RECORD_NO} | Sohbet referansı: {CONVERSATION_REF} | Oluşturma: {GENERATED.strftime("%d.%m.%Y %H:%M:%S %Z")}','small')]
OUT.parent.mkdir(parents=True,exist_ok=True);SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=15*mm,leftMargin=15*mm,topMargin=14*mm,bottomMargin=17*mm,title='Expiya Cars Karşılaştırma Raporu',author='Expiya').build(story,onFirstPage=footer,onLaterPages=footer);print(OUT)
