import { createHash } from "node:crypto"; import { mkdirSync, readFileSync, writeFileSync } from "node:fs"; import path from "node:path";
import { ELECTRONICS_WAVE_4_CATEGORY_IDS, ELECTRONICS_WAVE_4_PARENT_DIGEST, ELECTRONICS_WAVE_4_VERSION, validateWave4EvidenceClosure, type RiskGate, type Wave4EvidenceRelease } from "../features/electronics/wave4EvidenceClosure";
const root = process.cwd(); const pretty = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`; const sha = (raw: string | Buffer) => `sha256:${createHash("sha256").update(raw).digest("hex")}` as `sha256:${string}`;
const parentPath = path.join(root, "data/production/electronics/wave-3-evidence/releases/ELECTRONICS-WAVE-3-EVIDENCE-TR-v0.1/evidence-release.json"); if (sha(readFileSync(parentPath)) !== ELECTRONICS_WAVE_4_PARENT_DIGEST) throw new Error("WAVE_3_PARENT_DIGEST_MISMATCH");
const amazon = JSON.parse(readFileSync(path.join(root, "data/research/electronics/amazon-tr-primary-catalog-01/manifest.json"), "utf8")) as { payloadDigest: `sha256:${string}` };
type Product = Wave4EvidenceRelease["products"][number]; const products: Product[] = [
  { exactProductId: "electronics:smartwatch:samsung:sm-l330ndaatur", categoryId: "SMARTWATCH", manufacturer: "Samsung", modelCode: "SM-L330NDAATUR", configurationIdentity: "Samsung|Galaxy Watch8|44mm|Bluetooth|Graphite|Standard strap|TR", trApplicabilitySourceIds: ["samsung-tr:SM-L330NDAATUR"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:smartwatch:huawei:vli-b19-46-black", categoryId: "SMARTWATCH", manufacturer: "HUAWEI", modelCode: "VLI-B19", configurationIdentity: "HUAWEI|WATCH GT 5|VLI-B19|46mm|Bluetooth|Black fluoroelastomer strap|TR", trApplicabilitySourceIds: ["huawei-tr:WATCH-GT5"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:fitness-tracker:xiaomi:m2435b1-black", categoryId: "FITNESS_TRACKER", manufacturer: "Xiaomi", modelCode: "M2435B1", configurationIdentity: "Xiaomi|Smart Band 9 Pro|M2435B1|Black|Bluetooth|TR", trApplicabilitySourceIds: ["xiaomi-tr:Smart-Band-9-Pro"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:fitness-tracker:huawei:nor-b19-black", categoryId: "FITNESS_TRACKER", manufacturer: "HUAWEI", modelCode: "NOR-B19", configurationIdentity: "HUAWEI|Band 10|NOR-B19|Black polymer case|Black strap|Bluetooth|TR", trApplicabilitySourceIds: ["huawei-tr:Band10"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:home-security-camera:tp-link:tapo-c225-eu-v1", categoryId: "HOME_SECURITY_CAMERA", manufacturer: "TP-Link", modelCode: "Tapo C225(EU) V1", configurationIdentity: "TP-Link|Tapo C225|EU V1|Indoor|12V DC|1-pack|TR", trApplicabilitySourceIds: ["tplink-tr:C225-EU-V1"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:home-security-camera:ezviz:cs-c6n-a0-1c2wfr", categoryId: "HOME_SECURITY_CAMERA", manufacturer: "EZVIZ", modelCode: "CS-C6N-A0-1C2WFR", configurationIdentity: "EZVIZ|C6N|CS-C6N-A0-1C2WFR|Indoor|5V DC|1-pack|TR", trApplicabilitySourceIds: ["ezviz-tr:C6N"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:video-doorbell:tp-link:tapo-d235", categoryId: "VIDEO_DOORBELL", manufacturer: "TP-Link", modelCode: "Tapo D235", configurationIdentity: "TP-Link|Tapo D235|Battery or 8-24V wired|Chime included|1-pack|TR", trApplicabilitySourceIds: ["tplink-tr:D235"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:video-doorbell:ezviz:cs-ep3x-pro", categoryId: "VIDEO_DOORBELL", manufacturer: "EZVIZ", modelCode: "CS-EP3x Pro", configurationIdentity: "EZVIZ|EP3x Pro|CS-EP3x Pro|Battery/solar/wired option|Solar panel included|Chime excluded|TR", trApplicabilitySourceIds: ["ezviz-tr:EP3x-Pro"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:smart-home-hub:tp-link:tapo-h200-eu-v1", categoryId: "SMART_HOME_HUB", manufacturer: "TP-Link", modelCode: "Tapo H200(EU) V1", configurationIdentity: "TP-Link|Tapo H200|EU V1|2.4GHz Wi-Fi/Ethernet/Sub-1G EU|Hub only|TR", trApplicabilitySourceIds: ["tplink-tr:H200-EU-V1"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:ups:apc:bx1200mi-gr", categoryId: "UNINTERRUPTIBLE_POWER_SUPPLY", manufacturer: "APC", modelCode: "BX1200MI-GR", configurationIdentity: "APC|Back-UPS BX1200MI-GR|Line-interactive|1200VA|650W|4 Schuko|230V|TR", trApplicabilitySourceIds: ["schneider-tr:BX1200MI-GR"], unresolvedIdentityDiscriminators: [] },
  { exactProductId: "electronics:ups:eaton:5e1200ui", categoryId: "UNINTERRUPTIBLE_POWER_SUPPLY", manufacturer: "Eaton", modelCode: "5E1200UI", configurationIdentity: "Eaton|5E Gen2 5E1200UI|Line-interactive|1200VA|660W|6 C13|230V|TR", trApplicabilitySourceIds: ["eaton-tr:5E1200UI"], unresolvedIdentityDiscriminators: [] },
];
type Source = Wave4EvidenceRelease["sources"][number]; const src = (sourceId: string, uri: string, ids: string[], authority: Source["authority"] = "TECHNICAL", tr: Source["trApplicabilityAuthority"] = "EXACT", market: Source["market"] = "TR"): Source => ({ sourceId, uri, market, authority, exactProductIds: ids, trApplicabilityAuthority: tr, decisionAuthority: "NONE" }); const p = (i: number) => products[i].exactProductId;
const sources: Source[] = [
  src("samsung-tr:SM-L330NDAATUR", "https://www.samsung.com/tr/business/watches/galaxy-watch/galaxy-watch8-44mm-graphite-bluetooth-sm-l330ndaatur/", [p(0)]), src("huawei-tr:WATCH-GT5", "https://consumer.huawei.com/tr/wearables/watch-gt5/specs/", [p(1)]), src("xiaomi-tr:Smart-Band-9-Pro", "https://www.mi.com/tr/product/xiaomi-smart-band-9-pro/", [p(2)]), src("huawei-tr:Band10", "https://consumer.huawei.com/tr/wearables/band10/specs/", [p(3)]),
  src("tplink-tr:C225-EU-V1", "https://www.tp-link.com/tr/home-networking/cloud-camera/tapo-c225/v1/", [p(4)]), src("tplink-global:C225-EU-V1-datasheet", "https://static.tp-link.com/upload/product-overview/2023/202302/20230215/Tapo%20C225%28EU%291.0_Datasheet.pdf", [p(4)], "MANUAL", "NONE", "GLOBAL"), src("ezviz-tr:C6N", "https://www.ezviz.com/tr/product/C6N/47289", [p(5)]),
  src("tplink-tr:D235", "https://www.tp-link.com/tr/home-networking/cloud-camera/tapo-d235/", [p(6)]), src("ezviz-tr:EP3x-Pro", "https://www.ezviz.com/tr/product/ep3x-pro/63195", [p(7)]),
  src("tplink-tr:H200-EU-V1", "https://www.tp-link.com/tr/home-networking/smart-hub/tapo-h200/v1/", [p(8)]), src("aqara-global:Hub-M3", "https://www.aqara.com/eu/product/hub-m3/", [], "INTERNATIONAL_BOUNDED", "NONE", "GLOBAL"),
  src("schneider-tr:BX1200MI-GR", "https://www.se.com/tr/tr/product/BX1200MI-GR/", [p(9)]), src("eaton-tr:5E1200UI", "https://www.eaton.com/tr/tr-tr/skuPage.5E1200UI.html", [p(10)]),
];
type F = readonly [string, string | number | boolean, string?]; const input: readonly (readonly F[])[] = [
  [["case_size_mm", 44, "mm"], ["connectivity", "Bluetooth"], ["phone_requirement", "Android 12+"], ["health_boundary", "general wellness; not medical advice"]],
  [["case_size_mm", 46, "mm"], ["connectivity", "Bluetooth"], ["phone_requirement", "Android/iOS with HUAWEI Health"], ["health_boundary", "not a medical device"]],
  [["display_inches", 1.74, "in"], ["connectivity", "Bluetooth"], ["battery_days_max", 21, "days"], ["health_boundary", "product and Mi Fitness are not medical devices"]],
  [["display_inches", 1.47, "in"], ["connectivity", "Bluetooth 5.0/BLE"], ["battery_days_typical", 8, "days"], ["health_boundary", "not for diagnosis or treatment"]],
  [["resolution", "2K QHD"], ["power", "12V DC mains adapter"], ["local_storage", "microSD up to 512GB"], ["privacy", "physical lens shutter; optional Tapo Care cloud subscription"]],
  [["resolution", "1920x1080 up to 15fps"], ["power", "5V/1A Micro USB"], ["local_storage", "microSD up to 256GB"], ["privacy", "sleep mode; optional market-dependent encrypted cloud"]],
  [["resolution", "2K 5MP"], ["power", "10000mAh battery or wired"], ["local_storage", "microSD up to 512GB"], ["subscription", "local recording available; Tapo Care cloud optional"]],
  [["resolution", "2K plus 1080p dual lens"], ["power", "battery; solar panel included; wired option"], ["local_storage", "built-in 32GB eMMC"], ["subscription", "local clips without subscription; CloudPlay optional"]],
  [["protocols", "2.4GHz Wi-Fi/Ethernet/Sub-1G EU"], ["device_capacity", "64 sensors plus 4 cameras/doorbells"], ["local_storage", "microSD up to 512GB"], ["cloud_account_boundary", "Tapo app required for setup and remote control"]],
  [["topology", "line-interactive AVR"], ["capacity", "1200VA/650W"], ["mains_outlets", "230V; 4 Schuko"], ["electrical_safety", "sealed lead-acid; installation and battery safety documentation required"]],
  [["topology", "line-interactive AVR"], ["capacity", "1200VA/660W"], ["mains_outlets", "230V; C14 input; 6 C13 outputs"], ["electrical_safety", "IEC/EN 62040-1/-2/-3; sealed lead-acid"]],
];
const slug = (v: string) => v.replaceAll(/[^a-zA-Z0-9]+/gu, "-").replaceAll(/^-|-$/gu, "").toLowerCase(); const technical = (row: Product) => sources.find(source => source.exactProductIds.includes(row.exactProductId) && source.authority === "TECHNICAL")!;
const comparativeFacts: Wave4EvidenceRelease["comparativeFacts"] = products.flatMap((row, pi) => input[pi].map(([key, value, unit], fi) => ({ factId: `wave4-fact:${slug(row.exactProductId)}:${key}:${fi + 1}`, exactProductId: row.exactProductId, categoryId: row.categoryId, key, value, ...(unit ? { unit } : {}), sourceId: technical(row).sourceId, locator: "Exact official Türkiye product/specification or limitation field", decisionEligibility: "DRAFT_POLICY_INPUT", conflictState: "CLEAR" }))) as Wave4EvidenceRelease["comparativeFacts"];
const manuals: Wave4EvidenceRelease["manuals"] = [{ manualId: "wave4-manual:tapo-c225-eu-v1", exactProductId: p(4), sourceUri: sources[5].uri, localPath: "data/production/electronics/wave-4-evidence/manuals/tapo-c225-eu-v1-datasheet.pdf", sha256: sha(readFileSync(path.join(root, "data/production/electronics/wave-4-evidence/manuals/tapo-c225-eu-v1-datasheet.pdf"))), locators: ["Model and region", "Power", "Local/cloud storage", "Package contents"], layer: "L9_ADVISOR_KNOWLEDGE" }];
const gate = (categoryId: Wave4EvidenceRelease["riskGates"][number]["categoryId"], privacy: RiskGate, health: RiskGate, subscription: RiskGate, installation: RiskGate, electricalSafety: RiskGate, notes: string[]): Wave4EvidenceRelease["riskGates"][number] => ({ categoryId, privacy, health, subscription, installation, electricalSafety, notes });
const riskGates = [
  gate("SMARTWATCH", "UNKNOWN_NEUTRAL_NON_BLOCKING", "EVIDENCED", "EVIDENCED", "NOT_APPLICABLE", "EVIDENCED", ["No retention-sensitive ranking claim; account/app dependency and non-medical boundary recorded"]),
  gate("FITNESS_TRACKER", "UNKNOWN_NEUTRAL_NON_BLOCKING", "EVIDENCED", "EVIDENCED", "NOT_APPLICABLE", "EVIDENCED", ["No retention-sensitive ranking claim; non-medical boundary recorded"]),
  gate("HOME_SECURITY_CAMERA", "EVIDENCED", "NOT_APPLICABLE", "EVIDENCED", "EVIDENCED", "EVIDENCED", ["Local storage and physical/software privacy controls distinguished from optional cloud"]),
  gate("VIDEO_DOORBELL", "EVIDENCED", "NOT_APPLICABLE", "EVIDENCED", "EVIDENCED", "EVIDENCED", ["Power, included components, local storage, and optional cloud topology recorded"]),
  gate("SMART_HOME_HUB", "BLOCKED_MATERIAL", "NOT_APPLICABLE", "UNKNOWN_NEUTRAL_NON_BLOCKING", "EVIDENCED", "EVIDENCED", ["Second-manufacturer exact Türkiye applicability absent"]),
  gate("UNINTERRUPTIBLE_POWER_SUPPLY", "NOT_APPLICABLE", "NOT_APPLICABLE", "NOT_APPLICABLE", "EVIDENCED", "EVIDENCED", ["230V, topology, outlet form, battery chemistry, and safety standards recorded"]),
] as Wave4EvidenceRelease["riskGates"];
const categoryReadiness: Wave4EvidenceRelease["categoryReadiness"] = ELECTRONICS_WAVE_4_CATEGORY_IDS.map(categoryId => { const rows = products.filter(row => row.categoryId === categoryId); const blocked = categoryId === "SMART_HOME_HUB"; return { categoryId, candidateCount: rows.length, manufacturerCount: new Set(rows.map(row => row.manufacturer)).size, comparableFieldCount: new Set(comparativeFacts.filter(row => row.categoryId === categoryId).map(row => row.key)).size, readiness: blocked ? "BLOCKED_EVIDENCE" : "DECISION_EVIDENCE_READY", reasons: blocked ? ["SECOND_MANUFACTURER_EXACT_TR_APPLICABILITY_ABSENT", "MATERIAL_PRIVACY_AUTHORITY_INCOMPLETE"] : ["MULTI_MANUFACTURER_EXACT_TR_COMPARISON_WITH_CATEGORY_RISK_BOUNDARIES"], policyStatus: "REVIEW_REQUIRED_NON_ACTIVE" }; });
const decisionProjections: Wave4EvidenceRelease["decisionProjections"] = products.map(row => ({ projectionId: `wave4-projection:${slug(row.exactProductId)}`, exactProductId: row.exactProductId, eligibleFactIds: comparativeFacts.filter(fact => fact.exactProductId === row.exactProductId).map(fact => fact.factId), status: "DRAFT_NON_ACTIVE", unknownTreatment: "NEUTRAL_FAIL_CLOSED", rankingWeights: "NONE" }));
const rejectedInvestigations = [{ categoryId: "SMART_HOME_HUB", candidate: "Aqara Hub M3 HM-G01D", reason: "Official international technical and security records found, but no independent exact Türkiye applicability authority was established.", effect: "NONE" }] as Wave4EvidenceRelease["rejectedInvestigations"];
const unknownsAndConflicts: Wave4EvidenceRelease["unknownsAndConflicts"] = products.flatMap(row => ["L7_GOVERNED_EXPERIENCE_ABSENT", "GOVERNED_MEDIA_REUSE_PROVENANCE_ABSENT", ...(manuals.some(manual => manual.exactProductId === row.exactProductId) ? [] : ["EXACT_MANUAL_NOT_CHECKSUM_BOUND"]), ...(row.categoryId === "SMARTWATCH" || row.categoryId === "FITNESS_TRACKER" ? ["PRODUCT_SPECIFIC_DATA_RETENTION_AND_DELETION_INCOMPLETE"] : [])].map(code => ({ exactProductId: row.exactProductId, code, effect: "NEUTRAL_FAIL_CLOSED" })));
const boundaries = { l7Experience: "ABSENT", mediaImported: false, l10YEffect: "NONE", amazonStatusEffect: "NONE", activationPerformed: false, registryChanged: false, runtimeChanged: false, databaseChanged: false, pointerChanged: false, deploymentPerformed: false } as const;
const release: Wave4EvidenceRelease = { schemaVersion: "electronics-wave-4-evidence/v1", releaseVersion: ELECTRONICS_WAVE_4_VERSION, parent: { releaseDigest: ELECTRONICS_WAVE_4_PARENT_DIGEST, relationship: "IMMUTABLE_CHILD_NO_OVERWRITE" }, research: { amazonFirstDigest: amazon.payloadDigest, amazonRole: "DISCOVERY_ONLY_ZERO_DECISION_EFFECT", internationalRole: "TECHNICAL_GAP_FILL_ONLY_NOT_TR_APPLICABILITY" }, products, sources, comparativeFacts, manuals, riskGates, categoryReadiness, decisionProjections, rejectedInvestigations, unknownsAndConflicts, carryForward: { scope: "WAVES_1_TO_3_PARENT_CHAIN", parentReleaseDigest: ELECTRONICS_WAVE_4_PARENT_DIGEST, parentBytesUnmodified: true }, boundaries };
const issues = validateWave4EvidenceClosure(release); if (issues.length) throw new Error(`WAVE_4_INVALID:${issues.join(",")}`);
const comparison = { schemaVersion: "electronics-wave-4-comparison/v1", categories: categoryReadiness.map(row => ({ ...row, riskGates: riskGates.find(gate => gate.categoryId === row.categoryId), exactProductIds: products.filter(product => product.categoryId === row.categoryId).map(product => product.exactProductId), fields: [...new Set(comparativeFacts.filter(fact => fact.categoryId === row.categoryId).map(fact => fact.key))].sort() })) };
const policy = { schemaVersion: "electronics-wave-4-policy-input/v1", status: "NON_ACTIVE_CATEGORY_REVIEW_INPUT", categories: comparison.categories.map(row => ({ categoryId: row.categoryId, eligibleFields: row.fields, rankingWeights: "NONE", sufficiencyThresholds: "UNDEFINED_PENDING_PRODUCT_REVIEW", unknownTreatment: "NEUTRAL_FAIL_CLOSED", riskGates: row.riskGates, commerceEffect: "NONE" })) };
const reconciliation = { schemaVersion: "electronics-wave-4-reconciliation/v1", parentReleaseDigest: ELECTRONICS_WAVE_4_PARENT_DIGEST, parentBytesUnmodified: true, parentArtifactPath: path.relative(root, parentPath), amazonFirstDigest: amazon.payloadDigest, wave4ExactProductIds: products.map(row => row.exactProductId).sort(), rejectedInvestigations, activationEffect: "NONE" };
const output = path.join(root, "data/production/electronics/wave-4-evidence/releases", ELECTRONICS_WAVE_4_VERSION); mkdirSync(output, { recursive: true }); const artifacts = { "evidence-release.json": pretty(release), "comparative-matrix.json": pretty(comparison), "policy-input-proposal.json": pretty(policy), "reconciliation.json": pretty(reconciliation) }; for (const [name, raw] of Object.entries(artifacts)) writeFileSync(path.join(output, name), raw);
const manifest = { schemaVersion: "electronics-wave-4-manifest/v1", workUnitId: "WU-ELECTRONICS-WAVE-4-MULTI-CANDIDATE-EVIDENCE-CLOSURE-01", releaseVersion: ELECTRONICS_WAVE_4_VERSION, verdict: "PARTIAL", parentReleaseDigest: ELECTRONICS_WAVE_4_PARENT_DIGEST, counts: { categories: 6, products: products.length, manufacturers: new Set(products.map(row => row.manufacturer)).size, sources: sources.length, comparativeFacts: comparativeFacts.length, manuals: manuals.length, unknowns: unknownsAndConflicts.length, rejectedInvestigations: rejectedInvestigations.length }, readiness: Object.fromEntries(["DECISION_EVIDENCE_READY", "POLICY_REVIEW_REQUIRED", "INFORMATION_ONLY", "BLOCKED_EVIDENCE"].map(status => [status, categoryReadiness.filter(row => row.readiness === status).length])), artifacts: Object.fromEntries(Object.entries(artifacts).map(([name, raw]) => [name, sha(raw)])), activation: boundaries }; writeFileSync(path.join(output, "manifest.json"), pretty(manifest)); console.log(JSON.stringify({ output, ...manifest.counts, readiness: manifest.readiness, releaseDigest: manifest.artifacts["evidence-release.json"] }));
