import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { rankWithBoundedSoftSignals, type XpyCandidateSoftSignal } from "@/features/xpy/boundedSoftRanking";

const ROOT = process.cwd();
const FOUNDATION = "data/production/personas/universal/release-candidates/XPY-UNIVERSAL-PERSONA-AUTHORITY-TR-v0.1-owner-review-candidate";
const OUT = "data/production/personas/universal/external-evidence/XPY-UNIVERSAL-PERSONA-EXTERNAL-EVIDENCE-01";
const GENERATED_AT = "2026-09-06T00:00:00.000Z";
const ACCEPTED_DIGEST = "sha256:e9878272ea714c509334c0d56bdfd7b08c7af03471d1a18cfb80431ea4dfe961";
type InventoryRow = { exactProductId:string; departmentId:string; categoryId:string; brand:string; model:string; configurationIdentity:string };
const canonical=(value:unknown):unknown=>Array.isArray(value)?value.map(canonical):value&&typeof value==="object"?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,canonical(v)])):value;
const digest=(value:unknown)=>`sha256:${createHash("sha256").update(JSON.stringify(canonical(value))).digest("hex")}`;
const json=(value:unknown)=>`${JSON.stringify(value,null,2)}\n`;
const readJson=async(file:string)=>JSON.parse(await readFile(path.join(ROOT,file),"utf8"));

const externalSources = [
  {sourceId:"EXT-SONY-XM5-RTINGS-2025",url:"https://www.rtings.com/headphones/reviews/sony/wh-1000xm5-wireless",publisher:"RTINGS.com",sourceType:"INDEPENDENT_SPECIALIST_REVIEW",publishedAt:"2025-02-10",retrievedAt:"2026-09-06",market:"US/CA",independenceClass:"INDEPENDENT_EDITORIAL_WITH_AFFILIATE_DISCLOSURE",commercialRelationship:"Membership-supported; affiliate commission disclosed; editorial test methodology is separately stated.",exactProductIds:["electronics:headphones:sony:wh1000xm5b-ce7"],productIdentityMatch:"EXACT_MODEL_AND_BLACK_COLOR; TR SUFFIX NOT TESTED",assertionLocator:"Review lines 15-24, 35, 197-218; tested Black variant and methodology v2.3.",assertions:[{trait:"DESIGN_LED",paraphrase:"The tested black WH-1000XM5 has a visibly distinct redesign and sleek updated form."}],limitations:["Foreign-market unit; Turkish retail suffix CE7 is not printed in the review.","Affiliate links cannot be ranking inputs and were ignored."]},
  {sourceId:"EXT-SONY-XM5-SOUNDGUYS-2025",url:"https://www.soundguys.com/sony-whx-1000xm5-review-71783/",publisher:"SoundGuys",sourceType:"INDEPENDENT_SPECIALIST_REVIEW",publishedAt:"2025-09-11",retrievedAt:"2026-09-06",market:"CA/US",independenceClass:"INDEPENDENT_EDITORIAL_WITH_AFFILIATE_DISCLOSURE",commercialRelationship:"Retail-link commission disclosed; article states products are independently chosen.",exactProductIds:["electronics:headphones:sony:wh1000xm5b-ce7"],productIdentityMatch:"EXACT_MODEL; BLACK COLOR SHOWN; TR SUFFIX NOT STATED",assertionLocator:"Review lines 50, 57-65, 279-295.",assertions:[{trait:"DESIGN_LED",paraphrase:"The review treats the complete redesign as a central part of the product experience."}],limitations:["Foreign-market review; CE7 suffix compatibility is inferred only at model/color level.","Scores, price and retailer links were excluded."]},
  {sourceId:"EXT-CYBEX-BALIOS-MFM-2023",url:"https://www.madeformums.com/reviews/cybex-balios-s-lux-pushchair-and-carrycot-review/",publisher:"MadeForMums",sourceType:"INDEPENDENT_SPECIALIST_REVIEW",publishedAt:"2023-10-16",retrievedAt:"2026-09-06",market:"UK",independenceClass:"INDEPENDENT_EDITORIAL_WITH_AFFILIATE_DISCLOSURE",commercialRelationship:"Affiliate links disclosed; recommendation independence stated.",exactProductIds:["CYBEX_BALIOS_S_LUX_520001251_TR"],productIdentityMatch:"COMPATIBLE MODEL/FAMILY; EXACT TR SKU/COLOR NOT TESTED",assertionLocator:"Review lines 4-25, 70-75, 105-111, 160-163.",assertions:[{trait:"DESIGN_LED",paraphrase:"The tested Balios S Lux is repeatedly characterized through styling and visual/material treatment."}],limitations:["UK 2023 unit; Turkish SKU 520001251 and Navy Blue/Silver configuration not proven identical.","Star ratings and price/value statements were excluded."]},
  {sourceId:"EXT-CYBEX-BALIOS-BGL-2024",url:"https://www.babygearlab.com/reviews/getting-around/full-size-stroller/cybex-balios-s-lux",publisher:"BabyGearLab",sourceType:"INDEPENDENT_SPECIALIST_REVIEW",publishedAt:"2024-03-31",retrievedAt:"2026-09-06",market:"US",independenceClass:"INDEPENDENT_EDITORIAL_WITH_AFFILIATE_DISCLOSURE",commercialRelationship:"Editorial test publisher with retail links.",exactProductIds:["CYBEX_BALIOS_S_LUX_520001251_TR"],productIdentityMatch:"COMPATIBLE MODEL/FAMILY; EXACT TR SKU/COLOR NOT TESTED",assertionLocator:"Review lines 87-89, 131-160.",assertions:[{trait:"DESIGN_LED",paraphrase:"The review notes the model's considered overall look and fabric treatment while also documenting usability drawbacks."}],limitations:["US unit and configuration; exact Turkish SKU/color identity remains unproven.","Rank, score, price and retailer placement were excluded."]},
] as const;

async function main(){
 const inventory=(await readJson(`${FOUNDATION}/inventory.json`) as InventoryRow[]).sort((a,b)=>a.departmentId.localeCompare(b.departmentId)||a.categoryId.localeCompare(b.categoryId)||a.exactProductId.localeCompare(b.exactProductId));
 const foundation=await readJson(`${FOUNDATION}/persona-authority.json`); if(foundation.payloadDigest!==ACCEPTED_DIGEST)throw new Error("ACCEPTED_FOUNDATION_DIGEST_MISMATCH");
 const inventoryDigest=digest(inventory), methodology={version:"xpy-persona-external-method/v1",minimumIndependentCompatibleSources:2,userThemeThreshold:{minimumReviews:20,minimumPlatforms:2,minimumIndependentAuthors:20,personalData:"EXCLUDED"},manufacturerRole:"POSITIONING_ONLY",foreignMarketRule:"EXACT_FAMILY_COMPATIBILITY_AND_EXPLICIT_LIMITATION_REQUIRED",forbiddenInputs:["POPULARITY","STAR_AVERAGE","SALES_RANK","PRICE","AFFILIATE_STATE","AMAZON_ORDER","BRAND_PRESTIGE"]};
 const methodologyDigest=digest(methodology);
 const sourceIdsByProduct=new Map<string,string[]>(); for(const source of foundation.sources as Array<{sourceId:string;exactProductIds:string[]}>)for(const id of source.exactProductIds)sourceIdsByProduct.set(id,[...(sourceIdsByProduct.get(id)??[]),source.sourceId]);
 const externalByProduct=new Map<string,string[]>(); for(const source of externalSources)for(const id of source.exactProductIds)externalByProduct.set(id,[...(externalByProduct.get(id)??[]),source.sourceId]);
 const ledgers=inventory.map((row,index)=>({sequence:index+1,checkpointId:`${row.departmentId}:${row.categoryId}`,exactProductId:row.exactProductId,identity:{brand:row.brand,model:row.model,configurationIdentity:row.configurationIdentity},query:`\"${row.brand}\" \"${row.model}\" independent review design usability materials`,inspectedFoundationSourceIds:(sourceIdsByProduct.get(row.exactProductId)??[]).sort(),inspectedExternalSourceIds:(externalByProduct.get(row.exactProductId)??[]).sort(),identityDisposition:externalByProduct.has(row.exactProductId)?"FOREIGN_MODEL_COMPATIBLE_CONFIGURATION_LIMITED":"NO_COMPATIBLE_INDEPENDENT_SOURCE_CAPTURED",terminalStatus:"PERSONA_EVIDENCE_UNKNOWN",rejectedEvidenceReasons:externalByProduct.has(row.exactProductId)?["EXACT_TR_CONFIGURATION_COMPATIBILITY_NOT_PROVEN"]:["NO_TWO_INDEPENDENT_COMPATIBLE_SOURCES_CAPTURED"],resumeState:"TERMINAL_REVIEWED",personalDataStored:false}));
 const claims=externalSources.length?[{claimId:"PROPOSED-HOLD-SONY-XM5-DESIGN-LED",exactProductId:"electronics:headphones:sony:wh1000xm5b-ce7",trait:"DESIGN_LED",sourceIds:["EXT-SONY-XM5-RTINGS-2025","EXT-SONY-XM5-SOUNDGUYS-2025"],status:"HELD_IDENTITY_LIMIT",contribution:0,limitations:["Exact Turkish suffix compatibility is not independently proven."]},{claimId:"PROPOSED-HOLD-CYBEX-BALIOS-DESIGN-LED",exactProductId:"CYBEX_BALIOS_S_LUX_520001251_TR",trait:"DESIGN_LED",sourceIds:["EXT-CYBEX-BALIOS-MFM-2023","EXT-CYBEX-BALIOS-BGL-2024"],status:"HELD_IDENTITY_LIMIT",contribution:0,limitations:["Exact Turkish SKU/color configuration compatibility is not proven."]}]:[];
 const byCategory=Object.values(Object.groupBy(inventory,row=>`${row.departmentId}:${row.categoryId}`)).map(group=>({departmentId:group![0]!.departmentId,categoryId:group![0]!.categoryId,processed:group!.length,qualified:0,unknown:group!.length,conflicted:0})).sort((a,b)=>a.departmentId.localeCompare(b.departmentId)||a.categoryId.localeCompare(b.categoryId));
 const representative=["LAPTOP","SMARTPHONE","WASHING_MACHINE","REFRIGERATOR","FULLY_AUTOMATIC_ESPRESSO_MACHINE","HEADPHONES","STROLLER"];
 const authority={authorityId:"external-evidence-shadow-not-approved",version:"WU-XPY-UNIVERSAL-PERSONA-EXTERNAL-EVIDENCE-01",digest:digest(claims),decisionUse:"BOUNDED_SOFT_RANKING_ONLY" as const};
 const traces=representative.map(categoryId=>{const ids=inventory.filter(row=>row.categoryId===categoryId).slice(0,3).map(row=>row.exactProductId);const signals:XpyCandidateSoftSignal[]=ids.map(exactCandidateId=>({exactCandidateId,preferenceKey:"DESIGN_LED",mappingRef:"external-wave:unknown-neutral",evidenceRef:`persona-record:${exactCandidateId}`,evidenceState:"UNKNOWN",contribution:.25,reasonCode:"PERSONA_UNKNOWN_NEUTRAL",authority}));const before=[...ids].sort();const result=rankWithBoundedSoftSignals({eligibleCandidateIds:ids,preferences:[{eventId:`trace:${categoryId}`,preferenceKey:"DESIGN_LED",status:"ACTIVE"}],signals,scoreCap:.75,singleSelectionAuthorized:false});const reversed=rankWithBoundedSoftSignals({eligibleCandidateIds:[...ids].reverse(),preferences:[{eventId:`trace:${categoryId}`,preferenceKey:"DESIGN_LED",status:"ACTIVE"}],signals:[...signals].reverse(),scoreCap:.75,singleSelectionAuthorized:false});return{categoryId,before,productionAfter:result.orderedCandidateIds,membershipIdentical:JSON.stringify(before)===JSON.stringify(result.retainedCandidateIds),unknownNeutral:result.traces.every(row=>row.score===0),tiesPreserved:result.selectionOutcome==="NON_DOMINATED_SET",catalogOrderIndependent:result.deterministicFingerprint===reversed.deterministicFingerprint,personaSelectionAuthority:false,cap:.75};});
 const reconciliation={schemaVersion:"xpy-persona-external-reconciliation/v1",foundationDigest:ACCEPTED_DIGEST,inventoryDigest,methodologyDigest,processed:ledgers.length,expected:169,noSilentDrop:ledgers.length===169&&new Set(ledgers.map(row=>row.exactProductId)).size===169,qualified:0,unknown:169,conflicted:0,readiness:"CATALOG_NOT_READY — EXTERNAL_PERSONA_EVIDENCE_INCOMPLETE",ownerApprovalEligible:false};
 const coverage={schemaVersion:"xpy-persona-external-coverage/v1",totals:{processed:169,qualified:0,unknown:169,conflicted:0,independentEditorialSources:4,userThemeSources:0,manufacturerPositioningSources:foundation.sources.length,rejectedClaims:2},byCategory,traitCoverage:Object.fromEntries((foundation.vocabulary as Array<{trait:string}>).map(row=>[row.trait,0]))};
 const files:Record<string,unknown>={"frozen-input.json":{foundationDigest:ACCEPTED_DIGEST,inventoryDigest,methodologyDigest,inventory},"methodology.json":methodology,"acquisition-ledger.json":ledgers,"external-source-registry.json":externalSources,"proposed-claims-held.json":claims,"reconciliation.json":reconciliation,"coverage.json":coverage,"trace-previews.json":traces};
 const manifest={schemaVersion:"xpy-persona-external-manifest/v1",generatedAt:GENERATED_AT,lifecycle:"RESEARCH_CHECKPOINT_NOT_ACTIVE",artifacts:Object.fromEntries(Object.entries(files).map(([name,value])=>[name,digest(value)])),foundationDigest:ACCEPTED_DIGEST,ownerApprovalEligible:false};
 await mkdir(path.join(ROOT,OUT),{recursive:true}); for(const [name,value] of Object.entries({...files,"manifest.json":manifest}))await writeFile(path.join(ROOT,OUT,name),json(value));
 console.log(json({status:"GENERATED",processed:ledgers.length,qualified:0,unknown:169,externalSources:externalSources.length,output:OUT,manifestDigest:digest(manifest)}));
}
void main().catch(error=>{console.error(error);process.exitCode=1;});
