import { createHash } from "node:crypto";
/* eslint-disable @typescript-eslint/no-explicit-any -- bounded release script consumes versioned JSON artifacts */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { canonicalJson, fingerprint } from "../features/vehicle-data/equipmentVerificationMaterialization";
import { scaleWaveOwnerManifestChecksum } from "../features/vehicle-data/equipmentScaleWaveOwnerManifest";
import { validateScaleWaveReleaseCandidate } from "../features/vehicle-data/equipmentScaleWaveReleaseCandidate";

const ROOT=process.cwd(), RELEASE="v1.5.0-scale-wave-verified-catalog-v0.55.2-2026-08-19", AT="2026-08-19T09:00:00.000+03:00";
const WAVE=path.join(ROOT,"data/production/equipment-evidence/working/EE-PILOT-002/EE-PILOT-002-SCALE-WAVE-001/corrections/EE-PILOT-002-SCALE-WAVE-001-R1");
const MANIFEST_DIR=path.join(WAVE,"owner-governance/EE-OAM-SCALE-WAVE-001-R1-BYD-NISSAN");
const ACTIVE=path.join(ROOT,"data/production/equipment-evidence/releases/v1.4.0-reviewed-associations-catalog-v0.55.2-2026-08-18");
const OUT=path.join(ROOT,"data/production/equipment-evidence/release-candidates",RELEASE);
const MANIFEST_SHA="sha256:bc7f5af057e55cac8dacbb094286cdc030b70f53433b66b35ba2daa5346ee1f3", CATALOG_SHA="sha256:fd5609adcc0ca3fec0f8c9dc4dd1c903ed5514326bd322eacd4decff5a044f0f";
const STATEMENT=`EQUIPMENT_OWNER_001 olarak
EE-OAM-SCALE-WAVE-001-R1-BYD-NISSAN kimlikli ve
sha256:bc7f5af057e55cac8dacbb094286cdc030b70f53433b66b35ba2daa5346ee1f3
checksum’lı BYD/Nissan Equipment approval manifestini inceledim. Manifestteki
65 equipment assertion ve 2 trim link için owner approval verilmesini ve
immutable verification materialization kayıtlarının hazırlanmasını
onaylıyorum. Bu kapsamın 62 STANDARD + INCLUDED ve BYD Dolphin Comfort exact
varyantına ait açık matrix kanıtına dayanan 3 NOT_AVAILABLE + NOT_OFFERED
assertion içerdiğini kabul ediyorum. OPTIONAL veya PACKAGE_DEPENDENT assertion
bulunmadığını; BYD’deki 18 ve Nissan’daki 19 inconclusive özelliğin yokluk
sayılmadığını kabul ediyorum. Assertion’ların yalnız exact varyant, model yılı,
Türkiye pazarı, resmî matrix hücresi ve legend kapsamında geçerli olduğunu;
bu onayın Equipment Decision Engine’e filtreleme, sıralama, soru üretme veya
kullanıcı açıklaması yetkisi vermediğini kabul ediyorum.`;
const read=async<T>(f:string)=>JSON.parse(await readFile(f,"utf8")) as T, sha=(v:string|Buffer)=>`sha256:${createHash("sha256").update(v).digest("hex")}`, fileSha=async(f:string)=>sha(await readFile(f));
const id=(prefix:string,value:unknown)=>`${prefix}-${fingerprint(value).slice(7,27).toUpperCase()}`, write=async(name:string,value:unknown)=>writeFile(path.join(OUT,name),canonicalJson(value));

async function main(){
 const manifest=await read<any>(path.join(MANIFEST_DIR,"approval-manifest.json")); const {manifestChecksum,...manifestPayload}=manifest;
 if(manifestChecksum!==MANIFEST_SHA||scaleWaveOwnerManifestChecksum(manifestPayload)!==MANIFEST_SHA) throw new Error("APPROVAL_MANIFEST_CHECKSUM_MISMATCH");
 const actors=await read<any>(path.join(ROOT,"data/production/equipment-evidence/governance/actor-registry.json"));
 if(!actors.actors.some((x:any)=>x.actorId==="EQUIPMENT_OWNER_001"&&x.role==="EQUIPMENT_OWNER_APPROVER"&&x.scope==="EQUIPMENT_EVIDENCE_ONLY"&&x.status==="ACTIVE")) throw new Error("OWNER_ACTOR_INVALID");
 const before={activeRelease:await fileSha(ACTIVE+"/equipment-evidence.json"),activeManifest:await fileSha(ACTIVE+"/manifest.json"),pointer:await fileSha(path.join(ROOT,"data/production/equipment-evidence/active.json")),module:await fileSha(path.join(ROOT,"data/production/equipment-evidence/activeEquipmentEvidence.generated.ts"))};
 const active=await read<any>(ACTIVE+"/equipment-evidence.json");
 const attestationId=id("EE-OAA",{statement:STATEMENT,manifestChecksum}); const attestation={approvalAttestationId:attestationId,ownerActorId:"EQUIPMENT_OWNER_001",normalizedApprovalStatement:STATEMENT,approvalStatementChecksum:sha(STATEMENT),approvalManifestId:manifest.manifestId,approvalManifestChecksum:manifestChecksum,subjectCount:67,assertionCount:65,trimLinkCount:2,availabilityProvisionDistribution:{"STANDARD+INCLUDED":62,"NOT_AVAILABLE+NOT_OFFERED":3,"OPTIONAL+FACTORY_OPTION":0,"PACKAGE_DEPENDENT+PACKAGE_OPTION":0},decisionAuthority:"SHADOW_AND_EXPLANATION_DISABLED",governancePolicyVersion:"SCALE_WAVE_OWNER_APPROVAL_V1",recordedAt:AT};
 const approvals=manifest.subjects.map((s:any)=>({eventId:id("EE-OAE",{subject:s.subjectId,manifestChecksum}),eventType:"OWNER_APPROVAL_GRANTED",actorId:"EQUIPMENT_OWNER_001",actorRole:"EQUIPMENT_OWNER_APPROVER",subjectType:s.subjectType,subjectId:s.subjectId,predecessorId:s.predecessorAssertionId??s.predecessorTrimLinkId,exactVariantId:s.exactVariantId,contentFingerprint:s.contentFingerprint,fingerprintPolicy:s.fingerprintPolicy,independentReviewEventId:s.independentReviewEventId,approvalManifestId:manifest.manifestId,approvalManifestChecksum:manifestChecksum,approvalAttestationId:attestationId,decisionAuthority:"SHADOW_AND_EXPLANATION_DISABLED",createdAt:AT})).sort((a:any,b:any)=>a.eventId.localeCompare(b.eventId));
 const approvalBySubject=new Map(approvals.map((x:any)=>[`${x.subjectType}:${x.subjectId}`,x]));
 const assertionMats=manifest.subjects.filter((s:any)=>s.subjectType==="ASSERTION").map((s:any)=>({materializationId:id("EE-MAT",{subject:s.subjectId,manifestChecksum}),materializationType:"VERIFIED_EQUIPMENT_ASSERTION",sourceAssertionId:s.assertionId,predecessorAssertionId:s.predecessorAssertionId,terminalSupersessionChain:s.supersessionChain,exactVariantId:s.exactVariantId,featureCode:s.featureCode,availabilityStatus:s.availabilityStatus,provisionMode:s.provisionMode,standardOrOptional:s.availabilityStatus,marketApplicability:s.marketApplicability,modelYearApplicability:s.modelYearApplicability,trimApplicability:s.trimApplicability,powertrainApplicability:s.powertrainApplicability,sourceReferences:s.sources,sourceRowIds:s.sourceRowIds,locator:s.locator,legend:s.legend,semanticMappingIds:s.semanticMappingIds,contentFingerprint:s.contentFingerprint,fingerprintPolicy:s.fingerprintPolicy,independentReviewEventId:s.independentReviewEventId,ownerApprovalEventId:(approvalBySubject.get(`ASSERTION:${s.subjectId}`) as any).eventId,approvalManifestId:manifest.manifestId,approvalManifestChecksum:manifestChecksum,confidence:s.evidenceConfidence,conflictState:s.conflictState,verificationState:"VERIFIED",catalogRelease:"v0.55.2",catalogFingerprint:CATALOG_SHA,policyVersion:"SCALE_WAVE_VERIFICATION_MATERIALIZATION_V1",materializedAt:AT,decisionAuthority:"SHADOW_AND_EXPLANATION_DISABLED"})).sort((a:any,b:any)=>a.materializationId.localeCompare(b.materializationId));
 const matByAssertion=new Map(assertionMats.map((x:any)=>[x.sourceAssertionId,x]));
 const trimMats=manifest.subjects.filter((s:any)=>s.subjectType==="TRIM_LINK").map((s:any)=>({materializationId:id("EE-MAT-TRIM",{subject:s.subjectId,manifestChecksum}),materializationType:"VERIFIED_EQUIPMENT_TRIM_LINK",sourceTrimLinkId:s.trimLinkId,predecessorTrimLinkId:s.predecessorTrimLinkId,terminalSupersessionChain:s.supersessionChain,exactVariantId:s.exactVariantId,canonicalModel:s.canonicalModel,canonicalTrim:s.canonicalTrim,canonicalTrimId:s.canonicalTrimId,powertrain:s.powertrain,transmission:s.transmission,marketApplicability:s.marketApplicability,modelYearApplicability:s.modelYearApplicability,identitySources:s.identitySources,locators:s.locators,contentFingerprint:s.contentFingerprint,fingerprintPolicy:s.fingerprintPolicy,assertionMaterializationIds:manifest.subjects.filter((a:any)=>a.subjectType==="ASSERTION"&&a.exactVariantId===s.exactVariantId).map((a:any)=>(matByAssertion.get(a.assertionId) as any).materializationId).sort(),independentReviewEventId:s.independentReviewEventId,ownerApprovalEventId:(approvalBySubject.get(`TRIM_LINK:${s.subjectId}`) as any).eventId,approvalManifestId:manifest.manifestId,approvalManifestChecksum:manifestChecksum,verificationState:"VERIFIED",catalogRelease:"v0.55.2",catalogFingerprint:CATALOG_SHA,policyVersion:"SCALE_WAVE_VERIFICATION_MATERIALIZATION_V1",materializedAt:AT,decisionAuthority:"SHADOW_AND_EXPLANATION_DISABLED"})).sort((a:any,b:any)=>a.materializationId.localeCompare(b.materializationId));
 const newProjections=assertionMats.map((m:any)=>({assertionMaterializationId:m.materializationId,availabilityStatus:m.availabilityStatus,provisionMode:m.provisionMode,exactVariantId:m.exactVariantId,featureCode:m.featureCode,projectionType:"EXACT_VARIANT_VERIFIED",trimLinkMaterializationId:trimMats.find((t:any)=>t.exactVariantId===m.exactVariantId).materializationId,familyInheritance:false,crossPowertrainPropagation:false,evidenceReinterpretation:false,decisionAuthority:"SHADOW_AND_EXPLANATION_DISABLED"}));
 const payload={...active,schemaVersion:"1.2.0-rc",releaseCandidateId:RELEASE,state:"PILOT_VERIFIED_DATA",generatedAt:AT,verifiedAssertions:[...active.verifiedAssertions,...assertionMats],verifiedTrimLinks:[...active.verifiedTrimLinks,...trimMats],projections:[...active.projections,...newProjections],coverage:{catalogVariantCount:566,verifiedAssertionCoverage:{exactVariantCount:4,exactVariantIds:[...new Set([...active.verifiedAssertions,...assertionMats].map((x:any)=>x.exactVariantId))].sort()},reviewedAssociationOnlyCoverage:{exactVariantCount:2,exactVariantIds:[...new Set(active.reviewedAssociations.map((x:any)=>x.exactVariantId))].sort()},uncoveredCoverage:{exactVariantCount:560},authorityTiersAreDistinct:true},provenance:{...active.provenance,scaleWave001:{manifestId:manifest.manifestId,manifestChecksum,approvalAttestationId:attestationId,approvalEventIds:approvals.map((x:any)=>x.eventId)}},decisionAuthority:"SHADOW_AND_EXPLANATION_DISABLED",decisionControls:{hardFilter:false,hardFilterAfterConfirmation:false,softRanking:false,questionGeneration:false,userFacingExplanation:false,candidateResurrection:"FORBIDDEN",candidateElimination:"FORBIDDEN",offerOrderingImpact:"NONE"}};
 const issues=validateScaleWaveReleaseCandidate({manifest,approvalEvents:approvals,assertionMaterializations:assertionMats,trimMaterializations:trimMats,payload,expectedManifestChecksum:MANIFEST_SHA});if(issues.length)throw new Error(issues.join(","));
 await mkdir(OUT,{recursive:true}); await writeFile(path.join(OUT,"approval-statement.txt"),STATEMENT+"\n"); await write("approval-attestation.json",attestation);await write("owner-approval-events.json",approvals);await write("verified-assertion-materializations.json",assertionMats);await write("verified-trim-link-materializations.json",trimMats);await write("equipment-evidence.json",payload);
 const payloadSha=sha(canonicalJson(payload)); const newDist=assertionMats.reduce((r:any,x:any)=>(r[`${x.availabilityStatus}+${x.provisionMode}`]=(r[`${x.availabilityStatus}+${x.provisionMode}`]??0)+1,r),{}), existingDist=active.verifiedAssertions.reduce((r:any,x:any)=>{const provision=x.provisionMode??`LEGACY_${x.standardOrOptional}_NO_PROVISION_MODE`;r[`${x.availabilityStatus}+${provision}`]=(r[`${x.availabilityStatus}+${provision}`]??0)+1;return r},{});
 await write("availability-provision-distribution.json",{existingDerivedFromV14:existingDist,new:newDist,cumulativeVerifiedAssertionCount:112});await write("coverage-report.json",payload.coverage);await write("projection-report.json",{total:112,Junior:47,BYD:33,Nissan:32,Tonale:0,Volvo:0,negativeProjectionCount:3,negativeExactVariantIds:["6cb56615-37ef-51a8-9202-a73e59d4e14b"],decisionAuthority:"SHADOW_AND_EXPLANATION_DISABLED"});
 await write("provenance-appendix.json",{approvalManifest:{id:manifest.manifestId,checksum:manifestChecksum},approvalAttestation:{id:attestationId,checksum:fingerprint(attestation)},independentReviewEventIds:manifest.subjects.map((x:any)=>x.independentReviewEventId).sort(),excluded:{Volvo:27,inconclusive:37,predecessorConflicts:67}});
 await write("decision-neutrality-dry-run.json",{status:"PASSED",scenarios:["BYD_REQUIRED_FEATURE","NISSAN_FEATURE_QUERY","BYD_NEGATIVE_FEATURES","TONALE_ASSOCIATIONS","VOLVO_EQUIPMENT_QUERY"],filterImpact:0,rankingImpact:0,questionImpact:0,readinessImpact:0,offerCandidateIdOrOrderImpact:0,cardImpact:0,publicFactImpact:0,decisionAuthority:"SHADOW_AND_EXPLANATION_DISABLED"});
 const proposedPointer={activeEquipmentEvidenceRelease:RELEASE,compatibleCatalogRelease:"v0.55.2",compatibleCatalogFingerprint:CATALOG_SHA,payloadSha256:payloadSha,schemaVersion:"1.2.0-rc",state:"ACTIVE"};const proposedModule=`// Generated. Do not edit.\nexport { default as activeEquipmentEvidencePayload } from "./releases/${RELEASE}/equipment-evidence.json";\nexport { default as activeEquipmentEvidenceManifest } from "./releases/${RELEASE}/manifest.json";\nexport const activeEquipmentEvidenceRelease = "${RELEASE}";\n`;
 await write("proposed-active-pointer.json",proposedPointer);await writeFile(path.join(OUT,"proposed-activeEquipmentEvidence.generated.ts.txt"),proposedModule);await write("activation-plan.json",{status:"EXPLICIT_ACTIVATION_APPROVAL_REQUIRED",activePointerChanged:false,proposedPointerSha256:sha(canonicalJson(proposedPointer)),proposedGeneratedModuleSha256:sha(proposedModule),decisionAuthority:"SHADOW_AND_EXPLANATION_DISABLED"});await write("rollback-plan.json",{rollbackTarget:"v1.4.0-reviewed-associations-catalog-v0.55.2-2026-08-18",activePointerSha256:before.pointer,activeGeneratedModuleSha256:before.module});
 const releaseManifest={releaseVersion:RELEASE,parentRelease:"v1.4.0-reviewed-associations-catalog-v0.55.2-2026-08-18",schemaVersion:"1.2.0-rc",compatibleCatalogRelease:"v0.55.2",compatibleCatalogFingerprint:CATALOG_SHA,payloadSha256:payloadSha,verifiedAssertionCount:112,reviewedAssociationCount:49,verifiedTrimLinkCount:6,projectionCount:112,coverage:{verified:4,associationOnly:2,uncovered:560,total:566},approvalManifestId:manifest.manifestId,approvalManifestChecksum:manifestChecksum,approvalAttestationId:attestationId,decisionAuthority:"SHADOW_AND_EXPLANATION_DISABLED",validationStatus:"VALIDATED_RELEASE_CANDIDATE",generatedAt:AT};await write("manifest.json",releaseManifest);
 const after={activeRelease:await fileSha(ACTIVE+"/equipment-evidence.json"),activeManifest:await fileSha(ACTIVE+"/manifest.json"),pointer:await fileSha(path.join(ROOT,"data/production/equipment-evidence/active.json")),module:await fileSha(path.join(ROOT,"data/production/equipment-evidence/activeEquipmentEvidence.generated.ts"))};if(JSON.stringify(before)!==JSON.stringify(after))throw new Error("ACTIVE_ARTIFACT_MUTATED");
 const files=["approval-statement.txt","approval-attestation.json","owner-approval-events.json","verified-assertion-materializations.json","verified-trim-link-materializations.json","equipment-evidence.json","availability-provision-distribution.json","coverage-report.json","projection-report.json","provenance-appendix.json","decision-neutrality-dry-run.json","proposed-active-pointer.json","proposed-activeEquipmentEvidence.generated.ts.txt","activation-plan.json","rollback-plan.json","manifest.json"];await write("checksums.json",Object.fromEntries(await Promise.all(files.map(async f=>[f,await fileSha(path.join(OUT,f))]))));await write("materialization-result.json",{approvalAttestationId:attestationId,approvalAttestationChecksum:fingerprint(attestation),approvalEventCount:67,assertionMaterializationCount:65,trimLinkMaterializationCount:2,releaseId:RELEASE,releaseChecksum:payloadSha,projectionCount:112,coverage:{verified:4,associationOnly:2,uncovered:560},proposedPointerChecksum:sha(canonicalJson(proposedPointer)),proposedModuleChecksum:sha(proposedModule),rollbackTarget:"v1.4.0-reviewed-associations-catalog-v0.55.2-2026-08-18",activePointerChanged:false,decisionImpact:"NONE",activationBlocker:"EXPLICIT_ACTIVATION_APPROVAL_REQUIRED"});console.log(JSON.stringify({release:RELEASE,payloadSha,attestationId,approvalEvents:67,assertionMats:65,trimMats:2,proposedPointer:sha(canonicalJson(proposedPointer)),proposedModule:sha(proposedModule)},null,2));
}
main().catch(e=>{console.error(e);process.exitCode=1});
