import { readFileSync,existsSync,mkdirSync,writeFileSync } from "node:fs";
import path from "node:path";
import { digestQuestionPolicy, washingMachineQuestionPolicyPayloadSchema } from "../features/appliances/governance/questionPolicyAuthority";

const root=process.cwd(),draft=JSON.parse(readFileSync(path.join(root,"data/governance/appliances/question-policy/drafts/WASHING_MACHINE_QUESTION_POLICY-v0.1.json"),"utf8"));
const questions=draft.questions.map((q:Record<string,unknown>)=>{const answer=q.answerDomain as Record<string,unknown>,realization=q.realization as Record<string,unknown>;return{...q,answerDomain:q.targetConcept==="REMOTE_CONTROL"?{type:"ENUM",values:["WANTED","NOT_IMPORTANT"],normalizedShape:"{wanted:boolean}"}:answer,materiality:{...(q.materiality as object),softPreferenceEffect:"NON_FILTERING"},realization:q.targetConcept==="REMOTE_CONTROL"?{...realization,textTr:"Uygulamadan uzaktan kontrol özelliği istiyor musun, yoksa bu özellik senin için önemli değil mi?"}:realization,governanceClassification:"APPROVED_PRODUCT_GOVERNANCE"};});
const decisions=draft.decisionRegister.map((d:Record<string,unknown>)=>({decisionId:d.decisionId,topic:d.topic,authorityEvidence:d.currentAuthorityEvidence,approvedDecision:d.proposedDecision,alternativesConsidered:d.alternativesConsidered,runtimeConsequence:d.runtimeConsequence,riskControlled:d.riskIfUnresolved,governanceClassification:d.topic==="no-question-available"?"EXISTING_ARCHITECTURE_CONSTRAINT":d.topic==="persona-influence"?"EXISTING_SEMANTIC_AUTHORITY":"APPROVED_PRODUCT_GOVERNANCE",approvalStatus:"APPROVED"}));
const payload=washingMachineQuestionPolicyPayloadSchema.parse({schemaVersion:"washing-machine-question-policy/v1",policyId:draft.policyId,governanceStatus:"APPROVED",lifecycle:"FROZEN",runtimeActive:true,departmentId:draft.departmentId,productType:draft.productType,market:draft.market,stage:draft.stage,approvedAt:"2026-09-03T15:00:00+03:00",provenance:{draftWorkUnit:"WU-APPL-QUESTION-POLICY-01",approvalWorkUnit:"WU-APPL-QUESTION-POLICY-APPROVAL-01",approvedBy:"ORGANIZATOR",reviewVerdict:"ACCEPTED_WITH_REQUIRED_AMENDMENT",amendment:"REMOTE_CONTROL_DOMAIN_WANTED_OR_NOT_IMPORTANT"},bindings:{semanticRegistryVersion:draft.provenance.semanticRegistryVersion,semanticRegistryDigest:draft.provenance.semanticRegistryDigest,catalogRelease:draft.provenance.catalogRelease,catalogDigest:draft.provenance.catalogDigest,candidateEvaluationPolicy:draft.provenance.candidateEvaluationPolicy},selectionPolicy:{...draft.selectionPolicy,stableQuestionKeyTieBreak:true,noQuestionMeaning:"NO_AUTHORIZED_MATERIAL_QUESTION; NOT_SUFFICIENCY; NOT_RECOMMENDATION_READY; NOT_DECISION_READY; NOT_COMPLETE"},suppressionPolicy:{acceptedTargetSuppresses:true,pendingTargetSuppresses:true,unchangedAskedStateSuppresses:true,fingerprintCannotOverrideActiveAcceptedAnswer:true,transcriptInference:"FORBIDDEN",retryOrTimeReopening:"FORBIDDEN"},reopeningPolicy:{authorizedReasons:["TARGET_CLEARED","TARGET_CORRECTED","TARGET_SUPERSEDED","MATERIALLY_CHANGED_EVALUATION_AUTHORITY"]},questions,excludedTopics:draft.excludedTopics.map((x:Record<string,unknown>)=>x.topic==="CAPACITY_MINIMUM_KG"?{...x,classification:"FROZEN_EXCLUSION",reason:"Approved exclusion: no literal capacity threshold or household-to-kg rule is authorized."}:x),decisionRegister:decisions,failClosedContract:{version:"appliances-question-policy-fail-closed/v1",fallback:"NONE"}});
const policyDigest=digestQuestionPolicy(payload),artifact={envelopeSchemaVersion:"washing-machine-question-policy-artifact/v1",canonicalSerialization:"CANONICAL_JSON_SORTED_KEYS_V1",policyDigest,payload},pointer={schemaVersion:"appliances-question-policy-active-pointer/v1",policyId:payload.policyId,policyDigest,policyFile:"releases/WASHING_MACHINE_QUESTION_POLICY-v0.1/policy.json",lifecycle:"ACTIVE"};
const writeImmutable=(relative:string,value:unknown)=>{const target=path.join(root,relative),bytes=`${JSON.stringify(value,null,2)}\n`;mkdirSync(path.dirname(target),{recursive:true});if(existsSync(target)&&readFileSync(target,"utf8")!==bytes)throw new Error(`IMMUTABLE_RELEASE_CONFLICT:${relative}`);if(!existsSync(target))writeFileSync(target,bytes,{flag:"wx"});};
writeImmutable("data/production/appliances/question-policy/releases/WASHING_MACHINE_QUESTION_POLICY-v0.1/policy.json",artifact);writeFileSync(path.join(root,"data/production/appliances/question-policy/active.json"),`${JSON.stringify(pointer,null,2)}\n`);console.log(JSON.stringify({policyId:payload.policyId,policyDigest,questionCount:payload.questions.length},null,2));
