import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { approvalManifestChecksum, authorizationStatementHash, validateOwnerApprovalGrantEvents, type EquipmentApprovalManifest, type EquipmentOwnerActorRecord, type EquipmentOwnerApprovalGrantEvent } from "../features/vehicle-data/equipmentOwnerGovernance";
import { canonicalJson, fingerprint, selectTerminalSecondReviewed } from "../features/vehicle-data/equipmentVerificationMaterialization";
import type { EquipmentEvidenceAssertion, EquipmentReviewEvent, EquipmentTrimVariantLink } from "../types/equipmentEvidence";

const ROOT = process.cwd();
const BASE = path.join(ROOT, "data/production/equipment-evidence/working/EE-PILOT-002/EE-PILOT-002-BATCH-001");
const R1 = path.join(BASE, "corrections/EE-PILOT-002-CYCLE-001-R1"), R2 = path.join(BASE, "corrections/EE-PILOT-002-CYCLE-001-R2");
const MANIFEST_DIR = path.join(BASE, "owner-governance/EE-OWNER-APPROVAL-MANIFEST-001");
const RELEASE_ID = "v1.3.0-pilot-verified-catalog-v0.55.2-2026-08-18";
const OUTPUT = path.join(ROOT, "data/production/equipment-evidence/release-candidates", RELEASE_ID);
const CREATED_AT = "2026-08-18T22:20:00.000Z", POLICY = "1.0.0";
const CATALOG_FINGERPRINT = "sha256:fd5609adcc0ca3fec0f8c9dc4dd1c903ed5514326bd322eacd4decff5a044f0f" as const;
const APPROVAL_STATEMENT = `EQUIPMENT_OWNER_001 olarak EE-OWNER-APPROVAL-MANIFEST-001 kimlikli ve
sha256:f35e41f2882afc35a3d31eb0e9b918135c4c4ca82b4c9b6515f8447379f118bc
checksum’lı approval manifestini inceledim. Manifestteki 47 assertion ve
2 trim link için owner approval verilmesini, append-only approval event’lerinin
ve verification materialization kayıtlarının üretilmesini onaylıyorum.
Bu onayın Equipment Evidence pilot kapsamında olduğunu ve Decision Engine’e
henüz filtreleme, sıralama veya soru üretme yetkisi vermediğini kabul ediyorum.
`;
const read = async <T>(file: string): Promise<T> => JSON.parse(await readFile(file, "utf8")) as T;
const shaFile = async (file: string) => `sha256:${createHash("sha256").update(await readFile(file)).digest("hex")}`;
const id = (prefix: string, value: unknown) => `${prefix}-${fingerprint(value).slice(7, 27).toUpperCase()}`;

function chainForAssertion(item: EquipmentEvidenceAssertion, all: readonly EquipmentEvidenceAssertion[]): string[] {
  const chain = [item.assertionId]; let current = item;
  while (current.supersedesAssertionId) { const predecessor = all.find((candidate) => candidate.assertionId === current.supersedesAssertionId); if (!predecessor) throw new Error("ASSERTION_CHAIN_TARGET_MISSING"); chain.unshift(predecessor.assertionId); current = predecessor; }
  return chain;
}
function chainForLink(item: EquipmentTrimVariantLink, all: readonly EquipmentTrimVariantLink[]): string[] {
  const chain = [item.linkId]; let current = item;
  while (current.supersedesTrimLinkId) { const predecessor = all.find((candidate) => candidate.linkId === current.supersedesTrimLinkId); if (!predecessor) throw new Error("TRIM_CHAIN_TARGET_MISSING"); chain.unshift(predecessor.linkId); current = predecessor; }
  return chain;
}

async function main() {
  const actorRegistry = await read<{ actors: EquipmentOwnerActorRecord[] }>(path.join(ROOT, "data/production/equipment-evidence/governance/actor-registry.json"));
  const actor = actorRegistry.actors.find((candidate) => candidate.actorId === "EQUIPMENT_OWNER_001");
  const authorization = await readFile(path.join(ROOT, "data/production/equipment-evidence/governance/attestations/EQUIPMENT_OWNER_001-v1.txt"), "utf8");
  if (!actor || actor.status !== "ACTIVE" || actor.scope !== "EQUIPMENT_EVIDENCE_ONLY" || actor.authorizationStatementHash !== authorizationStatementHash(authorization)) throw new Error("OWNER_REGISTRY_OR_AUTHORIZATION_INVALID");
  const manifest = await read<EquipmentApprovalManifest>(path.join(MANIFEST_DIR, "approval-manifest.json"));
  const { manifestChecksum, ...manifestPayload } = manifest;
  if (manifest.manifestId !== "EE-OWNER-APPROVAL-MANIFEST-001" || manifestChecksum !== "sha256:f35e41f2882afc35a3d31eb0e9b918135c4c4ca82b4c9b6515f8447379f118bc" || approvalManifestChecksum(manifestPayload) !== manifestChecksum) throw new Error("APPROVAL_MANIFEST_CHECKSUM_MISMATCH");
  const allAssertions = [...await read<EquipmentEvidenceAssertion[]>(path.join(BASE, "assertions.json")), ...await read<EquipmentEvidenceAssertion[]>(path.join(R1, "assertions.json")), ...await read<EquipmentEvidenceAssertion[]>(path.join(R2, "assertions.json"))];
  const allLinks = [...await read<EquipmentTrimVariantLink[]>(path.join(BASE, "trim-links.json")), ...await read<EquipmentTrimVariantLink[]>(path.join(R1, "trim-links.json")), ...await read<EquipmentTrimVariantLink[]>(path.join(R2, "trim-links.json"))];
  const allReviews = [...await read<EquipmentReviewEvent[]>(path.join(BASE, "second-review-events.json")), ...await read<EquipmentReviewEvent[]>(path.join(R1, "second-review/second-review-events.json")), ...await read<EquipmentReviewEvent[]>(path.join(R2, "second-review/second-review-events.json"))];
  const terminal = selectTerminalSecondReviewed({ assertions: allAssertions, trimLinks: allLinks, reviewEvents: allReviews });
  const attestationChecksum = authorizationStatementHash(APPROVAL_STATEMENT);
  const attestationId = id("EE-OWNER-ATTEST", { actorId: actor.actorId, manifestId: manifest.manifestId, manifestChecksum, attestationChecksum });
  const attestation = { approvalAttestationId: attestationId, ownerActorId: actor.actorId, normalizedApprovalStatement: APPROVAL_STATEMENT, approvalStatementChecksum: attestationChecksum, approvalManifestId: manifest.manifestId, approvalManifestChecksum: manifestChecksum, subjectCount: 49, decisionAuthority: "SHADOW_AND_EXPLANATION_DISABLED", recordedAt: CREATED_AT, governancePolicyVersion: POLICY, identityAssurance: "REPOSITORY_GOVERNANCE_ATTESTATION_NOT_REAL_WORLD_CRYPTOGRAPHIC_IDENTITY" };
  const events: EquipmentOwnerApprovalGrantEvent[] = manifest.subjects.map((subject): EquipmentOwnerApprovalGrantEvent => ({ eventId: id("EE-OWNER-APP", { manifestChecksum, subjectType: subject.subjectType, subjectId: subject.subjectId, attestationId }), eventType: "OWNER_APPROVAL_GRANTED", actorId: actor.actorId, actorRole: "EQUIPMENT_OWNER_APPROVER", subjectType: subject.subjectType, subjectId: subject.subjectId, exactVariantId: subject.exactVariantId, approvalManifestId: manifest.manifestId, approvalManifestChecksum: manifestChecksum, sourceSecondReviewEventId: subject.secondReviewEventId, sourceContentFingerprint: subject.contentFingerprint, approvalAttestationId: attestationId, governancePolicyVersion: POLICY, createdAt: CREATED_AT, decisionAuthority: "SHADOW_AND_EXPLANATION_DISABLED" })).sort((a, b) => `${a.subjectType}|${a.subjectId}`.localeCompare(`${b.subjectType}|${b.subjectId}`));
  const eventIssues = validateOwnerApprovalGrantEvents({ events, manifest, ownerActor: actor }); if (eventIssues.length) throw new Error(`OWNER_EVENTS_INVALID:${eventIssues.join(",")}`);
  const eventBySubject = new Map(events.map((event) => [`${event.subjectType}:${event.subjectId}`, event]));
  const assertionMaterializations = terminal.assertions.map((assertion) => { const subject = manifest.subjects.find((candidate) => candidate.subjectType === "ASSERTION" && candidate.subjectId === assertion.assertionId), event = eventBySubject.get(`ASSERTION:${assertion.assertionId}`); if (!subject || !event || fingerprint(assertion) !== subject.contentFingerprint || assertion.conflictState !== "CLEAR" || assertion.availabilityStatus === "UNKNOWN") throw new Error("ASSERTION_MATERIALIZATION_GATE_FAILED"); return { materializationId: id("EE-MAT", { sourceAssertionId: assertion.assertionId, manifestChecksum, policy: POLICY }), materializationType: "VERIFIED_EQUIPMENT_ASSERTION", sourceAssertionId: assertion.assertionId, sourceAssertionFingerprint: subject.contentFingerprint, exactVariantId: assertion.exactVariantId, featureCode: assertion.featureCode, availabilityStatus: assertion.availabilityStatus, standardOrOptional: assertion.availabilityStatus, marketApplicability: assertion.market, modelYearApplicability: { from: assertion.modelYearFrom, to: assertion.modelYearTo }, terminalSupersessionChain: chainForAssertion(assertion, allAssertions), secondReviewEventId: subject.secondReviewEventId, ownerApprovalEventId: event.eventId, approvalManifestId: manifest.manifestId, approvalManifestChecksum: manifestChecksum, rawSourceReferences: [{ sourceId: assertion.source.sourceId, artifactReference: assertion.source.artifactReference, artifactSha256: assertion.source.artifactSha256 }], derivedArtifactReferences: assertion.derivedArtifact ? [assertion.derivedArtifact] : [], semanticMappingId: assertion.semanticMappingId ?? null, confidence: assertion.confidence, verificationState: "VERIFIED", catalogRelease: "v0.55.2", catalogFingerprint: CATALOG_FINGERPRINT, policyVersion: POLICY, materializedAt: CREATED_AT, decisionAuthority: "SHADOW_AND_EXPLANATION_DISABLED" }; }).sort((a, b) => a.materializationId.localeCompare(b.materializationId));
  const trimMaterializations = terminal.trimLinks.map((link) => { const subject = manifest.subjects.find((candidate) => candidate.subjectType === "TRIM_LINK" && candidate.subjectId === link.linkId), event = eventBySubject.get(`TRIM_LINK:${link.linkId}`), extended = link as EquipmentTrimVariantLink & { identitySourceIds?: string[]; provenanceSourceIds?: string[] }; if (!subject || !event || fingerprint(link) !== subject.contentFingerprint) throw new Error("TRIM_MATERIALIZATION_GATE_FAILED"); return { materializationId: id("EE-MAT-TRIM", { sourceTrimLinkId: link.linkId, manifestChecksum, policy: POLICY }), materializationType: "VERIFIED_EQUIPMENT_TRIM_LINK", sourceTrimLinkId: link.linkId, sourceTrimLinkFingerprint: subject.contentFingerprint, exactVariantId: link.exactVariantId, canonicalTrimId: link.canonicalTrimId, terminalSupersessionChain: chainForLink(link, allLinks), secondReviewEventId: subject.secondReviewEventId, ownerApprovalEventId: event.eventId, approvalManifestId: manifest.manifestId, approvalManifestChecksum: manifestChecksum, sourceIds: [...(extended.identitySourceIds ?? extended.provenanceSourceIds ?? [])].sort(), assertionMaterializationIds: link.assertionIds.map((assertionId) => assertionMaterializations.find((item) => item.sourceAssertionId === assertionId)!.materializationId).sort(), marketApplicability: link.market, modelYearApplicability: { from: link.modelYearFrom, to: link.modelYearTo }, verificationState: "VERIFIED", catalogRelease: "v0.55.2", catalogFingerprint: CATALOG_FINGERPRINT, policyVersion: POLICY, materializedAt: CREATED_AT, decisionAuthority: "SHADOW_AND_EXPLANATION_DISABLED" }; }).sort((a, b) => a.materializationId.localeCompare(b.materializationId));
  if (assertionMaterializations.length !== 47 || trimMaterializations.length !== 2 || new Set(assertionMaterializations.map((x) => x.sourceAssertionId)).size !== 47) throw new Error("MATERIALIZATION_COUNTS_INVALID");
  const activeRelease = await read<{ featureDefinitions: unknown[]; intentAliases: unknown[] }>(path.join(ROOT, "data/production/equipment-evidence/releases/v1.2.2-catalog-v0.55.2-2026-08-18/equipment-evidence.json"));
  const catalog = await read<{ records: Array<{ variant: { id: string } }> }>(path.join(ROOT, "data/production/catalog/releases/v0.55.2/catalog.json"));
  const coveredIds = [...new Set(assertionMaterializations.map((x) => x.exactVariantId))].sort(), uncoveredIds = catalog.records.map((x) => x.variant.id).filter((variantId) => !coveredIds.includes(variantId)).sort();
  const featureCoverage = activeRelease.featureDefinitions.map((definition) => { const featureCode = (definition as { featureCode: string }).featureCode, items = assertionMaterializations.filter((item) => item.featureCode === featureCode); return { featureCode, coveredExactVariantCount: new Set(items.map((item) => item.exactVariantId)).size, verifiedAssertionCount: items.length, uncoveredCatalogVariantCount: catalog.records.length - new Set(items.map((item) => item.exactVariantId)).size, authoritativeNegativeProjectionCount: 0, conflictProjectionCount: 0, decisionAuthority: "SHADOW_AND_EXPLANATION_DISABLED" }; });
  const projections = assertionMaterializations.map((item) => ({ projectionType: "EXACT_VARIANT_VERIFIED", exactVariantId: item.exactVariantId, featureCode: item.featureCode, availabilityStatus: item.availabilityStatus, standardOrOptional: item.standardOrOptional, assertionMaterializationId: item.materializationId, trimLinkMaterializationId: trimMaterializations.find((link) => link.exactVariantId === item.exactVariantId)?.materializationId, familyInheritance: false, crossPowertrainPropagation: false, evidenceReinterpretation: false, decisionAuthority: "SHADOW_AND_EXPLANATION_DISABLED" })).sort((a, b) => `${a.exactVariantId}|${a.featureCode}`.localeCompare(`${b.exactVariantId}|${b.featureCode}`));
  const releasePayload = { schemaVersion: "1.0.0-rc", releaseCandidateId: RELEASE_ID, state: "PILOT_VERIFIED_DATA", compatibleCatalogRelease: "v0.55.2", compatibleCatalogFingerprint: CATALOG_FINGERPRINT, generatedAt: CREATED_AT, canonicalSerializationVersion: "CANONICAL_JSON_SORTED_KEYS_V1", decisionAuthority: "SHADOW_AND_EXPLANATION_DISABLED", featureDefinitions: activeRelease.featureDefinitions, intentAliases: activeRelease.intentAliases, verifiedAssertions: assertionMaterializations, verifiedTrimLinks: trimMaterializations, projections, coverage: { catalogVariantCount: catalog.records.length, coveredExactVariantCount: coveredIds.length, uncoveredExactVariantCount: uncoveredIds.length, coveredExactVariantIds: coveredIds, uncoveredDisposition: "UNCOVERED_NOT_ASSERTED_UNKNOWN", syntheticUnknownAssertionCount: 0, authoritativeNegativeProjectionCount: 0, conflictProjectionCount: 0 }, provenance: { ownerActorId: actor.actorId, approvalAttestationId: attestationId, approvalManifestId: manifest.manifestId, approvalManifestChecksum: manifestChecksum, independentReviewEventIds: manifest.subjects.map((x) => x.secondReviewEventId).sort(), pilotId: manifest.pilotId, batchId: manifest.batchId, correctionCycleScope: manifest.correctionCycleScope }, decisionControls: { hardFilter: false, hardFilterAfterConfirmation: false, softRanking: false, questionGeneration: false, userFacingExplanation: false, candidateResurrection: "FORBIDDEN", candidateElimination: "FORBIDDEN", offerOrderingImpact: "NONE" } };
  const releaseChecksum = fingerprint(releasePayload);
  const immutableManifest = { releaseCandidateId: RELEASE_ID, state: "PILOT_VERIFIED_DATA", releaseChecksum, catalogRelease: "v0.55.2", catalogFingerprint: CATALOG_FINGERPRINT, featureDefinitionCount: activeRelease.featureDefinitions.length, verifiedAssertionCount: assertionMaterializations.length, verifiedTrimLinkCount: trimMaterializations.length, exactVariantCoverageCount: coveredIds.length, uncoveredExactVariantCount: uncoveredIds.length, approvalEventCount: events.length, approvalAttestationId: attestationId, approvalManifestId: manifest.manifestId, approvalManifestChecksum: manifestChecksum, canonicalSerializationVersion: "CANONICAL_JSON_SORTED_KEYS_V1", generatedAt: CREATED_AT, decisionAuthority: "SHADOW_AND_EXPLANATION_DISABLED", immutable: true };
  const activePointerPath = path.join(ROOT, "data/production/equipment-evidence/active.json"), generatedModulePath = path.join(ROOT, "data/production/equipment-evidence/activeEquipmentEvidence.generated.ts");
  const pointerHash = await shaFile(activePointerPath), moduleHash = await shaFile(generatedModulePath);
  const activation = { status: "COMPATIBLE_DECISION_NEUTRAL_AWAITING_SEPARATE_ACTIVATION_APPROVAL", releaseCandidateId: RELEASE_ID, releaseChecksum, catalogCompatible: catalog.records.length === 566, decisionNeutral: true, activePointerChanged: false, activePointerBeforeSha256: pointerHash, activePointerAfterSha256: pointerHash, generatedActiveModuleBeforeSha256: moduleHash, generatedActiveModuleAfterSha256: moduleHash, activationAuthorized: false };
  const rollback = { activationPerformed: false, currentActiveRelease: "v1.2.2-catalog-v0.55.2-2026-08-18", candidateRelease: RELEASE_ID, ifFutureActivationFails: { restoreActivePointerTo: "v1.2.2-catalog-v0.55.2-2026-08-18", restoreGeneratedModule: true, retainApprovalAndMaterializationAudit: true, appendOnlyRevocationRequired: true }, currentRollbackRequired: false };
  const historical = { originalIbridaAssertionsPreservedExcluded: 24, r1IbridaAssertionsPreservedExcluded: 24, historicalConflictAssertionsPreservedExcluded: 48, historicalConflictTrimLinksPreservedExcluded: 2, inconclusiveResearchRowsPreservedExcluded: 55, materializedHistoricalRecordCount: 0 };
  await mkdir(OUTPUT, { recursive: true });
  const files: Record<string, unknown | string> = { "approval-attestation.json": attestation, "approval-statement.txt": APPROVAL_STATEMENT, "owner-approval-events.json": events, "verified-assertion-materializations.json": assertionMaterializations, "verified-trim-link-materializations.json": trimMaterializations, "equipment-evidence-release-candidate.json": releasePayload, "immutable-release-manifest.json": immutableManifest, "coverage-report.json": { coveredExactVariantIds: coveredIds, uncoveredExactVariantCount: uncoveredIds.length, features: featureCoverage }, "historical-audit-integrity.json": historical, "activation-dry-run.json": activation, "rollback-plan.json": rollback };
  for (const [name, value] of Object.entries(files)) await writeFile(path.join(OUTPUT, name), typeof value === "string" ? value : canonicalJson(value));
  const names = Object.keys(files).sort(), checksums = Object.fromEntries(await Promise.all(names.map(async (name) => [name, await shaFile(path.join(OUTPUT, name))]))); await writeFile(path.join(OUTPUT, "checksums.json"), canonicalJson(checksums));
  console.log(canonicalJson({ approvalAttestationId: attestationId, approvalStatementChecksum: attestationChecksum, approvalEvents: events.length, assertionMaterializations: assertionMaterializations.length, trimLinkMaterializations: trimMaterializations.length, releaseCandidateId: RELEASE_ID, releaseChecksum, covered: coveredIds.length, uncovered: uncoveredIds.length, activePointerChanged: false }));
}

void main();
