import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

const root=process.cwd(), packagePath=path.join(root,"data/research/electronics/smartphone-amazon-tr-catalog-expansion-02/owner-approval-package.json"), baselinePath=path.join(root,"data/production/electronics/runtime/releases/ELECTRONICS-RUNTIME-CATALOG-TR-v1.2-ALL-CATEGORY-93/catalog.json");
const out=path.join(root,"data/research/electronics/smartphone-amazon-tr-catalog-expansion-02/exact-set-reconciliation-e0928d0");
const hash=(v:Buffer|string)=>createHash("sha256").update(v).digest("hex"), stable=(v:unknown):string=>v===null||typeof v!=="object"?JSON.stringify(v):Array.isArray(v)?`[${v.map(stable).join(",")}]`:`{${Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b,"en")).map(([k,x])=>`${JSON.stringify(k)}:${stable(x)}`).join(",")}}`;
const packageBytes=readFileSync(packagePath), baselineBytes=readFileSync(baselinePath), pkg=JSON.parse(packageBytes.toString()), baseline=JSON.parse(baselineBytes.toString());
if(hash(packageBytes)!=="f26713a71712a8b9b008269feb0c1ba00f66312176776d81a1894367207bc323")throw new Error("PACKAGE_DIGEST_MISMATCH");
if(hash(baselineBytes)!=="8df690e1d85292f466d4d7397cd86d6558e96e947403fcc9f4826ef36eab64f1")throw new Error("BASELINE_DIGEST_MISMATCH");
const successors:Record<string,string>={
 "electronics:smartphone:honor:dny-nx9-8-256-black":"electronics:smartphone:honor:honor-400:dny-nx9-8-256-gece-siyahi",
 "electronics:smartphone:samsung:sm-a266bzkctur":"electronics:smartphone:samsung:galaxy-a26-5g:sm-a266bzkctur-8-256-black",
 "electronics:smartphone:samsung:sm-a366bzkgtur":"electronics:smartphone:samsung:galaxy-a36-5g:sm-a366bzkgtur-8-256-black",
 "electronics:smartphone:xiaomi:14t-12-256-black":"electronics:smartphone:xiaomi:xiaomi-14t:no-public-sku-12-256-titan-siyah",
 "electronics:smartphone:xiaomi:redmi-note-14-pro-8-256-black":"electronics:smartphone:redmi:redmi-note-14-pro:no-public-sku-8-256-gece-siyahi"
};
const active=baseline.products.filter((p:{categoryId:string})=>p.categoryId==="SMARTPHONE"), pendingIds=new Set(pkg.products.map((p:{exactProductId:string})=>p.exactProductId));
const table=active.map((p:{exactProductId:string;manufacturer:string;modelCode:string;configurationIdentity:string})=>{
 const successor=successors[p.exactProductId]??null, exactOverlap=pendingIds.has(p.exactProductId);
 return {activeExactProductId:p.exactProductId,manufacturer:p.manufacturer,modelCode:p.modelCode,activeConfigurationIdentity:p.configurationIdentity,exactIdOverlap:exactOverlap,successorExactProductId:successor,disposition:exactOverlap?"PRESERVED_EXACT_ID":successor?"REPLACED_BY_EXPLICIT_EXACT_CONFIGURATION_SUCCESSOR":"PRESERVED_ACTIVE_NOT_COVERED_BY_PACKAGE",reason:exactOverlap?"Exact ID already in pending membership":successor?"Same brand/model and exact RAM/storage/color or manufacturer SKU configuration is explicitly mapped":"No equivalent exact configuration exists in the pending 33; silent drop prohibited"};
});
const preservedActive=active.filter((p:{exactProductId:string})=>!successors[p.exactProductId]&&!pendingIds.has(p.exactProductId)), nonSmartphone=baseline.products.filter((p:{categoryId:string})=>p.categoryId!=="SMARTPHONE");
const mapped=pkg.products.map((p:{exactProductId:string;brand:string;model:string;modelCode:string|null;configurationIdentity:string;facts:Record<string,unknown>;sourceIds:string[]})=>({exactProductId:p.exactProductId,categoryId:"SMARTPHONE",manufacturer:p.brand,modelCode:p.modelCode??p.model,configurationIdentity:p.configurationIdentity,evidenceReleaseDigest:"sha256:f26713a71712a8b9b008269feb0c1ba00f66312176776d81a1894367207bc323",facts:Object.entries(p.facts).filter(([,v])=>v!==null).map(([key,value],i)=>({factId:`smartphone-v02:${p.exactProductId.split(":").slice(2).join("-")}:${key}:${i+1}`,key,value,sourceId:p.sourceIds[0],locator:"Digest-bound exact Türkiye configuration owner-review package v02"})),unknownCodes:Object.entries(p.facts).filter(([,v])=>v===null).map(([key])=>`UNKNOWN_${key.toUpperCase()}`),personaEffect:"EXPLICIT_CONTEXT_AND_MATERIAL_FACTS_ONLY",commerceEffect:"NONE_FAIL_CLOSED"}));
const smartphones=[...preservedActive,...mapped], products=[...nonSmartphone,...smartphones], categories=baseline.categories.map((c:{categoryId:string;exactProductIds:string[]})=>c.categoryId==="SMARTPHONE"?{...c,exactProductIds:smartphones.map((p:{exactProductId:string})=>p.exactProductId)}:c);
if(products.length!==121||smartphones.length!==34||new Set(products.map((p:{exactProductId:string})=>p.exactProductId)).size!==121)throw new Error("RECONCILED_COUNTS_INVALID");
const candidate={...baseline,runtimeVersion:"XPY_RUNTIME/v0.3-READ-ONLY-CANDIDATE",releaseVersion:"ELECTRONICS-RUNTIME-CATALOG-TR-v1.3-SMARTPHONE-V02-RECONCILED-CANDIDATE",lifecycle:"CANDIDATE_NOT_ACTIVE",products,categories,evidenceChain:[...baseline.evidenceChain,{wave:"SMARTPHONE_V02_RECONCILED",releaseDigest:"sha256:f26713a71712a8b9b008269feb0c1ba00f66312176776d81a1894367207bc323"}],runtimeDigest:"NOT_FINAL_READ_ONLY",releaseDigest:"NOT_FINAL_READ_ONLY"};
const proof={schemaVersion:"electronics-smartphone-v02-reconciled-membership-proof/v1",sourceCommit:"f1ce8e61f76345aa10a1422bb511d2d9998dd954",auditCommit:"e0928d0",counts:{baselineTotal:93,baselineSmartphone:6,preservedNonSmartphone:87,replacedActiveSmartphone:5,preservedActiveSmartphone:1,pendingAdmitted:33,finalTotal:121,finalSmartphone:34,headphones:18,categories:24,exactIdOverlap:0,duplicates:0,silentDrops:0},activeReconciliation:table,finalSmartphoneExactProductIds:smartphones.map((p:{exactProductId:string})=>p.exactProductId),categories:categories.map((c:{categoryId:string;exactProductIds:string[]})=>({categoryId:c.categoryId,count:c.exactProductIds.length,membershipSha256:`sha256:${hash(stable(c.exactProductIds))}`,preservation:c.categoryId==="SMARTPHONE"?"RECONCILED_34":"IDENTICAL_TO_ELECTRONICS_V1_2"})),nonSmartphoneObjectSequenceSha256:`sha256:${hash(stable(nonSmartphone))}`,headphonesExactProductIds:products.filter((p:{categoryId:string})=>p.categoryId==="HEADPHONES").map((p:{exactProductId:string})=>p.exactProductId)};
const plan={schemaVersion:"electronics-smartphone-v02-reconciled-integration-plan/v1",status:"READ_ONLY_NOT_AUTHORIZED_NOT_ACTIVE",supersedes:["123_TOTAL_ASSUMPTION","120_TOTAL_NUMERIC_AUTHORIZATION","candidate-catalog-120.json"],reason:"One of six active smartphone identities, Apple iPhone 16e 128GB White TR, is not covered by the pending 33 and must be retained to prevent silent drop.",source:{commit:"f1ce8e61f76345aa10a1422bb511d2d9998dd954",catalogSha256:`sha256:${hash(baselineBytes)}`,pointerSha256:"sha256:c688c7d81ca191c7b1d41e5ec6434276b839cbe004e7e96c7db6c1209e233e4a"},package:{path:"data/research/electronics/smartphone-amazon-tr-catalog-expansion-02/owner-approval-package.json",sha256:"sha256:f26713a71712a8b9b008269feb0c1ba00f66312176776d81a1894367207bc323",regenerated:false},expected:{total:121,nonSmartphone:87,smartphone:34,headphones:18,categories:24,duplicates:0,silentDrops:0},preconditions:["Explicitly authorize reconciled 121/34/87/18 counts","Recheck source pointer and catalog byte digests","Recheck all 87 non-smartphone product objects and 23 non-smartphone category memberships","Recheck exact six-row reconciliation table and retained iPhone 16e","Run full targeted lineage tests and production build","Prepare immutable rollback then execute one CAS pointer update"],lineagePreservation:["Electronics v1.2 non-smartphone authority","Tools","Mobility","Universal Persona","Secretary","root catalog directory","Mitgo verification metadata"],invariants:{push:false,activePointerMutation:false,runtimeMutation:false,activation:false,deployment:false}};
const supersession={schemaVersion:"electronics-smartphone-authorization-supersession/v1",status:"SUPERSEDED_BY_EXACT_SET_RECONCILIATION",supersededAuthorization:"SMARTPHONE-V02-120-20260907",supersedingProof:"membership-proof.json",reason:plan.reason,newAuthorizationRequired:true};
rmSync(out,{recursive:true,force:true});mkdirSync(out,{recursive:true});const files:Record<string,unknown>={"active-six-reconciliation.json":{counts:{active:6,exactOverlap:0,replaced:5,preserved:1},rows:table},"candidate-catalog-121.json":candidate,"membership-proof.json":proof,"integration-plan.json":plan,"authorization-supersession.json":supersession};for(const [name,value] of Object.entries(files))writeFileSync(path.join(out,name),`${JSON.stringify(value,null,2)}\n`);
writeFileSync(path.join(out,"manifest.json"),`${JSON.stringify({schemaVersion:"electronics-smartphone-v02-exact-reconciliation-manifest/v1",status:plan.status,files:Object.entries(files).map(([name,value])=>({name,sha256:`sha256:${hash(`${JSON.stringify(value,null,2)}\n`)}`})),packageSha256:plan.package.sha256,pointerMutation:false,activation:false,deployment:false,push:false},null,2)}\n`);
console.log(JSON.stringify({out,counts:proof.counts,status:plan.status}));
