import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { approvalManifestChecksum, authorizationStatementHash, EQUIPMENT_APPROVAL_CANONICAL_SERIALIZATION_VERSION, EQUIPMENT_APPROVAL_MANIFEST_VERSION, EQUIPMENT_OWNER_AUTHORITY_VERSION, validateEquipmentApprovalManifest, validateEquipmentOwnerRegistry, type EquipmentApprovalManifest, type EquipmentApprovalManifestSubject, type EquipmentOwnerActorRecord } from "../features/vehicle-data/equipmentOwnerGovernance";
import { canonicalJson, fingerprint, selectTerminalSecondReviewed } from "../features/vehicle-data/equipmentVerificationMaterialization";
import type { EquipmentEvidenceAssertion, EquipmentReviewEvent, EquipmentTrimVariantLink } from "../types/equipmentEvidence";

const ROOT = process.cwd();
const BASE = path.join(ROOT, "data/production/equipment-evidence/working/EE-PILOT-002/EE-PILOT-002-BATCH-001");
const R1 = path.join(BASE, "corrections/EE-PILOT-002-CYCLE-001-R1"), R2 = path.join(BASE, "corrections/EE-PILOT-002-CYCLE-001-R2");
const GOVERNANCE = path.join(ROOT, "data/production/equipment-evidence/governance");
const OUTPUT = path.join(BASE, "owner-governance/EE-OWNER-APPROVAL-MANIFEST-001");
const GENERATED_AT = "2026-08-18T21:00:00.000Z";
const CATALOG_FINGERPRINT = "sha256:fd5609adcc0ca3fec0f8c9dc4dd1c903ed5514326bd322eacd4decff5a044f0f" as const;
const statement = `Expiya Cars Equipment Evidence katmanı için kendimi doğrulanmış
EQUIPMENT_OWNER_APPROVER olarak yetkilendiriyorum. Owner actor kimliğim
repository içinde kişisel veri içermeyen sabit bir ID ile temsil edilebilir.
Yetkim; bağımsız incelemeden geçmiş evidence kayıtlarını onaylama, reddetme
ve ayrı append-only event ile onayı geri alma kapsamındadır. Bu yetki ham
kanıtı değiştirme, bağımsız incelemeyi atlama veya conflict kayıtlarını
production’a taşıma hakkı vermez. EE-PILOT-002-BATCH-001 kapsamındaki
47 assertion ve 2 trim link için hazırlanan promotion paketini inceleme
ve onaylama yetkisini kabul ediyorum.
`;
const read = async <T>(file: string): Promise<T> => JSON.parse(await readFile(file, "utf8")) as T;
const shaFile = async (file: string) => `sha256:${createHash("sha256").update(await readFile(file)).digest("hex")}`;

async function main() {
  const actor: EquipmentOwnerActorRecord = { actorId: "EQUIPMENT_OWNER_001", role: "EQUIPMENT_OWNER_APPROVER", scope: "EQUIPMENT_EVIDENCE_ONLY", status: "ACTIVE", authorityVersion: EQUIPMENT_OWNER_AUTHORITY_VERSION, authorizationStatementHash: authorizationStatementHash(statement), authorizationRecordedAt: GENERATED_AT, authorizationSourceType: "EXPLICIT_PRODUCT_OWNER_DECLARATION", allowedActions: ["APPROVE_SECOND_REVIEW_PASSED", "REJECT_SECOND_REVIEW_PASSED", "REVOKE_PRIOR_OWNER_APPROVAL"], forbiddenActions: ["MODIFY_SOURCE_EVIDENCE", "MODIFY_REVIEW_RESULT", "BYPASS_SECOND_REVIEW", "APPROVE_CONFLICTING_SUBJECT", "APPROVE_SUPERSEDED_SUBJECT", "APPROVE_NON_TERMINAL_SUBJECT", "SELF_REVIEW_AS_INDEPENDENT_REVIEWER", "CHANGE_CATALOG_FACTS", "GRANT_DECISION_AUTHORITY"], revocationPolicy: "APPEND_ONLY_EVENT_REQUIRED", identityAssurance: "REPOSITORY_PRODUCT_OWNER_GOVERNANCE_ATTESTATION_NOT_REAL_WORLD_CRYPTOGRAPHIC_IDENTITY" };
  const assertions = [...await read<EquipmentEvidenceAssertion[]>(path.join(BASE, "assertions.json")), ...await read<EquipmentEvidenceAssertion[]>(path.join(R1, "assertions.json")), ...await read<EquipmentEvidenceAssertion[]>(path.join(R2, "assertions.json"))];
  const links = [...await read<EquipmentTrimVariantLink[]>(path.join(BASE, "trim-links.json")), ...await read<EquipmentTrimVariantLink[]>(path.join(R1, "trim-links.json")), ...await read<EquipmentTrimVariantLink[]>(path.join(R2, "trim-links.json"))];
  const events = [...await read<EquipmentReviewEvent[]>(path.join(BASE, "second-review-events.json")), ...await read<EquipmentReviewEvent[]>(path.join(R1, "second-review/second-review-events.json")), ...await read<EquipmentReviewEvent[]>(path.join(R2, "second-review/second-review-events.json"))];
  const selected = selectTerminalSecondReviewed({ assertions, trimLinks: links, reviewEvents: events });
  const assertionSubjects: EquipmentApprovalManifestSubject[] = selected.assertions.map((item) => ({ subjectType: "ASSERTION", subjectId: item.assertionId, exactVariantId: item.exactVariantId!, featureCode: item.featureCode, terminalSupersessionState: "TERMINAL_NOT_SUPERSEDED", secondReviewEventId: selected.passed.get(`ASSERTION:${item.assertionId}`)!.reviewEventId, secondReviewDisposition: "SECOND_REVIEW_PASSED", evidenceProvenanceFingerprint: fingerprint({ source: item.source, locator: item.locator, derivedArtifact: item.derivedArtifact, semanticMappingId: item.semanticMappingId }), availabilityStatus: item.availabilityStatus, standardOrOptional: item.availabilityStatus, marketApplicability: "TR", modelYearApplicability: { from: item.modelYearFrom!, to: item.modelYearTo! }, sourceIds: [item.source.sourceId], contentFingerprint: fingerprint(item) }));
  const linkSubjects: EquipmentApprovalManifestSubject[] = selected.trimLinks.map((item) => { const extended = item as EquipmentTrimVariantLink & { officialTrimName?: string; identitySourceIds?: string[]; provenanceSourceIds?: string[] }; const sourceIds = [...(extended.identitySourceIds ?? extended.provenanceSourceIds ?? [])].sort(); return { subjectType: "TRIM_LINK", subjectId: item.linkId, exactVariantId: item.exactVariantId, trimIdentity: { canonicalTrimId: item.canonicalTrimId, officialTrimName: extended.officialTrimName ?? "Speciale+" }, terminalSupersessionState: "TERMINAL_NOT_SUPERSEDED", secondReviewEventId: selected.passed.get(`TRIM_LINK:${item.linkId}`)!.reviewEventId, secondReviewDisposition: "SECOND_REVIEW_PASSED", evidenceProvenanceFingerprint: fingerprint({ sourceIds, assertionIds: item.assertionIds }), availabilityStatus: "NOT_APPLICABLE_TRIM_IDENTITY", standardOrOptional: "NOT_APPLICABLE_TRIM_IDENTITY", marketApplicability: "TR", modelYearApplicability: { from: item.modelYearFrom, to: item.modelYearTo }, sourceIds, contentFingerprint: fingerprint(item) }; });
  const subjects = [...assertionSubjects, ...linkSubjects].sort((a, b) => `${a.subjectType}|${a.subjectId}`.localeCompare(`${b.subjectType}|${b.subjectId}`));
  const payload: Omit<EquipmentApprovalManifest, "manifestChecksum"> = { manifestId: "EE-OWNER-APPROVAL-MANIFEST-001", manifestVersion: EQUIPMENT_APPROVAL_MANIFEST_VERSION, pilotId: "EE-PILOT-002", batchId: "EE-PILOT-002-BATCH-001", correctionCycleScope: ["EE-PILOT-002-CYCLE-001", "EE-PILOT-002-CYCLE-001-R2"], catalogRelease: "v0.55.2", catalogFingerprint: CATALOG_FINGERPRINT, subjectCount: subjects.length, assertionCount: assertionSubjects.length, trimLinkCount: linkSubjects.length, canonicalSerializationVersion: EQUIPMENT_APPROVAL_CANONICAL_SERIALIZATION_VERSION, generatedAt: GENERATED_AT, ownerActorId: actor.actorId, decisionAuthority: "SHADOW_AND_EXPLANATION_DISABLED", subjects };
  const manifest: EquipmentApprovalManifest = { ...payload, manifestChecksum: approvalManifestChecksum(payload) };
  const superseded = new Set([...assertions.flatMap((x) => x.supersedesAssertionId ? [`ASSERTION:${x.supersedesAssertionId}`] : []), ...links.flatMap((x) => x.supersedesTrimLinkId ? [`TRIM_LINK:${x.supersedesTrimLinkId}`] : [])]);
  const conflicts = new Set(events.filter((x) => x.toState === "CONFLICT_REVIEW_REQUIRED").map((x) => `${x.subjectType}:${x.subjectId}`));
  const passed = new Set(events.filter((x) => x.toState === "SECOND_REVIEW_PASSED").map((x) => `${x.subjectType}:${x.subjectId}`));
  const registryIssues = validateEquipmentOwnerRegistry({ actors: [actor], authorizationStatements: new Map([[actor.actorId, statement]]), collectorActorIds: new Set(["ACTOR-COLLECTOR-CODEX-CATALOG-001"]), reviewerActorIds: new Set(["ACTOR-REVIEWER-CODEX-EQUIPMENT-001"]) });
  const manifestIssues = validateEquipmentApprovalManifest({ manifest, ownerActors: [actor], expectedCatalogFingerprint: CATALOG_FINGERPRINT, terminalPassedSubjectIds: passed, supersededSubjectIds: superseded, conflictingSubjectIds: conflicts });
  if (registryIssues.length || manifestIssues.length) throw new Error(JSON.stringify({ registryIssues, manifestIssues }));
  const originalIbrida = (await read<EquipmentEvidenceAssertion[]>(path.join(BASE, "assertions.json"))).filter((x) => x.exactVariantId === "1a3cc01d-3bfa-56f3-817f-4cc77e723ef8");
  const r1Ibrida = await read<EquipmentEvidenceAssertion[]>(path.join(R1, "assertions.json"));
  const historical = { originalIbridaAssertionsExcluded: originalIbrida.length, r1IbridaAssertionsExcluded: r1Ibrida.length, historicalConflictAssertionsExcluded: 48, historicalConflictTrimLinksExcluded: 2, inconclusiveResearchRowsExcluded: 55, supersededSubjectsExcluded: superseded.size, recordsDeletedOrModified: 0, auditHashes: { originalAssertions: await shaFile(path.join(BASE, "assertions.json")), r1Assertions: await shaFile(path.join(R1, "assertions.json")), r2Assertions: await shaFile(path.join(R2, "assertions.json")), originalTrimLinks: await shaFile(path.join(BASE, "trim-links.json")), r1TrimLinks: await shaFile(path.join(R1, "trim-links.json")), r2TrimLinks: await shaFile(path.join(R2, "trim-links.json")) } };
  const byVariant = new Map<string, EquipmentApprovalManifestSubject[]>(); for (const subject of assertionSubjects) (byVariant.get(subject.exactVariantId) ?? byVariant.set(subject.exactVariantId, []).get(subject.exactVariantId)!).push(subject);
  const ownerReview = `# Equipment Owner Approval Manifest Review\n\n## Alfa Romeo Junior Elettrica 115 kW Speciale+\n\n- Exact ID: \`5a64b246-3b05-52b6-9f24-b8f52ccc2305\`\n- Pazar/model yılı: TR / MY2026\n- Önerilen onay: ${byVariant.get("5a64b246-3b05-52b6-9f24-b8f52ccc2305")!.map((x) => x.featureCode).sort().join(", ")}\n- Kaynaklar: SRC-000084; trim kimliği için SRC-000085\n- Independent review: 23/23 assertion ve trim link SECOND_REVIEW_PASSED\n- UNKNOWN kalan alan: 28 feature. UNKNOWN, NOT_AVAILABLE değildir.\n\n## Alfa Romeo Junior Ibrida 145 PS Speciale+ eDCT6\n\n- Exact ID: \`1a3cc01d-3bfa-56f3-817f-4cc77e723ef8\`\n- Pazar/model yılı: TR / MY2026\n- Önerilen onay: ${byVariant.get("1a3cc01d-3bfa-56f3-817f-4cc77e723ef8")!.map((x) => x.featureCode).sort().join(", ")}\n- Kaynaklar: SRC-000086; trim kimliği için SRC-000085\n- Independent review: 24/24 R2 assertion ve R2 trim link SECOND_REVIEW_PASSED\n- UNKNOWN kalan alan: 27 feature. Original ve R1 conflict kayıtları yalnız tarihsel audit içindir.\n\n## Availability anlamı ve sınırlar\n\nSTANDARD yalnız kanıtlanan exact varyant, Speciale+ trim, Türkiye pazarı ve MY2026 bağlamında geçerlidir. UNKNOWN, NOT_AVAILABLE değildir; kaynakta bulunmayan özellik yok sayılmaz. Bu onay stoktaki her fiziksel araçta opsiyon bulunacağını veya aracın sonradan değişmediğini kanıtlamaz. Onay yalnız manifestteki evidence ve identity kayıtlarının owner-governance aşamasına geçmesini sağlar; kaynakları ya da independent review kararını değiştirmez. Bu pilot Decision Engine'e filtreleme, sıralama, otomatik soru üretme veya kullanıcıya authoritative açıklama yapma yetkisi vermez.\n\n## Bu paket ne yapmaz?\n\nBu dosyanın ve manifestin üretilmesi approval eventi değildir. Verification materialization, production release veya active pointer değişikliği üretmez. Owner'ın manifest ID ve checksum'ı içeren ayrı açık kararı gerekir.\n`;
  await mkdir(path.join(GOVERNANCE, "attestations"), { recursive: true }); await mkdir(OUTPUT, { recursive: true });
  await writeFile(path.join(GOVERNANCE, "attestations/EQUIPMENT_OWNER_001-v1.txt"), statement); await writeFile(path.join(GOVERNANCE, "actor-registry.json"), canonicalJson({ schemaVersion: "1.0.0", actors: [actor] }));
  await writeFile(path.join(OUTPUT, "approval-manifest.json"), canonicalJson(manifest)); await writeFile(path.join(OUTPUT, "historical-audit-summary.json"), canonicalJson(historical)); await writeFile(path.join(OUTPUT, "owner-review.md"), ownerReview);
  await writeFile(path.join(OUTPUT, "package-status.json"), canonicalJson({ status: "AWAITING_EXPLICIT_OWNER_APPROVAL", approvalEventCount: 0, verificationMaterializationCount: 0, productionReleaseCreated: false, activePointerChanged: false, decisionAuthority: "SHADOW_AND_EXPLANATION_DISABLED" }));
  const names = ["approval-manifest.json", "historical-audit-summary.json", "owner-review.md", "package-status.json"]; const checksums = Object.fromEntries(await Promise.all(names.map(async (name) => [name, await shaFile(path.join(OUTPUT, name))]))); await writeFile(path.join(OUTPUT, "checksums.json"), canonicalJson(checksums));
  console.log(canonicalJson({ ownerActorId: actor.actorId, authorizationStatementHash: actor.authorizationStatementHash, manifestId: manifest.manifestId, manifestChecksum: manifest.manifestChecksum, subjects: manifest.subjectCount }));
}

void main();
