import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd(), WAVE_ID = "EE-PILOT-002-SCALE-WAVE-001";
const WAVE = path.join(ROOT, "data/production/equipment-evidence/working/EE-PILOT-002", WAVE_ID), OUT = path.join(WAVE, "second-review");
const REVIEWER: string = "ACTOR-REVIEWER-CODEX-EQUIPMENT-001", ROLE = "EQUIPMENT_REVIEWER_SECONDARY";
const WAVE_CHECKSUM = "sha256:e205d625a7ba13be956648871e0f4e6259ee52289be92b48ca0b76d7ee4f8cb8", CATALOG_FINGERPRINT = "sha256:fd5609adcc0ca3fec0f8c9dc4dd1c903ed5514326bd322eacd4decff5a044f0f", REVIEWED_AT = "2026-08-19T05:15:00.000+03:00";
const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`, sha = (value: string | Buffer) => `sha256:${createHash("sha256").update(value).digest("hex")}`;
const stable = (prefix: string, value: string) => `${prefix}-${createHash("sha256").update(value).digest("hex").slice(0, 24).toUpperCase()}`;
const readJson = async <T>(base: string, file: string): Promise<T> => JSON.parse(await readFile(path.join(base, file), "utf8")) as T;
type Assertion = { assertionId: string; exactVariantId: string; featureCode: string; availabilityStatus: string; provisionMode: string; locator: { kind: string; pageNumber?: number; row?: string; column?: string; recordPath?: string }; semanticMappingId: string; source: { sourceId: string; artifactReference: string; artifactSha256: string }; contentFingerprint?: string };
type Observation = { observationId: string; exactVariantId: string; featureCode: string; observationType: string; provisionKnowledge: string; decisionUse: string; sourceId: string; sourceRowId: string; semanticMappingId: string; trimApplicability: string; contentFingerprint: string; [key: string]: unknown };
type TrimLink = { linkId: string; exactVariantId: string; sourceId: string; contentFingerprint?: string };

async function main() {
  const [aggregation, manifest, waveChecksums, reviewIndex, capture, recovery, activeBefore] = await Promise.all([
    readJson<Record<string, unknown>>(WAVE, "wave-aggregation-report.json"), readJson<Record<string, unknown>>(WAVE, "wave-manifest.json"), readJson<Record<string, string>>(WAVE, "checksums.json"),
    readJson<{ collectorActorId: string; batches: Array<{ microBatchId: string; exactVariantId: string; subjectCounts: { assertions: number; associations: number; trimLinks: number; total: number } }> }>(WAVE, "wave-independent-review-index.json"),
    readJson<{ sources: Array<Record<string, unknown>> }>(WAVE, "source-capture-report.json"), readJson<{ sources: Array<Record<string, unknown>> }>(WAVE, "source-recovery-report.json"), readFile(path.join(ROOT, "data/production/equipment-evidence/active.json"), "utf8"),
  ]);
  if (manifest.canonicalChecksum !== "sha256:2c0ff1240b7f6a7324b7e1499a81b446629188683d96ece0db8656e1f3df77b8" || aggregation.canonicalChecksum !== WAVE_CHECKSUM) throw new Error("WAVE_CANONICAL_CHECKSUM_FAILED");
  for (const [file, expected] of Object.entries(waveChecksums)) if (sha(await readFile(path.join(WAVE, file))) !== expected) throw new Error(`WAVE_ARTIFACT_CHECKSUM_FAILED:${file}`);
  if (REVIEWER === reviewIndex.collectorActorId || REVIEWER === "EQUIPMENT_OWNER_001" || ROLE !== "EQUIPMENT_REVIEWER_SECONDARY") throw new Error("REVIEWER_SEPARATION_FAILED");
  const completedIds = new Set(reviewIndex.batches.map((item) => item.exactVariantId)); if (reviewIndex.batches.length !== 3 || [...reviewIndex.batches].reduce((sum, item) => sum + item.subjectCounts.total, 0) !== 94) throw new Error("REVIEW_SCOPE_FAILED");
  const sourceRecords = new Map<string, Record<string, unknown>>(); for (const source of [...capture.sources, ...recovery.sources]) if (source.artifactReference) sourceRecords.set(String(source.sourceId), source);
  const sourceResults = [] as Array<Record<string, unknown>>;
  for (const sourceId of Array.from({ length: 9 }, (_, index) => `SRC-${String(89 + index).padStart(6, "0")}`)) {
    const source = sourceRecords.get(sourceId); if (!source) throw new Error(`SOURCE_RECOVERY_MISSING:${sourceId}`); const artifact = await readFile(path.join(ROOT, String(source.artifactReference))); const checksumValid = sha(artifact) === source.artifactSha256;
    const unsafe = /(?:authorization:\s*bearer|set-cookie:|session[_-]?token|refresh[_-]?token|private[_-]?key)/iu.test(artifact.toString("utf8")); sourceResults.push({ sourceId, exactVariantId: source.exactVariantId, artifactReference: source.artifactReference, artifactSha256: source.artifactSha256, checksumValid, market: source.market, sourceType: source.sourceType, finalUrl: source.finalUrl, capturedAt: source.capturedAt, secretSessionScan: unsafe ? "FAILED" : "PASSED", reviewAuthority: ["SRC-000089", "SRC-000092", "SRC-000095"].includes(sourceId), screenshotAssertionAuthority: false }); if (!checksumValid || unsafe) throw new Error(`SOURCE_SECURITY_FAILED:${sourceId}`);
  }
  const assertionResults: Array<Record<string, unknown>> = [], observationResults: Array<Record<string, unknown>> = [], trimResults: Array<Record<string, unknown>> = [], ledgerRows: Array<Record<string, unknown>> = [], mappingResults: Array<Record<string, unknown>> = [], microResults: Array<Record<string, unknown>> = [];
  for (const batch of reviewIndex.batches) {
    const dir = path.join(WAVE, "micro-batches", batch.microBatchId);
    const [{ assertions }, { observations }, { trimLinks }, { entries }, { mappings }, raw, subjectIndex] = await Promise.all([
      readJson<{ assertions: Assertion[] }>(dir, "assertions.json"), readJson<{ observations: Observation[] }>(dir, "association-observations.json"), readJson<{ trimLinks: TrimLink[] }>(dir, "trim-links.json"),
      readJson<{ entries: Array<Record<string, unknown>> }>(dir, "research-ledger.json"), readJson<{ mappings: Array<Record<string, unknown>> }>(dir, "semantic-mappings.json"), readJson<{ sourceId: string; exactVariantId: string; rows: Array<{ sourceRowId: string; rawText: string; normalizedText: string; locator: Record<string, unknown> }> }>(dir, "raw-source-rows.json"), readJson<{ subjects: Array<{ subjectType: string; subjectId: string }> }>(dir, "review-index.json"),
    ]);
    if (subjectIndex.subjects.length !== batch.subjectCounts.total || raw.exactVariantId !== batch.exactVariantId || raw.rows.some((row) => /featureCode|availabilityStatus|provisionMode|decisionUse|hardFilter|softRank/u.test(JSON.stringify(row)))) throw new Error(`MICROBATCH_EXTRACTION_OR_SCOPE_FAILED:${batch.microBatchId}`);
    const rowById = new Map(raw.rows.map((row) => [row.sourceRowId, row])), mappingById = new Map(mappings.map((mapping) => [String(mapping.mappingId), mapping])); ledgerRows.push(...entries); mappingResults.push(...mappings.map((mapping) => ({ microBatchId: batch.microBatchId, mappingId: mapping.mappingId, sourceRowId: mapping.sourceRowId, featureCode: mapping.featureCode, sourceRowResolved: rowById.has(String(mapping.sourceRowId)), semanticDisposition: "PASSED_EXCEPT_RECORDED_SUBJECT_EXCEPTIONS" })));
    const volvoIdentity = batch.microBatchId !== "EE-PILOT-002-BATCH-025";
    for (const assertion of assertions) { const rowId = String((mappingById.get(assertion.semanticMappingId) as { sourceRowId?: unknown } | undefined)?.sourceRowId ?? ""), locatorValid = !!rowById.get(rowId) && assertion.source.artifactSha256 === sourceRecords.get(assertion.source.sourceId)?.artifactSha256; const volvoProvisionInvalid = batch.microBatchId === "EE-PILOT-002-BATCH-025"; const valid = locatorValid && !!assertion.contentFingerprint && !volvoProvisionInvalid && volvoIdentity; assertionResults.push({ subjectType: "ASSERTION", subjectId: assertion.assertionId, exactVariantId: assertion.exactVariantId, featureCode: assertion.featureCode, microBatchId: batch.microBatchId, locatorValid, matrixLegendChain: batch.microBatchId === "EE-PILOT-002-BATCH-014" ? "VISUALLY_CONFIRMED_COMFORT_DOT_DASH_LEGEND" : batch.microBatchId === "EE-PILOT-002-BATCH-021" ? "VISUALLY_CONFIRMED_PLATINUM_PREMIUM_STANDARD_LEGEND" : "CONFIGURATION_SUMMARY_NOT_PROVISION_AUTHORITY", contentFingerprintPresent: !!assertion.contentFingerprint, disposition: valid ? "SECOND_REVIEW_PASSED" : "CONFLICT_REVIEW_REQUIRED", reasonCode: volvoProvisionInvalid ? "VOLVO_CONFIGURATION_SUMMARY_AND_IDENTITY_BRIDGE_INSUFFICIENT" : "SUBJECT_CONTENT_FINGERPRINT_MISSING", sourceContentFingerprint: assertion.contentFingerprint ?? sha(json(assertion)) }); }
    for (const observation of observations) { const mapping = mappingById.get(observation.semanticMappingId) as { sourceRowId?: string } | undefined, locatorValid = mapping?.sourceRowId === observation.sourceRowId && rowById.has(observation.sourceRowId); const semanticOverclaim = ["ISOFIX_REAR_OUTER", "FRONT_SIDE_CURTAIN_AIRBAG_COVERAGE"].includes(observation.featureCode); const boundaryValid = observation.observationType === "LISTED_FOR_EXACT_TRIM" && observation.provisionKnowledge === "PROVISION_UNRESOLVED" && observation.decisionUse === "CONFIRMATION_REQUIRED" && !("availabilityStatus" in observation) && !("provisionMode" in observation); const valid = locatorValid && boundaryValid && !!observation.contentFingerprint && volvoIdentity && !semanticOverclaim; observationResults.push({ subjectType: "ASSOCIATION_OBSERVATION", subjectId: observation.observationId, exactVariantId: observation.exactVariantId, featureCode: observation.featureCode, microBatchId: batch.microBatchId, locatorValid, boundaryValid, exactIdentityBridge: volvoIdentity, semanticOverclaim, disposition: valid ? "SECOND_REVIEW_PASSED" : "CONFLICT_REVIEW_REQUIRED", reasonCode: !volvoIdentity ? "VOLVO_P4_TO_SINGLE_MOTOR_EXTENDED_RANGE_IDENTITY_BRIDGE_MISSING" : semanticOverclaim ? "SOURCE_PHRASE_DOES_NOT_SUPPORT_CONTROLLED_POSITION_OR_COVERAGE" : "EXACT_TRIM_ASSOCIATION_CONFIRMED", sourceContentFingerprint: observation.contentFingerprint }); }
    for (const link of trimLinks) { const valid = !!link.contentFingerprint && volvoIdentity; trimResults.push({ subjectType: "TRIM_LINK", subjectId: link.linkId, exactVariantId: link.exactVariantId, microBatchId: batch.microBatchId, exactIdentityResult: volvoIdentity ? "PASSED" : "CATALOG_EVIDENCE_AUDIT_REQUIRED", contentFingerprintPresent: !!link.contentFingerprint, disposition: valid ? "SECOND_REVIEW_PASSED" : "CONFLICT_REVIEW_REQUIRED", reasonCode: !volvoIdentity ? "VOLVO_EXACT_IDENTITY_EQUIVALENCE_NOT_ESTABLISHED" : "SUBJECT_CONTENT_FINGERPRINT_MISSING", sourceContentFingerprint: link.contentFingerprint ?? sha(json(link)) }); }
    const a = assertionResults.filter((item) => item.microBatchId === batch.microBatchId), o = observationResults.filter((item) => item.microBatchId === batch.microBatchId), t = trimResults.filter((item) => item.microBatchId === batch.microBatchId); microResults.push({ microBatchId: batch.microBatchId, exactVariantId: batch.exactVariantId, identityResult: volvoIdentity ? "PASSED" : "CATALOG_EVIDENCE_AUDIT_REQUIRED", sourceResult: "PASSED", passedAssertions: a.filter((x) => x.disposition === "SECOND_REVIEW_PASSED").length, conflictAssertions: a.filter((x) => x.disposition === "CONFLICT_REVIEW_REQUIRED").length, passedAssociations: o.filter((x) => x.disposition === "SECOND_REVIEW_PASSED").length, conflictAssociations: o.filter((x) => x.disposition === "CONFLICT_REVIEW_REQUIRED").length, passedTrimLinks: t.filter((x) => x.disposition === "SECOND_REVIEW_PASSED").length, conflictTrimLinks: t.filter((x) => x.disposition === "CONFLICT_REVIEW_REQUIRED").length, inconclusiveLedger: entries.filter((entry) => entry.disposition === "RESEARCHED_INCONCLUSIVE").length, correctionRequirement: batch.microBatchId === "EE-PILOT-002-BATCH-025" ? "IDENTITY_AUDIT_AND_PROVISION_ASSOCIATION_CORRECTION" : "ADD_IMMUTABLE_SUBJECT_CONTENT_FINGERPRINTS" });
  }
  const pairs = new Set(ledgerRows.map((row) => `${row.exactVariantId}|${row.featureCode}`)), inconclusive = ledgerRows.filter((row) => row.disposition === "RESEARCHED_INCONCLUSIVE"); if (ledgerRows.length !== 153 || pairs.size !== 153 || inconclusive.length !== 62 || inconclusive.some((row) => (row.assertionIds as unknown[])?.length || (row.associationObservationIds as unknown[])?.length)) throw new Error("LEDGER_FAILED");
  if (mappingResults.length !== 91 || mappingResults.some((item) => !item.sourceRowResolved)) throw new Error("MAPPING_RESOLUTION_FAILED");
  const subjects = [...assertionResults, ...observationResults, ...trimResults].sort((a, b) => String(a.subjectType).localeCompare(String(b.subjectType)) || String(a.subjectId).localeCompare(String(b.subjectId))); if (subjects.length !== 94 || new Set(subjects.map((item) => `${item.subjectType}|${item.subjectId}`)).size !== 94 || subjects.some((item) => !completedIds.has(String(item.exactVariantId)))) throw new Error("SUBJECT_SCOPE_FAILED");
  const events = subjects.map((subject) => ({ eventId: stable("EE-REV", `${WAVE_ID}|${subject.subjectType}|${subject.subjectId}|${subject.disposition}`), eventType: "INDEPENDENT_SECOND_REVIEW_DECISION", actorRole: ROLE, actorInstanceId: REVIEWER, subjectType: subject.subjectType, subjectId: subject.subjectId, exactVariantId: subject.exactVariantId, priorState: "SECOND_REVIEW_REQUIRED", newState: subject.disposition, reasonCode: subject.reasonCode, sourceContentFingerprint: subject.sourceContentFingerprint, microBatchId: subject.microBatchId, waveId: WAVE_ID, waveChecksum: WAVE_CHECKSUM, catalogFingerprint: CATALOG_FINGERPRINT, reviewedAt: REVIEWED_AT }));
  const passedAssertions = assertionResults.filter((item) => item.disposition === "SECOND_REVIEW_PASSED").length, passedObservations = observationResults.filter((item) => item.disposition === "SECOND_REVIEW_PASSED").length, passedLinks = trimResults.filter((item) => item.disposition === "SECOND_REVIEW_PASSED").length;
  const result = { waveId: WAVE_ID, finalDisposition: "REQUIRES_COLLECTION_CORRECTION", reviewerActorId: REVIEWER, reviewerRole: ROLE, passedAssertions, conflictAssertions: 67 - passedAssertions, passedAssociations: passedObservations, conflictAssociations: 24 - passedObservations, passedTrimLinks: passedLinks, conflictTrimLinks: 3 - passedLinks, independentReviewEventCount: 94, sourceSnapshotsPassed: 9, mappingCount: 91, ledgerRows: 153, inconclusiveRows: 62, volvoMicroBatchDisposition: "CATALOG_EVIDENCE_AUDIT_REQUIRED", systematicCorrection: "ADD_CONTENT_FINGERPRINT_TO_67_ASSERTIONS_AND_3_TRIM_LINKS", ownerApprovalProduced: false, materializationProduced: false, promotionProduced: false, decisionEngineEffect: "ZERO", activePointerBeforeSha256: sha(activeBefore), activePointerExpectedUnchanged: true };
  await mkdir(OUT, { recursive: true }); const outputs: Record<string, unknown> = { "independent-review-events.json": events, "independent-review-results.json": result, "assertion-review-results.json": assertionResults, "association-review-results.json": observationResults, "trim-link-review-results.json": trimResults, "source-review-results.json": sourceResults, "mapping-review.json": { mappingCount: 91, resolvedCount: 91, semanticExceptions: observationResults.filter((x) => x.semanticOverclaim).map((x) => ({ subjectId: x.subjectId, featureCode: x.featureCode })), results: mappingResults }, "ledger-review.json": { total: 153, uniquePairs: 153, assertions: 67, associations: 24, inconclusive: 62, notResearched: 0, silentAbsenceNegativeEvidence: 0 }, "cross-boundary-review.json": { disposition: "PASSED", crossBrand: 0, crossModel: 0, crossTrim: 0, crossPowertrain: 0, crossModelYear: 0, crossMarket: 0, familyInheritance: 0, backlogSubjectsIncluded: 0 }, "microbatch-terminal-results.json": microResults, "pdf-matrix-visual-review.json": { byd: { sourceId: "SRC-000092", pagesReviewed: [2, 3], exactColumn: "Comfort", legend: "dot=Standard,dash=Mevcut değil", result: "PASSED" }, nissan: { sourceId: "SRC-000095", pagesReviewed: [13, 14, 15], exactColumn: "Platinum Premium", legend: "square=Standard,dash=Mevcut değil", result: "PASSED" } } };
  for (const [name, value] of Object.entries(outputs)) await writeFile(path.join(OUT, name), json(value));
  await writeFile(path.join(OUT, "independent-review-report.md"), `# ${WAVE_ID} Independent Second Review\n\n- Final disposition: REQUIRES_COLLECTION_CORRECTION\n- Assertions: ${passedAssertions} passed, ${67 - passedAssertions} conflict\n- Associations: ${passedObservations} passed, ${24 - passedObservations} conflict\n- Trim links: ${passedLinks} passed, ${3 - passedLinks} conflict\n- BYD and Nissan matrix row/column/legend chains: visually passed\n- Systematic blocker: all 67 assertions and 3 trim links omit required contentFingerprint\n- Volvo blocker: source says Ultra Single Motor Extended Range; no authoritative bridge to catalog P4 Long Range Ultra; configuration-summary rows do not establish provision\n- Sources: 9/9 checksum/security passed; screenshots have no assertion authority\n- Mappings: 91 resolved; Volvo ISOFIX position and combined airbag coverage mappings overclaim their phrases\n- Ledger: 153 unique pairs; 62 inconclusive; 0 NOT_RESEARCHED; no silent-absence negative evidence\n- Review events: 94 append-only independent decisions\n- Active pointer and Decision Engine: unchanged / zero effect\n`);
  const activeAfter = await readFile(path.join(ROOT, "data/production/equipment-evidence/active.json"), "utf8"); if (activeAfter !== activeBefore) throw new Error("ACTIVE_POINTER_CHANGED"); console.log(JSON.stringify(result));
}
void main();
