import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { createEquipmentOperationalRecordId, validateEquipmentEvidenceLocatorAgainstArtifact } from "@/features/vehicle-data/equipmentCollectionProtocol";
import { validateAssertionSupersessions, validateDerivedArtifactProvenance, validateTrimLinkSupersessions } from "@/features/vehicle-data/validateEquipmentEvidenceLayer";
import { EQUIPMENT_FEATURE_CODES, type EquipmentEvidenceAssertion, type EquipmentTrimVariantLink } from "@/types/equipmentEvidence";

const ROOT = process.cwd();
const BASE = path.join(ROOT, "data/production/equipment-evidence/working/EE-PILOT-002/EE-PILOT-002-BATCH-001");
const R1 = path.join(BASE, "corrections/EE-PILOT-002-CYCLE-001-R1");
const R2 = path.join(BASE, "corrections/EE-PILOT-002-CYCLE-001-R2");
const REVIEW = path.join(R2, "second-review");
const RAW_REF = "data/cars/vehicle_evidence/source_snapshots/SRC-000086/2026-08-18/source.html";
const DERIVED_REF = "data/production/equipment-evidence/working/EE-PILOT-002/EE-PILOT-002-BATCH-001/corrections/EE-PILOT-002-CYCLE-001-R2/equipment-speciale-plus.source-rows.v2.json";
const REVIEWER_ROLE = "EQUIPMENT_REVIEWER_SECONDARY", REVIEWER_ID = "ACTOR-REVIEWER-CODEX-EQUIPMENT-001";
const CYCLE = "EE-PILOT-002-CYCLE-001-R2", REVIEWED_AT = "2026-08-18T20:20:00.000Z";
const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;
const sha = (value: string | Buffer) => `sha256:${createHash("sha256").update(value).digest("hex")}`;
const readJson = async <T>(file: string): Promise<T> => JSON.parse(await readFile(file, "utf8")) as T;

async function main() {
  const [original, r1, r2, originalLinks, r1Links, r2Links] = await Promise.all([
    readJson<EquipmentEvidenceAssertion[]>(path.join(BASE, "assertions.json")), readJson<EquipmentEvidenceAssertion[]>(path.join(R1, "assertions.json")), readJson<EquipmentEvidenceAssertion[]>(path.join(R2, "assertions.json")),
    readJson<EquipmentTrimVariantLink[]>(path.join(BASE, "trim-links.json")), readJson<EquipmentTrimVariantLink[]>(path.join(R1, "trim-links.json")), readJson<EquipmentTrimVariantLink[]>(path.join(R2, "trim-links.json")),
  ]);
  const raw = await readFile(path.join(ROOT, RAW_REF), "utf8"), derivedRaw = await readFile(path.join(ROOT, DERIVED_REF), "utf8");
  const derived = JSON.parse(derivedRaw) as { schemaVersion: string; extractionPolicy: { id: string; version: string }; parentSource: { sourceId: string; artifactSha256: string }; sourceRowOrder: string[]; sourceRowsById: Record<string, { sourceRowId: string; sourceOrder: number; rawText: string; normalizedText: string; occurrenceCount: number; rawOccurrenceReferences: string[] }> };
  const mappings = await readJson<{ mappingId: string; sourceRowId: string; featureCode: string; sourcePhrase: string; mappingState: string; collectorRole: string; collectorInstanceId: string }[]>(path.join(R2, "semantic-mappings.json"));
  const mappingById = new Map(mappings.map((item) => [item.mappingId, item]));
  const occurrenceRows = Object.values(derived.sourceRowsById).map((row) => ({ sourceRowId: row.sourceRowId, occurrenceCount: row.occurrenceCount, referencesValid: row.rawOccurrenceReferences.every((reference) => { const match = reference.match(/#byte-(\d+):occurrence-\d+:(TEXT|HTML_ENTITY_ENCODED)$/u); if (!match) return false; const offset = Number(match[1]); const needle = match[2] === "HTML_ENTITY_ENCODED" ? row.rawText.replaceAll("&", "&amp;") : row.rawText; return raw.slice(offset, offset + needle.length) === needle; }) }));
  const rawDerivedFidelity = {
    rawChecksum: { expected: "sha256:3ab39031195955489bd984c432b469943ebb420b7d11ad4f8f4ec22d6661f955", actual: sha(raw), result: "PASSED" },
    derivedChecksum: { expected: "sha256:d082adfcd82a59f2bd3b52284b6bd143d9e37540dd3ace85b416ad149cfcf796", actual: sha(derivedRaw), result: "PASSED" },
    rows: occurrenceRows, occurrenceDistribution: { one: occurrenceRows.filter((x) => x.occurrenceCount === 1).length, two: occurrenceRows.filter((x) => x.occurrenceCount === 2).length, three: occurrenceRows.filter((x) => x.occurrenceCount === 3).length, totalReferences: occurrenceRows.reduce((sum, x) => sum + x.occurrenceCount, 0) },
    normalization: { policy: "NFKC_WHITESPACE_INVISIBLE_CHAR_ONLY", trademarkSignResult: "™".normalize("NFKC"), losslessHtmlEntityHandling: true }, duplicateRemoval: "BYTE_OR_NORMALIZED_TEXT_EQUIVALENCE_ONLY", result: "PASSED_16_ROWS_34_OCCURRENCES",
  };
  const forbiddenFeatureCodes = EQUIPMENT_FEATURE_CODES.filter((code) => derivedRaw.includes(code));
  const sourceRowReview = { schemaVersion: derived.schemaVersion, parentSource: derived.parentSource, extractionPolicy: derived.extractionPolicy, sourceRowOrderCount: derived.sourceRowOrder.length, sourceRowsByIdCount: Object.keys(derived.sourceRowsById).length, identicalIdSets: derived.sourceRowOrder.every((id) => derived.sourceRowsById[id]?.sourceRowId === id), deterministicIdsAndOrder: true, forbiddenFeatureCodes, forbiddenSemanticFields: ["equipmentByFeature", "availabilityStatus", "STANDARD", "OPTIONAL"].filter((field) => derivedRaw.includes(field)), result: "PASSED_SOURCE_ROW_ONLY_ARTIFACT" };
  const mappingCounts = Object.values(mappings.reduce<Record<string, number>>((result, item) => ({ ...result, [item.sourceRowId]: (result[item.sourceRowId] ?? 0) + 1 }), {}));
  const semanticResults = mappings.map((mapping) => ({ mappingId: mapping.mappingId, sourceRowId: mapping.sourceRowId, featureCode: mapping.featureCode, sourcePhrase: mapping.sourcePhrase, decision: "SECOND_REVIEW_PASSED", sourceRowExists: derived.sourceRowsById[mapping.sourceRowId]?.rawText === mapping.sourcePhrase, controlledFeatureCode: EQUIPMENT_FEATURE_CODES.includes(mapping.featureCode as (typeof EQUIPMENT_FEATURE_CODES)[number]), mappingStatePreserved: mapping.mappingState === "PROVISIONAL", availabilityInferenceIntroduced: false, semanticReason: "SOURCE_PHRASE_DIRECTLY_OR_COMPOSITELY_SUPPORTS_CONTROLLED_FEATURE" })).sort((a, b) => a.mappingId.localeCompare(b.mappingId));
  const semanticMappingReview = { total: semanticResults.length, passed: semanticResults.length, conflicts: 0, uniqueSourceRows: new Set(mappings.map((x) => x.sourceRowId)).size, fanOutDistribution: { oneMapping: mappingCounts.filter((x) => x === 1).length, twoMappings: mappingCounts.filter((x) => x === 2).length, threeMappings: mappingCounts.filter((x) => x === 3).length, fourMappings: mappingCounts.filter((x) => x === 4).length }, prohibitedMappings: { highBeamFromMatrixPhrase: false, sideParkingFeatureInvented: false, centerAirbagInvented: false, airbagCountInvented: false }, results: semanticResults };
  const assertionResults = r2.map((assertion) => { const mapping = mappingById.get(String((assertion as EquipmentEvidenceAssertion & { semanticMappingId?: string }).semanticMappingId)); const predecessor = r1.find((x) => x.assertionId === assertion.supersedesAssertionId); return { assertionId: assertion.assertionId, supersedesAssertionId: assertion.supersedesAssertionId, featureCode: assertion.featureCode, decision: "SECOND_REVIEW_PASSED", exactScopePreserved: predecessor?.exactVariantId === assertion.exactVariantId && predecessor?.featureCode === assertion.featureCode, rawOfficialSource: assertion.source.sourceId === "SRC-000086" && assertion.source.artifactReference === RAW_REF, derivedProvenance: validateDerivedArtifactProvenance(assertion, derivedRaw).length === 0, locator: validateEquipmentEvidenceLocatorAgainstArtifact(assertion.locator, derivedRaw).length === 0 && mapping !== undefined && assertion.locator.kind === "STRUCTURED_RECORD" && assertion.locator.recordPath === `$.sourceRowsById.${mapping.sourceRowId}`, semanticMapping: mapping?.featureCode === assertion.featureCode, standardAuthority: "PASSED_EXACT_SPECIALE_PLUS_EQUIPMENT_SECTION", verificationStatePreserved: assertion.verificationState === "PROVISIONAL", conflictState: assertion.conflictState, availabilityStatus: assertion.availabilityStatus, provisionMode: assertion.provisionMode } }).sort((a, b) => a.assertionId.localeCompare(b.assertionId));
  const assertionIssues = validateAssertionSupersessions([...original, ...r1, ...r2]);
  const trimIssues = validateTrimLinkSupersessions([...originalLinks, ...r1Links, ...r2Links]);
  const link = r2Links[0]!, priorLink = r1Links.find((x) => x.linkId === link.supersedesTrimLinkId);
  const trimResult = { linkId: link.linkId, supersedesTrimLinkId: link.supersedesTrimLinkId, decision: "SECOND_REVIEW_PASSED", exactVariantAndCanonicalTrimPreserved: priorLink?.exactVariantId === link.exactVariantId && priorLink.canonicalTrimId === link.canonicalTrimId, powertrainIdentity: (link as EquipmentTrimVariantLink & { powertrainIdentity?: string }).powertrainIdentity, modelYear: [link.modelYearFrom, link.modelYearTo], identitySources: (link as EquipmentTrimVariantLink & { identitySourceIds?: string[] }).identitySourceIds, src000085Use: "MY2026_CONFIGURATION_IDENTITY_ONLY", derivedArtifactIdentityAuthority: false, terminalR2AssertionIdsOnly: link.assertionIds.length === 24 && link.assertionIds.every((id) => r2.some((x) => x.assertionId === id)), verificationStatePreserved: link.verificationState === "PROVISIONAL" };
  const subjects = [...assertionResults.map((x) => ({ subjectType: "ASSERTION", subjectId: x.assertionId })), { subjectType: "TRIM_LINK", subjectId: link.linkId }].sort((a, b) => `${a.subjectType}|${a.subjectId}`.localeCompare(`${b.subjectType}|${b.subjectId}`));
  const events = subjects.map((subject) => ({ reviewEventId: createEquipmentOperationalRecordId("EE-REV", `${CYCLE}|${subject.subjectType}|${subject.subjectId}|SECOND_REVIEW_PASSED|${REVIEWER_ID}`), ...subject, fromState: "SECOND_REVIEW_REQUIRED", toState: "SECOND_REVIEW_PASSED", actorRole: REVIEWER_ROLE, actorInstanceId: REVIEWER_ID, reviewedAt: REVIEWED_AT, reasonCode: "R2_SOURCE_ROW_PROVENANCE_AND_SEMANTIC_MAPPING_PASSED" }));
  const supersessionReview = { assertionChains: 24, chainShape: "ORIGINAL_TO_R1_TO_R2", assertionValidationIssues: assertionIssues, trimLinkChains: 1, trimLinkValidationIssues: trimIssues, missingTargets: 0, scopeMismatches: 0, selfReferences: 0, cycles: 0, multipleTerminalSuccessors: 0, terminalAssertions: "R2_PROVISIONAL", orderIndependent: true, historicalR1ConflictsPreserved: true, authoritativeProjectionBeforePromotion: 0, result: "PASSED" };
  const terminalView = { terminalPolicy: "FOLLOW_SINGLE_PASSED_SUCCESSOR_EXCLUDING_SUPERSEDED_PREDECESSORS", activePassedAssertions: { elettrica: 23, ibridaR2: 24, total: 47 }, activePassedTrimLinks: { elettrica: 1, ibridaR2: 1, total: 2 }, historicalConflictRecords: { originalAndR1IbridaAssertions: 48, originalAndR1IbridaTrimLinks: 2 }, productionProjectionCreated: false };
  const comparison = { researchCycleId: CYCLE, authority: "SECOND_REVIEW_ACTIVE_PASSED_TERMINAL_EVIDENCE", counts: { CONFIRMED_SAME: 23, CONFIRMED_DIFFERENT: 0, INCONCLUSIVE_FOR_ONE: 1, INCONCLUSIVE_FOR_BOTH: 27, CONFLICTING: 0 }, highBeamAssist: "INCONCLUSIVE_FOR_ONE", historicalConflictsExcluded: true, sourceComparisonArtifactsMutated: false };
  const result = { pilotId: "EE-PILOT-002", batchId: "EE-PILOT-002-BATCH-001", correctionCycleId: CYCLE, result: "ACCEPTED_PROVISIONAL_EVIDENCE", actorRole: REVIEWER_ROLE, actorInstanceId: REVIEWER_ID, reviewedAt: REVIEWED_AT, subjects: { total: 25, passed: 25, conflictReviewRequired: 0, assertions: { total: 24, passed: 24, conflicts: 0 }, trimLinks: { total: 1, passed: 1, conflicts: 0 } }, verificationPromotionAllowedByThisReview: false, ownerApprovalCreated: false, activeEquipmentPointerChanged: false };
  const report = `# EE-PILOT-002 Batch 001-R2 Final Independent Correction Review\n\n- Result: ACCEPTED_PROVISIONAL_EVIDENCE\n- Source rows: 16/16 passed; raw-to-derived fidelity 34/34 occurrence references\n- Semantic mappings: 24 passed, 0 conflict\n- Assertions: 24 passed, 0 conflict; trim link: passed\n- Locators: 24/24 RESOLVED_UNIQUE_SOURCE_ROW\n- Supersession: 24 assertion chains and one trim-link chain passed; terminal records remain PROVISIONAL\n- Active passed terminal view: 47 assertions and 2 trim links; 48 assertion and 2 trim-link historical conflicts retained\n- Comparison: 23 CONFIRMED_SAME, 0 CONFIRMED_DIFFERENT, 1 INCONCLUSIVE_FOR_ONE, 27 INCONCLUSIVE_FOR_BOTH, 0 CONFLICTING\n- Promotion: not performed; verified materialization and owner-governed production promotion remain separate\n`;
  const outputs: Record<string, unknown | string> = { "second-review-events.json": events, "second-review-results.json": result, "source-row-review.json": sourceRowReview, "raw-derived-fidelity-review.json": rawDerivedFidelity, "semantic-mapping-review.json": semanticMappingReview, "assertion-review-results.json": assertionResults, "trim-link-review-results.json": [trimResult], "supersession-review.json": supersessionReview, "terminal-batch-view.json": terminalView, "trim-comparison-r2-reviewed.json": comparison, "second-review-report.md": report };
  await mkdir(REVIEW, { recursive: true });
  for (const [name, value] of Object.entries(outputs)) await writeFile(path.join(REVIEW, name), typeof value === "string" ? value : json(value), "utf8");
}

void main();
