import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { canonicalJson } from "../features/catalog-factory/canonical";
import { ACCEPTED_DRILLS, buildCordlessDrillWaveInput, CORDLESS_DRILL_WAVE_ID } from "../features/catalog-factory/cordlessDrillWave";
import { runCatalogFactory, type CheckpointStore } from "../features/catalog-factory/pipeline";
import type { FactoryCheckpoint } from "../features/catalog-factory/contracts";

async function main(){ const directory=path.join(process.cwd(),"outputs/cordless-drill-real-wave-01"); const checkpointFile=path.join(directory,"checkpoint.json"); const store:CheckpointStore={async load(inputDigest){try{const row=JSON.parse(await readFile(checkpointFile,"utf8")) as FactoryCheckpoint;return row.inputDigest===inputDigest?row:undefined}catch{return undefined}},async save(value){await mkdir(directory,{recursive:true});await writeFile(checkpointFile,`${canonicalJson(value)}\n`)}}; const input=buildCordlessDrillWaveInput(); const result=await runCatalogFactory(input,{checkpointStore:store,concurrency:4,now:"2026-09-06T19:00:00.000Z"}); const accepted=new Set(input.identities.flatMap(row=>row.outcome==="EXACT"&&row.exactProductId?[row.exactProductId]:[])).size; const summary={schemaVersion:"cordless-drill-wave-summary/v1",workUnitId:CORDLESS_DRILL_WAVE_ID,status:"OWNER_REVIEW_CANDIDATE_NOT_ACTIVE",counts:{observed:input.observations.length,accepted,rejected:input.identities.filter(row=>row.outcome==="REJECTED").length,unknown:input.identities.filter(row=>row.outcome==="UNKNOWN").length},brands:[...new Set(ACCEPTED_DRILLS.map(row=>row.brand))].sort(),category:"CORDLESS_DRILL",factoryDigest:result.digest,ingestionDigest:input.ingestion.manifest.candidateDigest,readiness:result.gates,activation:result.activationPlan}; await writeFile(path.join(directory,"candidate.json"),`${canonicalJson(result)}\n`);await writeFile(path.join(directory,"summary.json"),`${canonicalJson(summary)}\n`);console.log(result.digest); }
void main();
