import assert from "node:assert/strict";
import { createHash, randomBytes } from "node:crypto";

import { getOpenAIClient } from "../lib/openai";
import { createCarsDecisionV2ProductionComposition } from "../features/decision/v2/composition/production.server";
import { InMemoryGovernedOfferStore } from "../features/decision/v2/offer/store";
import { createHmacOfferSigner } from "../features/decision/v2/offer/signer.server";
import { InMemoryV2ConversationStore } from "../features/decision/v2/orchestrator/store";
import { runCarsDecisionTurnV2 } from "../features/decision/v2/orchestrator/runCarsDecisionTurnV2";
import { createOpenAIStructuredProviderTransport, readCarsDecisionV2ProviderConfig } from "../features/decision/v2/provider/openaiTransport.server";
import { createStructuredProviderAdapters } from "../features/decision/v2/provider/structuredProvider";
import { assertSmoke, createMutableSmokeClock, runBoundedSmoke, writeJsonLine, type SmokePhase } from "./cars-decision-v2-smoke-lifecycle";

type Trace = Readonly<Record<string, unknown>>;

export async function main() {
  if (!process.env.OPENAI_API_KEY) throw new Error("OPENAI_API_KEY_REQUIRED");
  const config = readCarsDecisionV2ProviderConfig(process.env);
  const adapters = createStructuredProviderAdapters({ transport: createOpenAIStructuredProviderTransport(getOpenAIClient(), config), timeoutMs: config.timeoutMs });
  const runId = `manual-repair-${randomBytes(5).toString("hex")}`;
  async function journey(name: string, messages: readonly string[], context: { setPhase(phase: SmokePhase, turn?: number): void }, consentAt?: number) {
    const conversationId = `${runId}-${name}`; const conversationHash = createHash("sha256").update(conversationId).digest("hex").slice(0, 16);
    const store = new InMemoryV2ConversationStore(); const offerStore = new InMemoryGovernedOfferStore(); const traces: Trace[] = []; const clock = createMutableSmokeClock("2026-08-19T00:00:00.000Z"); const signer = createHmacOfferSigner({ secret: randomBytes(48).toString("base64url"), now: clock.now }); let activeTurnIndex = -1;
    const composition = createCarsDecisionV2ProductionComposition({ store, offerStore, interpreter: { interpret: async (request) => { context.setPhase("INTERPRETATION"); if (activeTurnIndex === consentAt) throw new Error("CONSENT_PROVIDER_MUST_BE_BYPASSED"); return adapters.interpreter.interpret(request); } }, realizer: { realize: async (request) => { context.setPhase("REALIZATION"); return adapters.realizer.realize(request); } }, signer, smokeObserver: (trace) => { traces.push(trace); if (trace.phase === "DECISION") context.setPhase("DECISION"); if (trace.phase === "REALIZATION") context.setPhase("REALIZATION"); } });
    let offerToken: string | undefined; const turns: Record<string, unknown>[] = [];
    for (const [index, initialMessage] of messages.entries()) {
      activeTurnIndex = index;
      context.setPhase(consentAt === index ? "CONSENT" : "DECISION", index + 1);
      const previous = turns.at(-1) as { options?: readonly { label: string }[] } | undefined;
      const userMessage = initialMessage === "$FIRST_OPTION" ? previous?.options?.[0]?.label ?? "Fark etmez" : initialMessage;
      const requestTime = `2026-08-19T00:${String(index).padStart(2, "0")}:00.000Z`; clock.set(requestTime);
      const before = await store.load(conversationId); const activeOfferBefore = before?.memory?.currentOffer;
      const suppliedToken = consentAt === index ? offerToken : undefined;
      const output = await runCarsDecisionTurnV2({ conversationId, messageId: `${name}-${index + 1}`, idempotencyKey: `${name}-${index + 1}`, expectedConversationRevision: index, userMessage, ...(suppliedToken ? { offerToken: suppliedToken } : {}), requestTime }, composition);
      offerToken = output.offer?.token ?? offerToken;
      const after = await store.load(conversationId); const activeOfferAfter = after?.memory?.currentOffer; const verification = suppliedToken ? signer.verify(suppliedToken) : undefined;
      const decision = traces.filter((trace) => trace.phase === "DECISION").at(-1) ?? {}; const realization = traces.filter((trace) => trace.phase === "REALIZATION").at(-1) ?? {}; const offerResponse = traces.filter((trace) => trace.phase === "OFFER_RESPONSE").at(-1) ?? {};
      if (index === consentAt) { assertSmoke(offerResponse.interpretationSource === "DETERMINISTIC_OFFER_RESPONSE", "CONSENT_NOT_CLASSIFIED"); assertSmoke(offerResponse.providerCalled === false, "CONSENT_PROVIDER_NOT_BYPASSED"); }
      context.setPhase(consentAt === index ? "REVEAL" : "ASSERTION", index + 1); assert.ok(output.message.trim()); assert.ok(Number(decision.materialQuestionCount ?? 0) <= 1); assert.doesNotMatch(output.message, /runtime|fingerprint|authorization|internal estimate/iu);
      turns.push({ turn: index + 1, readiness: decision.recommendationReadiness, unansweredFields: decision.unansweredDecisionFields, generatedQuestions: decision.generatedQuestionKeys, selectedQuestion: decision.selectedQuestionKey, candidatePool: decision.technicalBuckets, modelScope: decision.modelScope, action: decision.action, materialQuestionCount: decision.materialQuestionCount, activeOffer: decision.activeOffer, offerCreated: decision.offerCreated, consentBound: consentAt === index ? output.state === "REVEALED" : null, cards: output.cards.length, options: output.options.map((option) => ({ id: option.id, label: option.label })), realization: { source: realization.source, firstAttemptCodes: realization.firstAttemptCodes, repairAttemptCodes: realization.repairAttemptCodes } });
      await writeJsonLine(process.stdout, { type: "TURN_COMPLETED", runId, journey: name, turn: index + 1, readiness: decision.recommendationReadiness, action: decision.action, authoritativeConsent: index === consentAt ? (decision.interpretedActs as readonly string[] | undefined)?.includes("OFFER_ACCEPTANCE") ?? false : undefined, offerCreated: decision.offerCreated, offerPresentInOutput: Boolean(output.offer), activeOfferBefore: Boolean(activeOfferBefore), activeOfferAfter: Boolean(activeOfferAfter), offerLifecycleBefore: activeOfferBefore?.lifecycleState ?? null, offerLifecycleAfter: activeOfferAfter?.lifecycleState ?? null, offerTokenAvailable: Boolean(offerToken), offerTokenSupplied: Boolean(suppliedToken), offerVerification: verification?.status ?? null, decisionFingerprintMatch: activeOfferAfter ? activeOfferAfter.decisionFingerprint === after?.memory?.decisionFingerprint : null, catalogFingerprintMatch: activeOfferAfter ? activeOfferAfter.catalogFingerprint === after?.memory?.catalogAuthority.catalogFingerprint : null, newOfferCreated: index === consentAt ? Boolean(output.offer) : undefined, materialQuestionCount: decision.materialQuestionCount, cards: output.cards.length, state: output.state });
    }
    return { name, conversationHash, turns, status: "PASS" as const };
  }
  const result = await runBoundedSmoke({ runId, timeoutMs: Math.max(config.timeoutMs * 40, 600_000), write: (record) => writeJsonLine(process.stdout, record), journeys: [
    { name: "complete-first-car", run: async (context) => { const summary = await journey("complete-first-car", ["İlk arabam olacak; şehir içinde otomatik hibrit hatchback istiyorum, bütçem maksimum 3 milyon."], context); const turn = summary.turns[0]; context.setPhase("ASSERTION", 1); assertSmoke(turn?.action === "REQUEST_REVEAL_CONSENT", "FIRST_CAR_NOT_OFFERED"); assertSmoke(turn?.offerCreated === true, "FIRST_CAR_OFFER_NOT_CREATED"); assertSmoke(turn?.cards === 0, "FIRST_CAR_UNEXPECTED_CARDS"); return summary; } },
    { name: "natural-consent", run: async (context) => { const summary = await journey("natural-consent", ["Şehir içinde günlük kullanacağım. Otomatik, hibrit ve kompakt hatchback istiyorum. İki kabin boy bavul yeterli; bütçe önemli değil. Bana uygun seçenekleri hazırla.", "Paylaş"], context, 1); const turns = summary.turns; context.setPhase("ASSERTION", 2); assertSmoke(turns[0]?.readiness === "READY_FOR_OFFER", "CONSENT_TURN1_NOT_READY"); assertSmoke(turns[0]?.offerCreated === true, "CONSENT_TURN1_OFFER_NOT_CREATED"); assertSmoke(turns[0]?.cards === 0, "CONSENT_TURN1_UNEXPECTED_CARDS"); assertSmoke(turns[1]?.offerCreated === false, "CONSENT_TURN2_NEW_OFFER_CREATED"); assertSmoke(turns[1]?.consentBound === true, "CONSENT_TRANSITION_NOT_REVEALED"); assertSmoke(Number(turns[1]?.cards) >= 1, "CONSENT_NO_AUTHORIZED_CARDS"); assertSmoke(Number(turns[1]?.cards) <= 3, "CONSENT_TOO_MANY_CARDS"); return summary; } },
    { name: "family-prestige-correction", run: async (context) => { const summary = await journey("family-prestige-correction", ["Ailem için prestijli bir SUV istiyorum.", "Fikrimi değiştirdim, sedan olsun.", "Benzinli ve otomatik olsun; bütçem en fazla 5 milyon.", "Artık önerini söyle."], context, 3); const turns = summary.turns; context.setPhase("ASSERTION", 4); assertSmoke(turns.slice(0, 3).every((turn) => Number(turn.cards) === 0), "CORRECTION_REVEALED_BEFORE_CONSENT"); assertSmoke(Number(turns.at(-1)?.cards) >= 1 && Number(turns.at(-1)?.cards) <= 3, "CORRECTION_CONSENT_NOT_REVEALED"); return summary; } },
    { name: "ev-coffee-break-guidance", run: async (context) => { const summary = await journey("ev-coffee-break-guidance", ["Elektrikli araba istiyorum; uzun yolda kahve molası kadar kısa şarj olsun.", "Teknik terimleri bilmiyorum, günlük örnekle açıkla.", "$FIRST_OPTION", "SUV olsun, bütçem 5 milyon."], context); context.setPhase("ASSERTION", 4); assertSmoke(summary.turns.some((turn) => turn.action === "EXPLAIN_TECHNICAL_CONCEPT" || turn.action === "ANSWER_DIRECTLY"), "EV_GUIDANCE_NOT_ANSWERED"); assertSmoke(summary.turns.every((turn) => Number(turn.cards) === 0), "EV_GUIDANCE_REVEALED_WITHOUT_CONSENT"); return summary; } },
    { name: "clio-civic-comparison", run: async (context) => { const summary = await journey("clio-civic-comparison", ["Clio mu Civic mi kararsızım.", "Şehir içinde kullanacağım, otomatik olsun."], context); const first = summary.turns[0]; context.setPhase("ASSERTION", 2); assertSmoke(first?.readiness === "DIRECT_MODEL_SCOPE", "COMPARISON_NOT_SCOPED"); assertSmoke(Array.isArray(first?.modelScope) && first.modelScope.length >= 1, "COMPARISON_SCOPE_EMPTY"); assertSmoke(summary.turns.every((turn) => Number(turn.cards) === 0), "COMPARISON_REVEALED_WITHOUT_CONSENT"); return summary; } },
    { name: "micra-new-car-lookup", run: async (context) => { const summary = await journey("micra-new-car-lookup", ["Kızım için sıfır Nissan Micra düşünüyorum, katalogda var mı?", "Yoksa benzer sıfır otomatik küçük hatchback bulalım."], context); context.setPhase("ASSERTION", 2); assertSmoke(summary.turns[0]?.action === "ANSWER_MODEL_LOOKUP", "MICRA_LOOKUP_NOT_ANSWERED"); assertSmoke(summary.turns.every((turn) => Number(turn.cards) === 0), "LOOKUP_REVEALED_WITHOUT_CONSENT"); return summary; } },
    { name: "urban-cargo-van", run: async (context) => { const summary = await journey("urban-cargo-van", ["Şehir içinde mal dağıtıyorum; Caddy tarzı kapalı kasa, arka koltuksuz bir araç lazım.", "Dizel ve otomatik olsun.", "Bütçem 3 milyon; önerini hazırla."], context); const last = summary.turns.at(-1); context.setPhase("ASSERTION", 3); assertSmoke(Number((last?.candidatePool as { eligible?: number } | undefined)?.eligible ?? 577) < 577, "CARGO_POOL_NOT_REDUCED"); assertSmoke(summary.turns.every((turn) => Number(turn.cards) === 0), "CARGO_REVEALED_WITHOUT_CONSENT"); return summary; } },
    { name: "repeated-decision-changes", run: async (context) => { const summary = await journey("repeated-decision-changes", ["SUV ve benzinli istiyorum.", "Vazgeçtim, sedan ve hibrit olsun.", "Yok, hatchback ve elektrikli olsun.", "Son kararım otomatik hibrit sedan; bütçem 4 milyon."], context); context.setPhase("ASSERTION", 4); assertSmoke(summary.turns.every((turn) => Number(turn.materialQuestionCount) <= 1), "DECISION_CHANGE_MULTIPLE_QUESTIONS"); assertSmoke(summary.turns.every((turn) => Number(turn.cards) === 0), "DECISION_CHANGE_REVEALED_WITHOUT_CONSENT"); return summary; } },
    { name: "social-detour-return", run: async (context) => { const summary = await journey("social-detour-return", ["İlk arabam olacak, şehir içinde kullanacağım.", "Bu arada nasılsın, işler nasıl? 😄", "Neyse arabaya dönelim; otomatik hatchback istiyorum."], context); context.setPhase("ASSERTION", 3); assertSmoke(summary.turns[1]?.action === "SOCIAL_REPLY", "SOCIAL_DETOUR_NOT_HANDLED"); assertSmoke(summary.turns[2]?.action !== "SOCIAL_REPLY", "SOCIAL_DETOUR_DID_NOT_RETURN"); return summary; } },
    { name: "off-topic-recovery", run: async (context) => { const summary = await journey("off-topic-recovery", ["Hibrit bir araba arıyorum.", "Bana makarna tarifi versene.", "Hava durumunu da söyle.", "Tamam, arabaya dönelim; otomatik sedan olsun."], context); context.setPhase("ASSERTION", 4); assertSmoke(summary.turns[1]?.action === "RECOVER_OFF_TOPIC", "OFF_TOPIC_NOT_RECOVERED"); assertSmoke(summary.turns[3]?.action !== "END_POLITELY", "OFF_TOPIC_RETURN_NOT_ACCEPTED"); return summary; } },
    { name: "abusive-correction", run: async (context) => { const summary = await journey("abusive-correction", ["SUV istiyorum.", "Salak mısın, SUV değil sedan dedim.", "Tamam, sakin devam edelim; otomatik olsun."], context); context.setPhase("ASSERTION", 3); assertSmoke(summary.turns[1]?.action === "ANSWER_DIRECTLY", "ABUSIVE_CORRECTION_NOT_APPLIED"); assertSmoke(summary.turns[2]?.action !== "END_POLITELY", "RESPECTFUL_RETURN_REJECTED"); return summary; } },
    { name: "persona-activate-deactivate", run: async (context) => { const summary = await journey("persona-activate-deactivate", ["Şık, prestijli ve dikkat çekici bir araba istiyorum.", "Aslında tarz fark etmez, en mantıklısını seç.", "Otomatik sedan olsun; bütçem 5 milyon."], context); context.setPhase("ASSERTION", 3); assertSmoke(summary.turns.every((turn) => Number(turn.cards) === 0), "PERSONA_REVEALED_WITHOUT_CONSENT"); assertSmoke(summary.turns.at(-1)?.action === "ASK_MATERIAL_QUESTION" || summary.turns.at(-1)?.action === "REQUEST_REVEAL_CONSENT", "PERSONA_FLOW_STALLED"); return summary; } },
    { name: "budget-conflict-expansion", run: async (context) => { const summary = await journey("budget-conflict-expansion", ["Elektrikli coupe istiyorum, bütçem en fazla 2 milyon.", "Bütçeyi 5 milyona çıkarıyorum.", "Otomatik olsun; önerini hazırla."], context); context.setPhase("ASSERTION", 3); const firstEligible = Number((summary.turns[0]?.candidatePool as { eligible?: number } | undefined)?.eligible ?? 0); const secondEligible = Number((summary.turns[1]?.candidatePool as { eligible?: number } | undefined)?.eligible ?? 0); assertSmoke(secondEligible >= firstEligible, "BUDGET_EXPANSION_SHRANK_TECHNICAL_POOL"); assertSmoke(summary.turns.every((turn) => Number(turn.cards) === 0), "BUDGET_REVEALED_WITHOUT_CONSENT"); return summary; } },
    { name: "technical-novice", run: async (context) => { const summary = await journey("technical-novice", ["Bagaj litresi, kW ve tüketim değerlerinden anlamıyorum; günlük örneklerle yönlendir.", "İki büyük bavul sığsın, şehir içinde canlı olsun ama yakıtı üzmesin.", "$FIRST_OPTION"], context); context.setPhase("ASSERTION", 3); assertSmoke(summary.turns[0]?.action === "EXPLAIN_TECHNICAL_CONCEPT" || summary.turns[0]?.action === "ANSWER_DIRECTLY", "TECHNICAL_NOVICE_NOT_ANSWERED"); assertSmoke(summary.turns.every((turn) => Number(turn.materialQuestionCount) <= 1), "TECHNICAL_NOVICE_MULTIPLE_QUESTIONS"); return summary; } },
    { name: "candidate-rejection", run: async (context) => { const summary = await journey("candidate-rejection", ["Şehir içinde otomatik hibrit hatchback istiyorum; bütçe önemli değil. Önerini hazırla.", "Göster", "Bunları beğenmedim, başka seçeneklere bakalım."], context, 1); context.setPhase("ASSERTION", 3); assertSmoke(Number(summary.turns[1]?.cards) >= 1, "REJECTION_SETUP_NOT_REVEALED"); assertSmoke(summary.turns[2]?.action !== "REVEAL_AUTHORIZED_CARDS", "REJECTION_REVEALED_OLD_OFFER"); return summary; } },
    { name: "natural-long-offer", run: async (context) => { const summary = await journey("natural-long-offer", ["Merhaba, kendime ilk arabamı alacağım.", "Şehir içinde kullanacağım; premium ve şık dursun ama abartılı sportif olmasın.", "Otomatik hibrit hatchback olsun.", "İki büyük bavul yeter; bütçem 5 milyon.", "Önerini hazırla.", "Hadi görelim"], context, 5); const last = summary.turns.at(-1); context.setPhase("ASSERTION", 6); assertSmoke(Number(last?.cards) >= 1 && Number(last?.cards) <= 3, "LONG_OFFER_NOT_REVEALED"); assertSmoke(last?.consentBound === true, "LONG_OFFER_CONSENT_NOT_BOUND"); return summary; } },
  ] });
  return result.ok;
}

main().then(
  (ok) => { process.exitCode = ok ? 0 : 1; },
  async (error: unknown) => { await writeJsonLine(process.stdout, { type: "RUN_FAILED", runId: "setup", journey: "SETUP", turn: 0, phase: "SETUP", errorClass: error instanceof Error && /429/iu.test(error.message) ? "PROVIDER" : "SETUP", errorCode: error instanceof Error && /429/iu.test(error.message) ? "PROVIDER_RATE_LIMITED" : "SETUP_FAILED", completedJourneys: 0 }); process.exitCode = 1; },
);
