import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

async function main() {
  const root = process.cwd();
  const pointer = JSON.parse(await readFile(path.join(root, "data/production/equipment-evidence/active.json"), "utf8")) as { state: string; activeEquipmentEvidenceRelease: string; compatibleCatalogRelease: string; compatibleCatalogFingerprint: string; payloadSha256: string; schemaVersion: string };
  if (pointer.state !== "ACTIVE" || !/^v[0-9a-z.-]+$/u.test(pointer.activeEquipmentEvidenceRelease)
    || !["1.2.1", "1.0.0-rc"].includes(pointer.schemaVersion)) throw new Error("ACTIVE_EQUIPMENT_EVIDENCE_POINTER_INVALID");
  const dir = path.join(root, "data/production/equipment-evidence/releases", pointer.activeEquipmentEvidenceRelease);
  await Promise.all([readFile(path.join(dir, "equipment-evidence.json"), "utf8"), readFile(path.join(dir, "manifest.json"), "utf8")]);
  const source = [pointer.schemaVersion === "1.0.0-rc" ? "// Generated. Do not edit." : "// Generated by scripts/sync-active-equipment-evidence.ts. Do not edit manually.",
    `export { default as activeEquipmentEvidencePayload } from "./releases/${pointer.activeEquipmentEvidenceRelease}/equipment-evidence.json";`,
    `export { default as activeEquipmentEvidenceManifest } from "./releases/${pointer.activeEquipmentEvidenceRelease}/manifest.json";`,
    `export const activeEquipmentEvidenceRelease = "${pointer.activeEquipmentEvidenceRelease}";`, ""].join("\n");
  await writeFile(path.join(root, "data/production/equipment-evidence/activeEquipmentEvidence.generated.ts"), source, "utf8");
  console.log(JSON.stringify({ event: "active_equipment_evidence_synced", release: pointer.activeEquipmentEvidenceRelease }));
}
void main();
