import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

interface ActivePointer {
  readonly state: "ACTIVE";
  readonly activeTechnicalDailyLifeRelease: string;
  readonly compatibleCatalogRelease: string;
  readonly schemaVersion: 1;
}

async function main(): Promise<void> {
  const root = process.cwd();
  const pointerPath = path.join(root, "data/production/technical-daily-life/active.json");
  const generatedPath = path.join(root, "data/production/technical-daily-life/activeTechnicalDailyLife.generated.ts");
  const pointer = JSON.parse(await readFile(pointerPath, "utf8")) as ActivePointer;
  if (pointer.state !== "ACTIVE" || !/^v\d+\.\d+-\d+\.\d+\.\d+-\d{4}-\d{2}-\d{2}(?:-[a-z0-9-]+)?$/.test(pointer.activeTechnicalDailyLifeRelease)
    || !/^v\d+\.\d+\.\d+$/.test(pointer.compatibleCatalogRelease) || pointer.schemaVersion !== 1) {
    throw new Error("ACTIVE_TECHNICAL_DAILY_LIFE_POINTER_INVALID");
  }
  const releaseDirectory = path.join(root, "data/production/technical-daily-life/releases", pointer.activeTechnicalDailyLifeRelease);
  await Promise.all([readFile(path.join(releaseDirectory, "technical-daily-life.json"), "utf8"), readFile(path.join(releaseDirectory, "manifest.json"), "utf8")]);
  const source = [
    "// Generated by scripts/sync-active-technical-daily-life.ts. Do not edit manually.",
    `export { default as activeTechnicalDailyLifePayload } from "./releases/${pointer.activeTechnicalDailyLifeRelease}/technical-daily-life.json";`,
    `export { default as activeTechnicalDailyLifeManifest } from "./releases/${pointer.activeTechnicalDailyLifeRelease}/manifest.json";`,
    `export const activeTechnicalDailyLifeRelease = "${pointer.activeTechnicalDailyLifeRelease}";`,
    `export const compatibleTechnicalDailyLifeCatalogRelease = "${pointer.compatibleCatalogRelease}";`,
    "",
  ].join("\n");
  await writeFile(generatedPath, source, "utf8");
  console.log(JSON.stringify({ event: "active_technical_daily_life_synced", release: pointer.activeTechnicalDailyLifeRelease, generatedPath }));
}

void main();
