import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import type { ProductionCatalogActivation } from "../features/vehicle-data/productionCatalogRelease";

async function main(): Promise<void> {
  const root = process.cwd();
  const pointerPath = path.join(root, "data/production/catalog/active.json");
  const generatedPath = path.join(root, "data/production/catalog/activeCatalog.generated.ts");
  const activation = JSON.parse(await readFile(pointerPath, "utf8")) as ProductionCatalogActivation;
  if (activation.state !== "ACTIVE" || !/^\d+\.\d+\.\d+$/.test(activation.active_catalog_release_version)) {
    throw new Error("ACTIVE_CATALOG_POINTER_INVALID");
  }
  const version = activation.active_catalog_release_version;
  const releaseDirectory = path.join(root, `data/production/catalog/releases/v${version}`);
  await Promise.all([
    readFile(path.join(releaseDirectory, "catalog.json"), "utf8"),
    readFile(path.join(releaseDirectory, "manifest.json"), "utf8"),
    readFile(path.join(releaseDirectory, "decision-facets.json"), "utf8"),
  ]);
  const source = [
    "// Generated by scripts/sync-active-production-catalog.ts. Do not edit manually.",
    `export { default as activeCatalogPayload } from "./releases/v${version}/catalog.json";`,
    `export { default as activeCatalogManifest } from "./releases/v${version}/manifest.json";`,
    `export { default as activeDecisionFacetPayload } from "./releases/v${version}/decision-facets.json";`,
    `export const activeCatalogReleaseVersion = "${version}";`,
    "",
  ].join("\n");
  await writeFile(generatedPath, source, "utf8");
  console.log(JSON.stringify({ event: "active_catalog_module_synced", version, generatedPath }));
}

void main();
