import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { vehiclePersonaSafeTraitPointerSchema } from "@/features/vehicle-data/vehiclePersonaSafeTraits";

async function main(): Promise<void> {
  const root = process.cwd(); const base = path.join(root, "data/production/personas/safe-traits");
  const pointer = vehiclePersonaSafeTraitPointerSchema.parse(JSON.parse(await readFile(path.join(base, "active.json"), "utf8")));
  const releaseRoot = path.join(base, "releases", pointer.activeReleaseVersion);
  await Promise.all([readFile(path.join(releaseRoot, "vehicle-persona-safe-traits.json"), "utf8"), readFile(path.join(releaseRoot, "manifest.json"), "utf8")]);
  const source = [
    "// Generated by scripts/sync-active-vehicle-persona-safe-traits.ts. Do not edit manually.",
    `export { default as activeVehiclePersonaSafeTraitRelease } from "./releases/${pointer.activeReleaseVersion}/vehicle-persona-safe-traits.json";`,
    `export { default as activeVehiclePersonaSafeTraitManifest } from "./releases/${pointer.activeReleaseVersion}/manifest.json";`,
    `export const activeVehiclePersonaSafeTraitReleaseVersion = "${pointer.activeReleaseVersion}";`, "",
  ].join("\n");
  await writeFile(path.join(base, "activeVehiclePersonaSafeTraits.generated.ts"), source, "utf8");
}
void main();
