import { describe, expect, it } from "vitest";
import { allocateReadableId, canonicalizeSourceUrl, validate, type Tables } from "./vehicle-evidence";

const base = (): Tables => ({ models:[{model_id:"MOD-000001"}], generations:[{generation_id:"GEN-000001",model_id:"MOD-000001",identity_status:"VERIFIED"}], powertrains:[{powertrain_id:"PWR-000001",generation_id:"GEN-000001",identity_status:"VERIFIED"}], configurations:[{configuration_id:"CFG-000001",generation_id:"GEN-000001",powertrain_id:"PWR-000001",configuration_status:"VERIFIED"}], facts:[], equipment:[], safety:[], sources:[], assertions:[], queue:[], dictionary:[], lists:[] });
describe("vehicle evidence governance",()=>{
  it("canonicalizes tracking variants",()=>expect(canonicalizeSourceUrl("HTTPS://Example.COM/a/?utm_source=x#part")).toBe("https://example.com/a"));
  it("allocates the next readable id without changing existing ids",()=>expect(allocateReadableId("FAC",["FAC-000002","FAC-000009"])).toBe("FAC-000010"));
  it("rejects a verified configuration with a provisional ancestor",()=>{const t=base();t.generations[0].identity_status="PROVISIONAL";expect(validate(t).some((f)=>f.category==="IDENTITY"&&f.severity==="ERROR")).toBe(true)});
  it("rejects malformed ranges and charging facts",()=>{const t=base();t.facts=[{fact_id:"FAC-000001",subject_type:"CONFIGURATION",subject_id:"CFG-000001",fact_key:"dc_charge_time_min",value_type:"NUMBER",value:"29",value_min:"4",value_max:"5",range_semantics:"MIN_MAX",evidence_state:"REPORTED",soc_start_pct:"",soc_end_pct:""}];t.dictionary=[{sheet:"05_EVIDENCE_FACTS",field_key:"dc_charge_time_min"}];const errors=validate(t).filter((f)=>f.severity==="ERROR").map((f)=>f.category);expect(errors).toContain("RANGE");expect(errors).toContain("CHARGING")});
  it("rejects malformed or missing snapshot references",()=>{const t=base();t.sources=[{source_id:"SRC-000001",source_url:"https://example.com",source_observed_at:"2026-08-14",authority_class:"A1_OFFICIAL_MARKET",source_content_hash:"not-a-hash",source_snapshot_ref:"missing.html"}];expect(validate(t).filter((f)=>f.severity==="ERROR").map((f)=>f.category)).toContain("SNAPSHOT")});
  it("keeps an explicit unavailable snapshot non-blocking",()=>{const t=base();t.sources=[{source_id:"SRC-000001",source_url:"https://example.com",source_observed_at:"2026-08-14",authority_class:"A1_OFFICIAL_MARKET",source_content_hash:"",source_snapshot_ref:"SNAPSHOT_UNAVAILABLE"}];const findings=validate(t);expect(findings.some((f)=>f.category==="SNAPSHOT"&&f.severity==="WARNING")).toBe(true);expect(findings.some((f)=>f.category==="SNAPSHOT"&&f.severity==="ERROR")).toBe(false)});
});
