export type AlertSeverity = "PAGE" | "URGENT_TICKET" | "TICKET";
export interface StagingAlertRoute { readonly alertId: string; readonly signal: string; readonly severity: AlertSeverity; readonly ownerRole: string; readonly backupOwnerRole: string; readonly runbookPath: string; readonly notificationDestinationRef: string | null; readonly syntheticTestEvidenceChecksum: string | null; readonly realNotificationEnabled: false }
export const requiredStagingAlertRoutes: readonly StagingAlertRoute[] = Object.freeze([
  { alertId: "ALERT-TENANT-ISOLATION", signal: "tenant_isolation_failure > 0", severity: "PAGE", ownerRole: "SECURITY_ON_CALL", backupOwnerRole: "INCIDENT_COMMANDER", runbookPath: "docs/expiya-used-cars-moderation-fraud-incident-runbook-v0.1.md", notificationDestinationRef: null, syntheticTestEvidenceChecksum: null, realNotificationEnabled: false },
  { alertId: "ALERT-LEAD-SAFETY", signal: "unsafe_lead_handoff > 0", severity: "PAGE", ownerRole: "PRIVACY_OWNER", backupOwnerRole: "SECURITY_ON_CALL", runbookPath: "docs/expiya-used-cars-lead-consent-retention-v0.1.md", notificationDestinationRef: null, syntheticTestEvidenceChecksum: null, realNotificationEnabled: false },
  { alertId: "ALERT-STOCK-FRESHNESS", signal: "fresh_stock_ratio < 0.95", severity: "URGENT_TICKET", ownerRole: "DEALER_SUCCESS", backupOwnerRole: "PILOT_OWNER", runbookPath: "docs/expiya-used-cars-inventory-data-quality-runbook-v0.1.md", notificationDestinationRef: null, syntheticTestEvidenceChecksum: null, realNotificationEnabled: false },
  { alertId: "ALERT-MODERATION-SLA", signal: "moderation_sla_ratio < 0.95", severity: "URGENT_TICKET", ownerRole: "MODERATOR_L2", backupOwnerRole: "PILOT_OWNER", runbookPath: "docs/expiya-used-cars-moderation-fraud-incident-runbook-v0.1.md", notificationDestinationRef: null, syntheticTestEvidenceChecksum: null, realNotificationEnabled: false },
  { alertId: "ALERT-PARTNER-ERROR", signal: "partner_error_ratio > 0.02", severity: "TICKET", ownerRole: "ENGINEERING_ON_CALL", backupOwnerRole: "PILOT_OWNER", runbookPath: "docs/expiya-used-cars-observability-slo-runbook-v0.1.md", notificationDestinationRef: null, syntheticTestEvidenceChecksum: null, realNotificationEnabled: false },
]);
export function assessStagingAlertRoutes(routes: readonly StagingAlertRoute[]) { const codes: string[] = []; if (new Set(routes.map((item) => item.alertId)).size !== routes.length) codes.push("DUPLICATE_ALERT"); for (const route of routes) { if (!route.ownerRole || !route.backupOwnerRole || route.ownerRole === route.backupOwnerRole) codes.push(`OWNER_AND_BACKUP_REQUIRED:${route.alertId}`); if (!route.runbookPath.startsWith("docs/expiya-used-cars-")) codes.push(`RUNBOOK_REQUIRED:${route.alertId}`); if (!route.notificationDestinationRef || !/^sha256:[a-f0-9]{64}$/u.test(route.syntheticTestEvidenceChecksum ?? "")) codes.push(`ROUTE_TEST_PENDING:${route.alertId}`); if (route.realNotificationEnabled) codes.push(`REAL_NOTIFICATION_FORBIDDEN:${route.alertId}`); } return Object.freeze({ ready: codes.length === 0, codes: Object.freeze(codes), productionAlertingAuthorized: false as const }); }
