export type StagingDatabaseRole = "MIGRATION_OWNER" | "PUBLIC_READER" | "PARTNER_RUNTIME" | "OPS_RUNTIME" | "IMPORT_WORKER" | "AUDIT_READER";
export interface DatabaseRolePolicy { readonly role: StagingDatabaseRole; readonly login: boolean; readonly ownsTables: boolean; readonly bypassRls: boolean; readonly canSetTenantContext: boolean; readonly allowedCapabilities: readonly string[]; readonly forbiddenCapabilities: readonly string[] }
export const usedCarsStagingDatabaseRoles: readonly DatabaseRolePolicy[] = Object.freeze([
  { role: "MIGRATION_OWNER", login: false, ownsTables: true, bypassRls: false, canSetTenantContext: false, allowedCapabilities: ["DDL_DURING_MIGRATION"], forbiddenCapabilities: ["APPLICATION_LOGIN", "PUBLIC_QUERY"] },
  { role: "PUBLIC_READER", login: true, ownsTables: false, bypassRls: false, canSetTenantContext: false, allowedCapabilities: ["SELECT_PUBLIC_PROJECTION"], forbiddenCapabilities: ["SELECT_BASE_TABLE", "MUTATE", "READ_IDENTIFIERS", "READ_DOCUMENTS"] },
  { role: "PARTNER_RUNTIME", login: true, ownsTables: false, bypassRls: false, canSetTenantContext: true, allowedCapabilities: ["TENANT_SCOPED_SELECT", "TENANT_SCOPED_MUTATE"], forbiddenCapabilities: ["CROSS_TENANT", "DDL", "BYPASS_RLS"] },
  { role: "OPS_RUNTIME", login: true, ownsTables: false, bypassRls: false, canSetTenantContext: true, allowedCapabilities: ["TASK_GRANT_SCOPED_REVIEW"], forbiddenCapabilities: ["TENANT_IMPERSONATION", "BULK_LEAD_READ", "DDL"] },
  { role: "IMPORT_WORKER", login: true, ownsTables: false, bypassRls: false, canSetTenantContext: true, allowedCapabilities: ["TENANT_SCOPED_IMPORT"], forbiddenCapabilities: ["DELETION_BY_OMISSION", "CROSS_TENANT", "DDL"] },
  { role: "AUDIT_READER", login: true, ownsTables: false, bypassRls: false, canSetTenantContext: false, allowedCapabilities: ["SELECT_REDACTED_AUDIT_VIEW"], forbiddenCapabilities: ["RAW_PII", "MUTATE", "SELECT_BASE_TABLE"] },
]);
export function validateStagingDatabaseRoles(roles: readonly DatabaseRolePolicy[]) { const codes: string[] = []; if (new Set(roles.map((item) => item.role)).size !== 6 || roles.length !== 6) codes.push("ROLE_COVERAGE_REQUIRED"); if (roles.some((item) => item.role !== "MIGRATION_OWNER" && item.ownsTables)) codes.push("RUNTIME_TABLE_OWNERSHIP_FORBIDDEN"); if (roles.some((item) => item.bypassRls)) codes.push("BYPASS_RLS_FORBIDDEN"); if (roles.find((item) => item.role === "PUBLIC_READER")?.canSetTenantContext) codes.push("PUBLIC_TENANT_CONTEXT_FORBIDDEN"); return Object.freeze(codes); }
