import { APPLIANCES_CATEGORY_REGISTRY } from "@/features/appliances/categoryRegistry";
import { ELECTRONICS_CATEGORY_REGISTRY } from "@/features/electronics/architectureBaseline";
import { ELECTRONICS_CATEGORY_POLICY_VERSION } from "@/features/electronics/categoryPolicy";
export type DepartmentCapabilityStatus = "ACTIVE" | "NOT_READY" | "UNSUPPORTED";
export interface DepartmentCapability { readonly status: DepartmentCapabilityStatus; readonly authorityBinding?: string; readonly publicLabelTr: string; readonly destination: string }
export interface DepartmentRegistryEntry { readonly departmentId: string; readonly publicLabelTr: string; readonly canonicalPath: `/${string}`; readonly status: "ACTIVE" | "NOT_READY"; readonly capabilities: Readonly<Record<string, DepartmentCapability>> }
const capabilities = Object.freeze(Object.fromEntries(APPLIANCES_CATEGORY_REGISTRY.map(category => [category.categoryId, Object.freeze({ status: category.status, publicLabelTr: category.publicLabelTr, destination: `/appliances?entry=secretary&category=${category.categoryId}`, ...(category.authorityBinding ? { authorityBinding: category.authorityBinding } : {}) })])));
const electronicsCapabilities = Object.freeze(Object.fromEntries(ELECTRONICS_CATEGORY_REGISTRY.map(category => [category.categoryId, Object.freeze({ status: "ACTIVE" as const, publicLabelTr: category.publicLabelTr, destination: `/electronics/analysis?category=${category.categoryId}&entry=secretary`, authorityBinding: ELECTRONICS_CATEGORY_POLICY_VERSION })])));
const entries = Object.freeze({ TOOLS: Object.freeze({ departmentId: "TOOLS", publicLabelTr: "El aletleri", canonicalPath: "/tools", status: "ACTIVE", capabilities: Object.freeze({ CORDLESS_DRILL: Object.freeze({ status: "ACTIVE", publicLabelTr: "Akülü matkap", destination: "/tools?entry=secretary&category=CORDLESS_DRILL", authorityBinding: "sha256:04fa39c1130d598bc9b0ed1cac2a24d22180aebce976b21aa428764d1d18b658" }) }) }), CARS: Object.freeze({ departmentId: "CARS", publicLabelTr: "Otomobil", canonicalPath: "/cars", status: "ACTIVE", capabilities: Object.freeze({ NEW_CAR: Object.freeze({ status: "ACTIVE", publicLabelTr: "Sıfır otomobil", destination: "/cars#asama-1", authorityBinding: "ACTIVE_PRODUCTION_CATALOG" }) }) }), APPLIANCES: Object.freeze({ departmentId: "APPLIANCES", publicLabelTr: "Ev ürünleri", canonicalPath: "/appliances", status: "ACTIVE", capabilities }), ELECTRONICS: Object.freeze({ departmentId: "ELECTRONICS", publicLabelTr: "Elektronik", canonicalPath: "/electronics", status: "ACTIVE", capabilities: electronicsCapabilities }), BABY_AND_CHILD: Object.freeze({ departmentId: "BABY_AND_CHILD", publicLabelTr: "Bebek & Çocuk", canonicalPath: "/baby", status: "ACTIVE", capabilities: Object.freeze({ STROLLER: Object.freeze({ status: "ACTIVE", publicLabelTr: "Bebek arabası", destination: "/baby?entry=secretary", authorityBinding: "BABY-STROLLER-TR-v0.2-approval-candidate" }) }) }), MOBILITY: Object.freeze({ departmentId: "MOBILITY", publicLabelTr: "Mobilite", canonicalPath: "/mobility", status: "ACTIVE", capabilities: Object.freeze({ ELECTRIC_SCOOTER: Object.freeze({ status: "ACTIVE", publicLabelTr: "Elektrikli scooter", destination: "/mobility?entry=secretary&category=ELECTRIC_SCOOTER", authorityBinding: "MOBILITY-TR-v0.1-owner-review-candidate" }), ELECTRIC_BICYCLE: Object.freeze({ status: "ACTIVE", publicLabelTr: "Elektrikli bisiklet", destination: "/mobility?entry=secretary&category=ELECTRIC_BICYCLE", authorityBinding: "MOBILITY-TR-v0.1-owner-review-candidate" }), BICYCLE: Object.freeze({ status: "ACTIVE", publicLabelTr: "Bisiklet", destination: "/mobility?entry=secretary&category=BICYCLE", authorityBinding: "MOBILITY-TR-v0.1-owner-review-candidate" }) }) }) } satisfies Record<string, DepartmentRegistryEntry>);
export const ACTIVE_DEPARTMENT_REGISTRY: readonly DepartmentRegistryEntry[] = Object.freeze(Object.values(entries));
export function resolveDepartment(departmentId: string): DepartmentRegistryEntry | undefined { return entries[departmentId as keyof typeof entries]; }
export function resolveDepartmentCapability(departmentId: string, productType: string) { return resolveDepartment(departmentId)?.capabilities[productType]; }
