import { z } from "zod";
import { initializeAppliancesStore } from "@/features/appliances/persistence/initialize.server";
import { PostgresAppliancesConversationStore } from "@/features/appliances/persistence/postgresStore.server";
import { issueAppliancesStageTwoHandoff, loadAppliancesStageTwoHandoffService, readAppliancesStageTwoHandoff } from "@/features/appliances/stageTwo/handoff.server";
import { enforceRateLimit, readJsonWithLimit, verifySameOrigin } from "@/lib/security/requestSecurity";
import { PostgresComparisonEntitlementRepository } from "@/features/comparison-entitlements/postgresRepository.server";
import { loadGovernedManualAuthority, projectAuthorizedL9Knowledge, projectPublicAdvisorManualKnowledge } from "@/features/appliances/manuals/authority.server";
export const runtime="nodejs";
const schema=z.discriminatedUnion("action",[z.strictObject({action:z.literal("ISSUE"),conversationId:z.string().uuid(),expectedRevision:z.number().int().positive()}),z.strictObject({action:z.literal("READ"),handoff:z.string().min(80).max(4096)})]);
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{"Cache-Control":"no-store",Pragma:"no-cache","Referrer-Policy":"no-referrer"}});
const rejected=(status=403)=>json({kind:"HANDOFF_REJECTED",message:"Bu AŞAMA 2 bağlantısı geçersiz veya süresi dolmuş. AŞAMA 1’e dönüp güncel karardan yeniden açabilirsin."},status);
export async function POST(request:Request){const origin=verifySameOrigin(request);if(origin)return origin;const limited=await enforceRateLimit(request,{scope:"appliances-stage-two-handoff",limit:30,windowMs:60_000});if(limited)return limited;let value:unknown;try{value=await readJsonWithLimit(request,8_192);}catch{return rejected(400);}const parsed=schema.safeParse(value);if(!parsed.success)return rejected(400);const service=loadAppliancesStageTwoHandoffService();if(!service)return json({kind:"HANDOFF_UNAVAILABLE",message:"AŞAMA 2 şu anda açılamıyor. AŞAMA 1 kararın korunuyor."},503);const database=await initializeAppliancesStore({DATABASE_URL:process.env.DATABASE_URL,DATABASE_POOL_MAX:process.env.DATABASE_POOL_MAX});if(database.status!=="READY")return json({kind:"HANDOFF_UNAVAILABLE",message:"Karar kaydı şu anda doğrulanamıyor. AŞAMA 1’den daha sonra yeniden deneyebilirsin."},503);const store=new PostgresAppliancesConversationStore(database.pool);try{if(parsed.data.action==="ISSUE"){const result=await issueAppliancesStageTwoHandoff({store,service,...parsed.data});return result.status==="ISSUED"?json({kind:"HANDOFF_ISSUED",handoff:result.handoff}):rejected(409);}const result=await readAppliancesStageTwoHandoff({store,service,handoff:parsed.data.handoff,entitlementRepository:new PostgresComparisonEntitlementRepository(database.pool)});if(result.status!=="READY")return rejected();const manualAuthority=await loadGovernedManualAuthority();const l9=manualAuthority.status==="READY"?projectAuthorizedL9Knowledge({release:manualAuthority.authority.release,authorizedProductId:result.selectedCard.identity.productId,categoryId:result.productType,catalogRelease:result.catalogRelease,configurationIdentity:result.selectedCard.identity.configurationIdentity}):undefined;return json({kind:"STAGE_TWO_READY",productType:result.productType,revision:result.revision,selectedCard:result.selectedCard,comparisonEntitlement:result.comparisonEntitlement,manualKnowledge:projectPublicAdvisorManualKnowledge(l9)});}catch{return rejected(503);}}
