export type ApiSurface = "PUBLIC_B2C" | "PARTNER" | "OPS" | "SERVICE_FEED" | "PROVIDER_WEBHOOK";
export type ApiAuthMode = "ANONYMOUS_RATE_LIMITED" | "B2C_VERIFIED_ACTION" | "PARTNER_SESSION" | "OPS_SESSION" | "SERVICE_HMAC" | "PROVIDER_SIGNATURE";
export interface ApiEndpointPolicy { readonly endpointId: string; readonly method: "GET" | "POST" | "PATCH"; readonly pathTemplate: string; readonly version: "v1"; readonly surface: ApiSurface; readonly authMode: ApiAuthMode; readonly tenantContextRequired: boolean; readonly idempotencyRequired: boolean; readonly csrfRequired: boolean; readonly paginationRequired: boolean; readonly maximumBodyBytes: number; readonly requestsPerMinute: number; readonly productionEnabled: false }
export const usedCarsApiEndpointRegistry: readonly ApiEndpointPolicy[] = Object.freeze([
  { endpointId: "PUBLIC-LISTINGS", method: "GET", pathTemplate: "/api/used-cars/v1/listings", version: "v1", surface: "PUBLIC_B2C", authMode: "ANONYMOUS_RATE_LIMITED", tenantContextRequired: false, idempotencyRequired: false, csrfRequired: false, paginationRequired: true, maximumBodyBytes: 0, requestsPerMinute: 60, productionEnabled: false },
  { endpointId: "PUBLIC-LISTING-DETAIL", method: "GET", pathTemplate: "/api/used-cars/v1/listings/:id", version: "v1", surface: "PUBLIC_B2C", authMode: "ANONYMOUS_RATE_LIMITED", tenantContextRequired: false, idempotencyRequired: false, csrfRequired: false, paginationRequired: false, maximumBodyBytes: 0, requestsPerMinute: 60, productionEnabled: false },
  { endpointId: "B2C-LEAD", method: "POST", pathTemplate: "/api/used-cars/v1/leads", version: "v1", surface: "PUBLIC_B2C", authMode: "B2C_VERIFIED_ACTION", tenantContextRequired: true, idempotencyRequired: true, csrfRequired: true, paginationRequired: false, maximumBodyBytes: 32768, requestsPerMinute: 5, productionEnabled: false },
  { endpointId: "PARTNER-INVENTORY", method: "POST", pathTemplate: "/api/used-cars/v1/partner/inventory", version: "v1", surface: "PARTNER", authMode: "PARTNER_SESSION", tenantContextRequired: true, idempotencyRequired: true, csrfRequired: true, paginationRequired: false, maximumBodyBytes: 1048576, requestsPerMinute: 30, productionEnabled: false },
  { endpointId: "PARTNER-INVENTORY-UPDATE", method: "PATCH", pathTemplate: "/api/used-cars/v1/partner/inventory/:id", version: "v1", surface: "PARTNER", authMode: "PARTNER_SESSION", tenantContextRequired: true, idempotencyRequired: true, csrfRequired: true, paginationRequired: false, maximumBodyBytes: 131072, requestsPerMinute: 60, productionEnabled: false },
  { endpointId: "PARTNER-LEADS", method: "GET", pathTemplate: "/api/used-cars/v1/partner/leads", version: "v1", surface: "PARTNER", authMode: "PARTNER_SESSION", tenantContextRequired: true, idempotencyRequired: false, csrfRequired: false, paginationRequired: true, maximumBodyBytes: 0, requestsPerMinute: 60, productionEnabled: false },
  { endpointId: "OPS-MODERATION", method: "POST", pathTemplate: "/api/used-cars/v1/ops/moderation/:id/decision", version: "v1", surface: "OPS", authMode: "OPS_SESSION", tenantContextRequired: true, idempotencyRequired: true, csrfRequired: true, paginationRequired: false, maximumBodyBytes: 65536, requestsPerMinute: 30, productionEnabled: false },
  { endpointId: "FEED-IMPORT", method: "POST", pathTemplate: "/api/used-cars/v1/feed/inventory", version: "v1", surface: "SERVICE_FEED", authMode: "SERVICE_HMAC", tenantContextRequired: true, idempotencyRequired: true, csrfRequired: false, paginationRequired: false, maximumBodyBytes: 10485760, requestsPerMinute: 10, productionEnabled: false },
  { endpointId: "PAYMENT-WEBHOOK", method: "POST", pathTemplate: "/api/used-cars/v1/webhooks/payment", version: "v1", surface: "PROVIDER_WEBHOOK", authMode: "PROVIDER_SIGNATURE", tenantContextRequired: true, idempotencyRequired: true, csrfRequired: false, paginationRequired: false, maximumBodyBytes: 262144, requestsPerMinute: 60, productionEnabled: false },
  { endpointId: "CHANNEL-WEBHOOK", method: "POST", pathTemplate: "/api/used-cars/v1/webhooks/channel", version: "v1", surface: "PROVIDER_WEBHOOK", authMode: "PROVIDER_SIGNATURE", tenantContextRequired: true, idempotencyRequired: true, csrfRequired: false, paginationRequired: false, maximumBodyBytes: 262144, requestsPerMinute: 60, productionEnabled: false },
]);
export function validateApiEndpointRegistry(endpoints: readonly ApiEndpointPolicy[]) { const codes: string[] = []; if (new Set(endpoints.map((item) => item.endpointId)).size !== endpoints.length) codes.push("DUPLICATE_ENDPOINT_ID"); if (endpoints.some((item) => !item.pathTemplate.includes(`/${item.version}/`))) codes.push("PATH_VERSION_REQUIRED"); if (endpoints.some((item) => item.method !== "GET" && !item.idempotencyRequired)) codes.push("MUTATION_IDEMPOTENCY_REQUIRED"); if (endpoints.some((item) => ["PARTNER", "OPS"].includes(item.surface) && !item.tenantContextRequired)) codes.push("TENANT_CONTEXT_REQUIRED"); if (endpoints.some((item) => item.productionEnabled)) codes.push("PRODUCTION_ENDPOINT_FORBIDDEN"); return Object.freeze(codes); }
