import { describe, expect, it } from "vitest";
import type { ConversationMemory } from "../domain/conversationMemory";
import type { DirectAnswerObligation } from "../domain/decisionTurnResult";
import type { CandidateRanking } from "../ranking/types";
import { decideConversationAction } from "./decide";
import { ACTION_POLICY_V1 } from "./policy";
import { selectMaterialQuestion } from "./questions";
import type { QuestionCandidate } from "./types";

function memory(overrides: Partial<ConversationMemory> = {}): ConversationMemory { return { conversationId: "conversation", turn: 4, state: "UNDERSTANDING_NEEDS", vehicleIntentEstablished: true, events: [], budget: { financeFlexibility: "NONE", unresolvedFinancedCeiling: false, budgetImportance: "UNKNOWN", budgetUnknown: true, budgetExcluded: false }, modelReferences: [], revealedCandidateIds: [], socialState: { consecutiveSocialTurns: 0 }, offTopicState: { consecutiveOffTopicTurns: 0, boundaryStated: false }, abuseState: { level: "NONE", strikeCount: 0 }, directAnswerHistory: [], materialQuestionHistory: [], persona: { activated: false, requestedTraits: [] }, catalogAuthority: { market: "TR", releaseVersion: "1", catalogFingerprint: "catalog", manifestFingerprint: "manifest", activatedAt: "2026-08-19T00:00:00.000Z" }, memoryFingerprint: "memory", decisionFingerprint: "decision", ...overrides }; }
const ranking: CandidateRanking = { catalogFingerprint: "catalog", decisionFingerprint: "decision", rankedCandidateIds: ["v1", "v2"], priceUnresolvedCandidateIds: [], diagnostics: [], candidates: ["v1", "v2"].map((id, index) => ({ exactVariantId: id, modelFamilyId: `f${index}`, affordabilityTier: "VERIFIED_WITHIN_BUDGET", rankVector: [], rankingReasonCodes: [], explanationFactInputs: [], personaTrace: { personaActivated: false, requestedPersonaTraits: [], matchedPersonaTraits: [], personaScore: 0, affectedRanking: false, sourceAuthority: "NONE", decisionUse: "NONE" }, dailyLifeTrace: { mappings: [], score: 0, affectedRanking: false }, finalOrdinal: index + 1 })) };
const question = (key: string, field = "bodyStyle", supporting = ["v1"], stage: QuestionCandidate["stage"] = "VEHICLE_ARCHITECTURE"): QuestionCandidate => ({ question: { id: `q-${key}`, stableSemanticKey: key, field, promptIntent: "DISCRIMINATE_CANDIDATES", options: [{ id: "option", semanticValue: "VALUE", userFacingLabel: "Seçenek", provenance: { source: "CURRENT_CANDIDATE_POOL", candidatePoolFingerprint: "decision", supportingCandidateIds: supporting, authorityReference: "catalog" } }], answerCapabilities: ["ANSWER", "SKIP", "UNKNOWN", "NOT_IMPORTANT"], materialityReason: "changes shortlist" }, stage, eligible: true, blockedUntilStagesComplete: [], materiality: 1, informationGain: 1, conversationalRelevance: 1, reasonCodes: [], decisionChangeProbability: 1, conflictResolutionValue: 0, candidateReductionValue: 1, contextualRelevance: 1, answerability: 1, cognitiveLoad: 0, repetitionRisk: 0, timingPenalty: 0, technicalMismatchPenalty: 0, compatibleCandidateIds: supporting });
const direct = (kind: DirectAnswerObligation["kind"]): DirectAnswerObligation => ({ kind, sourceMessageId: "message", authorizedExplanationFactIds: ["fact"], authorizedCandidateIds: ["v1"], placement: "BEFORE_MATERIAL_QUESTION" });
function decide(overrides: Partial<Parameters<typeof decideConversationAction>[0]> = {}) { return decideConversationAction({ memory: memory(), directAnswerObligation: null, candidateAvailability: "READY", recommendationReadiness: "READY_FOR_OFFER", ranking, rankedShortlist: { candidateIds: ["v1", "v2"], mode: "FAMILY_DIVERSE" }, conflictAnalysis: null, unansweredDecisionFields: [], questionCandidates: [], normalizedUserAct: "INFORMATION", policy: ACTION_POLICY_V1, ...overrides }); }

describe("WP9 deterministic action and question policy", () => {
  it("answers a direct lookup without turning it into an unsolicited questionnaire", () => { const result = decide({ directAnswerObligation: direct("MODEL_AVAILABILITY"), questionCandidates: [question("usage")] }); expect(result.nextAction.type).toBe("ANSWER_MODEL_LOOKUP"); expect(result.materialQuestion).toBeNull(); expect(result.policyTrace.directAnswerPlacement).toBe("BEFORE_MATERIAL_QUESTION"); });
  it("turns recommendation requests into identity-free shortlist consent", () => { const result = decide({ normalizedUserAct: "RECOMMENDATION_REQUEST" }); expect(result.nextAction.type).toBe("REQUEST_REVEAL_CONSENT"); expect(result.shortlistIntent?.candidateIds).toEqual(["v1", "v2"]); expect(result.shortlistIntent?.requiresIdentityFreeConsent).toBe(true); expect(result.prohibitedClaims).toContain("UNAUTHORIZED_CANDIDATE_REVEAL"); });
  it("does not stall after the user completes a material discovery chain", () => { const result = decide({ memory: memory({ directAnswerHistory: [], materialQuestionHistory: [{ questionId: "usage", stableSemanticKey: "discovery.usageScenario", field: "usageScenario", askedOnTurn: 1, answerStatus: "ANSWERED", answeredOnTurn: 2 }] }), normalizedUserAct: "INFORMATION", recommendationReadiness: "READY_FOR_OFFER" }); expect(result.nextAction.type).toBe("REQUEST_REVEAL_CONSENT"); expect(result.policyTrace.matchedRule).toBe("COMPLETED_DISCOVERY_READY_SHORTLIST"); });
  it("supports single-request and approximate-budget shortlist intent", () => { expect(decide({ normalizedUserAct: "RECOMMENDATION_REQUEST", rankedShortlist: { candidateIds: ["v1"], mode: "SINGLE_REQUESTED" }, explicitSingleRequested: true }).shortlistIntent?.mode).toBe("SINGLE_REQUESTED"); expect(decide({ normalizedUserAct: "RECOMMENDATION_REQUEST", candidateAvailability: "READY_WITH_APPROXIMATE_BUDGET", approximateBudgetCaveatFactIds: ["approximate"] }).shortlistIntent).toMatchObject({ mode: "APPROXIMATE_BUDGET", requiredCaveatFactIds: ["approximate"] }); });
  it("does not ask answered, declined, or immediately deferred questions", () => { for (const answerStatus of ["ANSWERED", "DECLINED", "DEFERRED"] as const) { const selected = selectMaterialQuestion({ memory: memory({ materialQuestionHistory: [{ questionId: "old", stableSemanticKey: "usage", field: "bodyStyle", askedOnTurn: 3, answeredOnTurn: 4, answerStatus }] }), candidates: [question("usage")], currentCandidateIds: ["v1", "v2"], policy: ACTION_POLICY_V1 }); expect(selected.question).toBeNull(); } });
  it("keeps an unanswered open question active after an unrelated preference change", () => { const selected = selectMaterialQuestion({ memory: memory({ materialQuestionHistory: [{ questionId: "old", stableSemanticKey: "budget", field: "budget", askedOnTurn: 3, answerStatus: "OPEN" }] }), candidates: [question("budget", "budget", ["v1"], "BUDGET")], currentCandidateIds: ["v1", "v2"], policy: ACTION_POLICY_V1 }); expect(selected.question?.stableSemanticKey).toBe("budget"); });
  it("rejects question options outside the current candidate pool", () => { expect(selectMaterialQuestion({ memory: memory(), candidates: [question("bev-only", "powerKw", ["outside-bev"])], currentCandidateIds: ["v1", "v2"], policy: ACTION_POLICY_V1 }).question).toBeNull(); });
  it("closes budget questions after budget exclusion", () => { expect(selectMaterialQuestion({ memory: memory({ budget: { financeFlexibility: "NONE", unresolvedFinancedCeiling: false, budgetImportance: "NONE", budgetUnknown: false, budgetExcluded: true } }), candidates: [question("budget", "budget")], currentCandidateIds: ["v1"], policy: ACTION_POLICY_V1 }).question).toBeNull(); });
  it("never lets later-stage information gain outrank an eligible usage question", () => { const selected = selectMaterialQuestion({ memory: memory(), candidates: [question("fuel", "fuelType", ["v1"], "ENERGY_FIT"), { ...question("usage", "usageScenario", ["v1"], "USAGE_CONTEXT"), informationGain: 0.01, candidateReductionValue: 0 }], currentCandidateIds: ["v1", "v2"], policy: ACTION_POLICY_V1 }); expect(selected.question?.stableSemanticKey).toBe("usage"); });
  it("explains unknown technical concepts instead of repeating the same question", () => { const result = decide({ normalizedUserAct: "UNKNOWN_TECHNICAL_CONCEPT", questionCandidates: [question("consumption")] }); expect(result.nextAction.type).toBe("EXPLAIN_TECHNICAL_CONCEPT"); expect(result.nextState).toBe("TECHNICAL_GUIDANCE"); });
  it("distinguishes hard conflict from price and technical uncertainty", () => { expect(decide({ candidateAvailability: "HARD_CONFLICT" }).nextAction.type).toBe("EXPLAIN_CONFLICT"); expect(decide({ candidateAvailability: "PRICE_UNRESOLVED", rankedShortlist: { candidateIds: [], mode: "FAMILY_DIVERSE" } }).nextAction.type).not.toBe("EXPLAIN_CONFLICT"); expect(decide({ candidateAvailability: "TECHNICALLY_NOT_EVALUABLE", rankedShortlist: { candidateIds: [], mode: "FAMILY_DIVERSE" } }).nextAction.type).not.toBe("EXPLAIN_CONFLICT"); });
  it("implements the abuse ladder without mimicking abuse", () => { expect(decide({ normalizedUserAct: "ABUSE", memory: memory({ abuseState: { level: "NONE", strikeCount: 1 } }) }).policyTrace.matchedRule).toBe("ABUSE_BOUNDARY"); expect(decide({ normalizedUserAct: "ABUSE", memory: memory({ abuseState: { level: "BOUNDARY_SET", strikeCount: 2 } }) }).policyTrace.matchedRule).toBe("ABUSE_WARN"); expect(decide({ normalizedUserAct: "ABUSE", memory: memory({ abuseState: { level: "WARNED", strikeCount: 3 } }) }).nextAction.type).toBe("END_POLITELY"); });
  it("preserves correction handling even when anger follows a system error", () => { const result = decide({ normalizedUserAct: "ABUSE", systemCorrectionRequired: true }); expect(result.policyTrace.matchedRule).toBe("CORRECTION_RECOMPUTE_READY_SHORTLIST"); expect(result.nextAction.type).toBe("REQUEST_REVEAL_CONSENT"); });
  it("handles first and repeated off-topic turns without a blind global turn limit", () => { const noReady = { candidateAvailability: "PRICE_UNRESOLVED" as const, rankedShortlist: { candidateIds: [], mode: "FAMILY_DIVERSE" as const } }; expect(decide({ ...noReady, normalizedUserAct: "OFF_TOPIC", memory: memory({ offTopicState: { consecutiveOffTopicTurns: 1, boundaryStated: false } }) }).policyTrace.matchedRule).toBe("FIRST_OFF_TOPIC"); expect(decide({ ...noReady, normalizedUserAct: "OFF_TOPIC", memory: memory({ offTopicState: { consecutiveOffTopicTurns: 3, boundaryStated: true } }) }).nextAction.type).toBe("END_POLITELY"); expect(decide({ ...noReady, normalizedUserAct: "CLOSING", memory: memory({ turn: 999, state: "REVEALED" }) }).policyTrace.matchedRule).toBe("POLITE_CLOSING"); });
});
