import type { ConversationMemory } from "../domain/conversationMemory";
import type { MaterialQuestion } from "../domain/decisionState";
import { QUESTION_STAGE_ORDER, type ActionPolicy, type QuestionCandidate } from "./types";

export function selectMaterialQuestion(input: { readonly memory: ConversationMemory; readonly candidates: readonly QuestionCandidate[]; readonly currentCandidateIds: readonly string[]; readonly policy: ActionPolicy }): { readonly question: MaterialQuestion | null; readonly utilities: readonly { readonly stableSemanticKey: string; readonly utility: number; readonly eligible: boolean }[] } {
  const current = new Set(input.currentCandidateIds); const history = new Map(input.memory.materialQuestionHistory.map((entry) => [entry.stableSemanticKey, entry]));
  const evaluated = input.candidates.map((candidate) => { const previous = history.get(candidate.question.stableSemanticKey); const repeated = previous?.answerStatus === "ANSWERED" || previous?.answerStatus === "DECLINED" || previous?.answerStatus === "SUPERSEDED" || (previous?.answerStatus === "DEFERRED" && input.memory.turn - (previous.answeredOnTurn ?? previous.askedOnTurn) <= input.policy.deferredQuestionCooldownTurns); const provenanceValid = candidate.question.options.every((option) => option.provenance.source !== "CURRENT_CANDIDATE_POOL" || option.provenance.supportingCandidateIds.every((id) => current.has(id))) && candidate.compatibleCandidateIds.every((id) => current.has(id)); const budgetClosed = candidate.question.field === "budget" && input.memory.budget.budgetExcluded; const utility = candidate.materiality + candidate.conversationalRelevance + candidate.informationGain + candidate.conflictResolutionValue + candidate.answerability - candidate.cognitiveLoad - candidate.repetitionRisk - candidate.timingPenalty - candidate.technicalMismatchPenalty + (candidate.question.field === "budget" && current.size <= input.policy.budgetQuestionHighPriorityPoolSize ? 1 : 0); return { candidate, stableSemanticKey: candidate.question.stableSemanticKey, utility, eligible: candidate.eligible && !repeated && provenanceValid && !budgetClosed && utility > 0 }; });
  const earliestStage = QUESTION_STAGE_ORDER.find((stage) => evaluated.some((entry) => entry.eligible && entry.candidate.stage === stage));
  evaluated.sort((a, b) => QUESTION_STAGE_ORDER.indexOf(a.candidate.stage) - QUESTION_STAGE_ORDER.indexOf(b.candidate.stage) || b.utility - a.utility || b.candidate.informationGain - a.candidate.informationGain || b.candidate.candidateReductionValue - a.candidate.candidateReductionValue || a.stableSemanticKey.localeCompare(b.stableSemanticKey)); const selected = evaluated.find((entry) => entry.eligible && entry.candidate.stage === earliestStage)?.candidate.question ?? null;
  return Object.freeze({ question: selected, utilities: Object.freeze(evaluated.map(({ stableSemanticKey, utility, eligible }) => ({ stableSemanticKey, utility, eligible }))) });
}
