import type { ConversationMemory } from "../domain/conversationMemory";
import type { DecisionAction, DecisionState, MaterialQuestion } from "../domain/decisionState";
import type { DirectAnswerObligation } from "../domain/decisionTurnResult";
import type { CandidateDecisionAvailability, CandidateConflictAnalysis } from "../conflict/types";
import type { CandidateRanking, RankedShortlist } from "../ranking/types";
import type { RecommendationReadiness } from "./readiness";

export type NormalizedUserAct = "RECOMMENDATION_REQUEST" | "CONSENT" | "DECLINE" | "CORRECTION" | "REJECTION" | "TECHNICAL_EXPLANATION_REQUEST" | "UNKNOWN_TECHNICAL_CONCEPT" | "SOCIAL" | "OFF_TOPIC" | "ABUSE" | "CLOSING" | "INFORMATION";
export interface QuestionCandidate { readonly question: MaterialQuestion; readonly decisionChangeProbability: number; readonly conflictResolutionValue: number; readonly candidateReductionValue: number; readonly contextualRelevance: number; readonly answerability: number; readonly cognitiveLoad: number; readonly repetitionRisk: number; readonly timingPenalty: number; readonly technicalMismatchPenalty: number; readonly compatibleCandidateIds: readonly string[] }
export interface ShortlistIntent { readonly candidateIds: readonly [string, ...string[]]; readonly mode: "FAMILY_DIVERSE" | "SINGLE_REQUESTED" | "TRIM_COMPARISON" | "APPROXIMATE_BUDGET"; readonly requiresIdentityFreeConsent: boolean; readonly requiredCaveatFactIds: readonly string[] }
export interface ActionPolicy { readonly policyId: "v2-conversation-action"; readonly policyVersion: "1.0.0"; readonly budgetQuestionHighPriorityPoolSize: number; readonly deferredQuestionCooldownTurns: number; readonly offTopicEndThreshold: number }
export interface ActionPolicyTrace { readonly policyId: string; readonly policyVersion: string; readonly matchedRule: string; readonly questionUtilities: readonly { readonly stableSemanticKey: string; readonly utility: number; readonly eligible: boolean }[]; readonly directAnswerPlacement?: "BEFORE_MATERIAL_QUESTION" }
export interface ConversationActionDecision { readonly nextState: DecisionState; readonly nextAction: DecisionAction; readonly directAnswerObligation: DirectAnswerObligation | null; readonly materialQuestion: MaterialQuestion | null; readonly shortlistIntent: ShortlistIntent | null; readonly explanationFactIds: readonly string[]; readonly prohibitedClaims: readonly string[]; readonly policyTrace: ActionPolicyTrace }
export interface DecideActionInput { readonly memory: ConversationMemory; readonly directAnswerObligation: DirectAnswerObligation | null; readonly candidateAvailability: CandidateDecisionAvailability; readonly recommendationReadiness: RecommendationReadiness; readonly ranking: CandidateRanking; readonly rankedShortlist: RankedShortlist; readonly conflictAnalysis: CandidateConflictAnalysis | null; readonly unansweredDecisionFields: readonly string[]; readonly questionCandidates: readonly QuestionCandidate[]; readonly normalizedUserAct: NormalizedUserAct; readonly policy: ActionPolicy; readonly catalogSnapshotAvailable?: boolean; readonly explicitSingleRequested?: boolean; readonly explicitTrimComparisonRequested?: boolean; readonly approximateBudgetCaveatFactIds?: readonly string[]; readonly systemCorrectionRequired?: boolean }
