import type { AffordabilityCandidatePool, FinalCandidateDisposition } from "../affordability/types";
import type { CatalogSnapshot } from "../catalog/types";
import type { ShortlistIntent } from "../action/types";
import type { CandidateRanking } from "../ranking/types";
import type { PersistedAuthorizedCandidateRef, PersistedGovernedOffer } from "./types";
const forbidden = new Set<FinalCandidateDisposition>(["TECHNICALLY_NOT_EVALUABLE", "CONFIRMED_OVER_BUDGET", "ELIMINATED"]);
export class GovernedOfferAuthorizationError extends Error { constructor(readonly code: string) { super(code); } }
export function createPersistedGovernedOffer(input: { readonly shortlist: ShortlistIntent; readonly ranking: CandidateRanking; readonly affordability: AffordabilityCandidatePool; readonly snapshot: CatalogSnapshot; readonly conversationId: string; readonly offerId: string; readonly nonce: string; readonly createdAt: string; readonly expiresAt: string; readonly rejectedCandidateIds: readonly string[]; readonly explicitTrimComparisonRequested: boolean; readonly explicitPriceUnresolvedConsent: boolean; readonly budgetNearestVerifiedPriceSelection?: boolean }): PersistedGovernedOffer {
  const ids = input.shortlist.candidateIds; if (ids.length < 1 || ids.length > 3 || new Set(ids).size !== ids.length) throw new GovernedOfferAuthorizationError("INVALID_SHORTLIST_SIZE_OR_DUPLICATE");
  if (input.ranking.catalogFingerprint !== input.snapshot.authority.catalogFingerprint || input.affordability.catalogFingerprint !== input.snapshot.authority.catalogFingerprint || input.ranking.decisionFingerprint !== input.affordability.decisionFingerprint) throw new GovernedOfferAuthorizationError("FINGERPRINT_MISMATCH");
  const refs = ids.map((id): PersistedAuthorizedCandidateRef => { const ranked = input.ranking.candidates.find((item) => item.exactVariantId === id); const affordable = input.affordability.candidates.find((item) => item.exactVariantId === id); if (!ranked || !affordable || input.rejectedCandidateIds.includes(id) || forbidden.has(affordable.finalDisposition)) throw new GovernedOfferAuthorizationError("CANDIDATE_NOT_SELECTABLE"); if (affordable.finalDisposition === "TECHNICALLY_ELIGIBLE_PRICE_UNRESOLVED" && !input.explicitPriceUnresolvedConsent) throw new GovernedOfferAuthorizationError("PRICE_UNRESOLVED_CONSENT_REQUIRED"); if (affordable.finalDisposition === "CONDITIONALLY_ELIGIBLE_ESTIMATED_OVER_BUDGET" && !input.shortlist.requiredCaveatFactIds.length) throw new GovernedOfferAuthorizationError("APPROXIMATE_CAVEAT_REQUIRED"); return Object.freeze({ exactVariantId: id, modelFamilyId: ranked.modelFamilyId, finalDisposition: affordable.finalDisposition, rankingOrdinal: ranked.finalOrdinal, caveatFactIds: [...input.shortlist.requiredCaveatFactIds], priceRealizationPermission: affordable.priceAuthority.realizationPermission, ...(input.budgetNearestVerifiedPriceSelection ? { selectionBasis: "BUDGET_NEAREST_DECISION_PRICE" as const } : {}) }); });
  if (input.shortlist.mode === "TRIM_COMPARISON" && !input.explicitTrimComparisonRequested) throw new GovernedOfferAuthorizationError("TRIM_COMPARISON_NOT_EXPLICIT"); if (input.shortlist.mode !== "TRIM_COMPARISON" && new Set(refs.map((ref) => ref.modelFamilyId)).size !== refs.length) throw new GovernedOfferAuthorizationError("FAMILY_DIVERSITY_REQUIRED");
  return Object.freeze({ offerId: input.offerId, conversationId: input.conversationId, candidateRefs: Object.freeze(refs) as PersistedGovernedOffer["candidateRefs"], mode: input.explicitPriceUnresolvedConsent ? "PRICE_UNRESOLVED_ALTERNATIVES" : input.shortlist.mode, catalogReleaseVersion: input.snapshot.authority.releaseVersion, catalogFingerprint: input.snapshot.authority.catalogFingerprint, decisionFingerprint: input.ranking.decisionFingerprint, lifecycleState: "CREATED", createdAt: input.createdAt, expiresAt: input.expiresAt, authorizationVersion: "1.0.0", nonce: input.nonce });
}
export async function authorizePersistedCards(input: { readonly token: string; readonly signer: import("./types").OfferSigner; readonly store: import("./types").GovernedOfferStore; readonly conversationId: string; readonly catalogFingerprint: string; readonly decisionFingerprint: string }) { const verified = input.signer.verify(input.token); if (verified.status !== "VALID" || verified.conversationId !== input.conversationId || verified.catalogFingerprint !== input.catalogFingerprint || verified.decisionFingerprint !== input.decisionFingerprint) return { status: "UNAUTHORIZED" as const, cards: [] as const }; const record = await input.store.get(verified.offerId); if (!record || record.conversationId !== input.conversationId || record.lifecycleState !== "REVEALED") return { status: "UNAUTHORIZED" as const, cards: [] as const }; return { status: "AUTHORIZED" as const, cards: record.candidateRefs.map((ref) => ({ exactVariantId: ref.exactVariantId, caveatFactIds: ref.caveatFactIds, priceRealizationPermission: ref.priceRealizationPermission })) }; }
