import { describe, expect, it } from "vitest";
import { createHmacOfferSigner } from "./signer.server";
import { InMemoryGovernedOfferStore } from "./store";
import type { PersistedGovernedOffer } from "./types";
const now = new Date("2026-08-19T00:00:00.000Z");
const offer = (overrides: Partial<PersistedGovernedOffer> = {}): PersistedGovernedOffer => ({ offerId: "offer-1", conversationId: "conversation-1", candidateRefs: [{ exactVariantId: "variant-1", modelFamilyId: "family-1", finalDisposition: "FULLY_ELIGIBLE_VERIFIED_PRICE", rankingOrdinal: 1, caveatFactIds: [], priceRealizationPermission: "EXACT_PUBLIC_PRICE_ALLOWED" }], mode: "SINGLE_REQUESTED", catalogReleaseVersion: "0.55.0", catalogFingerprint: "catalog", decisionFingerprint: "decision", lifecycleState: "CREATED", createdAt: now.toISOString(), expiresAt: "2026-08-19T00:10:00.000Z", authorizationVersion: "1.0.0", nonce: "nonce-1", ...overrides });
describe("governed offer security", () => {
  it("signs a conversation/catalog/decision-bound token and rejects tampering, expiry and missing secret", () => { expect(() => createHmacOfferSigner({ secret: undefined, now: () => now })).toThrow("OFFER_SIGNING_SECRET_MISSING"); const signer = createHmacOfferSigner({ secret: "test-secret", now: () => now }); const token = signer.sign(offer()); expect(signer.verify(token)).toMatchObject({ status: "VALID", conversationId: "conversation-1", catalogFingerprint: "catalog", decisionFingerprint: "decision" }); expect(signer.verify(`${token}x`).status).toBe("INVALID"); expect(createHmacOfferSigner({ secret: "test-secret", now: () => new Date("2026-08-20") }).verify(token).status).toBe("EXPIRED"); });
  it("enforces revisions, idempotency, transitions, cross-conversation access and persistent lookup", async () => { const store = new InMemoryGovernedOfferStore(); expect((await store.create(offer(), 0, "create")).status).toBe("OK"); expect((await store.create(offer(), 0, "create")).status).toBe("OK"); expect((await store.create(offer({ nonce: "changed" }), 0, "create")).status).toBe("IDEMPOTENCY_CONFLICT"); expect((await store.transition({ offerId: "offer-1", conversationId: "other", to: "CONSENTED", at: now.toISOString(), expectedConversationRevision: 1, idempotencyKey: "cross" })).status).toBe("WRONG_CONVERSATION"); expect((await store.transition({ offerId: "offer-1", conversationId: "conversation-1", to: "CONSENTED", at: now.toISOString(), expectedConversationRevision: 1, idempotencyKey: "consent" })).status).toBe("OK"); expect((await store.transition({ offerId: "offer-1", conversationId: "conversation-1", to: "REVEALED", at: now.toISOString(), expectedConversationRevision: 2, idempotencyKey: "reveal" })).status).toBe("OK"); expect((await store.get("offer-1"))?.candidateRefs[0]?.exactVariantId).toBe("variant-1"); expect((await store.transition({ offerId: "offer-1", conversationId: "conversation-1", to: "REVEALED", at: now.toISOString(), expectedConversationRevision: 2, idempotencyKey: "reveal-again" })).status).toBe("OK"); });
  it("revokes open offers on decision fingerprint change but not same decision", async () => { const store = new InMemoryGovernedOfferStore(); await store.create(offer(), 0, "create"); await store.revokeByConversationDecisionFingerprint("conversation-1", "decision"); expect((await store.get("offer-1"))?.lifecycleState).toBe("CREATED"); await store.revokeByConversationDecisionFingerprint("conversation-1", "changed"); expect((await store.get("offer-1"))?.lifecycleState).toBe("REVOKED"); });
});
