import { describe, expect, it } from "vitest";
import type { PersistedGovernedOffer } from "./types";
import { InMemoryRecommendationOfferAuditStore } from "./recOfferAuditFoundation.server";
import { adaptVerifiedRecommendationOfferAudit } from "@/features/vehicle-data/equipmentRecommendationOfferAuditAdapter.server";
const offer = (overrides: Partial<PersistedGovernedOffer> = {}): PersistedGovernedOffer => ({ offerId: "offer-1", conversationId: "conversation-1", candidateRefs: [{ exactVariantId: "6cb56615-37ef-51a8-9202-a73e59d4e14b", modelFamilyId: "family", finalDisposition: "FULLY_ELIGIBLE_VERIFIED_PRICE", rankingOrdinal: 1, caveatFactIds: [], priceRealizationPermission: "EXACT_PUBLIC_PRICE_ALLOWED" }], mode: "SINGLE_REQUESTED", catalogReleaseVersion: "0.55.4", catalogFingerprint: `sha256:${"a".repeat(64)}`, decisionFingerprint: `sha256:${"b".repeat(64)}`, lifecycleState: "CREATED", createdAt: "2026-08-20T10:00:00.000Z", expiresAt: "2026-08-20T12:00:00.000Z", authorizationVersion: "1.0.0", nonce: "nonce", ...overrides });
const acceptance = { conversationId: "conversation-1", offerId: "offer-1", sourceMessageId: "message-1", idempotencyKey: "accept-1", recommendationTermsVersion: "REC-2026.08-v1.1" as const, expectedRevision: 0 };
describe("REC Offer Audit Foundation", () => {
  it("records separate durable acceptance/reveal instants and resolves VERIFIED proof", async () => { const instants = [new Date("2026-08-20T10:01:00.000Z"), new Date("2026-08-20T10:01:00.001Z")]; const store = new InMemoryRecommendationOfferAuditStore(() => instants.shift()!, [offer()]); const accepted = await store.recordRecommendationTermsAcceptance(acceptance); const revealed = await store.revealAcceptedOffer({ conversationId: "conversation-1", offerId: "offer-1", sourceMessageId: "message-1", idempotencyKey: "reveal-1", expectedRevision: 1 }); const proof = await store.resolveRecommendationOfferAuditProof("conversation-1", "offer-1", `sha256:${"a".repeat(64)}`); expect(accepted).toMatchObject({ status: "OK", event: { auditSequence: 1 } }); expect(revealed).toMatchObject({ status: "OK", event: { auditSequence: 2 } }); expect(proof).toMatchObject({ status: "VERIFIED", acceptanceSequence: 1, revealSequence: 2 }); expect(adaptVerifiedRecommendationOfferAudit(proof)).toMatchObject({ recommendationTermsAccepted: true, recommendationTermsAcceptanceOfferId: "offer-1" }); });
  it("is idempotent and rejects same key with another payload", async () => { const store = new InMemoryRecommendationOfferAuditStore(() => new Date("2026-08-20T10:01:00.000Z"), [offer()]); const first = await store.recordRecommendationTermsAcceptance(acceptance); expect(await store.recordRecommendationTermsAcceptance(acceptance)).toEqual(first); expect(await store.recordRecommendationTermsAcceptance({ ...acceptance, sourceMessageId: "other" })).toEqual({ status: "IDEMPOTENCY_CONFLICT" }); });
  it("keeps CONSENTED and returns bounded pending when clock has not advanced", async () => { const store = new InMemoryRecommendationOfferAuditStore(() => new Date("2026-08-20T10:01:00.000Z"), [offer()]); await store.recordRecommendationTermsAcceptance(acceptance); expect(await store.revealAcceptedOffer({ conversationId: "conversation-1", offerId: "offer-1", sourceMessageId: "message-1", idempotencyKey: "reveal", expectedRevision: 1 })).toEqual({ status: "REVEAL_PENDING_REAL_INSTANT" }); });
  it("fails closed for missing, wrong conversation, unrevealed and historical audit", async () => { const store = new InMemoryRecommendationOfferAuditStore(() => new Date(), [offer(), offer({ offerId: "historical", lifecycleState: "REVEALED", consentedAt: "2026-08-20T10:00:00.000Z", revealedAt: "2026-08-20T10:00:01.000Z" })]); expect((await store.resolveRecommendationOfferAuditProof("c", "missing")).status).toBe("OFFER_NOT_FOUND"); expect((await store.resolveRecommendationOfferAuditProof("wrong", "offer-1")).status).toBe("WRONG_CONVERSATION"); expect((await store.resolveRecommendationOfferAuditProof("conversation-1", "offer-1")).status).toBe("OFFER_NOT_REVEALED"); expect((await store.resolveRecommendationOfferAuditProof("conversation-1", "historical")).status).toBe("HISTORICAL_AUDIT_UNAVAILABLE"); });
});
