import { createHash } from "node:crypto";
import { canonicalize } from "../fingerprint/canonicalize";
import type { RecommendationOfferAuditEvent } from "../domain/conversationEvent";
import type { PersistedGovernedOffer } from "./types";

export const REC_OFFER_AUDIT_SEQUENCE_POLICY = Object.freeze({ policyId: "REC_OFFER_AUDIT_SEQUENCE_V1", version: "1.0.0", scope: "CONVERSATION_OFFER", acceptance: 1, reveal: 2 });
export type RecommendationOfferAuditStatus = "VERIFIED" | "OFFER_NOT_FOUND" | "WRONG_CONVERSATION" | "OFFER_NOT_REVEALED" | "ACCEPTANCE_EVENT_MISSING" | "REVEAL_EVENT_MISSING" | "ACCEPTANCE_EVENT_INVALID" | "REVEAL_EVENT_INVALID" | "TERMS_VERSION_MISMATCH" | "EVENT_REFERENCE_MISMATCH" | "SEQUENCE_ORDER_INVALID" | "TIME_ORDER_INVALID" | "CATALOG_BINDING_MISMATCH" | "OFFER_IDENTITY_MISMATCH" | "EXPIRED" | "HISTORICAL_AUDIT_UNAVAILABLE";
export type RecommendationOfferAuditProof = Readonly<{ status: RecommendationOfferAuditStatus; conversationId: string; offerId: string; recommendationTermsVersion?: "REC-2026.08-v1.1"; acceptanceEventId?: string; acceptedAt?: string; acceptanceSequence?: number; revealEventId?: string; revealedAt?: string; revealSequence?: number; catalogReleaseVersion?: string; catalogFingerprint?: string; offerIdentityFingerprint?: string }>;
export type RecAuditStoreResult = Readonly<{ status: "OK"; event: RecommendationOfferAuditEvent; offer: PersistedGovernedOffer }> | Readonly<{ status: "NOT_FOUND" | "WRONG_CONVERSATION" | "INVALID_TRANSITION" | "EXPIRED" | "REVISION_CONFLICT" | "IDEMPOTENCY_CONFLICT" | "REVEAL_PENDING_REAL_INSTANT" }>;
export interface RecommendationOfferAuditStore { recordRecommendationTermsAcceptance(input: Readonly<{ conversationId: string; offerId: string; sourceMessageId: string; idempotencyKey: string; recommendationTermsVersion: "REC-2026.08-v1.1"; expectedRevision: number }>): Promise<RecAuditStoreResult>; revealAcceptedOffer(input: Readonly<{ conversationId: string; offerId: string; sourceMessageId: string; idempotencyKey: string; expectedRevision: number }>): Promise<RecAuditStoreResult>; resolveRecommendationOfferAuditProof(conversationId: string, offerId: string, expectedCatalogFingerprint?: string): Promise<RecommendationOfferAuditProof> }
const sha = (value: string) => `sha256:${createHash("sha256").update(value).digest("hex")}` as const;
export const offerIdentityFingerprint = (offer: PersistedGovernedOffer) => sha(canonicalize({ offerId: offer.offerId, conversationId: offer.conversationId, candidateRefs: offer.candidateRefs, catalogReleaseVersion: offer.catalogReleaseVersion, catalogFingerprint: offer.catalogFingerprint, decisionFingerprint: offer.decisionFingerprint, nonce: offer.nonce }));
const eventId = (kind: string, key: string, fingerprint: string) => `v2audit_${createHash("sha256").update(`${kind}|${key}|${fingerprint}`).digest("hex").slice(0, 24)}`;

export function resolvePersistedRecommendationOfferAuditProof(input: { readonly conversationId: string; readonly offerId: string; readonly offer: PersistedGovernedOffer | null; readonly events: readonly RecommendationOfferAuditEvent[]; readonly expectedCatalogFingerprint?: string }): RecommendationOfferAuditProof {
  const { conversationId, offerId, offer, events } = input;
  if (!offer) return { status: "OFFER_NOT_FOUND", conversationId, offerId };
  if (offer.conversationId !== conversationId) return { status: "WRONG_CONVERSATION", conversationId, offerId };
  if (offer.lifecycleState !== "REVEALED") return { status: "OFFER_NOT_REVEALED", conversationId, offerId };
  const acceptance = events.find((item): item is Extract<RecommendationOfferAuditEvent, { eventType: "RECOMMENDATION_TERMS_ACCEPTED" }> => item.eventType === "RECOMMENDATION_TERMS_ACCEPTED");
  const reveal = events.find((item): item is Extract<RecommendationOfferAuditEvent, { eventType: "OFFER_REVEALED" }> => item.eventType === "OFFER_REVEALED");
  if (!acceptance && !reveal) return { status: "HISTORICAL_AUDIT_UNAVAILABLE", conversationId, offerId };
  if (!acceptance) return { status: "ACCEPTANCE_EVENT_MISSING", conversationId, offerId };
  if (!reveal) return { status: "REVEAL_EVENT_MISSING", conversationId, offerId };
  if (acceptance.conversationId !== conversationId || reveal.conversationId !== conversationId || acceptance.offerId !== offerId || reveal.offerId !== offerId) return { status: "OFFER_IDENTITY_MISMATCH", conversationId, offerId };
  if (acceptance.recommendationTermsVersion !== "REC-2026.08-v1.1" || reveal.recommendationTermsVersion !== acceptance.recommendationTermsVersion) return { status: "TERMS_VERSION_MISMATCH", conversationId, offerId };
  if (reveal.acceptanceEventId !== acceptance.id) return { status: "EVENT_REFERENCE_MISMATCH", conversationId, offerId };
  if (acceptance.auditSequence !== 1 || reveal.auditSequence !== 2 || acceptance.auditSequence >= reveal.auditSequence) return { status: "SEQUENCE_ORDER_INVALID", conversationId, offerId };
  if (Date.parse(acceptance.acceptedAt) >= Date.parse(reveal.revealedAt)) return { status: "TIME_ORDER_INVALID", conversationId, offerId };
  if ((input.expectedCatalogFingerprint && offer.catalogFingerprint !== input.expectedCatalogFingerprint) || reveal.catalogFingerprint !== offer.catalogFingerprint || reveal.catalogReleaseVersion !== offer.catalogReleaseVersion) return { status: "CATALOG_BINDING_MISMATCH", conversationId, offerId };
  const identity = offerIdentityFingerprint({ ...offer, lifecycleState: "CREATED", consentedAt: undefined, revealedAt: undefined } as PersistedGovernedOffer);
  if (reveal.offerIdentityFingerprint !== identity) return { status: "OFFER_IDENTITY_MISMATCH", conversationId, offerId };
  return { status: "VERIFIED", conversationId, offerId, recommendationTermsVersion: acceptance.recommendationTermsVersion, acceptanceEventId: acceptance.id, acceptedAt: acceptance.acceptedAt, acceptanceSequence: acceptance.auditSequence, revealEventId: reveal.id, revealedAt: reveal.revealedAt, revealSequence: reveal.auditSequence, catalogReleaseVersion: reveal.catalogReleaseVersion, catalogFingerprint: reveal.catalogFingerprint, offerIdentityFingerprint: reveal.offerIdentityFingerprint };
}

export class InMemoryRecommendationOfferAuditStore implements RecommendationOfferAuditStore {
  private readonly offers = new Map<string, PersistedGovernedOffer>(); private readonly events = new Map<string, RecommendationOfferAuditEvent[]>(); private readonly operations = new Map<string, { fingerprint: string; result: RecAuditStoreResult }>(); private revision = 0;
  constructor(private readonly clock: () => Date, offers: readonly PersistedGovernedOffer[] = []) { for (const offer of offers) this.offers.set(offer.offerId, structuredClone(offer)); }
  async recordRecommendationTermsAcceptance(input: Parameters<RecommendationOfferAuditStore["recordRecommendationTermsAcceptance"]>[0]) { const fingerprint = canonicalize(input); const replay = this.operations.get(input.idempotencyKey); if (replay) return replay.fingerprint === fingerprint ? replay.result : { status: "IDEMPOTENCY_CONFLICT" as const };
    const offer = this.offers.get(input.offerId); if (!offer) return { status: "NOT_FOUND" as const }; if (offer.conversationId !== input.conversationId) return { status: "WRONG_CONVERSATION" as const }; if (this.revision !== input.expectedRevision) return { status: "REVISION_CONFLICT" as const }; if (offer.lifecycleState !== "CREATED") return { status: "INVALID_TRANSITION" as const };
    const acceptedAt = this.clock().toISOString(); if (Date.parse(offer.expiresAt) < Date.parse(acceptedAt)) return { status: "EXPIRED" as const }; const payloadFingerprint = sha(fingerprint);
    const event: RecommendationOfferAuditEvent = { schemaVersion: 1, eventType: "RECOMMENDATION_TERMS_ACCEPTED", id: eventId("ACCEPT", input.idempotencyKey, payloadFingerprint), conversationId: input.conversationId, offerId: offer.offerId, recommendationTermsVersion: input.recommendationTermsVersion, acceptedAt, auditSequence: 1, sourceMessageId: input.sourceMessageId, sourceTurn: this.revision + 1, sequence: 0, actor: "USER", authority: "SERVER_RECORDED_USER_ACCEPTANCE", decisionEffect: "AUTHORIZATION_ONLY", createdAt: acceptedAt, predecessorLifecycleState: "CREATED", idempotencyKey: input.idempotencyKey, payloadFingerprint };
    const next = { ...offer, lifecycleState: "CONSENTED" as const, consentedAt: acceptedAt }; this.offers.set(offer.offerId, next); this.events.set(offer.offerId, [event]); this.revision += 1; const result = { status: "OK" as const, event, offer: next }; this.operations.set(input.idempotencyKey, { fingerprint, result }); return result; }
  async revealAcceptedOffer(input: Parameters<RecommendationOfferAuditStore["revealAcceptedOffer"]>[0]) { const fingerprint = canonicalize(input); const replay = this.operations.get(input.idempotencyKey); if (replay) return replay.fingerprint === fingerprint ? replay.result : { status: "IDEMPOTENCY_CONFLICT" as const };
    const offer = this.offers.get(input.offerId); if (!offer) return { status: "NOT_FOUND" as const }; if (offer.conversationId !== input.conversationId) return { status: "WRONG_CONVERSATION" as const }; if (this.revision !== input.expectedRevision) return { status: "REVISION_CONFLICT" as const }; if (offer.lifecycleState !== "CONSENTED" || !offer.consentedAt) return { status: "INVALID_TRANSITION" as const };
    const acceptance = this.events.get(offer.offerId)?.find((item) => item.eventType === "RECOMMENDATION_TERMS_ACCEPTED"); if (!acceptance) return { status: "INVALID_TRANSITION" as const }; const revealedAt = this.clock().toISOString(); if (Date.parse(revealedAt) <= Date.parse(offer.consentedAt)) return { status: "REVEAL_PENDING_REAL_INSTANT" as const }; if (Date.parse(offer.expiresAt) < Date.parse(revealedAt)) return { status: "EXPIRED" as const };
    const identity = offerIdentityFingerprint(offer); const event: RecommendationOfferAuditEvent = { schemaVersion: 1, eventType: "OFFER_REVEALED", id: eventId("REVEAL", input.idempotencyKey, identity), conversationId: input.conversationId, offerId: offer.offerId, revealedAt, auditSequence: 2, acceptanceEventId: acceptance.id, acceptanceAuditSequence: 1, recommendationTermsVersion: acceptance.recommendationTermsVersion, actor: "SYSTEM", authority: "SERVER_OFFER_LIFECYCLE", decisionEffect: "AUTHORIZATION_ONLY", createdAt: revealedAt, sourceMessageId: input.sourceMessageId, sourceTurn: this.revision + 1, sequence: 0, resultingLifecycleState: "REVEALED", catalogReleaseVersion: offer.catalogReleaseVersion, catalogFingerprint: offer.catalogFingerprint, offerIdentityFingerprint: identity, idempotencyKey: input.idempotencyKey };
    const next = { ...offer, lifecycleState: "REVEALED" as const, revealedAt }; this.offers.set(offer.offerId, next); this.events.set(offer.offerId, [...(this.events.get(offer.offerId) ?? []), event]); this.revision += 1; const result = { status: "OK" as const, event, offer: next }; this.operations.set(input.idempotencyKey, { fingerprint, result }); return result; }
  async resolveRecommendationOfferAuditProof(conversationId: string, offerId: string, expectedCatalogFingerprint?: string): Promise<RecommendationOfferAuditProof> { const offer = this.offers.get(offerId); if (!offer) return { status: "OFFER_NOT_FOUND", conversationId, offerId }; if (offer.conversationId !== conversationId) return { status: "WRONG_CONVERSATION", conversationId, offerId }; if (offer.lifecycleState !== "REVEALED") return { status: "OFFER_NOT_REVEALED", conversationId, offerId }; const events = this.events.get(offerId) ?? []; const acceptance = events.find((item): item is Extract<RecommendationOfferAuditEvent, { eventType: "RECOMMENDATION_TERMS_ACCEPTED" }> => item.eventType === "RECOMMENDATION_TERMS_ACCEPTED"); const reveal = events.find((item): item is Extract<RecommendationOfferAuditEvent, { eventType: "OFFER_REVEALED" }> => item.eventType === "OFFER_REVEALED"); if (!acceptance && !reveal) return { status: "HISTORICAL_AUDIT_UNAVAILABLE", conversationId, offerId }; if (!acceptance) return { status: "ACCEPTANCE_EVENT_MISSING", conversationId, offerId }; if (!reveal) return { status: "REVEAL_EVENT_MISSING", conversationId, offerId }; if (acceptance.recommendationTermsVersion !== "REC-2026.08-v1.1" || reveal.recommendationTermsVersion !== acceptance.recommendationTermsVersion) return { status: "TERMS_VERSION_MISMATCH", conversationId, offerId }; if (reveal.acceptanceEventId !== acceptance.id) return { status: "EVENT_REFERENCE_MISMATCH", conversationId, offerId }; if (acceptance.auditSequence >= reveal.auditSequence) return { status: "SEQUENCE_ORDER_INVALID", conversationId, offerId }; if (Date.parse(acceptance.acceptedAt) >= Date.parse(reveal.revealedAt)) return { status: "TIME_ORDER_INVALID", conversationId, offerId }; if (expectedCatalogFingerprint && offer.catalogFingerprint !== expectedCatalogFingerprint || reveal.catalogFingerprint !== offer.catalogFingerprint) return { status: "CATALOG_BINDING_MISMATCH", conversationId, offerId }; const identity = offerIdentityFingerprint({ ...offer, lifecycleState: "CONSENTED", revealedAt: undefined } as PersistedGovernedOffer); if (reveal.offerIdentityFingerprint !== identity) return { status: "OFFER_IDENTITY_MISMATCH", conversationId, offerId }; return { status: "VERIFIED", conversationId, offerId, recommendationTermsVersion: acceptance.recommendationTermsVersion, acceptanceEventId: acceptance.id, acceptedAt: acceptance.acceptedAt, acceptanceSequence: acceptance.auditSequence, revealEventId: reveal.id, revealedAt: reveal.revealedAt, revealSequence: reveal.auditSequence, catalogReleaseVersion: reveal.catalogReleaseVersion, catalogFingerprint: reveal.catalogFingerprint, offerIdentityFingerprint: reveal.offerIdentityFingerprint }; }
}
