import { canonicalize } from "../fingerprint/canonicalize";
import type { GovernedOfferStore, OfferStoreResult, PersistedGovernedOffer, PersistedOfferState } from "./types";
const transitions: Readonly<Record<PersistedOfferState, readonly PersistedOfferState[]>> = { CREATED: ["CONSENTED", "EXPIRED", "REVOKED"], CONSENTED: ["REVEALED", "EXPIRED", "REVOKED"], REVEALED: [], EXPIRED: [], REVOKED: [] };
export class InMemoryGovernedOfferStore implements GovernedOfferStore {
  private readonly offers = new Map<string, PersistedGovernedOffer>(); private readonly revisions = new Map<string, number>(); private readonly operations = new Map<string, string>();
  async create(record: PersistedGovernedOffer, expected: number, key: string): Promise<OfferStoreResult> { const payload = canonicalize(record); const prior = this.operations.get(key); if (prior) return prior === payload ? { status: "OK", record: this.offers.get(record.offerId)!, revision: this.revisions.get(record.conversationId)! } : { status: "IDEMPOTENCY_CONFLICT" }; const revision = this.revisions.get(record.conversationId) ?? 0; if (revision !== expected) return { status: "REVISION_CONFLICT" }; this.offers.set(record.offerId, structuredClone(record)); this.revisions.set(record.conversationId, revision + 1); this.operations.set(key, payload); return { status: "OK", record: structuredClone(record), revision: revision + 1 }; }
  async get(id: string) { const value = this.offers.get(id); return value ? structuredClone(value) : null; }
  async transition(input: { offerId: string; conversationId: string; to: PersistedOfferState; at: string; expectedConversationRevision: number; idempotencyKey: string }): Promise<OfferStoreResult> { const record = this.offers.get(input.offerId); if (!record) return { status: "NOT_FOUND" }; if (record.conversationId !== input.conversationId) return { status: "WRONG_CONVERSATION" }; const revision = this.revisions.get(input.conversationId) ?? 0; const payload = canonicalize(input); const prior = this.operations.get(input.idempotencyKey); if (prior) return prior === payload ? { status: "OK", record: structuredClone(record), revision } : { status: "IDEMPOTENCY_CONFLICT" }; if (record.lifecycleState === input.to && input.to === "REVEALED") return { status: "OK", record: structuredClone(record), revision }; if (revision !== input.expectedConversationRevision) return { status: "REVISION_CONFLICT" }; if (!transitions[record.lifecycleState].includes(input.to)) return { status: "INVALID_TRANSITION" }; if (new Date(record.expiresAt).getTime() < new Date(input.at).getTime()) return { status: "EXPIRED" }; const next = { ...record, lifecycleState: input.to, ...(input.to === "CONSENTED" ? { consentedAt: input.at } : {}), ...(input.to === "REVEALED" ? { revealedAt: input.at } : {}) }; this.offers.set(record.offerId, next); this.revisions.set(input.conversationId, revision + 1); this.operations.set(input.idempotencyKey, payload); return { status: "OK", record: structuredClone(next), revision: revision + 1 }; }
  async revokeByConversationDecisionFingerprint(conversationId: string, fingerprint: string) { for (const [id, offer] of this.offers) if (offer.conversationId === conversationId && offer.decisionFingerprint !== fingerprint && ["CREATED", "CONSENTED"].includes(offer.lifecycleState)) this.offers.set(id, { ...offer, lifecycleState: "REVOKED" }); }
}
