import type { FinalCandidateDisposition, PriceRealizationPermission } from "../affordability/types";

export type PersistedOfferMode = "FAMILY_DIVERSE" | "SINGLE_REQUESTED" | "TRIM_COMPARISON" | "APPROXIMATE_BUDGET" | "PRICE_UNRESOLVED_ALTERNATIVES";
export type PersistedOfferState = "CREATED" | "CONSENTED" | "REVEALED" | "EXPIRED" | "REVOKED";
export interface PersistedAuthorizedCandidateRef { readonly exactVariantId: string; readonly modelFamilyId: string; readonly finalDisposition: FinalCandidateDisposition; readonly rankingOrdinal: number; readonly caveatFactIds: readonly string[]; readonly priceRealizationPermission: PriceRealizationPermission; readonly selectionBasis?: "BUDGET_NEAREST_DECISION_PRICE" }
export interface PersistedGovernedOffer { readonly offerId: string; readonly conversationId: string; readonly candidateRefs: readonly [PersistedAuthorizedCandidateRef, ...PersistedAuthorizedCandidateRef[]]; readonly mode: PersistedOfferMode; readonly catalogReleaseVersion: string; readonly catalogFingerprint: string; readonly decisionFingerprint: string; readonly lifecycleState: PersistedOfferState; readonly createdAt: string; readonly expiresAt: string; readonly consentedAt?: string; readonly revealedAt?: string; readonly authorizationVersion: "1.0.0"; readonly nonce: string }
export type OfferStoreResult = { readonly status: "OK"; readonly record: PersistedGovernedOffer; readonly revision: number } | { readonly status: "NOT_FOUND" | "REVISION_CONFLICT" | "IDEMPOTENCY_CONFLICT" | "INVALID_TRANSITION" | "EXPIRED" | "WRONG_CONVERSATION" };
export interface GovernedOfferStore { readonly persistsCreationWithConversationCommit?: boolean; create(record: PersistedGovernedOffer, expectedConversationRevision: number, idempotencyKey: string): Promise<OfferStoreResult>; get(offerId: string): Promise<PersistedGovernedOffer | null>; transition(input: { readonly offerId: string; readonly conversationId: string; readonly to: PersistedOfferState; readonly at: string; readonly expectedConversationRevision: number; readonly idempotencyKey: string }): Promise<OfferStoreResult>; revokeByConversationDecisionFingerprint(conversationId: string, currentDecisionFingerprint: string, at: string): Promise<void> }
export interface OfferSigner { sign(offer: PersistedGovernedOffer): string; verify(token: string): { readonly status: "VALID"; readonly offerId: string; readonly conversationId: string; readonly catalogFingerprint: string; readonly decisionFingerprint: string; readonly expiresAt: string; readonly authorizationFingerprint: string } | { readonly status: "INVALID" | "EXPIRED" } }
