import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { sha256, splitExtractedPages, validateLocator, validateRelease, type GovernedManualRelease } from "./governedManuals";

const releaseId="APPLIANCES-GOVERNED-EXACT-MANUAL-L9-TR-v0.2";
const directory=path.join(process.cwd(),"data/production/appliances/manuals/releases",releaseId);
const load=async(name:string)=>JSON.parse(await readFile(path.join(directory,name),"utf8"));

describe("governed manual Batch 02 immutable artifacts",()=>{
  it("preserves the exact inventory and records the bounded before/after",async()=>{const release=await load("release.json") as GovernedManualRelease,coverage=await load("coverage.json"),retry=await load("retry-ledger.json");expect(release.members).toHaveLength(97);expect(new Set(release.members.map(x=>x.categoryId))).toHaveLength(24);expect(coverage.before).toMatchObject({manualCount:10,l9EntryCount:5,blockerCount:87,membersWithoutManualId:82});expect(coverage.after).toMatchObject({manualCount:14,l9EntryCount:9,blockerCount:83,membersWithoutAdmittedManual:83});expect(retry.batchPolicy).toEqual({knownIdenticalFailedUrlRetried:false,maxConcurrency:3,timeoutMs:30000,officialSourcesOnly:true});});
  it("admits only the four newly identity-proven official manuals",async()=>{const release=await load("release.json") as GovernedManualRelease;const newManuals=release.manuals.filter(x=>x.retrievedAt==="2026-09-04T18:30:00.000Z");expect(newManuals.map(x=>x.productId).sort()).toEqual(["BAYMAK_XLS65_TR","BOSCH_HXR390H21T_TR","PHILIPS_EP2220_10_TR","PHILIPS_HR7778_00_TR"]);expect(newManuals.every(x=>x.artifactSha256.startsWith("sha256:")&&x.sourceUrl.startsWith("https://"))).toBe(true);});
  it("verifies release, byte, text and every L9 locator digest",async()=>{const release=await load("release.json") as GovernedManualRelease;const bytes=new Map<string,Uint8Array>(),texts=new Map<string,string>();expect(await readdir(path.join(directory,"bytes"))).toHaveLength(release.manuals.length);expect(await readdir(path.join(directory,"text"))).toHaveLength(release.manuals.length);for(const manual of release.manuals){bytes.set(manual.immutableBytesPath,new Uint8Array(await readFile(path.join(directory,manual.immutableBytesPath))));texts.set(manual.immutableTextPath,await readFile(path.join(directory,manual.immutableTextPath),"utf8"));}expect(validateRelease(release,bytes,texts)).toEqual([]);for(const entry of release.l9AdvisorKnowledge){const manual=release.manuals.find(x=>x.manualId===entry.manualId)!;expect(validateLocator(splitExtractedPages(texts.get(manual.immutableTextPath)!),entry.locator)).toBe(true);expect(entry).toMatchObject({decisionAuthority:"NONE",candidateEffect:"NONE"});}});
  it("binds manifest and active pointer without changing decision authority",async()=>{const releaseRaw=await readFile(path.join(directory,"release.json"),"utf8"),manifestRaw=await readFile(path.join(directory,"manifest.json"),"utf8"),manifest=JSON.parse(manifestRaw),active=JSON.parse(await readFile(path.join(directory,"..","..","active.json"),"utf8"));expect(manifest.releaseArtifactSha256).toBe(sha256(releaseRaw));expect(active).toMatchObject({releaseId,releaseDigest:JSON.parse(releaseRaw).releaseDigest,authority:"L9_ADVISOR_ONLY"});expect(active.manifestSha256).toBe(`sha256:${createHash("sha256").update(manifestRaw).digest("hex")}`);expect(manifest.boundaries).toMatchObject({candidateEligibility:"NONE",scoring:"NONE",recommendation:"NONE",y:"NONE",absenceTreatment:"NEUTRAL"});});
});
