import { createHash } from "node:crypto";
import { requireXpyDomainPack } from "../domainPacks";
import { XPY_RUNTIME_DIGEST, XPY_RUNTIME_VERSION } from "../runtimeContract";
import type { Capability, CatalogEvidence, CatalogSource, DailyLifeInterpretation, NeedEvidenceMapping, ObjectiveFact, PersonaPlanningSignal, UsageSemantic, UserNeed, XpyCatalogRelease, XpyComparisonDimension } from "./contract";
import { XPY_CATALOG_VERSION } from "./contract";
import { validateXpyCatalogRelease, xpyCatalogReleaseDigest } from "./validation";

export const DISHWASHER_RICHNESS_RELEASE_VERSION = "APPLIANCES-DISHWASHER-CATALOG-RICHNESS-TR-v0.2" as const;
export const DISHWASHER_PARENT_RELEASE_VERSION = "APPLIANCES-DISHWASHER-TR-v0.1" as const;
export const DISHWASHER_PARENT_ARTIFACT_SHA256 = "66973c59f1b752f2598b4c6b30d6dc0d2b272948a342b33a08f4cd8f68f9124e" as const;
export const DISHWASHER_SEMANTIC_AUTHORITY_VERSION = "DISHWASHER_SEMANTIC_REGISTRY/v0.2" as const;
export const DISHWASHER_REVIEWED_AT = "2026-09-04T21:00:00.000+03:00" as const;

const products = [
  { id:"BOSCH_SMS4IKI62T_TR", brand:"Bosch", model:"SMS4IKI62T", configuration:"Bosch SMS4IKI62T / Türkiye / solo / 60 cm", source:"BOSCH-SMS4IKI62T-TR", facts:{widthMm:600,heightMm:845,depthMm:600,capacity:13,energyClass:"D",ecoWaterLitres:9.5,noiseDbA:48}, capabilities:{autoOpenDry:false,cutleryTray:false,homeConnect:true,aquaStop:false} },
  { id:"SIEMENS_SN25EI63MT_TR", brand:"Siemens", model:"SN25EI63MT", configuration:"Siemens SN25EI63MT / Türkiye / solo / 60 cm", source:"SIEMENS-SN25EI63MT-TR", facts:{widthMm:600,heightMm:845,depthMm:600,capacity:14,energyClass:"D",ecoWaterLitres:6.7,noiseDbA:44}, capabilities:{autoOpenDry:true,cutleryTray:true,homeConnect:true} },
  { id:"SAMSUNG_DW60DG560FWQTR", brand:"Samsung", model:"DW60DG560FWQTR", configuration:"Samsung DW60DG560FWQTR / Türkiye / solo / 60 cm", source:"SAMSUNG-DW60DG560FWQTR-TR", facts:{widthMm:598,heightMm:845,depthMm:600,capacity:14,energyClass:"D",ecoWaterLitres:11.6,noiseDbA:46}, capabilities:{autoOpenDry:true,cutleryTray:true} },
  { id:"BEKO_BM4044_TR", brand:"Beko", model:"BM 4044", configuration:"Beko BM 4044 / Türkiye / solo / 60 cm", source:"BEKO-BM4044-TR", facts:{widthMm:600,heightMm:850,depthMm:600,capacity:14}, capabilities:{autoOpenDry:false,cutleryTray:false,extraDry:true} },
] as const;
const sourceRows = [
  ["BOSCH-SMS4IKI62T-TR","https://www.bosch-home.com.tr/tr/product/bulasik-makineleri/solo-bulasik-makineleri/60cm-genisliginde-bulasik-makineleri/SMS4IKI62T","OFFICIAL"],
  ["SIEMENS-SN25EI63MT-TR","https://www.siemens-home.bsh-group.com/tr/tr/product/bulasik-makineleri/solo-bulasik-makineleri/tam-ebatli-bulasik-makineleri-60cm/SN25EI63MT","OFFICIAL"],
  ["SAMSUNG-DW60DG560FWQTR-TR","https://www.samsung.com/tr/dishwashers/freestanding/dw5500mm-14-place-settings-white-dw60dg560fwqtr/","OFFICIAL"],
  ["SAMSUNG-DW60DG560FWQTR-FICHE","https://images.samsung.com/is/content/samsung/p6/common/energylabel/common-energylabel-dw60dg560fsrtr-productfiche.pdf","REGULATORY"],
  ["BEKO-BM4044-TR","https://www.beko.com.tr/bulasik-makinesi/bm-4044-bulasik-makinesi","OFFICIAL"],
] as const;
const units:Record<string,string|undefined>={widthMm:"mm",heightMm:"mm",depthMm:"mm",capacity:"place settings",ecoWaterLitres:"L/eco cycle",noiseDbA:"dB(A) re 1 pW"};
const makeId=(prefix:string,id:string,key:string)=>`${prefix}:${id.toLowerCase()}:${key}`;

export function buildDishwasherRichnessRelease():XpyCatalogRelease {
  const sources:CatalogSource[]=sourceRows.map(([sourceId,uri,kind])=>({sourceId,kind,uri,version:"observed-2026-09-03",observedAt:"2026-09-03T12:00:00.000+03:00",reviewedAt:DISHWASHER_REVIEWED_AT,market:"TR",applicabilityStatus:"EXACT",status:"VERIFIED",language:"tr-TR"}));
  const evidence:CatalogEvidence[]=[]; const facts:ObjectiveFact[]=[]; const capabilities:Capability[]=[];
  for(const product of products){
    for(const [key,value] of Object.entries(product.facts)){const evidenceId=makeId("dishwasher-evidence-fact",product.id,key),factId=makeId("dishwasher-fact",product.id,key); evidence.push({evidenceId,kind:"TECHNICAL",sourceId:product.source,assertionId:factId,offeringIds:[product.id],market:"TR",observedAt:"2026-09-03T12:00:00.000+03:00",reviewedAt:DISHWASHER_REVIEWED_AT,confidence:"HIGH",status:"VERIFIED",limitations:[key==="ecoWaterLitres"?"Eco-cycle declaration only.":"Exact manufacturer-listed configuration only."],assertion:{locator:`parent.technicalFacts.${key}`,value, ...(units[key]?{unit:units[key]}:{}),applicability:{offeringId:product.id,market:"TR",model:product.model,configuration:product.configuration,status:"EXACT"}}}); facts.push({factId,offeringId:product.id,key,value,...(units[key]?{unit:units[key]}:{}),evidenceId});}
    for(const [key,value] of Object.entries(product.capabilities)){const evidenceId=makeId("dishwasher-evidence-capability",product.id,key),capabilityId=makeId("dishwasher-capability",product.id,key); evidence.push({evidenceId,kind:"CAPABILITY",sourceId:product.source,assertionId:capabilityId,offeringIds:[product.id],market:"TR",observedAt:"2026-09-03T12:00:00.000+03:00",reviewedAt:DISHWASHER_REVIEWED_AT,confidence:"HIGH",status:"VERIFIED",limitations:["Feature presence or absence does not establish cleaning or drying outcome."],assertion:{locator:`parent.capabilities.${key}`,value,applicability:{offeringId:product.id,market:"TR",model:product.model,configuration:product.configuration,status:"EXACT"}}}); capabilities.push({capabilityId,offeringId:product.id,key,state:value?"PRESENT":"ABSENT",evidenceId,limitations:["No cleaning, drying, reliability, or service outcome is guaranteed."]});}
  }
  const factIds=(key:string)=>facts.filter(x=>x.key===key).map(x=>x.factId),capIds=(key:string)=>capabilities.filter(x=>x.key===key).map(x=>x.capabilityId);
  const usageSemantics:UsageSemantic[]=[
    {semanticId:"dishwasher-semantic:fit",meaning:"Body dimensions support a bounded space check; nominal 60 cm class is not an exact fit guarantee.",factIds:[...factIds("widthMm"),...factIds("heightMm"),...factIds("depthMm")],capabilityIds:[]},
    {semanticId:"dishwasher-semantic:capacity",meaning:"Declared place-setting capacity is comparable capacity evidence, not a household-size or loading-pattern guarantee.",factIds:factIds("capacity"),capabilityIds:[]},
    {semanticId:"dishwasher-semantic:resource",meaning:"Energy class and water values are comparable only under the same verified declaration regime and Eco cycle; Beko remains unknown for this comparison.",factIds:[...factIds("energyClass"),...factIds("ecoWaterLitres")],capabilityIds:[]},
    {semanticId:"dishwasher-semantic:noise",meaning:"Declared airborne acoustic noise supports same-regime display, not perceived quietness in a particular home.",factIds:factIds("noiseDbA"),capabilityIds:[]},
    {semanticId:"dishwasher-semantic:drying",meaning:"Auto-open and extra-dry are feature-presence evidence only and do not guarantee a drying result, including plastics.",factIds:[],capabilityIds:[...capIds("autoOpenDry"),...capIds("extraDry")]},
    {semanticId:"dishwasher-semantic:loading",meaning:"A cutlery tray is a verified loading feature; usable layout and fit for particular items remain unproven.",factIds:[],capabilityIds:capIds("cutleryTray")},
    {semanticId:"dishwasher-semantic:connectivity",meaning:"Connectivity or water-protection feature state does not establish service availability or leak prevention outcome.",factIds:[],capabilityIds:[...capIds("homeConnect"),...capIds("aquaStop")]},
  ];
  const needs:UserNeed[]=[["INSTALLATION_ENVELOPE","Physical installation envelope"],["PLACE_SETTING_CAPACITY","Declared place-setting capacity need"],["AUTO_OPEN_DRY_NEED","Automatic door-opening feature need"],["CUTLERY_TRAY_NEED","Separate cutlery-tray need"],["LOW_NOISE_PRIORITY","Comparable standardized-noise priority"],["ECO_RESOURCE_PRIORITY","Comparable Eco-cycle resource priority"],["CONNECTED_CONTROL_NEED","Connected-control feature need"],["BUDGET_SENSITIVITY","Budget evaluated only through external current-price authority"]].map(([needId,meaning])=>({needId,meaning}));
  const mappings:NeedEvidenceMapping[]=[
    {mappingId:"dishwasher-map:fit",needId:"INSTALLATION_ENVELOPE",eligibleFactIds:[...factIds("widthMm"),...factIds("heightMm"),...factIds("depthMm")],eligibleCapabilityIds:[],policy:"HARD_FILTER"},
    {mappingId:"dishwasher-map:capacity",needId:"PLACE_SETTING_CAPACITY",eligibleFactIds:factIds("capacity"),eligibleCapabilityIds:[],policy:"HARD_FILTER"},
    {mappingId:"dishwasher-map:auto-open",needId:"AUTO_OPEN_DRY_NEED",eligibleFactIds:[],eligibleCapabilityIds:capIds("autoOpenDry"),policy:"HARD_FILTER"},
    {mappingId:"dishwasher-map:tray",needId:"CUTLERY_TRAY_NEED",eligibleFactIds:[],eligibleCapabilityIds:capIds("cutleryTray"),policy:"HARD_FILTER"},
    {mappingId:"dishwasher-map:noise",needId:"LOW_NOISE_PRIORITY",eligibleFactIds:factIds("noiseDbA"),eligibleCapabilityIds:[],policy:"SOFT_PREFERENCE"},
    {mappingId:"dishwasher-map:resource",needId:"ECO_RESOURCE_PRIORITY",eligibleFactIds:[...factIds("energyClass"),...factIds("ecoWaterLitres")],eligibleCapabilityIds:[],policy:"SOFT_PREFERENCE"},
    {mappingId:"dishwasher-map:connected",needId:"CONNECTED_CONTROL_NEED",eligibleFactIds:[],eligibleCapabilityIds:capIds("homeConnect"),policy:"HARD_FILTER"},
  ];
  const personaSignals:PersonaPlanningSignal[]=[{signalId:"dishwasher-planning:space-constrained",needIds:["INSTALLATION_ENVELOPE"],authority:"DOMAIN_PLANNING",classification:"DERIVED_PLANNING",decisionUse:"NONE",directCandidateEffect:"NONE"},{signalId:"dishwasher-planning:frequent-large-loads",needIds:["PLACE_SETTING_CAPACITY","CUTLERY_TRAY_NEED"],authority:"DOMAIN_PLANNING",classification:"DERIVED_PLANNING",decisionUse:"NONE",directCandidateEffect:"NONE"},{signalId:"dishwasher-planning:open-plan-home",needIds:["LOW_NOISE_PRIORITY"],authority:"DOMAIN_PLANNING",classification:"DERIVED_PLANNING",decisionUse:"NONE",directCandidateEffect:"NONE"}];
  const interpretations:DailyLifeInterpretation[]=products.flatMap(product=>{const ownFacts=(keys:string[])=>facts.filter(x=>x.offeringId===product.id&&keys.includes(x.key)).map(x=>x.factId),ownCaps=(keys:string[])=>capabilities.filter(x=>x.offeringId===product.id&&keys.includes(x.key)).map(x=>x.capabilityId),row=(suffix:string,text:string,keys:string[],caps:string[],limitations:string[],nonGuarantees:string[],polarity:DailyLifeInterpretation["polarity"]="NEUTRAL"):DailyLifeInterpretation=>({interpretationId:makeId("dishwasher-interpretation",product.id,suffix),offeringId:product.id,text,factIds:ownFacts(keys),capabilityIds:ownCaps(caps),method:"DETERMINISTIC_REVIEWED_MAPPING",reviewedAt:DISHWASHER_REVIEWED_AT,polarity,limitations,nonGuarantees}); const rows=[row("fit","Published body dimensions can support a bounded space check; service, hose, door-swing and clearance requirements remain unknown.",["widthMm","heightMm","depthMm"],[],["Nominal width class is not exact fit."],["No installation-fit guarantee."]),row("capacity","Declared place-setting capacity can be checked against a stated minimum, but does not describe item shape or loading habits.",["capacity"],[],["Place settings are a standardized declaration."],["No household-size or usable-layout guarantee."]),row("features","Verified loading, drying, connectivity and protection feature states can answer exact feature requirements only.",[],["autoOpenDry","cutleryTray","extraDry","homeConnect","aquaStop"],["Absent and unlisted are not interchangeable outside the frozen authority."],["No cleaning, drying, leak-prevention or service guarantee."],"POSITIVE")];if(product.id!=="BEKO_BM4044_TR")rows.push(row("resource","Same-regime energy, Eco-water and noise declarations support bounded comparison; actual use and perceived sound vary.",["energyClass","ecoWaterLitres","noiseDbA"],[],["Comparison requires the same verified regime and Eco-cycle basis."],["No bill, water-use, cleaning or quiet-home guarantee."]));return rows;});
  const evidenceFor=(id:string)=>evidence.filter(x=>x.offeringIds.includes(id)).map(x=>x.evidenceId),mappingsFor=(id:string)=>mappings.filter(m=>[...m.eligibleFactIds,...m.eligibleCapabilityIds].some(entity=>facts.some(x=>x.offeringId===id&&x.factId===entity)||capabilities.some(x=>x.offeringId===id&&x.capabilityId===entity))).map(x=>x.mappingId);
  const semanticPayload={version:DISHWASHER_SEMANTIC_AUTHORITY_VERSION,usageSemantics,needs,mappings,personaSignals,interpretations,comparisonPolicy:"DOMAIN_PACK_ONLY_NEUTRAL_UNKNOWN_FAIL_CLOSED"}; const semanticAuthorityDigest=`sha256:${createHash("sha256").update(JSON.stringify(semanticPayload)).digest("hex")}` as const; const pack=requireXpyDomainPack("APPLIANCES");
  const unsigned:Omit<XpyCatalogRelease,"releaseDigest">={schemaVersion:XPY_CATALOG_VERSION,releaseId:"appliances:dishwasher:catalog-richness:tr:v0.2",releaseVersion:DISHWASHER_RICHNESS_RELEASE_VERSION,departmentId:"APPLIANCES",categoryId:"DISHWASHER",market:"TR",lifecycle:"FROZEN",effectiveAt:DISHWASHER_REVIEWED_AT,compatibility:{runtime:{version:XPY_RUNTIME_VERSION,digest:XPY_RUNTIME_DIGEST,domainPackId:pack.domainPackId},domainPackVersion:pack.domainPackId,semanticAuthorityVersion:DISHWASHER_SEMANTIC_AUTHORITY_VERSION,semanticAuthorityDigest,revisionClass:"SEMANTIC_POLICY_CHANGE",semanticAuthorityChange:"VERSIONED_CHANGE"},sources,evidence,offerings:products.map(x=>({offeringId:x.id,market:"TR",lifecycle:"FROZEN",validFrom:"2026-09-03T12:00:00.000+03:00",identity:{kind:"PRODUCT",manufacturer:x.brand,model:x.model,configuration:x.configuration,identifiers:{productId:x.id}}})),layers:{l1Facts:facts,l2Capabilities:capabilities,l3UsageSemantics:usageSemantics,l4Needs:needs,l4NeedEvidenceMappings:mappings,l5PersonaSignals:personaSignals,l6DailyLifeInterpretations:interpretations,l7ExperienceRules:[],l8DecisionProjections:products.map(x=>({projectionId:makeId("dishwasher-decision-projection",x.id,"exact"),offeringId:x.id,eligibleEvidenceIds:evidenceFor(x.id),needMappingIds:mappingsFor(x.id),limitations:["Reads only exact approved Dishwasher evidence; unknowns remain neutral.","Planning, interpretation, commerce, media and Advisor content cannot filter, rank, or authorize."],disclosures:["The frozen v0.1 Dishwasher candidate and Y authority remains unchanged.","Cleaning, drying, installation, resource and noise outcomes are not guaranteed."],traceability:"EXACT"})),l9AdvisorKnowledge:[]},externalBoundaries:{commerce:"EXTERNAL_VOLATILE_EXACT_IDENTITY_JOIN_ONLY",media:"EXTERNAL_VOLATILE_EXACT_IDENTITY_JOIN_ONLY",offerIdentityAuthority:"NONE",offerRankingAuthority:"NONE",affiliateRankingAuthority:"NONE"}};
  const release=Object.freeze({...unsigned,releaseDigest:xpyCatalogReleaseDigest(unsigned)}); const issues=[...validateXpyCatalogRelease(release),...validateDishwasherRichnessDiscipline(release)]; if(issues.length)throw new TypeError(`DISHWASHER_RICHNESS_INVALID:${issues.join(",")}`); return release;
}

export const DISHWASHER_COMPARISON_DIMENSIONS:readonly XpyComparisonDimension[]=Object.freeze([["capacity","Kapasite","capacity","place settings"],["body-width","Gövde genişliği","widthMm","mm"],["body-height","Gövde yüksekliği","heightMm","mm"],["body-depth","Gövde derinliği","depthMm","mm"],["energy-class","Enerji sınıfı","energyClass","class"],["eco-water","Eco program su tüketimi","ecoWaterLitres","L/eco cycle"],["noise","Akustik hava kaynaklı gürültü","noiseDbA","dB(A) re 1 pW"]].map(([id,humanLabel,key,unit])=>({dimensionId:`dishwasher.${id}`,humanLabel,scope:`EXACT_TR_CONFIGURATION_SAME_REGIME_${unit}`,source:{kind:"FACT" as const,key,unitPolicy:"SAME_UNIT_REQUIRED" as const},authority:"DOMAIN_PACK" as const})));
export function validateDishwasherRichnessDiscipline(release:XpyCatalogRelease):readonly string[]{const issues:string[]=[],expected=products.map(x=>x.id).sort(),actual=release.offerings.map(x=>x.offeringId).sort();if(JSON.stringify(expected)!==JSON.stringify(actual)||release.offerings.some(x=>x.identity.kind!=="PRODUCT"||products.find(p=>p.id===x.offeringId)?.configuration!==x.identity.configuration))issues.push("MEMBERSHIP_OR_IDENTITY_CHANGED");if(release.evidence.some(x=>!x.assertion||x.assertion.applicability.offeringId!==x.offeringIds[0]))issues.push("ASSERTION_LEVEL_PROVENANCE_MISSING");if(release.layers.l5PersonaSignals.some(x=>x.decisionUse!=="NONE"||x.directCandidateEffect!=="NONE"))issues.push("PERSONA_DECISION_INFLUENCE");if(release.layers.l7ExperienceRules.length||release.evidence.some(x=>x.kind==="EXPERIENCE"))issues.push("EXPERIENCE_AUTHORITY_FABRICATED");if(release.layers.l9AdvisorKnowledge.length||release.evidence.some(x=>x.kind==="MANUAL"))issues.push("MANUAL_AUTHORITY_FABRICATED");if(release.layers.l1Facts.some(x=>x.offeringId==="BEKO_BM4044_TR"&&["energyClass","ecoWaterLitres","noiseDbA"].includes(x.key)))issues.push("BEKO_UNKNOWN_REGIME_PROMOTED");if(release.externalBoundaries.offerRankingAuthority!=="NONE"||release.externalBoundaries.affiliateRankingAuthority!=="NONE")issues.push("EXTERNAL_AUTHORITY_LEAKAGE");return issues;}
export const DISHWASHER_RICHNESS_COUNTS=Object.freeze({sources:5,offerings:4,objectiveFacts:25,capabilities:12,usageSemantics:7,needs:8,needEvidenceMappings:7,personaSignals:3,dailyLifeInterpretations:15,experienceRules:0,decisionProjections:4,advisorKnowledge:0,comparisonDimensions:7});
