import{createHash}from"node:crypto";import{readFile}from"node:fs/promises";import path from"node:path";import{describe,expect,it}from"vitest";import{loadActiveBoundedAuthority}from"@/features/appliances/bounded/authority.server";import type{XpyCatalogRelease}from"./contract";import{buildDishwasherRichnessRelease,DISHWASHER_COMPARISON_DIMENSIONS,DISHWASHER_PARENT_ARTIFACT_SHA256,DISHWASHER_RICHNESS_COUNTS,validateDishwasherRichnessDiscipline}from"./dishwasherRichness";import{loadActiveDishwasherRichnessRelease,loadPinnedDishwasherRichnessRelease}from"./dishwasherRichness.server";import{projectAdvisorRead,projectComparisonEvidence}from"./readProjections";import{validateXpyCatalogRelease,xpyCatalogReleaseDigest}from"./validation";
const root=path.resolve(process.cwd()),resign=(release:XpyCatalogRelease):XpyCatalogRelease=>({...release,releaseDigest:xpyCatalogReleaseDigest(release)}),auth=(release:XpyCatalogRelease)=>({purchaseStatus:"PURCHASED" as const,entitlementId:"test",comparisonSetId:"exact-dishwashers",exactOfferingIds:release.offerings.map(x=>x.offeringId)});
describe("Dishwasher XPY_CATALOG richness child",()=>{
 it("preserves exact membership and binds every promoted assertion",()=>{const release=buildDishwasherRichnessRelease();expect(release.offerings.map(x=>x.offeringId)).toEqual(["BOSCH_SMS4IKI62T_TR","SIEMENS_SN25EI63MT_TR","SAMSUNG_DW60DG560FWQTR","BEKO_BM4044_TR"]);expect(validateXpyCatalogRelease(release)).toEqual([]);expect(validateDishwasherRichnessDiscipline(release)).toEqual([]);expect(release.evidence).toHaveLength(DISHWASHER_RICHNESS_COUNTS.objectiveFacts+DISHWASHER_RICHNESS_COUNTS.capabilities);expect(release.evidence.every(x=>x.assertion?.applicability.status==="EXACT")).toBe(true)});
 it("keeps unknown regimes neutral and unsupported manual/experience absent",()=>{const release=buildDishwasherRichnessRelease();expect(release.layers.l1Facts.filter(x=>x.offeringId==="BEKO_BM4044_TR"&&["energyClass","ecoWaterLitres","noiseDbA"].includes(x.key))).toEqual([]);expect(release.layers.l7ExperienceRules).toEqual([]);expect(release.layers.l9AdvisorKnowledge).toEqual([]);expect(release.layers.l5PersonaSignals.every(x=>x.classification==="DERIVED_PLANNING"&&x.decisionUse==="NONE"&&x.directCandidateEffect==="NONE")).toBe(true)});
 it("enforces paid exact-set comparison and read-only Advisor boundaries",()=>{const release=buildDishwasherRichnessRelease(),comparison=projectComparisonEvidence({release,authorization:auth(release),dimensions:DISHWASHER_COMPARISON_DIMENSIONS}),beko=comparison.dimensions.find(x=>x.dimensionId==="dishwasher.energy-class")!.cells.find(x=>x.offeringId==="BEKO_BM4044_TR")!;expect(beko.state).toBe("UNKNOWN");expect(beko.limitations.join(" ")).toContain("not worse");expect(()=>projectComparisonEvidence({release,authorization:{...auth(release),purchaseStatus:"UNPAID"}as never,dimensions:DISHWASHER_COMPARISON_DIMENSIONS})).toThrow("COMPARISON_AUTHORIZATION_REQUIRED");expect(release.offerings.map(x=>projectAdvisorRead({release,authorizedDecision:{decisionId:x.offeringId,exactOfferingId:x.offeringId}})).every(x=>x.readOnly&&x.forbidden.includes("CHANGE_Y_AUTHORIZATION"))).toBe(true)});
 it("detects identity and persona inventions",()=>{const release=buildDishwasherRichnessRelease(),wrong=structuredClone(release)as XpyCatalogRelease;(wrong.offerings[0].identity as{configuration:string}).configuration="wrong";expect(validateDishwasherRichnessDiscipline(resign(wrong))).toContain("MEMBERSHIP_OR_IDENTITY_CHANGED");const persona=structuredClone(release)as XpyCatalogRelease;(persona.layers.l5PersonaSignals[0]as unknown as{directCandidateEffect:string}).directCandidateEffect="FILTER";expect(validateDishwasherRichnessDiscipline(resign(persona))).toContain("PERSONA_DECISION_INFLUENCE")});
 it("loads the pinned child and approved active successors",async()=>{const[pinned,active,authority,raw]=await Promise.all([loadPinnedDishwasherRichnessRelease(root),loadActiveDishwasherRichnessRelease(root),loadActiveBoundedAuthority(root,"DISHWASHER"),readFile(path.join(root,"data/production/appliances/dishwashers/releases/APPLIANCES-DISHWASHER-TR-v0.1/domain-pack.json"),"utf8")]);expect(pinned.status).toBe("READY");expect(active.status).toBe("READY");expect(authority.status).toBe("READY");expect(createHash("sha256").update(raw).digest("hex")).toBe(DISHWASHER_PARENT_ARTIFACT_SHA256);if(active.status==="READY"&&authority.status==="READY"){expect(authority.snapshot.catalogDigest).toBe("5bf0aa3dab0bb16c6db1bc7944370a20f2911caeccc0d48f60aa80cb2a399506");expect(authority.snapshot.semanticDigest).toBe("5bf0aa3dab0bb16c6db1bc7944370a20f2911caeccc0d48f60aa80cb2a399506");expect(authority.snapshot.richnessReleaseDigest).toBe(active.release.releaseDigest);expect(authority.snapshot.pack.selectionPolicy).toEqual({model:"HARD_COMPATIBILITY_THEN_EVIDENCE_BACKED_PARETO",scores:false,weights:false,implicitTieBreak:false})}});
});
