import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import type { XpyCatalogRelease } from "./contract";
import { DISHWASHER_PARENT_ARTIFACT_SHA256, DISHWASHER_PARENT_RELEASE_VERSION, DISHWASHER_RICHNESS_RELEASE_VERSION } from "./dishwasherRichness";
import { validateXpyCatalogRelease } from "./validation";
import { loadActiveMajorApplianceCatalogCategory, MAJOR_APPLIANCE_ADOPTION_CATEGORY_RELEASES, type ActiveMajorApplianceCatalogLoadResult } from "./majorApplianceCatalogActivation.server";
const sha=(raw:string)=>createHash("sha256").update(raw).digest("hex"),releaseRoot=`data/production/appliances/dishwashers/richness/releases/${DISHWASHER_RICHNESS_RELEASE_VERSION}`;
export interface DishwasherRichnessManifest{schemaVersion:"dishwasher-richness-manifest/v1";releaseVersion:typeof DISHWASHER_RICHNESS_RELEASE_VERSION;parent:{releaseVersion:typeof DISHWASHER_PARENT_RELEASE_VERSION;artifactSha256:typeof DISHWASHER_PARENT_ARTIFACT_SHA256;relationship:"IMMUTABLE_CHILD_NO_OVERWRITE"};catalogArtifactSha256:string;semanticArtifactSha256:string;coverageArtifactSha256:string;projectionsArtifactSha256:string;membershipDigest:string}
export interface DishwasherRichnessActivationEvent{schemaVersion:"dishwasher-richness-activation/v1";activationId:string;activatedAt:string;state:"ACTIVE_READ_ONLY_SEMANTIC_COMPOSITE";releaseVersion:typeof DISHWASHER_RICHNESS_RELEASE_VERSION;releaseDigest:string;catalogArtifactSha256:string;semanticArtifactSha256:string;projectionsArtifactSha256:string;immutableManifestSha256:string;membershipDigest:string;decisionAuthority:{releaseVersion:typeof DISHWASHER_PARENT_RELEASE_VERSION;artifactSha256:typeof DISHWASHER_PARENT_ARTIFACT_SHA256;ySemantics:"UNCHANGED"};productOwnerApproval:{approved:true;workUnitId:"WU-XPY-APPL-DISHWASHER-CATALOG-RICHNESS-01";scope:"COMPOSITE_READ_ONLY_RICHNESS_ACTIVATION"};review:readonly {check:string;status:"PASS";evidence:string}[];remainingUnknowns:readonly string[]}
type Pinned={status:"READY";release:XpyCatalogRelease;manifest:DishwasherRichnessManifest}|{status:"FAILED_CLOSED";reason:string};
export async function loadPinnedDishwasherRichnessRelease(root:string):Promise<Pinned>{try{const base=path.join(root,releaseRoot),[manifestRaw,releaseRaw,semanticRaw,coverageRaw,projectionsRaw,parentRaw]=await Promise.all(["manifest.json","catalog-release.json","semantic-registry.json","coverage-report.json","read-projections.json"].map(name=>readFile(path.join(base,name),"utf8")).concat(readFile(path.join(root,`data/production/appliances/dishwashers/releases/${DISHWASHER_PARENT_RELEASE_VERSION}/domain-pack.json`),"utf8")));const manifest=JSON.parse(manifestRaw) as DishwasherRichnessManifest,release=JSON.parse(releaseRaw) as XpyCatalogRelease;if(manifest.schemaVersion!=="dishwasher-richness-manifest/v1"||manifest.releaseVersion!==DISHWASHER_RICHNESS_RELEASE_VERSION||manifest.parent.releaseVersion!==DISHWASHER_PARENT_RELEASE_VERSION||manifest.parent.artifactSha256!==DISHWASHER_PARENT_ARTIFACT_SHA256||sha(parentRaw)!==DISHWASHER_PARENT_ARTIFACT_SHA256)return{status:"FAILED_CLOSED",reason:"PARENT_OR_MANIFEST_INVALID"};if(sha(releaseRaw)!==manifest.catalogArtifactSha256||sha(semanticRaw)!==manifest.semanticArtifactSha256||sha(coverageRaw)!==manifest.coverageArtifactSha256||sha(projectionsRaw)!==manifest.projectionsArtifactSha256||validateXpyCatalogRelease(release).length)return{status:"FAILED_CLOSED",reason:"ARTIFACT_OR_RELEASE_INVALID"};const ids=release.offerings.map(x=>x.offeringId).sort();if(ids.length!==4||sha(ids.join("\n"))!==manifest.membershipDigest)return{status:"FAILED_CLOSED",reason:"MEMBERSHIP_MISMATCH"};return{status:"READY",release:Object.freeze(release),manifest:Object.freeze(manifest)}}catch{return{status:"FAILED_CLOSED",reason:"DISHWASHER_RICHNESS_RELEASE_MISSING_OR_INVALID"}}}
export async function loadActiveDishwasherRichnessRelease(root:string):Promise<(Pinned&{activation:DishwasherRichnessActivationEvent})|ActiveMajorApplianceCatalogLoadResult>{try{const active=JSON.parse(await readFile(path.join(root,"data/production/appliances/dishwashers/active.json"),"utf8")) as {schemaVersion?:string;releaseVersion?:string;artifactSha256?:string;richness?:{releaseVersion?:string;releaseDigest?:string;catalogArtifactSha256?:string;membershipDigest?:string;activationManifest?:string;activationManifestSha256?:string;lifecycle?:string}};if(active.richness?.releaseVersion===MAJOR_APPLIANCE_ADOPTION_CATEGORY_RELEASES.DISHWASHER)return loadActiveMajorApplianceCatalogCategory(root,"DISHWASHER");if(active.schemaVersion!=="appliances-bounded-active-pointer/v2"||active.releaseVersion!==DISHWASHER_PARENT_RELEASE_VERSION||active.artifactSha256!==DISHWASHER_PARENT_ARTIFACT_SHA256||active.richness?.releaseVersion!==DISHWASHER_RICHNESS_RELEASE_VERSION||active.richness.lifecycle!=="ACTIVE_READ_ONLY")return{status:"FAILED_CLOSED",reason:"ACTIVE_COMPOSITE_POINTER_INVALID"};const pinned=await loadPinnedDishwasherRichnessRelease(root);if(pinned.status!=="READY")return pinned;if(active.richness.releaseDigest!==pinned.release.releaseDigest||active.richness.catalogArtifactSha256!==pinned.manifest.catalogArtifactSha256||active.richness.membershipDigest!==pinned.manifest.membershipDigest)return{status:"FAILED_CLOSED",reason:"ACTIVE_RELEASE_BINDING_MISMATCH"};const governanceRoot=path.resolve(root,"data/production/appliances/dishwashers/richness/governance/activation-events"),activationPath=path.resolve(root,active.richness.activationManifest??"");if(!activationPath.startsWith(`${governanceRoot}${path.sep}`))return{status:"FAILED_CLOSED",reason:"UNSAFE_ACTIVATION_MANIFEST_PATH"};const raw=await readFile(activationPath,"utf8");if(sha(raw)!==active.richness.activationManifestSha256)return{status:"FAILED_CLOSED",reason:"ACTIVATION_MANIFEST_DIGEST_MISMATCH"};const activation=JSON.parse(raw) as DishwasherRichnessActivationEvent;if(activation.schemaVersion!=="dishwasher-richness-activation/v1"||activation.state!=="ACTIVE_READ_ONLY_SEMANTIC_COMPOSITE"||activation.releaseDigest!==pinned.release.releaseDigest||activation.decisionAuthority.artifactSha256!==DISHWASHER_PARENT_ARTIFACT_SHA256||activation.decisionAuthority.ySemantics!=="UNCHANGED"||!activation.productOwnerApproval.approved||activation.review.some(x=>x.status!=="PASS"))return{status:"FAILED_CLOSED",reason:"ACTIVATION_MANIFEST_INVALID"};return{...pinned,activation:Object.freeze(activation)}}catch{return{status:"FAILED_CLOSED",reason:"ACTIVE_DISHWASHER_RICHNESS_UNAVAILABLE"}}}
