import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { loadActiveRefrigeratorAuthority } from "@/features/appliances/refrigerator/authority.server";
import type { XpyCatalogRelease } from "./contract";
import { projectAdvisorRead, projectComparisonEvidence } from "./readProjections";
import { buildRefrigeratorRichnessRelease, REFRIGERATOR_COMPARISON_DIMENSIONS, REFRIGERATOR_PARENT_ARTIFACT_SHA256, REFRIGERATOR_RICHNESS_COUNTS, validateRefrigeratorRichnessDiscipline } from "./refrigeratorRichness";
import { loadActiveRefrigeratorRichnessRelease, loadPinnedRefrigeratorRichnessRelease } from "./refrigeratorRichness.server";
import { validateXpyCatalogRelease, xpyCatalogReleaseDigest } from "./validation";
const root = path.resolve(process.cwd()), resign = (release: XpyCatalogRelease): XpyCatalogRelease => ({ ...release, releaseDigest: xpyCatalogReleaseDigest(release) });
const auth = (release: XpyCatalogRelease) => ({ purchaseStatus: "PURCHASED" as const, entitlementId: "test", comparisonSetId: "exact-refrigerators", exactOfferingIds: release.offerings.map((item) => item.offeringId) });

describe("Refrigerator XPY_CATALOG richness child", () => {
  it("preserves exact membership and binds every assertion to exact provenance", () => { const release = buildRefrigeratorRichnessRelease(); expect(release.offerings.map((item) => item.offeringId)).toEqual(["SAMSUNG_RB34C6B0E12_TR", "BOSCH_KGN55CIE0N_TR", "SIEMENS_KG56NVWD0N_TR", "LG_GC_B569NLLM_TR"]); expect(validateXpyCatalogRelease(release)).toEqual([]); expect(validateRefrigeratorRichnessDiscipline(release)).toEqual([]); expect(release.evidence).toHaveLength(REFRIGERATOR_RICHNESS_COUNTS.objectiveFacts + REFRIGERATOR_RICHNESS_COUNTS.capabilities); expect(release.evidence.every((item) => item.assertion?.applicability.status === "EXACT")).toBe(true); });
  it("keeps LG conflicts neutral, manuals/experience absent, and persona inert", () => { const release = buildRefrigeratorRichnessRelease(); expect(release.layers.l1Facts.filter((item) => item.offeringId === "LG_GC_B569NLLM_TR" && ["widthMm", "depthMm"].includes(item.key))).toEqual([]); expect(release.layers.l7ExperienceRules).toEqual([]); expect(release.layers.l9AdvisorKnowledge).toEqual([]); expect(release.layers.l5PersonaSignals.every((item) => item.classification === "DERIVED_PLANNING" && item.decisionUse === "NONE" && item.directCandidateEffect === "NONE")).toBe(true); });
  it("enforces paid comparison and read-only Advisor boundaries", () => { const release = buildRefrigeratorRichnessRelease(), comparison = projectComparisonEvidence({ release, authorization: auth(release), dimensions: REFRIGERATOR_COMPARISON_DIMENSIONS }); const lgWidth = comparison.dimensions.find((item) => item.dimensionId === "refrigerator.body-width")!.cells.find((item) => item.offeringId === "LG_GC_B569NLLM_TR")!; expect(lgWidth).toMatchObject({ state: "UNKNOWN" }); expect(lgWidth.limitations.join(" ")).toContain("not worse"); expect(() => projectComparisonEvidence({ release, authorization: { ...auth(release), purchaseStatus: "UNPAID" } as never, dimensions: REFRIGERATOR_COMPARISON_DIMENSIONS })).toThrow("COMPARISON_AUTHORIZATION_REQUIRED"); expect(release.offerings.map((item) => projectAdvisorRead({ release, authorizedDecision: { decisionId: item.offeringId, exactOfferingId: item.offeringId } })).every((item) => item.forbidden.includes("CHANGE_Y_AUTHORIZATION"))).toBe(true); });
  it("detects identity, manual, experience and persona policy inventions", () => { const release = buildRefrigeratorRichnessRelease(), wrong = structuredClone(release) as XpyCatalogRelease; (wrong.offerings[0].identity as { configuration: string }).configuration = "wrong"; expect(validateRefrigeratorRichnessDiscipline(resign(wrong))).toContain("MEMBERSHIP_OR_IDENTITY_CHANGED"); const persona = structuredClone(release) as XpyCatalogRelease; (persona.layers.l5PersonaSignals[0] as unknown as { directCandidateEffect: string }).directCandidateEffect = "FILTER"; expect(validateRefrigeratorRichnessDiscipline(resign(persona))).toContain("PERSONA_DECISION_INFLUENCE"); });
  it("loads the pinned child and byte-pinned parent", async () => { expect((await loadPinnedRefrigeratorRichnessRelease(root)).status).toBe("READY"); const raw = await readFile(path.join(root, "data/production/appliances/refrigerators/releases/APPLIANCES-REFRIGERATOR-TR-v0.1/domain-pack.json"), "utf8"); expect(createHash("sha256").update(raw).digest("hex")).toBe(REFRIGERATOR_PARENT_ARTIFACT_SHA256); });
  it("loads the approved active richness and decision successors", async () => { const [richness, authority] = await Promise.all([loadActiveRefrigeratorRichnessRelease(root), loadActiveRefrigeratorAuthority(root)]); expect(richness.status).toBe("READY"); expect(authority.status).toBe("READY"); if (richness.status !== "READY" || authority.status !== "READY") return; expect(authority.snapshot.catalogDigest).toBe("5b15f32f26e207fa83208a97208f189367aa98e404d4f1f709a520a06b875e0b"); expect(authority.snapshot.semanticDigest).toBe("5b15f32f26e207fa83208a97208f189367aa98e404d4f1f709a520a06b875e0b"); expect(authority.snapshot.richnessReleaseDigest).toBe(richness.release.releaseDigest); expect(authority.snapshot.pack.selectionPolicy).toEqual({ model: "HARD_COMPATIBILITY_THEN_EVIDENCE_BACKED_PARETO", scores: false, weights: false, implicitTieBreak: false }); });
});
