import { createHash } from "node:crypto";

import { requireXpyDomainPack } from "../domainPacks";
import { XPY_RUNTIME_DIGEST, XPY_RUNTIME_VERSION } from "../runtimeContract";
import type { Capability, CatalogEvidence, CatalogSource, DailyLifeInterpretation, NeedEvidenceMapping, ObjectiveFact, PersonaPlanningSignal, UsageSemantic, UserNeed, XpyCatalogRelease, XpyComparisonDimension } from "./contract";
import { XPY_CATALOG_VERSION } from "./contract";
import { validateXpyCatalogRelease, xpyCatalogReleaseDigest } from "./validation";

export const REFRIGERATOR_RICHNESS_RELEASE_VERSION = "APPLIANCES-REFRIGERATOR-CATALOG-RICHNESS-TR-v0.2" as const;
export const REFRIGERATOR_PARENT_RELEASE_VERSION = "APPLIANCES-REFRIGERATOR-TR-v0.1" as const;
export const REFRIGERATOR_PARENT_ARTIFACT_SHA256 = "4b9c4aef891c46c023c67a1564d87652e1d63fe25ef9482c7ff830548cf9e825" as const;
export const REFRIGERATOR_SEMANTIC_AUTHORITY_VERSION = "REFRIGERATOR_SEMANTIC_REGISTRY/v0.2" as const;
export const REFRIGERATOR_REVIEWED_AT = "2026-09-04T19:30:00.000+03:00" as const;

const products = [
  { id: "SAMSUNG_RB34C6B0E12_TR", brand: "Samsung", model: "RB34C6B0E12/TR", configuration: "Samsung RB34C6B0E12/TR / Türkiye / solo / alttan donduruculu kombi / No Frost", product: "SAMSUNG-RB34C6B0E12-TR-PRODUCT", fiche: "SAMSUNG-RB34C6B0E12-TR-FICHE", facts: { installation: "FREESTANDING", form: "BOTTOM_FREEZER_COMBI", frostTechnology: "NO_FROST", widthMm: 595, heightMm: 1853, depthMm: 658, totalNetLitres: 344, freshFoodNetLitres: 230, freezerNetLitres: 114, freezingCapacityKg24h: 8, energyClass: "E", annualEnergyKwh: 254, noiseDbA: 35, noiseClass: "B", ambientMinC: 10, ambientMaxC: 43 }, capabilities: { noFrost: true, automaticDefrostFresh: true, automaticDefrostFreezer: true, reversibleDoor: true, freezerDrawers: 3, fastCooling: true, fastFreezing: true, smartConnectivity: true } },
  { id: "BOSCH_KGN55CIE0N_TR", brand: "Bosch", model: "KGN55CIE0N", configuration: "Bosch KGN55CIE0N / Türkiye / solo / alttan donduruculu kombi / No Frost", product: "BOSCH-KGN55CIE0N-TR-PRODUCT", fiche: "BOSCH-KGN55CIE0N-TR-FICHE", facts: { installation: "FREESTANDING", form: "BOTTOM_FREEZER_COMBI", frostTechnology: "NO_FROST", widthMm: 700, heightMm: 1860, depthMm: 800, totalNetLitres: 483, freshFoodNetLitres: 375, freezerNetLitres: 108, freezingCapacityKg24h: 10, energyClass: "E", annualEnergyKwh: 261, noiseDbA: 40, noiseClass: "C", ambientMinC: 10, ambientMaxC: 43 }, capabilities: { noFrost: true, automaticDefrostFresh: true, automaticDefrostFreezer: true, fastCooling: true, fastFreezing: true, bigBox: true, preservationCompartment: true } },
  { id: "SIEMENS_KG56NVWD0N_TR", brand: "Siemens", model: "KG56NVWD0N", configuration: "Siemens KG56NVWD0N / Türkiye / solo / alttan donduruculu kombi / Total noFrost", product: "SIEMENS-KG56NVWD0N-TR-PRODUCT", fiche: "SIEMENS-KG56NVWD0N-TR-FICHE", facts: { installation: "FREESTANDING", form: "BOTTOM_FREEZER_COMBI", frostTechnology: "NO_FROST", widthMm: 695, heightMm: 1862, depthMm: 755, totalNetLitres: 500, freshFoodNetLitres: 223, chillerNetLitres: 119, freezerNetLitres: 158, freezingCapacityKg24h: 9, energyClass: "D", annualEnergyKwh: 261, noiseDbA: 35, noiseClass: "B", ambientMinC: 10, ambientMaxC: 43 }, capabilities: { noFrost: true, automaticDefrostFresh: true, automaticDefrostChiller: true, automaticDefrostFreezer: true, fastFreezing: true, smartConnectivity: true, preservationCompartment: true } },
  { id: "LG_GC_B569NLLM_TR", brand: "LG", model: "GC-B569NLLM", configuration: "LG GC-B569NLLM / Türkiye / bağımsız / alttan donduruculu kombi / No Frost", product: "LG-GC-B569NLLM-TR-PRODUCT", fiche: "LG-GC-B569NLLM-TR-FICHE", facts: { installation: "FREESTANDING", form: "BOTTOM_FREEZER_COMBI", frostTechnology: "NO_FROST", heightMm: 1850, totalNetLitres: 462, freshFoodNetLitres: 329, freezerNetLitres: 133, freezingCapacityKg24h: 7, energyClass: "E", annualEnergyKwh: 282, noiseDbA: 41, noiseClass: "C", ambientMinC: 16, ambientMaxC: 43 }, capabilities: { noFrost: true, automaticDefrostFresh: true, automaticDefrostFreezer: true, fastFreezing: true, doorCooling: true, smartDiagnosis: true } },
] as const;

const sourceRows = [
  ["SAMSUNG-RB34C6B0E12-TR-PRODUCT", "https://www.samsung.com/tr/business/refrigerators/bottom-mount-freezer/bespoke-bmfreezer-with-smartthings-ai-energy-mode-344l-clean-white-rb34c6b0e12-tr/", "OFFICIAL"], ["SAMSUNG-RB34C6B0E12-TR-FICHE", "https://images.samsung.com/is/content/samsung/p6/common/energylabel/common-energylabel-rb34c6b0e12-tr-productfiche.pdf", "REGULATORY"],
  ["BOSCH-KGN55CIE0N-TR-PRODUCT", "https://www.bosch-home.com.tr/tr/product/prboschfridge70/KGN55CIE0N", "OFFICIAL"], ["BOSCH-KGN55CIE0N-TR-FICHE", "https://media3.bsh-group.com/Documents/eudatasheet/tr-TR/KGN55CIE0N.pdf", "REGULATORY"],
  ["SIEMENS-KG56NVWD0N-TR-PRODUCT", "https://www.siemens-home.bsh-group.com/tr/tr/product/buzdolaplari-ve-derin-dondurucular/solo-buzdolaplari-ve-derin-dondurucular/alttan-donduruculu-solo-buzdolaplari/KG56NVWD0N", "OFFICIAL"], ["SIEMENS-KG56NVWD0N-TR-FICHE", "https://media3.bsh-group.com/Documents/eudatasheet/tr-TR/KG56NVWD0N.pdf", "REGULATORY"],
  ["LG-GC-B569NLLM-TR-PRODUCT", "https://www.lg.com/tr/buzdolabi/uzun-buzdolabi-donduruculari1/gc-b569nllm/", "OFFICIAL"], ["LG-GC-B569NLLM-TR-FICHE", "https://www.lg.com/tr/lgecs.downloadFile.ldwf?DOC_ID=20250520248484&FILE_NAME=T%C3%BCrkiye+PIS+GC-B569NLLM.pdf&GSRI_DOC=GSRI&ORIGINAL_NAME_b1_a1=T%C3%BCrkiye+PIS+GC-B569NLLM%5B20250520115146887%5D.pdf&SPEC_DOWNLOAD=N&TC=DwnCmd", "REGULATORY"],
] as const;
const sources: CatalogSource[] = sourceRows.map(([sourceId, uri, kind]) => ({ sourceId, uri, kind, version: "parent-reviewed-2026-09-03", observedAt: "2026-09-03T00:00:00.000+03:00", reviewedAt: REFRIGERATOR_REVIEWED_AT, market: "TR", applicabilityStatus: "EXACT", status: "REVIEWED", language: "tr-TR" }));
const slug = (value: string) => value.replace(/[^A-Za-z0-9]+/gu, "-").replace(/^-|-$/gu, "").toLowerCase();
const makeId = (prefix: string, ...parts: string[]) => `${prefix}:${parts.map(slug).join(":")}`;
const ficheKeys = new Set(["totalNetLitres", "freshFoodNetLitres", "chillerNetLitres", "freezerNetLitres", "freezingCapacityKg24h", "energyClass", "annualEnergyKwh", "noiseDbA", "noiseClass", "ambientMinC", "ambientMaxC"]);
const unitFor = (key: string) => key.endsWith("Mm") ? "mm" : key.endsWith("Litres") ? "L" : key === "freezingCapacityKg24h" ? "kg/24h" : key === "annualEnergyKwh" ? "kWh/year" : key === "noiseDbA" ? "dB(A) re 1 pW" : key.endsWith("C") ? "°C" : undefined;

export function buildRefrigeratorRichnessRelease(): XpyCatalogRelease {
  const evidence: CatalogEvidence[] = [], facts: ObjectiveFact[] = [], capabilities: Capability[] = [];
  for (const product of products) {
    for (const [key, value] of Object.entries(product.facts)) {
      const evidenceId = makeId("refrigerator-evidence", product.id, "fact", key), sourceId = ficheKeys.has(key) ? product.fiche : product.product, unit = unitFor(key);
      evidence.push({ evidenceId, kind: "TECHNICAL", sourceId, assertionId: makeId("refrigerator-assertion", product.id, key), offeringIds: [product.id], market: "TR", observedAt: "2026-09-03T00:00:00.000+03:00", reviewedAt: REFRIGERATOR_REVIEWED_AT, confidence: "HIGH", status: "REVIEWED", limitations: key === "annualEnergyKwh" || key === "noiseDbA" ? ["Comparable only within the approved TR_2019_2016_AB declaration regime; no household outcome promise."] : [], assertion: { locator: `domain-pack.products[${product.id}].technicalFacts.${key}`, value, ...(unit ? { unit } : {}), applicability: { offeringId: product.id, market: "TR", model: product.model, configuration: product.configuration, status: "EXACT" } } });
      facts.push({ factId: makeId("refrigerator-fact", product.id, key), offeringId: product.id, key, value, ...(unit ? { unit } : {}), evidenceId });
    }
    for (const [key, raw] of Object.entries(product.capabilities)) {
      const evidenceId = makeId("refrigerator-evidence", product.id, "capability", key), value = typeof raw === "number" ? raw : Boolean(raw), state = raw ? "PRESENT" as const : "ABSENT" as const;
      evidence.push({ evidenceId, kind: "CAPABILITY", sourceId: product.product, assertionId: makeId("refrigerator-assertion", product.id, key), offeringIds: [product.id], market: "TR", observedAt: "2026-09-03T00:00:00.000+03:00", reviewedAt: REFRIGERATOR_REVIEWED_AT, confidence: "HIGH", status: "REVIEWED", limitations: ["Capability presence does not guarantee a preservation, convenience, connectivity, or storage outcome."], assertion: { locator: `domain-pack.products[${product.id}].capabilities.${key}`, value, applicability: { offeringId: product.id, market: "TR", model: product.model, configuration: product.configuration, status: "EXACT" } } });
      capabilities.push({ capabilityId: makeId("refrigerator-capability", product.id, key), offeringId: product.id, key, state, evidenceId, limitations: ["Presence only; outcome and operating conditions are not inferred."] });
    }
  }
  const factIds = (...keys: string[]) => facts.filter((item) => keys.includes(item.key)).map((item) => item.factId);
  const capIds = (...keys: string[]) => capabilities.filter((item) => keys.includes(item.key)).map((item) => item.capabilityId);
  const usageSemantics: UsageSemantic[] = [
    { semanticId: "refrigerator-semantic:installation", meaning: "Body dimensions can be checked only against matching user space bounds; door-open envelope and required clearances remain unknown for every product in this release.", factIds: factIds("widthMm", "heightMm", "depthMm"), capabilityIds: [] },
    { semanticId: "refrigerator-semantic:capacity", meaning: "Total net, fresh-food net, chiller net, freezer net and gross capacity are distinct; no missing compartment value may be substituted or inferred.", factIds: factIds("totalNetLitres", "freshFoodNetLitres", "chillerNetLitres", "freezerNetLitres"), capabilityIds: [] },
    { semanticId: "refrigerator-semantic:energy", meaning: "Annual energy is a standardized declaration within the approved regime, not a household bill promise.", factIds: factIds("annualEnergyKwh", "energyClass"), capabilityIds: [] },
    { semanticId: "refrigerator-semantic:noise", meaning: "Standardized acoustic airborne noise supports like-for-like evidence display; it does not guarantee perceived quietness in a home.", factIds: factIds("noiseDbA", "noiseClass"), capabilityIds: [] },
    { semanticId: "refrigerator-semantic:ambient", meaning: "Published ambient limits are operating-envelope evidence, not a guarantee for a particular room or installation.", factIds: factIds("ambientMinC", "ambientMaxC"), capabilityIds: [] },
    { semanticId: "refrigerator-semantic:preservation", meaning: "Named preservation and cooling capabilities establish presence only; storage duration and food outcome are not guaranteed.", factIds: [], capabilityIds: capIds("preservationCompartment", "fastCooling", "fastFreezing", "doorCooling") },
    { semanticId: "refrigerator-semantic:connectivity", meaning: "Connectivity or diagnosis capability establishes feature presence only and does not establish service availability or an energy outcome.", factIds: [], capabilityIds: capIds("smartConnectivity", "smartDiagnosis") },
  ];
  const needs: UserNeed[] = [["INSTALLATION_ENVELOPE", "Physical installation envelope"], ["FRESH_FOOD_STORAGE_NEED", "Fresh-food net storage need"], ["FREEZER_STORAGE_NEED", "Freezer net storage need"], ["TOTAL_NET_CAPACITY_PRIORITY", "Total net capacity priority"], ["PRESERVATION_COMPARTMENT_NEED", "Named preservation compartment need"], ["LOW_NOISE_PRIORITY", "Comparable standardized-noise priority"], ["ENERGY_PRIORITY", "Comparable declared-energy priority"], ["SMART_CONNECTIVITY", "Smart connectivity need"], ["BUDGET_SENSITIVITY", "Budget evaluated only through external current-price authority"]].map(([needId, meaning]) => ({ needId, meaning }));
  const mappings: NeedEvidenceMapping[] = [
    { mappingId: "refrigerator-map:installation", needId: "INSTALLATION_ENVELOPE", eligibleFactIds: factIds("widthMm", "heightMm", "depthMm"), eligibleCapabilityIds: [], policy: "HARD_FILTER" },
    { mappingId: "refrigerator-map:fresh", needId: "FRESH_FOOD_STORAGE_NEED", eligibleFactIds: factIds("freshFoodNetLitres"), eligibleCapabilityIds: [], policy: "HARD_FILTER" },
    { mappingId: "refrigerator-map:freezer", needId: "FREEZER_STORAGE_NEED", eligibleFactIds: factIds("freezerNetLitres"), eligibleCapabilityIds: [], policy: "HARD_FILTER" },
    { mappingId: "refrigerator-map:total", needId: "TOTAL_NET_CAPACITY_PRIORITY", eligibleFactIds: factIds("totalNetLitres"), eligibleCapabilityIds: [], policy: "SOFT_PREFERENCE" },
    { mappingId: "refrigerator-map:preservation", needId: "PRESERVATION_COMPARTMENT_NEED", eligibleFactIds: factIds("chillerNetLitres"), eligibleCapabilityIds: capIds("preservationCompartment"), policy: "HARD_FILTER" },
    { mappingId: "refrigerator-map:noise", needId: "LOW_NOISE_PRIORITY", eligibleFactIds: factIds("noiseDbA"), eligibleCapabilityIds: [], policy: "SOFT_PREFERENCE" },
    { mappingId: "refrigerator-map:energy", needId: "ENERGY_PRIORITY", eligibleFactIds: factIds("annualEnergyKwh", "energyClass"), eligibleCapabilityIds: [], policy: "SOFT_PREFERENCE" },
    { mappingId: "refrigerator-map:smart", needId: "SMART_CONNECTIVITY", eligibleFactIds: [], eligibleCapabilityIds: capIds("smartConnectivity"), policy: "HARD_FILTER" },
  ];
  const personaSignals: PersonaPlanningSignal[] = [
    { signalId: "refrigerator-planning:space-constrained", needIds: ["INSTALLATION_ENVELOPE"], authority: "DOMAIN_PLANNING", classification: "DERIVED_PLANNING", decisionUse: "NONE", directCandidateEffect: "NONE" },
    { signalId: "refrigerator-planning:storage-intensive", needIds: ["FRESH_FOOD_STORAGE_NEED", "FREEZER_STORAGE_NEED", "TOTAL_NET_CAPACITY_PRIORITY"], authority: "DOMAIN_PLANNING", classification: "DERIVED_PLANNING", decisionUse: "NONE", directCandidateEffect: "NONE" },
    { signalId: "refrigerator-planning:open-plan-home", needIds: ["LOW_NOISE_PRIORITY"], authority: "DOMAIN_PLANNING", classification: "DERIVED_PLANNING", decisionUse: "NONE", directCandidateEffect: "NONE" },
  ];
  const interpretations: DailyLifeInterpretation[] = products.flatMap((product) => {
    const ownFacts = (keys: string[]) => facts.filter((item) => item.offeringId === product.id && keys.includes(item.key)).map((item) => item.factId);
    const ownCaps = (keys: string[]) => capabilities.filter((item) => item.offeringId === product.id && keys.includes(item.key)).map((item) => item.capabilityId);
    const row = (suffix: string, text: string, keys: string[], caps: string[], limitations: string[], nonGuarantees: string[], polarity: DailyLifeInterpretation["polarity"] = "NEUTRAL"): DailyLifeInterpretation => ({ interpretationId: makeId("refrigerator-interpretation", product.id, suffix), offeringId: product.id, text, factIds: ownFacts(keys), capabilityIds: ownCaps(caps), method: "DETERMINISTIC_REVIEWED_MAPPING", reviewedAt: REFRIGERATOR_REVIEWED_AT, polarity, limitations, nonGuarantees });
    return [
      row("capacity", "Published net compartment volumes can be checked against the matching stated storage need; the figures do not describe shelf usability or household fit by themselves.", ["totalNetLitres", "freshFoodNetLitres", "chillerNetLitres", "freezerNetLitres"], [], ["Compartment types remain distinct and missing values stay unknown."], ["No household-size or usable-layout guarantee."]),
      row("installation", product.id === "LG_GC_B569NLLM_TR" ? "The height is known, but conflicting official width and depth values remain unknown and cannot support an installation-fit conclusion." : "Published body dimensions can support a bounded space check; door-open depth and clearances remain unknown.", ["widthMm", "heightMm", "depthMm"], [], ["Door swing, ventilation and manufacturer installation instructions remain separate."], ["No installation-fit guarantee without a complete envelope."], product.id === "LG_GC_B569NLLM_TR" ? "UNKNOWN" : "NEUTRAL"),
      row("performance", "Standardized energy and noise declarations permit like-for-like evidence display, while household consumption and perceived sound depend on use and environment.", ["annualEnergyKwh", "energyClass", "noiseDbA", "noiseClass"], [], ["Only the approved common declaration regime is comparable."], ["No low-bill or quiet-home guarantee."]),
      row("capabilities", "Verified feature presence can inform a matching stated need, but named cooling, preservation, connectivity and diagnosis features do not prove an outcome.", [], ["preservationCompartment", "fastCooling", "fastFreezing", "doorCooling", "smartConnectivity", "smartDiagnosis"], ["Use conditions and availability may be model-specific."], ["No storage-duration, food-safety, service, or energy-saving guarantee."], "POSITIVE"),
    ];
  });
  const evidenceFor = (id: string) => evidence.filter((item) => item.offeringIds.includes(id)).map((item) => item.evidenceId);
  const mappingsFor = (id: string) => mappings.filter((mapping) => [...mapping.eligibleFactIds, ...mapping.eligibleCapabilityIds].some((entity) => facts.some((item) => item.offeringId === id && item.factId === entity) || capabilities.some((item) => item.offeringId === id && item.capabilityId === entity))).map((item) => item.mappingId);
  const semanticPayload = { version: REFRIGERATOR_SEMANTIC_AUTHORITY_VERSION, usageSemantics, needs, mappings, personaSignals, interpretations, comparisonPolicy: "DOMAIN_PACK_ONLY_NEUTRAL_UNKNOWN_FAIL_CLOSED" };
  const semanticAuthorityDigest = `sha256:${createHash("sha256").update(JSON.stringify(semanticPayload)).digest("hex")}` as const;
  const pack = requireXpyDomainPack("APPLIANCES");
  const unsigned: Omit<XpyCatalogRelease, "releaseDigest"> = { schemaVersion: XPY_CATALOG_VERSION, releaseId: "appliances:refrigerator:catalog-richness:tr:v0.2", releaseVersion: REFRIGERATOR_RICHNESS_RELEASE_VERSION, departmentId: "APPLIANCES", categoryId: "REFRIGERATOR", market: "TR", lifecycle: "FROZEN", effectiveAt: REFRIGERATOR_REVIEWED_AT, compatibility: { runtime: { version: XPY_RUNTIME_VERSION, digest: XPY_RUNTIME_DIGEST, domainPackId: pack.domainPackId }, domainPackVersion: pack.domainPackId, semanticAuthorityVersion: REFRIGERATOR_SEMANTIC_AUTHORITY_VERSION, semanticAuthorityDigest, revisionClass: "SEMANTIC_POLICY_CHANGE", semanticAuthorityChange: "VERSIONED_CHANGE" }, sources, evidence, offerings: products.map((item) => ({ offeringId: item.id, market: "TR", lifecycle: "FROZEN", validFrom: "2026-09-03T12:00:00.000+03:00", identity: { kind: "PRODUCT", manufacturer: item.brand, model: item.model, configuration: item.configuration, identifiers: { productId: item.id } } })), layers: { l1Facts: facts, l2Capabilities: capabilities, l3UsageSemantics: usageSemantics, l4Needs: needs, l4NeedEvidenceMappings: mappings, l5PersonaSignals: personaSignals, l6DailyLifeInterpretations: interpretations, l7ExperienceRules: [], l8DecisionProjections: products.map((item) => ({ projectionId: makeId("refrigerator-decision-projection", item.id), offeringId: item.id, eligibleEvidenceIds: evidenceFor(item.id), needMappingIds: mappingsFor(item.id), limitations: ["This projection reads only approved Refrigerator evidence; unknowns are neutral and dependent boundaries fail closed.", "Persona, daily-life interpretation, claims, price, media and Advisor content cannot filter, rank or authorize."], disclosures: ["The frozen v0.1 Refrigerator candidate and Y authority remains unchanged.", "Capacity, preservation, energy, noise and installation outcomes are not guaranteed."], traceability: "EXACT" })), l9AdvisorKnowledge: [] }, externalBoundaries: { commerce: "EXTERNAL_VOLATILE_EXACT_IDENTITY_JOIN_ONLY", media: "EXTERNAL_VOLATILE_EXACT_IDENTITY_JOIN_ONLY", offerIdentityAuthority: "NONE", offerRankingAuthority: "NONE", affiliateRankingAuthority: "NONE" } };
  const release = Object.freeze({ ...unsigned, releaseDigest: xpyCatalogReleaseDigest(unsigned) });
  const issues = [...validateXpyCatalogRelease(release), ...validateRefrigeratorRichnessDiscipline(release)];
  if (issues.length) throw new TypeError(`REFRIGERATOR_RICHNESS_INVALID:${issues.join(",")}`);
  return release;
}

export const REFRIGERATOR_COMPARISON_DIMENSIONS: readonly XpyComparisonDimension[] = Object.freeze([
  ["total-net", "Toplam net hacim", "totalNetLitres", "L"], ["fresh-food-net", "Taze gıda net hacmi", "freshFoodNetLitres", "L"], ["chiller-net", "Soğutucu bölme net hacmi", "chillerNetLitres", "L"], ["freezer-net", "Dondurucu net hacmi", "freezerNetLitres", "L"], ["body-width", "Gövde genişliği", "widthMm", "mm"], ["body-height", "Gövde yüksekliği", "heightMm", "mm"], ["body-depth", "Gövde derinliği", "depthMm", "mm"], ["annual-energy", "Yıllık enerji tüketimi", "annualEnergyKwh", "kWh/year"], ["noise", "Akustik hava kaynaklı gürültü", "noiseDbA", "dB(A) re 1 pW"],
].map(([id, humanLabel, key, unit]) => ({ dimensionId: `refrigerator.${id}`, humanLabel, scope: `EXACT_TR_CONFIGURATION_SAME_REGIME_${unit}`, source: { kind: "FACT" as const, key, unitPolicy: "SAME_UNIT_REQUIRED" as const }, authority: "DOMAIN_PACK" as const })));

export function validateRefrigeratorRichnessDiscipline(release: XpyCatalogRelease): readonly string[] {
  const issues: string[] = [], expected = products.map((item) => item.id).sort(), actual = release.offerings.map((item) => item.offeringId).sort();
  if (JSON.stringify(expected) !== JSON.stringify(actual) || release.offerings.some((item) => item.identity.kind !== "PRODUCT" || products.find((product) => product.id === item.offeringId)?.configuration !== item.identity.configuration)) issues.push("MEMBERSHIP_OR_IDENTITY_CHANGED");
  if (release.evidence.some((item) => !item.assertion || item.assertion.applicability.offeringId !== item.offeringIds[0])) issues.push("ASSERTION_LEVEL_PROVENANCE_MISSING");
  if (release.layers.l5PersonaSignals.some((item) => item.decisionUse !== "NONE" || item.directCandidateEffect !== "NONE")) issues.push("PERSONA_DECISION_INFLUENCE");
  if (release.layers.l7ExperienceRules.length || release.evidence.some((item) => item.kind === "EXPERIENCE")) issues.push("EXPERIENCE_AUTHORITY_FABRICATED");
  if (release.layers.l9AdvisorKnowledge.length || release.evidence.some((item) => item.kind === "MANUAL")) issues.push("MANUAL_AUTHORITY_FABRICATED");
  if (release.layers.l1Facts.some((item) => item.offeringId === "LG_GC_B569NLLM_TR" && ["widthMm", "depthMm"].includes(item.key))) issues.push("LG_DIMENSION_CONFLICT_PROMOTED");
  if (release.externalBoundaries.offerRankingAuthority !== "NONE" || release.externalBoundaries.affiliateRankingAuthority !== "NONE") issues.push("EXTERNAL_AUTHORITY_LEAKAGE");
  return issues;
}

export const REFRIGERATOR_RICHNESS_COUNTS = Object.freeze({ sources: 8, offerings: 4, objectiveFacts: products.reduce((sum, item) => sum + Object.keys(item.facts).length, 0), capabilities: products.reduce((sum, item) => sum + Object.keys(item.capabilities).length, 0), usageSemantics: 7, needs: 9, needEvidenceMappings: 8, personaSignals: 3, dailyLifeInterpretations: 16, experienceRules: 0, decisionProjections: 4, advisorKnowledge: 0, comparisonDimensions: 9 });
