import { createHash } from "node:crypto";
import parent from "@/data/production/appliances/robot-vacuums/releases/APPLIANCES-ROBOT-VACUUM-TR-v0.1/domain-pack.json";
import { requireXpyDomainPack } from "../domainPacks";
import { XPY_RUNTIME_DIGEST, XPY_RUNTIME_VERSION } from "../runtimeContract";
import type { Capability, CatalogEvidence, CatalogSource, DailyLifeInterpretation, NeedEvidenceMapping, ObjectiveFact, PersonaPlanningSignal, UsageSemantic, UserNeed, XpyCatalogRelease, XpyComparisonDimension } from "./contract";
import { XPY_CATALOG_VERSION } from "./contract";
import { validateXpyCatalogRelease, xpyCatalogReleaseDigest } from "./validation";

export const ROBOT_VACUUM_RICHNESS_RELEASE_VERSION="APPLIANCES-ROBOT-VACUUM-CATALOG-RICHNESS-TR-v0.2" as const;
export const ROBOT_VACUUM_PARENT_RELEASE_VERSION="APPLIANCES-ROBOT-VACUUM-TR-v0.1" as const;
export const ROBOT_VACUUM_PARENT_ARTIFACT_SHA256="86b3932c87873ffcb67bd53b91c162dd167fc3bb22bcec6a2cb9b759ffd79533" as const;
export const ROBOT_VACUUM_SEMANTIC_AUTHORITY_VERSION="ROBOT_VACUUM_SEMANTIC_REGISTRY/v0.2" as const;
export const ROBOT_VACUUM_REVIEWED_AT="2026-09-04T23:00:00.000+03:00" as const;
const units:Record<string,string|undefined>={widthMm:"mm",depthMm:"mm",heightMm:"mm",thresholdMm:"mm",dustMl:"mL",waterMl:"mL",batteryMah:"mAh",runtimeMinutes:"min",manufacturerPascal:"Pa manufacturer claim"};
const id=(prefix:string,product:string,key:string)=>`${prefix}:${product.toLowerCase()}:${key}`;
const products=parent.products;

export function buildRobotVacuumRichnessRelease():XpyCatalogRelease{
 const sources:CatalogSource[]=parent.sources.map(s=>({sourceId:s.sourceId,kind:"OFFICIAL",uri:s.url,version:`observed-${s.accessedAt}`,observedAt:`${s.accessedAt}T12:00:00.000+03:00`,reviewedAt:ROBOT_VACUUM_REVIEWED_AT,market:"TR",applicabilityStatus:"EXACT",status:"VERIFIED",language:"tr-TR"}));
 const evidence:CatalogEvidence[]=[],facts:ObjectiveFact[]=[],capabilities:Capability[]=[];
 for(const p of products){const sourceId=p.evidenceRefs[0];for(const[key,value]of Object.entries(p.technicalFacts)){if(value===null)continue;const evidenceId=id("robot-vacuum-evidence-fact",p.productId,key),factId=id("robot-vacuum-fact",p.productId,key);evidence.push({evidenceId,kind:"TECHNICAL",sourceId,assertionId:factId,offeringIds:[p.productId],market:"TR",observedAt:"2026-09-03T12:00:00.000+03:00",reviewedAt:ROBOT_VACUUM_REVIEWED_AT,confidence:"HIGH",status:"VERIFIED",limitations:[key==="manufacturerPascal"?"Manufacturer Pa cannot rank suction or cleaning performance.":key==="runtimeMinutes"?"Runtime is meaningful only with its exact declared context and is not home coverage.":"Exact manufacturer-listed configuration only."],assertion:{locator:`parent.technicalFacts.${key}`,value,...(units[key]?{unit:units[key]}:{}),applicability:{offeringId:p.productId,market:"TR",model:p.model,configuration:p.configurationIdentity,status:"EXACT"}}});facts.push({factId,offeringId:p.productId,key,value,...(units[key]?{unit:units[key]}:{}),evidenceId});}for(const[key,value]of Object.entries(p.capabilities)){const evidenceId=id("robot-vacuum-evidence-capability",p.productId,key),capabilityId=id("robot-vacuum-capability",p.productId,key);evidence.push({evidenceId,kind:"CAPABILITY",sourceId,assertionId:capabilityId,offeringIds:[p.productId],market:"TR",observedAt:"2026-09-03T12:00:00.000+03:00",reviewedAt:ROBOT_VACUUM_REVIEWED_AT,confidence:"HIGH",status:"VERIFIED",limitations:["Presence does not establish cleaning, navigation, obstacle, autonomy, privacy, reliability, or app-quality outcomes."],assertion:{locator:`parent.capabilities.${key}`,value,applicability:{offeringId:p.productId,market:"TR",model:p.model,configuration:p.configurationIdentity,status:"EXACT"}}});capabilities.push({capabilityId,offeringId:p.productId,key,state:value?"PRESENT":"ABSENT",evidenceId,limitations:["No performance or behavior outcome is guaranteed."]});}}
 const fs=(key:string)=>facts.filter(x=>x.key===key).map(x=>x.factId),cs=(key:string)=>capabilities.filter(x=>x.key===key).map(x=>x.capabilityId);
 const usageSemantics:UsageSemantic[]=[
  {semanticId:"robot-vacuum-semantic:dimensions",meaning:"Declared dimensions support exact clearance checks only; they do not establish navigation or fit across a home.",factIds:[...fs("widthMm"),...fs("depthMm"),...fs("heightMm")],capabilityIds:[]},
  {semanticId:"robot-vacuum-semantic:threshold",meaning:"Manufacturer maximum threshold is a bounded claim, not an obstacle-crossing guarantee in a particular home.",factIds:fs("thresholdMm"),capabilityIds:[]},
  {semanticId:"robot-vacuum-semantic:containers",meaning:"Declared dust and water capacities are equipment facts, not emptying, mopping, or coverage outcomes.",factIds:[...fs("dustMl"),...fs("waterMl")],capabilityIds:[]},
  {semanticId:"robot-vacuum-semantic:runtime",meaning:"Runtime is comparable only under the same stated mode and test context; missing context stays unknown and battery capacity is not a runtime substitute.",factIds:[...fs("runtimeMinutes"),...fs("runtimeContext"),...fs("batteryMah")],capabilityIds:[]},
  {semanticId:"robot-vacuum-semantic:pascal",meaning:"Manufacturer Pa is a marketing specification and cannot rank suction, cleaning performance, or suitability.",factIds:fs("manufacturerPascal"),capabilityIds:[]},
  {semanticId:"robot-vacuum-semantic:automation",meaning:"Station and mop-care states answer exact equipment questions only; they do not prove autonomy or reliability.",factIds:[],capabilityIds:[...cs("autoEmpty"),...cs("autoChargeReturn"),...cs("mopLift"),...cs("mopWash"),...cs("mopDry")]},
  {semanticId:"robot-vacuum-semantic:navigation-app",meaning:"Mapping and app-control presence do not establish navigation quality, obstacle avoidance, privacy, connectivity reliability, or app behavior.",factIds:[],capabilityIds:[...cs("mapping"),...cs("appControl")]},
  {semanticId:"robot-vacuum-semantic:mopping",meaning:"Wet-mop presence does not establish stain removal, floor compatibility, mopping quality, or surface safety.",factIds:[],capabilityIds:cs("wetMop")},
 ];
 const needs:UserNeed[]=["ROBOT_HEIGHT","THRESHOLD","DUST_CAPACITY","WATER_CAPACITY","RUNTIME_CONTEXT","AUTO_EMPTY_REQUIREMENT","MOP_LIFT_REQUIREMENT","MOP_CARE_REQUIREMENT","APP_CONTROL_REQUIREMENT","BUDGET_SENSITIVITY"].map(x=>({needId:x,meaning:x.replaceAll("_"," ")}));
 const mappings:NeedEvidenceMapping[]=[...["heightMm","thresholdMm","dustMl","waterMl"].map((key):NeedEvidenceMapping=>({mappingId:`robot-vacuum-map:${key}`,needId:{heightMm:"ROBOT_HEIGHT",thresholdMm:"THRESHOLD",dustMl:"DUST_CAPACITY",waterMl:"WATER_CAPACITY"}[key]!,eligibleFactIds:fs(key),eligibleCapabilityIds:[],policy:"HARD_FILTER"})),{mappingId:"robot-vacuum-map:runtime",needId:"RUNTIME_CONTEXT",eligibleFactIds:[...fs("runtimeMinutes"),...fs("runtimeContext")],eligibleCapabilityIds:[],policy:"QUESTION_INPUT"},...["autoEmpty","mopLift","appControl"].map((key):NeedEvidenceMapping=>({mappingId:`robot-vacuum-map:${key}`,needId:{autoEmpty:"AUTO_EMPTY_REQUIREMENT",mopLift:"MOP_LIFT_REQUIREMENT",appControl:"APP_CONTROL_REQUIREMENT"}[key]!,eligibleFactIds:[],eligibleCapabilityIds:cs(key),policy:"HARD_FILTER"})),{mappingId:"robot-vacuum-map:mop-care",needId:"MOP_CARE_REQUIREMENT",eligibleFactIds:[],eligibleCapabilityIds:[...cs("mopWash"),...cs("mopDry")],policy:"HARD_FILTER"}];
 const personaSignals:PersonaPlanningSignal[]=[{signalId:"robot-vacuum-planning:low-furniture",needIds:["ROBOT_HEIGHT"],authority:"DOMAIN_PLANNING",classification:"DERIVED_PLANNING",decisionUse:"NONE",directCandidateEffect:"NONE"},{signalId:"robot-vacuum-planning:thresholds",needIds:["THRESHOLD"],authority:"DOMAIN_PLANNING",classification:"DERIVED_PLANNING",decisionUse:"NONE",directCandidateEffect:"NONE"},{signalId:"robot-vacuum-planning:station-care",needIds:["AUTO_EMPTY_REQUIREMENT","MOP_CARE_REQUIREMENT"],authority:"DOMAIN_PLANNING",classification:"DERIVED_PLANNING",decisionUse:"NONE",directCandidateEffect:"NONE"},{signalId:"robot-vacuum-planning:connectivity",needIds:["APP_CONTROL_REQUIREMENT"],authority:"DOMAIN_PLANNING",classification:"DERIVED_PLANNING",decisionUse:"NONE",directCandidateEffect:"NONE"}];
 const interpretations:DailyLifeInterpretation[]=products.flatMap(p=>{const pf=(keys:string[])=>facts.filter(x=>x.offeringId===p.productId&&keys.includes(x.key)).map(x=>x.factId),pc=(keys:string[])=>capabilities.filter(x=>x.offeringId===p.productId&&keys.includes(x.key)).map(x=>x.capabilityId),row=(suffix:string,text:string,keys:string[],caps:string[]):DailyLifeInterpretation=>({interpretationId:id("robot-vacuum-interpretation",p.productId,suffix),offeringId:p.productId,text,factIds:pf(keys),capabilityIds:pc(caps),method:"DETERMINISTIC_REVIEWED_MAPPING",reviewedAt:ROBOT_VACUUM_REVIEWED_AT,polarity:"NEUTRAL",limitations:["Bounded to exact published facts and feature states."],nonGuarantees:["No cleaning, navigation, obstacle, autonomy, privacy, reliability, floor-safety, or app-quality outcome guarantee."]});return[row("fit","Published dimensions and threshold claim can inform exact clearance and threshold questions only.",["widthMm","depthMm","heightMm","thresholdMm"],[]),row("capacity-runtime","Container, battery and runtime declarations can be shown with exact context; missing context stays unknown.",["dustMl","waterMl","batteryMah","runtimeMinutes","runtimeContext"],[]),row("automation","Exact station and mop-care states answer bounded equipment questions only.",[],["autoEmpty","autoChargeReturn","mopLift","mopWash","mopDry"]),row("mapping-app","Mapping, app and wet-mop states identify listed functions only, not performance or behavior.",[],["mapping","appControl","wetMop"])].filter(x=>x.factIds.length+x.capabilityIds.length>0)});
 const evidenceFor=(offeringId:string)=>evidence.filter(x=>x.offeringIds.includes(offeringId)).map(x=>x.evidenceId),mappingFor=(offeringId:string)=>mappings.filter(m=>[...m.eligibleFactIds,...m.eligibleCapabilityIds].some(entity=>facts.some(x=>x.offeringId===offeringId&&x.factId===entity)||capabilities.some(x=>x.offeringId===offeringId&&x.capabilityId===entity))).map(x=>x.mappingId);
 const semanticPayload={version:ROBOT_VACUUM_SEMANTIC_AUTHORITY_VERSION,usageSemantics,needs,mappings,personaSignals,interpretations},semanticAuthorityDigest=`sha256:${createHash("sha256").update(JSON.stringify(semanticPayload)).digest("hex")}` as const,pack=requireXpyDomainPack("APPLIANCES");
 const unsigned:Omit<XpyCatalogRelease,"releaseDigest">={schemaVersion:XPY_CATALOG_VERSION,releaseId:"appliances:robot-vacuum:catalog-richness:tr:v0.2",releaseVersion:ROBOT_VACUUM_RICHNESS_RELEASE_VERSION,departmentId:"APPLIANCES",categoryId:"ROBOT_VACUUM",market:"TR",lifecycle:"FROZEN",effectiveAt:ROBOT_VACUUM_REVIEWED_AT,compatibility:{runtime:{version:XPY_RUNTIME_VERSION,digest:XPY_RUNTIME_DIGEST,domainPackId:pack.domainPackId},domainPackVersion:pack.domainPackId,semanticAuthorityVersion:ROBOT_VACUUM_SEMANTIC_AUTHORITY_VERSION,semanticAuthorityDigest,revisionClass:"SEMANTIC_POLICY_CHANGE",semanticAuthorityChange:"VERSIONED_CHANGE"},sources,evidence,offerings:products.map(p=>({offeringId:p.productId,market:"TR",lifecycle:"FROZEN",validFrom:"2026-09-03T12:00:00.000+03:00",identity:{kind:"PRODUCT",manufacturer:p.brand,model:p.model,configuration:p.configurationIdentity,identifiers:{productId:p.productId}}})),layers:{l1Facts:facts,l2Capabilities:capabilities,l3UsageSemantics:usageSemantics,l4Needs:needs,l4NeedEvidenceMappings:mappings,l5PersonaSignals:personaSignals,l6DailyLifeInterpretations:interpretations,l7ExperienceRules:[],l8DecisionProjections:products.map(p=>({projectionId:id("robot-vacuum-decision-projection",p.productId,"exact"),offeringId:p.productId,eligibleEvidenceIds:evidenceFor(p.productId),needMappingIds:mappingFor(p.productId),limitations:["Exact Robot Vacuum evidence only; unknowns remain neutral.","Pa, derived planning, interpretations, commerce, media and Advisor cannot filter, rank, or authorize."],disclosures:["Frozen v0.1 membership, blockers and Y remain unchanged.","No cleaning, navigation, obstacle, autonomy, privacy or app outcome is guaranteed."],traceability:"EXACT"})),l9AdvisorKnowledge:[]},externalBoundaries:{commerce:"EXTERNAL_VOLATILE_EXACT_IDENTITY_JOIN_ONLY",media:"EXTERNAL_VOLATILE_EXACT_IDENTITY_JOIN_ONLY",offerIdentityAuthority:"NONE",offerRankingAuthority:"NONE",affiliateRankingAuthority:"NONE"}};
 const result=Object.freeze({...unsigned,releaseDigest:xpyCatalogReleaseDigest(unsigned)}),issues=[...validateXpyCatalogRelease(result),...validateRobotVacuumRichnessDiscipline(result)];if(issues.length)throw new TypeError(`ROBOT_VACUUM_RICHNESS_INVALID:${issues.join(",")}`);return result;
}
export const ROBOT_VACUUM_COMPARISON_DIMENSIONS:readonly XpyComparisonDimension[]=Object.freeze([...[["height","Robot yüksekliği","heightMm","mm"],["threshold","Üretici azami eşik beyanı","thresholdMm","mm"],["dust","Toz haznesi","dustMl","mL"],["water","Su haznesi","waterMl","mL"]].map(([n,h,key,u])=>({dimensionId:`robot-vacuum.${n}`,humanLabel:h,scope:`EXACT_TR_CONFIGURATION_SAME_CONTEXT_${u}`,source:{kind:"FACT" as const,key,unitPolicy:"SAME_UNIT_REQUIRED" as const},authority:"DOMAIN_PACK" as const})),...[["auto-empty","Otomatik boşaltma","autoEmpty"],["mop-lift","Paspas kaldırma","mopLift"],["mop-wash","Paspas yıkama","mopWash"],["mop-dry","Paspas kurutma","mopDry"]].map(([n,h,key])=>({dimensionId:`robot-vacuum.${n}`,humanLabel:h,scope:"EXACT_TR_CONFIGURATION_FEATURE_STATE",source:{kind:"CAPABILITY" as const,key,unitPolicy:"STATE_ONLY" as const},authority:"DOMAIN_PACK" as const}))]);
export function validateRobotVacuumRichnessDiscipline(r:XpyCatalogRelease):readonly string[]{const issues:string[]=[],expected=products.map(x=>x.productId).sort();if(JSON.stringify(expected)!==JSON.stringify(r.offerings.map(x=>x.offeringId).sort())||r.offerings.some(x=>x.identity.kind!=="PRODUCT"||products.find(p=>p.productId===x.offeringId)?.configurationIdentity!==x.identity.configuration))issues.push("MEMBERSHIP_OR_IDENTITY_CHANGED");if(r.evidence.some(x=>!x.assertion||x.assertion.applicability.offeringId!==x.offeringIds[0]))issues.push("ASSERTION_LEVEL_PROVENANCE_MISSING");if(r.layers.l5PersonaSignals.some(x=>x.decisionUse!=="NONE"||x.directCandidateEffect!=="NONE"))issues.push("PERSONA_DECISION_INFLUENCE");if(r.layers.l7ExperienceRules.length||r.evidence.some(x=>x.kind==="EXPERIENCE"))issues.push("EXPERIENCE_AUTHORITY_FABRICATED");if(r.layers.l9AdvisorKnowledge.length||r.evidence.some(x=>x.kind==="MANUAL"))issues.push("MANUAL_AUTHORITY_FABRICATED");if(r.layers.l3UsageSemantics.some(x=>x.semanticId==="robot-vacuum-semantic:pascal"&&!x.meaning.includes("cannot rank")))issues.push("PASCAL_PERFORMANCE_LEAKAGE");return issues;}
export const ROBOT_VACUUM_RICHNESS_COUNTS=Object.freeze({sources:6,offerings:4,objectiveFacts:23,capabilities:26,usageSemantics:8,needs:10,needEvidenceMappings:9,personaSignals:4,dailyLifeInterpretations:14,experienceRules:0,decisionProjections:4,advisorKnowledge:0,comparisonDimensions:8});
