import { createHash } from "node:crypto";
import { requireXpyDomainPack } from "../domainPacks";
import { XPY_RUNTIME_DIGEST, XPY_RUNTIME_VERSION } from "../runtimeContract";
import type { Capability, CatalogEvidence, CatalogSource, DailyLifeInterpretation, NeedEvidenceMapping, ObjectiveFact, PersonaPlanningSignal, UsageSemantic, UserNeed, XpyCatalogRelease, XpyComparisonDimension } from "./contract";
import { XPY_CATALOG_VERSION } from "./contract";
import { validateXpyCatalogRelease, xpyCatalogReleaseDigest } from "./validation";

export const VACUUM_RICHNESS_RELEASE_VERSION="APPLIANCES-VACUUM-CATALOG-RICHNESS-TR-v0.2" as const;
export const VACUUM_PARENT_RELEASE_VERSION="APPLIANCES-VACUUM-TR-v0.1" as const;
export const VACUUM_PARENT_ARTIFACT_SHA256="849467eb66b81d4042076da4e1023836b56974a1d6e2fbfd9fd67d34555ad343" as const;
export const VACUUM_SEMANTIC_AUTHORITY_VERSION="VACUUM_SEMANTIC_REGISTRY/v0.2" as const;
export const VACUUM_REVIEWED_AT="2026-09-04T22:00:00.000+03:00" as const;

const products=[
 {id:"PHILIPS_FC9330_07_TR",brand:"Philips",model:"FC9330/07",configuration:"Philips PowerPro Compact FC9330/07 / Türkiye / kablolu torbasız kuru canister",source:"PHILIPS-FC9330-07-TR",facts:{capacity:1.5,inputPowerMaxW:900,radiusM:9,massKg:4.5,noiseDbA:76,filtrationStandard:"EN60312-1-2017_HEPA13_EQUIVALENT"},capabilities:{hepa:true,petHead:false,triActiveHead:true,washableFilter:true}},
 {id:"PHILIPS_FC9750_07_TR",brand:"Philips",model:"FC9750/07",configuration:"Philips PowerPro Max FC9750/07 / Türkiye / kablolu torbasız kuru canister",source:"PHILIPS-FC9750-07-TR",facts:{capacity:2,inputPowerMaxW:900,radiusM:10,massKg:5.5,noiseDbA:75,filtrationStandard:"EN60312-1-2017_HEPA13_EQUIVALENT"},capabilities:{hepa:true,petHead:false,carpetHead:true,hardFloorHead:true,washableFilter:true}},
 {id:"BOSCH_BGC21X300_TR",brand:"Bosch",model:"BGC21X300",configuration:"Bosch Serie 4 BGC21X300 / Türkiye / kablolu torbasız kuru canister",source:"BOSCH-BGC21X300-TR",facts:{capacity:2,inputPowerMaxW:550,radiusM:10,massKg:4.7,noiseDbA:76,filtrationStandard:"HEPA_LABEL_MANUFACTURER"},capabilities:{hepa:true,petHead:false,washableFilter:true}},
 {id:"BOSCH_BGC41PET_TR",brand:"Bosch",model:"BGC41PET",configuration:"Bosch Serie 6 ProAnimal BGC41PET / Türkiye / kablolu torbasız kuru canister",source:"BOSCH-BGC41PET-TR",facts:{capacity:2.4,inputPowerMaxW:600,radiusM:10,massKg:5.6,noiseDbA:72,filtrationStandard:"HEPA_LABEL_MANUFACTURER"},capabilities:{hepa:true,petHead:true,washableFilter:true}},
] as const;
const sourceRows=[["PHILIPS-FC9330-07-TR","https://www.philips.com.tr/c-p/FC9330_07/powerpro-compact-torbasiz-elektrikli-suepuerge"],["PHILIPS-FC9750-07-TR","https://www.philips.com.tr/c-p/FC9750_07/7000-series-torbasiz-elektrikli-suepuerge"],["BOSCH-BGC21X300-TR","https://www.bosch-home.com.tr/tr/product/elektrikli-supurgeler/toz-torbasiz-elektrikli-supurgeler/BGC21X300"],["BOSCH-BGC41PET-TR","https://www.bosch-home.com.tr/tr/product/elektrikli-supurgeler/toz-torbasiz-elektrikli-supurgeler/BGC41PET"]] as const;
const units:Record<string,string|undefined>={capacity:"L",inputPowerMaxW:"W input",radiusM:"m",massKg:"kg",noiseDbA:"dB(A)"};
const makeId=(prefix:string,id:string,key:string)=>`${prefix}:${id.toLowerCase()}:${key}`;

export function buildVacuumRichnessRelease():XpyCatalogRelease{
 const sources:CatalogSource[]=sourceRows.map(([sourceId,uri])=>({sourceId,kind:"OFFICIAL",uri,version:"observed-2026-09-03",observedAt:"2026-09-03T12:00:00.000+03:00",reviewedAt:VACUUM_REVIEWED_AT,market:"TR",applicabilityStatus:"EXACT",status:"VERIFIED",language:"tr-TR"}));
 const evidence:CatalogEvidence[]=[],facts:ObjectiveFact[]=[],capabilities:Capability[]=[];
 for(const product of products){for(const[key,value]of Object.entries(product.facts)){const evidenceId=makeId("vacuum-evidence-fact",product.id,key),factId=makeId("vacuum-fact",product.id,key);evidence.push({evidenceId,kind:"TECHNICAL",sourceId:product.source,assertionId:factId,offeringIds:[product.id],market:"TR",observedAt:"2026-09-03T12:00:00.000+03:00",reviewedAt:VACUUM_REVIEWED_AT,confidence:"HIGH",status:"VERIFIED",limitations:[key==="inputPowerMaxW"?"Electrical input power is not suction power or cleaning performance.":key==="filtrationStandard"?"Comparable only for the same verified label and test standard.":"Exact manufacturer-listed configuration only."],assertion:{locator:`parent.technicalFacts.${key}`,value,...(units[key]?{unit:units[key]}:{}),applicability:{offeringId:product.id,market:"TR",model:product.model,configuration:product.configuration,status:"EXACT"}}});facts.push({factId,offeringId:product.id,key,value,...(units[key]?{unit:units[key]}:{}),evidenceId});}for(const[key,value]of Object.entries(product.capabilities)){const evidenceId=makeId("vacuum-evidence-capability",product.id,key),capabilityId=makeId("vacuum-capability",product.id,key);evidence.push({evidenceId,kind:"CAPABILITY",sourceId:product.source,assertionId:capabilityId,offeringIds:[product.id],market:"TR",observedAt:"2026-09-03T12:00:00.000+03:00",reviewedAt:VACUUM_REVIEWED_AT,confidence:"HIGH",status:"VERIFIED",limitations:["Equipment or filter presence does not establish a cleaning, allergen, or pet-hair outcome."],assertion:{locator:`parent.capabilities.${key}`,value,applicability:{offeringId:product.id,market:"TR",model:product.model,configuration:product.configuration,status:"EXACT"}}});capabilities.push({capabilityId,offeringId:product.id,key,state:value?"PRESENT":"ABSENT",evidenceId,limitations:["No cleaning, filtration, allergen, pet-hair, durability, or service outcome is guaranteed."]});}}
 const factIds=(key:string)=>facts.filter(x=>x.key===key).map(x=>x.factId),capIds=(key:string)=>capabilities.filter(x=>x.key===key).map(x=>x.capabilityId);
 const usageSemantics:UsageSemantic[]=[{semanticId:"vacuum-semantic:capacity",meaning:"Declared dust-container volume is comparable capacity evidence, not a cleaning interval guarantee.",factIds:factIds("capacity"),capabilityIds:[]},{semanticId:"vacuum-semantic:input-power",meaning:"Maximum electrical input power describes consumption/input only and cannot rank suction or cleaning performance.",factIds:factIds("inputPowerMaxW"),capabilityIds:[]},{semanticId:"vacuum-semantic:radius",meaning:"Declared operating radius supports a bounded reach check, not room coverage or cable-length equivalence.",factIds:factIds("radiusM"),capabilityIds:[]},{semanticId:"vacuum-semantic:carry-mass",meaning:"Published mass supports same-context handling discussion, not perceived effort on stairs.",factIds:factIds("massKg"),capabilityIds:[]},{semanticId:"vacuum-semantic:noise",meaning:"Declared noise supports same-regime display, not perceived quietness in a particular home.",factIds:factIds("noiseDbA"),capabilityIds:[]},{semanticId:"vacuum-semantic:filtration",meaning:"Filtration is comparable only under the same verified label and test standard; HEPA wording alone does not prove equivalent capture or health outcome.",factIds:factIds("filtrationStandard"),capabilityIds:capIds("hepa")},{semanticId:"vacuum-semantic:heads",meaning:"Verified supplied-head states answer exact equipment requirements only and do not guarantee surface or pet-hair results.",factIds:[],capabilityIds:[...capIds("petHead"),...capIds("triActiveHead"),...capIds("carpetHead"),...capIds("hardFloorHead")]},{semanticId:"vacuum-semantic:filter-care",meaning:"Washable-filter presence is a maintenance feature, not a filter-life or hygiene guarantee.",factIds:[],capabilityIds:capIds("washableFilter")}];
 const needs:UserNeed[]=[...["DUST_CAPACITY","OPERATING_RADIUS","CARRY_MASS","LOW_NOISE_PRIORITY","FILTRATION_REQUIREMENT","PET_HEAD_REQUIREMENT","CARPET_HEAD_REQUIREMENT","HARD_FLOOR_HEAD_REQUIREMENT","WASHABLE_FILTER_REQUIREMENT","BUDGET_SENSITIVITY"].map(x=>({needId:x,meaning:x.replaceAll("_"," ")}))];
 const mappings:NeedEvidenceMapping[]=[{mappingId:"vacuum-map:capacity",needId:"DUST_CAPACITY",eligibleFactIds:factIds("capacity"),eligibleCapabilityIds:[],policy:"HARD_FILTER"},{mappingId:"vacuum-map:radius",needId:"OPERATING_RADIUS",eligibleFactIds:factIds("radiusM"),eligibleCapabilityIds:[],policy:"HARD_FILTER"},{mappingId:"vacuum-map:mass",needId:"CARRY_MASS",eligibleFactIds:factIds("massKg"),eligibleCapabilityIds:[],policy:"SOFT_PREFERENCE"},{mappingId:"vacuum-map:noise",needId:"LOW_NOISE_PRIORITY",eligibleFactIds:factIds("noiseDbA"),eligibleCapabilityIds:[],policy:"SOFT_PREFERENCE"},{mappingId:"vacuum-map:filtration",needId:"FILTRATION_REQUIREMENT",eligibleFactIds:factIds("filtrationStandard"),eligibleCapabilityIds:capIds("hepa"),policy:"HARD_FILTER"},...["petHead","carpetHead","hardFloorHead","washableFilter"].map((key):NeedEvidenceMapping=>({mappingId:`vacuum-map:${key}`,needId:{petHead:"PET_HEAD_REQUIREMENT",carpetHead:"CARPET_HEAD_REQUIREMENT",hardFloorHead:"HARD_FLOOR_HEAD_REQUIREMENT",washableFilter:"WASHABLE_FILTER_REQUIREMENT"}[key]!,eligibleFactIds:[],eligibleCapabilityIds:capIds(key),policy:"HARD_FILTER"}))];
 const personaSignals:PersonaPlanningSignal[]=[{signalId:"vacuum-planning:multi-room-reach",needIds:["OPERATING_RADIUS"],authority:"DOMAIN_PLANNING",classification:"DERIVED_PLANNING",decisionUse:"NONE",directCandidateEffect:"NONE"},{signalId:"vacuum-planning:stairs-or-carrying",needIds:["CARRY_MASS"],authority:"DOMAIN_PLANNING",classification:"DERIVED_PLANNING",decisionUse:"NONE",directCandidateEffect:"NONE"},{signalId:"vacuum-planning:pet-home",needIds:["PET_HEAD_REQUIREMENT"],authority:"DOMAIN_PLANNING",classification:"DERIVED_PLANNING",decisionUse:"NONE",directCandidateEffect:"NONE"},{signalId:"vacuum-planning:noise-sensitive-home",needIds:["LOW_NOISE_PRIORITY"],authority:"DOMAIN_PLANNING",classification:"DERIVED_PLANNING",decisionUse:"NONE",directCandidateEffect:"NONE"}];
 const interpretations:DailyLifeInterpretation[]=products.flatMap(product=>{const ownFacts=(keys:string[])=>facts.filter(x=>x.offeringId===product.id&&keys.includes(x.key)).map(x=>x.factId),ownCaps=(keys:string[])=>capabilities.filter(x=>x.offeringId===product.id&&keys.includes(x.key)).map(x=>x.capabilityId),row=(suffix:string,text:string,keys:string[],caps:string[]):DailyLifeInterpretation=>({interpretationId:makeId("vacuum-interpretation",product.id,suffix),offeringId:product.id,text,factIds:ownFacts(keys),capabilityIds:ownCaps(caps),method:"DETERMINISTIC_REVIEWED_MAPPING",reviewedAt:VACUUM_REVIEWED_AT,polarity:"NEUTRAL",limitations:["Interpretation is bounded to exact published facts and feature states."],nonGuarantees:["No cleaning, comfort, health, pet-hair, noise, durability, or maintenance outcome guarantee."]});return[row("handling","Capacity, operating radius and published mass can inform bounded emptying, reach and carrying discussions.",["capacity","radiusM","massKg"],[]),row("noise-power","Declared noise may be displayed on the same measurement basis; input watts cannot stand in for suction or cleaning performance.",["noiseDbA","inputPowerMaxW"],[]),row("filtration-care","Exact filtration label, HEPA and washable-filter states can answer bounded filter and care questions only.",["filtrationStandard"],["hepa","washableFilter"]),row("heads","Exact supplied-head states can answer whether the governed configuration lists a requested head.",[],["petHead","triActiveHead","carpetHead","hardFloorHead"])]});
 const evidenceFor=(id:string)=>evidence.filter(x=>x.offeringIds.includes(id)).map(x=>x.evidenceId),mappingsFor=(id:string)=>mappings.filter(m=>[...m.eligibleFactIds,...m.eligibleCapabilityIds].some(entity=>facts.some(x=>x.offeringId===id&&x.factId===entity)||capabilities.some(x=>x.offeringId===id&&x.capabilityId===entity))).map(x=>x.mappingId);
 const semanticPayload={version:VACUUM_SEMANTIC_AUTHORITY_VERSION,usageSemantics,needs,mappings,personaSignals,interpretations,comparisonPolicy:"DOMAIN_PACK_ONLY_NEUTRAL_UNKNOWN_FAIL_CLOSED"},semanticAuthorityDigest=`sha256:${createHash("sha256").update(JSON.stringify(semanticPayload)).digest("hex")}` as const,pack=requireXpyDomainPack("APPLIANCES");
 const unsigned:Omit<XpyCatalogRelease,"releaseDigest">={schemaVersion:XPY_CATALOG_VERSION,releaseId:"appliances:vacuum:catalog-richness:tr:v0.2",releaseVersion:VACUUM_RICHNESS_RELEASE_VERSION,departmentId:"APPLIANCES",categoryId:"VACUUM",market:"TR",lifecycle:"FROZEN",effectiveAt:VACUUM_REVIEWED_AT,compatibility:{runtime:{version:XPY_RUNTIME_VERSION,digest:XPY_RUNTIME_DIGEST,domainPackId:pack.domainPackId},domainPackVersion:pack.domainPackId,semanticAuthorityVersion:VACUUM_SEMANTIC_AUTHORITY_VERSION,semanticAuthorityDigest,revisionClass:"SEMANTIC_POLICY_CHANGE",semanticAuthorityChange:"VERSIONED_CHANGE"},sources,evidence,offerings:products.map(x=>({offeringId:x.id,market:"TR",lifecycle:"FROZEN",validFrom:"2026-09-03T12:00:00.000+03:00",identity:{kind:"PRODUCT",manufacturer:x.brand,model:x.model,configuration:x.configuration,identifiers:{productId:x.id}}})),layers:{l1Facts:facts,l2Capabilities:capabilities,l3UsageSemantics:usageSemantics,l4Needs:needs,l4NeedEvidenceMappings:mappings,l5PersonaSignals:personaSignals,l6DailyLifeInterpretations:interpretations,l7ExperienceRules:[],l8DecisionProjections:products.map(x=>({projectionId:makeId("vacuum-decision-projection",x.id,"exact"),offeringId:x.id,eligibleEvidenceIds:evidenceFor(x.id),needMappingIds:mappingsFor(x.id),limitations:["Reads only exact approved Vacuum evidence; unknowns remain neutral.","Input watts, planning, interpretation, commerce, media and Advisor content cannot filter, rank, or authorize."],disclosures:["The frozen v0.1 Vacuum candidate and Y authority remains unchanged.","Cleaning, filtration, health, handling, pet-hair and noise outcomes are not guaranteed."],traceability:"EXACT"})),l9AdvisorKnowledge:[]},externalBoundaries:{commerce:"EXTERNAL_VOLATILE_EXACT_IDENTITY_JOIN_ONLY",media:"EXTERNAL_VOLATILE_EXACT_IDENTITY_JOIN_ONLY",offerIdentityAuthority:"NONE",offerRankingAuthority:"NONE",affiliateRankingAuthority:"NONE"}};
 const release=Object.freeze({...unsigned,releaseDigest:xpyCatalogReleaseDigest(unsigned)}),issues=[...validateXpyCatalogRelease(release),...validateVacuumRichnessDiscipline(release)];if(issues.length)throw new TypeError(`VACUUM_RICHNESS_INVALID:${issues.join(",")}`);return release;
}
export const VACUUM_COMPARISON_DIMENSIONS:readonly XpyComparisonDimension[]=Object.freeze([
 ...[["capacity","Toz haznesi kapasitesi","capacity","L"],["radius","Çalışma yarıçapı","radiusM","m"],["mass","Yayınlanan ağırlık","massKg","kg"],["noise","Yayınlanan gürültü","noiseDbA","dB(A)"]].map(([id,humanLabel,key,unit])=>({dimensionId:`vacuum.${id}`,humanLabel,scope:`EXACT_TR_CONFIGURATION_SAME_CONTEXT_${unit}`,source:{kind:"FACT" as const,key,unitPolicy:"SAME_UNIT_REQUIRED" as const},authority:"DOMAIN_PACK" as const})),
 ...[["pet-head","Evcil hayvan başlığı","petHead"],["washable-filter","Yıkanabilir filtre","washableFilter"]].map(([id,humanLabel,key])=>({dimensionId:`vacuum.${id}`,humanLabel,scope:"EXACT_TR_CONFIGURATION_FEATURE_STATE",source:{kind:"CAPABILITY" as const,key,unitPolicy:"STATE_ONLY" as const},authority:"DOMAIN_PACK" as const})),
]);
export function validateVacuumRichnessDiscipline(release:XpyCatalogRelease):readonly string[]{const issues:string[]=[],expected=products.map(x=>x.id).sort(),actual=release.offerings.map(x=>x.offeringId).sort();if(JSON.stringify(expected)!==JSON.stringify(actual)||release.offerings.some(x=>x.identity.kind!=="PRODUCT"||products.find(p=>p.id===x.offeringId)?.configuration!==x.identity.configuration))issues.push("MEMBERSHIP_OR_IDENTITY_CHANGED");if(release.evidence.some(x=>!x.assertion||x.assertion.applicability.offeringId!==x.offeringIds[0]))issues.push("ASSERTION_LEVEL_PROVENANCE_MISSING");if(release.layers.l5PersonaSignals.some(x=>x.decisionUse!=="NONE"||x.directCandidateEffect!=="NONE"))issues.push("PERSONA_DECISION_INFLUENCE");if(release.layers.l7ExperienceRules.length||release.evidence.some(x=>x.kind==="EXPERIENCE"))issues.push("EXPERIENCE_AUTHORITY_FABRICATED");if(release.layers.l9AdvisorKnowledge.length||release.evidence.some(x=>x.kind==="MANUAL"))issues.push("MANUAL_AUTHORITY_FABRICATED");if(release.layers.l3UsageSemantics.some(x=>x.semanticId==="vacuum-semantic:input-power"&&!x.meaning.includes("cannot rank")))issues.push("INPUT_POWER_PERFORMANCE_LEAKAGE");if(release.externalBoundaries.offerRankingAuthority!=="NONE"||release.externalBoundaries.affiliateRankingAuthority!=="NONE")issues.push("EXTERNAL_AUTHORITY_LEAKAGE");return issues;}
export const VACUUM_RICHNESS_COUNTS=Object.freeze({sources:4,offerings:4,objectiveFacts:24,capabilities:15,usageSemantics:8,needs:10,needEvidenceMappings:9,personaSignals:4,dailyLifeInterpretations:16,experienceRules:0,decisionProjections:4,advisorKnowledge:0,comparisonDimensions:6});
