import{createHash}from"node:crypto";import{readFile}from"node:fs/promises";import path from"node:path";import{describe,expect,it}from"vitest";import{loadActiveBoundedAuthority}from"@/features/appliances/bounded/authority.server";import type{XpyCatalogRelease}from"./contract";import{buildVacuumRichnessRelease,VACUUM_COMPARISON_DIMENSIONS,VACUUM_PARENT_ARTIFACT_SHA256,VACUUM_RICHNESS_COUNTS,validateVacuumRichnessDiscipline}from"./vacuumRichness";import{loadActiveVacuumRichnessRelease,loadPinnedVacuumRichnessRelease}from"./vacuumRichness.server";import{projectAdvisorRead,projectComparisonEvidence}from"./readProjections";import{validateXpyCatalogRelease,xpyCatalogReleaseDigest}from"./validation";
const root=path.resolve(process.cwd()),resign=(release:XpyCatalogRelease):XpyCatalogRelease=>({...release,releaseDigest:xpyCatalogReleaseDigest(release)}),auth=(release:XpyCatalogRelease)=>({purchaseStatus:"PURCHASED"as const,entitlementId:"test",comparisonSetId:"exact-vacuums",exactOfferingIds:release.offerings.map(x=>x.offeringId)});
describe("Vacuum XPY_CATALOG richness child",()=>{
 it("preserves exact membership and binds every promoted assertion",()=>{const release=buildVacuumRichnessRelease();expect(release.offerings.map(x=>x.offeringId)).toEqual(["PHILIPS_FC9330_07_TR","PHILIPS_FC9750_07_TR","BOSCH_BGC21X300_TR","BOSCH_BGC41PET_TR"]);expect(validateXpyCatalogRelease(release)).toEqual([]);expect(validateVacuumRichnessDiscipline(release)).toEqual([]);expect(release.evidence).toHaveLength(VACUUM_RICHNESS_COUNTS.objectiveFacts+VACUUM_RICHNESS_COUNTS.capabilities);expect(release.evidence.every(x=>x.assertion?.applicability.status==="EXACT")).toBe(true)});
 it("keeps outcomes neutral and unsupported manual/experience absent",()=>{const release=buildVacuumRichnessRelease();expect(release.layers.l7ExperienceRules).toEqual([]);expect(release.layers.l9AdvisorKnowledge).toEqual([]);expect(release.layers.l5PersonaSignals.every(x=>x.classification==="DERIVED_PLANNING"&&x.decisionUse==="NONE"&&x.directCandidateEffect==="NONE")).toBe(true);expect(release.layers.l3UsageSemantics.find(x=>x.semanticId==="vacuum-semantic:input-power")?.meaning).toContain("cannot rank")});
 it("enforces purchased exact-set comparison and read-only Advisor boundaries",()=>{const release=buildVacuumRichnessRelease(),comparison=projectComparisonEvidence({release,authorization:auth(release),dimensions:VACUUM_COMPARISON_DIMENSIONS});expect(comparison.dimensions).toHaveLength(6);expect(()=>projectComparisonEvidence({release,authorization:{...auth(release),purchaseStatus:"UNPAID"}as never,dimensions:VACUUM_COMPARISON_DIMENSIONS})).toThrow("COMPARISON_AUTHORIZATION_REQUIRED");expect(release.offerings.map(x=>projectAdvisorRead({release,authorizedDecision:{decisionId:x.offeringId,exactOfferingId:x.offeringId}})).every(x=>x.readOnly&&x.forbidden.includes("CHANGE_Y_AUTHORIZATION"))).toBe(true)});
 it("keeps missing unlisted head state neutral and detects identity/persona inventions",()=>{const release=buildVacuumRichnessRelease(),comparison=projectComparisonEvidence({release,authorization:auth(release),dimensions:[{dimensionId:"vacuum.carpet-head",humanLabel:"Halı başlığı",scope:"EXACT_TR_CONFIGURATION_FEATURE_STATE",source:{kind:"CAPABILITY",key:"carpetHead",unitPolicy:"STATE_ONLY"},authority:"DOMAIN_PACK"}]});expect(comparison.dimensions[0].cells.find(x=>x.offeringId==="BOSCH_BGC21X300_TR")?.state).toBe("UNKNOWN");const wrong=structuredClone(release)as XpyCatalogRelease;(wrong.offerings[0].identity as{configuration:string}).configuration="wrong";expect(validateVacuumRichnessDiscipline(resign(wrong))).toContain("MEMBERSHIP_OR_IDENTITY_CHANGED");const persona=structuredClone(release)as XpyCatalogRelease;(persona.layers.l5PersonaSignals[0]as unknown as{directCandidateEffect:string}).directCandidateEffect="FILTER";expect(validateVacuumRichnessDiscipline(resign(persona))).toContain("PERSONA_DECISION_INFLUENCE")});
 it("loads the pinned child, active composite, and byte-stable parent",async()=>{const[pinned,active,authority,raw]=await Promise.all([loadPinnedVacuumRichnessRelease(root),loadActiveVacuumRichnessRelease(root),loadActiveBoundedAuthority(root,"VACUUM"),readFile(path.join(root,"data/production/appliances/vacuums/releases/APPLIANCES-VACUUM-TR-v0.1/domain-pack.json"),"utf8")]);expect(pinned.status).toBe("READY");expect(active.status).toBe("READY");expect(authority.status).toBe("READY");expect(createHash("sha256").update(raw).digest("hex")).toBe(VACUUM_PARENT_ARTIFACT_SHA256);if(active.status==="READY"&&authority.status==="READY"){expect(authority.snapshot.catalogDigest).toBe(VACUUM_PARENT_ARTIFACT_SHA256);expect(authority.snapshot.semanticDigest).toBe(VACUUM_PARENT_ARTIFACT_SHA256);expect(authority.snapshot.richnessReleaseDigest).toBe(active.release.releaseDigest);expect(authority.snapshot.pack.selectionPolicy).toEqual({model:"HARD_COMPATIBILITY_THEN_EVIDENCE_BACKED_PARETO",scores:false,weights:false,implicitTieBreak:false})}});
});
