import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import type { AppliancesProductType } from "../contracts";
import type { XpyCatalogRelease } from "@/features/xpy/catalog/contract";
import { loadActiveDishwasherRichnessRelease } from "@/features/xpy/catalog/dishwasherRichness.server";
import { loadActiveVacuumRichnessRelease } from "@/features/xpy/catalog/vacuumRichness.server";
import { loadActiveRobotVacuumRichnessRelease } from "@/features/xpy/catalog/robotVacuumRichness.server";
import { decisionActivationPointerSchema, validateDecisionActivationPointer } from "../decisionAdoption/approval.server";
import { BLOCKED_TEKA_DISHWASHER_ID, isExpectedDecisionAdoptionBinding, MAJOR_APPLIANCE_DECISION_ADDITIONS, MAJOR_APPLIANCE_DECISION_RELEASES } from "../decisionAdoption/contract";

export const BOUNDED_TYPES = ["DISHWASHER", "VACUUM", "ROBOT_VACUUM", "FREEZER", "BUILT_IN_OVEN", "FREESTANDING_COOKER", "HOB", "RANGE_HOOD", "COUNTERTOP_MICROWAVE_OVEN", "BUILT_IN_MICROWAVE_OVEN", "AIR_PURIFIER", "FULLY_AUTOMATIC_ESPRESSO_MACHINE", "MANUAL_ESPRESSO_MACHINE", "FILTER_COFFEE_MACHINE", "TURKISH_COFFEE_MACHINE", "AIR_FRYER", "BLENDER", "FOOD_PROCESSOR", "ELECTRIC_STORAGE_WATER_HEATER", "INSTANTANEOUS_ELECTRIC_WATER_HEATER", "SPLIT_AIR_CONDITIONER"] as const;
export type BoundedProductType = typeof BOUNDED_TYPES[number];
const slug: Record<BoundedProductType,string> = { DISHWASHER:"dishwashers", VACUUM:"vacuums", ROBOT_VACUUM:"robot-vacuums", FREEZER:"freezers", BUILT_IN_OVEN:"built-in-ovens", FREESTANDING_COOKER:"freestanding-cookers", HOB:"hobs", RANGE_HOOD:"range-hoods", COUNTERTOP_MICROWAVE_OVEN:"countertop-microwave-ovens", BUILT_IN_MICROWAVE_OVEN:"built-in-microwave-ovens", AIR_PURIFIER:"air-purifiers", FULLY_AUTOMATIC_ESPRESSO_MACHINE:"fully-automatic-espresso-machines", MANUAL_ESPRESSO_MACHINE:"manual-espresso-machines", FILTER_COFFEE_MACHINE:"filter-coffee-machines", TURKISH_COFFEE_MACHINE:"turkish-coffee-machines", AIR_FRYER:"air-fryers", BLENDER:"blenders", FOOD_PROCESSOR:"food-processors", ELECTRIC_STORAGE_WATER_HEATER:"electric-storage-water-heaters", INSTANTANEOUS_ELECTRIC_WATER_HEATER:"instantaneous-electric-water-heaters", SPLIT_AIR_CONDITIONER:"split-air-conditioners" };
const release: Record<BoundedProductType,string> = { DISHWASHER:"APPLIANCES-DISHWASHER-TR-v0.1", VACUUM:"APPLIANCES-VACUUM-TR-v0.1", ROBOT_VACUUM:"APPLIANCES-ROBOT-VACUUM-TR-v0.1", FREEZER:"APPLIANCES-FREEZER-TR-v0.2", BUILT_IN_OVEN:"APPLIANCES-BUILT-IN-OVEN-TR-v0.2", FREESTANDING_COOKER:"APPLIANCES-FREESTANDING-COOKER-TR-v0.2", HOB:"APPLIANCES-HOB-TR-v0.2", RANGE_HOOD:"APPLIANCES-RANGE-HOOD-TR-v0.2", COUNTERTOP_MICROWAVE_OVEN:"APPLIANCES-COUNTERTOP-MICROWAVE-TR-v0.1", BUILT_IN_MICROWAVE_OVEN:"APPLIANCES-BUILT-IN-MICROWAVE-TR-v0.1", AIR_PURIFIER:"APPLIANCES-AIR-PURIFIER-TR-v0.1", FULLY_AUTOMATIC_ESPRESSO_MACHINE:"APPLIANCES-FULLY-AUTOMATIC-ESPRESSO-TR-v0.1", MANUAL_ESPRESSO_MACHINE:"APPLIANCES-MANUAL-ESPRESSO-TR-v0.1", FILTER_COFFEE_MACHINE:"APPLIANCES-FILTER-COFFEE-TR-v0.1", TURKISH_COFFEE_MACHINE:"APPLIANCES-TURKISH-COFFEE-TR-v0.1", AIR_FRYER:"APPLIANCES-AIR-FRYER-TR-v0.1", BLENDER:"APPLIANCES-BLENDER-TR-v0.1", FOOD_PROCESSOR:"APPLIANCES-FOOD-PROCESSOR-TR-v0.1", ELECTRIC_STORAGE_WATER_HEATER:"APPLIANCES-ELECTRIC-STORAGE-WATER-HEATER-TR-v0.1", INSTANTANEOUS_ELECTRIC_WATER_HEATER:"APPLIANCES-INSTANTANEOUS-ELECTRIC-WATER-HEATER-TR-v0.1", SPLIT_AIR_CONDITIONER:"APPLIANCES-SPLIT-AIR-CONDITIONER-TR-v0.1" };
const product=z.object({productId:z.string().min(1),brand:z.string().min(1),model:z.string().min(1),configurationIdentity:z.string().min(1),marketStatus:z.enum(["CURRENT_TR","TR_LISTED_AVAILABILITY_UNKNOWN"]),runtimeSelectable:z.boolean(),runtimeBlockers:z.array(z.string()),technicalFacts:z.record(z.string(),z.unknown()),capabilities:z.record(z.string(),z.unknown()),claims:z.array(z.object({statement:z.string(),authority:z.literal("MANUFACTURER_CLAIM"),outcomeGuarantee:z.literal(false)})),evidenceRefs:z.array(z.string()).min(1),marketLifecycle:z.object({asOf:z.string(),warrantyStatus:z.enum(["EXACT_TERMS_VERIFIED","MANUFACTURER_TR_TERMS_NOT_EXACT_PRODUCT_BOUND"])}).optional(),comparisonEligibility:z.object({status:z.literal("ELIGIBLE"),identityCritical:z.array(z.string()).min(1),budgetEligibility:z.enum(["BUDGET_ELIGIBLE","BUDGET_ELIGIBILITY_UNKNOWN"])}).optional(),evidenceLayers:z.object({L3:z.array(z.string()).min(1),L4:z.array(z.string()).min(1),L5:z.array(z.string()).min(1),L6:z.array(z.string()).min(1),L7:z.array(z.string()).min(1),L8:z.array(z.string()).min(1),L9:z.literal("INELIGIBLE_NO_FROZEN_MANUAL_BYTES")}).optional()});
const pack=z.object({schemaVersion:z.literal("appliances-bounded-domain-pack/v1"),releaseVersion:z.string(),departmentId:z.literal("APPLIANCES"),productType:z.enum(BOUNDED_TYPES),market:z.literal("TR"),scope:z.record(z.string(),z.string()),governanceStatus:z.literal("APPROVED"),lifecycle:z.literal("FROZEN"),runtimeActive:z.literal(true),concepts:z.array(z.string()),comparability:z.record(z.string(),z.unknown()),selectionPolicy:z.object({model:z.literal("HARD_COMPATIBILITY_THEN_EVIDENCE_BACKED_PARETO"),scores:z.literal(false),weights:z.literal(false),implicitTieBreak:z.literal(false)}),products:z.array(product).min(1),sources:z.array(z.object({sourceId:z.string(),url:z.string().url(),accessedAt:z.string(),authority:z.string()}))}).passthrough();
const pointerFields={releaseVersion:z.string(),artifactSha256:z.string().regex(/^[a-f0-9]{64}$/u),lifecycle:z.literal("ACTIVE")} as const;
const richnessPointer=z.object({releaseVersion:z.string(),releaseDigest:z.string(),catalogArtifactSha256:z.string(),membershipDigest:z.string(),activationManifest:z.string(),activationManifestSha256:z.string(),lifecycle:z.literal("ACTIVE_READ_ONLY")});
const pointer=z.union([z.object({schemaVersion:z.literal("appliances-bounded-active-pointer/v1"),...pointerFields}),z.object({schemaVersion:z.literal("appliances-bounded-active-pointer/v2"),...pointerFields,richness:richnessPointer}),z.object({schemaVersion:z.literal("appliances-bounded-active-pointer/v3"),...pointerFields,richness:richnessPointer,decisionActivation:decisionActivationPointerSchema})]);
export type BoundedPack=z.infer<typeof pack>;
export type BoundedAuthority={pack:Readonly<BoundedPack>;releaseVersion:string;catalogDigest:string;semanticDigest:string;conceptIds:ReadonlySet<string>;richnessRelease?:Readonly<XpyCatalogRelease>;richnessReleaseDigest?:string};
const sha=(raw:string)=>createHash("sha256").update(raw).digest("hex");
export const isBoundedType=(value:AppliancesProductType):value is BoundedProductType=>(BOUNDED_TYPES as readonly string[]).includes(value);
export async function loadActiveBoundedAuthority(root:string,type:BoundedProductType):Promise<{status:"READY";snapshot:BoundedAuthority}|{status:"FAILED_CLOSED";reason:string}>{try{const base=path.join(root,"data/production/appliances",slug[type]);const p=pointer.parse(JSON.parse(await readFile(path.join(base,"active.json"),"utf8")));const allowedRelease=type==="DISHWASHER"?[MAJOR_APPLIANCE_DECISION_RELEASES.DISHWASHER.parent,MAJOR_APPLIANCE_DECISION_RELEASES.DISHWASHER.successor]:[release[type]];if(!allowedRelease.includes(p.releaseVersion))throw new Error("RELEASE");const file=path.join(base,"releases",p.releaseVersion,"domain-pack.json"),raw=await readFile(file,"utf8");if(sha(raw)!==p.artifactSha256)throw new Error("DIGEST");const parsed=pack.parse(JSON.parse(raw));if(parsed.productType!==type||parsed.releaseVersion!==p.releaseVersion)throw new Error("TYPE");const sourceIds=new Set(parsed.sources.map(s=>s.sourceId));const productIds=new Set(parsed.products.map(x=>x.productId));if(productIds.size!==parsed.products.length||parsed.products.some(x=>x.evidenceRefs.some(r=>!sourceIds.has(r)))||parsed.products.some(x=>x.runtimeSelectable&&x.runtimeBlockers.length))throw new Error("BINDING");if(type==="DISHWASHER"&&p.releaseVersion===MAJOR_APPLIANCE_DECISION_RELEASES.DISHWASHER.successor){if(p.schemaVersion!=="appliances-bounded-active-pointer/v3"||!await validateDecisionActivationPointer(root,p.decisionActivation)||!isExpectedDecisionAdoptionBinding("DISHWASHER",(parsed as Record<string,unknown>).decisionAdoption)||productIds.size!==MAJOR_APPLIANCE_DECISION_RELEASES.DISHWASHER.expectedCount||productIds.has(BLOCKED_TEKA_DISHWASHER_ID))throw new Error("DECISION_ADOPTION");const parentRaw=await readFile(path.join(base,"releases",MAJOR_APPLIANCE_DECISION_RELEASES.DISHWASHER.parent,"domain-pack.json"),"utf8"),parentIds=(JSON.parse(parentRaw) as {products:{productId:string}[]}).products.map(item=>item.productId);if(sha(parentRaw)!==MAJOR_APPLIANCE_DECISION_RELEASES.DISHWASHER.parentArtifactSha256||[...parentIds,...MAJOR_APPLIANCE_DECISION_ADDITIONS.DISHWASHER].some(id=>!productIds.has(id)))throw new Error("MEMBERSHIP");}const legacy=type==="DISHWASHER"||type==="VACUUM"||type==="ROBOT_VACUUM";const richness=p.schemaVersion!=="appliances-bounded-active-pointer/v1"&&legacy?(type==="DISHWASHER"?await loadActiveDishwasherRichnessRelease(root):type==="VACUUM"?await loadActiveVacuumRichnessRelease(root):await loadActiveRobotVacuumRichnessRelease(root)):undefined;if(richness?.status==="FAILED_CLOSED")throw new Error(richness.reason);return{status:"READY",snapshot:Object.freeze({pack:Object.freeze(parsed),releaseVersion:parsed.releaseVersion,catalogDigest:p.artifactSha256,semanticDigest:p.artifactSha256,conceptIds:new Set(parsed.concepts),...(richness?.status==="READY"?{richnessRelease:richness.release,richnessReleaseDigest:richness.release.releaseDigest}:{})})};}catch{return{status:"FAILED_CLOSED",reason:`${type}_AUTHORITY_INVALID`};}}
