import {describe,expect,it} from "vitest";
import {createFileSystemAppliancesArtifactRepository} from "../authority/loader.server";
import {enterAppliancesDepartment} from "../entry.server";
import {MemoryAppliancesConversationStore} from "../persistence/memoryStore.testSupport";
import {commitAppliancesBootstrap} from "../persistence/service";
import {recoverAppliancesConversation} from "../recovery.server";
import {loadActiveBoundedAuthority,type BoundedProductType} from "./authority.server";
import {runBoundedConversationTurn} from "./conversation.server";
async function fixture(type:BoundedProductType){const store=new MemoryAppliancesConversationStore(),conversationId=crypto.randomUUID(),repository=createFileSystemAppliancesArtifactRepository(process.cwd()),entry=await enterAppliancesDepartment({repository,productType:type,conversationId});if(entry.status!=="READY")throw new Error(entry.status);await commitAppliancesBootstrap({store,state:entry.state,messageId:"create",payload:{productType:type}});const loaded=await loadActiveBoundedAuthority(process.cwd(),type);if(loaded.status!=="READY")throw new Error(loaded.reason);return{store,conversationId,authority:loaded.snapshot};}
describe.each(["DISHWASHER","VACUUM","ROBOT_VACUUM"] as const)("%s bounded adapter",type=>{it("loads the approved exact products and preserves evidence blockers",async()=>{const loaded=await loadActiveBoundedAuthority(process.cwd(),type);expect(loaded.status).toBe("READY");if(loaded.status!=="READY")return;expect(loaded.snapshot.pack.products).toHaveLength(type === "DISHWASHER" ? 7 : 4);expect(loaded.snapshot.pack.selectionPolicy).toEqual({model:"HARD_COMPATIBILITY_THEN_EVIDENCE_BACKED_PARETO",scores:false,weights:false,implicitTieBreak:false});if(type==="ROBOT_VACUUM")expect(loaded.snapshot.pack.products.find(p=>p.model.includes("X20"))).toMatchObject({runtimeSelectable:false,runtimeBlockers:["EXACT_HARDWARE_CONFIGURATION_CODE_UNRESOLVED","OFFICIAL_SPECIFICATION_ARTIFACT_INCOMPLETE"]});});it("responds informationally without inventing performance",async()=>{const f=await fixture(type),r=await runBoundedConversationTurn({...f,expectedRevision:1,messageId:"m1",message:type==="VACUUM"?"Kaç watt önemli mi?":type==="ROBOT_VACUUM"?"Pa ne demek?":"Enerji önemli mi?"});expect(r.status).toBe("OK");if(r.status==="OK")expect(r.outcome.kind).toBe("RESPOND");});});
describe("bounded decisions",()=>{it("keeps a dishwasher tie cardless, asks one material discriminator, then stays cardless when evidence ties",async()=>{const f=await fixture("DISHWASHER");const tied=await runBoundedConversationTurn({...f,expectedRevision:1,messageId:"m1",message:"Genişlik en fazla 61 cm, en az 14 kişilik"});expect(tied.status).toBe("OK");if(tied.status!=="OK")return;expect(tied.outcome).toMatchObject({kind:"ASK",questionKey:"appliances.dishwasher.material"});const unique=await runBoundedConversationTurn({store:f.store,authority:f.authority,conversationId:f.conversationId,expectedRevision:2,messageId:"m2",message:"Çatal bıçak çekmecesi zorunlu"});expect(unique.status).toBe("OK");if(unique.status!=="OK")return;expect(unique.outcome.kind).toBe("CLARIFY");});it("never uses vacuum watts and can select the exact pet-head model",async()=>{const f=await fixture("VACUUM"),r=await runBoundedConversationTurn({...f,expectedRevision:1,messageId:"m1",message:"Evcil hayvan tüyü için başlık zorunlu"});expect(r.status).toBe("OK");if(r.status!=="OK")return;expect(r.outcome).toMatchObject({kind:"DECISION_READY",card:{identity:{model:"BGC41PET"}}});expect(JSON.stringify(r.outcome)).not.toContain("en güçlü");expect((await recoverAppliancesConversation(f.store,f.conversationId))?.outcome).toMatchObject({kind:"DECISION_READY",card:{identity:{model:"BGC41PET"}}});});it("keeps robot Pa non-authoritative and selects required auto-empty",async()=>{const f=await fixture("ROBOT_VACUUM"),r=await runBoundedConversationTurn({...f,expectedRevision:1,messageId:"m1",message:"Yükseklik en fazla 10 cm, otomatik toz boşaltma zorunlu"});expect(r.status).toBe("OK");if(r.status!=="OK")return;expect(r.outcome).toMatchObject({kind:"DECISION_READY",card:{identity:{model:"Robot Vacuum H40 / OV51"}}});expect(JSON.stringify(r.outcome)).not.toContain("Pa nedeniyle");});});

describe("bounded natural conversation parity",()=>{
  it("accepts Turkish air-purifier room area and asks exactly the next material question",async()=>{const f=await fixture("AIR_PURIFIER");const result=await runBoundedConversationTurn({...f,expectedRevision:1,messageId:"air-area",message:"küçük bir oda yaklaşık 10 m2"});expect(result.status).toBe("OK");if(result.status!=="OK")return;expect(result.outcome).toMatchObject({kind:"ASK",questionKey:"appliances.air-purifier.material"});expect(result.state.ledger).toEqual(expect.arrayContaining([expect.objectContaining({conceptId:"PM_CADR",normalizedValue:expect.objectContaining({roomAreaM2:10,selectionUse:"CONTEXT_ONLY",genericCoveragePromise:false})})]));expect(result.state.ledger.some(event=>event.conceptId==="FILTER_MAINTENANCE")).toBe(false);});
  it("turns a broad dishwasher capacity need into one contextual numeric question",async()=>{const f=await fixture("DISHWASHER");const first=await runBoundedConversationTurn({...f,expectedRevision:1,messageId:"n1",message:"Kalabalık sofralar oluyor"});expect(first.status).toBe("OK");if(first.status!=="OK")return;expect(first.outcome).toMatchObject({kind:"ASK",questionKey:"appliances.dishwasher.capacity"});const second=await runBoundedConversationTurn({...f,expectedRevision:2,messageId:"n2",message:"14"});expect(second.status).toBe("OK");if(second.status!=="OK")return;expect(second.state.ledger.filter(e=>e.conceptId==="CAPACITY"&&e.status==="SUPERSEDED")).toHaveLength(1);expect(second.state.ledger.some(e=>e.conceptId==="CAPACITY"&&e.status==="ACCEPTED_EXPLICIT"&&(e.normalizedValue as {minimum?:number}).minimum===14)).toBe(true);});
  it("asks for a vacuum radius threshold and never repeats that question",async()=>{const f=await fixture("VACUUM");const first=await runBoundedConversationTurn({...f,expectedRevision:1,messageId:"n1",message:"Priz değiştirmek istemiyorum"});expect(first.status).toBe("OK");if(first.status!=="OK")return;expect(first.outcome).toMatchObject({kind:"ASK",questionKey:"appliances.vacuum.radius"});const second=await runBoundedConversationTurn({...f,expectedRevision:2,messageId:"n2",message:"11 metre"});expect(second.status).toBe("OK");if(second.status!=="OK")return;expect(second.state.askedQuestionKeys.filter(k=>k==="appliances.vacuum.radius")).toHaveLength(1);expect(second.outcome).not.toMatchObject({questionKey:"appliances.vacuum.radius"});});
  it("asks for robot clearance and supports an explicit correction",async()=>{const f=await fixture("ROBOT_VACUUM");const first=await runBoundedConversationTurn({...f,expectedRevision:1,messageId:"n1",message:"Koltuk altına girsin"});expect(first.status).toBe("OK");if(first.status!=="OK")return;expect(first.outcome).toMatchObject({kind:"ASK",questionKey:"appliances.robot.height"});const measured=await runBoundedConversationTurn({...f,expectedRevision:2,messageId:"n2",message:"10 cm"});expect(measured.status).toBe("OK");if(measured.status!=="OK")return;const corrected=await runBoundedConversationTurn({...f,expectedRevision:3,messageId:"n3",message:"Aslında yükseklik en fazla 9,8 cm"});expect(corrected.status).toBe("OK");if(corrected.status!=="OK")return;expect(corrected.state.ledger.some(e=>e.conceptId==="ROBOT_HEIGHT"&&e.status==="SUPERSEDED")).toBe(true);expect(corrected.state.ledger.some(e=>e.conceptId==="ROBOT_HEIGHT"&&e.status==="ACCEPTED_EXPLICIT"&&(e.normalizedValue as {maximumMm?:number}).maximumMm===98)).toBe(true);});
  it.each([
    ["DISHWASHER", "Kalabalık sofralar oluyor", "appliances.dishwasher.capacity", "CAPACITY"],
    ["VACUUM", "Priz değiştirmek istemiyorum", "appliances.vacuum.radius", "RADIUS"],
    ["ROBOT_VACUUM", "Koltuk altına girsin", "appliances.robot.height", "ROBOT_HEIGHT"],
  ] as const)("binds a negative short answer for %s and does not repeat the answered question",async(type,message,key,concept)=>{const f=await fixture(type);const asked=await runBoundedConversationTurn({...f,expectedRevision:1,messageId:"q1",message});expect(asked.status==="OK"&&asked.outcome).toMatchObject({kind:"ASK",questionKey:key});const answered=await runBoundedConversationTurn({...f,expectedRevision:2,messageId:"q2",message:"gerek yok"});expect(answered.status).toBe("OK");if(answered.status!=="OK")return;expect(answered.outcome).not.toMatchObject({questionKey:key});expect(answered.state.ledger).toEqual(expect.arrayContaining([expect.objectContaining({conceptId:concept,decisionUse:"NONE",status:"ACCEPTED_EXPLICIT"})]));});
});
