"use client";

/* eslint-disable @next/next/no-img-element -- API-transient affiliate images must bypass the persistent Next image cache. */

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import type { AppliancesDecisionCard } from "@/features/appliances/recommendation/publicCard";
import type { AppliancesProductType } from "@/features/appliances/contracts";
import { buildAppliancesStageTwoProjection } from "@/features/appliances/stageTwo/projection";
import { answerAppliancesAdvisor } from "@/features/appliances/stageTwo/advisor";
import type { AdvisorManualKnowledge, AppliancesSalesActionKind, AppliancesStageTwoProjection, ComparisonReportEntitlement } from "@/features/appliances/stageTwo/contracts";

type ExperienceResponse = { readonly kind: "STAGE_TWO_READY"; readonly productType: AppliancesProductType; readonly revision: number; readonly selectedCard: AppliancesDecisionCard; readonly comparisonEntitlement: ComparisonReportEntitlement; readonly manualKnowledge: AdvisorManualKnowledge; readonly authorizedComparisonCards?: readonly AppliancesDecisionCard[] };

function EmptyState({ title, children }: { readonly title: string; readonly children: React.ReactNode }) { return <div className="mx-auto max-w-3xl px-5 py-16 sm:px-8"><div className="rounded-3xl border border-amber-200 bg-amber-50 p-7 text-amber-950"><h1 className="text-2xl font-semibold">{title}</h1><p className="mt-3 leading-7">{children}</p><Link href="/appliances#asama-1" className="mt-6 inline-flex rounded-full bg-stone-950 px-5 py-3 font-semibold text-white">AŞAMA 1’e dön</Link></div></div>; }

export function AppliancesStageTwoExperience({ handoff }: { readonly handoff: string }) {
  const [projection, setProjection] = useState<AppliancesStageTwoProjection>(); const [revision, setRevision] = useState(0); const [error, setError] = useState(""); const [draft, setDraft] = useState(""); const [messages, setMessages] = useState<readonly string[]>([]); const [reportNotice, setReportNotice] = useState(""); const [actionNotice, setActionNotice] = useState(""); const [pendingAction, setPendingAction] = useState<AppliancesSalesActionKind>(); const actionKeys = useRef<Partial<Record<AppliancesSalesActionKind, string>>>({});
  useEffect(() => { let cancelled = false; if (!handoff) return; void fetch("/api/appliances/stage-two-handoff", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "READ", handoff }) }).then(async response => { const body = await response.json() as ExperienceResponse & { message?: string }; if (!response.ok || body.kind !== "STAGE_TWO_READY" || !body.selectedCard) throw new Error(body.message ?? "Onaylanmış ürün kararı bulunamadı."); if (!cancelled) { setRevision(body.revision); setProjection(buildAppliancesStageTwoProjection({ productType: body.productType, selectedCard: body.selectedCard, entitlement: body.comparisonEntitlement, manualKnowledge: body.manualKnowledge, authorizedComparisonCards: body.authorizedComparisonCards })); } }).catch(reason => { if (!cancelled) setError(reason instanceof Error ? reason.message : "Karar okunamadı."); }); return () => { cancelled = true; }; }, [handoff]);
  const chart = useMemo(() => projection ? projection.content.chartDimensions.map((label, index) => ({ label, count: projection.selected.facts.filter((_, factIndex) => factIndex % 3 === index).length })) : [], [projection]);
  if (!handoff) return <EmptyState title="Önce ürününü seçmelisin">AŞAMA 2 yalnız güncel karar kartındaki “Ayrıntılı değerlendirmeyi aç” bağlantısıyla açılır.</EmptyState>;
  if (error) return <EmptyState title="Güvenli karar bağlantısı açılamadı">{error}</EmptyState>;
  if (!projection) return <div className="min-h-[70dvh] bg-stone-950 p-8 text-stone-300" aria-busy="true">Ürün kararı doğrulanıyor…</div>;
  const p = projection.selected; const max = Math.max(1, ...chart.map(item => item.count));
  async function runAction(action: AppliancesSalesActionKind) { if (!projection || pendingAction) return; setPendingAction(action); setActionNotice(""); actionKeys.current[action] ??= crypto.randomUUID(); try { const response = await fetch("/api/appliances/stage-two-action", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ handoff, action, exactProductId: projection.selected.id, productType: projection.productType, revision, idempotencyKey: actionKeys.current[action] }) }); const result = await response.json() as { status?: string; kind?: string; url?: string; sharePath?: string; flow?: string; message?: string }; if (!response.ok || result.status !== "READY") throw new Error(result.message ?? "Eylem kullanılamıyor."); if (result.kind === "VIEW_EXACT_OFFER" && result.url) window.open(result.url, "_blank", "noopener,noreferrer"); else if (result.kind === "SHARE_DECISION" && result.sharePath) { const url = new URL(result.sharePath, window.location.origin).toString(); const usedNativeShare = typeof navigator.share === "function"; if (usedNativeShare) await navigator.share({ title: `${projection.selected.brand} ${projection.selected.model}`, url }); else await navigator.clipboard.writeText(url); setActionNotice(usedNativeShare ? "Güvenli karar bağlantısı paylaşım ekranına hazırlandı." : "Güvenli karar bağlantısı panoya kopyalandı."); } else if (result.flow === "COMPARISON_REPORT_OFFER") { document.getElementById("comparison")?.scrollIntoView({ behavior: "smooth" }); setReportNotice("Karşılaştırma yalnız ayrı bir erişim kaydıyla açılır. Bu sayfa ödeme almaz, erişim tanımlamaz ve sipariş oluşturmaz."); } } catch (reason) { setActionNotice(reason instanceof Error ? reason.message : "Eylem doğrulanamadı; hiçbir işlem yapılmadı."); } finally { setPendingAction(undefined); } }
  return <div className="bg-[#f4f1eb] text-stone-950">
    <header className="sticky top-0 z-40 border-b border-white/10 bg-stone-950/95 text-white backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8"><span className="font-bold">EXPIYA <span className="font-light text-emerald-400">APPLIANCES</span></span><nav className="hidden gap-6 text-xs text-stone-300 md:flex" aria-label="Ürün değerlendirmesi"><a href="#evidence">Kanıt</a><a href="#daily">Günlük hayat</a><a href="#comparison">Karşılaştırma</a><a href="#advisor">Danışman</a></nav><Link href="/appliances#asama-1" className="rounded-full border border-white/20 px-4 py-2 text-xs">AŞAMA 1’e dön</Link></div></header>
    <section className="relative isolate overflow-hidden bg-stone-950 text-white"><div className="absolute inset-0">{p.media.src ? p.media.linkTarget ? <a href={p.media.linkTarget} target="_blank" rel="nofollow sponsored noreferrer" aria-label={`${p.media.alt}; ürün sayfasını aç`}><img src={p.media.src} alt="" className="h-full w-full object-contain opacity-50" referrerPolicy="strict-origin-when-cross-origin"/></a> : <Image src={p.media.src} alt="" fill priority sizes="100vw" className="object-contain opacity-50"/> : <div className="h-full bg-[radial-gradient(circle_at_70%_25%,#285943,transparent_38%),linear-gradient(130deg,#1c1917,#0c0a09)]"/>}<div className="absolute inset-0 bg-gradient-to-r from-black via-black/70 to-transparent"/></div><div className="relative mx-auto grid min-h-[68vh] max-w-7xl items-end gap-10 px-5 py-12 sm:px-8 lg:grid-cols-[1fr_24rem]"><div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full border border-white/25 bg-black/30 px-3 py-1.5">Ürün değerlendirmesi</span><span className="rounded-full border border-white/25 bg-black/30 px-3 py-1.5">AŞAMA 1’de seçildi</span>{p.media.disclosure ? <span className="rounded-full border border-amber-300/40 bg-black/50 px-3 py-1.5 text-amber-200">{p.media.disclosure}</span> : null}</div><p className="mt-7 text-xs font-semibold uppercase tracking-[.28em] text-emerald-300">{projection.content.eyebrow}</p><h1 className="mt-3 text-4xl font-semibold sm:text-6xl">{p.brand} {p.model}</h1><p className="mt-3 text-lg text-stone-300">{projection.categoryLabel} · Türkiye pazarı</p><p className="mt-6 max-w-2xl leading-7 text-stone-200">Bu sayfa seçtiğin ürünü doğrulanmış teknik bilgiler ve günlük kullanım açıklamalarıyla değerlendirir. Ürün seçimini değiştirmez; güncel satış bilgisi yoksa bunu açıkça belirtir.</p><div className="mt-7 flex flex-wrap gap-3"><a href="#advisor" className="rounded-full bg-emerald-400 px-5 py-3 font-semibold text-stone-950">Danışmana sor</a><a href="#comparison" className="rounded-full border border-white/30 px-5 py-3 font-semibold">Karşılaştırma raporu</a></div></div><div className="rounded-3xl border border-white/15 bg-black/40 p-6 backdrop-blur"><p className="text-xs uppercase tracking-wider text-stone-400">Fiyat durumu</p><p className="mt-2 text-3xl font-semibold">{p.price.display}</p><p className="mt-3 text-sm leading-6 text-stone-400">{p.price.note}</p></div></div></section>
    <main className="mx-auto max-w-7xl space-y-16 px-5 py-12 sm:px-8">
      <section aria-labelledby="actions-title"><p className="text-xs font-semibold uppercase tracking-[.24em] text-emerald-700">Sıradaki adımlar</p><h2 id="actions-title" className="mt-2 text-3xl font-semibold">Bu ürünle neler yapabilirsin?</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{projection.salesActions.map(action => <article key={action.kind} className="flex min-h-52 flex-col rounded-3xl border border-stone-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><h3 className="font-semibold">{action.label}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${action.availability === "AVAILABLE" ? "bg-emerald-100 text-emerald-900" : "bg-stone-100 text-stone-600"}`}>{action.availability === "AVAILABLE" ? "Kullanılabilir" : "Kullanılamıyor"}</span></div><p className="mt-3 flex-1 text-sm leading-6 text-stone-600">{action.explanation}</p>{action.observedAt ? <p className="mt-2 text-xs text-stone-500">Gözlem: {new Date(action.observedAt).toLocaleString("tr-TR")}</p> : null}<button type="button" disabled={action.availability !== "AVAILABLE" || Boolean(pendingAction)} onClick={() => void runAction(action.kind)} className="mt-4 min-h-11 rounded-full bg-stone-950 px-4 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-stone-200 disabled:text-stone-500">{pendingAction === action.kind ? "Doğrulanıyor…" : action.label}</button></article>)}</div>{actionNotice ? <p role="status" className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-950">{actionNotice}</p> : null}<p className="mt-4 text-xs leading-5 text-stone-500">Ticari iş ortaklıkları ürün sıralamasını ve kararı değiştirmez. Expiya burada ücret çekmez, sipariş vermez veya kişisel bilgileri satıcıya göndermez.</p></section>
      <section id="evidence"><p className="text-xs font-semibold uppercase tracking-[.24em] text-emerald-700">Ürün kanıtı</p><h2 className="mt-2 text-3xl font-semibold">Onaylı ürünün teknik görünümü</h2>{p.facts.length ? <dl className="mt-7 grid overflow-hidden rounded-3xl border border-stone-200 bg-white sm:grid-cols-2">{p.facts.map(fact => <div key={`${fact.label}:${fact.value}`} className="border-b border-stone-100 p-5"><dt className="text-sm text-stone-500">{fact.label}</dt><dd className="mt-2 text-xl font-semibold">{fact.value}</dd><p className="mt-3 text-xs leading-5 text-stone-500">Kaynak: {fact.sourceHref ? <a className="underline" href={fact.sourceHref} target="_blank" rel="noreferrer">{fact.sourceLabel}</a> : fact.sourceLabel} · {fact.observedAt ? `Gözlem: ${fact.observedAt}` : "Güncellik bilgisi bulunmuyor"}</p></div>)}</dl> : <p className="mt-6 rounded-3xl border border-amber-200 bg-amber-50 p-6">Yayınlanabilir teknik gerçek bulunmuyor; alanlar tahminle doldurulmadı.</p>}</section>
      <section aria-labelledby="chart-title"><h2 id="chart-title" className="text-3xl font-semibold">{projection.content.chartTitle}</h2><p className="mt-2 text-sm text-stone-500">Çubuklar yalnız yayımlanabilir kanıt alanı sayısını gösterir; puan veya ürün sıralaması değildir.</p><div className="mt-6 grid gap-4 rounded-3xl bg-stone-900 p-6 text-white sm:grid-cols-3">{chart.map(item => <div key={item.label}><div className="flex justify-between text-sm"><span>{item.label}</span><span>{item.count} alan</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-stone-700"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${(item.count / max) * 100}%` }}/></div></div>)}</div></section>
      <section id="daily"><p className="text-xs font-semibold uppercase tracking-[.24em] text-emerald-700">Gerçek hayatta</p><h2 className="mt-2 text-3xl font-semibold">{projection.content.dailyLifeTitle}</h2><div className="mt-7 grid gap-4 sm:grid-cols-2">{p.facts.filter(fact => fact.dailyMeaning).map(fact => <article key={fact.label} className="rounded-3xl bg-stone-900 p-6 text-white"><p className="text-sm text-emerald-300">{fact.label}</p><p className="mt-3 text-2xl font-semibold">{fact.value}</p><p className="mt-4 text-sm leading-6 text-stone-300">{fact.dailyMeaning}</p></article>)}</div></section>
      <section id="comparison" className="rounded-3xl border border-stone-200 bg-white p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.24em] text-emerald-700">Ayrı erişim</p><h2 className="mt-2 text-3xl font-semibold">Ürün karşılaştırması</h2>{projection.comparison.access === "LOCKED" ? <p className="mt-4 max-w-2xl leading-7 text-stone-600">Karşılaştırma kanıtı bu oturumda erişime açık değil. Tek karar görünümünde başka ürün adı, değer veya örtük sıralama gösterilmez.</p> : <div className="mt-6 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr><th className="p-3">Alan</th>{projection.comparison.products.map(item => <th className="p-3" key={item.id}>{item.brand} {item.model}</th>)}</tr></thead><tbody>{projection.comparison.rows.map(row => <tr className="border-t" key={row.label}><th className="p-3 font-medium">{row.label}</th>{row.values.map(cell => <td className="p-3" key={cell.productId}>{cell.value}<span className="block text-[10px] text-stone-500">{cell.sourceLabel ?? "Kaynak bilinmiyor"}</span></td>)}</tr>)}</tbody></table></div>}<button type="button" onClick={() => setReportNotice(projection.comparisonOffer.action === "OPEN_REPORT" ? "Bu oturum için tanımlanmış karşılaştırma raporu yukarıdaki tabloda açık." : "Bu oturumda karşılaştırma erişimi yok. Buradan ödeme alınmaz veya erişim tanımlanmaz.")} className="mt-6 rounded-full bg-stone-950 px-5 py-3 font-semibold text-white">{projection.comparisonOffer.label}</button><p className="mt-3 text-xs text-stone-500">Bu eylem satış, ödeme, sipariş veya satıcı iletişimi başlatmaz.</p>{reportNotice && <p role="status" className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{reportNotice}</p>}</section>
      <section id="advisor" className="overflow-hidden rounded-3xl border border-stone-200 bg-white"><div className="bg-stone-950 p-6 text-white"><h2 className="text-xl font-semibold">Expiya Satış Danışmanı</h2><p className="mt-1 text-xs text-stone-400">Yalnız onayladığın ürün ve erişimin varsa kayıtlı karşılaştırma seti</p></div><div className="min-h-40 space-y-3 bg-[#f7f5f0] p-5" aria-live="polite"><p className="max-w-2xl rounded-2xl bg-white p-4 text-sm leading-6 shadow-sm">Bu ürünün kanıtlarını ve günlük hayattaki anlamını açıklayabilirim. {projection.manualKnowledge.status === "AVAILABLE" ? "Bu ürüne bağlı doğrulanmış kılavuz açıklamasını da aktarabilirim." : "Bu ürün için doğrulanmış kılavuz açıklaması bulunmuyorsa bunu açıkça söylerim."} Kararı değiştiremem, yeni ürün ekleyemem veya bilinmeyen bilgiyi tamamlayamam.</p>{messages.map((message, index) => <p key={`${index}:${message}`} className="max-w-2xl rounded-2xl bg-white p-4 text-sm leading-6 shadow-sm">{message}</p>)}</div><form className="flex gap-2 border-t p-3" onSubmit={event => { event.preventDefault(); const question = draft.trim(); if (!question) return; setMessages(current => [...current, answerAppliancesAdvisor(projection, question).message]); setDraft(""); }}><label className="sr-only" htmlFor="appliances-advisor-question">Danışmana sor</label><input id="appliances-advisor-question" value={draft} onChange={event => setDraft(event.target.value)} className="min-w-0 flex-1 rounded-full bg-stone-100 px-4 py-3" placeholder="Bu ürünle ilgili bir şey sor…"/><button className="rounded-full bg-emerald-600 px-5 font-semibold text-white">Sor</button></form></section>
      <aside className="rounded-3xl border border-amber-200 bg-amber-50 p-6 text-sm leading-6 text-amber-950"><strong>Kapsam sınırı:</strong> Satıcı, teklif, sipariş, servis randevusu ve diğer satış eylemleri bu aşamada desteklenmez. AŞAMA 3 henüz açık değildir.</aside>
    </main>
  </div>;
}
